Repository microsoft/TypeScript, pull requests merged in 2020-02, with the labels that each got.

#36580 fix(33600): `Convert function into ES2015 class` quickfix returns empty result
  src/services/suggestionDiagnostics.ts
  tests/cases/fourslash/convertFunctionToEs6Class_noQuickInfoForIIFE.ts
Labels: For Milestone Bug

#36552 De-duplicate indentations in JSX Texts
  src/compiler/scanner.ts
  src/services/formatting/formatting.ts
  src/services/formatting/formattingScanner.ts
  tests/cases/fourslash/formatTsxClosingAfterJsxText.ts
Labels: Author: Team

#36569 Enable @typescript-eslint/space-before-function-paren, @typescript-eslint/no-unused-expressions
  .eslintrc.json
  package.json
  src/compiler/checker.ts
  src/compiler/watch.ts
  src/harness/harnessUtils.ts
  src/services/codefixes/fixClassIncorrectlyImplementsInterface.ts
  src/services/codefixes/fixSpelling.ts
  src/services/codefixes/fixStrictClassInitialization.ts
  src/services/refactors/generateGetAccessorAndSetAccessor.ts
  src/testRunner/externalCompileRunner.ts
  src/testRunner/rwcRunner.ts
  src/testRunner/unittests/services/languageService.ts
  src/testRunner/unittests/tsserver/session.ts
Labels: Housekeeping

#33797 Drop support for defunct Chakra host
  src/compiler/sys.ts
Labels: Housekeeping

#33500 Add rxjs to the docker suite
  tests/baselines/reference/docker/rxjs.log
  tests/cases/docker/rxjs/Dockerfile
Labels: Author: Team, Housekeeping

#33229 Expose hasOnlyExpressionInitializer as a public type guard
  src/compiler/utilitiesPublic.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Housekeeping

#36619 Fix crash when trying to import a non-exported type
  src/compiler/checker.ts
  tests/baselines/reference/importNonExportedMember2.errors.txt
  tests/baselines/reference/importNonExportedMember2.js
  tests/baselines/reference/importNonExportedMember2.symbols
  tests/baselines/reference/importNonExportedMember2.types
  tests/baselines/reference/importNonExportedMember3.errors.txt
  tests/baselines/reference/importNonExportedMember3.js
  tests/baselines/reference/importNonExportedMember3.symbols
  tests/baselines/reference/importNonExportedMember3.types
  tests/cases/compiler/importNonExportedMember2.ts
  tests/cases/compiler/importNonExportedMember3.ts
Labels: Author: Team

#23801 add support for Lift Template Literal Restriction
  src/compiler/binder.ts
  src/compiler/factoryPublic.ts
  src/compiler/parser.ts
  src/compiler/scanner.ts
  src/compiler/transformers/es2015.ts
  src/compiler/transformers/es2018.ts
  src/compiler/transformers/taggedTemplate.ts
  src/compiler/tsconfig.json
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/services/classifier.ts
  src/services/formatting/formattingScanner.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/invalidTaggedTemplateEscapeSequences(target=es2015).errors.txt
  tests/baselines/reference/invalidTaggedTemplateEscapeSequences(target=es2015).js
  tests/baselines/reference/invalidTaggedTemplateEscapeSequences(target=es2015).symbols
  tests/baselines/reference/invalidTaggedTemplateEscapeSequences(target=es2015).types
  tests/baselines/reference/invalidTaggedTemplateEscapeSequences(target=es5).errors.txt
  tests/baselines/reference/invalidTaggedTemplateEscapeSequences(target=es5).js
  tests/baselines/reference/invalidTaggedTemplateEscapeSequences(target=es5).symbols
  tests/baselines/reference/invalidTaggedTemplateEscapeSequences(target=es5).types
  tests/baselines/reference/invalidTaggedTemplateEscapeSequences(target=esnext).errors.txt
  tests/baselines/reference/invalidTaggedTemplateEscapeSequences(target=esnext).js
  tests/baselines/reference/invalidTaggedTemplateEscapeSequences(target=esnext).symbols
  tests/baselines/reference/invalidTaggedTemplateEscapeSequences(target=esnext).types
  tests/baselines/reference/invalidTaggedTemplateEscapeSequences.errors.txt
  tests/baselines/reference/invalidTaggedTemplateEscapeSequences.js
  tests/baselines/reference/invalidTaggedTemplateEscapeSequences.symbols
  tests/baselines/reference/invalidTaggedTemplateEscapeSequences.types
  tests/cases/conformance/es2018/invalidTaggedTemplateEscapeSequences.ts
Labels: For Milestone Bug

#36634 Cherry-pick: Fix crash when trying to import a non-exported type (#36619)
  src/compiler/checker.ts
  tests/baselines/reference/importNonExportedMember2.errors.txt
  tests/baselines/reference/importNonExportedMember2.js
  tests/baselines/reference/importNonExportedMember2.symbols
  tests/baselines/reference/importNonExportedMember2.types
  tests/baselines/reference/importNonExportedMember3.errors.txt
  tests/baselines/reference/importNonExportedMember3.js
  tests/baselines/reference/importNonExportedMember3.symbols
  tests/baselines/reference/importNonExportedMember3.types
  tests/cases/compiler/importNonExportedMember2.ts
  tests/cases/compiler/importNonExportedMember3.ts
Labels: Author: Team

#33865 Add vue-next to docker suite
  tests/baselines/reference/docker/vue-next.log
  tests/cases/docker/vue-next/Dockerfile
Labels: Author: Team, Housekeeping

#36658 Support property declarations in jsdoc template generation
  src/services/jsDoc.ts
  tests/cases/fourslash/docCommentTemplateClassDeclProperty01.ts
Labels: Author: Team

#36661 Fix jsdoc comment parsing initial state
  src/compiler/parser.ts
  tests/baselines/reference/quickInfoDisplayPartsParameters.baseline
  tests/cases/fourslash/quickInfoDisplayPartsParameters.ts
Labels: Author: Team

#35230 Either clone or pull, don't do both
  src/testRunner/externalCompileRunner.ts
Labels: Housekeeping

#36722 Handle walkThroughSnippet:/ and untitled:/ as dynamic files
  src/server/scriptInfo.ts
  src/testRunner/tsconfig.json
  src/testRunner/unittests/tsserver/dynamicFiles.ts
  src/testRunner/unittests/tsserver/projects.ts
  src/testRunner/unittests/tsserver/untitledFiles.ts
Labels: Author: Team

#36663 Allow intersections (and substitutions) to be checked against discriminable unions
  src/compiler/checker.ts
  tests/baselines/reference/discriminableUnionWithIntersectedMembers.js
  tests/baselines/reference/discriminableUnionWithIntersectedMembers.symbols
  tests/baselines/reference/discriminableUnionWithIntersectedMembers.types
  tests/cases/compiler/discriminableUnionWithIntersectedMembers.ts
Labels: Author: Team

#36615 Use type-only imports in auto-imports when it would be an error not to, and use auto-imports in “implement interface” fix
  src/services/codefixes/fixClassDoesntImplementInheritedAbstractMember.ts
  src/services/codefixes/fixClassIncorrectlyImplementsInterface.ts
  src/services/codefixes/helpers.ts
  src/services/codefixes/importFixes.ts
  src/services/codefixes/inferFromUsage.ts
  src/services/completions.ts
  src/services/utilities.ts
  tests/cases/fourslash/codeFixClassImplementInterfaceAutoImports.ts
  tests/cases/fourslash/codeFixClassImplementInterfaceAutoImports_typeOnly.ts
  tests/cases/fourslash/codeFixClassImplementInterface_typeInOtherFile.ts
  tests/cases/fourslash/codeFixInferFromUsageContextualImport4.ts
  tests/cases/fourslash/importNameCodeFix_typeOnly.ts
  tests/cases/fourslash/importNameCodeFix_typeOnly2.ts
  tests/cases/fourslash/quickfixImplementInterfaceUnreachableTypeUsesRelativeImport.ts
Labels: Author: Team

#35359 Don't npm install the parent project with no args
  src/testRunner/externalCompileRunner.ts
  tests/baselines/reference/user/TypeScript-Vue-Starter.log
  tests/cases/user/TypeScript-React-Starter/test.json
  tests/cases/user/TypeScript-Vue-Starter/test.json
  tests/cases/user/TypeScript-WeChat-Starter/test.json
Labels: Housekeeping

#35362 Add --git-dir and --work-tree to user tests
  src/testRunner/externalCompileRunner.ts
Labels: Housekeeping

#35753 Fix npm test if os.cpus().length == 1
  Gulpfile.js
Labels: Housekeeping

#35471 Adds puppeteer to test whether typescript.js runs in the browser
  .github/workflows/ci.yml
  Gulpfile.js
  package.json
  scripts/browserIntegrationTest.js
Labels: Author: Team, Housekeeping

#36790 Fix renaming an ExportSpecifier name when propertyName is present
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/services/findAllReferences.ts
  tests/baselines/reference/renameExportSpecifier.baseline
  tests/baselines/reference/renameExportSpecifier2.baseline
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/renameExportSpecifier.ts
  tests/cases/fourslash/renameExportSpecifier2.ts
Labels: Author: Team

#36794 Set correct pos for NamespaceExport
  src/compiler/parser.ts
  tests/baselines/reference/exportAsNamespace1(module=amd).symbols
  tests/baselines/reference/exportAsNamespace1(module=commonjs).symbols
  tests/baselines/reference/exportAsNamespace1(module=es2015).symbols
  tests/baselines/reference/exportAsNamespace1(module=esnext).symbols
  tests/baselines/reference/exportAsNamespace1(module=system).symbols
  tests/baselines/reference/exportAsNamespace1(module=umd).symbols
  tests/baselines/reference/exportAsNamespace2(module=amd).symbols
  tests/baselines/reference/exportAsNamespace2(module=commonjs).symbols
  tests/baselines/reference/exportAsNamespace2(module=es2015).symbols
  tests/baselines/reference/exportAsNamespace2(module=esnext).symbols
  tests/baselines/reference/exportAsNamespace2(module=system).symbols
  tests/baselines/reference/exportAsNamespace2(module=umd).symbols
  tests/baselines/reference/exportAsNamespace3(module=amd).symbols
  tests/baselines/reference/exportAsNamespace3(module=commonjs).symbols
  tests/baselines/reference/exportAsNamespace3(module=es2015).symbols
  tests/baselines/reference/exportAsNamespace3(module=esnext).symbols
  tests/baselines/reference/exportAsNamespace3(module=system).symbols
  tests/baselines/reference/exportAsNamespace3(module=umd).symbols
  tests/baselines/reference/exportNamespace2.symbols
  tests/baselines/reference/exportNamespace3.symbols
  tests/cases/fourslash/referencesForStatementKeywords.ts
Labels: Author: Team

#36804 Cherry-pick release bugs
  src/compiler/parser.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/services/findAllReferences.ts
  tests/baselines/reference/exportAsNamespace1(module=amd).symbols
  tests/baselines/reference/exportAsNamespace1(module=commonjs).symbols
  tests/baselines/reference/exportAsNamespace1(module=es2015).symbols
  tests/baselines/reference/exportAsNamespace1(module=esnext).symbols
  tests/baselines/reference/exportAsNamespace1(module=system).symbols
  tests/baselines/reference/exportAsNamespace1(module=umd).symbols
  tests/baselines/reference/exportAsNamespace2(module=amd).symbols
  tests/baselines/reference/exportAsNamespace2(module=commonjs).symbols
  tests/baselines/reference/exportAsNamespace2(module=es2015).symbols
  tests/baselines/reference/exportAsNamespace2(module=esnext).symbols
  tests/baselines/reference/exportAsNamespace2(module=system).symbols
  tests/baselines/reference/exportAsNamespace2(module=umd).symbols
  tests/baselines/reference/exportAsNamespace3(module=amd).symbols
  tests/baselines/reference/exportAsNamespace3(module=commonjs).symbols
  tests/baselines/reference/exportAsNamespace3(module=es2015).symbols
  tests/baselines/reference/exportAsNamespace3(module=esnext).symbols
  tests/baselines/reference/exportAsNamespace3(module=system).symbols
  tests/baselines/reference/exportAsNamespace3(module=umd).symbols
  tests/baselines/reference/exportNamespace2.symbols
  tests/baselines/reference/exportNamespace3.symbols
  tests/baselines/reference/renameExportSpecifier.baseline
  tests/baselines/reference/renameExportSpecifier2.baseline
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/referencesForStatementKeywords.ts
  tests/cases/fourslash/renameExportSpecifier.ts
  tests/cases/fourslash/renameExportSpecifier2.ts
Labels: Author: Team

#36016 Marked internal createAnonymousType type as allowing undefined Symbols
  src/compiler/types.ts
  src/services/codefixes/inferFromUsage.ts
Labels: Housekeeping

#36674 fix(30003): Formatter deletes comment
  src/services/formatting/formatting.ts
  src/services/formatting/rules.ts
  tests/cases/fourslash/formatNoSpaceBeforeCloseBrace.ts
  tests/cases/fourslash/formatNoSpaceBeforeCloseBrace1.ts
  tests/cases/fourslash/formatNoSpaceBeforeCloseBrace2.ts
Labels: For Backlog Bug

#36640 Exempt ambient private properties from noImplicitAny
  src/compiler/checker.ts
  tests/baselines/reference/privateNameAmbientNoImplicitAny.errors.txt
  tests/baselines/reference/privateNameAmbientNoImplicitAny.js
  tests/baselines/reference/privateNameAmbientNoImplicitAny.symbols
  tests/baselines/reference/privateNameAmbientNoImplicitAny.types
  tests/cases/conformance/classes/members/privateNames/privateNameAmbientNoImplicitAny.ts
Labels: For Backlog Bug

#36807 Fix organizeImports with type-only imports
  src/services/organizeImports.ts
  src/testRunner/unittests/services/organizeImports.ts
  tests/baselines/reference/organizeImports/TypeOnly.ts
Labels: Author: Team

#36814 Add comments about type-only import combination
  src/services/organizeImports.ts
  src/testRunner/unittests/services/organizeImports.ts
Labels: Author: Team

#36601 fix(29565): Add missing super() quickFix errors for constructors with access modifier
  src/services/codefixes/fixConstructorForDerivedNeedSuperCall.ts
  tests/cases/fourslash/codeFixAddMissingSuperCall.ts
  tests/cases/fourslash/codeFixAddMissingSuperCall1.ts
  tests/cases/fourslash/codeFixAddMissingSuperCall2.ts
Labels: For Backlog Bug

#35921 Include stdout in test worker error messages
  src/testRunner/externalCompileRunner.ts
Labels: Housekeeping

#35781 Add buildTsc to preTest for user test runner
  Gulpfile.js
Labels: Housekeeping

#36865 Fix initialization error when destructuring from object literal that includes a spread assignment
  src/compiler/checker.ts
  tests/baselines/reference/destructuringSpread.errors.txt
  tests/baselines/reference/destructuringSpread.js
  tests/baselines/reference/destructuringSpread.symbols
  tests/baselines/reference/destructuringSpread.types
  tests/cases/conformance/es6/destructuring/destructuringSpread.ts
Labels: Author: Team

#36885 Fix typo in getChangesSinceVersion
  src/server/project.ts
Labels: Author: Team

#36720 fix(33377): completions for string literals don't follow quoteStyle preference
  src/services/completions.ts
  src/services/services.ts
  src/services/utilities.ts
  tests/cases/fourslash/completionForStringLiteral_quotePreference.ts
  tests/cases/fourslash/completionForStringLiteral_quotePreference1.ts
  tests/cases/fourslash/completionForStringLiteral_quotePreference2.ts
  tests/cases/fourslash/completionForStringLiteral_quotePreference3.ts
  tests/cases/fourslash/completionForStringLiteral_quotePreference4.ts
  tests/cases/fourslash/completionForStringLiteral_quotePreference5.ts
  tests/cases/fourslash/completionForStringLiteral_quotePreference6.ts
Labels: For Milestone Bug

#36402 feat(36048): Apply uncalled function checks to ternaries
  src/compiler/checker.ts
  tests/baselines/reference/truthinessCallExpressionCoercion1.errors.txt
  tests/baselines/reference/truthinessCallExpressionCoercion1.js
  tests/baselines/reference/truthinessCallExpressionCoercion1.symbols
  tests/baselines/reference/truthinessCallExpressionCoercion1.types
  tests/cases/compiler/truthinessCallExpressionCoercion1.ts
Labels: For Milestone Bug

#36886 Remove trailing whitespace from copyright notice
  CopyrightNotice.txt
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team

#36902 azure-sdk test: move typescript location
  tests/cases/docker/azure-sdk/Dockerfile
Labels: Author: Team

#36725 Expose importModuleSpecifierEnding to protocol
  src/compiler/types.ts
  src/server/protocol.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team

#36915 Update scripts for octokit 17
  package.json
  scripts/open-cherry-pick-pr.ts
  scripts/open-user-pr.ts
  scripts/perf-result-post.js
  scripts/post-vsts-artifact-comment.js
  scripts/update-experimental-branches.js
Labels: Author: Team

#36941 Fix find-refs crash on JSDocNamepath
  src/compiler/utilitiesPublic.ts
  tests/baselines/reference/renameJSDocNamepath.baseline
  tests/cases/fourslash/renameJSDocNamepath.ts
Labels: Author: Team

#36342 Add elaboration & quickfix for async-able arrow function
  src/compiler/checker.ts
  src/services/codefixes/addMissingAsync.ts
  src/services/tsconfig.json
  tests/baselines/reference/errorOnUnionVsObjectShouldDeeplyDisambiguate.errors.txt
  tests/baselines/reference/errorOnUnionVsObjectShouldDeeplyDisambiguate2.errors.txt
  tests/cases/fourslash/codeFixAddMissingAsync.ts
  tests/cases/fourslash/codeFixAddMissingAsync2.ts
Labels: Author: Team, For Milestone Bug

#36953 sanitize yarn-node path in output
  src/testRunner/externalCompileRunner.ts
  tests/baselines/reference/docker/office-ui-fabric.log
Labels: Author: Team

#36553 Update CONTRIBUTING.md to reflect "new" CLA process
  CONTRIBUTING.md
Labels: Author: Team, Housekeeping

#36795 Fix class emit in converted loop body
  src/compiler/transformers/es2015.ts
  tests/baselines/reference/classInConvertedLoopES5.js
  tests/baselines/reference/classInConvertedLoopES5.symbols
  tests/baselines/reference/classInConvertedLoopES5.types
  tests/cases/compiler/classInConvertedLoopES5.ts
Labels: Author: Team

#36982 Set CI=true in the office-ui-fabric docker test so it doesn't use a progress indicator
  tests/cases/docker/office-ui-fabric/Dockerfile
Labels: Author: Team

#36914 Properly handle both special export forms when renaming
  src/compiler/utilities.ts
  src/services/importTracker.ts
  tests/baselines/reference/renameExportCrash.baseline
  tests/cases/fourslash/renameExportCrash.ts
Labels: Author: Team

#36996 Fix crash on aliased, exported @enum tag in jsdoc
  src/compiler/binder.ts
  tests/baselines/reference/exportedAliasedEnumTag.symbols
  tests/baselines/reference/exportedAliasedEnumTag.types
  tests/cases/conformance/jsdoc/exportedAliasedEnumTag.ts
Labels: Author: Team

#36998 Remove unneeded branch from getHelperName
  src/compiler/checker.ts
  src/compiler/types.ts
Labels: Author: Team

#37001 Declare dependencies between helpers in the declaritive fashion
  src/compiler/factory.ts
  src/compiler/transformers/es2018.ts
Labels: Author: Team

#36993 Harden telemetryOnOpenFile
  src/server/editorServices.ts
Labels: Author: Team

#36724 Add js-equivalent test for the binary expression stress and introduce trampoline into getJSSyntacticDiagnosticsForFile
  src/compiler/parser.ts
  src/compiler/program.ts
  tests/cases/compiler/binderBinaryExpressionStressJs.ts
Labels: Author: Team

#36643 Baseline arity checks for jsx sfc tags
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/utilities.ts
  tests/baselines/reference/jsxIssuesErrorWhenTagExpectsTooManyArguments.errors.txt
  tests/baselines/reference/jsxIssuesErrorWhenTagExpectsTooManyArguments.js
  tests/baselines/reference/jsxIssuesErrorWhenTagExpectsTooManyArguments.symbols
  tests/baselines/reference/jsxIssuesErrorWhenTagExpectsTooManyArguments.types
  tests/cases/compiler/jsxIssuesErrorWhenTagExpectsTooManyArguments.tsx
Labels: Author: Team

#36593 Support declaration emit for late bound element accesses assigned to functions in both TS and JS
  src/compiler/checker.ts
  src/compiler/transformers/declarations.ts
  src/compiler/transformers/declarations/diagnostics.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  tests/baselines/reference/lateBoundElementAccessAssignmentDeclarations.js
  tests/baselines/reference/lateBoundElementAccessAssignmentDeclarations.symbols
  tests/baselines/reference/lateBoundElementAccessAssignmentDeclarations.types
  tests/baselines/reference/lateBoundElementAccessAssignmentDeclarationsInJs.js
  tests/baselines/reference/lateBoundElementAccessAssignmentDeclarationsInJs.symbols
  tests/baselines/reference/lateBoundElementAccessAssignmentDeclarationsInJs.types
  tests/cases/compiler/lateBoundElementAccessAssignmentDeclarations.ts
  tests/cases/compiler/lateBoundElementAccessAssignmentDeclarationsInJs.ts
Labels: Author: Team

#37021 Check for undefined `source.symbol` when elaborating unmatched properties
  src/compiler/checker.ts
  tests/baselines/reference/privateFieldAssignabilityFromUnknown.errors.txt
  tests/baselines/reference/privateFieldAssignabilityFromUnknown.js
  tests/baselines/reference/privateFieldAssignabilityFromUnknown.symbols
  tests/baselines/reference/privateFieldAssignabilityFromUnknown.types
  tests/cases/compiler/privateFieldAssignabilityFromUnknown.ts
Labels: Author: Team

#36880 Adds floating block comments to the outlining spans response
  src/harness/fourslashImpl.ts
  src/services/outliningElementsCollector.ts
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/outlineSpansBlockCommentsWithoutStatements.ts
  tests/cases/fourslash/outlineSpansTrailingBlockCommentsAfterStatements.ts
  tests/cases/fourslash/server/getOutliningSpansForRegions.ts
Labels: Author: Team

#37024 Reduce lerna loglevel
  tests/cases/docker/office-ui-fabric/Dockerfile
Labels: Author: Team

#36952 Ignore data- props when excess property checking
  src/compiler/checker.ts
  tests/baselines/reference/tsxUnionMemberChecksFilterDataProps.js
  tests/baselines/reference/tsxUnionMemberChecksFilterDataProps.symbols
  tests/baselines/reference/tsxUnionMemberChecksFilterDataProps.types
  tests/cases/compiler/tsxUnionMemberChecksFilterDataProps.tsx
Labels: Author: Team

#37031 Ignore data- props when excess property checking (#36952)
  src/compiler/checker.ts
  tests/baselines/reference/tsxUnionMemberChecksFilterDataProps.js
  tests/baselines/reference/tsxUnionMemberChecksFilterDataProps.symbols
  tests/baselines/reference/tsxUnionMemberChecksFilterDataProps.types
  tests/cases/compiler/tsxUnionMemberChecksFilterDataProps.tsx
Labels: Author: Team

#37034 Revert "Support declaration emit for late bound element accesses assi…
  src/compiler/checker.ts
  src/compiler/transformers/declarations.ts
  src/compiler/transformers/declarations/diagnostics.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  tests/baselines/reference/lateBoundElementAccessAssignmentDeclarations.js
  tests/baselines/reference/lateBoundElementAccessAssignmentDeclarations.symbols
  tests/baselines/reference/lateBoundElementAccessAssignmentDeclarations.types
  tests/baselines/reference/lateBoundElementAccessAssignmentDeclarationsInJs.js
  tests/baselines/reference/lateBoundElementAccessAssignmentDeclarationsInJs.symbols
  tests/baselines/reference/lateBoundElementAccessAssignmentDeclarationsInJs.types
  tests/cases/compiler/lateBoundElementAccessAssignmentDeclarations.ts
  tests/cases/compiler/lateBoundElementAccessAssignmentDeclarationsInJs.ts
Labels: Author: Team

#32116 Unwrap substitutions both before _and_ after potential simplification
  src/compiler/checker.ts
  tests/baselines/reference/indexedAccessKeyofNestedSimplifiedSubstituteUnwrapped.js
  tests/baselines/reference/indexedAccessKeyofNestedSimplifiedSubstituteUnwrapped.symbols
  tests/baselines/reference/indexedAccessKeyofNestedSimplifiedSubstituteUnwrapped.types
  tests/cases/compiler/indexedAccessKeyofNestedSimplifiedSubstituteUnwrapped.ts
Labels: Author: Team, For Backlog Bug

#36781 No error on `this` expressions in static property declaration initialisers (ESNext+useDefineForClassFields)
  src/compiler/checker.ts
  tests/baselines/reference/thisInClassBodyStaticESNext.js
  tests/baselines/reference/thisInClassBodyStaticESNext.symbols
  tests/baselines/reference/thisInClassBodyStaticESNext.types
  tests/cases/compiler/thisInClassBodyStaticESNext.ts
Labels: Author: Team, For Milestone Bug

#37049 Update baseline
  tests/baselines/reference/thisInClassBodyStaticESNext.js
Labels: Author: Team

#37023 Detect circularities when removing 'undefined' from defaulted params
  src/compiler/checker.ts
  tests/baselines/reference/circularOptionalityRemoval.errors.txt
  tests/baselines/reference/circularOptionalityRemoval.js
  tests/baselines/reference/circularOptionalityRemoval.symbols
  tests/baselines/reference/circularOptionalityRemoval.types
  tests/cases/compiler/circularOptionalityRemoval.ts
Labels: Author: Team

#37059 Remove unnecessary assert
  src/server/editorServices.ts
  src/testRunner/unittests/tsserver/applyChangesToOpenFiles.ts
  src/testRunner/unittests/tsserver/openFile.ts
Labels: Author: Team

#36997 Allow --composite false or --composite null on the command line
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  src/testRunner/tsconfig.json
  src/testRunner/unittests/config/commandLineParsing.ts
  src/testRunner/unittests/tsc/composite.ts
  tests/baselines/reference/tsc/composite/initial-build/when-setting-composite-false-and-tsbuildinfo-as-null-on-command-line-but-has-tsbuild-info-in-config.js
  tests/baselines/reference/tsc/composite/initial-build/when-setting-composite-false-on-command-line-but-has-tsbuild-info-in-config.js
  tests/baselines/reference/tsc/composite/initial-build/when-setting-composite-false-on-command-line.js
  tests/baselines/reference/tsc/composite/initial-build/when-setting-composite-null-on-command-line.js
Labels: Author: Team

#37062 [release-3.8] Allow --composite false or --composite null on the command line (#36997)
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  src/testRunner/tsconfig.json
  src/testRunner/unittests/config/commandLineParsing.ts
  src/testRunner/unittests/tsc/composite.ts
  tests/baselines/reference/tsc/composite/initial-build/when-setting-composite-false-and-tsbuildinfo-as-null-on-command-line-but-has-tsbuild-info-in-config.js
  tests/baselines/reference/tsc/composite/initial-build/when-setting-composite-false-on-command-line-but-has-tsbuild-info-in-config.js
  tests/baselines/reference/tsc/composite/initial-build/when-setting-composite-false-on-command-line.js
  tests/baselines/reference/tsc/composite/initial-build/when-setting-composite-null-on-command-line.js
Labels: Author: Team

#36292 Adding support for @implements.
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/parser.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/compiler/utilitiesPublic.ts
  src/services/codefixes/fixClassIncorrectlyImplementsInterface.ts
  src/services/jsDoc.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/jsdocImplements_class.errors.txt
  tests/baselines/reference/jsdocImplements_class.js
  tests/baselines/reference/jsdocImplements_class.symbols
  tests/baselines/reference/jsdocImplements_class.types
  tests/baselines/reference/jsdocImplements_interface.errors.txt
  tests/baselines/reference/jsdocImplements_interface.js
  tests/baselines/reference/jsdocImplements_interface.symbols
  tests/baselines/reference/jsdocImplements_interface.types
  tests/baselines/reference/jsdocImplements_interface_multiple.errors.txt
  tests/baselines/reference/jsdocImplements_interface_multiple.js
  tests/baselines/reference/jsdocImplements_interface_multiple.symbols
  tests/baselines/reference/jsdocImplements_interface_multiple.types
  tests/baselines/reference/jsdocImplements_missingType.errors.txt
  tests/baselines/reference/jsdocImplements_missingType.js
  tests/baselines/reference/jsdocImplements_missingType.symbols
  tests/baselines/reference/jsdocImplements_missingType.types
  tests/baselines/reference/jsdocImplements_properties.errors.txt
  tests/baselines/reference/jsdocImplements_properties.js
  tests/baselines/reference/jsdocImplements_properties.symbols
  tests/baselines/reference/jsdocImplements_properties.types
  tests/baselines/reference/jsdocImplements_signatures.errors.txt
  tests/baselines/reference/jsdocImplements_signatures.js
  tests/baselines/reference/jsdocImplements_signatures.symbols
  tests/baselines/reference/jsdocImplements_signatures.types
  tests/cases/conformance/jsdoc/jsdocImplements_class.ts
  tests/cases/conformance/jsdoc/jsdocImplements_interface.ts
  tests/cases/conformance/jsdoc/jsdocImplements_interface_multiple.ts
  tests/cases/conformance/jsdoc/jsdocImplements_missingType.ts
  tests/cases/conformance/jsdoc/jsdocImplements_properties.ts
  tests/cases/conformance/jsdoc/jsdocImplements_signatures.ts
Labels: For Milestone Bug

#36409 Adds underlines to differences in failing test strings
  src/harness/fourslashImpl.ts
Labels: Author: Team, Housekeeping

#36867 Update the authors script to generate the content of authors.md
  AUTHORS.md
  scripts/authors.ts
Labels: Author: Team

#37054 Measure module and type reference directive times
  src/compiler/program.ts
Labels: Author: Team

#36913 Remove crashing diagnostic code
  src/services/importTracker.ts
  tests/cases/fourslash/emptyExportFindReferences.ts
Labels: Author: Team

#37050 Exempt ambient [#]private from unused error
  src/compiler/checker.ts
  tests/cases/fourslash/unusedVariableInClass4.ts
  tests/cases/fourslash/unusedVariableInClass5.ts
Labels: Author: Team

#36861 Proper treatment of splicing tuples in array literals
  src/compiler/checker.ts
  tests/baselines/reference/arrayLiteralExpressionContextualTyping.errors.txt
  tests/baselines/reference/arrayLiteralExpressionContextualTyping.types
  tests/baselines/reference/arrayLiterals3.errors.txt
  tests/baselines/reference/arrayLiterals3.types
  tests/baselines/reference/constAssertions.js
  tests/baselines/reference/constAssertions.types
  tests/baselines/reference/declarationsAndAssignments.types
  tests/baselines/reference/destructuringTuple.types
  tests/baselines/reference/for-of49.types
  tests/baselines/reference/literalFreshnessPropagationOnNarrowing.errors.txt
  tests/baselines/reference/restElementMustBeLast.types
  tests/baselines/reference/restElementWithAssignmentPattern1.errors.txt
  tests/baselines/reference/restElementWithAssignmentPattern1.types
  tests/baselines/reference/restElementWithAssignmentPattern3.types
  tests/baselines/reference/restElementWithAssignmentPattern5.types
  tests/baselines/reference/spliceTuples.errors.txt
  tests/baselines/reference/spliceTuples.js
  tests/baselines/reference/spliceTuples.symbols
  tests/baselines/reference/spliceTuples.types
  tests/cases/compiler/spliceTuples.ts
Labels: Author: Team

#37071 Reapply contextual type when recalculating array literals as tuples
  src/compiler/checker.ts
  tests/baselines/reference/errorsForCallAndAssignmentAreSimilar.errors.txt
  tests/baselines/reference/errorsForCallAndAssignmentAreSimilar.js
  tests/baselines/reference/errorsForCallAndAssignmentAreSimilar.symbols
  tests/baselines/reference/errorsForCallAndAssignmentAreSimilar.types
  tests/cases/compiler/errorsForCallAndAssignmentAreSimilar.ts
Labels: Author: Team

#37088 Harden findAllReferences.ts against `symbol.declarations = undefined` cases
  src/services/findAllReferences.ts
  tests/baselines/reference/highlightsForExportFromUnfoundModule.baseline
  tests/cases/fourslash/highlightsForExportFromUnfoundModule.ts
Labels: Author: Team

#37064 Grammar error on `export type *`
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/utilities.ts
  tests/baselines/reference/exportNamespace4.errors.txt
  tests/baselines/reference/exportNamespace4.js
  tests/baselines/reference/exportNamespace4.symbols
  tests/baselines/reference/exportNamespace4.types
  tests/cases/conformance/externalModules/typeOnly/exportNamespace4.ts
Labels: Author: Team

#37082 Cherry picks 36880 into 3.8
  src/harness/fourslashImpl.ts
  src/services/outliningElementsCollector.ts
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/outlineSpansBlockCommentsWithoutStatements.ts
  tests/cases/fourslash/outlineSpansTrailingBlockCommentsAfterStatements.ts
  tests/cases/fourslash/server/getOutliningSpansForRegions.ts
Labels: Author: Team

#37027 Full support for CommonJS auto-imports in JS
  src/compiler/checker.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/harness/fourslashImpl.ts
  src/services/codefixes/importFixes.ts
  src/services/completions.ts
  src/services/utilities.ts
  tests/cases/fourslash/completionsImport_compilerOptionsModule.ts
  tests/cases/fourslash/completionsImport_require_addNew.ts
  tests/cases/fourslash/completionsImport_require_addToExisting.ts
  tests/cases/fourslash/importFixWithMultipleModuleExportAssignment.ts
  tests/cases/fourslash/importFixesGlobalTypingsCache.ts
  tests/cases/fourslash/importNameCodeFix_all_js.ts
  tests/cases/fourslash/importNameCodeFix_defaultExport.ts
  tests/cases/fourslash/importNameCodeFix_require.ts
  tests/cases/fourslash/importNameCodeFix_require_UMD.ts
  tests/cases/fourslash/importNameCodeFix_require_addToExisting.ts
  tests/cases/fourslash/importNameCodeFix_require_importVsRequire_addToExistingWins.ts
  tests/cases/fourslash/importNameCodeFix_require_importVsRequire_importWins.ts
  tests/cases/fourslash/importNameCodeFix_require_importVsRequire_moduleTarget.ts
  tests/cases/fourslash/importNameCodeFix_require_namedAndDefault.ts
  tests/cases/fourslash/moveToNewFile_js.ts
Labels: Author: Team

#36696 Reduce intersections by discriminants
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/factory.ts
  src/compiler/transformers/classFields.ts
  src/compiler/types.ts
  tests/baselines/reference/discriminatedUnionTypes2.errors.txt
  tests/baselines/reference/discriminatedUnionTypes2.js
  tests/baselines/reference/discriminatedUnionTypes2.symbols
  tests/baselines/reference/discriminatedUnionTypes2.types
  tests/baselines/reference/intersectionReduction.errors.txt
  tests/baselines/reference/intersectionReduction.js
  tests/baselines/reference/intersectionReduction.symbols
  tests/baselines/reference/intersectionReduction.types
  tests/baselines/reference/intersectionReductionStrict.errors.txt
  tests/baselines/reference/intersectionReductionStrict.js
  tests/baselines/reference/intersectionReductionStrict.symbols
  tests/baselines/reference/intersectionReductionStrict.types
  tests/baselines/reference/objectSpread.types
  tests/baselines/reference/recursiveMappedTypes.errors.txt
  tests/baselines/reference/stringLiteralTypesAsTags01.types
  tests/baselines/reference/stringLiteralTypesAsTags02.types
  tests/baselines/reference/stringLiteralTypesAsTags03.types
  tests/baselines/reference/tsxUnionElementType1.errors.txt
  tests/baselines/reference/tsxUnionElementType2.errors.txt
  tests/baselines/reference/typeGuardsWithInstanceOf.errors.txt
  tests/baselines/reference/typeGuardsWithInstanceOf.symbols
  tests/baselines/reference/typeGuardsWithInstanceOf.types
  tests/cases/conformance/types/intersection/intersectionReduction.ts
  tests/cases/conformance/types/intersection/intersectionReductionStrict.ts
  tests/cases/conformance/types/union/discriminatedUnionTypes2.ts
  tests/cases/fourslash/quickInfoInheritedJSDoc.ts
  tests/cases/fourslash/tsxCompletionUnionElementType.ts
Labels: Breaking Change
