Repository microsoft/TypeScript, pull requests merged in 2020-08, with the labels that each got.

#39818 In JS declaration emit, move imports painted in nested contexts to the root private context
  src/compiler/checker.ts
  tests/baselines/reference/jsDeclarationsImportAliasExposedWithinNamespace.js
  tests/baselines/reference/jsDeclarationsImportAliasExposedWithinNamespace.symbols
  tests/baselines/reference/jsDeclarationsImportAliasExposedWithinNamespace.types
  tests/baselines/reference/jsDeclarationsImportAliasExposedWithinNamespaceCjs.errors.txt
  tests/baselines/reference/jsDeclarationsImportAliasExposedWithinNamespaceCjs.js
  tests/baselines/reference/jsDeclarationsImportAliasExposedWithinNamespaceCjs.symbols
  tests/baselines/reference/jsDeclarationsImportAliasExposedWithinNamespaceCjs.types
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsImportAliasExposedWithinNamespace.ts
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsImportAliasExposedWithinNamespaceCjs.ts
Labels: Author: Team, For Milestone Bug

#39855 Limit auto import provider project size
  src/compiler/types.ts
  src/server/editorServices.ts
  src/server/project.ts
  src/server/protocol.ts
  src/services/types.ts
  src/testRunner/unittests/tsserver/autoImportProvider.ts
  src/testRunner/unittests/tsserver/cachingFileSystemInformation.ts
  src/testRunner/unittests/tsserver/typingsInstaller.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#39868 LEGO: Pull request from lego/hb_998_20200803041043643 to master
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#39892 Make numeric Array constructors take ArrayLikeBuffer union
  src/lib/es5.d.ts
Labels: Author: Team, For Uncommitted Bug

#39896 LEGO: Pull request from lego/hb_998_20200804041041181 to master
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#39894 Bump version to 4.1.
  package.json
  src/compiler/corePublic.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Uncommitted Bug

#39897 Add an 'Update LKG' action
  .github/workflows/blank.yml
Labels: For Uncommitted Bug

#39904 LEGO: Pull request from lego/hb_998_20200804161041013 to master
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#39889 Handle the fact that noResolveResolution resolution is reused
  src/compiler/resolutionCache.ts
  src/testRunner/unittests/tsserver/approximateSemanticOnlyServer.ts
Labels: Author: Team, For Uncommitted Bug

#39913 LEGO: Pull request from lego/hb_998_20200804221105684 to master
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#37891 Fix indentation preservation in JSDoc (#37717)
  src/compiler/parser.ts
  tests/cases/fourslash/jsDocIndentationPreservation1.ts
  tests/cases/fourslash/jsDocIndentationPreservation2.ts
  tests/cases/fourslash/jsDocIndentationPreservation3.ts
Labels: For Backlog Bug

#39921 LEGO: Pull request from lego/hb_998_20200805161039274 to master
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#39912 Find tagless JSDoc as preceding token
  src/services/utilities.ts
  tests/cases/fourslash/completionsAfterJSDoc.ts
Labels: Author: Team, For Milestone Bug

#39883 Renames in servermode per feedback
  src/server/editorServices.ts
  src/server/project.ts
  src/server/session.ts
  src/services/services.ts
  src/services/types.ts
  src/testRunner/tsconfig.json
  src/testRunner/unittests/tsserver/partialSemanticServer.ts
  src/testRunner/unittests/tsserver/syntacticServer.ts
  src/tsserver/server.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#39927 LEGO: Pull request from lego/hb_998_20200805221115472 to master
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#39937 Handle empty package.json files
  src/server/editorServices.ts
  src/server/packageJsonCache.ts
  src/services/utilities.ts
  src/testRunner/unittests/tsserver/packageJsonInfo.ts
Labels: Author: Team, For Milestone Bug

#39932 Add missing 'importName' for private field helpers
  src/compiler/factory/emitHelpers.ts
  tests/baselines/reference/importHelpersES6.js
  tests/baselines/reference/importHelpersES6.symbols
  tests/baselines/reference/importHelpersES6.types
  tests/cases/compiler/importHelpersES6.ts
Labels: Author: Team, For Milestone Bug

#39924 Insert auto imports after header comment
  src/services/textChanges.ts
  src/services/utilities.ts
  tests/cases/fourslash/importNameCodeFix_HeaderComment1.ts
  tests/cases/fourslash/importNameCodeFix_HeaderComment2.ts
Labels: For Milestone Bug

#39940 Update CI node versions
  .github/workflows/ci.yml
  .travis.yml
Labels: Author: Team, For Uncommitted Bug

#39950 Use isUncalledFunctionReference for aliases too
  src/compiler/checker.ts
  tests/cases/fourslash/jsdocDeprecated_suggestion8.ts
  tests/cases/fourslash/jsdocDeprecated_suggestion9.ts
Labels: Author: Team, For Uncommitted Bug

#39820 Export anonymous functions in 2 steps, declare as variable and then assign to exports.
  src/compiler/transformers/module/module.ts
  tests/baselines/reference/aliasUsedAsNameValue.js
  tests/baselines/reference/declarationEmitAliasExportStar.js
  tests/baselines/reference/declarationEmitBundleWithAmbientReferences.js
  tests/baselines/reference/declarationEmitComputedNameCausesImportToBePainted.js
  tests/baselines/reference/declarationEmitExpandoWithGenericConstraint.js
  tests/baselines/reference/declarationEmitExportAliasVisibiilityMarking.js
  tests/baselines/reference/declarationEmitOptionalMethod.js
  tests/baselines/reference/declarationEmitRetainsJsdocyComments.js
  tests/baselines/reference/declarationEmitTypeAliasWithTypeParameters1.js
  tests/baselines/reference/declarationEmitTypeAliasWithTypeParameters2.js
  tests/baselines/reference/declarationEmitWithInvalidPackageJsonTypings.js
  tests/baselines/reference/declarationsForFileShadowingGlobalNoError.js
  tests/baselines/reference/declarationsWithRecursiveInternalTypesProduceUniqueTypeParams.js
  tests/baselines/reference/errorsWithInvokablesInUnions01.js
  tests/baselines/reference/esModuleInteropImportTSLibHasImport.js
  tests/baselines/reference/genericIndexedAccessMethodIntersectionCanBeAccessed.js
  tests/baselines/reference/importCallExpressionAsyncES3AMD.js
  tests/baselines/reference/importCallExpressionAsyncES3CJS.js
  tests/baselines/reference/importCallExpressionAsyncES3UMD.js
  tests/baselines/reference/importCallExpressionAsyncES5AMD.js
  tests/baselines/reference/importCallExpressionAsyncES5CJS.js
  tests/baselines/reference/importCallExpressionAsyncES5UMD.js
  tests/baselines/reference/importCallExpressionAsyncES6AMD.js
  tests/baselines/reference/importCallExpressionAsyncES6CJS.js
  tests/baselines/reference/importCallExpressionAsyncES6UMD.js
  tests/baselines/reference/inlineJsxFactoryDeclarationsLocalTypes.js
  tests/baselines/reference/mixinIntersectionIsValidbaseType.js
  tests/baselines/reference/moduleDeclarationExportStarShadowingGlobalIsNameable.js
  tests/baselines/reference/propertyAssignmentUseParentType1.js
  tests/baselines/reference/referenceTypesPreferedToPathIfPossible.js
  tests/baselines/reference/switchCaseNarrowsMatchingClausesEvenWhenNonMatchingClausesExist.js
  tests/baselines/reference/taggedTemplateWithoutDeclaredHelper.js
  tests/baselines/reference/topLevelLambda4.js
  tests/baselines/reference/typeReferenceDirectives7.js
  tests/baselines/reference/uniqueSymbolsDeclarationsErrors.js
Labels: For Milestone Bug

#39793 Make release-3.3 buildable
  .gitignore
  .npmrc
  .travis.yml
  package-lock.json
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/utilities.ts
Labels: For Uncommitted Bug

#39979 Make release-3.1 buildable
  .gitignore
  .npmrc
  .travis.yml
  package-lock.json
  src/compiler/binder.ts
  src/compiler/builder.ts
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/parser.ts
  src/compiler/utilities.ts
  src/harness/compiler.ts
Labels: For Uncommitted Bug

#39980 Make release-3.2 buildable
  .gitignore
  .npmrc
  .travis.yml
  package-lock.json
  src/compiler/binder.ts
  src/compiler/builder.ts
  src/compiler/checker.ts
  src/compiler/core.ts
  src/compiler/emitter.ts
  src/compiler/parser.ts
  src/compiler/utilities.ts
  src/harness/compiler.ts
  src/harness/fourslash.ts
  src/harness/harness.ts
  src/services/refactors/extractSymbol.ts
  src/tsserver/server.ts
Labels: For Uncommitted Bug

#39982 Make release-3.5 buildable
  .gitignore
  .npmrc
  .travis.yml
  package-lock.json
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/utilities.ts
Labels: For Uncommitted Bug

#39908 Bind alias ThisProperty assignment declarations
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/utilities.ts
  tests/baselines/reference/inferringClassMembersFromAssignments6.symbols
  tests/baselines/reference/inferringClassMembersFromAssignments6.types
  tests/baselines/reference/inferringClassMembersFromAssignments7.symbols
  tests/baselines/reference/inferringClassMembersFromAssignments7.types
  tests/baselines/reference/lateBoundClassMemberAssignmentJS3.js
  tests/baselines/reference/lateBoundClassMemberAssignmentJS3.symbols
  tests/baselines/reference/lateBoundClassMemberAssignmentJS3.types
  tests/baselines/reference/typeFromPropertyAssignment10.symbols
  tests/baselines/reference/typeFromPropertyAssignment10.types
  tests/baselines/reference/typeFromPropertyAssignment10_1.symbols
  tests/baselines/reference/typeFromPropertyAssignment10_1.types
  tests/baselines/reference/typeFromPropertyAssignment40.symbols
  tests/baselines/reference/typeFromPropertyAssignment40.types
  tests/baselines/reference/typeFromPropertyAssignment9.symbols
  tests/baselines/reference/typeFromPropertyAssignment9.types
  tests/baselines/reference/typeFromPropertyAssignment9_1.symbols
  tests/baselines/reference/typeFromPropertyAssignment9_1.types
  tests/cases/conformance/salsa/inferringClassMembersFromAssignments6.ts
  tests/cases/conformance/salsa/inferringClassMembersFromAssignments7.ts
  tests/cases/conformance/salsa/lateBoundClassMemberAssignmentJS3.ts
  tests/cases/conformance/salsa/typeFromPropertyAssignment40.ts
Labels: Author: Team, For Uncommitted Bug

#39803 fix export * as default syntax
  src/compiler/factory/utilities.ts
  src/compiler/parser.ts
  src/compiler/transformers/module/esnextAnd2015.ts
  src/compiler/transformers/module/module.ts
  src/compiler/utilities.ts
  tests/baselines/reference/exportAsNamespace4(module=amd).js
  tests/baselines/reference/exportAsNamespace4(module=amd).symbols
  tests/baselines/reference/exportAsNamespace4(module=amd).types
  tests/baselines/reference/exportAsNamespace4(module=commonjs).js
  tests/baselines/reference/exportAsNamespace4(module=commonjs).symbols
  tests/baselines/reference/exportAsNamespace4(module=commonjs).types
  tests/baselines/reference/exportAsNamespace4(module=es2015).js
  tests/baselines/reference/exportAsNamespace4(module=es2015).symbols
  tests/baselines/reference/exportAsNamespace4(module=es2015).types
  tests/baselines/reference/exportAsNamespace4(module=esnext).js
  tests/baselines/reference/exportAsNamespace4(module=esnext).symbols
  tests/baselines/reference/exportAsNamespace4(module=esnext).types
  tests/baselines/reference/exportAsNamespace4(module=system).js
  tests/baselines/reference/exportAsNamespace4(module=system).symbols
  tests/baselines/reference/exportAsNamespace4(module=system).types
  tests/baselines/reference/exportAsNamespace4(module=umd).js
  tests/baselines/reference/exportAsNamespace4(module=umd).symbols
  tests/baselines/reference/exportAsNamespace4(module=umd).types
  tests/cases/conformance/es2020/modules/exportAsNamespace4.ts
Labels: For Milestone Bug

#39981 Make release-3.4 buildable
  .gitignore
  .npmrc
  .travis.yml
  package-lock.json
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/utilities.ts
Labels: For Uncommitted Bug

#39702 Improve deprecated suggestion node position
  src/compiler/checker.ts
  tests/cases/fourslash/jsdocDeprecated_suggestion1.ts
  tests/cases/fourslash/jsdocDeprecated_suggestion2.ts
  tests/cases/fourslash/jsdocDeprecated_suggestion3.ts
Labels: For Milestone Bug

#39984 Make release-3.6 buildable
  .gitignore
  .npmrc
  .travis.yml
  package-lock.json
  src/compiler/binder.ts
  src/compiler/utilities.ts
Labels: For Uncommitted Bug

#39986 Make release-3.7 buildable
  .gitignore
  .npmrc
  .travis.yml
  package-lock.json
Labels: For Uncommitted Bug

#39987 Make release-3.8 buildable
  .github/workflows/ci.yml
  .gitignore
  .npmrc
  .travis.yml
  package-lock.json
Labels: For Uncommitted Bug

#39988 Make release-3.9 buildable
  .github/workflows/ci.yml
  .gitignore
  .npmrc
  .travis.yml
  package-lock.json
Labels: For Uncommitted Bug

#40009 No this-property assignments in TS
  src/compiler/binder.ts
  tests/baselines/reference/inferringClassMembersFromAssignments8.js
  tests/baselines/reference/inferringClassMembersFromAssignments8.symbols
  tests/baselines/reference/inferringClassMembersFromAssignments8.types
  tests/cases/conformance/salsa/inferringClassMembersFromAssignments8.ts
Labels: Author: Team, For Uncommitted Bug

#39994 fix(13503): Crash for `getTypeAtLocation(sourceFile)`
  src/compiler/checker.ts
  src/testRunner/unittests/publicApi.ts
Labels: For Backlog Bug

#39955 Avoid the double-symbol trick for enums
  src/compiler/binder.ts
  tests/baselines/reference/exportedEnumTypeAndValue.symbols
  tests/baselines/reference/exportedEnumTypeAndValue.types
  tests/baselines/reference/jsEnumTagOnObjectFrozen.symbols
  tests/cases/conformance/jsdoc/exportedEnumTypeAndValue.ts
  tests/cases/fourslash/quickInfoJSExport.ts
Labels: Author: Team, For Milestone Bug

#40026 Revert to including only open files in partial semantic server mode
  src/compiler/program.ts
  src/compiler/resolutionCache.ts
  src/compiler/types.ts
  src/compiler/watchPublic.ts
  src/server/editorServices.ts
  src/server/project.ts
  src/services/services.ts
  src/services/types.ts
  src/testRunner/unittests/tsserver/partialSemanticServer.ts
Labels: Author: Team, For Uncommitted Bug

#40005 feat(40004): Missing Compiler API predicate function: isNamedTupleMember
  src/compiler/factory/nodeTests.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Uncommitted Bug

#39989 Pin dependencies in release branch
  .github/workflows/ci.yml
  .gitignore
  .npmrc
  .travis.yml
  package-lock.json
Labels: For Uncommitted Bug

#40032 fix(15230): "Cannot compile namespaces" error with --isolatedModules and no namespaces
  src/compiler/diagnosticMessages.json
  src/compiler/program.ts
  tests/baselines/reference/importHelpersInIsolatedModules.errors.txt
  tests/baselines/reference/isolatedModulesNoExternalModule.errors.txt
  tests/baselines/reference/isolatedModulesOut.errors.txt
  tests/baselines/reference/isolatedModulesPlainFile-AMD.errors.txt
  tests/baselines/reference/isolatedModulesPlainFile-CommonJS.errors.txt
  tests/baselines/reference/isolatedModulesPlainFile-ES6.errors.txt
  tests/baselines/reference/isolatedModulesPlainFile-System.errors.txt
  tests/baselines/reference/isolatedModulesPlainFile-UMD.errors.txt
  tests/baselines/reference/tscWatch/emit/emit-for-configured-projects/should-always-return-the-file-itself-if-'--isolatedModules'-is-specified.js
Labels: For Backlog Bug

#39859 fix jsx completions after attributes
  src/services/completions.ts
  tests/cases/fourslash/completionsJsxAttribute2.ts
Labels: For Backlog Bug

#40041 Ensure file, include and exclude specs used are strings
  src/compiler/commandLineParser.ts
  src/compiler/types.ts
  src/testRunner/unittests/config/tsconfigParsing.ts
Labels: Author: Team

#40061 Add '(approximate)' to the beginning of quick info requests in PartialSemantic mode
  src/services/services.ts
  src/testRunner/unittests/tsserver/partialSemanticServer.ts
Labels: For Uncommitted Bug

#40002 Recursive conditional types
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/deeplyNestedConditionalTypes.types
  tests/baselines/reference/promiseTypeInference.types
  tests/baselines/reference/recursiveConditionalTypes.errors.txt
  tests/baselines/reference/recursiveConditionalTypes.js
  tests/baselines/reference/recursiveConditionalTypes.symbols
  tests/baselines/reference/recursiveConditionalTypes.types
  tests/cases/compiler/recursiveConditionalTypes.ts
Labels: For Milestone Bug

#40072 Revert "Add '(approximate)' to the beginning of quick info requests in PartialSemantic mode"
  src/services/services.ts
  src/testRunner/unittests/tsserver/partialSemanticServer.ts
Labels: For Uncommitted Bug

#40099 LEGO: Pull request from lego/hb_998_20200817221115725 to master
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#40094 Fix lack of error on default export of nonexistant name
  src/compiler/checker.ts
  src/compiler/program.ts
  src/harness/compilerImpl.ts
  tests/baselines/reference/exportDefaultMissingName.errors.txt
  tests/baselines/reference/exportDefaultMissingName.js
  tests/baselines/reference/exportDefaultMissingName.symbols
  tests/baselines/reference/exportDefaultMissingName.types
  tests/cases/compiler/exportDefaultMissingName.ts
Labels: Author: Team, For Uncommitted Bug

#40064 fix(10019): for-loop labels cannot be renamed
  src/services/rename.ts
  tests/baselines/reference/renameLabel1.baseline
  tests/baselines/reference/renameLabel2.baseline
  tests/baselines/reference/renameLabel3.baseline
  tests/baselines/reference/renameLabel4.baseline
  tests/baselines/reference/renameLabel5.baseline
  tests/baselines/reference/renameLabel6.baseline
  tests/cases/fourslash/renameLabel1.ts
  tests/cases/fourslash/renameLabel2.ts
  tests/cases/fourslash/renameLabel3.ts
  tests/cases/fourslash/renameLabel4.ts
  tests/cases/fourslash/renameLabel5.ts
  tests/cases/fourslash/renameLabel6.ts
Labels: For Backlog Bug

#40108 LEGO: Pull request from lego/hb_998_20200818101052368 to master
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#39529 Make the falsy part of any/unknown any/unknown
  src/compiler/checker.ts
  tests/baselines/reference/anyAndUnknownHaveFalsyComponents.js
  tests/baselines/reference/anyAndUnknownHaveFalsyComponents.symbols
  tests/baselines/reference/anyAndUnknownHaveFalsyComponents.types
  tests/baselines/reference/contextualExpressionTypecheckingDoesntBlowStack.types
  tests/baselines/reference/controlFlowCaching.types
  tests/baselines/reference/narrowingTruthyObject.types
  tests/cases/compiler/anyAndUnknownHaveFalsyComponents.ts
Labels: Author: Team, Breaking Change

#40114 Add unit tests for VersionRange
  src/compiler/semver.ts
  src/testRunner/unittests/semver.ts
Labels: Author: Team

#40117 Ping @sandersn on new user baseline commits
  scripts/open-user-pr.ts
Labels: Author: Team, For Uncommitted Bug

#40043 Set stackTraceLimit to 0 in fileSystemEntryExists
  src/compiler/sys.ts
Labels: For Uncommitted Bug

#40119 LEGO: Pull request from lego/hb_998_20200818221105285 to master
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#40055 Optimize source mapping into external source map sources
  src/compiler/sourcemap.ts
Labels: For Uncommitted Bug

#40126 Perf test PR for "Optimize source mapping into external source map sources"
  src/compiler/sourcemap.ts
Labels: For Uncommitted Bug

#40118 Fix tuple name homogeneity check
  src/compiler/checker.ts
  tests/baselines/reference/namedTupleMembersErrors.errors.txt
  tests/baselines/reference/namedTupleMembersErrors.js
  tests/baselines/reference/namedTupleMembersErrors.symbols
  tests/baselines/reference/namedTupleMembersErrors.types
  tests/cases/conformance/types/tuple/named/namedTupleMembersErrors.ts
Labels: Author: Team, For Uncommitted Bug

#40135 Fixes crash on chained property access on require
  src/compiler/checker.ts
  tests/baselines/reference/requireTwoPropertyAccesses.js
  tests/baselines/reference/requireTwoPropertyAccesses.symbols
  tests/baselines/reference/requireTwoPropertyAccesses.types
  tests/cases/conformance/salsa/requireTwoPropertyAccesses.ts
Labels: Author: Team, For Uncommitted Bug

#40130 Optimize external source maps without full cache
  src/compiler/emitter.ts
Labels: For Uncommitted Bug

#40120 Typescript Language Specification amended
  doc/spec.md
Labels: For Uncommitted Bug

#40147 Revamp dockerfile for office-ui-fabric to reduce noise
  tests/cases/docker/office-ui-fabric/Dockerfile
Labels: Author: Team, For Uncommitted Bug

#40057 Allow trailing params of undefined/unknown/any' to be optional in JS
  src/compiler/checker.ts
  tests/baselines/reference/callWithMissingVoidUndefinedUnknownAnyInJs(strict=false).errors.txt
  tests/baselines/reference/callWithMissingVoidUndefinedUnknownAnyInJs(strict=false).symbols
  tests/baselines/reference/callWithMissingVoidUndefinedUnknownAnyInJs(strict=false).types
  tests/baselines/reference/callWithMissingVoidUndefinedUnknownAnyInJs(strict=true).errors.txt
  tests/baselines/reference/callWithMissingVoidUndefinedUnknownAnyInJs(strict=true).symbols
  tests/baselines/reference/callWithMissingVoidUndefinedUnknownAnyInJs(strict=true).types
  tests/cases/conformance/expressions/functionCalls/callWithMissingVoidUndefinedUnknownAnyInJs.ts
Labels: Author: Team, For Uncommitted Bug

#40102 Add missing contextual type to static PropertyDeclarations
  src/compiler/checker.ts
  tests/baselines/reference/contextuallyTypedClassExpressionMethodDeclaration01.errors.txt
  tests/baselines/reference/contextuallyTypedClassExpressionMethodDeclaration01.symbols
  tests/baselines/reference/contextuallyTypedClassExpressionMethodDeclaration01.types
  tests/baselines/reference/staticFieldWithInterfaceContext.js
  tests/baselines/reference/staticFieldWithInterfaceContext.symbols
  tests/baselines/reference/staticFieldWithInterfaceContext.types
  tests/cases/compiler/staticFieldWithInterfaceContext.ts
Labels: Author: Team, For Milestone Bug

#40146 Adopt package-lock.json
  .github/workflows/ci.yml
  .github/workflows/new-release-branch.yaml
  .github/workflows/release-branch-artifact.yaml
  .github/workflows/set-version.yaml
  .github/workflows/sync-branch.yaml
  .github/workflows/update-lkg.yml
  .github/workflows/update-package-lock.yaml
  .npmrc
  .travis.yml
  Dockerfile
  README.md
  package-lock.json
Labels: For Uncommitted Bug

#40161 Delete extra npm update
  .github/workflows/ci.yml
Labels: For Uncommitted Bug

#40039 Add compactDisplay and signDisplay to NumberFormatOptions
  src/lib/es2020.intl.d.ts
  tests/lib/lib.d.ts
Labels: For Uncommitted Bug

#40221 Fix commonjs require of ES export
  src/compiler/checker.ts
  tests/baselines/reference/requireOfESWithPropertyAccess.errors.txt
  tests/baselines/reference/requireOfESWithPropertyAccess.js
  tests/baselines/reference/requireOfESWithPropertyAccess.symbols
  tests/baselines/reference/requireOfESWithPropertyAccess.types
  tests/cases/conformance/salsa/requireOfESWithPropertyAccess.ts
Labels: Author: Team, For Milestone Bug

#40236 LEGO: Pull request from lego/hb_998_20200825061107217 to master
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#40230 Update CONTRIBUTING.md for code contributors
  CONTRIBUTING.md
Labels: Author: Team, For Uncommitted Bug

#40244 Swallow empty-commit error
  .github/workflows/update-package-lock.yaml
Labels: For Uncommitted Bug

#40046 don't emit "unused @ts-expect-error" in unchecked js files
  src/compiler/program.ts
  tests/baselines/reference/ts-expect-error-js.errors.txt
  tests/baselines/reference/ts-expect-error-js.symbols
  tests/baselines/reference/ts-expect-error-js.types
  tests/baselines/reference/ts-expect-error-nocheck-js.symbols
  tests/baselines/reference/ts-expect-error-nocheck-js.types
  tests/baselines/reference/ts-expect-error-nocheck.js
  tests/baselines/reference/ts-expect-error-nocheck.symbols
  tests/baselines/reference/ts-expect-error-nocheck.types
  tests/cases/conformance/directives/ts-expect-error-js.ts
  tests/cases/conformance/directives/ts-expect-error-nocheck-js.ts
  tests/cases/conformance/directives/ts-expect-error-nocheck.ts
Labels: For Uncommitted Bug

#40255 LEGO: Pull request from lego/hb_998_20200826001146505 to master
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#40172 Fix `getContextualTypeForBindingElement` for arrays
  src/compiler/checker.ts
  tests/baselines/reference/contextualTypingArrayDestructuringWithDefaults.errors.txt
  tests/baselines/reference/contextualTypingArrayDestructuringWithDefaults.js
  tests/baselines/reference/contextualTypingArrayDestructuringWithDefaults.symbols
  tests/baselines/reference/contextualTypingArrayDestructuringWithDefaults.types
  tests/baselines/reference/staticFieldWithInterfaceContext.js
  tests/baselines/reference/staticFieldWithInterfaceContext.symbols
  tests/baselines/reference/staticFieldWithInterfaceContext.types
  tests/cases/compiler/contextualTypingArrayDestructuringWithDefaults.ts
  tests/cases/compiler/staticFieldWithInterfaceContext.ts
Labels: Author: Team, For Uncommitted Bug

#40282 LEGO: Pull request from lego/hb_998_20200827061105358 to master
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#40280 Disable diagnostic consistency checking for large tests
  src/harness/compilerImpl.ts
Labels: Author: Team, For Uncommitted Bug

#40105 Specified error diagnostic for invalid variable names
  src/compiler/diagnosticMessages.json
  src/compiler/parser.ts
  tests/baselines/reference/expressionTypeNodeShouldError.errors.txt
  tests/baselines/reference/getJavaScriptSyntacticDiagnostics02.baseline
  tests/baselines/reference/parserInvalidIdentifiersInVariableStatements1.errors.txt
  tests/baselines/reference/reservedWords2.errors.txt
  tests/baselines/reference/umd-errors.errors.txt
Labels: For Backlog Bug

#40289 LEGO: Pull request from lego/hb_998_20200827181105373 to master
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#40016 fix(40010): GetOutliningSpans does not include comment for const
  src/services/outliningElementsCollector.ts
  tests/cases/fourslash/getOutliningForBlockComments.ts
Labels: For Milestone Bug

#40268 Use a correct Object.entries polyfill
  src/compiler/core.ts
Labels: Author: Team, For Milestone Bug

#40231 Treat trailing 'void' as optional for assignability
  src/compiler/checker.ts
  src/compiler/debug.ts
  src/compiler/types.ts
  src/lib/es2015.promise.d.ts
  tests/baselines/reference/arrayFrom.types
  tests/baselines/reference/asyncArrowFunction11_es5.types
  tests/baselines/reference/asyncFunctionReturnType.types
  tests/baselines/reference/callWithMissingVoid.errors.txt
  tests/baselines/reference/exportDefaultAsyncFunction2.types
  tests/baselines/reference/generatorReturnContextualType.types
  tests/baselines/reference/genericFunctionInference1.types
  tests/baselines/reference/inferFromGenericFunctionReturnTypes3.types
  tests/baselines/reference/instantiateContextualTypes.types
  tests/baselines/reference/intersectionWithConflictingPrivates.types
  tests/baselines/reference/jsDeclarationsJSDocRedirectedLookups.types
  tests/baselines/reference/jsFileCompilationAwaitModifier.types
  tests/baselines/reference/jsdocArrayObjectPromiseImplicitAny.types
  tests/baselines/reference/jsdocArrayObjectPromiseNoImplicitAny.types
  tests/baselines/reference/noImplicitReturnsInAsync1.types
  tests/baselines/reference/promiseType.types
  tests/baselines/reference/promiseTypeStrictNull.types
  tests/baselines/reference/promiseVoidErrorCallback.types
  tests/baselines/reference/transformNestedGeneratorsWithTry.types
  tests/baselines/reference/types.asyncGenerators.es2018.1.types
  tests/baselines/reference/types.asyncGenerators.es2018.2.types
  tests/baselines/reference/unionAndIntersectionInference1.types
  tests/baselines/reference/uniqueSymbols.types
  tests/baselines/reference/uniqueSymbolsDeclarations.types
  tests/baselines/reference/voidParamAssignmentCompatibility.js
  tests/baselines/reference/voidParamAssignmentCompatibility.symbols
  tests/baselines/reference/voidParamAssignmentCompatibility.types
  tests/cases/conformance/expressions/functions/voidParamAssignmentCompatibility.ts
Labels: Author: Team, For Uncommitted Bug

#40211 feat(part of 40169): No spelling suggestion/quick fix for namespaces
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/services/codefixes/fixSpelling.ts
  tests/baselines/reference/exportSpellingSuggestion.errors.txt
  tests/baselines/reference/missingMemberErrorHasShortPath.errors.txt
  tests/baselines/reference/moduleVisibilityTest3.errors.txt
  tests/baselines/reference/moduleVisibilityTest4.errors.txt
  tests/baselines/reference/moduleVisibilityTest4.js
  tests/baselines/reference/moduleVisibilityTest4.symbols
  tests/baselines/reference/moduleVisibilityTest4.types
  tests/baselines/reference/tscWatch/emit/emit-with-outFile-or-out-setting/with---outFile-and-multiple-declaration-files-in-the-program.js
  tests/baselines/reference/tscWatch/emit/emit-with-outFile-or-out-setting/without---outFile-and-multiple-declaration-files-in-the-program.js
  tests/cases/compiler/moduleVisibilityTest4.ts
  tests/cases/fourslash/codeFixSpelling7.ts
  tests/cases/fourslash/codeFixSpelling8.ts
  tests/cases/fourslash/codeFixSpelling9.ts
Labels: For Uncommitted Bug

#40318 LEGO: Pull request from lego/hb_998_20200829181109026 to master
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#40273 Fix misplaced comma in auto imported specifier
  src/services/codefixes/importFixes.ts
  tests/cases/fourslash/importNameCodeFix_trailingComma.ts
Labels: Author: Team, For Milestone Bug

#40329 fix(docs): Tests for multiple files in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: For Uncommitted Bug

#40272 Fix extract symbol crash on unterminated literals; don’t offer to extract `export = ...`
  src/compiler/emitter.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/services/refactors/extractSymbol.ts
  src/services/textChanges.ts
  tests/cases/fourslash/extract-export-assignment.ts
  tests/cases/fourslash/extract-unterminated1.ts
  tests/cases/fourslash/extract-unterminated2.ts
  tests/cases/fourslash/extract-unterminated3.ts
  tests/cases/fourslash/extract-unterminated4.ts
  tests/cases/fourslash/extract-unterminated5.ts
Labels: Author: Team
