Repository microsoft/TypeScript, pull requests merged in 2020-11, with the labels that each got.

#41226 feat(eslint): upgrade typescript-eslint/eslint
  .eslintrc.json
  package-lock.json
  package.json
  scripts/tsconfig.eslint.json
Labels: For Uncommitted Bug

#41000 Rename 'compat' to 'deprecatedCompat'.
  src/compiler/parser.ts
  src/deprecatedCompat/deprecations.ts
  src/deprecatedCompat/tsconfig.json
  src/tsserver/tsconfig.json
  src/tsserverlibrary/tsconfig.json
  src/typescriptServices/tsconfig.json
Labels: For Uncommitted Bug

#40912 fix(40901): Variable arguments generated from JS although not applicable
  src/compiler/checker.ts
  tests/baselines/reference/argumentsReferenceInConstructor1_Js.js
  tests/baselines/reference/argumentsReferenceInConstructor1_Js.symbols
  tests/baselines/reference/argumentsReferenceInConstructor1_Js.types
  tests/baselines/reference/argumentsReferenceInConstructor2_Js.js
  tests/baselines/reference/argumentsReferenceInConstructor2_Js.symbols
  tests/baselines/reference/argumentsReferenceInConstructor2_Js.types
  tests/baselines/reference/argumentsReferenceInConstructor3_Js.js
  tests/baselines/reference/argumentsReferenceInConstructor3_Js.symbols
  tests/baselines/reference/argumentsReferenceInConstructor3_Js.types
  tests/baselines/reference/argumentsReferenceInConstructor4_Js.js
  tests/baselines/reference/argumentsReferenceInConstructor4_Js.symbols
  tests/baselines/reference/argumentsReferenceInConstructor4_Js.types
  tests/baselines/reference/argumentsReferenceInConstructor5_Js.js
  tests/baselines/reference/argumentsReferenceInConstructor5_Js.symbols
  tests/baselines/reference/argumentsReferenceInConstructor5_Js.types
  tests/baselines/reference/argumentsReferenceInConstructor6_Js.js
  tests/baselines/reference/argumentsReferenceInConstructor6_Js.symbols
  tests/baselines/reference/argumentsReferenceInConstructor6_Js.types
  tests/baselines/reference/argumentsReferenceInConstructor7_Js.js
  tests/baselines/reference/argumentsReferenceInConstructor7_Js.symbols
  tests/baselines/reference/argumentsReferenceInConstructor7_Js.types
  tests/baselines/reference/argumentsReferenceInMethod1_Js.js
  tests/baselines/reference/argumentsReferenceInMethod1_Js.symbols
  tests/baselines/reference/argumentsReferenceInMethod1_Js.types
  tests/baselines/reference/argumentsReferenceInMethod2_Js.js
  tests/baselines/reference/argumentsReferenceInMethod2_Js.symbols
  tests/baselines/reference/argumentsReferenceInMethod2_Js.types
  tests/baselines/reference/argumentsReferenceInMethod3_Js.js
  tests/baselines/reference/argumentsReferenceInMethod3_Js.symbols
  tests/baselines/reference/argumentsReferenceInMethod3_Js.types
  tests/baselines/reference/argumentsReferenceInMethod4_Js.js
  tests/baselines/reference/argumentsReferenceInMethod4_Js.symbols
  tests/baselines/reference/argumentsReferenceInMethod4_Js.types
  tests/baselines/reference/argumentsReferenceInMethod5_Js.js
  tests/baselines/reference/argumentsReferenceInMethod5_Js.symbols
  tests/baselines/reference/argumentsReferenceInMethod5_Js.types
  tests/baselines/reference/argumentsReferenceInMethod6_Js.js
  tests/baselines/reference/argumentsReferenceInMethod6_Js.symbols
  tests/baselines/reference/argumentsReferenceInMethod6_Js.types
  tests/baselines/reference/argumentsReferenceInMethod7_Js.js
  tests/baselines/reference/argumentsReferenceInMethod7_Js.symbols
  tests/baselines/reference/argumentsReferenceInMethod7_Js.types
  tests/cases/compiler/argumentsReferenceInConstructor1_Js.ts
  tests/cases/compiler/argumentsReferenceInConstructor2_Js.ts
  tests/cases/compiler/argumentsReferenceInConstructor3_Js.ts
  tests/cases/compiler/argumentsReferenceInConstructor4_Js.ts
  tests/cases/compiler/argumentsReferenceInConstructor5_Js.ts
  tests/cases/compiler/argumentsReferenceInConstructor6_Js.ts
  tests/cases/compiler/argumentsReferenceInConstructor7_Js.ts
  tests/cases/compiler/argumentsReferenceInMethod1_Js.ts
  tests/cases/compiler/argumentsReferenceInMethod2_Js.ts
  tests/cases/compiler/argumentsReferenceInMethod3_Js.ts
  tests/cases/compiler/argumentsReferenceInMethod4_Js.ts
  tests/cases/compiler/argumentsReferenceInMethod5_Js.ts
  tests/cases/compiler/argumentsReferenceInMethod6_Js.ts
  tests/cases/compiler/argumentsReferenceInMethod7_Js.ts
Labels: For Backlog Bug

#37903 Add index signature for anonymous object literal type
  src/compiler/checker.ts
  tests/baselines/reference/indexedAccessWithFreshObjectLiteral.errors.txt
  tests/baselines/reference/indexedAccessWithFreshObjectLiteral.js
  tests/baselines/reference/indexedAccessWithFreshObjectLiteral.symbols
  tests/baselines/reference/indexedAccessWithFreshObjectLiteral.types
  tests/baselines/reference/noImplicitAnyIndexing.errors.txt
  tests/baselines/reference/noImplicitAnyIndexing.types
  tests/baselines/reference/noImplicitAnyIndexingSuppressed.errors.txt
  tests/baselines/reference/noImplicitAnyIndexingSuppressed.types
  tests/baselines/reference/noImplicitAnyStringIndexerOnObject.errors.txt
  tests/baselines/reference/noImplicitAnyStringIndexerOnObject.types
  tests/cases/compiler/indexedAccessWithFreshObjectLiteral.ts
Labels: For Uncommitted Bug

#41127 fix(38283): Incorrect parse on static property followed by method
  src/compiler/parser.ts
  tests/baselines/reference/staticAsIdentifier.errors.txt
  tests/baselines/reference/staticAsIdentifier.js
  tests/baselines/reference/staticAsIdentifier.symbols
  tests/baselines/reference/staticAsIdentifier.types
  tests/cases/compiler/staticAsIdentifier.ts
Labels: For Milestone Bug

#40171 Add support for pedantic property access
  src/compiler/checker.ts
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  src/compiler/types.ts
  src/services/codefixes/fixNoPropertyAccessFromIndexSignature.ts
  src/services/tsconfig.json
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/noPropertyAccessFromIndexSignature1.errors.txt
  tests/baselines/reference/noPropertyAccessFromIndexSignature1.js
  tests/baselines/reference/noPropertyAccessFromIndexSignature1.symbols
  tests/baselines/reference/noPropertyAccessFromIndexSignature1.types
  tests/baselines/reference/showConfig/Shows tsconfig for single option/noPropertyAccessFromIndexSignature/tsconfig.json
  tests/baselines/reference/tsConfig/Default initialized TSConfig/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with advanced options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with boolean value compiler options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with enum value compiler options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with files options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with incorrect compiler option value/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with incorrect compiler option/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with list compiler options with enum value/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with list compiler options/tsconfig.json
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/declarationDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/when-outDir-and-declarationDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/when-outDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/with-outFile.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/without-outDir-or-outFile-is-specified-with-declaration-enabled.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/without-outDir-or-outFile-is-specified.js
  tests/cases/conformance/additionalChecks/noPropertyAccessFromIndexSignature1.ts
  tests/cases/fourslash/codeFixNoPropertyAccessFromIndexSignature1.ts
  tests/cases/fourslash/codeFixNoPropertyAccessFromIndexSignature2.ts
  tests/cases/fourslash/codeFixNoPropertyAccessFromIndexSignature3.ts
  tests/cases/fourslash/codeFixNoPropertyAccessFromIndexSignature_fixAll.ts
Labels: For Uncommitted Bug

#40265 fix(40257): Remove type parameters quick fix forgets the trailing >
  src/compiler/checker.ts
  src/compiler/utilities.ts
  src/services/textChanges.ts
  tests/cases/fourslash/unusedTypeParametersWithTrivia1.ts
  tests/cases/fourslash/unusedTypeParametersWithTrivia2.ts
  tests/cases/fourslash/unusedTypeParametersWithTrivia3.ts
  tests/cases/fourslash/unusedTypeParametersWithTrivia4.ts
Labels: For Milestone Bug

#37421 Support xml namespace prefix for JSX elements and attributes
  src/compiler/checker.ts
  src/compiler/scanner.ts
  src/compiler/utilities.ts
  tests/baselines/reference/jsxEsprimaFbTestSuite.errors.txt
  tests/baselines/reference/jsxEsprimaFbTestSuite.js
  tests/baselines/reference/jsxEsprimaFbTestSuite.symbols
  tests/baselines/reference/jsxEsprimaFbTestSuite.types
  tests/baselines/reference/jsxInvalidEsprimaTestSuite.errors.txt
  tests/baselines/reference/jsxInvalidEsprimaTestSuite.js
  tests/baselines/reference/jsxInvalidEsprimaTestSuite.symbols
  tests/baselines/reference/jsxInvalidEsprimaTestSuite.types
  tests/baselines/reference/jsxNamespacePrefixInName.errors.txt
  tests/baselines/reference/jsxNamespacePrefixInName.js
  tests/baselines/reference/jsxNamespacePrefixInName.symbols
  tests/baselines/reference/jsxNamespacePrefixInName.types
  tests/baselines/reference/jsxNamespacePrefixInNameReact.errors.txt
  tests/baselines/reference/jsxNamespacePrefixInNameReact.js
  tests/baselines/reference/jsxNamespacePrefixInNameReact.symbols
  tests/baselines/reference/jsxNamespacePrefixInNameReact.types
  tests/baselines/reference/jsxNamespacePrefixIntrinsics.errors.txt
  tests/baselines/reference/jsxNamespacePrefixIntrinsics.js
  tests/baselines/reference/jsxNamespacePrefixIntrinsics.symbols
  tests/baselines/reference/jsxNamespacePrefixIntrinsics.types
  tests/cases/compiler/jsxNamespacePrefixInName.tsx
  tests/cases/compiler/jsxNamespacePrefixInNameReact.tsx
  tests/cases/compiler/jsxNamespacePrefixIntrinsics.tsx
  tests/cases/conformance/jsx/jsxEsprimaFbTestSuite.tsx
Labels: For Uncommitted Bug

#41089 fix(41078): Convert to ES6 Class Refactoring removes methods named with quoted properties
  src/services/codefixes/convertFunctionToEs6Class.ts
  tests/cases/fourslash/convertFunctionToEs6Class10.ts
  tests/cases/fourslash/convertFunctionToEs6Class11.ts
  tests/cases/fourslash/convertFunctionToEs6Class12.ts
  tests/cases/fourslash/convertFunctionToEs6Class13.ts
  tests/cases/fourslash/convertFunctionToEs6Class4.ts
  tests/cases/fourslash/convertFunctionToEs6Class5.ts
  tests/cases/fourslash/convertFunctionToEs6Class6.ts
  tests/cases/fourslash/convertFunctionToEs6Class7.ts
  tests/cases/fourslash/convertFunctionToEs6Class8.ts
  tests/cases/fourslash/convertFunctionToEs6Class9.ts
Labels: For Backlog Bug

#40050 fix(40042): Convert to async function with decorator
  src/services/codefixes/convertToAsyncFunction.ts
  src/services/textChanges.ts
  src/testRunner/unittests/services/convertToAsyncFunction.ts
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_decoratedMethod.ts
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_decoratedMethodWithModifier.ts
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_decoratedMethodWithMultipleLineComment.ts
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_decoratedMethodWithSingleLineComment.ts
Labels: For Backlog Bug

#40154 fix(39858): "Convert to async function" refactor generates invalid code with imported functions
  src/services/codefixes/convertToAsyncFunction.ts
  src/testRunner/unittests/services/convertToAsyncFunction.ts
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_importedFunction.js
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_importedFunction.ts
Labels: For Backlog Bug

#41376 LEGO: Pull request from lego/hb_998_20201103061039042 to master
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#41377 Bump 4.2
  package.json
  src/compiler/corePublic.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Uncommitted Bug

#41375 Fix Markdown spec link
  README.md
Labels: For Uncommitted Bug

#37964 Dont look for properties of Object and Function type when looking to resolve named import from module with `export=`
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/moduleAugmentationWithNonExistentNamedImport.errors.txt
  tests/baselines/reference/moduleAugmentationWithNonExistentNamedImport.symbols
  tests/baselines/reference/moduleAugmentationWithNonExistentNamedImport.types
  tests/baselines/reference/namedImportNonExistentName.errors.txt
  tests/baselines/reference/namedImportNonExistentName.js
  tests/baselines/reference/namedImportNonExistentName.symbols
  tests/baselines/reference/namedImportNonExistentName.types
  tests/cases/compiler/moduleAugmentationWithNonExistentNamedImport.ts
  tests/cases/compiler/namedImportNonExistentName.ts
Labels: Author: Team, For Milestone Bug

#41052 feat(40750): Refactoring to add inferred return type annotation to a function
  src/compiler/diagnosticMessages.json
  src/services/refactors/inferFunctionReturnType.ts
  src/services/tsconfig.json
  tests/cases/fourslash/refactorConvertExport_namedToDefault_alreadyHasDefault.ts
  tests/cases/fourslash/refactorInferFunctionReturnType1.ts
  tests/cases/fourslash/refactorInferFunctionReturnType10.ts
  tests/cases/fourslash/refactorInferFunctionReturnType11.ts
  tests/cases/fourslash/refactorInferFunctionReturnType12.ts
  tests/cases/fourslash/refactorInferFunctionReturnType13.ts
  tests/cases/fourslash/refactorInferFunctionReturnType14.ts
  tests/cases/fourslash/refactorInferFunctionReturnType15.ts
  tests/cases/fourslash/refactorInferFunctionReturnType2.ts
  tests/cases/fourslash/refactorInferFunctionReturnType3.ts
  tests/cases/fourslash/refactorInferFunctionReturnType4.ts
  tests/cases/fourslash/refactorInferFunctionReturnType5.ts
  tests/cases/fourslash/refactorInferFunctionReturnType6.ts
  tests/cases/fourslash/refactorInferFunctionReturnType7.ts
  tests/cases/fourslash/refactorInferFunctionReturnType8.ts
  tests/cases/fourslash/refactorInferFunctionReturnType9.ts
Labels: For Uncommitted Bug

#39243 Add way to exclude files and directories to watch
  src/compiler/commandLineParser.ts
  src/compiler/sys.ts
  src/compiler/tsbuildPublic.ts
  src/compiler/types.ts
  src/compiler/watch.ts
  src/compiler/watchPublic.ts
  src/compiler/watchUtilities.ts
  src/harness/virtualFileSystemWithWatch.ts
  src/jsTyping/types.ts
  src/server/editorServices.ts
  src/server/project.ts
  src/server/protocol.ts
  src/testRunner/tsconfig.json
  src/testRunner/unittests/config/commandLineParsing.ts
  src/testRunner/unittests/config/tsconfigParsingWatchOptions.ts
  src/testRunner/unittests/tscWatch/watchEnvironment.ts
  src/testRunner/unittests/tsserver/reloadProjects.ts
  src/testRunner/unittests/tsserver/watchEnvironment.ts
  src/typingsInstallerCore/typingsInstaller.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/showConfig/Shows tsconfig for single option/excludeDirectories/tsconfig.json
  tests/baselines/reference/showConfig/Shows tsconfig for single option/excludeFiles/tsconfig.json
  tests/baselines/reference/tscWatch/watchEnvironment/watchOptions/with-excludeDirectories-option-extendedDiagnostics.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchOptions/with-excludeDirectories-option-with-recursive-directory-watching-extendedDiagnostics.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchOptions/with-excludeDirectories-option-with-recursive-directory-watching.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchOptions/with-excludeDirectories-option.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchOptions/with-excludeFiles-option-extendedDiagnostics.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchOptions/with-excludeFiles-option.js
Labels: Author: Team

#40699 fix(40632): Don't emit abstract members
  src/compiler/transformers/classFields.ts
  src/compiler/transformers/ts.ts
  tests/baselines/reference/abstractProperty(target=es2015).js
  tests/baselines/reference/abstractProperty(target=es2015).symbols
  tests/baselines/reference/abstractProperty(target=es2015).types
  tests/baselines/reference/abstractProperty(target=esnext).js
  tests/baselines/reference/abstractProperty(target=esnext).symbols
  tests/baselines/reference/abstractProperty(target=esnext).types
  tests/baselines/reference/accessorsOverrideProperty7.js
  tests/baselines/reference/privateNamesIncompatibleModifiers.js
  tests/cases/conformance/classes/propertyMemberDeclarations/abstractProperty.ts
Labels: For Milestone Bug

#40653 fix(40610): "Convert to template string" result unnecessarily complicated if one part was already a template string
  src/services/refactors/convertStringOrTemplateLiteral.ts
  tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_TemplateString1.ts
  tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_TemplateString10.ts
  tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_TemplateString2.ts
  tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_TemplateString3.ts
  tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_TemplateString4.ts
  tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_TemplateString5.ts
  tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_TemplateString6.ts
  tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_TemplateString7.ts
  tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_TemplateString8.ts
  tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_TemplateString9.ts
Labels: For Uncommitted Bug

#40476 fix(40469): "Convert to named function" refactoring is not suggested for non-arrow function expressions
  src/services/refactors/convertArrowFunctionOrFunctionExpression.ts
  tests/cases/fourslash/refactorConvertArrowFunctionOrFunctionExpression_Availability_Anon.ts
  tests/cases/fourslash/refactorConvertArrowFunctionOrFunctionExpression_Availability_Anon_unusedName.ts
Labels: For Backlog Bug

#39298 String literal rename support
  src/services/findAllReferences.ts
  src/services/rename.ts
  src/services/utilities.ts
  tests/cases/fourslash/renameStringLiteralOk.ts
  tests/cases/fourslash/renameStringLiteralOk1.ts
  tests/cases/fourslash/renameStringLiteralTypes.ts
Labels: For Backlog Bug

#41462 Revert "Revert "feat(40197): handle uncalled function checks in binar…
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/emitter.ts
  tests/baselines/reference/truthinessCallExpressionCoercion2.errors.txt
  tests/baselines/reference/truthinessCallExpressionCoercion2.js
  tests/baselines/reference/truthinessCallExpressionCoercion2.symbols
  tests/baselines/reference/truthinessCallExpressionCoercion2.types
  tests/cases/compiler/truthinessCallExpressionCoercion2.ts
  tests/cases/fourslash/codeFixMissingCallParentheses11.ts
  tests/cases/fourslash/codeFixMissingCallParentheses12.ts
  tests/cases/fourslash/codeFixMissingCallParentheses13.ts
  tests/cases/fourslash/codeFixMissingCallParentheses14.ts
  tests/cases/fourslash/codeFixMissingCallParentheses15.ts
  tests/cases/fourslash/codeFixMissingCallParentheses16.ts
  tests/cases/fourslash/codeFixMissingCallParentheses17.ts
Labels: Author: Team, For Uncommitted Bug

#41416 Add more team members to pr_owners.txt
  .github/pr_owners.txt
Labels: Author: Team, For Uncommitted Bug

#41479 Add missed resolveSymbol in commonjs import resolution
  src/compiler/checker.ts
  tests/baselines/reference/commonJSReexport.symbols
  tests/baselines/reference/commonJSReexport.types
  tests/cases/conformance/salsa/commonJSReexport.ts
Labels: Author: Team, For Milestone Bug

#41403 dispose Mocha Runner after use to avoid MaxlistenersExceededWarning
  src/testRunner/parallel/worker.ts
Labels: For Uncommitted Bug

#40637 Proposal: importModuleSpecifierPreference: project-relative
  src/compiler/moduleSpecifiers.ts
  src/compiler/types.ts
  src/harness/fourslashImpl.ts
  src/server/editorServices.ts
  src/server/project.ts
  src/server/protocol.ts
  src/services/types.ts
  src/services/utilities.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/server/importNameCodeFix_externalNonRelateive2.ts
  tests/cases/fourslash/server/importNameCodeFix_externalNonRelative1.ts
Labels: Author: Team, For Uncommitted Bug

#41460 Update link to TypeScript-Handbook
  doc/handbook/README.md
Labels: For Uncommitted Bug

#41467 Fix crash on attempting to suggest a ts import for a synthetic js resolution
  src/compiler/checker.ts
  src/compiler/utilities.ts
  src/testRunner/unittests/tsc/incremental.ts
  tests/baselines/reference/tsc/react-jsx-emit-mode/initial-build/with-no-backing-types-found-doesn't-crash-under---strict.js
  tests/baselines/reference/tsc/react-jsx-emit-mode/initial-build/with-no-backing-types-found-doesn't-crash.js
Labels: Author: Team, For Milestone Bug

#41500 Port #41467 to `release-4.1`
  src/compiler/checker.ts
  src/compiler/utilities.ts
  src/testRunner/unittests/tsc/incremental.ts
  tests/baselines/reference/tsc/react-jsx-emit-mode/initial-build/with-no-backing-types-found-doesn't-crash-under---strict.js
  tests/baselines/reference/tsc/react-jsx-emit-mode/initial-build/with-no-backing-types-found-doesn't-crash.js
Labels: Author: Team, For Uncommitted Bug

#41498 Fold tracing.begin and end into push and pop
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/parser.ts
  src/compiler/program.ts
  src/compiler/tracing.ts
Labels: Author: Team, For Uncommitted Bug

#41506 Fix post-LKG build
  src/harness/harnessIO.ts
Labels: Author: Team, For Uncommitted Bug

#41507 Fix definition of ts.Iterator
  package-lock.json
  src/compiler/corePublic.ts
  src/compiler/sys.ts
  src/shims/collectionShims.ts
  src/testRunner/unittests/tsbuild/helpers.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Milestone Bug

#41374 Add tracing support to tsserver
  src/compiler/checker.ts
  src/compiler/program.ts
  src/compiler/tracing.ts
  src/executeCommandLine/executeCommandLine.ts
  src/server/session.ts
  src/services/services.ts
  src/tsserver/server.ts
Labels: Author: Team, For Uncommitted Bug

#41502 fix(41492): Uncalled function checks need rhs-used-exemption for binary expression
  src/compiler/checker.ts
  tests/baselines/reference/truthinessCallExpressionCoercion2.errors.txt
  tests/baselines/reference/truthinessCallExpressionCoercion2.js
  tests/baselines/reference/truthinessCallExpressionCoercion2.symbols
  tests/baselines/reference/truthinessCallExpressionCoercion2.types
  tests/cases/compiler/truthinessCallExpressionCoercion2.ts
Labels: For Milestone Bug

#41476 Fix/jsx global preferred over config implicit
  src/compiler/checker.ts
  tests/baselines/reference/jsxEmptyExpressionNotCountedAsChild(jsx=react-jsx).js
  tests/baselines/reference/jsxEmptyExpressionNotCountedAsChild(jsx=react-jsxdev).js
  tests/baselines/reference/jsxNamespaceImplicitImportJSXNamespaceFromConfigPickedOverGlobalOne.js
  tests/baselines/reference/jsxNamespaceImplicitImportJSXNamespaceFromConfigPickedOverGlobalOne.symbols
  tests/baselines/reference/jsxNamespaceImplicitImportJSXNamespaceFromConfigPickedOverGlobalOne.types
  tests/baselines/reference/jsxNamespaceImplicitImportJSXNamespaceFromPragmaPickedOverGlobalOne.js
  tests/baselines/reference/jsxNamespaceImplicitImportJSXNamespaceFromPragmaPickedOverGlobalOne.symbols
  tests/baselines/reference/jsxNamespaceImplicitImportJSXNamespaceFromPragmaPickedOverGlobalOne.types
  tests/cases/compiler/jsxNamespaceImplicitImportJSXNamespaceFromConfigPickedOverGlobalOne.tsx
  tests/cases/compiler/jsxNamespaceImplicitImportJSXNamespaceFromPragmaPickedOverGlobalOne.tsx
Labels: For Uncommitted Bug

#41555 Unused Identifier codefix better understands constructors and methods
  src/services/codefixes/fixUnusedIdentifier.ts
  src/services/findAllReferences.ts
  src/services/utilities.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_super.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_super1.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_super2.ts
Labels: Author: Team, For Milestone Bug

#41275 fix(41227): Cryptic error message when assigning to a key also present on the construtor, but forggetting to declare it in the calss body
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/classImplementsClass6.errors.txt
  tests/baselines/reference/classSideInheritance1.errors.txt
  tests/baselines/reference/classStaticPropertyAccess.errors.txt
  tests/baselines/reference/classStaticPropertyAccess.js
  tests/baselines/reference/classStaticPropertyAccess.symbols
  tests/baselines/reference/classStaticPropertyAccess.types
  tests/baselines/reference/cloduleTest2.errors.txt
  tests/baselines/reference/staticMemberExportAccess.errors.txt
  tests/baselines/reference/staticOffOfInstance1.errors.txt
  tests/baselines/reference/staticOffOfInstance2.errors.txt
  tests/baselines/reference/staticPropertyNotInClassType.errors.txt
  tests/baselines/reference/staticVisibility2.errors.txt
  tests/baselines/reference/superAccess.errors.txt
  tests/baselines/reference/superAccess2.errors.txt
  tests/baselines/reference/superPropertyAccess2.errors.txt
  tests/baselines/reference/thisInOuterClassBody.errors.txt
  tests/baselines/reference/typeofClass.errors.txt
  tests/cases/compiler/classStaticPropertyAccess.ts
Labels: For Backlog Bug

#41583 Port #41476 to release-4.1 - Fix/jsx global preferred over config implicit
  src/compiler/checker.ts
  tests/baselines/reference/jsxEmptyExpressionNotCountedAsChild(jsx=react-jsx).js
  tests/baselines/reference/jsxEmptyExpressionNotCountedAsChild(jsx=react-jsxdev).js
  tests/baselines/reference/jsxNamespaceImplicitImportJSXNamespaceFromConfigPickedOverGlobalOne.js
  tests/baselines/reference/jsxNamespaceImplicitImportJSXNamespaceFromConfigPickedOverGlobalOne.symbols
  tests/baselines/reference/jsxNamespaceImplicitImportJSXNamespaceFromConfigPickedOverGlobalOne.types
  tests/baselines/reference/jsxNamespaceImplicitImportJSXNamespaceFromPragmaPickedOverGlobalOne.js
  tests/baselines/reference/jsxNamespaceImplicitImportJSXNamespaceFromPragmaPickedOverGlobalOne.symbols
  tests/baselines/reference/jsxNamespaceImplicitImportJSXNamespaceFromPragmaPickedOverGlobalOne.types
  tests/cases/compiler/jsxNamespaceImplicitImportJSXNamespaceFromConfigPickedOverGlobalOne.tsx
  tests/cases/compiler/jsxNamespaceImplicitImportJSXNamespaceFromPragmaPickedOverGlobalOne.tsx
Labels: Author: Team, For Uncommitted Bug

#41537 If there are no open files, do not schedule ensureProjectForOpenFiles
  src/server/editorServices.ts
  src/testRunner/unittests/tsserver/externalProjects.ts
  src/testRunner/unittests/tsserver/inferredProjects.ts
  src/testRunner/unittests/tsserver/projects.ts
  src/testRunner/unittests/tsserver/typingsInstaller.ts
Labels: Author: Team, For Uncommitted Bug

#36673 Do not parse template arguments in JavaScript files.
  src/compiler/parser.ts
  tests/baselines/reference/getJavaScriptSyntacticDiagnostics14.baseline
  tests/baselines/reference/jsFileCompilationTypeArgumentSyntaxOfCall.errors.txt
  tests/baselines/reference/jsFileCompilationTypeArgumentSyntaxOfCall.js
  tests/baselines/reference/jsxCheckJsxNoTypeArgumentsAllowed.errors.txt
  tests/baselines/reference/jsxCheckJsxNoTypeArgumentsAllowed.js
  tests/baselines/reference/jsxCheckJsxNoTypeArgumentsAllowed.symbols
  tests/baselines/reference/jsxCheckJsxNoTypeArgumentsAllowed.types
  tests/cases/compiler/jsFileCompilationTypeArgumentSyntaxOfCall.ts
Labels: API, Breaking Change, For Backlog Bug

#41602 Update JSX test errors
  tests/baselines/reference/jsFileCompilationTypeArgumentSyntaxOfCall.errors.txt
  tests/baselines/reference/jsxCheckJsxNoTypeArgumentsAllowed.errors.txt
Labels: Author: Team, For Uncommitted Bug

#41614 Adds Format param to the tsserver session
  src/server/protocol.ts
  src/server/session.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
Labels: Author: Team, For Uncommitted Bug

#39720 Split line and node counts by file extension
  src/executeCommandLine/executeCommandLine.ts
Labels: Author: Team, For Uncommitted Bug

#39898 Add an action to update baselines/fix lints
  .github/workflows/accept-baselines-fix-lints.yaml
Labels: For Milestone Bug

#41168 Remove-unused-identifiers codefix skips assigned identifiers
  src/compiler/checker.ts
  src/services/codefixes/fixUnusedIdentifier.ts
  src/services/findAllReferences.ts
  tests/baselines/reference/unusedDestructuringParameters.errors.txt
  tests/cases/fourslash/codeFixUnusedIdentifier_all_delete.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_deleteWrite.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_deleteWrite2.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_destructure_allUnused_all.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_destructure_partlyUnused.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_parameter.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_parameter_all.ts
Labels: Author: Team, For Milestone Bug

#41604 Pass throwIfNoEntry to fs.statSync
  src/compiler/sys.ts
  src/tsserver/server.ts
Labels: Author: Team, For Uncommitted Bug

#41128 Fix show deprecated suggestion for alias
  src/services/completions.ts
  src/services/rename.ts
  src/services/services.ts
  src/services/symbolDisplay.ts
  tests/baselines/reference/quickInfoDisplayPartsInternalModuleAlias.baseline
  tests/cases/fourslash/completionsExportImport.ts
  tests/cases/fourslash/completionsImport_named_didNotExistBefore.ts
  tests/cases/fourslash/completionsImport_reExportDefault.ts
  tests/cases/fourslash/completionsWithDeprecatedTag.ts
  tests/cases/fourslash/quickInfoAlias.ts
Labels: For Milestone Bug

#41435 fix(41240): Support emitting numerics with separators as-is in target: esnext
  src/compiler/emitter.ts
  src/compiler/utilities.ts
  tests/baselines/reference/numericUnderscoredSeparator(target=es2015).js
  tests/baselines/reference/numericUnderscoredSeparator(target=es2015).symbols
  tests/baselines/reference/numericUnderscoredSeparator(target=es2015).types
  tests/baselines/reference/numericUnderscoredSeparator(target=es2016).js
  tests/baselines/reference/numericUnderscoredSeparator(target=es2016).symbols
  tests/baselines/reference/numericUnderscoredSeparator(target=es2016).types
  tests/baselines/reference/numericUnderscoredSeparator(target=es2017).js
  tests/baselines/reference/numericUnderscoredSeparator(target=es2017).symbols
  tests/baselines/reference/numericUnderscoredSeparator(target=es2017).types
  tests/baselines/reference/numericUnderscoredSeparator(target=es2018).js
  tests/baselines/reference/numericUnderscoredSeparator(target=es2018).symbols
  tests/baselines/reference/numericUnderscoredSeparator(target=es2018).types
  tests/baselines/reference/numericUnderscoredSeparator(target=es2019).js
  tests/baselines/reference/numericUnderscoredSeparator(target=es2019).symbols
  tests/baselines/reference/numericUnderscoredSeparator(target=es2019).types
  tests/baselines/reference/numericUnderscoredSeparator(target=es3).js
  tests/baselines/reference/numericUnderscoredSeparator(target=es3).symbols
  tests/baselines/reference/numericUnderscoredSeparator(target=es3).types
  tests/baselines/reference/numericUnderscoredSeparator(target=es5).js
  tests/baselines/reference/numericUnderscoredSeparator(target=es5).symbols
  tests/baselines/reference/numericUnderscoredSeparator(target=es5).types
  tests/baselines/reference/numericUnderscoredSeparator(target=esnext).js
  tests/baselines/reference/numericUnderscoredSeparator(target=esnext).symbols
  tests/baselines/reference/numericUnderscoredSeparator(target=esnext).types
  tests/cases/compiler/numericUnderscoredSeparator.ts
Labels: For Backlog Bug

#41547 Add a comment to clarify the #private field
  src/compiler/transformers/declarations.ts
Labels: For Uncommitted Bug

#41441 fix(41194): Sort import: Uncoditionally removes JSX Fragment reference
  src/compiler/checker.ts
  src/compiler/types.ts
  src/services/organizeImports.ts
  src/testRunner/unittests/services/organizeImports.ts
  tests/baselines/reference/organizeImports/JsxFragmentPragmaTsx.ts
Labels: For Backlog Bug

#41217 Use stricter types for tracing event arguments
  src/compiler/tracing.ts
Labels: Author: Team, For Uncommitted Bug

#41572 Trace checkDeferredNode to cover JSX elements
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug

#41452 feat(41216): JSDoc not retained across default re-export
  src/services/symbolDisplay.ts
  tests/baselines/reference/jsDocAliasQuickInfo.baseline
  tests/cases/fourslash/jsDocAliasQuickInfo.ts
Labels: For Backlog Bug

#41522 Remove obsolete go-to-definition code after CommonJS alias changes
  src/services/goToDefinition.ts
Labels: Author: Team, For Uncommitted Bug

#41687 fix(41216): update baseline
  tests/baselines/reference/jsDocAliasQuickInfo.baseline
Labels: For Uncommitted Bug

#41665 Properly cache types for shared control flow nodes
  src/compiler/checker.ts
  tests/baselines/reference/controlFlowManyCallExpressionStatementsPerf.js
  tests/baselines/reference/controlFlowManyCallExpressionStatementsPerf.symbols
  tests/baselines/reference/controlFlowManyCallExpressionStatementsPerf.types
  tests/cases/compiler/controlFlowManyCallExpressionStatementsPerf.ts
Labels: Author: Team, For Milestone Bug

#41693 Fix getTypeFacts for pattern template literal types
  src/compiler/checker.ts
  tests/baselines/reference/templateLiteralTypesPatterns.errors.txt
  tests/baselines/reference/templateLiteralTypesPatterns.js
  tests/baselines/reference/templateLiteralTypesPatterns.symbols
  tests/baselines/reference/templateLiteralTypesPatterns.types
  tests/cases/conformance/types/literal/templateLiteralTypesPatterns.ts
Labels: Author: Team, For Milestone Bug

#41704 fix(41688): Provide correct intellisense completion/suggestion list after `infer` keyword
  src/harness/fourslashInterfaceImpl.ts
  src/services/completions.ts
  src/services/utilities.ts
  tests/cases/fourslash/completionListAtIdentifierDefinitionLocations_infers.ts
  tests/cases/fourslash/completionListInferKeyword.ts
Labels: For Milestone Bug

#41624 fix(41621): remove-unused-identifier codefix-all fails to remove ++
  src/services/codefixes/fixUnusedIdentifier.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_postfix_operator1.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_postfix_operator2.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_prefix_operator1.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_prefix_operator2.ts
Labels: For Milestone Bug

#41599 Improve uncalled function checks
  src/compiler/checker.ts
  tests/baselines/reference/truthinessCallExpressionCoercion1.errors.txt
  tests/baselines/reference/truthinessCallExpressionCoercion1.js
  tests/baselines/reference/truthinessCallExpressionCoercion1.symbols
  tests/baselines/reference/truthinessCallExpressionCoercion1.types
  tests/baselines/reference/truthinessCallExpressionCoercion2.errors.txt
  tests/baselines/reference/truthinessCallExpressionCoercion2.js
  tests/baselines/reference/truthinessCallExpressionCoercion2.symbols
  tests/baselines/reference/truthinessCallExpressionCoercion2.types
  tests/cases/compiler/truthinessCallExpressionCoercion1.ts
  tests/cases/compiler/truthinessCallExpressionCoercion2.ts
Labels: Author: Team, For Milestone Bug

#41589 Produce source maps for local typescriptServices build
  Gulpfile.js
  src/tsconfig-library-base.json
Labels: Author: Team, For Milestone Bug

#41307 Fix typos in comments
  tests/baselines/reference/commaOperatorOtherInvalidOperation.errors.txt
  tests/baselines/reference/commaOperatorOtherInvalidOperation.js
  tests/baselines/reference/commaOperatorOtherInvalidOperation.symbols
  tests/baselines/reference/commaOperatorOtherInvalidOperation.types
  tests/baselines/reference/commaOperatorOtherValidOperation.js
  tests/baselines/reference/commaOperatorOtherValidOperation.symbols
  tests/baselines/reference/commaOperatorOtherValidOperation.types
  tests/baselines/reference/commentsVarDecl.js
  tests/baselines/reference/commentsVarDecl.symbols
  tests/baselines/reference/commentsVarDecl.types
  tests/baselines/reference/switchStatements.errors.txt
  tests/baselines/reference/switchStatements.js
  tests/baselines/reference/switchStatements.symbols
  tests/baselines/reference/switchStatements.types
  tests/cases/compiler/commentsVarDecl.ts
  tests/cases/conformance/expressions/commaOperator/commaOperatorOtherInvalidOperation.ts
  tests/cases/conformance/expressions/commaOperator/commaOperatorOtherValidOperation.ts
  tests/cases/conformance/statements/switchStatements/switchStatements.ts
Labels: For Uncommitted Bug
