Repository microsoft/TypeScript, pull requests merged in 2020-05, with the labels that each got.

#38276 Fix jsdoc variadic type nodes not being remapped to equivalent TS in output
  src/compiler/checker.ts
  tests/baselines/reference/jsFileCompilationRestParamJsDocFunction.types
  tests/baselines/reference/jsdocParseDotDotDotInJSDocFunction.types
  tests/baselines/reference/jsdocParseStarEquals.types
  tests/baselines/reference/jsdocPrefixPostfixParsing.types
  tests/baselines/reference/jsdocRestParameter_es6.types
Labels: Author: Team

#38296 Fix incorrect line text computation to stop comment directive searching
  src/compiler/program.ts
  tests/baselines/reference/ts-expect-error.errors.txt
  tests/baselines/reference/ts-expect-error.js
  tests/baselines/reference/ts-expect-error.symbols
  tests/baselines/reference/ts-expect-error.types
  tests/cases/conformance/directives/ts-expect-error.ts
Labels: Author: Team

#38273 Harden node builder APIs to no longer return `undefined` for a node when `NodeBuilderFlags.IgnoreErrors` is provided
  src/compiler/checker.ts
  src/compiler/types.ts
  src/services/codefixes/convertToAsyncFunction.ts
  src/services/codefixes/fixAddMissingMember.ts
  src/services/codefixes/fixJSDocTypes.ts
  src/services/signatureHelp.ts
  src/services/symbolDisplay.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/signatureHelpForSignatureWithUnreachableType.ts
Labels: Author: Team

#38191 fix(31303): Return outlining spans for multiline descructured arguments
  src/services/outliningElementsCollector.ts
  tests/cases/fourslash/getOutliningForArrayDestructuring.ts
Labels: For Backlog Bug

#38179 Add outlining spans for the Tuple type
  src/services/outliningElementsCollector.ts
  tests/cases/fourslash/getOutliningForTupleType.ts
Labels: For Uncommitted Bug

#38155 fix(37703): Bad JSDoc comments leads to generate invalid declaration file
  src/compiler/checker.ts
  tests/baselines/reference/checkJsdocOptionalParamOrder.errors.txt
  tests/baselines/reference/checkJsdocOptionalParamOrder.js
  tests/baselines/reference/checkJsdocOptionalParamOrder.symbols
  tests/baselines/reference/checkJsdocOptionalParamOrder.types
  tests/baselines/reference/jsdocParseBackquotedParamName.errors.txt
  tests/cases/conformance/jsdoc/checkJsdocOptionalParamOrder.ts
Labels: For Backlog Bug

#37788 Updating dependencies
  package.json
Labels: Housekeeping

#37786 fix(36055): `prop in dict` does not report error if `prop` is union type such as `MyClass | string`
  src/compiler/checker.ts
  tests/baselines/reference/inOperatorWithInvalidOperands.errors.txt
  tests/baselines/reference/inOperatorWithInvalidOperands.js
  tests/baselines/reference/inOperatorWithInvalidOperands.symbols
  tests/baselines/reference/inOperatorWithInvalidOperands.types
  tests/baselines/reference/inOperatorWithValidOperands.js
  tests/baselines/reference/inOperatorWithValidOperands.symbols
  tests/baselines/reference/inOperatorWithValidOperands.types
  tests/cases/conformance/expressions/binaryOperators/inOperator/inOperatorWithInvalidOperands.ts
  tests/cases/conformance/expressions/binaryOperators/inOperator/inOperatorWithValidOperands.ts
Labels: For Backlog Bug

#38351 Fix regression in name resolution in parameter
  src/compiler/checker.ts
  tests/cases/conformance/functions/parameterInitializersBackwardReferencing.ts
Labels: Author: Team

#38228 Allowed comment directives to be multiline
  src/compiler/scanner.ts
  src/compiler/utilities.ts
  src/testRunner/unittests/incrementalParser.ts
  tests/baselines/reference/checkJsFiles_skipDiagnostics.errors.txt
  tests/baselines/reference/checkJsFiles_skipDiagnostics.symbols
  tests/baselines/reference/checkJsFiles_skipDiagnostics.types
  tests/baselines/reference/multiline.errors.txt
  tests/baselines/reference/multiline.js
  tests/baselines/reference/multiline.symbols
  tests/baselines/reference/multiline.types
  tests/baselines/reference/ts-expect-error.errors.txt
  tests/baselines/reference/ts-expect-error.js
  tests/baselines/reference/ts-expect-error.symbols
  tests/baselines/reference/ts-expect-error.types
  tests/cases/compiler/checkJsFiles_skipDiagnostics.ts
  tests/cases/conformance/directives/multiline.tsx
  tests/cases/conformance/directives/ts-expect-error.ts
Labels: For Milestone Bug

#37451 Add support of contextual quick info
  src/services/services.ts
  src/services/symbolDisplay.ts
  src/services/types.ts
  tests/cases/fourslash/commentsClassMembers.ts
  tests/cases/fourslash/quickInfoForGetterAndSetter.ts
Labels: For Backlog Bug

#29539 expose jsdoc factory
  src/compiler/factoryPublic.ts
  src/services/codefixes/inferFromUsage.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Uncommitted Bug

#37806 feat(37782): 'declare method' quick fix for adding a private method
  src/compiler/diagnosticMessages.json
  src/services/codefixes/fixAddMissingMember.ts
  src/services/codefixes/helpers.ts
  tests/cases/fourslash/codeFixAddMissingMember18_declarePrivateMethod.ts
  tests/cases/fourslash/codeFixAddMissingMember19_declarePrivateMethod.ts
  tests/cases/fourslash/codeFixUndeclaredMethod.ts
  tests/cases/fourslash/codeFixUndeclaredMethodFunctionArgs.ts
  tests/cases/fourslash/codeFixUndeclaredMethodObjectLiteralArgs.ts
Labels: For Uncommitted Bug

#33434 Unify logic in typeof narrowing
  src/compiler/checker.ts
  tests/baselines/reference/narrowingByTypeofInSwitch.js
  tests/baselines/reference/narrowingByTypeofInSwitch.symbols
  tests/baselines/reference/narrowingByTypeofInSwitch.types
  tests/cases/compiler/narrowingByTypeofInSwitch.ts
Labels: For Backlog Bug

#38377 moveToNewFile: handle namespace imports too
  src/services/refactors/moveToNewFile.ts
  tests/cases/fourslash/moveToNewFile_moveNamedImport.ts
  tests/cases/fourslash/moveToNewFile_moveNamespaceImport.ts
Labels: Author: Team

#38368 Fix js missing type arguments on existing nodes and jsdoc object literal declaration emit
  src/compiler/checker.ts
  tests/baselines/reference/exportNestedNamespaces.types
  tests/baselines/reference/jsDeclarationsClassStatic.js
  tests/baselines/reference/jsDeclarationsJSDocRedirectedLookups.js
  tests/baselines/reference/jsDeclarationsJSDocRedirectedLookups.symbols
  tests/baselines/reference/jsDeclarationsJSDocRedirectedLookups.types
  tests/baselines/reference/jsDeclarationsMissingGenerics.js
  tests/baselines/reference/jsDeclarationsMissingGenerics.symbols
  tests/baselines/reference/jsDeclarationsMissingGenerics.types
  tests/baselines/reference/jsDeclarationsNestedParams.js
  tests/baselines/reference/jsDeclarationsNestedParams.symbols
  tests/baselines/reference/jsDeclarationsNestedParams.types
  tests/baselines/reference/jsdocArrayObjectPromiseImplicitAny.types
  tests/baselines/reference/jsdocArrayObjectPromiseNoImplicitAny.types
  tests/baselines/reference/jsdocClassMissingTypeArguments.types
  tests/baselines/reference/jsdocParamTag2.types
  tests/baselines/reference/jsdocParamTagTypeLiteral.types
  tests/baselines/reference/jsdocTemplateConstructorFunction2.types
  tests/baselines/reference/jsdocTemplateTag.types
  tests/baselines/reference/jsdocTypeNongenericInstantiationAttempt.types
  tests/baselines/reference/jsdocTypeReferenceToValue.types
  tests/baselines/reference/moduleExportNestedNamespaces.types
  tests/baselines/reference/prototypePropertyAssignmentMergeWithInterfaceMethod.types
  tests/baselines/reference/typeFromPropertyAssignment35.types
  tests/baselines/reference/typeFromPropertyAssignment6.types
  tests/baselines/reference/varRequireFromJavascript.types
  tests/baselines/reference/varRequireFromTypescript.types
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsJSDocRedirectedLookups.ts
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsMissingGenerics.ts
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsNestedParams.ts
Labels: Author: Team

#38107 fix(38073): Extract to function refactoring generates invalid code for arrow function that references `this`
  src/services/refactors/extractSymbol.ts
  tests/cases/fourslash/extract-method38.ts
  tests/cases/fourslash/extract-method39.ts
Labels: For Backlog Bug

#37546 fix broken regex on "src/services/completions.ts#getCompletionData"
  src/services/completions.ts
Labels: For Uncommitted Bug

#38270 Improve assert message in binder
  src/compiler/binder.ts
Labels: Author: Team

#38403 Fix for jsdoc modifiers on constructor params
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/debug.ts
  src/compiler/factory.ts
  src/compiler/program.ts
  src/compiler/transformers/declarations.ts
  src/compiler/transformers/declarations/diagnostics.ts
  src/compiler/transformers/es2015.ts
  src/compiler/transformers/es2018.ts
  src/compiler/transformers/module/module.ts
  src/compiler/transformers/module/system.ts
  src/compiler/transformers/ts.ts
  src/compiler/transformers/utilities.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/compiler/utilitiesPublic.ts
  src/compiler/visitor.ts
  src/services/breakpoints.ts
  src/services/callHierarchy.ts
  src/services/codefixes/addMissingAsync.ts
  src/services/codefixes/addMissingAwait.ts
  src/services/codefixes/convertToMappedObjectType.ts
  src/services/codefixes/fixClassDoesntImplementInheritedAbstractMember.ts
  src/services/codefixes/fixClassIncorrectlyImplementsInterface.ts
  src/services/codefixes/fixStrictClassInitialization.ts
  src/services/codefixes/helpers.ts
  src/services/completions.ts
  src/services/findAllReferences.ts
  src/services/importTracker.ts
  src/services/navigationBar.ts
  src/services/refactors/convertExport.ts
  src/services/refactors/extractSymbol.ts
  src/services/refactors/generateGetAccessorAndSetAccessor.ts
  src/services/refactors/moveToNewFile.ts
  src/services/services.ts
  src/services/symbolDisplay.ts
  src/services/utilities.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/jsdocAccessibilityTagsDeclarations.js
  tests/baselines/reference/jsdocAccessibilityTagsDeclarations.symbols
  tests/baselines/reference/jsdocAccessibilityTagsDeclarations.types
  tests/baselines/reference/jsdocReadonlyDeclarations.js
  tests/baselines/reference/jsdocReadonlyDeclarations.symbols
  tests/baselines/reference/jsdocReadonlyDeclarations.types
  tests/baselines/reference/uniqueSymbolsDeclarationsInJs.js
  tests/baselines/reference/uniqueSymbolsDeclarationsInJs.symbols
  tests/baselines/reference/uniqueSymbolsDeclarationsInJs.types
  tests/baselines/reference/uniqueSymbolsDeclarationsInJsErrors.errors.txt
  tests/baselines/reference/uniqueSymbolsDeclarationsInJsErrors.js
  tests/baselines/reference/uniqueSymbolsDeclarationsInJsErrors.symbols
  tests/baselines/reference/uniqueSymbolsDeclarationsInJsErrors.types
  tests/cases/conformance/jsdoc/jsdocAccessibilityTagsDeclarations.ts
  tests/cases/conformance/jsdoc/jsdocReadonlyDeclarations.ts
  tests/cases/conformance/types/uniqueSymbol/uniqueSymbolsDeclarationsInJs.ts
  tests/cases/conformance/types/uniqueSymbol/uniqueSymbolsDeclarationsInJsErrors.ts
Labels: Author: Team

#38240 feat: Add outlining spans for object destructuring elements
  src/services/outliningElementsCollector.ts
  tests/cases/fourslash/getOutliningForObjectDestructuring.ts
Labels: For Uncommitted Bug

#38429 Fix detecting default project when file is part for more than one project but not part of default configured project (eg because its output of that projet)
  src/server/editorServices.ts
  src/testRunner/unittests/tsbuild/watchMode.ts
  src/testRunner/unittests/tsserver/configuredProjects.ts
  src/testRunner/unittests/tsserver/projectReferenceCompileOnSave.ts
  src/testRunner/unittests/tsserver/projectReferences.ts
Labels: Author: Team

#36543 fix(33836): VSCode - generate accessors fixup on readonly field removes modifier
  src/services/refactors/generateGetAccessorAndSetAccessor.ts
  tests/cases/fourslash/refactorConvertToGetAccessAndSetAccess14.ts
  tests/cases/fourslash/refactorConvertToGetAccessAndSetAccess33.ts
Labels: For Backlog Bug

#38577 Include unknown in spread prop override check
  src/compiler/checker.ts
  tests/baselines/reference/jsxPartialSpread.js
  tests/baselines/reference/jsxPartialSpread.symbols
  tests/baselines/reference/jsxPartialSpread.types
  tests/cases/compiler/jsxPartialSpread.tsx
Labels: Author: Team

#38508 Fix crash in JS declaration emit
  src/compiler/checker.ts
  tests/baselines/reference/jsDeclarationsClassLikeHeuristic.errors.txt
  tests/baselines/reference/jsDeclarationsClassLikeHeuristic.js
  tests/baselines/reference/jsDeclarationsClassLikeHeuristic.symbols
  tests/baselines/reference/jsDeclarationsClassLikeHeuristic.types
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsClassLikeHeuristic.ts
Labels: Author: Team

#38567 goToDefinition: find only the value if it's the RHS of an assignment
  src/services/goToDefinition.ts
  tests/cases/fourslash/goToDefinitionJsModuleExports.ts
  tests/cases/fourslash/goToDefinitionVariableAssignment.ts
  tests/cases/fourslash/goToDefinitionVariableAssignment1.ts
  tests/cases/fourslash/goToDefinitionVariableAssignment2.ts
  tests/cases/fourslash/goToDefinitionVariableAssignment3.ts
Labels: Author: Team

#38596 Make `processTaggedTemplateExpression` visit a returned node
  src/compiler/transformers/es2015.ts
  src/compiler/transformers/taggedTemplate.ts
  tests/baselines/reference/taggedTemplateStringsWithCurriedFunction.js
  tests/baselines/reference/taggedTemplateStringsWithCurriedFunction.symbols
  tests/baselines/reference/taggedTemplateStringsWithCurriedFunction.types
  tests/cases/compiler/taggedTemplateStringsWithCurriedFunction.ts
Labels: Author: Team

#38579 Ensure formatter can always get a newline character
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/services/formatting/formatting.ts
  src/services/formatting/rulesMap.ts
  src/services/services.ts
  src/services/types.ts
  src/services/utilities.ts
  src/testRunner/unittests/services/convertToAsyncFunction.ts
  src/testRunner/unittests/services/extract/helpers.ts
  src/testRunner/unittests/services/textChanges.ts
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/organizeImportsNoFormatOptions.ts
Labels: Author: Team

#38659 Remove mentions of runtests-browser in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Housekeeping

#38656 fix(33233): Code Folding on es5 object functions does not work (getOutliningSpans)
  src/services/outliningElementsCollector.ts
  tests/cases/fourslash/getOutliningForBlockComments.ts
  tests/cases/fourslash/getOutliningForSingleLineComments.ts
Labels: For Backlog Bug

#37912 fix: extract const in jsx
  src/services/refactors/extractSymbol.ts
  tests/cases/fourslash/extract-const4.ts
Labels: For Uncommitted Bug

#36084 Add d.ts for Intl.RelativeTimeFormat
  src/compiler/commandLineParser.ts
  src/lib/es2020.d.ts
  src/lib/es2020.intl.d.ts
  src/lib/libs.json
  src/testRunner/unittests/config/commandLineParsing.ts
  tests/baselines/reference/tsc/runWithoutArgs/initial-build/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
Labels: For Backlog Bug

#38498 make Atomics.notify last parameter optional
  src/lib/es2017.sharedmemory.d.ts
Labels: For Backlog Bug

#38425 Fix some JSDoc factory function return types
  src/compiler/factoryPublic.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Uncommitted Bug

#38600 fix(38299): Bug in the __rest helper function for numeric properties
  src/compiler/emitter.ts
  tests/baselines/reference/restElementWithNumberPropertyName.js
  tests/baselines/reference/restElementWithNumberPropertyName.symbols
  tests/baselines/reference/restElementWithNumberPropertyName.types
  tests/baselines/reference/restParameterWithBindingPattern3.js
  tests/cases/compiler/restElementWithNumberPropertyName.ts
Labels: For Milestone Bug

#38607 fix(38295): Duplicated object key in const not detected when the key is a number preceded by `-` or `+`
  src/compiler/utilities.ts
  tests/baselines/reference/duplicateObjectLiteralProperty_computedName.errors.txt
  tests/baselines/reference/duplicateObjectLiteralProperty_computedName.js
  tests/baselines/reference/duplicateObjectLiteralProperty_computedName.symbols
  tests/baselines/reference/duplicateObjectLiteralProperty_computedName.types
  tests/cases/compiler/duplicateObjectLiteralProperty_computedName.ts
Labels: For Backlog Bug

#37800 Better error message for accidental calls to get-accessors
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/accessorAccidentalCallDiagnostic.errors.txt
  tests/baselines/reference/accessorAccidentalCallDiagnostic.js
  tests/baselines/reference/accessorAccidentalCallDiagnostic.symbols
  tests/baselines/reference/accessorAccidentalCallDiagnostic.types
  tests/baselines/reference/instancePropertiesInheritedIntoClassType.errors.txt
  tests/baselines/reference/instancePropertyInClassType.errors.txt
  tests/cases/compiler/accessorAccidentalCallDiagnostic.ts
Labels: For Backlog Bug

#38631 fix(33286): Code folding fail for arrow function when param list has no parentheses
  src/services/outliningElementsCollector.ts
  tests/cases/fourslash/outliningSpansForFunction.ts
Labels: For Backlog Bug

#38481 fix(38463): No indexed access completions after Record<...>
  src/services/stringCompletions.ts
  tests/cases/fourslash/completionForStringLiteral14.ts
  tests/cases/fourslash/completionForStringLiteral15.ts
Labels: For Milestone Bug

#38712 Preserve module marker in es2015+ module emit for tool compatibility
  src/compiler/transformers/module/esnextAnd2015.ts
  tests/baselines/reference/asyncAwaitIsolatedModules_es2017.js
  tests/baselines/reference/asyncAwaitIsolatedModules_es6.js
  tests/baselines/reference/computedPropertyName.js
  tests/baselines/reference/decoratedClassFromExternalModule.js
  tests/baselines/reference/es6ExportAssignment.js
  tests/baselines/reference/es6ExportAssignment2.js
  tests/baselines/reference/es6ExportAssignment3.js
  tests/baselines/reference/es6ExportAssignment4.js
  tests/baselines/reference/es6ImportEqualsDeclaration.js
  tests/baselines/reference/es6ImportEqualsDeclaration2.js
  tests/baselines/reference/es6ImportEqualsExportModuleEs2015Error.js
  tests/baselines/reference/es6ImportNamedImportIdentifiersParsing.js
  tests/baselines/reference/es6ImportWithoutFromClauseNonInstantiatedModule.js
  tests/baselines/reference/es6modulekindWithES5Target10.js
  tests/baselines/reference/esnextmodulekindWithES5Target10.js
  tests/baselines/reference/exportAssignmentWithoutAllowSyntheticDefaultImportsError.js
  tests/baselines/reference/exportDefaultForNonInstantiatedModule.js
  tests/baselines/reference/importCallExpressionIncorrect2.js
  tests/baselines/reference/importMeta(module=esnext,target=es5).js
  tests/baselines/reference/importMeta(module=esnext,target=esnext).js
  tests/baselines/reference/importNonExportedMember6.js
  tests/baselines/reference/importNonExportedMember7.js
  tests/baselines/reference/instantiateContextualTypes.js
  tests/baselines/reference/isolatedModulesDontElideReExportStar.js
  tests/baselines/reference/potentiallyUncalledDecorators.js
  tests/baselines/reference/requireOfJsonFileWithModuleNodeResolutionEmitEs2015.js
  tests/baselines/reference/requireOfJsonFileWithModuleNodeResolutionEmitEsNext.js
  tests/baselines/reference/scannerUnicodeEscapeInKeyword2.js
  tests/baselines/reference/strictModeWordInImportDeclaration.js
  tests/baselines/reference/taggedTemplatesWithTypeArguments2.js
  tests/baselines/reference/tsxResolveExternalModuleExportsTypes.js
  tests/baselines/reference/umdGlobalAugmentationNoCrash.js
  tests/baselines/reference/umdNamespaceMergedWithGlobalAugmentationIsNotCircular.js
  tests/baselines/reference/unionAndIntersectionInference3.js
  tests/baselines/reference/unionTypeInference.js
Labels: Author: Team

#38415 Fix trancked es5 classes after new scope
  src/services/navigationBar.ts
  tests/cases/fourslash/navigationBarWithLocalVariables.ts
Labels: For Backlog Bug

#37894 Always error on property override accessor
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/services/codefixes/fixAddMissingMember.ts
  src/services/codefixes/fixPropertyOverrideAccessor.ts
  src/services/codefixes/generateAccessors.ts
  src/services/refactors/generateGetAccessorAndSetAccessor.ts
  src/services/tsconfig.json
  tests/baselines/reference/accessorsOverrideProperty6.errors.txt
  tests/baselines/reference/inheritanceMemberAccessorOverridingProperty.errors.txt
  tests/baselines/reference/inheritanceMemberPropertyOverridingAccessor.errors.txt
  tests/baselines/reference/tscWatch/programUpdates/updates-diagnostics-and-emit-when-useDefineForClassFields-changes.js
  tests/cases/fourslash/codeFixPropertyOverrideAccess.ts
  tests/cases/fourslash/codeFixPropertyOverrideAccess2.ts
  tests/cases/fourslash/codeFixPropertyOverrideAccess3.ts
  tests/cases/fourslash/codeFixPropertyOverrideAccess_all.ts
Labels: Author: Team, For Milestone Bug
