Repository microsoft/TypeScript, pull requests merged in 2020-09, with the labels that each got.

#40339 LEGO: Pull request from lego/hb_998_20200901061110451 to master
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#40186 Nested assignment to a require alias isn't a declaration
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/utilities.ts
  tests/baselines/reference/namespaceAssignmentToRequireAlias.errors.txt
  tests/baselines/reference/namespaceAssignmentToRequireAlias.js
  tests/baselines/reference/namespaceAssignmentToRequireAlias.symbols
  tests/baselines/reference/namespaceAssignmentToRequireAlias.types
  tests/cases/conformance/salsa/namespaceAssignmentToRequireAlias.ts
Labels: Author: Team, For Milestone Bug

#40249 Fix crash intersecting dynamic import w/esModuleInterop
  src/compiler/checker.ts
  tests/baselines/reference/intersectionsAndEmptyObjects.js
  tests/baselines/reference/intersectionsAndEmptyObjects.symbols
  tests/baselines/reference/intersectionsAndEmptyObjects.types
  tests/cases/conformance/types/intersection/intersectionsAndEmptyObjects.ts
Labels: Author: Team, For Milestone Bug

#40275 Checkjs implies allowjs
  src/compiler/program.ts
  src/compiler/utilities.ts
  src/harness/fourslashImpl.ts
  src/harness/harnessIO.ts
  src/server/project.ts
  src/server/typingsCache.ts
  tests/cases/conformance/salsa/inferringClassMembersFromAssignments2.ts
  tests/cases/conformance/salsa/moduleExportAlias4.ts
Labels: Author: Team, For Uncommitted Bug

#40348 Fix call hierarchy item serialization
  src/harness/client.ts
  src/server/session.ts
  tests/baselines/reference/callHierarchyContainerNameServer.callHierarchy.txt
  tests/cases/fourslash/server/callHierarchyContainerNameServer.ts
Labels: Author: Team, For Milestone Bug

#39505 fix(39410): Refacoring "Convert named export to default" removes function typeings
  src/services/refactors/convertExport.ts
  tests/cases/fourslash/refactorConvertExport_exportNodeKinds.ts
Labels: For Backlog Bug

#40308 Add support for customDescriptionGenerators (for compiler debugging)
  .vscode/launch.template.json
  src/compiler/debug.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/types.ts
Labels: Author: Team, For Uncommitted Bug

#39663 fix(31126): No completions for interface `extends` clause for members of nested namespaces
  src/services/completions.ts
  tests/cases/fourslash/completionListInNestedNamespaceName.ts
Labels: For Backlog Bug

#39817 Remove optionality for Promise resolve callback
  src/lib/es2015.promise.d.ts
  src/lib/es5.d.ts
  tests/baselines/reference/asyncAwaitNestedClasses_es5.types
  tests/baselines/reference/contextuallyTypeAsyncFunctionAwaitOperand.types
  tests/baselines/reference/contextuallyTypeAsyncFunctionReturnType.types
  tests/baselines/reference/defaultExportInAwaitExpression01.types
  tests/baselines/reference/defaultExportInAwaitExpression02.types
  tests/baselines/reference/inferenceLimit.types
  tests/baselines/reference/modularizeLibrary_NoErrorDuplicateLibOptions1.types
  tests/baselines/reference/modularizeLibrary_NoErrorDuplicateLibOptions2.types
  tests/baselines/reference/modularizeLibrary_TargetES5UsingES6Lib.types
  tests/baselines/reference/usePromiseFinally.types
Labels: Author: Team, For Milestone Bug

#40373 Mark spec files as archived
  Gulpfile.js
  doc/README.md
  doc/TypeScript Language Specification (Change Markup) - ARCHIVED.docx
  doc/TypeScript Language Specification (Change Markup) - ARCHIVED.pdf
  doc/TypeScript Language Specification - ARCHIVED.docx
  doc/TypeScript Language Specification - ARCHIVED.pdf
  doc/spec-ARCHIVED.md
Labels: Author: Team, For Uncommitted Bug

#38967 fix(lib/es2015): Remove `Reflect.enumerate(…)`
  src/lib/es2015.iterable.d.ts
  src/lib/es2015.proxy.d.ts
  tests/baselines/reference/mappedTypeRecursiveInference.types
  tests/baselines/reference/modularizeLibrary_NoErrorDuplicateLibOptions1.symbols
  tests/baselines/reference/modularizeLibrary_NoErrorDuplicateLibOptions2.symbols
  tests/baselines/reference/modularizeLibrary_TargetES5UsingES6Lib.symbols
  tests/baselines/reference/modularizeLibrary_TargetES6UsingES6Lib.symbols
  tests/baselines/reference/modularizeLibrary_UsingES5LibAndES6FeatureLibs.symbols
Labels: For Uncommitted Bug

#38994 Fixes stack overflow when exporting a lot in commonjs
  src/compiler/transformers/module/module.ts
  tests/baselines/reference/manyConstExports.js
  tests/baselines/reference/manyConstExports.symbols
  tests/baselines/reference/manyConstExports.types
  tests/cases/compiler/manyConstExports.ts
Labels: For Milestone Bug

#38939 Add CodeQL security scanning
  .github/codeql/codeql-configuration.yml
  .github/workflows/codeql.yml
Labels: For Uncommitted Bug, Housekeeping

#39697 fix(26141): String type autocomplete doesn't work with paren
  src/services/stringCompletions.ts
  tests/cases/fourslash/completionListStringParenthesizedExpression.ts
  tests/cases/fourslash/completionListStringParenthesizedType.ts
Labels: For Backlog Bug

#40347 Add optionalReplacementSpan to completions response
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/server/protocol.ts
  src/server/session.ts
  src/services/completions.ts
  src/services/stringCompletions.ts
  src/services/types.ts
  src/testRunner/unittests/tsserver/completions.ts
  src/testRunner/unittests/tsserver/metadataInResponse.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/completionsOptionalReplacementSpan1.ts
  tests/cases/fourslash/fourslash.ts
Labels: Author: Team, For Milestone Bug

#39963 fix(28516): Abstract methods should not allow `async` modifier
  src/compiler/checker.ts
  tests/baselines/reference/classAbstractMixedWithModifiers.errors.txt
  tests/baselines/reference/classAbstractMixedWithModifiers.js
  tests/baselines/reference/classAbstractMixedWithModifiers.symbols
  tests/baselines/reference/classAbstractMixedWithModifiers.types
  tests/cases/conformance/classes/classDeclarations/classAbstractKeyword/classAbstractMixedWithModifiers.ts
Labels: Breaking Change, For Backlog Bug

#40037 Better support class instances assigned to the module object for JS declarations
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/jsDeclarationsExportAssignedClassInstance1.js
  tests/baselines/reference/jsDeclarationsExportAssignedClassInstance1.symbols
  tests/baselines/reference/jsDeclarationsExportAssignedClassInstance1.types
  tests/baselines/reference/jsDeclarationsExportAssignedClassInstance2.js
  tests/baselines/reference/jsDeclarationsExportAssignedClassInstance2.symbols
  tests/baselines/reference/jsDeclarationsExportAssignedClassInstance2.types
  tests/baselines/reference/jsDeclarationsExportAssignedClassInstance3.js
  tests/baselines/reference/jsDeclarationsExportAssignedClassInstance3.symbols
  tests/baselines/reference/jsDeclarationsExportAssignedClassInstance3.types
  tests/baselines/reference/jsDeclarationsExportAssignedConstructorFunctionWithSub.errors.txt
  tests/baselines/reference/jsDeclarationsExportAssignedConstructorFunctionWithSub.types
  tests/baselines/reference/jsDeclarationsFunctionClassesCjsExportAssignment.types
  tests/baselines/reference/jsdocTypeReferenceToImportOfFunctionExpression.types
  tests/baselines/reference/moduleExportAssignment.types
  tests/baselines/reference/moduleExportAssignment5.types
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsExportAssignedClassInstance1.ts
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsExportAssignedClassInstance2.ts
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsExportAssignedClassInstance3.ts
Labels: Author: Team, For Milestone Bug

#39624 Add DockerFile for ChromeDevTools
  tests/cases/docker/chrome-devtools-frontend-next/Dockerfile
Labels: For Uncommitted Bug

#39978 Allow private symbols to be control flow narrowed
  src/compiler/binder.ts
  src/compiler/checker.ts
  tests/baselines/reference/controlFlowPrivateClassField.js
  tests/baselines/reference/controlFlowPrivateClassField.symbols
  tests/baselines/reference/controlFlowPrivateClassField.types
  tests/cases/compiler/controlFlowPrivateClassField.ts
Labels: Author: Team, For Milestone Bug

#40165 Add full stops in diagnostic messages
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/classImplementsClass6.errors.txt
  tests/baselines/reference/classSideInheritance1.errors.txt
  tests/baselines/reference/classStaticPropertyAccess.errors.txt
  tests/baselines/reference/cloduleTest2.errors.txt
  tests/baselines/reference/conditionalOperatorConditionIsObjectType.errors.txt
  tests/baselines/reference/importCallExpressionWithTypeArgument.errors.txt
  tests/baselines/reference/logicalAndOperatorStrictMode.errors.txt
  tests/baselines/reference/logicalAndOperatorWithEveryType.errors.txt
  tests/baselines/reference/logicalOrOperatorWithEveryType.errors.txt
  tests/baselines/reference/privateNameES5Ban(target=es3).errors.txt
  tests/baselines/reference/privateNameES5Ban(target=es5).errors.txt
  tests/baselines/reference/privateNameFieldsESNext.errors.txt
  tests/baselines/reference/privateNamesAndStaticFields.errors.txt
  tests/baselines/reference/privateNamesAndStaticMethods.errors.txt
  tests/baselines/reference/privateNamesConstructorChain-1.errors.txt
  tests/baselines/reference/privateNamesConstructorChain-2.errors.txt
  tests/baselines/reference/privateNamesInNestedClasses-2.errors.txt
  tests/baselines/reference/privateNamesIncompatibleModifiers.errors.txt
  tests/baselines/reference/privateNamesNotAllowedAsParameters.errors.txt
  tests/baselines/reference/privateNamesUnique-3.errors.txt
  tests/baselines/reference/requireOfJsonFileWithoutResolveJsonModule.errors.txt
  tests/baselines/reference/staticMemberExportAccess.errors.txt
  tests/baselines/reference/staticOffOfInstance1.errors.txt
  tests/baselines/reference/staticOffOfInstance2.errors.txt
  tests/baselines/reference/staticPropertyNotInClassType.errors.txt
  tests/baselines/reference/staticVisibility2.errors.txt
  tests/baselines/reference/superAccess.errors.txt
  tests/baselines/reference/superAccess2.errors.txt
  tests/baselines/reference/superPropertyAccess2.errors.txt
  tests/baselines/reference/thisInOuterClassBody.errors.txt
  tests/baselines/reference/tscWatch/programUpdates/updates-moduleResolution-when-resolveJsonModule-changes.js
  tests/baselines/reference/typePredicateInLoop.errors.txt
  tests/baselines/reference/typeofClass.errors.txt
  tests/baselines/reference/unusedTypeParameters_templateTag2.errors.txt
Labels: For Backlog Bug

#40407 Remove Language specification link from README
  README.md
Labels: For Uncommitted Bug

#40254 Consistently error when rest element isn't last in tuple type
  src/compiler/checker.ts
  tests/baselines/reference/variadicTuples1.errors.txt
  tests/baselines/reference/variadicTuples1.js
  tests/baselines/reference/variadicTuples1.symbols
  tests/baselines/reference/variadicTuples1.types
  tests/cases/conformance/types/tuple/variadicTuples1.ts
Labels: For Milestone Bug

#40293 Add errors when providing type arguments for intrinsic JSX tags
  src/compiler/checker.ts
  tests/baselines/reference/jsxIntrinsicElementsTypeArgumentErrors.errors.txt
  tests/baselines/reference/jsxIntrinsicElementsTypeArgumentErrors.js
  tests/baselines/reference/jsxIntrinsicElementsTypeArgumentErrors.symbols
  tests/baselines/reference/jsxIntrinsicElementsTypeArgumentErrors.types
  tests/cases/compiler/jsxIntrinsicElementsTypeArgumentErrors.tsx
Labels: Author: Team, For Uncommitted Bug

#40199 Remove trailing space from Gulpfile.js comment
  Gulpfile.js
Labels: For Uncommitted Bug, Housekeeping

#39258 Remove assignability cases in getNarrowedType + an isArray improvement for readonly arrays
  src/compiler/checker.ts
  src/lib/es5.d.ts
  tests/baselines/reference/consistentUnionSubtypeReduction.js
  tests/baselines/reference/consistentUnionSubtypeReduction.symbols
  tests/baselines/reference/consistentUnionSubtypeReduction.types
  tests/baselines/reference/declarationsWithRecursiveInternalTypesProduceUniqueTypeParams.types
  tests/baselines/reference/fixSignatureCaching.types
  tests/baselines/reference/instanceOfAssignability.types
  tests/baselines/reference/isArray.types
  tests/baselines/reference/literalFreshnessPropagationOnNarrowing.types
  tests/baselines/reference/malformedTags.types
  tests/baselines/reference/noIterationTypeErrorsInCFA.types
  tests/baselines/reference/parserharness.types
  tests/baselines/reference/partiallyDiscriminantedUnions.types
  tests/baselines/reference/spreadBooleanRespectsFreshness.types
  tests/baselines/reference/typeGuardIntersectionTypes.symbols
  tests/baselines/reference/typeGuardIntersectionTypes.types
  tests/baselines/reference/typeGuardsWithInstanceOf.errors.txt
  tests/baselines/reference/typeGuardsWithInstanceOf.js
  tests/baselines/reference/typeGuardsWithInstanceOf.symbols
  tests/baselines/reference/typeGuardsWithInstanceOf.types
  tests/cases/compiler/consistentUnionSubtypeReduction.ts
  tests/cases/conformance/expressions/typeGuards/typeGuardsWithInstanceOf.ts
Labels: Author: Team, For Milestone Bug

#40240 fix(40222): Uncaught exception in "catch" type annotation with destructuring
  src/compiler/checker.ts
  tests/baselines/reference/catchClauseWithTypeAnnotation.errors.txt
  tests/baselines/reference/catchClauseWithTypeAnnotation.js
  tests/baselines/reference/catchClauseWithTypeAnnotation.symbols
  tests/baselines/reference/catchClauseWithTypeAnnotation.types
  tests/cases/conformance/statements/tryStatements/catchClauseWithTypeAnnotation.ts
Labels: For Uncommitted Bug

#40191 fix(40150): "Convert to async function" refactor generates invalid code with a function returning Promise<function>
  src/services/codefixes/convertToAsyncFunction.ts
  src/testRunner/unittests/services/convertToAsyncFunction.ts
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_callbackArgument.ts
Labels: For Backlog Bug

#40226 feat(25770): Bad error message for type used as index / add Quick Fix
  src/compiler/diagnosticMessages.json
  src/services/codefixes/convertLiteralTypeToMappedType.ts
  src/services/tsconfig.json
  tests/cases/fourslash/convertLiteralTypeToMappedType1.ts
  tests/cases/fourslash/convertLiteralTypeToMappedType2.ts
  tests/cases/fourslash/convertLiteralTypeToMappedType3.ts
Labels: For Uncommitted Bug

#40299 fix(39676): Default code action for unused function parameter (6133) in non-final position should not delete
  src/services/codefixes/fixUnusedIdentifier.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_all_delete.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_parameter_callback1.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_parameter_callback2.ts
Labels: For Milestone Bug

#39760 Add see tag support
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/factory/nodeTests.ts
  src/compiler/parser.ts
  src/compiler/types.ts
  src/services/utilities.ts
  src/testRunner/unittests/jsDocParsing.ts
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.@link tags.json
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/seeTag1.js
  tests/baselines/reference/seeTag1.symbols
  tests/baselines/reference/seeTag1.types
  tests/baselines/reference/seeTag2.js
  tests/baselines/reference/seeTag2.symbols
  tests/baselines/reference/seeTag2.types
  tests/cases/conformance/jsdoc/seeTag1.ts
  tests/cases/conformance/jsdoc/seeTag2.ts
  tests/cases/fourslash/codeFixInferFromUsageExistingJSDoc.ts
  tests/cases/fourslash/jsDocSee1.ts
  tests/cases/fourslash/jsDocSee2.ts
  tests/cases/fourslash/jsDocSee3.ts
  tests/cases/fourslash/jsDocSee4.ts
  tests/cases/fourslash/jsDocSee_rename1.ts
Labels: For Uncommitted Bug

#40424 fix(40322): bad completions for string literal type as indexed access type object
  src/services/stringCompletions.ts
  tests/cases/fourslash/completionListsStringLiteralTypeAsIndexedAccessTypeObject.ts
Labels: For Backlog Bug

#40336 Template literal types and mapped type 'as' clauses
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/emitter.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/parser.ts
  src/compiler/scanner.ts
  src/compiler/types.ts
  src/compiler/visitorPublic.ts
  src/services/codefixes/convertLiteralTypeToMappedType.ts
  src/services/codefixes/convertToMappedObjectType.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/complicatedIndexesOfIntersectionsAreInferencable.types
  tests/baselines/reference/keyofAndIndexedAccess.types
  tests/baselines/reference/lateBoundConstraintTypeChecksCorrectly.types
  tests/baselines/reference/mappedTypeAsClauses.js
  tests/baselines/reference/mappedTypeAsClauses.symbols
  tests/baselines/reference/mappedTypeAsClauses.types
  tests/baselines/reference/mappedTypesArraysTuples.types
  tests/baselines/reference/objectLiteralExcessProperties.errors.txt
  tests/baselines/reference/objectLiteralExcessProperties.types
  tests/baselines/reference/privatePropertyInUnion.types
  tests/baselines/reference/stringLiteralTypesInUnionTypes01.types
  tests/baselines/reference/stringLiteralTypesInUnionTypes03.types
  tests/baselines/reference/templateLiteralTypes1.errors.txt
  tests/baselines/reference/templateLiteralTypes1.js
  tests/baselines/reference/templateLiteralTypes1.symbols
  tests/baselines/reference/templateLiteralTypes1.types
  tests/baselines/reference/templateStringInFunctionParameterType.errors.txt
  tests/baselines/reference/templateStringInFunctionParameterType.js
  tests/baselines/reference/templateStringInFunctionParameterType.symbols
  tests/baselines/reference/templateStringInFunctionParameterType.types
  tests/baselines/reference/templateStringInFunctionParameterTypeES6.errors.txt
  tests/baselines/reference/templateStringInFunctionParameterTypeES6.js
  tests/baselines/reference/templateStringInFunctionParameterTypeES6.symbols
  tests/baselines/reference/templateStringInFunctionParameterTypeES6.types
  tests/baselines/reference/typeAliases.types
  tests/baselines/reference/unionWithIndexSignature.types
  tests/cases/conformance/types/literal/templateLiteralTypes1.ts
  tests/cases/conformance/types/mapped/mappedTypeAsClauses.ts
Labels: For Uncommitted Bug

#40458 Fix see tag quickinfo
  src/services/jsDoc.ts
  tests/baselines/reference/quickInfoJsDocTags.baseline
  tests/cases/fourslash/quickInfoJsDocTags.ts
Labels: Author: Team, For Milestone Bug

#40456 Fix JS declaration emit for acessors in a class/interface merge
  src/compiler/checker.ts
  tests/baselines/reference/jsDeclarationsClassAccessor.js
  tests/baselines/reference/jsDeclarationsClassAccessor.symbols
  tests/baselines/reference/jsDeclarationsClassAccessor.types
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsClassAccessor.ts
Labels: Author: Team, For Milestone Bug

#40228 Alias for `module.exports.x = x`
  src/compiler/binder.ts
  src/compiler/types.ts
  tests/baselines/reference/commonJSImportClassExpression.js
  tests/baselines/reference/commonJSImportClassExpression.symbols
  tests/baselines/reference/commonJSImportClassExpression.types
  tests/baselines/reference/commonJSImportClassTypeReference.js
  tests/baselines/reference/commonJSImportClassTypeReference.symbols
  tests/baselines/reference/commonJSImportClassTypeReference.types
  tests/baselines/reference/commonJSImportNestedClassTypeReference.js
  tests/baselines/reference/commonJSImportNestedClassTypeReference.symbols
  tests/baselines/reference/commonJSImportNestedClassTypeReference.types
  tests/baselines/reference/exportNestedNamespaces.symbols
  tests/baselines/reference/exportNestedNamespaces.types
  tests/baselines/reference/findAllRefsCommonJsRequire2.baseline.jsonc
  tests/baselines/reference/jsDeclarationsExportDoubleAssignmentInClosure.js
  tests/baselines/reference/jsDeclarationsExportDoubleAssignmentInClosure.symbols
  tests/baselines/reference/jsDeclarationsExportDoubleAssignmentInClosure.types
  tests/baselines/reference/jsDeclarationsFunctionsCjs.js
  tests/baselines/reference/jsDeclarationsImportAliasExposedWithinNamespaceCjs.errors.txt
  tests/baselines/reference/jsDeclarationsImportAliasExposedWithinNamespaceCjs.js
  tests/baselines/reference/jsDeclarationsImportAliasExposedWithinNamespaceCjs.types
  tests/baselines/reference/jsdocImportTypeReferenceToClassAlias.types
  tests/baselines/reference/jsdocTypeFromChainedAssignment3.symbols
  tests/baselines/reference/jsdocTypeFromChainedAssignment3.types
  tests/baselines/reference/lateBoundAssignmentDeclarationSupport4.types
  tests/baselines/reference/lateBoundAssignmentDeclarationSupport5.types
  tests/baselines/reference/lateBoundAssignmentDeclarationSupport6.types
  tests/baselines/reference/lateBoundAssignmentDeclarationSupport7.symbols
  tests/baselines/reference/lateBoundAssignmentDeclarationSupport7.types
  tests/baselines/reference/moduleExportAlias4.symbols
  tests/baselines/reference/moduleExportAlias4.types
  tests/baselines/reference/moduleExportNestedNamespaces.symbols
  tests/baselines/reference/moduleExportNestedNamespaces.types
  tests/baselines/reference/typedefCrossModule2.errors.txt
  tests/baselines/reference/typedefCrossModule2.symbols
  tests/baselines/reference/typedefCrossModule2.types
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsExportDoubleAssignmentInClosure.ts
  tests/cases/conformance/salsa/commonJSImportClassExpression.ts
  tests/cases/conformance/salsa/commonJSImportClassTypeReference.ts
  tests/cases/conformance/salsa/commonJSImportNestedClassTypeReference.ts
  tests/cases/fourslash/findAllRefsClassExpression2.ts
  tests/cases/fourslash/findAllRefs_importType_js.ts
  tests/cases/fourslash/goToDefinitionImportedNames10.ts
  tests/cases/fourslash/server/completionEntryDetailAcrossFiles01.ts
  tests/cases/fourslash/server/completionEntryDetailAcrossFiles02.ts
  tests/cases/fourslash/syntheticImportFromBabelGeneratedFile1.ts
  tests/cases/fourslash/syntheticImportFromBabelGeneratedFile2.ts
Labels: Author: Team, For Milestone Bug

#40245 Retains trailing comments in a logical manner in extract type
  src/services/refactors/extractType.ts
  src/services/textChanges.ts
  tests/cases/fourslash/typeExtractionDoesNotDuplicateTrailingComment.ts
Labels: Author: Team, For Milestone Bug

#40063 Trace key operations
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  src/compiler/emitter.ts
  src/compiler/parser.ts
  src/compiler/program.ts
  src/compiler/tracing.ts
  src/compiler/transformer.ts
  src/compiler/tsbuildPublic.ts
  src/compiler/tsconfig.json
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/executeCommandLine/executeCommandLine.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/showConfig/Shows tsconfig for single option/generateTrace/tsconfig.json
Labels: For Uncommitted Bug

#40188 Use ad-hoc code for nested destructuring in require
  src/compiler/utilities.ts
  tests/baselines/reference/nestedDestructuringOfRequire.errors.txt
  tests/baselines/reference/nestedDestructuringOfRequire.js
  tests/baselines/reference/nestedDestructuringOfRequire.symbols
  tests/baselines/reference/nestedDestructuringOfRequire.types
  tests/cases/conformance/salsa/nestedDestructuringOfRequire.ts
Labels: Author: Team, For Milestone Bug

#39541 Add lib es2020.sharedmemory
  src/compiler/commandLineParser.ts
  src/lib/es2020.d.ts
  src/lib/es2020.sharedmemory.d.ts
  src/lib/libs.json
  src/testRunner/unittests/config/commandLineParsing.ts
  tests/baselines/reference/tsc/runWithoutArgs/initial-build/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
Labels: For Milestone Bug

#40350 A union including non-iterable types is not iterable
  src/compiler/checker.ts
  tests/baselines/reference/destructuringArrayBindingPatternAndAssignment4.errors.txt
  tests/baselines/reference/destructuringArrayBindingPatternAndAssignment4.js
  tests/baselines/reference/destructuringArrayBindingPatternAndAssignment4.symbols
  tests/baselines/reference/destructuringArrayBindingPatternAndAssignment4.types
  tests/baselines/reference/generatorReturnTypeIndirectReferenceToGlobalType.js
  tests/baselines/reference/generatorReturnTypeIndirectReferenceToGlobalType.symbols
  tests/baselines/reference/generatorReturnTypeIndirectReferenceToGlobalType.types
  tests/baselines/reference/generatorYieldContextualType.types
  tests/baselines/reference/types.asyncGenerators.es2018.2.errors.txt
  tests/cases/conformance/es6/destructuring/destructuringArrayBindingPatternAndAssignment4.ts
  tests/cases/conformance/generators/generatorReturnTypeIndirectReferenceToGlobalType.ts
Labels: Author: Team, For Milestone Bug

#39199 Add emit support for jsx/jsxs experimental jsx runtime api
  src/compiler/checker.ts
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  src/compiler/parser.ts
  src/compiler/program.ts
  src/compiler/transformer.ts
  src/compiler/transformers/jsx.ts
  src/compiler/transformers/module/module.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/testRunner/unittests/config/commandLineParsing.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/jsxJsxsCjsTransformCustomImport(jsx=react-jsx).js
  tests/baselines/reference/jsxJsxsCjsTransformCustomImport(jsx=react-jsx).symbols
  tests/baselines/reference/jsxJsxsCjsTransformCustomImport(jsx=react-jsx).types
  tests/baselines/reference/jsxJsxsCjsTransformCustomImport(jsx=react-jsxdev).js
  tests/baselines/reference/jsxJsxsCjsTransformCustomImport(jsx=react-jsxdev).symbols
  tests/baselines/reference/jsxJsxsCjsTransformCustomImport(jsx=react-jsxdev).types
  tests/baselines/reference/jsxJsxsCjsTransformCustomImportPragma(jsx=react-jsx).js
  tests/baselines/reference/jsxJsxsCjsTransformCustomImportPragma(jsx=react-jsx).symbols
  tests/baselines/reference/jsxJsxsCjsTransformCustomImportPragma(jsx=react-jsx).types
  tests/baselines/reference/jsxJsxsCjsTransformCustomImportPragma(jsx=react-jsxdev).js
  tests/baselines/reference/jsxJsxsCjsTransformCustomImportPragma(jsx=react-jsxdev).symbols
  tests/baselines/reference/jsxJsxsCjsTransformCustomImportPragma(jsx=react-jsxdev).types
  tests/baselines/reference/jsxJsxsCjsTransformSubstitutesNames(jsx=react-jsx).js
  tests/baselines/reference/jsxJsxsCjsTransformSubstitutesNames(jsx=react-jsx).symbols
  tests/baselines/reference/jsxJsxsCjsTransformSubstitutesNames(jsx=react-jsx).types
  tests/baselines/reference/jsxJsxsCjsTransformSubstitutesNames(jsx=react-jsxdev).js
  tests/baselines/reference/jsxJsxsCjsTransformSubstitutesNames(jsx=react-jsxdev).symbols
  tests/baselines/reference/jsxJsxsCjsTransformSubstitutesNames(jsx=react-jsxdev).types
  tests/baselines/reference/jsxJsxsCjsTransformSubstitutesNamesFragment(jsx=react-jsx).js
  tests/baselines/reference/jsxJsxsCjsTransformSubstitutesNamesFragment(jsx=react-jsx).symbols
  tests/baselines/reference/jsxJsxsCjsTransformSubstitutesNamesFragment(jsx=react-jsx).types
  tests/baselines/reference/jsxJsxsCjsTransformSubstitutesNamesFragment(jsx=react-jsxdev).js
  tests/baselines/reference/jsxJsxsCjsTransformSubstitutesNamesFragment(jsx=react-jsxdev).symbols
  tests/baselines/reference/jsxJsxsCjsTransformSubstitutesNamesFragment(jsx=react-jsxdev).types
  tests/baselines/reference/showConfig/Shows tsconfig for single option/jsxImportSource/tsconfig.json
  tests/cases/conformance/jsx/jsxs/jsxJsxsCjsTransformCustomImport.tsx
  tests/cases/conformance/jsx/jsxs/jsxJsxsCjsTransformCustomImportPragma.tsx
  tests/cases/conformance/jsx/jsxs/jsxJsxsCjsTransformSubstitutesNames.tsx
  tests/cases/conformance/jsx/jsxs/jsxJsxsCjsTransformSubstitutesNamesFragment.tsx
Labels: Author: Team, Experiment, For Milestone Bug

#39560 --noUncheckedIndexedAccess
  src/compiler/checker.ts
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  src/compiler/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/noUncheckedIndexedAccess.errors.txt
  tests/baselines/reference/noUncheckedIndexedAccess.js
  tests/baselines/reference/noUncheckedIndexedAccess.symbols
  tests/baselines/reference/noUncheckedIndexedAccess.types
  tests/baselines/reference/noUncheckedIndexedAccessDestructuring.errors.txt
  tests/baselines/reference/noUncheckedIndexedAccessDestructuring.js
  tests/baselines/reference/noUncheckedIndexedAccessDestructuring.symbols
  tests/baselines/reference/noUncheckedIndexedAccessDestructuring.types
  tests/baselines/reference/showConfig/Shows tsconfig for single option/noUncheckedIndexedAccess/tsconfig.json
  tests/baselines/reference/tsConfig/Default initialized TSConfig/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with advanced options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with boolean value compiler options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with enum value compiler options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with files options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with incorrect compiler option value/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with incorrect compiler option/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with list compiler options with enum value/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with list compiler options/tsconfig.json
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/declarationDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/when-outDir-and-declarationDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/when-outDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/with-outFile.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/without-outDir-or-outFile-is-specified-with-declaration-enabled.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/without-outDir-or-outFile-is-specified.js
  tests/cases/conformance/pedantic/noUncheckedIndexedAccess.ts
  tests/cases/conformance/pedantic/noUncheckedIndexedAccessDestructuring.ts
Labels: Author: Team, For Uncommitted Bug

#40428 feat(14751): Completions on class: put statics first
  src/services/completions.ts
  src/services/jsDoc.ts
  src/services/stringCompletions.ts
  src/testRunner/unittests/tsserver/metadataInResponse.ts
  tests/cases/fourslash/cloduleAsBaseClass.ts
  tests/cases/fourslash/cloduleAsBaseClass2.ts
  tests/cases/fourslash/cloduleTypeOf1.ts
  tests/cases/fourslash/commentsClassMembers.ts
  tests/cases/fourslash/completionListCladule.ts
  tests/cases/fourslash/completionListClassMembers.ts
  tests/cases/fourslash/completionListErrorRecovery.ts
  tests/cases/fourslash/completionListInExtendsClause.ts
  tests/cases/fourslash/completionListOnAliases2.ts
  tests/cases/fourslash/completionListStaticMembers.ts
  tests/cases/fourslash/completionListStaticProtectedMembers.ts
  tests/cases/fourslash/completionListStaticProtectedMembers2.ts
  tests/cases/fourslash/completionListStaticProtectedMembers3.ts
  tests/cases/fourslash/completionListStaticProtectedMembers4.ts
  tests/cases/fourslash/completionListsThroughTransitiveBaseClasses.ts
  tests/cases/fourslash/completionsNamespaceMergedWithClass.ts
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/jsdocTypedefTagTypeExpressionCompletion.ts
  tests/cases/fourslash/memberListErrorRecovery.ts
  tests/cases/fourslash/multiModuleClodule1.ts
Labels: For Backlog Bug

#40295 Don't crash when observing invalid 'export' in object literal
  src/services/documentHighlights.ts
  tests/cases/fourslash/exportInObjectLiteral.ts
Labels: Author: Team, For Milestone Bug

#40498 Properly check types in template literal placeholders
  src/compiler/checker.ts
  tests/baselines/reference/templateLiteralTypes1.errors.txt
  tests/baselines/reference/templateLiteralTypes1.js
  tests/baselines/reference/templateLiteralTypes1.symbols
  tests/baselines/reference/templateLiteralTypes1.types
  tests/cases/conformance/types/literal/templateLiteralTypes1.ts
Labels: For Uncommitted Bug

#40514 Support element access aliases: exports["x"] = x
  src/compiler/checker.ts
  tests/baselines/reference/moduleExportAliasElementAccessExpression.symbols
  tests/baselines/reference/moduleExportAliasElementAccessExpression.types
  tests/cases/conformance/salsa/moduleExportAliasElementAccessExpression.ts
Labels: Author: Team, For Uncommitted Bug

#40095 Added zero-padding to timestamp output
  src/compiler/core.ts
  src/jsTyping/shared.ts
Labels: For Backlog Bug

#40518 Consistent inferences when inferring to template literal type
  src/compiler/checker.ts
  tests/baselines/reference/templateLiteralTypes1.errors.txt
  tests/baselines/reference/templateLiteralTypes1.js
  tests/baselines/reference/templateLiteralTypes1.symbols
  tests/baselines/reference/templateLiteralTypes1.types
  tests/cases/conformance/types/literal/templateLiteralTypes1.ts
Labels: For Uncommitted Bug

#40526 Remove technically unnecessary 'module' option from 'harness' config.
  src/harness/tsconfig.json
Labels: For Uncommitted Bug

#40541 Fix incorrect name of index signature flag in implementation
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/noUncheckedIndexedAccess.errors.txt
  tests/baselines/reference/noUncheckedIndexedAccess.types
  tests/baselines/reference/noUncheckedIndexedAccessDestructuring.errors.txt
  tests/baselines/reference/noUncheckedIndexedAccessDestructuring.types
Labels: Author: Team, For Uncommitted Bug

#40547 LEGO: Pull request from lego/hb_998_20200914181051933 to master
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#40477 Issue a diagnostic when the node builder performs truncation despite the `NoTruncation` flag being set
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/transformers/declarations.ts
  src/compiler/types.ts
  tests/baselines/reference/hugeDeclarationOutputGetsTruncatedWithError.errors.txt
  tests/baselines/reference/hugeDeclarationOutputGetsTruncatedWithError.js
  tests/baselines/reference/hugeDeclarationOutputGetsTruncatedWithError.symbols
  tests/baselines/reference/hugeDeclarationOutputGetsTruncatedWithError.types
  tests/cases/compiler/hugeDeclarationOutputGetsTruncatedWithError.ts
Labels: Author: Team, For Milestone Bug

#40306 Move to new file doesn't maintain prologues directives
  src/compiler/core.ts
  src/services/refactors/moveToNewFile.ts
  tests/cases/fourslash/moveToNewFile_prologueDirectives1.ts
  tests/cases/fourslash/moveToNewFile_prologueDirectives2.ts
  tests/cases/fourslash/moveToNewFile_prologueDirectives3.ts
  tests/cases/fourslash/moveToNewFile_prologueDirectives4.ts
  tests/cases/fourslash/moveToNewFile_prologueDirectives5.ts
  tests/cases/fourslash/moveToNewFile_prologueDirectives6.ts
  tests/cases/fourslash/moveToNewFile_prologueDirectives7.ts
Labels: For Uncommitted Bug

#40545 Fix error on duplicate commonjs exports
  src/compiler/binder.ts
  src/compiler/checker.ts
  tests/baselines/reference/moduleExportAliasElementAccessExpression.js
  tests/baselines/reference/moduleExportAliasElementAccessExpression.symbols
  tests/baselines/reference/moduleExportAliasElementAccessExpression.types
  tests/baselines/reference/moduleExportDuplicateAlias.errors.txt
  tests/baselines/reference/moduleExportDuplicateAlias.js
  tests/baselines/reference/moduleExportDuplicateAlias.symbols
  tests/baselines/reference/moduleExportDuplicateAlias.types
  tests/cases/conformance/salsa/moduleExportAliasElementAccessExpression.ts
  tests/cases/conformance/salsa/moduleExportDuplicateAlias.ts
Labels: Author: Team, Breaking Change, For Uncommitted Bug

#40546 Support auto-import from paths alias without baseUrl
  src/compiler/moduleNameResolver.ts
  src/compiler/moduleSpecifiers.ts
  src/compiler/utilities.ts
  tests/cases/fourslash/importNameCodeFix_pathsWithoutBaseUrl.ts
Labels: Author: Team, For Uncommitted Bug

#40558 Add quick fix to add 'void' to Promise resolved without value
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/harness/fourslashImpl.ts
  src/services/codefixes/fixAddVoidToPromise.ts
  src/services/tsconfig.json
  tests/cases/fourslash/codeFixAddVoidToPromise.1.ts
  tests/cases/fourslash/codeFixAddVoidToPromise.2.ts
  tests/cases/fourslash/codeFixAddVoidToPromise.3.ts
  tests/cases/fourslash/codeFixAddVoidToPromise.4.ts
  tests/cases/fourslash/codeFixAddVoidToPromise.5.ts
  tests/cases/fourslash/codeFixAddVoidToPromiseJS.1.ts
  tests/cases/fourslash/codeFixAddVoidToPromiseJS.2.ts
  tests/cases/fourslash/codeFixAddVoidToPromiseJS.3.ts
  tests/cases/fourslash/codeFixAddVoidToPromiseJS.4.ts
  tests/cases/fourslash/codeFixAddVoidToPromiseJS.5.ts
  tests/cases/fourslash/codeFixAddVoidToPromiseJS_all.ts
  tests/cases/fourslash/codeFixAddVoidToPromise_all.ts
  tests/cases/fourslash/codeFixClassImplementInterfaceComputedPropertyNameWellKnownSymbols.ts
  tests/cases/fourslash/incrementalParsingDynamicImport1.ts
  tests/cases/fourslash/incrementalParsingDynamicImport3.ts
Labels: Author: Team, For Uncommitted Bug

#40556 Use unexpanded parameter list in serialization when the expanded list…
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitTupleRestSignatureLeadingVariadic.js
  tests/baselines/reference/declarationEmitTupleRestSignatureLeadingVariadic.symbols
  tests/baselines/reference/declarationEmitTupleRestSignatureLeadingVariadic.types
  tests/baselines/reference/variadicTuples1.types
  tests/cases/compiler/declarationEmitTupleRestSignatureLeadingVariadic.ts
Labels: Author: Team, For Milestone Bug

#40444 Set stackTraceLimit to 0 in fileSystemEntryExists
  src/compiler/sys.ts
Labels: For Uncommitted Bug

#40606 Fix missing renamed compiler flags
  src/compiler/checker.ts
  tests/baselines/reference/noUncheckedIndexedAccess.errors.txt
  tests/baselines/reference/noUncheckedIndexedAccess.types
  tests/baselines/reference/noUncheckedIndexedAccessDestructuring.errors.txt
  tests/baselines/reference/noUncheckedIndexedAccessDestructuring.types
Labels: For Milestone Bug

#40481 fix(40432): `as` keyword is missing in completion lists within function bodies
  src/harness/fourslashInterfaceImpl.ts
  src/services/completions.ts
  tests/cases/fourslash/completionAsKeyword.ts
Labels: For Milestone Bug

#40592 Map over unions when getting iterated element type from contextual type
  src/compiler/checker.ts
  tests/baselines/reference/contextualTypeIterableUnions.js
  tests/baselines/reference/contextualTypeIterableUnions.symbols
  tests/baselines/reference/contextualTypeIterableUnions.types
  tests/cases/compiler/contextualTypeIterableUnions.ts
Labels: Author: Team, For Milestone Bug

#40412 fix(39899): Export default child items of function parameter not included in 'navtree'
  src/services/navigationBar.ts
  tests/cases/fourslash/navigationItemsExportDefaultExpression.ts
Labels: For Backlog Bug

#40630 Fix children prop for `react-jsx` and `react-jsxdev`
  src/compiler/transformers/jsx.ts
  tests/baselines/reference/jsxJsxsCjsTransformChildren(jsx=react-jsx).js
  tests/baselines/reference/jsxJsxsCjsTransformChildren(jsx=react-jsx).symbols
  tests/baselines/reference/jsxJsxsCjsTransformChildren(jsx=react-jsx).types
  tests/baselines/reference/jsxJsxsCjsTransformChildren(jsx=react-jsxdev).js
  tests/baselines/reference/jsxJsxsCjsTransformChildren(jsx=react-jsxdev).symbols
  tests/baselines/reference/jsxJsxsCjsTransformChildren(jsx=react-jsxdev).types
  tests/cases/conformance/jsx/jsxs/jsxJsxsCjsTransformChildren.tsx
Labels: For Uncommitted Bug

#40633 Properly preserve modifiers in homomorphic mapped types with 'as' clauses
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypeAsClauses.js
  tests/baselines/reference/mappedTypeAsClauses.symbols
  tests/baselines/reference/mappedTypeAsClauses.types
  tests/cases/conformance/types/mapped/mappedTypeAsClauses.ts
Labels: For Milestone Bug

#40668 Fix typo in isChangedSignagure
  src/compiler/builder.ts
Labels: For Uncommitted Bug

#40482 Support properties of mapped types in assertion control flow analysis
  src/compiler/checker.ts
  tests/baselines/reference/neverReturningFunctions1.errors.txt
  tests/baselines/reference/neverReturningFunctions1.js
  tests/baselines/reference/neverReturningFunctions1.symbols
  tests/baselines/reference/neverReturningFunctions1.types
  tests/cases/conformance/controlFlow/neverReturningFunctions1.ts
Labels: For Milestone Bug

#40580 Intrinsic string types
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/emitter.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/parser.ts
  src/compiler/scanner.ts
  src/compiler/types.ts
  src/harness/fourslashInterfaceImpl.ts
  src/lib/es5.d.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/intrinsicKeyword.errors.txt
  tests/baselines/reference/intrinsicKeyword.js
  tests/baselines/reference/intrinsicKeyword.symbols
  tests/baselines/reference/intrinsicKeyword.types
  tests/baselines/reference/intrinsicTypes.errors.txt
  tests/baselines/reference/intrinsicTypes.js
  tests/baselines/reference/intrinsicTypes.symbols
  tests/baselines/reference/intrinsicTypes.types
  tests/baselines/reference/mappedTypeAsClauses.js
  tests/baselines/reference/mappedTypeAsClauses.symbols
  tests/baselines/reference/mappedTypeAsClauses.types
  tests/baselines/reference/templateLiteralTypes1.errors.txt
  tests/baselines/reference/templateLiteralTypes1.js
  tests/baselines/reference/templateLiteralTypes1.symbols
  tests/baselines/reference/templateLiteralTypes1.types
  tests/cases/conformance/types/literal/templateLiteralTypes1.ts
  tests/cases/conformance/types/mapped/mappedTypeAsClauses.ts
  tests/cases/conformance/types/typeAliases/intrinsicKeyword.ts
  tests/cases/conformance/types/typeAliases/intrinsicTypes.ts
Labels: For Uncommitted Bug

#40669 feat(40663/40664): improve error messages for assignment assertions '!'
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/definiteAssignmentAssertions.errors.txt
  tests/baselines/reference/definiteAssignmentAssertions.js
  tests/baselines/reference/definiteAssignmentAssertions.symbols
  tests/baselines/reference/definiteAssignmentAssertions.types
  tests/baselines/reference/definiteAssignmentWithErrorStillStripped.errors.txt
  tests/cases/conformance/controlFlow/definiteAssignmentAssertions.ts
Labels: For Backlog Bug

#40675 feat(40674): make error messages more consistent
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/definiteAssignmentAssertions.errors.txt
Labels: For Backlog Bug

#40680 fix(40640) add missing notApplicableReason in protocol
  src/server/protocol.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
Labels: For Milestone Bug

#40688 [release-4.0] Cherry-pick notApplicableReason property addition from #40680
  src/server/protocol.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
Labels: For Uncommitted Bug

#40703 Backport package-lock infra changes to 4.0
  .github/workflows/new-release-branch.yaml
  .github/workflows/release-branch-artifact.yaml
  .github/workflows/set-version.yaml
  .github/workflows/sync-branch.yaml
  .github/workflows/update-lkg.yml
  Dockerfile
  README.md
Labels: For Milestone Bug

#39649 fix(39589): await is missing after autofix convert to an async function
  src/services/codefixes/convertToAsyncFunction.ts
  src/testRunner/unittests/services/convertToAsyncFunction.ts
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_PromiseAllAndThen1.js
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_PromiseAllAndThen1.ts
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_PromiseAllAndThen3.js
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_PromiseAllAndThen3.ts
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_PromiseAllAndThen4.js
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_PromiseAllAndThen4.ts
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_Return1.ts
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_Return2.ts
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_Return3.ts
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_noArgs1.ts
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_noArgs2.ts
Labels: For Backlog Bug

#40707 Const contexts for template literals
  src/compiler/checker.ts
  tests/baselines/reference/constAssertions.errors.txt
  tests/baselines/reference/constAssertions.js
  tests/baselines/reference/constAssertions.symbols
  tests/baselines/reference/constAssertions.types
  tests/cases/conformance/expressions/typeAssertions/constAssertions.ts
Labels: For Uncommitted Bug

#40677 Fix indentation of arrow functions returning parenthesized expressions
  src/harness/fourslashImpl.ts
  src/services/formatting/smartIndenter.ts
  tests/cases/fourslash/formattingArrowFunctionParenthesizedExpression.ts
Labels: Author: Team, For Milestone Bug

#40524 fix(40510): Convert to optional chaining doesn't show up for expressions with bracket accessor
  src/services/refactors/convertToOptionalChainExpression.ts
  tests/cases/fourslash/refactorConvertToOptionalChainExpression_ElementAccessExpression1.ts
  tests/cases/fourslash/refactorConvertToOptionalChainExpression_ElementAccessExpression2.ts
Labels: For Backlog Bug

#40483 Allow an infer type node to resolve its own name
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitShadowingInferNotRenamed.js
  tests/baselines/reference/declarationEmitShadowingInferNotRenamed.symbols
  tests/baselines/reference/declarationEmitShadowingInferNotRenamed.types
  tests/cases/compiler/declarationEmitShadowingInferNotRenamed.ts
Labels: Author: Team, For Milestone Bug

#40406 Fix missing constraints for parenthesized `infer T`
  src/compiler/checker.ts
  src/compiler/utilities.ts
  tests/baselines/reference/inferTInParentheses.js
  tests/baselines/reference/inferTInParentheses.symbols
  tests/baselines/reference/inferTInParentheses.types
  tests/cases/compiler/inferTInParentheses.ts
Labels: For Backlog Bug

#40717 Reorder LKG tasks so protocol build isn't using partial LKG
  scripts/produceLKG.ts
Labels: Author: Team, For Uncommitted Bug

#40596 Fix crash on js declaration emit of export assigned default augmented function
  src/compiler/checker.ts
  tests/baselines/reference/jsDeclarationsFunctionWithDefaultAssignedMember.js
  tests/baselines/reference/jsDeclarationsFunctionWithDefaultAssignedMember.symbols
  tests/baselines/reference/jsDeclarationsFunctionWithDefaultAssignedMember.types
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsFunctionWithDefaultAssignedMember.ts
Labels: Author: Team, For Milestone Bug

#40574 Allow discrimination to identical object types when discriminating contextual types
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/inferenceUnionOfObjectsMappedContextualType.js
  tests/baselines/reference/inferenceUnionOfObjectsMappedContextualType.symbols
  tests/baselines/reference/inferenceUnionOfObjectsMappedContextualType.types
  tests/cases/compiler/inferenceUnionOfObjectsMappedContextualType.ts
Labels: Author: Team, For Milestone Bug

#40598 Allow pattern literal types like `http://${string}` to exist and be reasoned about
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/types.ts
  tests/baselines/reference/constAssertions.js
  tests/baselines/reference/constAssertions.types
  tests/baselines/reference/templateLiteralTypesPatterns.errors.txt
  tests/baselines/reference/templateLiteralTypesPatterns.js
  tests/baselines/reference/templateLiteralTypesPatterns.symbols
  tests/baselines/reference/templateLiteralTypesPatterns.types
  tests/cases/conformance/types/literal/templateLiteralTypesPatterns.ts
Labels: Author: Team, For Uncommitted Bug

#40711 Fix spec links in README
  README.md
Labels: Author: Team, For Uncommitted Bug

#40620 Fix premature closing of AutoImportProviderProject for unbuilt monorepos
  src/server/project.ts
  src/testRunner/unittests/tsserver/autoImportProvider.ts
Labels: Author: Team, For Uncommitted Bug

#40738 Add missing visitor of template literal type
  src/compiler/factory/nodeTests.ts
  src/compiler/visitorPublic.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Uncommitted Bug

#40752 Remove old Typescript-*-Starter user tests
  tests/cases/user/TypeScript-React-Starter/test.json
  tests/cases/user/TypeScript-Vue-Starter/test.json
Labels: Author: Team, For Uncommitted Bug

#40325 feat: expose findAncestor.
  src/compiler/utilities.ts
  src/compiler/utilitiesPublic.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Uncommitted Bug

#40702 CommonJS imports support destructuring+property access
  src/compiler/checker.ts
  tests/baselines/reference/jsDeclarationsTypeReferences2.errors.txt
  tests/baselines/reference/jsDeclarationsTypeReferences2.js
  tests/baselines/reference/jsDeclarationsTypeReferences2.types
Labels: Author: Team, For Milestone Bug

#40775 jsx option affects emit
  src/compiler/commandLineParser.ts
  src/testRunner/unittests/tscWatch/programUpdates.ts
  tests/baselines/reference/tscWatch/programUpdates/updates-emit-on-jsx-option-change.js
Labels: Author: Team, For Milestone Bug

#40338 feat(40233): Include JS Doc types in smart selection
  src/services/smartSelection.ts
  tests/baselines/reference/smartSelection_JSDocTags1.baseline
  tests/baselines/reference/smartSelection_JSDocTags10.baseline
  tests/baselines/reference/smartSelection_JSDocTags2.baseline
  tests/baselines/reference/smartSelection_JSDocTags3.baseline
  tests/baselines/reference/smartSelection_JSDocTags4.baseline
  tests/baselines/reference/smartSelection_JSDocTags5.baseline
  tests/baselines/reference/smartSelection_JSDocTags6.baseline
  tests/baselines/reference/smartSelection_JSDocTags7.baseline
  tests/baselines/reference/smartSelection_JSDocTags8.baseline
  tests/baselines/reference/smartSelection_JSDocTags9.baseline
  tests/cases/fourslash/smartSelection_JSDocTags1.ts
  tests/cases/fourslash/smartSelection_JSDocTags10.ts
  tests/cases/fourslash/smartSelection_JSDocTags2.ts
  tests/cases/fourslash/smartSelection_JSDocTags3.ts
  tests/cases/fourslash/smartSelection_JSDocTags4.ts
  tests/cases/fourslash/smartSelection_JSDocTags5.ts
  tests/cases/fourslash/smartSelection_JSDocTags6.ts
  tests/cases/fourslash/smartSelection_JSDocTags7.ts
  tests/cases/fourslash/smartSelection_JSDocTags8.ts
  tests/cases/fourslash/smartSelection_JSDocTags9.ts
Labels: For Milestone Bug

#40764 fix(40756): TS Refactoring to Infer type inserts ellipses, creating syntax error
  src/services/utilities.ts
  tests/cases/fourslash/codeFixInferFromUsageNoTruncation.ts
Labels: For Uncommitted Bug

#40813 Don’t offer non-relative non-`paths` path when baseUrl is undefined
  src/compiler/moduleSpecifiers.ts
  tests/cases/fourslash/importNameCodeFix_pathsWithoutBaseUrl1.ts
  tests/cases/fourslash/importNameCodeFix_pathsWithoutBaseUrl2.ts
Labels: Author: Team, For Milestone Bug

#40820 fix(40609): Crash on extract to type alias
  src/services/refactors/extractType.ts
  tests/cases/fourslash/refactorExtractType69.ts
  tests/cases/fourslash/refactorExtractType70.ts
Labels: For Milestone Bug

#40784 Update type diagnostic messages with --save-dev (#40776)
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/anonymousModules.errors.txt
  tests/baselines/reference/conflictingCommonJSES2015Exports.errors.txt
  tests/baselines/reference/constructorWithIncompleteTypeAnnotation.errors.txt
  tests/baselines/reference/didYouMeanSuggestionErrors.errors.txt
  tests/baselines/reference/externModule.errors.txt
  tests/baselines/reference/fixSignatureCaching.errors.txt
  tests/baselines/reference/innerModExport1.errors.txt
  tests/baselines/reference/innerModExport2.errors.txt
  tests/baselines/reference/jsDeclarationsExportFormsErr.errors.txt
  tests/baselines/reference/jsxAndTypeAssertion.errors.txt
  tests/baselines/reference/metadataImportType.errors.txt
  tests/baselines/reference/moduleExports1.errors.txt
  tests/baselines/reference/moduleKeywordRepeatError.errors.txt
  tests/baselines/reference/overloadingStaticFunctionsInFunctions.errors.txt
  tests/baselines/reference/parser509534.errors.txt
  tests/baselines/reference/parser509693.errors.txt
  tests/baselines/reference/parser519458.errors.txt
  tests/baselines/reference/parser521128.errors.txt
  tests/baselines/reference/parserCommaInTypeMemberList2.errors.txt
  tests/baselines/reference/parserharness.errors.txt
  tests/baselines/reference/reservedWords2.errors.txt
  tests/baselines/reference/staticsInAFunction.errors.txt
  tests/baselines/reference/templateStringInModuleName.errors.txt
  tests/baselines/reference/templateStringInModuleNameES6.errors.txt
  tests/baselines/reference/typecheckIfCondition.errors.txt
  tests/baselines/reference/typingsSuggestion1.errors.txt
  tests/baselines/reference/typingsSuggestion2.errors.txt
  tests/baselines/reference/untypedModuleImport_noImplicitAny.errors.txt
  tests/baselines/reference/untypedModuleImport_noImplicitAny_scoped.errors.txt
  tests/baselines/reference/untypedModuleImport_noImplicitAny_typesForPackageExist.errors.txt
Labels: For Backlog Bug

#40834 fix(40609): add tests to cover TemplateLiteralType extraction
  tests/cases/fourslash/refactorExtractType71.ts
Labels: For Uncommitted Bug

#40783 Fixed bug with toggleLineComment ends in a start line
  src/services/services.ts
  tests/cases/fourslash/toggleLineComment11.ts
  tests/cases/fourslash/toggleMultilineComment1.ts
  tests/cases/fourslash/uncommentSelection1.ts
Labels: For Uncommitted Bug

#40722 Install playwright on demand
  .github/workflows/ci.yml
  package-lock.json
  package.json
  scripts/browserIntegrationTest.js
Labels: Author: Team, For Uncommitted Bug

#40841 Match suffix _after_ prefix when inferring literals out of templates
  src/compiler/checker.ts
  tests/baselines/reference/templateLiteralTypesPatternsPrefixSuffixAssignability.errors.txt
  tests/baselines/reference/templateLiteralTypesPatternsPrefixSuffixAssignability.js
  tests/baselines/reference/templateLiteralTypesPatternsPrefixSuffixAssignability.symbols
  tests/baselines/reference/templateLiteralTypesPatternsPrefixSuffixAssignability.types
  tests/cases/conformance/types/literal/templateLiteralTypesPatternsPrefixSuffixAssignability.ts
Labels: Author: Team, For Milestone Bug

#40605 fix(40441): Deprecated errors not shown for deprecated property in namespace
  src/compiler/checker.ts
  tests/cases/fourslash/jsdocDeprecated_suggestion10.ts
Labels: For Milestone Bug

#40836 Fix default property assigned prototype
  src/compiler/checker.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/services/suggestionDiagnostics.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/defaultPropertyAssignedClassWithPrototype.symbols
  tests/baselines/reference/defaultPropertyAssignedClassWithPrototype.types
  tests/cases/conformance/salsa/defaultPropertyAssignedClassWithPrototype.ts
Labels: Author: Team, For Milestone Bug

#40843 Use correct program when checking for reexports from AutoImportProviderProject
  src/services/codefixes/importFixes.ts
  tests/cases/fourslash/server/autoImportProvider5.ts
Labels: Author: Team, For Milestone Bug

#40667 Remove duplicate comment
  src/compiler/builderState.ts
Labels: For Uncommitted Bug, Housekeeping

#40755 Enforce a size limit in getSpreadType
  src/compiler/checker.ts
  tests/baselines/reference/objectSpreadRepeatedComplexity.errors.txt
  tests/baselines/reference/objectSpreadRepeatedComplexity.js
  tests/baselines/reference/objectSpreadRepeatedComplexity.symbols
  tests/baselines/reference/objectSpreadRepeatedComplexity.types
  tests/cases/conformance/types/spread/objectSpreadRepeatedComplexity.ts
Labels: For Uncommitted Bug
