Repository microsoft/TypeScript, pull requests merged in 2020-04, with the labels that each got.

#37726 Add support for extraFileExtensions on WatchCompilerHost
  src/compiler/commandLineParser.ts
  src/compiler/watch.ts
  src/compiler/watchPublic.ts
  src/executeCommandLine/executeCommandLine.ts
  src/testRunner/unittests/reuseProgramStructure.ts
  src/testRunner/unittests/tscWatch/helpers.ts
  src/testRunner/unittests/tscWatch/sourceOfProjectReferenceRedirect.ts
  src/testRunner/unittests/tscWatch/watchApi.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team

#37499 Add node to zone.js' tsconfig types
  tests/cases/user/zone.js/tsconfig.json
Labels: Author: Team

#37626 Fix crash on bad namespace parse
  src/compiler/transformers/ts.ts
  tests/baselines/reference/nestedGlobalNamespaceInClass.errors.txt
  tests/baselines/reference/nestedGlobalNamespaceInClass.js
  tests/baselines/reference/nestedGlobalNamespaceInClass.symbols
  tests/baselines/reference/nestedGlobalNamespaceInClass.types
  tests/cases/compiler/nestedGlobalNamespaceInClass.ts
Labels: Author: Team

#37589 Disallow partial matches for discriminant properties when generating error messages
  src/compiler/checker.ts
  tests/baselines/reference/unionErrorMessageOnMatchingDiscriminant.errors.txt
  tests/baselines/reference/unionErrorMessageOnMatchingDiscriminant.js
  tests/baselines/reference/unionErrorMessageOnMatchingDiscriminant.symbols
  tests/baselines/reference/unionErrorMessageOnMatchingDiscriminant.types
  tests/cases/compiler/unionErrorMessageOnMatchingDiscriminant.ts
Labels: Author: Team

#37476 Add replacer function overload for replaceAll
  src/lib/esnext.string.d.ts
Labels: For Backlog Bug

#37691 Explicitly merge module augmentation members into the exports added by export * declarations
  src/compiler/checker.ts
  tests/baselines/reference/augmentExportEquals3.symbols
  tests/baselines/reference/augmentExportEquals3.types
  tests/baselines/reference/augmentExportEquals3_1.symbols
  tests/baselines/reference/augmentExportEquals3_1.types
  tests/baselines/reference/augmentExportEquals4.symbols
  tests/baselines/reference/augmentExportEquals4.types
  tests/baselines/reference/augmentExportEquals4_1.symbols
  tests/baselines/reference/augmentExportEquals4_1.types
  tests/baselines/reference/augmentExportEquals5.symbols
  tests/baselines/reference/augmentExportEquals5.types
  tests/baselines/reference/augmentExportEquals6.symbols
  tests/baselines/reference/augmentExportEquals6.types
  tests/baselines/reference/augmentExportEquals6_1.symbols
  tests/baselines/reference/augmentExportEquals6_1.types
  tests/baselines/reference/declarationFileNoCrashOnExtraExportModifier.types
  tests/baselines/reference/duplicateVarsAcrossFileBoundaries.symbols
  tests/baselines/reference/es5ExportEquals.types
  tests/baselines/reference/es6ExportEquals.types
  tests/baselines/reference/exportAssignmentAndDeclaration.types
  tests/baselines/reference/exportAssignmentMembersVisibleInAugmentation.symbols
  tests/baselines/reference/exportAssignmentMembersVisibleInAugmentation.types
  tests/baselines/reference/exportAssignmentWithExports.types
  tests/baselines/reference/importDeclWithExportModifierAndExportAssignment.types
  tests/baselines/reference/importDeclWithExportModifierAndExportAssignmentInAmbientContext.types
  tests/baselines/reference/intersectionsOfLargeUnions2.symbols
  tests/baselines/reference/moduleAugmentationDoesInterfaceMergeOfReexport.js
  tests/baselines/reference/moduleAugmentationDoesInterfaceMergeOfReexport.symbols
  tests/baselines/reference/moduleAugmentationDoesInterfaceMergeOfReexport.types
  tests/baselines/reference/moduleAugmentationDoesNamespaceEnumMergeOfReexport.js
  tests/baselines/reference/moduleAugmentationDoesNamespaceEnumMergeOfReexport.symbols
  tests/baselines/reference/moduleAugmentationDoesNamespaceEnumMergeOfReexport.types
  tests/baselines/reference/moduleAugmentationDoesNamespaceMergeOfReexport.js
  tests/baselines/reference/moduleAugmentationDoesNamespaceMergeOfReexport.symbols
  tests/baselines/reference/moduleAugmentationDoesNamespaceMergeOfReexport.types
  tests/baselines/reference/moduleAugmentationDuringSyntheticDefaultCheck.symbols
  tests/baselines/reference/moduleAugmentationEnumClassMergeOfReexportIsError.errors.txt
  tests/baselines/reference/moduleAugmentationEnumClassMergeOfReexportIsError.js
  tests/baselines/reference/moduleAugmentationEnumClassMergeOfReexportIsError.symbols
  tests/baselines/reference/moduleAugmentationEnumClassMergeOfReexportIsError.types
  tests/baselines/reference/moduleAugmentationOfAlias.symbols
  tests/baselines/reference/moduleAugmentationOfAlias.types
  tests/baselines/reference/module_augmentUninstantiatedModule.symbols
  tests/baselines/reference/reactTransitiveImportHasValidDeclaration.symbols
  tests/baselines/reference/tsxResolveExternalModuleExportsTypes.symbols
  tests/baselines/reference/typedefCrossModule2.errors.txt
  tests/baselines/reference/typedefCrossModule3.errors.txt
  tests/baselines/reference/typedefCrossModule4.errors.txt
  tests/baselines/reference/umd-augmentation-3.symbols
  tests/baselines/reference/umd-augmentation-3.types
  tests/baselines/reference/umd-augmentation-4.symbols
  tests/baselines/reference/umd-augmentation-4.types
  tests/baselines/reference/umdNamespaceMergedWithGlobalAugmentationIsNotCircular.symbols
  tests/baselines/reference/umdNamespaceMergedWithGlobalAugmentationIsNotCircular.types
  tests/cases/compiler/moduleAugmentationDoesInterfaceMergeOfReexport.ts
  tests/cases/compiler/moduleAugmentationDoesNamespaceEnumMergeOfReexport.ts
  tests/cases/compiler/moduleAugmentationDoesNamespaceMergeOfReexport.ts
  tests/cases/compiler/moduleAugmentationEnumClassMergeOfReexportIsError.ts
Labels: Author: Team

#37490 Add replacement span for string literal
  src/services/completions.ts
  src/services/stringCompletions.ts
  src/services/utilities.ts
  tests/cases/fourslash/completionForQuotedPropertyInPropertyAssignment1.ts
  tests/cases/fourslash/completionForQuotedPropertyInPropertyAssignment2.ts
  tests/cases/fourslash/completionForQuotedPropertyInPropertyAssignment3.ts
  tests/cases/fourslash/completionForQuotedPropertyInPropertyAssignment4.ts
  tests/cases/fourslash/completionForStringLiteral.ts
  tests/cases/fourslash/completionForStringLiteral10.ts
  tests/cases/fourslash/completionForStringLiteral11.ts
  tests/cases/fourslash/completionForStringLiteral12.ts
  tests/cases/fourslash/completionForStringLiteral2.ts
  tests/cases/fourslash/completionForStringLiteral3.ts
  tests/cases/fourslash/completionForStringLiteral4.ts
  tests/cases/fourslash/completionForStringLiteral6.ts
  tests/cases/fourslash/completionForStringLiteral7.ts
  tests/cases/fourslash/completionForStringLiteralFromSignature.ts
  tests/cases/fourslash/completionForStringLiteralInIndexedAccess01.ts
  tests/cases/fourslash/completionForStringLiteral_details.ts
  tests/cases/fourslash/completionInfoWithExplicitTypeArguments.ts
  tests/cases/fourslash/completionListAfterStringLiteralTypeWithNoSubstitutionTemplateLiteral.ts
  tests/cases/fourslash/completionListForStringUnion.ts
  tests/cases/fourslash/completionListInvalidMemberNames.ts
  tests/cases/fourslash/completionsJsPropertyAssignment.ts
  tests/cases/fourslash/completionsKeyof.ts
  tests/cases/fourslash/completionsStringLiteral_fromTypeConstraint.ts
  tests/cases/fourslash/completionsStringsWithTriggerCharacter.ts
  tests/cases/fourslash/completionsTriggerCharacter.ts
  tests/cases/fourslash/completionsWithGenericStringLiteral.ts
  tests/cases/fourslash/completionsWithStringReplacementMode.ts
  tests/cases/fourslash/completionsWithStringReplacementMode1.ts
  tests/cases/fourslash/getJavaScriptCompletions21.ts
Labels: For Backlog Bug

#37504 fix(37431): Formatter no longer normalizes spaces in method signature
  src/services/formatting/rules.ts
  tests/cases/fourslash/formatAsyncClassMethod1.ts
  tests/cases/fourslash/formatAsyncClassMethod2.ts
Labels: For Backlog Bug

#37745 Fix rename for type symbols imported as a different name
  src/services/utilities.ts
  tests/baselines/reference/renameImportSpecifierPropertyName.baseline
  tests/cases/fourslash/renameImportSpecifierPropertyName.ts
Labels: Author: Team

#33652 Fix goto implementation does not suggest all subtypes
  src/services/findAllReferences.ts
  tests/cases/fourslash/goToImplementationInterface_01.ts
Labels: For Backlog Bug

#26434 Quick fix for functions lacking return expressions
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/factoryPublic.ts
  src/services/codefixes/returnValueCorrect.ts
  src/services/refactors/addOrRemoveBracesToArrowFunction.ts
  src/services/refactors/convertParamsToDestructuredObject.ts
  src/services/tsconfig.json
  src/services/utilities.ts
  tests/cases/fourslash/codeFixAwaitInSyncFunction10.ts
  tests/cases/fourslash/codeFixAwaitInSyncFunction11.ts
  tests/cases/fourslash/codeFixAwaitInSyncFunction12.ts
  tests/cases/fourslash/codeFixAwaitInSyncFunction13.ts
  tests/cases/fourslash/codeFixAwaitInSyncFunction14.ts
  tests/cases/fourslash/codeFixAwaitInSyncFunction15.ts
  tests/cases/fourslash/codeFixAwaitInSyncFunction8.ts
  tests/cases/fourslash/codeFixAwaitInSyncFunction9.ts
  tests/cases/fourslash/codeFixCorrectReturnValue1.ts
  tests/cases/fourslash/codeFixCorrectReturnValue10.ts
  tests/cases/fourslash/codeFixCorrectReturnValue11.ts
  tests/cases/fourslash/codeFixCorrectReturnValue12.ts
  tests/cases/fourslash/codeFixCorrectReturnValue13.ts
  tests/cases/fourslash/codeFixCorrectReturnValue14.ts
  tests/cases/fourslash/codeFixCorrectReturnValue15.ts
  tests/cases/fourslash/codeFixCorrectReturnValue16.ts
  tests/cases/fourslash/codeFixCorrectReturnValue17.ts
  tests/cases/fourslash/codeFixCorrectReturnValue18.ts
  tests/cases/fourslash/codeFixCorrectReturnValue19.ts
  tests/cases/fourslash/codeFixCorrectReturnValue2.ts
  tests/cases/fourslash/codeFixCorrectReturnValue20.ts
  tests/cases/fourslash/codeFixCorrectReturnValue21.ts
  tests/cases/fourslash/codeFixCorrectReturnValue22.ts
  tests/cases/fourslash/codeFixCorrectReturnValue23.ts
  tests/cases/fourslash/codeFixCorrectReturnValue24.ts
  tests/cases/fourslash/codeFixCorrectReturnValue25.ts
  tests/cases/fourslash/codeFixCorrectReturnValue26.ts
  tests/cases/fourslash/codeFixCorrectReturnValue3.ts
  tests/cases/fourslash/codeFixCorrectReturnValue4.ts
  tests/cases/fourslash/codeFixCorrectReturnValue5.ts
  tests/cases/fourslash/codeFixCorrectReturnValue6.ts
  tests/cases/fourslash/codeFixCorrectReturnValue7.ts
  tests/cases/fourslash/codeFixCorrectReturnValue8.ts
  tests/cases/fourslash/codeFixCorrectReturnValue9.ts
  tests/cases/fourslash/codeFixCorrectReturnValue_all1.ts
  tests/cases/fourslash/codeFixCorrectReturnValue_all2.ts
  tests/cases/fourslash/codeFixCorrectReturnValue_all3.ts
Labels: For Backlog Bug, lib update

#37757 Remove error when spreading optional any
  src/compiler/checker.ts
  tests/baselines/reference/spreadOverwritesPropertyStrict.errors.txt
  tests/baselines/reference/spreadOverwritesPropertyStrict.js
  tests/baselines/reference/spreadOverwritesPropertyStrict.symbols
  tests/baselines/reference/spreadOverwritesPropertyStrict.types
  tests/cases/conformance/types/spread/spreadOverwritesPropertyStrict.ts
Labels: Author: Team

#37761 convertToAsync: Fix variable name collisions
  src/services/codefixes/convertToAsyncFunction.ts
  src/testRunner/unittests/services/convertToAsyncFunction.ts
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_InnerPromiseRetBinding1.ts
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_ParameterNameCollision.ts
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_basicWithComments.ts
Labels: Author: Team

#37749 Cache the regularized form of union types
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/conditionalTypeDiscriminatingLargeUnionRegularTypeFetchingSpeedReasonable.js
  tests/baselines/reference/conditionalTypeDiscriminatingLargeUnionRegularTypeFetchingSpeedReasonable.symbols
  tests/baselines/reference/conditionalTypeDiscriminatingLargeUnionRegularTypeFetchingSpeedReasonable.types
  tests/cases/compiler/conditionalTypeDiscriminatingLargeUnionRegularTypeFetchingSpeedReasonable.ts
Labels: Author: Team

#37764 Fix crash for private identifier in expando assignments
  src/compiler/utilities.ts
  tests/baselines/reference/privateIdentifierExpando.js
  tests/baselines/reference/privateIdentifierExpando.symbols
  tests/baselines/reference/privateIdentifierExpando.types
  tests/baselines/reference/privateNameJsBadAssignment.errors.txt
  tests/baselines/reference/privateNameJsBadAssignment.symbols
  tests/baselines/reference/privateNameJsBadAssignment.types
  tests/cases/conformance/salsa/privateIdentifierExpando.ts
Labels: Author: Team

#37776 Consider arrays and tuples within one another as possibly requiring deferral
  src/compiler/checker.ts
  tests/baselines/reference/circularlyReferentialInterfaceAccessNoCrash.errors.txt
  tests/baselines/reference/deferredTypeReferenceWithinArrayWithinTuple.js
  tests/baselines/reference/deferredTypeReferenceWithinArrayWithinTuple.symbols
  tests/baselines/reference/deferredTypeReferenceWithinArrayWithinTuple.types
  tests/cases/compiler/deferredTypeReferenceWithinArrayWithinTuple.ts
Labels: Author: Team

#37780 Fix serialisation of static class members in JS
  src/compiler/checker.ts
  tests/baselines/reference/jsDeclarationsClassStatic.js
  tests/baselines/reference/jsDeclarationsClassStatic.symbols
  tests/baselines/reference/jsDeclarationsClassStatic.types
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsClassStatic.ts
Labels: Author: Team

#37819 Look for outer type parameters on VariableStatements
  src/compiler/checker.ts
  tests/baselines/reference/instantiateTemplateTagTypeParameterOnVariableStatement.js
  tests/baselines/reference/instantiateTemplateTagTypeParameterOnVariableStatement.symbols
  tests/baselines/reference/instantiateTemplateTagTypeParameterOnVariableStatement.types
  tests/cases/conformance/jsdoc/instantiateTemplateTagTypeParameterOnVariableStatement.ts
Labels: Author: Team

#32131 Accurate Array.prototype.flat definition
  src/lib/es2019.array.d.ts
Labels: For Milestone Bug

#37543 Disambiguate types with same name from different namespaces in mapToTypeNodes
  src/compiler/checker.ts
  src/compiler/core.ts
  src/compiler/utilities.ts
  tests/baselines/reference/namespaceDisambiguationInUnion.errors.txt
  tests/baselines/reference/namespaceDisambiguationInUnion.js
  tests/baselines/reference/namespaceDisambiguationInUnion.symbols
  tests/baselines/reference/namespaceDisambiguationInUnion.types
  tests/cases/compiler/namespaceDisambiguationInUnion.ts
Labels: Author: Team

#37808 Make skipLibCheck: true the default in --init
  src/compiler/commandLineParser.ts
  tests/baselines/reference/tsConfig/Default initialized TSConfig/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with boolean value compiler options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with enum value compiler options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with files options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with incorrect compiler option value/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with incorrect compiler option/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with list compiler options with enum value/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with list compiler options/tsconfig.json
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/declarationDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/when-outDir-and-declarationDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/when-outDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/with-outFile.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/without-outDir-or-outFile-is-specified.js
Labels: Author: Team

#37646 Skip `isBlockScopedNameDeclaredBeforeUse` error in interface or type declarations
  src/compiler/checker.ts
  tests/baselines/reference/forwardRefInTypeDeclaration.js
  tests/baselines/reference/forwardRefInTypeDeclaration.symbols
  tests/baselines/reference/forwardRefInTypeDeclaration.types
  tests/cases/compiler/forwardRefInTypeDeclaration.ts
Labels: Author: Team

#37838 Fix easy misunderstanding "! ==="
  src/compiler/scanner.ts
  src/services/codefixes/addMissingAwait.ts
Labels: Housekeeping

#37836 Fix metadata serialization for invalid jsdoc types
  src/compiler/transformers/ts.ts
  tests/baselines/reference/decoratorMetadata-jsdoc.errors.txt
  tests/baselines/reference/decoratorMetadata-jsdoc.js
  tests/baselines/reference/decoratorMetadata-jsdoc.symbols
  tests/baselines/reference/decoratorMetadata-jsdoc.types
  tests/cases/conformance/decorators/decoratorMetadata-jsdoc.ts
Labels: Author: Team

#37594 Use comments from host variable declaration when exporting a signature in js declarations
  src/compiler/checker.ts
  tests/baselines/reference/jsDeclarationsDocCommentsOnConsts.js
  tests/baselines/reference/jsDeclarationsDocCommentsOnConsts.symbols
  tests/baselines/reference/jsDeclarationsDocCommentsOnConsts.types
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsDocCommentsOnConsts.ts
Labels: Author: Team

#37845 Fix async function block return expr error in js
  src/compiler/checker.ts
  tests/baselines/reference/asyncArrowFunction_allowJs.errors.txt
  tests/baselines/reference/asyncArrowFunction_allowJs.symbols
  tests/baselines/reference/asyncArrowFunction_allowJs.types
  tests/cases/conformance/async/es2017/asyncArrowFunction/asyncArrowFunction_allowJs.ts
Labels: Author: Team

#37828 Set contextual type on elaborated error node rather than passing it, …
  src/compiler/checker.ts
  tests/baselines/reference/arrayLiteralTypeInference.errors.txt
  tests/baselines/reference/declarationsAndAssignments.errors.txt
  tests/baselines/reference/destructuringParameterProperties5.errors.txt
  tests/baselines/reference/excessPropertyChecksWithNestedIntersections.errors.txt
  tests/baselines/reference/partialDiscriminatedUnionMemberHasGoodError.errors.txt
  tests/baselines/reference/partialDiscriminatedUnionMemberHasGoodError.js
  tests/baselines/reference/partialDiscriminatedUnionMemberHasGoodError.symbols
  tests/baselines/reference/partialDiscriminatedUnionMemberHasGoodError.types
  tests/cases/compiler/partialDiscriminatedUnionMemberHasGoodError.ts
Labels: Author: Team

#37743 Remove extraneous string escape from convert to template string refactor
  src/compiler/utilities.ts
  src/services/refactors/convertStringOrTemplateLiteral.ts
  tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_escapedBackslashes.ts
Labels: Author: Team

#37715 Error on invalid uses of namespace export
  src/compiler/checker.ts
  tests/baselines/reference/exportAsNamespace_exportAssignment.errors.txt
  tests/baselines/reference/exportAsNamespace_exportAssignment.js
  tests/baselines/reference/exportAsNamespace_missingEmitHelpers.errors.txt
  tests/baselines/reference/exportAsNamespace_missingEmitHelpers.js
  tests/baselines/reference/exportAsNamespace_nonExistent.errors.txt
  tests/baselines/reference/exportAsNamespace_nonExistent.js
  tests/cases/conformance/es2020/modules/exportAsNamespace_exportAssignment.ts
  tests/cases/conformance/es2020/modules/exportAsNamespace_missingEmitHelpers.ts
  tests/cases/conformance/es2020/modules/exportAsNamespace_nonExistent.ts
Labels: Author: Team

#37869 Lock playwright version
  package.json
Labels: Author: Team

#37696 Fix crash from missing valueDeclaration on intersection property
  src/compiler/checker.ts
  tests/baselines/reference/jsEmitIntersectionProperty.js
  tests/baselines/reference/narrowingByTypeofInSwitch.symbols
  tests/cases/compiler/jsEmitIntersectionProperty.ts
Labels: Author: Team

#37870 Remove node 8 from the github actions
  .github/workflows/ci.yml
Labels: Author: Team

#37367 fix(37364): No completions in string literal index on mapped type
  src/services/stringCompletions.ts
  tests/cases/fourslash/completionForStringLiteral_mappedTypeMembers.ts
Labels: For Milestone Bug

#37183 fix(37150): private field should not conflict with string index type
  src/compiler/checker.ts
  tests/baselines/reference/classIndexer5.js
  tests/baselines/reference/classIndexer5.symbols
  tests/baselines/reference/classIndexer5.types
  tests/cases/compiler/classIndexer5.ts
Labels: For Backlog Bug

#37827 Avoid circular reference in this-property assignments
  src/compiler/checker.ts
  tests/baselines/reference/thisPropertyAssignmentCircular.js
  tests/baselines/reference/thisPropertyAssignmentCircular.symbols
  tests/baselines/reference/thisPropertyAssignmentCircular.types
  tests/cases/conformance/salsa/thisPropertyAssignmentCircular.ts
Labels: Author: Team

#37899 Error on missing BigInt in es2020
  src/compiler/checker.ts
  tests/baselines/reference/bigintMissingES2019.js
  tests/baselines/reference/bigintMissingES2019.symbols
  tests/baselines/reference/bigintMissingES2019.types
  tests/baselines/reference/bigintMissingES2020.errors.txt
  tests/baselines/reference/bigintMissingES2020.js
  tests/baselines/reference/bigintMissingES2020.symbols
  tests/baselines/reference/bigintMissingES2020.types
  tests/baselines/reference/bigintMissingESNext.errors.txt
  tests/baselines/reference/bigintMissingESNext.js
  tests/baselines/reference/bigintMissingESNext.symbols
  tests/baselines/reference/bigintMissingESNext.types
  tests/cases/conformance/es2020/bigintMissingES2019.ts
  tests/cases/conformance/es2020/bigintMissingES2020.ts
  tests/cases/conformance/es2020/bigintMissingESNext.ts
Labels: Author: Team

#37820 Retain imports in declaration emit if they augment an export of the importing file
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/transformers/declarations.ts
  src/compiler/types.ts
  tests/baselines/reference/declarationEmitForModuleImportingModuleAugmentationRetainsImport.js
  tests/baselines/reference/declarationEmitForModuleImportingModuleAugmentationRetainsImport.symbols
  tests/baselines/reference/declarationEmitForModuleImportingModuleAugmentationRetainsImport.types
  tests/cases/compiler/declarationEmitForModuleImportingModuleAugmentationRetainsImport.ts
Labels: Author: Team

#37236 Update __exportStar helper to skip default and __esModule members
  src/compiler/transformers/module/module.ts
  tests/baselines/reference/ambientShorthand_reExport.js
  tests/baselines/reference/declarationEmitAliasExportStar.js
  tests/baselines/reference/declarationEmitReexportedSymlinkReference.js
  tests/baselines/reference/declarationEmitReexportedSymlinkReference2.js
  tests/baselines/reference/declarationEmitReexportedSymlinkReference3.js
  tests/baselines/reference/doubleUnderscoreExportStarConflict.js
  tests/baselines/reference/es6ExportAllInEs5.js
  tests/baselines/reference/es6ExportEqualsInterop.js
  tests/baselines/reference/esModuleInteropWithExportStar(target=es3).js
  tests/baselines/reference/esModuleInteropWithExportStar(target=es5).js
  tests/baselines/reference/exportNamespace1.js
  tests/baselines/reference/exportStar-amd.js
  tests/baselines/reference/exportStar.js
  tests/baselines/reference/exportStarForValues.js
  tests/baselines/reference/exportStarForValues2.js
  tests/baselines/reference/exportStarForValues3.js
  tests/baselines/reference/exportStarForValues4.js
  tests/baselines/reference/exportStarForValues5.js
  tests/baselines/reference/exportStarForValues7.js
  tests/baselines/reference/exportStarForValues8.js
  tests/baselines/reference/exportStarForValues9.js
  tests/baselines/reference/exportStarFromEmptyModule.js
  tests/baselines/reference/exportStarNotElided.js
  tests/baselines/reference/inlineJsxFactoryDeclarations.js
  tests/baselines/reference/jsDeclarationsExportForms.js
  tests/baselines/reference/jsDeclarationsExportFormsErr.js
  tests/baselines/reference/moduleDeclarationExportStarShadowingGlobalIsNameable.js
  tests/baselines/reference/moduleSameValueDuplicateExportedBindings1.js
  tests/baselines/reference/moduleSameValueDuplicateExportedBindings2.js
  tests/baselines/reference/symbolLinkDeclarationEmitModuleNames.js
  tests/baselines/reference/transformApi/transformsCorrectly.transformAddCommentToImport.js
  tests/baselines/reference/tsbuild/watchMode/reexport/Reports-errors-correctly.js
  tests/baselines/reference/tsc/declarationEmit/when-pkg-references-sibling-package-through-indirect-symlink-moduleCaseChange.js
  tests/baselines/reference/tsc/declarationEmit/when-pkg-references-sibling-package-through-indirect-symlink.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependencies/updates-errors-when-file-transitively-exported-file-changes/when-there-are-circular-import-and-exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependencies/updates-errors-when-file-transitively-exported-file-changes/when-there-are-no-circular-import-and-exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependenciesAndD/updates-errors-when-file-transitively-exported-file-changes/when-there-are-circular-import-and-exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependenciesAndD/updates-errors-when-file-transitively-exported-file-changes/when-there-are-no-circular-import-and-exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/default/updates-errors-when-file-transitively-exported-file-changes/when-there-are-circular-import-and-exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/default/updates-errors-when-file-transitively-exported-file-changes/when-there-are-no-circular-import-and-exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/defaultAndD/updates-errors-when-file-transitively-exported-file-changes/when-there-are-circular-import-and-exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/defaultAndD/updates-errors-when-file-transitively-exported-file-changes/when-there-are-no-circular-import-and-exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModules/updates-errors-when-file-transitively-exported-file-changes/when-there-are-circular-import-and-exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModules/updates-errors-when-file-transitively-exported-file-changes/when-there-are-no-circular-import-and-exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModulesAndD/updates-errors-when-file-transitively-exported-file-changes/when-there-are-circular-import-and-exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModulesAndD/updates-errors-when-file-transitively-exported-file-changes/when-there-are-no-circular-import-and-exports.js
  tests/baselines/reference/tscWatch/programUpdates/changes-in-files-are-reflected-in-project-structure.js
  tests/baselines/reference/tscWatch/programUpdates/deleted-files-affect-project-structure-2.js
  tests/baselines/reference/tscWatch/programUpdates/deleted-files-affect-project-structure.js
Labels: Author: Team, For Milestone Bug

#37945 Accept recent tests with updated helper baseline code
  tests/baselines/reference/moduleAugmentationDoesInterfaceMergeOfReexport.js
  tests/baselines/reference/moduleAugmentationDoesNamespaceEnumMergeOfReexport.js
  tests/baselines/reference/moduleAugmentationDoesNamespaceMergeOfReexport.js
  tests/baselines/reference/moduleAugmentationEnumClassMergeOfReexportIsError.js
Labels: Author: Team

#37481 Add fastpath to isRelatedTo for type references
  src/compiler/checker.ts
  tests/baselines/reference/recursiveArrayNotCircular.js
  tests/baselines/reference/recursiveArrayNotCircular.symbols
  tests/baselines/reference/recursiveArrayNotCircular.types
  tests/cases/compiler/recursiveArrayNotCircular.ts
Labels: Author: Team, For Milestone Bug

#34655 Added error when Enum member initaliser references itself
  src/compiler/checker.ts
  tests/baselines/reference/enumPropertyAccessBeforeInitalisation.errors.txt
  tests/baselines/reference/enumPropertyAccessBeforeInitalisation.js
  tests/baselines/reference/enumPropertyAccessBeforeInitalisation.symbols
  tests/baselines/reference/enumPropertyAccessBeforeInitalisation.types
  tests/cases/compiler/enumPropertyAccessBeforeInitalisation.ts
Labels: For Backlog Bug

#37790 Improve error message for computed enums
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/arrowFunctionContexts.errors.txt
  tests/baselines/reference/enumErrors.errors.txt
  tests/baselines/reference/enumErrors.js
  tests/baselines/reference/enumErrors.symbols
  tests/baselines/reference/enumErrors.types
  tests/cases/conformance/enums/enumErrors.ts
Labels: For Backlog Bug

#35937 fix(refactor): keep comments after refactor
  src/services/refactors/addOrRemoveBracesToArrowFunction.ts
  tests/cases/fourslash/refactorAddOrRemoveBracesToArrowFunction24.ts
  tests/cases/fourslash/refactorAddOrRemoveBracesToArrowFunction25.ts
  tests/cases/fourslash/refactorAddOrRemoveBracesToArrowFunction26.ts
  tests/cases/fourslash/refactorAddOrRemoveBracesToArrowFunction27.ts
  tests/cases/fourslash/refactorAddOrRemoveBracesToArrowFunction28.ts
Labels: For Backlog Bug

#37989 Typo at Uint8Array[Symbol.toStringTag]
  src/lib/es2015.symbol.wellknown.d.ts
  tests/baselines/reference/typedArraysCrossAssignability01.errors.txt
Labels: Author: Team

#37992 Fix crash on declaration emit for globalThis
  src/compiler/checker.ts
  tests/baselines/reference/globalThisDeclarationEmit.errors.txt
  tests/baselines/reference/globalThisDeclarationEmit.js
  tests/baselines/reference/globalThisDeclarationEmit.symbols
  tests/baselines/reference/globalThisDeclarationEmit.types
  tests/baselines/reference/globalThisDeclarationEmit2.js
  tests/baselines/reference/globalThisDeclarationEmit2.symbols
  tests/baselines/reference/globalThisDeclarationEmit2.types
  tests/baselines/reference/globalThisDeclarationEmit3.js
  tests/baselines/reference/globalThisDeclarationEmit3.symbols
  tests/baselines/reference/globalThisDeclarationEmit3.types
  tests/cases/compiler/globalThisDeclarationEmit.ts
  tests/cases/compiler/globalThisDeclarationEmit2.ts
  tests/cases/compiler/globalThisDeclarationEmit3.ts
Labels: Author: Team

#37936 Use string representation for negative numeric property names
  src/compiler/checker.ts
  tests/baselines/reference/enumKeysQuotedAsObjectPropertiesInDeclarationEmit.js
  tests/baselines/reference/enumKeysQuotedAsObjectPropertiesInDeclarationEmit.symbols
  tests/baselines/reference/enumKeysQuotedAsObjectPropertiesInDeclarationEmit.types
  tests/baselines/reference/objectTypeWithStringNamedNumericProperty.types
  tests/cases/compiler/enumKeysQuotedAsObjectPropertiesInDeclarationEmit.ts
Labels: Author: Team

#36152 prefix-unused-parameter-with-_ codefix now works in jsdoc @param
  src/services/codefixes/fixUnusedIdentifier.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_all_prefix.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_prefix.ts
Labels: For Backlog Bug

#38032 Fix doc comment template on assignment expressions
  src/services/jsDoc.ts
  tests/cases/fourslash/docCommentTemplateExportAssignmentJS.ts
Labels: Author: Team

#37911 fix(37242): No location for 'must return a value' error
  src/compiler/utilitiesPublic.ts
  tests/baselines/reference/asyncArrowFunction_allowJs.errors.txt
  tests/baselines/reference/jsdocFunction_missingReturn.errors.txt
  tests/baselines/reference/jsdocFunction_missingReturn.symbols
  tests/baselines/reference/jsdocFunction_missingReturn.types
  tests/cases/conformance/jsdoc/jsdocFunction_missingReturn.ts
Labels: For Backlog Bug

#37988 Handle non literal computed name when trying to get the name for object literal property name in json object
  src/compiler/checker.ts
  src/compiler/commandLineParser.ts
  src/compiler/utilities.ts
  tests/baselines/reference/requireOfJsonFileWithComputedPropertyName.errors.txt
  tests/baselines/reference/requireOfJsonFileWithComputedPropertyName.js
  tests/baselines/reference/requireOfJsonFileWithComputedPropertyName.symbols
  tests/baselines/reference/requireOfJsonFileWithComputedPropertyName.types
  tests/cases/compiler/requireOfJsonFileWithComputedPropertyName.ts
Labels: Author: Team

#38033 Fix use-before-def with methods on esnext+useDefineForClassFields
  src/compiler/checker.ts
  tests/baselines/reference/assignParameterPropertyToPropertyDeclarationESNext.errors.txt
  tests/baselines/reference/assignParameterPropertyToPropertyDeclarationESNext.js
  tests/baselines/reference/assignParameterPropertyToPropertyDeclarationESNext.symbols
  tests/baselines/reference/assignParameterPropertyToPropertyDeclarationESNext.types
  tests/cases/conformance/classes/propertyMemberDeclarations/assignParameterPropertyToPropertyDeclarationESNext.ts
Labels: Author: Team

#37947 Remove superCallShouldBeFirst error
  src/compiler/checker.ts
  tests/baselines/reference/privateNameBadSuperUseDefineForClassFields.js
  tests/baselines/reference/privateNameBadSuperUseDefineForClassFields.symbols
  tests/baselines/reference/privateNameBadSuperUseDefineForClassFields.types
  tests/cases/conformance/classes/members/privateNames/privateNameBadSuperUseDefineForClassFields.ts
Labels: Author: Team

#37970 Fix js declaration emit for inherited and this-typed inherited fields
  src/compiler/checker.ts
  tests/baselines/reference/declarationsWithRecursiveInternalTypesProduceUniqueTypeParams.types
  tests/baselines/reference/jsDeclarationsInterfaces.js
  tests/baselines/reference/jsDeclarationsThisTypes.js
  tests/baselines/reference/jsDeclarationsThisTypes.symbols
  tests/baselines/reference/jsDeclarationsThisTypes.types
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsThisTypes.ts
Labels: Author: Team

#37851 Delay pulling on signature contextual type until absolutely needed
  src/compiler/checker.ts
  tests/baselines/reference/reverseMappedTypeContextualTypeNotCircular.errors.txt
  tests/baselines/reference/reverseMappedTypeContextualTypeNotCircular.js
  tests/baselines/reference/reverseMappedTypeContextualTypeNotCircular.symbols
  tests/baselines/reference/reverseMappedTypeContextualTypeNotCircular.types
  tests/cases/compiler/reverseMappedTypeContextualTypeNotCircular.ts
Labels: Author: Team

#38027 Navto covers all projects
  src/server/protocol.ts
  src/server/session.ts
  src/testRunner/unittests/tsserver/declarationFileMaps.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
Labels: Author: Team

#37846 Fix preserveNewlines printer option when a list child has the same start or end as its parent
  src/compiler/emitter.ts
  src/compiler/utilities.ts
  tests/cases/fourslash/textChangesPreserveNewlines8.ts
Labels: Author: Team

#37921 Add check for delete expression must be optional
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/controlFlowDeleteOperator.errors.txt
  tests/baselines/reference/deleteChain.errors.txt
  tests/baselines/reference/deleteExpressionMustBeOptional(strict=false).errors.txt
  tests/baselines/reference/deleteExpressionMustBeOptional(strict=false).js
  tests/baselines/reference/deleteExpressionMustBeOptional(strict=false).symbols
  tests/baselines/reference/deleteExpressionMustBeOptional(strict=false).types
  tests/baselines/reference/deleteExpressionMustBeOptional(strict=true).errors.txt
  tests/baselines/reference/deleteExpressionMustBeOptional(strict=true).js
  tests/baselines/reference/deleteExpressionMustBeOptional(strict=true).symbols
  tests/baselines/reference/deleteExpressionMustBeOptional(strict=true).types
  tests/baselines/reference/privateNamesNoDelete.errors.txt
  tests/cases/compiler/deleteExpressionMustBeOptional.ts
Labels: For Uncommitted Bug

#37906 fix(37825): js extended class autocomplete includes extender's private fields
  src/services/completions.ts
  tests/cases/fourslash/completionListClassPrivateFields.ts
  tests/cases/fourslash/completionListClassPrivateFields_JS.ts
Labels: For Uncommitted Bug

#38116 Filter undefined only in binding patterns in parameters w/initialiser
  src/compiler/checker.ts
  tests/baselines/reference/contextualTypeForInitalizedVariablesFiltersUndefined.errors.txt
  tests/baselines/reference/contextualTypeForInitalizedVariablesFiltersUndefined.js
  tests/baselines/reference/contextualTypeForInitalizedVariablesFiltersUndefined.symbols
  tests/baselines/reference/contextualTypeForInitalizedVariablesFiltersUndefined.types
  tests/cases/compiler/contextualTypeForInitalizedVariablesFiltersUndefined.ts
Labels: Author: Team

#36015 Prefer a likely literal over anonymous type in --noImplicitAny codefixes
  src/services/codefixes/inferFromUsage.ts
  src/services/textChanges.ts
  tests/cases/fourslash/codeFixInferFromUsageParameterLiteral.ts
  tests/cases/fourslash/codeFixInferFromUsagePropertyAccess.ts
  tests/cases/fourslash/codeFixInferFromUsagePropertyAccessJS.ts
  tests/cases/fourslash/codeFixInferFromUsageVariableLiteral.ts
Labels: For Backlog Bug

#38122 Filter undefined from binding elements with initialisers without undefined in the type
  src/compiler/checker.ts
  tests/baselines/reference/contextualTypeForInitalizedVariablesFiltersUndefined.errors.txt
  tests/baselines/reference/contextualTypeForInitalizedVariablesFiltersUndefined.js
  tests/baselines/reference/contextualTypeForInitalizedVariablesFiltersUndefined.symbols
  tests/baselines/reference/contextualTypeForInitalizedVariablesFiltersUndefined.types
  tests/cases/compiler/contextualTypeForInitalizedVariablesFiltersUndefined.ts
Labels: Author: Team

#38119 Fix newline issues when adding multiple imports
  src/compiler/core.ts
  src/services/codefixes/importFixes.ts
  src/services/refactors/moveToNewFile.ts
  src/services/textChanges.ts
  src/services/utilities.ts
  tests/cases/fourslash/importNameCodeFix_all2.ts
  tests/cases/fourslash/importNameCodeFix_exportEquals.ts
Labels: Author: Team

#38148 Issue an error on cross-file merges we can't emit
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/transformers/declarations.ts
  src/compiler/types.ts
  tests/baselines/reference/jsDeclarationsCrossfileMerge.errors.txt
  tests/baselines/reference/jsDeclarationsCrossfileMerge.js
  tests/baselines/reference/jsDeclarationsCrossfileMerge.symbols
  tests/baselines/reference/jsDeclarationsCrossfileMerge.types
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsCrossfileMerge.ts
Labels: Author: Team

#38152 convertToAsyncFunction: Disable for `.then` with both fulfillment and rejection handlers
  src/services/suggestionDiagnostics.ts
  src/testRunner/unittests/services/convertToAsyncFunction.ts
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_Rej.ts
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_RejNoBrackets.ts
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_RejRef.ts
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_ResRejNoArgsArrow.js
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_ResRejNoArgsArrow.ts
Labels: Author: Team

#38121 Fix temp variable scoping in async generators
  src/compiler/transformers/es2018.ts
  tests/baselines/reference/nullishCoalescingOperatorInAsyncGenerator(target=es2015).js
  tests/baselines/reference/nullishCoalescingOperatorInAsyncGenerator(target=es5).js
  tests/baselines/reference/nullishCoalescingOperatorInAsyncGenerator(target=esnext).js
  tests/cases/conformance/expressions/nullishCoalescingOperator/nullishCoalescingOperatorInAsyncGenerator.ts
Labels: Author: Team

#38163 Fix truthiness call check for this-property access
  src/compiler/checker.ts
  tests/baselines/reference/truthinessCallExpressionCoercion1.errors.txt
  tests/baselines/reference/truthinessCallExpressionCoercion1.js
  tests/baselines/reference/truthinessCallExpressionCoercion1.symbols
  tests/baselines/reference/truthinessCallExpressionCoercion1.types
  tests/cases/compiler/truthinessCallExpressionCoercion1.ts
Labels: Author: Team

#38151 Special-case export assigned namespaces in getSpecifierForModuleSymbol
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitExportAssignedNamespaceNoTripleSlashTypesReference.js
  tests/baselines/reference/declarationEmitExportAssignedNamespaceNoTripleSlashTypesReference.symbols
  tests/baselines/reference/declarationEmitExportAssignedNamespaceNoTripleSlashTypesReference.types
  tests/cases/compiler/declarationEmitExportAssignedNamespaceNoTripleSlashTypesReference.ts
Labels: Author: Team

#37896 Fix values and types merging in JS module exports
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/utilities.ts
  tests/baselines/reference/jsDeclarationsClassExtendsVisibility.symbols
  tests/baselines/reference/jsDeclarationsClassStatic.symbols
  tests/baselines/reference/jsDeclarationsCrossfileMerge.symbols
  tests/baselines/reference/jsDeclarationsExportAssignedClassExpressionAnonymousWithSub.symbols
  tests/baselines/reference/jsDeclarationsExportAssignedClassExpressionShadowing.symbols
  tests/baselines/reference/jsDeclarationsExportSubAssignments.symbols
  tests/baselines/reference/jsExportMemberMergedWithModuleAugmentation.symbols
  tests/baselines/reference/jsExportMemberMergedWithModuleAugmentation.types
  tests/baselines/reference/jsExportMemberMergedWithModuleAugmentation2.errors.txt
  tests/baselines/reference/jsExportMemberMergedWithModuleAugmentation2.symbols
  tests/baselines/reference/jsExportMemberMergedWithModuleAugmentation2.types
  tests/baselines/reference/moduleExportAlias2.symbols
  tests/baselines/reference/moduleExportAlias4.symbols
  tests/baselines/reference/moduleExportAliasImported.symbols
  tests/baselines/reference/moduleExportPropertyAssignmentDefault.symbols
  tests/baselines/reference/moduleExportWithExportPropertyAssignment3.symbols
  tests/baselines/reference/moduleExportWithExportPropertyAssignment4.symbols
  tests/baselines/reference/typedefCrossModule2.types
  tests/baselines/reference/typedefCrossModule4.types
  tests/cases/compiler/jsExportMemberMergedWithModuleAugmentation.ts
  tests/cases/compiler/jsExportMemberMergedWithModuleAugmentation2.ts
  tests/cases/fourslash/completionsImportModuleAugmentationWithJS.ts
Labels: Author: Team

#38170 Reset error variable in downlevel for-await-of loop
  src/compiler/transformers/es2018.ts
  tests/baselines/reference/emitter.forAwait(target=es2015).js
  tests/baselines/reference/emitter.forAwait(target=es2015).symbols
  tests/baselines/reference/emitter.forAwait(target=es2015).types
  tests/baselines/reference/emitter.forAwait(target=es2017).js
  tests/baselines/reference/emitter.forAwait(target=es2017).symbols
  tests/baselines/reference/emitter.forAwait(target=es2017).types
  tests/baselines/reference/emitter.forAwait(target=es2018).js
  tests/baselines/reference/emitter.forAwait(target=es2018).symbols
  tests/baselines/reference/emitter.forAwait(target=es2018).types
  tests/baselines/reference/emitter.forAwait(target=es5).js
  tests/baselines/reference/emitter.forAwait(target=es5).symbols
  tests/baselines/reference/emitter.forAwait(target=es5).types
  tests/cases/conformance/emitter/es2015/forAwait/emitter.forAwait.es2015.ts
  tests/cases/conformance/emitter/es2017/forAwait/emitter.forAwait.es2017.ts
  tests/cases/conformance/emitter/es5/forAwait/emitter.forAwait.es5.ts
  tests/cases/conformance/statements/for-await-ofStatements/emitter.forAwait.ts
Labels: Author: Team

#38172 Revert #37106
  src/compiler/checker.ts
  tests/baselines/reference/inKeywordTypeguard.errors.txt
  tests/baselines/reference/inKeywordTypeguard.types
Labels: Author: Team

#38101 Skip comparing optional property flag when comparing against discriminant properties
  src/compiler/checker.ts
  tests/baselines/reference/unionRelationshipCheckPasses.js
  tests/baselines/reference/unionRelationshipCheckPasses.symbols
  tests/baselines/reference/unionRelationshipCheckPasses.types
  tests/cases/compiler/unionRelationshipCheckPasses.ts
Labels: Author: Team

#37784 this: undefined in modules
  src/compiler/checker.ts
  tests/baselines/reference/inlineJsxFactoryDeclarationsLocalTypes.errors.txt
  tests/baselines/reference/inlineJsxFactoryDeclarationsLocalTypes.symbols
  tests/baselines/reference/inlineJsxFactoryDeclarationsLocalTypes.types
  tests/baselines/reference/thisInInvalidContextsExternalModule.errors.txt
  tests/baselines/reference/thisInInvalidContextsExternalModule.symbols
  tests/baselines/reference/thisInInvalidContextsExternalModule.types
  tests/baselines/reference/topLevelLambda4.errors.txt
  tests/baselines/reference/topLevelLambda4.symbols
  tests/baselines/reference/topLevelLambda4.types
  tests/baselines/reference/tsxAttributeResolution15.errors.txt
  tests/baselines/reference/tsxAttributeResolution15.symbols
  tests/baselines/reference/tsxAttributeResolution15.types
  tests/baselines/reference/tsxSpreadAttributesResolution4.errors.txt
  tests/baselines/reference/tsxSpreadAttributesResolution4.symbols
  tests/baselines/reference/tsxSpreadAttributesResolution4.types
Labels: Author: Team, For Milestone Bug

#38031 Adds support for looking up past Blocks in expando objects
  src/compiler/binder.ts
  src/compiler/utilities.ts
  tests/baselines/reference/topLevelBlockExpando.symbols
  tests/baselines/reference/topLevelBlockExpando.types
  tests/cases/compiler/topLevelBlockExpando.ts
Labels: Author: Team

#35219 Fix: convertFunctionToEs6Class cannot recognize `x.prototype = {}` pattern
  src/services/codefixes/convertFunctionToEs6Class.ts
  tests/cases/fourslash/convertFunctionToEs6Class-propertyMember.ts
  tests/cases/fourslash/convertFunctionToEs6Class-prototypeAccessor.ts
  tests/cases/fourslash/convertFunctionToEs6Class-prototypeMethod.ts
  tests/cases/fourslash/convertFunctionToEs6Class-removeConstructor.ts
  tests/cases/fourslash/convertFunctionToEs6Class-removeConstructor2.ts
Labels: For Backlog Bug

#38272 Fix crash on duplicate default exports
  src/compiler/binder.ts
  tests/baselines/reference/exportDefaultDuplicateCrash.errors.txt
  tests/baselines/reference/exportDefaultDuplicateCrash.js
  tests/cases/compiler/exportDefaultDuplicateCrash.ts
Labels: Author: Team
