Repository microsoft/TypeScript, pull requests merged in 2020-03, with the labels that each got.

#37114 Remove bogus @implements errors
  src/compiler/checker.ts
  src/compiler/utilities.ts
  tests/baselines/reference/jsdocImplements_class.errors.txt
  tests/baselines/reference/jsdocImplements_class.js
  tests/baselines/reference/jsdocImplements_class.symbols
  tests/baselines/reference/jsdocImplements_class.types
  tests/cases/conformance/jsdoc/jsdocImplements_class.ts
Labels: Author: Team

#37162 Use merged symbol to pick up js-alias-merged members on export assignments
  src/compiler/checker.ts
  tests/baselines/reference/jsDeclarationsExportDoubleAssignmentInClosure.js
  tests/baselines/reference/jsDeclarationsExportDoubleAssignmentInClosure.symbols
  tests/baselines/reference/jsDeclarationsExportDoubleAssignmentInClosure.types
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsExportDoubleAssignmentInClosure.ts
Labels: Author: Team

#37124 Retain reexports in js emit even when they export nothing
  src/compiler/transformers/ts.ts
  tests/baselines/reference/declarationEmitAliasExportStar.js
  tests/baselines/reference/es6ExportEqualsInterop.js
  tests/baselines/reference/exportStarForValues.js
  tests/baselines/reference/exportStarForValues10.js
  tests/baselines/reference/exportStarForValues2.js
  tests/baselines/reference/exportStarForValues3.js
  tests/baselines/reference/exportStarForValues4.js
  tests/baselines/reference/exportStarForValues5.js
  tests/baselines/reference/exportStarForValues6.js
  tests/baselines/reference/exportStarForValues7.js
  tests/baselines/reference/exportStarForValues8.js
  tests/baselines/reference/exportStarForValues9.js
  tests/baselines/reference/exportStarForValuesInSystem.js
  tests/baselines/reference/exportStarNotElided.js
  tests/baselines/reference/exportStarNotElided.symbols
  tests/baselines/reference/exportStarNotElided.types
  tests/baselines/reference/moduleDeclarationExportStarShadowingGlobalIsNameable.js
  tests/baselines/reference/symbolLinkDeclarationEmitModuleNames.js
  tests/baselines/reference/tsbuild/watchMode/reexport/Reports-errors-correctly.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependencies/updates-errors-when-file-transitively-exported-file-changes/when-there-are-circular-import-and-exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependencies/updates-errors-when-file-transitively-exported-file-changes/when-there-are-no-circular-import-and-exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependenciesAndD/updates-errors-when-file-transitively-exported-file-changes/when-there-are-circular-import-and-exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependenciesAndD/updates-errors-when-file-transitively-exported-file-changes/when-there-are-no-circular-import-and-exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/default/updates-errors-when-file-transitively-exported-file-changes/when-there-are-circular-import-and-exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/default/updates-errors-when-file-transitively-exported-file-changes/when-there-are-no-circular-import-and-exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/defaultAndD/updates-errors-when-file-transitively-exported-file-changes/when-there-are-circular-import-and-exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/defaultAndD/updates-errors-when-file-transitively-exported-file-changes/when-there-are-no-circular-import-and-exports.js
  tests/cases/compiler/exportStarNotElided.ts
Labels: Author: Team, Breaking Change

#33414 fix: Intl.PluralRulesOptions to behave according to spec
  src/lib/es2018.intl.d.ts
Labels: For Milestone Bug

#36858 Clean up convert-to-async refactor
  src/services/codefixes/convertToAsyncFunction.ts
  src/services/utilities.ts
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_InnerPromise.ts
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_basicWithComments.ts
Labels: Author: Team

#29571 Reinterpret a type parameter constrained to any as an upper bound constraint
  src/compiler/checker.ts
  tests/baselines/reference/contextuallyTypedParametersWithInitializers.types
  tests/baselines/reference/jsxExcessPropsAndAssignability.errors.txt
  tests/baselines/reference/jsxExcessPropsAndAssignability.js
  tests/baselines/reference/jsxExcessPropsAndAssignability.symbols
  tests/baselines/reference/jsxExcessPropsAndAssignability.types
  tests/baselines/reference/mappedTypeWithAny.types
  tests/baselines/reference/typeArgumentInferenceWithConstraints.types
  tests/baselines/reference/typeParameterConstraints1.types
  tests/baselines/reference/typeParameterExplicitlyExtendsAny.errors.txt
  tests/baselines/reference/typeParameterExplicitlyExtendsAny.symbols
  tests/baselines/reference/typeParameterExplicitlyExtendsAny.types
  tests/baselines/reference/varianceProblingAndZeroOrderIndexSignatureRelationsAlign.js
  tests/baselines/reference/varianceProblingAndZeroOrderIndexSignatureRelationsAlign.symbols
  tests/baselines/reference/varianceProblingAndZeroOrderIndexSignatureRelationsAlign.types
  tests/baselines/reference/varianceProblingAndZeroOrderIndexSignatureRelationsAlign2.js
  tests/baselines/reference/varianceProblingAndZeroOrderIndexSignatureRelationsAlign2.symbols
  tests/baselines/reference/varianceProblingAndZeroOrderIndexSignatureRelationsAlign2.types
  tests/cases/compiler/jsxExcessPropsAndAssignability.tsx
  tests/cases/compiler/varianceProblingAndZeroOrderIndexSignatureRelationsAlign.ts
  tests/cases/compiler/varianceProblingAndZeroOrderIndexSignatureRelationsAlign2.ts
Labels: Author: Team, Breaking Change, For Milestone Bug

#37159 Remove incorrect non-null assertion in `getRenameInfoForNode`
  src/services/rename.ts
Labels: Author: Team

#37170 Thread host.useCaseSensitiveFileNames through program and node builder into specifier generation
  src/compiler/checker.ts
  src/compiler/program.ts
  src/compiler/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/missingMemberErrorHasShortPath.errors.txt
  tests/baselines/reference/missingMemberErrorHasShortPath.js
  tests/baselines/reference/missingMemberErrorHasShortPath.symbols
  tests/baselines/reference/missingMemberErrorHasShortPath.types
  tests/cases/compiler/missingMemberErrorHasShortPath.ts
Labels: Author: Team

#37176 Emit an `any` for namepath types
  src/compiler/checker.ts
  tests/baselines/reference/jsDeclarationsModuleReferenceHasEmit.js
  tests/baselines/reference/jsDeclarationsModuleReferenceHasEmit.symbols
  tests/baselines/reference/jsDeclarationsModuleReferenceHasEmit.types
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsModuleReferenceHasEmit.ts
Labels: Author: Team

#37168 fix(36238): No spelling suggestion/quick fix for misspelled uses of an import
  src/compiler/checker.ts
  tests/cases/fourslash/codeFixSpelling6.ts
Labels: For Milestone Bug

#37192 More precise property-overwritten-by-spread errors
  src/compiler/checker.ts
  tests/baselines/reference/objectSpreadSetonlyAccessor.errors.txt
  tests/baselines/reference/spreadOverwritesPropertyStrict.errors.txt
  tests/baselines/reference/spreadOverwritesPropertyStrict.js
  tests/baselines/reference/spreadOverwritesPropertyStrict.symbols
  tests/baselines/reference/spreadOverwritesPropertyStrict.types
  tests/cases/conformance/types/spread/spreadOverwritesPropertyStrict.ts
Labels: Author: Team

#37173 Preserve arity for preserving js optional parameters
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/jsDeclarationsClassLeadingOptional.js
  tests/baselines/reference/jsDeclarationsClassLeadingOptional.symbols
  tests/baselines/reference/jsDeclarationsClassLeadingOptional.types
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsClassLeadingOptional.ts
Labels: Author: Team

#37164 Don't crash when there's no class type to derive a 'this' type from
  src/compiler/checker.ts
  tests/baselines/reference/allowJsClassThisTypeCrash.symbols
  tests/baselines/reference/allowJsClassThisTypeCrash.types
  tests/cases/compiler/allowJsClassThisTypeCrash.ts
Labels: Author: Team

#37019 Fix emitting `?.`
  src/compiler/emitter.ts
  src/compiler/utilities.ts
  src/compiler/visitorPublic.ts
  src/services/textChanges.ts
  tests/baselines/reference/propertyAccessExpressionInnerComments.js
  tests/baselines/reference/propertyAccessExpressionInnerComments.symbols
  tests/baselines/reference/propertyAccessExpressionInnerComments.types
  tests/cases/compiler/propertyAccessExpressionInnerComments.ts
  tests/cases/fourslash/extract-const2.ts
  tests/cases/fourslash/extract-const3.ts
Labels: Author: Team

#34501 Don't inferFromIndexTypes() twice
  src/compiler/checker.ts
  tests/baselines/reference/correctOrderOfPromiseMethod.js
  tests/baselines/reference/correctOrderOfPromiseMethod.symbols
  tests/baselines/reference/correctOrderOfPromiseMethod.types
  tests/baselines/reference/restTupleElements1.types
  tests/baselines/reference/typeInferenceWithTupleType.js
  tests/baselines/reference/typeInferenceWithTupleType.symbols
  tests/baselines/reference/typeInferenceWithTupleType.types
  tests/cases/compiler/correctOrderOfPromiseMethod.ts
  tests/cases/conformance/types/tuple/typeInferenceWithTupleType.ts
Labels: For Milestone Bug

#33845 add string.prototype.replaceAll
  src/compiler/commandLineParser.ts
  src/lib/esnext.d.ts
  src/lib/esnext.string.d.ts
  src/lib/libs.json
  src/testRunner/unittests/config/commandLineParsing.ts
  src/testRunner/unittests/config/convertCompilerOptionsFromJson.ts
  tests/baselines/reference/tsc/runWithoutArgs/initial-build/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
Labels: For Milestone Bug

#36014 Added @ts-expect-error to @ts-ignore directives
  src/compiler/diagnosticMessages.json
  src/compiler/parser.ts
  src/compiler/program.ts
  src/compiler/scanner.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/services/services.ts
  tests/baselines/reference/ts-expect-error.errors.txt
  tests/baselines/reference/ts-expect-error.js
  tests/baselines/reference/ts-expect-error.symbols
  tests/baselines/reference/ts-expect-error.types
  tests/baselines/reference/ts-ignore.errors.txt
  tests/baselines/reference/ts-ignore.js
  tests/baselines/reference/ts-ignore.symbols
  tests/baselines/reference/ts-ignore.types
  tests/cases/conformance/directives/ts-expect-error.ts
  tests/cases/conformance/directives/ts-ignore.ts
Labels: For Backlog Bug

#37233 Reinstate incorrectly removed esnext.bigint
  src/compiler/commandLineParser.ts
  src/testRunner/unittests/config/commandLineParsing.ts
  src/testRunner/unittests/config/convertCompilerOptionsFromJson.ts
  tests/baselines/reference/tsc/runWithoutArgs/initial-build/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
Labels: Author: Team

#28163 Fixes duplicated comment when executing code fix to add missing enum …
  src/services/codefixes/fixAddMissingMember.ts
  tests/cases/fourslash/codeFixAddMissingEnumMember12.ts
Labels: For Backlog Bug

#37266 Reset hasChangedAutomaticTypeDirectiveNames once new program is created
  src/compiler/watchPublic.ts
  src/testRunner/unittests/tsbuild/watchMode.ts
  src/testRunner/unittests/tscWatch/consoleClearing.ts
  src/testRunner/unittests/tscWatch/helpers.ts
  src/testRunner/unittests/tscWatch/programUpdates.ts
  src/testRunner/unittests/tscWatch/resolutionCache.ts
  tests/baselines/reference/tscWatch/resolutionCache/when-types-in-compiler-option-are-global-and-installed-at-later-point.js
Labels: Author: Team

#37264 Fix longer type-only property access in non-emitting heritage clauses
  src/compiler/utilities.ts
  tests/baselines/reference/nestedNamespace.js
  tests/baselines/reference/nestedNamespace.symbols
  tests/baselines/reference/nestedNamespace.types
  tests/cases/conformance/externalModules/typeOnly/nestedNamespace.ts
Labels: Author: Team

#37305 Fix lint error in release-3.8
  src/compiler/binder.ts
Labels: Author: Team

#33917 cleanup: remove unused variable assignment
  scripts/buildProtocol.ts
Labels: Housekeeping

#37308 Handle WatchCompilerHost without timeout methods to retrieve correct program
  src/compiler/watchPublic.ts
  src/testRunner/unittests/tscWatch/watchApi.ts
Labels: Author: Team

#34756 Support NetBSD platform
  src/tsserver/server.ts
Labels: For Backlog Bug

#33574 Add flag to omit default case in getSwitchClauseTypeOfWitnesses
  src/compiler/checker.ts
Labels: For Backlog Bug

#33844 add promise.any
  src/compiler/commandLineParser.ts
  src/lib/esnext.d.ts
  src/lib/esnext.promise.d.ts
  src/lib/libs.json
  src/testRunner/unittests/config/commandLineParsing.ts
  src/testRunner/unittests/config/convertCompilerOptionsFromJson.ts
  tests/baselines/reference/tsc/runWithoutArgs/initial-build/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
Labels: For Milestone Bug

#36845 Add constructor functions for {Symbol,Node}Links
  src/compiler/checker.ts
Labels: For Backlog Bug

#32774 Implement constructor type guard
  src/compiler/checker.ts
  src/compiler/utilities.ts
  tests/baselines/reference/typeGuardConstructorClassAndNumber.errors.txt
  tests/baselines/reference/typeGuardConstructorClassAndNumber.js
  tests/baselines/reference/typeGuardConstructorClassAndNumber.symbols
  tests/baselines/reference/typeGuardConstructorClassAndNumber.types
  tests/baselines/reference/typeGuardConstructorDerivedClass.errors.txt
  tests/baselines/reference/typeGuardConstructorDerivedClass.js
  tests/baselines/reference/typeGuardConstructorDerivedClass.symbols
  tests/baselines/reference/typeGuardConstructorDerivedClass.types
  tests/baselines/reference/typeGuardConstructorNarrowAny.js
  tests/baselines/reference/typeGuardConstructorNarrowAny.symbols
  tests/baselines/reference/typeGuardConstructorNarrowAny.types
  tests/baselines/reference/typeGuardConstructorNarrowPrimitivesInUnion.js
  tests/baselines/reference/typeGuardConstructorNarrowPrimitivesInUnion.symbols
  tests/baselines/reference/typeGuardConstructorNarrowPrimitivesInUnion.types
  tests/baselines/reference/typeGuardConstructorPrimitiveTypes.js
  tests/baselines/reference/typeGuardConstructorPrimitiveTypes.symbols
  tests/baselines/reference/typeGuardConstructorPrimitiveTypes.types
  tests/cases/compiler/typeGuardConstructorClassAndNumber.ts
  tests/cases/compiler/typeGuardConstructorDerivedClass.ts
  tests/cases/compiler/typeGuardConstructorNarrowAny.ts
  tests/cases/compiler/typeGuardConstructorNarrowPrimitivesInUnion.ts
  tests/cases/compiler/typeGuardConstructorPrimitiveTypes.ts
Labels: For Backlog Bug

#37055 Optimize module resolution cache for watch and editor
  src/compiler/moduleNameResolver.ts
  src/compiler/resolutionCache.ts
  src/compiler/types.ts
  src/compiler/watchPublic.ts
  src/executeCommandLine/executeCommandLine.ts
  src/testRunner/unittests/tscWatch/helpers.ts
  src/testRunner/unittests/tscWatch/programUpdates.ts
  src/testRunner/unittests/tscWatch/resolutionCache.ts
  src/testRunner/unittests/tsserver/events/projectUpdatedInBackground.ts
  src/testRunner/unittests/tsserver/resolutionCache.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team

#37350 Update user test baseline script to diff against a single authoratative WIP master branch
  scripts/open-user-pr.ts
Labels: Author: Team

#37121 Increase the idle time before which ensureProject for open file is called
  src/server/editorServices.ts
  src/server/project.ts
Labels: Author: Team

#37359 adds error message for using value as type argument
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/allowImportClausesToMergeWithTypes.errors.txt
  tests/baselines/reference/intrinsics.errors.txt
  tests/baselines/reference/parserAmbiguityWithBinaryOperator4.errors.txt
  tests/baselines/reference/typeAssertions.errors.txt
  tests/baselines/reference/typeGuardFunctionErrors.errors.txt
Labels: For Backlog Bug

#37370 Move useSourceOfProjectReferenceRedirect to program so other hosts can use it too, enabling it for WatchHost
  src/compiler/program.ts
  src/compiler/resolutionCache.ts
  src/compiler/types.ts
  src/compiler/watchPublic.ts
  src/server/editorServices.ts
  src/server/project.ts
  src/services/services.ts
  src/services/types.ts
  src/testRunner/tsconfig.json
  src/testRunner/unittests/tscWatch/helpers.ts
  src/testRunner/unittests/tscWatch/sourceOfProjectReferenceRedirect.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team

#35427 add config to insert space for empty braces
  src/services/formatting/rules.ts
  src/services/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/formattingOptionsChange.ts
Labels: For Backlog Bug

#32643 make splice `deleteCount` required in es5.d.ts
  src/lib/es2015.core.d.ts
  src/lib/es5.d.ts
  tests/baselines/reference/arraySlice.types
  tests/baselines/reference/invalidSplice.types
  tests/baselines/reference/jsDeclarationsImportTypeBundled.types
  tests/baselines/reference/jsDeclarationsTypeReassignmentFromDeclaration.types
  tests/baselines/reference/jsDeclarationsTypeReassignmentFromDeclaration2.types
  tests/baselines/reference/parserharness.types
  tests/baselines/reference/restInvalidArgumentType.types
  tests/baselines/reference/restParameterWithBindingPattern3.types
  tests/baselines/reference/restPropertyWithBindingPattern.types
  tests/baselines/reference/spliceES5.errors.txt
  tests/baselines/reference/spliceES5.js
  tests/baselines/reference/spliceES5.symbols
  tests/baselines/reference/spliceES5.types
  tests/baselines/reference/spliceES6.js
  tests/baselines/reference/spliceES6.symbols
  tests/baselines/reference/spliceES6.types
  tests/baselines/reference/spreadInvalidArgumentType.types
  tests/baselines/reference/staticAnonymousTypeNotReferencingTypeParameter.types
  tests/baselines/reference/taggedTemplateStringsWithOverloadResolution3_ES6.errors.txt
  tests/cases/compiler/spliceES5.ts
  tests/cases/compiler/spliceES6.ts
Labels: For Backlog Bug

#36289 Don't parse duplicate JSDoc for ExpressionStatement starting with ParenthesizedExpression
  src/compiler/parser.ts
  tests/baselines/reference/jsdocTypedefBeforeParenthesizedExpression.symbols
  tests/baselines/reference/jsdocTypedefBeforeParenthesizedExpression.types
  tests/cases/compiler/jsdocTypedefBeforeParenthesizedExpression.ts
Labels: For Backlog Bug

#36301 More clear comment for String.prototype.match()
  src/lib/es2015.symbol.wellknown.d.ts
Labels: For Backlog Bug

#36911 fix(36102): fix extra new line in Organize Imports
  src/services/textChanges.ts
Labels: For Milestone Bug

#33879 Add implementation for fixExpectedComma
  src/services/codefixes/fixExpectedComma.ts
  src/services/tsconfig.json
  tests/cases/fourslash/codeFixExpectedComma01.ts
  tests/cases/fourslash/codeFixExpectedComma02.ts
  tests/cases/fourslash/codeFixExpectedComma03.ts
Labels: For Backlog Bug

#37372 Remove 'path' from assert call
  src/services/services.ts
Labels: Author: Team

#35922 Treat write-only-access to a class member with setter as a reference.
  src/compiler/checker.ts
  tests/baselines/reference/unusedPrivateMembers.errors.txt
  tests/baselines/reference/unusedPrivateMembers.js
  tests/baselines/reference/unusedPrivateMembers.symbols
  tests/baselines/reference/unusedPrivateMembers.types
  tests/cases/compiler/unusedPrivateMembers.ts
Labels: For Backlog Bug

#37373 Fix crash when host.getSourceFile returns undefined
  src/compiler/checker.ts
Labels: Author: Team

#33688 Support template literals in preProcess (fixes #33680)
  src/services/preProcess.ts
  src/testRunner/unittests/services/preProcessFile.ts
Labels: For Backlog Bug

#36317 Show token hints for missing closing braces
  src/compiler/parser.ts
  tests/baselines/reference/missingCloseBraceInObjectLiteral.errors.txt
  tests/baselines/reference/missingCloseBraceInObjectLiteral.js
  tests/baselines/reference/missingCloseBraceInObjectLiteral.symbols
  tests/baselines/reference/missingCloseBraceInObjectLiteral.types
  tests/baselines/reference/nestedClassDeclaration.errors.txt
  tests/baselines/reference/objectLiteralWithSemicolons4.errors.txt
  tests/baselines/reference/objectSpreadNegativeParse.errors.txt
  tests/baselines/reference/parseErrorIncorrectReturnToken.errors.txt
  tests/baselines/reference/parserErrorRecovery_ObjectLiteral2.errors.txt
  tests/baselines/reference/parserErrorRecovery_ObjectLiteral3.errors.txt
  tests/baselines/reference/parserErrorRecovery_ObjectLiteral4.errors.txt
  tests/baselines/reference/parserErrorRecovery_ObjectLiteral5.errors.txt
  tests/cases/compiler/missingCloseBraceInObjectLiteral.ts
Labels: For Backlog Bug

#37309 Filter the type of a binding pattern to not include undefined is the pattern parent has an initializer
  src/compiler/checker.ts
  tests/baselines/reference/contextualTypeForInitalizedVariablesFiltersUndefined.js
  tests/baselines/reference/contextualTypeForInitalizedVariablesFiltersUndefined.symbols
  tests/baselines/reference/contextualTypeForInitalizedVariablesFiltersUndefined.types
  tests/cases/compiler/contextualTypeForInitalizedVariablesFiltersUndefined.ts
Labels: Author: Team

#36740 [minor] Adds some docs to the LSP interface
  src/harness/harnessLanguageService.ts
  src/services/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team

#36632 feat(36249): Declare property quick fix should add private properties (or be configurable)
  src/compiler/diagnosticMessages.json
  src/services/codefixes/fixAddMissingMember.ts
  src/services/refactors/generateGetAccessorAndSetAccessor.ts
  src/services/utilities.ts
  tests/cases/fourslash/codeFixAddMissingMember17.ts
Labels: For Uncommitted Bug

#37239 Handle when default project for file is solution with file actually referenced by one of the project references
  src/server/editorServices.ts
  src/server/project.ts
  src/server/session.ts
  src/testRunner/unittests/publicApi.ts
  src/testRunner/unittests/tsserver/helpers.ts
  src/testRunner/unittests/tsserver/projectReferences.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
Labels: Author: Team

#37374 Add outlining spans for case clauses
  src/services/outliningElementsCollector.ts
  tests/cases/fourslash/getOutliningSpans.ts
  tests/cases/fourslash/outliningSpansSwitchCases.ts
  tests/cases/fourslash/shims-pp/getOutliningSpans.ts
  tests/cases/fourslash/shims/getOutliningSpans.ts
Labels: Author: Team

#37348 Make substitution types even if the substitution base isnt a type variable
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/inlineConditionalHasSimilarAssignability.js
  tests/baselines/reference/inlineConditionalHasSimilarAssignability.symbols
  tests/baselines/reference/inlineConditionalHasSimilarAssignability.types
  tests/cases/compiler/inlineConditionalHasSimilarAssignability.ts
Labels: Author: Team

#37152 feat(33792): Add quick fix for `This condition will always return true since the function is always defined. Did you mean to call it instead
  src/compiler/diagnosticMessages.json
  src/services/codefixes/fixMissingCallParentheses.ts
  src/services/tsconfig.json
  tests/cases/fourslash/codeFixMissingCallParentheses1.ts
  tests/cases/fourslash/codeFixMissingCallParentheses10.ts
  tests/cases/fourslash/codeFixMissingCallParentheses11.ts
  tests/cases/fourslash/codeFixMissingCallParentheses2.ts
  tests/cases/fourslash/codeFixMissingCallParentheses3.ts
  tests/cases/fourslash/codeFixMissingCallParentheses4.ts
  tests/cases/fourslash/codeFixMissingCallParentheses5.ts
  tests/cases/fourslash/codeFixMissingCallParentheses6.ts
  tests/cases/fourslash/codeFixMissingCallParentheses7.ts
  tests/cases/fourslash/codeFixMissingCallParentheses8.ts
  tests/cases/fourslash/codeFixMissingCallParentheses9.ts
Labels: For Uncommitted Bug

#36905 Add trimTrailingWhitespace Editor Option
  src/server/protocol.ts
  src/services/formatting/formatting.ts
  src/services/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/formatDocumentPreserveTrailingWhitespace.ts
  tests/cases/fourslash/formatSelectionPreserveTrailingWhitespace.ts
  tests/cases/fourslash/fourslash.ts
Labels: Author: Team

#36668 Add valueOf declarations for TypedArrays
  src/lib/es2020.bigint.d.ts
  src/lib/es5.d.ts
  tests/baselines/reference/valueOfTypedArray.js
  tests/baselines/reference/valueOfTypedArray.symbols
  tests/baselines/reference/valueOfTypedArray.types
  tests/cases/compiler/valueOfTypedArray.ts
Labels: For Backlog Bug

#31979 getPropertiesOfUnionOrIntersectionType: handle types with index signature
  src/compiler/checker.ts
  tests/baselines/reference/conditionalTypes2.errors.txt
  tests/cases/fourslash/completionEntryForUnionProperty2.ts
Labels: For Backlog Bug

#37195 Fix assignment of intersections to objects with optional properties
  src/compiler/checker.ts
  tests/baselines/reference/intersectionsAndOptionalProperties.errors.txt
  tests/baselines/reference/intersectionsAndOptionalProperties.js
  tests/baselines/reference/intersectionsAndOptionalProperties.symbols
  tests/baselines/reference/intersectionsAndOptionalProperties.types
  tests/baselines/reference/normalizedIntersectionTooComplex.errors.txt
  tests/baselines/reference/propTypeValidatorInference.js
  tests/baselines/reference/propTypeValidatorInference.symbols
  tests/baselines/reference/propTypeValidatorInference.types
  tests/cases/compiler/intersectionsAndOptionalProperties.ts
  tests/cases/compiler/propTypeValidatorInference.ts
Labels: Breaking Change

#37387 When the imported module is through node_modules and symlink to folder that isnt node_modules
  src/compiler/moduleSpecifiers.ts
  src/harness/fourslashImpl.ts
  src/harness/harnessIO.ts
  src/services/codefixes/importFixes.ts
  tests/cases/fourslash/importFixesWithSymlinkInSiblingRushPnpm.ts
  tests/cases/fourslash/importFixesWithSymlinkInSiblingRushYarn.ts
Labels: Author: Team

#36583 Flatten immediately nested conditional types in the false position
  src/compiler/checker.ts
  tests/baselines/reference/deeplyNestedConditionalTypes.js
  tests/baselines/reference/deeplyNestedConditionalTypes.symbols
  tests/baselines/reference/deeplyNestedConditionalTypes.types
  tests/cases/compiler/deeplyNestedConditionalTypes.ts
Labels: For Backlog Bug

#37422 Add script to work around GH issue with suggested reviewers
  .gitignore
  Gulpfile.js
  scripts/request-pr-review.ts
  scripts/tsconfig.json
Labels: Author: Team

#27565 Add codefix for --noImplicitThis
  src/compiler/diagnosticMessages.json
  src/compiler/factoryPublic.ts
  src/services/codefixes/fixImplicitThis.ts
  src/services/codefixes/inferFromUsage.ts
  src/services/findAllReferences.ts
  src/services/refactors/extractSymbol.ts
  src/services/textChanges.ts
  src/services/tsconfig.json
  src/services/utilities.ts
  tests/cases/fourslash/codeFixImplicitThis_js_all.ts
  tests/cases/fourslash/codeFixImplicitThis_js_classTag.ts
  tests/cases/fourslash/codeFixImplicitThis_js_classTag_addToComment.ts
  tests/cases/fourslash/codeFixImplicitThis_ts_all.ts
  tests/cases/fourslash/codeFixImplicitThis_ts_cantFixNonFunction.ts
  tests/cases/fourslash/codeFixImplicitThis_ts_functionDeclaration.ts
  tests/cases/fourslash/codeFixImplicitThis_ts_functionExpression.ts
  tests/cases/fourslash/codeFixImplicitThis_ts_functionExpression_noName.ts
  tests/cases/fourslash/codeFixImplicitThis_ts_functionExpression_selfReferencing.ts
Labels: For Backlog Bug

#37329 feat(36908): Add related span for conflicting declaration in spread "'prop' is specified more than once" error
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/jsxSpreadOverwritesAttributeStrict.errors.txt
  tests/baselines/reference/jsxSpreadOverwritesAttributeStrict.js
  tests/baselines/reference/jsxSpreadOverwritesAttributeStrict.symbols
  tests/baselines/reference/jsxSpreadOverwritesAttributeStrict.types
  tests/baselines/reference/objectSpreadNegative.errors.txt
  tests/baselines/reference/objectSpreadSetonlyAccessor.errors.txt
  tests/baselines/reference/spreadOverwritesPropertyStrict.errors.txt
  tests/cases/conformance/jsx/jsxSpreadOverwritesAttributeStrict.tsx
Labels: For Backlog Bug

#37077 fix(36936): tsc crashes with: Cannot read property 'get' of undefined
  src/compiler/checker.ts
  tests/baselines/reference/tsxResolveExternalModuleExportsTypes.js
  tests/baselines/reference/tsxResolveExternalModuleExportsTypes.symbols
  tests/baselines/reference/tsxResolveExternalModuleExportsTypes.types
  tests/cases/compiler/tsxResolveExternalModuleExportsTypes.ts
Labels: For Milestone Bug

#37438 Fix declaration emit when the packages are included through symlinks
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/moduleSpecifiers.ts
  src/compiler/program.ts
  src/compiler/transformers/declarations.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/harness/virtualFileSystemWithWatch.ts
  src/services/codefixes/helpers.ts
  src/services/codefixes/importFixes.ts
  src/services/getEditsForFileRename.ts
  src/services/types.ts
  src/services/utilities.ts
  src/testRunner/unittests/tsc/declarationEmit.ts
  src/testRunner/unittests/tscWatch/helpers.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/declarationEmitReexportedSymlinkReference3.errors.txt
  tests/baselines/reference/declarationEmitReexportedSymlinkReference3.js
  tests/baselines/reference/tsc/declarationEmit/initial-build/when-pkg-references-sibling-package-through-indirect-symlink.js
  tests/baselines/reference/tsc/declarationEmit/initial-build/when-same-version-is-referenced-through-source-and-another-symlinked-package.js
  tests/baselines/reference/tsc/declarationEmit/when-pkg-references-sibling-package-through-indirect-symlink-moduleCaseChange.js
  tests/baselines/reference/tsc/declarationEmit/when-pkg-references-sibling-package-through-indirect-symlink.js
  tests/baselines/reference/tsc/declarationEmit/when-same-version-is-referenced-through-source-and-another-symlinked-package-moduleCaseChange.js
  tests/baselines/reference/tsc/declarationEmit/when-same-version-is-referenced-through-source-and-another-symlinked-package-with-indirect-link-moduleCaseChange.js
  tests/baselines/reference/tsc/declarationEmit/when-same-version-is-referenced-through-source-and-another-symlinked-package-with-indirect-link.js
  tests/baselines/reference/tsc/declarationEmit/when-same-version-is-referenced-through-source-and-another-symlinked-package.js
Labels: Author: Team

#35956 Clarified file-not-found error for reference paths without extensions
  src/compiler/diagnosticMessages.json
  src/compiler/program.ts
  tests/baselines/reference/declarationEmitInvalidReferenceAllowJs.errors.txt
  tests/baselines/reference/declarationEmitInvalidReferenceAllowJs.js
  tests/baselines/reference/declarationEmitInvalidReferenceAllowJs.symbols
  tests/baselines/reference/declarationEmitInvalidReferenceAllowJs.types
  tests/baselines/reference/project/invalidRootFile/amd/invalidRootFile.errors.txt
  tests/baselines/reference/project/invalidRootFile/node/invalidRootFile.errors.txt
  tests/cases/compiler/declarationEmitInvalidReferenceAllowJs.ts
Labels: For Backlog Bug

#37285 fix(36247): disallow 'constructor' as a parameter property name
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/parameterPropertyInConstructor3.errors.txt
  tests/baselines/reference/parameterPropertyInConstructor3.js
  tests/baselines/reference/parameterPropertyInConstructor3.symbols
  tests/baselines/reference/parameterPropertyInConstructor3.types
  tests/cases/compiler/parameterPropertyInConstructor3.ts
Labels: For Backlog Bug

#36077 Fix #33732
  tests/baselines/reference/excessPropertyCheckWithUnions.errors.txt
  tests/baselines/reference/excessPropertyCheckWithUnions.js
  tests/baselines/reference/excessPropertyCheckWithUnions.symbols
  tests/baselines/reference/excessPropertyCheckWithUnions.types
  tests/cases/compiler/excessPropertyCheckWithUnions.ts
Labels: For Backlog Bug

#37253 fix(37194): Crash in JS constructors initialized with intermediate `module.exports` assignment
  src/services/goToDefinition.ts
  tests/cases/fourslash/goToDefinitionVariableAssignment.ts
  tests/cases/fourslash/goToDefinitionVariableAssignment1.ts
  tests/cases/fourslash/goToDefinitionVariableAssignment2.ts
  tests/cases/fourslash/goToDefinitionVariableAssignment3.ts
Labels: For Milestone Bug

#37443 Always generate configFileDiag if file is going to be added to configured project
  src/server/editorServices.ts
  src/testRunner/unittests/tsserver/projectErrors.ts
Labels: Author: Team

#37457 Simplify return type of Object.fromEntries
  src/lib/es2019.object.d.ts
  tests/baselines/reference/objectFromEntries.types
Labels: Author: Team

#37310 Allow assertion signatures to narrow by discriminant
  src/compiler/checker.ts
  tests/baselines/reference/assertionFunctionsCanNarrowByDiscriminant.js
  tests/baselines/reference/assertionFunctionsCanNarrowByDiscriminant.symbols
  tests/baselines/reference/assertionFunctionsCanNarrowByDiscriminant.types
  tests/cases/compiler/assertionFunctionsCanNarrowByDiscriminant.ts
Labels: Author: Team

#36688 Preserve newlines from original source when printing nodes from TextChanges
  src/compiler/emitter.ts
  src/compiler/factoryPublic.ts
  src/compiler/scanner.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/harness/fourslashImpl.ts
  src/services/formatting/formatting.ts
  src/services/refactors/extractType.ts
  src/services/textChanges.ts
  tests/baselines/reference/objectLiteralShorthandPropertiesErrorFromNotUsingIdentifier.js
  tests/baselines/reference/objectLiteralShorthandPropertiesErrorWithModule.js
  tests/baselines/reference/objectTypesWithOptionalProperties2.js
  tests/baselines/reference/parserErrorRecovery_ObjectLiteral2.js
  tests/cases/fourslash/extract-const-callback-function-this3.ts
  tests/cases/fourslash/moveToNewFile_declarationKinds.ts
  tests/cases/fourslash/refactorConvertToEs6Module_export_object.ts
  tests/cases/fourslash/refactorConvertToEs6Module_expressionToDeclaration.ts
  tests/cases/fourslash/textChangesPreserveNewlines1.ts
  tests/cases/fourslash/textChangesPreserveNewlines2.ts
  tests/cases/fourslash/textChangesPreserveNewlines3.ts
  tests/cases/fourslash/textChangesPreserveNewlines4.ts
  tests/cases/fourslash/textChangesPreserveNewlines5.ts
  tests/cases/fourslash/textChangesPreserveNewlines6.ts
  tests/cases/fourslash/textChangesPreserveNewlines7.ts
Labels: Author: Team

#37461 Add huge maximal length for noTruncation mode
  src/compiler/checker.ts
  src/compiler/utilities.ts
Labels: Author: Team

#37208 Allow nested conditionals to be related via constraints
  src/compiler/checker.ts
  tests/baselines/reference/circularlyConstrainedMappedTypeContainingConditionalNoInfiniteInstantiationDepth.errors.txt
  tests/baselines/reference/conditionalTypes1.errors.txt
  tests/baselines/reference/conditionalTypes2.errors.txt
  tests/baselines/reference/reactReduxLikeDeferredInferenceAllowsAssignment.errors.txt
  tests/baselines/reference/simplifyingConditionalWithInteriorConditionalIsRelated.js
  tests/baselines/reference/simplifyingConditionalWithInteriorConditionalIsRelated.symbols
  tests/baselines/reference/simplifyingConditionalWithInteriorConditionalIsRelated.types
  tests/cases/compiler/simplifyingConditionalWithInteriorConditionalIsRelated.ts
Labels: Author: Team

#37462 Support rich compile on save emit reponse so we can report diagnostics
  src/compiler/builderState.ts
  src/compiler/builderStatePublic.ts
  src/harness/client.ts
  src/server/project.ts
  src/server/protocol.ts
  src/server/session.ts
  src/services/shims.ts
  src/testRunner/unittests/services/languageService.ts
  src/testRunner/unittests/tsserver/compileOnSave.ts
  src/testRunner/unittests/tsserver/projectReferenceCompileOnSave.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
Labels: Author: Team

#37468 Add code fix for importsNotUsedAsValues error
  src/services/codefixes/convertToTypeOnlyImport.ts
  src/services/tsconfig.json
  tests/cases/fourslash/codeFixConvertToTypeOnlyImport1.ts
  tests/cases/fourslash/codeFixConvertToTypeOnlyImport2.ts
  tests/cases/fourslash/codeFixConvertToTypeOnlyImport3.ts
Labels: Author: Team

#37473 Fix `getSignatureOfTypeTag`
  src/compiler/checker.ts
  tests/baselines/reference/jsdocCallbackAndType.errors.txt
  tests/baselines/reference/jsdocCallbackAndType.symbols
  tests/baselines/reference/jsdocCallbackAndType.types
  tests/cases/compiler/jsdocCallbackAndType.ts
Labels: Author: Team

#37482 Handle auto import scenarios when using project references
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/moduleSpecifiers.ts
  src/compiler/program.ts
  src/compiler/types.ts
  src/services/utilities.ts
  src/testRunner/unittests/tsserver/projectReferenceErrors.ts
  src/testRunner/unittests/tsserver/projectReferences.ts
Labels: Author: Team

#37483 If emitting declaration file, update the d.ts signature in state to not have to save all files when different file changes without changing its shape
  src/compiler/builderState.ts
  src/server/project.ts
  src/testRunner/unittests/tsserver/compileOnSave.ts
Labels: Author: Team

#37502 Bring over last 3.9 dom changes
  src/lib/dom.generated.d.ts
  tests/baselines/reference/intersectionsOfLargeUnions2.errors.txt
Labels: Author: Team

#37508 Handle import type and export type in preprocess
  src/services/preProcess.ts
  src/testRunner/unittests/services/preProcessFile.ts
Labels: Author: Team

#37544 Check JSDocPropetyTag
  src/compiler/checker.ts
  tests/baselines/reference/jsdocPropertyTagInvalid.errors.txt
  tests/baselines/reference/jsdocPropertyTagInvalid.symbols
  tests/baselines/reference/jsdocPropertyTagInvalid.types
  tests/cases/compiler/jsdocPropertyTagInvalid.ts
Labels: Author: Team

#37545 Do not include global errors in semantic errors from the file
  src/server/session.ts
  src/testRunner/unittests/tsserver/helpers.ts
  src/testRunner/unittests/tsserver/projectErrors.ts
  src/testRunner/unittests/tsserver/projectReferenceErrors.ts
Labels: Author: Team

#37463 Convert to async function: handle type arguments to then/catch
  src/compiler/emitter.ts
  src/services/codefixes/convertToAsyncFunction.ts
  src/services/suggestionDiagnostics.ts
  src/testRunner/unittests/services/convertToAsyncFunction.ts
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_catchTypeArgument1.ts
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_thenTypeArgument1.ts
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_thenTypeArgument2.ts
  tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_thenTypeArgument3.ts
Labels: Author: Team

#37568 Revert cloneNode overrides in the DOM
  src/lib/dom.generated.d.ts
  tests/baselines/reference/intersectionsOfLargeUnions2.errors.txt
  tests/baselines/reference/mappedTypeRecursiveInference.errors.txt
  tests/baselines/reference/mappedTypeRecursiveInference.types
Labels: Author: Team

#37563 Handle if reading tsconfig file fails
  src/server/editorServices.ts
  src/testRunner/unittests/tsserver/configuredProjects.ts
Labels: Author: Team

#37312 Add test for #35011
  src/testRunner/unittests/tsserver/projects.ts
Labels: Housekeeping

#37541 Sort the arrays of fileNames in the build info
  src/compiler/builder.ts
  src/harness/fakesHosts.ts
  tests/baselines/reference/tsbuild/demo/initial-build/in-master-branch-with-everything-setup-correctly-and-reports-no-error.js
  tests/baselines/reference/tsbuild/javascriptProjectEmit/initial-build/loads-js-based-projects-and-emits-them-correctly.js
  tests/baselines/reference/tsbuild/javascriptProjectEmit/initial-build/loads-js-based-projects-with-non-moved-json-files-and-emits-them-correctly.js
  tests/baselines/reference/tsbuild/moduleSpecifiers/initial-build/synthesized-module-specifiers-resolve-correctly.js
  tests/baselines/reference/tsbuild/resolveJsonModule/initial-build/importing-json-module-from-project-reference.js
  tests/baselines/reference/tsbuild/watchMode/demo/updates-with-circular-reference.js
Labels: Author: Team

#37307 Ensure computed property names are always checked
  src/compiler/checker.ts
  tests/baselines/reference/jsFileImportPreservedWhenUsed.js
  tests/baselines/reference/jsFileImportPreservedWhenUsed.symbols
  tests/baselines/reference/jsFileImportPreservedWhenUsed.types
  tests/cases/compiler/jsFileImportPreservedWhenUsed.ts
Labels: Author: Team

#37609 Don’t suppress completions after yield
  src/services/completions.ts
  tests/cases/fourslash/completionListInUnclosedYieldExpression01.ts
  tests/cases/fourslash/completionsImportYieldExpression.ts
Labels: Author: Team

#36539 Fix emit for optional chain with non-null assertion
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/debug.ts
  src/compiler/factory.ts
  src/compiler/factoryPublic.ts
  src/compiler/parser.ts
  src/compiler/transformers/es2020.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/compiler/utilitiesPublic.ts
  src/services/utilities.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/callChain.js
  tests/baselines/reference/callChain.symbols
  tests/baselines/reference/callChain.types
  tests/baselines/reference/elementAccessChain.js
  tests/baselines/reference/elementAccessChain.symbols
  tests/baselines/reference/elementAccessChain.types
  tests/baselines/reference/propertyAccessChain.js
  tests/baselines/reference/propertyAccessChain.symbols
  tests/baselines/reference/propertyAccessChain.types
  tests/cases/conformance/expressions/optionalChaining/callChain/callChain.ts
  tests/cases/conformance/expressions/optionalChaining/elementAccessChain/elementAccessChain.ts
  tests/cases/conformance/expressions/optionalChaining/propertyAccessChain/propertyAccessChain.ts
Labels: Author: Team, For Milestone Bug

#37596 Release the documents from language service using paths and keys
  src/services/services.ts
  src/testRunner/unittests/tsserver/dynamicFiles.ts
Labels: Author: Team

#37561 Handle packages inside another node modules package when auto importing
  src/compiler/moduleSpecifiers.ts
  tests/cases/fourslash/importFixesWithPackageJsonInSideAnotherPackage.ts
Labels: Author: Team

#37558 Fix sys.debugMode when using VSCode's new preview debugger
  src/compiler/sys.ts
Labels: Author: Team

#37611 Report error when cannot read file
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  src/server/editorServices.ts
  src/testRunner/unittests/tsserver/configuredProjects.ts
  tests/baselines/reference/tsbuild/configFileErrors/initial-build/when-tsconfig-extends-the-missing-file.js
  tests/baselines/reference/tsbuild/exitCodeOnBogusFile/initial-build/test-exit-code.js
  tests/baselines/reference/tsbuild/watchMode/programUpdates/watches-config-files-that-are-not-present.js
  tests/baselines/reference/tscWatch/programUpdates/config-file-is-deleted.js
Labels: Author: Team

#37606 Support completions for local named exports
  src/services/completions.ts
  tests/cases/fourslash/completionsInExport.ts
  tests/cases/fourslash/completionsInExport_invalid.ts
  tests/cases/fourslash/completionsInExport_moduleBlock.ts
Labels: Author: Team

#37632 Handle comment directives in incremental parsing
  src/compiler/parser.ts
  src/testRunner/unittests/incrementalParser.ts
  src/testRunner/unittests/tsserver/configuredProjects.ts
  src/testRunner/unittests/tsserver/forceConsistentCasingInFileNames.ts
  src/testRunner/unittests/tsserver/helpers.ts
  src/testRunner/unittests/tsserver/openFile.ts
  src/testRunner/unittests/tsserver/projectErrors.ts
  src/testRunner/unittests/tsserver/projectReferences.ts
  src/testRunner/unittests/tsserver/projects.ts
Labels: Author: Team

#37212 feat(37092): Improve error when default-importing from a module that `export *`s from a module with a default export
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/exportStar-amd.errors.txt
  tests/baselines/reference/exportStar.errors.txt
Labels: For Uncommitted Bug

#34932 Fix Number.is* to accept unknown again
  src/lib/es2015.core.d.ts
Labels: For Backlog Bug

#36925 fix(36909): wrong error message when trying to named-import an export
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/es6ImportNamedImportNoNamedExports.errors.txt
  tests/baselines/reference/importNonExportedMember10.errors.txt
  tests/baselines/reference/importNonExportedMember10.symbols
  tests/baselines/reference/importNonExportedMember10.types
  tests/baselines/reference/importNonExportedMember11.errors.txt
  tests/baselines/reference/importNonExportedMember11.symbols
  tests/baselines/reference/importNonExportedMember11.types
  tests/baselines/reference/importNonExportedMember4.errors.txt
  tests/baselines/reference/importNonExportedMember4.js
  tests/baselines/reference/importNonExportedMember4.symbols
  tests/baselines/reference/importNonExportedMember4.types
  tests/baselines/reference/importNonExportedMember5.errors.txt
  tests/baselines/reference/importNonExportedMember5.js
  tests/baselines/reference/importNonExportedMember5.symbols
  tests/baselines/reference/importNonExportedMember5.types
  tests/baselines/reference/importNonExportedMember6.errors.txt
  tests/baselines/reference/importNonExportedMember6.js
  tests/baselines/reference/importNonExportedMember6.symbols
  tests/baselines/reference/importNonExportedMember6.types
  tests/baselines/reference/importNonExportedMember7.errors.txt
  tests/baselines/reference/importNonExportedMember7.js
  tests/baselines/reference/importNonExportedMember7.symbols
  tests/baselines/reference/importNonExportedMember7.types
  tests/baselines/reference/importNonExportedMember8.errors.txt
  tests/baselines/reference/importNonExportedMember8.symbols
  tests/baselines/reference/importNonExportedMember8.types
  tests/baselines/reference/importNonExportedMember9.errors.txt
  tests/baselines/reference/importNonExportedMember9.symbols
  tests/baselines/reference/importNonExportedMember9.types
  tests/cases/compiler/importNonExportedMember10.ts
  tests/cases/compiler/importNonExportedMember11.ts
  tests/cases/compiler/importNonExportedMember4.ts
  tests/cases/compiler/importNonExportedMember5.ts
  tests/cases/compiler/importNonExportedMember6.ts
  tests/cases/compiler/importNonExportedMember7.ts
  tests/cases/compiler/importNonExportedMember8.ts
  tests/cases/compiler/importNonExportedMember9.ts
Labels: For Milestone Bug

#36739 fix(33054): noUnusedLocals not working with array destructuring assignment in for-loop
  src/compiler/checker.ts
  tests/baselines/reference/unusedVariablesWithUnderscoreInForOfLoop.js
  tests/baselines/reference/unusedVariablesWithUnderscoreInForOfLoop.symbols
  tests/baselines/reference/unusedVariablesWithUnderscoreInForOfLoop.types
  tests/baselines/reference/unusedVariablesWithUnderscoreInForOfLoop1.errors.txt
  tests/baselines/reference/unusedVariablesWithUnderscoreInForOfLoop1.js
  tests/baselines/reference/unusedVariablesWithUnderscoreInForOfLoop1.symbols
  tests/baselines/reference/unusedVariablesWithUnderscoreInForOfLoop1.types
  tests/cases/compiler/unusedVariablesWithUnderscoreInForOfLoop.ts
  tests/cases/compiler/unusedVariablesWithUnderscoreInForOfLoop1.ts
Labels: For Backlog Bug

#32702 Improve error message for invalid return type of JSX component
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/inlineJsxFactoryDeclarationsLocalTypes.errors.txt
  tests/baselines/reference/jsxComponentTypeErrors.errors.txt
  tests/baselines/reference/jsxComponentTypeErrors.js
  tests/baselines/reference/jsxComponentTypeErrors.symbols
  tests/baselines/reference/jsxComponentTypeErrors.types
  tests/baselines/reference/tsxElementResolution10.errors.txt
  tests/baselines/reference/tsxElementResolution9.errors.txt
  tests/baselines/reference/tsxSfcReturnUndefinedStrictNullChecks.errors.txt
  tests/baselines/reference/tsxTypeArgumentPartialDefinitionStillErrors.errors.txt
  tests/cases/compiler/jsxComponentTypeErrors.tsx
Labels: For Backlog Bug

#34686 Add link to documentation in tsconfig.json template generated by tsc --init
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/tsConfig/Default initialized TSConfig/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with advanced options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with boolean value compiler options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with enum value compiler options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with files options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with incorrect compiler option value/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with incorrect compiler option/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with list compiler options with enum value/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with list compiler options/tsconfig.json
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/declarationDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/when-outDir-and-declarationDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/when-outDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/with-outFile.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/without-outDir-or-outFile-is-specified.js
Labels: For Backlog Bug

#37205 Fix contextual types for maybe-async callbacks
  src/compiler/checker.ts
  tests/baselines/reference/asyncFunctionContextuallyTypedReturns.js
  tests/baselines/reference/asyncFunctionContextuallyTypedReturns.symbols
  tests/baselines/reference/asyncFunctionContextuallyTypedReturns.types
  tests/cases/compiler/asyncFunctionContextuallyTypedReturns.ts
Labels: Author: Team, For Milestone Bug

#35438 Make never rest type top-like
  src/compiler/checker.ts
  tests/baselines/reference/genericRestTypes.errors.txt
  tests/baselines/reference/genericRestTypes.js
  tests/baselines/reference/genericRestTypes.symbols
  tests/baselines/reference/genericRestTypes.types
  tests/cases/compiler/genericRestTypes.ts
Labels: For Uncommitted Bug

#35862 Fixed issue with unreported error on missing method call in if test.
  src/compiler/checker.ts
  tests/baselines/reference/truthinessCallExpressionCoercion.errors.txt
  tests/baselines/reference/truthinessCallExpressionCoercion.js
  tests/baselines/reference/truthinessCallExpressionCoercion.symbols
  tests/baselines/reference/truthinessCallExpressionCoercion.types
  tests/cases/compiler/truthinessCallExpressionCoercion.ts
Labels: For Backlog Bug

#37652 Don’t offer `this.` completions on `self`, `window`, `global`, `globalThis`. Disambiguate `this.` completions from others in details requests.
  src/compiler/types.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/services/completions.ts
  src/services/utilities.ts
  tests/cases/fourslash/completionsJsxAttributeInitializer.ts
  tests/cases/fourslash/completionsThisProperties_globalSameName.ts
  tests/cases/fourslash/completionsThisProperties_globalType.ts
  tests/cases/fourslash/completionsThisType.ts
  tests/cases/fourslash/fourslash.ts
Labels: Author: Team

#37106 fix(37039): Support 'in' type guard of intersections
  src/compiler/checker.ts
  tests/baselines/reference/inKeywordTypeguard.errors.txt
  tests/baselines/reference/inKeywordTypeguard.js
  tests/baselines/reference/inKeywordTypeguard.symbols
  tests/baselines/reference/inKeywordTypeguard.types
  tests/cases/compiler/inKeywordTypeguard.ts
Labels: For Backlog Bug

#37719 Fix emit of simple module.exports.C.prototype pattern
  src/compiler/checker.ts
  tests/baselines/reference/jsDeclarationsExportAssignedConstructorFunction.js
Labels: Author: Team

#33320 fix #32843 : evaluate right scope when checked if all type parameter …
  src/compiler/checker.ts
  tests/baselines/reference/unusedTypeParameters_templateTag2.errors.txt
  tests/baselines/reference/unusedTypeParameters_templateTag2.symbols
  tests/baselines/reference/unusedTypeParameters_templateTag2.types
  tests/cases/compiler/unusedTypeParameters_templateTag2.ts
Labels: For Backlog Bug
