Repository microsoft/TypeScript, pull requests merged in 2020-07, with the labels that each got.

#39316 Use MS repo for making PR builds of monaco for the playground
  scripts/post-vsts-artifact-comment.js
Labels: Author: Team

#39337 Emit fallback for decorator metadata for type only imports
  src/compiler/checker.ts
  tests/baselines/reference/decoratorMetadataWithTypeOnlyImport.js
  tests/baselines/reference/decoratorMetadataWithTypeOnlyImport.symbols
  tests/baselines/reference/decoratorMetadataWithTypeOnlyImport.types
  tests/cases/conformance/decorators/decoratorMetadataWithTypeOnlyImport.ts
Labels: Author: Team

#39323 Node-based @deprecated checks
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/jsdocDeprecated_suggestion1.ts
  tests/cases/fourslash/jsdocDeprecated_suggestion2.ts
  tests/cases/fourslash/jsdocDeprecated_suggestion3.ts
Labels: Author: Team

#38036 allow consecutive newlines in jsdoc tag comments
  src/compiler/parser.ts
  src/testRunner/unittests/jsDocParsing.ts
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.consecutive newline tokens.json
Labels: For Milestone Bug

#39210 Split the GH actions CI into multiple stages
  .github/tsc.json
  .github/workflows/ci.yml
  Gulpfile.js
Labels: Author: Team

#38859 Adds support for hooking up dev builds of TS to the playground
  scripts/createPlaygroundBuild.js
Labels: Author: Team

#39450 Fix the CI for eslint changes
  Gulpfile.js
  package.json
Labels: Author: Team

#39452 In JS, assignment to `void 0` isn't a declaration
  src/compiler/utilities.ts
  tests/baselines/reference/assignmentToVoidZero1.js
  tests/baselines/reference/assignmentToVoidZero1.symbols
  tests/baselines/reference/assignmentToVoidZero1.types
  tests/baselines/reference/assignmentToVoidZero2.errors.txt
  tests/baselines/reference/assignmentToVoidZero2.js
  tests/baselines/reference/assignmentToVoidZero2.symbols
  tests/baselines/reference/assignmentToVoidZero2.types
  tests/cases/conformance/salsa/assignmentToVoidZero1.ts
  tests/cases/conformance/salsa/assignmentToVoidZero2.ts
Labels: Author: Team

#39457 Parse *= separately in types
  src/compiler/parser.ts
  src/compiler/scanner.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/jsdocParseStarEquals.symbols
  tests/baselines/reference/jsdocParseStarEquals.types
  tests/cases/conformance/jsdoc/jsdocParseStarEquals.ts
Labels: Author: Team

#38099 Don't narrow against unions of constructor functions with instanceof
  src/compiler/checker.ts
  tests/baselines/reference/doesNotNarrowUnionOfConstructorsWithInstanceof.js
  tests/baselines/reference/doesNotNarrowUnionOfConstructorsWithInstanceof.symbols
  tests/baselines/reference/doesNotNarrowUnionOfConstructorsWithInstanceof.types
  tests/cases/compiler/doesNotNarrowUnionOfConstructorsWithInstanceof.ts
Labels: Author: Team, For Milestone Bug

#38045 fix(23871): convertFunctionToEs6Class: Avoid insertNodeAfter
  src/services/codefixes/convertFunctionToEs6Class.ts
  tests/cases/fourslash/convertFunctionToEs6Class_commentOnVariableDeclaration.ts
  tests/cases/fourslash/server/convertFunctionToEs6Class-server1.ts
  tests/cases/fourslash/server/convertFunctionToEs6Class-server2.ts
Labels: For Backlog Bug

#39468 Mark @typedef as a type declaration
  src/compiler/checker.ts
  tests/cases/fourslash/jsdocDeprecated_suggestion5.ts
Labels: Author: Team

#39130 Process type nodes in codefixes/refactors for auto-imports recursively
  src/services/codefixes/helpers.ts
  src/services/codefixes/inferFromUsage.ts
  tests/cases/fourslash/codeFixClassImplementInterfaceAutoImports.ts
Labels: Author: Team

#39393 Fix for relating covered discriminants in unions
  src/compiler/checker.ts
  tests/baselines/reference/assignmentCompatWithDiscriminatedUnion.errors.txt
  tests/baselines/reference/assignmentCompatWithDiscriminatedUnion.js
  tests/baselines/reference/assignmentCompatWithDiscriminatedUnion.symbols
  tests/baselines/reference/assignmentCompatWithDiscriminatedUnion.types
  tests/cases/conformance/types/typeRelationships/assignmentCompatibility/assignmentCompatWithDiscriminatedUnion.ts
Labels: Author: Team

#39472 Dont include auto type reference directives on syntax only server
  src/server/project.ts
  src/testRunner/unittests/tsserver/semanticOperationsOnSyntaxServer.ts
Labels: Author: Team

#39478 Fix test semantic merge conflict between #39348 and #39130
  tests/cases/fourslash/codeFixClassImplementInterfaceAutoImports.ts
Labels: Author: Team

#39481 Fix crash in decorator metadata calculation when serializing template literal type nodes
  src/compiler/transformers/ts.ts
  tests/baselines/reference/templateLiteralsAndDecoratorMetadata.js
  tests/baselines/reference/templateLiteralsAndDecoratorMetadata.symbols
  tests/baselines/reference/templateLiteralsAndDecoratorMetadata.types
  tests/cases/compiler/templateLiteralsAndDecoratorMetadata.ts
Labels: Author: Team

#39363 Fix getTypeAtLocation for dotted implements clauses
  src/compiler/checker.ts
  src/testRunner/unittests/publicApi.ts
Labels: Author: Team

#38920 Ensure type/namespaceish statics are included in the list of namespace merge members
  src/compiler/checker.ts
  tests/baselines/reference/jsDeclarationsClassStaticMethodAugmentation.js
  tests/baselines/reference/jsDeclarationsClassStaticMethodAugmentation.symbols
  tests/baselines/reference/jsDeclarationsClassStaticMethodAugmentation.types
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsClassStaticMethodAugmentation.ts
Labels: Author: Team

#39483 Remove unnecessary assert in tryReuseStructureFromOldProgram
  src/compiler/program.ts
Labels: Author: Team

#39507 Fixes searches for symbols exported using export * as
  src/services/importTracker.ts
  tests/cases/fourslash/findAllRefsReExportStarAs.ts
Labels: Author: Team

#39479 Add regression test for #38834
  tests/baselines/reference/jsDeclarationsConstsAsNamespacesWithReferences.js
  tests/baselines/reference/jsDeclarationsConstsAsNamespacesWithReferences.symbols
  tests/baselines/reference/jsDeclarationsConstsAsNamespacesWithReferences.types
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsConstsAsNamespacesWithReferences.ts
Labels: Author: Team

#39487 Better checking of @param/@property tags
  src/compiler/checker.ts
  tests/baselines/reference/jsdocParamTagTypeLiteral.types
Labels: Author: Team

#39394 Insert auto-imports in sorted order
  src/compiler/core.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/services/codefixes/importFixes.ts
  src/services/organizeImports.ts
  src/services/refactors/moveToNewFile.ts
  src/services/textChanges.ts
  src/services/utilities.ts
  tests/baselines/reference/organizeImports/TypeOnly.ts
  tests/cases/fourslash/codeFixInferFromUsageContextualImport4.ts
  tests/cases/fourslash/codeFixUndeclaredMethodFunctionArgs_importArgumentType.ts
  tests/cases/fourslash/codeFixUndeclaredMethodFunctionArgs_importArgumentType1.ts
  tests/cases/fourslash/codeFixUndeclaredMethodFunctionArgs_importArgumentType2.ts
  tests/cases/fourslash/completionsImport_default_alreadyExistedWithRename.ts
  tests/cases/fourslash/completionsImport_named_addToNamedImports.ts
  tests/cases/fourslash/completionsImport_named_didNotExistBefore.ts
  tests/cases/fourslash/completionsImport_reExport_wrongName.ts
  tests/cases/fourslash/extract-method32.ts
  tests/cases/fourslash/extract-method33.ts
  tests/cases/fourslash/extract-method34.ts
  tests/cases/fourslash/extract-method35.ts
  tests/cases/fourslash/extract-method36.ts
  tests/cases/fourslash/extract-method37.ts
  tests/cases/fourslash/importNameCodeFixExistingImport0.ts
  tests/cases/fourslash/importNameCodeFixExistingImport1.ts
  tests/cases/fourslash/importNameCodeFixExistingImport10.ts
  tests/cases/fourslash/importNameCodeFixExistingImport11.ts
  tests/cases/fourslash/importNameCodeFixExistingImport6.ts
  tests/cases/fourslash/importNameCodeFixExistingImport7.ts
  tests/cases/fourslash/importNameCodeFixExistingImport8.ts
  tests/cases/fourslash/importNameCodeFixExistingImport9.ts
  tests/cases/fourslash/importNameCodeFixExistingImportEquals0.ts
  tests/cases/fourslash/importNameCodeFixNewImportAmbient1.ts
  tests/cases/fourslash/importNameCodeFixNewImportAmbient3.ts
  tests/cases/fourslash/importNameCodeFixNewImportFileQuoteStyle0.ts
  tests/cases/fourslash/importNameCodeFixNewImportFileQuoteStyle1.ts
  tests/cases/fourslash/importNameCodeFixNewImportFileQuoteStyle2.ts
  tests/cases/fourslash/importNameCodeFixNewImportFileQuoteStyleMixed0.ts
  tests/cases/fourslash/importNameCodeFixNewImportFileQuoteStyleMixed1.ts
  tests/cases/fourslash/importNameCodeFixUMDGlobal1.ts
  tests/cases/fourslash/importNameCodeFixUMDGlobalReact0.ts
  tests/cases/fourslash/importNameCodeFixUMDGlobalReact1.ts
  tests/cases/fourslash/importNameCodeFix_all.ts
  tests/cases/fourslash/importNameCodeFix_all2.ts
  tests/cases/fourslash/importNameCodeFix_avoidRelativeNodeModules.ts
  tests/cases/fourslash/importNameCodeFix_fileWithNoTrailingNewline.ts
  tests/cases/fourslash/importNameCodeFix_jsx.ts
  tests/cases/fourslash/importNameCodeFix_order.ts
  tests/cases/fourslash/importNameCodeFix_require.ts
  tests/cases/fourslash/importNameCodeFix_withJson.ts
  tests/cases/fourslash/quickfixImplementInterfaceUnreachableTypeUsesRelativeImport.ts
Labels: Author: Team

#39533 Fixes searches for export * as 'identifier'
  src/services/findAllReferences.ts
  src/services/importTracker.ts
  tests/cases/fourslash/findAllRefsReExportStarAs.ts
  tests/cases/fourslash/referencesForStatementKeywords.ts
Labels: Author: Team

#39532 Fix @param type parameter lookup
  src/compiler/checker.ts
  tests/baselines/reference/paramTagTypeResolution2.symbols
  tests/baselines/reference/paramTagTypeResolution2.types
  tests/cases/conformance/jsdoc/paramTagTypeResolution2.ts
Labels: Author: Team

#39551 Handle typeAcquisition could be undefined
  src/server/project.ts
Labels: Author: Team

#39557 Add ClassExpression, FunctionExpression and ArrowFunction to check for cancellation token from classifier
  src/services/classifier.ts
Labels: Author: Team

#39558 Don’t create expando declarations on alias symbols
  src/compiler/binder.ts
  src/compiler/checker.ts
  tests/baselines/reference/expandoOnAlias.errors.txt
  tests/baselines/reference/expandoOnAlias.js
  tests/baselines/reference/expandoOnAlias.symbols
  tests/baselines/reference/expandoOnAlias.types
  tests/baselines/reference/exportDefaultMarksIdentifierAsUsed.symbols
  tests/baselines/reference/exportDefaultMarksIdentifierAsUsed.types
  tests/baselines/reference/propertyAssignmentOnImportedSymbol.symbols
  tests/baselines/reference/propertyAssignmentOnImportedSymbol.types
  tests/cases/conformance/salsa/expandoOnAlias.ts
Labels: Author: Team

#39591 Fix find-all-references on undefined
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/services/findAllReferences.ts
  tests/baselines/reference/findAllReferencesUndefined.baseline.jsonc
  tests/cases/fourslash/findAllReferencesUndefined.ts
  tests/cases/fourslash/fourslash.ts
Labels: Author: Team

#37029 Add ToggleLineComment and ToggleMultilineComment service
  src/harness/client.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/harness/harnessLanguageService.ts
  src/server/protocol.ts
  src/server/session.ts
  src/services/services.ts
  src/services/shims.ts
  src/services/types.ts
  src/services/utilities.ts
  src/testRunner/unittests/tsserver/session.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/commentSelection1.ts
  tests/cases/fourslash/commentSelection2.ts
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/toggleLineComment1.ts
  tests/cases/fourslash/toggleLineComment10.ts
  tests/cases/fourslash/toggleLineComment2.ts
  tests/cases/fourslash/toggleLineComment3.ts
  tests/cases/fourslash/toggleLineComment4.ts
  tests/cases/fourslash/toggleLineComment5.ts
  tests/cases/fourslash/toggleLineComment6.ts
  tests/cases/fourslash/toggleLineComment7.ts
  tests/cases/fourslash/toggleLineComment8.ts
  tests/cases/fourslash/toggleLineComment9.ts
  tests/cases/fourslash/toggleMultilineComment1.ts
  tests/cases/fourslash/toggleMultilineComment2.ts
  tests/cases/fourslash/toggleMultilineComment3.ts
  tests/cases/fourslash/toggleMultilineComment4.ts
  tests/cases/fourslash/toggleMultilineComment5.ts
  tests/cases/fourslash/toggleMultilineComment6.ts
  tests/cases/fourslash/toggleMultilineComment7.ts
  tests/cases/fourslash/toggleMultilineComment8.ts
  tests/cases/fourslash/toggleMultilineComment9.ts
  tests/cases/fourslash/uncommentSelection1.ts
  tests/cases/fourslash/uncommentSelection2.ts
  tests/cases/fourslash/uncommentSelection3.ts
  tests/cases/fourslash/uncommentSelection4.ts
Labels: For Milestone Bug

#39604 Fix tsc --watch crash on module augmentations when module resolution changes
  src/compiler/builderState.ts
  src/testRunner/unittests/tscWatch/programUpdates.ts
  tests/baselines/reference/tscWatch/programUpdates/change-module-to-none.js
Labels: Author: Team

#38419 fix(33511): React Native <Text> component quick fix weird import suggestion
  src/services/codefixes/importFixes.ts
  tests/cases/fourslash/importNameCodeFix_jsx1.ts
  tests/cases/fourslash/importNameCodeFix_jsx2.ts
  tests/cases/fourslash/importNameCodeFix_jsx3.ts
  tests/cases/fourslash/importNameCodeFix_jsx4.ts
  tests/cases/fourslash/importNameCodeFix_jsx5.ts
  tests/cases/fourslash/importNameCodeFix_jsx6.ts
  tests/cases/fourslash/importNameCodeFix_jsx7.ts
Labels: For Backlog Bug

#39475 Use jsxFragmentFactory entity name for factory name lookup from checking fragments
  src/compiler/checker.ts
  tests/baselines/reference/jsxFactoryAndJsxFragmentFactory.js
  tests/baselines/reference/jsxFactoryAndJsxFragmentFactory.symbols
  tests/baselines/reference/jsxFactoryAndJsxFragmentFactory.types
  tests/baselines/reference/jsxFragmentFactoryNoUnusedLocals.js
  tests/baselines/reference/jsxFragmentFactoryNoUnusedLocals.symbols
  tests/baselines/reference/jsxFragmentFactoryNoUnusedLocals.types
  tests/cases/compiler/jsxFactoryAndJsxFragmentFactory.tsx
  tests/cases/compiler/jsxFragmentFactoryNoUnusedLocals.tsx
Labels: Author: Team

#39606 Don’t give all instantiated signatures in JS strict arity
  src/compiler/types.ts
  tests/baselines/reference/unannotatedParametersAreOptional.symbols
  tests/baselines/reference/unannotatedParametersAreOptional.types
  tests/cases/conformance/salsa/unannotatedParametersAreOptional.ts
Labels: Author: Team

#39552 Flag mapped types with circular property types and do not attempt to print them structurally
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/recursivelyExpandingUnionNoStackoverflow.errors.txt
  tests/baselines/reference/recursivelyExpandingUnionNoStackoverflow.js
  tests/baselines/reference/recursivelyExpandingUnionNoStackoverflow.symbols
  tests/baselines/reference/recursivelyExpandingUnionNoStackoverflow.types
  tests/cases/compiler/recursivelyExpandingUnionNoStackoverflow.ts
Labels: Author: Team

#39617 Do not resolve require calls in typescript files even if it contains dynamic import
  src/compiler/program.ts
  tests/baselines/reference/moduleResolutionWithRequire.js
  tests/baselines/reference/moduleResolutionWithRequire.symbols
  tests/baselines/reference/moduleResolutionWithRequire.trace.json
  tests/baselines/reference/moduleResolutionWithRequire.types
  tests/baselines/reference/moduleResolutionWithRequireAndImport.js
  tests/baselines/reference/moduleResolutionWithRequireAndImport.symbols
  tests/baselines/reference/moduleResolutionWithRequireAndImport.trace.json
  tests/baselines/reference/moduleResolutionWithRequireAndImport.types
  tests/cases/compiler/moduleResolutionWithRequire.ts
  tests/cases/compiler/moduleResolutionWithRequireAndImport.ts
Labels: Author: Team

#39621 fix(38868): Annotate with type from JSDocs generates a line break between generics instead of a comma
  src/services/textChanges.ts
  tests/cases/fourslash/annotateWithTypeFromJSDoc23.ts
Labels: For Backlog Bug

#39554 fix(39515): Add all imports inserts all commas before imports in files with crlf line endings
  src/services/textChanges.ts
  src/testRunner/unittests/services/textChanges.ts
  tests/baselines/reference/textChanges/insertNodeInListAfter19.js
  tests/baselines/reference/textChanges/insertNodeInListAfter20.js
Labels: For Milestone Bug

#39476 Resolve only relative references in open files on syntax server
  src/compiler/program.ts
  src/compiler/resolutionCache.ts
  src/compiler/types.ts
  src/compiler/watchPublic.ts
  src/server/editorServices.ts
  src/server/project.ts
  src/services/services.ts
  src/services/types.ts
  src/testRunner/unittests/tsserver/semanticOperationsOnSyntaxServer.ts
Labels: Author: Team, For Uncommitted Bug

#39628 Add twoslash repros to issues in this repo
  .github/workflows/twoslash-repros.yaml
Labels: Author: Team, For Uncommitted Bug

#39567 fix(39373): const {} = require import causes Debug Failure
  src/compiler/diagnosticMessages.json
  src/compiler/transformers/declarations/diagnostics.ts
  tests/baselines/reference/declarationEmitExpressionInExtends6.errors.txt
  tests/baselines/reference/declarationEmitExpressionInExtends6.js
  tests/baselines/reference/declarationEmitExpressionInExtends6.symbols
  tests/baselines/reference/declarationEmitExpressionInExtends6.types
  tests/cases/compiler/declarationEmitExpressionInExtends6.ts
Labels: For Milestone Bug

#39636 Explicitly add dependency on node to compiler tsconfig, remove es6+ string method usage
  src/compiler/resolutionCache.ts
  src/compiler/tsconfig.json
Labels: Author: Team, For Uncommitted Bug

#39675 Consistent errors on circular base types
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/circularBaseTypes.errors.txt
  tests/baselines/reference/circularBaseTypes.js
  tests/baselines/reference/circularBaseTypes.symbols
  tests/baselines/reference/circularBaseTypes.types
  tests/baselines/reference/circularConstraintYieldsAppropriateError.errors.txt
  tests/baselines/reference/interfaceDeclaration1.errors.txt
  tests/baselines/reference/interfaceThatIndirectlyInheritsFromItself.errors.txt
  tests/baselines/reference/recursiveBaseCheck5.errors.txt
  tests/baselines/reference/recursiveInheritance.errors.txt
  tests/cases/compiler/circularBaseTypes.ts
Labels: For Milestone Bug

#39682 LEGO: Pull request from lego/hb_998_20200721041046239 to master
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#39579 fix 39453
  src/services/callHierarchy.ts
  tests/baselines/reference/callHierarchyCallExpressionByConstNamedFunctionExpression.callHierarchy.txt
  tests/cases/fourslash/callHierarchyCallExpressionByConstNamedFunctionExpression.ts
Labels: For Milestone Bug

#39593 Add disableReferencedProjectLoad to stop loading child projects to allow users to disable loading large solutions
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  src/compiler/types.ts
  src/server/editorServices.ts
  src/server/project.ts
  src/testRunner/unittests/tsserver/helpers.ts
  src/testRunner/unittests/tsserver/projectReferences.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/showConfig/Shows tsconfig for single option/disableReferencedProjectLoad/tsconfig.json
Labels: Author: Team, For Milestone Bug

#39613 Support loading of child project if found project is not pure solution has some of its own files and project references
  src/server/editorServices.ts
  src/server/project.ts
  src/testRunner/unittests/tsserver/projectReferences.ts
Labels: Author: Team, For Milestone Bug

#39463 not escape unicode char for import path string.
  src/compiler/checker.ts
  tests/cases/fourslash/quickInfoImportNonunicodePath.ts
Labels: For Milestone Bug

#39670 Fix 31995: make cached key more precise to avoid returning wrong cached value.
  src/compiler/checker.ts
  tests/baselines/reference/typeOfThisInstanceMemberNarrowedWithLoopAntecedent.errors.txt
  tests/baselines/reference/typeOfThisInstanceMemberNarrowedWithLoopAntecedent.js
  tests/baselines/reference/typeOfThisInstanceMemberNarrowedWithLoopAntecedent.symbols
  tests/baselines/reference/typeOfThisInstanceMemberNarrowedWithLoopAntecedent.types
  tests/cases/conformance/classes/members/instanceAndStaticMembers/typeOfThisInstanceMemberNarrowedWithLoopAntecedent.ts
Labels: For Milestone Bug

#39672 Fix 38219: signature helper works for optional function condition.
  src/services/signatureHelp.ts
  tests/cases/fourslash/signatureHelpForOptionalMethods.ts
Labels: For Milestone Bug

#39506 Fix emit/formatting issues in refactors
  src/compiler/emitter.ts
  src/services/formatting/formatting.ts
  src/services/refactors/moveToNewFile.ts
  src/services/textChanges.ts
  tests/baselines/reference/textChanges/replaceRangeWithForcedIndentation.js
  tests/cases/fourslash/moveToNewFile.ts
  tests/cases/fourslash/moveToNewFile_cleanUpLastNamedImport.ts
  tests/cases/fourslash/moveToNewFile_defaultImport.ts
  tests/cases/fourslash/moveToNewFile_exportImport.ts
  tests/cases/fourslash/moveToNewFile_getter.ts
  tests/cases/fourslash/moveToNewFile_importEquals.ts
  tests/cases/fourslash/moveToNewFile_js.ts
  tests/cases/fourslash/moveToNewFile_moveImport.ts
  tests/cases/fourslash/moveToNewFile_moveJsxImport1.ts
  tests/cases/fourslash/moveToNewFile_moveJsxImport2.ts
  tests/cases/fourslash/moveToNewFile_moveJsxImport4.ts
  tests/cases/fourslash/moveToNewFile_moveNamedImport.ts
  tests/cases/fourslash/moveToNewFile_moveNamespaceImport.ts
  tests/cases/fourslash/moveToNewFile_multiple.ts
  tests/cases/fourslash/moveToNewFile_selectionOnName.ts
  tests/cases/fourslash/moveToNewFile_variableDeclarationWithNoInitializer.ts
  tests/cases/fourslash/textChangesIndentStyle.ts
  tests/cases/fourslash/textChangesPreserveNewlines10.ts
Labels: Author: Team

#39696 Add a fastpath for comparing common mapped types like `Pick` which avoids manufacturing intermediate type identities
  src/compiler/checker.ts
Labels: Author: Team, For Milestone Bug

#39679 Make AutoImportProviderProject work with symlinked monorepos
  src/compiler/checker.ts
  src/compiler/moduleSpecifiers.ts
  src/compiler/program.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/harness/harnessLanguageService.ts
  src/server/project.ts
  src/services/services.ts
  src/services/types.ts
  src/services/utilities.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/cases/fourslash/server/autoImportProvider4.ts
Labels: Author: Team, For Milestone Bug

#39706 LEGO: Pull request from lego/hb_998_20200722221053535 to master
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#39721 Fixes confusing logs and unnecessary configFile checks from navto by keeping project with result.
  src/server/editorServices.ts
  src/server/project.ts
  src/server/session.ts
  src/testRunner/unittests/tsserver/navTo.ts
Labels: Author: Team, For Milestone Bug

#39723 Lower priority for speculative variadic tuple inferences
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/variadicTuples1.errors.txt
  tests/baselines/reference/variadicTuples1.js
  tests/baselines/reference/variadicTuples1.symbols
  tests/baselines/reference/variadicTuples1.types
  tests/cases/conformance/types/tuple/variadicTuples1.ts
Labels: For Milestone Bug

#39731 Handle unresolved baseType when trying to get completions for static member
  src/services/completions.ts
  tests/cases/fourslash/completionEntryForClassMembers_StaticWhenBaseTypeIsNotResolved.ts
Labels: Author: Team, For Uncommitted Bug

#39772 Add contextual type for generator return type
  src/compiler/checker.ts
  tests/baselines/reference/destructuringArrayBindingPatternAndAssignment4.errors.txt
  tests/baselines/reference/destructuringArrayBindingPatternAndAssignment4.js
  tests/baselines/reference/destructuringArrayBindingPatternAndAssignment4.symbols
  tests/baselines/reference/destructuringArrayBindingPatternAndAssignment4.types
  tests/baselines/reference/generatorReturnContextualType.errors.txt
  tests/baselines/reference/generatorReturnContextualType.js
  tests/baselines/reference/generatorReturnContextualType.symbols
  tests/baselines/reference/generatorReturnContextualType.types
  tests/baselines/reference/generatorYieldContextualType.types
  tests/cases/conformance/es6/destructuring/destructuringArrayBindingPatternAndAssignment4.ts
  tests/cases/conformance/generators/generatorReturnContextualType.ts
Labels: Author: Team, For Milestone Bug

#39779 Undo accidental change from #39772
  src/compiler/checker.ts
  tests/baselines/reference/destructuringArrayBindingPatternAndAssignment4.errors.txt
  tests/baselines/reference/destructuringArrayBindingPatternAndAssignment4.js
  tests/baselines/reference/destructuringArrayBindingPatternAndAssignment4.symbols
  tests/baselines/reference/destructuringArrayBindingPatternAndAssignment4.types
  tests/baselines/reference/generatorYieldContextualType.types
  tests/cases/conformance/es6/destructuring/destructuringArrayBindingPatternAndAssignment4.ts
Labels: Author: Team, For Uncommitted Bug

#39776 Reduce unnecessary error computation
  src/compiler/checker.ts
Labels: For Uncommitted Bug

#39790 Add diagnostic info to getNameForExportedSymbol crash
  src/services/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#39791 Make @enum,@this tag construction stricter
  src/compiler/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Milestone Bug

#39794 Move off deprecated mocha types
  src/testRunner/externalCompileRunner.ts
  src/testRunner/rwcRunner.ts
Labels: For Uncommitted Bug

#39792 Reduce unnecessary error computation
  src/compiler/checker.ts
Labels: For Uncommitted Bug

#39815 Fix location for duplicate function implementation errors
  src/compiler/checker.ts
  tests/baselines/reference/exportDefaultInterfaceAndTwoFunctions.errors.txt
  tests/baselines/reference/exportDefaultInterfaceAndTwoFunctions.js
  tests/baselines/reference/exportDefaultInterfaceAndTwoFunctions.symbols
  tests/baselines/reference/exportDefaultInterfaceAndTwoFunctions.types
  tests/cases/compiler/exportDefaultInterfaceAndTwoFunctions.ts
Labels: Author: Team, For Uncommitted Bug

#39814 Fix this-parameter emit for JSDocFunction types
  src/compiler/checker.ts
  tests/baselines/reference/jsDeclarationsRestArgsWithThisTypeInJSDocFunction.js
  tests/baselines/reference/jsDeclarationsRestArgsWithThisTypeInJSDocFunction.symbols
  tests/baselines/reference/jsDeclarationsRestArgsWithThisTypeInJSDocFunction.types
  tests/baselines/reference/jsdocDisallowedInTypescript.types
  tests/baselines/reference/jsdocFunctionType.types
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsRestArgsWithThisTypeInJSDocFunction.ts
Labels: Author: Team, For Milestone Bug

#39356 fix(39245): Weird related diagnostic for missing rest parameter arguments
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/callWithMissingVoid.errors.txt
  tests/baselines/reference/genericRestArity.errors.txt
  tests/baselines/reference/genericRestArityStrict.errors.txt
  tests/baselines/reference/spreadOfParamsFromGeneratorMakesRequiredParams.errors.txt
Labels: For Milestone Bug

#38449 Updates Uint8ArrayConstructor to match MDN documentation.
  src/lib/es5.d.ts
Labels: For Backlog Bug

#39806 Make `getLocalSymbolForExportDefault` look harder for an export
  src/compiler/utilities.ts
  tests/baselines/reference/exportDefaultInterfaceAndValue.js
  tests/baselines/reference/exportDefaultInterfaceAndValue.symbols
  tests/baselines/reference/exportDefaultInterfaceAndValue.types
  tests/cases/compiler/exportDefaultInterfaceAndValue.ts
Labels: Author: Team, For Milestone Bug

#39718 Fix formatting scanner on JSX text that looks like trivia
  src/compiler/utilities.ts
  src/services/formatting/formatting.ts
  src/services/formatting/formattingScanner.ts
  tests/cases/fourslash/formatTSXWithInlineComment.ts
Labels: Author: Team, For Milestone Bug

#39722 The iteration type of overloaded iterator signatures derives from the intersection of their return types
  src/compiler/checker.ts
  tests/baselines/reference/for-of58.js
  tests/baselines/reference/for-of58.symbols
  tests/baselines/reference/for-of58.types
  tests/cases/conformance/es6/for-ofStatements/for-of58.ts
Labels: Author: Team, For Milestone Bug

#39824 Allow assignments to a narrowable reference to be considered narrowable
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/debug/dbg.ts
  tests/baselines/reference/controlFlowAssignmentExpression.js
  tests/baselines/reference/controlFlowAssignmentExpression.symbols
  tests/baselines/reference/controlFlowAssignmentExpression.types
  tests/cases/conformance/controlFlow/controlFlowAssignmentExpression.ts
Labels: Author: Team, For Milestone Bug
