Repository microsoft/TypeScript, pull requests merged in 2020-10, with the labels that each got.

#40837 Properly distribute over unions in keyof for mapped types with as clause
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypeAsClauses.js
  tests/baselines/reference/mappedTypeAsClauses.symbols
  tests/baselines/reference/mappedTypeAsClauses.types
  tests/cases/conformance/types/mapped/mappedTypeAsClauses.ts
Labels: For Milestone Bug

#40735 Fix typo in JSON.stringify doc
  src/lib/es5.d.ts
Labels: For Uncommitted Bug

#40871 Add extensions to jsx automatically added import, per babel change
  src/compiler/transformers/jsx.ts
  tests/baselines/reference/jsxJsxsCjsTransformChildren(jsx=react-jsx).js
  tests/baselines/reference/jsxJsxsCjsTransformChildren(jsx=react-jsxdev).js
  tests/baselines/reference/jsxJsxsCjsTransformCustomImport(jsx=react-jsx).js
  tests/baselines/reference/jsxJsxsCjsTransformCustomImport(jsx=react-jsxdev).js
  tests/baselines/reference/jsxJsxsCjsTransformCustomImportPragma(jsx=react-jsx).js
  tests/baselines/reference/jsxJsxsCjsTransformCustomImportPragma(jsx=react-jsxdev).js
  tests/baselines/reference/jsxJsxsCjsTransformSubstitutesNames(jsx=react-jsx).js
  tests/baselines/reference/jsxJsxsCjsTransformSubstitutesNames(jsx=react-jsxdev).js
  tests/baselines/reference/jsxJsxsCjsTransformSubstitutesNamesFragment(jsx=react-jsx).js
  tests/baselines/reference/jsxJsxsCjsTransformSubstitutesNamesFragment(jsx=react-jsxdev).js
Labels: Author: Team, For Uncommitted Bug

#40679 Emit non-identifier enum member references as typeof parent[some name]
  src/compiler/checker.ts
  tests/baselines/reference/ambientConstLiterals.types
  tests/baselines/reference/bitwiseNotOperatorWithEnumType.types
  tests/baselines/reference/declFileEnums.types
  tests/baselines/reference/declarationEmitSpreadStringlyKeyedEnum.js
  tests/baselines/reference/declarationEmitSpreadStringlyKeyedEnum.symbols
  tests/baselines/reference/declarationEmitSpreadStringlyKeyedEnum.types
  tests/baselines/reference/decrementOperatorWithEnumType.types
  tests/baselines/reference/decrementOperatorWithEnumTypeInvalidOperations.types
  tests/baselines/reference/deleteOperatorWithEnumType.types
  tests/baselines/reference/doubleUnderscoreEnumEmit.types
  tests/baselines/reference/enumErrors.types
  tests/baselines/reference/enumIdentifierLiterals.types
  tests/baselines/reference/enumWithNegativeInfinityProperty.types
  tests/baselines/reference/enumWithQuotedElementName1.types
  tests/baselines/reference/enumWithQuotedElementName2.types
  tests/baselines/reference/enumWithUnicodeEscape1.types
  tests/baselines/reference/incrementOperatorWithEnumType.types
  tests/baselines/reference/incrementOperatorWithEnumTypeInvalidOperations.types
  tests/baselines/reference/literalsInComputedProperties1.types
  tests/baselines/reference/negateOperatorWithEnumType.types
  tests/baselines/reference/parserEnum5.types
  tests/baselines/reference/parserEnum7.types
  tests/baselines/reference/plusOperatorWithEnumType.types
  tests/baselines/reference/typeofOperatorWithEnumType.types
  tests/baselines/reference/voidOperatorWithEnumType.types
  tests/cases/compiler/declarationEmitSpreadStringlyKeyedEnum.ts
Labels: Author: Team, For Milestone Bug

#40875 Propagate wildcard types in template literal type construction
  src/compiler/checker.ts
  tests/baselines/reference/templateLiteralTypes1.errors.txt
  tests/baselines/reference/templateLiteralTypes1.js
  tests/baselines/reference/templateLiteralTypes1.symbols
  tests/baselines/reference/templateLiteralTypes1.types
  tests/cases/conformance/types/literal/templateLiteralTypes1.ts
Labels: For Milestone Bug

#40681 Fix noUncheckedIndexedAccess with tuple rest types and generic index types
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/noUncheckedIndexedAccess.errors.txt
  tests/baselines/reference/noUncheckedIndexedAccess.js
  tests/baselines/reference/noUncheckedIndexedAccess.symbols
  tests/baselines/reference/noUncheckedIndexedAccess.types
  tests/cases/conformance/pedantic/noUncheckedIndexedAccess.ts
Labels: Author: Team, For Milestone Bug

#40839 Ensure whitespace jsx elements are not counted when determining if a jsx child is the only child
  src/compiler/transformers/jsx.ts
  tests/baselines/reference/jsxJsxsCjsTransformNestedSelfClosingChild(jsx=react-jsx).js
  tests/baselines/reference/jsxJsxsCjsTransformNestedSelfClosingChild(jsx=react-jsx).symbols
  tests/baselines/reference/jsxJsxsCjsTransformNestedSelfClosingChild(jsx=react-jsx).types
  tests/baselines/reference/jsxJsxsCjsTransformNestedSelfClosingChild(jsx=react-jsxdev).js
  tests/baselines/reference/jsxJsxsCjsTransformNestedSelfClosingChild(jsx=react-jsxdev).symbols
  tests/baselines/reference/jsxJsxsCjsTransformNestedSelfClosingChild(jsx=react-jsxdev).types
  tests/cases/conformance/jsx/jsxs/jsxJsxsCjsTransformNestedSelfClosingChild.tsx
Labels: Author: Team, For Milestone Bug

#40882 Limit export= js declaration emit to only json source files
  src/compiler/checker.ts
  tests/baselines/reference/jsDeclarationsExportedClassAliases.js
  tests/baselines/reference/jsDeclarationsExportedClassAliases.symbols
  tests/baselines/reference/jsDeclarationsExportedClassAliases.types
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsExportedClassAliases.ts
Labels: Author: Team, For Milestone Bug

#40889 Updated error message for TS1031
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/classExpressionPropertyModifiers.errors.txt
  tests/baselines/reference/derivedUninitializedPropertyDeclaration.errors.txt
  tests/baselines/reference/illegalModifiersOnClassElements.errors.txt
  tests/baselines/reference/parserConstructorDeclaration3.errors.txt
  tests/baselines/reference/parserConstructorDeclaration4.errors.txt
  tests/baselines/reference/parserMemberAccessorDeclaration10.errors.txt
  tests/baselines/reference/parserMemberAccessorDeclaration11.errors.txt
  tests/baselines/reference/parserMemberFunctionDeclaration4.errors.txt
  tests/baselines/reference/parserMemberFunctionDeclaration5.errors.txt
  tests/baselines/reference/parserMemberVariableDeclaration4.errors.txt
Labels: For Backlog Bug

#40861 Fix recursive types in @typedef
  src/compiler/checker.ts
  tests/baselines/reference/assertionsAndNonReturningFunctions.types
  tests/baselines/reference/checkJsTypeDefNoUnusedLocalMarked.types
  tests/baselines/reference/checkJsdocTypeTag4.types
  tests/baselines/reference/contextualTypedSpecialAssignment.types
  tests/baselines/reference/enumTag.types
  tests/baselines/reference/expandoFunctionContextualTypesJs.types
  tests/baselines/reference/exportDefaultWithJSDoc1.types
  tests/baselines/reference/exportDefaultWithJSDoc2.types
  tests/baselines/reference/jsDeclarationsEnumTag.types
  tests/baselines/reference/jsDeclarationsFunctionClassesCjsExportAssignment.js
  tests/baselines/reference/jsDeclarationsFunctionClassesCjsExportAssignment.types
  tests/baselines/reference/jsDeclarationsImportAliasExposedWithinNamespace.js
  tests/baselines/reference/jsDeclarationsImportAliasExposedWithinNamespace.types
  tests/baselines/reference/jsDeclarationsImportAliasExposedWithinNamespaceCjs.js
  tests/baselines/reference/jsDeclarationsImportAliasExposedWithinNamespaceCjs.types
  tests/baselines/reference/jsDeclarationsImportTypeBundled.types
  tests/baselines/reference/jsDeclarationsTypeAliases.types
  tests/baselines/reference/jsDeclarationsTypedefAndImportTypes.types
  tests/baselines/reference/jsDeclarationsTypedefPropertyAndExportAssignment.js
  tests/baselines/reference/jsDeclarationsUniqueSymbolUsage.types
  tests/baselines/reference/jsdocTemplateClass.types
  tests/baselines/reference/jsdocTemplateConstructorFunction.types
  tests/baselines/reference/jsdocTypeDefAtStartOfFile.types
  tests/baselines/reference/recursiveTypeReferences2.errors.txt
  tests/baselines/reference/recursiveTypeReferences2.js
  tests/baselines/reference/recursiveTypeReferences2.symbols
  tests/baselines/reference/recursiveTypeReferences2.types
  tests/baselines/reference/typedefCrossModule.types
  tests/baselines/reference/typedefMultipleTypeParameters.types
  tests/baselines/reference/typedefTagWrapping.types
  tests/cases/conformance/types/typeRelationships/recursiveTypes/recursiveTypeReferences2.ts
Labels: Author: Team, For Milestone Bug

#40908 Fix function merged with export as namespace sourcefile
  src/compiler/checker.ts
  tests/baselines/reference/sourceFileMergeWithFunction.js
  tests/baselines/reference/sourceFileMergeWithFunction.symbols
  tests/baselines/reference/sourceFileMergeWithFunction.types
  tests/cases/conformance/salsa/sourceFileMergeWithFunction.ts
Labels: Author: Team, For Milestone Bug

#40885 Properly compare path prefixes when generating module paths
  src/compiler/moduleSpecifiers.ts
  tests/baselines/reference/declarationEmitSymlinkPaths.js
  tests/baselines/reference/declarationEmitSymlinkPaths.symbols
  tests/baselines/reference/declarationEmitSymlinkPaths.types
  tests/cases/compiler/declarationEmitSymlinkPaths.ts
Labels: Author: Team, For Milestone Bug

#40891 Remove unnecessary requirement for createHash since we already handle absence of it
  src/compiler/builder.ts
  src/compiler/builderState.ts
  src/compiler/program.ts
  src/compiler/watch.ts
  src/server/editorServices.ts
  src/server/project.ts
Labels: Author: Team, For Uncommitted Bug

#40890 Do not create packagejson imports and auto import provider in partial semantic server mode
  src/server/project.ts
  src/testRunner/unittests/tsserver/partialSemanticServer.ts
Labels: Author: Team, For Uncommitted Bug

#40907 #40763 Fixed: Bad error message when forgetting a comma in an array of templ…
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/missingCommaInTemplateStringsArray.errors.txt
  tests/baselines/reference/missingCommaInTemplateStringsArray.js
  tests/baselines/reference/missingCommaInTemplateStringsArray.symbols
  tests/baselines/reference/missingCommaInTemplateStringsArray.types
  tests/cases/compiler/missingCommaInTemplateStringsArray.ts
Labels: For Uncommitted Bug

#40650 fix(40320): Better errors when using properties/methods from newer versions of ECMAScript
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/utilities.ts
  tests/baselines/reference/bigintWithoutLib.errors.txt
  tests/baselines/reference/decoratorMetadataNoLibIsolatedModulesTypes.errors.txt
  tests/baselines/reference/didYouMeanSuggestionErrors.errors.txt
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2015.errors.txt
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2015.js
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2015.symbols
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2015.types
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2016Plus.errors.txt
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2016Plus.js
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2016Plus.symbols
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2016Plus.types
  tests/baselines/reference/modularizeLibrary_ErrorFromUsingES6FeaturesWithOnlyES5Lib.errors.txt
  tests/baselines/reference/parserMissingLambdaOpenBrace1.errors.txt
  tests/baselines/reference/tscWatch/programUpdates/correctly-handles-changes-in-lib-section-of-config-file.js
  tests/baselines/reference/useObjectValuesAndEntries2.errors.txt
  tests/baselines/reference/useObjectValuesAndEntries3.errors.txt
  tests/baselines/reference/useSharedArrayBuffer2.errors.txt
  tests/baselines/reference/useSharedArrayBuffer3.errors.txt
  tests/cases/compiler/doYouNeedToChangeYourTargetLibraryES2015.ts
  tests/cases/compiler/doYouNeedToChangeYourTargetLibraryES2016Plus.ts
Labels: For Uncommitted Bug

#40115 Handles creating a reasonable AST when destructuring into a parens'd expresssion
  src/compiler/checker.ts
  tests/baselines/reference/destructuringControlFlowNoCrash.errors.txt
  tests/baselines/reference/destructuringControlFlowNoCrash.js
  tests/baselines/reference/destructuringControlFlowNoCrash.symbols
  tests/baselines/reference/destructuringControlFlowNoCrash.types
  tests/cases/compiler/destructuringControlFlowNoCrash.ts
Labels: Author: Team, For Milestone Bug

#40879 Use other files when necessary to determine import style in JS
  src/services/codefixes/importFixes.ts
  tests/cases/fourslash/importFixWithMultipleModuleExportAssignment.ts
  tests/cases/fourslash/importNameCodeFixNewImportExportEqualsJavaScript.ts
  tests/cases/fourslash/importNameCodeFix_jsCJSvsESM1.ts
  tests/cases/fourslash/importNameCodeFix_jsCJSvsESM2.ts
  tests/cases/fourslash/importNameCodeFix_jsCJSvsESM3.ts
  tests/cases/fourslash/importNameCodeFix_require_namedAndDefault.ts
Labels: Author: Team, For Milestone Bug

#40835 Skip past `module.exports = { Foo }` in go-to-defintion on 'Foo'
  src/harness/fourslashImpl.ts
  src/services/goToDefinition.ts
  tests/cases/fourslash/goToDefinitionDestructuredRequire1.ts
  tests/cases/fourslash/goToDefinitionDestructuredRequire2.ts
  tests/cases/fourslash/goToDefinitionImportedNames11.ts
Labels: Author: Team, For Milestone Bug

#40886 Limit when we allow nested unique symbols to be serialized
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitExpressionWithNonlocalPrivateUniqueSymbol.errors.txt
  tests/baselines/reference/declarationEmitExpressionWithNonlocalPrivateUniqueSymbol.js
  tests/baselines/reference/declarationEmitExpressionWithNonlocalPrivateUniqueSymbol.symbols
  tests/baselines/reference/declarationEmitExpressionWithNonlocalPrivateUniqueSymbol.types
  tests/cases/compiler/declarationEmitExpressionWithNonlocalPrivateUniqueSymbol.ts
Labels: Author: Team, For Milestone Bug

#40660 Fix class expression from being assignable if types don't match
  src/compiler/checker.ts
  tests/baselines/reference/classExpressionAssignment.errors.txt
  tests/baselines/reference/classExpressionAssignment.js
  tests/baselines/reference/classExpressionAssignment.symbols
  tests/baselines/reference/classExpressionAssignment.types
  tests/cases/compiler/classExpressionAssignment.ts
Labels: For Milestone Bug

#40931 fix(40929) PromiseConstructor error message for newer versions of ECMAScript
  src/compiler/utilities.ts
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2016Plus.errors.txt
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2016Plus.js
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2016Plus.symbols
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2016Plus.types
  tests/cases/compiler/doYouNeedToChangeYourTargetLibraryES2016Plus.ts
Labels: For Uncommitted Bug

#40728 fix(40685): JSDoc generation for arrow functions within object does not work
  src/services/jsDoc.ts
  tests/cases/fourslash/docCommentTemplateObjectLiteralMethods01.ts
Labels: For Backlog Bug

#40795 fix: change deprecated FunctionLike type to SignatureDeclaration
  src/compiler/checker.ts
  src/compiler/transformers/declarations.ts
  src/compiler/types.ts
  src/services/codefixes/inferFromUsage.ts
  src/services/outliningElementsCollector.ts
  src/services/symbolDisplay.ts
  src/services/textChanges.ts
Labels: For Uncommitted Bug

#40858 lib: remove `length` field from SharedArrayBuffer
  src/lib/es2017.sharedmemory.d.ts
  tests/baselines/reference/useSharedArrayBuffer6.errors.txt
  tests/baselines/reference/useSharedArrayBuffer6.js
  tests/baselines/reference/useSharedArrayBuffer6.symbols
  tests/baselines/reference/useSharedArrayBuffer6.types
  tests/cases/conformance/es2017/useSharedArrayBuffer6.ts
Labels: For Backlog Bug

#38232 Add definitions for WeakRef and FinalizationRegistry
  src/lib/esnext.d.ts
  src/lib/esnext.weakref.d.ts
Labels: For Backlog Bug

#40905 Use npm ci for nightly builds
  .github/workflows/nightly.yaml
Labels: For Uncommitted Bug

#40845 fix(40817): Dts compiled from anonymous arrow functions cannot be automatically imported
  src/services/codefixes/importFixes.ts
  tests/cases/fourslash/importNameCodeFixDefaultExport4.ts
  tests/cases/fourslash/importNameCodeFixDefaultExport5.ts
Labels: For Backlog Bug

#40965 LEGO: Pull request from lego/hb_998_20201006181049194 to master
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#40954 Fixes calculating resolved project reference to redirect for module resolution
  src/compiler/program.ts
  src/testRunner/tsconfig.json
  src/testRunner/unittests/tsbuild/moduleResolution.ts
  tests/baselines/reference/tsbuild/moduleResolution/resolves-specifier-in-output-declaration-file-from-referenced-project-correctly-with-preserveSymlinks.js
  tests/baselines/reference/tsbuild/moduleResolution/resolves-specifier-in-output-declaration-file-from-referenced-project-correctly.js
Labels: Author: Team, For Uncommitted Bug

#40576 Add pyright user test
  tests/baselines/reference/docker/pyright.log
  tests/cases/docker/pyright/Dockerfile
Labels: Author: Team, For Milestone Bug

#40967 Test indexed access to `this` on intersections
  tests/baselines/reference/indexedAccessToThisTypeOnIntersection01.js
  tests/baselines/reference/indexedAccessToThisTypeOnIntersection01.symbols
  tests/baselines/reference/indexedAccessToThisTypeOnIntersection01.types
  tests/cases/compiler/indexedAccessToThisTypeOnIntersection01.ts
Labels: For Uncommitted Bug

#40709 Add currency sign to NumberFormatOptions type
  src/lib/es5.d.ts
  tests/baselines/reference/numberFormatCurrencySign.js
  tests/baselines/reference/numberFormatCurrencySign.symbols
  tests/baselines/reference/numberFormatCurrencySign.types
  tests/cases/compiler/numberFormatCurrencySign.ts
Labels: For Backlog Bug

#40971 Add isDeeplyNestedType logic to getResolvedBaseConstraint
  src/compiler/checker.ts
  tests/baselines/reference/infiniteConstraints.errors.txt
  tests/baselines/reference/recursiveConditionalTypes.errors.txt
  tests/baselines/reference/templateLiteralTypes1.errors.txt
  tests/baselines/reference/templateLiteralTypes1.js
  tests/baselines/reference/templateLiteralTypes1.symbols
  tests/baselines/reference/templateLiteralTypes1.types
  tests/cases/conformance/types/literal/templateLiteralTypes1.ts
Labels: For Milestone Bug

#40981 Fix missed tasks to add esnext.weakref
  src/compiler/commandLineParser.ts
  src/lib/libs.json
  tests/baselines/reference/tsc/runWithoutArgs/initial-build/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
Labels: Author: Team, For Uncommitted Bug

#40984 LEGO: Pull request from lego/hb_998_20201007181041045 to master
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#40953 Improve the performance of requesting completions within a massive array literal
  src/compiler/core.ts
  src/services/utilities.ts
  tests/cases/fourslash/excessivelyLargeArrayLiteralCompletions.ts
Labels: Author: Team, For Milestone Bug

#40980 Fix export binding of namespaced typedefs
  src/compiler/binder.ts
  tests/baselines/reference/jsDeclarationsImportAliasExposedWithinNamespace.js
  tests/baselines/reference/jsDeclarationsImportAliasExposedWithinNamespace.symbols
  tests/baselines/reference/jsDeclarationsImportAliasExposedWithinNamespace.types
  tests/baselines/reference/jsDeclarationsImportNamespacedType.js
  tests/baselines/reference/jsDeclarationsImportNamespacedType.symbols
  tests/baselines/reference/jsDeclarationsImportNamespacedType.types
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsImportNamespacedType.ts
Labels: Author: Team, For Milestone Bug

#40260 feat(40197): No "did you mean to call" error when invocation is part of a logical expression
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/emitter.ts
  tests/baselines/reference/truthinessCallExpressionCoercion2.errors.txt
  tests/baselines/reference/truthinessCallExpressionCoercion2.js
  tests/baselines/reference/truthinessCallExpressionCoercion2.symbols
  tests/baselines/reference/truthinessCallExpressionCoercion2.types
  tests/cases/compiler/truthinessCallExpressionCoercion2.ts
  tests/cases/fourslash/codeFixMissingCallParentheses11.ts
  tests/cases/fourslash/codeFixMissingCallParentheses12.ts
  tests/cases/fourslash/codeFixMissingCallParentheses13.ts
  tests/cases/fourslash/codeFixMissingCallParentheses14.ts
  tests/cases/fourslash/codeFixMissingCallParentheses15.ts
  tests/cases/fourslash/codeFixMissingCallParentheses16.ts
  tests/cases/fourslash/codeFixMissingCallParentheses17.ts
Labels: Breaking Change, For Backlog Bug

#40976 fix(3758): Object literals in an assignment pattern do not get completions
  src/services/completions.ts
  tests/cases/fourslash/completionListInObjectLiteralAssignmentPattern1.ts
  tests/cases/fourslash/completionListInObjectLiteralAssignmentPattern2.ts
Labels: For Backlog Bug

#41001 Add elaboration when call fails all overloads but succeeds against the implementation signature
  src/compiler/builder.ts
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/utilities.ts
  tests/baselines/reference/constructorOverloads1.errors.txt
  tests/baselines/reference/functionOverloads2.errors.txt
  tests/baselines/reference/functionOverloads27.errors.txt
  tests/baselines/reference/functionOverloads40.errors.txt
  tests/baselines/reference/heterogeneousArrayAndOverloads.errors.txt
  tests/baselines/reference/incompatibleTypes.errors.txt
  tests/baselines/reference/optionalBindingParametersInOverloads1.errors.txt
  tests/baselines/reference/optionalBindingParametersInOverloads2.errors.txt
  tests/baselines/reference/overloadErrorMatchesImplementationElaboaration.errors.txt
  tests/baselines/reference/overloadErrorMatchesImplementationElaboaration.js
  tests/baselines/reference/overloadErrorMatchesImplementationElaboaration.symbols
  tests/baselines/reference/overloadErrorMatchesImplementationElaboaration.types
  tests/baselines/reference/overloadOnConstNoAnyImplementation2.errors.txt
  tests/baselines/reference/overloadOnConstNoStringImplementation2.errors.txt
  tests/baselines/reference/overloadResolutionTest1.errors.txt
  tests/baselines/reference/overloadingOnConstants2.errors.txt
  tests/baselines/reference/recursiveFunctionTypes.errors.txt
  tests/baselines/reference/taggedTemplateStringsWithOverloadResolution1.errors.txt
  tests/baselines/reference/taggedTemplateStringsWithOverloadResolution1_ES6.errors.txt
  tests/baselines/reference/tsxStatelessFunctionComponentOverload5.errors.txt
  tests/cases/compiler/overloadErrorMatchesImplementationElaboaration.ts
Labels: Author: Team, For Milestone Bug

#40987 Fix overlapping changes when un-qualifying import use site within transformed export
  src/services/codefixes/convertToAsyncFunction.ts
  src/services/codefixes/convertToEs6Module.ts
  src/services/utilities.ts
  tests/cases/fourslash/refactorConvertToEs6Module_renameWithinTransformedExports.ts
Labels: Author: Team, For Milestone Bug

#41018 Handle extra file extensions when wild card directory watch is invoked
  src/compiler/watchPublic.ts
  src/testRunner/unittests/tscWatch/watchApi.ts
Labels: Author: Team, For Milestone Bug

#41017 Fix crash due to unchecked cast in addImplementationSuccessElaboration
  src/compiler/checker.ts
  tests/baselines/reference/namespaceMergedWithFunctionWithOverloadsUsage.errors.txt
  tests/baselines/reference/namespaceMergedWithFunctionWithOverloadsUsage.js
  tests/baselines/reference/namespaceMergedWithFunctionWithOverloadsUsage.symbols
  tests/baselines/reference/namespaceMergedWithFunctionWithOverloadsUsage.types
  tests/cases/compiler/namespaceMergedWithFunctionWithOverloadsUsage.ts
Labels: Author: Team, For Milestone Bug

#40986 Fix relative paths in declaration emit for commonjs imports with trailing property access
  src/compiler/checker.ts
  tests/baselines/reference/jsDeclarationsCommonjsRelativePath.js
  tests/baselines/reference/jsDeclarationsCommonjsRelativePath.symbols
  tests/baselines/reference/jsDeclarationsCommonjsRelativePath.types
  tests/baselines/reference/jsDeclarationsTypeReferences.js
  tests/baselines/reference/jsDeclarationsTypeReferences3.js
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsCommonjsRelativePath.ts
Labels: Author: Team, For Uncommitted Bug

#40880 Handle noEmit and noEmitOnError with SemanticDiagnosticsBuilder
  src/compiler/builder.ts
  src/compiler/program.ts
  src/compiler/types.ts
  src/testRunner/unittests/tscWatch/watchApi.ts
Labels: Author: Team, For Uncommitted Bug

#40961 fix: show deprecated error for alias
  src/compiler/checker.ts
  tests/cases/fourslash/jsdocDeprecated_suggestion11.ts
Labels: For Uncommitted Bug

#40838 Fix crash resolving ImportTypeNode in JSDoc
  src/compiler/checker.ts
  tests/baselines/reference/jsdocImportTypeNodeNamespace.errors.txt
  tests/baselines/reference/jsdocImportTypeNodeNamespace.symbols
  tests/baselines/reference/jsdocImportTypeNodeNamespace.types
  tests/cases/compiler/jsdocImportTypeNodeNamespace.ts
Labels: Author: Team, For Milestone Bug

#40778 Always create optional properties when spreading objects conditionally
  src/compiler/checker.ts
  tests/baselines/reference/objectSpreadRepeatedComplexity.errors.txt
  tests/baselines/reference/objectSpreadRepeatedComplexity.types
  tests/baselines/reference/spreadOverwritesPropertyStrict.types
Labels: Author: Team, For Milestone Bug

#41068 Fix auto imports for export default edge cases
  src/services/codefixes/importFixes.ts
  tests/cases/fourslash/importNameCodeFixDefaultExport6.ts
  tests/cases/fourslash/importNameCodeFixDefaultExport7.ts
Labels: Author: Team

#40597 Handle the mapping between Array and ReadonlyArray in isTypeDerivedFrom
  src/compiler/checker.ts
  tests/baselines/reference/instanceofNarrowReadonlyArray.js
  tests/baselines/reference/instanceofNarrowReadonlyArray.symbols
  tests/baselines/reference/instanceofNarrowReadonlyArray.types
  tests/cases/compiler/instanceofNarrowReadonlyArray.ts
Labels: Author: Team, For Milestone Bug

#41079 `transformGenerators`: handle `CommaListExpression`
  src/compiler/transformers/generators.ts
  tests/baselines/reference/es5-asyncFunctionLongObjectLiteral.js
  tests/baselines/reference/es5-asyncFunctionLongObjectLiteral.symbols
  tests/baselines/reference/es5-asyncFunctionLongObjectLiteral.types
  tests/cases/compiler/es5-asyncFunctionLongObjectLiteral.ts
Labels: Author: Team, For Milestone Bug

#41070 Use minimal endings when generating declarations for js
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitOutFileBundlePaths.js
  tests/baselines/reference/declarationEmitOutFileBundlePaths.symbols
  tests/baselines/reference/declarationEmitOutFileBundlePaths.types
  tests/cases/compiler/declarationEmitOutFileBundlePaths.ts
Labels: Author: Team, For Milestone Bug

#40645 fix: IOSession access this before calling super
  src/tsserver/server.ts
Labels: For Backlog Bug

#40590 `performanceTimestamp`: use `performance.now` on node
  src/compiler/performanceTimestamp.ts
  src/harness/virtualFileSystemWithWatch.ts
Labels: Author: Team, For Backlog Bug

#41084 Move anonymous type instantiation cache from AST node to root type
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/objectInstantiationFromUnionSpread.js
  tests/baselines/reference/objectInstantiationFromUnionSpread.symbols
  tests/baselines/reference/objectInstantiationFromUnionSpread.types
  tests/cases/compiler/objectInstantiationFromUnionSpread.ts
Labels: For Uncommitted Bug

#40952 Add editor configurable filename-based ATA
  src/compiler/commandLineParser.ts
  src/compiler/types.ts
  src/jsTyping/jsTyping.ts
  src/server/editorServices.ts
  src/server/project.ts
  src/server/protocol.ts
  src/testRunner/unittests/tsserver/typingsInstaller.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Milestone Bug

#41126 Optimizes project loading in few scenarios
  src/compiler/program.ts
  src/compiler/types.ts
  src/server/editorServices.ts
  src/server/project.ts
  src/testRunner/unittests/tsserver/projectReferences.ts
Labels: Author: Team, For Uncommitted Bug

#41162 Properly reduce intersections of string literal and template literal types
  src/compiler/checker.ts
  tests/baselines/reference/templateLiteralTypesPatterns.errors.txt
  tests/baselines/reference/templateLiteralTypesPatterns.js
  tests/baselines/reference/templateLiteralTypesPatterns.symbols
  tests/baselines/reference/templateLiteralTypesPatterns.types
  tests/cases/conformance/types/literal/templateLiteralTypesPatterns.ts
Labels: For Milestone Bug

#41167 Revert "Add extensions to jsx automatically added import, per babel change (#40871)"
  src/compiler/transformers/jsx.ts
  tests/baselines/reference/jsxJsxsCjsTransformChildren(jsx=react-jsx).js
  tests/baselines/reference/jsxJsxsCjsTransformChildren(jsx=react-jsxdev).js
  tests/baselines/reference/jsxJsxsCjsTransformCustomImport(jsx=react-jsx).js
  tests/baselines/reference/jsxJsxsCjsTransformCustomImport(jsx=react-jsxdev).js
  tests/baselines/reference/jsxJsxsCjsTransformCustomImportPragma(jsx=react-jsx).js
  tests/baselines/reference/jsxJsxsCjsTransformCustomImportPragma(jsx=react-jsxdev).js
  tests/baselines/reference/jsxJsxsCjsTransformNestedSelfClosingChild(jsx=react-jsx).js
  tests/baselines/reference/jsxJsxsCjsTransformNestedSelfClosingChild(jsx=react-jsxdev).js
  tests/baselines/reference/jsxJsxsCjsTransformSubstitutesNames(jsx=react-jsx).js
  tests/baselines/reference/jsxJsxsCjsTransformSubstitutesNames(jsx=react-jsxdev).js
  tests/baselines/reference/jsxJsxsCjsTransformSubstitutesNamesFragment(jsx=react-jsx).js
  tests/baselines/reference/jsxJsxsCjsTransformSubstitutesNamesFragment(jsx=react-jsxdev).js
Labels: Author: Team, For Uncommitted Bug

#41166 Do not consider empty jsx expressions semantically important children
  src/compiler/checker.ts
  src/compiler/transformers/jsx.ts
  src/compiler/utilities.ts
  tests/baselines/reference/jsxEmptyExpressionNotCountedAsChild(jsx=react).js
  tests/baselines/reference/jsxEmptyExpressionNotCountedAsChild(jsx=react).symbols
  tests/baselines/reference/jsxEmptyExpressionNotCountedAsChild(jsx=react).types
  tests/baselines/reference/jsxEmptyExpressionNotCountedAsChild(jsx=react-jsx).js
  tests/baselines/reference/jsxEmptyExpressionNotCountedAsChild(jsx=react-jsx).symbols
  tests/baselines/reference/jsxEmptyExpressionNotCountedAsChild(jsx=react-jsx).types
  tests/baselines/reference/jsxEmptyExpressionNotCountedAsChild(jsx=react-jsxdev).js
  tests/baselines/reference/jsxEmptyExpressionNotCountedAsChild(jsx=react-jsxdev).symbols
  tests/baselines/reference/jsxEmptyExpressionNotCountedAsChild(jsx=react-jsxdev).types
  tests/cases/compiler/jsxEmptyExpressionNotCountedAsChild.tsx
Labels: Author: Team, For Milestone Bug

#41151 Fix/create element new jsx transform
  src/compiler/factory/utilities.ts
  src/compiler/transformers/jsx.ts
  tests/baselines/reference/jsxJsxsCjsTransformKeyProp(jsx=react-jsx).js
  tests/baselines/reference/jsxJsxsCjsTransformKeyProp(jsx=react-jsx).symbols
  tests/baselines/reference/jsxJsxsCjsTransformKeyProp(jsx=react-jsx).types
  tests/baselines/reference/jsxJsxsCjsTransformKeyProp(jsx=react-jsxdev).js
  tests/baselines/reference/jsxJsxsCjsTransformKeyProp(jsx=react-jsxdev).symbols
  tests/baselines/reference/jsxJsxsCjsTransformKeyProp(jsx=react-jsxdev).types
  tests/baselines/reference/jsxJsxsCjsTransformKeyPropCustomImport(jsx=react-jsx).js
  tests/baselines/reference/jsxJsxsCjsTransformKeyPropCustomImport(jsx=react-jsx).symbols
  tests/baselines/reference/jsxJsxsCjsTransformKeyPropCustomImport(jsx=react-jsx).types
  tests/baselines/reference/jsxJsxsCjsTransformKeyPropCustomImport(jsx=react-jsxdev).js
  tests/baselines/reference/jsxJsxsCjsTransformKeyPropCustomImport(jsx=react-jsxdev).symbols
  tests/baselines/reference/jsxJsxsCjsTransformKeyPropCustomImport(jsx=react-jsxdev).types
  tests/baselines/reference/jsxJsxsCjsTransformKeyPropCustomImportPragma(jsx=react-jsx).js
  tests/baselines/reference/jsxJsxsCjsTransformKeyPropCustomImportPragma(jsx=react-jsx).symbols
  tests/baselines/reference/jsxJsxsCjsTransformKeyPropCustomImportPragma(jsx=react-jsx).types
  tests/baselines/reference/jsxJsxsCjsTransformKeyPropCustomImportPragma(jsx=react-jsxdev).js
  tests/baselines/reference/jsxJsxsCjsTransformKeyPropCustomImportPragma(jsx=react-jsxdev).symbols
  tests/baselines/reference/jsxJsxsCjsTransformKeyPropCustomImportPragma(jsx=react-jsxdev).types
  tests/cases/conformance/jsx/jsxs/jsxJsxsCjsTransformKeyProp.tsx
  tests/cases/conformance/jsx/jsxs/jsxJsxsCjsTransformKeyPropCustomImport.tsx
  tests/cases/conformance/jsx/jsxs/jsxJsxsCjsTransformKeyPropCustomImportPragma.tsx
Labels: For Uncommitted Bug

#41102 Percent-encode source map URLs
  src/compiler/emitter.ts
  tests/baselines/reference/sourceMapPercentEncoded.js
  tests/baselines/reference/sourceMapPercentEncoded.js.map
  tests/baselines/reference/sourceMapPercentEncoded.sourcemap.txt
  tests/baselines/reference/sourceMapPercentEncoded.symbols
  tests/baselines/reference/sourceMapPercentEncoded.types
  tests/cases/compiler/sourceMapPercentEncoded.ts
Labels: Author: Team, For Milestone Bug

#41186 Don't reduce 'keyof M' for mapped types with non-distributive 'as' clauses
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypeAsClauses.js
  tests/baselines/reference/mappedTypeAsClauses.symbols
  tests/baselines/reference/mappedTypeAsClauses.types
  tests/cases/conformance/types/mapped/mappedTypeAsClauses.ts
Labels: For Milestone Bug

#40634 Tracing work
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/parser.ts
  src/compiler/program.ts
  src/compiler/tracing.ts
  src/compiler/transformer.ts
Labels: Author: Team, For Uncommitted Bug

#40974 fix(40933): Better Error Message for a New Ecmascript Property With a Name Similar to an Existing Property
  src/compiler/checker.ts
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2015.errors.txt
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2016Plus.errors.txt
  tests/baselines/reference/modularizeLibrary_ErrorFromUsingES6FeaturesWithOnlyES5Lib.errors.txt
Labels: For Backlog Bug

#41106 Support partial reverse mapped inferences with tuple types
  src/compiler/checker.ts
  tests/baselines/reference/reverseMappedPartiallyInferableTypes.errors.txt
  tests/baselines/reference/reverseMappedPartiallyInferableTypes.js
  tests/baselines/reference/reverseMappedPartiallyInferableTypes.symbols
  tests/baselines/reference/reverseMappedPartiallyInferableTypes.types
  tests/cases/compiler/reverseMappedPartiallyInferableTypes.ts
Labels: For Milestone Bug

#41204 Pick/41079/release 4.0
  src/compiler/transformers/generators.ts
  tests/baselines/reference/es5-asyncFunctionLongObjectLiteral.js
  tests/baselines/reference/es5-asyncFunctionLongObjectLiteral.symbols
  tests/baselines/reference/es5-asyncFunctionLongObjectLiteral.types
  tests/cases/compiler/es5-asyncFunctionLongObjectLiteral.ts
Labels: For Uncommitted Bug

#41190 Handle the new js binding element alias symbols in JS declaration emit
  src/compiler/checker.ts
  tests/baselines/reference/jsDeclarationsReexportedCjsAlias.js
  tests/baselines/reference/jsDeclarationsReexportedCjsAlias.symbols
  tests/baselines/reference/jsDeclarationsReexportedCjsAlias.types
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsReexportedCjsAlias.ts
Labels: Author: Team, For Milestone Bug

#41177 fix(41176): Missing Compiler API predicate function: isTemplateLiteralTypeNode
  src/compiler/factory/nodeTests.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Uncommitted Bug

#41180 Add tracepoints within createProgram
  src/compiler/program.ts
Labels: For Uncommitted Bug

#40968 Don't emit duplicate triple-slash directives when using API to print a .d.ts
  src/compiler/emitter.ts
  src/testRunner/unittests/printer.ts
Labels: Author: Team, For Milestone Bug

#40593 Migrate 'ts.performance' to use native performance hooks when available
  src/compiler/diagnosticMessages.json
  src/compiler/performance.ts
  src/compiler/performanceCore.ts
  src/compiler/performanceTimestamp.ts
  src/compiler/tsconfig.json
  src/executeCommandLine/executeCommandLine.ts
  src/shims/tsconfig.json
  src/testRunner/unittests/tscWatch/helpers.ts
Labels: Author: Team, For Uncommitted Bug

#41221 Make 'getIndentString' just use a loop.
  src/compiler/utilities.ts
  tests/baselines/reference/commentWithUnreasonableIndentationLevel01.js
  tests/baselines/reference/commentWithUnreasonableIndentationLevel01.symbols
  tests/baselines/reference/commentWithUnreasonableIndentationLevel01.types
  tests/cases/compiler/commentWithUnreasonableIndentationLevel01.ts
Labels: For Milestone Bug

#41253 Fix dependency order and observer registration
  src/compiler/performance.ts
  src/compiler/performanceCore.ts
  src/compiler/tsconfig.json
Labels: Author: Team, For Uncommitted Bug

#41261 Stop doing tracing work when tracing is disabled
  src/compiler/tracing.ts
Labels: For Uncommitted Bug

#41272 LEGO: Pull request from lego/hb_998_20201027121037794 to master
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#41011 fix(40994): Generate 'get' and 'set' accessors refactoring with optional property causes compiler error
  src/services/codefixes/fixPropertyOverrideAccessor.ts
  src/services/codefixes/generateAccessors.ts
  src/services/refactors/generateGetAccessorAndSetAccessor.ts
  tests/cases/fourslash/refactorConvertToGetAccessAndSetAccess37.ts
  tests/cases/fourslash/refactorConvertToGetAccessAndSetAccess38.ts
  tests/cases/fourslash/refactorConvertToGetAccessAndSetAccess39.ts
  tests/cases/fourslash/refactorConvertToGetAccessAndSetAccess40.ts
Labels: For Uncommitted Bug

#41218 Don't cache Ternary.Maybe results when recursion is encountered during variance measurement
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/varianceMeasurement.errors.txt
  tests/baselines/reference/varianceMeasurement.js
  tests/baselines/reference/varianceMeasurement.symbols
  tests/baselines/reference/varianceMeasurement.types
  tests/cases/compiler/varianceMeasurement.ts
Labels: For Milestone Bug

#41257 Fix visibility lookup for cjs require aliases
  src/compiler/checker.ts
  tests/baselines/reference/jsDeclarationsImportAliasExposedWithinNamespaceCjs.js
  tests/baselines/reference/jsDeclarationsImportAliasExposedWithinNamespaceCjs.types
Labels: Author: Team, For Uncommitted Bug

#41191 Track control flow for comma expressions in call expressions
  src/compiler/binder.ts
  src/compiler/checker.ts
  tests/baselines/reference/controlFlowCommaExpressionFunctionCall.js
  tests/baselines/reference/controlFlowCommaExpressionFunctionCall.symbols
  tests/baselines/reference/controlFlowCommaExpressionFunctionCall.types
  tests/cases/compiler/controlFlowCommaExpressionFunctionCall.ts
Labels: Author: Team, For Uncommitted Bug

#41267 fix(41244): Wrong quote type preference detection when importHelpers are set to true
  src/services/utilities.ts
  tests/cases/fourslash/importFixes_quotePreferenceDouble_importHelpers.ts
  tests/cases/fourslash/importFixes_quotePreferenceSingle_importHelpers.ts
Labels: For Milestone Bug

#40490 Fix two issues with ConvertToTypeOnlyExport codefix
  src/services/codefixes/convertToTypeOnlyExport.ts
  tests/cases/fourslash/codeFixConvertToTypeOnlyExport1.ts
  tests/cases/fourslash/codeFixConvertToTypeOnlyExport3.ts
Labels: For Backlog Bug

#41276 Remove string literals from unions with matching template literals
  src/compiler/checker.ts
  tests/baselines/reference/templateLiteralTypesPatterns.errors.txt
  tests/baselines/reference/templateLiteralTypesPatterns.js
  tests/baselines/reference/templateLiteralTypesPatterns.symbols
  tests/baselines/reference/templateLiteralTypesPatterns.types
  tests/cases/conformance/types/literal/templateLiteralTypesPatterns.ts
Labels: For Uncommitted Bug

#41274 feat(41249): Allow import.meta with module: es2020
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/importMeta(module=commonjs,target=es5).errors.txt
  tests/baselines/reference/importMeta(module=commonjs,target=esnext).errors.txt
  tests/baselines/reference/importMeta(module=es2020,target=es5).errors.txt
  tests/baselines/reference/importMeta(module=es2020,target=es5).js
  tests/baselines/reference/importMeta(module=es2020,target=es5).symbols
  tests/baselines/reference/importMeta(module=es2020,target=es5).types
  tests/baselines/reference/importMeta(module=es2020,target=esnext).errors.txt
  tests/baselines/reference/importMeta(module=es2020,target=esnext).js
  tests/baselines/reference/importMeta(module=es2020,target=esnext).symbols
  tests/baselines/reference/importMeta(module=es2020,target=esnext).types
  tests/cases/conformance/es2019/importMeta/importMeta.ts
Labels: For Milestone Bug

#41075 allow type narrowing with NonNullExpression
  src/compiler/binder.ts
  src/compiler/checker.ts
  tests/baselines/reference/narrowingWithNonNullExpression.js
  tests/baselines/reference/narrowingWithNonNullExpression.symbols
  tests/baselines/reference/narrowingWithNonNullExpression.types
  tests/cases/compiler/narrowingWithNonNullExpression.ts
Labels: For Backlog Bug

#41282 When creating synthetic default symbol set parent as module symbol
  src/compiler/checker.ts
  tests/cases/fourslash/exportEqualNamespaceClassESModuleInterop.ts
Labels: Author: Team, For Milestone Bug

#41304 fix(41208): add insertSpaceAfterOpeningAndBeforeClosingEmptyBraces tsserver protocol
  src/server/protocol.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
Labels: For Uncommitted Bug

#41308 Don't relate unmatched parameter positions in signatures
  src/compiler/checker.ts
  tests/baselines/reference/unmatchedParameterPositions.js
  tests/baselines/reference/unmatchedParameterPositions.symbols
  tests/baselines/reference/unmatchedParameterPositions.types
  tests/cases/compiler/unmatchedParameterPositions.ts
Labels: For Milestone Bug

#41287 Bind `module.export = {Thing}` with alias symbols
  src/compiler/binder.ts
  src/compiler/checker.ts
  tests/baselines/reference/findAllRefsCommonJsRequire3.baseline.jsonc
  tests/baselines/reference/jsDeclarationsCommonjsRelativePath.js
  tests/baselines/reference/jsDeclarationsCommonjsRelativePath.symbols
  tests/baselines/reference/jsDeclarationsCommonjsRelativePath.types
  tests/baselines/reference/jsDeclarationsDocCommentsOnConsts.symbols
  tests/baselines/reference/jsDeclarationsDocCommentsOnConsts.types
  tests/baselines/reference/jsDeclarationsExportForms.js
  tests/baselines/reference/jsDeclarationsExportForms.symbols
  tests/baselines/reference/jsDeclarationsExportForms.types
  tests/baselines/reference/jsDeclarationsExportedClassAliases.js
  tests/baselines/reference/jsDeclarationsExportedClassAliases.symbols
  tests/baselines/reference/jsDeclarationsExportedClassAliases.types
  tests/baselines/reference/jsDeclarationsImportAliasExposedWithinNamespaceCjs.symbols
  tests/baselines/reference/jsDeclarationsImportAliasExposedWithinNamespaceCjs.types
  tests/baselines/reference/jsDeclarationsReexportedCjsAlias.symbols
  tests/baselines/reference/jsDeclarationsReexportedCjsAlias.types
  tests/baselines/reference/jsDeclarationsReferenceToClassInstanceCrossFile.js
  tests/baselines/reference/jsDeclarationsReferenceToClassInstanceCrossFile.symbols
  tests/baselines/reference/jsDeclarationsReferenceToClassInstanceCrossFile.types
  tests/baselines/reference/jsDeclarationsTypeAliases.symbols
  tests/baselines/reference/jsDeclarationsTypeAliases.types
  tests/baselines/reference/jsDeclarationsTypeReferences.symbols
  tests/baselines/reference/jsDeclarationsTypeReferences.types
  tests/baselines/reference/jsDeclarationsTypeReferences2.symbols
  tests/baselines/reference/jsDeclarationsTypeReferences2.types
  tests/baselines/reference/jsDeclarationsTypedefAndImportTypes.symbols
  tests/baselines/reference/jsDeclarationsTypedefAndImportTypes.types
  tests/baselines/reference/jsDeclarationsTypedefPropertyAndExportAssignment.symbols
  tests/baselines/reference/jsDeclarationsTypedefPropertyAndExportAssignment.types
  tests/baselines/reference/jsExportMemberMergedWithModuleAugmentation.errors.txt
  tests/baselines/reference/jsExportMemberMergedWithModuleAugmentation.symbols
  tests/baselines/reference/jsExportMemberMergedWithModuleAugmentation.types
  tests/baselines/reference/moduleExportAlias3.symbols
  tests/baselines/reference/moduleExportAlias3.types
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsReferenceToClassInstanceCrossFile.ts
  tests/cases/fourslash/completionsImport_require_addNew.ts
  tests/cases/fourslash/completionsImport_require_addToExisting.ts
Labels: Author: Team

#41312 Bind comma expression LHS call expressions
  src/compiler/binder.ts
  tests/baselines/reference/controlFlowCommaExpressionAssertionWithinTernary.js
  tests/baselines/reference/controlFlowCommaExpressionAssertionWithinTernary.symbols
  tests/baselines/reference/controlFlowCommaExpressionAssertionWithinTernary.types
  tests/cases/compiler/controlFlowCommaExpressionAssertionWithinTernary.ts
Labels: Author: Team, For Backlog Bug

#41314 Fix crashes when the global JSX namespace is an alias
  src/compiler/checker.ts
  tests/baselines/reference/jsxNamespaceGlobalReexport.js
  tests/baselines/reference/jsxNamespaceGlobalReexport.symbols
  tests/baselines/reference/jsxNamespaceGlobalReexport.types
  tests/baselines/reference/jsxNamespaceGlobalReexportMissingAliasTarget.errors.txt
  tests/baselines/reference/jsxNamespaceGlobalReexportMissingAliasTarget.js
  tests/baselines/reference/jsxNamespaceGlobalReexportMissingAliasTarget.symbols
  tests/baselines/reference/jsxNamespaceGlobalReexportMissingAliasTarget.types
  tests/cases/compiler/jsxNamespaceGlobalReexport.tsx
  tests/cases/compiler/jsxNamespaceGlobalReexportMissingAliasTarget.tsx
Labels: Author: Team, For Uncommitted Bug

#41315 Log AutoImportProvider creation time
  src/server/project.ts
Labels: Author: Team, For Uncommitted Bug

#41222 Fix missing file name of extended source file in synchronizeProjectList when it is missing on disk
  src/compiler/commandLineParser.ts
  src/testRunner/unittests/tsserver/projects.ts
Labels: Author: Team, For Milestone Bug

#41291 noop in setTypeAcquisiton for undefined
  src/server/project.ts
  src/testRunner/unittests/tsserver/inferredProjects.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
Labels: For Uncommitted Bug

#40942 fix(40671): Enable "Convert to template string" on expressions that don't start with a string
  src/services/refactors/convertStringOrTemplateLiteral.ts
  tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_ToTemplateBinaryExprWithElementAccess.ts
  tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_ToTemplateBinaryExprWithPropertyAccess.ts
Labels: For Milestone Bug

#41331 Fix double alias of complex export/import/default/namespace combination
  src/compiler/checker.ts
  tests/baselines/reference/exportAssignmentOfExportNamespaceWithDefault.js
  tests/baselines/reference/exportAssignmentOfExportNamespaceWithDefault.symbols
  tests/baselines/reference/exportAssignmentOfExportNamespaceWithDefault.types
  tests/cases/conformance/externalModules/exportAssignmentOfExportNamespaceWithDefault.ts
Labels: Author: Team, For Milestone Bug

#40985 Adjust typeof import name lookup to better match type query lookup
  src/compiler/checker.ts
  tests/baselines/reference/importTypeTypeofClassStaticLookup.symbols
  tests/baselines/reference/importTypeTypeofClassStaticLookup.types
  tests/cases/compiler/importTypeTypeofClassStaticLookup.ts
Labels: Author: Team, For Milestone Bug

#41330 Auto-include types for the jsx import source in the new jsx transforms
  src/compiler/checker.ts
  src/compiler/commandLineParser.ts
  src/compiler/program.ts
  src/compiler/transformers/jsx.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/testRunner/unittests/tscWatch/incremental.ts
  tests/baselines/reference/jsxJsxsCjsTransformCustomImport(jsx=react-jsx).errors.txt
  tests/baselines/reference/jsxJsxsCjsTransformCustomImport(jsx=react-jsxdev).errors.txt
  tests/baselines/reference/jsxJsxsCjsTransformCustomImportPragma(jsx=react-jsx).errors.txt
  tests/baselines/reference/jsxJsxsCjsTransformCustomImportPragma(jsx=react-jsxdev).errors.txt
  tests/baselines/reference/jsxJsxsCjsTransformKeyPropCustomImport(jsx=react-jsx).errors.txt
  tests/baselines/reference/jsxJsxsCjsTransformKeyPropCustomImport(jsx=react-jsxdev).errors.txt
  tests/baselines/reference/jsxJsxsCjsTransformKeyPropCustomImportPragma(jsx=react-jsx).errors.txt
  tests/baselines/reference/jsxJsxsCjsTransformKeyPropCustomImportPragma(jsx=react-jsxdev).errors.txt
  tests/baselines/reference/jsxNamespaceImplicitImportJSXNamespace.js
  tests/baselines/reference/jsxNamespaceImplicitImportJSXNamespace.symbols
  tests/baselines/reference/jsxNamespaceImplicitImportJSXNamespace.types
  tests/baselines/reference/tscWatch/incremental/jsxImportSource-option-changed-incremental.js
  tests/baselines/reference/tscWatch/incremental/jsxImportSource-option-changed-watch.js
  tests/baselines/reference/tscWatch/programUpdates/updates-emit-on-jsx-option-change.js
  tests/cases/compiler/jsxNamespaceImplicitImportJSXNamespace.tsx
  tests/lib/react16.d.ts
Labels: Author: Team, For Milestone Bug
