Repository microsoft/TypeScript, pull requests merged in 2021-03, with the labels that each got.

#42556 Optimize checking involving large discriminated union types
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/typeParameterLeak.types
  tests/baselines/reference/unionOfClassCalls.types
Labels: Author: Team, For Uncommitted Bug

#42962 Tracing: dump more information about types
  src/compiler/tracing.ts
Labels: Author: Team, For Uncommitted Bug

#42890 Add 'data' property to completion entry for better coordination between completions and completion details
  src/compiler/checker.ts
  src/compiler/types.ts
  src/harness/client.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/harness/harnessLanguageService.ts
  src/server/protocol.ts
  src/server/session.ts
  src/services/completions.ts
  src/services/services.ts
  src/services/shims.ts
  src/services/types.ts
  src/testRunner/unittests/services/cancellableLanguageServiceOperations.ts
  src/testRunner/unittests/tsserver/completions.ts
  src/testRunner/unittests/tsserver/partialSemanticServer.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/completionListForUnicodeEscapeName.ts
  tests/cases/fourslash/completionsImport_defaultAndNamedConflict.ts
  tests/cases/fourslash/completionsImport_exportEquals_anonymous.ts
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/server/completionsImport_defaultAndNamedConflict_server.ts
Labels: Author: Team, For Milestone Bug

#43028 Update package-lock.json.
  package-lock.json
Labels: For Uncommitted Bug

#42975 Add undefined to Symbol.declarations' type
  src/compiler/binder.ts
  src/compiler/builderState.ts
  src/compiler/checker.ts
  src/compiler/core.ts
  src/compiler/moduleSpecifiers.ts
  src/compiler/transformers/declarations.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/harness/fourslashImpl.ts
  src/services/callHierarchy.ts
  src/services/codefixes/convertFunctionToEs6Class.ts
  src/services/codefixes/generateAccessors.ts
  src/services/completions.ts
  src/services/findAllReferences.ts
  src/services/getEditsForFileRename.ts
  src/services/goToDefinition.ts
  src/services/importTracker.ts
  src/services/refactors/convertOverloadListToSingleSignature.ts
  src/services/refactors/convertParamsToDestructuredObject.ts
  src/services/refactors/extractType.ts
  src/services/refactors/moveToNewFile.ts
  src/services/rename.ts
  src/services/symbolDisplay.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug, Housekeeping

#42539 Support go-to-definition for imports of arbitrary files
  src/harness/client.ts
  src/harness/fourslashImpl.ts
  src/server/protocol.ts
  src/services/findAllReferences.ts
  src/services/goToDefinition.ts
  src/services/services.ts
  src/services/types.ts
  src/services/utilities.ts
  src/testRunner/unittests/tsserver/partialSemanticServer.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/goToDefinitionCSSPatternAmbientModule.ts
  tests/cases/fourslash/goToDefinitionScriptImport.ts
  tests/cases/fourslash/server/goToDefinitionScriptImportServer.ts
Labels: Author: Team, For Milestone Bug

#43024 Only filter ignored paths from module specifier generation if there exists a better option
  src/compiler/moduleSpecifiers.ts
  tests/baselines/reference/nodeModuleReexportFromDottedPath.js
  tests/baselines/reference/nodeModuleReexportFromDottedPath.symbols
  tests/baselines/reference/nodeModuleReexportFromDottedPath.types
  tests/cases/compiler/nodeModuleReexportFromDottedPath.ts
Labels: Author: Team, For Milestone Bug

#42899 typo
  src/server/editorServices.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
Labels: For Uncommitted Bug

#42816 Fixed typo error.
  CONTRIBUTING.md
Labels: For Uncommitted Bug

#42900 Possible typo
  src/server/project.ts
Labels: For Uncommitted Bug

#42792 fix(42765): require should not work in ts files
  src/compiler/checker.ts
  tests/baselines/reference/resolveNameWithNamspace.js
  tests/baselines/reference/resolveNameWithNamspace.symbols
  tests/baselines/reference/resolveNameWithNamspace.types
  tests/cases/compiler/resolveNameWithNamspace.ts
Labels: For Backlog Bug

#43033 Add undefined to Symbol.valueDeclaration
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/moduleSpecifiers.ts
  src/compiler/transformers/declarations.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/compiler/utilitiesPublic.ts
  src/services/codefixes/convertConstToLet.ts
  src/services/codefixes/convertFunctionToEs6Class.ts
  src/services/codefixes/convertToAsyncFunction.ts
  src/services/codefixes/fixSpelling.ts
  src/services/codefixes/importFixes.ts
  src/services/codefixes/inferFromUsage.ts
  src/services/importTracker.ts
  src/services/refactors/extractType.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#43021 fix(43006): 'Add missing function decoration' quick fix can duplicate //@ts-check comment
  src/services/codefixes/fixAddMissingMember.ts
  src/services/codefixes/helpers.ts
  tests/cases/fourslash/codeFixAddMissingFunctionDeclaration17.ts
  tests/cases/fourslash/codeFixAddMissingFunctionDeclaration18.ts
Labels: For Uncommitted Bug

#42542 Move fixed chunk size polling as a watch option and move it out of server
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  src/compiler/sys.ts
  src/compiler/tsbuildPublic.ts
  src/compiler/types.ts
  src/harness/virtualFileSystemWithWatch.ts
  src/server/protocol.ts
  src/testRunner/unittests/config/commandLineParsing.ts
  src/testRunner/unittests/tscWatch/watchEnvironment.ts
  src/tsserver/nodeServer.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/tscWatch/watchEnvironment/watchFile/setting-default-as-fixed-chunk-size-watch-file-works.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchFile/using-fixed-chunk-size-polling.js
Labels: Author: Team, For Milestone Bug

#43052 Delete old, different-case name of quickInfoJSDocTags.baseline
  tests/baselines/reference/quickInfoJsDocTags.baseline
Labels: Author: Team, For Uncommitted Bug

#43055 Filter transient flags to fix useDefineForClassFields
  tests/baselines/reference/intersectionType_useDefineForClassFields.js
  tests/baselines/reference/intersectionType_useDefineForClassFields.symbols
  tests/baselines/reference/intersectionType_useDefineForClassFields.types
  tests/cases/compiler/intersectionType_useDefineForClassFields.ts
Labels: For Milestone Bug

#35494 capture thisArg of optionalChaining in parens
  src/compiler/transformers/es2020.ts
  src/testRunner/unittests/evaluation/optionalCall.ts
  tests/baselines/reference/parentheses.js
  tests/cases/conformance/expressions/optionalChaining/callChain/parentheses.ts
Labels: For Milestone Bug

#42966 Do a shallow clone for Docker tests.
  tests/cases/docker/azure-sdk/Dockerfile
  tests/cases/docker/chrome-devtools-frontend-next/Dockerfile
  tests/cases/docker/office-ui-fabric/Dockerfile
  tests/cases/docker/prettier/Dockerfile
  tests/cases/docker/pyright/Dockerfile
  tests/cases/docker/rxjs/Dockerfile
  tests/cases/docker/vscode/Dockerfile
  tests/cases/docker/vue-next/Dockerfile
  tests/cases/docker/xterm.js/Dockerfile
Labels: For Uncommitted Bug

#43070 Update the DOM: March 03, 2021
  src/lib/dom.generated.d.ts
  src/lib/dom.iterable.generated.d.ts
  src/lib/webworker.generated.d.ts
  src/lib/webworker.iterable.generated.d.ts
  tests/baselines/reference/globalThisBlockscopedProperties.types
  tests/baselines/reference/intersectionsOfLargeUnions2.errors.txt
  tests/baselines/reference/mappedTypeRecursiveInference.types
  tests/baselines/reference/moduleDeclarationExportStarShadowingGlobalIsNameable.symbols
Labels: Author: Team, For Uncommitted Bug

#43083 Expose 'reservedInNestedScopes' option when creating temp and loop vars
  src/compiler/factory/nodeFactory.ts
  src/compiler/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Milestone Bug

#42392 fix(39836): `unknown` type declaration for catch argument doesn't work in js
  src/compiler/checker.ts
  src/compiler/parser.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/jsdocCatchClauseWithTypeAnnotation.errors.txt
  tests/baselines/reference/jsdocCatchClauseWithTypeAnnotation.js
  tests/baselines/reference/jsdocCatchClauseWithTypeAnnotation.symbols
  tests/baselines/reference/jsdocCatchClauseWithTypeAnnotation.types
  tests/baselines/reference/jsdocVariableDeclarationWithTypeAnnotation.js
  tests/baselines/reference/jsdocVariableDeclarationWithTypeAnnotation.symbols
  tests/baselines/reference/jsdocVariableDeclarationWithTypeAnnotation.types
  tests/cases/conformance/jsdoc/jsdocCatchClauseWithTypeAnnotation.ts
  tests/cases/conformance/jsdoc/jsdocVariableDeclarationWithTypeAnnotation.ts
Labels: For Backlog Bug

#43065 Relax requirements on index signatures to 'any' when a type also contains a string index signature to 'any'
  src/compiler/checker.ts
  tests/baselines/reference/objectTypeWithStringAndNumberIndexSignatureToAny.errors.txt
  tests/baselines/reference/objectTypeWithStringAndNumberIndexSignatureToAny.js
  tests/baselines/reference/objectTypeWithStringAndNumberIndexSignatureToAny.symbols
  tests/baselines/reference/objectTypeWithStringAndNumberIndexSignatureToAny.types
  tests/cases/conformance/types/members/objectTypeWithStringAndNumberIndexSignatureToAny.ts
Labels: For Milestone Bug

#42747 Properly instantiate inferred constraints in conditional types
  src/compiler/checker.ts
  tests/baselines/reference/inferTypeParameterConstraints.js
  tests/baselines/reference/inferTypeParameterConstraints.symbols
  tests/baselines/reference/inferTypeParameterConstraints.types
  tests/cases/compiler/inferTypeParameterConstraints.ts
Labels: Author: Team, For Milestone Bug

#42952 Unnecessary elaboration about not being assignable to type parameters
  src/compiler/checker.ts
  tests/baselines/reference/callSignatureAssignabilityInInheritance6.errors.txt
  tests/baselines/reference/conditionalTypes1.errors.txt
  tests/baselines/reference/constructSignatureAssignabilityInInheritance6.errors.txt
  tests/baselines/reference/doNotElaborateAssignabilityToTypeParameters.errors.txt
  tests/baselines/reference/doNotElaborateAssignabilityToTypeParameters.js
  tests/baselines/reference/doNotElaborateAssignabilityToTypeParameters.symbols
  tests/baselines/reference/doNotElaborateAssignabilityToTypeParameters.types
  tests/baselines/reference/genericCallWithObjectTypeArgsAndInitializers.errors.txt
  tests/baselines/reference/mappedTypeRelationships.errors.txt
  tests/baselines/reference/recursiveConditionalTypes.errors.txt
  tests/baselines/reference/subtypesOfTypeParameterWithConstraints.errors.txt
  tests/baselines/reference/subtypesOfTypeParameterWithRecursiveConstraints.errors.txt
  tests/baselines/reference/subtypingWithConstructSignatures6.errors.txt
  tests/baselines/reference/typeParameterAssignability2.errors.txt
  tests/baselines/reference/typeParameterDiamond2.errors.txt
  tests/baselines/reference/typeParameterDiamond3.errors.txt
  tests/baselines/reference/typeParameterDiamond4.errors.txt
  tests/baselines/reference/typeParametersShouldNotBeEqual.errors.txt
  tests/baselines/reference/typeParametersShouldNotBeEqual2.errors.txt
  tests/baselines/reference/unionTypesAssignability.errors.txt
  tests/cases/compiler/doNotElaborateAssignabilityToTypeParameters.ts
Labels: For Backlog Bug

#42756 Update parseInt parameter name and jsdoc
  src/lib/es2015.core.d.ts
  src/lib/es5.d.ts
  tests/baselines/reference/abstractPropertyInConstructor.types
  tests/baselines/reference/completionsCommentsClass.baseline
  tests/baselines/reference/completionsCommentsClassMembers.baseline
  tests/baselines/reference/completionsCommentsCommentParsing.baseline
  tests/baselines/reference/completionsCommentsFunctionDeclaration.baseline
  tests/baselines/reference/completionsCommentsFunctionExpression.baseline
  tests/baselines/reference/externFunc.types
  tests/baselines/reference/parserRealSource11.types
Labels: For Backlog Bug

#43086 Remove undefined from optional properties when inferring to index signatures
  src/compiler/checker.ts
  tests/baselines/reference/inferenceOptionalPropertiesToIndexSignatures.js
  tests/baselines/reference/inferenceOptionalPropertiesToIndexSignatures.symbols
  tests/baselines/reference/inferenceOptionalPropertiesToIndexSignatures.types
  tests/cases/compiler/inferenceOptionalPropertiesToIndexSignatures.ts
Labels: Author: Team, For Milestone Bug

#42472 Exclude enum/number compatibility rule from comparable relation
  src/compiler/checker.ts
  tests/baselines/reference/equalityWithEnumTypes.errors.txt
  tests/baselines/reference/equalityWithEnumTypes.js
  tests/baselines/reference/equalityWithEnumTypes.symbols
  tests/baselines/reference/equalityWithEnumTypes.types
  tests/cases/conformance/types/typeRelationships/comparable/equalityWithEnumTypes.ts
Labels: Author: Team, Breaking Change, For Milestone Bug

#43166 Fix37991
  src/compiler/checker.ts
  tests/baselines/reference/tslibInJs.errors.txt
  tests/baselines/reference/tslibInJs.symbols
  tests/baselines/reference/tslibInJs.types
  tests/cases/compiler/tslibInJs.ts
Labels: Author: Team, For Milestone Bug

#43165 Don't inherit jsdoc tags from overloaded signatures
  src/services/services.ts
  tests/baselines/reference/deprecatedInheritedJSDocOverload.baseline
  tests/cases/fourslash/deprecatedInheritedJSDocOverload.ts
Labels: Author: Team, For Milestone Bug

#42599 Error message clarification for accessing protected members
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/protectedClassPropertyAccessibleWithinNestedSubclass1.errors.txt
  tests/baselines/reference/protectedClassPropertyAccessibleWithinSubclass2.errors.txt
  tests/baselines/reference/protectedInstanceMemberAccessibility.errors.txt
  tests/baselines/reference/protectedMembers.errors.txt
Labels: For Backlog Bug

#43084 Ensure that when new file affecting global scope is added, the signatures are updated
  src/compiler/builder.ts
  src/testRunner/unittests/tsc/incremental.ts
  tests/baselines/reference/tsc/incremental/initial-build/when-global-file-is-added,-the-signatures-are-updated.js
Labels: Author: Team, For Uncommitted Bug

#42276 fix(42265): Missing error when accessing abstract property in constructor via destructuring
  src/compiler/checker.ts
  src/compiler/utilities.ts
  tests/baselines/reference/abstractPropertyInConstructor.errors.txt
  tests/baselines/reference/abstractPropertyInConstructor.js
  tests/baselines/reference/abstractPropertyInConstructor.symbols
  tests/baselines/reference/abstractPropertyInConstructor.types
  tests/baselines/reference/destructureComputedProperty.errors.txt
  tests/baselines/reference/privateProtectedMembersAreNotAccessibleDestructuring.errors.txt
  tests/cases/compiler/abstractPropertyInConstructor.ts
Labels: For Backlog Bug

#40379 Fix missing func modifier
  src/services/refactors/convertArrowFunctionOrFunctionExpression.ts
  tests/cases/fourslash/refactorConvertArrowFunctionOrFunctionExpression_AsyncModifiers.ts
Labels: For Milestone Bug

#41103 fix(41027): recursive private static gets missed in --noUnusedLocals
  src/compiler/checker.ts
  tests/baselines/reference/unusedPrivateStaticMembers.errors.txt
  tests/baselines/reference/unusedPrivateStaticMembers.js
  tests/baselines/reference/unusedPrivateStaticMembers.symbols
  tests/baselines/reference/unusedPrivateStaticMembers.types
  tests/cases/compiler/unusedPrivateStaticMembers.ts
Labels: For Backlog Bug

#40297 Don't crash when renaming a JS property declared via module.exports
  src/services/importTracker.ts
  tests/baselines/reference/findAllRefsCommonJsRequire2.baseline.jsonc
  tests/baselines/reference/indirectJsRequireRename.baseline.jsonc
  tests/cases/fourslash/indirectJsRequireRename.ts
Labels: Author: Team, For Uncommitted Bug

#38610 Fix #38608
  src/compiler/checker.ts
  tests/baselines/reference/fixSignatureCaching.errors.txt
  tests/baselines/reference/fixSignatureCaching.symbols
  tests/baselines/reference/fixSignatureCaching.types
  tests/baselines/reference/inKeywordTypeguard.errors.txt
  tests/baselines/reference/inKeywordTypeguard.js
  tests/baselines/reference/inKeywordTypeguard.symbols
  tests/baselines/reference/inKeywordTypeguard.types
  tests/cases/compiler/inKeywordTypeguard.ts
Labels: For Uncommitted Bug

#35863 Fixes non-null assertion applied to type narrowed to never not issuing an error.
  src/compiler/checker.ts
  tests/baselines/reference/exhaustiveSwitchStatements1.errors.txt
  tests/baselines/reference/exhaustiveSwitchStatements1.js
  tests/baselines/reference/exhaustiveSwitchStatements1.symbols
  tests/baselines/reference/exhaustiveSwitchStatements1.types
  tests/cases/conformance/controlFlow/exhaustiveSwitchStatements1.ts
Labels: For Backlog Bug

#42424 Accept generics for defineProperty
  src/lib/es5.d.ts
  tests/baselines/reference/checkExportsObjectAssignProperty.types
  tests/baselines/reference/checkExportsObjectAssignPrototypeProperty.types
  tests/baselines/reference/checkObjectDefineProperty.types
  tests/baselines/reference/checkOtherObjectAssignProperty.types
  tests/baselines/reference/ensureNoCrashExportAssignmentDefineProperrtyPotentialMerge.types
  tests/baselines/reference/esNextWeakRefs_IterableWeakMap.types
  tests/baselines/reference/excessPropertyCheckWithEmptyObject.types
  tests/baselines/reference/getterSetterNonAccessor.types
  tests/baselines/reference/importAliasModuleExports.types
  tests/baselines/reference/javascriptDefinePropertyPrototypeNonConstructor.types
  tests/baselines/reference/jsCheckObjectDefineThisNoCrash.types
  tests/baselines/reference/jsDeclarationsExportDefinePropertyEmit.types
  tests/baselines/reference/jsDeclarationsGetterSetter.types
  tests/baselines/reference/jsExpandoObjectDefineProperty.types
  tests/baselines/reference/jsFileESModuleWithEnumTag.types
  tests/baselines/reference/lateBoundAssignmentDeclarationSupport3.types
  tests/baselines/reference/lateBoundAssignmentDeclarationSupport6.types
  tests/baselines/reference/objectLitGetterSetter.types
  tests/baselines/reference/parserUsingConstructorAsIdentifier.types
  tests/lib/lib.d.ts
Labels: For Uncommitted Bug

#43197 Bloomberg computed property name fix
  src/compiler/checker.ts
  src/compiler/transformer.ts
  src/compiler/transformers/classFields.ts
  src/compiler/transformers/es2017.ts
  src/compiler/transformers/es2018.ts
  src/compiler/transformers/generators.ts
  src/compiler/transformers/module/system.ts
  src/compiler/types.ts
  src/compiler/visitorPublic.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/classDeclarationLoop.js
  tests/baselines/reference/classDeclarationLoop.symbols
  tests/baselines/reference/classDeclarationLoop.types
  tests/baselines/reference/classExpressionLoop.js
  tests/baselines/reference/classExpressionLoop.symbols
  tests/baselines/reference/classExpressionLoop.types
  tests/baselines/reference/classExpressionWithStaticProperties3.js
  tests/baselines/reference/computedPropertyNames52(target=es2015).js
  tests/baselines/reference/computedPropertyNames52(target=es2015).symbols
  tests/baselines/reference/computedPropertyNames52(target=es2015).types
  tests/baselines/reference/computedPropertyNames52(target=es5).js
  tests/baselines/reference/computedPropertyNames52(target=es5).symbols
  tests/baselines/reference/computedPropertyNames52(target=es5).types
  tests/baselines/reference/privateNameClassExpressionLoop.js
  tests/baselines/reference/privateNameClassExpressionLoop.symbols
  tests/baselines/reference/privateNameClassExpressionLoop.types
  tests/cases/conformance/classes/classDeclarations/classDeclarationLoop.ts
  tests/cases/conformance/classes/classExpressions/classExpressionLoop.ts
  tests/cases/conformance/classes/members/privateNames/privateNameClassExpressionLoop.ts
  tests/cases/conformance/es6/computedProperties/computedPropertyNames52.ts
Labels: Author: Team, For Uncommitted Bug

#30639 Add missing relationship allowing a type to be assignable to a conditional when assignable to both branches
  src/compiler/checker.ts
  tests/baselines/reference/conditionalTypeAssignabilityWhenDeferred.errors.txt
  tests/baselines/reference/conditionalTypeAssignabilityWhenDeferred.js
  tests/baselines/reference/conditionalTypeAssignabilityWhenDeferred.symbols
  tests/baselines/reference/conditionalTypeAssignabilityWhenDeferred.types
  tests/baselines/reference/conditionalTypeSubclassExtendsTypeParam.js
  tests/baselines/reference/conditionalTypeSubclassExtendsTypeParam.symbols
  tests/baselines/reference/conditionalTypeSubclassExtendsTypeParam.types
  tests/baselines/reference/ramdaToolsNoInfinite2.js
  tests/baselines/reference/ramdaToolsNoInfinite2.symbols
  tests/baselines/reference/ramdaToolsNoInfinite2.types
  tests/cases/compiler/conditionalTypeAssignabilityWhenDeferred.ts
  tests/cases/compiler/conditionalTypeSubclassExtendsTypeParam.ts
  tests/cases/compiler/ramdaToolsNoInfinite2.ts
Labels: Author: Team, For Milestone Bug

#39827 Updated error message for TS2539
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/arithAssignTyping.errors.txt
  tests/baselines/reference/assignAnyToEveryType.errors.txt
  tests/baselines/reference/assignToEnum.errors.txt
  tests/baselines/reference/assignToExistingClass.errors.txt
  tests/baselines/reference/assignmentLHSIsValue.errors.txt
  tests/baselines/reference/assignmentToFunction.errors.txt
  tests/baselines/reference/assignmentToParenthesizedIdentifiers.errors.txt
  tests/baselines/reference/assignmentToReferenceTypes.errors.txt
  tests/baselines/reference/assignments.errors.txt
  tests/baselines/reference/compoundAssignmentLHSIsValue.errors.txt
  tests/baselines/reference/compoundExponentiationAssignmentLHSIsValue.errors.txt
  tests/baselines/reference/concatClassAndString.errors.txt
  tests/baselines/reference/decrementOperatorWithAnyOtherTypeInvalidOperations.errors.txt
  tests/baselines/reference/decrementOperatorWithEnumTypeInvalidOperations.errors.txt
  tests/baselines/reference/importsImplicitlyReadonly.errors.txt
  tests/baselines/reference/incrementOperatorWithAnyOtherTypeInvalidOperations.errors.txt
  tests/baselines/reference/incrementOperatorWithEnumTypeInvalidOperations.errors.txt
  tests/baselines/reference/invalidBooleanAssignments.errors.txt
  tests/baselines/reference/invalidNumberAssignments.errors.txt
  tests/baselines/reference/invalidStringAssignments.errors.txt
  tests/baselines/reference/invalidUndefinedAssignments.errors.txt
  tests/baselines/reference/invalidVoidAssignments.errors.txt
  tests/baselines/reference/parserStrictMode3-negative.errors.txt
  tests/baselines/reference/parserStrictMode3.errors.txt
  tests/baselines/reference/parserStrictMode5.errors.txt
  tests/baselines/reference/parserStrictMode6-negative.errors.txt
  tests/baselines/reference/parserStrictMode6.errors.txt
  tests/baselines/reference/parserStrictMode7.errors.txt
  tests/baselines/reference/unaryOperatorsInStrictMode.errors.txt
  tests/baselines/reference/user/debug.log
  tests/baselines/reference/user/graceful-fs.log
  tests/baselines/reference/user/url-search-params.log
  tests/baselines/reference/validNullAssignments.errors.txt
Labels: For Uncommitted Bug

#43204 Bigint constructor forbids object null undefined
  src/lib/es2020.bigint.d.ts
  tests/baselines/reference/constructBigint.errors.txt
  tests/baselines/reference/constructBigint.js
  tests/baselines/reference/constructBigint.symbols
  tests/baselines/reference/constructBigint.types
  tests/cases/conformance/es2020/constructBigint.ts
Labels: Author: Team, For Uncommitted Bug

#43205 Improvements to dts emit for tsbuildinfo
  src/compiler/builderState.ts
  src/compiler/emitter.ts
  src/compiler/utilities.ts
  src/testRunner/unittests/tsbuild/javascriptProjectEmit.ts
  tests/baselines/reference/tsbuild/emitDeclarationOnly/initial-build/only-dts-output-in-circular-import-project-with-emitDeclarationOnly-and-declarationMap.js
  tests/baselines/reference/tsbuild/emitDeclarationOnly/initial-build/only-dts-output-in-non-circular-imports-project-with-emitDeclarationOnly.js
  tests/baselines/reference/tsbuild/emptyFiles/initial-build/does-not-have-empty-files-diagnostic-when-files-is-empty-and-references-are-provided.js
  tests/baselines/reference/tsbuild/javascriptProjectEmit/initial-build/loads-js-based-projects-with-non-moved-json-files-and-emits-them-correctly.js
  tests/baselines/reference/tsbuild/javascriptProjectEmit/initial-build/loads-outfile-js-projects-and-concatenates-them-correctly.js
  tests/baselines/reference/tsbuild/outFile/initial-build/non-module-projects-without-prepend.js
  tests/baselines/reference/tsbuild/resolveJsonModule/initial-build/importing-json-module-from-project-reference.js
  tests/baselines/reference/tsbuild/sample1/incremental-declaration-changes/Detects-type-only-changes-in-upstream-projects.js
  tests/baselines/reference/tsbuild/sample1/incremental-declaration-changes/rebuilds-from-start-if-force-option-is-set.js
  tests/baselines/reference/tsbuild/sample1/initial-build/always-builds-under-with-force-option.js
  tests/baselines/reference/tsbuild/sample1/initial-build/builds-correctly-when-declarationDir-is-specified.js
  tests/baselines/reference/tsbuild/sample1/initial-build/builds-correctly-when-outDir-is-specified.js
  tests/baselines/reference/tsbuild/sample1/initial-build/can-detect-when-and-what-to-rebuild.js
  tests/baselines/reference/tsbuild/sample1/initial-build/does-not-build-downstream-projects-if-upstream-projects-have-errors.js
  tests/baselines/reference/tsbuild/sample1/initial-build/explainFiles.js
  tests/baselines/reference/tsbuild/sample1/initial-build/listEmittedFiles.js
  tests/baselines/reference/tsbuild/sample1/initial-build/listFiles.js
  tests/baselines/reference/tsbuild/sample1/initial-build/rebuilds-when-extended-config-file-changes.js
  tests/baselines/reference/tsbuild/sample1/initial-build/sample.js
  tests/baselines/reference/tsbuild/sample1/initial-build/when-esModuleInterop-option-changes.js
  tests/baselines/reference/tsbuild/sample1/initial-build/when-logic-specifies-tsBuildInfoFile.js
  tests/baselines/reference/tsbuild/watchMode/programUpdates/creates-solution-in-watch-mode.js
  tests/baselines/reference/tsbuild/watchMode/programUpdates/incremental-updates-in-verbose-mode.js
  tests/baselines/reference/tsbuild/watchMode/programUpdates/reportErrors/when-preserveWatchOutput-is-not-used.js
  tests/baselines/reference/tsbuild/watchMode/programUpdates/reportErrors/when-preserveWatchOutput-is-passed-on-command-line.js
  tests/baselines/reference/tsbuild/watchMode/programUpdates/should-not-trigger-recompilation-because-of-program-emit.js
  tests/baselines/reference/tsbuild/watchMode/programUpdates/watches-config-files-that-are-not-present.js
  tests/baselines/reference/tsbuild/watchMode/programUpdates/with-simple-project-reference-graph/builds-when-new-file-is-added,-and-its-subsequent-updates.js
  tests/baselines/reference/tsbuild/watchMode/programUpdates/with-simple-project-reference-graph/change-builds-changes-and-reports-found-errors-message.js
  tests/baselines/reference/tsbuild/watchMode/programUpdates/with-simple-project-reference-graph/non-local-change-does-not-start-build-of-referencing-projects.js
  tests/baselines/reference/tscWatch/projectsWithReferences/on-sample-project.js
Labels: Author: Team, For Uncommitted Bug

#43218 Fix issue with some baselines for tsbuildinfo not getting generated
  src/testRunner/unittests/tsbuild/helpers.ts
  src/testRunner/unittests/tsc/helpers.ts
  tests/baselines/reference/tsbuild/sample1/initial-build/sample.js
  tests/baselines/reference/tsbuild/sample1/initial-build/when-logic-specifies-tsBuildInfoFile.js
  tests/baselines/reference/tsbuild/watchMode/noEmitOnError/does-not-emit-any-files-on-error-with-incremental.js
  tests/baselines/reference/tsbuild/watchMode/programUpdates/should-not-trigger-recompilation-because-of-program-emit-with-outDir-specified.js
  tests/baselines/reference/tsbuild/watchMode/programUpdates/when-referenced-project-change-introduces-error-in-the-down-stream-project-and-then-fixes-it.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependencies/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependenciesAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/default/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/defaultAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModules/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModulesAndD/with-noEmitOnError-with-incremental.js
Labels: Author: Team, For Uncommitted Bug

#43221 Emit readable BuilderFileEmit kind
  src/testRunner/unittests/tsbuild/helpers.ts
  tests/baselines/reference/tsbuild/demo/initial-build/in-bad-ref-branch-reports-the-error-about-files-not-in-rootDir-at-the-import-location.js
  tests/baselines/reference/tsbuild/inferredTypeFromTransitiveModule/initial-build/reports-errors-in-files-affected-by-change-in-signature-with-isolatedModules.js
  tests/baselines/reference/tsbuild/noEmitOnError/initial-build/semantic-errors-with-incremental.js
  tests/baselines/reference/tsbuild/resolveJsonModule/initial-build/include-only.js
  tests/baselines/reference/tsbuild/sample1/initial-build/does-not-build-downstream-projects-if-upstream-projects-have-errors.js
  tests/baselines/reference/tsbuild/transitiveReferences/initial-build/reports-error-about-module-not-found-with-node-resolution-with-external-module-name.js
  tests/baselines/reference/tsbuild/watchMode/demo/updates-with-bad-reference.js
  tests/baselines/reference/tsbuild/watchMode/noEmitOnError/does-not-emit-any-files-on-error-with-incremental.js
  tests/baselines/reference/tsbuild/watchMode/programUpdates/reportErrors/when-preserveWatchOutput-is-not-used.js
  tests/baselines/reference/tsbuild/watchMode/programUpdates/reportErrors/when-preserveWatchOutput-is-passed-on-command-line.js
  tests/baselines/reference/tsc/incremental/initial-build/noEmit-changes-composite.js
  tests/baselines/reference/tsc/incremental/initial-build/noEmit-changes-incremental-declaration.js
  tests/baselines/reference/tsc/incremental/initial-build/noEmit-changes-incremental.js
  tests/baselines/reference/tsc/incremental/initial-build/noEmit-changes-with-initial-noEmit-composite.js
  tests/baselines/reference/tsc/incremental/initial-build/noEmit-changes-with-initial-noEmit-incremental-declaration.js
  tests/baselines/reference/tsc/incremental/initial-build/noEmit-changes-with-initial-noEmit-incremental.js
  tests/baselines/reference/tsc/incremental/initial-build/with-noEmitOnError-semantic-errors.js
  tests/baselines/reference/tsc/incremental/initial-build/with-noEmitOnError-syntax-errors.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependencies/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependenciesAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/default/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/defaultAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModules/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModulesAndD/with-noEmitOnError-with-incremental.js
Labels: Author: Team, For Uncommitted Bug

#42671 Fix jsx formatting
  src/compiler/scanner.ts
  src/services/formatting/formatting.ts
  src/services/formatting/formattingScanner.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/formattingJsxTexts1.ts
  tests/cases/fourslash/formattingJsxTexts2.ts
  tests/cases/fourslash/formattingJsxTexts3.ts
Labels: For Milestone Bug

#43111 Fixed reporting error for type arity
  src/compiler/checker.ts
Labels: For Milestone Bug

#43262 Refactor the test for easy maintainability
  src/testRunner/unittests/tsserver/projectReferenceCompileOnSave.ts
Labels: Author: Team, For Uncommitted Bug

#43263 Fix dump of tracing legend
  src/compiler/tracing.ts
  src/executeCommandLine/executeCommandLine.ts
Labels: Author: Team, For Uncommitted Bug

#43273 fix(43254): Named tuple properties get typed as "any" on hover
  src/services/services.ts
  tests/cases/fourslash/quickInfoForNamedTupleMember.ts
Labels: For Backlog Bug

#43131 Fix narrowing of intersections of type variables and primitive types
  src/compiler/checker.ts
  tests/baselines/reference/intersectionNarrowing.errors.txt
  tests/baselines/reference/intersectionNarrowing.js
  tests/baselines/reference/intersectionNarrowing.symbols
  tests/baselines/reference/intersectionNarrowing.types
  tests/cases/conformance/types/intersection/intersectionNarrowing.ts
Labels: Author: Team, For Milestone Bug

#43202 Normalize target type after null-stripping unions in relationship checks
  src/compiler/checker.ts
  tests/baselines/reference/indexedAccessNormalization.js
  tests/baselines/reference/indexedAccessNormalization.symbols
  tests/baselines/reference/indexedAccessNormalization.types
  tests/cases/compiler/indexedAccessNormalization.ts
Labels: Author: Team, For Milestone Bug

#43304 Only catalog types when tracing
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug

#43240 [GH-43213] Fix duplicate comments printed in quick info section
  src/services/services.ts
  tests/cases/fourslash/server/quickinfoWrongComment.ts
Labels: For Backlog Bug

#43145 Made TS6059 rootDir validation consistent for programmatic usage
  src/compiler/program.ts
  src/testRunner/unittests/services/transpile.ts
  tests/baselines/reference/project/rootDirectoryWithoutOutDir/amd/rootDirectoryWithoutOutDir.errors.txt
  tests/baselines/reference/project/rootDirectoryWithoutOutDir/amd/rootDirectoryWithoutOutDir.json
  tests/baselines/reference/project/rootDirectoryWithoutOutDir/node/rootDirectoryWithoutOutDir.errors.txt
  tests/baselines/reference/project/rootDirectoryWithoutOutDir/node/rootDirectoryWithoutOutDir.json
  tests/cases/project/rootDirectoryWithoutOutDir.json
Labels: For Backlog Bug

#43090 fix CommonJs modules no longer affecting the global scope
  src/compiler/builderState.ts
  tests/baselines/reference/tsbuild/javascriptProjectEmit/initial-build/loads-js-based-projects-and-emits-them-correctly.js
Labels: For Uncommitted Bug

#43183 Improve narrowing of generic types in control flow analysis
  src/compiler/checker.ts
  tests/baselines/reference/assignmentNonObjectTypeConstraints.types
  tests/baselines/reference/conditionalTypes1.errors.txt
  tests/baselines/reference/conditionalTypes1.types
  tests/baselines/reference/controlFlowGenericTypes.errors.txt
  tests/baselines/reference/controlFlowGenericTypes.js
  tests/baselines/reference/controlFlowGenericTypes.symbols
  tests/baselines/reference/controlFlowGenericTypes.types
  tests/baselines/reference/deeplyNestedConstraints.types
  tests/baselines/reference/enumPropertyAccess.errors.txt
  tests/baselines/reference/enumPropertyAccess.types
  tests/baselines/reference/functionCallOnConstrainedTypeVariable.types
  tests/baselines/reference/intrinsicTypes.types
  tests/baselines/reference/keyofAndIndexedAccess.types
  tests/baselines/reference/keyofAndIndexedAccess2.types
  tests/baselines/reference/narrowingByTypeofInSwitch.symbols
  tests/baselines/reference/narrowingByTypeofInSwitch.types
  tests/baselines/reference/noUncheckedIndexedAccess.errors.txt
  tests/baselines/reference/noUncheckedIndexedAccess.types
  tests/baselines/reference/nonNullMappedType.types
  tests/baselines/reference/nonNullParameterExtendingStringAssignableToString.types
  tests/baselines/reference/recursiveTypeRelations.types
  tests/baselines/reference/restInvalidArgumentType.types
  tests/baselines/reference/switchWithConstrainedTypeVariable.types
  tests/baselines/reference/templateLiteralTypes1.types
  tests/baselines/reference/typeParameterExtendingUnion1.types
  tests/baselines/reference/typeParameterExtendingUnion2.types
  tests/baselines/reference/unionWithIndexSignature.types
  tests/baselines/reference/voidReturnIndexUnionInference.types
  tests/cases/conformance/controlFlow/controlFlowGenericTypes.ts
Labels: Author: Team, For Backlog Bug, For Milestone Bug

#43035 Use shared binary trampoline in checker
  src/compiler/checker.ts
  src/compiler/factory/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#43322 Accepts baseline change caused by #43035
  tests/baselines/reference/tsbuild/javascriptProjectEmit/initial-build/loads-js-based-projects-and-emits-them-correctly.js
Labels: Author: Team, For Uncommitted Bug

#43104 Adjust scanning of keywordy jsx namespace names, add grammar error for jsx dotted names containing namespace names
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/scanner.ts
  tests/baselines/reference/checkJsxNamespaceNamesQuestionableForms.errors.txt
  tests/baselines/reference/checkJsxNamespaceNamesQuestionableForms.js
  tests/baselines/reference/checkJsxNamespaceNamesQuestionableForms.symbols
  tests/baselines/reference/checkJsxNamespaceNamesQuestionableForms.types
  tests/baselines/reference/jsxInvalidEsprimaTestSuite.errors.txt
  tests/cases/conformance/jsx/checkJsxNamespaceNamesQuestionableForms.tsx
Labels: Author: Team, For Milestone Bug

#43320 Delete deprecated issue_template.md
  .github/issue_template.md
Labels: For Uncommitted Bug

#42467 Fix Issue #39155 (importModuleSpecifierEnding does not apply for module specifier completions)
  src/services/completions.ts
  src/services/stringCompletions.ts
  tests/cases/fourslash/completionImportModuleSpecifierEnding.ts
Labels: For Backlog Bug

#43351 Use last detected JSX import source pragma as canonical source, rather than first
  src/compiler/utilities.ts
  tests/baselines/reference/jsxImportSourceNonPragmaComment.errors.txt
  tests/baselines/reference/jsxImportSourceNonPragmaComment.js
  tests/baselines/reference/jsxImportSourceNonPragmaComment.symbols
  tests/baselines/reference/jsxImportSourceNonPragmaComment.types
  tests/cases/compiler/jsxImportSourceNonPragmaComment.tsx
Labels: Author: Team, For Uncommitted Bug

#43348 Don't use _fs.realpathSync.native on windows, a semi-revert of #41292
  src/compiler/sys.ts
Labels: Author: Team, For Uncommitted Bug

#43180 Don't inherit jsdoc tags from overloaded signatures (#43165)
  src/services/services.ts
  tests/baselines/reference/deprecatedInheritedJSDocOverload.baseline
  tests/cases/fourslash/deprecatedInheritedJSDocOverload.ts
Labels: Author: Team, For Uncommitted Bug

#42968 `deleteDeclaration`: don't crash on the top node.
  src/server/session.ts
  src/services/codefixes/fixUnusedIdentifier.ts
  src/services/textChanges.ts
Labels: Author: Team, For Milestone Bug

#43372 `getSemanticDocumentHighlights`: don't fail...
  src/services/documentHighlights.ts
  tests/cases/fourslash/documentHighlights_33722.ts
Labels: Author: Team, For Milestone Bug

#43381 Update typescript-eslint to latest
  package-lock.json
  package.json
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/parser.ts
  src/compiler/transformers/classFields.ts
  src/compiler/transformers/module/system.ts
  src/compiler/utilities.ts
  src/harness/fourslashImpl.ts
  src/server/project.ts
  src/services/shims.ts
  src/services/symbolDisplay.ts
Labels: Author: Team, For Uncommitted Bug

#43380 Use 'abstract new' in InstanceType and ConstructorParameters
  src/lib/es5.d.ts
  tests/baselines/reference/inferTypes1.errors.txt
  tests/baselines/reference/inferTypes1.types
Labels: Author: Team, For Uncommitted Bug

#43354 Don't build type catalog during server tracing
  src/compiler/checker.ts
  src/compiler/program.ts
  src/compiler/tracing.ts
  src/compiler/types.ts
  src/executeCommandLine/executeCommandLine.ts
  src/tsserver/nodeServer.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#43384 Port realpath workaround from release-4.2
  src/compiler/sys.ts
Labels: Author: Team, For Uncommitted Bug

#43385 Un-reverse realpath case-sensitivity check
  src/compiler/sys.ts
Labels: Author: Team, For Uncommitted Bug

#43376 Template literal types for contextually typed template literal expressions
  src/compiler/checker.ts
  tests/baselines/reference/stringLiteralTypesWithTemplateStrings02.errors.txt
  tests/baselines/reference/stringLiteralTypesWithTemplateStrings02.types
  tests/baselines/reference/templateLiteralTypes1.types
  tests/baselines/reference/templateLiteralTypes2.errors.txt
  tests/baselines/reference/templateLiteralTypes2.js
  tests/baselines/reference/templateLiteralTypes2.symbols
  tests/baselines/reference/templateLiteralTypes2.types
  tests/cases/conformance/types/literal/templateLiteralTypes2.ts
Labels: Author: Team, For Milestone Bug

#43149 Import statement completions
  src/compiler/checker.ts
  src/compiler/moduleSpecifiers.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/server/editorServices.ts
  src/server/project.ts
  src/server/protocol.ts
  src/server/scriptInfo.ts
  src/server/session.ts
  src/services/codefixes/importFixes.ts
  src/services/completions.ts
  src/services/stringCompletions.ts
  src/services/types.ts
  src/services/utilities.ts
  src/testRunner/tsconfig.json
  src/testRunner/unittests/tsserver/completions.ts
  src/testRunner/unittests/tsserver/exportMapCache.ts
  src/testRunner/unittests/tsserver/importSuggestionsCache.ts
  src/testRunner/unittests/tsserver/jsdocTag.ts
  src/testRunner/unittests/tsserver/moduleSpecifierCache.ts
  src/testRunner/unittests/tsserver/partialSemanticServer.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/completionEntryForImportName.ts
  tests/cases/fourslash/completionsImport_defaultAndNamedConflict.ts
  tests/cases/fourslash/completionsImport_details_withMisspelledName.ts
  tests/cases/fourslash/completionsImport_exportEquals_global.ts
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/importStatementCompletions1.ts
  tests/cases/fourslash/importStatementCompletions_esModuleInterop1.ts
  tests/cases/fourslash/importStatementCompletions_esModuleInterop2.ts
  tests/cases/fourslash/importStatementCompletions_noPatternAmbient.ts
  tests/cases/fourslash/importStatementCompletions_noSnippet.ts
  tests/cases/fourslash/importStatementCompletions_quotes.ts
  tests/cases/fourslash/importStatementCompletions_semicolons.ts
  tests/cases/fourslash/server/completionsImport_defaultAndNamedConflict_server.ts
Labels: Author: Team, For Milestone Bug

#37797 Add static index signature
  src/compiler/checker.ts
  tests/baselines/reference/parserIndexMemberDeclaration10.errors.txt
  tests/baselines/reference/parserIndexMemberDeclaration6.errors.txt
  tests/baselines/reference/parserSymbolIndexer3.errors.txt
  tests/baselines/reference/staticIndexSignature1.errors.txt
  tests/baselines/reference/staticIndexSignature1.js
  tests/baselines/reference/staticIndexSignature1.symbols
  tests/baselines/reference/staticIndexSignature1.types
  tests/baselines/reference/staticIndexSignature2.errors.txt
  tests/baselines/reference/staticIndexSignature2.js
  tests/baselines/reference/staticIndexSignature2.symbols
  tests/baselines/reference/staticIndexSignature2.types
  tests/baselines/reference/staticIndexSignature3.js
  tests/baselines/reference/staticIndexSignature3.symbols
  tests/baselines/reference/staticIndexSignature3.types
  tests/baselines/reference/staticIndexSignature4.errors.txt
  tests/baselines/reference/staticIndexSignature4.js
  tests/baselines/reference/staticIndexSignature4.symbols
  tests/baselines/reference/staticIndexSignature4.types
  tests/baselines/reference/staticIndexSignature5.errors.txt
  tests/baselines/reference/staticIndexSignature5.js
  tests/baselines/reference/staticIndexSignature5.symbols
  tests/baselines/reference/staticIndexSignature5.types
  tests/baselines/reference/staticIndexSignature6.js
  tests/baselines/reference/staticIndexSignature6.symbols
  tests/baselines/reference/staticIndexSignature6.types
  tests/baselines/reference/staticIndexSignature7.errors.txt
  tests/baselines/reference/staticIndexSignature7.js
  tests/baselines/reference/staticIndexSignature7.symbols
  tests/baselines/reference/staticIndexSignature7.types
  tests/baselines/reference/staticIndexer.errors.txt
  tests/baselines/reference/staticIndexer.js
  tests/baselines/reference/staticIndexer.symbols
  tests/baselines/reference/staticIndexer.types
  tests/baselines/reference/staticIndexers.errors.txt
  tests/cases/compiler/staticIndexer.ts
  tests/cases/conformance/classes/staticIndexSignature/staticIndexSignature1.ts
  tests/cases/conformance/classes/staticIndexSignature/staticIndexSignature2.ts
  tests/cases/conformance/classes/staticIndexSignature/staticIndexSignature3.ts
  tests/cases/conformance/classes/staticIndexSignature/staticIndexSignature4.ts
  tests/cases/conformance/classes/staticIndexSignature/staticIndexSignature5.ts
  tests/cases/conformance/classes/staticIndexSignature/staticIndexSignature6.ts
  tests/cases/conformance/classes/staticIndexSignature/staticIndexSignature7.ts
Labels: For Backlog Bug, Rescheduled

#42425 Variant accessors
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/parser.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  tests/baselines/reference/abstractPropertyNegative.errors.txt
  tests/baselines/reference/accessorBodyInTypeContext.errors.txt
  tests/baselines/reference/accessorBodyInTypeContext.js
  tests/baselines/reference/accessorBodyInTypeContext.symbols
  tests/baselines/reference/accessorBodyInTypeContext.types
  tests/baselines/reference/accessorWithMismatchedAccessibilityModifiers.errors.txt
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/divergentAccessors1.js
  tests/baselines/reference/divergentAccessors1.symbols
  tests/baselines/reference/divergentAccessors1.types
  tests/baselines/reference/divergentAccessorsTypes1.js
  tests/baselines/reference/divergentAccessorsTypes1.symbols
  tests/baselines/reference/divergentAccessorsTypes1.types
  tests/baselines/reference/divergentAccessorsTypes2.errors.txt
  tests/baselines/reference/divergentAccessorsTypes2.js
  tests/baselines/reference/divergentAccessorsTypes2.symbols
  tests/baselines/reference/divergentAccessorsTypes2.types
  tests/baselines/reference/divergentAccessorsVisibility1.errors.txt
  tests/baselines/reference/divergentAccessorsVisibility1.js
  tests/baselines/reference/divergentAccessorsVisibility1.symbols
  tests/baselines/reference/divergentAccessorsVisibility1.types
  tests/baselines/reference/getAndSetNotIdenticalType.errors.txt
  tests/baselines/reference/getAndSetNotIdenticalType2.errors.txt
  tests/baselines/reference/getAndSetNotIdenticalType2.types
  tests/baselines/reference/getAndSetNotIdenticalType3.errors.txt
  tests/baselines/reference/getAndSetNotIdenticalType3.types
  tests/baselines/reference/gettersAndSettersAccessibility.errors.txt
  tests/baselines/reference/gettersAndSettersErrors.errors.txt
  tests/baselines/reference/jsdocAccessibilityTags.errors.txt
  tests/baselines/reference/objectLiteralErrors.errors.txt
  tests/baselines/reference/thisTypeInAccessorsNegative.errors.txt
  tests/cases/compiler/accessorBodyInTypeContext.ts
  tests/cases/compiler/divergentAccessors1.ts
  tests/cases/compiler/divergentAccessorsTypes1.ts
  tests/cases/compiler/divergentAccessorsTypes2.ts
  tests/cases/compiler/divergentAccessorsVisibility1.ts
  tests/cases/fourslash/incrementalResolveAccessor.ts
Labels: Author: Team, For Uncommitted Bug

#43405 Rename isWrite -> writing
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug

#43361 Support relations and inference between template literal types
  src/compiler/checker.ts
  tests/baselines/reference/templateLiteralTypes3.errors.txt
  tests/baselines/reference/templateLiteralTypes3.js
  tests/baselines/reference/templateLiteralTypes3.symbols
  tests/baselines/reference/templateLiteralTypes3.types
  tests/cases/conformance/types/literal/templateLiteralTypes3.ts
Labels: Author: Team, For Uncommitted Bug

#43404 Fix typo
  src/lib/es5.d.ts
  tests/baselines/reference/completionEntryForUnionMethod.baseline
Labels: For Uncommitted Bug

#43023 Improve (and actually use) "always truthy promise" error
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/services/codefixes/addMissingAwait.ts
  src/services/codefixes/fixMissingCallParentheses.ts
  tests/baselines/reference/truthinessCallExpressionCoercion.errors.txt
  tests/baselines/reference/truthinessCallExpressionCoercion1.errors.txt
  tests/baselines/reference/truthinessCallExpressionCoercion2.errors.txt
  tests/baselines/reference/truthinessPromiseCoercion.errors.txt
Labels: For Uncommitted Bug

#43401 Fix length of `JSDocTypedefTag`
  src/compiler/parser.ts
  tests/baselines/reference/jsDeclarationsParameterTagReusesInputNodeInEmit1.errors.txt
  tests/baselines/reference/jsDocSignature-43394.baseline
  tests/cases/fourslash/findAllRefsJsDocTypeDef_js.ts
  tests/cases/fourslash/findAllRefsTypedef_importType.ts
  tests/cases/fourslash/jsDocSignature-43394.ts
  tests/cases/fourslash/jsdocTypedefTagSemanticMeaning0.ts
  tests/cases/fourslash/server/jsdocTypedefTagRename02.ts
Labels: Author: Team, For Uncommitted Bug

#43194 Consider class field properties to redeclare parent definitions
  src/compiler/checker.ts
  tests/baselines/reference/redeclaredProperty.errors.txt
  tests/baselines/reference/redeclaredProperty.js
  tests/baselines/reference/redefinedPararameterProperty.errors.txt
  tests/baselines/reference/redefinedPararameterProperty.js
  tests/baselines/reference/redefinedPararameterProperty.symbols
  tests/baselines/reference/redefinedPararameterProperty.types
  tests/cases/conformance/classes/propertyMemberDeclarations/redeclaredProperty.ts
  tests/cases/conformance/classes/propertyMemberDeclarations/redefinedPararameterProperty.ts
Labels: For Backlog Bug

#43217 fix(43215): Reserved type primitive names should not be allowed as interface names
  src/compiler/checker.ts
  tests/baselines/reference/interfacesWithPredefinedTypesAsNames.errors.txt
  tests/baselines/reference/interfacesWithPredefinedTypesAsNames.js
  tests/baselines/reference/interfacesWithPredefinedTypesAsNames.symbols
  tests/baselines/reference/interfacesWithPredefinedTypesAsNames.types
  tests/cases/conformance/interfaces/interfaceDeclarations/interfacesWithPredefinedTypesAsNames.ts
Labels: For Backlog Bug

#43399 Remote duplicated initialization of 'diagnostics'
  src/harness/compilerImpl.ts
Labels: Author: Team, For Uncommitted Bug

#40884 Adding Diagnostic message for missing ']' and ')' in Array literal and conditional statements
  src/compiler/diagnosticMessages.json
  src/compiler/parser.ts
  tests/baselines/reference/constructorWithIncompleteTypeAnnotation.errors.txt
  tests/baselines/reference/destructuringParameterDeclaration2.errors.txt
  tests/baselines/reference/missingCloseBracketInArray.errors.txt
  tests/baselines/reference/missingCloseBracketInArray.js
  tests/baselines/reference/missingCloseBracketInArray.symbols
  tests/baselines/reference/missingCloseBracketInArray.types
  tests/baselines/reference/missingCloseParenStatements.errors.txt
  tests/baselines/reference/missingCloseParenStatements.js
  tests/baselines/reference/missingCloseParenStatements.symbols
  tests/baselines/reference/missingCloseParenStatements.types
  tests/baselines/reference/parserErrorRecoveryArrayLiteralExpression3.errors.txt
  tests/baselines/reference/parserErrorRecoveryIfStatement2.errors.txt
  tests/baselines/reference/parserErrorRecoveryIfStatement3.errors.txt
  tests/baselines/reference/reservedWords2.errors.txt
  tests/baselines/reference/typeAssertions.errors.txt
  tests/cases/compiler/missingCloseBracketInArray.ts
  tests/cases/compiler/missingCloseParenStatements.ts
  tests/cases/conformance/parser/ecmascript5/ErrorRecovery/ArrayLiteralExpressions/parserErrorRecoveryArrayLiteralExpression3.ts
Labels: For Backlog Bug

#43435 Consider base types in isArrayLikeType
  src/compiler/checker.ts
  tests/baselines/reference/excessiveStackDepthFlatArray.errors.txt
  tests/baselines/reference/excessiveStackDepthFlatArray.js
  tests/baselines/reference/excessiveStackDepthFlatArray.symbols
  tests/baselines/reference/excessiveStackDepthFlatArray.types
  tests/cases/compiler/excessiveStackDepthFlatArray.ts
Labels: Author: Team, For Milestone Bug

#43309 fix(services): convert to es6 module generate invalid code with .default
  src/services/codefixes/convertToEs6Module.ts
  tests/cases/fourslash/refactorConvertToEs6Module_import_es6DefaultImport.ts
Labels: For Backlog Bug

#43315 fix(43313): Remove braces refactoring produces broken code if returning an object literal with type casting
  src/services/utilities.ts
  tests/cases/fourslash/refactorAddOrRemoveBracesToArrowFunction29.ts
  tests/cases/fourslash/refactorAddOrRemoveBracesToArrowFunction30.ts
Labels: For Backlog Bug

#43440 Fix template literal type relations
  src/compiler/checker.ts
  tests/baselines/reference/templateLiteralTypes2.errors.txt
  tests/baselines/reference/templateLiteralTypes2.js
  tests/baselines/reference/templateLiteralTypes2.symbols
  tests/baselines/reference/templateLiteralTypes2.types
  tests/cases/conformance/types/literal/templateLiteralTypes2.ts
Labels: Author: Team, For Milestone Bug

#43448 Do not delete output file names that are same as input file name
  src/compiler/tsbuildPublic.ts
  src/testRunner/tsconfig.json
  src/testRunner/unittests/tsbuild/clean.ts
  tests/baselines/reference/tsbuild/clean/initial-build/file-name-and-output-name-clashing.js
Labels: Author: Team, For Milestone Bug

#43460 Only issue matching token errors on non-dupe locations
  src/compiler/parser.ts
  tests/baselines/reference/constructorWithIncompleteTypeAnnotation.errors.txt
  tests/baselines/reference/destructuringParameterDeclaration2.errors.txt
  tests/baselines/reference/errorRecoveryWithDotFollowedByNamespaceKeyword.errors.txt
  tests/baselines/reference/nestedClassDeclaration.errors.txt
  tests/baselines/reference/objectLiteralWithSemicolons4.errors.txt
  tests/baselines/reference/objectSpreadNegativeParse.errors.txt
  tests/baselines/reference/parseErrorIncorrectReturnToken.errors.txt
  tests/baselines/reference/parserErrorRecoveryArrayLiteralExpression3.errors.txt
  tests/baselines/reference/parserFuzz1.errors.txt
  tests/baselines/reference/reservedWords2.errors.txt
  tests/baselines/reference/tsbuild/noEmitOnError/initial-build/syntax-errors-with-incremental.js
  tests/baselines/reference/tsbuild/noEmitOnError/initial-build/syntax-errors.js
  tests/baselines/reference/tsbuild/watchMode/noEmitOnError/does-not-emit-any-files-on-error-with-incremental.js
  tests/baselines/reference/tsbuild/watchMode/noEmitOnError/does-not-emit-any-files-on-error.js
  tests/baselines/reference/tsc/incremental/initial-build/with-noEmitOnError-syntax-errors.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependencies/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependencies/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependenciesAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependenciesAndD/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/default/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/default/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/defaultAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/defaultAndD/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/assumeChangesOnlyAffectDirectDependencies/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/assumeChangesOnlyAffectDirectDependencies/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/assumeChangesOnlyAffectDirectDependenciesAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/assumeChangesOnlyAffectDirectDependenciesAndD/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/default/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/default/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/defaultAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/defaultAndD/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/isolatedModules/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/isolatedModules/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/isolatedModulesAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/isolatedModulesAndD/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModules/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModules/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModulesAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModulesAndD/with-noEmitOnError.js
Labels: Author: Team, For Uncommitted Bug

#43446 Only catalog types when tracing
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug

#41115 Error if assignment after block
  src/compiler/diagnosticMessages.json
  src/compiler/parser.ts
  tests/baselines/reference/assignmentLHSIsValue.errors.txt
  tests/baselines/reference/assignmentLHSIsValue.types
  tests/baselines/reference/destructionAssignmentError.errors.txt
  tests/baselines/reference/destructionAssignmentError.js
  tests/baselines/reference/destructionAssignmentError.symbols
  tests/baselines/reference/destructionAssignmentError.types
  tests/cases/compiler/destructionAssignmentError.ts
Labels: For Backlog Bug
