Repository microsoft/TypeScript, pull requests merged in 2021-04, with the labels that each got.

#43387 Added BindingElement to isSomeImportDeclaration
  src/compiler/checker.ts
  tests/baselines/reference/commonJsImportBindingElementNarrowType.symbols
  tests/baselines/reference/commonJsImportBindingElementNarrowType.types
  tests/cases/conformance/externalModules/commonJsImportBindingElementNarrowType.ts
Labels: For Milestone Bug

#43473 Add @deprecated to tree walk
  src/compiler/parser.ts
  tests/baselines/reference/quickInfoInheritedLinkTag.baseline
  tests/cases/fourslash/quickInfoInheritedLinkTag.ts
Labels: Author: Team, For Milestone Bug

#43475 Add @link jsdoc auto-complete
  src/services/jsDoc.ts
  tests/cases/fourslash/completionInJsDoc.ts
Labels: For Milestone Bug

#43100 Disabled 'used before initialization' error for optional properties
  src/compiler/checker.ts
  tests/baselines/reference/classUsedBeforeInitializedVariables.errors.txt
  tests/baselines/reference/classUsedBeforeInitializedVariables.js
  tests/baselines/reference/classUsedBeforeInitializedVariables.symbols
  tests/baselines/reference/classUsedBeforeInitializedVariables.types
  tests/cases/compiler/classUsedBeforeInitializedVariables.ts
Labels: For Backlog Bug

#43510 Add grunt user test
  tests/baselines/reference/user/grunt.log
  tests/cases/user/grunt/test.json
  tests/cases/user/grunt/tsconfig.json
Labels: Author: Team, For Uncommitted Bug

#43439 Do not covariantly mix in constraints from contravarrying positions
  src/compiler/checker.ts
  tests/baselines/reference/callOfConditionalTypeWithConcreteBranches.js
  tests/baselines/reference/callOfConditionalTypeWithConcreteBranches.symbols
  tests/baselines/reference/callOfConditionalTypeWithConcreteBranches.types
  tests/cases/compiler/callOfConditionalTypeWithConcreteBranches.ts
Labels: Author: Team, For Uncommitted Bug

#43358 fix(43316): TS should not suggest converting to async function if void is explicitly returned
  src/services/codefixes/convertToAsyncFunction.ts
  src/services/suggestionDiagnostics.ts
  src/testRunner/unittests/services/convertToAsyncFunction.ts
Labels: For Backlog Bug

#42584 When reusing input type nodes, only instantiate the type for comparison if it is a this type
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitOverloadedPrivateInference.js
  tests/baselines/reference/declarationEmitOverloadedPrivateInference.symbols
  tests/baselines/reference/declarationEmitOverloadedPrivateInference.types
  tests/baselines/reference/declarationsWithRecursiveInternalTypesProduceUniqueTypeParams.types
  tests/baselines/reference/jsDeclarationsInterfaces.js
  tests/cases/compiler/declarationEmitOverloadedPrivateInference.ts
Labels: Author: Team, For Milestone Bug

#42485 Allow nested reverse mapped type printback
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/genericFunctionInference2.types
  tests/baselines/reference/isomorphicMappedTypeInference.js
  tests/baselines/reference/isomorphicMappedTypeInference.types
  tests/baselines/reference/mappedTypeRecursiveInference.errors.txt
  tests/baselines/reference/reverseMappedTypeDeepDeclarationEmit.js
  tests/baselines/reference/reverseMappedTypeDeepDeclarationEmit.symbols
  tests/baselines/reference/reverseMappedTypeDeepDeclarationEmit.types
  tests/cases/compiler/reverseMappedTypeDeepDeclarationEmit.ts
  tests/cases/fourslash/reverseMappedTypeQuickInfo.ts
Labels: Author: Team, For Milestone Bug

#43339 Make origin union cache key unique for key lists still under construction
  src/compiler/checker.ts
  tests/baselines/reference/keyofGenericExtendingClassDoubleLayer.js
  tests/baselines/reference/keyofGenericExtendingClassDoubleLayer.symbols
  tests/baselines/reference/keyofGenericExtendingClassDoubleLayer.types
  tests/cases/compiler/keyofGenericExtendingClassDoubleLayer.ts
Labels: Author: Team, For Milestone Bug

#42936 fix(42605): support refactoring for export default assignment without equal
  src/services/findAllReferences.ts
  src/services/refactors/convertExport.ts
  tests/cases/fourslash/refactorConvertExport_defaultToNamed2.ts
Labels: For Uncommitted Bug

#43527 Fix getRecursionIdentity function to always return some identity
  src/compiler/checker.ts
  tests/baselines/reference/circularlyConstrainedMappedTypeContainingConditionalNoInfiniteInstantiationDepth.errors.txt
  tests/baselines/reference/flatArrayNoExcessiveStackDepth.errors.txt
  tests/baselines/reference/flatArrayNoExcessiveStackDepth.js
  tests/baselines/reference/flatArrayNoExcessiveStackDepth.symbols
  tests/baselines/reference/flatArrayNoExcessiveStackDepth.types
  tests/baselines/reference/reactReduxLikeDeferredInferenceAllowsAssignment.errors.txt
  tests/cases/compiler/flatArrayNoExcessiveStackDepth.ts
Labels: Author: Team, For Milestone Bug

#43356 fix quickinfo of narrowed private filed
  src/compiler/checker.ts
  tests/cases/fourslash/quickInfoOnNarrowedType.ts
Labels: For Backlog Bug

#43474 Handle document Registry to distinguish between files with same name and document registry key(compiler options affecting source file) but different ScriptKind
  src/services/documentRegistry.ts
  src/services/services.ts
  src/testRunner/unittests/tsserver/documentRegistry.ts
  src/testRunner/unittests/tsserver/dynamicFiles.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Milestone Bug

#43483 Go to definition: pass `unverified` through server
  src/harness/client.ts
  src/harness/fourslashImpl.ts
  src/server/protocol.ts
  src/server/session.ts
  src/services/goToDefinition.ts
  src/testRunner/unittests/tsserver/partialSemanticServer.ts
  src/testRunner/unittests/tsserver/projectReferencesSourcemap.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/goToDefinitionCSSPatternAmbientModule.ts
  tests/cases/fourslash/goToDefinitionScriptImport.ts
  tests/cases/fourslash/server/goToDefinitionScriptImportServer.ts
Labels: Author: Team, For Uncommitted Bug

#43382 Add asserts to type only symbols meaning exclusion
  src/services/completions.ts
  tests/cases/fourslash/completionsAsserts.ts
Labels: For Backlog Bug

#43367 fix(43160): improve error location for functions without explicit return
  src/compiler/checker.ts
  tests/baselines/reference/errorOnFunctionReturnType.errors.txt
  tests/baselines/reference/errorOnFunctionReturnType.symbols
  tests/baselines/reference/errorOnFunctionReturnType.types
  tests/cases/conformance/jsdoc/errorOnFunctionReturnType.ts
Labels: For Backlog Bug

#43544 Always grammar checker for override
  src/compiler/checker.ts
  tests/baselines/reference/override7.errors.txt
Labels: For Milestone Bug

#43369 fix(43347): Exception occured when export type to existing commonJs imported name
  src/compiler/checker.ts
  tests/baselines/reference/commonJsExportTypeDeclarationError.errors.txt
  tests/baselines/reference/commonJsExportTypeDeclarationError.js
  tests/baselines/reference/commonJsExportTypeDeclarationError.symbols
  tests/baselines/reference/commonJsExportTypeDeclarationError.types
  tests/cases/compiler/commonJsExportTypeDeclarationError.ts
Labels: For Milestone Bug

#43545 Enforce `override` precedes `readonly`
  src/compiler/checker.ts
  tests/baselines/reference/override5.errors.txt
  tests/baselines/reference/override7.errors.txt
Labels: For Uncommitted Bug

#43536 fix(43535): TypeScript preserves 'override' modifier in JavaScript output
  src/compiler/factory/nodeFactory.ts
  tests/baselines/reference/override12(target=es2015).js
  tests/baselines/reference/override12(target=es2015).symbols
  tests/baselines/reference/override12(target=es2015).types
  tests/baselines/reference/override12(target=esnext).js
  tests/baselines/reference/override12(target=esnext).symbols
  tests/baselines/reference/override12(target=esnext).types
  tests/cases/conformance/override/override12.ts
Labels: For Milestone Bug

#43504 fix(43495): noImplicitOverride quick fix puts the keyword in the wrong spot
  src/services/codefixes/fixOverrideModifier.ts
  tests/cases/fourslash/codeFixOverrideModifier13.ts
  tests/cases/fourslash/codeFixOverrideModifier14.ts
  tests/cases/fourslash/codeFixOverrideModifier15.ts
  tests/cases/fourslash/codeFixOverrideModifier16.ts
  tests/cases/fourslash/codeFixOverrideModifier17.ts
  tests/cases/fourslash/codeFixOverrideModifier18.ts
Labels: For Milestone Bug

#43562 Fix getTypeFromJSDocVariadicType in callback tag
  src/compiler/checker.ts
  tests/baselines/reference/callbackTagVariadicType.js
  tests/baselines/reference/callbackTagVariadicType.symbols
  tests/baselines/reference/callbackTagVariadicType.types
  tests/cases/conformance/jsdoc/callbackTagVariadicType.ts
Labels: Author: Team, For Milestone Bug

#43175 Corrected parsing for decorators on 'this' parameters
  src/compiler/diagnosticMessages.json
  src/compiler/parser.ts
  tests/baselines/reference/decoratorOnClassMethodThisParameter.errors.txt
  tests/baselines/reference/decoratorOnClassMethodThisParameter.js
  tests/baselines/reference/decoratorOnClassMethodThisParameter.symbols
  tests/baselines/reference/decoratorOnClassMethodThisParameter.types
  tests/baselines/reference/decoratorOnFunctionParameter.errors.txt
  tests/baselines/reference/decoratorOnFunctionParameter.js
  tests/baselines/reference/decoratorOnFunctionParameter.symbols
  tests/baselines/reference/decoratorOnFunctionParameter.types
  tests/baselines/reference/thisTypeInFunctionsNegative.errors.txt
  tests/baselines/reference/thisTypeInFunctionsNegative.symbols
  tests/baselines/reference/thisTypeInFunctionsNegative.types
  tests/cases/conformance/decorators/class/method/parameter/decoratorOnClassMethodThisParameter.ts
  tests/cases/conformance/decorators/invalid/decoratorOnFunctionParameter.ts
Labels: For Backlog Bug

#43007 Again: Improve error messages for empty DOM interface property access
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/missingDomElements.errors.txt
  tests/baselines/reference/missingDomElements.js
  tests/baselines/reference/missingDomElements.symbols
  tests/baselines/reference/missingDomElements.types
  tests/cases/compiler/missingDomElements.ts
Labels: For Backlog Bug

#43538 Properly handle tagged primitives in control flow analysis
  src/compiler/checker.ts
  tests/baselines/reference/taggedPrimitiveNarrowing.js
  tests/baselines/reference/taggedPrimitiveNarrowing.symbols
  tests/baselines/reference/taggedPrimitiveNarrowing.types
  tests/cases/compiler/taggedPrimitiveNarrowing.ts
Labels: Author: Team, For Milestone Bug

#43453 Fix Add all missing imports when ordered alphabetically
  src/services/textChanges.ts
  tests/cases/fourslash/addAllMissingImportsNoCrash.ts
Labels: For Milestone Bug

#43199 Specified diagnostic for CLI flags mismatched with/out --build
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  src/compiler/types.ts
  src/testRunner/unittests/config/commandLineParsing.ts
Labels: For Backlog Bug

#43390 Improve rendering of JSDoc comment text with displayparts
  src/services/jsDoc.ts
  src/services/utilities.ts
  src/testRunner/unittests/tsserver/jsdocTag.ts
  tests/baselines/reference/completionEntryForUnionMethod.baseline
  tests/baselines/reference/completionsCommentsClass.baseline
  tests/baselines/reference/completionsCommentsClassMembers.baseline
  tests/baselines/reference/completionsCommentsCommentParsing.baseline
  tests/baselines/reference/completionsCommentsFunctionDeclaration.baseline
  tests/baselines/reference/completionsCommentsFunctionExpression.baseline
  tests/baselines/reference/completionsSalsaMethodsOnAssignedFunctionExpressions.baseline
  tests/baselines/reference/jsDocFunctionSignatures5.baseline
  tests/baselines/reference/jsDocFunctionSignatures6.baseline
  tests/baselines/reference/quickInfoCommentsClassMembers.baseline
  tests/baselines/reference/quickInfoCommentsCommentParsing.baseline
  tests/baselines/reference/quickInfoCommentsFunctionExpression.baseline
  tests/baselines/reference/quickInfoJSDocTags.baseline
  tests/baselines/reference/quickInfoJsDocTags1.baseline
  tests/baselines/reference/quickInfoJsDocTags3.baseline
  tests/baselines/reference/quickInfoJsDocTags4.baseline
  tests/baselines/reference/quickInfoJsDocTags5.baseline
  tests/baselines/reference/quickInfoJsDocTags6.baseline
  tests/baselines/reference/quickInfoJsDocTagsCallback.baseline
  tests/baselines/reference/quickInfoJsDocTagsTypedef.baseline
  tests/baselines/reference/quickInfoJsDocTextFormatting1.baseline
  tests/baselines/reference/signatureHelpCommentsClass.baseline
  tests/baselines/reference/signatureHelpCommentsCommentParsing.baseline
  tests/baselines/reference/signatureHelpCommentsFunctionDeclaration.baseline
  tests/baselines/reference/signatureHelpCommentsFunctionExpression.baseline
  tests/baselines/reference/signatureHelpConstructorCallParamProperties.baseline
  tests/baselines/reference/signatureHelpJSMissingPropertyAccess.baseline
  tests/baselines/reference/signatureHelpTypeArguments2.baseline
  tests/baselines/reference/signatureHelpWithUnknown.baseline
  tests/baselines/reference/trailingCommaSignatureHelp.baseline
  tests/cases/fourslash/importJsNodeModule3.ts
  tests/cases/fourslash/quickInfoJsDocTagsCallback.ts
  tests/cases/fourslash/quickInfoJsDocTagsTypedef.ts
  tests/cases/fourslash/signatureHelpWhenEditingCallExpression.ts
Labels: For Backlog Bug

#43569 ignore static and declared member if checking override
  src/compiler/checker.ts
  tests/baselines/reference/override13.errors.txt
  tests/baselines/reference/override13.js
  tests/baselines/reference/override13.symbols
  tests/baselines/reference/override13.types
  tests/baselines/reference/override14.js
  tests/baselines/reference/override14.symbols
  tests/baselines/reference/override14.types
  tests/baselines/reference/override5.errors.txt
  tests/baselines/reference/override7.errors.txt
  tests/cases/conformance/override/override13.ts
  tests/cases/conformance/override/override14.ts
Labels: For Milestone Bug

#43611 Process only existing files and directories in the test harness
  src/harness/harnessIO.ts
Labels: Author: Team, For Uncommitted Bug

#43588 Catch hover on as const
  src/services/services.ts
  tests/cases/fourslash/quickInfoForConstTypeReference.ts
Labels: For Backlog Bug

#43602 Don't start jsdoc tag before whitespace
  src/compiler/parser.ts
  tests/baselines/reference/quickInfoJSDocAtBeforeSpace.baseline
  tests/cases/fourslash/quickInfoJSDocAtBeforeSpace.ts
Labels: Author: Team, For Uncommitted Bug

#43625 @link and @see resolve C.m as a class property reference
  src/compiler/checker.ts
  src/compiler/parser.ts
  src/harness/fourslashImpl.ts
  tests/baselines/reference/findAllReferencesLinkTag1.baseline.jsonc
  tests/baselines/reference/jsdocLink_findAllReferences1.baseline.jsonc
  tests/cases/fourslash/findAllReferencesLinkTag1.ts
Labels: Author: Team, For Milestone Bug

#43593 Don’t error for missing await when promise is referenced in condition body
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/services/codefixes/addMissingAwait.ts
  src/services/codefixes/fixMissingCallParentheses.ts
  tests/baselines/reference/truthinessCallExpressionCoercion.errors.txt
  tests/baselines/reference/truthinessCallExpressionCoercion1.errors.txt
  tests/baselines/reference/truthinessCallExpressionCoercion2.errors.txt
  tests/baselines/reference/truthinessPromiseCoercion.errors.txt
  tests/baselines/reference/truthinessPromiseCoercion.js
  tests/baselines/reference/truthinessPromiseCoercion.symbols
  tests/baselines/reference/truthinessPromiseCoercion.types
  tests/cases/compiler/truthinessPromiseCoercion.ts
Labels: Author: Team, For Milestone Bug

#43540 Trim indexed access and type variable constraint error output
  src/compiler/checker.ts
  tests/baselines/reference/errorInfoForRelatedIndexTypesNoConstraintElaboration.errors.txt
  tests/baselines/reference/errorInfoForRelatedIndexTypesNoConstraintElaboration.js
  tests/baselines/reference/errorInfoForRelatedIndexTypesNoConstraintElaboration.symbols
  tests/baselines/reference/errorInfoForRelatedIndexTypesNoConstraintElaboration.types
  tests/baselines/reference/genericTypeAssertions6.errors.txt
  tests/baselines/reference/intrinsicTypes.errors.txt
  tests/baselines/reference/keyofAndIndexedAccessErrors.errors.txt
  tests/baselines/reference/objectTypeWithRecursiveWrappedPropertyCheckedNominally.errors.txt
  tests/baselines/reference/subtypesOfTypeParameterWithConstraints.errors.txt
  tests/baselines/reference/subtypesOfTypeParameterWithConstraints4.errors.txt
  tests/baselines/reference/templateLiteralTypes1.errors.txt
  tests/baselines/reference/typeParameterAssignability2.errors.txt
  tests/baselines/reference/typeParameterAssignability3.errors.txt
  tests/baselines/reference/typeParametersShouldNotBeEqual2.errors.txt
  tests/baselines/reference/typeParametersShouldNotBeEqual3.errors.txt
  tests/baselines/reference/variadicTuples1.errors.txt
  tests/cases/compiler/errorInfoForRelatedIndexTypesNoConstraintElaboration.ts
Labels: Author: Team, For Milestone Bug

#43511 Fix sending correct symbol when using commonjs require and destructuring
  src/services/findAllReferences.ts
  tests/baselines/reference/findAllReferencesJsRequireDestructuring.baseline.jsonc
  tests/cases/fourslash/findAllReferencesJsRequireDestructuring.ts
Labels: For Milestone Bug

#43661 Reinstate constraint check for template literal types
  src/compiler/checker.ts
  tests/baselines/reference/templateLiteralTypes3.errors.txt
  tests/baselines/reference/templateLiteralTypes3.js
  tests/baselines/reference/templateLiteralTypes3.symbols
  tests/baselines/reference/templateLiteralTypes3.types
  tests/cases/conformance/types/literal/templateLiteralTypes3.ts
Labels: Author: Team, For Milestone Bug

#43659 Add jsdoc to all js statements
  src/compiler/parser.ts
  src/compiler/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/typedefOnStatements.errors.txt
  tests/baselines/reference/typedefOnStatements.js
  tests/baselines/reference/typedefOnStatements.symbols
  tests/baselines/reference/typedefOnStatements.types
  tests/cases/conformance/jsdoc/typedefOnStatements.ts
Labels: Author: Team, For Milestone Bug

#43607 fix(43444): Make JSDoc function signatures work on returned function expressions
  src/compiler/utilities.ts
  tests/baselines/reference/jsdocSignatureOnReturnedFunction.js
  tests/baselines/reference/jsdocSignatureOnReturnedFunction.symbols
  tests/baselines/reference/jsdocSignatureOnReturnedFunction.types
  tests/cases/conformance/jsdoc/jsdocSignatureOnReturnedFunction.ts
Labels: For Milestone Bug

#43664 Add telemetry properties for import statement completions
  src/server/protocol.ts
  src/server/session.ts
  src/services/completions.ts
  src/services/types.ts
  src/testRunner/unittests/tsserver/completions.ts
  src/testRunner/unittests/tsserver/partialSemanticServer.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#43599 Expand exception to contravariant constraint elision to all type variables
  src/compiler/checker.ts
  tests/baselines/reference/callOfConditionalTypeWithConcreteBranches.js
  tests/baselines/reference/callOfConditionalTypeWithConcreteBranches.symbols
  tests/baselines/reference/callOfConditionalTypeWithConcreteBranches.types
  tests/cases/compiler/callOfConditionalTypeWithConcreteBranches.ts
Labels: Author: Team, For Milestone Bug

#43560 Consider identical instances of the same symbol equivalent when creating union and intersection properties
  src/compiler/checker.ts
  tests/baselines/reference/bivariantInferences.symbols
  tests/baselines/reference/bivariantInferences.types
  tests/baselines/reference/completionEntryForUnionMethod.baseline
  tests/baselines/reference/conditionalTypeClassMembers.js
  tests/baselines/reference/conditionalTypeClassMembers.symbols
  tests/baselines/reference/conditionalTypeClassMembers.types
  tests/baselines/reference/mixinAccessModifiers.symbols
  tests/baselines/reference/mixinAccessModifiers.types
  tests/baselines/reference/mixinIntersectionIsValidbaseType.types
  tests/baselines/reference/sliceResultCast.js
  tests/baselines/reference/sliceResultCast.symbols
  tests/baselines/reference/sliceResultCast.types
  tests/baselines/reference/typeParameterExtendingUnion1.symbols
  tests/baselines/reference/typeParameterExtendingUnion1.types
  tests/baselines/reference/typeParameterExtendingUnion2.symbols
  tests/baselines/reference/typeParameterExtendingUnion2.types
  tests/cases/compiler/conditionalTypeClassMembers.ts
  tests/cases/compiler/sliceResultCast.ts
Labels: Author: Team, For Milestone Bug

#43682 Fix @typedef/@callback scope
  src/compiler/binder.ts
  tests/baselines/reference/typedefScope1.errors.txt
  tests/baselines/reference/typedefScope1.js
  tests/baselines/reference/typedefScope1.symbols
  tests/baselines/reference/typedefScope1.types
  tests/cases/conformance/jsdoc/typedefScope1.ts
Labels: Author: Team, For Milestone Bug

#43688 Do not erase signatures in getSignatureOfTypeTag
  src/compiler/checker.ts
  tests/baselines/reference/typeTagNoErasure.errors.txt
  tests/baselines/reference/typeTagNoErasure.js
  tests/baselines/reference/typeTagNoErasure.symbols
  tests/baselines/reference/typeTagNoErasure.types
  tests/cases/conformance/jsdoc/typeTagNoErasure.ts
Labels: Author: Team, For Milestone Bug

#43660 Enforce keyword order between override and static/async
  src/compiler/checker.ts
  tests/baselines/reference/override5.errors.txt
  tests/baselines/reference/override5.js
  tests/baselines/reference/override5.symbols
  tests/baselines/reference/override5.types
  tests/baselines/reference/override7.errors.txt
  tests/baselines/reference/override7.js
  tests/baselines/reference/override7.symbols
  tests/baselines/reference/override7.types
  tests/baselines/reference/overrideKeywordOrder.errors.txt
  tests/cases/conformance/override/override5.ts
  tests/cases/conformance/override/override7.ts
  tests/cases/conformance/override/overrideKeywordOrder.ts
Labels: Author: Team, For Milestone Bug

#43699 Node factory should insert override modifier between static and astnc
  src/compiler/factory/nodeFactory.ts
Labels: Author: Team, For Uncommitted Bug

#43701 Don't re-alias top-level type aliases with local type aliases
  src/compiler/checker.ts
  tests/baselines/reference/conditionalTypes1.errors.txt
  tests/baselines/reference/conditionalTypes1.types
Labels: Author: Team, For Milestone Bug

#43455 Wire up 'writing' parameter through protected derived class detection
  src/compiler/checker.ts
  tests/baselines/reference/publicGetterProtectedSetterFromThisParameter.errors.txt
  tests/baselines/reference/publicGetterProtectedSetterFromThisParameter.js
  tests/baselines/reference/publicGetterProtectedSetterFromThisParameter.symbols
  tests/baselines/reference/publicGetterProtectedSetterFromThisParameter.types
  tests/cases/compiler/publicGetterProtectedSetterFromThisParameter.ts
Labels: Author: Team, For Milestone Bug

#43652 Remove preprinter, add parenthesizer callback to emit
  src/compiler/emitter.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/factory/parenthesizerRules.ts
  src/compiler/transformer.ts
  src/compiler/types.ts
  tests/baselines/reference/inlineJsxFactoryDeclarationsLocalTypes.js
  tests/baselines/reference/jsxCheckJsxNoTypeArgumentsAllowed.js
Labels: Author: Team, For Uncommitted Bug

#43666 Skip up-to-date checks during force build
  src/compiler/diagnosticMessages.json
  src/compiler/tsbuildPublic.ts
  tests/baselines/reference/tsbuild/sample1/incremental-declaration-changes/rebuilds-from-start-if-force-option-is-set.js
Labels: Author: Team, For Uncommitted Bug

#43228 Fix organize imports overlap
  src/services/organizeImports.ts
  src/services/textChanges.ts
  tests/cases/fourslash/organizeImports4.ts
  tests/cases/fourslash/organizeImports5.ts
  tests/cases/fourslash/organizeImports6.ts
  tests/cases/fourslash/organizeImports7.ts
Labels: For Milestone Bug

#43696 Use faster, stricter prop type comparison when merging props in union prop creation
  src/compiler/checker.ts
  tests/baselines/reference/bivariantInferences.symbols
  tests/baselines/reference/bivariantInferences.types
  tests/baselines/reference/completionEntryForUnionMethod.baseline
  tests/baselines/reference/mixinAccessModifiers.symbols
  tests/baselines/reference/mixinAccessModifiers.types
  tests/baselines/reference/sliceResultCast.symbols
  tests/baselines/reference/sliceResultCast.types
  tests/baselines/reference/stackDepthLimitCastingType.js
  tests/baselines/reference/stackDepthLimitCastingType.symbols
  tests/baselines/reference/stackDepthLimitCastingType.types
  tests/baselines/reference/typeParameterExtendingUnion1.symbols
  tests/baselines/reference/typeParameterExtendingUnion1.types
  tests/baselines/reference/typeParameterExtendingUnion2.symbols
  tests/baselines/reference/typeParameterExtendingUnion2.types
  tests/baselines/reference/types.asyncGenerators.es2018.2.errors.txt
  tests/cases/compiler/stackDepthLimitCastingType.ts
Labels: Author: Team, For Milestone Bug

#43732 Clean up ObjectFlags enum
  src/compiler/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#43741 Stop checking getter/setter compatability twice
  src/compiler/checker.ts
  tests/baselines/reference/getAndSetNotIdenticalType2.errors.txt
  tests/baselines/reference/getAndSetNotIdenticalType3.errors.txt
  tests/baselines/reference/getterErrorMessageNotDuplicated.errors.txt
  tests/baselines/reference/getterErrorMessageNotDuplicated.js
  tests/baselines/reference/getterErrorMessageNotDuplicated.symbols
  tests/baselines/reference/getterErrorMessageNotDuplicated.types
  tests/cases/compiler/getterErrorMessageNotDuplicated.ts
Labels: Author: Team, For Milestone Bug

#43745 Check type flags before checking multiple-meaning object flags
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug

#43564 Instantiate getter when infering setter parameter value
  src/compiler/checker.ts
  tests/baselines/reference/genericSetterInClassType.js
  tests/baselines/reference/genericSetterInClassType.symbols
  tests/baselines/reference/genericSetterInClassType.types
  tests/baselines/reference/genericSetterInClassTypeJsDoc.js
  tests/baselines/reference/genericSetterInClassTypeJsDoc.symbols
  tests/baselines/reference/genericSetterInClassTypeJsDoc.types
  tests/cases/conformance/classes/members/classTypes/genericSetterInClassType.ts
  tests/cases/conformance/classes/members/classTypes/genericSetterInClassTypeJsDoc.ts
Labels: For Milestone Bug

#43184 Added skipDestructiveCodeActions argument to organize imports server command
  src/harness/client.ts
  src/harness/harnessLanguageService.ts
  src/server/protocol.ts
  src/server/session.ts
  src/services/organizeImports.ts
  src/services/services.ts
  src/services/types.ts
  src/testRunner/unittests/services/organizeImports.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/organizeImports/Syntax_Error_Body.ts
  tests/baselines/reference/organizeImports/Syntax_Error_Body_skipDestructiveCodeActions.ts
  tests/baselines/reference/organizeImports/Syntax_Error_Imports.ts
  tests/baselines/reference/organizeImports/Syntax_Error_Imports_skipDestructiveCodeActions.ts
Labels: For Backlog Bug

#43645 Fix getCodeFixesAtPosition for ts(2339) thows error False expression: Token end is child end
  src/services/codefixes/fixAddMissingMember.ts
  tests/cases/fourslash/codeFixAddMissingMember20.ts
Labels: For Backlog Bug

#43572 Fix object literals lack of this references
  src/services/findAllReferences.ts
  tests/cases/fourslash/getOccurrencesThis6.ts
Labels: For Backlog Bug

#43526 Completion list for type literals in type arguments
  src/compiler/checker.ts
  src/compiler/types.ts
  src/services/completions.ts
  tests/cases/fourslash/completionListInTypeLiteralInTypeParameter1.ts
  tests/cases/fourslash/completionListInTypeLiteralInTypeParameter2.ts
  tests/cases/fourslash/completionListInTypeLiteralInTypeParameter3.ts
  tests/cases/fourslash/completionListInTypeLiteralInTypeParameter4.ts
  tests/cases/fourslash/completionListInTypeLiteralInTypeParameter5.ts
  tests/cases/fourslash/completionListInTypeLiteralInTypeParameter6.ts
  tests/cases/fourslash/completionListInTypeLiteralInTypeParameter7.ts
  tests/cases/fourslash/completionListInTypeLiteralInTypeParameter8.ts
  tests/cases/fourslash/completionListInTypeLiteralInTypeParameter9.ts
Labels: For Uncommitted Bug

#43762 Pin octokit types
  .github/workflows/update-package-lock.yaml
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#43649 Add `infer T` constraint inference rule matching up mapped type templates across check/extends types
  src/compiler/checker.ts
  tests/baselines/reference/inferConditionalConstraintMappedMember.js
  tests/baselines/reference/inferConditionalConstraintMappedMember.symbols
  tests/baselines/reference/inferConditionalConstraintMappedMember.types
  tests/cases/compiler/inferConditionalConstraintMappedMember.ts
Labels: Author: Team, For Milestone Bug

#43766 Remove @octokit/types pin, it’s fixed
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#43769 Handle getter setter quickInfo
  src/compiler/checker.ts
  tests/cases/fourslash/quickInfoGetterSetter.ts
  tests/cases/fourslash/quickInfoSpecialPropertyAssignment.ts
Labels: Author: Team, For Milestone Bug

#43700 Module Resolution and Type Reference directive cache updates and its API changes
  src/compiler/diagnosticMessages.json
  src/compiler/moduleNameResolver.ts
  src/compiler/program.ts
  src/compiler/resolutionCache.ts
  src/compiler/tsbuildPublic.ts
  src/testRunner/unittests/reuseProgramStructure.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/duplicatePackage_relativeImportWithinPackage.trace.json
  tests/baselines/reference/duplicatePackage_relativeImportWithinPackage_scoped.trace.json
  tests/baselines/reference/importWithTrailingSlash.trace.json
  tests/baselines/reference/library-reference-1.trace.json
  tests/baselines/reference/library-reference-10.trace.json
  tests/baselines/reference/library-reference-2.trace.json
  tests/baselines/reference/library-reference-6.trace.json
  tests/baselines/reference/library-reference-8.trace.json
  tests/baselines/reference/maxNodeModuleJsDepthDefaultsToZero.trace.json
  tests/baselines/reference/moduleResolutionPackageIdWithRelativeAndAbsolutePath.trace.json
  tests/baselines/reference/moduleResolutionWithExtensions_unexpected.trace.json
  tests/baselines/reference/moduleResolutionWithExtensions_unexpected2.trace.json
  tests/baselines/reference/moduleResolutionWithExtensions_withAmbientPresent.trace.json
  tests/baselines/reference/moduleResolutionWithExtensions_withPaths.trace.json
  tests/baselines/reference/moduleResolutionWithSymlinks_preserveSymlinks.trace.json
  tests/baselines/reference/moduleResolution_packageJson_yesAtPackageRoot.trace.json
  tests/baselines/reference/moduleResolution_packageJson_yesAtPackageRoot_fakeScopedPackage.trace.json
  tests/baselines/reference/packageJsonMain.trace.json
  tests/baselines/reference/packageJsonMain_isNonRecursive.trace.json
  tests/baselines/reference/pathMappingBasedModuleResolution_withExtension_MapedToNodeModules.trace.json
  tests/baselines/reference/requireOfJsonFileWithoutResolveJsonModuleAndPathMapping.trace.json
  tests/baselines/reference/requireOfJsonFile_PathMapping.trace.json
  tests/baselines/reference/scopedPackages.trace.json
  tests/baselines/reference/typeReferenceDirectives1.trace.json
  tests/baselines/reference/typeReferenceDirectives10.trace.json
  tests/baselines/reference/typeReferenceDirectives12.trace.json
  tests/baselines/reference/typeReferenceDirectives13.trace.json
  tests/baselines/reference/typeReferenceDirectives3.trace.json
  tests/baselines/reference/typeReferenceDirectives4.trace.json
  tests/baselines/reference/typeReferenceDirectives5.trace.json
  tests/baselines/reference/typeReferenceDirectives6.trace.json
  tests/baselines/reference/typeReferenceDirectives7.trace.json
  tests/baselines/reference/typeReferenceDirectives9.trace.json
  tests/baselines/reference/typesVersions.ambientModules.trace.json
  tests/baselines/reference/typesVersions.multiFile.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.ambient.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFile.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFileBackReferenceToSelf.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFileBackReferenceToUnmapped.trace.json
  tests/baselines/reference/typingsLookup1.trace.json
  tests/baselines/reference/typingsLookup3.trace.json
  tests/baselines/reference/typingsLookup4.trace.json
  tests/baselines/reference/typingsLookupAmd.trace.json
Labels: Author: Team, For Milestone Bug

#43452 fix(42829) ignore preceeding jsx whitespace
  src/services/refactors/extractSymbol.ts
  src/services/utilities.ts
  tests/cases/fourslash/extract-method_jsxPreceedingWhitespace.ts
Labels: For Backlog Bug

#43783 Don’t allow an object literal with a spread as a fallback for destructuring a property not present in all constituents
  src/compiler/checker.ts
  tests/baselines/reference/destructuringFromUnionSpread.errors.txt
  tests/baselines/reference/destructuringFromUnionSpread.js
  tests/baselines/reference/destructuringFromUnionSpread.symbols
  tests/baselines/reference/destructuringFromUnionSpread.types
  tests/cases/compiler/destructuringFromUnionSpread.ts
Labels: Author: Team, Breaking Change, For Milestone Bug

#43765 Compute dervied generic-ness for substitutions and create lower priority inferences for substitutes
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/nongenericConditionalNotPartiallyComputed.js
  tests/baselines/reference/nongenericConditionalNotPartiallyComputed.symbols
  tests/baselines/reference/nongenericConditionalNotPartiallyComputed.types
  tests/cases/compiler/nongenericConditionalNotPartiallyComputed.ts
Labels: Author: Team, For Milestone Bug

#43800 Omit spaces after https in jsdoc comments
  src/services/jsDoc.ts
  tests/baselines/reference/quickInfoForJSDocWithHttpLinks.baseline
  tests/cases/fourslash/quickInfoForJSDocWithHttpLinks.ts
Labels: Author: Team, For Milestone Bug

#43579 fix(43559): no-default-lib causes 'You cannot rename elements that are defined in the standard TypeScript library'
  src/services/rename.ts
  tests/cases/fourslash/renameNoDefaultLib.ts
Labels: For Backlog Bug

#43633 update contextual discrimination to include omitted members
  src/compiler/checker.ts
  tests/baselines/reference/discriminantPropertyInference.js
  tests/baselines/reference/discriminantPropertyInference.symbols
  tests/baselines/reference/discriminantPropertyInference.types
  tests/baselines/reference/tsxDiscriminantPropertyInference.js
  tests/baselines/reference/tsxDiscriminantPropertyInference.symbols
  tests/baselines/reference/tsxDiscriminantPropertyInference.types
  tests/cases/compiler/discriminantPropertyInference.ts
  tests/cases/compiler/tsxDiscriminantPropertyInference.tsx
Labels: For Backlog Bug

#43598 Contextual typing checks property assignments for type annotation
  src/compiler/checker.ts
  tests/baselines/reference/typeTagOnPropertyAssignment.symbols
  tests/baselines/reference/typeTagOnPropertyAssignment.types
  tests/cases/conformance/jsdoc/typeTagOnPropertyAssignment.ts
Labels: Author: Team, For Milestone Bug

#43828 Don’t create invalid type-only imports during add missing import
  src/services/codefixes/importFixes.ts
  tests/cases/fourslash/importNameCodeFix_typeOnly3.ts
Labels: Author: Team, For Milestone Bug

#43835 Refrain from attempting to perform parameter fixing on a generic signature multiple times
  src/compiler/checker.ts
  tests/baselines/reference/contextuallyTypedGenericAssignment.js
  tests/baselines/reference/contextuallyTypedGenericAssignment.symbols
  tests/baselines/reference/contextuallyTypedGenericAssignment.types
  tests/cases/compiler/contextuallyTypedGenericAssignment.ts
Labels: Author: Team, For Uncommitted Bug

#42449 Add instantiation rules for reverse mapped types
  src/compiler/checker.ts
  tests/baselines/reference/genericFunctionsAndConditionalInference.js
  tests/baselines/reference/genericFunctionsAndConditionalInference.symbols
  tests/baselines/reference/genericFunctionsAndConditionalInference.types
  tests/cases/compiler/genericFunctionsAndConditionalInference.ts
Labels: Author: Team, For Milestone Bug

#43624 Relate non-augmenting subtypes without resorting to structural comparison
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/arrayLiterals3.errors.txt
  tests/baselines/reference/assignmentCompatWithObjectMembersAccessibility.errors.txt
  tests/baselines/reference/checkJsxChildrenProperty5.errors.txt
  tests/baselines/reference/classImplementsClass4.errors.txt
  tests/baselines/reference/crashInsourcePropertyIsRelatableToTargetProperty.errors.txt
  tests/baselines/reference/implementingAnInterfaceExtendingClassWithProtecteds.errors.txt
  tests/baselines/reference/inheritance1.errors.txt
  tests/baselines/reference/inheritanceGrandParentPrivateMemberCollisionWithPublicMember.errors.txt
  tests/baselines/reference/inheritanceGrandParentPublicMemberCollisionWithPrivateMember.errors.txt
  tests/baselines/reference/interfaceImplementation8.errors.txt
  tests/baselines/reference/privateNamesUnique-4.errors.txt
  tests/baselines/reference/privateNamesUnique-5.errors.txt
  tests/baselines/reference/recursiveComplicatedClasses.types
Labels: Author: Team, For Uncommitted Bug

#43854 Fix `node.getStart()` for nodes spanning multiline JSDoc comments
  src/compiler/scanner.ts
  src/compiler/utilities.ts
  tests/cases/fourslash/documentHighlightJSDocTypedef.ts
Labels: Author: Team, For Milestone Bug

#43707 typeRelatedToSomeType passes through intersectionState
  src/compiler/checker.ts
  tests/baselines/reference/recursiveExcessPropertyChecks.js
  tests/baselines/reference/recursiveExcessPropertyChecks.symbols
  tests/baselines/reference/recursiveExcessPropertyChecks.types
  tests/cases/compiler/recursiveExcessPropertyChecks.ts
Labels: Author: Team, For Milestone Bug

#43831 Allow `override` as parameter property
  src/compiler/checker.ts
  src/compiler/types.ts
  src/harness/fourslashInterfaceImpl.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/override11.errors.txt
  tests/baselines/reference/overrideParameterProperty.errors.txt
  tests/baselines/reference/overrideParameterProperty.js
  tests/baselines/reference/overrideParameterProperty.symbols
  tests/baselines/reference/overrideParameterProperty.types
  tests/cases/conformance/override/overrideParameterProperty.ts
Labels: Author: Team, For Uncommitted Bug

#43829 Enforce keyword order of `abstract` and `override`
  src/compiler/checker.ts
  tests/baselines/reference/override10.js
  tests/baselines/reference/override10.symbols
  tests/baselines/reference/override10.types
  tests/baselines/reference/override5.errors.txt
  tests/baselines/reference/override7.errors.txt
  tests/baselines/reference/overrideKeywordOrder.errors.txt
  tests/cases/conformance/override/override10.ts
  tests/cases/conformance/override/overrideKeywordOrder.ts
Labels: Author: Team, For Uncommitted Bug

#43634 Use single quotes consistently in diagnostic messages.
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/ES5For-ofTypeCheck10.errors.txt
  tests/baselines/reference/ES5SymbolProperty2.errors.txt
  tests/baselines/reference/ES5SymbolProperty6.errors.txt
  tests/baselines/reference/argumentsObjectIterator02_ES5.errors.txt
  tests/baselines/reference/asyncFunctionNoReturnType.errors.txt
  tests/baselines/reference/asyncFunctionReturnExpressionErrorSpans.errors.txt
  tests/baselines/reference/bigintWithoutLib.errors.txt
  tests/baselines/reference/constructorWithIncompleteTypeAnnotation.errors.txt
  tests/baselines/reference/decoratorMetadataNoLibIsolatedModulesTypes.errors.txt
  tests/baselines/reference/destructuringControlFlowNoCrash.errors.txt
  tests/baselines/reference/didYouMeanSuggestionErrors.errors.txt
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2015.errors.txt
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2016Plus.errors.txt
  tests/baselines/reference/forwardDeclaredCommonTypes01.errors.txt
  tests/baselines/reference/importCallExpressionNoModuleKindSpecified.errors.txt
  tests/baselines/reference/importMeta(module=commonjs,target=es5).errors.txt
  tests/baselines/reference/importMeta(module=commonjs,target=esnext).errors.txt
  tests/baselines/reference/importMeta(module=es2020,target=es5).errors.txt
  tests/baselines/reference/importMeta(module=es2020,target=esnext).errors.txt
  tests/baselines/reference/importMeta(module=esnext,target=es5).errors.txt
  tests/baselines/reference/importMeta(module=esnext,target=esnext).errors.txt
  tests/baselines/reference/importMeta(module=system,target=es5).errors.txt
  tests/baselines/reference/importMeta(module=system,target=esnext).errors.txt
  tests/baselines/reference/incrementalInvalid.errors.txt
  tests/baselines/reference/modularizeLibrary_ErrorFromUsingES6FeaturesWithOnlyES5Lib.errors.txt
  tests/baselines/reference/modularizeLibrary_ErrorFromUsingWellknownSymbolWithOutES6WellknownSymbolLib.errors.txt
  tests/baselines/reference/namedTupleMembersErrors.errors.txt
  tests/baselines/reference/operationsAvailableOnPromisedType.errors.txt
  tests/baselines/reference/parserES5SymbolProperty1.errors.txt
  tests/baselines/reference/parserES5SymbolProperty2.errors.txt
  tests/baselines/reference/parserES5SymbolProperty3.errors.txt
  tests/baselines/reference/parserES5SymbolProperty4.errors.txt
  tests/baselines/reference/parserES5SymbolProperty5.errors.txt
  tests/baselines/reference/parserES5SymbolProperty6.errors.txt
  tests/baselines/reference/parserES5SymbolProperty7.errors.txt
  tests/baselines/reference/parserES5SymbolProperty8.errors.txt
  tests/baselines/reference/parserES5SymbolProperty9.errors.txt
  tests/baselines/reference/parserMissingLambdaOpenBrace1.errors.txt
  tests/baselines/reference/tscWatch/emit/emit-for-configured-projects/should-contains-only-itself-if-a-module-file's-shape-didn't-change,-and-all-files-referencing-it-if-its-shape-changed.js
  tests/baselines/reference/tscWatch/programUpdates/correctly-handles-changes-in-lib-section-of-config-file.js
  tests/baselines/reference/tscWatch/programUpdates/create-watch-without-config-file.js
  tests/baselines/reference/typingsSuggestion1.errors.txt
  tests/baselines/reference/untypedModuleImport_noImplicitAny_typesForPackageExist.errors.txt
  tests/baselines/reference/useObjectValuesAndEntries2.errors.txt
  tests/baselines/reference/useObjectValuesAndEntries3.errors.txt
  tests/baselines/reference/useSharedArrayBuffer2.errors.txt
  tests/baselines/reference/useSharedArrayBuffer3.errors.txt
  tests/cases/fourslash/jsDocAugmentsAndExtends.ts
Labels: For Backlog Bug

#43476 fix(43408): JSDoc accessor declaration emit drops undefined when strictNullChecks is off
  src/compiler/checker.ts
  tests/baselines/reference/jsDeclarationsReusesExistingTypeAnnotations.js
  tests/baselines/reference/jsDeclarationsReusesExistingTypeAnnotations.symbols
  tests/baselines/reference/jsDeclarationsReusesExistingTypeAnnotations.types
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsReusesExistingTypeAnnotations.ts
Labels: For Backlog Bug

#43654 Complete `constructor` keyword after property declaration
  src/services/completions.ts
  tests/cases/fourslash/completionConstructorKeywordAfterPropertyDeclaration.ts
Labels: For Backlog Bug

#43855 Simplify arity errors, rewording spread errors
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/callOverload.errors.txt
  tests/baselines/reference/callWithSpread2.errors.txt
  tests/baselines/reference/callWithSpread3.errors.txt
  tests/baselines/reference/callWithSpread3.js
  tests/baselines/reference/callWithSpread3.symbols
  tests/baselines/reference/callWithSpread3.types
  tests/baselines/reference/callWithSpread4.errors.txt
  tests/baselines/reference/callWithSpread4.js
  tests/baselines/reference/callWithSpread4.symbols
  tests/baselines/reference/callWithSpread4.types
  tests/baselines/reference/callWithSpread5.errors.txt
  tests/baselines/reference/callWithSpread5.js
  tests/baselines/reference/callWithSpread5.symbols
  tests/baselines/reference/callWithSpread5.types
  tests/baselines/reference/functionParameterArityMismatch.errors.txt
  tests/baselines/reference/iteratorSpreadInCall.errors.txt
  tests/baselines/reference/iteratorSpreadInCall10.errors.txt
  tests/baselines/reference/iteratorSpreadInCall2.errors.txt
  tests/baselines/reference/iteratorSpreadInCall4.errors.txt
  tests/baselines/reference/noImplicitAnyLoopCrash.errors.txt
  tests/baselines/reference/readonlyRestParameters.errors.txt
  tests/cases/conformance/expressions/functionCalls/callWithSpread3.ts
  tests/cases/conformance/expressions/functionCalls/callWithSpread4.ts
  tests/cases/conformance/expressions/functionCalls/callWithSpread5.ts
Labels: Author: Team, For Backlog Bug, For Milestone Bug

#43718 getExternalModuleMember:always resolve alias of moduleSymbol
  src/compiler/checker.ts
  tests/baselines/reference/commonJSAliasedExport.js
  tests/baselines/reference/commonJSAliasedExport.symbols
  tests/baselines/reference/commonJSAliasedExport.types
  tests/baselines/tj.json
  tests/cases/conformance/salsa/commonJSAliasedExport.ts
Labels: Author: Team, For Milestone Bug

#43851 Handle localness in special cases by checking exported variable assignment
  src/compiler/utilitiesPublic.ts
  src/services/goToDefinition.ts
  src/testRunner/unittests/tsserver/projectReferences.ts
  tests/baselines/reference/implicitAnyFromCircularInference.errors.txt
  tests/cases/fourslash/goToDefinitionJsModuleExports.ts
  tests/cases/fourslash/goToDefinitionSignatureAlias.ts
  tests/cases/fourslash/goToTypeDefinition_returnType.ts
Labels: Author: Team, For Milestone Bug

#42232 Use project relative preference for declaration emit
  src/compiler/checker.ts
  src/compiler/moduleSpecifiers.ts
  src/compiler/transformers/declarations.ts
  tests/baselines/reference/declarationEmitPathMappingMonorepo2.js
  tests/baselines/reference/declarationEmitPathMappingMonorepo2.symbols
  tests/baselines/reference/declarationEmitPathMappingMonorepo2.types
  tests/cases/compiler/declarationEmitPathMappingMonorepo2.ts
Labels: Author: Team, For Milestone Bug

#43903 Displayparts resolves non-values in link tags
  src/services/utilities.ts
  tests/baselines/reference/jsdocLink4.baseline
  tests/baselines/reference/quickInfoForJSDocWithHttpLinks.baseline
  tests/cases/fourslash/jsdocLink4.ts
Labels: Author: Team, For Milestone Bug
