Repository microsoft/TypeScript, pull requests merged in 2021-06, with the labels that each got.

#44368 Add a testcase that fails when someone tries to make an Object.keys PR
  tests/baselines/reference/noObjectKeysToKeyofT.js
  tests/baselines/reference/noObjectKeysToKeyofT.symbols
  tests/baselines/reference/noObjectKeysToKeyofT.types
  tests/cases/compiler/noObjectKeysToKeyofT.ts
Labels: Author: Team, For Uncommitted Bug

#44347 Switch references to master to main in the codebase + validating infra post-main migration
  .github/pull_request_template.md
  .github/workflows/ci.yml
  .github/workflows/sync-branch.yaml
  CONTRIBUTING.md
  README.md
  scripts/open-user-pr.ts
  scripts/update-experimental-branches.js
Labels: Author: Team, For Uncommitted Bug

#44370 [release-4.3] Fix unintended 'as const' name lookup error (#44311)
  src/compiler/checker.ts
  tests/baselines/reference/noAsConstNameLookup.js
  tests/baselines/reference/noAsConstNameLookup.symbols
  tests/baselines/reference/noAsConstNameLookup.types
  tests/cases/compiler/noAsConstNameLookup.ts
Labels: For Milestone Bug

#44367 Fixes subset of bugs (three tests fixed) listed in issue #41974
  src/compiler/checker.ts
  tests/baselines/reference/enumTagCircularReference.errors.txt
  tests/baselines/reference/jsdocImportTypeNodeNamespace.errors.txt
  tests/baselines/reference/jsdocTypeTagCast.errors.txt
Labels: For Uncommitted Bug

#42514 Rename TSConfig option categories
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  src/testRunner/unittests/config/commandLineParsing.ts
  tests/baselines/reference/showConfig/Shows tsconfig for single option/locale/tsconfig.json
  tests/baselines/reference/tsConfig/Default initialized TSConfig/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with advanced options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with boolean value compiler options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with enum value compiler options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with files options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with incorrect compiler option value/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with incorrect compiler option/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with list compiler options with enum value/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with list compiler options/tsconfig.json
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/declarationDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/when-outDir-and-declarationDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/when-outDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/with-outFile.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/without-outDir-or-outFile-is-specified-with-declaration-enabled.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/without-outDir-or-outFile-is-specified.js
Labels: Author: Team, For Uncommitted Bug

#44352 Improve non-ambient class and function merge error
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/augmentedTypesClass2a.errors.txt
  tests/baselines/reference/augmentedTypesFunction.errors.txt
  tests/baselines/reference/callOverloads1.errors.txt
  tests/baselines/reference/callOverloads2.errors.txt
  tests/baselines/reference/callOverloads3.errors.txt
  tests/baselines/reference/callOverloads4.errors.txt
  tests/baselines/reference/callOverloads5.errors.txt
  tests/baselines/reference/classOverloadForFunction.errors.txt
  tests/baselines/reference/classOverloadForFunction2.errors.txt
  tests/baselines/reference/duplicateIdentifiersAcrossContainerBoundaries.errors.txt
  tests/baselines/reference/duplicateIdentifiersAcrossFileBoundaries.errors.txt
  tests/baselines/reference/funClodule.errors.txt
  tests/baselines/reference/multipleDefaultExports01.errors.txt
  tests/baselines/reference/multipleExportDefault5.errors.txt
  tests/baselines/reference/nameCollisions.errors.txt
  tests/baselines/reference/staticClassMemberError.errors.txt
  tests/cases/fourslash/insertReturnStatementInDuplicateIdentifierFunction.ts
Labels: Author: Team, For Backlog Bug

#41013 Add flag to change `catch` variables' default types to `unknown`
  src/compiler/checker.ts
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  src/compiler/types.ts
  src/compiler/utilities.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/controlFlowForCatchAndFinally.types
  tests/baselines/reference/showConfig/Shows tsconfig for single option/useUnknownInCatchVariables/tsconfig.json
  tests/baselines/reference/tryCatchFinallyControlFlow.types
  tests/baselines/reference/tsConfig/Default initialized TSConfig/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with advanced options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with boolean value compiler options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with enum value compiler options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with files options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with incorrect compiler option value/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with incorrect compiler option/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with list compiler options with enum value/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with list compiler options/tsconfig.json
  tests/baselines/reference/tsc/runWithoutArgs/initial-build/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/declarationDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/when-outDir-and-declarationDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/when-outDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/with-outFile.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/without-outDir-or-outFile-is-specified-with-declaration-enabled.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/without-outDir-or-outFile-is-specified.js
  tests/baselines/reference/typedefOnStatements.types
  tests/baselines/reference/useUnknownInCatchVariables01.errors.txt
  tests/baselines/reference/useUnknownInCatchVariables01.js
  tests/baselines/reference/useUnknownInCatchVariables01.symbols
  tests/baselines/reference/useUnknownInCatchVariables01.types
  tests/cases/compiler/useUnknownInCatchVariables01.ts
Labels: For Milestone Bug

#44290 fix(44273): preserves 'override' modifier in JavaScript output
  src/compiler/transformers/ts.ts
  tests/baselines/reference/override16(target=es2015).js
  tests/baselines/reference/override16(target=es2015).symbols
  tests/baselines/reference/override16(target=es2015).types
  tests/baselines/reference/override16(target=esnext).js
  tests/baselines/reference/override16(target=esnext).symbols
  tests/baselines/reference/override16(target=esnext).types
  tests/baselines/reference/override16.js
  tests/baselines/reference/override16.symbols
  tests/baselines/reference/override16.types
  tests/baselines/reference/override17(target=es2015).js
  tests/baselines/reference/override17(target=es2015).symbols
  tests/baselines/reference/override17(target=es2015).types
  tests/baselines/reference/override17(target=esnext).js
  tests/baselines/reference/override17(target=esnext).symbols
  tests/baselines/reference/override17(target=esnext).types
  tests/baselines/reference/override18(target=es2015).js
  tests/baselines/reference/override18(target=es2015).symbols
  tests/baselines/reference/override18(target=es2015).types
  tests/baselines/reference/override18(target=esnext).js
  tests/baselines/reference/override18(target=esnext).symbols
  tests/baselines/reference/override18(target=esnext).types
  tests/cases/conformance/override/override16.ts
  tests/cases/conformance/override/override17.ts
  tests/cases/conformance/override/override18.ts
Labels: For Milestone Bug

#44394 Handle strict flag when writing tsbuildinfo
  src/compiler/builder.ts
  src/compiler/commandLineParser.ts
  src/testRunner/unittests/tsc/incremental.ts
  tests/baselines/reference/tsbuild/demo/initial-build/in-bad-ref-branch-reports-the-error-about-files-not-in-rootDir-at-the-import-location.js
  tests/baselines/reference/tsbuild/demo/initial-build/in-master-branch-with-everything-setup-correctly-and-reports-no-error.js
  tests/baselines/reference/tsbuild/emitDeclarationOnly/initial-build/only-dts-output-in-circular-import-project-with-emitDeclarationOnly-and-declarationMap.js
  tests/baselines/reference/tsbuild/emitDeclarationOnly/initial-build/only-dts-output-in-circular-import-project-with-emitDeclarationOnly.js
  tests/baselines/reference/tsbuild/emitDeclarationOnly/initial-build/only-dts-output-in-non-circular-imports-project-with-emitDeclarationOnly.js
  tests/baselines/reference/tsbuild/outFile/initial-build/non-module-projects-without-prepend.js
  tests/baselines/reference/tsbuild/resolveJsonModule/initial-build/importing-json-module-from-project-reference.js
  tests/baselines/reference/tsbuild/watchMode/demo/updates-with-bad-reference.js
  tests/baselines/reference/tsbuild/watchMode/demo/updates-with-circular-reference.js
  tests/baselines/reference/tsc/incremental/initial-build/when-project-has-strict-true.js
  tests/baselines/reference/tsc/react-jsx-emit-mode/initial-build/with-no-backing-types-found-doesn't-crash-under---strict.js
Labels: Author: Team, For Uncommitted Bug

#44344 fix: check if sysFormatDiagnosticsHost is defined
  src/compiler/watch.ts
Labels: For Uncommitted Bug

#44070 Do not incorrectly add line separators for non-synthetic nodes when emitting node list
  src/compiler/emitter.ts
  src/testRunner/unittests/transform.ts
  tests/baselines/reference/decoratorOnClassMethodThisParameter.js
  tests/baselines/reference/jsxJsxsCjsTransformNestedSelfClosingChild(jsx=react-jsx).js
  tests/baselines/reference/jsxJsxsCjsTransformNestedSelfClosingChild(jsx=react-jsxdev).js
  tests/baselines/reference/objectLiteralShorthandPropertiesErrorFromNotUsingIdentifier.js
  tests/baselines/reference/objectLiteralShorthandPropertiesErrorWithModule.js
  tests/baselines/reference/objectTypesWithOptionalProperties2.js
  tests/baselines/reference/parserErrorRecovery_ObjectLiteral2.js
  tests/baselines/reference/transformApi/transformsCorrectly.issue44068.js
Labels: For Milestone Bug

#44443 Fix duplicate visit of param tag comments
  src/compiler/parser.ts
  src/testRunner/unittests/publicApi.ts
Labels: Author: Team, For Milestone Bug

#44444 [release-4.3] Fix duplicate visit of param tag comments (#44443)
  src/compiler/parser.ts
  src/testRunner/unittests/publicApi.ts
Labels: For Milestone Bug

#44456 Update playground build script for tsc
  scripts/createPlaygroundBuild.js
Labels: Author: Team, For Uncommitted Bug

#44489 Add SolutionBuilderHostBase.getCustomTransformers to be used when emitting.
  src/compiler/tsbuildPublic.ts
  src/testRunner/tsconfig.json
  src/testRunner/unittests/tsbuildWatch/publicApi.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/tsbuild/watchMode/publicApi/with-custom-transformers.js
Labels: Author: Team, For Uncommitted Bug

#44259 Include type reference directives in symlink cache, wait until program is present to create it
  src/compiler/checker.ts
  src/compiler/moduleSpecifiers.ts
  src/compiler/program.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/harness/client.ts
  src/server/project.ts
  src/services/codefixes/importFixes.ts
  src/services/completions.ts
  src/services/utilities.ts
  src/testRunner/tsconfig.json
  src/testRunner/unittests/tsserver/symlinkCache.ts
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/importStatementCompletions1.ts
  tests/cases/fourslash/importStatementCompletions_esModuleInterop1.ts
  tests/cases/fourslash/importStatementCompletions_esModuleInterop2.ts
  tests/cases/fourslash/importStatementCompletions_noPatternAmbient.ts
  tests/cases/fourslash/importStatementCompletions_noSnippet.ts
  tests/cases/fourslash/importStatementCompletions_quotes.ts
  tests/cases/fourslash/importStatementCompletions_semicolons.ts
  tests/cases/fourslash/server/importNameCodeFix_pnpm1.ts
  tests/cases/fourslash/server/importStatementCompletions_pnpm1.ts
Labels: Author: Team, For Uncommitted Bug

#44266 feat(44263): Provide quick fix for misspelled override error
  src/compiler/checker.ts
  src/compiler/types.ts
  src/services/codefixes/fixSpelling.ts
  tests/baselines/reference/override_js4.errors.txt
  tests/baselines/reference/override_js4.symbols
  tests/baselines/reference/override_js4.types
  tests/cases/conformance/override/override_js4.ts
  tests/cases/fourslash/codeFixSpelling10.ts
  tests/cases/fourslash/codeFixSpelling11.ts
  tests/cases/fourslash/codeFixSpelling12.ts
Labels: For Uncommitted Bug

#44236 fix(43298): Function refactor removes comment
  src/services/refactors/convertArrowFunctionOrFunctionExpression.ts
  tests/cases/fourslash/refactorConvertArrowFunctionOrFunctionExpression_ToAnonymous_Comment1.ts
  tests/cases/fourslash/refactorConvertArrowFunctionOrFunctionExpression_ToAnonymous_Comment2.ts
Labels: For Backlog Bug

#44517 Fix typo in open-cherry-pick-pr.ts
  scripts/open-cherry-pick-pr.ts
Labels: For Uncommitted Bug

#44413 Re-name really long test file
  src/testRunner/unittests/tsserver/projectReferences.ts
  tests/baselines/reference/tsserver/projectReferences/special-handling-of-localness-when-using-arrow-function-as-object-literal-property-types.js
  tests/baselines/reference/tsserver/projectReferences/special-handling-of-localness-when-using-arrow-function-as-object-literal-property.js
Labels: Author: Team, For Uncommitted Bug

#44514 Add missing JSXSpreadAttribute case to JSX completion logic
  src/services/completions.ts
  tests/cases/fourslash/jsxAriaLikeCompletions.ts
Labels: Author: Team, For Milestone Bug

#44176 Include actual generated module specifiers in module specifier cache
  src/compiler/moduleSpecifiers.ts
  src/compiler/transformers/declarations.ts
  src/compiler/types.ts
  src/server/editorServices.ts
  src/server/project.ts
  src/server/watchType.ts
  src/services/codefixes/importFixes.ts
  src/services/completions.ts
  src/services/utilities.ts
  src/testRunner/unittests/tsserver/moduleSpecifierCache.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/tsserver/projectErrors/correct-errors-when-resolution-resolves-to-file-that-has-same-ambient-module-and-is-also-module.js
  tests/baselines/reference/tsserver/projectErrors/npm-install-when-timeout-occurs-after-installation.js
  tests/baselines/reference/tsserver/projectErrors/npm-install-when-timeout-occurs-inbetween-installation.js
  tests/baselines/reference/tsserver/projectReferences/auto-import-with-referenced-project-when-built-with-disableSourceOfProjectReferenceRedirect.js
  tests/baselines/reference/tsserver/projectReferences/auto-import-with-referenced-project-when-built.js
  tests/baselines/reference/tsserver/projectReferences/auto-import-with-referenced-project.js
  tests/baselines/reference/tsserver/resolutionCache/npm-install-@types-works.js
Labels: Author: Team, For Uncommitted Bug

#44206 fixes(44110): allow "extract to inner function" refactoring inside function expression
  src/services/refactors/extractSymbol.ts
  src/testRunner/unittests/services/extract/functions.ts
  tests/baselines/reference/extractFunction/extractFunction10.ts
  tests/baselines/reference/extractFunction/extractFunction11.ts
  tests/baselines/reference/extractFunction/extractFunction12.ts
  tests/baselines/reference/extractFunction/extractFunction13.ts
  tests/baselines/reference/extractFunction/extractFunction17.ts
  tests/baselines/reference/extractFunction/extractFunction18.ts
  tests/baselines/reference/extractFunction/extractFunction20.js
  tests/baselines/reference/extractFunction/extractFunction20.ts
  tests/baselines/reference/extractFunction/extractFunction26.js
  tests/baselines/reference/extractFunction/extractFunction26.ts
  tests/baselines/reference/extractFunction/extractFunction27.js
  tests/baselines/reference/extractFunction/extractFunction27.ts
  tests/baselines/reference/extractFunction/extractFunction28.js
  tests/baselines/reference/extractFunction/extractFunction28.ts
  tests/baselines/reference/extractFunction/extractFunction31.ts
  tests/baselines/reference/extractFunction/extractFunction32.ts
  tests/baselines/reference/extractFunction/extractFunction34.js
  tests/baselines/reference/extractFunction/extractFunction34.ts
  tests/baselines/reference/extractFunction/extractFunction_NamelessClass.js
  tests/baselines/reference/extractFunction/extractFunction_NamelessClass.ts
  tests/cases/fourslash/extract-method20.ts
Labels: For Backlog Bug

#44322 Make handleDtsMayChangeOf void-returning
  src/compiler/builder.ts
Labels: Author: Team, For Uncommitted Bug

#44565 Ensure singleton types always compare identical
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/strictOptionalProperties1.errors.txt
  tests/baselines/reference/strictOptionalProperties1.js
  tests/baselines/reference/strictOptionalProperties1.symbols
  tests/baselines/reference/strictOptionalProperties1.types
  tests/cases/compiler/strictOptionalProperties1.ts
Labels: Author: Team, For Milestone Bug

#44568 Correct tuple relations in --strictOptionalProperties mode
  src/compiler/checker.ts
  tests/baselines/reference/arityAndOrderCompatibility01.errors.txt
  tests/baselines/reference/castingTuple.errors.txt
  tests/baselines/reference/contextualTypeWithTuple.errors.txt
  tests/baselines/reference/iterableArrayPattern29.errors.txt
  tests/baselines/reference/restTupleElements1.errors.txt
  tests/baselines/reference/strictOptionalProperties2.js
  tests/baselines/reference/strictOptionalProperties2.symbols
  tests/baselines/reference/strictOptionalProperties2.types
  tests/baselines/reference/tupleTypes.errors.txt
  tests/baselines/reference/variadicTuples1.errors.txt
  tests/cases/compiler/strictOptionalProperties2.ts
Labels: Author: Team, For Milestone Bug

#44523 Fix bug due to sharing of `.type.members`
  src/services/codefixes/helpers.ts
  src/services/textChanges.ts
  src/services/utilities.ts
  tests/cases/fourslash/extract-method-two-type-literals.ts
Labels: Author: Team, For Milestone Bug

#44271 Issue "Cannot find name did-you-mean" errors as suggestions in plain JS
  src/compiler/builder.ts
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/program.ts
  src/services/codefixes/fixSpelling.ts
  tests/baselines/reference/argumentsReferenceInConstructor3_Js.types
  tests/baselines/reference/jsObjectsMarkedAsOpenEnded.types
  tests/baselines/reference/spellingUncheckedJS.symbols
  tests/baselines/reference/spellingUncheckedJS.types
  tests/cases/conformance/salsa/spellingUncheckedJS.ts
  tests/cases/fourslash/codeFixSpellingJs1.ts
  tests/cases/fourslash/codeFixSpellingJs2.ts
  tests/cases/fourslash/codeFixSpellingJs3.ts
  tests/cases/fourslash/codeFixSpellingJs4.ts
  tests/cases/fourslash/codeFixSpellingJs5.ts
  tests/cases/fourslash/codeFixSpellingJs6.ts
  tests/cases/fourslash/codeFixSpellingJs7.ts
  tests/cases/fourslash/codeFixSpellingJs8.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_delete_templateTag.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_jsdocTypeParameter.ts
  tests/cases/fourslash/convertToEs6Class_emptyCatchClause.ts
Labels: Author: Team, For Milestone Bug

#44409 Update descriptions for all compiler options
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/tsConfig/Default initialized TSConfig/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with advanced options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with boolean value compiler options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with enum value compiler options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with files options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with incorrect compiler option value/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with incorrect compiler option/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with list compiler options with enum value/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with list compiler options/tsconfig.json
  tests/baselines/reference/tsc/runWithoutArgs/initial-build/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/declarationDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/when-outDir-and-declarationDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/when-outDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/with-outFile.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/without-outDir-or-outFile-is-specified-with-declaration-enabled.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/without-outDir-or-outFile-is-specified.js
Labels: Author: Team, For Uncommitted Bug

#44582 [release-3.9] Pass throwIfNoEntry to fs.statSync
  src/compiler/sys.ts
  src/tsserver/server.ts
Labels: For Uncommitted Bug

#44583 [release-4.0] Pass throwIfNoEntry to fs.statSync
  src/compiler/sys.ts
  src/tsserver/server.ts
Labels: For Uncommitted Bug

#44584 [release-4.1] Pass throwIfNoEntry to fs.statSync
  src/compiler/sys.ts
  src/tsserver/server.ts
Labels: For Uncommitted Bug

#44595 Fixes to inference and mapped types in --strictOptionalProperties mode
  src/compiler/checker.ts
  tests/baselines/reference/inferenceOptionalProperties.js
  tests/baselines/reference/inferenceOptionalProperties.symbols
  tests/baselines/reference/inferenceOptionalProperties.types
  tests/baselines/reference/inferenceOptionalPropertiesStrict.js
  tests/baselines/reference/inferenceOptionalPropertiesStrict.symbols
  tests/baselines/reference/inferenceOptionalPropertiesStrict.types
  tests/baselines/reference/inferenceOptionalPropertiesToIndexSignatures.types
  tests/cases/compiler/inferenceOptionalProperties.ts
  tests/cases/compiler/inferenceOptionalPropertiesStrict.ts
Labels: Author: Team, For Uncommitted Bug

#44608 Backport package-lock infra changes to 3.9
  .github/workflows/new-release-branch.yaml
  .github/workflows/release-branch-artifact.yaml
  .github/workflows/set-version.yaml
  .github/workflows/sync-branch.yaml
  .github/workflows/update-lkg.yml
  Dockerfile
  README.md
Labels: For Milestone Bug

#43344 Fix late bound method name assignment, added tests
  src/compiler/binder.ts
  src/compiler/checker.ts
  tests/baselines/reference/lateBoundMethodNameAssigmentJS.js
  tests/baselines/reference/lateBoundMethodNameAssigmentJS.symbols
  tests/baselines/reference/lateBoundMethodNameAssigmentJS.types
  tests/cases/compiler/lateBoundMethodNameAssigmentJS.ts
Labels: For Milestone Bug

#44615 Skip base type checks that can cause circularities
  src/compiler/checker.ts
  tests/baselines/reference/recursiveClassBaseType.js
  tests/baselines/reference/recursiveClassBaseType.symbols
  tests/baselines/reference/recursiveClassBaseType.types
  tests/cases/compiler/recursiveClassBaseType.ts
Labels: Author: Team, For Milestone Bug

#44329 support JSDoc comments inherited for parameter properties
  src/services/services.ts
  tests/baselines/reference/quickInfoOnParameterProperties.baseline
  tests/cases/fourslash/quickInfoOnParameterProperties.ts
Labels: For Backlog Bug

#44609 Don't attach declarations to symbols in mapped types with 'as XXX' clauses
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypeAsStringTemplate.errors.txt
  tests/baselines/reference/mappedTypeAsStringTemplate.js
  tests/baselines/reference/mappedTypeAsStringTemplate.symbols
  tests/baselines/reference/mappedTypeAsStringTemplate.types
  tests/cases/compiler/mappedTypeAsStringTemplate.ts
Labels: Author: Team, For Milestone Bug

#44496 [release-4.3] Add SolutionBuilderHostBase.getCustomTransformers to be used when emitting.
  src/compiler/tsbuildPublic.ts
  src/testRunner/tsconfig.json
  src/testRunner/unittests/tsbuildWatch/publicApi.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/tsbuild/watchMode/publicApi/with-custom-transformers.js
Labels: Author: Team, For Uncommitted Bug

#44621 Slightly more conservative check in isConstraintPosition function
  src/compiler/checker.ts
  tests/baselines/reference/controlFlowGenericTypes.errors.txt
  tests/baselines/reference/controlFlowGenericTypes.js
  tests/baselines/reference/controlFlowGenericTypes.symbols
  tests/baselines/reference/controlFlowGenericTypes.types
  tests/cases/conformance/controlFlow/controlFlowGenericTypes.ts
Labels: Author: Team, For Milestone Bug

#43898 allow `this` in typeQuery
  src/compiler/checker.ts
  src/compiler/utilities.ts
  tests/baselines/reference/initializerReferencingConstructorLocals.errors.txt
  tests/baselines/reference/initializerReferencingConstructorParameters.errors.txt
  tests/baselines/reference/initializerReferencingConstructorParameters.js
  tests/baselines/reference/initializerReferencingConstructorParameters.symbols
  tests/baselines/reference/initializerReferencingConstructorParameters.types
  tests/baselines/reference/typeofThis.errors.txt
  tests/baselines/reference/typeofThis.js
  tests/baselines/reference/typeofThis.symbols
  tests/baselines/reference/typeofThis.types
  tests/baselines/reference/typeofThisWithImplicitThis.js
  tests/baselines/reference/typeofThisWithImplicitThis.symbols
  tests/baselines/reference/typeofThisWithImplicitThis.types
  tests/cases/conformance/classes/propertyMemberDeclarations/initializerReferencingConstructorParameters.ts
  tests/cases/conformance/types/specifyingTypes/typeQueries/typeofThis.ts
  tests/cases/conformance/types/specifyingTypes/typeQueries/typeofThisWithImplicitThis.ts
Labels: For Backlog Bug

#44402 Make export-module and reference maps invertible
  src/compiler/builder.ts
  src/compiler/builderState.ts
  src/testRunner/unittests/tscWatch/incremental.ts
Labels: Author: Team, For Uncommitted Bug

#44576 feat(28491): add QF to declare missing properties
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/types.ts
  src/services/codefixes/fixAddMissingMember.ts
  src/services/codefixes/helpers.ts
  tests/cases/fourslash/codeFixAddMissingProperties1.ts
  tests/cases/fourslash/codeFixAddMissingProperties10.ts
  tests/cases/fourslash/codeFixAddMissingProperties11.ts
  tests/cases/fourslash/codeFixAddMissingProperties2.ts
  tests/cases/fourslash/codeFixAddMissingProperties3.ts
  tests/cases/fourslash/codeFixAddMissingProperties4.ts
  tests/cases/fourslash/codeFixAddMissingProperties5.ts
  tests/cases/fourslash/codeFixAddMissingProperties6.ts
  tests/cases/fourslash/codeFixAddMissingProperties7.ts
  tests/cases/fourslash/codeFixAddMissingProperties8.ts
  tests/cases/fourslash/codeFixAddMissingProperties9.ts
  tests/cases/fourslash/codeFixAddMissingProperties_all.ts
Labels: For Uncommitted Bug

#44622 `services/utilities/getMeaningFromLocation()`: fix w/ export specifiers
  src/harness/fourslashInterfaceImpl.ts
  src/services/utilities.ts
  tests/cases/fourslash/documentHighlightInTypeExport.ts
  tests/cases/fourslash/fourslash.ts
Labels: Author: Team, For Uncommitted Bug

#44651 Make files safe for Windows
  src/testRunner/unittests/tscWatch/emitAndErrorUpdates.ts
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependencies/deepImportChanges/errors-for-.d.ts-change.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependencies/deepImportChanges/errors-for-.ts-change.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependencies/transitive-exports/no-circular-import/export.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependencies/transitive-exports/yes-circular-import/exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependenciesAndD/deepImportChanges/errors-for-.d.ts-change.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependenciesAndD/deepImportChanges/errors-for-.ts-change.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependenciesAndD/transitive-exports/no-circular-import/export.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependenciesAndD/transitive-exports/yes-circular-import/exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/default/deepImportChanges/errors-for-.d.ts-change.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/default/deepImportChanges/errors-for-.ts-change.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/default/transitive-exports/no-circular-import/export.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/default/transitive-exports/yes-circular-import/exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/defaultAndD/deepImportChanges/errors-for-.d.ts-change.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/defaultAndD/deepImportChanges/errors-for-.ts-change.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/defaultAndD/transitive-exports/no-circular-import/export.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/defaultAndD/transitive-exports/yes-circular-import/exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/assumeChangesOnlyAffectDirectDependencies/deepImportChanges/errors-for-.d.ts-change.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/assumeChangesOnlyAffectDirectDependencies/deepImportChanges/errors-for-.ts-change.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/assumeChangesOnlyAffectDirectDependencies/transitive-exports/no-circular-import/export.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/assumeChangesOnlyAffectDirectDependencies/transitive-exports/yes-circular-import/exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/assumeChangesOnlyAffectDirectDependenciesAndD/deepImportChanges/errors-for-.d.ts-change.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/assumeChangesOnlyAffectDirectDependenciesAndD/deepImportChanges/errors-for-.ts-change.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/assumeChangesOnlyAffectDirectDependenciesAndD/transitive-exports/no-circular-import/export.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/assumeChangesOnlyAffectDirectDependenciesAndD/transitive-exports/yes-circular-import/exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/default/deepImportChanges/errors-for-.d.ts-change.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/default/deepImportChanges/errors-for-.ts-change.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/default/transitive-exports/no-circular-import/export.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/default/transitive-exports/yes-circular-import/exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/defaultAndD/deepImportChanges/errors-for-.d.ts-change.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/defaultAndD/deepImportChanges/errors-for-.ts-change.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/defaultAndD/transitive-exports/no-circular-import/export.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/defaultAndD/transitive-exports/yes-circular-import/exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/isolatedModules/deepImportChanges/errors-for-.d.ts-change.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/isolatedModules/deepImportChanges/errors-for-.ts-change.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/isolatedModules/transitive-exports/no-circular-import/export.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/isolatedModules/transitive-exports/yes-circular-import/exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/isolatedModulesAndD/deepImportChanges/errors-for-.d.ts-change.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/isolatedModulesAndD/deepImportChanges/errors-for-.ts-change.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/isolatedModulesAndD/transitive-exports/no-circular-import/export.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/isolatedModulesAndD/transitive-exports/yes-circular-import/exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModules/deepImportChanges/errors-for-.d.ts-change.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModules/deepImportChanges/errors-for-.ts-change.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModules/transitive-exports/no-circular-import/export.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModules/transitive-exports/yes-circular-import/exports.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModulesAndD/deepImportChanges/errors-for-.d.ts-change.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModulesAndD/deepImportChanges/errors-for-.ts-change.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModulesAndD/transitive-exports/no-circular-import/export.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModulesAndD/transitive-exports/yes-circular-import/exports.js
  tests/baselines/reference/typeOfThis.symbols
  tests/baselines/reference/typeOfThisGeneral.errors.txt
  tests/baselines/reference/typeOfThisGeneral.js
  tests/baselines/reference/typeOfThisGeneral.symbols
  tests/baselines/reference/typeOfThisGeneral.types
  tests/baselines/reference/typeofThis.types
  tests/cases/conformance/expressions/thisKeyword/typeOfThisGeneral.ts
Labels: Author: Team, For Uncommitted Bug

#44652 Forbid duplicates in baselines
  src/testRunner/runner.ts
  tests/baselines/reference/abstractProperty.symbols
  tests/baselines/reference/abstractPropertyBasics.js
  tests/baselines/reference/abstractPropertyBasics.symbols
  tests/baselines/reference/abstractPropertyBasics.types
  tests/cases/compiler/abstractPropertyBasics.ts
  tests/cases/fourslash/augmentedTypesClass3Fourslash.ts
  tests/cases/fourslash/codeFixUnusedInterfaceInNamespace1.ts
  tests/cases/fourslash/codeFixUnusedInterfaceInNamespace2.ts
  tests/cases/fourslash/codeFixUnusedNamespaceInNamespace.ts
  tests/cases/fourslash/commentsEnumsFourslash.ts
  tests/cases/fourslash/commentsExternalModulesFourslash.ts
  tests/cases/fourslash/commentsInheritanceFourslash.ts
  tests/cases/fourslash/commentsInterfaceFourslash.ts
  tests/cases/fourslash/commentsModulesFourslash.ts
  tests/cases/fourslash/commentsMultiModuleMultiFileFourslash.ts
  tests/cases/fourslash/commentsMultiModuleSingleFileFourslash.ts
  tests/cases/fourslash/commentsOverloadsFourslash.ts
  tests/cases/fourslash/completionsAugmentedTypesClass2.ts
  tests/cases/fourslash/completionsExternalModuleReferenceResolutionOrderInImportDeclaration.ts
  tests/cases/fourslash/completionsGenericTypeWithMultipleBases1.ts
  tests/cases/fourslash/completionsMergedDeclarations1.ts
  tests/cases/fourslash/completionsMergedDeclarations2.ts
  tests/cases/fourslash/contextualTypingOfArrayLiterals.ts
  tests/cases/fourslash/diagnosticsJsFileCompilationDuplicateFunctionImplementation.ts
  tests/cases/fourslash/multiModuleClodule.ts
  tests/cases/fourslash/multiModuleFundule.ts
  tests/cases/fourslash/quickInfoAssignToExistingClass.ts
  tests/cases/fourslash/quickInfoCloduleWithRecursiveReference.ts
  tests/cases/fourslash/quickInfoContextualTyping.ts
  tests/cases/fourslash/quickInfoExtendArray.ts
  tests/cases/fourslash/quickInfoForIn.ts
  tests/cases/fourslash/quickInfoGenericCombinators2.ts
  tests/cases/fourslash/quickInfoGenericTypeArgumentInference1.ts
  tests/cases/fourslash/quickInfoModuleVariables.ts
  tests/cases/fourslash/quickInfoNamedTupleMembers.ts
  tests/cases/fourslash/quickInfoRecursiveObjectLiteral.ts
  tests/cases/fourslash/quickInfoStaticPrototypePropertyOnClass.ts
  tests/cases/fourslash/quickInfoTypeOfThisInStatics.ts
  tests/cases/fourslash/quickInfoTypedGenericPrototypeMember.ts
  tests/cases/fourslash/quickInfoUntypedModuleImport.ts
  tests/cases/fourslash/quickInfoWidenedTypes.ts
Labels: Author: Team, For Uncommitted Bug

#44291 Allows plugin to register commands
  src/server/editorServices.ts
  src/server/project.ts
  src/server/session.ts
  src/testRunner/unittests/tsserver/helpers.ts
  src/testRunner/unittests/tsserver/plugins.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
Labels: For Uncommitted Bug

#44378 fix(44377): Compiler error : TypeError: Cannot read property 'kind' of undefined
  src/compiler/transformers/ts.ts
  tests/baselines/reference/labeledStatementWithLabel.js
  tests/baselines/reference/labeledStatementWithLabel_es2015.js
  tests/baselines/reference/labeledStatementWithLabel_strict.js
  tests/baselines/reference/typeAliasDeclarationEmit3.js
  tests/baselines/reference/typeAliasDeclarationEmit3.symbols
  tests/baselines/reference/typeAliasDeclarationEmit3.types
  tests/cases/compiler/typeAliasDeclarationEmit3.ts
Labels: For Backlog Bug

#44490 fix(44465): Remove unused declaration code fix will remove preceeding statements on same line
  src/services/textChanges.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_singleLineStatements1.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_singleLineStatements2.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_singleLineStatements3.ts
Labels: For Backlog Bug

#44655 fix(44637): TypeScript formatter doesn't format export= properly
  src/services/formatting/rules.ts
  tests/cases/fourslash/formatExportAssignment.ts
Labels: For Backlog Bug

#44484 `getEditsForFileRename`: fix `updateTsconfigFiles` w/ empty `include`
  src/services/getEditsForFileRename.ts
  tests/cases/fourslash/getEditsForFileRename_tsconfig_empty_include.ts
Labels: Author: Team, For Milestone Bug

#44677 fix(44676): fix constToLetQuickFix selection range
  src/services/codefixes/convertConstToLet.ts
  tests/cases/fourslash/codeFixConstToLet.ts
  tests/cases/fourslash/codeFixConstToLet1.ts
  tests/cases/fourslash/codeFixConstToLet2.ts
  tests/cases/fourslash/codeFixConstToLet3.ts
Labels: For Uncommitted Bug

#44671 Report exact position of invalid characters in scanner
  src/compiler/scanner.ts
  tests/baselines/reference/MemberFunctionDeclaration8_es6.errors.txt
  tests/baselines/reference/emitBOM.js
  tests/baselines/reference/parseErrorInHeritageClause1.errors.txt
  tests/baselines/reference/parserErrorRecovery_Block2.errors.txt
  tests/baselines/reference/parserErrorRecovery_ClassElement3.errors.txt
  tests/baselines/reference/parserErrorRecovery_ParameterList4.errors.txt
  tests/baselines/reference/parserSkippedTokens16.errors.txt
  tests/baselines/reference/scannerUnexpectedNullCharacter1.errors.txt
  tests/baselines/reference/unicodeIdentifierName2.errors.txt
Labels: For Backlog Bug

#44687 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210621224857864 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#44393 Fix 'arguments' check in class field initializer or static initialization block
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/argumentsUsedInClassFieldInitializerOrStaticInitializationBlock.errors.txt
  tests/baselines/reference/argumentsUsedInClassFieldInitializerOrStaticInitializationBlock.js
  tests/baselines/reference/argumentsUsedInClassFieldInitializerOrStaticInitializationBlock.symbols
  tests/baselines/reference/argumentsUsedInClassFieldInitializerOrStaticInitializationBlock.types
  tests/cases/compiler/argumentsUsedInClassFieldInitializerOrStaticInitializationBlock.ts
Labels: For Backlog Bug

#44680 Improve parsing in await and yield context
  src/compiler/parser.ts
  tests/baselines/reference/asyncOrYieldAsBindingIdentifier1.errors.txt
  tests/baselines/reference/asyncOrYieldAsBindingIdentifier1.js
  tests/baselines/reference/asyncOrYieldAsBindingIdentifier1.symbols
  tests/baselines/reference/asyncOrYieldAsBindingIdentifier1.types
  tests/cases/conformance/async/es6/functionDeclarations/asyncOrYieldAsBindingIdentifier1.ts
Labels: For Backlog Bug

#44696 Fix check for overwritten properties in object spreads
  src/compiler/checker.ts
  tests/baselines/reference/spreadDuplicate.errors.txt
  tests/baselines/reference/spreadDuplicate.js
  tests/baselines/reference/spreadDuplicate.symbols
  tests/baselines/reference/spreadDuplicate.types
  tests/baselines/reference/spreadDuplicateExact.errors.txt
  tests/baselines/reference/spreadDuplicateExact.js
  tests/baselines/reference/spreadDuplicateExact.symbols
  tests/baselines/reference/spreadDuplicateExact.types
  tests/baselines/reference/spreadOverwritesPropertyStrict.errors.txt
  tests/cases/conformance/types/spread/spreadDuplicate.ts
  tests/cases/conformance/types/spread/spreadDuplicateExact.ts
Labels: Author: Team, For Milestone Bug

#44703 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210622231816174 to main
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#44690 json modules should not treated as affecting global scope
  src/compiler/builderState.ts
  tests/baselines/reference/tsbuild/javascriptProjectEmit/initial-build/loads-js-based-projects-with-non-moved-json-files-and-emits-them-correctly.js
  tests/baselines/reference/tsbuild/resolveJsonModule/initial-build/files-containing-json-file.js
  tests/baselines/reference/tsbuild/resolveJsonModule/initial-build/importing-json-module-from-project-reference.js
  tests/baselines/reference/tsbuild/resolveJsonModule/initial-build/include-and-files.js
  tests/baselines/reference/tsbuild/resolveJsonModule/initial-build/include-of-json-along-with-other-include-and-file-name-matches-ts-file.js
  tests/baselines/reference/tsbuild/resolveJsonModule/initial-build/include-of-json-along-with-other-include.js
  tests/baselines/reference/tsbuild/resolveJsonModule/initial-build/include-only.js
  tests/baselines/reference/tsbuild/resolveJsonModule/initial-build/sourcemap.js
  tests/baselines/reference/tsbuild/resolveJsonModule/initial-build/without-outDir.js
  tests/baselines/reference/tscWatch/programUpdates/updates-moduleResolution-when-resolveJsonModule-changes.js
Labels: For Uncommitted Bug

#44707 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210623171316573 to main
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#44569 regard TemplateLiteral as discriminant property
  src/compiler/checker.ts
  tests/baselines/reference/discriminatedUnionTypes3.js
  tests/baselines/reference/discriminatedUnionTypes3.symbols
  tests/baselines/reference/discriminatedUnionTypes3.types
  tests/cases/conformance/types/union/discriminatedUnionTypes3.ts
Labels: For Backlog Bug

#44714 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210623231301074 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#43677 Skip typedef in services getJSDocTags
  src/services/jsDoc.ts
  tests/baselines/reference/quickInfoTypedefTag.baseline
  tests/cases/fourslash/quickInfoTypedefTag.ts
Labels: Author: Team, For Milestone Bug

#44728 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210624171255906 to main
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#44724 Fix auto imports in opening JSX tag
  src/services/completions.ts
  tests/cases/fourslash/completionsImportFromJSXTag.ts
Labels: Author: Team, For Milestone Bug

#44737 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210624231300864 to main
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#44730 Control flow analysis of aliased conditional expressions and discriminants
  src/compiler/checker.ts
  tests/baselines/reference/controlFlowAliasing.errors.txt
  tests/baselines/reference/controlFlowAliasing.js
  tests/baselines/reference/controlFlowAliasing.symbols
  tests/baselines/reference/controlFlowAliasing.types
  tests/baselines/reference/controlFlowCommaExpressionAssertionWithinTernary.types
  tests/baselines/reference/logicalAndOperatorStrictMode.types
  tests/baselines/reference/logicalAndOperatorWithEveryType.types
  tests/baselines/reference/voidIsInitialized.types
  tests/cases/conformance/controlFlow/controlFlowAliasing.ts
Labels: Author: Team, For Uncommitted Bug

#44684 Migrate latest dom types into libdom.d.ts
  src/lib/dom.generated.d.ts
  src/lib/dom.iterable.generated.d.ts
  tests/baselines/reference/customEventDetail.types
  tests/baselines/reference/elaboratedErrors.symbols
  tests/baselines/reference/globalThisBlockscopedProperties.types
  tests/baselines/reference/importMeta(module=commonjs,target=es5).types
  tests/baselines/reference/importMeta(module=commonjs,target=esnext).types
  tests/baselines/reference/importMeta(module=es2020,target=es5).types
  tests/baselines/reference/importMeta(module=es2020,target=esnext).types
  tests/baselines/reference/importMeta(module=esnext,target=es5).types
  tests/baselines/reference/importMeta(module=esnext,target=esnext).types
  tests/baselines/reference/importMeta(module=system,target=es5).types
  tests/baselines/reference/importMeta(module=system,target=esnext).types
  tests/baselines/reference/intersectionsOfLargeUnions.types
  tests/baselines/reference/intersectionsOfLargeUnions2.errors.txt
  tests/baselines/reference/intersectionsOfLargeUnions2.types
  tests/baselines/reference/mappedTypeRecursiveInference.errors.txt
  tests/baselines/reference/mappedTypeRecursiveInference.types
  tests/baselines/reference/truthinessCallExpressionCoercion2.errors.txt
  tests/baselines/reference/truthinessCallExpressionCoercion2.js
  tests/baselines/reference/truthinessCallExpressionCoercion2.symbols
  tests/baselines/reference/truthinessCallExpressionCoercion2.types
  tests/cases/compiler/truthinessCallExpressionCoercion2.ts
Labels: Author: Team, For Uncommitted Bug

#44739 fix(44738): build-eslint-rules failed after setup
  package-lock.json
  package.json
  scripts/eslint/rules/boolean-trivia.ts
  scripts/eslint/rules/no-double-space.ts
Labels: For Uncommitted Bug

#44713 Resolve module specifiers for auto imports in completion list (in incomplete chunks)
  src/compiler/moduleSpecifiers.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/server/editorServices.ts
  src/server/project.ts
  src/server/protocol.ts
  src/server/session.ts
  src/services/codefixes/importFixes.ts
  src/services/completions.ts
  src/services/services.ts
  src/services/types.ts
  src/services/utilities.ts
  src/testRunner/tsconfig.json
  src/testRunner/unittests/tsserver/completions.ts
  src/testRunner/unittests/tsserver/completionsIncomplete.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/completionsImport_matching.ts
  tests/cases/fourslash/fourslash.ts
Labels: Author: Team, For Milestone Bug

#44752 Forbid duplicate tests only in compiler+fourslash runner
  src/testRunner/runner.ts
Labels: Author: Team, For Uncommitted Bug

#44757 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210626171252278 to main
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#44763 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210626231345229 to main
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#44770 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210627171317118 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#44780 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210628051242962 to main
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#44791 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210628171241707 to main
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#44491 Issue unawaited promise error on symbol-less expressions
  src/compiler/checker.ts
  tests/baselines/reference/truthinessPromiseCoercion.errors.txt
  tests/baselines/reference/truthinessPromiseCoercion.js
  tests/baselines/reference/truthinessPromiseCoercion.symbols
  tests/baselines/reference/truthinessPromiseCoercion.types
  tests/cases/compiler/truthinessPromiseCoercion.ts
Labels: Author: Team, For Uncommitted Bug

#44740 feat(44736): Go-to-def on override should navigate to the overridden method
  src/services/goToDefinition.ts
  tests/cases/fourslash/goToDefinitionOverriddenMember1.ts
  tests/cases/fourslash/goToDefinitionOverriddenMember10.ts
  tests/cases/fourslash/goToDefinitionOverriddenMember11.ts
  tests/cases/fourslash/goToDefinitionOverriddenMember12.ts
  tests/cases/fourslash/goToDefinitionOverriddenMember13.ts
  tests/cases/fourslash/goToDefinitionOverriddenMember14.ts
  tests/cases/fourslash/goToDefinitionOverriddenMember15.ts
  tests/cases/fourslash/goToDefinitionOverriddenMember2.ts
  tests/cases/fourslash/goToDefinitionOverriddenMember3.ts
  tests/cases/fourslash/goToDefinitionOverriddenMember4.ts
  tests/cases/fourslash/goToDefinitionOverriddenMember5.ts
  tests/cases/fourslash/goToDefinitionOverriddenMember6.ts
  tests/cases/fourslash/goToDefinitionOverriddenMember7.ts
  tests/cases/fourslash/goToDefinitionOverriddenMember8.ts
  tests/cases/fourslash/goToDefinitionOverriddenMember9.ts
Labels: For Backlog Bug

#44710 Reduce exceptions
  src/compiler/sys.ts
  src/compiler/utilities.ts
  src/compiler/watchUtilities.ts
  src/harness/fakesHosts.ts
  src/harness/virtualFileSystemWithWatch.ts
Labels: Author: Team, For Uncommitted Bug

#44762 Fix constant reference check in CFA
  src/compiler/checker.ts
  tests/baselines/reference/controlFlowAliasing.errors.txt
  tests/baselines/reference/controlFlowAliasing.js
  tests/baselines/reference/controlFlowAliasing.symbols
  tests/baselines/reference/controlFlowAliasing.types
  tests/cases/conformance/controlFlow/controlFlowAliasing.ts
Labels: Author: Team, For Uncommitted Bug

#44746 Fix bad line number assertion in `ScriptInfo.positionToLineOffset`
  src/server/scriptVersionCache.ts
  src/testRunner/unittests/tsserver/versionCache.ts
Labels: Author: Team, For Milestone Bug

#44801 Fix types in the boolean trivial lint rule
  scripts/eslint/rules/boolean-trivia.ts
Labels: Author: Team, For Uncommitted Bug

#44734 fix(44725): Tagged template literal call incorrectly computes type of this parameter
  src/compiler/checker.ts
  tests/baselines/reference/thisTypeInTaggedTemplateCall.js
  tests/baselines/reference/thisTypeInTaggedTemplateCall.symbols
  tests/baselines/reference/thisTypeInTaggedTemplateCall.types
  tests/cases/conformance/types/thisType/thisTypeInTaggedTemplateCall.ts
Labels: For Backlog Bug

#44815 Validate symbol-named properties against symbol index signatures
  src/compiler/checker.ts
  tests/baselines/reference/indexSignatures1.errors.txt
  tests/baselines/reference/indexSignatures1.js
  tests/baselines/reference/indexSignatures1.symbols
  tests/baselines/reference/indexSignatures1.types
  tests/cases/conformance/types/members/indexSignatures1.ts
Labels: Author: Team, For Milestone Bug

#44570 ensure export modifier is used before default modifier
  src/compiler/checker.ts
  src/compiler/parser.ts
  tests/baselines/reference/classAbstractManyKeywords.errors.txt
  tests/baselines/reference/defaultKeywordWithoutExport1.errors.txt
  tests/baselines/reference/defaultKeywordWithoutExport1.js
  tests/baselines/reference/defaultKeywordWithoutExport1.symbols
  tests/baselines/reference/defaultKeywordWithoutExport1.types
  tests/baselines/reference/defaultKeywordWithoutExport2.errors.txt
  tests/baselines/reference/defaultKeywordWithoutExport2.js
  tests/baselines/reference/defaultKeywordWithoutExport2.symbols
  tests/baselines/reference/defaultKeywordWithoutExport2.types
  tests/cases/compiler/defaultKeywordWithoutExport1.ts
  tests/cases/compiler/defaultKeywordWithoutExport2.ts
Labels: For Backlog Bug

#44827 feat(44799): Allow auto import codefix for shorthand object notation
  src/services/codefixes/importFixes.ts
  tests/cases/fourslash/importNameCodeFix_shorthandPropertyAssignment1.ts
  tests/cases/fourslash/importNameCodeFix_shorthandPropertyAssignment2.ts
Labels: For Backlog Bug
