Repository microsoft/TypeScript, pull requests merged in 2021-02, with the labels that each got.

#42586 Switched 'ts.performance' to a mixed mode only uses native performance APIs when necessary
  src/compiler/performance.ts
  src/compiler/performanceCore.ts
  src/compiler/sys.ts
  src/executeCommandLine/executeCommandLine.ts
Labels: Author: Team, For Uncommitted Bug

#39716 fix 38503.
  src/compiler/transformers/classFields.ts
  tests/baselines/reference/privateNameFieldCallExpression.js
  tests/baselines/reference/privateNameFieldCallExpression.symbols
  tests/baselines/reference/privateNameFieldCallExpression.types
  tests/cases/conformance/classes/members/privateNames/privateNameFieldCallExpression.ts
Labels: For Milestone Bug

#42448 Limit tuple size resulting from spread
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/excessivelyLargeTupleSpread.errors.txt
  tests/baselines/reference/excessivelyLargeTupleSpread.js
  tests/baselines/reference/excessivelyLargeTupleSpread.symbols
  tests/baselines/reference/excessivelyLargeTupleSpread.types
  tests/cases/compiler/excessivelyLargeTupleSpread.ts
Labels: Author: Team, Breaking Change, For Milestone Bug

#42612 Make object literal properties new identifier locations when not contextually typed
  src/services/completions.ts
  tests/cases/fourslash/completionListInObjectLiteral5.ts
  tests/cases/fourslash/completionPropertyShorthandForObjectLiteral.ts
  tests/cases/fourslash/completionPropertyShorthandForObjectLiteral5.ts
  tests/cases/fourslash/completionsGenericUnconstrained.ts
  tests/cases/fourslash/completionsSelfDeclaring2.ts
Labels: Author: Team, For Milestone Bug

#42614 Sort import fixes by number of directory separators
  src/compiler/moduleSpecifiers.ts
  src/compiler/utilities.ts
  src/services/codefixes/importFixes.ts
  tests/cases/fourslash/importNameCodeFix_sortByDistance.ts
Labels: Author: Team, For Uncommitted Bug

#42544 Keep extended config's raw file, include, exclude relative to itself and correct it when setting extending options
  src/compiler/commandLineParser.ts
  src/testRunner/tsconfig.json
  src/testRunner/unittests/tsbuild/configFileExtends.ts
  tests/baselines/reference/tsbuild/configFileExtends/initial-build/when-building-project-uses-reference-and-both-extend-config-with-include.js
  tests/baselines/reference/tsbuild/configFileExtends/initial-build/when-building-solution-with-projects-extends-config-with-include.js
Labels: Author: Team, For Milestone Bug

#42500 Use spaces instead of non-breaking spaces, narrow non-breaking spaces.
  src/lib/es5.d.ts
  src/services/codefixes/helpers.ts
Labels: For Uncommitted Bug

#42536 Strip nullable types from 'this' type in inference with optional chain calls
  src/compiler/checker.ts
  tests/baselines/reference/callChainInference.js
  tests/baselines/reference/callChainInference.symbols
  tests/baselines/reference/callChainInference.types
  tests/cases/conformance/expressions/optionalChaining/callChain/callChainInference.ts
Labels: Author: Team, For Milestone Bug

#41156 fix(39022): If exported variable is renamed, tsc will generate code with a syntax error
  src/compiler/transformers/module/module.ts
  tests/baselines/reference/es6ExportClauseWithAssignmentInEs5.js
  tests/baselines/reference/moduleExportsUnaryExpression.js
  tests/baselines/reference/moduleExportsUnaryExpression.symbols
  tests/baselines/reference/moduleExportsUnaryExpression.types
  tests/cases/compiler/moduleExportsUnaryExpression.ts
Labels: For Milestone Bug

#42583 Fix completions crash on transient exported property named 'default'
  src/harness/fourslashImpl.ts
  src/services/codefixes/importFixes.ts
  src/services/completions.ts
  src/services/utilities.ts
  tests/cases/fourslash/completionsImport_weirdDefaultSynthesis.ts
Labels: Author: Team, For Milestone Bug

#42353 Smarter subtype reduction in union types
  src/compiler/checker.ts
  tests/baselines/reference/callChain.types
  tests/baselines/reference/callChainInference.types
  tests/baselines/reference/controlFlowOptionalChain.errors.txt
  tests/baselines/reference/controlFlowOptionalChain.types
  tests/baselines/reference/controlFlowSuperPropertyAccess.types
  tests/baselines/reference/discriminantPropertyCheck.types
  tests/baselines/reference/promiseTypeStrictNull.types
  tests/baselines/reference/superMethodCall.types
  tests/baselines/reference/thisMethodCall.types
  tests/baselines/reference/truthinessCallExpressionCoercion2.types
  tests/baselines/reference/typeVariableTypeGuards.types
  tests/baselines/reference/unionSubtypeReductionErrors.errors.txt
  tests/baselines/reference/unionSubtypeReductionErrors.types
  tests/baselines/reference/voidReturnIndexUnionInference.types
Labels: Author: Team, Breaking Change, For Uncommitted Bug

#42651 Add check for no match into fs watch rename event handler
  src/compiler/sys.ts
Labels: Author: Team, For Uncommitted Bug

#42649 Replace _all_ tabs in pretty output, not just the first on each line
  src/compiler/program.ts
  tests/baselines/reference/prettyFileWithErrorsAndTabs.errors.txt
  tests/baselines/reference/prettyFileWithErrorsAndTabs.js
  tests/baselines/reference/prettyFileWithErrorsAndTabs.symbols
  tests/baselines/reference/prettyFileWithErrorsAndTabs.types
  tests/cases/compiler/prettyFileWithErrorsAndTabs.ts
Labels: Author: Team, For Uncommitted Bug

#42653 Use a (hopefully) more efficient regex for matching jquery in the safelist
  src/server/editorServices.ts
Labels: Author: Team, For Uncommitted Bug

#42650 Swapping the quote style of a string for completions should swap _all_ quotes in the string
  src/services/utilities.ts
  tests/cases/fourslash/completionForStringLiteral_quotePreference8.ts
Labels: Author: Team, For Uncommitted Bug

#42592 Signature help turns off current-parameter display for non-trailing rest parameters
  src/services/signatureHelp.ts
  src/services/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/signatureHelpLeadingRestTuple.ts
  tests/cases/fourslash/signatureHelpTrailingRestTuple.ts
Labels: Author: Team, For Milestone Bug

#42411 Fix Format Selection on JSDoc comments
  src/services/formatting/formatting.ts
  tests/cases/fourslash/formatSelectionDocCommentInBlock.ts
Labels: Author: Team, For Milestone Bug

#42585 Add fallback error locations for nameless declarations, better class error locations
  src/compiler/transformers/declarations.ts
  tests/baselines/reference/declarationEmitMixinPrivateProtected.errors.txt
  tests/baselines/reference/declarationEmitMixinPrivateProtected.js
  tests/baselines/reference/declarationEmitMixinPrivateProtected.symbols
  tests/baselines/reference/declarationEmitMixinPrivateProtected.types
  tests/baselines/reference/emitClassExpressionInDeclarationFile2.errors.txt
  tests/cases/compiler/declarationEmitMixinPrivateProtected.ts
Labels: Author: Team, For Milestone Bug

#42642 feat(42637): Add setting to disable @return generation for JS Doc comments
  src/harness/client.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/harness/harnessLanguageService.ts
  src/server/protocol.ts
  src/server/session.ts
  src/services/jsDoc.ts
  src/services/services.ts
  src/services/shims.ts
  src/services/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/docCommentTemplateReturnsTag1.ts
  tests/cases/fourslash/docCommentTemplateReturnsTag2.ts
  tests/cases/fourslash/fourslash.ts
Labels: For Uncommitted Bug

#42323 Re-do tracing initialization and tests around calls
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/parser.ts
  src/compiler/program.ts
  src/compiler/tracing.ts
  src/compiler/transformer.ts
  src/compiler/utilities.ts
  src/executeCommandLine/executeCommandLine.ts
  src/server/session.ts
  src/services/services.ts
  src/tsserver/nodeServer.ts
Labels: Author: Team, For Uncommitted Bug

#42697 Use a 10ms sampling frequency to filter tracing dumps
  src/compiler/tracing.ts
Labels: Author: Team, For Uncommitted Bug

#42713 Allow only package names as plugin names
  src/server/project.ts
  src/testRunner/tsconfig.json
  src/testRunner/unittests/tsserver/plugins.ts
Labels: For Milestone Bug

#42652 Refactor params for interface
  src/services/refactors/convertParamsToDestructuredObject.ts
  tests/cases/fourslash/refactorConvertParamsToDestructuredObject_interface.ts
  tests/cases/fourslash/refactorConvertParamsToDestructuredObject_interfaceAssignability.ts
  tests/cases/fourslash/refactorConvertParamsToDestructuredObject_interfaceContextualParams.ts
  tests/cases/fourslash/refactorConvertParamsToDestructuredObject_interfaceMultipleSignatures.ts
  tests/cases/fourslash/refactorConvertParamsToDestructuredObject_interfaceNoIntersection.ts
  tests/cases/fourslash/refactorConvertParamsToDestructuredObject_interfaceNoUnion.ts
  tests/cases/fourslash/refactorConvertParamsToDestructuredObject_typeLiteral.ts
Labels: Author: Team, For Milestone Bug

#42231 Revert assignability cases in getNarrowedType
  src/compiler/checker.ts
  tests/baselines/reference/instanceOfAssignability.types
  tests/baselines/reference/narrowingAssignmentReadonlyRespectsAssertion.js
  tests/baselines/reference/narrowingAssignmentReadonlyRespectsAssertion.symbols
  tests/baselines/reference/narrowingAssignmentReadonlyRespectsAssertion.types
  tests/baselines/reference/typeGuardIntersectionTypes.symbols
  tests/baselines/reference/typeGuardIntersectionTypes.types
  tests/baselines/reference/typeGuardsWithInstanceOf.errors.txt
  tests/baselines/reference/typeGuardsWithInstanceOf.js
  tests/baselines/reference/typeGuardsWithInstanceOf.symbols
  tests/baselines/reference/typeGuardsWithInstanceOf.types
  tests/cases/compiler/narrowingAssignmentReadonlyRespectsAssertion.ts
  tests/cases/conformance/expressions/typeGuards/typeGuardsWithInstanceOf.ts
Labels: Author: Team, For Uncommitted Bug

#42717 Handle if plugin doesnt specify name
  src/server/project.ts
  src/testRunner/unittests/tsserver/plugins.ts
Labels: Author: Team, For Milestone Bug

#42720 [release-4.1] Handle if plugin doesnt specify name
  src/server/project.ts
  src/testRunner/unittests/tsserver/plugins.ts
Labels: Author: Team, For Milestone Bug

#42721 [release-4.0] Plugin without name40
  src/server/project.ts
  src/testRunner/unittests/tsserver/plugins.ts
Labels: Author: Team, For Milestone Bug

#42722 [release-3.9] Handle if plugin doesnt specify name
  src/server/project.ts
  src/testRunner/unittests/tsserver/plugins.ts
Labels: Author: Team, For Milestone Bug

#42723 [release-3.7] Handle if plugin doesnt specify name
  src/server/project.ts
  src/testRunner/unittests/tsserver/plugins.ts
Labels: Author: Team, For Milestone Bug

#42724 [release-3.1] Handle if plugin doesnt specify name
  src/server/project.ts
Labels: Author: Team, For Milestone Bug

#42728 Bump version to 4.3
  package.json
  src/compiler/corePublic.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Uncommitted Bug

#42746 Pin Node version for Volta users (like me)
  package.json
Labels: For Uncommitted Bug

#42737 fix(42714): "Infer function return type" is annoyingly suggested in function bodies
  src/services/refactors/inferFunctionReturnType.ts
  tests/cases/fourslash/refactorInferFunctionReturnType16.ts
  tests/cases/fourslash/refactorInferFunctionReturnType17.ts
  tests/cases/fourslash/refactorInferFunctionReturnType18.ts
  tests/cases/fourslash/refactorInferFunctionReturnType19.ts
  tests/cases/fourslash/refactorInferFunctionReturnType20.ts
  tests/cases/fourslash/refactorInferFunctionReturnType21.ts
  tests/cases/fourslash/refactorKind_rewriteFunction.ts
Labels: For Milestone Bug

#42710 Refactor the tracing namespace organization
  src/compiler/tracing.ts
  src/executeCommandLine/executeCommandLine.ts
  src/tsserver/nodeServer.ts
Labels: Author: Team, For Uncommitted Bug

#42459 Improve error message for overload that takes spread arguments
  src/compiler/checker.ts
  tests/baselines/reference/functionParameterArityMismatch.errors.txt
  tests/baselines/reference/functionParameterArityMismatch.js
  tests/baselines/reference/functionParameterArityMismatch.symbols
  tests/baselines/reference/functionParameterArityMismatch.types
  tests/cases/compiler/functionParameterArityMismatch.ts
Labels: For Backlog Bug

#42766 Avoid getting undefined `callSignatures`/`constructSignatures` in `getPropertyOfType`
  src/compiler/checker.ts
  tests/baselines/reference/moduleExportsAliasLoop1.errors.txt
  tests/baselines/reference/moduleExportsAliasLoop1.symbols
  tests/baselines/reference/moduleExportsAliasLoop1.types
  tests/baselines/reference/moduleExportsAliasLoop2.errors.txt
  tests/baselines/reference/moduleExportsAliasLoop2.symbols
  tests/baselines/reference/moduleExportsAliasLoop2.types
  tests/cases/conformance/salsa/moduleExportsAliasLoop1.ts
  tests/cases/conformance/salsa/moduleExportsAliasLoop2.ts
Labels: Author: Team, For Milestone Bug

#42662 fix(42133): undefined[] converted to any[] in js
  src/compiler/checker.ts
  tests/baselines/reference/typeFromJSInitializer.errors.txt
  tests/baselines/reference/typeFromJSInitializer.symbols
  tests/baselines/reference/typeFromJSInitializer.types
  tests/cases/conformance/salsa/typeFromJSInitializer.ts
Labels: For Milestone Bug

#42763 feat(42735): add single line comments to selection ranges
  src/services/smartSelection.ts
  tests/baselines/reference/smartSelection_comment1.baseline
  tests/baselines/reference/smartSelection_comment2.baseline
  tests/cases/fourslash/smartSelection_comment1.ts
  tests/cases/fourslash/smartSelection_comment2.ts
Labels: For Uncommitted Bug

#42626 No did-you-mean-to-call error on casts
  src/compiler/checker.ts
  tests/baselines/reference/truthinessCallExpressionCoercion3.js
  tests/baselines/reference/truthinessCallExpressionCoercion3.symbols
  tests/baselines/reference/truthinessCallExpressionCoercion3.types
  tests/cases/compiler/truthinessCallExpressionCoercion3.ts
Labels: Author: Team, For Milestone Bug

#42779 No did-you-mean-to-call error on casts Part 2
  src/compiler/checker.ts
  tests/baselines/reference/truthinessCallExpressionCoercion3.js
  tests/baselines/reference/truthinessCallExpressionCoercion3.symbols
  tests/baselines/reference/truthinessCallExpressionCoercion3.types
  tests/cases/compiler/truthinessCallExpressionCoercion3.ts
Labels: Author: Team, For Uncommitted Bug

#42782 Refactor project references and source map tsserver tests so they are inline for easy editing
  src/harness/virtualFileSystemWithWatch.ts
  src/testRunner/tsconfig.json
  src/testRunner/unittests/tsserver/projectReferences.ts
  src/testRunner/unittests/tsserver/projectReferencesSourcemap.ts
Labels: Author: Team, For Uncommitted Bug

#42532 fix(42519): 'Infer function return type' quick fix generates invalid code for arrow functions without parens
  src/services/refactors/inferFunctionReturnType.ts
  tests/cases/fourslash/refactorInferFunctionReturnType22.ts
  tests/cases/fourslash/refactorInferFunctionReturnType23.ts
Labels: For Backlog Bug

#42701 --inspect can no longer be used as a flag through gulp
  CONTRIBUTING.md
  Gulpfile.js
  scripts/build/options.js
  scripts/build/tests.js
Labels: Author: Team, For Uncommitted Bug

#39175 Add error for missing await in conditionals
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/truthinessPromiseCoercion.errors.txt
  tests/baselines/reference/truthinessPromiseCoercion.js
  tests/baselines/reference/truthinessPromiseCoercion.symbols
  tests/baselines/reference/truthinessPromiseCoercion.types
  tests/cases/compiler/truthinessPromiseCoercion.ts
  tests/cases/fourslash/codeFixAddMissingAwait_condition.ts
Labels: For Uncommitted Bug

#41950 Fix import fix on react or react dev
  src/services/codefixes/fixCannotFindModule.ts
  src/services/codefixes/importFixes.ts
  tests/cases/fourslash/codeFixAddMissingImportForReactJsx1.ts
  tests/cases/fourslash/codeFixAddMissingImportForReactJsx2.ts
Labels: For Backlog Bug

#42041 Add a basic dev container
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  CONTRIBUTING.md
Labels: For Uncommitted Bug, Housekeeping

#42826 Ignore .devcontainer for npm publishes
  .npmignore
Labels: For Uncommitted Bug

#39661 fix: fix RelativeTimeFormat type definition
  src/lib/es2020.intl.d.ts
Labels: For Backlog Bug

#38726 fix(37578): Deprecate variable name AllowQualifedNameInPlaceOfIdentifier
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Uncommitted Bug

#42770 Expand extractSymbol ranges
  src/services/refactors/extractSymbol.ts
  src/testRunner/unittests/services/extract/ranges.ts
  tests/cases/fourslash/extractSymbolForTriggerReason1.ts
  tests/cases/fourslash/extractSymbolForTriggerReason2.ts
Labels: Author: Team, For Milestone Bug

#42846 Reduce void | undefined only in conjunction with subtype reduction
  src/compiler/checker.ts
  tests/baselines/reference/callChain.types
  tests/baselines/reference/callChainInference.types
  tests/baselines/reference/controlFlowOptionalChain.types
  tests/baselines/reference/controlFlowSuperPropertyAccess.types
  tests/baselines/reference/discriminantPropertyCheck.types
  tests/baselines/reference/promiseTypeStrictNull.types
  tests/baselines/reference/superMethodCall.types
  tests/baselines/reference/thisMethodCall.types
  tests/baselines/reference/truthinessCallExpressionCoercion2.types
  tests/baselines/reference/typeVariableTypeGuards.types
  tests/baselines/reference/voidReturnIndexUnionInference.types
  tests/baselines/reference/voidUndefinedReduction.js
  tests/baselines/reference/voidUndefinedReduction.symbols
  tests/baselines/reference/voidUndefinedReduction.types
  tests/cases/compiler/voidUndefinedReduction.ts
Labels: Author: Team, For Uncommitted Bug

#42017 Check for missing type parameter names in JSDoc template tags
  src/compiler/parser.ts
  src/testRunner/unittests/jsDocParsing.ts
  tests/baselines/reference/jsdocTemplateTag3.types
Labels: Author: Team, For Backlog Bug

#42029 Provide completion for partial expression on closing jsx tags
  src/services/completions.ts
  tests/cases/fourslash/tsxCompletion15.ts
Labels: For Backlog Bug

#41947 fix(41740): TypeScript server crashes when renaming function parameter erroneously named as reserved word "default"
  src/services/findAllReferences.ts
  tests/baselines/reference/findAllRefsForDefaultKeyword.baseline.jsonc
  tests/cases/fourslash/findAllRefsForDefaultKeyword.ts
  tests/cases/fourslash/renameDefaultKeyword.ts
Labels: For Milestone Bug

#40070 Specified diagnostic for iterating known array type without --downlevelIteration
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/typedArrays-es5.errors.txt
  tests/baselines/reference/typedArrays-es5.js
  tests/baselines/reference/typedArrays-es5.symbols
  tests/baselines/reference/typedArrays-es5.types
  tests/baselines/reference/typedArrays-es6.js
  tests/baselines/reference/typedArrays-es6.symbols
  tests/baselines/reference/typedArrays-es6.types
  tests/cases/compiler/typedArrays-es5.ts
  tests/cases/compiler/typedArrays-es6.ts
Labels: For Backlog Bug

#42851 Improve @template lookup and resilience
  src/compiler/checker.ts
  tests/baselines/reference/jsdocOuterTypeParameters1.errors.txt
  tests/baselines/reference/jsdocOuterTypeParameters1.symbols
  tests/baselines/reference/jsdocOuterTypeParameters1.types
  tests/baselines/reference/jsdocOuterTypeParameters2.errors.txt
  tests/baselines/reference/jsdocOuterTypeParameters2.symbols
  tests/baselines/reference/jsdocOuterTypeParameters2.types
  tests/baselines/reference/jsdocOuterTypeParameters3.errors.txt
  tests/baselines/reference/jsdocOuterTypeParameters3.symbols
  tests/baselines/reference/jsdocOuterTypeParameters3.types
  tests/cases/conformance/jsdoc/jsdocOuterTypeParameters1.ts
  tests/cases/conformance/jsdoc/jsdocOuterTypeParameters2.ts
  tests/cases/conformance/jsdoc/jsdocOuterTypeParameters3.ts
Labels: Author: Team, For Milestone Bug

#42850 Fix duplicate auto-import completions
  src/compiler/utilities.ts
  src/harness/fourslashImpl.ts
  src/services/codefixes/convertToTypeOnlyExport.ts
  src/services/codefixes/fixAwaitInSyncFunction.ts
  src/services/codefixes/fixClassDoesntImplementInheritedAbstractMember.ts
  src/services/codefixes/fixClassIncorrectlyImplementsInterface.ts
  src/services/codefixes/fixClassSuperMustPrecedeThisAccess.ts
  src/services/completions.ts
  src/services/findAllReferences.ts
  src/services/textChanges.ts
  tests/cases/fourslash/completionsImport_reExportDefault.ts
Labels: Author: Team, For Uncommitted Bug

#42855 typo
  src/server/scriptInfo.ts
Labels: For Uncommitted Bug

#42861 Fix for crash on call expression with private identifiers.
  src/compiler/checker.ts
  tests/baselines/reference/privateNameAndAny.errors.txt
  tests/baselines/reference/privateNameAndAny.js
  tests/baselines/reference/privateNameAndAny.symbols
  tests/baselines/reference/privateNameAndAny.types
  tests/cases/conformance/classes/members/privateNames/privateNameAndAny.ts
Labels: For Milestone Bug

#42675 Improve error messages for computed class property names
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/awaitAndYieldInProperty.errors.txt
  tests/baselines/reference/capturedParametersInInitializers2.errors.txt
  tests/baselines/reference/computedPropertyNames12_ES5.errors.txt
  tests/baselines/reference/computedPropertyNames12_ES6.errors.txt
  tests/baselines/reference/decoratorsOnComputedProperties.errors.txt
  tests/baselines/reference/indexSignatureMustHaveTypeAnnotation.errors.txt
  tests/baselines/reference/indexSignatureWithInitializer.errors.txt
  tests/baselines/reference/indexWithoutParamType2.errors.txt
  tests/baselines/reference/parserComputedPropertyName10.errors.txt
  tests/baselines/reference/parserComputedPropertyName22.errors.txt
  tests/baselines/reference/parserComputedPropertyName25.errors.txt
  tests/baselines/reference/parserComputedPropertyName28.errors.txt
  tests/baselines/reference/parserComputedPropertyName29.errors.txt
  tests/baselines/reference/parserComputedPropertyName31.errors.txt
  tests/baselines/reference/parserComputedPropertyName36.errors.txt
  tests/baselines/reference/parserComputedPropertyName7.errors.txt
  tests/baselines/reference/parserComputedPropertyName8.errors.txt
  tests/baselines/reference/parserComputedPropertyName9.errors.txt
  tests/baselines/reference/parserES5ComputedPropertyName1.errors.txt
  tests/baselines/reference/parserES5ComputedPropertyName10.errors.txt
  tests/baselines/reference/parserES5ComputedPropertyName7.errors.txt
  tests/baselines/reference/parserES5ComputedPropertyName9.errors.txt
  tests/baselines/reference/symbolProperty7.errors.txt
Labels: For Uncommitted Bug

#42274 feat(lib/es2021): Add type parameter to `FinalizationRegistry`
  src/lib/esnext.weakref.d.ts
  tests/baselines/reference/esNextWeakRefs_IterableWeakMap.js
  tests/baselines/reference/esNextWeakRefs_IterableWeakMap.symbols
  tests/baselines/reference/esNextWeakRefs_IterableWeakMap.types
  tests/cases/compiler/esNextWeakRefs_IterableWeakMap.ts
Labels: For Uncommitted Bug

#42554 fix(42368): Spread syntax is always converted to Object.assign for ES2018 and up
  src/compiler/transformers/jsx.ts
  tests/baselines/reference/tsxEmitSpreadAttribute(target=es2015).js
  tests/baselines/reference/tsxEmitSpreadAttribute(target=es2015).symbols
  tests/baselines/reference/tsxEmitSpreadAttribute(target=es2015).types
  tests/baselines/reference/tsxEmitSpreadAttribute(target=es2018).js
  tests/baselines/reference/tsxEmitSpreadAttribute(target=es2018).symbols
  tests/baselines/reference/tsxEmitSpreadAttribute(target=es2018).types
  tests/baselines/reference/tsxEmitSpreadAttribute(target=esnext).js
  tests/baselines/reference/tsxEmitSpreadAttribute(target=esnext).symbols
  tests/baselines/reference/tsxEmitSpreadAttribute(target=esnext).types
  tests/cases/conformance/jsx/tsxEmitSpreadAttribute.ts
Labels: For Backlog Bug

#42841 Update npm in user tests
  .gitignore
  tests/baselines/reference/user/npm.log
  tests/cases/user/npm/index.ts
  tests/cases/user/npm/package.json
  tests/cases/user/npm/test.json
  tests/cases/user/npm/tsconfig.json
Labels: Author: Team, For Uncommitted Bug, Housekeeping

#42865 improve isRequireVariableDeclaration parameters
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/utilities.ts
  src/services/codefixes/importFixes.ts
  src/services/goToDefinition.ts
  src/services/importTracker.ts
Labels: Author: Team, For Uncommitted Bug

#42886 Make 'calendar' and 'numberingSystem' open strings in es2020.intl.
  src/lib/es2020.intl.d.ts
Labels: For Milestone Bug

#42620 Combine multiple overloads into a single contextual signature
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/callsOnComplexSignatures.errors.txt
  tests/baselines/reference/callsOnComplexSignatures.types
  tests/baselines/reference/circularlySimplifyingConditionalTypesNoCrash.types
  tests/baselines/reference/contextualOverloadListFromArrayUnion.js
  tests/baselines/reference/contextualOverloadListFromArrayUnion.symbols
  tests/baselines/reference/contextualOverloadListFromArrayUnion.types
  tests/baselines/reference/contextualOverloadListFromUnionWithPrimitiveNoImplicitAny.errors.txt
  tests/baselines/reference/contextualOverloadListFromUnionWithPrimitiveNoImplicitAny.js
  tests/baselines/reference/contextualOverloadListFromUnionWithPrimitiveNoImplicitAny.symbols
  tests/baselines/reference/contextualOverloadListFromUnionWithPrimitiveNoImplicitAny.types
  tests/baselines/reference/redefineArray.errors.txt
  tests/baselines/reference/redefineArray.types
  tests/cases/compiler/contextualOverloadListFromArrayUnion.ts
  tests/cases/compiler/contextualOverloadListFromUnionWithPrimitiveNoImplicitAny.ts
Labels: Author: Team, For Uncommitted Bug

#42921 Fix version regexes.
  .github/workflows/new-release-branch.yaml
  .github/workflows/set-version.yaml
Labels: For Uncommitted Bug

#42881 fix(42833): Incorrect code generated using 'implement abstract class' quick fix on class with overloads
  src/services/codefixes/helpers.ts
  tests/cases/fourslash/codeFixClassExtendAbstractMethod.ts
  tests/cases/fourslash/codeFixClassImplementInterfaceComputedPropertyNameWellKnownSymbols.ts
  tests/cases/fourslash/codeFixClassImplementInterfaceMethodTypePredicate.ts
  tests/cases/fourslash/codeFixClassImplementInterfaceMultipleSignatures.ts
  tests/cases/fourslash/codeFixClassImplementInterfaceMultipleSignaturesRest1.ts
  tests/cases/fourslash/codeFixClassImplementInterfaceMultipleSignaturesRest2.ts
Labels: For Milestone Bug

#42657 Improve JSON parser error recovery
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  src/compiler/parser.ts
  src/testRunner/tsconfig.json
  src/testRunner/unittests/config/convertCompilerOptionsFromJson.ts
  src/testRunner/unittests/jsonParserRecovery.ts
  tests/baselines/reference/jsonParserRecovery/JSX.errors.txt
  tests/baselines/reference/jsonParserRecovery/Two_comma-separated_objects.errors.txt
  tests/baselines/reference/jsonParserRecovery/Two_objects.errors.txt
  tests/baselines/reference/jsonParserRecovery/TypeScript_code.errors.txt
  tests/baselines/reference/jsonParserRecovery/trailing_identifier.errors.txt
Labels: Author: Team, For Backlog Bug, For Milestone Bug

#42926 Refactor to simplify project references tsc-watch and tsserver tests
  src/testRunner/tsconfig.json
  src/testRunner/unittests/tsbuild/watchMode.ts
  src/testRunner/unittests/tsc/helpers.ts
  src/testRunner/unittests/tscWatch/helpers.ts
  src/testRunner/unittests/tscWatch/projectsWithReferences.ts
  src/testRunner/unittests/tsserver/helpers.ts
  src/testRunner/unittests/tsserver/projectsWithReferences.ts
  tests/baselines/reference/tscWatch/projectsWithReferences/on-sample-project.js
  tests/baselines/reference/tscWatch/projectsWithReferences/on-transitive-references-in-different-folders.js
  tests/baselines/reference/tscWatch/projectsWithReferences/on-transitive-references.js
  tests/baselines/reference/tscWatch/projectsWithReferences/when-referenced-project-uses-different-module-resolution.js
Labels: Author: Team, For Uncommitted Bug

#42727 Bail when comparing a specialized form of an already ongoing comparison
  src/compiler/checker.ts
  tests/baselines/reference/performanceComparisonOfStructurallyIdenticalInterfacesWithGenericSignatures.js
  tests/baselines/reference/performanceComparisonOfStructurallyIdenticalInterfacesWithGenericSignatures.symbols
  tests/baselines/reference/performanceComparisonOfStructurallyIdenticalInterfacesWithGenericSignatures.types
  tests/cases/compiler/performanceComparisonOfStructurallyIdenticalInterfacesWithGenericSignatures.ts
Labels: Author: Team, For Milestone Bug

#42703 Base signatures resolve only the type parameters local to the signatue
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/conditionalTypeGenericInSignatureTypeParameterConstraint.js
  tests/baselines/reference/conditionalTypeGenericInSignatureTypeParameterConstraint.symbols
  tests/baselines/reference/conditionalTypeGenericInSignatureTypeParameterConstraint.types
  tests/cases/compiler/conditionalTypeGenericInSignatureTypeParameterConstraint.ts
Labels: Author: Team, For Uncommitted Bug

#42917 Never-reducing intersections are not untyped function call targets
  src/compiler/checker.ts
  tests/baselines/reference/neverIntersectionNotCallable.errors.txt
  tests/baselines/reference/neverIntersectionNotCallable.js
  tests/baselines/reference/neverIntersectionNotCallable.symbols
  tests/baselines/reference/neverIntersectionNotCallable.types
  tests/cases/conformance/types/never/neverIntersectionNotCallable.ts
Labels: Author: Team, For Milestone Bug

#42868 Do not cache directory structure for symlinked directories
  src/compiler/watchUtilities.ts
  src/harness/virtualFileSystemWithWatch.ts
  src/testRunner/unittests/tscWatch/programUpdates.ts
  src/testRunner/unittests/tsserver/cachingFileSystemInformation.ts
  tests/baselines/reference/tscWatch/programUpdates/when-creating-new-file-in-symlinked-folder.js
Labels: Author: Team, For Milestone Bug

#42924 fix(42923): Provide go-to-definition on unresolved shorthand properties
  src/services/goToDefinition.ts
  tests/cases/fourslash/goToDefinitionShorthandProperty04.ts
  tests/cases/fourslash/goToDefinitionShorthandProperty05.ts
  tests/cases/fourslash/goToDefinitionShorthandProperty06.ts
Labels: For Milestone Bug

#42332 fix(42259): Outline and breadcrumb show wrong namespace name
  src/services/navigationBar.ts
  tests/cases/fourslash/navigationBarItemsModules1.ts
  tests/cases/fourslash/navigationBarItemsModules2.ts
Labels: For Milestone Bug

#42904 fix(42339): "import" missing in transpiled code when variable typed as `unknown`
  src/compiler/checker.ts
  tests/baselines/reference/spreadUnion3.errors.txt
  tests/baselines/reference/unusedImportWithSpread.js
  tests/baselines/reference/unusedImportWithSpread.symbols
  tests/baselines/reference/unusedImportWithSpread.types
  tests/cases/compiler/unusedImportWithSpread.ts
Labels: For Milestone Bug

#42819 Type lookup in getIntrinsicAttributestypeFromJsxOpeningLikeElement should match getIntrinsicTagSymbol
  src/compiler/checker.ts
  tests/baselines/reference/jsxLocalNamespaceIndexSignatureNoCrash.js
  tests/baselines/reference/jsxLocalNamespaceIndexSignatureNoCrash.symbols
  tests/baselines/reference/jsxLocalNamespaceIndexSignatureNoCrash.types
  tests/cases/compiler/jsxLocalNamespaceIndexSignatureNoCrash.tsx
Labels: Author: Team, For Milestone Bug

#42951 Use common helper for consistency
  src/server/editorServices.ts
Labels: For Uncommitted Bug

#42961 Use yarn resolutions to inject nightly TS version across whole workspace in fabric test
  tests/cases/docker/office-ui-fabric/Dockerfile
Labels: Author: Team, For Milestone Bug

#42640 Expose EncodedSemanticClassificationsRequest in protocol.d.ts
  src/server/protocol.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
Labels: Author: Team, For Milestone Bug

#42943 Properly handle duplicate enum types in type inference
  src/compiler/checker.ts
  tests/baselines/reference/unionOfEnumInference.js
  tests/baselines/reference/unionOfEnumInference.symbols
  tests/baselines/reference/unionOfEnumInference.types
  tests/cases/compiler/unionOfEnumInference.ts
Labels: Author: Team, For Milestone Bug

#42965 Expose EncodedSemanticClassificationsRequest in protocol.d.ts
  src/server/protocol.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
Labels: Author: Team, For Uncommitted Bug

#42971 Fix: checkAliasSymbol crash when checking for @deprecated
  src/compiler/checker.ts
  tests/baselines/reference/importPropertyFromMappedType.js
  tests/baselines/reference/importPropertyFromMappedType.symbols
  tests/baselines/reference/importPropertyFromMappedType.types
  tests/cases/compiler/importPropertyFromMappedType.ts
Labels: Author: Team, For Milestone Bug

#41660 Remove special `any` assignability for numeric index signatures
  src/compiler/checker.ts
  tests/baselines/reference/functionAssignabilityWithArrayLike01(strict=false).errors.txt
  tests/baselines/reference/functionAssignabilityWithArrayLike01(strict=false).js
  tests/baselines/reference/functionAssignabilityWithArrayLike01(strict=false).symbols
  tests/baselines/reference/functionAssignabilityWithArrayLike01(strict=false).types
  tests/baselines/reference/functionAssignabilityWithArrayLike01(strict=true).errors.txt
  tests/baselines/reference/functionAssignabilityWithArrayLike01(strict=true).js
  tests/baselines/reference/functionAssignabilityWithArrayLike01(strict=true).symbols
  tests/baselines/reference/functionAssignabilityWithArrayLike01(strict=true).types
  tests/baselines/reference/subclassThisTypeAssignable.errors.txt
  tests/baselines/reference/subclassThisTypeAssignable01.errors.txt
  tests/baselines/reference/subclassThisTypeAssignable01.js
  tests/baselines/reference/subclassThisTypeAssignable01.symbols
  tests/baselines/reference/subclassThisTypeAssignable01.types
  tests/baselines/reference/subclassThisTypeAssignable02.js
  tests/baselines/reference/subclassThisTypeAssignable02.symbols
  tests/baselines/reference/subclassThisTypeAssignable02.types
  tests/cases/compiler/functionAssignabilityWithArrayLike01.ts
  tests/cases/compiler/subclassThisTypeAssignable01.ts
  tests/cases/compiler/subclassThisTypeAssignable02.ts
Labels: For Milestone Bug

#42676 Refactor emit substitution into transform
  scripts/perf-result-post.js
  src/compiler/binder.ts
  src/compiler/debug.ts
  src/compiler/emitter.ts
  src/compiler/factory/nodeTests.ts
  src/compiler/factory/utilities.ts
  src/compiler/transformers/module/module.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/compiler/utilitiesPublic.ts
  src/compiler/visitorPublic.ts
  src/deprecatedCompat/deprecations.ts
  src/services/codefixes/fixSpelling.ts
  src/services/completions.ts
  src/services/textChanges.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/es6ExportClauseWithAssignmentInEs5.js
  tests/baselines/reference/importMeta(module=commonjs,target=es5).js
  tests/baselines/reference/importMeta(module=commonjs,target=esnext).js
  tests/baselines/reference/importMeta(module=system,target=es5).js
  tests/baselines/reference/importMeta(module=system,target=esnext).js
  tests/baselines/reference/inlineJsxFactoryDeclarationsLocalTypes.js
  tests/baselines/reference/jsxCheckJsxNoTypeArgumentsAllowed.js
  tests/baselines/reference/moduleExportsUnaryExpression.js
  tests/baselines/reference/objectLiteralShorthandPropertiesErrorFromNotUsingIdentifier.js
  tests/baselines/reference/objectLiteralShorthandPropertiesErrorWithModule.js
  tests/baselines/reference/objectTypesWithOptionalProperties2.js
  tests/baselines/reference/parserErrorRecovery_ObjectLiteral2.js
Labels: Author: Team, For Milestone Bug

#42630 Fix preserveSourceNewlines sibling node comparison (fixes extra newlines in organize imports)
  src/compiler/emitter.ts
  src/compiler/utilities.ts
  tests/cases/fourslash/organizeImports1.ts
  tests/cases/fourslash/organizeImports2.ts
  tests/cases/fourslash/organizeImports3.ts
Labels: Author: Team, For Milestone Bug
