Repository microsoft/TypeScript, pull requests merged in 2021-10, with the labels that each got.

#45983 fix(sourcemap): accept a sourceMappingURL that ends with a newline
  src/compiler/sourcemap.ts
Labels: For Milestone Bug

#45930 feat: display the tsconfig generated when running tsc --init
  src/compiler/commandLineParser.ts
  src/executeCommandLine/executeCommandLine.ts
Labels: For Uncommitted Bug

#44813 Allow for class static vars to be called static
  src/compiler/parser.ts
  tests/baselines/reference/multipleClassPropertyModifiersErrors.errors.txt
  tests/baselines/reference/multipleClassPropertyModifiersErrors.symbols
  tests/baselines/reference/multipleClassPropertyModifiersErrors.types
  tests/baselines/reference/parserIndexMemberDeclaration10.errors.txt
  tests/baselines/reference/parserIndexMemberDeclaration10.symbols
  tests/baselines/reference/parserIndexMemberDeclaration10.types
  tests/baselines/reference/parserMemberAccessorDeclaration8.errors.txt
  tests/baselines/reference/parserMemberAccessorDeclaration8.js
  tests/baselines/reference/parserMemberAccessorDeclaration8.symbols
  tests/baselines/reference/parserMemberAccessorDeclaration8.types
  tests/baselines/reference/parserMemberFunctionDeclaration2.errors.txt
  tests/baselines/reference/parserMemberFunctionDeclaration2.js
  tests/baselines/reference/parserMemberFunctionDeclaration2.symbols
  tests/baselines/reference/parserMemberFunctionDeclaration2.types
  tests/baselines/reference/parserMemberVariableDeclaration2.errors.txt
  tests/baselines/reference/parserMemberVariableDeclaration2.symbols
  tests/baselines/reference/parserMemberVariableDeclaration2.types
  tests/baselines/reference/staticAsIdentifier.errors.txt
  tests/baselines/reference/staticAsIdentifier.js
  tests/baselines/reference/staticAsIdentifier.symbols
  tests/baselines/reference/staticAsIdentifier.types
  tests/baselines/reference/staticModifierAlreadySeen.errors.txt
  tests/baselines/reference/staticModifierAlreadySeen.js
  tests/baselines/reference/staticModifierAlreadySeen.symbols
  tests/baselines/reference/staticModifierAlreadySeen.types
  tests/cases/compiler/staticAsIdentifier.ts
Labels: Author: Team, For Milestone Bug

#46156 Modify synthetic default generation code for dual-mode module resolution
  src/compiler/checker.ts
  tests/baselines/reference/nodeModulesAllowJsSynchronousCallErrors(module=node12).types
  tests/baselines/reference/nodeModulesAllowJsSynchronousCallErrors(module=nodenext).types
  tests/baselines/reference/nodeModulesCjsFormatFileAlwaysHasDefault(module=node12).js
  tests/baselines/reference/nodeModulesCjsFormatFileAlwaysHasDefault(module=node12).symbols
  tests/baselines/reference/nodeModulesCjsFormatFileAlwaysHasDefault(module=node12).types
  tests/baselines/reference/nodeModulesCjsFormatFileAlwaysHasDefault(module=nodenext).js
  tests/baselines/reference/nodeModulesCjsFormatFileAlwaysHasDefault(module=nodenext).symbols
  tests/baselines/reference/nodeModulesCjsFormatFileAlwaysHasDefault(module=nodenext).types
  tests/baselines/reference/nodeModulesDeclarationEmitDynamicImportWithPackageExports.js
  tests/baselines/reference/nodeModulesDeclarationEmitDynamicImportWithPackageExports.types
  tests/baselines/reference/nodeModulesSynchronousCallErrors(module=node12).types
  tests/baselines/reference/nodeModulesSynchronousCallErrors(module=nodenext).types
  tests/cases/conformance/node/nodeModulesCjsFormatFileAlwaysHasDefault.ts
Labels: Author: Team, For Uncommitted Bug

#46160 Fixes main by updating baselines
  src/testRunner/parallel/host.ts
  src/testRunner/parallel/worker.ts
  tests/baselines/reference/multipleClassPropertyModifiersErrors.errors.txt
  tests/baselines/reference/parserIndexMemberDeclaration10.errors.txt
  tests/baselines/reference/parserMemberAccessorDeclaration8.errors.txt
  tests/baselines/reference/parserMemberFunctionDeclaration2.errors.txt
  tests/baselines/reference/parserMemberVariableDeclaration2.errors.txt
  tests/baselines/reference/staticAsIdentifier.errors.txt
  tests/baselines/reference/staticModifierAlreadySeen.errors.txt
Labels: Author: Team, For Uncommitted Bug

#46161 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20211001171323598 to main
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#46159 Follow and respect export maps when generating module specifiers
  src/compiler/moduleNameResolver.ts
  src/compiler/moduleSpecifiers.ts
  src/testRunner/unittests/tsbuild/moduleSpecifiers.ts
  tests/baselines/reference/nodeModulesExportsBlocksSpecifierResolution(module=node12).errors.txt
  tests/baselines/reference/nodeModulesExportsBlocksSpecifierResolution(module=node12).js
  tests/baselines/reference/nodeModulesExportsBlocksSpecifierResolution(module=node12).symbols
  tests/baselines/reference/nodeModulesExportsBlocksSpecifierResolution(module=node12).types
  tests/baselines/reference/nodeModulesExportsBlocksSpecifierResolution(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesExportsBlocksSpecifierResolution(module=nodenext).js
  tests/baselines/reference/nodeModulesExportsBlocksSpecifierResolution(module=nodenext).symbols
  tests/baselines/reference/nodeModulesExportsBlocksSpecifierResolution(module=nodenext).types
  tests/baselines/reference/nodeModulesExportsSpecifierGenerationConditions(module=node12).errors.txt
  tests/baselines/reference/nodeModulesExportsSpecifierGenerationConditions(module=node12).js
  tests/baselines/reference/nodeModulesExportsSpecifierGenerationConditions(module=node12).symbols
  tests/baselines/reference/nodeModulesExportsSpecifierGenerationConditions(module=node12).types
  tests/baselines/reference/nodeModulesExportsSpecifierGenerationConditions(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesExportsSpecifierGenerationConditions(module=nodenext).js
  tests/baselines/reference/nodeModulesExportsSpecifierGenerationConditions(module=nodenext).symbols
  tests/baselines/reference/nodeModulesExportsSpecifierGenerationConditions(module=nodenext).types
  tests/baselines/reference/nodeModulesExportsSpecifierGenerationDirectory(module=node12).errors.txt
  tests/baselines/reference/nodeModulesExportsSpecifierGenerationDirectory(module=node12).js
  tests/baselines/reference/nodeModulesExportsSpecifierGenerationDirectory(module=node12).symbols
  tests/baselines/reference/nodeModulesExportsSpecifierGenerationDirectory(module=node12).types
  tests/baselines/reference/nodeModulesExportsSpecifierGenerationDirectory(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesExportsSpecifierGenerationDirectory(module=nodenext).js
  tests/baselines/reference/nodeModulesExportsSpecifierGenerationDirectory(module=nodenext).symbols
  tests/baselines/reference/nodeModulesExportsSpecifierGenerationDirectory(module=nodenext).types
  tests/baselines/reference/nodeModulesExportsSpecifierGenerationPattern(module=node12).errors.txt
  tests/baselines/reference/nodeModulesExportsSpecifierGenerationPattern(module=node12).js
  tests/baselines/reference/nodeModulesExportsSpecifierGenerationPattern(module=node12).symbols
  tests/baselines/reference/nodeModulesExportsSpecifierGenerationPattern(module=node12).types
  tests/baselines/reference/nodeModulesExportsSpecifierGenerationPattern(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesExportsSpecifierGenerationPattern(module=nodenext).js
  tests/baselines/reference/nodeModulesExportsSpecifierGenerationPattern(module=nodenext).symbols
  tests/baselines/reference/nodeModulesExportsSpecifierGenerationPattern(module=nodenext).types
  tests/baselines/reference/tsbuild/moduleSpecifiers/initial-build/synthesized-module-specifiers-across-projects-resolve-correctly.js
  tests/cases/conformance/node/nodeModulesExportsBlocksSpecifierResolution.ts
  tests/cases/conformance/node/nodeModulesExportsSpecifierGenerationConditions.ts
  tests/cases/conformance/node/nodeModulesExportsSpecifierGenerationDirectory.ts
  tests/cases/conformance/node/nodeModulesExportsSpecifierGenerationPattern.ts
Labels: Author: Team, For Uncommitted Bug

#46158 improve response time of invalid rename attempts
  src/server/session.ts
  src/services/rename.ts
  src/services/services.ts
  src/testRunner/unittests/tsserver/rename.ts
Labels: For Backlog Bug

#46168 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20211001231353330 to main
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#46170 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20211002051544076 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#46203 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20211004171413687 to main
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#42126 Feat/quick fix for types
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/services/codefixes/fixSpelling.ts
  tests/baselines/reference/declarationEmitUnknownImport.errors.txt
  tests/baselines/reference/declarationEmitUnknownImport2.errors.txt
  tests/baselines/reference/extendArray.errors.txt
  tests/baselines/reference/importedModuleAddToGlobal.errors.txt
  tests/baselines/reference/invalidInstantiatedModule.errors.txt
  tests/baselines/reference/jsdocPropertyTagInvalid.errors.txt
  tests/baselines/reference/jsxFactoryIdentifierWithAbsentParameter.errors.txt
  tests/baselines/reference/jsxFactoryQualifiedNameResolutionError.errors.txt
  tests/baselines/reference/parserUnfinishedTypeNameBeforeKeyword1.errors.txt
  tests/baselines/reference/parserUnterminatedGeneric1.errors.txt
  tests/baselines/reference/parserUnterminatedGeneric2.errors.txt
  tests/baselines/reference/primaryExpressionMods.errors.txt
  tests/cases/fourslash/codeFixSpellingCaseSensitive4.ts
Labels: For Uncommitted Bug

#46209 Limit package.json realpath lookup to only successful resolutions
  src/compiler/tsbuildPublic.ts
Labels: Author: Team, For Uncommitted Bug

#46211 Only set package data map under watch mode
  src/compiler/tsbuildPublic.ts
Labels: Author: Team, For Uncommitted Bug

#46212 Properly support scoped package self name lookups
  src/compiler/moduleNameResolver.ts
  tests/baselines/reference/nodePackageSelfNameScoped(module=node12).errors.txt
  tests/baselines/reference/nodePackageSelfNameScoped(module=node12).js
  tests/baselines/reference/nodePackageSelfNameScoped(module=node12).symbols
  tests/baselines/reference/nodePackageSelfNameScoped(module=node12).types
  tests/baselines/reference/nodePackageSelfNameScoped(module=nodenext).errors.txt
  tests/baselines/reference/nodePackageSelfNameScoped(module=nodenext).js
  tests/baselines/reference/nodePackageSelfNameScoped(module=nodenext).symbols
  tests/baselines/reference/nodePackageSelfNameScoped(module=nodenext).types
  tests/cases/conformance/node/nodePackageSelfNameScoped.ts
Labels: Author: Team, For Milestone Bug

#46238 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20211006171335650 to main
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#46239 Accept new moduleResolution options on commandline
  src/compiler/commandLineParser.ts
  src/testRunner/compilerRunner.ts
  src/testRunner/unittests/config/commandLineParsing.ts
  tests/baselines/reference/moduleResolutionWithModule(module=commonjs,moduleresolution=node).errors.txt
  tests/baselines/reference/moduleResolutionWithModule(module=commonjs,moduleresolution=node).js
  tests/baselines/reference/moduleResolutionWithModule(module=commonjs,moduleresolution=node).symbols
  tests/baselines/reference/moduleResolutionWithModule(module=commonjs,moduleresolution=node).types
  tests/baselines/reference/moduleResolutionWithModule(module=commonjs,moduleresolution=node12).js
  tests/baselines/reference/moduleResolutionWithModule(module=commonjs,moduleresolution=node12).symbols
  tests/baselines/reference/moduleResolutionWithModule(module=commonjs,moduleresolution=node12).types
  tests/baselines/reference/moduleResolutionWithModule(module=commonjs,moduleresolution=nodenext).js
  tests/baselines/reference/moduleResolutionWithModule(module=commonjs,moduleresolution=nodenext).symbols
  tests/baselines/reference/moduleResolutionWithModule(module=commonjs,moduleresolution=nodenext).types
  tests/baselines/reference/moduleResolutionWithModule(module=node12,moduleresolution=node).errors.txt
  tests/baselines/reference/moduleResolutionWithModule(module=node12,moduleresolution=node).js
  tests/baselines/reference/moduleResolutionWithModule(module=node12,moduleresolution=node).symbols
  tests/baselines/reference/moduleResolutionWithModule(module=node12,moduleresolution=node).types
  tests/baselines/reference/moduleResolutionWithModule(module=node12,moduleresolution=node12).js
  tests/baselines/reference/moduleResolutionWithModule(module=node12,moduleresolution=node12).symbols
  tests/baselines/reference/moduleResolutionWithModule(module=node12,moduleresolution=node12).types
  tests/baselines/reference/moduleResolutionWithModule(module=node12,moduleresolution=nodenext).js
  tests/baselines/reference/moduleResolutionWithModule(module=node12,moduleresolution=nodenext).symbols
  tests/baselines/reference/moduleResolutionWithModule(module=node12,moduleresolution=nodenext).types
  tests/baselines/reference/moduleResolutionWithModule(module=nodenext,moduleresolution=node).errors.txt
  tests/baselines/reference/moduleResolutionWithModule(module=nodenext,moduleresolution=node).js
  tests/baselines/reference/moduleResolutionWithModule(module=nodenext,moduleresolution=node).symbols
  tests/baselines/reference/moduleResolutionWithModule(module=nodenext,moduleresolution=node).types
  tests/baselines/reference/moduleResolutionWithModule(module=nodenext,moduleresolution=node12).js
  tests/baselines/reference/moduleResolutionWithModule(module=nodenext,moduleresolution=node12).symbols
  tests/baselines/reference/moduleResolutionWithModule(module=nodenext,moduleresolution=node12).types
  tests/baselines/reference/moduleResolutionWithModule(module=nodenext,moduleresolution=nodenext).js
  tests/baselines/reference/moduleResolutionWithModule(module=nodenext,moduleresolution=nodenext).symbols
  tests/baselines/reference/moduleResolutionWithModule(module=nodenext,moduleresolution=nodenext).types
  tests/cases/compiler/moduleResolutionWithModule.ts
Labels: Author: Team, For Uncommitted Bug

#46557 Add error on new module/moduleResolution modes when used in non-nightly TS
  src/compiler/diagnosticMessages.json
  src/compiler/program.ts
Labels: Author: Team, For Milestone Bug

#46586 Fix mapped type instantiation circularity
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypeWithAny.errors.txt
  tests/baselines/reference/mappedTypeWithAny.js
  tests/baselines/reference/mappedTypeWithAny.symbols
  tests/baselines/reference/mappedTypeWithAny.types
  tests/cases/conformance/types/mapped/mappedTypeWithAny.ts
Labels: Author: Team, For Milestone Bug

#46592 Enable auto imports in member snippet completions
  src/compiler/diagnosticMessages.json
  src/harness/fourslashImpl.ts
  src/services/codeFixProvider.ts
  src/services/codefixes/importFixes.ts
  src/services/completions.ts
  src/services/utilities.ts
  tests/cases/fourslash/completionsOverridingMethod8.ts
  tests/cases/fourslash/fourslash.ts
Labels: Author: Team, For Uncommitted Bug

#46569 Set hasAddedOrRemovedSymlinks when discovering an existing file by its link
  src/compiler/program.ts
  src/compiler/resolutionCache.ts
  src/server/project.ts
  tests/cases/fourslash/server/completionsImport_addToNamedWithDifferentCacheValue.ts
Labels: Author: Team, For Milestone Bug

#46597 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20211029231305209 to main
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#46598 Remove placeholders in class member snippets
  src/services/completions.ts
  tests/cases/fourslash/completionsOverridingMethod2.ts
Labels: Author: Team, For Uncommitted Bug

#46601 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20211030051550493 to main
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug
