Repository microsoft/TypeScript, pull requests merged in 2021-07, with the labels that each got.

#44854 Correctly check for 'delete' on optional properties in 'exactOptionalPropertyTypes'.
  src/compiler/checker.ts
  tests/baselines/reference/deleteExpressionMustBeOptional_exactOptionalPropertyTypes(exactoptionalpropertytypes=true).errors.txt
Labels: For Milestone Bug

#44862 Further optional delete corrections
  src/compiler/checker.ts
  tests/baselines/reference/deleteExpressionMustBeOptional_exactOptionalPropertyTypes(exactoptionalpropertytypes=false).errors.txt
  tests/baselines/reference/deleteExpressionMustBeOptional_exactOptionalPropertyTypes(exactoptionalpropertytypes=false).js
  tests/baselines/reference/deleteExpressionMustBeOptional_exactOptionalPropertyTypes(exactoptionalpropertytypes=false).symbols
  tests/baselines/reference/deleteExpressionMustBeOptional_exactOptionalPropertyTypes(exactoptionalpropertytypes=false).types
  tests/baselines/reference/deleteExpressionMustBeOptional_exactOptionalPropertyTypes(exactoptionalpropertytypes=true).errors.txt
  tests/baselines/reference/deleteExpressionMustBeOptional_exactOptionalPropertyTypes(exactoptionalpropertytypes=true).js
  tests/baselines/reference/deleteExpressionMustBeOptional_exactOptionalPropertyTypes(exactoptionalpropertytypes=true).symbols
  tests/baselines/reference/deleteExpressionMustBeOptional_exactOptionalPropertyTypes(exactoptionalpropertytypes=true).types
  tests/cases/compiler/deleteExpressionMustBeOptional_exactOptionalPropertyTypes.ts
Labels: For Milestone Bug

#44877 Fix class name reference in class expr
  src/compiler/checker.ts
  tests/baselines/reference/classStaticBlock27.js
  tests/baselines/reference/classStaticBlock27.symbols
  tests/baselines/reference/classStaticBlock27.types
  tests/cases/conformance/classes/classStaticBlock/classStaticBlock27.ts
Labels: Author: Team, For Milestone Bug

#44878 Add evaluation tests for class static initializers
  src/testRunner/tsconfig.json
  src/testRunner/unittests/evaluation/superInStaticInitializer.ts
Labels: Author: Team, For Uncommitted Bug

#44884 Change PerformanceObserver to be compatible with new Node types
  src/compiler/performanceCore.ts
  src/tsserver/nodeServer.ts
Labels: Author: Team, For Uncommitted Bug

#44881 fix(44868): Imported type incorrectly allowed to be used as a value when object shorthand is used
  src/compiler/utilities.ts
  tests/baselines/reference/importClause_default.errors.txt
  tests/baselines/reference/importClause_default.js
  tests/baselines/reference/importClause_default.symbols
  tests/baselines/reference/importClause_default.types
  tests/baselines/reference/importClause_namedImports.errors.txt
  tests/baselines/reference/importClause_namedImports.js
  tests/baselines/reference/importClause_namedImports.symbols
  tests/baselines/reference/importClause_namedImports.types
  tests/baselines/reference/importClause_namespaceImport.errors.txt
  tests/baselines/reference/importClause_namespaceImport.js
  tests/baselines/reference/importClause_namespaceImport.symbols
  tests/baselines/reference/importClause_namespaceImport.types
  tests/cases/conformance/externalModules/typeOnly/importClause_default.ts
  tests/cases/conformance/externalModules/typeOnly/importClause_namedImports.ts
  tests/cases/conformance/externalModules/typeOnly/importClause_namespaceImport.ts
Labels: For Milestone Bug

#44816 Refactor export map cache to not store transient symbols
  src/server/moduleSpecifierCache.ts
  src/server/project.ts
  src/server/tsconfig.json
  src/services/codefixes/importFixes.ts
  src/services/completions.ts
  src/services/exportInfoMap.ts
  src/services/tsconfig.json
  src/services/types.ts
  src/services/utilities.ts
  src/testRunner/unittests/tsserver/completionsIncomplete.ts
  src/testRunner/unittests/tsserver/exportMapCache.ts
Labels: Author: Team, For Uncommitted Bug

#44873 Consistently ignore attributes with hyphenated names in JSX
  src/compiler/checker.ts
  tests/baselines/reference/ignoredJsxAttributes.errors.txt
  tests/baselines/reference/ignoredJsxAttributes.js
  tests/baselines/reference/ignoredJsxAttributes.symbols
  tests/baselines/reference/ignoredJsxAttributes.types
  tests/baselines/reference/tsxAttributeResolution7.errors.txt
  tests/baselines/reference/tsxStatelessFunctionComponentOverload4.errors.txt
  tests/baselines/reference/tsxStatelessFunctionComponentOverload5.errors.txt
  tests/baselines/reference/tsxStatelessFunctionComponentsWithTypeArguments2.errors.txt
  tests/cases/compiler/ignoredJsxAttributes.tsx
Labels: Author: Team, For Uncommitted Bug

#44399 Improve "Convert to template string" with template-strings
  src/services/refactors/convertStringOrTemplateLiteral.ts
  tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_TemplateString11.ts
  tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_TemplateString12.ts
Labels: Author: Team, For Backlog Bug

#44836 Apply disableReferencedProjectLoad to getOriginalLocationEnsuringConfiguredProject
  src/server/editorServices.ts
  src/testRunner/unittests/tsserver/projectReferences.ts
  tests/baselines/reference/tsserver/projectReferences/find-all-references-to-a-symbol-declared-in-another-project-when-proj-is-loaded--and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-all-references-to-a-symbol-declared-in-another-project-when-proj-is-loaded--and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-all-references-to-a-symbol-declared-in-another-project-when-proj-is-loaded--and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-all-references-to-a-symbol-declared-in-another-project-when-proj-is-loaded--and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-all-references-to-a-symbol-declared-in-another-project-when-proj-is-loaded--and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-all-references-to-a-symbol-declared-in-another-project-when-proj-is-loaded--and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-all-references-to-a-symbol-declared-in-another-project-when-proj-is-loaded--and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-all-references-to-a-symbol-declared-in-another-project-when-proj-is-loaded--and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-all-references-to-a-symbol-declared-in-another-project-when-proj-is-not-loaded--and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-all-references-to-a-symbol-declared-in-another-project-when-proj-is-not-loaded--and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-all-references-to-a-symbol-declared-in-another-project-when-proj-is-not-loaded--and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-all-references-to-a-symbol-declared-in-another-project-when-proj-is-not-loaded--and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-all-references-to-a-symbol-declared-in-another-project-when-proj-is-not-loaded--and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-all-references-to-a-symbol-declared-in-another-project-when-proj-is-not-loaded--and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-all-references-to-a-symbol-declared-in-another-project-when-proj-is-not-loaded--and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-all-references-to-a-symbol-declared-in-another-project-when-proj-is-not-loaded--and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-present.js
Labels: Author: Team, For Uncommitted Bug

#44929 fix(44926): Wrong description for noImplicitOverride with tsc --all
  src/compiler/commandLineParser.ts
  tests/baselines/reference/tsConfig/Default initialized TSConfig/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with advanced options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with boolean value compiler options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with enum value compiler options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with files options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with incorrect compiler option value/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with incorrect compiler option/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with list compiler options with enum value/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with list compiler options/tsconfig.json
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/declarationDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/when-outDir-and-declarationDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/when-outDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/with-outFile.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/without-outDir-or-outFile-is-specified-with-declaration-enabled.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/without-outDir-or-outFile-is-specified.js
Labels: For Milestone Bug

#44933 Fix decorator emit regression for static fields
  src/compiler/transformers/classFields.ts
  src/compiler/transformers/ts.ts
  src/compiler/utilities.ts
  src/tsserver/nodeServer.ts
  tests/baselines/reference/decoratorOnClassConstructorParameter5.js
  tests/cases/conformance/decorators/class/constructor/parameter/decoratorOnClassConstructorParameter5.ts
Labels: Author: Team, For Milestone Bug

#43733 Detect circularities printing recursive conditional types
  src/compiler/checker.ts
  tests/baselines/reference/arrayFakeFlatNoCrashInferenceDeclarations.types
  tests/baselines/reference/recursiveConditionalCrash1.js
  tests/baselines/reference/recursiveConditionalCrash1.symbols
  tests/baselines/reference/recursiveConditionalCrash1.types
  tests/baselines/reference/recursiveConditionalCrash2.js
  tests/baselines/reference/recursiveConditionalCrash2.symbols
  tests/baselines/reference/recursiveConditionalCrash2.types
  tests/baselines/reference/recursiveConditionalCrash3.js
  tests/baselines/reference/recursiveConditionalCrash3.symbols
  tests/baselines/reference/recursiveConditionalCrash3.types
  tests/cases/compiler/recursiveConditionalCrash1.ts
  tests/cases/compiler/recursiveConditionalCrash2.ts
  tests/cases/compiler/recursiveConditionalCrash3.ts
Labels: Author: Team, For Uncommitted Bug

#41951 fix(35050): Decorator emit incorrect within `try` block
  src/compiler/transformers/ts.ts
  tests/baselines/reference/decoratedBlockScopedClass1.js
  tests/baselines/reference/decoratedBlockScopedClass1.symbols
  tests/baselines/reference/decoratedBlockScopedClass1.types
  tests/baselines/reference/decoratedBlockScopedClass2.js
  tests/baselines/reference/decoratedBlockScopedClass2.symbols
  tests/baselines/reference/decoratedBlockScopedClass2.types
  tests/baselines/reference/decoratedBlockScopedClass3.js
  tests/baselines/reference/decoratedBlockScopedClass3.symbols
  tests/baselines/reference/decoratedBlockScopedClass3.types
  tests/cases/conformance/decorators/class/decoratedBlockScopedClass1.ts
  tests/cases/conformance/decorators/class/decoratedBlockScopedClass2.ts
  tests/cases/conformance/decorators/class/decoratedBlockScopedClass3.ts
Labels: For Milestone Bug

#44876 Add collision check for 'Reflect' when using super in static initializers
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/types.ts
  src/compiler/utilities.ts
  tests/baselines/reference/es6ImportNameSpaceImportMergeErrors.errors.txt
  tests/baselines/reference/exportDefault.errors.txt
  tests/baselines/reference/extendsClause.errors.txt
  tests/baselines/reference/importClause_namespaceImport.errors.txt
  tests/baselines/reference/importEquals1.errors.txt
  tests/baselines/reference/importEquals3.errors.txt
  tests/baselines/reference/namespaceMergedWithImportAliasNoCrash.errors.txt
  tests/baselines/reference/superInStaticMembers1(target=es2015).errors.txt
  tests/baselines/reference/superInStaticMembers1(target=es2015).js
  tests/baselines/reference/superInStaticMembers1(target=es2021).errors.txt
  tests/baselines/reference/superInStaticMembers1(target=es2021).js
  tests/baselines/reference/superInStaticMembers1(target=es5).js
  tests/baselines/reference/superInStaticMembers1(target=esnext).js
  tests/cases/conformance/classes/members/instanceAndStaticMembers/superInStaticMembers1.ts
Labels: Author: Team, For Uncommitted Bug

#44989 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210712171351157 to main
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#44935 Watch mode watches for changes in package.json files used in resolution
  src/compiler/moduleNameResolver.ts
  src/compiler/program.ts
  src/compiler/resolutionCache.ts
  src/compiler/tsbuildPublic.ts
  src/compiler/types.ts
  src/compiler/watch.ts
  src/compiler/watchPublic.ts
  src/compiler/watchUtilities.ts
  src/testRunner/unittests/tsbuild/moduleResolution.ts
  tests/baselines/reference/tsbuild/watchMode/demo/updates-with-bad-reference.js
  tests/baselines/reference/tsbuild/watchMode/moduleResolution/build-mode-watches-for-changes-to-package-json-main-fields.js
  tests/baselines/reference/tsbuild/watchMode/moduleResolutionCache/handles-the-cache-correctly-when-two-projects-use-different-module-resolution-settings.js
  tests/baselines/reference/tsbuild/watchMode/reexport/Reports-errors-correctly.js
  tests/baselines/reference/tscWatch/forceConsistentCasingInFileNames/jsxImportSource-option-changed.js
  tests/baselines/reference/tscWatch/incremental/importHelpers-backing-types-removed-watch.js
  tests/baselines/reference/tscWatch/incremental/jsxImportSource-backing-types-added-watch.js
  tests/baselines/reference/tscWatch/incremental/jsxImportSource-backing-types-removed-watch.js
  tests/baselines/reference/tscWatch/incremental/jsxImportSource-option-changed-watch.js
  tests/baselines/reference/tscWatch/moduleResolution/watches-for-changes-to-package-json-main-fields.js
  tests/baselines/reference/tscWatch/programUpdates/should-properly-handle-module-resolution-changes-in-config-file.js
  tests/baselines/reference/tscWatch/programUpdates/types-should-load-from-config-file-path-if-config-exists.js
  tests/baselines/reference/tscWatch/projectsWithReferences/on-transitive-references-in-different-folders-with-no-files-clause.js
  tests/baselines/reference/tscWatch/projectsWithReferences/on-transitive-references-in-different-folders.js
  tests/baselines/reference/tscWatch/resolutionCache/ignores-changes-in-node_modules-that-start-with-dot/watch-with-configFile.js
  tests/baselines/reference/tscWatch/resolutionCache/ignores-changes-in-node_modules-that-start-with-dot/watch-without-configFile.js
  tests/baselines/reference/tscWatch/resolutionCache/when-types-in-compiler-option-are-global-and-installed-at-later-point.js
  tests/baselines/reference/tscWatch/resolutionCache/with-modules-linked-to-sibling-folder.js
  tests/baselines/reference/tscWatch/resolutionCache/works-when-installing-something-in-node_modules-or-@types-when-there-is-no-notification-from-fs-for-index-file.js
  tests/baselines/reference/tscWatch/resolutionCache/works-when-module-resolution-changes-to-ambient-module.js
  tests/baselines/reference/tscWatch/resolutionCache/works-when-renaming-node_modules-folder-that-already-contains-@types-folder.js
  tests/baselines/reference/tscWatch/resolutionCache/works-when-reusing-program-with-files-from-external-library.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchDirectories/when-there-are-symlinks-to-folders-in-recursive-folders.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchDirectories/with-non-synchronous-watch-directory-with-outDir-and-declaration-enabled.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchDirectories/with-non-synchronous-watch-directory.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchOptions/with-excludeDirectories-option-extendedDiagnostics.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchOptions/with-excludeDirectories-option-with-recursive-directory-watching-extendedDiagnostics.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchOptions/with-excludeDirectories-option-with-recursive-directory-watching.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchOptions/with-excludeDirectories-option.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchOptions/with-excludeFiles-option-extendedDiagnostics.js
Labels: Author: Team, For Uncommitted Bug

#44771 Fix "Union types are not being narrowed down correctly in 4.3 #44401"
  src/compiler/checker.ts
  tests/baselines/reference/intersectionOfUnionNarrowing.js
  tests/baselines/reference/intersectionOfUnionNarrowing.symbols
  tests/baselines/reference/intersectionOfUnionNarrowing.types
  tests/cases/conformance/types/intersection/intersectionOfUnionNarrowing.ts
Labels: For Backlog Bug

#44859 Support syntactic diagnostics in partial mode
  src/server/session.ts
  src/services/services.ts
  src/testRunner/unittests/tsserver/partialSemanticServer.ts
  tests/baselines/reference/tsserver/partialSemanticServer/syntactic-diagnostics-are-returned-with-no-error.js
Labels: For Milestone Bug

#44864 Fixes JSDoc @type function with variable args is interpreted incorrectly
  src/compiler/checker.ts
  tests/baselines/reference/jsdocVariadicType.symbols
  tests/baselines/reference/jsdocVariadicType.types
  tests/cases/conformance/jsdoc/jsdocVariadicType.ts
Labels: For Milestone Bug

#45016 chore(typo): fix comment
  src/compiler/checker.ts
Labels: For Uncommitted Bug

#45019 Fix namespace name conflict detection in "Convert named imports to namespace import" action
  src/services/refactors/convertImport.ts
  tests/cases/fourslash/refactorConvertImport_namedToNamespace1.ts
  tests/cases/fourslash/refactorConvertImport_namedToNamespace2.ts
  tests/cases/fourslash/refactorConvertImport_namedToNamespace3.ts
  tests/cases/fourslash/refactorConvertImport_namedToNamespace4.ts
  tests/cases/fourslash/refactorConvertImport_namedToNamespace5.ts
Labels: For Milestone Bug

#43005 Specific diagnostic suggestions for unexpected keyword or identifier
  src/compiler/diagnosticMessages.json
  src/compiler/parser.ts
  src/compiler/scanner.ts
  tests/baselines/reference/ClassDeclaration26.errors.txt
  tests/baselines/reference/anonymousModules.errors.txt
  tests/baselines/reference/classUpdateTests.errors.txt
  tests/baselines/reference/commonMissingSemicolons.errors.txt
  tests/baselines/reference/commonMissingSemicolons.symbols
  tests/baselines/reference/commonMissingSemicolons.types
  tests/baselines/reference/decoratorOnClassAccessor3.errors.txt
  tests/baselines/reference/decoratorOnClassAccessor6.errors.txt
  tests/baselines/reference/decoratorOnClassMethod3.errors.txt
  tests/baselines/reference/decoratorOnClassProperty3.errors.txt
  tests/baselines/reference/derivedClassSuperCallsInNonConstructorMembers.errors.txt
  tests/baselines/reference/derivedClassSuperCallsInNonConstructorMembers.js
  tests/baselines/reference/derivedClassSuperCallsInNonConstructorMembers.symbols
  tests/baselines/reference/derivedClassSuperCallsInNonConstructorMembers.types
  tests/baselines/reference/es6ImportNamedImportParsingError.errors.txt
  tests/baselines/reference/extension.errors.txt
  tests/baselines/reference/externModule.errors.txt
  tests/baselines/reference/innerModExport1.errors.txt
  tests/baselines/reference/innerModExport2.errors.txt
  tests/baselines/reference/interfaceDeclaration4.errors.txt
  tests/baselines/reference/interfaceNaming1.errors.txt
  tests/baselines/reference/interfacesWithPredefinedTypesAsNames.errors.txt
  tests/baselines/reference/invalidSyntaxNamespaceImportWithAMD.errors.txt
  tests/baselines/reference/invalidSyntaxNamespaceImportWithCommonjs.errors.txt
  tests/baselines/reference/invalidSyntaxNamespaceImportWithSystem.errors.txt
  tests/baselines/reference/parseErrorIncorrectReturnToken.errors.txt
  tests/baselines/reference/parser.numericSeparators.decmialNegative.errors.txt
  tests/baselines/reference/parser0_004152.errors.txt
  tests/baselines/reference/parserErrorRecovery_IncompleteMemberVariable2.errors.txt
  tests/baselines/reference/parserFuzz1.errors.txt
  tests/baselines/reference/parserSkippedTokens16.errors.txt
  tests/baselines/reference/parserUnterminatedGeneric2.errors.txt
  tests/baselines/reference/privateInstanceMemberAccessibility.errors.txt
  tests/baselines/reference/reservedNamesInAliases.errors.txt
  tests/baselines/reference/reservedWords2.errors.txt
  tests/baselines/reference/templateStringInModuleName.errors.txt
  tests/baselines/reference/templateStringInModuleNameES6.errors.txt
  tests/baselines/reference/thisTypeInFunctionsNegative.errors.txt
  tests/baselines/reference/transpile/Generates expected syntactic diagnostics.errors.txt
  tests/baselines/reference/transpile/Generates expected syntactic diagnostics.oldTranspile.errors.txt
  tests/baselines/reference/typeAssertions.errors.txt
  tests/baselines/reference/typeGuardFunctionErrors.errors.txt
  tests/cases/compiler/commonMissingSemicolons.ts
Labels: For Backlog Bug

#44955 Fix JS auto import of CJS module with --module=es2015+ and allowSyntheticDefaultExports
  src/services/codefixes/importFixes.ts
  tests/cases/fourslash/importNameCodeFix_commonjs_allowSynthetic.ts
Labels: Author: Team, For Milestone Bug

#45060 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210715231311346 to main
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#44601 Avoid bogus circularity error on context sensitive constructor property assignments
  src/compiler/checker.ts
  tests/baselines/reference/classAttributeInferenceTemplate.js
  tests/baselines/reference/classAttributeInferenceTemplate.symbols
  tests/baselines/reference/classAttributeInferenceTemplate.types
  tests/baselines/reference/classAttributeInferenceTemplateJS.symbols
  tests/baselines/reference/classAttributeInferenceTemplateJS.types
  tests/cases/compiler/classAttributeInferenceTemplate.ts
  tests/cases/compiler/classAttributeInferenceTemplateJS.ts
Labels: Author: Team, For Milestone Bug

#45067 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210716111303528 to main
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#44904 fix(44902): TS Server crashed when extending a mixin class and use the override keyword (after 4.4.0)
  src/compiler/checker.ts
  tests/baselines/reference/override19.errors.txt
  tests/baselines/reference/override19.js
  tests/baselines/reference/override19.symbols
  tests/baselines/reference/override19.types
  tests/cases/conformance/override/override19.ts
  tests/cases/fourslash/codeFixSpelling13.ts
  tests/cases/fourslash/codeFixSpelling14.ts
Labels: For Milestone Bug

#44755 fix(44168): "Move to new file" adds duplicate export
  src/services/refactors/moveToNewFile.ts
  tests/cases/fourslash/moveToNewFile_namedExport1.ts
  tests/cases/fourslash/moveToNewFile_namedExport2.ts
  tests/cases/fourslash/moveToNewFile_namedExport3.ts
Labels: For Milestone Bug

#45054 Shorten baseline names
  src/testRunner/unittests/tsserver/projectReferences.ts
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-not-loaded-and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-not-loaded-and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-not-loaded-and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-not-loaded-and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-not-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-not-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-not-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-not-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-present.js
Labels: Author: Team, For Uncommitted Bug

#45072 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210716171252461 to main
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#44995 Dont swallow declaration emit errors when issued on nodes without names
  src/compiler/transformers/declarations.ts
  tests/baselines/reference/declarationEmitObjectAssignedDefaultExport.errors.txt
  tests/baselines/reference/declarationEmitObjectAssignedDefaultExport.js
  tests/baselines/reference/declarationEmitObjectAssignedDefaultExport.symbols
  tests/baselines/reference/declarationEmitObjectAssignedDefaultExport.types
  tests/cases/compiler/declarationEmitObjectAssignedDefaultExport.ts
Labels: Author: Team, For Milestone Bug

#45073 Properly propagate silentNeverType in intersections
  src/compiler/checker.ts
  tests/baselines/reference/silentNeverPropagation.js
  tests/baselines/reference/silentNeverPropagation.symbols
  tests/baselines/reference/silentNeverPropagation.types
  tests/cases/compiler/silentNeverPropagation.ts
Labels: Author: Team, For Milestone Bug

#44708 fix(44701): Rename Symbol(F2) failed to rename the rhs of "===" when operate on union of string literal
  src/services/utilities.ts
  tests/cases/fourslash/renameStringLiteralOk1.ts
  tests/cases/fourslash/renameStringLiteralTypes1.ts
  tests/cases/fourslash/renameStringLiteralTypes2.ts
Labels: For Backlog Bug

#45052 fix(45049): Change phrasing for "default property value" diagnostic
  src/compiler/diagnosticMessages.json
  src/compiler/parser.ts
  tests/baselines/reference/parserErrorRecovery_IncompleteMemberVariable2.errors.txt
  tests/baselines/reference/privateInstanceMemberAccessibility.errors.txt
Labels: For Backlog Bug

#44947 Check for watched directories before clearing map
  src/server/editorServices.ts
Labels: Author: Team, For Milestone Bug

#45081 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210716231341439 to main
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45083 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210717051416220 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45092 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210718231737704 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45080 Detect preference for `node:`-prefixed node core modules
  src/compiler/program.ts
  src/compiler/types.ts
  src/harness/fourslashInterfaceImpl.ts
  src/jsTyping/jsTyping.ts
  src/services/codefixes/importFixes.ts
  src/services/completions.ts
  src/services/utilities.ts
  tests/cases/fourslash/completionsImport_uriStyleNodeCoreModules1.ts
  tests/cases/fourslash/completionsImport_uriStyleNodeCoreModules2.ts
  tests/cases/fourslash/completionsImport_uriStyleNodeCoreModules3.ts
  tests/cases/fourslash/importNameCodeFix_uriStyleNodeCoreModules1.ts
  tests/cases/fourslash/importNameCodeFix_uriStyleNodeCoreModules2.ts
  tests/cases/fourslash/importNameCodeFix_uriStyleNodeCoreModules3.ts
Labels: Author: Team, For Milestone Bug

#45055 Fix auto import crashes caused by unrelocatable symbols
  src/services/exportInfoMap.ts
  tests/cases/fourslash/server/completionsImport_computedSymbolName.ts
  tests/cases/fourslash/server/completionsImport_mergedReExport.ts
Labels: Author: Team, For Milestone Bug

#44968 Fix and validate post-increment/decrement in module emit
  src/compiler/factory/nodeFactory.ts
  src/compiler/transformers/module/module.ts
  src/compiler/transformers/module/system.ts
  src/compiler/types.ts
  src/harness/evaluatorImpl.ts
  src/testRunner/tsconfig.json
  src/testRunner/unittests/evaluation/updateExpressionInModule.ts
  tests/baselines/reference/es6ExportClauseWithAssignmentInEs5.js
  tests/baselines/reference/es6ExportClauseWithAssignmentInEs5.symbols
  tests/baselines/reference/es6ExportClauseWithAssignmentInEs5.types
  tests/baselines/reference/moduleExportsUnaryExpression.js
  tests/baselines/reference/systemModule8.js
  tests/cases/compiler/es6ExportClauseWithAssignmentInEs5.ts
Labels: Author: Team, For Milestone Bug

#45126 Don’t try to create auto import provider when host program doesn’t exist
  src/server/project.ts
Labels: Author: Team, For Milestone Bug

#44893 feat(42639): "in" operator not narrowing the type if used with a const
  src/compiler/binder.ts
  src/compiler/checker.ts
  tests/baselines/reference/controlFlowInOperator.js
  tests/baselines/reference/controlFlowInOperator.symbols
  tests/baselines/reference/controlFlowInOperator.types
  tests/cases/conformance/controlFlow/controlFlowInOperator.ts
Labels: For Milestone Bug

#45138 Check cancellation token during exportInfoMap generation
  src/services/completions.ts
  src/services/exportInfoMap.ts
  src/services/services.ts
Labels: Author: Team, For Milestone Bug

#45168 Filter auto imports by symbol flags before resolving module specifiers
  src/services/codefixes/importFixes.ts
  src/services/completions.ts
  src/services/exportInfoMap.ts
  tests/cases/fourslash/importStatementCompletions1.ts
Labels: Author: Team, For Uncommitted Bug

#45156 Consider module augmentations in files referenced by imports in watch/incremental
  src/compiler/builderState.ts
  src/testRunner/unittests/tscWatch/incremental.ts
  tests/baselines/reference/tsbuild/lateBoundSymbol/initial-build/interface-is-merged-and-contains-late-bound-member.js
  tests/baselines/reference/tscWatch/incremental/editing-module-augmentation-incremental.js
  tests/baselines/reference/tscWatch/incremental/editing-module-augmentation-watch.js
Labels: Author: Team, For Milestone Bug

#45165 fix(45157): Decorator parsing after field with ASI'd arrow function fails
  src/compiler/parser.ts
  tests/baselines/reference/decoratorOnClassMethod14.js
  tests/baselines/reference/decoratorOnClassMethod14.symbols
  tests/baselines/reference/decoratorOnClassMethod14.types
  tests/baselines/reference/decoratorOnClassMethod15.js
  tests/baselines/reference/decoratorOnClassMethod15.symbols
  tests/baselines/reference/decoratorOnClassMethod15.types
  tests/baselines/reference/decoratorOnClassMethod16.js
  tests/baselines/reference/decoratorOnClassMethod16.symbols
  tests/baselines/reference/decoratorOnClassMethod16.types
  tests/baselines/reference/decoratorOnClassMethod17.errors.txt
  tests/baselines/reference/decoratorOnClassMethod17.js
  tests/baselines/reference/decoratorOnClassMethod17.symbols
  tests/baselines/reference/decoratorOnClassMethod17.types
  tests/baselines/reference/decoratorOnClassMethod18.js
  tests/baselines/reference/decoratorOnClassMethod18.symbols
  tests/baselines/reference/decoratorOnClassMethod18.types
  tests/cases/conformance/decorators/class/method/decoratorOnClassMethod14.ts
  tests/cases/conformance/decorators/class/method/decoratorOnClassMethod15.ts
  tests/cases/conformance/decorators/class/method/decoratorOnClassMethod16.ts
  tests/cases/conformance/decorators/class/method/decoratorOnClassMethod17.ts
  tests/cases/conformance/decorators/class/method/decoratorOnClassMethod18.ts
Labels: For Uncommitted Bug

#45124 fix(45114): Crash on file consisting of #
  src/compiler/scanner.ts
  tests/baselines/reference/privateNameHashCharName.errors.txt
  tests/baselines/reference/privateNameHashCharName.js
  tests/baselines/reference/privateNameHashCharName.symbols
  tests/baselines/reference/privateNameHashCharName.types
  tests/cases/conformance/classes/members/privateNames/privateNameHashCharName.ts
Labels: For Milestone Bug

#45121 Supress hints for access expr too
  src/services/inlayHints.ts
  tests/cases/fourslash/inlayHintsShouldWork54.ts
Labels: For Milestone Bug

#45151 fix(44837): No graceful recovery for require completions in JS
  src/services/stringCompletions.ts
  tests/cases/fourslash/completionsInRequire.ts
Labels: For Milestone Bug

#45193 fix(45182): Incorrect "Property is used before its initialization" error with body-less arrow functions
  src/compiler/checker.ts
  tests/baselines/reference/assignParameterPropertyToPropertyDeclarationESNext.errors.txt
  tests/baselines/reference/assignParameterPropertyToPropertyDeclarationESNext.js
  tests/baselines/reference/assignParameterPropertyToPropertyDeclarationESNext.symbols
  tests/baselines/reference/assignParameterPropertyToPropertyDeclarationESNext.types
  tests/cases/conformance/classes/propertyMemberDeclarations/assignParameterPropertyToPropertyDeclarationESNext.ts
Labels: For Backlog Bug

#45214 feat(45210): Add inlay hints for getters
  src/services/inlayHints.ts
  tests/cases/fourslash/inlayHintsShouldWork55.ts
Labels: For Backlog Bug

#44313 Fix template string refactoring and nodeFactory bug
  src/compiler/factory/nodeFactory.ts
  src/services/refactors/convertStringOrTemplateLiteral.ts
  tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_escapeSequences.ts
Labels: Author: Team, For Milestone Bug

#45231 fix(45225): Add missing member codefix changes lib files
  src/services/codefixes/fixAddMissingMember.ts
  tests/cases/fourslash/codeFixAddMissingMember21.ts
Labels: For Milestone Bug

#45128 Fix import statement completions for export= in JS files
  src/services/codefixes/importFixes.ts
  src/services/completions.ts
  tests/cases/fourslash/importStatementCompletions_js.ts
  tests/cases/fourslash/importStatementCompletions_js2.ts
Labels: Author: Team, For Milestone Bug

#45190 Fix compiler crash on property symbols without declarations
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/transformers/declarations.ts
  src/compiler/types.ts
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty.errors.txt
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty.js
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty.symbols
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty.types
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty2.errors.txt
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty2.js
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty2.symbols
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty2.types
  tests/cases/compiler/mappedTypeWithAsClauseAndLateBoundProperty.ts
  tests/cases/compiler/mappedTypeWithAsClauseAndLateBoundProperty2.ts
Labels: For Milestone Bug

#45152 Allow narrowing for any left-hand in operand
  src/compiler/binder.ts
  tests/baselines/reference/controlFlowForInStatement2.js
  tests/baselines/reference/controlFlowForInStatement2.symbols
  tests/baselines/reference/controlFlowForInStatement2.types
  tests/cases/conformance/controlFlow/controlFlowForInStatement2.ts
Labels: For Uncommitted Bug

#44991 Fix getChildCount/At methods in EndOfFileTokens
  src/services/services.ts
  src/testRunner/unittests/publicApi.ts
Labels: For Backlog Bug

#45238 Avoid no-op export map updates
  src/compiler/builderState.ts
Labels: Author: Team, For Uncommitted Bug

#44961 Avoid provide hints for binding patterns
  src/services/inlayHints.ts
  tests/cases/fourslash/inlayHintsShouldWork56.ts
Labels: For Milestone Bug

#45242 Use arrow functions to bind globals correctly in web scenarios
  src/webServer/webServer.ts
Labels: Author: Team, For Uncommitted Bug

#45059 Fix bigInt completions
  src/services/completions.ts
  tests/cases/fourslash/completionsBigIntShowNoCompletions.ts
Labels: For Milestone Bug

#44847 fix(44812): Collapse icons disappears for comments
  src/services/outliningElementsCollector.ts
  tests/cases/fourslash/getOutliningForBlockComments.ts
Labels: For Milestone Bug
