Repository microsoft/TypeScript, pull requests merged in 2021-08, with the labels that each got.

#45285 Actually instantiate the type of the annotation used for contextual types
  src/compiler/checker.ts
  tests/baselines/reference/inheritedConstructorPropertyContextualType.js
  tests/baselines/reference/inheritedConstructorPropertyContextualType.symbols
  tests/baselines/reference/inheritedConstructorPropertyContextualType.types
  tests/cases/compiler/inheritedConstructorPropertyContextualType.ts
Labels: Author: Team, For Milestone Bug

#44915 Fix decorator metadata references to type-only-imported namespaces
  src/compiler/checker.ts
  tests/baselines/reference/decoratorMetadataWithTypeOnlyImport2.js
  tests/baselines/reference/decoratorMetadataWithTypeOnlyImport2.symbols
  tests/baselines/reference/decoratorMetadataWithTypeOnlyImport2.types
  tests/cases/conformance/decorators/decoratorMetadataWithTypeOnlyImport2.ts
Labels: Author: Team, For Milestone Bug

#45245 fix(45192): Implement interface only working after specifying import
  src/services/codefixes/importFixes.ts
  tests/cases/fourslash/codeFixClassImplementInterfaceAutoImportsReExports.ts
Labels: For Milestone Bug

#43788 Replace non-null assertion with optional chain on assert nodes
  src/compiler/debug.ts
Labels: For Milestone Bug

#44644 expose getImmediateAliasedSymbol() publicly
  src/compiler/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Uncommitted Bug

#45299 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210802231324642 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45292 Ensure all `SortText` entries have the same length
  src/services/completions.ts
  tests/baselines/reference/completionEntryForUnionMethod.baseline
  tests/baselines/reference/completionsCommentsClass.baseline
  tests/baselines/reference/completionsCommentsClassMembers.baseline
  tests/baselines/reference/completionsCommentsCommentParsing.baseline
  tests/baselines/reference/completionsCommentsFunctionDeclaration.baseline
  tests/baselines/reference/completionsCommentsFunctionExpression.baseline
  tests/baselines/reference/completionsJSDocTags.baseline
  tests/baselines/reference/completionsSalsaMethodsOnAssignedFunctionExpressions.baseline
  tests/cases/fourslash/fourslash.ts
Labels: For Milestone Bug

#45274 Fix position of keyword in "Add 'override' modifier" code fix
  src/compiler/factory/nodeTests.ts
  src/services/codefixes/fixOverrideModifier.ts
  tests/cases/fourslash/codeFixOverrideModifier12.ts
Labels: For Uncommitted Bug

#45116 fix(45102): Refactor to convert to/from arrow function does not consider 'arguments'
  src/compiler/checker.ts
  src/compiler/types.ts
  src/services/refactors/convertArrowFunctionOrFunctionExpression.ts
  tests/cases/fourslash/refactorConvertArrowFunctionOrFunctionExpression_Availability_Anon_arguments.ts
  tests/cases/fourslash/refactorConvertArrowFunctionOrFunctionExpression_Availability_Arrow_arguments.ts
Labels: For Backlog Bug

#45229 fix(45224): No inlay hints for setter parameter
  src/compiler/checker.ts
  src/compiler/utilities.ts
  src/services/inlayHints.ts
  tests/cases/fourslash/inlayHintsShouldWork57.ts
  tests/cases/fourslash/inlayHintsShouldWork58.ts
  tests/cases/fourslash/inlayHintsShouldWork59.ts
  tests/cases/fourslash/inlayHintsShouldWork60.ts
Labels: For Uncommitted Bug

#44778 Do not classify Infinity and NaN
  src/services/classifier2020.ts
  tests/cases/fourslash/semanticModernClassificationInfinityAndNaN.ts
Labels: For Milestone Bug

#45312 Visit children of jsdoc type aliases in the binder
  src/compiler/binder.ts
  src/compiler/parser.ts
  tests/baselines/reference/quickInfoLink2.baseline
  tests/cases/fourslash/quickInfoLink2.ts
Labels: Author: Team, For Milestone Bug

#45323 fix(45221): Unresolved import aliases are not suggested in type positions
  src/services/completions.ts
  tests/cases/fourslash/completionsNonExistentImport.ts
  tests/cases/fourslash/nonExistingImport.ts
Labels: For Milestone Bug

#45031 Fix getting completion details for meta properties
  src/compiler/checker.ts
  src/services/completions.ts
  tests/baselines/reference/importMeta(module=commonjs,target=es5).symbols
  tests/baselines/reference/importMeta(module=commonjs,target=esnext).symbols
  tests/baselines/reference/importMeta(module=es2020,target=es5).symbols
  tests/baselines/reference/importMeta(module=es2020,target=esnext).symbols
  tests/baselines/reference/importMeta(module=esnext,target=es5).symbols
  tests/baselines/reference/importMeta(module=esnext,target=esnext).symbols
  tests/baselines/reference/importMeta(module=system,target=es5).symbols
  tests/baselines/reference/importMeta(module=system,target=esnext).symbols
  tests/baselines/reference/importMetaNarrowing(module=es2020).symbols
  tests/baselines/reference/importMetaNarrowing(module=esnext).symbols
  tests/baselines/reference/importMetaNarrowing(module=system).symbols
  tests/baselines/reference/misspelledNewMetaProperty.symbols
  tests/baselines/reference/newTarget.es5.symbols
  tests/baselines/reference/newTarget.es6.symbols
  tests/baselines/reference/newTargetNarrowing.symbols
  tests/baselines/reference/shadowedReservedCompilerDeclarationsWithNoEmit.symbols
  tests/cases/fourslash/completionForMetaProperty.ts
  tests/cases/fourslash/goToDefinitionMetaProperty.ts
Labels: For Backlog Bug, lib update

#45279 `convertStringOrTemplateLiteral.ts`: Re-fix `escapeStringForTemplate`
  src/services/refactors/convertStringOrTemplateLiteral.ts
  tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_escapeSequences.ts
Labels: Author: Team, For Uncommitted Bug

#45289 Store symbol table map key in CachedSymbolExportInfo
  src/compiler/checker.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/services/completions.ts
  src/services/exportInfoMap.ts
  tests/cases/fourslash/server/completionsImport_mergedReExport.ts
Labels: Author: Team, For Milestone Bug

#45324 Migrate over 4.4 lib dom and webworker
  src/lib/dom.generated.d.ts
  src/lib/dom.iterable.generated.d.ts
  src/lib/webworker.generated.d.ts
  src/lib/webworker.iterable.generated.d.ts
  tests/baselines/reference/globalThisBlockscopedProperties.types
  tests/baselines/reference/intersectionsOfLargeUnions2.errors.txt
  tests/baselines/reference/mappedTypeRecursiveInference.errors.txt
  tests/baselines/reference/mappedTypeRecursiveInference.types
  tests/baselines/reference/truthinessCallExpressionCoercion2.types
  tests/baselines/reference/webworkerIterable.types
Labels: Author: Team, For Uncommitted Bug

#45099 Some tweaks for backtick strings
  src/compiler/transformers/taggedTemplate.ts
  src/compiler/utilities.ts
  tests/baselines/reference/templateLiteralsInTypes.errors.txt
  tests/baselines/reference/templateLiteralsInTypes.js
  tests/baselines/reference/templateLiteralsInTypes.symbols
  tests/baselines/reference/templateLiteralsInTypes.types
  tests/cases/compiler/templateLiteralsInTypes.ts
Labels: Author: Team, For Uncommitted Bug

#45313 Enable events on web server
  src/webServer/webServer.ts
Labels: For Uncommitted Bug

#45340 Fix completions in return when in function with contextual 'this'
  src/services/completions.ts
  tests/cases/fourslash/completionListInReturnWithContextualThis.ts
Labels: Author: Team, For Milestone Bug

#45148 Fix check for generic types in control flow analysis
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/controlFlowGenericTypes.errors.txt
  tests/baselines/reference/controlFlowGenericTypes.js
  tests/baselines/reference/controlFlowGenericTypes.symbols
  tests/baselines/reference/controlFlowGenericTypes.types
  tests/cases/conformance/controlFlow/controlFlowGenericTypes.ts
Labels: Author: Team, For Milestone Bug

#45185 Fix index signature assignability from optional properties in --exactOptionalPropertyTypes mode
  src/compiler/checker.ts
  tests/baselines/reference/strictOptionalProperties1.errors.txt
  tests/baselines/reference/strictOptionalProperties1.js
  tests/baselines/reference/strictOptionalProperties1.symbols
  tests/baselines/reference/strictOptionalProperties1.types
  tests/cases/compiler/strictOptionalProperties1.ts
Labels: Author: Team, For Milestone Bug

#45179 feat(45163): add QF to declare missing jsx attributes
  src/compiler/diagnosticMessages.json
  src/services/codefixes/fixAddMissingMember.ts
  tests/cases/fourslash/codeFixAddMissingAttributes1.ts
  tests/cases/fourslash/codeFixAddMissingAttributes2.ts
  tests/cases/fourslash/codeFixAddMissingAttributes3.ts
  tests/cases/fourslash/codeFixAddMissingAttributes4.ts
  tests/cases/fourslash/codeFixAddMissingAttributes5.ts
  tests/cases/fourslash/codeFixAddMissingAttributes6.ts
  tests/cases/fourslash/codeFixAddMissingAttributes7.ts
  tests/cases/fourslash/codeFixAddMissingAttributes_all.ts
Labels: For Uncommitted Bug

#44892 Improve error message TS1210
  src/compiler/binder.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/classStaticBlock6.errors.txt
  tests/baselines/reference/collisionArgumentsClassConstructor.errors.txt
  tests/baselines/reference/collisionArgumentsClassMethod.errors.txt
  tests/baselines/reference/emitArrowFunctionWhenUsingArguments12.errors.txt
  tests/baselines/reference/emitArrowFunctionWhenUsingArguments12_ES6.errors.txt
  tests/baselines/reference/jsFileCompilationBindStrictModeErrors.errors.txt
  tests/baselines/reference/parseClassDeclarationInStrictModeByDefaultInES6.errors.txt
  tests/baselines/reference/parserRealSource11.errors.txt
Labels: For Backlog Bug

#44936 Fix symbol display exception when handling incomplete class
  src/services/utilities.ts
  tests/baselines/reference/quickInfoDisplayPartsClassDefaultAnonymous.baseline
  tests/baselines/reference/quickInfoDisplayPartsClassDefaultNamed.baseline
  tests/baselines/reference/quickInfoDisplayPartsClassIncomplete.baseline
  tests/baselines/reference/quickInfoDisplayPartsFunctionIncomplete.baseline
  tests/cases/fourslash/quickInfoDisplayPartsClassDefaultAnonymous.ts
  tests/cases/fourslash/quickInfoDisplayPartsClassDefaultNamed.ts
  tests/cases/fourslash/quickInfoDisplayPartsClassIncomplete.ts
  tests/cases/fourslash/quickInfoDisplayPartsFunctionIncomplete.ts
Labels: Author: Team, For Uncommitted Bug

#45356 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210807171316989 to main
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45362 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210808111357949 to main
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45365 Fix typo in helpers.ts
  src/services/refactors/helpers.ts
Labels: For Uncommitted Bug

#45386 Fix __spreadArray for non-concat-spreadables
  src/compiler/factory/emitHelpers.ts
  tests/baselines/reference/argumentExpressionContextualTyping.js
  tests/baselines/reference/arrayLiteralExpressionContextualTyping.js
  tests/baselines/reference/arrayLiteralSpread.js
  tests/baselines/reference/arrayLiteralSpreadES5iterable.js
  tests/baselines/reference/arrayLiterals2ES5.js
  tests/baselines/reference/arrayLiterals3.js
  tests/baselines/reference/callChain.js
  tests/baselines/reference/callOverload.js
  tests/baselines/reference/callWithSpread.js
  tests/baselines/reference/callWithSpread2.js
  tests/baselines/reference/callWithSpread3.js
  tests/baselines/reference/callWithSpread5.js
  tests/baselines/reference/destructuringArrayBindingPatternAndAssignment1ES5.js
  tests/baselines/reference/destructuringArrayBindingPatternAndAssignment1ES5iterable.js
  tests/baselines/reference/destructuringArrayBindingPatternAndAssignment2.js
  tests/baselines/reference/destructuringParameterDeclaration3ES5iterable.js
  tests/baselines/reference/destructuringVariableDeclaration1ES5.js
  tests/baselines/reference/destructuringVariableDeclaration1ES5iterable.js
  tests/baselines/reference/excessiveStackDepthFlatArray.js
  tests/baselines/reference/excessivelyLargeTupleSpread.js
  tests/baselines/reference/functionParameterArityMismatch.js
  tests/baselines/reference/genericRestParameters1.js
  tests/baselines/reference/genericRestParameters2.js
  tests/baselines/reference/genericRestParameters3.js
  tests/baselines/reference/keyofAndIndexedAccess.js
  tests/baselines/reference/literalFreshnessPropagationOnNarrowing.js
  tests/baselines/reference/newWithSpread.js
  tests/baselines/reference/newWithSpreadES5.js
  tests/baselines/reference/noCrashOnNoLib.js
  tests/baselines/reference/operationsAvailableOnPromisedType.js
  tests/baselines/reference/readonlyRestParameters.js
  tests/baselines/reference/recursiveReverseMappedType.js
  tests/baselines/reference/recursiveTypeReferences1.js
  tests/baselines/reference/restTuplesFromContextualTypes.js
  tests/baselines/reference/selfReferencingSpreadInLoop.js
  tests/baselines/reference/spliceTuples.js
  tests/baselines/reference/spreadBooleanRespectsFreshness.js
  tests/baselines/reference/tsbuild/amdModulesWithOut/incremental-declaration-doesnt-change/multiple-emitHelpers-in-all-projects.js
  tests/baselines/reference/tsbuild/amdModulesWithOut/incremental-headers-change-without-dts-changes/multiple-emitHelpers-in-all-projects.js
  tests/baselines/reference/tsbuild/amdModulesWithOut/initial-build/multiple-emitHelpers-in-all-projects.js
  tests/baselines/reference/tsbuild/outfile-concat/incremental-declaration-doesnt-change/multiple-emitHelpers-in-all-projects.js
  tests/baselines/reference/tsbuild/outfile-concat/incremental-declaration-doesnt-change/multiple-emitHelpers-in-different-projects.js
  tests/baselines/reference/tsbuild/outfile-concat/incremental-headers-change-without-dts-changes/multiple-emitHelpers-in-all-projects.js
  tests/baselines/reference/tsbuild/outfile-concat/incremental-headers-change-without-dts-changes/multiple-emitHelpers-in-different-projects.js
  tests/baselines/reference/tsbuild/outfile-concat/initial-build/multiple-emitHelpers-in-all-projects.js
  tests/baselines/reference/tsbuild/outfile-concat/initial-build/multiple-emitHelpers-in-different-projects.js
  tests/baselines/reference/tsxEmit1.js
  tests/baselines/reference/tsxReactEmit1.js
  tests/baselines/reference/typedArrays-es5.js
  tests/baselines/reference/variadicTuples1.js
  tests/baselines/reference/variadicTuples2.js
Labels: Author: Team, For Uncommitted Bug

#45394 Use getFileAndProject in session provideInlayHints to ensure language service updates are applied
  src/server/session.ts
  src/testRunner/tsconfig.json
  src/testRunner/unittests/tsserver/inlayHints.ts
Labels: Author: Team, For Milestone Bug

#45352 fix(45345): noImplicitOverride doesn't work if member is defined in multiple interfaces
  src/compiler/checker.ts
  tests/baselines/reference/override20.errors.txt
  tests/baselines/reference/override20.js
  tests/baselines/reference/override20.symbols
  tests/baselines/reference/override20.types
  tests/cases/conformance/override/override20.ts
  tests/cases/fourslash/codeFixOverrideModifier22.ts
Labels: For Milestone Bug

#45399 fix(45393): show parameter name hints for unary literal expressions
  src/services/inlayHints.ts
  tests/cases/fourslash/inlayHintsShouldWork63.ts
Labels: For Uncommitted Bug

#45383 Update tsc-instrumented for project build
  Gulpfile.js
  src/harness/tsconfig.json
  src/instrumenter/instrumenter.ts
  src/loggedIO/loggedIO.ts
  src/loggedIO/tsconfig-tsc-instrumented.json
  src/loggedIO/tsconfig.json
  src/testRunner/tsconfig.json
Labels: Author: Team, For Uncommitted Bug

#45032 Fix unassignable properties by adding undefined with exactOptionalPropertyTypes
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/types.ts
  src/harness/fourslashImpl.ts
  src/services/codefixes/addMissingAwait.ts
  src/services/codefixes/addOptionalPropertyUndefined.ts
  src/services/tsconfig.json
  src/services/utilities.ts
  tests/baselines/reference/strictOptionalProperties1.errors.txt
  tests/baselines/reference/strictOptionalProperties1.js
  tests/baselines/reference/strictOptionalProperties1.symbols
  tests/baselines/reference/strictOptionalProperties1.types
  tests/cases/compiler/strictOptionalProperties1.ts
  tests/cases/fourslash/fixExactOptionalUnassignableProperties1.ts
  tests/cases/fourslash/fixExactOptionalUnassignableProperties10.ts
  tests/cases/fourslash/fixExactOptionalUnassignableProperties11.ts
  tests/cases/fourslash/fixExactOptionalUnassignableProperties12.ts
  tests/cases/fourslash/fixExactOptionalUnassignableProperties13.ts
  tests/cases/fourslash/fixExactOptionalUnassignableProperties14.ts
  tests/cases/fourslash/fixExactOptionalUnassignableProperties15.ts
  tests/cases/fourslash/fixExactOptionalUnassignableProperties16.ts
  tests/cases/fourslash/fixExactOptionalUnassignableProperties17.ts
  tests/cases/fourslash/fixExactOptionalUnassignableProperties18.ts
  tests/cases/fourslash/fixExactOptionalUnassignableProperties19.ts
  tests/cases/fourslash/fixExactOptionalUnassignableProperties3.ts
  tests/cases/fourslash/fixExactOptionalUnassignableProperties4.ts
  tests/cases/fourslash/fixExactOptionalUnassignableProperties5.ts
  tests/cases/fourslash/fixExactOptionalUnassignableProperties6.ts
  tests/cases/fourslash/fixExactOptionalUnassignableProperties7.ts
  tests/cases/fourslash/fixExactOptionalUnassignableProperties8.ts
  tests/cases/fourslash/fixExactOptionalUnassignableProperties9.ts
Labels: Author: Team, For Milestone Bug

#44695 fix(44694): nodeWillIndentChild judge for BinaryExpression with JsxElement child
  src/services/formatting/smartIndenter.ts
  tests/cases/fourslash/formatSelectionJsxWithBinaryExpression.ts
Labels: For Backlog Bug

#45444 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210813171329486 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45426 fix(45417): null and literal-like identifiers do not get inlay hints
  src/compiler/checker.ts
  src/compiler/utilities.ts
  src/services/classifier2020.ts
  src/services/inlayHints.ts
  tests/cases/fourslash/inlayHintsShouldWork64.ts
Labels: For Uncommitted Bug

#45342 fix(45233): export default can not be typed via jsdoc
  src/compiler/checker.ts
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment1.errors.txt
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment1.js
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment1.symbols
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment1.types
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment2.errors.txt
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment2.js
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment2.symbols
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment2.types
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment3.errors.txt
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment3.js
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment3.symbols
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment3.types
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment4.errors.txt
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment4.js
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment4.symbols
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment4.types
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment5.js
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment5.symbols
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment5.types
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment6.errors.txt
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment6.js
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment6.symbols
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment6.types
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment7.js
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment7.symbols
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment7.types
  tests/cases/compiler/checkJsdocTypeTagOnExportAssignment1.ts
  tests/cases/compiler/checkJsdocTypeTagOnExportAssignment2.ts
  tests/cases/compiler/checkJsdocTypeTagOnExportAssignment3.ts
  tests/cases/compiler/checkJsdocTypeTagOnExportAssignment4.ts
  tests/cases/compiler/checkJsdocTypeTagOnExportAssignment5.ts
  tests/cases/compiler/checkJsdocTypeTagOnExportAssignment6.ts
  tests/cases/compiler/checkJsdocTypeTagOnExportAssignment7.ts
Labels: For Milestone Bug

#45475 Enable `max-statements-per-line` lint rule
  .eslintrc.json
  scripts/processDiagnosticMessages.ts
  scripts/produceLKG.ts
  src/compiler/builder.ts
  src/compiler/builderState.ts
  src/compiler/checker.ts
  src/compiler/core.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/program.ts
  src/compiler/resolutionCache.ts
  src/compiler/sys.ts
  src/compiler/tsbuildPublic.ts
  src/compiler/utilities.ts
  src/harness/fourslashImpl.ts
  src/harness/harnessGlobals.ts
  src/harness/harnessIO.ts
  src/harness/harnessUtils.ts
  src/harness/typeWriter.ts
  src/harness/vfsUtil.ts
  src/server/project.ts
  src/services/codefixes/fixExpectedComma.ts
  src/services/codefixes/inferFromUsage.ts
  src/services/findAllReferences.ts
  src/services/organizeImports.ts
  src/services/services.ts
  src/services/shims.ts
  src/services/textChanges.ts
  src/services/utilities.ts
  src/testRunner/compilerRunner.ts
  src/testRunner/parallel/worker.ts
  src/testRunner/projectsRunner.ts
  src/testRunner/unittests/createMapShim.ts
  src/testRunner/unittests/createSetShim.ts
  src/testRunner/unittests/debugDeprecation.ts
  src/testRunner/unittests/services/colorization.ts
  src/testRunner/unittests/tsbuild/amdModulesWithOut.ts
  src/testRunner/unittests/tsbuild/outFile.ts
Labels: Author: Team, For Uncommitted Bug

#45474 Create SECURITY.md
  SECURITY.md
Labels: Author: Team, For Uncommitted Bug

#45305 fix(45294): Parameter inlay hints don't show for interpolated string when set to literals
  src/services/inlayHints.ts
  tests/cases/fourslash/inlayHintsShouldWork62.ts
Labels: For Backlog Bug

#44863 Expose getTypePredicateOfSignature
  src/compiler/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Uncommitted Bug

#44767 feat(43963): Deconstructed parameter are described as a var on hover
  src/services/utilities.ts
  tests/cases/fourslash/findAllReferencesDynamicImport3.ts
  tests/cases/fourslash/findAllRefsObjectBindingElementPropertyName04.ts
  tests/cases/fourslash/parameterWithDestructuring.ts
  tests/cases/fourslash/parameterWithNestedDestructuring.ts
  tests/cases/fourslash/quickInfoForContextuallyTypedIife.ts
Labels: For Backlog Bug

#44769 feat(18147): Extract function should remove uncessary parenthesis
  src/services/refactors/extractSymbol.ts
  tests/cases/fourslash/extract-const8.ts
  tests/cases/fourslash/extract-const9.ts
  tests/cases/fourslash/extract-method42.ts
  tests/cases/fourslash/extract-method43.ts
Labels: For Backlog Bug

#45025 Increase type instantiation depth limit
  src/compiler/checker.ts
  tests/baselines/reference/recursiveConditionalTypes.errors.txt
  tests/baselines/reference/recursiveConditionalTypes.js
  tests/baselines/reference/recursiveConditionalTypes.symbols
  tests/baselines/reference/recursiveConditionalTypes.types
  tests/cases/compiler/recursiveConditionalTypes.ts
Labels: Author: Team, For Uncommitted Bug

#45424 `getReferencesAtLocation`: fix handling of destructoring imports
  src/services/findAllReferences.ts
  tests/baselines/reference/findAllReferencesJsRequireDestructuring1.baseline.jsonc
  tests/cases/fourslash/findAllReferencesJsRequireDestructuring1.ts
Labels: Author: Team, For Backlog Bug

#45388 Reuse checker's property accessibility check for completions
  src/compiler/checker.ts
  src/compiler/types.ts
  src/services/completions.ts
  tests/cases/fourslash/completionsWrappedClass.ts
Labels: For Uncommitted Bug

#45007 support contextual return type of iife
  src/compiler/checker.ts
  tests/baselines/reference/contextualReturnTypeOfIIFE.js
  tests/baselines/reference/contextualReturnTypeOfIIFE.symbols
  tests/baselines/reference/contextualReturnTypeOfIIFE.types
  tests/baselines/reference/generatorTypeCheck27.symbols
  tests/baselines/reference/generatorTypeCheck27.types
  tests/baselines/reference/generatorTypeCheck29.symbols
  tests/baselines/reference/generatorTypeCheck29.types
  tests/baselines/reference/generatorTypeCheck30.symbols
  tests/baselines/reference/generatorTypeCheck30.types
  tests/baselines/reference/generatorTypeCheck31.errors.txt
  tests/baselines/reference/generatorTypeCheck31.types
  tests/baselines/reference/types.asyncGenerators.es2018.1.types
  tests/baselines/reference/types.asyncGenerators.es2018.2.errors.txt
  tests/baselines/reference/types.asyncGenerators.es2018.2.types
  tests/cases/compiler/contextualReturnTypeOfIIFE.ts
Labels: For Backlog Bug

#45084 feat(44720): Rename Symbol(F2) failed to rename the value in switch statement when operate on union of string literal
  src/services/findAllReferences.ts
  src/services/rename.ts
  src/services/utilities.ts
  tests/cases/fourslash/renameStringLiteralTypes3.ts
Labels: For Backlog Bug

#45507 Fix incorrect suggestion for package that bundles types
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/declarationNotFoundPackageBundlesTypes.errors.txt
  tests/baselines/reference/declarationNotFoundPackageBundlesTypes.js
  tests/baselines/reference/declarationNotFoundPackageBundlesTypes.symbols
  tests/baselines/reference/declarationNotFoundPackageBundlesTypes.types
  tests/cases/conformance/moduleResolution/declarationNotFoundPackageBundlesTypes.ts
Labels: For Milestone Bug

#44781 feat(16755): interface stubbing for anonymous implementations
  src/services/codefixes/fixAddMissingMember.ts
  tests/cases/fourslash/codeFixAddMissingProperties12.ts
  tests/cases/fourslash/codeFixAddMissingProperties13.ts
  tests/cases/fourslash/codeFixAddMissingProperties14.ts
  tests/cases/fourslash/codeFixAddMissingProperties_all.ts
Labels: For Backlog Bug

#45044 feat(44888): Don't show object property name completions when the originating type is a class with private or protected members
  src/services/completions.ts
  tests/cases/fourslash/completionInsideObjectLiteralExpressionWithInstantiatedClassType.ts
Labels: For Backlog Bug

#45020 fix for 45006
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/gettersAndSetters.errors.txt
  tests/baselines/reference/gettersAndSetters.js
  tests/baselines/reference/gettersAndSetters.symbols
  tests/baselines/reference/gettersAndSetters.types
  tests/cases/compiler/gettersAndSetters.ts
Labels: For Backlog Bug

#45554 Restore HTMLDocument constructable value in DOM
  src/lib/dom.generated.d.ts
  tests/baselines/reference/intersectionsOfLargeUnions2.errors.txt
  tests/baselines/reference/mappedTypeRecursiveInference.types
Labels: Author: Team, For Uncommitted Bug

#45391 Some cleanup around inlay hints types to get more-precise checking.
  src/harness/client.ts
  src/server/protocol.ts
  src/server/session.ts
  src/services/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Housekeeping, For Uncommitted Bug

#44324 Adds a script for removing unused diagnostics
  scripts/find-unused-diganostic-messages.mjs
  src/compiler/diagnosticMessages.json
Labels: Author: Team, For Uncommitted Bug

#45514 fix(45501): VS Code removes spaces between empty object literals even if insertSpaceAfterOpeningAndBeforeClosingEmptyBraces is true
  src/services/formatting/rules.ts
  tests/cases/fourslash/formattingNoSpaceBetweenEmptyBraceBrackets.ts
  tests/cases/fourslash/formattingSpaceBetweenEmptyBraceBrackets.ts
Labels: For Backlog Bug

#45431 Add rich navigation indexing action
  .github/workflow-resources/.lsifrc.json
  .github/workflows/rich-navigation.yml
Labels: For Uncommitted Bug

#45484 Fixed JS completions type spread
  src/services/completions.ts
  tests/cases/fourslash/getJavaScriptCompletions22.ts
Labels: For Milestone Bug

#45568 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210825000026362 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45464 Fix 'as const'-like behavior in JSDoc type cast
  src/compiler/checker.ts
  src/compiler/factory/utilities.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/jsdocTypeTagCast.errors.txt
  tests/baselines/reference/jsdocTypeTagCast.js
  tests/baselines/reference/jsdocTypeTagCast.symbols
  tests/baselines/reference/jsdocTypeTagCast.types
  tests/cases/conformance/jsdoc/jsdocTypeTagCast.ts
Labels: Author: Team, For Uncommitted Bug

#45615 Fix `verify.baselineCompletions` used in fourslash tests
  src/harness/fourslashImpl.ts
  tests/baselines/reference/completionEntryForUnionMethod.baseline
  tests/baselines/reference/completionsCommentsClassMembers.baseline
  tests/baselines/reference/completionsCommentsCommentParsing.baseline
  tests/baselines/reference/completionsCommentsFunctionDeclaration.baseline
  tests/baselines/reference/completionsCommentsFunctionExpression.baseline
  tests/baselines/reference/completionsJSDocTags.baseline
  tests/baselines/reference/completionsSalsaMethodsOnAssignedFunctionExpressions.baseline
Labels: For Uncommitted Bug

#43710 Update lib types to mark Annex B as deprecated
  src/harness/fourslashInterfaceImpl.ts
  src/lib/es2015.core.d.ts
  src/lib/es2019.string.d.ts
  src/lib/es5.d.ts
  tests/baselines/reference/completionsCommentsClass.baseline
  tests/baselines/reference/completionsCommentsClassMembers.baseline
  tests/baselines/reference/completionsCommentsCommentParsing.baseline
  tests/baselines/reference/completionsCommentsFunctionDeclaration.baseline
  tests/baselines/reference/completionsCommentsFunctionExpression.baseline
  tests/baselines/reference/completionsStringMethods.baseline
  tests/baselines/reference/destructuringParameterDeclaration4.errors.txt
  tests/baselines/reference/destructuringTuple.errors.txt
  tests/baselines/reference/duplicateNumericIndexers.errors.txt
  tests/baselines/reference/errorMessageOnObjectLiteralType.errors.txt
  tests/baselines/reference/externModule.errors.txt
  tests/baselines/reference/invalidTypeOfTarget.errors.txt
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty.errors.txt
  tests/baselines/reference/narrowExceptionVariableInCatchClause.errors.txt
  tests/baselines/reference/narrowFromAnyWithInstanceof.errors.txt
  tests/baselines/reference/narrowFromAnyWithTypePredicate.errors.txt
  tests/baselines/reference/objectTypeHidingMembersOfExtendedObject.errors.txt
  tests/baselines/reference/objectTypeWithStringIndexerHidingObjectIndexer.errors.txt
  tests/baselines/reference/parserMemberAccessAfterPostfixExpression1.errors.txt
  tests/baselines/reference/parserS7.2_A1.5_T2.errors.txt
  tests/baselines/reference/parserS7.3_A1.1_T2.errors.txt
  tests/baselines/reference/parserS7.6_A4.2_T1.errors.txt
  tests/baselines/reference/parserUnicode1.errors.txt
  tests/baselines/reference/promisePermutations.errors.txt
  tests/baselines/reference/promisePermutations2.errors.txt
  tests/baselines/reference/promisePermutations3.errors.txt
  tests/baselines/reference/redefineArray.errors.txt
  tests/baselines/reference/scannerS7.2_A1.5_T2.errors.txt
  tests/baselines/reference/scannerS7.3_A1.1_T2.errors.txt
  tests/baselines/reference/scannerS7.6_A4.2_T1.errors.txt
  tests/baselines/reference/taggedTemplateStringsWithOverloadResolution1.errors.txt
  tests/baselines/reference/taggedTemplateStringsWithOverloadResolution1_ES6.errors.txt
  tests/baselines/reference/taggedTemplateStringsWithOverloadResolution3_ES6.errors.txt
  tests/cases/fourslash/completionAfterGlobalThis.ts
  tests/cases/fourslash/completionListAfterRegularExpressionLiteral01.ts
  tests/cases/fourslash/completionListAfterRegularExpressionLiteral1.ts
  tests/cases/fourslash/completionListAfterStringLiteral1.ts
  tests/cases/fourslash/completionsStringMethods.ts
  tests/cases/fourslash/getJavaScriptCompletions18.ts
  tests/cases/fourslash/getJavaScriptCompletions19.ts
  tests/cases/fourslash/getJavaScriptQuickInfo8.ts
  tests/cases/fourslash/javaScriptClass1.ts
  tests/cases/fourslash/javaScriptClass4.ts
  tests/cases/fourslash/javaScriptPrototype1.ts
  tests/cases/fourslash/jsDocFunctionSignatures3.ts
Labels: For Milestone Bug, For Backlog Bug

#45642 Close package json watches in watch mode on close
  src/compiler/watchPublic.ts
  tests/baselines/reference/tscWatch/incremental/editing-module-augmentation-watch.js
  tests/baselines/reference/tscWatch/incremental/importHelpers-backing-types-removed-watch.js
  tests/baselines/reference/tscWatch/incremental/jsxImportSource-backing-types-removed-watch.js
  tests/baselines/reference/tscWatch/incremental/jsxImportSource-option-changed-watch.js
Labels: Author: Team, For Milestone Bug
