Repository microsoft/TypeScript, pull requests merged in 2021-05, with the labels that each got.

#43914 Use options from referenced project for including resolved imports in the file when using sources of project reference
  src/compiler/program.ts
  src/testRunner/unittests/tsserver/projectReferences.ts
Labels: Author: Team, For Milestone Bug

#43959 fix(43957): Add 'override' quick fix results in broken ordering
  src/services/codefixes/fixOverrideModifier.ts
  tests/cases/fourslash/codeFixOverrideModifier19.ts
  tests/cases/fourslash/codeFixOverrideModifier20.ts
Labels: For Uncommitted Bug

#43888 Unwrap substitutions on conditional check types before comparing them
  src/compiler/checker.ts
  tests/baselines/reference/curiousNestedConditionalEvaluationResult.js
  tests/baselines/reference/curiousNestedConditionalEvaluationResult.symbols
  tests/baselines/reference/curiousNestedConditionalEvaluationResult.types
  tests/cases/compiler/curiousNestedConditionalEvaluationResult.ts
Labels: Author: Team, For Milestone Bug

#43763 Allow filterType to consider union constraints of non-union types when determining never-ness
  src/compiler/checker.ts
  src/compiler/watch.ts
  tests/baselines/reference/quickinfoTypeAtReturnPositionsInaccurate.errors.txt
  tests/baselines/reference/quickinfoTypeAtReturnPositionsInaccurate.js
  tests/baselines/reference/quickinfoTypeAtReturnPositionsInaccurate.symbols
  tests/baselines/reference/quickinfoTypeAtReturnPositionsInaccurate.types
  tests/cases/compiler/quickinfoTypeAtReturnPositionsInaccurate.ts
Labels: Author: Team, For Milestone Bug

#43895 Fix typo in system.ts
  src/compiler/transformers/module/system.ts
Labels: For Uncommitted Bug

#43944 fix(43939): Quick fix shouldn't be available for converting getters to async await
  src/services/codefixes/convertToAsyncFunction.ts
  src/services/suggestionDiagnostics.ts
  src/testRunner/unittests/services/convertToAsyncFunction.ts
Labels: For Uncommitted Bug

#43974 When directory watcher is invoked with any file from node_modules package, invalidate for file paths in that package
  src/compiler/moduleNameResolver.ts
  src/compiler/resolutionCache.ts
  src/testRunner/unittests/tscWatch/resolutionCache.ts
  tests/baselines/reference/tscWatch/resolutionCache/works-when-installing-something-in-node_modules-or-@types-when-there-is-no-notification-from-fs-for-index-file.js
Labels: Author: Team, For Milestone Bug

#43969 Dont allow namespace reexport symbols when looking up valid local names
  src/compiler/checker.ts
  src/compiler/utilities.ts
  tests/baselines/reference/declarationEmitDoesNotUseReexportedNamespaceAsLocal.js
  tests/baselines/reference/declarationEmitDoesNotUseReexportedNamespaceAsLocal.symbols
  tests/baselines/reference/declarationEmitDoesNotUseReexportedNamespaceAsLocal.types
  tests/baselines/reference/exportAsNamespace1(module=amd).types
  tests/baselines/reference/exportAsNamespace1(module=commonjs).types
  tests/baselines/reference/exportAsNamespace1(module=es2015).types
  tests/baselines/reference/exportAsNamespace1(module=esnext).types
  tests/baselines/reference/exportAsNamespace1(module=system).types
  tests/baselines/reference/exportAsNamespace1(module=umd).types
  tests/baselines/reference/exportAsNamespace2(module=amd).types
  tests/baselines/reference/exportAsNamespace2(module=commonjs).types
  tests/baselines/reference/exportAsNamespace2(module=es2015).types
  tests/baselines/reference/exportAsNamespace2(module=esnext).types
  tests/baselines/reference/exportAsNamespace2(module=system).types
  tests/baselines/reference/exportAsNamespace2(module=umd).types
  tests/baselines/reference/exportNamespace2.types
  tests/baselines/reference/exportNamespace3.types
  tests/baselines/reference/exportNamespace4.types
  tests/baselines/reference/exportStarNotElided.types
  tests/baselines/reference/importHelpersWithExportStarAs(esmoduleinterop=false,module=amd).types
  tests/baselines/reference/importHelpersWithExportStarAs(esmoduleinterop=false,module=commonjs).types
  tests/baselines/reference/importHelpersWithExportStarAs(esmoduleinterop=false,module=es2015).types
  tests/baselines/reference/importHelpersWithExportStarAs(esmoduleinterop=false,module=es2020).types
  tests/baselines/reference/importHelpersWithExportStarAs(esmoduleinterop=false,module=system).types
  tests/baselines/reference/importHelpersWithExportStarAs(esmoduleinterop=true,module=amd).types
  tests/baselines/reference/importHelpersWithExportStarAs(esmoduleinterop=true,module=commonjs).types
  tests/baselines/reference/importHelpersWithExportStarAs(esmoduleinterop=true,module=es2015).types
  tests/baselines/reference/importHelpersWithExportStarAs(esmoduleinterop=true,module=es2020).types
  tests/baselines/reference/importHelpersWithExportStarAs(esmoduleinterop=true,module=system).types
  tests/cases/compiler/declarationEmitDoesNotUseReexportedNamespaceAsLocal.ts
Labels: Author: Team, For Milestone Bug

#43983 Revert "typeRelatedToSomeType passes through intersectionState (#43707)"
  src/compiler/checker.ts
  tests/baselines/reference/recursiveExcessPropertyChecks.js
  tests/baselines/reference/recursiveExcessPropertyChecks.symbols
  tests/baselines/reference/recursiveExcessPropertyChecks.types
  tests/cases/compiler/recursiveExcessPropertyChecks.ts
Labels: Author: Team, For Uncommitted Bug

#43949 Fix perf regression from #42556
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug

#43967 Improve errors for incorrectly nested export default
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/services/findAllReferences.ts
  src/services/importTracker.ts
  src/services/symbolDisplay.ts
  tests/baselines/reference/moduleElementsInWrongContext.errors.txt
  tests/baselines/reference/moduleElementsInWrongContext2.errors.txt
  tests/baselines/reference/moduleElementsInWrongContext3.errors.txt
  tests/baselines/reference/quickInfoNestedExportEqualExportDefault.baseline
  tests/cases/fourslash/documentHighlights_40082.ts
  tests/cases/fourslash/quickInfoNestedExportEqualExportDefault.ts
Labels: Author: Team, For Milestone Bug

#43986 Correctly use ownMap from module resolution cache
  src/compiler/moduleNameResolver.ts
  src/testRunner/unittests/tsbuild/watchMode.ts
  tests/baselines/reference/tsbuild/watchMode/moduleResolutionCache/handles-the-cache-correctly-when-two-projects-use-different-module-resolution-settings.js
Labels: Author: Team, For Uncommitted Bug

#43998 Remove accidentally added file in baselines
  tests/baselines/tj.json
Labels: Author: Team, For Uncommitted Bug

#43984 Add writeFile and customTransformers to build and buildReferences
  src/compiler/tsbuildPublic.ts
  src/testRunner/tsconfig.json
  src/testRunner/unittests/tsbuild/publicApi.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/tsbuild/$publicAPI/initial-build/build-with-custom-transformers.js
Labels: Author: Team, For Uncommitted Bug

#44002 Don't eagerly get apparent type of spread expression contextual type
  src/compiler/checker.ts
  tests/baselines/reference/spreadExpressionContextualType.js
  tests/baselines/reference/spreadExpressionContextualType.symbols
  tests/baselines/reference/spreadExpressionContextualType.types
  tests/cases/compiler/spreadExpressionContextualType.ts
Labels: Author: Team, For Milestone Bug

#44010 Update diagnostic message and quickfix for parameter property
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/services/codefixes/fixOverrideModifier.ts
  tests/baselines/reference/override6.errors.txt
  tests/baselines/reference/override8.errors.txt
  tests/baselines/reference/overrideParameterProperty.errors.txt
  tests/baselines/reference/overrideParameterProperty.js
  tests/baselines/reference/overrideParameterProperty.symbols
  tests/baselines/reference/overrideParameterProperty.types
  tests/cases/conformance/override/overrideParameterProperty.ts
  tests/cases/fourslash/codeFixOverrideModifier10.ts
  tests/cases/fourslash/codeFixOverrideModifier21.ts
  tests/cases/fourslash/codeFixOverrideModifier9.ts
Labels: For Uncommitted Bug

#44008 Test for Update the type reference cache with correct project options
  src/testRunner/unittests/tsbuild/moduleResolution.ts
  tests/baselines/reference/tsbuild/moduleResolution/initial-build/type-reference-resolution-uses-correct-options-for-different-resolution-options-referenced-project.js
Labels: Author: Team, For Uncommitted Bug

#44028 Bump version to 4.4.
  package.json
  src/compiler/corePublic.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Uncommitted Bug

#43933 fix(43030): undefined[] converted to any[] in JS
  src/compiler/checker.ts
  tests/baselines/reference/typeFromJSInitializer.errors.txt
  tests/baselines/reference/typeFromJSInitializer.symbols
  tests/baselines/reference/typeFromJSInitializer.types
  tests/baselines/reference/typeFromJSInitializer2.symbols
  tests/baselines/reference/typeFromJSInitializer2.types
  tests/baselines/reference/typeFromJSInitializer3.symbols
  tests/baselines/reference/typeFromJSInitializer3.types
  tests/baselines/reference/typeFromJSInitializer4.errors.txt
  tests/baselines/reference/typeFromJSInitializer4.symbols
  tests/baselines/reference/typeFromJSInitializer4.types
  tests/cases/conformance/salsa/typeFromJSInitializer.ts
  tests/cases/conformance/salsa/typeFromJSInitializer2.ts
  tests/cases/conformance/salsa/typeFromJSInitializer3.ts
  tests/cases/conformance/salsa/typeFromJSInitializer4.ts
Labels: For Backlog Bug

#43886 fix(43879): `for ( async of` should be a syntax error
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/for-inStatementsAsyncIdentifier.js
  tests/baselines/reference/for-inStatementsAsyncIdentifier.symbols
  tests/baselines/reference/for-inStatementsAsyncIdentifier.types
  tests/baselines/reference/parserForOfStatement22.errors.txt
  tests/baselines/reference/parserForOfStatement22.js
  tests/baselines/reference/parserForOfStatement22.symbols
  tests/baselines/reference/parserForOfStatement22.types
  tests/baselines/reference/parserForOfStatement23.js
  tests/baselines/reference/parserForOfStatement23.symbols
  tests/baselines/reference/parserForOfStatement23.types
  tests/baselines/reference/parserForOfStatement24.js
  tests/baselines/reference/parserForOfStatement24.symbols
  tests/baselines/reference/parserForOfStatement24.types
  tests/cases/conformance/parser/ecmascript6/Iterators/parserForOfStatement22.ts
  tests/cases/conformance/parser/ecmascript6/Iterators/parserForOfStatement23.ts
  tests/cases/conformance/parser/ecmascript6/Iterators/parserForOfStatement24.ts
  tests/cases/conformance/statements/for-inStatements/for-inStatementsAsyncIdentifier.ts
Labels: For Backlog Bug

#43610 Loosen up the first argument type for `String.raw`
  src/lib/es2015.core.d.ts
  tests/baselines/reference/stringRawType.js
  tests/baselines/reference/stringRawType.symbols
  tests/baselines/reference/stringRawType.types
  tests/cases/compiler/stringRawType.ts
Labels: Author: Team, For Uncommitted Bug

#43973 Cache accessibe symbol chains and serialized type parameter name generation
  src/compiler/checker.ts
  src/compiler/transformers/declarations.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/harness/compilerImpl.ts
  src/services/codefixes/helpers.ts
  src/services/utilities.ts
  tests/baselines/reference/declarationEmitPrivatePromiseLikeInterface.errors.txt
  tests/baselines/reference/declarationEmitPrivatePromiseLikeInterface.js
  tests/baselines/reference/declarationsWithRecursiveInternalTypesProduceUniqueTypeParams.types
  tests/cases/compiler/declarationEmitPrivatePromiseLikeInterface.ts
Labels: Author: Team, For Milestone Bug

#43930 Fix typo in host.ts
  src/testRunner/parallel/host.ts
Labels: For Uncommitted Bug

#44081 Don't allow generic narrowing when contextually typed by a binding pattern
  src/compiler/checker.ts
  tests/baselines/reference/genericObjectSpreadResultInSwitch.js
  tests/baselines/reference/genericObjectSpreadResultInSwitch.symbols
  tests/baselines/reference/genericObjectSpreadResultInSwitch.types
  tests/baselines/reference/restInvalidArgumentType.types
  tests/cases/compiler/genericObjectSpreadResultInSwitch.ts
Labels: Author: Team, For Milestone Bug

#44124 Simplify codeql github action
  .github/workflows/codeql.yml
Labels: Author: Team, For Uncommitted Bug, Housekeeping

#44125 Don’t offer import statement completions at `from` position
  src/services/completions.ts
  tests/cases/fourslash/importStatementCompletions1.ts
Labels: Author: Team, For Uncommitted Bug

#44031 Generate SourceMap mappings string using array of character codes and fewer String.fromCharCode calls
  src/compiler/sourcemap.ts
Labels: For Milestone Bug

#44104 `skipParenthesesUp()` is exactly the same as `walkUpParenthesizedExpressions()`
  src/compiler/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#43880 fix(43796): Sort @deprecated completions lower than others
  src/services/completions.ts
  src/services/symbolDisplay.ts
  src/services/utilities.ts
  tests/cases/fourslash/completionsWithDeprecatedTag1.ts
  tests/cases/fourslash/completionsWithDeprecatedTag10.ts
  tests/cases/fourslash/completionsWithDeprecatedTag2.ts
  tests/cases/fourslash/completionsWithDeprecatedTag3.ts
  tests/cases/fourslash/completionsWithDeprecatedTag4.ts
  tests/cases/fourslash/completionsWithDeprecatedTag5.ts
  tests/cases/fourslash/completionsWithDeprecatedTag6.ts
  tests/cases/fourslash/completionsWithDeprecatedTag7.ts
  tests/cases/fourslash/completionsWithDeprecatedTag8.ts
  tests/cases/fourslash/completionsWithDeprecatedTag9.ts
  tests/cases/fourslash/fourslash.ts
Labels: For Milestone Bug

#44015 fix(43799): Support bigint type for Intl.NumberFormat.formatToParts
  src/lib/esnext.intl.d.ts
  tests/baselines/reference/formatToPartsBigInt.js
  tests/baselines/reference/formatToPartsBigInt.symbols
  tests/baselines/reference/formatToPartsBigInt.types
  tests/cases/compiler/formatToPartsBigInt.ts
Labels: For Backlog Bug

#43627 Improve docstring for array fill methods
  src/lib/es2015.core.d.ts
  src/lib/es2020.bigint.d.ts
  src/lib/es5.d.ts
Labels: For Backlog Bug

#44042 Fix logic for determining whether to simplify keyof on mapped types
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypeAsClauses.errors.txt
  tests/baselines/reference/mappedTypeAsClauses.js
  tests/baselines/reference/mappedTypeAsClauses.symbols
  tests/baselines/reference/mappedTypeAsClauses.types
  tests/cases/conformance/types/mapped/mappedTypeAsClauses.ts
Labels: Author: Team, For Milestone Bug

#44122 Preserve generics in contextual types for rest arguments
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/controlFlowGenericTypes.errors.txt
  tests/baselines/reference/controlFlowGenericTypes.js
  tests/baselines/reference/controlFlowGenericTypes.symbols
  tests/baselines/reference/controlFlowGenericTypes.types
  tests/cases/conformance/controlFlow/controlFlowGenericTypes.ts
Labels: Author: Team, For Milestone Bug

#44175 Revert #43460 and #40884
  src/compiler/diagnosticMessages.json
  src/compiler/parser.ts
  tests/baselines/reference/constructorWithIncompleteTypeAnnotation.errors.txt
  tests/baselines/reference/errorRecoveryWithDotFollowedByNamespaceKeyword.errors.txt
  tests/baselines/reference/missingCloseBracketInArray.errors.txt
  tests/baselines/reference/missingCloseBracketInArray.js
  tests/baselines/reference/missingCloseBracketInArray.symbols
  tests/baselines/reference/missingCloseBracketInArray.types
  tests/baselines/reference/missingCloseParenStatements.errors.txt
  tests/baselines/reference/missingCloseParenStatements.js
  tests/baselines/reference/missingCloseParenStatements.symbols
  tests/baselines/reference/missingCloseParenStatements.types
  tests/baselines/reference/nestedClassDeclaration.errors.txt
  tests/baselines/reference/objectLiteralWithSemicolons4.errors.txt
  tests/baselines/reference/objectSpreadNegativeParse.errors.txt
  tests/baselines/reference/parseErrorIncorrectReturnToken.errors.txt
  tests/baselines/reference/parserErrorRecoveryIfStatement2.errors.txt
  tests/baselines/reference/parserErrorRecoveryIfStatement3.errors.txt
  tests/baselines/reference/parserFuzz1.errors.txt
  tests/baselines/reference/reservedWords2.errors.txt
  tests/baselines/reference/tsbuild/noEmitOnError/initial-build/syntax-errors-with-incremental.js
  tests/baselines/reference/tsbuild/noEmitOnError/initial-build/syntax-errors.js
  tests/baselines/reference/tsbuild/watchMode/noEmitOnError/does-not-emit-any-files-on-error-with-incremental.js
  tests/baselines/reference/tsbuild/watchMode/noEmitOnError/does-not-emit-any-files-on-error.js
  tests/baselines/reference/tsc/incremental/initial-build/with-noEmitOnError-syntax-errors.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependencies/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependencies/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependenciesAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependenciesAndD/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/default/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/default/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/defaultAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/defaultAndD/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/assumeChangesOnlyAffectDirectDependencies/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/assumeChangesOnlyAffectDirectDependencies/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/assumeChangesOnlyAffectDirectDependenciesAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/assumeChangesOnlyAffectDirectDependenciesAndD/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/default/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/default/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/defaultAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/defaultAndD/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/isolatedModules/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/isolatedModules/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/isolatedModulesAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/isolatedModulesAndD/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModules/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModules/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModulesAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModulesAndD/with-noEmitOnError.js
  tests/baselines/reference/typeAssertions.errors.txt
  tests/cases/compiler/missingCloseBracketInArray.ts
  tests/cases/compiler/missingCloseParenStatements.ts
  tests/cases/conformance/parser/ecmascript5/ErrorRecovery/ArrayLiteralExpressions/parserErrorRecoveryArrayLiteralExpression3.ts
Labels: Author: Team, For Uncommitted Bug

#44083 Fix the code that checks for variadic signatures
  src/services/signatureHelp.ts
  tests/cases/fourslash/jsSignature-41059.ts
Labels: Author: Team, For Uncommitted Bug

#43615 Error for abstract property with initialiser
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/abstractPropertyInitializer.errors.txt
  tests/baselines/reference/abstractPropertyInitializer.js
  tests/baselines/reference/abstractPropertyInitializer.symbols
  tests/baselines/reference/abstractPropertyInitializer.types
  tests/baselines/reference/accessorsOverrideProperty7.errors.txt
  tests/baselines/reference/privateNamesIncompatibleModifiers.errors.txt
  tests/cases/conformance/classes/propertyMemberDeclarations/abstractPropertyInitializer.ts
Labels: Author: Team, For Milestone Bug

#43905 fix(WeakMapConstructor): readonly iterable items
  src/lib/es2015.iterable.d.ts
Labels: For Backlog Bug

#43780 Improve parser recovery for unclosed/mismatched JSX elements
  src/compiler/parser.ts
  src/harness/fourslashImpl.ts
  tests/baselines/reference/jsFileCompilationTypeArgumentSyntaxOfCall.errors.txt
  tests/baselines/reference/jsxAndTypeAssertion.js
  tests/baselines/reference/jsxAndTypeAssertion.types
  tests/baselines/reference/jsxInvalidEsprimaTestSuite.errors.txt
  tests/baselines/reference/jsxParsingError2.errors.txt
  tests/baselines/reference/jsxParsingError2.js
  tests/baselines/reference/jsxParsingError2.types
  tests/baselines/reference/jsxUnclosedParserRecovery.errors.txt
  tests/baselines/reference/jsxUnclosedParserRecovery.js
  tests/baselines/reference/jsxUnclosedParserRecovery.symbols
  tests/baselines/reference/jsxUnclosedParserRecovery.types
  tests/cases/conformance/jsx/jsxUnclosedParserRecovery.ts
Labels: Author: Team, For Milestone Bug

#44149 Correct path segment regex
  src/compiler/path.ts
Labels: Author: Team, For Uncommitted Bug

#43635 Fix regression no codefix for ts2657
  src/services/codefixes/wrapJsxInFragment.ts
  tests/cases/fourslash/codeFixWrapJsxInFragment3.ts
  tests/cases/fourslash/codeFixWrapJsxInFragment4.ts
Labels: For Backlog Bug

#44177 Revert #43460 and #40884 (#44175)
  src/compiler/diagnosticMessages.json
  src/compiler/parser.ts
  tests/baselines/reference/constructorWithIncompleteTypeAnnotation.errors.txt
  tests/baselines/reference/errorRecoveryWithDotFollowedByNamespaceKeyword.errors.txt
  tests/baselines/reference/missingCloseBracketInArray.errors.txt
  tests/baselines/reference/missingCloseBracketInArray.js
  tests/baselines/reference/missingCloseBracketInArray.symbols
  tests/baselines/reference/missingCloseBracketInArray.types
  tests/baselines/reference/missingCloseParenStatements.errors.txt
  tests/baselines/reference/missingCloseParenStatements.js
  tests/baselines/reference/missingCloseParenStatements.symbols
  tests/baselines/reference/missingCloseParenStatements.types
  tests/baselines/reference/nestedClassDeclaration.errors.txt
  tests/baselines/reference/objectLiteralWithSemicolons4.errors.txt
  tests/baselines/reference/objectSpreadNegativeParse.errors.txt
  tests/baselines/reference/parseErrorIncorrectReturnToken.errors.txt
  tests/baselines/reference/parserErrorRecoveryIfStatement2.errors.txt
  tests/baselines/reference/parserErrorRecoveryIfStatement3.errors.txt
  tests/baselines/reference/parserFuzz1.errors.txt
  tests/baselines/reference/reservedWords2.errors.txt
  tests/baselines/reference/tsbuild/noEmitOnError/initial-build/syntax-errors-with-incremental.js
  tests/baselines/reference/tsbuild/noEmitOnError/initial-build/syntax-errors.js
  tests/baselines/reference/tsbuild/watchMode/noEmitOnError/does-not-emit-any-files-on-error-with-incremental.js
  tests/baselines/reference/tsbuild/watchMode/noEmitOnError/does-not-emit-any-files-on-error.js
  tests/baselines/reference/tsc/incremental/initial-build/with-noEmitOnError-syntax-errors.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependencies/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependencies/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependenciesAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependenciesAndD/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/default/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/default/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/defaultAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/defaultAndD/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/assumeChangesOnlyAffectDirectDependencies/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/assumeChangesOnlyAffectDirectDependencies/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/assumeChangesOnlyAffectDirectDependenciesAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/assumeChangesOnlyAffectDirectDependenciesAndD/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/default/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/default/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/defaultAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/defaultAndD/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/isolatedModules/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/isolatedModules/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/isolatedModulesAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/isolatedModulesAndD/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModules/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModules/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModulesAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModulesAndD/with-noEmitOnError.js
  tests/baselines/reference/typeAssertions.errors.txt
  tests/cases/compiler/missingCloseBracketInArray.ts
  tests/cases/compiler/missingCloseParenStatements.ts
  tests/cases/conformance/parser/ecmascript5/ErrorRecovery/ArrayLiteralExpressions/parserErrorRecoveryArrayLiteralExpression3.ts
Labels: Author: Team, For Uncommitted Bug

#44186 Move class name capture for private state after declaration evaluates
  src/compiler/transformers/classFields.ts
  tests/baselines/reference/privateNameComputedPropertyName4(target=es2015).js
  tests/baselines/reference/privateNameComputedPropertyName4(target=esnext).js
  tests/cases/conformance/classes/members/privateNames/privateNameComputedPropertyName4.ts
Labels: Author: Team, For Milestone Bug

#44184 Private identifiers use standard identifier scanning
  src/compiler/scanner.ts
  tests/baselines/reference/extendedUnicodePlaneIdentifiers.js
  tests/baselines/reference/extendedUnicodePlaneIdentifiers.symbols
  tests/baselines/reference/extendedUnicodePlaneIdentifiers.types
  tests/cases/compiler/extendedUnicodePlaneIdentifiers.ts
Labels: Author: Team, For Uncommitted Bug

#44150 Add jsdoc member names: Class#method
  src/compiler/checker.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/factory/nodeTests.ts
  src/compiler/parser.ts
  src/compiler/scanner.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/services/findAllReferences.ts
  src/services/utilities.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/findAllReferencesLinkTag1.baseline.jsonc
  tests/baselines/reference/findAllReferencesLinkTag2.baseline.jsonc
  tests/baselines/reference/jsdocLink1.baseline
  tests/baselines/reference/jsdocLink2.baseline
  tests/baselines/reference/jsdocLink3.baseline
  tests/cases/fourslash/findAllReferencesLinkTag1.ts
  tests/cases/fourslash/findAllReferencesLinkTag2.ts
  tests/cases/fourslash/jsDocSee4.ts
Labels: Author: Team, For Milestone Bug

#44100 Avoid calling replace in normalizeSlashes when it would do nothing
  src/compiler/path.ts
Labels: Author: Team, For Uncommitted Bug

#43592 support QualifiedName when narrowing inside loops
  src/compiler/binder.ts
  src/compiler/checker.ts
  tests/baselines/reference/narrowingOfQualifiedNames.errors.txt
  tests/baselines/reference/narrowingOfQualifiedNames.js
  tests/baselines/reference/narrowingOfQualifiedNames.symbols
  tests/baselines/reference/narrowingOfQualifiedNames.types
  tests/cases/compiler/narrowingOfQualifiedNames.ts
Labels: For Backlog Bug

#44109 fix: internal createSignature declaration could be undefined
  src/compiler/types.ts
  src/services/codefixes/inferFromUsage.ts
Labels: For Uncommitted Bug, Housekeeping

#44173 Kick out of normalizePath if there's nothing to do
  src/compiler/path.ts
Labels: Author: Team, For Uncommitted Bug

#44106 Avoid `convertExport` when there's a non-identifier or a bogus one
  src/compiler/diagnosticMessages.json
  src/services/refactors/convertExport.ts
  tests/cases/fourslash/refactorConvertExport_onlyValidIdentifiers.ts
Labels: Author: Team, For Uncommitted Bug

#44208 Add @linkcode and @linkplain tags
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/factory/nodeTests.ts
  src/compiler/parser.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/compiler/utilitiesPublic.ts
  src/services/codefixes/inferFromUsage.ts
  src/services/jsDoc.ts
  src/services/utilities.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/findAllReferencesLinkTag3.baseline.jsonc
  tests/baselines/reference/quickInfoLinkCodePlain.baseline
  tests/cases/fourslash/findAllReferencesLinkTag3.ts
  tests/cases/fourslash/quickInfoLinkCodePlain.ts
Labels: Author: Team, For Milestone Bug

#44207 Implement a two-way mirroring between the wiki and its public repo
  .github/workflows/sync-wiki.yml
Labels: Author: Team, For Uncommitted Bug

#44129 Ensure static index signatures have an errorNode available
  src/compiler/checker.ts
  tests/baselines/reference/staticIndexSignature3.errors.txt
  tests/baselines/reference/staticIndexSignatureAndNormalIndexSignature.js
  tests/baselines/reference/staticIndexSignatureAndNormalIndexSignature.symbols
  tests/baselines/reference/staticIndexSignatureAndNormalIndexSignature.types
  tests/cases/compiler/staticIndexSignatureAndNormalIndexSignature.ts
Labels: Author: Team, For Milestone Bug

#44197 Simplify or optimize regexes with polynomial time worst cases
  src/compiler/commandLineParser.ts
  src/compiler/core.ts
  src/compiler/debug.ts
  src/compiler/parser.ts
  src/compiler/program.ts
  src/compiler/scanner.ts
  src/compiler/semver.ts
  src/compiler/sourcemap.ts
  src/compiler/utilities.ts
  src/services/classifier.ts
  src/services/outliningElementsCollector.ts
Labels: Author: Team, For Uncommitted Bug

#44235 don't duplicate function properties when emiting definitions of overl…
  src/compiler/transformers/declarations.ts
  tests/baselines/reference/declarationEmitFunctionDuplicateNamespace.js
  tests/baselines/reference/declarationEmitFunctionDuplicateNamespace.symbols
  tests/baselines/reference/declarationEmitFunctionDuplicateNamespace.types
  tests/cases/compiler/declarationEmitFunctionDuplicateNamespace.ts
Labels: For Milestone Bug

#44219 Properly remove generic types that are constrained to 'null | undefined' in getNonNullableType
  src/compiler/checker.ts
  tests/baselines/reference/nonNullableReduction.js
  tests/baselines/reference/nonNullableReduction.symbols
  tests/baselines/reference/nonNullableReduction.types
  tests/baselines/reference/nonNullableReductionNonStrict.js
  tests/baselines/reference/nonNullableReductionNonStrict.symbols
  tests/baselines/reference/nonNullableReductionNonStrict.types
  tests/cases/compiler/nonNullableReduction.ts
  tests/cases/compiler/nonNullableReductionNonStrict.ts
Labels: Author: Team, For Milestone Bug

#44258 Refactor tsbuild watch tests
  src/testRunner/tsconfig.json
  src/testRunner/unittests/tsbuildWatch/configFileErrors.ts
  src/testRunner/unittests/tsbuildWatch/demo.ts
  src/testRunner/unittests/tsbuildWatch/moduleResolution.ts
  src/testRunner/unittests/tsbuildWatch/noEmitOnError.ts
  src/testRunner/unittests/tsbuildWatch/programUpdates.ts
  src/testRunner/unittests/tsbuildWatch/reexport.ts
  src/testRunner/unittests/tsbuildWatch/watchEnvironment.ts
Labels: Author: Team, For Uncommitted Bug

#44213 feat(44190): Attempt to find misspelled base members in override checks
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/override15.errors.txt
  tests/baselines/reference/override15.js
  tests/baselines/reference/override15.symbols
  tests/baselines/reference/override15.types
  tests/cases/conformance/override/override15.ts
Labels: For Uncommitted Bug

#44078 Cache parsed path mapping patterns
  src/compiler/binder.ts
  src/compiler/commandLineParser.ts
  src/compiler/moduleNameResolver.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/services/stringCompletions.ts
Labels: Author: Team, For Uncommitted Bug

#44202 Add unqualified JSDoc member references
  src/compiler/checker.ts
  tests/baselines/reference/findAllReferencesLinkTag1.baseline.jsonc
Labels: Author: Team, For Milestone Bug

#44252 fix(44249): JSX: "extract to constant" generates invalid code when using fragment syntax
  src/services/refactors/extractSymbol.ts
  tests/cases/fourslash/extract-const_insideJsxFragment1.ts
Labels: For Milestone Bug

#44275 Use correct state when getting it from redirected program
  src/compiler/builder.ts
  src/compiler/builderPublic.ts
  tests/baselines/reference/tsbuild/watchMode/programUpdates/reportErrors/declarationEmitErrors/introduceError/when-file-with-no-error-changes.js
  tests/baselines/reference/tsbuild/watchMode/programUpdates/reportErrors/declarationEmitErrors/introduceError/when-fixing-errors-only-changed-file-is-emitted.js
  tests/baselines/reference/tsbuild/watchMode/programUpdates/reportErrors/declarationEmitErrors/when-file-with-no-error-changes.js
  tests/baselines/reference/tsbuild/watchMode/programUpdates/reportErrors/declarationEmitErrors/when-fixing-error-files-all-files-are-emitted.js
Labels: Author: Team, For Uncommitted Bug

#44277 Fix outFile check
  src/compiler/watchUtilities.ts
Labels: Author: Team, For Uncommitted Bug

#44276 Updates to program reuse with different option changes
  src/compiler/commandLineParser.ts
  src/compiler/program.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/testRunner/unittests/reuseProgramStructure.ts
  tests/baselines/reference/tscWatch/programUpdates/correctly-handles-changes-in-lib-section-of-config-file.js
Labels: Author: Team, For Uncommitted Bug

#44274 Ensure AutoImportProviderProject can share source files with main program
  src/harness/fourslashImpl.ts
  src/server/project.ts
  src/testRunner/unittests/tsserver/autoImportProvider.ts
  tests/cases/fourslash/server/autoImportProvider6.ts
Labels: Author: Team, For Uncommitted Bug

#44278 redirectsTarget is keyed with Path
  src/compiler/program.ts
  src/compiler/types.ts
  src/services/documentHighlights.ts
Labels: Author: Team, For Uncommitted Bug

#44282 Add traces for module resolution reuse
  src/compiler/diagnosticMessages.json
  src/compiler/program.ts
  src/compiler/resolutionCache.ts
  src/testRunner/unittests/reuseProgramStructure.ts
  src/testRunner/unittests/tsserver/resolutionCache.ts
Labels: Author: Team, For Uncommitted Bug

#44280 Add type brands for fileId and fileIdListId for tsbuildinfo
  src/compiler/builder.ts
  src/testRunner/unittests/tsbuild/helpers.ts
Labels: Author: Team, For Uncommitted Bug

#44308 Move string trim methods from utilities to core
  src/compiler/core.ts
  src/compiler/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#44306 Dont update timestamps of output files if noEmit was specified
  src/compiler/tsbuildPublic.ts
  src/harness/virtualFileSystemWithWatch.ts
  src/testRunner/tsconfig.json
  src/testRunner/unittests/tsbuildWatch/noEmit.ts
  tests/baselines/reference/tsbuild/watchMode/noEmit/does-not-go-in-loop-when-watching-when-no-files-are-emitted-with-incremental.js
  tests/baselines/reference/tsbuild/watchMode/noEmit/does-not-go-in-loop-when-watching-when-no-files-are-emitted.js
Labels: Author: Team, For Milestone Bug

#44311 Fix unintended 'as const' name lookup error
  src/compiler/checker.ts
  tests/baselines/reference/noAsConstNameLookup.js
  tests/baselines/reference/noAsConstNameLookup.symbols
  tests/baselines/reference/noAsConstNameLookup.types
  tests/cases/compiler/noAsConstNameLookup.ts
Labels: Author: Team, For Milestone Bug

#44147 fix(44123): Do not provide suggestions to convert to async when the callback is a generator
  src/services/suggestionDiagnostics.ts
  src/testRunner/unittests/services/convertToAsyncFunction.ts
Labels: For Backlog Bug

#44126 Consider inferences between mapped type templates lower priority
  src/compiler/checker.ts
  tests/baselines/reference/localTypeParameterInferencePriority.js
  tests/baselines/reference/localTypeParameterInferencePriority.symbols
  tests/baselines/reference/localTypeParameterInferencePriority.types
  tests/cases/compiler/localTypeParameterInferencePriority.ts
Labels: Author: Team, For Milestone Bug
