Repository microsoft/TypeScript, pull requests merged in 2021-12, with the labels that each got.

#46498 Describe defaults of more options
  src/compiler/commandLineParser.ts
  src/compiler/types.ts
  src/executeCommandLine/executeCommandLine.ts
  src/harness/harnessIO.ts
  src/testRunner/unittests/config/commandLineParsing.ts
  tests/baselines/reference/tsc/runWithoutArgs/initial-build/does-not-add-color-when-NO_COLOR-is-set.js
  tests/baselines/reference/tsc/runWithoutArgs/initial-build/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped-when-host-can't-provide-terminal-width.js
  tests/baselines/reference/tsc/runWithoutArgs/initial-build/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
Labels: For Uncommitted Bug

#46985 Pin chalk to ^4.1
  package-lock.json
  package.json
  scripts/browserIntegrationTest.js
  scripts/build/utils.js
Labels: Author: Team, For Uncommitted Bug

#46996 Add jakebailey to pr_owners.txt
  .github/pr_owners.txt
Labels: For Uncommitted Bug

#46389 fix(46195): handle numeric separators and larger integers correctly in codefix for large integers
  src/compiler/checker.ts
  tests/cases/fourslash/codeFixUseBigIntLiteral2.ts
  tests/cases/fourslash/codeFixUseBigIntLiteralWithNumericSeparators.ts
Labels: For Backlog Bug

#46446 fix(46345): declare on computed class field with decorator makes invalid code that crashes due to missing _a
  src/compiler/transformers/ts.ts
  tests/baselines/reference/decoratorInAmbientContext.js
  tests/baselines/reference/decoratorInAmbientContext.symbols
  tests/baselines/reference/decoratorInAmbientContext.types
  tests/cases/conformance/decorators/decoratorInAmbientContext.ts
Labels: For Backlog Bug

#46994 feat(46986): Offer quick fix for some uses of 'await' outside an async context
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/services/codefixes/fixAwaitInSyncFunction.ts
  tests/baselines/reference/awaitCallExpressionInSyncFunction.errors.txt
  tests/baselines/reference/awaitCallExpressionInSyncFunction.js
  tests/baselines/reference/awaitCallExpressionInSyncFunction.symbols
  tests/baselines/reference/awaitCallExpressionInSyncFunction.types
  tests/cases/compiler/awaitCallExpressionInSyncFunction.ts
  tests/cases/fourslash/codeFixAwaitInSyncFunction16.ts
Labels: For Uncommitted Bug

#46581 fix(46563): keyof autocomplete seems like it's missing autocomplete values with polymorphic this type
  src/compiler/checker.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/services/services.ts
  src/services/stringCompletions.ts
  src/services/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/completionListAtThisType.ts
Labels: For Backlog Bug

#46973 Fix checker initialization crash
  src/compiler/checker.ts
Labels: Author: Team, For Milestone Bug

#47014 Cherry-pick: Pin chalk to ^4.1 (#46985)
  package.json
Labels: Author: Team, For Uncommitted Bug

#47010 Improve isValidSpreadType check
  src/compiler/checker.ts
  tests/baselines/reference/spreadObjectOrFalsy.errors.txt
  tests/baselines/reference/spreadObjectOrFalsy.js
  tests/baselines/reference/spreadObjectOrFalsy.symbols
  tests/baselines/reference/spreadObjectOrFalsy.types
  tests/cases/conformance/types/spread/spreadObjectOrFalsy.ts
Labels: Author: Team, For Milestone Bug

#47007 Use features for selected module resolution rather than all features …
  src/compiler/moduleNameResolver.ts
  tests/baselines/reference/tripleSlashTypesReferenceWithMissingExports(module=commonjs).js
  tests/baselines/reference/tripleSlashTypesReferenceWithMissingExports(module=commonjs).symbols
  tests/baselines/reference/tripleSlashTypesReferenceWithMissingExports(module=commonjs).types
  tests/baselines/reference/tripleSlashTypesReferenceWithMissingExports(module=node12).errors.txt
  tests/baselines/reference/tripleSlashTypesReferenceWithMissingExports(module=node12).js
  tests/baselines/reference/tripleSlashTypesReferenceWithMissingExports(module=node12).symbols
  tests/baselines/reference/tripleSlashTypesReferenceWithMissingExports(module=node12).types
  tests/baselines/reference/tripleSlashTypesReferenceWithMissingExports(module=nodenext).errors.txt
  tests/baselines/reference/tripleSlashTypesReferenceWithMissingExports(module=nodenext).js
  tests/baselines/reference/tripleSlashTypesReferenceWithMissingExports(module=nodenext).symbols
  tests/baselines/reference/tripleSlashTypesReferenceWithMissingExports(module=nodenext).types
  tests/cases/compiler/tripleSlashTypesReferenceWithMissingExports.ts
Labels: Author: Team, For Milestone Bug

#46929 "No repeated property names" error in object literals is duplicated in strict mode
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/duplicateIdentifierDifferentSpelling.errors.txt
  tests/baselines/reference/duplicateObjectLiteralProperty.errors.txt
  tests/baselines/reference/duplicateObjectLiteralProperty_computedName.errors.txt
  tests/baselines/reference/duplicatePropertiesInStrictMode.errors.txt
  tests/baselines/reference/duplicatePropertyNames.errors.txt
  tests/baselines/reference/jsFileCompilationBindStrictModeErrors.errors.txt
  tests/baselines/reference/lastPropertyInLiteralWins.errors.txt
  tests/baselines/reference/memberOverride.errors.txt
  tests/baselines/reference/noRepeatedPropertyNames.errors.txt
  tests/baselines/reference/noRepeatedPropertyNames.js
  tests/baselines/reference/noRepeatedPropertyNames.symbols
  tests/baselines/reference/noRepeatedPropertyNames.types
  tests/baselines/reference/numericStringNamedPropertyEquivalence.errors.txt
  tests/baselines/reference/objectLiteralErrors.errors.txt
  tests/baselines/reference/objectSpreadNegative.errors.txt
  tests/baselines/reference/objectTypeWithDuplicateNumericProperty.errors.txt
  tests/cases/compiler/noRepeatedPropertyNames.ts
Labels: For Backlog Bug

#42776 fix(42678): detect access to uninitialized variable in IIFE
  src/compiler/checker.ts
  tests/baselines/reference/blockScopedVariablesUseBeforeDef.errors.txt
  tests/baselines/reference/blockScopedVariablesUseBeforeDef.js
  tests/baselines/reference/blockScopedVariablesUseBeforeDef.symbols
  tests/baselines/reference/blockScopedVariablesUseBeforeDef.types
  tests/baselines/reference/tryCatchFinallyControlFlow.errors.txt
  tests/cases/compiler/blockScopedVariablesUseBeforeDef.ts
Labels: For Backlog Bug

#46782 Properly union inferred template literal string types
  src/compiler/checker.ts
  tests/baselines/reference/templateLiteralTypes3.errors.txt
  tests/baselines/reference/templateLiteralTypes3.js
  tests/baselines/reference/templateLiteralTypes3.symbols
  tests/baselines/reference/templateLiteralTypes3.types
  tests/cases/conformance/types/literal/templateLiteralTypes3.ts
Labels: Author: Team, For Milestone Bug

#46823 Fix strict/es5+ octal literal 2x error #46810
  src/compiler/binder.ts
  tests/baselines/reference/jsFileCompilationBindStrictModeErrors.errors.txt
  tests/baselines/reference/plainJSBinderErrors.errors.txt
  tests/baselines/reference/strictModeOctalLiterals.errors.txt
  tests/baselines/reference/strictModeOctalLiterals.js
  tests/baselines/reference/strictModeOctalLiterals.symbols
  tests/baselines/reference/strictModeOctalLiterals.types
  tests/cases/conformance/expressions/literals/strictModeOctalLiterals.ts
Labels: lib update, For Backlog Bug

#47000 fix(46998): Hover on as const shows type const = /*unresolved*/ any
  src/services/symbolDisplay.ts
  tests/baselines/reference/quickInfoForConstAssertions.baseline
  tests/cases/fourslash/quickInfoForConstAssertions.ts
Labels: For Milestone Bug

#46962 Unwrap parens when checking for JSDocFunctionType in conditional expression
  src/compiler/parser.ts
  tests/baselines/reference/parserParenthesizedVariableAndParenthesizedFunctionInTernary.js
  tests/baselines/reference/parserParenthesizedVariableAndParenthesizedFunctionInTernary.symbols
  tests/baselines/reference/parserParenthesizedVariableAndParenthesizedFunctionInTernary.types
  tests/cases/conformance/parser/ecmascript5/parserParenthesizedVariableAndParenthesizedFunctionInTernary.ts
Labels: Author: Team, For Milestone Bug

#46951 Fix Awaited<T> for onfulfilled callbacks with more than one argument
  src/lib/es5.d.ts
  tests/baselines/reference/awaitedType.errors.txt
  tests/baselines/reference/awaitedType.js
  tests/baselines/reference/awaitedType.symbols
  tests/baselines/reference/awaitedType.types
  tests/baselines/reference/awaitedTypeStrictNull.errors.txt
  tests/baselines/reference/awaitedTypeStrictNull.js
  tests/baselines/reference/awaitedTypeStrictNull.symbols
  tests/baselines/reference/awaitedTypeStrictNull.types
  tests/cases/compiler/awaitedType.ts
  tests/cases/compiler/awaitedTypeStrictNull.ts
Labels: Author: Team, For Uncommitted Bug

#46656 Add a test for a destructured union with tuple members
  tests/baselines/reference/dependentDestructuredVariables.js
  tests/baselines/reference/dependentDestructuredVariables.symbols
  tests/baselines/reference/dependentDestructuredVariables.types
  tests/cases/conformance/controlFlow/dependentDestructuredVariables.ts
Labels: For Uncommitted Bug

#46657 fix(46606): Autocomplete not working for @property types
  src/services/completions.ts
  tests/cases/fourslash/jsdocPropertyTagCompletion.ts
Labels: For Backlog Bug

#47066 fix(47043): as const cast wrong colour when using typescript 4.5.2
  src/services/classifier.ts
  tests/cases/fourslash/semanticClassificationConstAssertion.ts
Labels: For Milestone Bug

#47070 Exempt tslib from indirect call transform
  src/compiler/transformers/module/module.ts
  tests/baselines/reference/es5-importHelpersAsyncFunctions.js
  tests/baselines/reference/esModuleInteropImportTSLibHasImport.js
  tests/baselines/reference/esModuleInteropTslibHelpers.js
  tests/baselines/reference/exportAsNamespace_missingEmitHelpers.js
  tests/baselines/reference/importHelpers.js
  tests/baselines/reference/importHelpersAmd.js
  tests/baselines/reference/importHelpersInIsolatedModules.js
  tests/baselines/reference/importHelpersInTsx.js
  tests/baselines/reference/importHelpersNoHelpers.js
  tests/baselines/reference/importHelpersNoHelpersForAsyncGenerators.js
  tests/baselines/reference/importHelpersNoHelpersForPrivateFields.js
  tests/baselines/reference/importHelpersNoModule.js
  tests/baselines/reference/importHelpersOutFile.js
  tests/baselines/reference/importHelpersWithExportStarAs(esmoduleinterop=true,module=amd).js
  tests/baselines/reference/importHelpersWithExportStarAs(esmoduleinterop=true,module=commonjs).js
  tests/baselines/reference/importHelpersWithImportOrExportDefault(esmoduleinterop=true,module=amd).js
  tests/baselines/reference/importHelpersWithImportOrExportDefault(esmoduleinterop=true,module=commonjs).js
  tests/baselines/reference/importHelpersWithImportStarAs(esmoduleinterop=true,module=amd).js
  tests/baselines/reference/importHelpersWithImportStarAs(esmoduleinterop=true,module=commonjs).js
  tests/baselines/reference/importHelpersWithLocalCollisions(module=amd).js
  tests/baselines/reference/importHelpersWithLocalCollisions(module=commonjs).js
  tests/baselines/reference/javascriptCommonjsModule.js
  tests/baselines/reference/nodeModulesAllowJsImportHelpersCollisions1(module=node12).js
  tests/baselines/reference/nodeModulesAllowJsImportHelpersCollisions1(module=nodenext).js
  tests/baselines/reference/nodeModulesAllowJsImportHelpersCollisions2(module=node12).js
  tests/baselines/reference/nodeModulesAllowJsImportHelpersCollisions2(module=nodenext).js
  tests/baselines/reference/nodeModulesImportHelpersCollisions(module=node12).js
  tests/baselines/reference/nodeModulesImportHelpersCollisions(module=nodenext).js
  tests/baselines/reference/nodeModulesImportHelpersCollisions2(module=node12).js
  tests/baselines/reference/nodeModulesImportHelpersCollisions2(module=nodenext).js
  tests/baselines/reference/taggedTemplateWithoutDeclaredHelper.js
  tests/baselines/reference/tscWatch/incremental/importHelpers-backing-types-removed-incremental.js
  tests/baselines/reference/tscWatch/incremental/importHelpers-backing-types-removed-watch.js
Labels: Author: Team, For Uncommitted Bug

#47075 Add 12 more grammar errors
  src/compiler/program.ts
  tests/baselines/reference/plainJSGrammarErrors.errors.txt
  tests/baselines/reference/plainJSGrammarErrors.js
  tests/baselines/reference/plainJSGrammarErrors.symbols
  tests/baselines/reference/plainJSGrammarErrors.types
  tests/cases/conformance/salsa/plainJSGrammarErrors.ts
Labels: Author: Team, For Uncommitted Bug

#46843 fix: do not use `ts.NodeArray` in factory inputs
  src/compiler/factory/nodeFactory.ts
Labels: For Uncommitted Bug

#46756 chore: add packageManager field to support corepack
  package.json
Labels: Housekeeping, For Uncommitted Bug

#47078 Explicitly Omit unspreadable properties from rest type in the generic case
  src/compiler/checker.ts
  tests/baselines/reference/destructuringUnspreadableIntoRest.errors.txt
  tests/baselines/reference/destructuringUnspreadableIntoRest.js
  tests/baselines/reference/destructuringUnspreadableIntoRest.symbols
  tests/baselines/reference/destructuringUnspreadableIntoRest.types
  tests/cases/compiler/destructuringUnspreadableIntoRest.ts
Labels: Author: Team, For Milestone Bug

#46797 fix(44693): Overriden properties in jsdoc annotation are not picked up in declaration file
  src/compiler/checker.ts
  tests/baselines/reference/jsDeclarationsInheritedTypes.js
  tests/baselines/reference/jsDeclarationsInheritedTypes.symbols
  tests/baselines/reference/jsDeclarationsInheritedTypes.types
  tests/cases/compiler/jsDeclarationsInheritedTypes.ts
Labels: For Backlog Bug

#47125 Revert change to getFalsyFlags
  src/compiler/checker.ts
  tests/baselines/reference/spreadObjectOrFalsy.errors.txt
  tests/baselines/reference/spreadObjectOrFalsy.js
  tests/baselines/reference/spreadObjectOrFalsy.symbols
  tests/baselines/reference/spreadObjectOrFalsy.types
  tests/cases/conformance/types/spread/spreadObjectOrFalsy.ts
Labels: Author: Team, For Milestone Bug

#47136 Fix extract type crash on unresolvable alias references
  src/services/refactors/extractType.ts
  tests/cases/fourslash/extractTypeUnresolvedAlias.ts
Labels: Author: Team, For Milestone Bug

#47059 Fix enums and namespace merge
  src/compiler/checker.ts
  tests/baselines/reference/enumWithExport.errors.txt
  tests/baselines/reference/enumWithExport.js
  tests/baselines/reference/enumWithExport.symbols
  tests/baselines/reference/enumWithExport.types
  tests/cases/compiler/enumWithExport.ts
Labels: Author: Team, For Milestone Bug

#47112 fix(47062): support generic arrow function with default type parameter in tsx
  src/compiler/parser.ts
  tests/baselines/reference/tsxGenericArrowFunctionParsing.errors.txt
  tests/baselines/reference/tsxGenericArrowFunctionParsing.js
  tests/baselines/reference/tsxGenericArrowFunctionParsing.symbols
  tests/baselines/reference/tsxGenericArrowFunctionParsing.types
  tests/cases/conformance/jsx/tsxGenericArrowFunctionParsing.tsx
  tests/cases/fourslash/completionListIsGlobalCompletion.ts
Labels: For Backlog Bug

#47138 fix(47134): Inconsistent QuickInfo on type-only imported symbols
  src/services/utilities.ts
  tests/cases/fourslash/documentHighlightInTypeExport.ts
  tests/cases/fourslash/quickInfoTypeOnlyImportExport.ts
Labels: For Backlog Bug

#47109 Fix multiple issues with indexed access types applied to mapped types
  src/compiler/checker.ts
  tests/baselines/reference/correlatedUnions.js
  tests/baselines/reference/correlatedUnions.symbols
  tests/baselines/reference/correlatedUnions.types
  tests/cases/compiler/correlatedUnions.ts
Labels: Author: Team, For Uncommitted Bug

#47157 update es2020.intl DisplayNames#of
  src/lib/es2020.intl.d.ts
Labels: For Milestone Bug

#47116 fix(46824): remove duplicate private identifier errors
  src/compiler/checker.ts
  tests/baselines/reference/privateNameInInExpression.errors.txt
Labels: For Backlog Bug

#47057 fix(47056): Only the first did-you-mean-colon error in an object literal is reported
  src/compiler/checker.ts
  tests/baselines/reference/objectLiteralErrors.errors.txt
  tests/baselines/reference/objectLiteralErrors.js
  tests/baselines/reference/objectLiteralErrors.symbols
  tests/baselines/reference/objectLiteralErrors.types
  tests/cases/conformance/expressions/objectLiterals/objectLiteralErrors.ts
Labels: For Backlog Bug

#47054 fix(47004): arguments detection for jsdoc / javascript has a false positive
  src/compiler/checker.ts
  tests/baselines/reference/argumentsPropertyNameInJsMode1.errors.txt
  tests/baselines/reference/argumentsPropertyNameInJsMode1.js
  tests/baselines/reference/argumentsPropertyNameInJsMode1.symbols
  tests/baselines/reference/argumentsPropertyNameInJsMode1.types
  tests/baselines/reference/argumentsPropertyNameInJsMode2.js
  tests/baselines/reference/argumentsPropertyNameInJsMode2.symbols
  tests/baselines/reference/argumentsPropertyNameInJsMode2.types
  tests/baselines/reference/quickInfoForArgumentsPropertyNameInJsMode1.baseline
  tests/baselines/reference/quickInfoForArgumentsPropertyNameInJsMode2.baseline
  tests/cases/compiler/argumentsPropertyNameInJsMode1.ts
  tests/cases/compiler/argumentsPropertyNameInJsMode2.ts
  tests/cases/fourslash/quickInfoForArgumentsPropertyNameInJsMode1.ts
  tests/cases/fourslash/quickInfoForArgumentsPropertyNameInJsMode2.ts
Labels: For Backlog Bug

#47170 fix merging of function and derived class
  src/compiler/checker.ts
  tests/baselines/reference/classFunctionMerging2.js
  tests/baselines/reference/classFunctionMerging2.symbols
  tests/baselines/reference/classFunctionMerging2.types
  tests/cases/compiler/classFunctionMerging2.ts
Labels: For Backlog Bug

#47177 Fix baselines from bad merge
  tests/baselines/reference/privateNameInInExpression(target=es2022).errors.txt
  tests/baselines/reference/privateNameInInExpression(target=esnext).errors.txt
Labels: Author: Team, For Uncommitted Bug

#46908 Discourage typo fixes in PR template
  .github/pull_request_template.md
Labels: For Uncommitted Bug
