Repository microsoft/TypeScript, pull requests merged in 2021-09, with the labels that each got.

#45513 Fix the default text for --useDefineForClassFields
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
Labels: Author: Team, For Milestone Bug

#45684 Remove unused code coverage command
  Gulpfile.js
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#45682 Revert "fix(45501): VS Code removes spaces between empty object literals even if insertSpaceAfterOpeningAndBeforeClosingEmptyBraces is true"
  src/services/formatting/rules.ts
  tests/cases/fourslash/formattingNoSpaceBetweenEmptyBraceBrackets.ts
  tests/cases/fourslash/formattingSpaceBetweenEmptyBraceBrackets.ts
Labels: Author: Team, For Uncommitted Bug

#45694 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210902171327574 to main
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45695 fix(45687): Offer 'convert import to namespace' even when selection extends to next line
  src/services/refactors/convertImport.ts
  tests/cases/fourslash/refactorConvertImport_namedToNamespace6.ts
  tests/cases/fourslash/refactorConvertImport_namedToNamespace7.ts
  tests/cases/fourslash/refactorConvertImport_namedToNamespace8.ts
  tests/cases/fourslash/refactorConvertImport_namedToNamespace9.ts
Labels: For Milestone Bug

#45699 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210902231327156 to main
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45706 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210903051335954 to main
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45354 improve error message for using property of type as type
  src/compiler/checker.ts
  tests/baselines/reference/errorForUsingPropertyOfTypeAsType01.errors.txt
  tests/baselines/reference/errorForUsingPropertyOfTypeAsType03.errors.txt
  tests/baselines/reference/genericFunduleInModule.errors.txt
  tests/baselines/reference/genericFunduleInModule2.errors.txt
  tests/baselines/reference/importClause_namespaceImport.errors.txt
  tests/baselines/reference/parserharness.errors.txt
Labels: For Backlog Bug

#45720 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210903231322331 to main
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45725 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210904171317702 to main
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45773 Include index signatures for tagged primitives in keyof
  src/compiler/checker.ts
  tests/baselines/reference/indexSignatures1.errors.txt
  tests/baselines/reference/indexSignatures1.js
  tests/baselines/reference/indexSignatures1.symbols
  tests/baselines/reference/indexSignatures1.types
  tests/cases/conformance/types/members/indexSignatures1.ts
Labels: Author: Team, For Milestone Bug

#45710 Fix missing abstract keyword in completion
  src/harness/fourslashInterfaceImpl.ts
  src/services/completions.ts
  tests/baselines/reference/completionsCommentsClass.baseline
  tests/baselines/reference/completionsCommentsClassMembers.baseline
  tests/baselines/reference/completionsCommentsCommentParsing.baseline
  tests/baselines/reference/completionsCommentsFunctionExpression.baseline
Labels: For Backlog Bug

#45719 Stop looking at binding patterns for type argument inference
  src/compiler/checker.ts
  tests/baselines/reference/destructuringTuple.errors.txt
  tests/baselines/reference/destructuringTuple.types
  tests/cases/fourslash/completionsBindingPatternAffectsInference.ts
Labels: Breaking Change, Experiment, Author: Team, For Milestone Bug

#44964 Add support for raising if you set a tsconfig entry of target/module with the right setting in the root
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  src/testRunner/unittests/config/convertCompilerOptionsFromJson.ts
  src/testRunner/unittests/tsbuildWatch/programUpdates.ts
  tests/baselines/reference/tsbuild/watchMode/programUpdates/works-correctly-when-project-with-extended-config-is-removed.js
Labels: Author: Team, For Uncommitted Bug

#45647 Intl 2021 Updates
  lib/lib.es2021.d.ts
  src/compiler/commandLineParser.ts
  src/lib/README.md
  src/lib/es2018.intl.d.ts
  src/lib/es2020.intl.d.ts
  src/lib/es2021.intl.d.ts
  src/lib/es5.d.ts
  src/lib/esnext.intl.d.ts
  src/lib/libs.json
  tests/baselines/reference/bigintWithLib.symbols
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2016Plus.errors.txt
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2016Plus.js
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2016Plus.symbols
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2016Plus.types
  tests/baselines/reference/es2018IntlAPIs.js
  tests/baselines/reference/es2018IntlAPIs.symbols
  tests/baselines/reference/es2018IntlAPIs.types
  tests/baselines/reference/es2020IntlAPIs.js
  tests/baselines/reference/es2020IntlAPIs.symbols
  tests/baselines/reference/es2020IntlAPIs.types
  tests/baselines/reference/formatToPartsBigInt.symbols
  tests/baselines/reference/tsc/runWithoutArgs/initial-build/does-not-add-color-when-NO_COLOR-is-set.js
  tests/baselines/reference/tsc/runWithoutArgs/initial-build/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped-when-host-can't-provide-terminal-width.js
  tests/baselines/reference/tsc/runWithoutArgs/initial-build/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
  tests/cases/compiler/doYouNeedToChangeYourTargetLibraryES2016Plus.ts
  tests/cases/conformance/es2018/es2018IntlAPIs.ts
  tests/cases/conformance/es2020/es2020IntlAPIs.ts
Labels: Author: Team, For Uncommitted Bug

#45532 feat(45010): handle unclosed fragment in `getJsxClosingTagAtPosition`
  src/compiler/types.ts
  src/services/completions.ts
  src/services/services.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/autoCloseFragment.ts
Labels: For Backlog Bug

#45700 Allow type comparison when target is generic mapped type with key remapping
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypeAsClauseRelationships.errors.txt
  tests/baselines/reference/mappedTypeAsClauseRelationships.js
  tests/baselines/reference/mappedTypeAsClauseRelationships.symbols
  tests/baselines/reference/mappedTypeAsClauseRelationships.types
  tests/cases/conformance/types/mapped/mappedTypeAsClauseRelationships.ts
Labels: For Milestone Bug

#45711 Tail recursive evaluation of conditional types
  src/compiler/checker.ts
  tests/baselines/reference/tailRecursiveConditionalTypes.js
  tests/baselines/reference/tailRecursiveConditionalTypes.symbols
  tests/baselines/reference/tailRecursiveConditionalTypes.types
  tests/cases/compiler/tailRecursiveConditionalTypes.ts
Labels: Author: Team, For Uncommitted Bug

#44619 Add `--preserveValueImports`
  src/compiler/checker.ts
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  src/compiler/program.ts
  src/compiler/transformers/ts.ts
  src/compiler/types.ts
  src/compiler/utilitiesPublic.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/isolatedModulesReExportType.errors.txt
  tests/baselines/reference/isolatedModulesReExportType.js
  tests/baselines/reference/isolatedModulesReExportType.symbols
  tests/baselines/reference/isolatedModulesReExportType.types
  tests/baselines/reference/preserveValueImports(isolatedmodules=false).errors.txt
  tests/baselines/reference/preserveValueImports(isolatedmodules=false).js
  tests/baselines/reference/preserveValueImports(isolatedmodules=false).symbols
  tests/baselines/reference/preserveValueImports(isolatedmodules=false).types
  tests/baselines/reference/preserveValueImports(isolatedmodules=true).errors.txt
  tests/baselines/reference/preserveValueImports(isolatedmodules=true).js
  tests/baselines/reference/preserveValueImports(isolatedmodules=true).symbols
  tests/baselines/reference/preserveValueImports(isolatedmodules=true).types
  tests/baselines/reference/preserveValueImports_errors(isolatedmodules=false).js
  tests/baselines/reference/preserveValueImports_errors(isolatedmodules=false).symbols
  tests/baselines/reference/preserveValueImports_errors(isolatedmodules=false).types
  tests/baselines/reference/preserveValueImports_errors(isolatedmodules=true).errors.txt
  tests/baselines/reference/preserveValueImports_errors(isolatedmodules=true).js
  tests/baselines/reference/preserveValueImports_errors(isolatedmodules=true).symbols
  tests/baselines/reference/preserveValueImports_errors(isolatedmodules=true).types
  tests/baselines/reference/preserveValueImports_module(module=amd).errors.txt
  tests/baselines/reference/preserveValueImports_module(module=amd).js
  tests/baselines/reference/preserveValueImports_module(module=commonjs).errors.txt
  tests/baselines/reference/preserveValueImports_module(module=commonjs).js
  tests/baselines/reference/preserveValueImports_module(module=es2015).js
  tests/baselines/reference/preserveValueImports_module(module=system).errors.txt
  tests/baselines/reference/preserveValueImports_module(module=system).js
  tests/baselines/reference/showConfig/Shows tsconfig for single option/preserveValueImports/tsconfig.json
  tests/baselines/reference/tsConfig/Default initialized TSConfig/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with advanced options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with boolean value compiler options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with enum value compiler options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with files options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with incorrect compiler option value/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with incorrect compiler option/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with list compiler options with enum value/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with list compiler options/tsconfig.json
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/declarationDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/when-outDir-and-declarationDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/when-outDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/with-outFile.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/without-outDir-or-outFile-is-specified-with-declaration-enabled.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/without-outDir-or-outFile-is-specified.js
  tests/cases/compiler/isolatedModulesReExportType.ts
  tests/cases/conformance/externalModules/typeOnly/preserveValueImports.ts
  tests/cases/conformance/externalModules/typeOnly/preserveValueImports_errors.ts
  tests/cases/conformance/externalModules/typeOnly/preserveValueImports_module.ts
Labels: Author: Team, For Milestone Bug

#45575 Track non-null unknown types in control flow analysis
  src/compiler/checker.ts
  tests/baselines/reference/controlFlowTypeofObject.errors.txt
  tests/baselines/reference/controlFlowTypeofObject.js
  tests/baselines/reference/controlFlowTypeofObject.symbols
  tests/baselines/reference/controlFlowTypeofObject.types
  tests/cases/conformance/controlFlow/controlFlowTypeofObject.ts
Labels: Author: Team, For Milestone Bug

#45803 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210909171320215 to main
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45350 Adds 'Awaited' type alias and updates to Promise.all/race/allSettled/any
  src/compiler/checker.ts
  src/harness/fourslashInterfaceImpl.ts
  src/lib/es2015.iterable.d.ts
  src/lib/es2015.promise.d.ts
  src/lib/es2020.promise.d.ts
  src/lib/es2021.promise.d.ts
  src/lib/es5.d.ts
  tests/baselines/reference/asyncArrowFunction9_es2017.errors.txt
  tests/baselines/reference/asyncArrowFunction9_es5.errors.txt
  tests/baselines/reference/asyncArrowFunction9_es6.errors.txt
  tests/baselines/reference/awaitedType.errors.txt
  tests/baselines/reference/awaitedType.js
  tests/baselines/reference/awaitedType.symbols
  tests/baselines/reference/awaitedType.types
  tests/baselines/reference/awaitedTypeStrictNull.errors.txt
  tests/baselines/reference/awaitedTypeStrictNull.js
  tests/baselines/reference/awaitedTypeStrictNull.symbols
  tests/baselines/reference/awaitedTypeStrictNull.types
  tests/baselines/reference/correctOrderOfPromiseMethod.symbols
  tests/baselines/reference/correctOrderOfPromiseMethod.types
  tests/baselines/reference/doNotElaborateAssignabilityToTypeParameters.errors.txt
  tests/baselines/reference/doNotElaborateAssignabilityToTypeParameters.types
  tests/baselines/reference/forAwaitForUnion.types
  tests/baselines/reference/inferFromGenericFunctionReturnTypes3.symbols
  tests/baselines/reference/inferFromGenericFunctionReturnTypes3.types
  tests/baselines/reference/inferenceLimit.symbols
  tests/baselines/reference/inferenceLimit.types
  tests/baselines/reference/mappedTypesArraysTuples.js
  tests/baselines/reference/mappedTypesArraysTuples.symbols
  tests/baselines/reference/mappedTypesArraysTuples.types
  tests/baselines/reference/recursiveConditionalTypes.errors.txt
  tests/baselines/reference/recursiveConditionalTypes.js
  tests/baselines/reference/recursiveConditionalTypes.symbols
  tests/baselines/reference/recursiveConditionalTypes.types
  tests/cases/compiler/awaitedType.ts
  tests/cases/compiler/awaitedTypeStrictNull.ts
  tests/cases/compiler/recursiveConditionalTypes.ts
  tests/cases/conformance/types/mapped/mappedTypesArraysTuples.ts
Labels: Author: Team, For Milestone Bug

#45812 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210910051352418 to main
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45816 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210910111500866 to main
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45822 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210910171318096 to main
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45820 Intl fix for nightly
  src/lib/es2018.intl.d.ts
  src/lib/es2020.intl.d.ts
  tests/baselines/reference/libCompileChecks.js
  tests/baselines/reference/libCompileChecks.symbols
  tests/baselines/reference/libCompileChecks.types
  tests/cases/compiler/libCompileChecks.ts
Labels: Author: Team, For Milestone Bug

#45827 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210910231355873 to main
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45829 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210911051452543 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45832 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210911171333135 to main
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45833 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210911231315444 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45841 fix(45840): remove duplicate entries in diagnosticMessages.json
  src/compiler/diagnosticMessages.json
Labels: For Uncommitted Bug

#45845 Fix infinite recursion in control flow analyzer inlining logic
  src/compiler/checker.ts
  tests/baselines/reference/controlFlowAliasing.errors.txt
  tests/baselines/reference/controlFlowAliasing.js
  tests/baselines/reference/controlFlowAliasing.symbols
  tests/baselines/reference/controlFlowAliasing.types
  tests/cases/conformance/controlFlow/controlFlowAliasing.ts
Labels: Author: Team, For Milestone Bug

#45843 Adds back NumberFormatPartType to the global types from intl
  src/lib/es2018.intl.d.ts
Labels: Author: Team, For Uncommitted Bug

#45723 feat(45679): support 'did you mean' diagnostics for string literal union
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/didYouMeanStringLiteral.errors.txt
  tests/baselines/reference/didYouMeanStringLiteral.js
  tests/baselines/reference/didYouMeanStringLiteral.symbols
  tests/baselines/reference/didYouMeanStringLiteral.types
  tests/baselines/reference/errorsForCallAndAssignmentAreSimilar.errors.txt
  tests/cases/compiler/didYouMeanStringLiteral.ts
Labels: For Backlog Bug

#45797 fix(44880): Control Flow Analysis of Aliased Conditions doesn't work with --useUnknownInCatchVariables
  src/compiler/checker.ts
  src/compiler/utilities.ts
  src/testRunner/compilerRunner.ts
  tests/baselines/reference/controlFlowAliasingCatchVariables(useunknownincatchvariables=false).js
  tests/baselines/reference/controlFlowAliasingCatchVariables(useunknownincatchvariables=false).symbols
  tests/baselines/reference/controlFlowAliasingCatchVariables(useunknownincatchvariables=false).types
  tests/baselines/reference/controlFlowAliasingCatchVariables(useunknownincatchvariables=true).errors.txt
  tests/baselines/reference/controlFlowAliasingCatchVariables(useunknownincatchvariables=true).js
  tests/baselines/reference/controlFlowAliasingCatchVariables(useunknownincatchvariables=true).symbols
  tests/baselines/reference/controlFlowAliasingCatchVariables(useunknownincatchvariables=true).types
  tests/cases/conformance/controlFlow/controlFlowAliasingCatchVariables.ts
Labels: For Milestone Bug

#45892 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210915171350820 to main
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45889 Go back to the old spelling of Intl's NumberFormatPartTypes to not break DT
  src/lib/es2018.intl.d.ts
Labels: Author: Team, For Uncommitted Bug

#45771 Support resolving `@typescript/[lib]` in node modules
  src/compiler/program.ts
  tests/baselines/reference/libTypeScriptOverrideSimple.errors.txt
  tests/baselines/reference/libTypeScriptOverrideSimple.js
  tests/baselines/reference/libTypeScriptOverrideSimple.symbols
  tests/baselines/reference/libTypeScriptOverrideSimple.types
  tests/baselines/reference/libTypeScriptSubfileResolving.errors.txt
  tests/baselines/reference/libTypeScriptSubfileResolving.js
  tests/baselines/reference/libTypeScriptSubfileResolving.symbols
  tests/baselines/reference/libTypeScriptSubfileResolving.types
  tests/cases/compiler/libTypeScriptOverrideSimple.ts
  tests/cases/compiler/libTypeScriptSubfileResolving.ts
Labels: Author: Team, For Uncommitted Bug

#45656 fix: add corresponding message for override error in js files
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/services/codefixes/fixSpelling.ts
  tests/baselines/reference/jsdocOverrideTag1.errors.txt
  tests/baselines/reference/override_js2.errors.txt
  tests/baselines/reference/override_js4.errors.txt
Labels: For Backlog Bug

#45895 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210915231305001 to main
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45911 Update pr_owners.txt for the TypeScript repo bot
  .github/pr_owners.txt
Labels: Author: Team, For Uncommitted Bug

#45838 Fix for resolvedTrueType and resolvedFalseType of conditionType not resolved
  src/compiler/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: lib update, For Uncommitted Bug

#45910 Fix main by using '.default' on the new ms release
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#45914 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210916171326160 to main
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45858 fix(45850): Generated code when re-exporting a const enum using "preserveConstEnums": true is inconsistent
  src/compiler/checker.ts
  tests/baselines/reference/constEnumPreserveEmitNamedExport1.js
  tests/baselines/reference/constEnumPreserveEmitNamedExport1.symbols
  tests/baselines/reference/constEnumPreserveEmitNamedExport1.types
  tests/baselines/reference/constEnumPreserveEmitNamedExport2.js
  tests/baselines/reference/constEnumPreserveEmitNamedExport2.symbols
  tests/baselines/reference/constEnumPreserveEmitNamedExport2.types
  tests/cases/compiler/constEnumPreserveEmitNamedExport1.ts
  tests/cases/compiler/constEnumPreserveEmitNamedExport2.ts
Labels: For Milestone Bug

#45918 Simplify a branch of the Awaited type and clean up comments
  src/lib/es5.d.ts
Labels: Author: Team, For Uncommitted Bug

#45931 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210917103725685 to main
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45935 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210917111746337 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45940 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210917171834463 to main
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45807 Fixed trimming comments on the remaining range
  src/services/formatting/formatting.ts
  tests/cases/fourslash/server/formatTrimRemainingRangets
Labels: For Milestone Bug

#45936 fix(45489): Type intersection allows comparison with string and number values
  tests/baselines/reference/comparisonOperatorWithIntersectionType.errors.txt
  tests/baselines/reference/comparisonOperatorWithIntersectionType.js
  tests/baselines/reference/comparisonOperatorWithIntersectionType.symbols
  tests/baselines/reference/comparisonOperatorWithIntersectionType.types
  tests/cases/conformance/expressions/binaryOperators/comparisonOperator/comparisonOperatorWithIntersectionType.ts
Labels: For Milestone Bug

#45973 Fix typo in findAllReferences.ts
  src/services/findAllReferences.ts
Labels: For Uncommitted Bug

#45989 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210921171323938 to main
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45994 fix(45987): Typescript 4.3.5. Debug Failure
  src/compiler/parser.ts
  tests/baselines/reference/parseInvalidNames.errors.txt
  tests/baselines/reference/parseInvalidNames.js
  tests/baselines/reference/parseInvalidNames.symbols
  tests/baselines/reference/parseInvalidNames.types
  tests/cases/compiler/parseInvalidNames.ts
Labels: For Milestone Bug

#45996 Update github workflows node10 -> node16
  .github/workflows/ci.yml
Labels: Author: Team, Housekeeping, For Uncommitted Bug

#45997 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210921231801942 to main
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#46002 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210922111456067 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#46008 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210922171329763 to main
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45903 Added Jsx Snippet Completion feature
  src/compiler/types.ts
  src/server/protocol.ts
  src/services/completions.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/jsxAttributeCompletionStyleAuto.ts
  tests/cases/fourslash/jsxAttributeCompletionStyleBraces.ts
  tests/cases/fourslash/jsxAttributeCompletionStyleDefault.ts
  tests/cases/fourslash/jsxAttributeCompletionStyleNoSnippet.ts
  tests/cases/fourslash/jsxAttributeCompletionStyleNone.ts
Labels: Author: Team, For Uncommitted Bug

#46014 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210922231341930 to main
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#45925 Avoid Promise<Awaited<T>> in return type inference
  src/compiler/checker.ts
  tests/baselines/reference/awaitedTypeStrictNull.errors.txt
  tests/baselines/reference/awaitedTypeStrictNull.js
  tests/baselines/reference/awaitedTypeStrictNull.symbols
  tests/baselines/reference/awaitedTypeStrictNull.types
  tests/cases/compiler/awaitedTypeStrictNull.ts
Labels: Author: Team, For Uncommitted Bug

#46013 Revert "Stop looking at binding patterns for type argument inference"
  src/compiler/checker.ts
  tests/baselines/reference/destructuringTuple.errors.txt
  tests/baselines/reference/destructuringTuple.types
  tests/cases/fourslash/completionsBindingPatternAffectsInference.ts
Labels: Author: Team, For Uncommitted Bug

#45905 Adds more Intl.ResolvedDateTimeFormatOptions, and hooks up Intl for ES2021
  src/lib/es2021.d.ts
  src/lib/es2021.intl.d.ts
  tests/baselines/reference/formatToPartsBigInt.symbols
Labels: Author: Team, For Backlog Bug

#45873 fix(45607): Snippet import statement completions don't work for 'import type'
  src/services/completions.ts
  tests/cases/fourslash/importTypeCompletions1.ts
  tests/cases/fourslash/importTypeCompletions2.ts
  tests/cases/fourslash/importTypeCompletions3.ts
  tests/cases/fourslash/importTypeCompletions4.ts
  tests/cases/fourslash/importTypeCompletions5.ts
  tests/cases/fourslash/importTypeCompletions6.ts
  tests/cases/fourslash/importTypeCompletions7.ts
Labels: For Milestone Bug

#44648 ES private field check
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/emitter.ts
  src/compiler/factory/emitHelpers.ts
  src/compiler/factory/parenthesizerRules.ts
  src/compiler/parser.ts
  src/compiler/transformers/classFields.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/compiler/utilitiesPublic.ts
  src/services/codefixes/fixForgottenThisPropertyAccess.ts
  src/services/codefixes/fixSpelling.ts
  src/services/services.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/importHelpersES6.js
  tests/baselines/reference/importHelpersES6.symbols
  tests/baselines/reference/importHelpersES6.types
  tests/baselines/reference/importHelpersNoHelpersForPrivateFields.errors.txt
  tests/baselines/reference/importHelpersNoHelpersForPrivateFields.js
  tests/baselines/reference/importHelpersNoHelpersForPrivateFields.symbols
  tests/baselines/reference/importHelpersNoHelpersForPrivateFields.types
  tests/baselines/reference/inOperatorWithInvalidOperands.errors.txt
  tests/baselines/reference/privateNameHashCharName.errors.txt
  tests/baselines/reference/privateNameHashCharName.types
  tests/baselines/reference/privateNameInInExpression.errors.txt
  tests/baselines/reference/privateNameInInExpression.js
  tests/baselines/reference/privateNameInInExpression.symbols
  tests/baselines/reference/privateNameInInExpression.types
  tests/baselines/reference/privateNameInInExpressionTransform(target=es2020).errors.txt
  tests/baselines/reference/privateNameInInExpressionTransform(target=es2020).js
  tests/baselines/reference/privateNameInInExpressionTransform(target=es2020).symbols
  tests/baselines/reference/privateNameInInExpressionTransform(target=es2020).types
  tests/baselines/reference/privateNameInInExpressionTransform(target=esnext).errors.txt
  tests/baselines/reference/privateNameInInExpressionTransform(target=esnext).js
  tests/baselines/reference/privateNameInInExpressionTransform(target=esnext).symbols
  tests/baselines/reference/privateNameInInExpressionTransform(target=esnext).types
  tests/baselines/reference/privateNameInInExpressionUnused.errors.txt
  tests/baselines/reference/privateNameInInExpressionUnused.js
  tests/baselines/reference/privateNameInInExpressionUnused.symbols
  tests/baselines/reference/privateNameInInExpressionUnused.types
  tests/cases/compiler/importHelpersES6.ts
  tests/cases/compiler/importHelpersNoHelpersForPrivateFields.ts
  tests/cases/conformance/classes/members/privateNames/privateNameInInExpression.ts
  tests/cases/conformance/classes/members/privateNames/privateNameInInExpressionTransform.ts
  tests/cases/conformance/classes/members/privateNames/privateNameInInExpressionUnused.ts
  tests/cases/fourslash/codeFixSpellingPrivateNameInIn.ts
  tests/cases/fourslash/findAllRefsPrivateNameProperties.ts
Labels: For Backlog Bug

#45693 Transform JSX spread children
  src/compiler/transformers/jsx.ts
  tests/baselines/reference/inlineJsxFactoryDeclarationsLocalTypes.js
  tests/baselines/reference/tsxSpreadChildrenInvalidType(target=es2015).errors.txt
  tests/baselines/reference/tsxSpreadChildrenInvalidType(target=es2015).js
  tests/baselines/reference/tsxSpreadChildrenInvalidType(target=es2015).symbols
  tests/baselines/reference/tsxSpreadChildrenInvalidType(target=es2015).types
  tests/baselines/reference/tsxSpreadChildrenInvalidType(target=es5).errors.txt
  tests/baselines/reference/tsxSpreadChildrenInvalidType(target=es5).js
  tests/baselines/reference/tsxSpreadChildrenInvalidType(target=es5).symbols
  tests/baselines/reference/tsxSpreadChildrenInvalidType(target=es5).types
  tests/cases/conformance/jsx/tsxSpreadChildrenInvalidType.tsx
Labels: For Uncommitted Bug

#46046 Resolve with -lib in TypeScript lib lookup via node-style resolution
  src/compiler/program.ts
  tests/baselines/reference/libTypeScriptOverrideSimple.errors.txt
  tests/baselines/reference/libTypeScriptOverrideSimple.symbols
  tests/baselines/reference/libTypeScriptOverrideSimple.types
  tests/baselines/reference/libTypeScriptSubfileResolving.errors.txt
  tests/baselines/reference/libTypeScriptSubfileResolving.symbols
  tests/baselines/reference/libTypeScriptSubfileResolving.types
  tests/cases/compiler/libTypeScriptOverrideSimple.ts
  tests/cases/compiler/libTypeScriptSubfileResolving.ts
Labels: Author: Team, For Milestone Bug

#45934 Default tsc --init to es2016
  src/compiler/commandLineParser.ts
  tests/baselines/reference/tsConfig/Default initialized TSConfig/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with advanced options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with boolean value compiler options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with files options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with incorrect compiler option value/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with incorrect compiler option/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with list compiler options with enum value/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with list compiler options/tsconfig.json
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/declarationDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/when-outDir-and-declarationDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/when-outDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/with-outFile.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/without-outDir-or-outFile-is-specified-with-declaration-enabled.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/without-outDir-or-outFile-is-specified.js
Labels: Author: Team, For Uncommitted Bug

#46058 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210925171322614 to main
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#46052 Properly handle missingType in intersections
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/strictOptionalProperties1.errors.txt
  tests/baselines/reference/strictOptionalProperties1.js
  tests/baselines/reference/strictOptionalProperties1.symbols
  tests/baselines/reference/strictOptionalProperties1.types
  tests/cases/compiler/strictOptionalProperties1.ts
Labels: Author: Team, For Milestone Bug

#46077 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210926231336054 to main
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#46075 Make `never` inferences with template literal types only in special cases
  src/compiler/checker.ts
  tests/baselines/reference/templateLiteralTypes1.types
  tests/baselines/reference/templateLiteralTypes3.errors.txt
  tests/baselines/reference/templateLiteralTypes3.js
  tests/baselines/reference/templateLiteralTypes3.symbols
  tests/baselines/reference/templateLiteralTypes3.types
  tests/cases/conformance/types/literal/templateLiteralTypes3.ts
Labels: Author: Team, For Milestone Bug

#46080 Updates the DOM APIs
  src/lib/dom.generated.d.ts
  src/lib/dom.iterable.generated.d.ts
  src/lib/webworker.generated.d.ts
  src/lib/webworker.iterable.generated.d.ts
  tests/baselines/reference/importMeta(module=commonjs,target=es5).types
  tests/baselines/reference/importMeta(module=commonjs,target=esnext).types
  tests/baselines/reference/importMeta(module=es2020,target=es5).types
  tests/baselines/reference/importMeta(module=es2020,target=esnext).types
  tests/baselines/reference/importMeta(module=esnext,target=es5).types
  tests/baselines/reference/importMeta(module=esnext,target=esnext).types
  tests/baselines/reference/importMeta(module=system,target=es5).types
  tests/baselines/reference/importMeta(module=system,target=esnext).types
  tests/baselines/reference/intersectionsOfLargeUnions2.errors.txt
  tests/baselines/reference/mappedTypeRecursiveInference.errors.txt
  tests/baselines/reference/mappedTypeRecursiveInference.types
Labels: Author: Team, For Uncommitted Bug

#46088 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210927171329633 to main
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#46106 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210927231336403 to main
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#46105 Fix indexing error in guessDirectorySymlink
  src/compiler/utilities.ts
  src/testRunner/unittests/tsserver/symlinkCache.ts
Labels: Author: Team, For Milestone Bug

#45923 `keyof` should always include remapped keys
  src/compiler/checker.ts
  tests/baselines/reference/computedTypesKeyofNoIndexSignatureType.types
  tests/baselines/reference/keyRemappingKeyofResult.js
  tests/baselines/reference/keyRemappingKeyofResult.symbols
  tests/baselines/reference/keyRemappingKeyofResult.types
  tests/baselines/reference/mappedTypeAsClauses.types
  tests/cases/compiler/keyRemappingKeyofResult.ts
Labels: Author: Team, For Milestone Bug

#46117 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210928171328273 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#46126 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210928231435543 to main
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#46133 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210929111445583 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#46038 Update parameter types of RegExp compile method
  src/lib/es5.d.ts
Labels: For Backlog Bug

#46040 fix(45999): Inlay hints for parameter declaration should before initializer
  src/services/inlayHints.ts
  tests/cases/fourslash/inlayHintsShouldWork65.ts
Labels: For Milestone Bug

#45883 fix(45876): Remove "ascii character" order from docs for Float64Array.sort
  src/lib/es5.d.ts
Labels: For Backlog Bug

#45894 fix(44021): reference jsx pragma when JsxFragment is used
  src/compiler/checker.ts
  tests/baselines/reference/inlineJsxAndJsxFragPragma.errors.txt
  tests/baselines/reference/inlineJsxAndJsxFragPragma.js
  tests/baselines/reference/inlineJsxAndJsxFragPragma.symbols
  tests/baselines/reference/inlineJsxAndJsxFragPragma.types
  tests/cases/conformance/jsx/inline/inlineJsxAndJsxFragPragma.tsx
Labels: For Backlog Bug

#45960 fix(26635): JSdoc casts should only work when directly attached to an expression
  src/compiler/checker.ts
  tests/baselines/reference/jsdocTypeCast.errors.txt
  tests/baselines/reference/jsdocTypeCast.js
  tests/baselines/reference/jsdocTypeCast.symbols
  tests/baselines/reference/jsdocTypeCast.types
  tests/cases/compiler/jsdocTypeCast.ts
Labels: For Backlog Bug

#46138 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20210929231308470 to main
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#46137 Fix issues + Support template literal types as discriminants
  src/compiler/checker.ts
  tests/baselines/reference/templateLiteralTypes3.errors.txt
  tests/baselines/reference/templateLiteralTypes3.js
  tests/baselines/reference/templateLiteralTypes3.symbols
  tests/baselines/reference/templateLiteralTypes3.types
  tests/cases/conformance/types/literal/templateLiteralTypes3.ts
Labels: Author: Team, For Milestone Bug

#46056 feat(36080): Should it be an error to add JSDoc visibility modifiers to #privateFields
  src/compiler/checker.ts
  tests/baselines/reference/privateNamesIncompatibleModifiersJs.errors.txt
  tests/baselines/reference/privateNamesIncompatibleModifiersJs.js
  tests/baselines/reference/privateNamesIncompatibleModifiersJs.symbols
  tests/baselines/reference/privateNamesIncompatibleModifiersJs.types
  tests/cases/conformance/classes/members/privateNames/privateNamesIncompatibleModifiersJs.ts
Labels: For Milestone Bug

#45952 fix(45919): TS2775 when using arrow function for type predicate
  src/compiler/checker.ts
  src/compiler/utilities.ts
  tests/baselines/reference/assertionTypePredicates2.js
  tests/baselines/reference/assertionTypePredicates2.symbols
  tests/baselines/reference/assertionTypePredicates2.types
  tests/cases/conformance/controlFlow/assertionTypePredicates2.ts
Labels: For Backlog Bug

#46148 Minimal fix for auto-importing node_modules in node12/nodenext
  src/compiler/moduleSpecifiers.ts
  tests/cases/fourslash/autoImport_node12_node_modules1.ts
Labels: Author: Team, For Uncommitted Bug

#41821 Track source and target relationship stack depth seperately, only increase on change in value
  src/compiler/checker.ts
  tests/baselines/reference/circularlyConstrainedMappedTypeContainingConditionalNoInfiniteInstantiationDepth.errors.txt
  tests/baselines/reference/conditionalTypeVarianceBigArrayConstraintsPerformance.errors.txt
  tests/baselines/reference/conditionalTypeVarianceBigArrayConstraintsPerformance.js
  tests/baselines/reference/conditionalTypeVarianceBigArrayConstraintsPerformance.symbols
  tests/baselines/reference/conditionalTypeVarianceBigArrayConstraintsPerformance.types
  tests/baselines/reference/deepComparisons.errors.txt
  tests/baselines/reference/deepComparisons.js
  tests/baselines/reference/deepComparisons.symbols
  tests/baselines/reference/deepComparisons.types
  tests/baselines/reference/genericCapturingFunctionNarrowing.js
  tests/baselines/reference/genericCapturingFunctionNarrowing.symbols
  tests/baselines/reference/genericCapturingFunctionNarrowing.types
  tests/baselines/reference/genericConditionalConstrainedToUnknownNotAssignableToConcreteObject.errors.txt
  tests/baselines/reference/genericConditionalConstrainedToUnknownNotAssignableToConcreteObject.js
  tests/baselines/reference/genericConditionalConstrainedToUnknownNotAssignableToConcreteObject.symbols
  tests/baselines/reference/genericConditionalConstrainedToUnknownNotAssignableToConcreteObject.types
  tests/baselines/reference/infiniteConstraints.errors.txt
  tests/baselines/reference/quickinfoTypeAtReturnPositionsInaccurate.errors.txt
  tests/baselines/reference/quickinfoTypeAtReturnPositionsInaccurate.types
  tests/baselines/reference/reactReduxLikeDeferredInferenceAllowsAssignment.errors.txt
  tests/cases/compiler/conditionalTypeVarianceBigArrayConstraintsPerformance.ts
  tests/cases/compiler/deepComparisons.ts
  tests/cases/compiler/genericCapturingFunctionNarrowing.ts
  tests/cases/compiler/genericConditionalConstrainedToUnknownNotAssignableToConcreteObject.ts
Labels: Author: Team, For Milestone Bug
