Repository microsoft/TypeScript, pull requests merged in 2021-11, with the labels that each got.

#46614 Check for type parameters on original type when getting type argument completions
  src/compiler/checker.ts
  tests/cases/fourslash/stringLiteralTypeCompletionsInTypeArgForNonGeneric1.ts
Labels: For Milestone Bug

#46537 Fix `findUpDir.ts` and uses
  scripts/build/projects.js
  src/harness/findUpDir.ts
  src/harness/harnessIO.ts
  src/harness/tsconfig.json
  src/testRunner/parallel/host.ts
Labels: Author: Team, For Uncommitted Bug

#46531 fix(43292): Template string literals now participate in occurrences highlighting
  src/services/findAllReferences.ts
  tests/cases/fourslash/documentHighlightMultilineTemplateStrings.ts
  tests/cases/fourslash/documentHighlightTemplateStrings.ts
Labels: For Backlog Bug

#46632 Exclude identity relation from mapped type relation check
  src/compiler/checker.ts
  tests/baselines/reference/noExcessiveStackDepthError.errors.txt
  tests/baselines/reference/noExcessiveStackDepthError.js
  tests/baselines/reference/noExcessiveStackDepthError.symbols
  tests/baselines/reference/noExcessiveStackDepthError.types
  tests/cases/compiler/noExcessiveStackDepthError.ts
Labels: Author: Team, For Milestone Bug

#46647 Fix git remote in cherry pick script
  scripts/open-cherry-pick-pr.ts
Labels: Author: Team, For Uncommitted Bug

#46645 Properly check whether union type contains only primitive types
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/primitiveUnionDetection.js
  tests/baselines/reference/primitiveUnionDetection.symbols
  tests/baselines/reference/primitiveUnionDetection.types
  tests/cases/compiler/primitiveUnionDetection.ts
Labels: Author: Team, For Milestone Bug

#46599 Improve recursion depth checks
  src/compiler/checker.ts
  tests/baselines/reference/invariantGenericErrorElaboration.errors.txt
Labels: Author: Team, For Uncommitted Bug

#46558 Fix contextual typing for symbol-named properties
  src/compiler/checker.ts
  src/lib/es5.d.ts
  tests/baselines/reference/contextuallyTypedSymbolNamedProperties.js
  tests/baselines/reference/contextuallyTypedSymbolNamedProperties.symbols
  tests/baselines/reference/contextuallyTypedSymbolNamedProperties.types
  tests/cases/compiler/contextuallyTypedSymbolNamedProperties.ts
Labels: Author: Team, For Milestone Bug

#46546 fix(46512): JSX cannot use tag names that start with "public-"
  src/compiler/scanner.ts
  tests/baselines/reference/jsxParsingError4(strict=false).js
  tests/baselines/reference/jsxParsingError4(strict=false).symbols
  tests/baselines/reference/jsxParsingError4(strict=false).types
  tests/baselines/reference/jsxParsingError4(strict=true).errors.txt
  tests/baselines/reference/jsxParsingError4(strict=true).js
  tests/baselines/reference/jsxParsingError4(strict=true).symbols
  tests/baselines/reference/jsxParsingError4(strict=true).types
  tests/cases/conformance/jsx/jsxParsingError4.tsx
Labels: For Backlog Bug

#46630 Allow import assertions on esm imports under module: nodenext
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/importAssertion1(module=commonjs).errors.txt
  tests/baselines/reference/importAssertion1(module=es2015).errors.txt
  tests/baselines/reference/importAssertion2(module=commonjs).errors.txt
  tests/baselines/reference/importAssertion2(module=es2015).errors.txt
  tests/baselines/reference/importAssertion3(module=es2015).errors.txt
  tests/baselines/reference/importCallExpressionGrammarError.errors.txt
  tests/baselines/reference/nodeModulesImportAssertions(module=node12).errors.txt
  tests/baselines/reference/nodeModulesImportAssertions(module=node12).js
  tests/baselines/reference/nodeModulesImportAssertions(module=node12).symbols
  tests/baselines/reference/nodeModulesImportAssertions(module=node12).types
  tests/baselines/reference/nodeModulesImportAssertions(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesImportAssertions(module=nodenext).js
  tests/baselines/reference/nodeModulesImportAssertions(module=nodenext).symbols
  tests/baselines/reference/nodeModulesImportAssertions(module=nodenext).types
  tests/cases/conformance/node/nodeModulesImportAssertions.ts
Labels: Author: Team, For Milestone Bug

#46266 Control flow analysis for destructured discriminated unions
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/controlFlowAliasing.errors.txt
  tests/baselines/reference/controlFlowAliasing.types
  tests/baselines/reference/dependentDestructuredVariables.js
  tests/baselines/reference/dependentDestructuredVariables.symbols
  tests/baselines/reference/dependentDestructuredVariables.types
  tests/cases/conformance/controlFlow/dependentDestructuredVariables.ts
Labels: Author: Team, For Milestone Bug

#46649 Cherry-pick #46645 to release-4.5
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/primitiveUnionDetection.js
  tests/baselines/reference/primitiveUnionDetection.symbols
  tests/baselines/reference/primitiveUnionDetection.types
  tests/cases/compiler/primitiveUnionDetection.ts
Labels: Author: Team, For Uncommitted Bug

#46625 Duplicate GDPR fragment from VS Code repo
  src/server/protocol.ts
Labels: Author: Team, For Uncommitted Bug

#46594 fix(46589): Extra ? added to method in method signature completion for optional method
  src/services/codefixes/helpers.ts
  src/services/completions.ts
  tests/cases/fourslash/completionsOverridingMethod9.ts
Labels: For Milestone Bug

#46670 Make specifier generation from export map information conditional on module resolution mode
  src/compiler/moduleSpecifiers.ts
  tests/baselines/reference/legacyNodeModulesExportsSpecifierGenerationConditions.js
  tests/baselines/reference/legacyNodeModulesExportsSpecifierGenerationConditions.symbols
  tests/baselines/reference/legacyNodeModulesExportsSpecifierGenerationConditions.types
  tests/cases/conformance/node/legacyNodeModulesExportsSpecifierGenerationConditions.ts
Labels: Author: Team, For Milestone Bug

#46628 fix(46615): Incorrect assertion in quick fix code
  src/compiler/checker.ts
  src/services/codefixes/addNameToNamelessParameter.ts
  tests/baselines/reference/noImplicitAnyNamelessParameter.errors.txt
  tests/baselines/reference/noImplicitAnyNamelessParameter.js
  tests/baselines/reference/noImplicitAnyNamelessParameter.symbols
  tests/baselines/reference/noImplicitAnyNamelessParameter.types
  tests/cases/compiler/noImplicitAnyNamelessParameter.ts
  tests/cases/fourslash/codeFixAddParameterNames1.ts
  tests/cases/fourslash/codeFixAddParameterNames2.ts
  tests/cases/fourslash/codeFixAddParameterNames3.ts
Labels: For Backlog Bug

#46291 Add `target: "es2022"`
  src/compiler/commandLineParser.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/compiler/utilitiesPublic.ts
  src/lib/es2022.array.d.ts
  src/lib/es2022.d.ts
  src/lib/es2022.error.d.ts
  src/lib/es2022.full.d.ts
  src/lib/es2022.object.d.ts
  src/lib/es2022.string.d.ts
  src/lib/esnext.d.ts
  src/lib/libs.json
  src/server/protocol.ts
  src/testRunner/unittests/config/commandLineParsing.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/callChainWithSuper(target=es2022).js
  tests/baselines/reference/callWithSpread4.symbols
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2016Plus.errors.txt
  tests/baselines/reference/errorCause(target=es2021).errors.txt
  tests/baselines/reference/errorCause(target=es2021).js
  tests/baselines/reference/errorCause(target=es2021).symbols
  tests/baselines/reference/errorCause(target=es2021).types
  tests/baselines/reference/errorCause(target=es2022).js
  tests/baselines/reference/errorCause(target=es2022).symbols
  tests/baselines/reference/errorCause(target=es2022).types
  tests/baselines/reference/errorCause(target=esnext).js
  tests/baselines/reference/errorCause(target=esnext).symbols
  tests/baselines/reference/errorCause(target=esnext).types
  tests/baselines/reference/esNextWeakRefs_IterableWeakMap.symbols
  tests/baselines/reference/flatArrayNoExcessiveStackDepth.symbols
  tests/baselines/reference/importExportInternalComments.symbols
  tests/baselines/reference/indexAt(target=es2021).errors.txt
  tests/baselines/reference/indexAt(target=es2021).js
  tests/baselines/reference/indexAt(target=es2021).symbols
  tests/baselines/reference/indexAt(target=es2021).types
  tests/baselines/reference/indexAt(target=es2022).js
  tests/baselines/reference/indexAt(target=es2022).symbols
  tests/baselines/reference/indexAt(target=es2022).types
  tests/baselines/reference/indexAt(target=esnext).js
  tests/baselines/reference/indexAt(target=esnext).symbols
  tests/baselines/reference/indexAt(target=esnext).types
  tests/baselines/reference/inferenceOptionalPropertiesToIndexSignatures.symbols
  tests/baselines/reference/keyofAndIndexedAccess2.symbols
  tests/baselines/reference/noIterationTypeErrorsInCFA.symbols
  tests/baselines/reference/reactJsxReactResolvedNodeNext.trace.json
  tests/baselines/reference/reactJsxReactResolvedNodeNextEsm.trace.json
  tests/baselines/reference/recursiveConditionalTypes.symbols
  tests/baselines/reference/taggedTemplatesWithTypeArguments1.symbols
  tests/baselines/reference/tsc/runWithoutArgs/initial-build/does-not-add-color-when-NO_COLOR-is-set.js
  tests/baselines/reference/tsc/runWithoutArgs/initial-build/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped-when-host-can't-provide-terminal-width.js
  tests/baselines/reference/tsc/runWithoutArgs/initial-build/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
  tests/baselines/reference/typeGuardConstructorNarrowAny.symbols
  tests/baselines/reference/typeGuardConstructorPrimitiveTypes.symbols
  tests/baselines/reference/unionTypeInference.symbols
  tests/cases/compiler/errorCause.ts
  tests/cases/compiler/indexAt.ts
Labels: For Backlog Bug

#46682 fix(46666): No outlining span returned for multiline comment
  src/services/outliningElementsCollector.ts
  tests/cases/fourslash/getOutliningForBlockComments.ts
Labels: For Backlog Bug

#46635 [release-4.5] Exclude identity relation from mapped type relation check
  src/compiler/checker.ts
  tests/baselines/reference/noExcessiveStackDepthError.errors.txt
  tests/baselines/reference/noExcessiveStackDepthError.js
  tests/baselines/reference/noExcessiveStackDepthError.symbols
  tests/baselines/reference/noExcessiveStackDepthError.types
  tests/cases/compiler/noExcessiveStackDepthError.ts
Labels: For Uncommitted Bug

#45765 fix(33325): Allow running extract refactoring on selected statement even when trailing semicolon is not included in selection
  src/services/refactors/extractSymbol.ts
  src/testRunner/unittests/services/extract/ranges.ts
  tests/cases/fourslash/extract-const10.ts
Labels: For Backlog Bug

#45739 fix(44059): Refactoring Infer type from usage duplicate function type
  src/services/codefixes/inferFromUsage.ts
  tests/cases/fourslash/codeFixInferFromUsageVariable4.ts
Labels: For Backlog Bug

#45729 fix(45692): Some identical types not being merged when one is optional in an object spread
  src/compiler/checker.ts
  tests/baselines/reference/spreadUnion4.js
  tests/baselines/reference/spreadUnion4.symbols
  tests/baselines/reference/spreadUnion4.types
  tests/cases/conformance/types/spread/spreadUnion4.ts
Labels: For Backlog Bug

#46733 Big[U]Int64Array.at returns bigint, not number
  src/lib/es2022.array.d.ts
  tests/baselines/reference/indexAt(target=es2022).types
  tests/baselines/reference/indexAt(target=esnext).types
Labels: Author: Team, For Uncommitted Bug

#46274 fix(45907): Quick info uses JSDoc for inherited instance property with static property of same name
  src/services/services.ts
  tests/cases/fourslash/jsDocInheritDoc.ts
Labels: For Backlog Bug

#46743 fix(46605): Template literal autocomplete not working for parameter objects
  src/services/completions.ts
  tests/cases/fourslash/completionListInObjectLiteral6.ts
Labels: For Backlog Bug

#46767 Removed replacement from jsx completions
  src/services/completions.ts
  tests/cases/fourslash/jsxAttributeCompletionStyleAuto.ts
  tests/cases/fourslash/jsxAttributeCompletionStyleBraces.ts
Labels: Author: Team, For Milestone Bug

#46787 Revert changes to matchFiles/readDirectory made since 4.3
  src/compiler/sys.ts
  src/compiler/utilities.ts
  src/compiler/watchUtilities.ts
  src/harness/fakesHosts.ts
  src/harness/harnessIO.ts
  src/harness/virtualFileSystemWithWatch.ts
  src/testRunner/unittests/publicApi.ts
Labels: Author: Team, For Milestone Bug

#46740 fix(46712): Add "exceptZero" for "signDisplay" option of Intl.NumberF…
  src/lib/es2020.intl.d.ts
Labels: For Backlog Bug

#44718 fix(43359): Emit bug: default export is missing when exporting type+named+default
  src/compiler/checker.ts
  tests/baselines/reference/defaultNamedExportWithType1.js
  tests/baselines/reference/defaultNamedExportWithType1.symbols
  tests/baselines/reference/defaultNamedExportWithType1.types
  tests/baselines/reference/defaultNamedExportWithType2.js
  tests/baselines/reference/defaultNamedExportWithType2.symbols
  tests/baselines/reference/defaultNamedExportWithType2.types
  tests/baselines/reference/defaultNamedExportWithType3.js
  tests/baselines/reference/defaultNamedExportWithType3.symbols
  tests/baselines/reference/defaultNamedExportWithType3.types
  tests/baselines/reference/defaultNamedExportWithType4.js
  tests/baselines/reference/defaultNamedExportWithType4.symbols
  tests/baselines/reference/defaultNamedExportWithType4.types
  tests/baselines/reference/duplicateVarsAcrossFileBoundaries.js
  tests/baselines/reference/importDeclWithExportModifierAndExportAssignment.js
  tests/cases/compiler/defaultNamedExportWithType1.ts
  tests/cases/compiler/defaultNamedExportWithType2.ts
  tests/cases/compiler/defaultNamedExportWithType3.ts
  tests/cases/compiler/defaultNamedExportWithType4.ts
Labels: For Milestone Bug

#46829 Allow nightly-only flags in `-insiders` builds
  src/compiler/program.ts
Labels: Author: Team, For Uncommitted Bug

#46830 Update symlink cache from AutoImportProvider resolution even if host project already contains the file via its realpath
  src/server/project.ts
  tests/cases/fourslash/server/autoImportProvider7.ts
Labels: Author: Team, For Uncommitted Bug

#46818 Fix broken module resolution after large/rapid edits in nodenext
  src/compiler/program.ts
  src/harness/fourslashImpl.ts
  tests/cases/fourslash/server/impliedNodeFormat.ts
Labels: Author: Team, For Milestone Bug

#46511 fix(42238): JSDoc '@this' not emitted in declaration file
  src/compiler/checker.ts
  tests/baselines/reference/thisTag1.types
  tests/baselines/reference/thisTag2.js
  tests/baselines/reference/thisTag2.symbols
  tests/baselines/reference/thisTag2.types
  tests/cases/conformance/jsdoc/thisTag2.ts
Labels: For Backlog Bug

#46714 enable go-to-type-definition on type nodes
  src/services/goToDefinition.ts
  tests/cases/fourslash/goToTypeDefinition3.ts
  tests/cases/fourslash/goToTypeDefinition4.ts
  tests/cases/fourslash/goToTypeDefinition5.ts
Labels: For Backlog Bug

#46831 Stop calling our own @deprecrated APIs
  src/compiler/core.ts
  src/compiler/debug.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/resolutionCache.ts
  src/compiler/transformers/es2018.ts
  src/compiler/transformers/jsx.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/server/session.ts
  src/services/codefixes/fixImplicitThis.ts
  src/testRunner/unittests/tsserver/autoImportProvider.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#46431 fix(46366): Escaped notation in an enum's computed property shows as non-escaped on hover
  src/compiler/checker.ts
  tests/baselines/reference/enumWithUnicodeEscape1.symbols
  tests/baselines/reference/quickInfoDisplayPartsEnum2.baseline
  tests/baselines/reference/quickInfoDisplayPartsEnum3.baseline
  tests/baselines/reference/quickInfoDisplayPartsEnum4.baseline
  tests/cases/fourslash/quickInfoDisplayPartsEnum4.ts
Labels: For Backlog Bug

#46816 Plain JS binder errors
  src/compiler/program.ts
  tests/baselines/reference/argumentsReferenceInConstructor4_Js.errors.txt
  tests/baselines/reference/argumentsReferenceInMethod4_Js.errors.txt
  tests/baselines/reference/jsdocTypedefNoCrash2.errors.txt
  tests/baselines/reference/plainJSBinderErrors.errors.txt
  tests/baselines/reference/plainJSBinderErrors.js
  tests/baselines/reference/plainJSBinderErrors.symbols
  tests/baselines/reference/plainJSBinderErrors.types
  tests/baselines/reference/plainJSModuleStrict.errors.txt
  tests/baselines/reference/plainJSModuleStrict.js
  tests/baselines/reference/plainJSModuleStrict.symbols
  tests/baselines/reference/plainJSModuleStrict.types
  tests/baselines/reference/plainJSRedeclare.errors.txt
  tests/baselines/reference/plainJSRedeclare.js
  tests/baselines/reference/plainJSRedeclare.symbols
  tests/baselines/reference/plainJSRedeclare.types
  tests/baselines/reference/plainJSRedeclare2.errors.txt
  tests/baselines/reference/plainJSRedeclare2.js
  tests/baselines/reference/plainJSRedeclare2.symbols
  tests/baselines/reference/plainJSRedeclare2.types
  tests/baselines/reference/plainJSRedeclare3.js
  tests/baselines/reference/plainJSRedeclare3.symbols
  tests/baselines/reference/plainJSRedeclare3.types
  tests/baselines/reference/plainJSReservedStrict.errors.txt
  tests/baselines/reference/plainJSReservedStrict.js
  tests/baselines/reference/plainJSReservedStrict.symbols
  tests/baselines/reference/plainJSReservedStrict.types
  tests/cases/conformance/salsa/plainJSBinderErrors.ts
  tests/cases/conformance/salsa/plainJSRedeclare.ts
  tests/cases/conformance/salsa/plainJSRedeclare2.ts
  tests/cases/conformance/salsa/plainJSRedeclare3.ts
  tests/cases/conformance/salsa/plainJSReservedStrict.ts
Labels: Author: Team, For Milestone Bug

#46751 Switch `deferredNodes` from a `Map` to a `Set`.
  src/compiler/checker.ts
  src/compiler/types.ts
Labels: For Uncommitted Bug

#46728 Add function names for code fixes.
  src/services/codefixes/addConvertToUnknownForNonOverlappingTypes.ts
  src/services/codefixes/addEmptyExportDeclaration.ts
  src/services/codefixes/addMissingAsync.ts
  src/services/codefixes/addMissingAwait.ts
  src/services/codefixes/addMissingConst.ts
  src/services/codefixes/addMissingDeclareProperty.ts
  src/services/codefixes/addMissingInvocationForDecorator.ts
  src/services/codefixes/addNameToNamelessParameter.ts
  src/services/codefixes/convertConstToLet.ts
  src/services/codefixes/convertLiteralTypeToMappedType.ts
  src/services/codefixes/convertToMappedObjectType.ts
  src/services/codefixes/convertToTypeOnlyExport.ts
  src/services/codefixes/convertToTypeOnlyImport.ts
  src/services/codefixes/disableJsDiagnostics.ts
  src/services/codefixes/fixAddModuleReferTypeMissingTypeof.ts
  src/services/codefixes/fixAwaitInSyncFunction.ts
  src/services/codefixes/fixCannotFindModule.ts
  src/services/codefixes/fixClassDoesntImplementInheritedAbstractMember.ts
  src/services/codefixes/fixEnableExperimentalDecorators.ts
  src/services/codefixes/fixEnableJsxFlag.ts
  src/services/codefixes/fixIncorrectNamedTupleSyntax.ts
  src/services/codefixes/fixModuleAndTargetOptions.ts
  src/services/codefixes/fixOverrideModifier.ts
  src/services/codefixes/fixReturnTypeInAsyncFunction.ts
  src/services/codefixes/fixStrictClassInitialization.ts
  src/services/codefixes/removeUnnecessaryAwait.ts
  src/services/codefixes/returnValueCorrect.ts
  src/services/codefixes/splitTypeOnlyImport.ts
  src/services/codefixes/useBigintLiteral.ts
  src/services/codefixes/wrapJsxInFragment.ts
Labels: For Uncommitted Bug

#46931 Import chalk with import() syntax
  scripts/browserIntegrationTest.js
  scripts/build/utils.js
Labels: For Uncommitted Bug

#46875 Fix formatting the end of a selection
  src/services/formatting/formatting.ts
  src/services/formatting/formattingScanner.ts
  src/services/utilities.ts
  tests/cases/fourslash/completionsOverridingMethod5.ts
  tests/cases/fourslash/formatSelectionEditAtEndOfRange.ts
  tests/cases/fourslash/refactorExtractType12.ts
  tests/cases/fourslash/refactorExtractType13.ts
Labels: Author: Team, For Uncommitted Bug

#44666 fix(44639): Transpilation of optional chaining combined with type casting results in function call losing its context
  src/compiler/emitter.ts
  src/compiler/transformers/es2020.ts
  src/compiler/transformers/ts.ts
  tests/baselines/reference/optionalChainingInTypeAssertions(target=es2015).js
  tests/baselines/reference/optionalChainingInTypeAssertions(target=es2015).symbols
  tests/baselines/reference/optionalChainingInTypeAssertions(target=es2015).types
  tests/baselines/reference/optionalChainingInTypeAssertions(target=esnext).js
  tests/baselines/reference/optionalChainingInTypeAssertions(target=esnext).symbols
  tests/baselines/reference/optionalChainingInTypeAssertions(target=esnext).types
  tests/cases/conformance/expressions/optionalChaining/optionalChainingInTypeAssertions.ts
Labels: For Milestone Bug

#46960 Fix parsing of parenthesized functions in conditional expressions
  src/compiler/parser.ts
  tests/baselines/reference/parserParenthesizedVariableAndParenthesizedFunctionInTernary.js
  tests/baselines/reference/parserParenthesizedVariableAndParenthesizedFunctionInTernary.symbols
  tests/baselines/reference/parserParenthesizedVariableAndParenthesizedFunctionInTernary.types
  tests/cases/conformance/parser/ecmascript5/parserParenthesizedVariableAndParenthesizedFunctionInTernary.ts
Labels: For Milestone Bug

#46963 Don't call afterEach within beforeEach
  src/testRunner/unittests/createMapShim.ts
  src/testRunner/unittests/createSetShim.ts
  src/testRunner/unittests/debugDeprecation.ts
Labels: Author: Team, For Uncommitted Bug
