Repository microsoft/TypeScript, pull requests merged in 2022-10, with the labels that each got.

#50757 fix(50750): Object type literal with string literal property in contextual typing position causes language service error on all literal type references
  src/services/utilities.ts
  tests/baselines/reference/findAllRefsForStringLiteral.baseline.jsonc
  tests/baselines/reference/renameForStringLiteral.baseline
  tests/cases/fourslash/findAllRefsForStringLiteral.ts
  tests/cases/fourslash/renameForStringLiteral.ts
Labels: For Milestone Bug

#51016 Fix crash in goto-def on `@override`
  src/services/goToDefinition.ts
  tests/cases/fourslash/goToDefinitionOverriddenMember16.ts
Labels: Author: Team, For Milestone Bug

#50630 Adding a JSDoc comment to the es5 type declarations to describe the functionality of Date.now()
  src/lib/es5.d.ts
  tests/baselines/reference/destructuringParameterDeclaration4.errors.txt
  tests/baselines/reference/destructuringTuple.errors.txt
  tests/baselines/reference/duplicateNumericIndexers.errors.txt
  tests/baselines/reference/externModule.errors.txt
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty.errors.txt
  tests/baselines/reference/narrowExceptionVariableInCatchClause.errors.txt
  tests/baselines/reference/narrowFromAnyWithInstanceof.errors.txt
  tests/baselines/reference/narrowFromAnyWithTypePredicate.errors.txt
  tests/baselines/reference/parserRegularExpressionDivideAmbiguity1.errors.txt
  tests/baselines/reference/parserRegularExpressionDivideAmbiguity2.errors.txt
  tests/baselines/reference/parserS7.2_A1.5_T2.errors.txt
  tests/baselines/reference/parserS7.3_A1.1_T2.errors.txt
  tests/baselines/reference/parserS7.6_A4.2_T1.errors.txt
  tests/baselines/reference/parserUnicode1.errors.txt
  tests/baselines/reference/promisePermutations.errors.txt
  tests/baselines/reference/promisePermutations2.errors.txt
  tests/baselines/reference/promisePermutations3.errors.txt
  tests/baselines/reference/redefineArray.errors.txt
  tests/baselines/reference/scannerS7.2_A1.5_T2.errors.txt
  tests/baselines/reference/scannerS7.3_A1.1_T2.errors.txt
  tests/baselines/reference/scannerS7.6_A4.2_T1.errors.txt
Labels: For Backlog Bug

#51045 Update GitHub Actions
  .github/workflows/accept-baselines-fix-lints.yaml
  .github/workflows/codeql.yml
  .github/workflows/ensure-related-repos-run-crons.yml
  .github/workflows/new-release-branch.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release-branch-artifact.yaml
  .github/workflows/rich-navigation.yml
  .github/workflows/set-version.yaml
  .github/workflows/sync-branch.yaml
  .github/workflows/sync-wiki.yml
  .github/workflows/update-lkg.yml
  .github/workflows/update-package-lock.yaml
Labels: Author: Team, For Uncommitted Bug

#51048 Remove configureLanguageServiceBuild, instrumenter
  Gulpfile.js
  scripts/configureLanguageServiceBuild.ts
  src/instrumenter/instrumenter.ts
  src/instrumenter/tsconfig.json
  src/loggedIO/tsconfig-tsc-instrumented.json
Labels: Author: Team, For Uncommitted Bug

#51061 Use typescript.d.ts in APISample tests
  src/harness/harnessIO.ts
  tests/baselines/reference/APISample_Watch.js
  tests/baselines/reference/APISample_WatchWithDefaults.js
  tests/baselines/reference/APISample_WatchWithOwnWatchHost.js
  tests/baselines/reference/APISample_compile.js
  tests/baselines/reference/APISample_jsdoc.js
  tests/baselines/reference/APISample_linter.js
  tests/baselines/reference/APISample_parseConfig.js
  tests/baselines/reference/APISample_transform.js
  tests/baselines/reference/APISample_watcher.js
  tests/cases/compiler/APISample_Watch.ts
  tests/cases/compiler/APISample_WatchWithDefaults.ts
  tests/cases/compiler/APISample_WatchWithOwnWatchHost.ts
  tests/cases/compiler/APISample_compile.ts
  tests/cases/compiler/APISample_jsdoc.ts
  tests/cases/compiler/APISample_linter.ts
  tests/cases/compiler/APISample_parseConfig.ts
  tests/cases/compiler/APISample_transform.ts
  tests/cases/compiler/APISample_watcher.ts
Labels: Author: Team, For Uncommitted Bug

#51087 Plugins in project were adding up after every config file reload
  src/server/project.ts
  src/testRunner/unittests/tsserver/plugins.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/tsserver/plugins/gets-external-files-with-config-file-reload.js
Labels: Author: Team, For Uncommitted Bug

#51079 Plugin probe location is higher priority than peer node_modules
  src/server/project.ts
Labels: Author: Team, For Backlog Bug

#51081 fix(51017): Make lineText in the references response opt-out
  src/server/protocol.ts
  src/server/session.ts
  src/testRunner/unittests/tsserver/getFileReferences.ts
  src/testRunner/unittests/tsserver/helpers.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
Labels: For Milestone Bug

#51082 fix(51072): ts.preProcessFile finds import in template string after conditional expression with template strings
  src/services/preProcess.ts
  src/testRunner/unittests/services/preProcessFile.ts
Labels: For Backlog Bug

#51131 Fix nightly publish oops in Gulpfile
  Gulpfile.mjs
Labels: Author: Team, For Uncommitted Bug

#51107 fix(51100): ensure tsserver shuts down when parent process is killed
  src/tsserver/nodeServer.ts
Labels: For Milestone Bug

#51091 Remove unused declarations array in extractSymbol's TargetRange
  src/services/refactors/extractSymbol.ts
Labels: Author: Team, For Uncommitted Bug

#50904 Overloads shouldn't gain @deprecated tags of other overloads in quick info
  src/services/symbolDisplay.ts
  tests/cases/fourslash/quickInfoJsDocTagsFunctionOverload06.ts
Labels: For Uncommitted Bug

#51095 Fix isExhaustiveSwitchStatement to better handle circularities
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/exhaustiveSwitchCheckCircularity.errors.txt
  tests/baselines/reference/exhaustiveSwitchCheckCircularity.js
  tests/baselines/reference/exhaustiveSwitchCheckCircularity.symbols
  tests/baselines/reference/exhaustiveSwitchCheckCircularity.types
  tests/cases/compiler/exhaustiveSwitchCheckCircularity.ts
Labels: Author: Team, For Milestone Bug

#51140 Check nested weak types in intersections on target side of relation
  src/compiler/checker.ts
  tests/baselines/reference/nestedExcessPropertyChecking.errors.txt
  tests/baselines/reference/nestedExcessPropertyChecking.js
  tests/baselines/reference/nestedExcessPropertyChecking.symbols
  tests/baselines/reference/nestedExcessPropertyChecking.types
  tests/cases/compiler/nestedExcessPropertyChecking.ts
Labels: Author: Team, For Milestone Bug

#51151 Remove carve-out in conditional type instantiation that hopefully has been rendered unneeded
  src/compiler/checker.ts
  tests/baselines/reference/recursiveTypeAliasWithSpreadConditionalReturnNotCircular.js
  tests/baselines/reference/recursiveTypeAliasWithSpreadConditionalReturnNotCircular.symbols
  tests/baselines/reference/recursiveTypeAliasWithSpreadConditionalReturnNotCircular.types
  tests/cases/compiler/recursiveTypeAliasWithSpreadConditionalReturnNotCircular.ts
Labels: Author: Team, For Milestone Bug

#51165 feat(51163): quick fix to fill in missing properties not available on mapped type
  src/services/codefixes/fixAddMissingMember.ts
  tests/cases/fourslash/codeFixAddMissingProperties24.ts
Labels: For Backlog Bug

#51142 fix(51112): Parameter JSDoc for a destructured parameter emits an error when a function uses arguments
  src/compiler/checker.ts
  tests/baselines/reference/jsdocParamTag2.errors.txt
  tests/baselines/reference/paramTagWrapping.errors.txt
Labels: For Milestone Bug

#51166 Remove VSDevMode.ps1 and createPlaygroundBuild
  scripts/VSDevMode.ps1
  scripts/createPlaygroundBuild.mjs
Labels: Author: Team, For Uncommitted Bug

#51038 feat(37440): Provide a quick-fix for non-exported types
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/utilities.ts
  src/services/codefixes/fixAddMissingMember.ts
  src/services/codefixes/fixImportNonExportedMember.ts
  src/services/tsconfig.json
  src/services/utilities.ts
  tests/cases/fourslash/codeFixImportNonExportedMember1.ts
  tests/cases/fourslash/codeFixImportNonExportedMember10.ts
  tests/cases/fourslash/codeFixImportNonExportedMember11.ts
  tests/cases/fourslash/codeFixImportNonExportedMember12.ts
  tests/cases/fourslash/codeFixImportNonExportedMember13.ts
  tests/cases/fourslash/codeFixImportNonExportedMember2.ts
  tests/cases/fourslash/codeFixImportNonExportedMember3.ts
  tests/cases/fourslash/codeFixImportNonExportedMember4.ts
  tests/cases/fourslash/codeFixImportNonExportedMember5.ts
  tests/cases/fourslash/codeFixImportNonExportedMember6.ts
  tests/cases/fourslash/codeFixImportNonExportedMember7.ts
  tests/cases/fourslash/codeFixImportNonExportedMember8.ts
  tests/cases/fourslash/codeFixImportNonExportedMember9.ts
  tests/cases/fourslash/codeFixImportNonExportedMember_all1.ts
  tests/cases/fourslash/codeFixImportNonExportedMember_all2.ts
  tests/cases/fourslash/codeFixImportNonExportedMember_all3.ts
  tests/cases/fourslash/codeFixImportNonExportedMember_all4.ts
  tests/cases/fourslash/codeFixImportNonExportedMember_all5.ts
  tests/cases/fourslash/codeFixImportNonExportedMember_all6.ts
  tests/cases/fourslash/codeFixImportNonExportedMember_all7.ts
Labels: For Uncommitted Bug

#50663 fix(50416): correctly names disabled export refactors
  src/harness/fourslashImpl.ts
  src/services/refactors/extractSymbol.ts
  tests/cases/fourslash/server/fixExtractToInnerFunctionDuplicaton.ts
Labels: For Uncommitted Bug

#51167 Add an extra regression test for awaited unresolvable recursive union
  tests/baselines/reference/unresolvableSelfReferencingAwaitedUnion.errors.txt
  tests/baselines/reference/unresolvableSelfReferencingAwaitedUnion.symbols
  tests/baselines/reference/unresolvableSelfReferencingAwaitedUnion.types
  tests/cases/compiler/unresolvableSelfReferencingAwaitedUnion.ts
Labels: For Milestone Bug

#51200 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20221017102418464 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#51204 Remove some unnecessary code discovered by rollup
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug

#51175 fix(51170): Completing an unimplemented property overwrites rest of line
  src/services/completions.ts
  tests/cases/fourslash/completionsOverridingProperties1.ts
  tests/cases/fourslash/completionsOverridingProperties2.ts
  tests/cases/fourslash/completionsOverridingProperties3.ts
Labels: For Milestone Bug

#51135 fix(49196): The '/ * *' snippet should support parameter deconstruction of typescript interface member functions
  src/services/jsDoc.ts
  tests/cases/fourslash/docCommentTemplateInterfacePropertyFunctionType.ts
Labels: For Backlog Bug

#51215 Rename internal functions to `narrowTypeBySwitchOnTypeOf` and `narrowTypeByInKeyword`
  src/compiler/checker.ts
Labels: For Uncommitted Bug

#49663 fix: avoid downleveled dynamic import closing over specifier expression
  src/compiler/transformers/module/module.ts
  tests/baselines/reference/asyncImportNestedYield.js
  tests/baselines/reference/dynamicImportEvaluateSpecifier.js
  tests/baselines/reference/dynamicImportEvaluateSpecifier.symbols
  tests/baselines/reference/dynamicImportEvaluateSpecifier.types
  tests/baselines/reference/dynamicImportTrailingComma.js
  tests/baselines/reference/importCallExpressionDeclarationEmit1.js
  tests/baselines/reference/importCallExpressionGrammarError.js
  tests/baselines/reference/importCallExpressionNestedCJS.js
  tests/baselines/reference/importCallExpressionNestedCJS2.js
  tests/baselines/reference/importCallExpressionReturnPromiseOfAny.js
  tests/baselines/reference/importCallExpressionSpecifierNotStringTypeError.js
  tests/baselines/reference/jsdocInTypeScript.js
  tests/cases/compiler/dynamicImportEvaluateSpecifier.ts
Labels: For Milestone Bug

#50833 Fixed a false positive "await has no effect on the type" diagnostic with mixed generic union
  src/compiler/checker.ts
  tests/cases/fourslash/codeFixRemoveUnnecessaryAwait_mixedUnion.ts
Labels: For Backlog Bug

#51220 Remove old tslint comments
  src/compiler/factory/baseNodeFactory.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/parser.ts
Labels: Author: Team, For Uncommitted Bug

#51219 `markAliasReferenced` should include `ExportValue` as well
  src/compiler/checker.ts
  tests/baselines/reference/importElisionExportNonExportAndDefault.js
  tests/baselines/reference/importElisionExportNonExportAndDefault.symbols
  tests/baselines/reference/importElisionExportNonExportAndDefault.types
  tests/cases/compiler/importElisionExportNonExportAndDefault.ts
Labels: Author: Team, For Milestone Bug

#51227 fix(51222): Go-to-definition on return statements should jump to the containing function declaration
  src/services/goToDefinition.ts
  tests/cases/fourslash/goToDefinitionReturn1.ts
  tests/cases/fourslash/goToDefinitionReturn2.ts
  tests/cases/fourslash/goToDefinitionReturn3.ts
  tests/cases/fourslash/goToDefinitionReturn4.ts
  tests/cases/fourslash/goToDefinitionReturn5.ts
  tests/cases/fourslash/goToDefinitionReturn6.ts
  tests/cases/fourslash/goToDefinitionReturn7.ts
Labels: For Backlog Bug

#51231 fix(51222): Change type
  src/services/goToDefinition.ts
Labels: For Uncommitted Bug

#51076 Revert structuredTypeRelatedTo change and fix isUnitLikeType
  src/compiler/checker.ts
  tests/baselines/reference/unknownControlFlow.errors.txt
  tests/baselines/reference/unknownControlFlow.js
  tests/baselines/reference/unknownControlFlow.symbols
  tests/baselines/reference/unknownControlFlow.types
  tests/cases/conformance/types/unknown/unknownControlFlow.ts
Labels: Author: Team, For Milestone Bug

#50560 fix(50551): Destructuring assignment with var bypasses "variable is used before being assigned" check (2454)
  src/compiler/checker.ts
  tests/baselines/reference/controlFlowDestructuringVariablesInTryCatch.errors.txt
  tests/baselines/reference/controlFlowDestructuringVariablesInTryCatch.js
  tests/baselines/reference/controlFlowDestructuringVariablesInTryCatch.symbols
  tests/baselines/reference/controlFlowDestructuringVariablesInTryCatch.types
  tests/baselines/reference/controlFlowInitializedDestructuringVariables.js
  tests/baselines/reference/controlFlowInitializedDestructuringVariables.symbols
  tests/baselines/reference/controlFlowInitializedDestructuringVariables.types
  tests/cases/compiler/controlFlowDestructuringVariablesInTryCatch.ts
  tests/cases/compiler/controlFlowInitializedDestructuringVariables.ts
Labels: For Backlog Bug

#51247 Make the init config category order predictable
  src/compiler/commandLineParser.ts
Labels: Author: Team, For Uncommitted Bug

#51240 Fix super property transform in async arrow in method
  src/compiler/checker.ts
  src/compiler/transformers/es2017.ts
  src/compiler/transformers/es2018.ts
  src/compiler/types.ts
  tests/baselines/reference/asyncMethodWithSuper_es6.js
  tests/baselines/reference/asyncMethodWithSuper_es6.symbols
  tests/baselines/reference/asyncMethodWithSuper_es6.types
  tests/cases/conformance/async/es6/asyncMethodWithSuper_es6.ts
Labels: Author: Team, For Milestone Bug

#51230 Use base constraint when testing whether a type needs an `Awaited<T>` wrapper
  src/compiler/checker.ts
  tests/baselines/reference/asyncFunctionReturnType.2.js
  tests/baselines/reference/asyncFunctionReturnType.2.symbols
  tests/baselines/reference/asyncFunctionReturnType.2.types
  tests/cases/compiler/asyncFunctionReturnType.2.ts
Labels: Author: Team, For Milestone Bug

#51262 Fix typo in canWatchDirectoryOrFile found by CodeQL
  src/compiler/resolutionCache.ts
Labels: Author: Team, For Uncommitted Bug

#51244 Generate shortest `rootDirs` module specifier instead of first possible
  src/compiler/core.ts
  src/compiler/moduleSpecifiers.ts
  src/services/patternMatcher.ts
  tests/cases/fourslash/autoImportRootDirs.ts
Labels: Author: Team, For Backlog Bug

#51248 Fix apparent typo in getStringMappingType
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug

#51271 Add a GH Action to file a new issue if we go a week without seeing a typescript-error-deltas issue
  .github/workflows/error-deltas-watchdog.yaml
Labels: Author: Team, For Uncommitted Bug

#51299 fix(50068): Refactors trigger debug failure when JSX text has a ' and a tag on the same line.
  src/services/formatting/formattingScanner.ts
  tests/cases/fourslash/extract-const_jsxElement4.ts
  tests/cases/fourslash/extract-const_jsxElement5.ts
  tests/cases/fourslash/extract-const_jsxElement6.ts
  tests/cases/fourslash/extract-const_jsxElement7.ts
Labels: For Milestone Bug

#51300 Dom update 2022-10-25
  src/lib/dom.generated.d.ts
  src/lib/dom.iterable.generated.d.ts
  src/lib/webworker.generated.d.ts
  src/lib/webworker.iterable.generated.d.ts
  tests/baselines/reference/baseCheck.errors.txt
  tests/baselines/reference/extendArray.errors.txt
  tests/baselines/reference/globalThisBlockscopedProperties.types
  tests/baselines/reference/intersectionsOfLargeUnions2.errors.txt
  tests/baselines/reference/jsxFactoryIdentifierWithAbsentParameter.errors.txt
  tests/baselines/reference/jsxFactoryQualifiedNameResolutionError.errors.txt
  tests/baselines/reference/mappedTypeRecursiveInference.types
  tests/baselines/reference/parserRealSource7.errors.txt
Labels: Author: Team, For Uncommitted Bug

#50681 fix(50654): "Move to a new file" breaks the declaration of referenced variable
  src/services/refactors/moveToNewFile.ts
  tests/cases/fourslash/moveToNewFile_requireImport1.ts
  tests/cases/fourslash/moveToNewFile_requireImport2.ts
  tests/cases/fourslash/moveToNewFile_requireImport3.ts
Labels: For Backlog Bug

#51256 fix(51245): Class with parameter decorator in arrow function causes "convert to default export" refactoring failure
  src/services/formatting/rules.ts
  tests/cases/fourslash/refactorConvertExport_namedToDefault1.ts
  tests/cases/fourslash/refactorConvertExport_namedToDefault2.ts
Labels: For Uncommitted Bug

#51263 Update CodeQL workflow and configuration, fix found bugs
  .github/codeql/codeql-configuration.yml
  .github/workflows/codeql.yml
  scripts/generateLocalizedDiagnosticMessages.mjs
  scripts/importDefinitelyTypedTests.mjs
  scripts/processDiagnosticMessages.mjs
Labels: Author: Team, For Uncommitted Bug

#51320 fix(51301): Fixing an unused import at the end of a line removes the newline
  src/services/textChanges.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_destructuring_elements1.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_destructuring_elements2.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_destructuring_elements3.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_destructuring_elements4.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_destructuring_elements5.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_destructuring_elements6.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_importSpecifier1.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_importSpecifier2.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_importSpecifier3.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_importSpecifier4.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_importSpecifier5.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_parameter1.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_parameter2.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_parameter3.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_parameter4.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_parameter5.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_parameter6.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_typeParameter1.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_typeParameter2.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_typeParameter3.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_typeParameter4.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_typeParameter5.ts
Labels: For Milestone Bug

#51324 Fix assertion functions accessed via wildcard imports
  src/compiler/checker.ts
  tests/baselines/reference/assertionFunctionWildcardImport1.js
  tests/baselines/reference/assertionFunctionWildcardImport1.symbols
  tests/baselines/reference/assertionFunctionWildcardImport1.types
  tests/baselines/reference/assertionFunctionWildcardImport2.js
  tests/baselines/reference/assertionFunctionWildcardImport2.symbols
  tests/baselines/reference/assertionFunctionWildcardImport2.types
  tests/cases/compiler/assertionFunctionWildcardImport1.ts
  tests/cases/compiler/assertionFunctionWildcardImport2.ts
Labels: Author: Team, For Milestone Bug

#51295 fix for-in enumeration containing yield in generator
  src/compiler/transformers/generators.ts
  tests/baselines/reference/es5-asyncFunctionForInStatements.js
  tests/baselines/reference/yieldInForInInDownlevelGenerator.js
  tests/baselines/reference/yieldInForInInDownlevelGenerator.symbols
  tests/baselines/reference/yieldInForInInDownlevelGenerator.types
  tests/cases/compiler/yieldInForInInDownlevelGenerator.ts
Labels: Author: Team, For Milestone Bug

#51345 Fix for broken baseline in yieldInForInInDownlevelGenerator
  tests/baselines/reference/yieldInForInInDownlevelGenerator.js
Labels: Author: Team, For Uncommitted Bug

#51297 In for-await-of, only call return() for an abrupt completion in user code
  src/compiler/transformers/es2018.ts
  src/testRunner/unittests/evaluation/forAwaitOf.ts
  tests/baselines/reference/emitter.forAwait(target=es2015).js
  tests/baselines/reference/emitter.forAwait(target=es2017).js
  tests/baselines/reference/emitter.forAwait(target=es5).js
  tests/baselines/reference/forAwaitPerIterationBindingDownlevel.js
  tests/baselines/reference/operationsAvailableOnPromisedType.js
  tests/baselines/reference/topLevelAwait.1(module=es2022,target=es2015).js
  tests/baselines/reference/topLevelAwait.1(module=es2022,target=es2017).js
  tests/baselines/reference/topLevelAwait.1(module=esnext,target=es2015).js
  tests/baselines/reference/topLevelAwait.1(module=esnext,target=es2017).js
  tests/baselines/reference/topLevelAwait.1(module=system,target=es2015).js
  tests/baselines/reference/topLevelAwait.1(module=system,target=es2017).js
Labels: Author: Team, For Milestone Bug

#51246 Compress buildinfo by changing how affectedFilesPendingEmit are stored
  src/compiler/builder.ts
  src/testRunner/unittests/tsbuild/helpers.ts
  tests/baselines/reference/tsbuild/demo/in-bad-ref-branch-reports-the-error-about-files-not-in-rootDir-at-the-import-location.js
  tests/baselines/reference/tsbuild/inferredTypeFromTransitiveModule/reports-errors-in-files-affected-by-change-in-signature-with-isolatedModules.js
  tests/baselines/reference/tsbuild/javascriptProjectEmit/loads-js-based-projects-and-emits-them-correctly.js
  tests/baselines/reference/tsbuild/noEmit/semantic-errors-with-incremental.js
  tests/baselines/reference/tsbuild/noEmit/syntax-errors-with-incremental.js
  tests/baselines/reference/tsbuild/noEmitOnError/semantic-errors-with-incremental.js
  tests/baselines/reference/tsbuild/resolveJsonModule/include-only.js
  tests/baselines/reference/tsbuild/sample1/does-not-build-downstream-projects-if-upstream-projects-have-errors.js
  tests/baselines/reference/tsbuild/transitiveReferences/reports-error-about-module-not-found-with-node-resolution-with-external-module-name.js
  tests/baselines/reference/tsbuildWatch/demo/updates-with-bad-reference.js
  tests/baselines/reference/tsbuildWatch/noEmit/does-not-go-in-loop-when-watching-when-no-files-are-emitted-with-incremental.js
  tests/baselines/reference/tsbuildWatch/noEmitOnError/does-not-emit-any-files-on-error-with-incremental.js
  tests/baselines/reference/tsbuildWatch/programUpdates/reportErrors/when-preserveWatchOutput-is-not-used.js
  tests/baselines/reference/tsbuildWatch/programUpdates/reportErrors/when-preserveWatchOutput-is-passed-on-command-line.js
  tests/baselines/reference/tsc/incremental/noEmit-changes-composite.js
  tests/baselines/reference/tsc/incremental/noEmit-changes-incremental-declaration.js
  tests/baselines/reference/tsc/incremental/noEmit-changes-incremental.js
  tests/baselines/reference/tsc/incremental/noEmit-changes-with-initial-noEmit-composite.js
  tests/baselines/reference/tsc/incremental/noEmit-changes-with-initial-noEmit-incremental-declaration.js
  tests/baselines/reference/tsc/incremental/noEmit-changes-with-initial-noEmit-incremental.js
  tests/baselines/reference/tsc/incremental/when-project-has-strict-true.js
  tests/baselines/reference/tsc/incremental/with-noEmitOnError-semantic-errors.js
  tests/baselines/reference/tsc/incremental/with-noEmitOnError-syntax-errors.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependencies/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependenciesAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/default/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/defaultAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModules/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModulesAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/watchApi/noEmit-with-composite-with-emit-builder.js
  tests/baselines/reference/tscWatch/watchApi/noEmit-with-composite-with-semantic-builder.js
  tests/baselines/reference/tscWatch/watchApi/noEmitOnError-with-composite-with-emit-builder.js
  tests/baselines/reference/tscWatch/watchApi/noEmitOnError-with-composite-with-semantic-builder.js
  tests/baselines/reference/tscWatch/watchApi/semantic-builder-emitOnlyDts.js
  tests/baselines/reference/tsserver/projectReferences/auto-import-with-referenced-project-when-built-with-disableSourceOfProjectReferenceRedirect.js
  tests/baselines/reference/tsserver/projectReferences/auto-import-with-referenced-project-when-built.js
Labels: Author: Team, For Uncommitted Bug, Merge/Review for Next Release

#51243 Fixes the tests that got disabled when generating config set es2016 expecting to find libFile and remove incorrect affects flag from listFilesOnly
  src/compiler/commandLineParser.ts
  src/testRunner/unittests/tsc/helpers.ts
  src/testRunner/unittests/tsc/listFilesOnly.ts
  src/testRunner/unittests/tscWatch/programUpdates.ts
  tests/baselines/reference/tsc/listFilesOnly/combined-with-incremental.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/declarationDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/when-outDir-and-declarationDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/when-outDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/with-outFile.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/without-outDir-or-outFile-is-specified-with-declaration-enabled.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/without-outDir-or-outFile-is-specified.js
Labels: Author: Team, For Uncommitted Bug

#50977 Set impliedNodeFormat on sourceFile we get from host to ensure the field is set correctly
  src/compiler/program.ts
  src/harness/fakesHosts.ts
  src/harness/virtualFileSystemWithWatch.ts
  src/testRunner/unittests/tsbuild/moduleResolution.ts
  tests/baselines/reference/tsbuild/moduleResolution/impliedNodeFormat-differs-between-projects-for-shared-file.js
Labels: Author: Team, For Milestone Bug
