Repository microsoft/TypeScript, pull requests merged in 2022-03, with the labels that each got.

#48067 Fix incorrect parser error assumption in semicolon handling leading to incremental parser brokenness
  src/compiler/parser.ts
  tests/baselines/reference/parser0_004152.errors.txt
  tests/cases/fourslash/parserCorruptionAfterMapInClass.ts
Labels: Author: Team, For Milestone Bug

#48066 Fix modifier order for class member completions
  src/services/completions.ts
  tests/cases/fourslash/completionsOverridingMethod.ts
  tests/cases/fourslash/completionsOverridingMethod1.ts
  tests/cases/fourslash/completionsOverridingMethod10.ts
  tests/cases/fourslash/completionsOverridingMethod11.ts
  tests/cases/fourslash/completionsOverridingMethod12.ts
  tests/cases/fourslash/completionsOverridingMethod2.ts
  tests/cases/fourslash/completionsOverridingMethod3.ts
  tests/cases/fourslash/completionsOverridingMethod4.ts
  tests/cases/fourslash/completionsOverridingMethod5.ts
  tests/cases/fourslash/completionsOverridingMethod6.ts
  tests/cases/fourslash/completionsOverridingMethod7.ts
  tests/cases/fourslash/completionsOverridingMethod8.ts
  tests/cases/fourslash/completionsOverridingMethod9.ts
Labels: Author: Team, For Milestone Bug

#47951 fix(47946): Literal types cannot be used in JSDoc export default { } syntax
  src/compiler/checker.ts
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment8.js
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment8.symbols
  tests/baselines/reference/checkJsdocTypeTagOnExportAssignment8.types
  tests/cases/compiler/checkJsdocTypeTagOnExportAssignment8.ts
Labels: For Backlog Bug

#48062 Esm imports of cjs files should unconditionally have a default patched on
  src/compiler/checker.ts
  tests/baselines/reference/nodeModules1(module=node12).types
  tests/baselines/reference/nodeModules1(module=nodenext).types
  tests/baselines/reference/nodeModulesAllowJs1(module=node12).types
  tests/baselines/reference/nodeModulesAllowJs1(module=nodenext).types
  tests/baselines/reference/nodeModulesAllowJsPackageExports(module=node12).symbols
  tests/baselines/reference/nodeModulesAllowJsPackageExports(module=node12).types
  tests/baselines/reference/nodeModulesAllowJsPackageExports(module=nodenext).symbols
  tests/baselines/reference/nodeModulesAllowJsPackageExports(module=nodenext).types
  tests/baselines/reference/nodeModulesAllowJsPackagePatternExports(module=node12).symbols
  tests/baselines/reference/nodeModulesAllowJsPackagePatternExports(module=node12).types
  tests/baselines/reference/nodeModulesAllowJsPackagePatternExports(module=nodenext).symbols
  tests/baselines/reference/nodeModulesAllowJsPackagePatternExports(module=nodenext).types
  tests/baselines/reference/nodeModulesAllowJsPackagePatternExportsTrailers(module=nodenext).symbols
  tests/baselines/reference/nodeModulesAllowJsPackagePatternExportsTrailers(module=nodenext).types
  tests/baselines/reference/nodeModulesPackageExports(module=node12).symbols
  tests/baselines/reference/nodeModulesPackageExports(module=node12).types
  tests/baselines/reference/nodeModulesPackageExports(module=nodenext).symbols
  tests/baselines/reference/nodeModulesPackageExports(module=nodenext).types
  tests/baselines/reference/nodeModulesPackagePatternExports(module=node12).symbols
  tests/baselines/reference/nodeModulesPackagePatternExports(module=node12).types
  tests/baselines/reference/nodeModulesPackagePatternExports(module=nodenext).symbols
  tests/baselines/reference/nodeModulesPackagePatternExports(module=nodenext).types
  tests/baselines/reference/nodeModulesPackagePatternExportsTrailers(module=nodenext).symbols
  tests/baselines/reference/nodeModulesPackagePatternExportsTrailers(module=nodenext).types
  tests/baselines/reference/nodeModulesTypesVersionPackageExports(module=node12).symbols
  tests/baselines/reference/nodeModulesTypesVersionPackageExports(module=nodenext).symbols
  tests/baselines/reference/nodeNextCjsNamespaceImportDefault1.js
  tests/baselines/reference/nodeNextCjsNamespaceImportDefault1.symbols
  tests/baselines/reference/nodeNextCjsNamespaceImportDefault1.types
  tests/baselines/reference/nodeNextCjsNamespaceImportDefault2.js
  tests/baselines/reference/nodeNextCjsNamespaceImportDefault2.symbols
  tests/baselines/reference/nodeNextCjsNamespaceImportDefault2.types
  tests/cases/compiler/nodeNextCjsNamespaceImportDefault1.ts
  tests/cases/compiler/nodeNextCjsNamespaceImportDefault2.ts
Labels: Author: Team, For Milestone Bug

#47807 Add import assertions to type only imports and import types to force the resolution mode of the specifier
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/emitter.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/moduleSpecifiers.ts
  src/compiler/parser.ts
  src/compiler/program.ts
  src/compiler/transformers/declarations.ts
  src/compiler/types.ts
  src/compiler/visitorPublic.ts
  src/server/moduleSpecifierCache.ts
  src/services/exportInfoMap.ts
  src/testRunner/unittests/tsserver/moduleSpecifierCache.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/nodeModulesDeclarationEmitDynamicImportWithPackageExports.js
  tests/baselines/reference/nodeModulesDeclarationEmitDynamicImportWithPackageExports.types
  tests/baselines/reference/nodeModulesImportModeDeclarationEmit1(module=node12).errors.txt
  tests/baselines/reference/nodeModulesImportModeDeclarationEmit1(module=node12).js
  tests/baselines/reference/nodeModulesImportModeDeclarationEmit1(module=node12).symbols
  tests/baselines/reference/nodeModulesImportModeDeclarationEmit1(module=node12).types
  tests/baselines/reference/nodeModulesImportModeDeclarationEmit1(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesImportModeDeclarationEmit1(module=nodenext).js
  tests/baselines/reference/nodeModulesImportModeDeclarationEmit1(module=nodenext).symbols
  tests/baselines/reference/nodeModulesImportModeDeclarationEmit1(module=nodenext).types
  tests/baselines/reference/nodeModulesImportModeDeclarationEmit2(module=node12).errors.txt
  tests/baselines/reference/nodeModulesImportModeDeclarationEmit2(module=node12).js
  tests/baselines/reference/nodeModulesImportModeDeclarationEmit2(module=node12).symbols
  tests/baselines/reference/nodeModulesImportModeDeclarationEmit2(module=node12).types
  tests/baselines/reference/nodeModulesImportModeDeclarationEmit2(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesImportModeDeclarationEmit2(module=nodenext).js
  tests/baselines/reference/nodeModulesImportModeDeclarationEmit2(module=nodenext).symbols
  tests/baselines/reference/nodeModulesImportModeDeclarationEmit2(module=nodenext).types
  tests/baselines/reference/nodeModulesImportModeDeclarationEmitErrors1(module=node12).errors.txt
  tests/baselines/reference/nodeModulesImportModeDeclarationEmitErrors1(module=node12).js
  tests/baselines/reference/nodeModulesImportModeDeclarationEmitErrors1(module=node12).symbols
  tests/baselines/reference/nodeModulesImportModeDeclarationEmitErrors1(module=node12).types
  tests/baselines/reference/nodeModulesImportModeDeclarationEmitErrors1(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesImportModeDeclarationEmitErrors1(module=nodenext).js
  tests/baselines/reference/nodeModulesImportModeDeclarationEmitErrors1(module=nodenext).symbols
  tests/baselines/reference/nodeModulesImportModeDeclarationEmitErrors1(module=nodenext).types
  tests/baselines/reference/nodeModulesImportTypeModeDeclarationEmit1(module=node12).js
  tests/baselines/reference/nodeModulesImportTypeModeDeclarationEmit1(module=node12).symbols
  tests/baselines/reference/nodeModulesImportTypeModeDeclarationEmit1(module=node12).types
  tests/baselines/reference/nodeModulesImportTypeModeDeclarationEmit1(module=nodenext).js
  tests/baselines/reference/nodeModulesImportTypeModeDeclarationEmit1(module=nodenext).symbols
  tests/baselines/reference/nodeModulesImportTypeModeDeclarationEmit1(module=nodenext).types
  tests/baselines/reference/nodeModulesImportTypeModeDeclarationEmitErrors1(module=node12).errors.txt
  tests/baselines/reference/nodeModulesImportTypeModeDeclarationEmitErrors1(module=node12).js
  tests/baselines/reference/nodeModulesImportTypeModeDeclarationEmitErrors1(module=node12).symbols
  tests/baselines/reference/nodeModulesImportTypeModeDeclarationEmitErrors1(module=node12).types
  tests/baselines/reference/nodeModulesImportTypeModeDeclarationEmitErrors1(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesImportTypeModeDeclarationEmitErrors1(module=nodenext).js
  tests/baselines/reference/nodeModulesImportTypeModeDeclarationEmitErrors1(module=nodenext).symbols
  tests/baselines/reference/nodeModulesImportTypeModeDeclarationEmitErrors1(module=nodenext).types
  tests/cases/conformance/node/nodeModulesImportModeDeclarationEmit1.ts
  tests/cases/conformance/node/nodeModulesImportModeDeclarationEmit2.ts
  tests/cases/conformance/node/nodeModulesImportModeDeclarationEmitErrors1.ts
  tests/cases/conformance/node/nodeModulesImportTypeModeDeclarationEmit1.ts
  tests/cases/conformance/node/nodeModulesImportTypeModeDeclarationEmitErrors1.ts
Labels: Author: Team, For Milestone Bug

#48078 Add explicit assertion on somewhat commonly incorrectly passed argument
  src/compiler/moduleNameResolver.ts
Labels: Author: Team, Housekeeping, For Uncommitted Bug

#47990 Fix const enum comments
  src/compiler/transformers/ts.ts
  tests/baselines/reference/constEnums.js
  tests/baselines/reference/constEnums.symbols
  tests/baselines/reference/constEnums.types
  tests/cases/compiler/constEnums.ts
Labels: For Backlog Bug

#48015 Add extra test for call expression in removeComments=false mode
  tests/baselines/reference/emitOneLineVariableDeclarationRemoveCommentsFalse.js
  tests/baselines/reference/emitOneLineVariableDeclarationRemoveCommentsFalse.symbols
  tests/baselines/reference/emitOneLineVariableDeclarationRemoveCommentsFalse.types
  tests/cases/compiler/emitOneLineVariableDeclarationRemoveCommentsFalse.ts
Labels: Author: Team, For Milestone Bug

#33544 fix: add this type for Reflect.defineProperty
  src/lib/es2015.reflect.d.ts
Labels: For Uncommitted Bug

#33767 Add an overload to Object.freeze that preserves literal types
  src/lib/es5.d.ts
  tests/baselines/reference/circularContextualReturnType.symbols
  tests/baselines/reference/circularContextualReturnType.types
  tests/baselines/reference/destructuringParameterDeclaration4.errors.txt
  tests/baselines/reference/destructuringTuple.errors.txt
  tests/baselines/reference/duplicateNumericIndexers.errors.txt
  tests/baselines/reference/externModule.errors.txt
  tests/baselines/reference/invalidTypeOfTarget.errors.txt
  tests/baselines/reference/jsEnumTagOnObjectFrozen.symbols
  tests/baselines/reference/jsEnumTagOnObjectFrozen.types
  tests/baselines/reference/keyofAndIndexedAccess.symbols
  tests/baselines/reference/keyofAndIndexedAccess.types
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty.errors.txt
  tests/baselines/reference/narrowExceptionVariableInCatchClause.errors.txt
  tests/baselines/reference/narrowFromAnyWithInstanceof.errors.txt
  tests/baselines/reference/narrowFromAnyWithTypePredicate.errors.txt
  tests/baselines/reference/objectFreeze.symbols
  tests/baselines/reference/objectFreeze.types
  tests/baselines/reference/objectFromEntries.symbols
  tests/baselines/reference/objectFromEntries.types
  tests/baselines/reference/parserMemberAccessAfterPostfixExpression1.errors.txt
  tests/baselines/reference/parserS7.2_A1.5_T2.errors.txt
  tests/baselines/reference/parserS7.3_A1.1_T2.errors.txt
  tests/baselines/reference/parserS7.6_A4.2_T1.errors.txt
  tests/baselines/reference/parserUnicode1.errors.txt
  tests/baselines/reference/promisePermutations.errors.txt
  tests/baselines/reference/promisePermutations2.errors.txt
  tests/baselines/reference/promisePermutations3.errors.txt
  tests/baselines/reference/redefineArray.errors.txt
  tests/baselines/reference/scannerS7.2_A1.5_T2.errors.txt
  tests/baselines/reference/scannerS7.3_A1.1_T2.errors.txt
  tests/baselines/reference/scannerS7.6_A4.2_T1.errors.txt
  tests/baselines/reference/taggedTemplateStringsWithOverloadResolution1.errors.txt
  tests/baselines/reference/taggedTemplateStringsWithOverloadResolution1_ES6.errors.txt
Labels: Author: Team, For Uncommitted Bug

#48028 Prevent crash on code fixes on default keyword
  src/services/codefixes/importFixes.ts
  tests/cases/fourslash/addAllMissingImportsNoCrash2.ts
Labels: Author: Team, For Milestone Bug

#44545 fix(44477): confuse comment emit when const multi enum has same key
  src/compiler/transformers/ts.ts
  tests/baselines/reference/amdModuleConstEnumUsage.js
  tests/baselines/reference/assignmentNonObjectTypeConstraints.js
  tests/baselines/reference/blockScopedEnumVariablesUseBeforeDef.js
  tests/baselines/reference/blockScopedEnumVariablesUseBeforeDef_preserve.js
  tests/baselines/reference/constEnum3.js
  tests/baselines/reference/constEnumExternalModule.js
  tests/baselines/reference/constEnumNamespaceReferenceCausesNoImport(isolatedmodules=false).js
  tests/baselines/reference/constEnumNamespaceReferenceCausesNoImport2.js
  tests/baselines/reference/constEnumNoEmitReexport.js
  tests/baselines/reference/constEnumNoPreserveDeclarationReexport.js
  tests/baselines/reference/constEnumOnlyModuleMerging.js
  tests/baselines/reference/constEnumPropertyAccess1.js
  tests/baselines/reference/constEnumPropertyAccess2.js
  tests/baselines/reference/constEnumSyntheticNodesComments.js
  tests/baselines/reference/constEnumToStringWithComments.js
  tests/baselines/reference/constEnums.js
  tests/baselines/reference/constIndexedAccess.js
  tests/baselines/reference/constantEnumAssert.js
  tests/baselines/reference/declarationEmitStringEnumUsedInNonlocalSpread.js
  tests/baselines/reference/destructuringParameterDeclaration3ES5.js
  tests/baselines/reference/destructuringParameterDeclaration3ES5iterable.js
  tests/baselines/reference/destructuringParameterDeclaration3ES6.js
  tests/baselines/reference/discriminantPropertyCheck.js
  tests/baselines/reference/enumLiteralTypes1.js
  tests/baselines/reference/enumLiteralTypes2.js
  tests/baselines/reference/enumLiteralTypes3.js
  tests/baselines/reference/enumUsedBeforeDeclaration.js
  tests/baselines/reference/enums.js
  tests/baselines/reference/es6ModuleConstEnumDeclaration.js
  tests/baselines/reference/es6ModuleConstEnumDeclaration2.js
  tests/baselines/reference/exportImportCanSubstituteConstEnumForValue.js
  tests/baselines/reference/importAliasFromNamespace.js
  tests/baselines/reference/importsNotUsedAsValues_error.js
  tests/baselines/reference/stringEnumLiteralTypes1.js
  tests/baselines/reference/stringEnumLiteralTypes2.js
  tests/baselines/reference/stringEnumLiteralTypes3.js
  tests/baselines/reference/systemModuleConstEnums.js
  tests/baselines/reference/tscWatch/emit/emit-file-content/elides-const-enums-correctly-in-incremental-compilation.js
  tests/cases/fourslash/constEnumsEmitOutputInMultipleFiles.ts
Labels: For Backlog Bug

#40973 Fixes #35735: Avoids listing missing properties for types with only call/construct signatures
  src/compiler/checker.ts
  tests/baselines/reference/arrayAssignmentTest1.errors.txt
  tests/baselines/reference/arrayAssignmentTest2.errors.txt
  tests/baselines/reference/arrayAssignmentTest4.errors.txt
  tests/baselines/reference/assignLambdaToNominalSubtypeOfFunction.errors.txt
  tests/baselines/reference/assignmentCompatWithCallSignatures2.errors.txt
  tests/baselines/reference/assignmentCompatWithConstructSignatures2.errors.txt
  tests/baselines/reference/avoidListingPropertiesForTypesWithOnlyCallOrConstructSignatures.errors.txt
  tests/baselines/reference/avoidListingPropertiesForTypesWithOnlyCallOrConstructSignatures.js
  tests/baselines/reference/avoidListingPropertiesForTypesWithOnlyCallOrConstructSignatures.symbols
  tests/baselines/reference/avoidListingPropertiesForTypesWithOnlyCallOrConstructSignatures.types
  tests/baselines/reference/checkJsdocTypeTag6.errors.txt
  tests/baselines/reference/crashInsourcePropertyIsRelatableToTargetProperty.errors.txt
  tests/baselines/reference/functionToFunctionWithPropError.errors.txt
  tests/baselines/reference/functionToFunctionWithPropError.js
  tests/baselines/reference/functionToFunctionWithPropError.symbols
  tests/baselines/reference/functionToFunctionWithPropError.types
  tests/baselines/reference/intTypeCheck.errors.txt
  tests/cases/compiler/avoidListingPropertiesForTypesWithOnlyCallOrConstructSignatures.ts
  tests/cases/compiler/functionToFunctionWithPropError.ts
Labels: For Backlog Bug

#43937 Fix contextual discrimination for omitted members
  src/compiler/checker.ts
  tests/baselines/reference/discriminantPropertyInference.js
  tests/baselines/reference/discriminantPropertyInference.symbols
  tests/baselines/reference/discriminantPropertyInference.types
  tests/baselines/reference/tsxDiscriminantPropertyInference.js
  tests/baselines/reference/tsxDiscriminantPropertyInference.symbols
  tests/baselines/reference/tsxDiscriminantPropertyInference.types
  tests/cases/compiler/discriminantPropertyInference.ts
  tests/cases/compiler/tsxDiscriminantPropertyInference.tsx
Labels: For Backlog Bug

#45069 Note git's core.longpaths in CONTRIBUTING
  CONTRIBUTING.md
Labels: Author: Team, For Uncommitted Bug

#44578 support generic type when checking implicit conversion of symbol to string
  src/compiler/checker.ts
  tests/baselines/reference/noImplicitSymbolToString.errors.txt
  tests/baselines/reference/noImplicitSymbolToString.js
  tests/baselines/reference/noImplicitSymbolToString.symbols
  tests/baselines/reference/noImplicitSymbolToString.types
  tests/cases/compiler/noImplicitSymbolToString.ts
Labels: For Backlog Bug

#46798 Describe jsxFragmentFactory option default value
  src/compiler/commandLineParser.ts
Labels: Housekeeping, For Uncommitted Bug

#46923 fix(43154): Syntax error in emitted output from tsc when exporting value of symbol key
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitClassMemberWithComputedPropertyName.js
  tests/baselines/reference/declarationEmitClassMemberWithComputedPropertyName.symbols
  tests/baselines/reference/declarationEmitClassMemberWithComputedPropertyName.types
  tests/cases/compiler/declarationEmitClassMemberWithComputedPropertyName.ts
Labels: For Backlog Bug

#47991 Fix crash when `this` is typed as a generic `T` with no type constraints
  src/compiler/checker.ts
  tests/baselines/reference/protectedMembersThisParameter.errors.txt
  tests/baselines/reference/protectedMembersThisParameter.js
  tests/baselines/reference/protectedMembersThisParameter.symbols
  tests/baselines/reference/protectedMembersThisParameter.types
  tests/baselines/reference/publicGetterProtectedSetterFromThisParameter.errors.txt
  tests/cases/compiler/protectedMembersThisParameter.ts
Labels: For Backlog Bug

#47978 Add a test for emit of a computed property based on an aliased symbol
  tests/baselines/reference/symbolProperty61.js
  tests/baselines/reference/symbolProperty61.symbols
  tests/baselines/reference/symbolProperty61.types
  tests/cases/conformance/es6/Symbols/symbolProperty61.ts
Labels: Housekeeping, For Uncommitted Bug

#48114 Show error when trying to instantiate a union of abstract and concrete constructors
  src/compiler/checker.ts
  tests/baselines/reference/abstractClassUnionInstantiation.errors.txt
  tests/baselines/reference/abstractClassUnionInstantiation.js
  tests/baselines/reference/abstractClassUnionInstantiation.symbols
  tests/baselines/reference/abstractClassUnionInstantiation.types
  tests/cases/compiler/abstractClassUnionInstantiation.ts
Labels: For Backlog Bug

#48106 Tidy up navto and find-file-references
  src/server/session.ts
  src/testRunner/unittests/tsserver/declarationFileMaps.ts
Labels: Author: Team, For Uncommitted Bug

#48079 Don't crash on non-literal computed property names during getPropertyAssignment
  src/compiler/utilities.ts
  src/harness/client.ts
  tests/cases/fourslash/server/tsconfigComputedPropertyError.ts
Labels: Author: Team, For Milestone Bug

#46981 Bail on 0- and 1-length lists in `removeSubtypes` to avoid spurious circularity problems
  src/compiler/checker.ts
  tests/baselines/reference/trivialSubtypeReductionNoStructuralCheck.errors.txt
  tests/baselines/reference/trivialSubtypeReductionNoStructuralCheck.js
  tests/baselines/reference/trivialSubtypeReductionNoStructuralCheck.symbols
  tests/baselines/reference/trivialSubtypeReductionNoStructuralCheck.types
  tests/baselines/reference/trivialSubtypeReductionNoStructuralCheck2.js
  tests/baselines/reference/trivialSubtypeReductionNoStructuralCheck2.symbols
  tests/baselines/reference/trivialSubtypeReductionNoStructuralCheck2.types
  tests/cases/compiler/trivialSubtypeReductionNoStructuralCheck.ts
  tests/cases/compiler/trivialSubtypeReductionNoStructuralCheck2.ts
Labels: Author: Team, For Uncommitted Bug

#44416 Rename SyntaxKind.JSDocComment -> JSDoc
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/factory/nodeTests.ts
  src/compiler/parser.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/compiler/utilitiesPublic.ts
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.@@ does not start a new tag.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.@link tags.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.Chained tags, no leading whitespace.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.Initial email address is not a tag.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.Initial star is not a tag.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.Initial star space is not a tag.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.Nested @param tags.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.argSynonymForParamTag.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.argumentSynonymForParamTag.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.asteriskAfterPreamble.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.authorTag.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.consecutive newline tokens.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.emptyComment.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.leadingAsterisk.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.less-than and greater-than characters.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.no space before @ is not a new tag.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.noLeadingAsterisk.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.noReturnType.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.oneParamTag.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.paramTag1.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.paramTagBracketedName1.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.paramTagBracketedName2.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.paramTagNameThenType1.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.paramTagNameThenType2.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.paramWithoutType.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.returnTag1.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.returnTag2.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.returnsTag1.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.templateTag.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.templateTag2.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.templateTag3.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.templateTag4.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.templateTag5.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.templateTag6.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.threeAsterisks.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.twoParamTag2.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.twoParamTagOnSameLine.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.typeTag.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.typedefTagWithChildrenTags.json
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, Housekeeping, For Uncommitted Bug

#48128 Handle nonmaster branches in user suite tests
  src/testRunner/externalCompileRunner.ts
  tests/baselines/reference/user/TypeScript-Node-Starter.log
  tests/baselines/reference/user/TypeScript-React-Native-Starter.log
  tests/baselines/reference/user/acorn.log
  tests/baselines/reference/user/adonis-framework.log
  tests/baselines/reference/user/assert.log
  tests/baselines/reference/user/async.log
  tests/baselines/reference/user/axios-src.log
  tests/baselines/reference/user/bluebird.log
  tests/baselines/reference/user/chrome-devtools-frontend.log
  tests/baselines/reference/user/clone.log
  tests/baselines/reference/user/create-react-app.log
  tests/baselines/reference/user/debug.log
  tests/baselines/reference/user/discord.js.log
  tests/baselines/reference/user/enhanced-resolve.log
  tests/baselines/reference/user/follow-redirects.log
  tests/baselines/reference/user/fp-ts.log
  tests/baselines/reference/user/graceful-fs.log
  tests/baselines/reference/user/lodash.log
  tests/baselines/reference/user/minimatch.log
  tests/baselines/reference/user/npm.log
  tests/baselines/reference/user/npmlog.log
  tests/baselines/reference/user/puppeteer.log
  tests/baselines/reference/user/soap.log
  tests/baselines/reference/user/ts-toolbelt.log
  tests/baselines/reference/user/uglify-js.log
  tests/baselines/reference/user/webpack.log
  tests/cases/docker/vscode/Dockerfile
  tests/cases/docker/vue-next/Dockerfile
  tests/cases/user/create-react-app/test.json
  tests/cases/user/discord.js/package.json
  tests/cases/user/firebase/index.ts
  tests/cases/user/formik/package.json
  tests/cases/user/grunt/test.json
  tests/cases/user/mqtt/package.json
  tests/cases/user/npm/test.json
  tests/cases/user/puppeteer/test.json
  tests/cases/user/soap/package.json
  tests/cases/user/ts-toolbelt/index.ts
  tests/cases/user/ts-toolbelt/package.json
  tests/cases/user/ts-toolbelt/tsconfig.json
  tests/cases/user/vue/package.json
  tests/cases/user/vuex/package.json
  tests/cases/user/webpack/test.json
Labels: Author: Team, For Uncommitted Bug

#48091 Preserve the homomorphism of inlined mapped types in declaration emit
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypeGenericInstantiationPreservesHomomorphism.js
  tests/baselines/reference/mappedTypeGenericInstantiationPreservesHomomorphism.symbols
  tests/baselines/reference/mappedTypeGenericInstantiationPreservesHomomorphism.types
  tests/baselines/reference/mappedTypeUnionConstraintInferences.js
  tests/cases/compiler/mappedTypeGenericInstantiationPreservesHomomorphism.ts
Labels: Author: Team, For Milestone Bug

#46812 Don't eagerly simplify reducible generic union index types
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/mappedTypeNotMistakenlyHomomorphic.errors.txt
  tests/baselines/reference/mappedTypeNotMistakenlyHomomorphic.js
  tests/baselines/reference/mappedTypeNotMistakenlyHomomorphic.symbols
  tests/baselines/reference/mappedTypeNotMistakenlyHomomorphic.types
  tests/cases/compiler/mappedTypeNotMistakenlyHomomorphic.ts
Labels: Author: Team, For Milestone Bug

#31455 Fix conditional type type parameter leak
  src/compiler/checker.ts
  tests/baselines/reference/conditionalDoesntLeakUninstantiatedTypeParameter.errors.txt
  tests/baselines/reference/conditionalDoesntLeakUninstantiatedTypeParameter.js
  tests/baselines/reference/conditionalDoesntLeakUninstantiatedTypeParameter.symbols
  tests/baselines/reference/conditionalDoesntLeakUninstantiatedTypeParameter.types
  tests/cases/compiler/conditionalDoesntLeakUninstantiatedTypeParameter.ts
Labels: Author: Team, For Milestone Bug

#39816 Make direct assignments to cjs exports considered literal contexts
  src/compiler/checker.ts
  src/compiler/utilities.ts
  tests/baselines/reference/assignmentToVoidZero1.js
  tests/baselines/reference/assignmentToVoidZero1.types
  tests/baselines/reference/assignmentToVoidZero2.js
  tests/baselines/reference/assignmentToVoidZero2.types
  tests/baselines/reference/commonJsUnusedLocals.types
  tests/baselines/reference/commonjsAccessExports.types
  tests/baselines/reference/declarationEmitOutFileBundlePaths.js
  tests/baselines/reference/jsDeclarationsCrossfileMerge.types
  tests/baselines/reference/jsDeclarationsDefault.js
  tests/baselines/reference/jsDeclarationsExportAssignedClassInstance3.js
  tests/baselines/reference/jsDeclarationsExportAssignedClassInstance3.types
  tests/baselines/reference/jsDeclarationsImportNamespacedType.js
  tests/baselines/reference/jsExportAssignmentNonMutableLocation.js
  tests/baselines/reference/jsExportAssignmentNonMutableLocation.symbols
  tests/baselines/reference/jsExportAssignmentNonMutableLocation.types
  tests/baselines/reference/jsExportMemberMergedWithModuleAugmentation3.types
  tests/baselines/reference/jsFileCompilationExternalPackageError.types
  tests/baselines/reference/moduleExportAlias5.types
  tests/baselines/reference/moduleExportAliasExports.types
  tests/baselines/reference/moduleExportAliasImported.types
  tests/baselines/reference/moduleExportAssignment.types
  tests/baselines/reference/moduleExportDuplicateAlias3.js
  tests/baselines/reference/moduleExportDuplicateAlias3.types
  tests/baselines/reference/moduleExportWithExportPropertyAssignment3.errors.txt
  tests/baselines/reference/moduleExportWithExportPropertyAssignment3.types
  tests/baselines/reference/moduleExportWithExportPropertyAssignment4.errors.txt
  tests/baselines/reference/moduleExportWithExportPropertyAssignment4.types
  tests/baselines/reference/moduleResolution_explicitNodeModulesImport.types
  tests/baselines/reference/nodeModulesAllowJsCjsFromJs(module=node12).types
  tests/baselines/reference/nodeModulesAllowJsCjsFromJs(module=nodenext).types
  tests/baselines/reference/typedefCrossModule2.types
  tests/cases/compiler/jsExportAssignmentNonMutableLocation.ts
  tests/cases/fourslash/inlayHintsShouldWork46.ts
Labels: Breaking Change, Author: Team, For Milestone Bug, For Backlog Bug

#48207 Move `hasOwn` from Object instance to Object constructor
  src/lib/es2022.object.d.ts
  tests/baselines/reference/esNextWeakRefs_IterableWeakMap.symbols
  tests/baselines/reference/inferenceOptionalPropertiesToIndexSignatures.symbols
  tests/baselines/reference/unionTypeInference.symbols
Labels: Author: Team, For Uncommitted Bug

#48214 Clean up a load of unused dependencies, broken jake script
  package-lock.json
  package.json
  scripts/bisect-test.ts
Labels: Author: Team, For Uncommitted Bug

#48110 Fix/dependent parameters obj methods
  src/compiler/checker.ts
  tests/baselines/reference/dependentDestructuredVariables.js
  tests/baselines/reference/dependentDestructuredVariables.symbols
  tests/baselines/reference/dependentDestructuredVariables.types
  tests/cases/conformance/controlFlow/dependentDestructuredVariables.ts
Labels: For Backlog Bug

#48111 Properly reduce intersections to never in identity relation
  src/compiler/checker.ts
  tests/baselines/reference/identityRelationNeverTypes.js
  tests/baselines/reference/identityRelationNeverTypes.symbols
  tests/baselines/reference/identityRelationNeverTypes.types
  tests/cases/compiler/identityRelationNeverTypes.ts
Labels: Author: Team, For Milestone Bug

#43845 Add assertion on invalid cache set
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug

#48169 Introduce set with custom equals and getHashCode
  src/compiler/core.ts
  src/server/session.ts
  src/testRunner/unittests/compilerCore.ts
Labels: Author: Team, For Uncommitted Bug

#48115 fix(48081): importing a value defined with require() gets flagged as an error
  src/compiler/binder.ts
  tests/baselines/reference/importNonExportedMember12.symbols
  tests/baselines/reference/importNonExportedMember12.types
  tests/cases/compiler/importNonExportedMember12.ts
Labels: For Backlog Bug

#47657 fix(47597): preProcessFile incorrectly identifies imports in comments after a template literal type
  src/services/preProcess.ts
  src/testRunner/unittests/services/preProcessFile.ts
Labels: For Milestone Bug

#47889 Exclude mapped types with 'as' clauses from certain checks
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypeConstraints2.errors.txt
  tests/baselines/reference/mappedTypeConstraints2.js
  tests/baselines/reference/mappedTypeConstraints2.symbols
  tests/baselines/reference/mappedTypeConstraints2.types
  tests/cases/conformance/types/mapped/mappedTypeConstraints2.ts
Labels: Author: Team, For Milestone Bug

#44158 Fix parser regression for bad related diagnostic on missing matching brackets
  src/compiler/diagnosticMessages.json
  src/compiler/parser.ts
  tests/baselines/reference/constructorWithIncompleteTypeAnnotation.errors.txt
  tests/baselines/reference/errorRecoveryWithDotFollowedByNamespaceKeyword.errors.txt
  tests/baselines/reference/jsonParserRecovery/JSX.errors.txt
  tests/baselines/reference/jsonParserRecovery/TypeScript_code.errors.txt
  tests/baselines/reference/jsonParserRecovery/trailing_identifier.errors.txt
  tests/baselines/reference/missingCloseBracketInArray.errors.txt
  tests/baselines/reference/missingCloseBracketInArray.js
  tests/baselines/reference/missingCloseBracketInArray.symbols
  tests/baselines/reference/missingCloseBracketInArray.types
  tests/baselines/reference/missingCloseParenStatements.errors.txt
  tests/baselines/reference/missingCloseParenStatements.js
  tests/baselines/reference/missingCloseParenStatements.symbols
  tests/baselines/reference/missingCloseParenStatements.types
  tests/baselines/reference/nestedClassDeclaration.errors.txt
  tests/baselines/reference/objectLiteralWithSemicolons4.errors.txt
  tests/baselines/reference/objectSpreadNegativeParse.errors.txt
  tests/baselines/reference/parseErrorIncorrectReturnToken.errors.txt
  tests/baselines/reference/parserErrorRecoveryIfStatement2.errors.txt
  tests/baselines/reference/parserErrorRecoveryIfStatement3.errors.txt
  tests/baselines/reference/parserFuzz1.errors.txt
  tests/baselines/reference/tsbuild/noEmitOnError/initial-build/syntax-errors-with-incremental.js
  tests/baselines/reference/tsbuild/noEmitOnError/initial-build/syntax-errors.js
  tests/baselines/reference/tsbuild/watchMode/noEmitOnError/does-not-emit-any-files-on-error-with-incremental.js
  tests/baselines/reference/tsbuild/watchMode/noEmitOnError/does-not-emit-any-files-on-error.js
  tests/baselines/reference/tsc/incremental/initial-build/with-noEmitOnError-syntax-errors.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependencies/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependencies/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependenciesAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependenciesAndD/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/default/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/default/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/defaultAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/defaultAndD/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/assumeChangesOnlyAffectDirectDependencies/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/assumeChangesOnlyAffectDirectDependencies/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/assumeChangesOnlyAffectDirectDependenciesAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/assumeChangesOnlyAffectDirectDependenciesAndD/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/default/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/default/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/defaultAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/defaultAndD/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/isolatedModules/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/isolatedModules/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/isolatedModulesAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/incremental/isolatedModulesAndD/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModules/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModules/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModulesAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModulesAndD/with-noEmitOnError.js
  tests/baselines/reference/tsserver/partialSemanticServer/syntactic-diagnostics-are-returned-with-no-error.js
  tests/baselines/reference/typeAssertions.errors.txt
  tests/cases/compiler/missingCloseBracketInArray.ts
  tests/cases/compiler/missingCloseParenStatements.ts
  tests/cases/conformance/parser/ecmascript5/ErrorRecovery/ArrayLiteralExpressions/parserErrorRecoveryArrayLiteralExpression3.ts
  tests/cases/fourslash/smartIndentMissingBracketsDoKeyword.ts
  tests/cases/fourslash/smartIndentMissingBracketsIfKeyword.ts
  tests/cases/fourslash/smartIndentMissingBracketsWhileKeyword.ts
  tests/cases/fourslash/smartIndentMissingBracketsWithKeyword.ts
Labels: Author: Team, For Uncommitted Bug

#48273 Exclude mapped types with optionality modifiers and 'as' clauses from constraint logic
  src/compiler/checker.ts
  tests/baselines/reference/correlatedUnions.js
  tests/baselines/reference/correlatedUnions.symbols
  tests/baselines/reference/correlatedUnions.types
  tests/cases/compiler/correlatedUnions.ts
Labels: Author: Team, For Milestone Bug

#47306 Consistently avoid pulling on the source return type when the target return type is any
  src/compiler/checker.ts
  tests/baselines/reference/conditionalTypeBasedContextualTypeReturnTypeWidening.js
  tests/baselines/reference/conditionalTypeBasedContextualTypeReturnTypeWidening.symbols
  tests/baselines/reference/conditionalTypeBasedContextualTypeReturnTypeWidening.types
  tests/cases/compiler/conditionalTypeBasedContextualTypeReturnTypeWidening.ts
Labels: Author: Team, For Uncommitted Bug

#48263 Handle JS synthetic rest args in contextual parameter assignment
  src/compiler/checker.ts
  tests/baselines/reference/noParameterReassignmentIIFEAnnotated.errors.txt
  tests/baselines/reference/noParameterReassignmentIIFEAnnotated.symbols
  tests/baselines/reference/noParameterReassignmentIIFEAnnotated.types
  tests/baselines/reference/noParameterReassignmentJSIIFE.symbols
  tests/baselines/reference/noParameterReassignmentJSIIFE.types
  tests/cases/compiler/noParameterReassignmentIIFEAnnotated.ts
  tests/cases/compiler/noParameterReassignmentJSIIFE.ts
Labels: Author: Team, For Uncommitted Bug

#48283 fix(48277): Add parameter type inlay hints after ? operator
  src/services/inlayHints.ts
  tests/cases/fourslash/inlayHintsShouldWork66.ts
Labels: For Backlog Bug

#48270 feat(48231): Cannot declare unique symbol type in jsdoc in js file
  src/compiler/checker.ts
  tests/baselines/reference/uniqueSymbolsDeclarationsInJs.js
  tests/baselines/reference/uniqueSymbolsDeclarationsInJs.symbols
  tests/baselines/reference/uniqueSymbolsDeclarationsInJs.types
  tests/cases/conformance/types/uniqueSymbol/uniqueSymbolsDeclarationsInJs.ts
Labels: For Backlog Bug

#48299 fix(48191): Duplicates comments on "Add definite assignment assertion to property"
  src/services/codefixes/fixStrictClassInitialization.ts
  tests/cases/fourslash/codeFixClassPropertyInitialization17.ts
  tests/cases/fourslash/codeFixClassPropertyInitialization18.ts
  tests/cases/fourslash/codeFixClassPropertyInitialization19.ts
  tests/cases/fourslash/codeFixClassPropertyInitialization20.ts
Labels: For Backlog Bug

#42915 Add isolatedModules error for ambiguous imports referenced in decorator metadata
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/services/codefixes/fixUnreferenceableDecoratorMetadata.ts
  src/services/refactors/convertImport.ts
  src/services/tsconfig.json
  tests/baselines/reference/emitDecoratorMetadata_isolatedModules(module=commonjs).js
  tests/baselines/reference/emitDecoratorMetadata_isolatedModules(module=commonjs).symbols
  tests/baselines/reference/emitDecoratorMetadata_isolatedModules(module=commonjs).types
  tests/baselines/reference/emitDecoratorMetadata_isolatedModules(module=esnext).errors.txt
  tests/baselines/reference/emitDecoratorMetadata_isolatedModules(module=esnext).js
  tests/baselines/reference/emitDecoratorMetadata_isolatedModules(module=esnext).symbols
  tests/baselines/reference/emitDecoratorMetadata_isolatedModules(module=esnext).types
  tests/baselines/reference/emitDecoratorMetadata_isolatedModules.errors.txt
  tests/baselines/reference/emitDecoratorMetadata_isolatedModules.js
  tests/baselines/reference/emitDecoratorMetadata_isolatedModules.symbols
  tests/baselines/reference/emitDecoratorMetadata_isolatedModules.types
  tests/cases/compiler/emitDecoratorMetadata_isolatedModules.ts
  tests/cases/fourslash/codefixUnreferenceableDecoratorMetadata1.ts
  tests/cases/fourslash/codefixUnreferenceableDecoratorMetadata2.ts
  tests/cases/fourslash/codefixUnreferenceableDecoratorMetadata3.ts
Labels: Author: Team, For Milestone Bug

#37902 Infer extracted local variable name from property name
  src/services/refactors/extractSymbol.ts
  src/testRunner/unittests/services/extract/constants.ts
  tests/baselines/reference/extractConstant/extractConstant_PropertyName.js
  tests/baselines/reference/extractConstant/extractConstant_PropertyName.ts
  tests/baselines/reference/extractConstant/extractConstant_PropertyName_ExistingName.js
  tests/baselines/reference/extractConstant/extractConstant_PropertyName_ExistingName.ts
  tests/baselines/reference/extractConstant/extractConstant_PropertyName_Keyword.js
  tests/baselines/reference/extractConstant/extractConstant_PropertyName_Keyword.ts
  tests/baselines/reference/extractConstant/extractConstant_PropertyName_PrivateIdentifierKeyword.js
  tests/baselines/reference/extractConstant/extractConstant_PropertyName_PrivateIdentifierKeyword.ts
Labels: For Backlog Bug

#48304 fix(48291): TS1193 in JS File
  src/compiler/checker.ts
  tests/baselines/reference/plainJSGrammarErrors2.js
  tests/baselines/reference/plainJSGrammarErrors2.symbols
  tests/baselines/reference/plainJSGrammarErrors2.types
  tests/cases/conformance/salsa/plainJSGrammarErrors2.ts
Labels: For Milestone Bug

#48282 Add server tracepoints
  src/compiler/commandLineParser.ts
  src/server/editorServices.ts
  src/server/project.ts
  src/server/session.ts
  src/services/services.ts
Labels: Author: Team, For Uncommitted Bug

#48329 Make AutoImportProvider look in ATA cache
  src/harness/harnessLanguageService.ts
  src/server/project.ts
  src/services/exportInfoMap.ts
  tests/cases/fourslash/importFixesGlobalTypingsCache.ts
  tests/cases/fourslash/server/autoImportProvider_globalTypingsCache.ts
Labels: Author: Team, For Milestone Bug

#48072 fix(48053) Description of tsBuildInfoFile is misleading in generated tsconfig.json
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/tsConfig/Default initialized TSConfig/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with advanced options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with boolean value compiler options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with enum value compiler options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with files options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with incorrect compiler option value/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with incorrect compiler option/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with list compiler options with enum value/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with list compiler options/tsconfig.json
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/declarationDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/when-outDir-and-declarationDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/when-outDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/with-outFile.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/without-outDir-or-outFile-is-specified-with-declaration-enabled.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/without-outDir-or-outFile-is-specified.js
Labels: For Backlog Bug

#48259 fix(48258): export default anonymous function works with prefixText and suffixText when disabled
  src/services/findAllReferences.ts
  src/testRunner/unittests/tsserver/rename.ts
Labels: For Backlog Bug

#48044 fix(48034): Get a literal string of type intersection in a template literal type
  src/compiler/checker.ts
  tests/baselines/reference/templateLiteralIntersection.js
  tests/baselines/reference/templateLiteralIntersection.symbols
  tests/baselines/reference/templateLiteralIntersection.types
  tests/cases/compiler/templateLiteralIntersection.ts
Labels: For Backlog Bug

#48262 fix(48218): Split Intl.DisplayNames options
  src/lib/es2020.intl.d.ts
Labels: For Backlog Bug

#44969 align ClassStaticBlockDeclaration with IIFE in CFA
  src/compiler/binder.ts
  src/compiler/checker.ts
  tests/baselines/reference/classStaticBlock28.js
  tests/baselines/reference/classStaticBlock28.symbols
  tests/baselines/reference/classStaticBlock28.types
  tests/baselines/reference/classStaticBlockUseBeforeDef3.errors.txt
  tests/baselines/reference/classStaticBlockUseBeforeDef3.symbols
  tests/baselines/reference/classStaticBlockUseBeforeDef3.types
  tests/cases/conformance/classes/classStaticBlock/classStaticBlock28.ts
  tests/cases/conformance/classes/classStaticBlock/classStaticBlockUseBeforeDef3.ts
Labels: For Milestone Bug

#48389 Fix document registry cache key calculation for `paths` compiler option
  src/services/documentRegistry.ts
  src/testRunner/unittests/tsserver/languageService.ts
Labels: Author: Team, For Milestone Bug

#36747 Merge diagnosticsProducing and nonDiagnosticsProducing checkers into a single checker supporting lazy diagnostics
  src/compiler/checker.ts
  src/compiler/program.ts
  src/compiler/types.ts
  src/harness/harnessIO.ts
  src/harness/typeWriter.ts
  src/services/codefixes/addMissingAsync.ts
  src/services/codefixes/addMissingAwait.ts
  src/services/codefixes/convertFunctionToEs6Class.ts
  src/testRunner/unittests/programApi.ts
  tests/baselines/reference/findAllRefs_importType_js.1.baseline.jsonc
  tests/cases/fourslash/convertFunctionToEs6Class1.ts
  tests/cases/fourslash/convertFunctionToEs6Class2.ts
  tests/cases/fourslash/convertFunctionToEs6Class3.ts
  tests/cases/fourslash/convertFunctionToEs6Class_asyncMethods.ts
Labels: Author: Team, For Uncommitted Bug

#48366 Make the unconstrained type parameter and {} assignability rule not apply under strictNullChecks
  src/compiler/checker.ts
  src/compiler/core.ts
  src/compiler/diagnosticMessages.json
  src/harness/harnessGlobals.ts
  src/services/shims.ts
  tests/baselines/reference/isomorphicMappedTypeInference.js
  tests/baselines/reference/isomorphicMappedTypeInference.symbols
  tests/baselines/reference/isomorphicMappedTypeInference.types
  tests/baselines/reference/keyofAndIndexedAccess.errors.txt
  tests/baselines/reference/mappedTypesAndObjects.errors.txt
  tests/baselines/reference/tsxNotUsingApparentTypeOfSFC.errors.txt
  tests/baselines/reference/unknownType1.errors.txt
  tests/cases/conformance/types/mapped/isomorphicMappedTypeInference.ts
Labels: Author: Team, For Milestone Bug

#48400 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220324095059360 to main
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#48403 Fix test build post-LKG
  src/testRunner/unittests/tsserver/projectReferencesSourcemap.ts
Labels: Author: Team, For Uncommitted Bug

#47104 fix(47081): Autocomplete breaks in overloaded generic function
  src/services/completions.ts
  tests/cases/fourslash/completionListInObjectLiteral7.ts
Labels: For Backlog Bug

#48426 Revert "Fix contextual discrimination for omitted members (#43937)"
  src/compiler/checker.ts
  tests/baselines/reference/discriminantPropertyInference.js
  tests/baselines/reference/discriminantPropertyInference.symbols
  tests/baselines/reference/discriminantPropertyInference.types
  tests/baselines/reference/tsxDiscriminantPropertyInference.js
  tests/baselines/reference/tsxDiscriminantPropertyInference.symbols
  tests/baselines/reference/tsxDiscriminantPropertyInference.types
  tests/cases/compiler/discriminantPropertyInference.ts
  tests/cases/compiler/tsxDiscriminantPropertyInference.tsx
Labels: Author: Team, For Uncommitted Bug

#48050 fix(48031): No circularity error for self referential get accessor annotations
  src/compiler/checker.ts
  tests/baselines/reference/circularGetAccessor(noimplicitany=false).errors.txt
  tests/baselines/reference/circularGetAccessor(noimplicitany=false).js
  tests/baselines/reference/circularGetAccessor(noimplicitany=false).symbols
  tests/baselines/reference/circularGetAccessor(noimplicitany=false).types
  tests/baselines/reference/circularGetAccessor(noimplicitany=true).errors.txt
  tests/baselines/reference/circularGetAccessor(noimplicitany=true).js
  tests/baselines/reference/circularGetAccessor(noimplicitany=true).symbols
  tests/baselines/reference/circularGetAccessor(noimplicitany=true).types
  tests/cases/compiler/circularGetAccessor.ts
Labels: For Backlog Bug

#48450 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220327094908759 to main
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#48337 fix(48166): Checking module.exports should not yield a This condition will always return true since this function is always defined error
  src/compiler/checker.ts
  tests/baselines/reference/truthinessCallExpressionCoercion4.symbols
  tests/baselines/reference/truthinessCallExpressionCoercion4.types
  tests/cases/compiler/truthinessCallExpressionCoercion4.ts
Labels: For Uncommitted Bug

#48459 Revise accessor resolution logic and error reporting
  src/compiler/checker.ts
  src/compiler/utilitiesPublic.ts
  tests/baselines/reference/circularAccessorAnnotations.errors.txt
  tests/baselines/reference/circularAccessorAnnotations.js
  tests/baselines/reference/circularAccessorAnnotations.symbols
  tests/baselines/reference/circularAccessorAnnotations.types
  tests/baselines/reference/circularIndexedAccessErrors.errors.txt
  tests/baselines/reference/limitDeepInstantiations.errors.txt
  tests/cases/compiler/circularAccessorAnnotations.ts
Labels: Author: Team, For Milestone Bug

#48464 Prevent looking up symbol for as const from triggering an error
  src/compiler/checker.ts
  tests/cases/fourslash/asConstRefsNoErrors1.ts
  tests/cases/fourslash/asConstRefsNoErrors2.ts
  tests/cases/fourslash/asConstRefsNoErrors3.ts
Labels: Author: Team, For Uncommitted Bug

#48463 Fix newline inserted in empty block at end of formatting range
  src/services/formatting/formatting.ts
  src/services/utilities.ts
  tests/cases/fourslash/formatOnTypeOpenCurlyWithBraceCompletion.ts
Labels: Author: Team, For Uncommitted Bug

#48449 fix(48445): import { type X } not flagged in JavaScript
  src/compiler/program.ts
  tests/baselines/reference/exportSpecifiers_js.errors.txt
  tests/baselines/reference/exportSpecifiers_js.symbols
  tests/baselines/reference/exportSpecifiers_js.types
  tests/baselines/reference/importSpecifiers_js.errors.txt
  tests/baselines/reference/importSpecifiers_js.symbols
  tests/baselines/reference/importSpecifiers_js.types
  tests/cases/conformance/externalModules/typeOnly/exportSpecifiers_js.ts
  tests/cases/conformance/externalModules/typeOnly/importSpecifiers_js.ts
Labels: For Backlog Bug

#48410 Fix string literal completions when a partially-typed string fixes inference to a type parameter
  src/compiler/checker.ts
  src/compiler/types.ts
  src/harness/fourslashImpl.ts
  src/services/stringCompletions.ts
  tests/cases/fourslash/completionsLiteralOverload.ts
Labels: Author: Team, For Milestone Bug

#48168 Enable method signature completion for object literals
  src/compiler/types.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/server/protocol.ts
  src/services/completions.ts
  src/services/utilities.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/completionsCommentsClass.baseline
  tests/baselines/reference/completionsCommentsClassMembers.baseline
  tests/baselines/reference/completionsCommentsCommentParsing.baseline
  tests/baselines/reference/completionsCommentsFunctionDeclaration.baseline
  tests/baselines/reference/completionsCommentsFunctionExpression.baseline
  tests/baselines/reference/completionsStringMethods.baseline
  tests/cases/fourslash/completionAfterGlobalThis.ts
  tests/cases/fourslash/completionListAfterRegularExpressionLiteral01.ts
  tests/cases/fourslash/completionListAfterRegularExpressionLiteral1.ts
  tests/cases/fourslash/completionListAfterStringLiteral1.ts
  tests/cases/fourslash/completionsObjectLiteralMethod1.ts
  tests/cases/fourslash/completionsObjectLiteralMethod2.ts
  tests/cases/fourslash/completionsObjectLiteralMethod3.ts
  tests/cases/fourslash/completionsWithDeprecatedTag1.ts
  tests/cases/fourslash/completionsWithDeprecatedTag10.ts
  tests/cases/fourslash/completionsWithDeprecatedTag2.ts
  tests/cases/fourslash/completionsWithDeprecatedTag4.ts
  tests/cases/fourslash/completionsWithDeprecatedTag5.ts
  tests/cases/fourslash/completionsWithDeprecatedTag6.ts
  tests/cases/fourslash/completionsWithDeprecatedTag7.ts
  tests/cases/fourslash/completionsWithDeprecatedTag8.ts
  tests/cases/fourslash/completionsWithDeprecatedTag9.ts
  tests/cases/fourslash/fourslash.ts
Labels: Author: Team, For Milestone Bug

#48429 Add label details to completion entry
  src/compiler/types.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/server/protocol.ts
  src/server/session.ts
  src/services/completions.ts
  src/services/types.ts
  src/testRunner/unittests/tsserver/completions.ts
  src/testRunner/unittests/tsserver/partialSemanticServer.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/completionsObjectLiteralMethod1.ts
  tests/cases/fourslash/completionsObjectLiteralMethod2.ts
  tests/cases/fourslash/completionsObjectLiteralMethod3.ts
  tests/cases/fourslash/fourslash.ts
Labels: Author: Team, For Uncommitted Bug

#47212 feat(27615): fixAddMissingMember should work for type literal
  src/services/codefixes/fixAddMissingMember.ts
  src/services/codefixes/fixClassDoesntImplementInheritedAbstractMember.ts
  src/services/codefixes/fixClassIncorrectlyImplementsInterface.ts
  src/services/codefixes/generateAccessors.ts
  src/services/codefixes/helpers.ts
  src/services/textChanges.ts
  tests/cases/fourslash/codeFixAddMissingMember22.ts
  tests/cases/fourslash/codeFixAddMissingMember23.ts
  tests/cases/fourslash/codeFixAddMissingMember24.ts
  tests/cases/fourslash/codeFixAddMissingMember25.ts
  tests/cases/fourslash/codeFixAddMissingMember26.ts
  tests/cases/fourslash/codeFixAddMissingMember_all.ts
Labels: For Backlog Bug

#48490 Ensure that we copy empty NodeArrays during transform
  src/compiler/checker.ts
  tests/cases/fourslash/completionsOverridingMethodCrash1.ts
Labels: Author: Team, For Milestone Bug

#47748 fix(47733): JSDoc comment template incorrectly returned for element that already has JSDoc comment
  src/services/jsDoc.ts
  tests/cases/fourslash/docCommentTemplateWithExistingJSDoc.ts
Labels: For Backlog Bug

#48380 No contextual typing from return types for boolean literals
  src/compiler/checker.ts
  tests/baselines/reference/contextuallyTypedBooleanLiterals.js
  tests/baselines/reference/contextuallyTypedBooleanLiterals.symbols
  tests/baselines/reference/contextuallyTypedBooleanLiterals.types
  tests/baselines/reference/inferFromGenericFunctionReturnTypes3.errors.txt
  tests/baselines/reference/inferFromGenericFunctionReturnTypes3.types
  tests/cases/compiler/contextuallyTypedBooleanLiterals.ts
Labels: Author: Team, For Milestone Bug

#48411 CFA for dependent parameters typed by generic constraints
  src/compiler/checker.ts
  tests/baselines/reference/dependentDestructuredVariables.js
  tests/baselines/reference/dependentDestructuredVariables.symbols
  tests/baselines/reference/dependentDestructuredVariables.types
  tests/cases/conformance/controlFlow/dependentDestructuredVariables.ts
Labels: Author: Team, For Milestone Bug

#48481 fix(48405): Crash on 'extract type' for deep recursive mapped type
  src/compiler/emitter.ts
  tests/cases/fourslash/refactorExtractType76.ts
  tests/cases/fourslash/refactorExtractType77.ts
Labels: For Backlog Bug

#48499 Correct node used for isDefinition calculation
  src/services/findAllReferences.ts
  tests/baselines/reference/findAllRefsExportEquals.baseline.jsonc
  tests/baselines/reference/findAllRefs_importType_exportEquals.baseline.jsonc
  tests/baselines/reference/referencesForDeclarationKeywords.baseline.jsonc
  tests/baselines/reference/referencesForExpressionKeywords.baseline.jsonc
  tests/baselines/reference/referencesForModifiers.baseline.jsonc
  tests/baselines/reference/referencesForStatementKeywords.baseline.jsonc
  tests/baselines/reference/referencesForTypeKeywords.baseline.jsonc
Labels: Author: Team, For Uncommitted Bug
