Repository microsoft/TypeScript, pull requests merged in 2022-04, with the labels that each got.

#48502 Reserve a core in runtests-parallel on non-CI machines
  scripts/build/options.js
Labels: Author: Team, For Uncommitted Bug

#48505 Fix API under exactOptionalPropertyTypes
  src/compiler/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Milestone Bug

#48512 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220401124110313 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#48506 Respect @BaselineFile in fourslash tests
  src/harness/fourslashImpl.ts
  tests/baselines/reference/quickInfoDisplayPartsVar.shims-pp.baseline
  tests/baselines/reference/quickInfoDisplayPartsVar.shims.baseline
  tests/cases/fourslash/shims-pp/quickInfoDisplayPartsVarShims.ts
Labels: Author: Team, For Uncommitted Bug

#48526 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220402123449549 to main
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#48534 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220403104626098 to main
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#48521 fix(48520): Add missing properties quick fix on rest parameter incorrectly adds Array methods
  src/services/codefixes/fixAddMissingMember.ts
  tests/cases/fourslash/codeFixAddMissingProperties20.ts
Labels: For Uncommitted Bug

#48539 Fix crash when circular reference in variance annotations
  src/compiler/checker.ts
  tests/baselines/reference/varianceAnnotationsWithCircularlyReferencesError.errors.txt
  tests/baselines/reference/varianceAnnotationsWithCircularlyReferencesError.js
  tests/baselines/reference/varianceAnnotationsWithCircularlyReferencesError.symbols
  tests/baselines/reference/varianceAnnotationsWithCircularlyReferencesError.types
  tests/cases/conformance/types/typeParameters/typeParameterLists/varianceAnnotationsWithCircularlyReferencesError.ts
Labels: For Milestone Bug

#48548 fix(48541): Refactoring to "extract to inner/local function" crashes in concise arrow function
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/services/refactors/extractSymbol.ts
  tests/baselines/reference/extractConstant/extractConstant_ArrowFunction_Expression.js
  tests/baselines/reference/extractConstant/extractConstant_ArrowFunction_Expression.ts
  tests/cases/fourslash/extract-method-two-type-literals.ts
  tests/cases/fourslash/extract-method44.ts
  tests/cases/fourslash/fourslash.ts
Labels: For Milestone Bug

#48549 fix(48542): Crash in signature help in declaration list contextually typed by union
  src/services/signatureHelp.ts
  tests/baselines/reference/signatureHelp_unionType.baseline
  tests/cases/fourslash/signatureHelp_unionType.ts
Labels: For Milestone Bug

#48555 Remove nightly-only flagging for nodenext features
  src/compiler/program.ts
Labels: Author: Team, For Uncommitted Bug

#48425 fixed code duplication
  src/compiler/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Backlog Bug

#48407 fix(48406): Document @link failed to resolve in type annotation
  src/compiler/utilities.ts
  tests/baselines/reference/quickInfoLink9.baseline
  tests/cases/fourslash/quickInfoLink9.ts
Labels: For Uncommitted Bug

#48420 fix(48418): Refactoring: "Add missing properties" fails for interfaces containing a function property whose definition includes a generic argument that is an empty tuple
  src/services/codefixes/helpers.ts
  tests/cases/fourslash/codeFixAddMissingProperties19.ts
Labels: For Backlog Bug

#48554 Properly check singleton labeled tuple before unwrapping
  src/compiler/checker.ts
  tests/baselines/reference/singletonLabeledTuple.js
  tests/baselines/reference/singletonLabeledTuple.symbols
  tests/baselines/reference/singletonLabeledTuple.types
  tests/cases/compiler/singletonLabeledTuple.ts
Labels: Author: Team, For Milestone Bug

#48564 Remove non-baselining fourslash FAR validation
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  tests/baselines/reference/cancellationWhenfindingAllRefsOnDefinition.1.baseline.jsonc
  tests/baselines/reference/cancellationWhenfindingAllRefsOnDefinition.3.baseline.jsonc
  tests/baselines/reference/findAllRefsPrimitive.baseline.jsonc
  tests/baselines/reference/findReferencesAfterEdit.1.baseline.jsonc
  tests/baselines/reference/findReferencesAfterEdit.2.baseline.jsonc
  tests/baselines/reference/findReferencesJSXTagName3.baseline.jsonc
  tests/baselines/reference/jsDocServices.baseline.jsonc
  tests/baselines/reference/jsdocTypedefTagServices.baseline.jsonc
  tests/baselines/reference/localGetReferences.baseline.jsonc
  tests/baselines/reference/remoteGetReferences.baseline.jsonc
  tests/cases/fourslash/cancellationWhenfindingAllRefsOnDefinition.ts
  tests/cases/fourslash/findAllRefsPrimitive.ts
  tests/cases/fourslash/findReferencesAfterEdit.ts
  tests/cases/fourslash/findReferencesJSXTagName3.ts
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/jsDocServices.ts
  tests/cases/fourslash/jsdocTypedefTagServices.ts
  tests/cases/fourslash/localGetReferences.ts
  tests/cases/fourslash/remoteGetReferences.ts
Labels: Author: Team, For Uncommitted Bug

#48493 Allow arrow function parameter parsing to bail out during speculation, redo
  src/compiler/parser.ts
  tests/baselines/reference/arrowFunctionParsingDoesNotConfuseParenthesizedObjectForArrowHead.js
  tests/baselines/reference/arrowFunctionParsingDoesNotConfuseParenthesizedObjectForArrowHead.symbols
  tests/baselines/reference/arrowFunctionParsingDoesNotConfuseParenthesizedObjectForArrowHead.types
  tests/baselines/reference/arrowFunctionParsingGenericInObject.js
  tests/baselines/reference/arrowFunctionParsingGenericInObject.symbols
  tests/baselines/reference/arrowFunctionParsingGenericInObject.types
  tests/cases/compiler/arrowFunctionParsingDoesNotConfuseParenthesizedObjectForArrowHead.ts
  tests/cases/compiler/arrowFunctionParsingGenericInObject.ts
Labels: Author: Team, For Milestone Bug

#48440 fix(48109) - 'Convert to arrow function' refactoring adds extra indent
  src/services/formatting/smartIndenter.ts
  tests/cases/fourslash/refactorConvertArrowFunctionOrFunctionExpression_ToAnon_FnArgument.ts
  tests/cases/fourslash/refactorConvertArrowFunctionOrFunctionExpression_ToArrow_FnArgIndent.ts
  tests/cases/fourslash/refactorConvertArrowFunctionOrFunctionExpression_ToArrow_FunctionFnArgIndent.ts
Labels: For Backlog Bug

#48434 narrow type for generic variables inside TypeQuery
  src/compiler/checker.ts
  tests/baselines/reference/narrowingOfQualifiedNames.errors.txt
  tests/baselines/reference/narrowingOfQualifiedNames.js
  tests/baselines/reference/narrowingOfQualifiedNames.symbols
  tests/baselines/reference/narrowingOfQualifiedNames.types
  tests/cases/compiler/narrowingOfQualifiedNames.ts
Labels: For Backlog Bug

#48330 [Feature] - Automatically create sort groups based on newlines
  src/services/organizeImports.ts
  src/testRunner/unittests/services/organizeImports.ts
  tests/baselines/reference/organizeImports/SortComments.ts
  tests/baselines/reference/organizeImports/TopLevelAndAmbientModule.ts
  tests/cases/fourslash/organizeImports6.ts
  tests/cases/fourslash/organizeImportsGroup_CommentInNewline.ts
  tests/cases/fourslash/organizeImportsGroup_MultiNewlines.ts
  tests/cases/fourslash/organizeImportsGroup_MultilineCommentInNewline.ts
  tests/cases/fourslash/organizeImportsGroup_Newline.ts
Labels: For Backlog Bug

#48112 Add 'extends' clause to 'infer' type
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/emitter.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/factory/parenthesizerRules.ts
  src/compiler/parser.ts
  src/compiler/types.ts
  src/services/textChanges.ts
  tests/baselines/reference/JSDocParsing/TypeExpressions.parsesCorrectly.nonNullableType.json
  tests/baselines/reference/JSDocParsing/TypeExpressions.parsesCorrectly.nonNullableType2.json
  tests/baselines/reference/JSDocParsing/TypeExpressions.parsesCorrectly.nullableType.json
  tests/baselines/reference/JSDocParsing/TypeExpressions.parsesCorrectly.nullableType2.json
  tests/baselines/reference/ambientConstLiterals.types
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/bitwiseNotOperatorWithEnumType.types
  tests/baselines/reference/constEnums.types
  tests/baselines/reference/declFileEnums.types
  tests/baselines/reference/declarationEmitSpreadStringlyKeyedEnum.js
  tests/baselines/reference/declarationEmitSpreadStringlyKeyedEnum.types
  tests/baselines/reference/decrementOperatorWithEnumType.types
  tests/baselines/reference/decrementOperatorWithEnumTypeInvalidOperations.types
  tests/baselines/reference/deleteOperatorWithEnumType.types
  tests/baselines/reference/doubleUnderscoreEnumEmit.types
  tests/baselines/reference/enumErrors.types
  tests/baselines/reference/enumIdentifierLiterals.types
  tests/baselines/reference/enumWithNegativeInfinityProperty.types
  tests/baselines/reference/enumWithQuotedElementName1.types
  tests/baselines/reference/enumWithQuotedElementName2.types
  tests/baselines/reference/enumWithUnicodeEscape1.types
  tests/baselines/reference/incrementOperatorWithEnumType.types
  tests/baselines/reference/incrementOperatorWithEnumTypeInvalidOperations.types
  tests/baselines/reference/inferTypes1.errors.txt
  tests/baselines/reference/inferTypes1.js
  tests/baselines/reference/inferTypes1.symbols
  tests/baselines/reference/inferTypes1.types
  tests/baselines/reference/inferTypesWithExtends1.js
  tests/baselines/reference/inferTypesWithExtends1.symbols
  tests/baselines/reference/inferTypesWithExtends1.types
  tests/baselines/reference/inferTypesWithExtends2.errors.txt
  tests/baselines/reference/inferTypesWithExtends2.js
  tests/baselines/reference/inferTypesWithExtends2.symbols
  tests/baselines/reference/inferTypesWithExtends2.types
  tests/baselines/reference/infiniteConstraints.types
  tests/baselines/reference/keyofAndIndexedAccess2.types
  tests/baselines/reference/literalsInComputedProperties1.types
  tests/baselines/reference/negateOperatorWithEnumType.types
  tests/baselines/reference/parserEnum5.types
  tests/baselines/reference/parserEnum7.types
  tests/baselines/reference/plusOperatorWithEnumType.types
  tests/baselines/reference/typeofOperatorWithEnumType.types
  tests/baselines/reference/voidOperatorWithEnumType.types
  tests/cases/conformance/types/conditional/inferTypes1.ts
  tests/cases/conformance/types/conditional/inferTypesWithExtends1.ts
  tests/cases/conformance/types/conditional/inferTypesWithExtends2.ts
  tests/cases/fourslash/refactorExtractType48.ts
Labels: Author: Team, For Uncommitted Bug

#48538 Improve inference for context sensitive functions in object and array literal arguments
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/contextualTypingOfOptionalMembers.types
  tests/baselines/reference/intraExpressionInferences.errors.txt
  tests/baselines/reference/intraExpressionInferences.js
  tests/baselines/reference/intraExpressionInferences.symbols
  tests/baselines/reference/intraExpressionInferences.types
  tests/cases/conformance/types/typeRelationships/typeInference/intraExpressionInferences.ts
Labels: Author: Team, For Milestone Bug, For Backlog Bug

#48574 Run API tests with 'strict' and 'exactOptionalProperties'.
  src/testRunner/unittests/publicApi.ts
Labels: Author: Team, For Uncommitted Bug

#47254 feat(46907): Add `Intl.ListFormat` type declarations
  src/lib/es2021.intl.d.ts
Labels: For Backlog Bug

#48467 Add more options to `DateTimeFormatOptions.timeZoneName`
  src/lib/es5.d.ts
  tests/baselines/reference/es2022IntlAPIs.js
  tests/baselines/reference/es2022IntlAPIs.symbols
  tests/baselines/reference/es2022IntlAPIs.types
  tests/cases/conformance/es2022/es2022IntlAPIs.ts
Labels: For Backlog Bug

#48577 Update DOM for 4.7 beta
  src/lib/dom.generated.d.ts
  src/lib/dom.iterable.generated.d.ts
  src/lib/webworker.generated.d.ts
  src/lib/webworker.iterable.generated.d.ts
  tests/baselines/reference/baseCheck.errors.txt
  tests/baselines/reference/extendArray.errors.txt
  tests/baselines/reference/globalThisBlockscopedProperties.types
  tests/baselines/reference/importMeta(module=commonjs,target=es5).types
  tests/baselines/reference/importMeta(module=commonjs,target=esnext).types
  tests/baselines/reference/importMeta(module=es2020,target=es5).types
  tests/baselines/reference/importMeta(module=es2020,target=esnext).types
  tests/baselines/reference/importMeta(module=esnext,target=es5).types
  tests/baselines/reference/importMeta(module=esnext,target=esnext).types
  tests/baselines/reference/importMeta(module=system,target=es5).types
  tests/baselines/reference/importMeta(module=system,target=esnext).types
  tests/baselines/reference/intersectionsOfLargeUnions2.errors.txt
  tests/baselines/reference/jsxFactoryIdentifierWithAbsentParameter.errors.txt
  tests/baselines/reference/jsxFactoryQualifiedNameResolutionError.errors.txt
  tests/baselines/reference/mappedTypeRecursiveInference.types
Labels: Author: Team, For Uncommitted Bug

#48545 fix(48540): Extract to typedef from (invalid) type with comments in JS file causes assertion failure
  src/services/refactors/extractType.ts
  tests/cases/fourslash/refactorExtractType_js_TypeLiteral_CommentAfterProperty.ts
  tests/cases/fourslash/refactorExtractType_js_TypeLiteral_CommentBeforeProperty.ts
  tests/cases/fourslash/refactorExtractType_js_Union_CommentAfterMember.ts
  tests/cases/fourslash/refactorExtractType_js_Union_CommentBeforeMember.ts
Labels: For Backlog Bug

#48550 fix(48544): Crash in "convert to default export" when using an import(...) type
  src/services/findAllReferences.ts
  src/services/refactors/convertExport.ts
  tests/cases/fourslash/refactorConvertExport_defaultToNamed3.ts
Labels: For Uncommitted Bug

#48442 Update Intl.DisplayNames types for better spec compliance
  src/lib/es2020.intl.d.ts
  tests/baselines/reference/es2020IntlAPIs.errors.txt
  tests/baselines/reference/es2020IntlAPIs.js
  tests/baselines/reference/es2020IntlAPIs.symbols
  tests/baselines/reference/es2020IntlAPIs.types
  tests/cases/conformance/es2020/es2020IntlAPIs.ts
Labels: For Uncommitted Bug

#48580 manually update webworker to remove AbortSignal.abort
  src/lib/webworker.generated.d.ts
Labels: Author: Team, For Uncommitted Bug

#48589 Permit type alias variance annotations only for certain object types
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/varianceAnnotations.errors.txt
  tests/baselines/reference/varianceAnnotationsWithCircularlyReferencesError.errors.txt
Labels: Author: Team, For Uncommitted Bug

#48584 Add additional tests for intra expression inference
  tests/baselines/reference/intraExpressionInferences.errors.txt
  tests/baselines/reference/intraExpressionInferences.js
  tests/baselines/reference/intraExpressionInferences.symbols
  tests/baselines/reference/intraExpressionInferences.types
  tests/cases/conformance/types/typeRelationships/typeInference/intraExpressionInferences.ts
Labels: For Milestone Bug

#48558 Ensure late painted statements are only transformed once, so inner substitutions are consistently read
  src/compiler/transformers/declarations.ts
  tests/baselines/reference/declarationEmitNamespaceMergedWithInterfaceNestedFunction.js
  tests/baselines/reference/declarationEmitNamespaceMergedWithInterfaceNestedFunction.symbols
  tests/baselines/reference/declarationEmitNamespaceMergedWithInterfaceNestedFunction.types
  tests/cases/compiler/declarationEmitNamespaceMergedWithInterfaceNestedFunction.ts
Labels: Author: Team, For Milestone Bug

#48592 Preserve the distributivity of inlined conditional types in declaration emit
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitInlinedDistributiveConditional.js
  tests/baselines/reference/declarationEmitInlinedDistributiveConditional.symbols
  tests/baselines/reference/declarationEmitInlinedDistributiveConditional.types
  tests/cases/compiler/declarationEmitInlinedDistributiveConditional.ts
Labels: Author: Team, For Milestone Bug

#48427 Do not reset control flow analysis on index signatures
  src/compiler/binder.ts
  tests/baselines/reference/controlFlowForIndexSignatures.errors.txt
  tests/baselines/reference/controlFlowForIndexSignatures.js
  tests/baselines/reference/controlFlowForIndexSignatures.symbols
  tests/baselines/reference/controlFlowForIndexSignatures.types
  tests/cases/compiler/controlFlowForIndexSignatures.ts
Labels: For Backlog Bug

#48602 Fix the version in baselines
  src/testRunner/unittests/tsbuild/outFile.ts
  src/testRunner/unittests/tsbuild/sample.ts
  src/testRunner/unittests/tsc/helpers.ts
  tests/baselines/reference/tsbuild/outFile/builds-till-project-specified.js
  tests/baselines/reference/tsbuild/outFile/rebuilds-completely-when-version-in-tsbuildinfo-doesnt-match-ts-version.js
  tests/baselines/reference/tsbuild/sample1/building-using-buildReferencedProject.js
  tests/baselines/reference/tsbuild/sample1/builds-till-project-specified.js
  tests/baselines/reference/tsbuild/sample1/does-not-rebuild-if-there-is-no-program-and-bundle-in-the-ts-build-info-event-if-version-doesnt-match-ts-version.js
  tests/baselines/reference/tsbuild/sample1/rebuilds-completely-when-version-in-tsbuildinfo-doesnt-match-ts-version.js
Labels: Author: Team, For Uncommitted Bug

#41992 preserve this when extracting functions
  src/services/refactors/extractSymbol.ts
  tests/cases/fourslash/extractFunctionContainingThis1.ts
  tests/cases/fourslash/extractFunctionContainingThis2.ts
  tests/cases/fourslash/extractFunctionContainingThis3.ts
  tests/cases/fourslash/extractFunctionContainingThis4.ts
Labels: For Backlog Bug

#47098 fix(44179): disentangle the meaning of `SymbolLinks.target`
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/spreadExpressionContextualTypeWithNamespace.js
  tests/baselines/reference/spreadExpressionContextualTypeWithNamespace.symbols
  tests/baselines/reference/spreadExpressionContextualTypeWithNamespace.types
  tests/cases/compiler/spreadExpressionContextualTypeWithNamespace.ts
Labels: For Backlog Bug

#48612 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220408145846943 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#48496 fix(48487): "Unexpected PrivateIdentifier in name expression with literal-like access" being hit
  src/compiler/utilities.ts
  tests/baselines/reference/typeFromPrivatePropertyAssignment.js
  tests/baselines/reference/typeFromPrivatePropertyAssignment.symbols
  tests/baselines/reference/typeFromPrivatePropertyAssignment.types
  tests/baselines/reference/typeFromPrivatePropertyAssignmentJs.js
  tests/baselines/reference/typeFromPrivatePropertyAssignmentJs.symbols
  tests/baselines/reference/typeFromPrivatePropertyAssignmentJs.types
  tests/cases/conformance/classes/members/privateNames/typeFromPrivatePropertyAssignment.ts
  tests/cases/conformance/classes/members/privateNames/typeFromPrivatePropertyAssignmentJs.ts
Labels: For Milestone Bug

#48605 Reuse type nodes from optional parameters even when not written as a union with `undefined`
  src/compiler/checker.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/services/codefixes/helpers.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/arrayFakeFlatNoCrashInferenceDeclarations.types
  tests/baselines/reference/assertionTypePredicates1.types
  tests/baselines/reference/asyncFunctionsAndStrictNullChecks.types
  tests/baselines/reference/callsOnComplexSignatures.types
  tests/baselines/reference/circularOptionalityRemoval.types
  tests/baselines/reference/contextuallyTypedParametersWithInitializers.types
  tests/baselines/reference/controlFlowAliasing.types
  tests/baselines/reference/controlFlowForIndexSignatures.types
  tests/baselines/reference/controlFlowOptionalChain.types
  tests/baselines/reference/defaultParameterAddsUndefinedWithStrictNullChecks.types
  tests/baselines/reference/destructureOptionalParameter.types
  tests/baselines/reference/destructuringAssignmentWithDefault.types
  tests/baselines/reference/genericFunctionInference1.types
  tests/baselines/reference/genericRestParameters1.types
  tests/baselines/reference/indexedAccessNormalization.types
  tests/baselines/reference/inferFromBindingPattern.types
  tests/baselines/reference/inferenceErasedSignatures.types
  tests/baselines/reference/initializedParameterBeforeNonoptionalNotOptional.types
  tests/baselines/reference/intersectionWithConflictingPrivates.types
  tests/baselines/reference/jsDeclarationsReactComponents.js
  tests/baselines/reference/jsxNamespaceGlobalReexport.types
  tests/baselines/reference/jsxNamespaceGlobalReexportMissingAliasTarget.types
  tests/baselines/reference/jsxNamespaceImplicitImportJSXNamespace.types
  tests/baselines/reference/leaveOptionalParameterAsWritten.js
  tests/baselines/reference/leaveOptionalParameterAsWritten.symbols
  tests/baselines/reference/leaveOptionalParameterAsWritten.types
  tests/baselines/reference/neverReturningFunctions1.types
  tests/baselines/reference/noCrashOnThisTypeUsage.types
  tests/baselines/reference/observableInferenceCanBeMade.types
  tests/baselines/reference/optionalParameterRetainsNull.types
  tests/baselines/reference/primitiveUnionDetection.types
  tests/baselines/reference/propertyAccessWidening.types
  tests/baselines/reference/spreadIdenticalTypesRemoved.types
  tests/baselines/reference/spreadUnion3.types
  tests/baselines/reference/stackDepthLimitCastingType.types
  tests/baselines/reference/strictNullLogicalAndOr.types
  tests/baselines/reference/substitutionTypesInIndexedAccessTypes.types
  tests/baselines/reference/thisTypeInObjectLiterals2.types
  tests/baselines/reference/truthinessCallExpressionCoercion.types
  tests/baselines/reference/truthinessCallExpressionCoercion1.types
  tests/baselines/reference/truthinessCallExpressionCoercion2.types
  tests/baselines/reference/unionReductionMutualSubtypes.types
  tests/baselines/reference/unionTypeReduction2.types
  tests/baselines/reference/variadicTuples1.types
  tests/cases/conformance/declarationEmit/leaveOptionalParameterAsWritten.ts
Labels: Author: Team, For Milestone Bug

#48613 Explore fewer constraints in getResolvedBaseConstraint
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug

#48633 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220410101528891 to main
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#48607 Don't have type annotations on suggested object literal methods
  src/services/completions.ts
  tests/cases/fourslash/completionsObjectLiteralMethod1.ts
  tests/cases/fourslash/completionsObjectLiteralMethod2.ts
  tests/cases/fourslash/completionsObjectLiteralMethod3.ts
Labels: Author: Team, For Milestone Bug

#48615 Don't skip tests named *Fourslash.ts
  src/testRunner/fourslashRunner.ts
  tests/cases/fourslash/commentsInterfaceFourslash.ts
Labels: For Uncommitted Bug

#48641 Fix nightly: Make LKG and nightly declaration emit the same for public API
  src/deprecatedCompat/deprecations.ts
Labels: Author: Team, For Uncommitted Bug

#48614 Fix the issue with not serializing impliedFormat when signature and version of the file are same
  src/compiler/builder.ts
  src/compiler/builderState.ts
  tests/baselines/reference/tsbuild/moduleSpecifiers/synthesized-module-specifiers-across-projects-resolve-correctly.js
  tests/baselines/reference/tsbuildWatch/moduleResolution/resolves-specifier-in-output-declaration-file-from-referenced-project-correctly-with-cts-and-mts-extensions.js
Labels: Author: Team, For Uncommitted Bug

#48645 Variance annotations on class expressions + deferred valiation
  src/compiler/checker.ts
  tests/baselines/reference/varianceAnnotations.errors.txt
  tests/baselines/reference/varianceAnnotations.js
  tests/baselines/reference/varianceAnnotations.symbols
  tests/baselines/reference/varianceAnnotations.types
  tests/cases/conformance/types/typeParameters/typeParameterLists/varianceAnnotations.ts
Labels: Author: Team, For Milestone Bug

#48659 More permissive parsing of instantiation expressions
  src/compiler/parser.ts
  tests/baselines/reference/instantiationExpressionErrors.errors.txt
  tests/baselines/reference/instantiationExpressionErrors.js
  tests/baselines/reference/instantiationExpressionErrors.symbols
  tests/baselines/reference/instantiationExpressionErrors.types
  tests/cases/conformance/types/typeParameters/typeArgumentLists/instantiationExpressionErrors.ts
Labels: Author: Team, For Milestone Bug

#48661 fix(48657): Using reserved words as intrinsic elements in TSX
  src/compiler/utilities.ts
  tests/baselines/reference/jsxElementsAsIdentifierNames.js
  tests/baselines/reference/jsxElementsAsIdentifierNames.symbols
  tests/baselines/reference/jsxElementsAsIdentifierNames.types
  tests/baselines/reference/jsxParsingError4(strict=true).errors.txt
  tests/baselines/reference/jsxParsingError4(strict=true).types
  tests/cases/compiler/jsxElementsAsIdentifierNames.tsx
Labels: For Backlog Bug

#48677 Update signatures to avoid post-LKG error
  src/deprecatedCompat/deprecations.ts
Labels: Author: Team, For Uncommitted Bug

#48682 Add support for git bisecting a twoslash repro run
  .github/workflows/twoslash-repros.yaml
Labels: Author: Team, For Uncommitted Bug

#48688 Twoslash repro workflow: setup-node needs a version spec
  .github/workflows/twoslash-repros.yaml
Labels: Author: Team, For Uncommitted Bug

#48689 Twoslash bisect: git checkout needs tags and all the history
  .github/workflows/twoslash-repros.yaml
Labels: Author: Team, For Uncommitted Bug

#48687 Fixed multiple prologue directives with parameter properties
  src/compiler/checker.ts
  src/compiler/transformers/ts.ts
  tests/baselines/reference/parameterPropertyInConstructorWithPrologues.js
  tests/baselines/reference/parameterPropertyInConstructorWithPrologues.symbols
  tests/baselines/reference/parameterPropertyInConstructorWithPrologues.types
  tests/cases/compiler/parameterPropertyInConstructorWithPrologues.ts
Labels: For Milestone Bug

#48707 Fix lints after dep update
  src/testRunner/unittests/services/extract/ranges.ts
  src/testRunner/unittests/tsserver/completionsIncomplete.ts
Labels: Author: Team, For Uncommitted Bug

#48264 Find Source Definition
  src/compiler/checker.ts
  src/compiler/moduleNameResolver.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/harness/client.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/server/editorServices.ts
  src/server/project.ts
  src/server/protocol.ts
  src/server/scriptInfo.ts
  src/server/session.ts
  src/server/utilitiesPublic.ts
  src/services/codefixes/importFixes.ts
  src/services/findAllReferences.ts
  src/services/goToDefinition.ts
  src/services/services.ts
  src/services/types.ts
  src/testRunner/tsconfig.json
  src/testRunner/unittests/tsserver/auxiliaryProject.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/showConfig/Shows tsconfig for single option/noDtsResolution/tsconfig.json
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/goToDefinitionExpandoElementAccess.ts
  tests/cases/fourslash/quickInfoUntypedModuleImport.ts
  tests/cases/fourslash/server/goToSource10_mapFromAtTypes3.ts
  tests/cases/fourslash/server/goToSource11_propertyOfAlias.ts
  tests/cases/fourslash/server/goToSource12_callbackParam.ts
  tests/cases/fourslash/server/goToSource1_localJsBesideDts.ts
  tests/cases/fourslash/server/goToSource2_nodeModulesWithTypes.ts
  tests/cases/fourslash/server/goToSource3_nodeModulesAtTypes.ts
  tests/cases/fourslash/server/goToSource5_sameAsGoToDef1.ts
  tests/cases/fourslash/server/goToSource6_sameAsGoToDef2.ts
  tests/cases/fourslash/server/goToSource7_conditionallyMinified.ts
  tests/cases/fourslash/server/goToSource8_mapFromAtTypes.ts
  tests/cases/fourslash/server/goToSource9_mapFromAtTypes2.ts
Labels: Author: Team, For Milestone Bug

#48721 Allow triggering twoslash repro bisection manually
  .github/workflows/twoslash-repros.yaml
Labels: Author: Team, For Uncommitted Bug

#48579 Instead of maintaining cache id etc, reset the "working" exports map cache.
  src/compiler/builder.ts
  src/compiler/builderState.ts
Labels: Author: Team, For Uncommitted Bug

#48699 Constraints for mapped types with filtering 'as' clauses
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypeConstraints2.errors.txt
  tests/baselines/reference/mappedTypeConstraints2.js
  tests/baselines/reference/mappedTypeConstraints2.symbols
  tests/baselines/reference/mappedTypeConstraints2.types
  tests/cases/conformance/types/mapped/mappedTypeConstraints2.ts
Labels: Author: Team, For Milestone Bug

#48755 Disallow line break between entity name and type arguments in typeof expression
  src/compiler/parser.ts
  tests/baselines/reference/newLineInTypeofInstantiation.js
  tests/baselines/reference/newLineInTypeofInstantiation.symbols
  tests/baselines/reference/newLineInTypeofInstantiation.types
  tests/cases/compiler/newLineInTypeofInstantiation.ts
Labels: Author: Team, For Milestone Bug

#48765 Fix constructor code when there is code between prologue statements and super call
  src/compiler/transformers/es2015.ts
  tests/baselines/reference/constructorWithSuperAndPrologue.es5.js
  tests/baselines/reference/constructorWithSuperAndPrologue.es5.symbols
  tests/baselines/reference/constructorWithSuperAndPrologue.es5.types
  tests/cases/compiler/constructorWithSuperAndPrologue.es5.ts
Labels: For Milestone Bug

#48770 Ensure enum aliases referenced in other enum members do not get marked as referenced
  src/compiler/checker.ts
  tests/baselines/reference/importElisionEnum.js
  tests/baselines/reference/importElisionEnum.symbols
  tests/baselines/reference/importElisionEnum.types
  tests/cases/compiler/importElisionEnum.ts
Labels: Author: Team, For Milestone Bug

#48773 Fix meta property symbol lookup
  src/compiler/checker.ts
  tests/baselines/reference/importMeta(module=commonjs,target=es5).symbols
  tests/baselines/reference/importMeta(module=commonjs,target=esnext).symbols
  tests/baselines/reference/importMeta(module=es2020,target=es5).symbols
  tests/baselines/reference/importMeta(module=es2020,target=esnext).symbols
  tests/baselines/reference/importMeta(module=esnext,target=es5).symbols
  tests/baselines/reference/importMeta(module=esnext,target=esnext).symbols
  tests/baselines/reference/importMeta(module=system,target=es5).symbols
  tests/baselines/reference/importMeta(module=system,target=esnext).symbols
  tests/baselines/reference/importMetaNarrowing(module=es2020).symbols
  tests/baselines/reference/importMetaNarrowing(module=esnext).symbols
  tests/baselines/reference/importMetaNarrowing(module=system).symbols
  tests/baselines/reference/misspelledNewMetaProperty.symbols
  tests/baselines/reference/nodeModulesAllowJsImportMeta(module=node12).symbols
  tests/baselines/reference/nodeModulesAllowJsImportMeta(module=nodenext).symbols
  tests/baselines/reference/nodeModulesImportMeta(module=node12).symbols
  tests/baselines/reference/nodeModulesImportMeta(module=nodenext).symbols
  tests/baselines/reference/plainJSGrammarErrors.symbols
  tests/cases/fourslash/goToDefinitionImportMeta.ts
Labels: Author: Team, For Milestone Bug

#48600 If we are updating dts of any of the file and it affects global scope, everything needs update in signature and dts emit
  src/compiler/builder.ts
  src/testRunner/unittests/tsc/incremental.ts
  tests/baselines/reference/tsc/incremental/change-to-type-that-gets-used-as-global-through-export-in-another-file-through-indirect-import.js
  tests/baselines/reference/tsc/incremental/change-to-type-that-gets-used-as-global-through-export-in-another-file.js
Labels: Author: Team, For Milestone Bug

#48793 Format completion snippet text before escaping
  src/services/completions.ts
  tests/cases/fourslash/completionsOverridingMethod2.ts
Labels: Author: Team, For Milestone Bug

#48570 fix(48556): never cannot be spread into object, but it can be spread into JSX props
  src/compiler/checker.ts
  tests/baselines/reference/correctlyMarkAliasAsReferences3.errors.txt
  tests/baselines/reference/jsxExcessPropsAndAssignability.errors.txt
  tests/baselines/reference/jsxNamespacePrefixInName.errors.txt
  tests/baselines/reference/jsxNamespacePrefixInNameReact.errors.txt
  tests/baselines/reference/tsxSpreadInvalidType.errors.txt
  tests/baselines/reference/tsxSpreadInvalidType.js
  tests/baselines/reference/tsxSpreadInvalidType.symbols
  tests/baselines/reference/tsxSpreadInvalidType.types
  tests/cases/conformance/jsx/tsxSpreadInvalidType.tsx
Labels: For Backlog Bug

#48751 Fix: verification of incremental correctness that was not working because of using wrote writeFile
  src/testRunner/unittests/tsbuild/helpers.ts
  src/testRunner/unittests/tsbuild/noEmitOnError.ts
  src/testRunner/unittests/tsbuild/publicApi.ts
  src/testRunner/unittests/tsbuild/sample.ts
  src/testRunner/unittests/tsc/helpers.ts
  src/testRunner/unittests/tsc/incremental.ts
  src/testRunner/unittests/tscWatch/helpers.ts
  src/testRunner/unittests/tscWatch/sourceOfProjectReferenceRedirect.ts
  src/testRunner/unittests/tsserver/projectReferences.ts
  tests/baselines/reference/tsbuild/noEmitOnError/semantic-errors-with-incremental-discrepancies.js
  tests/baselines/reference/tsbuild/noEmitOnError/syntax-errors-with-incremental-discrepancies.js
  tests/baselines/reference/tsbuild/sample1/building-using-getNextInvalidatedProject.js
  tests/baselines/reference/tsbuild/sample1/invalidates-projects-correctly.js
  tests/baselines/reference/tsc/incremental/noEmit-changes-composite-discrepancies.js
  tests/baselines/reference/tsc/incremental/noEmit-changes-incremental-declaration-discrepancies.js
  tests/baselines/reference/tsc/incremental/noEmit-changes-incremental-discrepancies.js
  tests/baselines/reference/tsc/incremental/noEmit-changes-with-initial-noEmit-composite-discrepancies.js
  tests/baselines/reference/tsc/incremental/noEmit-changes-with-initial-noEmit-incremental-declaration-discrepancies.js
  tests/baselines/reference/tsc/incremental/noEmit-changes-with-initial-noEmit-incremental-discrepancies.js
  tests/baselines/reference/tsc/incremental/when-new-file-is-added-to-the-referenced-project-discrepancies.js
  tests/baselines/reference/tsc/incremental/with-noEmitOnError-semantic-errors-discrepancies.js
  tests/baselines/reference/tsc/incremental/with-noEmitOnError-syntax-errors-discrepancies.js
  tests/baselines/reference/tscWatch/projectsWithReferences/on-sample-project.js
  tests/baselines/reference/tscWatch/projectsWithReferences/on-transitive-references-in-different-folders-with-no-files-clause.js
  tests/baselines/reference/tscWatch/projectsWithReferences/on-transitive-references-in-different-folders.js
  tests/baselines/reference/tscWatch/projectsWithReferences/on-transitive-references.js
  tests/baselines/reference/tscWatch/projectsWithReferences/when-referenced-project-uses-different-module-resolution.js
  tests/baselines/reference/tscWatch/sourceOfProjectReferenceRedirect/when-packageJson-has-types-field-when-solution-is-already-built.js
  tests/baselines/reference/tscWatch/sourceOfProjectReferenceRedirect/when-packageJson-has-types-field-with-preserveSymlinks-when-solution-is-already-built.js
  tests/baselines/reference/tscWatch/sourceOfProjectReferenceRedirect/when-packageJson-has-types-field-with-scoped-package-when-solution-is-already-built.js
  tests/baselines/reference/tscWatch/sourceOfProjectReferenceRedirect/when-packageJson-has-types-field-with-scoped-package-with-preserveSymlinks-when-solution-is-already-built.js
  tests/baselines/reference/tscWatch/sourceOfProjectReferenceRedirect/when-referencing-file-from-subFolder-when-solution-is-already-built.js
  tests/baselines/reference/tscWatch/sourceOfProjectReferenceRedirect/when-referencing-file-from-subFolder-with-preserveSymlinks-when-solution-is-already-built.js
  tests/baselines/reference/tscWatch/sourceOfProjectReferenceRedirect/when-referencing-file-from-subFolder-with-scoped-package-when-solution-is-already-built.js
  tests/baselines/reference/tscWatch/sourceOfProjectReferenceRedirect/when-referencing-file-from-subFolder-with-scoped-package-with-preserveSymlinks-when-solution-is-already-built.js
  tests/baselines/reference/tscWatch/sourceOfProjectReferenceRedirect/with-simple-project-when-solution-is-already-built.js
Labels: Author: Team, For Uncommitted Bug

#48774 Fix emit for undefined SourceFile
  src/compiler/emitter.ts
  src/compiler/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#48815 Fix auto-import completions sometimes not updating existing imports
  src/services/codefixes/importFixes.ts
  src/services/completions.ts
  tests/cases/fourslash/completionsImport_preferUpdatingExistingImport.ts
Labels: Author: Team, For Milestone Bug

#48693 Don't run scheduled GitHub actions on forks
  .github/workflows/codeql.yml
  .github/workflows/ensure-related-repos-run-crons.yml
  .github/workflows/nightly.yaml
  .github/workflows/twoslash-repros.yaml
  .github/workflows/update-package-lock.yaml
Labels: For Backlog Bug, Housekeeping

#48842 Fix workflow syntax error
  .github/workflows/twoslash-repros.yaml
Labels: Author: Team, For Uncommitted Bug

#48837 Improve support for numeric string types
  src/compiler/checker.ts
  tests/baselines/reference/numericStringLiteralTypes.js
  tests/baselines/reference/numericStringLiteralTypes.symbols
  tests/baselines/reference/numericStringLiteralTypes.types
  tests/baselines/reference/templateLiteralTypes1.errors.txt
  tests/baselines/reference/templateLiteralTypes1.js
  tests/baselines/reference/templateLiteralTypes1.symbols
  tests/baselines/reference/templateLiteralTypes1.types
  tests/cases/conformance/types/literal/numericStringLiteralTypes.ts
  tests/cases/conformance/types/literal/templateLiteralTypes1.ts
Labels: Author: Team, For Uncommitted Bug

#48769 Fix `getExportSymbolOfValueSymbolIfExported`
  src/compiler/checker.ts
  tests/baselines/reference/reExportJsFromTs.js
  tests/baselines/reference/reExportJsFromTs.symbols
  tests/baselines/reference/reExportJsFromTs.types
  tests/cases/conformance/salsa/reExportJsFromTs.ts
Labels: Author: Team, For Milestone Bug

#48824 Add Node v18 to CI
  .github/workflows/accept-baselines-fix-lints.yaml
  .github/workflows/ci.yml
  .github/workflows/new-release-branch.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release-branch-artifact.yaml
  .github/workflows/rich-navigation.yml
  .github/workflows/set-version.yaml
  .github/workflows/sync-branch.yaml
  .github/workflows/twoslash-repros.yaml
  .github/workflows/update-lkg.yml
  .github/workflows/update-package-lock.yaml
Labels: For Uncommitted Bug

#48860 Stop tag after @callback from crashing
  src/compiler/parser.ts
  tests/cases/fourslash/jsTagAfterCallback1.ts
  tests/cases/fourslash/jsTagAfterCallback2.ts
  tests/cases/fourslash/jsTagAfterTypedef1.ts
Labels: Author: Team, For Milestone Bug

#48533 Add JS-specific diagnostic message for `resolve()` in Promise where type argument can't be inferred
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/services/codefixes/fixAddVoidToPromise.ts
  tests/cases/fourslash/codeFixAddVoidToPromiseJS.1.ts
  tests/cases/fourslash/codeFixAddVoidToPromiseJS.2.ts
  tests/cases/fourslash/codeFixAddVoidToPromiseJS.3.ts
  tests/cases/fourslash/codeFixAddVoidToPromiseJS.4.ts
Labels: For Backlog Bug

#48757 feat(48743): No autocompletion in parameter object destructuring in JavaScript files
  src/services/completions.ts
  tests/cases/fourslash/completionListInObjectBindingPattern16.ts
Labels: For Backlog Bug

#48752 Eagerly resolve module specifiers for auto-import completions in `--moduleResolution node12+`
  src/compiler/types.ts
  src/server/moduleSpecifierCache.ts
  src/server/protocol.ts
  src/services/codefixes/importFixes.ts
  src/services/completions.ts
  src/services/exportInfoMap.ts
  src/services/types.ts
  src/services/utilities.ts
  src/testRunner/unittests/tsserver/completions.ts
  src/testRunner/unittests/tsserver/metadataInResponse.ts
  src/testRunner/unittests/tsserver/moduleSpecifierCache.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/completionEntryForUnionMethod.baseline
  tests/baselines/reference/completionImportCallAssertion.baseline
  tests/baselines/reference/completionsCommentsClass.baseline
  tests/baselines/reference/completionsCommentsClassMembers.baseline
  tests/baselines/reference/completionsCommentsCommentParsing.baseline
  tests/baselines/reference/completionsCommentsFunctionDeclaration.baseline
  tests/baselines/reference/completionsCommentsFunctionExpression.baseline
  tests/baselines/reference/completionsJSDocTags.baseline
  tests/baselines/reference/completionsSalsaMethodsOnAssignedFunctionExpressions.baseline
  tests/baselines/reference/completionsStringMethods.baseline
  tests/cases/fourslash/autoImportsNodeNext1.ts
  tests/cases/fourslash/server/autoImportProvider_exportMap3.ts
  tests/cases/fourslash/server/autoImportProvider_exportMap8.ts
Labels: Author: Team, For Uncommitted Bug

#48323 Fix export default expression comment
  src/compiler/transformers/declarations.ts
  tests/baselines/reference/exportDefaultExpressionComments.js
  tests/baselines/reference/exportDefaultExpressionComments.symbols
  tests/baselines/reference/exportDefaultExpressionComments.types
  tests/cases/conformance/declarationEmit/exportDefaultExpressionComments.ts
Labels: For Backlog Bug

#48853 fix(48851): Document highlights on 'in' in mapped type causes debug failure
  src/services/documentHighlights.ts
  tests/cases/fourslash/documentHighlightInKeyword.ts
Labels: For Backlog Bug

#48866 Dont reload config file when package.json change is detected
  src/compiler/tsbuildPublic.ts
Labels: Author: Team, For Uncommitted Bug

#48881 Use same error for iteration in <=ES5
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/services/codefixes/addMissingAwait.ts
  tests/baselines/reference/ES5For-ofTypeCheck13.errors.txt
  tests/baselines/reference/ES5For-ofTypeCheck14.errors.txt
Labels: Author: Team, For Uncommitted Bug

#47824 Fix #47753 - Organize imports removes type imports that are only referenced in @link (jsdoc)
  src/compiler/checker.ts
  tests/baselines/reference/jsdocLink3.baseline
  tests/cases/fourslash/organizeImports10.ts
  tests/cases/fourslash/organizeImports11.ts
Labels: For Backlog Bug

#48787 fix(48759): import<T> is valid syntax in nightly
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/importCallExpressionWithTypeArgument.errors.txt
  tests/baselines/reference/importWithTypeArguments.errors.txt
  tests/baselines/reference/importWithTypeArguments.js
  tests/baselines/reference/importWithTypeArguments.symbols
  tests/baselines/reference/importWithTypeArguments.types
  tests/cases/conformance/types/import/importWithTypeArguments.ts
Labels: For Milestone Bug
