Repository microsoft/TypeScript, pull requests merged in 2022-05, with the labels that each got.

#48909 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220501124712191 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#48913 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220502133721319 to main
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#48910 Add a regression test for completion list in object literal involving inferred obj with optional members
  tests/cases/fourslash/completionListInObjectLiteral8.ts
Labels: For Uncommitted Bug

#48921 Fix formatter's processChildNodes
  src/services/formatting/formatting.ts
  src/services/formatting/formattingScanner.ts
  tests/cases/fourslash/formatAfterPasteInString.ts
Labels: Author: Team, For Milestone Bug

#48560 fix(48557): Add missing JSDoc parameters
  AUTHORS.md
  src/lib/es2020.bigint.d.ts
  src/lib/es5.d.ts
Labels: For Backlog Bug

#48923 Temporarily revert unconstrained type parameter strictness in TS 4.7
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/genericUnboundedTypeParamAssignability.errors.txt
  tests/baselines/reference/keyofAndIndexedAccess.errors.txt
  tests/baselines/reference/mappedTypesAndObjects.errors.txt
  tests/baselines/reference/tsxNotUsingApparentTypeOfSFC.errors.txt
  tests/baselines/reference/unknownType1.errors.txt
Labels: Author: Team, For Uncommitted Bug

#48758 Don't go past import in cross-project renaming
  src/harness/client.ts
  src/server/session.ts
  src/services/goToDefinition.ts
  src/services/services.ts
  src/services/types.ts
  tests/baselines/reference/renameNamedImport.baseline
  tests/baselines/reference/renameNamespaceImport.baseline
  tests/cases/fourslash/server/renameNamedImport.ts
  tests/cases/fourslash/server/renameNamespaceImport.ts
Labels: Author: Team, For Milestone Bug

#48782 Pick PR #48687 to release-4.6
  src/compiler/checker.ts
  src/compiler/transformers/ts.ts
  tests/baselines/reference/parameterPropertyInConstructorWithPrologues.js
  tests/baselines/reference/parameterPropertyInConstructorWithPrologues.symbols
  tests/baselines/reference/parameterPropertyInConstructorWithPrologues.types
  tests/cases/compiler/parameterPropertyInConstructorWithPrologues.ts
Labels: Author: Team, For Uncommitted Bug

#48941 Fix blocking of recursive dependencies in getNarrowedTypeOfSymbol
  src/compiler/checker.ts
  tests/baselines/reference/dependentDestructuredVariables.errors.txt
  tests/baselines/reference/dependentDestructuredVariables.js
  tests/baselines/reference/dependentDestructuredVariables.symbols
  tests/baselines/reference/dependentDestructuredVariables.types
  tests/cases/conformance/controlFlow/dependentDestructuredVariables.ts
Labels: Author: Team, For Milestone Bug

#48943 [release-4.6] Cherry pick #48941 (get narrowed type of symbol fix)
  src/compiler/checker.ts
  tests/baselines/reference/dependentDestructuredVariables.errors.txt
  tests/baselines/reference/dependentDestructuredVariables.js
  tests/baselines/reference/dependentDestructuredVariables.symbols
  tests/baselines/reference/dependentDestructuredVariables.types
  tests/cases/conformance/controlFlow/dependentDestructuredVariables.ts
Labels: Author: Team, For Milestone Bug

#48836 Add tests case for function check type being correctly paranthesized in quick info
  tests/cases/fourslash/quickInfoFunctionCheckType.ts
Labels: For Backlog Bug

#48803 Document encodeURIComponent/encodeURI's argument as unencoded
  src/lib/es5.d.ts
  tests/baselines/reference/completionsCommentsClass.baseline
  tests/baselines/reference/completionsCommentsClassMembers.baseline
  tests/baselines/reference/completionsCommentsCommentParsing.baseline
  tests/baselines/reference/completionsCommentsFunctionDeclaration.baseline
  tests/baselines/reference/completionsCommentsFunctionExpression.baseline
Labels: For Backlog Bug

#48797 Run `mocha` using `process.execPath` instead of harcoding `"node"`
  scripts/build/tests.js
Labels: Housekeeping, For Uncommitted Bug

#48862 When source file is redirected, set the prototype correctly in node factory
  src/compiler/factory/nodeFactory.ts
  src/testRunner/tsconfig.json
  src/testRunner/unittests/tsc/redirect.ts
  tests/baselines/reference/tsc/redirect/when-redirecting-ts-file.js
Labels: Author: Team, For Milestone Bug

#48940 Revert "Don't treat a colon in a conditional expression branch as part of an arrow function"
  src/compiler/parser.ts
  tests/baselines/reference/parserArrowFunctionExpression10.errors.txt
  tests/baselines/reference/parserArrowFunctionExpression10.js
  tests/baselines/reference/parserArrowFunctionExpression10.symbols
  tests/baselines/reference/parserArrowFunctionExpression10.types
  tests/baselines/reference/parserArrowFunctionExpression11.errors.txt
  tests/baselines/reference/parserArrowFunctionExpression11.js
  tests/baselines/reference/parserArrowFunctionExpression11.symbols
  tests/baselines/reference/parserArrowFunctionExpression11.types
  tests/baselines/reference/parserArrowFunctionExpression12.errors.txt
  tests/baselines/reference/parserArrowFunctionExpression12.js
  tests/baselines/reference/parserArrowFunctionExpression12.symbols
  tests/baselines/reference/parserArrowFunctionExpression12.types
  tests/baselines/reference/parserArrowFunctionExpression15.js
  tests/baselines/reference/parserArrowFunctionExpression15.symbols
  tests/baselines/reference/parserArrowFunctionExpression15.types
  tests/baselines/reference/parserArrowFunctionExpression16.js
  tests/baselines/reference/parserArrowFunctionExpression16.symbols
  tests/baselines/reference/parserArrowFunctionExpression16.types
  tests/baselines/reference/parserArrowFunctionExpression8.errors.txt
  tests/baselines/reference/parserArrowFunctionExpression8.js
  tests/baselines/reference/parserArrowFunctionExpression8.symbols
  tests/baselines/reference/parserArrowFunctionExpression8.types
  tests/baselines/reference/parserArrowFunctionExpression8Js.errors.txt
  tests/baselines/reference/parserArrowFunctionExpression8Js.js
  tests/baselines/reference/parserArrowFunctionExpression8Js.symbols
  tests/baselines/reference/parserArrowFunctionExpression8Js.types
  tests/baselines/reference/parserArrowFunctionExpression9.errors.txt
  tests/baselines/reference/parserArrowFunctionExpression9.js
  tests/baselines/reference/parserArrowFunctionExpression9.symbols
  tests/baselines/reference/parserArrowFunctionExpression9.types
  tests/cases/conformance/parser/ecmascript5/ArrowFunctionExpressions/parserArrowFunctionExpression15.ts
  tests/cases/conformance/parser/ecmascript5/ArrowFunctionExpressions/parserArrowFunctionExpression16.ts
Labels: Author: Team, For Milestone Bug

#48953 Skip missing nodes in formatting
  src/services/formatting/formatting.ts
  tests/cases/fourslash/formatV8Directive.ts
Labels: Author: Team, For Milestone Bug

#48959 Revert "feat(47595): allow using private fields in type queries"
  src/compiler/parser.ts
  tests/baselines/reference/privateNameInTypeQuery.errors.txt
  tests/baselines/reference/privateNameInTypeQuery.js
  tests/baselines/reference/privateNameInTypeQuery.symbols
  tests/baselines/reference/privateNameInTypeQuery.types
  tests/cases/conformance/classes/members/privateNames/privateNameInTypeQuery.ts
Labels: Author: Team, For Uncommitted Bug

#48938 Skip ambient modules in globalThis
  src/compiler/checker.ts
  tests/baselines/reference/globalThisAmbientModules.errors.txt
  tests/baselines/reference/globalThisAmbientModules.js
  tests/baselines/reference/globalThisAmbientModules.symbols
  tests/baselines/reference/globalThisAmbientModules.types
  tests/cases/conformance/es2019/globalThisAmbientModules.ts
Labels: Author: Team, For Milestone Bug

#48874 No error on toplevel return in JS
  src/compiler/program.ts
  tests/baselines/reference/emitDecoratorMetadata_isolatedModules.errors.txt
  tests/baselines/reference/emitDecoratorMetadata_isolatedModules.js
  tests/baselines/reference/emitDecoratorMetadata_isolatedModules.symbols
  tests/baselines/reference/emitDecoratorMetadata_isolatedModules.types
  tests/baselines/reference/plainJSGrammarErrors.errors.txt
Labels: Author: Team, For Milestone Bug

#48974 Fix node16 tests for module resolution
  src/testRunner/unittests/tsbuild/moduleResolution.ts
  src/testRunner/unittests/tsbuild/moduleSpecifiers.ts
  tests/baselines/reference/tsbuild/moduleSpecifiers/synthesized-module-specifiers-across-projects-resolve-correctly.js
  tests/baselines/reference/tsbuildWatch/moduleResolution/resolves-specifier-in-output-declaration-file-from-referenced-project-correctly-with-cts-and-mts-extensions.js
Labels: Author: Team, For Uncommitted Bug

#47925 Allow export map entries to remap back to input files for a program
  src/compiler/diagnosticMessages.json
  src/compiler/moduleNameResolver.ts
  src/compiler/program.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/testRunner/unittests/moduleResolution.ts
  tests/baselines/reference/nodeAllowJsPackageSelfName(module=node16).errors.txt
  tests/baselines/reference/nodeAllowJsPackageSelfName(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesAllowJsConditionalPackageExports(module=node16).errors.txt
  tests/baselines/reference/nodeModulesAllowJsConditionalPackageExports(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesAllowJsPackageExports(module=node16).errors.txt
  tests/baselines/reference/nodeModulesAllowJsPackageExports(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesAllowJsPackageImports(module=node16).errors.txt
  tests/baselines/reference/nodeModulesAllowJsPackageImports(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesConditionalPackageExports(module=node16).errors.txt
  tests/baselines/reference/nodeModulesConditionalPackageExports(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesDeclarationEmitWithPackageExports(module=node16).errors.txt
  tests/baselines/reference/nodeModulesDeclarationEmitWithPackageExports(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesPackageExports(module=node16).errors.txt
  tests/baselines/reference/nodeModulesPackageExports(module=nodenext).errors.txt
  tests/baselines/reference/nodeNextPackageImportMapRootDir.js
  tests/baselines/reference/nodeNextPackageImportMapRootDir.symbols
  tests/baselines/reference/nodeNextPackageImportMapRootDir.types
  tests/baselines/reference/nodeNextPackageSelfNameWithOutDir.errors.txt
  tests/baselines/reference/nodeNextPackageSelfNameWithOutDir.js
  tests/baselines/reference/nodeNextPackageSelfNameWithOutDir.symbols
  tests/baselines/reference/nodeNextPackageSelfNameWithOutDir.types
  tests/baselines/reference/nodeNextPackageSelfNameWithOutDirDeclDir.errors.txt
  tests/baselines/reference/nodeNextPackageSelfNameWithOutDirDeclDir.js
  tests/baselines/reference/nodeNextPackageSelfNameWithOutDirDeclDir.symbols
  tests/baselines/reference/nodeNextPackageSelfNameWithOutDirDeclDir.types
  tests/baselines/reference/nodeNextPackageSelfNameWithOutDirDeclDirComposite.js
  tests/baselines/reference/nodeNextPackageSelfNameWithOutDirDeclDirComposite.symbols
  tests/baselines/reference/nodeNextPackageSelfNameWithOutDirDeclDirComposite.types
  tests/baselines/reference/nodeNextPackageSelfNameWithOutDirDeclDirCompositeNestedDirs.js
  tests/baselines/reference/nodeNextPackageSelfNameWithOutDirDeclDirCompositeNestedDirs.symbols
  tests/baselines/reference/nodeNextPackageSelfNameWithOutDirDeclDirCompositeNestedDirs.types
  tests/baselines/reference/nodeNextPackageSelfNameWithOutDirDeclDirNestedDirs.errors.txt
  tests/baselines/reference/nodeNextPackageSelfNameWithOutDirDeclDirNestedDirs.js
  tests/baselines/reference/nodeNextPackageSelfNameWithOutDirDeclDirNestedDirs.symbols
  tests/baselines/reference/nodeNextPackageSelfNameWithOutDirDeclDirNestedDirs.types
  tests/baselines/reference/nodeNextPackageSelfNameWithOutDirDeclDirRootDir.js
  tests/baselines/reference/nodeNextPackageSelfNameWithOutDirDeclDirRootDir.symbols
  tests/baselines/reference/nodeNextPackageSelfNameWithOutDirDeclDirRootDir.types
  tests/baselines/reference/nodeNextPackageSelfNameWithOutDirRootDir.js
  tests/baselines/reference/nodeNextPackageSelfNameWithOutDirRootDir.symbols
  tests/baselines/reference/nodeNextPackageSelfNameWithOutDirRootDir.types
  tests/cases/compiler/nodeNextPackageImportMapRootDir.ts
  tests/cases/compiler/nodeNextPackageSelfNameWithOutDir.ts
  tests/cases/compiler/nodeNextPackageSelfNameWithOutDirDeclDir.ts
  tests/cases/compiler/nodeNextPackageSelfNameWithOutDirDeclDirComposite.ts
  tests/cases/compiler/nodeNextPackageSelfNameWithOutDirDeclDirCompositeNestedDirs.ts
  tests/cases/compiler/nodeNextPackageSelfNameWithOutDirDeclDirNestedDirs.ts
  tests/cases/compiler/nodeNextPackageSelfNameWithOutDirDeclDirRootDir.ts
  tests/cases/compiler/nodeNextPackageSelfNameWithOutDirRootDir.ts
Labels: Author: Team, For Milestone Bug

#48967 fix(48878): TypeChecker.getTypeAtLocation throws runtime errors when passed valid nodes
  src/compiler/checker.ts
  src/testRunner/unittests/publicApi.ts
Labels: For Backlog Bug

#48979 Clear ExportMapCache on cancellation requested
  src/services/exportInfoMap.ts
Labels: Author: Team, For Milestone Bug

#48978 Harden combineProjectOutputForReferences against empty results
  src/server/session.ts
  tests/baselines/reference/referencesToNonPropertyNameStringLiteral.baseline.jsonc
  tests/cases/fourslash/server/referencesToNonPropertyNameStringLiteral.ts
Labels: Author: Team, For Milestone Bug

#48800 Add ES2022 `Intl.Segmenter` type
  src/compiler/commandLineParser.ts
  src/lib/es2022.d.ts
  src/lib/es2022.intl.d.ts
  src/lib/libs.json
  tests/baselines/reference/es2022IntlAPIs.symbols
  tests/baselines/reference/formatToPartsBigInt.symbols
  tests/baselines/reference/numberFormatCurrencySign.symbols
  tests/baselines/reference/numberFormatCurrencySignResolved.symbols
  tests/baselines/reference/reactJsxReactResolvedNodeNext.trace.json
  tests/baselines/reference/reactJsxReactResolvedNodeNextEsm.trace.json
  tests/baselines/reference/tsc/runWithoutArgs/does-not-add-color-when-NO_COLOR-is-set.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped-when-host-can't-provide-terminal-width.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
Labels: For Backlog Bug

#48994 Fix more tests missing 'it' call in 'describe'
  src/testRunner/unittests/publicApi.ts
Labels: Author: Team, For Uncommitted Bug

#48995 Respect importModuleSpecifierEnding inside node_modules packages
  src/compiler/moduleSpecifiers.ts
  tests/cases/fourslash/autoImportNoPackageJson_commonjs.ts
  tests/cases/fourslash/autoImportNoPackageJson_nodenext.ts
  tests/cases/fourslash/importNameCodeFixJsEnding.ts
Labels: Author: Team, For Milestone Bug

#48999 Fix missing parsingContext restore at return in parseDelimitedList
  src/compiler/parser.ts
  tests/baselines/reference/parserUnparsedTokenCrash1.errors.txt
  tests/baselines/reference/parserUnparsedTokenCrash1.js
  tests/baselines/reference/parserUnparsedTokenCrash1.symbols
  tests/baselines/reference/parserUnparsedTokenCrash1.types
  tests/baselines/reference/parserUnparsedTokenCrash2.errors.txt
  tests/baselines/reference/parserUnparsedTokenCrash2.js
  tests/baselines/reference/parserUnparsedTokenCrash2.symbols
  tests/baselines/reference/parserUnparsedTokenCrash2.types
  tests/cases/compiler/parserUnparsedTokenCrash1.ts
  tests/cases/compiler/parserUnparsedTokenCrash2.ts
Labels: Author: Team, For Milestone Bug

#49002 Flag resolution mode assertions in non-nightly builds
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/program.ts
  src/compiler/transformers/declarations.ts
  src/compiler/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#49016 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220508150540507 to main
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#48861 Fix type parameter comparability to consistently allow comparisons on unconstrained type parameters
  src/compiler/checker.ts
  tests/baselines/reference/comparisonOperatorWithNoRelationshipTypeParameter.errors.txt
  tests/baselines/reference/genericWithNoConstraintComparableWithCurlyCurly.errors.txt
  tests/baselines/reference/genericWithNoConstraintComparableWithCurlyCurly.js
  tests/baselines/reference/genericWithNoConstraintComparableWithCurlyCurly.symbols
  tests/baselines/reference/genericWithNoConstraintComparableWithCurlyCurly.types
  tests/baselines/reference/intersectionNarrowing.types
  tests/baselines/reference/unknownType1.errors.txt
  tests/baselines/reference/variadicTuples2.errors.txt
  tests/cases/compiler/genericWithNoConstraintComparableWithCurlyCurly.ts
Labels: Author: Team, For Milestone Bug

#49035 Fix module specifier generation crash from typesVersions
  src/compiler/moduleSpecifiers.ts
  tests/cases/fourslash/importNameCodeFix_typesVersions.ts
Labels: Author: Team, For Uncommitted Bug

#48946 Report error for invalid 'this' type during 'await'
  src/compiler/checker.ts
  tests/baselines/reference/await_incorrectThisType.errors.txt
  tests/cases/conformance/async/es2017/await_incorrectThisType.ts
Labels: Author: Team, For Milestone Bug

#48888 fix(48887) exposing rest helper functions externally
  src/compiler/utilities.ts
  src/compiler/utilitiesPublic.ts
  src/harness/harnessIO.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Uncommitted Bug

#48813 fix(48673): Find all reference doesn't work on access modifier for constructor
  src/services/utilities.ts
  tests/baselines/reference/constructorFindAllReferences1.baseline.jsonc
  tests/baselines/reference/constructorFindAllReferences2.baseline.jsonc
  tests/baselines/reference/constructorFindAllReferences3.baseline.jsonc
  tests/baselines/reference/constructorFindAllReferences4.baseline.jsonc
  tests/cases/fourslash/constructorFindAllReferences1.ts
  tests/cases/fourslash/constructorFindAllReferences2.ts
  tests/cases/fourslash/constructorFindAllReferences3.ts
  tests/cases/fourslash/constructorFindAllReferences4.ts
Labels: For Backlog Bug

#49014 fix(48912): fractionalSecondDigits configure
  src/lib/es2021.intl.d.ts
Labels: lib update, For Milestone Bug

#49009 fix(49001): Missing properties quickfix does not add missing imports
  src/services/codefixes/fixAddMissingMember.ts
  tests/cases/fourslash/codeFixAddMissingProperties21.ts
Labels: For Milestone Bug

#46719 Add JSDoc's @inheritDoc Support for Static Class Members for TypeScript
  src/services/jsDoc.ts
  src/services/services.ts
  tests/baselines/reference/quickInfoInheritDoc.baseline
  tests/baselines/reference/quickInfoInheritDoc2.baseline
  tests/baselines/reference/quickInfoInheritDoc3.baseline
  tests/cases/fourslash/jsDocInheritDoc.ts
  tests/cases/fourslash/quickInfoInheritDoc.ts
  tests/cases/fourslash/quickInfoInheritDoc2.ts
  tests/cases/fourslash/quickInfoInheritDoc3.ts
Labels: For Backlog Bug

#48754 Add missing source property to Intl formatRangeToParts methods
  src/lib/es2021.intl.d.ts
  src/lib/esnext.intl.d.ts
  tests/baselines/reference/DateTimeFormatAndNumberFormatES2021.types
Labels: For Backlog Bug

#48668 Fixed an issue with contextual type for intersection properties
  src/compiler/checker.ts
  tests/baselines/reference/contextualTypeFunctionObjectPropertyIntersection.js
  tests/baselines/reference/contextualTypeFunctionObjectPropertyIntersection.symbols
  tests/baselines/reference/contextualTypeFunctionObjectPropertyIntersection.types
  tests/cases/compiler/contextualTypeFunctionObjectPropertyIntersection.ts
Labels: For Backlog Bug

#49042 fix(48912): fractionalSecondDigits is 1, 2 or 3.
  src/lib/es2021.intl.d.ts
  tests/lib/lib.d.ts
Labels: For Milestone Bug

#46508 fix: update types for RTF.p.formatToParts() result
  src/lib/es2020.intl.d.ts
Labels: lib update, For Milestone Bug

#49057 Add regression test for #46192
  src/harness/fourslashInterfaceImpl.ts
  tests/cases/fourslash/autoImportPathsAliasesAndBarrels.ts
  tests/cases/fourslash/fourslash.ts
Labels: Author: Team, For Uncommitted Bug

#49029 fix(44466): Fixes parsing contextual keyword casts as arrow functions
  src/compiler/parser.ts
  tests/baselines/reference/modifierParenCast.js
  tests/baselines/reference/modifierParenCast.symbols
  tests/baselines/reference/modifierParenCast.types
  tests/cases/compiler/modifierParenCast.ts
Labels: For Milestone Bug, For Backlog Bug

#49056 Allow referencing type-only exports as namespace members in ImportTypes and TypeQueries
  src/compiler/checker.ts
  tests/baselines/reference/namespaceImportTypeQuery.errors.txt
  tests/baselines/reference/namespaceImportTypeQuery.js
  tests/baselines/reference/namespaceImportTypeQuery.symbols
  tests/baselines/reference/namespaceImportTypeQuery.types
  tests/baselines/reference/typeofImportTypeOnlyExport.js
  tests/baselines/reference/typeofImportTypeOnlyExport.symbols
  tests/baselines/reference/typeofImportTypeOnlyExport.types
  tests/cases/conformance/declarationEmit/typeofImportTypeOnlyExport.ts
  tests/cases/conformance/externalModules/typeOnly/namespaceImportTypeQuery.ts
Labels: Author: Team, For Milestone Bug

#47994 fix(7410): Support JSX Element as JSX Attribute Value
  src/compiler/diagnosticMessages.json
  src/compiler/factory/nodeFactory.ts
  src/compiler/parser.ts
  src/compiler/transformers/jsx.ts
  src/compiler/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/jsxAttributeInitializer(jsx=preserve).errors.txt
  tests/baselines/reference/jsxAttributeInitializer(jsx=preserve).js
  tests/baselines/reference/jsxAttributeInitializer(jsx=preserve).symbols
  tests/baselines/reference/jsxAttributeInitializer(jsx=preserve).types
  tests/baselines/reference/jsxAttributeInitializer(jsx=react).errors.txt
  tests/baselines/reference/jsxAttributeInitializer(jsx=react).js
  tests/baselines/reference/jsxAttributeInitializer(jsx=react).symbols
  tests/baselines/reference/jsxAttributeInitializer(jsx=react).types
  tests/baselines/reference/jsxAttributeMissingInitializer.errors.txt
  tests/baselines/reference/jsxEsprimaFbTestSuite.errors.txt
  tests/baselines/reference/jsxEsprimaFbTestSuite.js
  tests/baselines/reference/jsxEsprimaFbTestSuite.symbols
  tests/baselines/reference/jsxEsprimaFbTestSuite.types
  tests/baselines/reference/jsxInvalidEsprimaTestSuite.errors.txt
  tests/baselines/reference/jsxInvalidEsprimaTestSuite.js
  tests/baselines/reference/jsxInvalidEsprimaTestSuite.types
  tests/cases/conformance/jsx/jsxAttributeInitializer.ts
Labels: For Backlog Bug

#49051 fix: `getDefaultLibFilePath` should normalize `__dirname`
  src/services/services.ts
Labels: For Uncommitted Bug

#45978 feat: support error when comparing with object/array literals
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/utilitiesPublic.ts
  tests/baselines/reference/conditionalEqualityOnLiteralObjects.errors.txt
  tests/baselines/reference/conditionalEqualityOnLiteralObjects.js
  tests/baselines/reference/conditionalEqualityOnLiteralObjects.symbols
  tests/baselines/reference/conditionalEqualityOnLiteralObjects.types
  tests/baselines/reference/functionImplementationErrors.errors.txt
  tests/baselines/reference/functionImplementations.errors.txt
  tests/baselines/reference/narrowByEquality.errors.txt
  tests/baselines/reference/parserRealSource7.errors.txt
  tests/cases/compiler/conditionalEqualityOnLiteralObjects.ts
Labels: For Uncommitted Bug

#49087 Make watch/FS testing code friendlier for project loading in module transformation
  src/compiler/watch.ts
  src/harness/virtualFileSystemWithWatch.ts
  src/server/tsconfig.json
  src/server/watchType.ts
Labels: Author: Team, For Uncommitted Bug

#49098 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220513105801844 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#48954 fix(48948): constructor can't be the name of class accessors and generators
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/program.ts
  tests/baselines/reference/constructorNameInAccessor.errors.txt
  tests/baselines/reference/constructorNameInAccessor.js
  tests/baselines/reference/constructorNameInAccessor.symbols
  tests/baselines/reference/constructorNameInAccessor.types
  tests/baselines/reference/constructorNameInGenerator.errors.txt
  tests/baselines/reference/constructorNameInGenerator.js
  tests/baselines/reference/constructorNameInGenerator.symbols
  tests/baselines/reference/constructorNameInGenerator.types
  tests/cases/conformance/salsa/constructorNameInAccessor.ts
  tests/cases/conformance/salsa/constructorNameInGenerator.ts
Labels: For Backlog Bug

#49108 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220514120841224 to main
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#49130 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220516151600014 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#49094 fix(48556) / confused comment in test
  tests/baselines/reference/jsxExcessPropsAndAssignability.errors.txt
  tests/baselines/reference/jsxExcessPropsAndAssignability.js
  tests/baselines/reference/jsxExcessPropsAndAssignability.symbols
  tests/baselines/reference/jsxExcessPropsAndAssignability.types
  tests/cases/compiler/jsxExcessPropsAndAssignability.tsx
Labels: For Uncommitted Bug

#49148 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220517104508064 to main
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#49157 Fix uncalled function check usage detection for && expressions
  src/compiler/checker.ts
  tests/baselines/reference/uncalledFunctionChecksInConditional.errors.txt
  tests/baselines/reference/uncalledFunctionChecksInConditional.js
  tests/baselines/reference/uncalledFunctionChecksInConditional.symbols
  tests/baselines/reference/uncalledFunctionChecksInConditional.types
  tests/cases/compiler/uncalledFunctionChecksInConditional.ts
Labels: Author: Team, For Milestone Bug

#48619 Clean up FAR aggregation
  src/harness/client.ts
  src/harness/harnessLanguageService.ts
  src/server/session.ts
  src/services/findAllReferences.ts
  src/services/services.ts
  src/services/types.ts
  src/services/utilities.ts
  src/testRunner/unittests/tsserver/declarationFileMaps.ts
  src/testRunner/unittests/tsserver/projectReferences.ts
  tests/baselines/reference/isDefinitionAcrossGlobalProjects.baseline.jsonc
  tests/baselines/reference/isDefinitionAcrossModuleProjects.baseline.jsonc
  tests/baselines/reference/referencesToNonPropertyNameStringLiteral.baseline.jsonc
  tests/baselines/reference/tsserver/projectReferences/ancestor-and-project-ref-management.js
  tests/baselines/reference/tsserver/projectReferences/can-successfully-find-references-with-out-option.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-not-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-not-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-not-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/finding-local-reference-doesnt-load-ancestor/sibling-projects.js
  tests/baselines/reference/tsserver/projectReferences/finding-references-in-overlapping-projects.js
  tests/baselines/reference/tsserver/projectReferences/project-is-directly-referenced-by-solution.js
  tests/baselines/reference/tsserver/projectReferences/project-is-indirectly-referenced-by-solution.js
  tests/baselines/reference/tsserver/projectReferences/root-file-is-file-from-referenced-project.js
  tests/baselines/reference/tsserver/projectReferences/solution-with-its-own-files-and-project-found-is-not-solution-but-references-open-file-through-project-reference.js
  tests/baselines/reference/tsserver/projectReferences/solution-with-its-own-files-and-project-is-indirectly-referenced-by-solution.js
  tests/baselines/reference/tsserver/projectReferences/special-handling-of-localness-when-using-arrow-function-as-object-literal-property-types.js
  tests/baselines/reference/tsserver/projectReferences/special-handling-of-localness-when-using-arrow-function-assignment.js
  tests/baselines/reference/tsserver/projectReferences/special-handling-of-localness-when-using-method-of-class-expression.js
  tests/baselines/reference/tsserver/projectReferences/special-handling-of-localness-when-using-object-literal-property.js
  tests/cases/fourslash/server/isDefinitionAcrossGlobalProjects.ts
  tests/cases/fourslash/server/isDefinitionAcrossModuleProjects.ts
Labels: Author: Team, For Uncommitted Bug

#49090 Update CONTRIBUTING.md to mention issue claiming and force pushing
  CONTRIBUTING.md
Labels: Author: Team, For Uncommitted Bug

#49154 Fix path completions for typesVersions
  src/compiler/core.ts
  src/services/stringCompletions.ts
  tests/cases/fourslash/completionForStringLiteralNonrelativeImport13.ts
  tests/cases/fourslash/completionsPaths_pathMapping_topLevel.ts
  tests/cases/fourslash/pathCompletionsTypesVersionsWildcard1.ts
  tests/cases/fourslash/pathCompletionsTypesVersionsWildcard2.ts
  tests/cases/fourslash/pathCompletionsTypesVersionsWildcard3.ts
  tests/cases/fourslash/pathCompletionsTypesVersionsWildcard4.ts
  tests/cases/fourslash/pathCompletionsTypesVersionsWildcard5.ts
  tests/cases/fourslash/pathCompletionsTypesVersionsWildcard6.ts
Labels: Author: Team, For Milestone Bug

#49205 Instantiate original target type in substituteIndexedMappedType
  src/compiler/checker.ts
Labels: Author: Team, For Milestone Bug

#49222 Key validity of import=require in module: node off of module and not target
  src/compiler/transformers/module/esnextAnd2015.ts
  tests/baselines/reference/moduleNodeImportRequireEmit(target=es2016).js
  tests/baselines/reference/moduleNodeImportRequireEmit(target=es2016).symbols
  tests/baselines/reference/moduleNodeImportRequireEmit(target=es2016).types
  tests/baselines/reference/moduleNodeImportRequireEmit(target=es2020).js
  tests/baselines/reference/moduleNodeImportRequireEmit(target=es2020).symbols
  tests/baselines/reference/moduleNodeImportRequireEmit(target=es2020).types
  tests/baselines/reference/moduleNodeImportRequireEmit(target=es5).js
  tests/baselines/reference/moduleNodeImportRequireEmit(target=es5).symbols
  tests/baselines/reference/moduleNodeImportRequireEmit(target=es5).types
  tests/baselines/reference/moduleNodeImportRequireEmit(target=esnext).js
  tests/baselines/reference/moduleNodeImportRequireEmit(target=esnext).symbols
  tests/baselines/reference/moduleNodeImportRequireEmit(target=esnext).types
  tests/cases/compiler/moduleNodeImportRequireEmit.ts
Labels: Author: Team, For Milestone Bug

#49086 Limit type argument inference from binding patterns
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/bindingPatternCannotBeOnlyInferenceSource.errors.txt
  tests/baselines/reference/bindingPatternCannotBeOnlyInferenceSource.js
  tests/baselines/reference/bindingPatternCannotBeOnlyInferenceSource.symbols
  tests/baselines/reference/bindingPatternCannotBeOnlyInferenceSource.types
  tests/baselines/reference/bindingPatternContextualTypeDoesNotCauseWidening.js
  tests/baselines/reference/bindingPatternContextualTypeDoesNotCauseWidening.symbols
  tests/baselines/reference/bindingPatternContextualTypeDoesNotCauseWidening.types
  tests/baselines/reference/declarationEmitDestructuring4.errors.txt
  tests/baselines/reference/declarationEmitDestructuringObjectLiteralPattern.errors.txt
  tests/baselines/reference/declarationEmitDestructuringObjectLiteralPattern1.errors.txt
  tests/baselines/reference/declarationsAndAssignments.errors.txt
  tests/baselines/reference/declarationsAndAssignments.js
  tests/baselines/reference/declarationsAndAssignments.symbols
  tests/baselines/reference/declarationsAndAssignments.types
  tests/baselines/reference/emptyObjectBindingPatternParameter04.errors.txt
  tests/baselines/reference/inferTupleFromBindingPattern.js
  tests/baselines/reference/inferTupleFromBindingPattern.symbols
  tests/baselines/reference/inferTupleFromBindingPattern.types
  tests/baselines/reference/missingAndExcessProperties.errors.txt
  tests/baselines/reference/objectBindingPatternContextuallyTypesArgument.js
  tests/baselines/reference/objectBindingPatternContextuallyTypesArgument.symbols
  tests/baselines/reference/objectBindingPatternContextuallyTypesArgument.types
  tests/cases/compiler/bindingPatternCannotBeOnlyInferenceSource.ts
  tests/cases/compiler/bindingPatternContextualTypeDoesNotCauseWidening.ts
  tests/cases/compiler/inferTupleFromBindingPattern.ts
  tests/cases/compiler/objectBindingPatternContextuallyTypesArgument.ts
  tests/cases/conformance/es6/destructuring/declarationsAndAssignments.ts
Labels: Breaking Change, Author: Team, For Milestone Bug

#49134 fix(49131): IntelliSense/autocomplete does not suggest "type" keyword when declaring a type alias inside a function
  src/harness/fourslashInterfaceImpl.ts
  src/services/completions.ts
  tests/baselines/reference/completionsCommentsClassMembers.baseline
  tests/baselines/reference/completionsCommentsCommentParsing.baseline
  tests/baselines/reference/completionsCommentsFunctionDeclaration.baseline
  tests/baselines/reference/completionsCommentsFunctionExpression.baseline
  tests/cases/fourslash/typeKeywordInFunction.ts
Labels: For Uncommitted Bug

#48529 fix(47562): Add option to suppress type hint if variable name matches type name
  src/compiler/types.ts
  src/server/protocol.ts
  src/services/inlayHints.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/inlayHintsShouldWork67.ts
Labels: For Backlog Bug

#49233 Fix extensions for noDtsResolution in node16/nodenext
  src/compiler/moduleNameResolver.ts
  tests/cases/fourslash/server/goToSource13_nodenext.ts
Labels: Author: Team, For Uncommitted Bug

#49252 Fix crash from inaccurate type guard implementation
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/utilities.ts
  src/services/findAllReferences.ts
  src/services/importTracker.ts
  tests/cases/fourslash/server/goToSource14_unresolvedRequireDestructuring.ts
Labels: Author: Team, For Uncommitted Bug

#49268 moduleDetection: auto makes cjs/cts files parse as modules, and ...
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/utilities.ts
  tests/baselines/reference/moduleResolutionWithoutExtension8.js
  tests/baselines/reference/nodeModulesAllowJsExportAssignment(module=node16).js
  tests/baselines/reference/nodeModulesAllowJsExportAssignment(module=nodenext).js
  tests/baselines/reference/nodeModulesAllowJsExportlessJsModuleDetectionAuto(module=node16).js
  tests/baselines/reference/nodeModulesAllowJsExportlessJsModuleDetectionAuto(module=node16).symbols
  tests/baselines/reference/nodeModulesAllowJsExportlessJsModuleDetectionAuto(module=node16).types
  tests/baselines/reference/nodeModulesAllowJsExportlessJsModuleDetectionAuto(module=nodenext).js
  tests/baselines/reference/nodeModulesAllowJsExportlessJsModuleDetectionAuto(module=nodenext).symbols
  tests/baselines/reference/nodeModulesAllowJsExportlessJsModuleDetectionAuto(module=nodenext).types
  tests/baselines/reference/tripleSlashTypesReferenceWithMissingExports(module=node16).js
  tests/baselines/reference/tripleSlashTypesReferenceWithMissingExports(module=nodenext).js
  tests/cases/conformance/node/allowJs/nodeModulesAllowJsExportlessJsModuleDetectionAuto.ts
Labels: Author: Team, For Milestone Bug

#49267 Port #48978 forward to the revised FAR code
  src/server/session.ts
  tests/baselines/reference/referencesInEmptyFileWithMultipleProjects.baseline.jsonc
  tests/baselines/reference/referencesInStringLiteralValueWithMultipleProjects.baseline.jsonc
  tests/cases/fourslash/server/referencesInEmptyFileWithMultipleProjects.ts
  tests/cases/fourslash/server/referencesInStringLiteralValueWithMultipleProjects.ts
Labels: Author: Team, For Uncommitted Bug

#49168 fix(30003): formatter deletes comment after trailing comma (again)
  src/services/formatting/formatting.ts
  tests/cases/fourslash/formatNoSpaceBeforeCloseBrace3.ts
  tests/cases/fourslash/formatNoSpaceBeforeCloseBrace4.ts
  tests/cases/fourslash/formatNoSpaceBeforeCloseBrace5.ts
  tests/cases/fourslash/formatNoSpaceBeforeCloseBrace6.ts
Labels: For Backlog Bug

#48094 More specific inference for constrained 'infer' types in template literal types
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/templateLiteralTypes4.errors.txt
  tests/baselines/reference/templateLiteralTypes4.js
  tests/baselines/reference/templateLiteralTypes4.symbols
  tests/baselines/reference/templateLiteralTypes4.types
  tests/cases/conformance/types/literal/templateLiteralTypes4.ts
Labels: Author: Team, For Uncommitted Bug

#49119 Improve intersection reduction and CFA for truthy, equality, and typeof checks
  src/compiler/checker.ts
  src/compiler/core.ts
  src/compiler/diagnosticMessages.json
  src/compiler/types.ts
  src/lib/es5.d.ts
  tests/baselines/reference/assertionTypePredicates1.types
  tests/baselines/reference/conditionalTypes1.errors.txt
  tests/baselines/reference/conditionalTypes1.types
  tests/baselines/reference/conditionalTypes2.errors.txt
  tests/baselines/reference/controlFlowGenericTypes.types
  tests/baselines/reference/controlFlowTruthiness.types
  tests/baselines/reference/controlFlowTypeofObject.types
  tests/baselines/reference/findAllRefsRootSymbols.baseline.jsonc
  tests/baselines/reference/genericUnboundedTypeParamAssignability.errors.txt
  tests/baselines/reference/inDoesNotOperateOnPrimitiveTypes.errors.txt
  tests/baselines/reference/inDoesNotOperateOnPrimitiveTypes.types
  tests/baselines/reference/intersectionReduction.types
  tests/baselines/reference/intersectionWithUnionConstraint.errors.txt
  tests/baselines/reference/intersectionWithUnionConstraint.types
  tests/baselines/reference/intersectionsAndEmptyObjects.types
  tests/baselines/reference/keyofAndIndexedAccess.errors.txt
  tests/baselines/reference/mappedTypeAsClauseRelationships.errors.txt
  tests/baselines/reference/mappedTypes4.types
  tests/baselines/reference/mappedTypes6.errors.txt
  tests/baselines/reference/mappedTypesAndObjects.errors.txt
  tests/baselines/reference/narrowByEquality.types
  tests/baselines/reference/narrowingByTypeofInSwitch.types
  tests/baselines/reference/narrowingTruthyObject.types
  tests/baselines/reference/narrowingTypeofFunction.types
  tests/baselines/reference/nonPrimitiveUnionIntersection.errors.txt
  tests/baselines/reference/nonPrimitiveUnionIntersection.types
  tests/baselines/reference/propTypeValidatorInference.types
  tests/baselines/reference/recursiveTupleTypeInference.errors.txt
  tests/baselines/reference/spreadObjectOrFalsy.js
  tests/baselines/reference/spreadObjectOrFalsy.types
  tests/baselines/reference/strictNullNotNullIndexTypeNoLib.errors.txt
  tests/baselines/reference/strictNullNotNullIndexTypeNoLib.symbols
  tests/baselines/reference/strictNullNotNullIndexTypeNoLib.types
  tests/baselines/reference/strictOptionalProperties1.types
  tests/baselines/reference/templateLiteralIntersection.types
  tests/baselines/reference/tsxNotUsingApparentTypeOfSFC.errors.txt
  tests/baselines/reference/typeGuardTypeOfUndefined.types
  tests/baselines/reference/typeVariableTypeGuards.types
  tests/baselines/reference/unionWithIndexSignature.types
  tests/baselines/reference/unknownControlFlow.errors.txt
  tests/baselines/reference/unknownControlFlow.js
  tests/baselines/reference/unknownControlFlow.symbols
  tests/baselines/reference/unknownControlFlow.types
  tests/baselines/reference/unknownType1.errors.txt
  tests/baselines/reference/unknownType2.types
  tests/baselines/reference/voidUndefinedReduction.types
  tests/cases/conformance/types/unknown/unknownControlFlow.ts
  tests/cases/fourslash/completionPreferredSuggestions1.ts
Labels: Breaking Change, Author: Team, For Milestone Bug, For Backlog Bug

#49300 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220529111623036 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#49008 fixes #48630 array binding pattern with only OmittedExpressions does not check RHS of for-of loop
  src/compiler/checker.ts
  test.js
  test.ts
  tests/baselines/reference/omittedExpressionForOfLoop.errors.txt
  tests/baselines/reference/omittedExpressionForOfLoop.js
  tests/baselines/reference/omittedExpressionForOfLoop.symbols
  tests/baselines/reference/omittedExpressionForOfLoop.types
  tests/cases/compiler/omittedExpressionForOfLoop.ts
Labels: For Backlog Bug

#49327 Fix index fallback of CJS package from ESM-mode import when `main` is present but does not resolve
  src/compiler/moduleNameResolver.ts
  tests/baselines/reference/nodeNextImportModeImplicitIndexResolution2.errors.txt
  tests/baselines/reference/nodeNextImportModeImplicitIndexResolution2.js
  tests/baselines/reference/nodeNextImportModeImplicitIndexResolution2.symbols
  tests/baselines/reference/nodeNextImportModeImplicitIndexResolution2.types
  tests/cases/compiler/nodeNextImportModeImplicitIndexResolution2.ts
Labels: Author: Team, For Uncommitted Bug

#41994 Allow accessors to override non-class or abstract properties
  src/compiler/checker.ts
  tests/baselines/reference/accessorsOverrideProperty8.js
  tests/baselines/reference/accessorsOverrideProperty8.symbols
  tests/baselines/reference/accessorsOverrideProperty8.types
  tests/baselines/reference/accessorsOverrideProperty9.js
  tests/baselines/reference/accessorsOverrideProperty9.symbols
  tests/baselines/reference/accessorsOverrideProperty9.types
  tests/cases/conformance/classes/propertyMemberDeclarations/accessorsOverrideProperty8.ts
  tests/cases/conformance/classes/propertyMemberDeclarations/accessorsOverrideProperty9.ts
Labels: Author: Team, For Milestone Bug

#49179 fix(49178): Inlay hints doesn't appear when calling function after extends keyword in Typescript files
  src/services/inlayHints.ts
  tests/cases/fourslash/inlayHintsShouldWork68.ts
Labels: For Uncommitted Bug

#49221 Issue serialization error when attempting to serialize a late-bound name from a mapped type
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitMappedTypeTemplateTypeofSymbol.errors.txt
  tests/baselines/reference/declarationEmitMappedTypeTemplateTypeofSymbol.js
  tests/baselines/reference/declarationEmitMappedTypeTemplateTypeofSymbol.symbols
  tests/baselines/reference/declarationEmitMappedTypeTemplateTypeofSymbol.types
  tests/cases/compiler/declarationEmitMappedTypeTemplateTypeofSymbol.ts
Labels: Author: Team, For Milestone Bug

#49165 fix(49151): formatter wrongly indent '>' after type parameters/arguments
  src/services/formatting/formatting.ts
  tests/cases/fourslash/genericsFormattingMultiline.ts
Labels: For Uncommitted Bug

#46357 Fix46246
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/errorLocationForInterfaceExtension.errors.txt
  tests/baselines/reference/interfacedeclWithIndexerErrors.errors.txt
  tests/baselines/reference/interfacedeclWithIndexerErrors.js
  tests/baselines/reference/interfacedeclWithIndexerErrors.symbols
  tests/baselines/reference/interfacedeclWithIndexerErrors.types
  tests/cases/compiler/interfacedeclWithIndexerErrors.ts
Labels: For Backlog Bug
