Repository microsoft/TypeScript, pull requests merged in 2022-02, with the labels that each got.

#47677 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220201001451528 to main
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#47681 Fix captured let/const in 'for' condition or incrementer
  src/compiler/transformers/es2015.ts
  tests/baselines/reference/capturedLetConstInLoop1.js
Labels: Author: Team, For Milestone Bug

#47684 Fix inlay hint crash for jsdoc function type syntax
  src/compiler/checker.ts
  tests/cases/fourslash/inlayHintsCrash1.ts
Labels: Author: Team, For Milestone Bug

#47095 Transform param patterns/initializers after object rest
  src/compiler/transformers/es2018.ts
  tests/baselines/reference/functionParameterObjectRestAndInitializers.js
  tests/cases/conformance/functions/functionParameterObjectRestAndInitializers.ts
Labels: Author: Team, For Milestone Bug

#47680 Fix captured const in downlevel for-await
  src/compiler/transformers/es2018.ts
  tests/baselines/reference/forAwaitPerIterationBindingDownlevel.js
  tests/cases/conformance/statements/for-await-ofStatements/forAwaitPerIterationBindingDownlevel.ts
Labels: Author: Team, For Milestone Bug

#47583 fix typefacts of intersection
  src/compiler/checker.ts
  tests/baselines/reference/narrowingTypeofFunction.js
  tests/baselines/reference/narrowingTypeofFunction.symbols
  tests/baselines/reference/narrowingTypeofFunction.types
  tests/baselines/reference/narrowingTypeofObject.js
  tests/baselines/reference/narrowingTypeofObject.symbols
  tests/baselines/reference/narrowingTypeofObject.types
  tests/cases/compiler/narrowingTypeofFunction.ts
  tests/cases/compiler/narrowingTypeofObject.ts
Labels: Author: Team, For Uncommitted Bug

#47156 Correctly check computed property names in type-space get/set accessors
  src/compiler/checker.ts
  tests/baselines/reference/noMappedGetSet.errors.txt
  tests/baselines/reference/noMappedGetSet.js
  tests/baselines/reference/noMappedGetSet.symbols
  tests/baselines/reference/noMappedGetSet.types
  tests/cases/compiler/noMappedGetSet.ts
Labels: Author: Team, For Milestone Bug

#47687 Use node moduleResolution everywhere
  src/testRunner/tsconfig.json
  src/tsconfig-base.json
Labels: Author: Team, For Uncommitted Bug

#47085 support quickinfo and go-to-definition on `typeof this`
  src/compiler/checker.ts
  src/services/symbolDisplay.ts
  tests/baselines/reference/initializerReferencingConstructorLocals.symbols
  tests/baselines/reference/initializerReferencingConstructorLocals.types
  tests/baselines/reference/initializerReferencingConstructorParameters.symbols
  tests/baselines/reference/initializerReferencingConstructorParameters.types
  tests/baselines/reference/quickInfoOnThis5.baseline
  tests/baselines/reference/typeofThis.symbols
  tests/baselines/reference/typeofThis.types
  tests/cases/fourslash/goToDefinitionTypeofThis.ts
  tests/cases/fourslash/quickInfoOnThis5.ts
Labels: For Backlog Bug

#47676 fix(47670): "Organize imports" should remove import any alias that are aliased as the same name as the export
  src/services/organizeImports.ts
  tests/cases/fourslash/organizeImports8.ts
  tests/cases/fourslash/organizeImports9.ts
Labels: For Backlog Bug

#47705 Fix @link https:// formatting
  src/compiler/utilitiesPublic.ts
  src/services/utilities.ts
  tests/baselines/reference/linkTagEmit1.js
  tests/baselines/reference/linkTagEmit1.symbols
  tests/baselines/reference/linkTagEmit1.types
  tests/baselines/reference/quickInfoForJSDocWithUnresolvedHttpLinks.baseline
  tests/cases/conformance/jsdoc/linkTagEmit1.ts
  tests/cases/fourslash/quickInfoForJSDocWithUnresolvedHttpLinks.ts
Labels: Author: Team, For Milestone Bug

#46945 "Convert parameters to destructured object": enable for functions with just one parameter
  src/services/refactors/convertParamsToDestructuredObject.ts
  tests/cases/fourslash/refactorConvertParamsToDestructuredObject_arrowFunctionWithSingleParameter.ts
Labels: For Backlog Bug

#46924 i18n:Inappropriate localization
  lib/zh-cn/diagnosticMessages.generated.json
Labels: For Uncommitted Bug

#46886 feat(27601): Copy JSDoc from type when destructing arguments
  src/services/symbolDisplay.ts
  tests/baselines/reference/quickInfoForObjectBindingElementName03.baseline
  tests/baselines/reference/quickInfoForObjectBindingElementName04.baseline
  tests/baselines/reference/quickInfoForObjectBindingElementName05.baseline
  tests/cases/fourslash/quickInfoForObjectBindingElementName03.ts
  tests/cases/fourslash/quickInfoForObjectBindingElementName04.ts
  tests/cases/fourslash/quickInfoForObjectBindingElementName05.ts
Labels: For Backlog Bug

#47678 Auto-import perf: Do symbol name/flags filtering before cache rehydration
  src/services/completions.ts
  src/services/exportInfoMap.ts
  src/services/utilities.ts
  src/testRunner/unittests/tsserver/exportMapCache.ts
Labels: Author: Team, For Uncommitted Bug

#46970 fix(45917): String literal completions missing when last argument of a call is followed by a comma
  src/services/signatureHelp.ts
  tests/cases/fourslash/completionForStringLiteral16.ts
Labels: For Backlog Bug

#47707 Use 'static {}' for static fields when available and useDefineForClassFields is false
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/transformers/classFields.ts
  tests/baselines/reference/computedPropertyName.js
  tests/baselines/reference/privateNameErrorsOnNotUseDefineForClassFieldsInEsNext(target=es2020).symbols
  tests/baselines/reference/privateNameErrorsOnNotUseDefineForClassFieldsInEsNext(target=es2020).types
  tests/baselines/reference/privateNameErrorsOnNotUseDefineForClassFieldsInEsNext(target=esnext).errors.txt
  tests/baselines/reference/privateNameErrorsOnNotUseDefineForClassFieldsInEsNext(target=esnext).symbols
  tests/baselines/reference/privateNameErrorsOnNotUseDefineForClassFieldsInEsNext(target=esnext).types
  tests/baselines/reference/privateNameFieldsESNext(target=es2022).js
  tests/baselines/reference/privateNameFieldsESNext(target=esnext).errors.txt
  tests/baselines/reference/privateNameFieldsESNext(target=esnext).js
  tests/baselines/reference/privateNameInInExpressionTransform(target=esnext).errors.txt
  tests/baselines/reference/privateNameStaticAndStaticInitializer(target=es2022).js
  tests/baselines/reference/privateNameStaticAndStaticInitializer(target=esnext).errors.txt
  tests/baselines/reference/privateNameStaticAndStaticInitializer(target=esnext).js
  tests/baselines/reference/privateNameStaticFieldDestructuredBinding(target=es2022).js
  tests/baselines/reference/privateNameStaticFieldDestructuredBinding(target=esnext).errors.txt
  tests/baselines/reference/privateNameStaticFieldDestructuredBinding(target=esnext).js
  tests/baselines/reference/privateNameStaticFieldInitializer(target=es2022).js
  tests/baselines/reference/privateNameStaticFieldInitializer(target=esnext).errors.txt
  tests/baselines/reference/privateNameStaticFieldInitializer(target=esnext).js
  tests/baselines/reference/privateNameWhenNotUseDefineForClassFieldsInEsNext(target=es2020).js
  tests/baselines/reference/privateNameWhenNotUseDefineForClassFieldsInEsNext(target=es2020).symbols
  tests/baselines/reference/privateNameWhenNotUseDefineForClassFieldsInEsNext(target=es2020).types
  tests/baselines/reference/privateNameWhenNotUseDefineForClassFieldsInEsNext(target=esnext).js
  tests/baselines/reference/privateNameWhenNotUseDefineForClassFieldsInEsNext(target=esnext).symbols
  tests/baselines/reference/privateNameWhenNotUseDefineForClassFieldsInEsNext(target=esnext).types
  tests/baselines/reference/thisAndSuperInStaticMembers2(target=es2022).js
  tests/baselines/reference/thisAndSuperInStaticMembers2(target=esnext).js
  tests/baselines/reference/transformApi/transformsCorrectly.rewrittenNamespaceFollowingClass.js
  tests/baselines/reference/typeOfThisInStaticMembers10(target=es2022).js
  tests/baselines/reference/typeOfThisInStaticMembers10(target=esnext).js
  tests/baselines/reference/typeOfThisInStaticMembers12(target=es2022).js
  tests/baselines/reference/typeOfThisInStaticMembers12(target=esnext).js
  tests/baselines/reference/typeOfThisInStaticMembers3(target=es2022).js
  tests/baselines/reference/typeOfThisInStaticMembers3(target=esnext).js
  tests/baselines/reference/uniqueSymbols.js
  tests/baselines/reference/uniqueSymbolsDeclarations.js
  tests/baselines/reference/uniqueSymbolsDeclarationsInJs.js
  tests/baselines/reference/unusedPrivateStaticMembers.js
  tests/cases/conformance/classes/members/privateNames/privateNameWhenNotUseDefineForClassFieldsInEsNext.ts
Labels: Author: Team, For Milestone Bug

#47567 fix(32941): Template tag constraints not displayed in vscode intellisense
  src/services/jsDoc.ts
  tests/baselines/reference/jsdocReturnsTag.baseline
  tests/baselines/reference/quickInfoJsDocTags10.baseline
  tests/baselines/reference/quickInfoJsDocTags11.baseline
  tests/baselines/reference/quickInfoJsDocTags7.baseline
  tests/baselines/reference/quickInfoJsDocTags8.baseline
  tests/baselines/reference/quickInfoJsDocTags9.baseline
  tests/baselines/reference/signatureHelpTypeArguments2.baseline
  tests/cases/fourslash/quickInfoJsDocTags10.ts
  tests/cases/fourslash/quickInfoJsDocTags11.ts
  tests/cases/fourslash/quickInfoJsDocTags7.ts
  tests/cases/fourslash/quickInfoJsDocTags8.ts
  tests/cases/fourslash/quickInfoJsDocTags9.ts
Labels: For Uncommitted Bug

#47744 Refactor named imports to default instead of namespace when esModuleInterop is on and module is an `export=`
  src/compiler/core.ts
  src/compiler/diagnosticMessages.json
  src/services/refactors/convertImport.ts
  tests/cases/fourslash/refactorConvertImport_namedToDefault1.ts
Labels: Author: Team, For Milestone Bug

#47761 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220207104844820 to main
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#47784 fix(47782): Crash in extract function due to non-null assertion
  src/services/refactors/extractSymbol.ts
  tests/cases/fourslash/extractSuperOutsideClass.ts
Labels: For Milestone Bug

#47786 fix(47783): Crash after case keyword outside of switch statement
  src/services/completions.ts
  tests/cases/fourslash/completionAtCaseClause.ts
Labels: For Milestone Bug

#47791 Fix substitution types of indexed access types of substitution types
  src/compiler/checker.ts
  tests/baselines/reference/substitutionTypeForIndexedAccessType1.js
  tests/baselines/reference/substitutionTypeForIndexedAccessType1.symbols
  tests/baselines/reference/substitutionTypeForIndexedAccessType1.types
  tests/baselines/reference/substitutionTypeForIndexedAccessType2.js
  tests/baselines/reference/substitutionTypeForIndexedAccessType2.symbols
  tests/baselines/reference/substitutionTypeForIndexedAccessType2.types
  tests/cases/compiler/substitutionTypeForIndexedAccessType1.ts
  tests/cases/compiler/substitutionTypeForIndexedAccessType2.ts
Labels: Author: Team, For Milestone Bug

#47781 Log per-project FAR and update baselines
  src/server/session.ts
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-not-loaded-and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-not-loaded-and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-not-loaded-and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-not-loaded-and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-not-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-not-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-not-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-not-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/finding-local-reference-doesnt-load-ancestor/sibling-projects.js
  tests/baselines/reference/tsserver/projectReferences/project-is-directly-referenced-by-solution.js
  tests/baselines/reference/tsserver/projectReferences/project-is-indirectly-referenced-by-solution.js
  tests/baselines/reference/tsserver/projectReferences/root-file-is-file-from-referenced-project-and-using-declaration-maps.js
  tests/baselines/reference/tsserver/projectReferences/root-file-is-file-from-referenced-project.js
  tests/baselines/reference/tsserver/projectReferences/solution-with-its-own-files-and-project-found-is-not-solution-but-references-open-file-through-project-reference.js
  tests/baselines/reference/tsserver/projectReferences/solution-with-its-own-files-and-project-is-indirectly-referenced-by-solution.js
  tests/baselines/reference/tsserver/projectReferences/special-handling-of-localness-when-using-arrow-function-as-object-literal-property-types.js
  tests/baselines/reference/tsserver/projectReferences/special-handling-of-localness-when-using-arrow-function-as-object-literal-property.js
  tests/baselines/reference/tsserver/projectReferences/special-handling-of-localness-when-using-arrow-function-assignment.js
  tests/baselines/reference/tsserver/projectReferences/special-handling-of-localness-when-using-method-of-class-expression.js
  tests/baselines/reference/tsserver/projectReferences/special-handling-of-localness-when-using-object-literal-property.js
  tests/baselines/reference/tsserver/projectReferences/when-files-from-two-projects-are-open-and-one-project-references.js
  tests/baselines/reference/tsserver/projectReferences/with-disableSolutionSearching-solution-and-siblings-are-not-loaded.js
Labels: Author: Team, For Uncommitted Bug

#47785 Trace document registry operations
  src/services/documentRegistry.ts
Labels: Author: Team, For Uncommitted Bug

#47801 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220208112251731 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#47798 fix(47788): Invalid cast for code fix on index signatures
  src/services/codefixes/convertToMappedObjectType.ts
  tests/cases/fourslash/codeFixConvertToMappedObjectType13.ts
Labels: For Uncommitted Bug

#47674 Compute writeType from set accessors for union and intersection properties
  src/compiler/checker.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  tests/baselines/reference/divergentAccessorsTypes3.js
  tests/baselines/reference/divergentAccessorsTypes3.symbols
  tests/baselines/reference/divergentAccessorsTypes3.types
  tests/baselines/reference/divergentAccessorsTypes4.errors.txt
  tests/baselines/reference/divergentAccessorsTypes4.js
  tests/baselines/reference/divergentAccessorsTypes4.symbols
  tests/baselines/reference/divergentAccessorsTypes4.types
  tests/baselines/reference/divergentAccessorsTypes5.errors.txt
  tests/baselines/reference/divergentAccessorsTypes5.js
  tests/baselines/reference/divergentAccessorsTypes5.symbols
  tests/baselines/reference/divergentAccessorsTypes5.types
  tests/cases/compiler/divergentAccessorsTypes3.ts
  tests/cases/compiler/divergentAccessorsTypes4.ts
  tests/cases/compiler/divergentAccessorsTypes5.ts
Labels: Author: Team, For Milestone Bug

#47797 fix(47787): Incorrect assertion for "bad syntax kind" in unused parameter codefix
  src/services/codefixes/fixUnusedIdentifier.ts
  src/services/formatting/smartIndenter.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_parameterInGetAccessor.ts
Labels: For Uncommitted Bug

#47818 Avoid pulling on setter type when only getter type is needed to break circularity
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypeCircularReferenceInAccessor.js
  tests/baselines/reference/mappedTypeCircularReferenceInAccessor.symbols
  tests/baselines/reference/mappedTypeCircularReferenceInAccessor.types
  tests/cases/compiler/mappedTypeCircularReferenceInAccessor.ts
Labels: Author: Team, For Milestone Bug

#47742 Constructor function methods:Add two missing tag lookups
  src/compiler/checker.ts
  src/compiler/utilities.ts
  tests/baselines/reference/constructorFunctionMethodTypeParameters.symbols
  tests/baselines/reference/constructorFunctionMethodTypeParameters.types
  tests/cases/conformance/salsa/constructorFunctionMethodTypeParameters.ts
Labels: Author: Team, For Milestone Bug

#47337 Fix destructuring and narrowing interaction
  src/compiler/checker.ts
  tests/baselines/reference/genericObjectSpreadResultInSwitch.types
  tests/baselines/reference/narrowingDestructuring.js
  tests/baselines/reference/narrowingDestructuring.symbols
  tests/baselines/reference/narrowingDestructuring.types
  tests/baselines/reference/restInvalidArgumentType.types
  tests/cases/compiler/narrowingDestructuring.ts
Labels: Author: Team, For Milestone Bug

#47087 fix(47076):Fix error term of declaration in modules
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/program.ts
  tests/baselines/reference/importDeclarationInModuleDeclaration2.errors.txt
  tests/baselines/reference/importDeclarationInModuleDeclaration2.symbols
  tests/baselines/reference/importDeclarationInModuleDeclaration2.types
  tests/baselines/reference/labeledStatementWithLabel.errors.txt
  tests/baselines/reference/labeledStatementWithLabel_es2015.errors.txt
  tests/baselines/reference/labeledStatementWithLabel_strict.errors.txt
  tests/baselines/reference/moduleElementsInWrongContext.errors.txt
  tests/baselines/reference/moduleElementsInWrongContext2.errors.txt
  tests/baselines/reference/moduleElementsInWrongContext3.errors.txt
  tests/baselines/reference/plainJSGrammarErrors.errors.txt
  tests/cases/compiler/importDeclarationInModuleDeclaration2.ts
Labels: For Backlog Bug

#47825 mergeSymbol in checker:Remove block-scoped duplicate declaration errors in plain JS
  src/compiler/checker.ts
  src/compiler/program.ts
  src/compiler/utilities.ts
  tests/baselines/reference/plainJSReservedStrict.errors.txt
Labels: Author: Team, For Uncommitted Bug

#46688 fix(46611): Typescript may not recognize jsdoc @type on class method
  src/compiler/checker.ts
  tests/baselines/reference/checkJsdocTypeTag7.symbols
  tests/baselines/reference/checkJsdocTypeTag7.types
  tests/cases/conformance/jsdoc/checkJsdocTypeTag7.ts
Labels: For Backlog Bug

#47838 Add missing isolatedModules error for `export import`
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/isolatedModulesExportImportUninstantiatedNamespace.errors.txt
  tests/baselines/reference/isolatedModulesExportImportUninstantiatedNamespace.js
  tests/baselines/reference/isolatedModulesReExportType.errors.txt
  tests/cases/compiler/isolatedModulesExportImportUninstantiatedNamespace.ts
Labels: Author: Team, For Milestone Bug

#47843 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220211110032967 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#47836 Enable path completions for node12/nodenext
  src/services/stringCompletions.ts
  tests/baselines/reference/nodeNextPathCompletions.baseline
  tests/cases/fourslash/server/nodeNextPathCompletions.ts
Labels: Author: Team, For Milestone Bug

#47247 fix(46803): unused React import doesn't get removed running organize imports with new react jsx transform
  src/services/codefixes/importFixes.ts
  src/services/organizeImports.ts
  src/services/utilities.ts
  tests/baselines/reference/organizeImports/JsxFactoryUsedJs.ts
  tests/cases/fourslash/organizeImportsReactJsx.ts
  tests/cases/fourslash/organizeImportsReactJsxDev.ts
Labels: For Backlog Bug

#47850 Correctly resolve imports ending with "." and ".."
  src/compiler/moduleNameResolver.ts
  src/compiler/path.ts
  tests/baselines/reference/importFromDot.errors.txt
  tests/baselines/reference/importFromDot.js
  tests/baselines/reference/importFromDot.symbols
  tests/baselines/reference/importFromDot.types
  tests/baselines/reference/importWithTrailingSlash.errors.txt
  tests/baselines/reference/importWithTrailingSlash.symbols
  tests/baselines/reference/importWithTrailingSlash.trace.json
  tests/baselines/reference/importWithTrailingSlash.types
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-disabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-not-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-not-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-not-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-present.js
  tests/cases/conformance/moduleResolution/importFromDot.ts
Labels: Author: Team, For Milestone Bug

#47835 Consider a symbol visible for declaration emit when it is the target of an ambient module's export=
  src/compiler/checker.ts
  tests/baselines/reference/amdLikeInputDeclarationEmit.js
  tests/baselines/reference/amdLikeInputDeclarationEmit.symbols
  tests/baselines/reference/amdLikeInputDeclarationEmit.types
  tests/baselines/reference/importDeclFromTypeNodeInJsSource.types
  tests/baselines/reference/importTypeAmbient.types
  tests/baselines/reference/incompatibleExports1.types
  tests/cases/compiler/amdLikeInputDeclarationEmit.ts
Labels: Author: Team, For Milestone Bug

#47069 Ensure subtype relation ordering for readonly properties
  src/compiler/checker.ts
  src/services/textChanges.ts
  tests/baselines/reference/readonlyPropertySubtypeRelationDirected.errors.txt
  tests/baselines/reference/readonlyPropertySubtypeRelationDirected.js
  tests/baselines/reference/readonlyPropertySubtypeRelationDirected.symbols
  tests/baselines/reference/readonlyPropertySubtypeRelationDirected.types
  tests/cases/compiler/readonlyPropertySubtypeRelationDirected.ts
Labels: Author: Team, For Milestone Bug

#47816 Ensure empty array literal is assignable to never[]
  src/compiler/checker.ts
  tests/baselines/reference/neverTypeErrors1.errors.txt
  tests/baselines/reference/neverTypeErrors1.js
  tests/baselines/reference/neverTypeErrors1.symbols
  tests/baselines/reference/neverTypeErrors1.types
  tests/baselines/reference/neverTypeErrors2.errors.txt
  tests/baselines/reference/neverTypeErrors2.js
  tests/baselines/reference/neverTypeErrors2.symbols
  tests/baselines/reference/neverTypeErrors2.types
  tests/cases/conformance/types/never/neverTypeErrors1.ts
  tests/cases/conformance/types/never/neverTypeErrors2.ts
Labels: Author: Team, For Milestone Bug

#47894 [GH Actions] Implicitly use AUTHORIZATION header instead of PAT-in-URL
  .github/workflows/ensure-related-repos-run-crons.yml
Labels: Author: Team, For Uncommitted Bug

#47893 Allow extensionless `main`s for cjs mode packages even from an esm import
  src/compiler/moduleNameResolver.ts
  tests/baselines/reference/nodeNextEsmImportsOfPackagesWithExtensionlessMains.js
  tests/baselines/reference/nodeNextEsmImportsOfPackagesWithExtensionlessMains.symbols
  tests/baselines/reference/nodeNextEsmImportsOfPackagesWithExtensionlessMains.types
  tests/cases/compiler/nodeNextEsmImportsOfPackagesWithExtensionlessMains.ts
Labels: Author: Team, For Milestone Bug

#47738 Eliminate redundant or meaningless elaborations in type relations
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/types.ts
  tests/baselines/reference/bigintWithLib.errors.txt
  tests/baselines/reference/checkJsdocTypeTagOnObjectProperty2.errors.txt
  tests/baselines/reference/checkJsxChildrenProperty4.errors.txt
  tests/baselines/reference/circularlyConstrainedMappedTypeContainingConditionalNoInfiniteInstantiationDepth.errors.txt
  tests/baselines/reference/conditionalTypes2.errors.txt
  tests/baselines/reference/constructBigint.errors.txt
  tests/baselines/reference/decoratorOnClassMethod8.errors.txt
  tests/baselines/reference/destructuringObjectBindingPatternAndAssignment3.errors.txt
  tests/baselines/reference/divergentAccessorsTypes2.errors.txt
  tests/baselines/reference/inferTypes1.errors.txt
  tests/baselines/reference/interfaceExtendsObjectIntersectionErrors.errors.txt
  tests/baselines/reference/intersectionAndUnionTypes.errors.txt
  tests/baselines/reference/intersectionPropertyCheck.errors.txt
  tests/baselines/reference/intersectionWithUnionConstraint.errors.txt
  tests/baselines/reference/jsxIntrinsicElementsTypeArgumentErrors.errors.txt
  tests/baselines/reference/mappedTypeErrors.errors.txt
  tests/baselines/reference/mappedTypeErrors2.errors.txt
  tests/baselines/reference/mappedTypeRelationships.errors.txt
  tests/baselines/reference/nonPrimitiveAndTypeVariables.errors.txt
  tests/baselines/reference/objectCreate-errors.errors.txt
  tests/baselines/reference/objectLiteralNormalization.errors.txt
  tests/baselines/reference/potentiallyUncalledDecorators.errors.txt
  tests/baselines/reference/reactReduxLikeDeferredInferenceAllowsAssignment.errors.txt
  tests/baselines/reference/tsxLibraryManagedAttributes.errors.txt
  tests/baselines/reference/typeFromJSInitializer.errors.txt
  tests/baselines/reference/typeParameterDiamond3.errors.txt
  tests/baselines/reference/types.asyncGenerators.es2018.2.errors.txt
  tests/baselines/reference/unionTypesAssignability.errors.txt
  tests/baselines/reference/unknownType1.errors.txt
  tests/baselines/reference/variadicTuples1.errors.txt
Labels: Author: Team, For Milestone Bug

#47790 Fix 47746 - Missing properties quickfix does not handle generic parameters
  tests/cases/fourslash/codeFixAddMissingProperties17.ts
  tests/cases/fourslash/codeFixAddMissingProperties18.ts
Labels: For Backlog Bug

#47909 Fix incorrect rest element type inside contextually typed parameter
  src/compiler/checker.ts
  tests/baselines/reference/narrowingRestGenericCall.js
  tests/baselines/reference/narrowingRestGenericCall.symbols
  tests/baselines/reference/narrowingRestGenericCall.types
  tests/cases/compiler/narrowingRestGenericCall.ts
Labels: Author: Team, For Milestone Bug

#47741 fix(47713): @link comments don't work above switch cases
  src/compiler/parser.ts
  src/compiler/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/quickInfoLink4.baseline
  tests/cases/fourslash/quickInfoLink4.ts
Labels: For Backlog Bug

#47750 Fix inference for generic-typed constructor parameter when no explicit constructor is present
  src/compiler/checker.ts
  tests/baselines/reference/inferringReturnTypeFromConstructSignatureGeneric.js
  tests/baselines/reference/inferringReturnTypeFromConstructSignatureGeneric.symbols
  tests/baselines/reference/inferringReturnTypeFromConstructSignatureGeneric.types
  tests/cases/compiler/inferringReturnTypeFromConstructSignatureGeneric.ts
Labels: For Backlog Bug

#47740 Add support for formatRange to Intl.DateTimeFormat
  src/lib/esnext.intl.d.ts
Labels: For Backlog Bug

#47729 Merge `InlayHintOptions` into `UserPreferences`
  src/compiler/types.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/harness/harnessLanguageService.ts
  src/server/protocol.ts
  src/services/inlayHints.ts
  src/services/services.ts
  src/services/shims.ts
  src/services/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#47717 mark length of readonly tuple as readonly
  src/compiler/checker.ts
  tests/baselines/reference/tupleTypes.errors.txt
  tests/baselines/reference/tupleTypes.js
  tests/baselines/reference/tupleTypes.symbols
  tests/baselines/reference/tupleTypes.types
  tests/cases/compiler/tupleTypes.ts
Labels: For Backlog Bug

#47720 Make Intl.Locale.prototype baseName & language properties required
  src/lib/es2020.intl.d.ts
Labels: For Backlog Bug

#47696 feat(47595): Inability to use typeof on an ES private property
  src/compiler/parser.ts
  tests/baselines/reference/privateNameInTypeQuery.errors.txt
  tests/baselines/reference/privateNameInTypeQuery.js
  tests/baselines/reference/privateNameInTypeQuery.symbols
  tests/baselines/reference/privateNameInTypeQuery.types
  tests/cases/conformance/classes/members/privateNames/privateNameInTypeQuery.ts
Labels: For Backlog Bug

#47400 fix(47256): @deprecated does not work on index signatures
  src/compiler/checker.ts
  tests/cases/fourslash/jsdocDeprecated_suggestion17.ts
Labels: For Backlog Bug

#47403 fix(47261): TS error when JSDoc @see tag starts with an inline @linkcode tag
  src/compiler/parser.ts
  tests/baselines/reference/seeTag4.js
  tests/baselines/reference/seeTag4.symbols
  tests/baselines/reference/seeTag4.types
  tests/cases/conformance/jsdoc/seeTag4.ts
Labels: For Backlog Bug

#47607 Instantiation expressions
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/emitter.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/parser.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/compiler/utilitiesPublic.ts
  src/compiler/visitorPublic.ts
  src/services/utilities.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/arrayTypeOfTypeOf.errors.txt
  tests/baselines/reference/arrayTypeOfTypeOf.js
  tests/baselines/reference/arrayTypeOfTypeOf.types
  tests/baselines/reference/genericCallWithoutArgs.errors.txt
  tests/baselines/reference/genericCallWithoutArgs.js
  tests/baselines/reference/genericCallWithoutArgs.types
  tests/baselines/reference/genericCallsWithoutParens.errors.txt
  tests/baselines/reference/genericCallsWithoutParens.js
  tests/baselines/reference/genericCallsWithoutParens.types
  tests/baselines/reference/genericObjectCreationWithoutTypeArgs.errors.txt
  tests/baselines/reference/genericObjectCreationWithoutTypeArgs.js
  tests/baselines/reference/genericObjectCreationWithoutTypeArgs.symbols
  tests/baselines/reference/genericObjectCreationWithoutTypeArgs.types
  tests/baselines/reference/instantiationExpressionErrors.errors.txt
  tests/baselines/reference/instantiationExpressionErrors.js
  tests/baselines/reference/instantiationExpressionErrors.symbols
  tests/baselines/reference/instantiationExpressionErrors.types
  tests/baselines/reference/instantiationExpressions.errors.txt
  tests/baselines/reference/instantiationExpressions.js
  tests/baselines/reference/instantiationExpressions.symbols
  tests/baselines/reference/instantiationExpressions.types
  tests/baselines/reference/newOperatorErrorCases.errors.txt
  tests/baselines/reference/newOperatorErrorCases.js
  tests/baselines/reference/newOperatorErrorCases.symbols
  tests/baselines/reference/newOperatorErrorCases.types
  tests/baselines/reference/parserConstructorAmbiguity3.errors.txt
  tests/baselines/reference/parserMemberAccessExpression1.errors.txt
  tests/baselines/reference/parserMemberAccessExpression1.js
  tests/baselines/reference/parserMemberAccessExpression1.types
  tests/baselines/reference/parserMemberAccessOffOfGenericType1.errors.txt
  tests/baselines/reference/parserMemberAccessOffOfGenericType1.js
  tests/baselines/reference/parserMemberAccessOffOfGenericType1.types
  tests/baselines/reference/parserTypeQuery8.errors.txt
  tests/baselines/reference/parserTypeQuery8.js
  tests/baselines/reference/parserTypeQuery8.types
  tests/baselines/reference/taggedTemplatesWithTypeArguments2.errors.txt
  tests/baselines/reference/taggedTemplatesWithTypeArguments2.js
  tests/baselines/reference/taggedTemplatesWithTypeArguments2.types
  tests/cases/compiler/genericCallsWithoutParens.ts
  tests/cases/compiler/genericConstructExpressionWithoutArgs.ts
  tests/cases/compiler/genericObjectCreationWithoutTypeArgs.ts
  tests/cases/conformance/expressions/newOperator/newOperatorErrorCases.ts
  tests/cases/conformance/types/typeParameters/typeArgumentLists/instantiationExpressionErrors.ts
  tests/cases/conformance/types/typeParameters/typeArgumentLists/instantiationExpressions.ts
  tests/cases/fourslash/smartIndentTypeArgumentList.ts
Labels: Author: Team, For Uncommitted Bug

#47830 fix(47820): Assertion crash when requesting refactorings in JSDoc comment with {@link } on next line
  src/services/refactors/extractSymbol.ts
  tests/cases/fourslash/extract-jsdoc.ts
Labels: For Milestone Bug

#47162 Fix #38482
  src/lib/es5.d.ts
  tests/baselines/reference/strictBindCallApply1.errors.txt
  tests/baselines/reference/strictBindCallApply1.js
  tests/baselines/reference/strictBindCallApply1.symbols
  tests/baselines/reference/strictBindCallApply1.types
  tests/cases/conformance/functions/strictBindCallApply1.ts
Labels: For Backlog Bug

#47624 feat(47619): Extract jsx string to constant
  src/services/refactors/extractSymbol.ts
  tests/cases/fourslash/extract-const_jsxAttribute1.ts
  tests/cases/fourslash/extract-const_jsxAttribute2.ts
  tests/cases/fourslash/extract-const_jsxAttribute3.ts
Labels: For Backlog Bug

#47575 fix(47391): JSDoc/TSDoc @link with custom display text incorrectly shows vertical bar
  src/services/utilities.ts
  tests/baselines/reference/jsdocLink1.baseline
  tests/baselines/reference/jsdocLink2.baseline
  tests/baselines/reference/jsdocLink3.baseline
  tests/baselines/reference/quickInfoLink5.baseline
  tests/baselines/reference/quickInfoLink6.baseline
  tests/baselines/reference/quickInfoLink7.baseline
  tests/baselines/reference/quickInfoLink8.baseline
  tests/cases/fourslash/quickInfoLink5.ts
  tests/cases/fourslash/quickInfoLink6.ts
  tests/cases/fourslash/quickInfoLink7.ts
  tests/cases/fourslash/quickInfoLink8.ts
Labels: For Backlog Bug

#47934 Remove unnecessary check for misaligned complex rest parameters
  src/compiler/checker.ts
  tests/baselines/reference/genericRestParameters3.errors.txt
  tests/baselines/reference/genericRestParameters3.js
  tests/baselines/reference/genericRestParameters3.symbols
  tests/baselines/reference/genericRestParameters3.types
  tests/cases/conformance/types/rest/genericRestParameters3.ts
Labels: Author: Team, For Milestone Bug

#42835 Uncalled function checks only works with single conditional
  src/compiler/checker.ts
  src/compiler/debug.ts
  tests/baselines/reference/uncalledFunctionChecksInConditional.errors.txt
  tests/baselines/reference/uncalledFunctionChecksInConditional.js
  tests/baselines/reference/uncalledFunctionChecksInConditional.symbols
  tests/baselines/reference/uncalledFunctionChecksInConditional.types
  tests/baselines/reference/unknownType2.errors.txt
  tests/baselines/reference/unknownType2.js
  tests/baselines/reference/unknownType2.symbols
  tests/baselines/reference/unknownType2.types
  tests/cases/compiler/uncalledFunctionChecksInConditional.ts
  tests/cases/conformance/types/unknown/unknownType2.ts
Labels: For Backlog Bug

#46871 fix issue where duplicate default exports aren't detected
  src/compiler/checker.ts
  tests/baselines/reference/exportDefaultClassAndValue.errors.txt
  tests/baselines/reference/exportDefaultClassAndValue.js
  tests/baselines/reference/exportDefaultClassAndValue.symbols
  tests/baselines/reference/exportDefaultClassAndValue.types
  tests/baselines/reference/exportDefaultInterfaceAndFunctionOverloads.js
  tests/baselines/reference/exportDefaultInterfaceAndFunctionOverloads.symbols
  tests/baselines/reference/exportDefaultInterfaceAndFunctionOverloads.types
  tests/baselines/reference/exportDefaultInterfaceAndTwoFunctions.errors.txt
  tests/baselines/reference/exportDefaultInterfaceClassAndFunctionOverloads.errors.txt
  tests/baselines/reference/exportDefaultInterfaceClassAndFunctionOverloads.js
  tests/baselines/reference/exportDefaultInterfaceClassAndFunctionOverloads.symbols
  tests/baselines/reference/exportDefaultInterfaceClassAndFunctionOverloads.types
  tests/baselines/reference/exportDefaultInterfaceClassAndValue.errors.txt
  tests/baselines/reference/exportDefaultInterfaceClassAndValue.js
  tests/baselines/reference/exportDefaultInterfaceClassAndValue.symbols
  tests/baselines/reference/exportDefaultInterfaceClassAndValue.types
  tests/baselines/reference/exportDefaultTypeAndClass.errors.txt
  tests/baselines/reference/exportDefaultTypeAndClass.js
  tests/baselines/reference/exportDefaultTypeAndClass.symbols
  tests/baselines/reference/exportDefaultTypeAndClass.types
  tests/baselines/reference/exportDefaultTypeAndFunctionOverloads.errors.txt
  tests/baselines/reference/exportDefaultTypeAndFunctionOverloads.js
  tests/baselines/reference/exportDefaultTypeAndFunctionOverloads.symbols
  tests/baselines/reference/exportDefaultTypeAndFunctionOverloads.types
  tests/baselines/reference/exportDefaultTypeClassAndValue.errors.txt
  tests/baselines/reference/exportDefaultTypeClassAndValue.js
  tests/baselines/reference/exportDefaultTypeClassAndValue.symbols
  tests/baselines/reference/exportDefaultTypeClassAndValue.types
  tests/baselines/reference/exportInterfaceClassAndValue.errors.txt
  tests/baselines/reference/exportInterfaceClassAndValue.js
  tests/baselines/reference/exportInterfaceClassAndValue.symbols
  tests/baselines/reference/exportInterfaceClassAndValue.types
  tests/baselines/reference/exportInterfaceClassAndValueWithDuplicatesInImportList.errors.txt
  tests/baselines/reference/exportInterfaceClassAndValueWithDuplicatesInImportList.js
  tests/baselines/reference/exportInterfaceClassAndValueWithDuplicatesInImportList.symbols
  tests/baselines/reference/exportInterfaceClassAndValueWithDuplicatesInImportList.types
  tests/baselines/reference/exportTwoInterfacesWithSameName.js
  tests/baselines/reference/exportTwoInterfacesWithSameName.symbols
  tests/baselines/reference/exportTwoInterfacesWithSameName.types
  tests/cases/compiler/exportDefaultClassAndValue.ts
  tests/cases/compiler/exportDefaultInterfaceAndFunctionOverloads.ts
  tests/cases/compiler/exportDefaultInterfaceClassAndFunctionOverloads.ts
  tests/cases/compiler/exportDefaultInterfaceClassAndValue.ts
  tests/cases/compiler/exportDefaultTypeAndClass.ts
  tests/cases/compiler/exportDefaultTypeAndFunctionOverloads.ts
  tests/cases/compiler/exportDefaultTypeClassAndValue.ts
  tests/cases/compiler/exportInterfaceClassAndValue.ts
  tests/cases/compiler/exportInterfaceClassAndValueWithDuplicatesInImportList.ts
  tests/cases/compiler/exportTwoInterfacesWithSameName.ts
Labels: For Backlog Bug

#46944 Use webworker typings for webServer.ts
  src/tsserver/webServer.ts
Labels: Housekeeping, For Uncommitted Bug

#47308 feat(47281): Implementing an interface suggests any as type
  src/services/codefixes/helpers.ts
  tests/cases/fourslash/codeFixClassExtendAbstractMethod.ts
  tests/cases/fourslash/codeFixClassImplementInterfaceComputedPropertyNameWellKnownSymbols.ts
  tests/cases/fourslash/codeFixClassImplementInterfaceMethodTypePredicate.ts
  tests/cases/fourslash/codeFixClassImplementInterfaceMultipleSignatures.ts
  tests/cases/fourslash/codeFixClassImplementInterfaceMultipleSignaturesRest1.ts
  tests/cases/fourslash/codeFixClassImplementInterfaceMultipleSignaturesRest2.ts
  tests/cases/fourslash/completionsOverridingMethod.ts
  tests/cases/fourslash/completionsOverridingMethod10.ts
  tests/cases/fourslash/completionsOverridingMethod11.ts
  tests/cases/fourslash/completionsOverridingMethod6.ts
Labels: For Backlog Bug

#47117 fix(47024):fix type of DateTimeFormat and NumberFormat
  src/lib/es2021.intl.d.ts
  src/lib/es5.d.ts
  src/lib/esnext.intl.d.ts
  tests/baselines/reference/DateTimeFormatAndNumberFormatES2021.errors.txt
  tests/baselines/reference/DateTimeFormatAndNumberFormatES2021.js
  tests/baselines/reference/DateTimeFormatAndNumberFormatES2021.symbols
  tests/baselines/reference/DateTimeFormatAndNumberFormatES2021.types
  tests/baselines/reference/bigintWithLib.types
  tests/baselines/reference/bigintWithoutLib.types
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2016Plus.types
  tests/baselines/reference/es2020IntlAPIs.types
  tests/baselines/reference/formatToPartsBigInt.symbols
  tests/baselines/reference/formatToPartsBigInt.types
  tests/baselines/reference/numberFormatCurrencySign.symbols
  tests/baselines/reference/numberFormatCurrencySign.types
  tests/baselines/reference/numberFormatCurrencySignResolved.symbols
  tests/baselines/reference/numberFormatCurrencySignResolved.types
  tests/cases/compiler/DateTimeFormatAndNumberFormatES2021.ts
Labels: For Backlog Bug

#47948 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220218104901942 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#47129 Standardized aka.ms links for tsc and tsconfig
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  src/executeCommandLine/executeCommandLine.ts
  tests/baselines/reference/tsConfig/Default initialized TSConfig/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with advanced options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with boolean value compiler options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with enum value compiler options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with files options/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with incorrect compiler option value/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with incorrect compiler option/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with list compiler options with enum value/tsconfig.json
  tests/baselines/reference/tsConfig/Initialized TSConfig with list compiler options/tsconfig.json
  tests/baselines/reference/tsc/runWithoutArgs/initial-build/does-not-add-color-when-NO_COLOR-is-set.js
  tests/baselines/reference/tsc/runWithoutArgs/initial-build/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped-when-host-can't-provide-terminal-width.js
  tests/baselines/reference/tsc/runWithoutArgs/initial-build/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/declarationDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/when-outDir-and-declarationDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/when-outDir-is-specified.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/with-outFile.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/without-outDir-or-outFile-is-specified-with-declaration-enabled.js
  tests/baselines/reference/tscWatch/programUpdates/should-not-trigger-recompilation-because-of-program-emit/without-outDir-or-outFile-is-specified.js
Labels: For Milestone Bug

#40909 Fix object.assign first param constraint
  src/lib/es2015.core.d.ts
  tests/baselines/reference/conditionalTypeDoesntSpinForever.types
  tests/baselines/reference/declarationsWithRecursiveInternalTypesProduceUniqueTypeParams.types
  tests/baselines/reference/es2018ObjectAssign.types
  tests/baselines/reference/intersectionsAndEmptyObjects.types
  tests/baselines/reference/unionAndIntersectionInference1.types
Labels: Author: Team, For Milestone Bug

#47777 feat(44956): jsdoc comments - remove hyphen separator
  src/services/jsDoc.ts
  src/testRunner/unittests/tsserver/jsdocTag.ts
  tests/baselines/reference/jsDocFunctionSignatures6.baseline
  tests/baselines/reference/quickInfoJsDocTags3.baseline
  tests/baselines/reference/quickInfoJsDocTags4.baseline
  tests/baselines/reference/quickInfoJsDocTags5.baseline
  tests/baselines/reference/quickInfoJsDocTags6.baseline
  tests/baselines/reference/signatureHelpJSDocCallbackTag.baseline
  tests/cases/fourslash/server/jsdocCallbackTag.ts
  tests/cases/fourslash/server/jsdocTypedefTag.ts
Labels: For Backlog Bug

#47960 Update baseline
  tests/baselines/reference/declarationEmitObjectAssignedDefaultExport.types
Labels: For Uncommitted Bug

#47959 Only suggest `@param` codefixes in TS
  src/compiler/checker.ts
  tests/cases/fourslash/jsdocParam_suggestion1.ts
Labels: Author: Team, For Uncommitted Bug

#47973 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220220104913021 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#47985 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220221105423952 to main
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#47307 fix(47296): Folding for multi-line statements when wrapped in parenthesis
  src/services/outliningElementsCollector.ts
  tests/cases/fourslash/getJSXOutliningSpans.tsx
  tests/cases/fourslash/getOutliningSpans.ts
  tests/cases/fourslash/outliningSpansForArrowFunctionBody.ts
  tests/cases/fourslash/outliningSpansForParenthesizedExpression.ts
  tests/cases/fourslash/shims-pp/getOutliningSpans.ts
  tests/cases/fourslash/shims/getOutliningSpans.ts
Labels: For Uncommitted Bug

#47927 Don't error if binding pattern type is never in control flow analysis for destructured discriminated union
  src/compiler/checker.ts
  tests/baselines/reference/arrayDestructuringInSwitch1.js
  tests/baselines/reference/arrayDestructuringInSwitch1.symbols
  tests/baselines/reference/arrayDestructuringInSwitch1.types
  tests/baselines/reference/arrayDestructuringInSwitch2.errors.txt
  tests/baselines/reference/arrayDestructuringInSwitch2.js
  tests/baselines/reference/arrayDestructuringInSwitch2.symbols
  tests/baselines/reference/arrayDestructuringInSwitch2.types
  tests/cases/compiler/arrayDestructuringInSwitch1.ts
  tests/cases/compiler/arrayDestructuringInSwitch2.ts
Labels: Author: Team, For Milestone Bug

#47407 fix(47158): Removes comments when line variable declaration
  src/compiler/emitter.ts
  src/compiler/factory/emitNode.ts
  src/compiler/transformers/ts.ts
  src/compiler/types.ts
  tests/baselines/reference/emitOneLineVariableDeclarationRemoveCommentsFalse.js
  tests/baselines/reference/emitOneLineVariableDeclarationRemoveCommentsFalse.symbols
  tests/baselines/reference/emitOneLineVariableDeclarationRemoveCommentsFalse.types
  tests/cases/compiler/emitOneLineVariableDeclarationRemoveCommentsFalse.ts
Labels: For Backlog Bug

#42546 Use related spans for "implement abstract class" errors
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/services/codefixes/fixClassDoesntImplementInheritedAbstractMember.ts
  tests/baselines/reference/abstractPropertyNegative.errors.txt
  tests/baselines/reference/classAbstractDeclarations.d.errors.txt
  tests/baselines/reference/classAbstractExtends.errors.txt
  tests/baselines/reference/classAbstractGeneric.errors.txt
  tests/baselines/reference/classAbstractInheritance.errors.txt
  tests/baselines/reference/classAbstractInstantiations2.errors.txt
  tests/baselines/reference/classAbstractOverrideWithAbstract.errors.txt
  tests/baselines/reference/classAbstractUsingAbstractMethods2.errors.txt
  tests/baselines/reference/classExpressionExtendingAbstractClass.errors.txt
  tests/baselines/reference/mixinAbstractClasses.2.errors.txt
Labels: For Backlog Bug

#48029 Revert "Use related spans for "implement abstract class" errors"
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/services/codefixes/fixClassDoesntImplementInheritedAbstractMember.ts
  tests/baselines/reference/abstractPropertyNegative.errors.txt
  tests/baselines/reference/classAbstractDeclarations.d.errors.txt
  tests/baselines/reference/classAbstractExtends.errors.txt
  tests/baselines/reference/classAbstractGeneric.errors.txt
  tests/baselines/reference/classAbstractInheritance.errors.txt
  tests/baselines/reference/classAbstractInstantiations2.errors.txt
  tests/baselines/reference/classAbstractOverrideWithAbstract.errors.txt
  tests/baselines/reference/classAbstractUsingAbstractMethods2.errors.txt
  tests/baselines/reference/classExpressionExtendingAbstractClass.errors.txt
  tests/baselines/reference/mixinAbstractClasses.2.errors.txt
Labels: Author: Team, For Uncommitted Bug

#44364 go-to-type-definition, and find-all-refs should work for import.meta
  src/services/findAllReferences.ts
  src/services/goToDefinition.ts
  src/services/services.ts
  tests/baselines/reference/findAllRefsImportMeta.baseline.jsonc
  tests/baselines/reference/quickInfoImportMeta.baseline
  tests/cases/fourslash/findAllRefsImportMeta.ts
  tests/cases/fourslash/goToDefinitionImportMeta.ts
  tests/cases/fourslash/goToTypeDefinitionImportMeta.ts
  tests/cases/fourslash/quickInfoImportMeta.ts
Labels: For Backlog Bug

#47550 Don't treat a colon in a conditional expression branch as part of an arrow function
  src/compiler/parser.ts
  tests/baselines/reference/parserArrowFunctionExpression10.errors.txt
  tests/baselines/reference/parserArrowFunctionExpression10.js
  tests/baselines/reference/parserArrowFunctionExpression10.symbols
  tests/baselines/reference/parserArrowFunctionExpression10.types
  tests/baselines/reference/parserArrowFunctionExpression11.errors.txt
  tests/baselines/reference/parserArrowFunctionExpression11.js
  tests/baselines/reference/parserArrowFunctionExpression11.symbols
  tests/baselines/reference/parserArrowFunctionExpression11.types
  tests/baselines/reference/parserArrowFunctionExpression12.errors.txt
  tests/baselines/reference/parserArrowFunctionExpression12.js
  tests/baselines/reference/parserArrowFunctionExpression12.symbols
  tests/baselines/reference/parserArrowFunctionExpression12.types
  tests/baselines/reference/parserArrowFunctionExpression13.errors.txt
  tests/baselines/reference/parserArrowFunctionExpression13.js
  tests/baselines/reference/parserArrowFunctionExpression13.symbols
  tests/baselines/reference/parserArrowFunctionExpression13.types
  tests/baselines/reference/parserArrowFunctionExpression14.errors.txt
  tests/baselines/reference/parserArrowFunctionExpression14.js
  tests/baselines/reference/parserArrowFunctionExpression14.symbols
  tests/baselines/reference/parserArrowFunctionExpression14.types
  tests/baselines/reference/parserArrowFunctionExpression8.errors.txt
  tests/baselines/reference/parserArrowFunctionExpression8.js
  tests/baselines/reference/parserArrowFunctionExpression8.symbols
  tests/baselines/reference/parserArrowFunctionExpression8.types
  tests/baselines/reference/parserArrowFunctionExpression8Js.errors.txt
  tests/baselines/reference/parserArrowFunctionExpression8Js.js
  tests/baselines/reference/parserArrowFunctionExpression8Js.symbols
  tests/baselines/reference/parserArrowFunctionExpression8Js.types
  tests/baselines/reference/parserArrowFunctionExpression9.errors.txt
  tests/baselines/reference/parserArrowFunctionExpression9.js
  tests/baselines/reference/parserArrowFunctionExpression9.symbols
  tests/baselines/reference/parserArrowFunctionExpression9.types
  tests/cases/conformance/parser/ecmascript5/ArrowFunctionExpressions/parserArrowFunctionExpression10.ts
  tests/cases/conformance/parser/ecmascript5/ArrowFunctionExpressions/parserArrowFunctionExpression11.ts
  tests/cases/conformance/parser/ecmascript5/ArrowFunctionExpressions/parserArrowFunctionExpression12.ts
  tests/cases/conformance/parser/ecmascript5/ArrowFunctionExpressions/parserArrowFunctionExpression13.ts
  tests/cases/conformance/parser/ecmascript5/ArrowFunctionExpressions/parserArrowFunctionExpression14.ts
  tests/cases/conformance/parser/ecmascript5/ArrowFunctionExpressions/parserArrowFunctionExpression8.ts
  tests/cases/conformance/parser/ecmascript5/ArrowFunctionExpressions/parserArrowFunctionExpression8Js.ts
  tests/cases/conformance/parser/ecmascript5/ArrowFunctionExpressions/parserArrowFunctionExpression9.ts
Labels: Author: Team, For Milestone Bug

#44599 Expose text property of SourceFileLike for some Public APIs
  src/compiler/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Uncommitted Bug

#47976 fix(47853): Convert to template string issue
  src/services/refactors/convertStringOrTemplateLiteral.ts
  tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_TemplateString13.ts
Labels: For Backlog Bug

#48061 Add missing `getReducedType` call in `getConditionalTypeInstantiation`
  src/compiler/checker.ts
  tests/baselines/reference/objectAssignLikeNonUnionResult.js
  tests/baselines/reference/objectAssignLikeNonUnionResult.symbols
  tests/baselines/reference/objectAssignLikeNonUnionResult.types
  tests/cases/compiler/objectAssignLikeNonUnionResult.ts
Labels: Author: Team, For Uncommitted Bug

#47811 Add `Intl.Locale` parameter type to `toLocale[X]String` signatures.
  src/compiler/commandLineParser.ts
  src/lib/es2020.bigint.d.ts
  src/lib/es2020.d.ts
  src/lib/es2020.date.d.ts
  src/lib/es2020.intl.d.ts
  src/lib/es2020.number.d.ts
  src/lib/libs.json
  tests/baselines/reference/bigintWithLib.types
  tests/baselines/reference/es2020IntlAPIs.symbols
  tests/baselines/reference/localesObjectArgument.js
  tests/baselines/reference/localesObjectArgument.symbols
  tests/baselines/reference/localesObjectArgument.types
  tests/baselines/reference/reactJsxReactResolvedNodeNext.trace.json
  tests/baselines/reference/reactJsxReactResolvedNodeNextEsm.trace.json
  tests/baselines/reference/tsc/runWithoutArgs/initial-build/does-not-add-color-when-NO_COLOR-is-set.js
  tests/baselines/reference/tsc/runWithoutArgs/initial-build/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped-when-host-can't-provide-terminal-width.js
  tests/baselines/reference/tsc/runWithoutArgs/initial-build/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
  tests/baselines/reference/typeGuardConstructorNarrowAny.symbols
  tests/baselines/reference/typeGuardConstructorPrimitiveTypes.symbols
  tests/cases/conformance/es2020/localesObjectArgument.ts
Labels: For Backlog Bug

#48064 Use full `isReadonlySymbol` check rather than declaration flags
  src/compiler/checker.ts
  tests/baselines/reference/typeGuardNarrowByMutableUntypedField.js
  tests/baselines/reference/typeGuardNarrowByMutableUntypedField.symbols
  tests/baselines/reference/typeGuardNarrowByMutableUntypedField.types
  tests/baselines/reference/typeGuardNarrowByUntypedField.js
  tests/baselines/reference/typeGuardNarrowByUntypedField.symbols
  tests/baselines/reference/typeGuardNarrowByUntypedField.types
  tests/cases/compiler/typeGuardNarrowByMutableUntypedField.ts
  tests/cases/compiler/typeGuardNarrowByUntypedField.ts
Labels: Author: Team, For Milestone Bug
