Repository microsoft/TypeScript, pull requests merged in 2022-12, with the labels that each got.

#51704 Unconditionally call `checkExpression` from `checkSatisfiesExpression`
  src/compiler/checker.ts
  tests/baselines/reference/satisfiesEmit.errors.txt
  tests/baselines/reference/satisfiesEmit.js
  tests/baselines/reference/satisfiesEmit.symbols
  tests/baselines/reference/satisfiesEmit.types
  tests/cases/compiler/satisfiesEmit.ts
Labels: Author: Team, For Uncommitted Bug

#51056 fix(51053): Extract type on JSDoc causes an assertion failure
  src/services/refactors/extractType.ts
  tests/cases/fourslash/refactorExtractType_js8.ts
Labels: For Backlog Bug

#51602 Fixed method signature of Atomics.waitAsync
  src/lib/es2022.sharedmemory.d.ts
  tests/baselines/reference/es2022SharedMemory.symbols
  tests/baselines/reference/es2022SharedMemory.types
  tests/cases/conformance/es2022/es2022SharedMemory.ts
Labels: For Uncommitted Bug

#50996 Exhaustive case completion for switch statements
  src/compiler/checker.ts
  src/compiler/utilities.ts
  src/services/completions.ts
  src/services/services.ts
  tests/cases/fourslash/exhaustiveCaseCompletions1.ts
  tests/cases/fourslash/exhaustiveCaseCompletions2.ts
  tests/cases/fourslash/exhaustiveCaseCompletions3.ts
  tests/cases/fourslash/exhaustiveCaseCompletions4.ts
  tests/cases/fourslash/exhaustiveCaseCompletions5.ts
  tests/cases/fourslash/fourslash.ts
Labels: Author: Team, For Uncommitted Bug

#51712 Cherry-pick #51704 to release 4.9
  src/compiler/checker.ts
  tests/baselines/reference/satisfiesEmit.errors.txt
  tests/baselines/reference/satisfiesEmit.js
  tests/baselines/reference/satisfiesEmit.symbols
  tests/baselines/reference/satisfiesEmit.types
  tests/cases/compiler/satisfiesEmit.ts
Labels: Author: Team, For Uncommitted Bug

#51720 Fix narrowing by `typeof` applied to discriminant property
  src/compiler/checker.ts
  tests/baselines/reference/narrowingTypeofDiscriminant.js
  tests/baselines/reference/narrowingTypeofDiscriminant.symbols
  tests/baselines/reference/narrowingTypeofDiscriminant.types
  tests/cases/compiler/narrowingTypeofDiscriminant.ts
Labels: Author: Team, For Milestone Bug

#51762 Fix #51623
  src/compiler/checker.ts
  tests/baselines/reference/fixCrashAliasLookupForDefauledImport.js
  tests/baselines/reference/fixCrashAliasLookupForDefauledImport.symbols
  tests/baselines/reference/fixCrashAliasLookupForDefauledImport.types
  tests/cases/compiler/fixCrashAliasLookupForDefauledImport.ts
Labels: Author: Team, For Milestone Bug

#51640 fix(40365): deprecated for properties of merged Interfaces
  src/compiler/checker.ts
  tests/cases/fourslash/jsdocDeprecated_suggestion19.ts
Labels: For Backlog Bug

#51702 (fix #50725, #50710) add file extensions in import statements
  src/compiler/moduleSpecifiers.ts
  src/services/refactors/moveToNewFile.ts
  tests/cases/fourslash/getEditsForFileRename_keepFileExtensions.ts
  tests/cases/fourslash/moveToNewFile_importFileExtensions.ts
Labels: For Milestone Bug

#51775 Add FabricBot config, removing @amcasey pings
  .github/fabricbot.json
Labels: Author: Team, For Uncommitted Bug

#51785 Unconditionally use WeakMap in debug
  src/compiler/debug.ts
Labels: Author: Team, For Uncommitted Bug

#51373 Fix missed errors in switch when using union of literal and non-literal types (#38686)
  src/compiler/checker.ts
  tests/baselines/reference/switchAssignmentCompat.errors.txt
  tests/baselines/reference/switchCaseCircularRefeference.errors.txt
  tests/baselines/reference/switchCasesExpressionTypeMismatch.errors.txt
  tests/baselines/reference/switchCasesExpressionTypeMismatch.js
  tests/baselines/reference/switchCasesExpressionTypeMismatch.symbols
  tests/baselines/reference/switchCasesExpressionTypeMismatch.types
  tests/cases/compiler/switchCasesExpressionTypeMismatch.ts
Labels: For Backlog Bug

#51446 Remove some files from the repo root
  .eslintignore
  .eslintrc.json
  .yarnrc
  Herebyfile.mjs
  scripts/CopyrightNotice.txt
  scripts/dtsBundler.mjs
  src/testRunner/externalCompileRunner.ts
  tests/cases/docker/Dockerfile
  tests/cases/docker/Dockerfile.dockerignore
Labels: Author: Team, For Uncommitted Bug

#51732 Use non relative name cache for type reference resolutions and API updates
  src/compiler/moduleNameResolver.ts
  src/compiler/program.ts
  src/testRunner/unittests/moduleResolution.ts
  src/testRunner/unittests/tsserver/getEditsForFileRename.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/library-reference-6.trace.json
Labels: Author: Team, For Uncommitted Bug

#51795 Remove emitDeclarationOnly hack now that build mode supports it as a flag
  Herebyfile.mjs
  scripts/build/projects.mjs
Labels: Author: Team, For Uncommitted Bug

#51792 Don't offer exhaustive case completion after dot
  src/services/completions.ts
  tests/cases/fourslash/exhaustiveCaseCompletions3.ts
Labels: Author: Team, For Uncommitted Bug

#51797 [moveToNewFile] Fix namespace import update bug, simplify, comment, and rename
  src/services/refactors/moveToNewFile.ts
  tests/cases/fourslash/moveToNewFile_updateNamespaceImport.ts
Labels: Author: Team, For Uncommitted Bug

#51718 [Test Infrastructure] Instead of computing signatures during building, compute them afterwards for verification
  src/compiler/builder.ts
  src/compiler/builderPublic.ts
  src/compiler/builderState.ts
  src/compiler/sys.ts
  src/compiler/types.ts
  src/compiler/watch.ts
  src/compiler/watchPublic.ts
  src/testRunner/unittests/tsbuild/commandLine.ts
  src/testRunner/unittests/tsbuild/noEmitOnError.ts
  src/testRunner/unittests/tsc/helpers.ts
  src/testRunner/unittests/tsc/incremental.ts
  tests/baselines/reference/tsbuild/commandLine/different-options-with-incremental-discrepancies.js
  tests/baselines/reference/tsbuild/noEmitOnError/semantic-errors-with-incremental-discrepancies.js
  tests/baselines/reference/tsc/incremental/different-options-with-incremental-discrepancies.js
  tests/baselines/reference/tsc/incremental/noEmit-changes-composite-discrepancies.js
  tests/baselines/reference/tsc/incremental/noEmit-changes-incremental-declaration-discrepancies.js
  tests/baselines/reference/tsc/incremental/noEmit-changes-incremental-discrepancies.js
  tests/baselines/reference/tsc/incremental/noEmit-changes-with-initial-noEmit-composite-discrepancies.js
  tests/baselines/reference/tsc/incremental/noEmit-changes-with-initial-noEmit-incremental-declaration-discrepancies.js
  tests/baselines/reference/tsc/incremental/noEmit-changes-with-initial-noEmit-incremental-discrepancies.js
  tests/baselines/reference/tsc/incremental/with-noEmitOnError-semantic-errors-discrepancies.js
  tests/baselines/reference/tsc/incremental/with-noEmitOnError-syntax-errors-discrepancies.js
Labels: Author: Team, For Uncommitted Bug

#51653 Use `missingType` in `--noUncheckedIndexedAccess` mode
  src/compiler/checker.ts
  tests/baselines/reference/inKeywordNarrowingWithNoUncheckedIndexedAccess.symbols
  tests/baselines/reference/inKeywordNarrowingWithNoUncheckedIndexedAccess.types
  tests/baselines/reference/noUncheckedIndexedAccess.errors.txt
  tests/cases/compiler/inKeywordNarrowingWithNoUncheckedIndexedAccess.ts
Labels: Author: Team, For Uncommitted Bug

#51703 Ignore switch statement bypass control flows that produce `never`
  src/compiler/checker.ts
  tests/baselines/reference/exhaustiveSwitchCheckCircularity.errors.txt
  tests/baselines/reference/exhaustiveSwitchCheckCircularity.js
  tests/baselines/reference/exhaustiveSwitchCheckCircularity.symbols
  tests/baselines/reference/exhaustiveSwitchCheckCircularity.types
  tests/cases/compiler/exhaustiveSwitchCheckCircularity.ts
Labels: Author: Team, For Milestone Bug

#51803 Update to esbuild v0.16
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#51769 Make getSupportedCodeFixes on LS so it can be proxied by plugins
  src/harness/client.ts
  src/harness/harnessLanguageService.ts
  src/server/protocol.ts
  src/server/session.ts
  src/services/codeFixProvider.ts
  src/services/services.ts
  src/services/types.ts
  src/testRunner/unittests/tsserver/plugins.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/tsserver/plugins/getSupportedCodeFixes-can-be-proxied.js
Labels: Author: Team, For Backlog Bug

#51830 Create special --no-typecheck script
  .vscode/tasks.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#50983 fix(50888): Organize Imports may delete preceding comments when all members of all import statements are unused
  src/services/organizeImports.ts
  tests/cases/fourslash/organizeImports14.ts
  tests/cases/fourslash/organizeImports15.ts
Labels: For Backlog Bug

#51028 feat(47977): Autocomplete not working for @extends tags
  src/services/completions.ts
  tests/cases/fourslash/jsdocExtendsTagCompletion.ts
  tests/cases/fourslash/jsdocImplementsTagCompletion.ts
Labels: For Backlog Bug

#51594 Fix #51437 Duplicate "Duplicate identifier" errors
  src/compiler/program.ts
  tests/baselines/reference/tsserver/projects/handles-the-missing-files-added-with-tripleslash-ref.js
  tests/cases/fourslash/codeFixInferFromUsageMultipleParametersJS.ts
  tests/cases/fourslash/deduplicateDuplicateMergedBindCheckErrors.ts
Labels: For Backlog Bug

#51037 Fixed tuple types indexed by a type parameter
  src/compiler/checker.ts
  tests/baselines/reference/narrowingDestructuring.types
  tests/baselines/reference/spreadTupleAccessedByTypeParameter.js
  tests/baselines/reference/spreadTupleAccessedByTypeParameter.symbols
  tests/baselines/reference/spreadTupleAccessedByTypeParameter.types
  tests/cases/compiler/spreadTupleAccessedByTypeParameter.ts
Labels: For Backlog Bug

#51093 fix(51077): jsxAttributeCompletionStyle doesn't work as expected
  src/services/completions.ts
  tests/cases/fourslash/jsxTagNameCompletionWithExistingJsxInitializer.ts
Labels: For Backlog Bug

#51839 Fix the test from #51037
  tests/baselines/reference/spreadTupleAccessedByTypeParameter.js
Labels: Author: Team, For Uncommitted Bug

#51834 Properly detect explicitly-set ES3 target
  src/compiler/commandLineParser.ts
  src/compiler/utilities.ts
  tests/baselines/reference/ES3For-ofTypeCheck1.errors.txt
  tests/baselines/reference/ES3For-ofTypeCheck4.errors.txt
  tests/baselines/reference/accessorWithES3.errors.txt
  tests/baselines/reference/accessorsNotAllowedInES3.errors.txt
  tests/baselines/reference/definePropertyOutputES3.errors.txt
  tests/baselines/reference/es3-oldStyleOctalLiteralInEnums.errors.txt
  tests/baselines/reference/es3-oldStyleOctalLiteralTypes.errors.txt
  tests/baselines/reference/es3defaultAliasIsQuoted.js
  tests/baselines/reference/esModuleInteropWithExportStar(target=es3).js
  tests/baselines/reference/exportAndImport-es3-amd.js
  tests/baselines/reference/exportAndImport-es3.js
  tests/baselines/reference/exportsAndImportsWithUnderscores1.js
  tests/baselines/reference/exportsAndImportsWithUnderscores2.js
  tests/baselines/reference/exportsAndImportsWithUnderscores3.js
  tests/baselines/reference/exportsAndImportsWithUnderscores4.js
  tests/baselines/reference/importCallExpressionAsyncES3AMD.js
  tests/baselines/reference/importCallExpressionAsyncES3CJS.js
  tests/baselines/reference/importCallExpressionAsyncES3System.js
  tests/baselines/reference/importCallExpressionAsyncES3UMD.js
  tests/baselines/reference/isLiteral2.errors.txt
  tests/baselines/reference/objectLiteralErrorsES3.errors.txt
  tests/baselines/reference/objectTypeWithStringNamedNumericProperty.errors.txt
  tests/baselines/reference/privateNameES5Ban(target=es3).errors.txt
  tests/baselines/reference/propertyAccessNumericLiterals.errors.txt
  tests/baselines/reference/trailingCommasES3.js
  tests/baselines/reference/transpile/Elides import equals referenced only by export type.js
  tests/baselines/reference/transpile/Elides import equals referenced only by export type.oldTranspile.js
  tests/baselines/reference/transpile/Elides import equals referenced only by type only export specifier.js
  tests/baselines/reference/transpile/Elides import equals referenced only by type only export specifier.oldTranspile.js
  tests/baselines/reference/transpile/Export star as ns conflict does not crash.js
  tests/baselines/reference/transpile/Export star as ns conflict does not crash.oldTranspile.js
  tests/baselines/reference/transpile/Generates no diagnostics for missing module imports.js
  tests/baselines/reference/transpile/Generates no diagnostics for missing module imports.oldTranspile.js
  tests/baselines/reference/transpile/Rename dependencies - AMD.js
  tests/baselines/reference/transpile/Rename dependencies - UMD.js
  tests/baselines/reference/tsbuild/sample1/rebuilds-when-extended-config-file-changes.js
  tests/baselines/reference/tsc/runWithoutArgs/does-not-add-color-when-NO_COLOR-is-set.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped-when-host-can't-provide-terminal-width.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
Labels: Author: Team, For Uncommitted Bug

#49891 feat(49323): Render JSDoc @throws {type} as a link
  src/compiler/emitter.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/factory/nodeTests.ts
  src/compiler/parser.ts
  src/compiler/types.ts
  src/services/classifier.ts
  src/services/completions.ts
  src/services/jsDoc.ts
  src/testRunner/unittests/jsDocParsing.ts
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.exceptionTag1.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.exceptionTag2.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.exceptionTag3.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.throwsTag1.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.throwsTag2.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.throwsTag3.json
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/jsdocThrowsTag_findAllReferences.baseline.jsonc
  tests/baselines/reference/jsdocThrowsTag_rename.baseline
  tests/baselines/reference/parseThrowsTag.js
  tests/baselines/reference/parseThrowsTag.symbols
  tests/baselines/reference/parseThrowsTag.types
  tests/baselines/reference/quickInfoJsDocTags3.baseline
  tests/baselines/reference/quickInfoThrowsTag.baseline
  tests/cases/conformance/jsdoc/parseThrowsTag.ts
  tests/cases/fourslash/gotoDefinitionThrowsTag.ts
  tests/cases/fourslash/jsdocThrowsTagCompletion.ts
  tests/cases/fourslash/jsdocThrowsTag_findAllReferences.ts
  tests/cases/fourslash/jsdocThrowsTag_rename.ts
  tests/cases/fourslash/quickInfoThrowsTag.ts
Labels: For Backlog Bug

#50106 fix(50089): JSDoc/TSDoc @link with custom display text incorrectly shows vertical bar
  src/services/utilities.ts
  tests/baselines/reference/quickInfoForJSDocWithHttpLinks.baseline
  tests/baselines/reference/quickInfoLink10.baseline
  tests/cases/fourslash/quickInfoLink10.ts
Labels: For Backlog Bug

#50709 fix(47954): Auto implementation of interface with a constructor prop causes error
  src/services/codefixes/helpers.ts
  tests/cases/fourslash/codeFixClassImplementInterfaceConstructorName1.ts
  tests/cases/fourslash/codeFixClassImplementInterfaceConstructorName2.ts
Labels: For Backlog Bug

#51878 Remove excluded CodeQL rules, fix reference to Gulpfile
  .github/codeql/codeql-configuration.yml
Labels: Author: Team, For Milestone Bug

#50403 Fix(29118): tsconfig.extends as array
  src/compiler/builder.ts
  src/compiler/commandLineParser.ts
  src/compiler/types.ts
  src/executeCommandLine/executeCommandLine.ts
  src/harness/harnessIO.ts
  src/services/getEditsForFileRename.ts
  src/testRunner/unittests/config/configurationExtension.ts
  src/testRunner/unittests/config/showConfig.ts
  src/testRunner/unittests/tsbuildWatch/programUpdates.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/configFileExtendsAsList.errors.txt
  tests/baselines/reference/configFileExtendsAsList.js
  tests/baselines/reference/configFileExtendsAsList.symbols
  tests/baselines/reference/configFileExtendsAsList.types
  tests/baselines/reference/tsbuildWatch/programUpdates/works-with-extended-source-files.js
  tests/cases/compiler/configFileExtendsAsList.ts
Labels: Author: Team, For Milestone Bug

#51877 Update esbuild to v0.16.5 and use new --packages=external option
  Herebyfile.mjs
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#51790 Don't include already-covered cases in switch completions
  src/compiler/factory/nodeTests.ts
  src/compiler/types.ts
  src/services/completions.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/switchCompletions.ts
Labels: Author: Team, For Milestone Bug

#51733 Add option for organize imports case sensitivity
  src/compiler/core.ts
  src/compiler/types.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/server/protocol.ts
  src/services/codefixes/importFixes.ts
  src/services/organizeImports.ts
  src/services/utilities.ts
  src/testRunner/unittests/services/organizeImports.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/organizeImports/Syntax_Error_Imports_skipDestructiveCodeActions.ts
  tests/cases/fourslash/autoImportSortCaseSensitivity1.ts
  tests/cases/fourslash/autoImportSortCaseSensitivity2.ts
  tests/cases/fourslash/codeFixInferFromUsageContextualImport1.ts
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/organizeImports1.ts
  tests/cases/fourslash/organizeImports13.ts
  tests/cases/fourslash/organizeImports16.ts
Labels: Author: Team, For Milestone Bug

#51766 Add missing type argument constraints check
  src/compiler/checker.ts
  tests/baselines/reference/unmetTypeConstraintInImportCall.errors.txt
  tests/baselines/reference/unmetTypeConstraintInImportCall.symbols
  tests/baselines/reference/unmetTypeConstraintInImportCall.types
  tests/baselines/reference/unmetTypeConstraintInJSDocImportCall.errors.txt
  tests/baselines/reference/unmetTypeConstraintInJSDocImportCall.symbols
  tests/baselines/reference/unmetTypeConstraintInJSDocImportCall.types
  tests/cases/compiler/unmetTypeConstraintInImportCall.ts
  tests/cases/compiler/unmetTypeConstraintInJSDocImportCall.ts
Labels: For Backlog Bug

#51880 Monomorphic Symbol access
  src/compiler/checker.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/services/codefixes/fixInvalidImportSyntax.ts
  src/services/codefixes/inferFromUsage.ts
  src/services/codefixes/returnValueCorrect.ts
  src/services/refactors/extractSymbol.ts
  src/services/services.ts
  src/services/signatureHelp.ts
  src/services/symbolDisplay.ts
  src/services/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#51900 Move auto-generated identifier info into separate object
  src/compiler/emitter.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/factory/utilities.ts
  src/compiler/transformers/classFields.ts
  src/compiler/transformers/module/module.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/compiler/utilitiesPublic.ts
  src/harness/harnessUtils.ts
  src/services/services.ts
Labels: Author: Team, For Uncommitted Bug

#51908 Remove isJSDocOptionalParameter and isOptionalDeclaration from public API
  src/compiler/utilities.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Uncommitted Bug

#51894 Fix excess property checking for intersections with index signatures
  src/compiler/checker.ts
  tests/baselines/reference/excessPropertyCheckIntersectionWithIndexSignature.errors.txt
  tests/baselines/reference/excessPropertyCheckIntersectionWithIndexSignature.js
  tests/baselines/reference/excessPropertyCheckIntersectionWithIndexSignature.symbols
  tests/baselines/reference/excessPropertyCheckIntersectionWithIndexSignature.types
  tests/cases/compiler/excessPropertyCheckIntersectionWithIndexSignature.ts
Labels: Author: Team, For Milestone Bug

#51907 Add JSDocOverloadTag to ForEachChildTable
  src/compiler/parser.ts
  src/compiler/types.ts
  src/compiler/utilitiesPublic.ts
Labels: For Uncommitted Bug

#51922 fix(51920): "Add missing members" quick fixes incorrectly add TypeScript types in JavaScript files
  src/services/codefixes/helpers.ts
  tests/cases/fourslash/codeFixAddMissingProperties25.ts
Labels: For Milestone Bug

#51924 skip optional parameters in js files
  src/services/codefixes/helpers.ts
  tests/cases/fourslash/codeFixAddMissingProperties26.ts
Labels: For Uncommitted Bug

#51033 Added override keyword to codefix implemented abstract methods
  src/compiler/core.ts
  src/services/codefixes/helpers.ts
  tests/cases/fourslash/codeFixAmbientClassExtendAbstractMethod.ts
  tests/cases/fourslash/codeFixClassExtendAbstractGetterSetter.ts
  tests/cases/fourslash/codeFixClassExtendAbstractMethod.ts
  tests/cases/fourslash/codeFixClassExtendAbstractMethodModifiersAlreadyIncludeOverride.ts
  tests/cases/fourslash/codeFixClassExtendAbstractMethod_all.ts
  tests/cases/fourslash/codeFixClassExtendAbstractMethod_comment.ts
  tests/cases/fourslash/codeFixClassExtendAbstractPrivateProperty.ts
  tests/cases/fourslash/codeFixClassExtendAbstractProperty.ts
  tests/cases/fourslash/codeFixClassExtendAbstractPropertyThis.ts
  tests/cases/fourslash/codeFixClassExtendAbstractProtectedProperty.ts
  tests/cases/fourslash/codeFixClassExtendAbstractPublicProperty.ts
  tests/cases/fourslash/codeFixClassExtendAbstractSomePropertiesPresent.ts
Labels: For Backlog Bug

#51865 `const` modifier on type parameters
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/parser.ts
  src/compiler/types.ts
  tests/baselines/reference/tsserver/plugins/getSupportedCodeFixes-can-be-proxied.js
  tests/baselines/reference/typeParameterConstModifiers.errors.txt
  tests/baselines/reference/typeParameterConstModifiers.js
  tests/baselines/reference/typeParameterConstModifiers.symbols
  tests/baselines/reference/typeParameterConstModifiers.types
  tests/cases/conformance/types/typeParameters/typeParameterLists/typeParameterConstModifiers.ts
Labels: Author: Team, For Uncommitted Bug

#51935 Allow `const` modifiers on class expression type parameters
  src/compiler/checker.ts
  tests/baselines/reference/typeParameterConstModifiers.errors.txt
  tests/baselines/reference/typeParameterConstModifiers.js
  tests/baselines/reference/typeParameterConstModifiers.symbols
  tests/baselines/reference/typeParameterConstModifiers.types
  tests/cases/conformance/types/typeParameters/typeParameterLists/typeParameterConstModifiers.ts
Labels: Author: Team, For Milestone Bug

#51965 Go back to using explicit node verisons in CI
  .github/workflows/ci.yml
  src/compiler/watch.ts
Labels: Author: Team, For Uncommitted Bug

#51937 Support outlining in multiline import/export decls
  src/services/outliningElementsCollector.ts
  tests/cases/fourslash/outliningSpansForImportsAndExports.ts
Labels: Author: Team, For Uncommitted Bug

#51968 Fix quote style of string literal in exhaustive case completions
  src/services/completions.ts
  tests/cases/fourslash/exhaustiveCaseCompletions6.ts
Labels: Author: Team, For Uncommitted Bug

#50955 feat(48665): tsconfig "extends" field ignores "exports" field of source package
  src/compiler/commandLineParser.ts
  src/compiler/moduleNameResolver.ts
  src/testRunner/unittests/config/configurationExtension.ts
Labels: For Uncommitted Bug

#51971 --moduleResolution bundler: Allow import assignment in ambient contexts
  src/compiler/checker.ts
  tests/baselines/reference/bundlerSyntaxRestrictions.errors.txt
  tests/baselines/reference/bundlerSyntaxRestrictions.js
  tests/baselines/reference/bundlerSyntaxRestrictions.symbols
  tests/baselines/reference/bundlerSyntaxRestrictions.types
  tests/cases/conformance/moduleResolution/bundler/bundlerSyntaxRestrictions.ts
Labels: Author: Team, For Uncommitted Bug

#51770 Improve string literal completions for property values when a partially-typed string fixes inference to a type parameter
  src/services/stringCompletions.ts
  src/services/utilities.ts
  tests/cases/fourslash/completionsLiteralOnPropertyValueMatchingGeneric.ts
Labels: For Uncommitted Bug

#51729 fix(51716): "Find all references" do not find imported JSDoc types
  src/services/importTracker.ts
  tests/baselines/reference/findAllRefs_importType_js.4.baseline.jsonc
  tests/cases/fourslash/findAllRefs_importType_js.4.ts
Labels: For Backlog Bug

#51824 fix(51820): Using auto-accessor with readonly or declare should raise an error
  src/compiler/checker.ts
  tests/baselines/reference/autoAccessorDisallowedModifiers.errors.txt
  tests/baselines/reference/autoAccessorDisallowedModifiers.js
  tests/cases/conformance/classes/propertyMemberDeclarations/autoAccessorDisallowedModifiers.ts
Labels: For Backlog Bug

#51838 fix(51223): Go-to-definition for yield and await keyword; jump to respective function definition
  src/services/goToDefinition.ts
  tests/cases/fourslash/goToDefinitionAwait1.ts
  tests/cases/fourslash/goToDefinitionAwait2.ts
  tests/cases/fourslash/goToDefinitionAwait3.ts
  tests/cases/fourslash/goToDefinitionAwait4.ts
  tests/cases/fourslash/goToDefinitionYield1.ts
  tests/cases/fourslash/goToDefinitionYield2.ts
  tests/cases/fourslash/goToDefinitionYield3.ts
  tests/cases/fourslash/goToDefinitionYield4.ts
Labels: For Backlog Bug

#51978 Keep track of multiple current inference contexts
  src/compiler/checker.ts
  tests/baselines/reference/multipleInferenceContexts.js
  tests/baselines/reference/multipleInferenceContexts.symbols
  tests/baselines/reference/multipleInferenceContexts.types
  tests/cases/compiler/multipleInferenceContexts.ts
Labels: Author: Team, For Milestone Bug

#51897 Add undefined to JSON.stringify return type
  src/lib/es5.d.ts
  tests/baselines/reference/controlFlowPropertyDeclarations.symbols
  tests/baselines/reference/controlFlowPropertyDeclarations.types
  tests/baselines/reference/destructuringInitializerContextualTypeFromContext.symbols
  tests/baselines/reference/destructuringInitializerContextualTypeFromContext.types
  tests/baselines/reference/destructuringParameterDeclaration4.errors.txt
  tests/baselines/reference/destructuringTuple.errors.txt
  tests/baselines/reference/duplicateNumericIndexers.errors.txt
  tests/baselines/reference/json.stringify.js
  tests/baselines/reference/json.stringify.symbols
  tests/baselines/reference/json.stringify.types
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty.errors.txt
  tests/baselines/reference/parserharness.symbols
  tests/baselines/reference/parserharness.types
  tests/baselines/reference/promisePermutations.errors.txt
  tests/baselines/reference/promisePermutations2.errors.txt
  tests/baselines/reference/promisePermutations3.errors.txt
  tests/baselines/reference/redefineArray.errors.txt
  tests/baselines/reference/staticAnonymousTypeNotReferencingTypeParameter.symbols
  tests/baselines/reference/staticAnonymousTypeNotReferencingTypeParameter.types
  tests/cases/compiler/json.stringify.ts
Labels: For Backlog Bug

#51767 fix(51760): Nullish-coalescing assignment narrows type to assigned value
  src/compiler/checker.ts
  tests/baselines/reference/equalityWithtNullishCoalescingAssignment(strict=false).js
  tests/baselines/reference/equalityWithtNullishCoalescingAssignment(strict=false).symbols
  tests/baselines/reference/equalityWithtNullishCoalescingAssignment(strict=false).types
  tests/baselines/reference/equalityWithtNullishCoalescingAssignment(strict=true).js
  tests/baselines/reference/equalityWithtNullishCoalescingAssignment(strict=true).symbols
  tests/baselines/reference/equalityWithtNullishCoalescingAssignment(strict=true).types
  tests/cases/conformance/types/typeRelationships/comparable/equalityWithtNullishCoalescingAssignment.ts
Labels: For Backlog Bug

#50793 fix(29648): Error message related to JSDoc for non-JSDoc syntax error
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/parser.ts
  src/compiler/types.ts
  src/services/codefixes/fixJSDocTypes.ts
  tests/baselines/reference/decoratorMetadata-jsdoc.errors.txt
  tests/baselines/reference/expressionWithJSDocTypeArguments.errors.txt
  tests/baselines/reference/jsdocDisallowedInTypescript.errors.txt
  tests/baselines/reference/namedTupleMembersErrors.errors.txt
  tests/baselines/reference/parseInvalidNonNullableTypes.errors.txt
  tests/baselines/reference/parseInvalidNonNullableTypes.js
  tests/baselines/reference/parseInvalidNonNullableTypes.symbols
  tests/baselines/reference/parseInvalidNonNullableTypes.types
  tests/baselines/reference/parseInvalidNullableTypes.errors.txt
  tests/baselines/reference/parseInvalidNullableTypes.js
  tests/baselines/reference/parseInvalidNullableTypes.symbols
  tests/baselines/reference/parseInvalidNullableTypes.types
  tests/baselines/reference/restTupleElements1.errors.txt
  tests/baselines/reference/tsserver/plugins/getSupportedCodeFixes-can-be-proxied.js
  tests/cases/compiler/parseInvalidNonNullableTypes.ts
  tests/cases/compiler/parseInvalidNullableTypes.ts
  tests/cases/fourslash/codeFixChangeJSDocSyntax10.ts
  tests/cases/fourslash/codeFixChangeJSDocSyntax11.ts
  tests/cases/fourslash/codeFixChangeJSDocSyntax14.ts
  tests/cases/fourslash/codeFixChangeJSDocSyntax15.ts
  tests/cases/fourslash/codeFixChangeJSDocSyntax27.ts
  tests/cases/fourslash/codeFixChangeJSDocSyntax28.ts
  tests/cases/fourslash/codeFixChangeJSDocSyntax5.ts
  tests/cases/fourslash/codeFixChangeJSDocSyntax6.ts
  tests/cases/fourslash/codeFixChangeJSDocSyntax_all.ts
Labels: For Backlog Bug

#52052 Remove unused node flag
  src/compiler/types.ts
Labels: For Uncommitted Bug
