Repository microsoft/TypeScript, pull requests merged in 2022-01, with the labels that each got.

#46849 fix(46845): Add missing "locale" field to Intl.DisplayNamesOptions
  src/lib/es2020.intl.d.ts
Labels: For Backlog Bug

#47190 Control flow analysis for dependent parameters
  src/compiler/checker.ts
  tests/baselines/reference/dependentDestructuredVariables.js
  tests/baselines/reference/dependentDestructuredVariables.symbols
  tests/baselines/reference/dependentDestructuredVariables.types
  tests/cases/conformance/controlFlow/dependentDestructuredVariables.ts
Labels: Author: Team, For Uncommitted Bug

#46832 Gabritto/semicolons
  src/compiler/emitter.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/transformers/declarations.ts
  src/compiler/types.ts
  src/harness/fourslashImpl.ts
  src/harness/harnessLanguageService.ts
  src/server/session.ts
  src/services/completions.ts
  src/services/services.ts
  src/services/shims.ts
  src/services/stringCompletions.ts
  src/services/textChanges.ts
  src/services/types.ts
  src/services/utilities.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/completionsOverridingMethod11.ts
Labels: Author: Team, For Uncommitted Bug

#46418 Use node ipc for TS Server
  src/server/session.ts
  src/tsserver/nodeServer.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
Labels: For Uncommitted Bug

#47336 docs(common): url link format updated
  CONTRIBUTING.md
Labels: For Uncommitted Bug

#46747 Adds a github actions workflow which pings related repos with a blank commit
  .github/workflows/ensure-related-repos-run-crons.yml
Labels: Author: Team, Housekeeping, For Uncommitted Bug

#47341 Fix conditional type constraint exploration + signature relations
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug

#47088 Prevent merged class/namespace from overlapping with `Record<string, unknown>`
  src/compiler/checker.ts
  tests/baselines/reference/mergedClassNamespaceRecordCast.errors.txt
  tests/baselines/reference/mergedClassNamespaceRecordCast.js
  tests/baselines/reference/mergedClassNamespaceRecordCast.symbols
  tests/baselines/reference/mergedClassNamespaceRecordCast.types
  tests/cases/compiler/mergedClassNamespaceRecordCast.ts
Labels: Author: Team, For Milestone Bug

#46716 fix(46402): Add quick fix support for all valid strings for computed properties
  src/compiler/checker.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/services/codefixes/fixAddMissingMember.ts
  tests/cases/fourslash/codeFixAddMissingAttributes10.ts
  tests/cases/fourslash/codeFixAddMissingAttributes8.ts
  tests/cases/fourslash/codeFixAddMissingAttributes9.ts
  tests/cases/fourslash/codeFixAddMissingProperties15.ts
  tests/cases/fourslash/codeFixAddMissingProperties16.ts
Labels: For Backlog Bug

#47344 Use relative paths for the end of compile report
  src/compiler/types.ts
  src/compiler/watch.ts
  src/executeCommandLine/executeCommandLine.ts
  src/harness/harnessIO.ts
  src/testRunner/unittests/tsbuild/publicApi.ts
  src/testRunner/unittests/tscWatch/helpers.ts
  tests/baselines/reference/tsc/incremental/initial-build/noEmit-changes-composite.js
  tests/baselines/reference/tsc/incremental/initial-build/noEmit-changes-incremental-declaration.js
  tests/baselines/reference/tsc/incremental/initial-build/noEmit-changes-incremental.js
  tests/baselines/reference/tsc/incremental/initial-build/noEmit-changes-with-initial-noEmit-composite.js
  tests/baselines/reference/tsc/incremental/initial-build/noEmit-changes-with-initial-noEmit-incremental-declaration.js
  tests/baselines/reference/tsc/incremental/initial-build/noEmit-changes-with-initial-noEmit-incremental.js
  tests/baselines/reference/tsc/incremental/initial-build/when-global-file-is-added,-the-signatures-are-updated.js
Labels: Author: Team, For Uncommitted Bug

#47164 fix ATA toplevel dep detection
  src/jsTyping/jsTyping.ts
  src/testRunner/unittests/tsserver/typingsInstaller.ts
Labels: For Milestone Bug

#47348 Fix checker initialization crash with esModuleInterop and global merges resolving to ImportEquals aliases
  src/compiler/checker.ts
  tests/baselines/reference/checkerInitializationCrash.js
  tests/baselines/reference/checkerInitializationCrash.symbols
  tests/baselines/reference/checkerInitializationCrash.types
  tests/cases/compiler/checkerInitializationCrash.ts
Labels: Author: Team, For Uncommitted Bug

#47370 Add missing mapped type indexed access constraint
  src/compiler/checker.ts
  tests/baselines/reference/correlatedUnions.js
  tests/baselines/reference/correlatedUnions.symbols
  tests/baselines/reference/correlatedUnions.types
  tests/cases/compiler/correlatedUnions.ts
Labels: Author: Team, For Milestone Bug

#47386 Fix the related repos CI
  .github/workflows/ensure-related-repos-run-crons.yml
Labels: Author: Team, For Uncommitted Bug

#47092 Process package.json exports with auto-import provider
  src/compiler/moduleNameResolver.ts
  src/compiler/moduleSpecifiers.ts
  src/compiler/utilities.ts
  src/server/project.ts
  src/services/getEditsForFileRename.ts
  src/services/utilities.ts
  src/testRunner/unittests/tsserver/exportMapCache.ts
  src/testRunner/unittests/tsserver/moduleSpecifierCache.ts
  src/testRunner/unittests/tsserver/symlinkCache.ts
  tests/cases/fourslash/server/autoImportProvider8.ts
  tests/cases/fourslash/server/autoImportProvider_exportMap1.ts
  tests/cases/fourslash/server/autoImportProvider_exportMap2.ts
  tests/cases/fourslash/server/autoImportProvider_exportMap3.ts
  tests/cases/fourslash/server/autoImportProvider_exportMap4.ts
  tests/cases/fourslash/server/autoImportProvider_exportMap5.ts
  tests/cases/fourslash/server/autoImportProvider_exportMap6.ts
  tests/cases/fourslash/server/autoImportProvider_exportMap7.ts
  tests/cases/fourslash/server/autoImportProvider_exportMap8.ts
  tests/cases/fourslash/server/autoImportProvider_exportMap9.ts
  tests/cases/fourslash/server/completionsImport_mergedReExport.ts
Labels: Author: Team, For Milestone Bug

#47363 Avoid printing comments on static fields twice.
  src/compiler/transformers/classFields.ts
  src/testRunner/unittests/transform.ts
  tests/baselines/reference/transformApi/transformsCorrectly.transformSyntheticCommentOnStaticFieldInClassDeclaration.js
  tests/baselines/reference/transformApi/transformsCorrectly.transformSyntheticCommentOnStaticFieldInClassExpression.js
Labels: For Backlog Bug

#47375 Add names for refactoring functions.
  src/services/refactors/addOrRemoveBracesToArrowFunction.ts
  src/services/refactors/convertArrowFunctionOrFunctionExpression.ts
  src/services/refactors/convertExport.ts
  src/services/refactors/convertImport.ts
  src/services/refactors/convertOverloadListToSingleSignature.ts
  src/services/refactors/convertParamsToDestructuredObject.ts
  src/services/refactors/convertStringOrTemplateLiteral.ts
  src/services/refactors/convertToOptionalChainExpression.ts
  src/services/refactors/extractSymbol.ts
  src/services/refactors/extractType.ts
  src/services/refactors/generateGetAccessorAndSetAccessor.ts
  src/services/refactors/inferFunctionReturnType.ts
  src/services/refactors/moveToNewFile.ts
  src/testRunner/unittests/services/extract/helpers.ts
Labels: Author: Team, For Uncommitted Bug

#47395 Fix for crash in navbar with double ambient modules
  src/services/navigationBar.ts
  tests/cases/fourslash/navbarForDoubleAmbientModules01.ts
Labels: Author: Team, For Milestone Bug

#47411 Fix for crash for auto import completions with a rooted rootDirs entry
  src/compiler/moduleSpecifiers.ts
  tests/cases/fourslash/autoImportsWithRootDirsAndRootedPath01.ts
Labels: Author: Team, For Milestone Bug

#46913 fix(46406): Template literal types with decorator crashes in emit
  src/compiler/transformers/ts.ts
  tests/baselines/reference/decoratorOnClassProperty12.js
  tests/baselines/reference/decoratorOnClassProperty12.symbols
  tests/baselines/reference/decoratorOnClassProperty12.types
  tests/cases/conformance/decorators/class/property/decoratorOnClassProperty12.ts
Labels: For Milestone Bug

#47424 fix(47415): Code fix crash with incorrect JSDoc assertion
  src/services/codefixes/addConvertToUnknownForNonOverlappingTypes.ts
  tests/cases/fourslash/codeFixAddConvertToUnknownForNonOverlappingTypes9.ts
Labels: For Milestone Bug

#47418 Fix implicit glob detection when ancestor directory contains `.`
  src/compiler/commandLineParser.ts
  src/testRunner/unittests/config/tsconfigParsing.ts
Labels: Author: Team, For Milestone Bug

#47430 Fix type error in fourslash.ts
  tests/cases/fourslash/fourslash.ts
Labels: Author: Team, For Uncommitted Bug

#47412 Rewrite logic for JSX attribute completion detection
  src/services/completions.ts
  tests/cases/fourslash/jsxAttributeSnippetCompletionClosed.ts
  tests/cases/fourslash/jsxAttributeSnippetCompletionUnclosed.ts
  tests/cases/fourslash/jsxTagNameCompletionClosed.ts
  tests/cases/fourslash/jsxTagNameCompletionUnclosed.ts
  tests/cases/fourslash/jsxTagNameCompletionUnderElementClosed.ts
  tests/cases/fourslash/jsxTagNameCompletionUnderElementUnclosed.ts
Labels: Author: Team, For Milestone Bug

#47413 Rewrite logic for JSX attribute completion detection [4.5 cherry pick]
  src/services/completions.ts
  tests/cases/fourslash/jsxAttributeAsTagNameNoSnippet.ts
  tests/cases/fourslash/jsxAttributeSnippetCompletionClosed.ts
  tests/cases/fourslash/jsxAttributeSnippetCompletionUnclosed.ts
  tests/cases/fourslash/jsxTagNameCompletionClosed.ts
  tests/cases/fourslash/jsxTagNameCompletionUnclosed.ts
  tests/cases/fourslash/jsxTagNameCompletionUnderElementClosed.ts
  tests/cases/fourslash/jsxTagNameCompletionUnderElementUnclosed.ts
Labels: Author: Team, For Uncommitted Bug

#47432 Deprioritize import paths made up of only dots and slashes
  src/services/codefixes/importFixes.ts
  tests/cases/fourslash/importNameCodeFix_barrelExport.ts
Labels: Author: Team, For Milestone Bug

#47449 fix(47417): Code fix crash in JSDoc with strictPropertyInitialization
  src/services/codefixes/fixStrictClassInitialization.ts
  src/services/textChanges.ts
  tests/cases/fourslash/codeFixClassPropertyInitialization14.ts
  tests/cases/fourslash/codeFixClassPropertyInitialization15.ts
  tests/cases/fourslash/codeFixClassPropertyInitialization16.ts
  tests/cases/fourslash/codeFixClassPropertyInitialization_all_4.ts
Labels: For Milestone Bug

#43396 Make Map constructor argument optional and nullable
  src/lib/es2015.iterable.d.ts
  tests/baselines/reference/for-of39.errors.txt
  tests/baselines/reference/iterableArrayPattern28.errors.txt
  tests/baselines/reference/mapConstructor.js
  tests/baselines/reference/mapConstructor.symbols
  tests/baselines/reference/mapConstructor.types
  tests/baselines/reference/newMap.types
  tests/cases/compiler/mapConstructor.ts
Labels: For Backlog Bug

#47467 feat(47439): Suggestion: omit void 0 from output of new JSX transform (react-jsx)
  src/compiler/transformers/jsx.ts
  tests/baselines/reference/commentsOnJSXExpressionsArePreserved(jsx=react-jsx,module=commonjs).js
  tests/baselines/reference/commentsOnJSXExpressionsArePreserved(jsx=react-jsx,module=system).js
  tests/baselines/reference/jsxEmptyExpressionNotCountedAsChild(jsx=react-jsx).js
  tests/baselines/reference/jsxJsxsCjsTransformChildren(jsx=react-jsx).js
  tests/baselines/reference/jsxJsxsCjsTransformCustomImport(jsx=react-jsx).js
  tests/baselines/reference/jsxJsxsCjsTransformCustomImportPragma(jsx=react-jsx).js
  tests/baselines/reference/jsxJsxsCjsTransformNestedSelfClosingChild(jsx=react-jsx).js
  tests/baselines/reference/jsxJsxsCjsTransformSubstitutesNames(jsx=react-jsx).js
  tests/baselines/reference/jsxJsxsCjsTransformSubstitutesNamesFragment(jsx=react-jsx).js
  tests/baselines/reference/jsxNamespaceGlobalReexport.js
  tests/baselines/reference/jsxNamespaceGlobalReexportMissingAliasTarget.js
  tests/baselines/reference/jsxNamespaceImplicitImportJSXNamespace.js
  tests/baselines/reference/jsxNamespaceImplicitImportJSXNamespaceFromConfigPickedOverGlobalOne(jsx=react-jsx).js
  tests/baselines/reference/jsxNamespaceImplicitImportJSXNamespaceFromPragmaPickedOverGlobalOne.js
  tests/baselines/reference/reactImportUnusedInNewJSXEmit(jsx=react-jsx).js
  tests/baselines/reference/reactJsxReactResolvedNodeNext.js
  tests/baselines/reference/reactJsxReactResolvedNodeNextEsm.js
  tests/baselines/reference/tsc/react-jsx-emit-mode/initial-build/with-no-backing-types-found-doesn't-crash-under---strict.js
  tests/baselines/reference/tsc/react-jsx-emit-mode/initial-build/with-no-backing-types-found-doesn't-crash.js
  tests/baselines/reference/tscWatch/forceConsistentCasingInFileNames/jsxImportSource-option-changed.js
  tests/baselines/reference/tscWatch/incremental/jsxImportSource-backing-types-added-incremental.js
  tests/baselines/reference/tscWatch/incremental/jsxImportSource-backing-types-added-watch.js
  tests/baselines/reference/tscWatch/incremental/jsxImportSource-backing-types-removed-incremental.js
  tests/baselines/reference/tscWatch/incremental/jsxImportSource-backing-types-removed-watch.js
  tests/baselines/reference/tscWatch/incremental/jsxImportSource-option-changed-incremental.js
  tests/baselines/reference/tscWatch/incremental/jsxImportSource-option-changed-watch.js
  tests/baselines/reference/tsxReactEmit8(jsx=react-jsx).js
  tests/baselines/reference/tsxReactEmit8(jsx=react-jsx).symbols
  tests/baselines/reference/tsxReactEmit8(jsx=react-jsx).types
  tests/baselines/reference/tsxReactEmit8(jsx=react-jsxdev).js
  tests/baselines/reference/tsxReactEmit8(jsx=react-jsxdev).symbols
  tests/baselines/reference/tsxReactEmit8(jsx=react-jsxdev).types
  tests/baselines/reference/tsxReactEmitSpreadAttribute(target=es2015).js
  tests/baselines/reference/tsxReactEmitSpreadAttribute(target=es2018).js
  tests/baselines/reference/tsxReactEmitSpreadAttribute(target=esnext).js
  tests/baselines/reference/tsxSpreadChildrenInvalidType(jsx=react-jsx,target=es2015).js
  tests/baselines/reference/tsxSpreadChildrenInvalidType(jsx=react-jsx,target=es5).js
  tests/cases/conformance/jsx/tsxReactEmit8.tsx
Labels: For Backlog Bug

#47049 Bind RHS of comma expressions too
  src/compiler/binder.ts
  tests/baselines/reference/controlFlowCommaExpressionAssertionMultiple.js
  tests/baselines/reference/controlFlowCommaExpressionAssertionMultiple.symbols
  tests/baselines/reference/controlFlowCommaExpressionAssertionMultiple.types
  tests/cases/compiler/controlFlowCommaExpressionAssertionMultiple.ts
Labels: Author: Team, For Milestone Bug

#47460 fix(47438): No auto-complete for 'this.' or the class inside static blocks
  src/services/completions.ts
  tests/cases/fourslash/completionListInClassStaticBlocks.ts
Labels: For Backlog Bug

#47388 Better reuse of package.json cache, module resolution cache, and package.json auto import filter
  src/compiler/checker.ts
  src/compiler/moduleSpecifiers.ts
  src/compiler/types.ts
  src/server/project.ts
  src/services/codefixes/importFixes.ts
  src/services/completions.ts
  src/services/services.ts
  src/services/types.ts
  src/services/utilities.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
Labels: Author: Team, For Uncommitted Bug

#47414 Deprecate ScriptElementKind.jsxAttribute
  src/services/symbolDisplay.ts
  src/services/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/completionsInJsxTag.ts
  tests/cases/fourslash/completionsJsxAttribute.ts
  tests/cases/fourslash/completionsJsxAttributeGeneric.ts
  tests/cases/fourslash/completionsJsxAttributeInitializer.ts
  tests/cases/fourslash/jsxAttributeSnippetCompletionClosed.ts
  tests/cases/fourslash/jsxAttributeSnippetCompletionUnclosed.ts
  tests/cases/fourslash/jsxGenericQuickInfo.tsx
  tests/cases/fourslash/jsxTagNameCompletionClosed.ts
  tests/cases/fourslash/jsxTagNameCompletionUnclosed.ts
  tests/cases/fourslash/jsxTagNameCompletionUnderElementClosed.ts
  tests/cases/fourslash/jsxTagNameCompletionUnderElementUnclosed.ts
  tests/cases/fourslash/tsxCompletion12.ts
  tests/cases/fourslash/tsxCompletion13.ts
  tests/cases/fourslash/tsxCompletion7.ts
  tests/cases/fourslash/tsxQuickInfo3.ts
  tests/cases/fourslash/tsxQuickInfo4.ts
  tests/cases/fourslash/tsxQuickInfo5.ts
Labels: Author: Team, For Uncommitted Bug

#47493 fix(47451): Implicit 'any' quick fix text grabs text from wrong file
  src/services/codefixes/inferFromUsage.ts
  tests/cases/fourslash/codeFixInferFromUsageVariable5.ts
Labels: For Uncommitted Bug

#47345 Do not show the additional file/errors table when there's 1 file with many errors
  src/compiler/diagnosticMessages.json
  src/compiler/watch.ts
  tests/baselines/reference/deeplyNestedAssignabilityIssue.errors.txt
  tests/baselines/reference/duplicateIdentifierRelatedSpans1.errors.txt
  tests/baselines/reference/duplicateIdentifierRelatedSpans2.errors.txt
  tests/baselines/reference/duplicateIdentifierRelatedSpans3.errors.txt
  tests/baselines/reference/duplicateIdentifierRelatedSpans4.errors.txt
  tests/baselines/reference/duplicateIdentifierRelatedSpans5.errors.txt
  tests/baselines/reference/duplicateIdentifierRelatedSpans6.errors.txt
  tests/baselines/reference/duplicateIdentifierRelatedSpans7.errors.txt
  tests/baselines/reference/esModuleInteropPrettyErrorRelatedInformation.errors.txt
  tests/baselines/reference/manyCompilerErrorsInTheTwoFiles.errors.txt
  tests/baselines/reference/multiLineContextDiagnosticWithPretty.errors.txt
  tests/baselines/reference/prettyContextNotDebugAssertion.errors.txt
  tests/baselines/reference/prettyFileWithErrorsAndTabs.errors.txt
  tests/baselines/reference/tsc/composite/initial-build/when-setting-composite-false-on-command-line-but-has-tsbuild-info-in-config.js
  tests/baselines/reference/tsc/declarationEmit/when-pkg-references-sibling-package-through-indirect-symlink-moduleCaseChange.js
  tests/baselines/reference/tsc/declarationEmit/when-pkg-references-sibling-package-through-indirect-symlink.js
  tests/baselines/reference/tsc/incremental/initial-build/noEmit-changes-composite.js
  tests/baselines/reference/tsc/incremental/initial-build/noEmit-changes-incremental-declaration.js
  tests/baselines/reference/tsc/incremental/initial-build/noEmit-changes-incremental.js
  tests/baselines/reference/tsc/incremental/initial-build/noEmit-changes-with-initial-noEmit-composite.js
  tests/baselines/reference/tsc/incremental/initial-build/noEmit-changes-with-initial-noEmit-incremental-declaration.js
  tests/baselines/reference/tsc/incremental/initial-build/noEmit-changes-with-initial-noEmit-incremental.js
  tests/baselines/reference/tsc/incremental/initial-build/when-global-file-is-added,-the-signatures-are-updated.js
  tests/baselines/reference/tsc/incremental/initial-build/with-noEmitOnError-semantic-errors.js
  tests/baselines/reference/tsc/incremental/initial-build/with-noEmitOnError-syntax-errors.js
  tests/baselines/reference/tsc/projectReferences/initial-build/when-project-contains-invalid-project-reference.js
  tests/baselines/reference/tsc/projectReferences/initial-build/when-project-references-composite-project-with-noEmit.js
  tests/baselines/reference/tsc/react-jsx-emit-mode/initial-build/with-no-backing-types-found-doesn't-crash-under---strict.js
  tests/baselines/reference/tscWatch/incremental/editing-module-augmentation-incremental.js
  tests/baselines/reference/tscWatch/incremental/importHelpers-backing-types-removed-incremental.js
  tests/baselines/reference/tscWatch/incremental/jsxImportSource-backing-types-added-incremental.js
  tests/baselines/reference/tscWatch/incremental/jsxImportSource-backing-types-removed-incremental.js
  tests/baselines/reference/tscWatch/incremental/jsxImportSource-option-changed-incremental.js
  tests/baselines/reference/tscWatch/incremental/module-compilation/own-file-emit-with-errors-incremental.js
  tests/baselines/reference/tscWatch/incremental/own-file-emit-with-errors-incremental.js
  tests/baselines/reference/tscWatch/incremental/when-file-with-ambient-global-declaration-file-is-deleted-incremental.js
  tests/baselines/reference/typedefCrossModule5.errors.txt
Labels: Author: Team, For Uncommitted Bug

#47507 Remove abort from the abort signal
  src/lib/dom.generated.d.ts
Labels: Author: Team, For Uncommitted Bug

#47500 Modify debug assertion to avoid crashing on SyntaxList
  src/services/utilities.ts
  tests/cases/fourslash/quickInfoOnClosingJsx.ts
Labels: Author: Team, For Milestone Bug, For Backlog Bug

#47433 Avoid crash for import code fixes with dotted require
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/services/codefixes/importFixes.ts
  src/services/findAllReferences.ts
  src/services/goToDefinition.ts
  src/services/importTracker.ts
  tests/cases/fourslash/importFixesWithExistingDottedRequire.ts
Labels: Author: Team, For Milestone Bug

#47504 fix(47492): more detailed parseTryStatement error message
  src/compiler/diagnosticMessages.json
  src/compiler/parser.ts
  tests/baselines/reference/invalidTryStatements.errors.txt
Labels: For Uncommitted Bug

#47491 Avoid global mutations
  src/compiler/sys.ts
  src/compiler/utilities.ts
  src/services/services.ts
Labels: Author: Team, For Uncommitted Bug

#47522 Add a comment to `maybeSetLocalizedDiagnosticMessages`
  src/compiler/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#47535 Fix import assertion occurrences crash
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/factory/nodeFactory.ts
  src/compiler/parser.ts
  src/compiler/types.ts
  src/compiler/visitorPublic.ts
  src/services/findAllReferences.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/importAssertionNonstring.errors.txt
  tests/baselines/reference/importAssertionNonstring.js
  tests/baselines/reference/importAssertionNonstring.symbols
  tests/baselines/reference/importAssertionNonstring.types
  tests/cases/compiler/importAssertionNonstring.ts
  tests/cases/fourslash/getOccurrencesNonStringImportAssertion.ts
Labels: Author: Team, For Uncommitted Bug

#47530 Associate paths with nodes when tracing
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/tracing.ts
Labels: Author: Team, For Uncommitted Bug

#47434 Fixed Go To Definition using jsconfig
  src/compiler/checker.ts
  tests/baselines/reference/checkJsxNotSetError.errors.txt
  tests/baselines/reference/checkJsxNotSetError.js
  tests/baselines/reference/checkJsxNotSetError.symbols
  tests/baselines/reference/checkJsxNotSetError.types
  tests/cases/compiler/checkJsxNotSetError.ts
  tests/cases/fourslash/goToDefinitionJsxNotSet.ts
Labels: Author: Team, For Milestone Bug

#47527 fix(47524): Assertion crash in code fix for "infer type of 'this'"
  src/services/codefixes/fixImplicitThis.ts
  tests/cases/fourslash/codeFixImplicitThis_ts_functionDeclarationInGlobalScope.ts
Labels: For Uncommitted Bug

#47463 fix(47435): return early from `fixUnreachableCode` if syntactic errors exists
  src/services/codefixes/fixUnreachableCode.ts
Labels: For Backlog Bug

#47541 fix(47165): from keyword can get hover definition in import ... from ''; statement
  src/services/goToDefinition.ts
  tests/cases/fourslash/goToDefinitionImport1.ts
  tests/cases/fourslash/goToDefinitionImport2.ts
  tests/cases/fourslash/goToDefinitionImport3.ts
Labels: For Backlog Bug

#47545 Fix parser test cases missing 'it' calls
  src/testRunner/unittests/jsDocParsing.ts
Labels: Author: Team, For Uncommitted Bug

#47483 Fix narrowing of intersection with function type
  src/compiler/checker.ts
  tests/baselines/reference/narrowingTypeofFunction.js
  tests/baselines/reference/narrowingTypeofFunction.symbols
  tests/baselines/reference/narrowingTypeofFunction.types
  tests/cases/compiler/narrowingTypeofFunction.ts
Labels: Author: Team, For Milestone Bug

#47409 Fix detecting an existing `Map`/`Set`
  src/compiler/corePublic.ts
Labels: Author: Team, For Uncommitted Bug

#47472 Allow structure reuse if a declaration file within a package is updated
  src/compiler/program.ts
  src/compiler/utilities.ts
  src/testRunner/unittests/reuseProgramStructure.ts
Labels: For Backlog Bug

#47602 Don't trace bindSourceFile cache hits
  src/compiler/binder.ts
Labels: Author: Team, For Uncommitted Bug

#47293 feat(42684): Override JSDoc for re-exported types / enum / classes / interfaces
  src/compiler/checker.ts
  src/compiler/parser.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/jsdocDeprecated_suggestion14.ts
  tests/cases/fourslash/jsdocDeprecated_suggestion15.ts
  tests/cases/fourslash/jsdocDeprecated_suggestion16.ts
Labels: For Backlog Bug

#47609 fix(47561): bad declaration emit for rebound type parameter name
  src/compiler/checker.ts
  tests/baselines/reference/typeParametersAvailableInNestedScope3.js
  tests/baselines/reference/typeParametersAvailableInNestedScope3.symbols
  tests/baselines/reference/typeParametersAvailableInNestedScope3.types
  tests/cases/conformance/types/typeParameters/typeParameterLists/typeParametersAvailableInNestedScope3.ts
Labels: For Milestone Bug

#47604 Fix diagnostic serialization crash
  src/compiler/checker.ts
  src/compiler/utilities.ts
  src/testRunner/unittests/tsc/incremental.ts
  tests/baselines/reference/tsc/incremental/initial-build/serializing-error-chains.js
Labels: Author: Team, For Uncommitted Bug

#47623 Update DOM 2022-01-26
  src/lib/dom.generated.d.ts
  src/lib/dom.iterable.generated.d.ts
  src/lib/webworker.generated.d.ts
  tests/baselines/reference/baseCheck.errors.txt
  tests/baselines/reference/extendArray.errors.txt
  tests/baselines/reference/globalThisBlockscopedProperties.types
  tests/baselines/reference/intersectionsOfLargeUnions2.errors.txt
  tests/baselines/reference/jsxFactoryIdentifierWithAbsentParameter.errors.txt
  tests/baselines/reference/jsxFactoryQualifiedNameResolutionError.errors.txt
  tests/baselines/reference/mappedTypeRecursiveInference.errors.txt
  tests/baselines/reference/mappedTypeRecursiveInference.types
Labels: Author: Team, For Uncommitted Bug

#47287 fix: enum self reference
  src/compiler/checker.ts
  tests/baselines/reference/constEnumErrors.errors.txt
  tests/baselines/reference/enumBasics2.errors.txt
  tests/baselines/reference/enumBasics2.js
  tests/baselines/reference/enumBasics2.symbols
  tests/baselines/reference/enumBasics2.types
  tests/baselines/reference/enumBasics3.errors.txt
  tests/baselines/reference/enumBasics3.js
  tests/baselines/reference/enumBasics3.symbols
  tests/baselines/reference/enumBasics3.types
  tests/cases/compiler/enumBasics2.ts
  tests/cases/compiler/enumBasics3.ts
Labels: For Backlog Bug

#47501 Don't block completion after end of type parameters in JSX elements
  src/services/completions.ts
  tests/cases/fourslash/jsxAttributeSnippetCompletionAfterTypeArgs.ts
Labels: Author: Team, For Uncommitted Bug

#47552 Add codefix and completions for promoting existing type-only imports to non-type-only
  src/compiler/diagnosticMessages.json
  src/compiler/types.ts
  src/services/codefixes/importFixes.ts
  src/services/completions.ts
  src/services/textChanges.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/completionsImport_promoteTypeOnly1.ts
  tests/cases/fourslash/completionsImport_promoteTypeOnly2.ts
  tests/cases/fourslash/completionsImport_promoteTypeOnly3.ts
  tests/cases/fourslash/completionsImport_promoteTypeOnly4.ts
  tests/cases/fourslash/completionsImport_promoteTypeOnly5.ts
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/importNameCodeFix_importType5.ts
  tests/cases/fourslash/importNameCodeFix_importType6.ts
  tests/cases/fourslash/importNameCodeFix_importType7.ts
  tests/cases/fourslash/importNameCodeFix_importType8.ts
Labels: Author: Team, For Milestone Bug

#47625 Allow moduleSymbolToValidIdentifier to be uppercase for JSX tags
  src/services/codefixes/importFixes.ts
  src/services/completions.ts
  src/services/exportInfoMap.ts
  src/services/utilities.ts
  src/testRunner/unittests/tsserver/exportMapCache.ts
  tests/cases/fourslash/completionsImport_jsxOpeningTagImportDefault.ts
  tests/cases/fourslash/importNameCodeFix_jsxOpeningTagImportDefault.ts
Labels: Author: Team, For Milestone Bug

#47643 Revert to temporary AbortSignal fix
  src/lib/dom.generated.d.ts
Labels: Author: Team, For Uncommitted Bug

#47584 Fix duplicate completions from two different copies of a node_modules package
  src/compiler/moduleSpecifiers.ts
  src/compiler/utilities.ts
  src/services/exportInfoMap.ts
  tests/cases/fourslash/completionsImport_duplicatePackages_scoped.ts
  tests/cases/fourslash/completionsImport_duplicatePackages_scopedTypes.ts
  tests/cases/fourslash/completionsImport_duplicatePackages_scopedTypesAndNotTypes.ts
  tests/cases/fourslash/completionsImport_duplicatePackages_types.ts
  tests/cases/fourslash/completionsImport_duplicatePackages_typesAndNotTypes.ts
Labels: Author: Team, For Milestone Bug

#47644 Add `assert` keyword in completions
  src/services/completions.ts
  tests/cases/fourslash/completionsAssertKeyword.ts
Labels: Author: Team, For Milestone Bug

#47642 Allow usage of local value symbol merged with type-only import
  src/compiler/checker.ts
  tests/baselines/reference/mergedWithLocalValue.js
  tests/baselines/reference/mergedWithLocalValue.symbols
  tests/baselines/reference/mergedWithLocalValue.types
  tests/cases/conformance/externalModules/typeOnly/mergedWithLocalValue.ts
Labels: Author: Team, For Milestone Bug

#47647 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220128061813234 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#47649 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220128121413131 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#47596 fix(47582): Debug assertion violation for extract type refactoring
  src/services/refactors/extractType.ts
  tests/cases/fourslash/refactorExtractType72.ts
  tests/cases/fourslash/refactorExtractType73.ts
  tests/cases/fourslash/refactorExtractType74.ts
  tests/cases/fourslash/refactorExtractType75.ts
Labels: For Uncommitted Bug

#46821 Fix confusing file name in generated diagnostics file
  scripts/processDiagnosticMessages.ts
Labels: Housekeeping, For Uncommitted Bug

#47655 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220129001417568 to main
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#47198 Remove unused errors/branches in checkGrammarModifiers
  src/compiler/checker.ts
Labels: Housekeeping, For Uncommitted Bug

#47192 Update terminal.integrated.shell.linux config in devcontainer.json
  .devcontainer/devcontainer.json
Labels: Housekeeping, For Uncommitted Bug

#47659 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220129181512427 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#47666 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220130181915444 to main
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#47675 Manual revert of AbortSignal.abort in webworker.generated.d.ts
  src/lib/webworker.generated.d.ts
Labels: Author: Team, For Uncommitted Bug
