Repository microsoft/TypeScript, pull requests merged in 2022-06, with the labels that each got.

#49330 Use NonNullable<T> in more scenarios
  src/compiler/checker.ts
  tests/baselines/reference/discriminatedUnionJsxElement.types
  tests/baselines/reference/mappedTypes4.types
  tests/baselines/reference/neverType.js
  tests/baselines/reference/neverType.types
  tests/baselines/reference/nonNullParameterExtendingStringAssignableToString.types
  tests/baselines/reference/nonNullableTypes1.js
  tests/baselines/reference/nonNullableTypes1.symbols
  tests/baselines/reference/nonNullableTypes1.types
  tests/baselines/reference/nullishCoalescingOperator2.types
  tests/baselines/reference/nullishCoalescingOperator_es2020.types
  tests/baselines/reference/privateIdentifierChain.1.types
  tests/baselines/reference/simplifyingConditionalWithInteriorConditionalIsRelated.types
  tests/cases/compiler/nonNullableTypes1.ts
Labels: Author: Team, For Uncommitted Bug

#41042 Remove `undefined` from source type of renaming destructuring assignment with default
  src/compiler/checker.ts
  tests/baselines/reference/destructuringAssignmentWithDefault2.errors.txt
  tests/baselines/reference/destructuringAssignmentWithDefault2.js
  tests/baselines/reference/destructuringAssignmentWithDefault2.symbols
  tests/baselines/reference/destructuringAssignmentWithDefault2.types
  tests/cases/compiler/destructuringAssignmentWithDefault2.ts
Labels: For Backlog Bug

#49313 fix(49306): Missing Compiler API predicate functions: isImportTypeAssertionContainer
  src/compiler/factory/nodeTests.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Milestone Bug

#49361 Use node's algorithm for calculating the longest matching export/import pattern
  src/compiler/moduleNameResolver.ts
  tests/baselines/reference/nodeModulesAllowJsPackagePatternExportsExclude(module=node16).errors.txt
  tests/baselines/reference/nodeModulesAllowJsPackagePatternExportsExclude(module=node16).js
  tests/baselines/reference/nodeModulesAllowJsPackagePatternExportsExclude(module=node16).symbols
  tests/baselines/reference/nodeModulesAllowJsPackagePatternExportsExclude(module=node16).types
  tests/baselines/reference/nodeModulesAllowJsPackagePatternExportsExclude(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesAllowJsPackagePatternExportsExclude(module=nodenext).js
  tests/baselines/reference/nodeModulesAllowJsPackagePatternExportsExclude(module=nodenext).symbols
  tests/baselines/reference/nodeModulesAllowJsPackagePatternExportsExclude(module=nodenext).types
  tests/baselines/reference/nodeModulesPackagePatternExportsExclude(module=node16).errors.txt
  tests/baselines/reference/nodeModulesPackagePatternExportsExclude(module=node16).js
  tests/baselines/reference/nodeModulesPackagePatternExportsExclude(module=node16).symbols
  tests/baselines/reference/nodeModulesPackagePatternExportsExclude(module=node16).types
  tests/baselines/reference/nodeModulesPackagePatternExportsExclude(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesPackagePatternExportsExclude(module=nodenext).js
  tests/baselines/reference/nodeModulesPackagePatternExportsExclude(module=nodenext).symbols
  tests/baselines/reference/nodeModulesPackagePatternExportsExclude(module=nodenext).types
  tests/cases/conformance/node/allowJs/nodeModulesAllowJsPackagePatternExportsExclude.ts
  tests/cases/conformance/node/nodeModulesPackagePatternExportsExclude.ts
Labels: Author: Team, For Milestone Bug

#49365 Pick PR #49356 (Add nightly-only error on ImportType resolution mode assertion) into release-4.7
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/program.ts
  src/compiler/transformers/declarations.ts
  src/compiler/types.ts
  tests/baselines/reference/nodeModulesDeclarationEmitDynamicImportWithPackageExports.errors.txt
  tests/baselines/reference/nodeModulesDeclarationEmitDynamicImportWithPackageExports.js
  tests/baselines/reference/nodeModulesImportModeDeclarationEmit1(module=node16).errors.txt
  tests/baselines/reference/nodeModulesImportModeDeclarationEmit1(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesImportModeDeclarationEmit2(module=node16).errors.txt
  tests/baselines/reference/nodeModulesImportModeDeclarationEmit2(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesImportModeDeclarationEmitErrors1(module=node16).errors.txt
  tests/baselines/reference/nodeModulesImportModeDeclarationEmitErrors1(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesImportTypeModeDeclarationEmit1(module=node16).errors.txt
  tests/baselines/reference/nodeModulesImportTypeModeDeclarationEmit1(module=node16).js
  tests/baselines/reference/nodeModulesImportTypeModeDeclarationEmit1(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesImportTypeModeDeclarationEmit1(module=nodenext).js
  tests/baselines/reference/nodeModulesImportTypeModeDeclarationEmitErrors1(module=node16).errors.txt
  tests/baselines/reference/nodeModulesImportTypeModeDeclarationEmitErrors1(module=node16).js
  tests/baselines/reference/nodeModulesImportTypeModeDeclarationEmitErrors1(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesImportTypeModeDeclarationEmitErrors1(module=nodenext).js
  tests/baselines/reference/nodeModulesTripleSlashReferenceModeOverrideOldResolutionError.errors.txt
Labels: Author: Team, For Uncommitted Bug

#49284 fix(49223): checker.getTypeAtLocation for ExpressionWithTypeArguments returns an error any type
  src/compiler/utilities.ts
  src/testRunner/unittests/publicApi.ts
  tests/baselines/reference/genericCallWithoutArgs.types
  tests/baselines/reference/importWithTypeArguments.types
  tests/baselines/reference/instantiationExpressionErrors.types
  tests/baselines/reference/instantiationExpressions.types
  tests/baselines/reference/parserMemberAccessExpression1.types
  tests/baselines/reference/parserMemberAccessOffOfGenericType1.types
Labels: For Milestone Bug

#49369 Cherry pick #49284 to release-4.7
  src/compiler/utilities.ts
  src/testRunner/unittests/publicApi.ts
  tests/baselines/reference/genericCallWithoutArgs.types
  tests/baselines/reference/importWithTypeArguments.types
  tests/baselines/reference/instantiationExpressionErrors.types
  tests/baselines/reference/instantiationExpressions.types
  tests/baselines/reference/parserMemberAccessExpression1.types
  tests/baselines/reference/parserMemberAccessOffOfGenericType1.types
Labels: Author: Team, For Uncommitted Bug

#49360 Expose import mode calculation functions
  src/compiler/program.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Milestone Bug

#48669 Move legacy decorators into separate transform
  src/compiler/factory/nodeFactory.ts
  src/compiler/factory/utilities.ts
  src/compiler/transformer.ts
  src/compiler/transformers/legacyDecorators.ts
  src/compiler/transformers/ts.ts
  src/compiler/transformers/typeSerializer.ts
  src/compiler/transformers/utilities.ts
  src/compiler/tsconfig.json
  src/compiler/types.ts
  src/compiler/utilities.ts
  tests/baselines/reference/sourceMapValidationDecorators.js.map
  tests/baselines/reference/sourceMapValidationDecorators.sourcemap.txt
Labels: Author: Team, For Uncommitted Bug

#49380 Explicit `types` should prevent ATA from doing package.json discovery
  src/jsTyping/jsTyping.ts
  src/services/shims.ts
  src/testRunner/unittests/tsserver/typingsInstaller.ts
  src/typingsInstallerCore/typingsInstaller.ts
Labels: Author: Team, For Milestone Bug

#47822 [Experiment] feat(47558): Warning 6133 ignores @link tags
  src/compiler/checker.ts
  tests/baselines/reference/jsdocLinkTag1.js
  tests/baselines/reference/jsdocLinkTag1.symbols
  tests/baselines/reference/jsdocLinkTag1.types
  tests/baselines/reference/jsdocLinkTag2.symbols
  tests/baselines/reference/jsdocLinkTag2.types
  tests/baselines/reference/jsdocLinkTag3.js
  tests/baselines/reference/jsdocLinkTag3.symbols
  tests/baselines/reference/jsdocLinkTag3.types
  tests/baselines/reference/jsdocLinkTag4.js
  tests/baselines/reference/jsdocLinkTag4.symbols
  tests/baselines/reference/jsdocLinkTag4.types
  tests/baselines/reference/jsdocLinkTag5.js
  tests/baselines/reference/jsdocLinkTag5.symbols
  tests/baselines/reference/jsdocLinkTag5.types
  tests/cases/conformance/jsdoc/jsdocLinkTag1.ts
  tests/cases/conformance/jsdoc/jsdocLinkTag2.ts
  tests/cases/conformance/jsdoc/jsdocLinkTag3.ts
  tests/cases/conformance/jsdoc/jsdocLinkTag4.ts
  tests/cases/conformance/jsdoc/jsdocLinkTag5.ts
Labels: For Backlog Bug

#49387 Fix definite assignment analysis issue caused by `x !== null` checks
  src/compiler/checker.ts
  tests/baselines/reference/unknownControlFlow.errors.txt
  tests/baselines/reference/unknownControlFlow.js
  tests/baselines/reference/unknownControlFlow.symbols
  tests/baselines/reference/unknownControlFlow.types
  tests/cases/conformance/types/unknown/unknownControlFlow.ts
Labels: Author: Team, For Milestone Bug

#49403 Use symbolic GitHub Actions Node.js versions
  .github/workflows/accept-baselines-fix-lints.yaml
  .github/workflows/ci.yml
  .github/workflows/new-release-branch.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release-branch-artifact.yaml
  .github/workflows/rich-navigation.yml
  .github/workflows/set-version.yaml
  .github/workflows/sync-branch.yaml
  .github/workflows/twoslash-repros.yaml
  .github/workflows/update-lkg.yml
  .github/workflows/update-package-lock.yaml
Labels: For Uncommitted Bug

#49410 Replace ts.hasOwnProperty.call(...) with hasProperty(...)
  src/services/documentRegistry.ts
Labels: Author: Team, For Uncommitted Bug

#49422 Revise and simplify CFA for `typeof` check expressions
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypes4.types
  tests/baselines/reference/typeGuardOfFormTypeOfFunction.js
  tests/baselines/reference/typeGuardOfFormTypeOfFunction.symbols
  tests/baselines/reference/typeGuardOfFormTypeOfFunction.types
  tests/baselines/reference/typeGuardTypeOfUndefined.types
  tests/baselines/reference/unknownControlFlow.types
  tests/cases/conformance/expressions/typeGuards/typeGuardOfFormTypeOfFunction.ts
Labels: Author: Team, For Milestone Bug

#49407 Give cjs export assigned types an alias symbol
  src/compiler/checker.ts
  tests/baselines/reference/jsDeclarationEmitExportAssignedArray.js
  tests/baselines/reference/jsDeclarationEmitExportAssignedArray.symbols
  tests/baselines/reference/jsDeclarationEmitExportAssignedArray.types
  tests/baselines/reference/jsDeclarationsImportTypeBundled.types
  tests/baselines/reference/jsDeclarationsTypeReassignmentFromDeclaration.types
  tests/baselines/reference/jsDeclarationsTypeReassignmentFromDeclaration2.types
  tests/cases/compiler/jsDeclarationEmitExportAssignedArray.ts
Labels: Author: Team, For Milestone Bug

#49440 Serialize inaccessible class declarations the same as class expressions in declaration emit
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitClassMixinLocalClassDeclaration.js
  tests/baselines/reference/declarationEmitClassMixinLocalClassDeclaration.symbols
  tests/baselines/reference/declarationEmitClassMixinLocalClassDeclaration.types
  tests/baselines/reference/jsDeclarationsParameterTagReusesInputNodeInEmit1.errors.txt
  tests/baselines/reference/jsDeclarationsParameterTagReusesInputNodeInEmit1.js
  tests/cases/compiler/declarationEmitClassMixinLocalClassDeclaration.ts
  tests/cases/fourslash/getDeclarationDiagnostics.ts
  tests/cases/fourslash/getSemanticDiagnosticForDeclaration.ts
  tests/cases/fourslash/shims-pp/getSemanticDiagnostics.ts
  tests/cases/fourslash/shims/getSemanticDiagnostics.ts
Labels: Author: Team, For Milestone Bug

#49455 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220609122601266 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#49442 Avoid repeating codefix work when resolving auto-import specifiers for completions
  src/services/codefixes/importFixes.ts
  src/services/completions.ts
Labels: Author: Team, For Uncommitted Bug

#49353 Instantiation expression can be followed by line break or binary operator
  src/compiler/parser.ts
  tests/baselines/reference/instantiationExpressionErrors.errors.txt
  tests/baselines/reference/instantiationExpressionErrors.js
  tests/baselines/reference/instantiationExpressionErrors.symbols
  tests/baselines/reference/instantiationExpressionErrors.types
  tests/cases/conformance/types/typeParameters/typeArgumentLists/instantiationExpressionErrors.ts
  tests/cases/fourslash/completionListInUnclosedTypeArguments.ts
Labels: Author: Team, For Milestone Bug

#49482 fix(49478): TS declare method produces compile errors with noImplicitAny enabled
  src/services/codefixes/helpers.ts
  src/services/textChanges.ts
  tests/cases/fourslash/codeFixAddMissingMember24.ts
  tests/cases/fourslash/codeFixAddMissingMember27.ts
  tests/cases/fourslash/codeFixAddMissingMember28.ts
  tests/cases/fourslash/codeFixAddMissingMember_all.ts
Labels: For Milestone Bug

#49487 Improve performance of Debug.format functions
  src/compiler/debug.ts
Labels: Author: Team, For Uncommitted Bug

#49485 Eliminate (ts as any).SyntaxKind (and similar) in favor of Debug.format functions
  src/compiler/binder.ts
  src/compiler/transformers/declarations.ts
  src/compiler/transformers/declarations/diagnostics.ts
  src/compiler/types.ts
  src/harness/harnessUtils.ts
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.@link tags.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.Nested @param tags.json
  tests/baselines/reference/JSDocParsing/TypeExpressions.parsesCorrectly.newType1.json
  tests/baselines/reference/JSDocParsing/TypeExpressions.parsesCorrectly.thisType1.json
  tests/baselines/reference/JSDocParsing/TypeExpressions.parsesCorrectly.typeReference3.json
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#49503 Fresh `{}` is subtype of `object`
  src/compiler/checker.ts
  tests/baselines/reference/nonPrimitiveAndEmptyObject.js
  tests/baselines/reference/nonPrimitiveAndEmptyObject.symbols
  tests/baselines/reference/nonPrimitiveAndEmptyObject.types
  tests/cases/conformance/types/nonPrimitive/nonPrimitiveAndEmptyObject.ts
Labels: Author: Team, For Milestone Bug

#49337 fix #49235 Objects that pass the spread syntax can no longer be assigned to assignable types.
  src/compiler/checker.ts
  tests/baselines/reference/restElementAssignable.js
  tests/baselines/reference/restElementAssignable.symbols
  tests/baselines/reference/restElementAssignable.types
  tests/cases/compiler/restElementAssignable.ts
Labels: For Backlog Bug

#41044 Forbid unused property renaming in destructuring binding in function types
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/transformers/declarations.ts
  tests/baselines/reference/contextuallyTypedBindingInitializerNegative.types
  tests/baselines/reference/declarationEmitBindingPatterns.js
  tests/baselines/reference/declarationEmitBindingPatterns.types
  tests/baselines/reference/declarationsAndAssignments.types
  tests/baselines/reference/destructuringInFunctionType.errors.txt
  tests/baselines/reference/destructuringInFunctionType.js
  tests/baselines/reference/destructuringInFunctionType.types
  tests/baselines/reference/destructuringParameterDeclaration1ES5.types
  tests/baselines/reference/destructuringParameterDeclaration1ES5iterable.types
  tests/baselines/reference/destructuringParameterDeclaration1ES6.types
  tests/baselines/reference/destructuringParameterDeclaration6.types
  tests/baselines/reference/excessPropertyCheckWithSpread.errors.txt
  tests/baselines/reference/excessPropertyCheckWithSpread.types
  tests/baselines/reference/objectRestParameter.types
  tests/baselines/reference/objectRestParameterES5.types
  tests/baselines/reference/paramterDestrcuturingDeclaration.errors.txt
  tests/baselines/reference/paramterDestrcuturingDeclaration.js
  tests/baselines/reference/renamingDestructuredPropertyInFunctionType.errors.txt
  tests/baselines/reference/renamingDestructuredPropertyInFunctionType.js
  tests/baselines/reference/renamingDestructuredPropertyInFunctionType.symbols
  tests/baselines/reference/renamingDestructuredPropertyInFunctionType.types
  tests/baselines/reference/renamingDestructuredPropertyInFunctionType2.js
  tests/baselines/reference/renamingDestructuredPropertyInFunctionType2.symbols
  tests/baselines/reference/renamingDestructuredPropertyInFunctionType2.types
  tests/baselines/reference/renamingDestructuredPropertyInFunctionType3.errors.txt
  tests/baselines/reference/renamingDestructuredPropertyInFunctionType3.js
  tests/baselines/reference/renamingDestructuredPropertyInFunctionType3.symbols
  tests/baselines/reference/renamingDestructuredPropertyInFunctionType3.types
  tests/baselines/reference/sourceMapValidationDestructuringParameterNestedObjectBindingPattern.types
  tests/baselines/reference/sourceMapValidationDestructuringParameterNestedObjectBindingPatternDefaultValues.types
  tests/baselines/reference/sourceMapValidationDestructuringParameterObjectBindingPattern.types
  tests/baselines/reference/sourceMapValidationDestructuringParameterObjectBindingPatternDefaultValues.types
  tests/baselines/reference/syntheticDefaultExportsWithDynamicImports.types
  tests/baselines/reference/tsxStatelessFunctionComponentOverload1.errors.txt
  tests/baselines/reference/tsxStatelessFunctionComponentOverload1.types
  tests/cases/compiler/renamingDestructuredPropertyInFunctionType.ts
  tests/cases/compiler/renamingDestructuredPropertyInFunctionType2.ts
  tests/cases/compiler/renamingDestructuredPropertyInFunctionType3.ts
Labels: Breaking Change, For Backlog Bug

#47377 Enable TS Server plugins on web
  Gulpfile.js
  scripts/produceLKG.ts
  src/dynamicImportCompat/dynamicImportCompat.ts
  src/dynamicImportCompat/tsconfig.json
  src/harness/util.ts
  src/server/editorServices.ts
  src/server/project.ts
  src/server/session.ts
  src/server/types.ts
  src/testRunner/unittests/tsserver/webServer.ts
  src/tsconfig.json
  src/tsserver/nodeServer.ts
  src/webServer/webServer.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
Labels: For Uncommitted Bug

#49496 fix(49483): Plain JS files don't issue error on await inside non-async function
  src/compiler/program.ts
  tests/baselines/reference/plainJSGrammarErrors3.errors.txt
  tests/baselines/reference/plainJSGrammarErrors3.js
  tests/baselines/reference/plainJSGrammarErrors3.symbols
  tests/baselines/reference/plainJSGrammarErrors3.types
  tests/cases/conformance/salsa/plainJSGrammarErrors3.ts
Labels: For Milestone Bug

#49524 Ensure scripts compile, are checked in strict mode
  package-lock.json
  package.json
  scripts/buildProtocol.ts
  scripts/tsconfig.json
Labels: Author: Team, Housekeeping, For Uncommitted Bug

#49521 Handle `this` in isEntityNameVisible
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitTypeofThisInClass.js
  tests/baselines/reference/declarationEmitTypeofThisInClass.symbols
  tests/baselines/reference/declarationEmitTypeofThisInClass.types
  tests/cases/compiler/declarationEmitTypeofThisInClass.ts
Labels: Author: Team, For Milestone Bug

#48563 Allow exports map entries to point at `.ts` source files
  tests/baselines/reference/nodeModulesExportsSourceTs(module=node16).errors.txt
  tests/baselines/reference/nodeModulesExportsSourceTs(module=node16).js
  tests/baselines/reference/nodeModulesExportsSourceTs(module=node16).symbols
  tests/baselines/reference/nodeModulesExportsSourceTs(module=node16).types
  tests/baselines/reference/nodeModulesExportsSourceTs(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesExportsSourceTs(module=nodenext).js
  tests/baselines/reference/nodeModulesExportsSourceTs(module=nodenext).symbols
  tests/baselines/reference/nodeModulesExportsSourceTs(module=nodenext).types
  tests/cases/conformance/node/nodeModulesExportsSourceTs.ts
Labels: Author: Team, For Uncommitted Bug

#49560 Properly re-scan `>` token in type argument list determination logic
  src/compiler/parser.ts
  tests/baselines/reference/instantiationExpressionErrors.errors.txt
  tests/baselines/reference/instantiationExpressionErrors.js
  tests/baselines/reference/instantiationExpressionErrors.symbols
  tests/baselines/reference/instantiationExpressionErrors.types
  tests/cases/conformance/types/typeParameters/typeArgumentLists/instantiationExpressionErrors.ts
Labels: Author: Team, For Milestone Bug

#49412 feat(49385): Inlay hint for type of literal-initialized constant is unnecessary
  src/services/inlayHints.ts
  tests/cases/fourslash/inlayHintsShouldWork15.ts
  tests/cases/fourslash/inlayHintsShouldWork16.ts
  tests/cases/fourslash/inlayHintsShouldWork17.ts
  tests/cases/fourslash/inlayHintsShouldWork18.ts
  tests/cases/fourslash/inlayHintsShouldWork22.ts
  tests/cases/fourslash/inlayHintsShouldWork56.ts
  tests/cases/fourslash/inlayHintsShouldWork65.ts
  tests/cases/fourslash/inlayHintsShouldWork69.ts
Labels: For Backlog Bug

#49570 [release-4.7] Cherry pick #49560: Properly re-scan `>` token in type argument list determination logic
  src/compiler/parser.ts
  tests/baselines/reference/instantiationExpressionErrors.errors.txt
  tests/baselines/reference/instantiationExpressionErrors.js
  tests/baselines/reference/instantiationExpressionErrors.symbols
  tests/baselines/reference/instantiationExpressionErrors.types
  tests/cases/conformance/types/typeParameters/typeArgumentLists/instantiationExpressionErrors.ts
Labels: Author: Team, For Milestone Bug

#49574 fix(49566): Implicit this.property completions not returned while writing property
  src/compiler/checker.ts
  src/compiler/types.ts
  src/services/completions.ts
  tests/cases/fourslash/completionsThisPropertiesInPropertyDeclaration1.ts
  tests/cases/fourslash/completionsThisPropertiesInPropertyDeclaration2.ts
Labels: For Milestone Bug

#49550 Update all depedencies, including ESLint 8, refresh lockfile
  .eslintrc.json
  .vscode/settings.template.json
  package-lock.json
  package.json
  scripts/eslint/rules/boolean-trivia.ts
  scripts/eslint/rules/debug-assert.ts
  scripts/eslint/rules/no-double-space.ts
  scripts/eslint/rules/no-in-operator.ts
  scripts/eslint/rules/no-keywords.ts
  scripts/eslint/rules/no-type-assertion-whitespace.ts
  scripts/eslint/rules/object-literal-surrounding-space.ts
  scripts/eslint/rules/one-namespace-per-file.ts
  scripts/eslint/rules/only-arrow-functions.ts
  scripts/eslint/rules/simple-indent.ts
  scripts/eslint/rules/type-operator-spacing.ts
  scripts/eslint/rules/utils.ts
  scripts/eslint/tests/support/RuleTester.ts
Labels: Author: Team, Housekeeping, For Uncommitted Bug

#49581 Tune FAR aggregation
  src/server/session.ts
Labels: Author: Team, For Uncommitted Bug

#49568 Fix renaming of node_modules
  src/compiler/diagnosticMessages.json
  src/compiler/types.ts
  src/harness/client.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/harness/harnessLanguageService.ts
  src/server/session.ts
  src/services/rename.ts
  src/services/services.ts
  src/services/shims.ts
  src/services/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/findAllRefs_importType_exportEquals.ts
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/renameFromNodeModulesDep1.ts
  tests/cases/fourslash/renameFromNodeModulesDep2.ts
  tests/cases/fourslash/renameFromNodeModulesDep3.ts
  tests/cases/fourslash/renameFromNodeModulesDep4.ts
  tests/cases/fourslash/renameImport.ts
Labels: Author: Team, For Milestone Bug

#47050 Allow nongeneric string mapping types to exist
  src/compiler/checker.ts
  tests/baselines/reference/intrinsicTypes.errors.txt
  tests/baselines/reference/intrinsicTypes.js
  tests/baselines/reference/intrinsicTypes.symbols
  tests/baselines/reference/intrinsicTypes.types
  tests/baselines/reference/mappedTypeConstraints2.errors.txt
  tests/baselines/reference/stringLiteralsAssignedToStringMappings.errors.txt
  tests/baselines/reference/stringLiteralsAssignedToStringMappings.js
  tests/baselines/reference/stringLiteralsAssignedToStringMappings.symbols
  tests/baselines/reference/stringLiteralsAssignedToStringMappings.types
  tests/baselines/reference/stringMappingOverPatternLiterals.errors.txt
  tests/baselines/reference/stringMappingOverPatternLiterals.js
  tests/baselines/reference/stringMappingOverPatternLiterals.symbols
  tests/baselines/reference/stringMappingOverPatternLiterals.types
  tests/cases/conformance/types/literal/stringLiteralsAssignedToStringMappings.ts
  tests/cases/conformance/types/literal/stringMappingOverPatternLiterals.ts
  tests/cases/conformance/types/typeAliases/intrinsicTypes.ts
Labels: Breaking Change, Author: Team, For Uncommitted Bug

#49590 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220617102130127 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#49592 Downgrade node-fetch back to v2
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#49580 Add error when importing/exporting types in JS files
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/importingExportingTypes.errors.txt
  tests/baselines/reference/importingExportingTypes.symbols
  tests/baselines/reference/importingExportingTypes.types
  tests/baselines/reference/jsDeclarationsImportAliasExposedWithinNamespace.errors.txt
  tests/baselines/reference/jsDeclarationsInterfaces.errors.txt
  tests/baselines/reference/jsxCheckJsxNoTypeArgumentsAllowed.errors.txt
  tests/baselines/reference/tsbuild/javascriptProjectEmit/loads-js-based-projects-and-emits-them-correctly.js
  tests/cases/conformance/salsa/importingExportingTypes.ts
Labels: Breaking Change, Author: Team, For Milestone Bug

#49578 Add TS Server option to exclude files from auto-imports
  src/compiler/types.ts
  src/server/protocol.ts
  src/services/codefixes/importFixes.ts
  src/services/completions.ts
  src/services/exportInfoMap.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/autoImportFileExcludePatterns1.ts
  tests/cases/fourslash/autoImportFileExcludePatterns2.ts
  tests/cases/fourslash/autoImportFileExcludePatterns3.ts
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/server/autoImportFileExcludePatterns1.ts
Labels: Author: Team, For Milestone Bug

#49602 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220619100116409 to main
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#49600 fix(49548): No completions (and poor formatting) when trying to use variable that starts with default in block
  src/services/completions.ts
  tests/cases/fourslash/completionsAfterKeywordsInBlock.ts
Labels: For Backlog Bug

#49554 fix(49546): 'Add missing properties' quick fix incorrectly handles symbol property
  src/services/codefixes/fixAddMissingMember.ts
  tests/cases/fourslash/codeFixAddMissingProperties22.ts
Labels: For Backlog Bug

#49569 Add `fractionalSecond` part type to DateTimeFormat().formatToParts
  src/lib/es2017.intl.d.ts
  src/lib/es2021.intl.d.ts
  tests/baselines/reference/formatToPartsFractionalSecond.js
  tests/baselines/reference/formatToPartsFractionalSecond.symbols
  tests/baselines/reference/formatToPartsFractionalSecond.types
  tests/cases/compiler/formatToPartsFractionalSecond.ts
Labels: For Milestone Bug

#49598 Ensure resolved signature is cached before processing call errors
  src/compiler/checker.ts
  tests/baselines/reference/circularResolvedSignature.errors.txt
  tests/baselines/reference/circularResolvedSignature.js
  tests/baselines/reference/circularResolvedSignature.symbols
  tests/baselines/reference/circularResolvedSignature.types
  tests/baselines/reference/genericCallWithGenericSignatureArguments3.errors.txt
  tests/baselines/reference/genericCallWithGenericSignatureArguments3.types
  tests/cases/compiler/circularResolvedSignature.ts
Labels: Author: Team, For Milestone Bug

#49593 fix(49449): Unexpected error location when passing objects/arrays to an argument of type never
  src/compiler/checker.ts
  tests/baselines/reference/assignmentCompatability46.errors.txt
  tests/baselines/reference/assignmentCompatability46.js
  tests/baselines/reference/assignmentCompatability46.symbols
  tests/baselines/reference/assignmentCompatability46.types
  tests/cases/compiler/assignmentCompatability46.ts
Labels: For Backlog Bug

#49493 Fixes #49491: assertion failure in generate get/set accessors when name has escape characters
  src/services/utilities.ts
  tests/cases/fourslash/refactorConvertToGetAccessAndSetAccess41.ts
  tests/cases/fourslash/refactorConvertToGetAccessAndSetAccess42.ts
Labels: For Backlog Bug

#49623 Add a simple queue implementation with better performance than `Array.shift`
  src/compiler/binder.ts
  src/compiler/core.ts
  src/compiler/types.ts
  src/harness/client.ts
  src/server/session.ts
  src/services/findAllReferences.ts
  src/tsserver/nodeServer.ts
Labels: Author: Team, For Uncommitted Bug

#49675 Add case to capture enum subtype reduction (addresses #35867)
  tests/baselines/reference/enumMemberReduction.js
  tests/baselines/reference/enumMemberReduction.symbols
  tests/baselines/reference/enumMemberReduction.types
  tests/cases/compiler/enumMemberReduction.ts
Labels: For Backlog Bug

#49464 Disallow expression with type parameters as left side of property access
  src/compiler/diagnosticMessages.json
  src/compiler/parser.ts
  tests/baselines/reference/genericCallWithoutArgs.errors.txt
  tests/baselines/reference/instantiationExpressionErrors.errors.txt
  tests/baselines/reference/optionalChainWithInstantiationExpression1(target=es2019).errors.txt
  tests/baselines/reference/optionalChainWithInstantiationExpression1(target=es2019).js
  tests/baselines/reference/optionalChainWithInstantiationExpression1(target=es2019).symbols
  tests/baselines/reference/optionalChainWithInstantiationExpression1(target=es2019).types
  tests/baselines/reference/optionalChainWithInstantiationExpression1(target=es2020).errors.txt
  tests/baselines/reference/optionalChainWithInstantiationExpression1(target=es2020).js
  tests/baselines/reference/optionalChainWithInstantiationExpression1(target=es2020).symbols
  tests/baselines/reference/optionalChainWithInstantiationExpression1(target=es2020).types
  tests/baselines/reference/optionalChainWithInstantiationExpression2(target=es2019).js
  tests/baselines/reference/optionalChainWithInstantiationExpression2(target=es2019).symbols
  tests/baselines/reference/optionalChainWithInstantiationExpression2(target=es2019).types
  tests/baselines/reference/optionalChainWithInstantiationExpression2(target=es2020).js
  tests/baselines/reference/optionalChainWithInstantiationExpression2(target=es2020).symbols
  tests/baselines/reference/optionalChainWithInstantiationExpression2(target=es2020).types
  tests/baselines/reference/parserMemberAccessExpression1.errors.txt
  tests/baselines/reference/parserMemberAccessOffOfGenericType1.errors.txt
  tests/cases/compiler/optionalChainWithInstantiationExpression1.ts
  tests/cases/compiler/optionalChainWithInstantiationExpression2.ts
Labels: Author: Team, For Milestone Bug

#49679 Fix parser TODO
  src/compiler/parser.ts
Labels: Author: Team, For Uncommitted Bug

#49641 Reuse start position in binarySearchKey
  src/services/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#49543 To handle d.ts emit errors that could affect other files, in incremental mode use d.ts emit text + diagnostics as signature of the file
  src/compiler/builder.ts
  src/compiler/builderState.ts
  src/compiler/builderStatePublic.ts
  src/compiler/emitter.ts
  src/compiler/types.ts
  src/server/project.ts
  src/testRunner/unittests/services/languageService.ts
  src/testRunner/unittests/tsc/incremental.ts
  src/testRunner/unittests/tsserver/projectReferenceCompileOnSave.ts
  tests/baselines/reference/tsc/incremental/change-to-modifier-of-class-expression-field-with-declaration-emit-enabled.js
  tests/baselines/reference/tsc/incremental/change-to-modifier-of-class-expression-field.js
Labels: Author: Team, For Uncommitted Bug

#49678 Use value meaning for computed property name for visibility check
  src/compiler/checker.ts
  tests/baselines/reference/computedPropertyNameAndTypeParameterConflict.js
  tests/baselines/reference/computedPropertyNameAndTypeParameterConflict.symbols
  tests/baselines/reference/computedPropertyNameAndTypeParameterConflict.types
  tests/cases/compiler/computedPropertyNameAndTypeParameterConflict.ts
Labels: Author: Team, For Milestone Bug

#49689 Add reference to TypeScript-Compiler-Notes in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: For Uncommitted Bug

#49707 Pass contextFlags when getting contextual type of JSX elements/attributes
  src/compiler/checker.ts
  tests/baselines/reference/contextuallyTypedJsxAttribute.js
  tests/baselines/reference/contextuallyTypedJsxAttribute.symbols
  tests/baselines/reference/contextuallyTypedJsxAttribute.types
  tests/cases/compiler/contextuallyTypedJsxAttribute.ts
Labels: Author: Team, For Milestone Bug

#49716 Demote priority of JS completions
  src/services/completions.ts
  tests/cases/fourslash/completionInJSDocFunctionNew.ts
  tests/cases/fourslash/completionInJSDocFunctionThis.ts
  tests/cases/fourslash/completionListClassThisJS.ts
Labels: Author: Team, For Milestone Bug

#49673 For missing constraint quickfix insert position, Use node name end rather than related span end
  src/services/codefixes/fixAddMissingConstraint.ts
  tests/cases/fourslash/quickfixAddMissingConstraint3.ts
Labels: Author: Team, For Uncommitted Bug

#49677 Fixed an issue with self-referential awaited union
  src/compiler/checker.ts
  tests/baselines/reference/unresolvableSelfReferencingAwaitedUnion.errors.txt
  tests/baselines/reference/unresolvableSelfReferencingAwaitedUnion.symbols
  tests/baselines/reference/unresolvableSelfReferencingAwaitedUnion.types
  tests/cases/compiler/unresolvableSelfReferencingAwaitedUnion.ts
Labels: For Backlog Bug

#49712 Add variance results to tracing, capture variance verification on annotated type params
  src/compiler/checker.ts
  src/compiler/debug.ts
  src/compiler/tracing.ts
Labels: Author: Team, For Uncommitted Bug

#49737 Fix mapper used to instantiate distributive conditional manufactured in declaration emit
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/declarationEmitDistributiveConditionalWithInfer.js
  tests/baselines/reference/declarationEmitDistributiveConditionalWithInfer.symbols
  tests/baselines/reference/declarationEmitDistributiveConditionalWithInfer.types
  tests/cases/compiler/declarationEmitDistributiveConditionalWithInfer.ts
Labels: Author: Team, For Milestone Bug

#49744 Get type arguments lazily for instantiating inferred type parameter constraint
  src/compiler/checker.ts
  tests/baselines/reference/inferTypeConstraintInstantiationCircularity.js
  tests/baselines/reference/inferTypeConstraintInstantiationCircularity.symbols
  tests/baselines/reference/inferTypeConstraintInstantiationCircularity.types
  tests/cases/compiler/inferTypeConstraintInstantiationCircularity.ts
Labels: Author: Team, For Milestone Bug
