Repository microsoft/TypeScript, pull requests merged in 2022-07, with the labels that each got.

#49748 Fix for Awaited<T> inference
  src/compiler/checker.ts
  tests/baselines/reference/awaitedType.errors.txt
  tests/baselines/reference/awaitedType.js
  tests/baselines/reference/awaitedType.symbols
  tests/baselines/reference/awaitedType.types
  tests/cases/compiler/awaitedType.ts
Labels: Author: Team, For Milestone Bug

#49760 Cache results of expensive repetitive type operations
  src/compiler/checker.ts
Labels: Author: Team, For Milestone Bug

#49757 fix(49426): Object method snippet completions incorrectly add this parameters
  src/compiler/checker.ts
  src/compiler/types.ts
  src/services/completions.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/completionsObjectLiteralMethod4.ts
Labels: For Milestone Bug

#49791 Minor fixes
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/tsbuildPublic.ts
  src/compiler/watchPublic.ts
Labels: Author: Team, For Uncommitted Bug

#49639 Set Error.prototype.cause type to unknown (#70)
  src/lib/es2022.error.d.ts
  tests/baselines/reference/errorCause(target=es2021).errors.txt
  tests/baselines/reference/errorCause(target=es2021).js
  tests/baselines/reference/errorCause(target=es2021).symbols
  tests/baselines/reference/errorCause(target=es2021).types
  tests/baselines/reference/errorCause(target=es2022).js
  tests/baselines/reference/errorCause(target=es2022).symbols
  tests/baselines/reference/errorCause(target=es2022).types
  tests/baselines/reference/errorCause(target=esnext).js
  tests/baselines/reference/errorCause(target=esnext).symbols
  tests/baselines/reference/errorCause(target=esnext).types
  tests/cases/compiler/errorCause.ts
Labels: For Backlog Bug

#49740 Infer rest type without using assignContextualParameterTypes
  src/compiler/checker.ts
  tests/baselines/reference/inferredRestTypeFixedOnce.js
  tests/baselines/reference/inferredRestTypeFixedOnce.symbols
  tests/baselines/reference/inferredRestTypeFixedOnce.types
  tests/cases/compiler/inferredRestTypeFixedOnce.ts
Labels: Author: Team, For Milestone Bug

#49756 Retire $ExpectError awareness from DefinitelyTypedRunner
  src/testRunner/externalCompileRunner.ts
Labels: Housekeeping, For Uncommitted Bug

#49545 fix(49544): Delimiting accessors in interface with comma causes parser error
  src/compiler/parser.ts
  tests/baselines/reference/parserInterfaceDeclaration9.js
  tests/baselines/reference/parserInterfaceDeclaration9.symbols
  tests/baselines/reference/parserInterfaceDeclaration9.types
  tests/cases/conformance/parser/ecmascript5/InterfaceDeclarations/parserInterfaceDeclaration9.ts
Labels: For Backlog Bug

#49793 Constrain infer type parameters made to preserve distributivity for …
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitMappedTypeDistributivityPreservesConstraints.js
  tests/baselines/reference/declarationEmitMappedTypeDistributivityPreservesConstraints.symbols
  tests/baselines/reference/declarationEmitMappedTypeDistributivityPreservesConstraints.types
  tests/cases/compiler/declarationEmitMappedTypeDistributivityPreservesConstraints.ts
Labels: Author: Team, For Milestone Bug

#49813 Protect against a language service host mutating its underlying source for `getScriptFileNames`
  src/services/services.ts
Labels: Author: Team, For Uncommitted Bug

#49718 Always resetErrorInfo if structuredTypeRelatedTo succeeds
  src/compiler/checker.ts
  tests/baselines/reference/relatedViaDiscriminatedTypeNoError.js
  tests/baselines/reference/relatedViaDiscriminatedTypeNoError.symbols
  tests/baselines/reference/relatedViaDiscriminatedTypeNoError.types
  tests/cases/compiler/relatedViaDiscriminatedTypeNoError.ts
Labels: Author: Team, For Milestone Bug

#49815 Remove dependence on `module` compiler option to consider mts/cts files always modules
  src/compiler/utilities.ts
  tests/baselines/reference/moduleDetectionIsolatedModulesCjsFileScope.js
  tests/baselines/reference/moduleDetectionIsolatedModulesCjsFileScope.symbols
  tests/baselines/reference/moduleDetectionIsolatedModulesCjsFileScope.types
  tests/cases/compiler/moduleDetectionIsolatedModulesCjsFileScope.ts
Labels: Author: Team, For Milestone Bug

#49732 Add debug format helpers for more enums
  src/compiler/checker.ts
  src/compiler/debug.ts
Labels: Author: Team, For Uncommitted Bug

#49654 fix(49642): Missing some item docs in Intellisense from JSDoc in getters/setters
  src/services/services.ts
  tests/baselines/reference/quickInfoJsDoc.baseline
  tests/cases/fourslash/quickInfoJsDoc.ts
Labels: For Backlog Bug

#49697 fix(49685): Incorrect visibility error when setter precedes getter
  src/compiler/utilities.ts
  tests/baselines/reference/accessorDeclarationOrder.js
  tests/baselines/reference/accessorDeclarationOrder.symbols
  tests/baselines/reference/accessorDeclarationOrder.types
  tests/cases/compiler/accessorDeclarationOrder.ts
Labels: For Backlog Bug

#49720 Make contextFlags an explicitly required parameter
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug

#49644 Add path completions for package.json exports with wildcards
  src/compiler/moduleNameResolver.ts
  src/services/stringCompletions.ts
  tests/cases/fourslash/pathCompletionsPackageJsonExportsWildcard1.ts
  tests/cases/fourslash/pathCompletionsPackageJsonExportsWildcard2.ts
  tests/cases/fourslash/pathCompletionsPackageJsonExportsWildcard3.ts
  tests/cases/fourslash/pathCompletionsPackageJsonExportsWildcard4.ts
  tests/cases/fourslash/pathCompletionsPackageJsonExportsWildcard5.ts
  tests/cases/fourslash/pathCompletionsPackageJsonExportsWildcard6.ts
  tests/cases/fourslash/server/nodeNextPathCompletions.ts
Labels: Author: Team, For Uncommitted Bug

#49828 Handle pseudo-references in getFlowCacheKey
  src/compiler/checker.ts
  tests/baselines/reference/dependentDestructuredVariables.errors.txt
  tests/baselines/reference/dependentDestructuredVariables.js
  tests/baselines/reference/dependentDestructuredVariables.symbols
  tests/baselines/reference/dependentDestructuredVariables.types
  tests/cases/conformance/controlFlow/dependentDestructuredVariables.ts
Labels: Author: Team, For Milestone Bug

#49696 Defer types like `keyof (T & {})`
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypes4.js
  tests/baselines/reference/mappedTypes4.symbols
  tests/baselines/reference/mappedTypes4.types
  tests/baselines/reference/unknownControlFlow.errors.txt
  tests/baselines/reference/unknownControlFlow.js
  tests/baselines/reference/unknownControlFlow.symbols
  tests/baselines/reference/unknownControlFlow.types
  tests/cases/conformance/types/mapped/mappedTypes4.ts
  tests/cases/conformance/types/unknown/unknownControlFlow.ts
Labels: Author: Team, For Milestone Bug

#49864 Move DebugTypeMapper to debug.ts
  src/compiler/checker.ts
  src/compiler/debug.ts
Labels: Author: Team, For Uncommitted Bug

#49804 🐛 Fix smart selection of propery signatures having JSDoc comments
  src/services/smartSelection.ts
  tests/baselines/reference/smartSelection_JSDocTags11.baseline
  tests/baselines/reference/smartSelection_JSDocTags12.baseline
  tests/baselines/reference/smartSelection_JSDocTags13.baseline
  tests/cases/fourslash/smartSelection_JSDocTags11.ts
  tests/cases/fourslash/smartSelection_JSDocTags12.ts
  tests/cases/fourslash/smartSelection_JSDocTags13.ts
Labels: For Backlog Bug

#49374 Fixed initialization-time inference for class properties assigned through element access
  src/compiler/checker.ts
  tests/baselines/reference/classPropInitializationInferenceWithElementAccess.symbols
  tests/baselines/reference/classPropInitializationInferenceWithElementAccess.types
  tests/cases/compiler/classPropInitializationInferenceWithElementAccess.ts
Labels: For Backlog Bug

#49879 Delete unused code in object literal binding
  src/compiler/binder.ts
Labels: Author: Team, Housekeeping, For Uncommitted Bug

#49023 Fixed an issue with generic naked T not being allowed as async generator's return
  src/compiler/checker.ts
  tests/baselines/reference/asyncGeneratorGenericNonWrappedReturn.symbols
  tests/baselines/reference/asyncGeneratorGenericNonWrappedReturn.types
  tests/cases/conformance/generators/asyncGeneratorGenericNonWrappedReturn.ts
Labels: For Milestone Bug

#49522 Fix(49472): Added docs for Set and Map types
  src/lib/es2015.collection.d.ts
Labels: For Backlog Bug

#49887 Properly propagate ObjectFlags.NonInferrableType, clean up non-inferrable code paths
  src/compiler/checker.ts
  tests/baselines/reference/nonInferrableTypePropagation1.js
  tests/baselines/reference/nonInferrableTypePropagation1.symbols
  tests/baselines/reference/nonInferrableTypePropagation1.types
  tests/baselines/reference/nonInferrableTypePropagation2.js
  tests/baselines/reference/nonInferrableTypePropagation2.symbols
  tests/baselines/reference/nonInferrableTypePropagation2.types
  tests/cases/compiler/nonInferrableTypePropagation1.ts
  tests/cases/compiler/nonInferrableTypePropagation2.ts
Labels: Author: Team, For Milestone Bug

#49625 Improve narrowing logic for `instanceof`, type predicate functions, and assertion functions
  src/compiler/checker.ts
  tests/baselines/reference/controlFlowOptionalChain.types
  tests/baselines/reference/narrowingUnionToUnion.js
  tests/baselines/reference/narrowingUnionToUnion.symbols
  tests/baselines/reference/narrowingUnionToUnion.types
  tests/cases/compiler/narrowingUnionToUnion.ts
Labels: Author: Team, For Backlog Bug

#49918 check base constraint when checking operand of plus
  src/compiler/checker.ts
  tests/baselines/reference/numberVsBigIntOperations.errors.txt
  tests/baselines/reference/numberVsBigIntOperations.js
  tests/baselines/reference/numberVsBigIntOperations.symbols
  tests/baselines/reference/numberVsBigIntOperations.types
  tests/cases/compiler/numberVsBigIntOperations.ts
Labels: For Backlog Bug

#49768 fix(49392): classMemberSnippets not working with optional method and strictNullChecks
  src/services/codefixes/helpers.ts
  tests/cases/fourslash/completionsOverridingMethod14.ts
Labels: For Milestone Bug

#49810 feat(49786): Typescript: Add intellisense on extended types (ie: interface Itest extends Pick<T, keyof T>)
  src/services/stringCompletions.ts
  tests/cases/fourslash/completionsAtTypeArguments.ts
Labels: For Milestone Bug

#49943 Don't leak EvolvingArray out of code flow
  src/compiler/checker.ts
  tests/baselines/reference/evolvingArrayResolvedAssert.errors.txt
  tests/baselines/reference/evolvingArrayResolvedAssert.js
  tests/baselines/reference/evolvingArrayResolvedAssert.symbols
  tests/baselines/reference/evolvingArrayResolvedAssert.types
  tests/cases/compiler/evolvingArrayResolvedAssert.ts
Labels: Author: Team, For Milestone Bug

#49840 fix(49838): "Extract function" refactoring action is disabled for a wrong reason
  src/services/refactors/extractSymbol.ts
  tests/cases/fourslash/extract-method45.ts
  tests/cases/fourslash/extract-method46.ts
  tests/cases/fourslash/extract-method47.ts
  tests/cases/fourslash/extract-method48.ts
Labels: For Backlog Bug

#49915 Clean up inference of type parameters, contravariant types
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug

#49960 Copy type parameters to function with @type tag
  src/compiler/checker.ts
  src/compiler/utilitiesPublic.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/typeTagOnFunctionReferencesGeneric.js
  tests/baselines/reference/typeTagOnFunctionReferencesGeneric.symbols
  tests/baselines/reference/typeTagOnFunctionReferencesGeneric.types
  tests/cases/conformance/salsa/typeTagOnFunctionReferencesGeneric.ts
Labels: Author: Team, For Milestone Bug

#49743 fix(49704): Code folding not working in file with simple syntax error
  src/compiler/checker.ts
  src/compiler/parser.ts
  tests/baselines/reference/parserSuperExpression2.symbols
  tests/baselines/reference/superWithTypeArgument.symbols
  tests/baselines/reference/superWithTypeArgument2.symbols
  tests/baselines/reference/superWithTypeArgument3.symbols
  tests/cases/fourslash/getOutliningSpans.ts
Labels: For Backlog Bug

#49976 Update DOM lib for 4.8 RC
  src/lib/dom.generated.d.ts
  src/lib/webworker.generated.d.ts
Labels: Author: Team, For Milestone Bug

#49725 fix(49719): Incorrect error 2301 when using ES standard class properties
  src/compiler/checker.ts
  src/testRunner/compilerRunner.ts
  tests/baselines/reference/classMemberInitializerScoping2(target=es2017,usedefineforclassfields=false).errors.txt
  tests/baselines/reference/classMemberInitializerScoping2(target=es2017,usedefineforclassfields=false).js
  tests/baselines/reference/classMemberInitializerScoping2(target=es2017,usedefineforclassfields=false).symbols
  tests/baselines/reference/classMemberInitializerScoping2(target=es2017,usedefineforclassfields=false).types
  tests/baselines/reference/classMemberInitializerScoping2(target=es2017,usedefineforclassfields=true).errors.txt
  tests/baselines/reference/classMemberInitializerScoping2(target=es2017,usedefineforclassfields=true).js
  tests/baselines/reference/classMemberInitializerScoping2(target=es2017,usedefineforclassfields=true).symbols
  tests/baselines/reference/classMemberInitializerScoping2(target=es2017,usedefineforclassfields=true).types
  tests/baselines/reference/classMemberInitializerScoping2(target=esnext,usedefineforclassfields=false).errors.txt
  tests/baselines/reference/classMemberInitializerScoping2(target=esnext,usedefineforclassfields=false).js
  tests/baselines/reference/classMemberInitializerScoping2(target=esnext,usedefineforclassfields=false).symbols
  tests/baselines/reference/classMemberInitializerScoping2(target=esnext,usedefineforclassfields=false).types
  tests/baselines/reference/classMemberInitializerScoping2(target=esnext,usedefineforclassfields=true).js
  tests/baselines/reference/classMemberInitializerScoping2(target=esnext,usedefineforclassfields=true).symbols
  tests/baselines/reference/classMemberInitializerScoping2(target=esnext,usedefineforclassfields=true).types
  tests/cases/compiler/classMemberInitializerScoping2.ts
Labels: For Backlog Bug

#49858 fix(49854): Code Generation - Line omitted from class constructor
  src/compiler/transformers/ts.ts
  tests/baselines/reference/parameterPropertyInConstructorWithPrologues.js
  tests/baselines/reference/parameterPropertyInConstructorWithPrologues.symbols
  tests/baselines/reference/parameterPropertyInConstructorWithPrologues.types
  tests/cases/compiler/parameterPropertyInConstructorWithPrologues.ts
Labels: For Milestone Bug

#49888 Fixed closing JSDoc when adding multiple blocks
  src/services/jsDoc.ts
  tests/cases/fourslash/docCommentTemplateWithMultipleJSDoc.ts
  tests/cases/fourslash/docCommentTemplateWithMultipleJSDocAndParameters.ts
Labels: Author: Team, For Uncommitted Bug

#49990 Protect watcher from double close
  src/compiler/sys.ts
Labels: Author: Team, For Milestone Bug

#49868 More fixes to uncalled function checks in && expressions
  src/compiler/checker.ts
  tests/baselines/reference/uncalledFunctionChecksInConditional2.errors.txt
  tests/baselines/reference/uncalledFunctionChecksInConditional2.js
  tests/baselines/reference/uncalledFunctionChecksInConditional2.symbols
  tests/baselines/reference/uncalledFunctionChecksInConditional2.types
  tests/cases/compiler/uncalledFunctionChecksInConditional2.ts
Labels: Author: Team, For Milestone Bug

#49992 Remove uses of visitNodes and visitNode in visitEachChild
  src/compiler/visitorPublic.ts
  src/services/formatting/formatting.ts
  tests/cases/fourslash/extractFunctionWithSyntheticNodes.ts
Labels: Author: Team, For Milestone Bug

#50024 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220724103040364 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#50021 Properly handle null and undefined in getCommonSupertype
  src/compiler/checker.ts
  tests/baselines/reference/inferenceDoesNotAddUndefinedOrNull.js
  tests/baselines/reference/inferenceDoesNotAddUndefinedOrNull.symbols
  tests/baselines/reference/inferenceDoesNotAddUndefinedOrNull.types
  tests/baselines/reference/inferenceOfNullableObjectTypesWithCommonBase.js
  tests/baselines/reference/inferenceOfNullableObjectTypesWithCommonBase.symbols
  tests/baselines/reference/inferenceOfNullableObjectTypesWithCommonBase.types
  tests/cases/compiler/inferenceDoesNotAddUndefinedOrNull.ts
  tests/cases/compiler/inferenceOfNullableObjectTypesWithCommonBase.ts
Labels: Author: Team, For Uncommitted Bug

#50040 Parse parameter decorators outside of Await context when appropriate
  src/compiler/parser.ts
  tests/baselines/reference/decoratorOnClassMethodParameter3.errors.txt
  tests/baselines/reference/decoratorOnClassMethodParameter3.js
  tests/baselines/reference/decoratorOnClassMethodParameter3.symbols
  tests/baselines/reference/decoratorOnClassMethodParameter3.types
  tests/cases/conformance/decorators/class/method/parameter/decoratorOnClassMethodParameter3.ts
Labels: Author: Team, For Milestone Bug

#50042 Walk tokens with the correct walker
  src/compiler/visitorPublic.ts
Labels: Author: Team, For Uncommitted Bug

#50051 fix(50048): "Fix all" on "add `extends constraint" creates overlapping ranges, fails
  src/services/codefixes/fixAddMissingConstraint.ts
  tests/cases/fourslash/quickfixAddMissingConstraint5.ts
Labels: For Milestone Bug

#50011 Resolve parsingContextErrors TODO
  src/compiler/diagnosticMessages.json
  src/compiler/parser.ts
  tests/baselines/reference/parseAssertEntriesError.errors.txt
  tests/baselines/reference/parseAssertEntriesError.js
  tests/baselines/reference/parseAssertEntriesError.symbols
  tests/baselines/reference/parseAssertEntriesError.types
  tests/cases/compiler/parseAssertEntriesError.ts
Labels: Author: Team, For Uncommitted Bug

#49674 Fix(49525): Adds documentation for the Proxy type.
  src/lib/es2015.proxy.d.ts
Labels: For Backlog Bug

#49727 Account for type parameters in missing function codefix
  src/services/codefixes/helpers.ts
  tests/cases/fourslash/codeFixUndeclaredMethod.ts
  tests/cases/fourslash/incompleteFunctionCallCodefixTypeKeyof.ts
  tests/cases/fourslash/incompleteFunctionCallCodefixTypeParameter.ts
  tests/cases/fourslash/incompleteFunctionCallCodefixTypeParameterArgumentDifferent.ts
  tests/cases/fourslash/incompleteFunctionCallCodefixTypeParameterArgumentSame.ts
  tests/cases/fourslash/incompleteFunctionCallCodefixTypeParameterConstrained.ts
  tests/cases/fourslash/incompleteFunctionCallCodefixTypeParameterNarrowed.ts
  tests/cases/fourslash/incompleteFunctionCallCodefixTypeParameterVariable.ts
  tests/cases/fourslash/incompleteFunctionCallCodefixTypeParameters.ts
  tests/cases/fourslash/incompleteFunctionCallCodefixTypeParametersConstrained.ts
  tests/cases/fourslash/incompleteFunctionCallCodefixTypeParametersNested2D.ts
  tests/cases/fourslash/incompleteFunctionCallCodefixTypeParametersNested3D.ts
  tests/cases/fourslash/incompleteFunctionCallCodefixTypeUnion.ts
  tests/cases/fourslash/incompleteFunctionCallCodefixTypeUnions.ts
Labels: For Backlog Bug

#50044 Favor asserted type in type predicate narrowing
  src/compiler/checker.ts
  tests/baselines/reference/controlFlowBinaryOrExpression.symbols
  tests/baselines/reference/controlFlowBinaryOrExpression.types
  tests/baselines/reference/instanceofWithStructurallyIdenticalTypes.symbols
  tests/baselines/reference/instanceofWithStructurallyIdenticalTypes.types
  tests/baselines/reference/typePredicateStructuralMatch.symbols
  tests/baselines/reference/unionWithIndexSignature.types
Labels: Author: Team, For Uncommitted Bug

#50012 Use proper type for result of resultModuleNamesReusingOldState
  src/compiler/program.ts
  src/compiler/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#50062 Don't uninstall typescript before npm ci in GHA
  .github/workflows/ci.yml
  .github/workflows/release-branch-artifact.yaml
Labels: Author: Team, For Uncommitted Bug

#49956 Normalize effective constraint intersection before checking if source is a part of it
  src/compiler/checker.ts
  tests/baselines/reference/instanceofTypeAliasToGenericClass.js
  tests/baselines/reference/instanceofTypeAliasToGenericClass.symbols
  tests/baselines/reference/instanceofTypeAliasToGenericClass.types
  tests/baselines/reference/typeVariableConstraintedToAliasNotAssignableToUnion.errors.txt
  tests/baselines/reference/typeVariableConstraintedToAliasNotAssignableToUnion.js
  tests/baselines/reference/typeVariableConstraintedToAliasNotAssignableToUnion.symbols
  tests/baselines/reference/typeVariableConstraintedToAliasNotAssignableToUnion.types
  tests/cases/compiler/instanceofTypeAliasToGenericClass.ts
  tests/cases/compiler/typeVariableConstraintedToAliasNotAssignableToUnion.ts
Labels: Author: Team, For Milestone Bug

#49941 Update to npm 8, pin in package.json via volta and corepack
  .github/workflows/update-package-lock.yaml
  package-lock.json
  package.json
Labels: Infrastructure, Author: Team, For Uncommitted Bug

#49746 Report error only on local declaration with additional related information
  src/compiler/checker.ts
  tests/baselines/reference/computedPropertyNames45_ES5.errors.txt
  tests/baselines/reference/computedPropertyNames45_ES6.errors.txt
  tests/baselines/reference/indexSignatureInOtherFile.errors.txt
  tests/baselines/reference/indexSignatureInOtherFile.js
  tests/baselines/reference/indexSignatureInOtherFile.symbols
  tests/baselines/reference/indexSignatureInOtherFile.types
  tests/baselines/reference/indexSignatureInOtherFile1.errors.txt
  tests/baselines/reference/indexSignatureInOtherFile1.js
  tests/baselines/reference/indexSignatureInOtherFile1.symbols
  tests/baselines/reference/indexSignatureInOtherFile1.types
  tests/baselines/reference/symbolProperty32.errors.txt
  tests/cases/compiler/indexSignatureInOtherFile.ts
  tests/cases/compiler/indexSignatureInOtherFile1.ts
Labels: Author: Team, For Milestone Bug

#49875 feat(49358): [refactoring] Move to a new file should pick a name based on exported names rather than the first named thing encountered
  src/services/refactors/moveToNewFile.ts
  tests/cases/fourslash/moveToNewFile_fileNameBasedOnExportedName.ts
Labels: For Backlog Bug

#50082 Fix trailing formatting edit when range ends mid-token
  src/services/formatting/formatting.ts
  tests/cases/fourslash/formatTemplateStringOnPaste.ts
Labels: Author: Team, For Milestone Bug

#49901 feat(47983): Negative tuple index access should not be allowed
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/indexerWithTuple.errors.txt
  tests/baselines/reference/indexerWithTuple.js
  tests/baselines/reference/indexerWithTuple.symbols
  tests/baselines/reference/indexerWithTuple.types
  tests/cases/conformance/types/tuple/indexerWithTuple.ts
Labels: For Backlog Bug

#49904 fix dts generation of jsdoc
  src/compiler/checker.ts
  tests/baselines/reference/jsDeclarationsTypedefFunction.js
  tests/baselines/reference/jsDeclarationsTypedefFunction.symbols
  tests/baselines/reference/jsDeclarationsTypedefFunction.types
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsTypedefFunction.ts
Labels: For Backlog Bug

#50065 Add an additional test for favoring the asserted type in type predicate narrowing
  tests/baselines/reference/controlFlowFavorAssertedTypeThroughTypePredicate.errors.txt
  tests/baselines/reference/controlFlowFavorAssertedTypeThroughTypePredicate.symbols
  tests/baselines/reference/controlFlowFavorAssertedTypeThroughTypePredicate.types
  tests/cases/compiler/controlFlowFavorAssertedTypeThroughTypePredicate.ts
Labels: For Uncommitted Bug

#50074 Transform decorators that reference private names into a 'static {}' block
  src/compiler/factory/nodeFactory.ts
  src/compiler/transformers/legacyDecorators.ts
  src/compiler/types.ts
  tests/baselines/reference/decoratorOnClassMethod19(target=es2015).js
  tests/baselines/reference/decoratorOnClassMethod19(target=es2015).symbols
  tests/baselines/reference/decoratorOnClassMethod19(target=es2015).types
  tests/baselines/reference/decoratorOnClassMethod19(target=es2022).js
  tests/baselines/reference/decoratorOnClassMethod19(target=es2022).symbols
  tests/baselines/reference/decoratorOnClassMethod19(target=es2022).types
  tests/baselines/reference/decoratorOnClassMethod19(target=esnext).js
  tests/baselines/reference/decoratorOnClassMethod19(target=esnext).symbols
  tests/baselines/reference/decoratorOnClassMethod19(target=esnext).types
  tests/cases/conformance/decorators/class/method/decoratorOnClassMethod19.ts
Labels: Author: Team, For Milestone Bug

#50094 fix(49869): No error in JavaScript on optional binding pattern parameter
  src/compiler/checker.ts
  tests/baselines/reference/optionalBindingParameters3.errors.txt
  tests/baselines/reference/optionalBindingParameters3.symbols
  tests/baselines/reference/optionalBindingParameters3.types
  tests/cases/conformance/es6/destructuring/optionalBindingParameters3.ts
Labels: For Milestone Bug

#50104 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20220730104619999 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug
