Repository microsoft/TypeScript, pull requests merged in 2022-11, with the labels that each got.

#50976 Fix #50869, only cache calculated type for non-context sensitive parameters
  src/compiler/checker.ts
  tests/baselines/reference/completionDetailsOfContextSensitiveParameterNoCrash.baseline
  tests/cases/fourslash/completionDetailsOfContextSensitiveParameterNoCrash.ts
Labels: Author: Team, For Milestone Bug, Merge/Review for Next Release

#50929 Fix services' type's `isLiteral` implementation
  src/services/services.ts
  tests/cases/fourslash/completionsLiterals.ts
Labels: Breaking Change, Author: Team, For Uncommitted Bug

#50218 Fixed the issue with some longer variadic tuples with `any` rest being incorrectly assignable to shorter variadic tuples
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/restTupleElements1.errors.txt
  tests/baselines/reference/variadicTuples2.errors.txt
  tests/baselines/reference/variadicTuples2.js
  tests/baselines/reference/variadicTuples2.symbols
  tests/baselines/reference/variadicTuples2.types
  tests/cases/conformance/types/tuple/variadicTuples2.ts
Labels: For Backlog Bug

#50199 do not report use-before-declaration error in async IIFE initializer
  src/compiler/checker.ts
  tests/baselines/reference/blockScopedVariablesUseBeforeDef.errors.txt
  tests/baselines/reference/blockScopedVariablesUseBeforeDef.js
  tests/baselines/reference/blockScopedVariablesUseBeforeDef.symbols
  tests/baselines/reference/blockScopedVariablesUseBeforeDef.types
  tests/cases/compiler/blockScopedVariablesUseBeforeDef.ts
Labels: For Backlog Bug

#51379 There is no use of creating reference map with --out since its not used anyways
  src/compiler/builderState.ts
  src/testRunner/unittests/tsserver/compileOnSave.ts
  tests/baselines/reference/tsserver/compileOnSave/CompileOnSaveAffectedFileListRequest-when-projectFile-is-not-specified.js
  tests/baselines/reference/tsserver/compileOnSave/CompileOnSaveAffectedFileListRequest-when-projectFile-is-specified.js
  tests/baselines/reference/tsserver/compileOnSave/compileOnSaveAffectedFileList-projectUsesOutFile-should-be-true-if-out-is-set.js
  tests/baselines/reference/tsserver/compileOnSave/compileOnSaveAffectedFileList-projectUsesOutFile-should-be-true-if-outFile-is-set.js
  tests/baselines/reference/tsserver/compileOnSave/compileOnSaveAffectedFileList-projectUsesOutFile-should-not-be-returned-if-not-set.js
Labels: Author: Team, For Uncommitted Bug

#51405 Improve reduction of similar intersections in type inference
  src/compiler/checker.ts
  tests/baselines/reference/unionAndIntersectionInference3.js
  tests/baselines/reference/unionAndIntersectionInference3.symbols
  tests/baselines/reference/unionAndIntersectionInference3.types
  tests/cases/conformance/types/typeRelationships/typeInference/unionAndIntersectionInference3.ts
Labels: Author: Team, For Milestone Bug

#51403 Avoid unnecessary buildInfo read if host supports caching it (avoids in --build scenario) and some reporting cleanup
  src/compiler/emitter.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/program.ts
  src/compiler/tsbuildPublic.ts
  src/compiler/types.ts
  src/compiler/watch.ts
  src/executeCommandLine/executeCommandLine.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/tsbuild/outfile-concat/baseline-sectioned-sourcemaps.js
  tests/baselines/reference/tsbuild/outfile-concat/emitHelpers-in-all-projects.js
  tests/baselines/reference/tsbuild/outfile-concat/multiple-prologues-in-all-projects.js
  tests/baselines/reference/tsbuild/outfile-concat/shebang-in-all-projects.js
  tests/baselines/reference/tsbuild/outfile-concat/strict-in-all-projects.js
  tests/baselines/reference/tsbuild/outfile-concat/stripInternal-when-one-two-three-are-prepended-in-order.js
  tests/baselines/reference/tsbuild/outfile-concat/stripInternal.js
  tests/baselines/reference/tsbuild/outfile-concat/triple-slash-refs-in-all-projects.js
Labels: Author: Team, For Uncommitted Bug

#51378 fix(51374): ts(80004): Quick fix... > Annotate with type from JSDoc :: object types
  src/compiler/checker.ts
  src/compiler/utilities.ts
  src/services/codefixes/annotateWithTypeFromJSDoc.ts
  tests/cases/fourslash/annotateWithTypeFromJSDoc24.ts
  tests/cases/fourslash/annotateWithTypeFromJSDoc25.ts
  tests/cases/fourslash/annotateWithTypeFromJSDoc26.ts
Labels: For Uncommitted Bug

#49738 Pass in information for the module name resolution when resolutions from file are partially used
  src/compiler/moduleNameResolver.ts
  src/compiler/program.ts
  src/compiler/resolutionCache.ts
  src/compiler/tsbuildPublic.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/compiler/utilitiesPublic.ts
  src/compiler/watchPublic.ts
  src/server/project.ts
  src/services/types.ts
  src/testRunner/unittests/tscWatch/moduleResolution.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/tscWatch/moduleResolution/module-resolutions-from-file-are-partially-used.js
Labels: Author: Team, For Milestone Bug

#51432 Fix nightly post-#50528 merge
  src/debug/dbg.ts
Labels: Author: Team, For Uncommitted Bug

#49750 Reuse type reference directive resolutions
  src/compiler/moduleNameResolver.ts
  src/compiler/program.ts
  src/compiler/resolutionCache.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/compiler/watchPublic.ts
  src/server/project.ts
  src/services/types.ts
  src/testRunner/unittests/reuseProgramStructure.ts
  src/testRunner/unittests/tscWatch/moduleResolution.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/tscWatch/moduleResolution/type-reference-resolutions-reuse.js
Labels: Author: Team, For Uncommitted Bug

#50081 Add known keys of the mapped type constraint to its members
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypeGenericWithKnownKeys.errors.txt
  tests/baselines/reference/mappedTypeGenericWithKnownKeys.symbols
  tests/baselines/reference/mappedTypeGenericWithKnownKeys.types
  tests/cases/compiler/mappedTypeGenericWithKnownKeys.ts
Labels: For Backlog Bug

#51436 Depend on build-src in runtests
  Herebyfile.mjs
Labels: Author: Team, For Uncommitted Bug

#51445 Bump volta/packageManager in package.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#51438 Replace eslint-plugin-jsdoc by extending local jsdoc-format rule, saving ~20% of our linting time
  .eslintrc.json
  package-lock.json
  package.json
  scripts/eslint/rules/jsdoc-format.cjs
Labels: Author: Team, For Uncommitted Bug

#51459 Fix --bundle=false on Windows
  Herebyfile.mjs
Labels: Author: Team, For Uncommitted Bug

#51460 Add --no-typecheck option for runtests/runtests-parallel/min/local
  Herebyfile.mjs
  scripts/build/options.mjs
Labels: Author: Team, For Uncommitted Bug

#51465 Fix missing awaits in Herebyfile
  Herebyfile.mjs
Labels: Author: Team, For Uncommitted Bug

#51461 Simplistic watch mode for runtests
  Herebyfile.mjs
  package-lock.json
  package.json
  scripts/build/tests.mjs
  scripts/build/utils.mjs
Labels: Author: Team, For Uncommitted Bug

#51468 Make lkg task depend on local task instead
  Herebyfile.mjs
Labels: Author: Team, For Uncommitted Bug

#51456 Remove no-unnecessary-qualifier from eslintrc
  src/.eslintrc.json
  src/server/protocol.ts
  src/testRunner/unittests/tsserver/helpers.ts
  src/testRunner/unittests/tsserver/session.ts
  src/typingsInstallerCore/typingsInstaller.ts
Labels: Author: Team, For Uncommitted Bug

#51474 Fix __importDefault when used on typescript libraries
  src/tsserverlibrary/tsserverlibrary.ts
  src/typescript/typescript.ts
Labels: Author: Team, For Uncommitted Bug

#51475 Handle reusing type reference resolution in resolution cache correctly
  src/compiler/resolutionCache.ts
  src/testRunner/unittests/tscWatch/resolutionCache.ts
  tests/baselines/reference/tscWatch/resolutionCache/reusing-type-ref-resolution.js
Labels: Author: Team, For Uncommitted Bug

#51482 Add alias ResolutionMode for ModuleKind.ESNext | ModuleKind.CommonJs | undefined
  src/compiler/builderState.ts
  src/compiler/checker.ts
  src/compiler/moduleNameResolver.ts
  src/compiler/moduleSpecifiers.ts
  src/compiler/parser.ts
  src/compiler/program.ts
  src/compiler/resolutionCache.ts
  src/compiler/transformers/declarations.ts
  src/compiler/tsbuildPublic.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/compiler/watchPublic.ts
  src/server/project.ts
  src/services/documentRegistry.ts
  src/services/stringCompletions.ts
  src/services/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#51464 Add smoke tests to CI
  .github/workflows/ci.yml
Labels: Author: Team, For Uncommitted Bug

#51494 Fix smoke test substitution
  .github/workflows/ci.yml
Labels: Author: Team, For Uncommitted Bug

#51529 Undo accidental style changes from Map/Set PR
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/moduleNameResolver.ts
  src/compiler/moduleSpecifiers.ts
  src/compiler/program.ts
  src/compiler/transformers/es2018.ts
Labels: Author: Team, For Uncommitted Bug

#51258 fix(51112): Parameter JSDoc for a destructured parameter emits an error when a function uses arguments
  src/compiler/checker.ts
  tests/baselines/reference/jsdocParamTag2.errors.txt
  tests/baselines/reference/jsdocParamTag2.symbols
  tests/baselines/reference/jsdocParamTag2.types
  tests/cases/conformance/jsdoc/jsdocParamTag2.ts
Labels: For Milestone Bug

#51278 fix(51277): Array find thisArg fix from being void
  src/lib/es2015.core.d.ts
  tests/baselines/reference/arrayFind.types
  tests/baselines/reference/formatToPartsFractionalSecond.types
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty.errors.txt
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty.types
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty2.types
  tests/baselines/reference/thisInFunctionCall.errors.txt
  tests/baselines/reference/thisInFunctionCall.js
  tests/baselines/reference/thisInFunctionCall.symbols
  tests/baselines/reference/thisInFunctionCall.types
  tests/cases/compiler/thisInFunctionCall.ts
Labels: For Uncommitted Bug

#51365 Improving Date.getTime documentation
  src/lib/es5.d.ts
Labels: For Uncommitted Bug

#51274 Fix asyncDelegator reporting "done" too early
  src/compiler/factory/emitHelpers.ts
  src/testRunner/unittests/evaluation/asyncGenerator.ts
  tests/baselines/reference/emitter.asyncGenerators.classMethods.es2015.js
  tests/baselines/reference/emitter.asyncGenerators.classMethods.es5.js
  tests/baselines/reference/emitter.asyncGenerators.functionDeclarations.es2015.js
  tests/baselines/reference/emitter.asyncGenerators.functionDeclarations.es5.js
  tests/baselines/reference/emitter.asyncGenerators.functionExpressions.es2015.js
  tests/baselines/reference/emitter.asyncGenerators.functionExpressions.es5.js
  tests/baselines/reference/emitter.asyncGenerators.objectLiteralMethods.es2015.js
  tests/baselines/reference/emitter.asyncGenerators.objectLiteralMethods.es5.js
Labels: For Milestone Bug

#51543 fix: visitEachChild not traversing all nodes
  src/compiler/visitorPublic.ts
Labels: For Milestone Bug

#51561 Numeric literals assignable to enum literals only when values match
  src/compiler/checker.ts
  src/compiler/transformers/es2015.ts
  src/compiler/transformers/es2017.ts
  src/compiler/types.ts
  src/services/formatting/rule.ts
  src/services/formatting/rulesMap.ts
  src/testRunner/unittests/helpers.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/enumAssignability.errors.txt
  tests/baselines/reference/enumAssignmentCompat.errors.txt
  tests/baselines/reference/enumAssignmentCompat2.errors.txt
  tests/baselines/reference/enumAssignmentCompat5.errors.txt
  tests/baselines/reference/validEnumAssignments.errors.txt
Labels: Breaking Change, Author: Team, For Milestone Bug

#51575 Consistently respect --no-typecheck flag in build
  .vscode/tasks.json
  Herebyfile.mjs
  scripts/build/options.mjs
Labels: Author: Team, For Uncommitted Bug

#51152 Preserve alias symbols on references to type aliases via imports
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitExportAssignedNamespaceNoTripleSlashTypesReference.js
  tests/baselines/reference/declarationEmitExportAssignedNamespaceNoTripleSlashTypesReference.types
  tests/baselines/reference/declarationEmitRecursiveConditionalAliasPreserved.js
  tests/baselines/reference/declarationEmitRecursiveConditionalAliasPreserved.symbols
  tests/baselines/reference/declarationEmitRecursiveConditionalAliasPreserved.types
  tests/baselines/reference/genericInferenceDefaultTypeParameterJsxReact.types
  tests/baselines/reference/ramdaToolsNoInfinite2.types
  tests/cases/compiler/declarationEmitRecursiveConditionalAliasPreserved.ts
Labels: Author: Team, For Milestone Bug

#50781 Preserve input key style when writing mapped type keys in declaration emit
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitMappedTypePropertyFromNumericStringKey.js
  tests/baselines/reference/declarationEmitMappedTypePropertyFromNumericStringKey.symbols
  tests/baselines/reference/declarationEmitMappedTypePropertyFromNumericStringKey.types
  tests/cases/compiler/declarationEmitMappedTypePropertyFromNumericStringKey.ts
Labels: Author: Team, For Milestone Bug

#51562 Avoid emitting temp variable in downleveled import()
  src/compiler/transformers/module/module.ts
  tests/baselines/reference/asyncImportNestedYield.js
  tests/baselines/reference/dynamicImportEvaluateSpecifier.js
  tests/baselines/reference/dynamicImportTrailingComma.js
  tests/baselines/reference/importCallExpressionDeclarationEmit1.js
  tests/baselines/reference/importCallExpressionGrammarError.js
  tests/baselines/reference/importCallExpressionNestedCJS.js
  tests/baselines/reference/importCallExpressionNestedCJS2.js
  tests/baselines/reference/importCallExpressionReturnPromiseOfAny.js
  tests/baselines/reference/importCallExpressionSpecifierNotStringTypeError.js
  tests/baselines/reference/jsdocInTypeScript.js
Labels: For Uncommitted Bug

#51502 Fixed an issue with `in` not being able to be used on narrowed down expression of a generic nullable type
  src/compiler/checker.ts
  tests/baselines/reference/inKeywordTypeguard(strict=false).errors.txt
  tests/baselines/reference/inKeywordTypeguard(strict=false).js
  tests/baselines/reference/inKeywordTypeguard(strict=false).symbols
  tests/baselines/reference/inKeywordTypeguard(strict=false).types
  tests/baselines/reference/inKeywordTypeguard(strict=true).errors.txt
  tests/baselines/reference/inKeywordTypeguard(strict=true).js
  tests/baselines/reference/inKeywordTypeguard(strict=true).symbols
  tests/baselines/reference/inKeywordTypeguard(strict=true).types
  tests/cases/compiler/inKeywordTypeguard.ts
Labels: For Milestone Bug

#51634 Fix multiline import specifier sorting
  src/compiler/emitter.ts
  src/compiler/types.ts
  src/services/organizeImports.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/organizeImports1.ts
  tests/cases/fourslash/organizeImports13.ts
  tests/cases/fourslash/organizeImports2.ts
  tests/cases/fourslash/organizeImportsNoFormatOptions.ts
Labels: Author: Team, For Uncommitted Bug

#51631 Fix isTypeDerivedFrom to properly handle `{}` and intersections
  src/compiler/checker.ts
  tests/baselines/reference/inKeywordAndIntersection.js
  tests/baselines/reference/inKeywordAndIntersection.symbols
  tests/baselines/reference/inKeywordAndIntersection.types
  tests/baselines/reference/inKeywordAndUnknown.errors.txt
  tests/baselines/reference/inKeywordAndUnknown.js
  tests/baselines/reference/inKeywordAndUnknown.symbols
  tests/baselines/reference/inKeywordAndUnknown.types
  tests/cases/compiler/inKeywordAndIntersection.ts
  tests/cases/compiler/inKeywordAndUnknown.ts
Labels: Author: Team, For Milestone Bug

#51544 Cherry-pick fix around `visitEachChild` to release-4.9.
  src/compiler/visitorPublic.ts
Labels: Author: Team, For Uncommitted Bug

#51593 Dont calculate version paths proactively as they may not be needed
  src/compiler/moduleNameResolver.ts
  tests/baselines/reference/duplicatePackage_relativeImportWithinPackage.trace.json
  tests/baselines/reference/duplicatePackage_relativeImportWithinPackage_scoped.trace.json
  tests/baselines/reference/library-reference-11.trace.json
  tests/baselines/reference/library-reference-12.trace.json
  tests/baselines/reference/moduleResolutionWithExtensions_unexpected.trace.json
  tests/baselines/reference/moduleResolutionWithExtensions_unexpected2.trace.json
  tests/baselines/reference/moduleResolution_packageJson_notAtPackageRoot.trace.json
  tests/baselines/reference/moduleResolution_packageJson_notAtPackageRoot_fakeScopedPackage.trace.json
  tests/baselines/reference/moduleResolution_packageJson_scopedPackage.trace.json
  tests/baselines/reference/moduleResolution_packageJson_yesAtPackageRoot_mainFieldInSubDirectory.trace.json
  tests/baselines/reference/nodeModulesExportsBlocksTypesVersions(module=node16).trace.json
  tests/baselines/reference/nodeModulesExportsBlocksTypesVersions(module=nodenext).trace.json
  tests/baselines/reference/nodeModulesPackageImports(module=node16).trace.json
  tests/baselines/reference/nodeModulesPackageImports(module=nodenext).trace.json
  tests/baselines/reference/nodeModulesPackagePatternExportsTrailers(module=node16).trace.json
  tests/baselines/reference/nodeModulesPackagePatternExportsTrailers(module=nodenext).trace.json
  tests/baselines/reference/packageJsonMain.trace.json
  tests/baselines/reference/packageJsonMain_isNonRecursive.trace.json
  tests/baselines/reference/reactJsxReactResolvedNodeNextEsm.trace.json
  tests/baselines/reference/tsbuild/moduleResolution/impliedNodeFormat-differs-between-projects-for-shared-file.js
  tests/baselines/reference/tsbuild/moduleResolution/resolves-specifier-in-output-declaration-file-from-referenced-project-correctly-with-preserveSymlinks.js
  tests/baselines/reference/tsbuild/moduleResolution/resolves-specifier-in-output-declaration-file-from-referenced-project-correctly.js
  tests/baselines/reference/tsbuildWatch/moduleResolution/build-mode-watches-for-changes-to-package-json-main-fields.js
  tests/baselines/reference/tsbuildWatch/moduleResolution/resolves-specifier-in-output-declaration-file-from-referenced-project-correctly-with-cts-and-mts-extensions.js
  tests/baselines/reference/tsc/declarationEmit/when-same-version-is-referenced-through-source-and-another-symlinked-package-moduleCaseChange.js
  tests/baselines/reference/tsc/declarationEmit/when-same-version-is-referenced-through-source-and-another-symlinked-package-with-indirect-link-moduleCaseChange.js
  tests/baselines/reference/tsc/declarationEmit/when-same-version-is-referenced-through-source-and-another-symlinked-package-with-indirect-link.js
  tests/baselines/reference/tsc/declarationEmit/when-same-version-is-referenced-through-source-and-another-symlinked-package.js
  tests/baselines/reference/tscWatch/forceConsistentCasingInFileNames/package-json-is-looked-up-for-file.js
  tests/baselines/reference/tscWatch/forceConsistentCasingInFileNames/self-name-package-reference.js
  tests/baselines/reference/tscWatch/forceConsistentCasingInFileNames/with-nodeNext-resolution.js
  tests/baselines/reference/tscWatch/moduleResolution/diagnostics-from-cache.js
  tests/baselines/reference/tscWatch/moduleResolution/module-resolutions-from-file-are-partially-used.js
  tests/baselines/reference/tscWatch/moduleResolution/package-json-file-is-edited-when-package-json-with-type-module-exists.js
  tests/baselines/reference/tscWatch/moduleResolution/package-json-file-is-edited.js
  tests/baselines/reference/tscWatch/moduleResolution/type-reference-resolutions-reuse.js
  tests/baselines/reference/tscWatch/moduleResolution/watches-for-changes-to-package-json-main-fields.js
  tests/baselines/reference/tsserver/moduleResolution/package-json-file-is-edited-when-package-json-with-type-module-exists.js
  tests/baselines/reference/tsserver/moduleResolution/package-json-file-is-edited.js
  tests/baselines/reference/typesVersions.ambientModules.trace.json
  tests/baselines/reference/typesVersions.multiFile.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.ambient.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFile.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFileBackReferenceToUnmapped.trace.json
  tests/baselines/reference/typingsLookup4.trace.json
Labels: Author: Team, For Uncommitted Bug

#51674 Fix the crash when affected file pending emit is not in program is being serialized into buildInfo
  src/compiler/builder.ts
  src/testRunner/unittests/tsc/incremental.ts
  tests/baselines/reference/tsc/incremental/file-deleted-before-fixing-error-with-noEmitOnError.js
Labels: Author: Team, For Uncommitted Bug

#51626 When there is no change in file text for program, no need to update program
  src/compiler/tsbuildPublic.ts
  src/compiler/watch.ts
  src/compiler/watchPublic.ts
  src/testRunner/unittests/tscWatch/watchEnvironment.ts
  src/testRunner/unittests/virtualFileSystemWithWatch.ts
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependencies/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependencies/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependenciesAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependenciesAndD/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/default/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/default/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/defaultAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/defaultAndD/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModules/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModules/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModulesAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModulesAndD/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/watchApi/host-implements-hasInvalidatedResolutions.js
  tests/baselines/reference/tscWatch/watchEnvironment/fsEvent-for-change-is-repeated.js
Labels: Author: Team, For Uncommitted Bug

#51627 Port of #51626 and #51689 to release-4.9
  src/compiler/tsbuildPublic.ts
  src/compiler/watch.ts
  src/compiler/watchPublic.ts
  src/harness/virtualFileSystemWithWatch.ts
  src/testRunner/unittests/tscWatch/watchEnvironment.ts
  tests/baselines/reference/tsbuildWatch/noEmit/does-not-go-in-loop-when-watching-when-no-files-are-emitted-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependencies/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependencies/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependenciesAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependenciesAndD/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/default/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/default/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/defaultAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/defaultAndD/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModules/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModules/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModulesAndD/with-noEmitOnError-with-incremental.js
  tests/baselines/reference/tscWatch/emitAndErrorUpdates/isolatedModulesAndD/with-noEmitOnError.js
  tests/baselines/reference/tscWatch/watchApi/host-implements-hasInvalidatedResolutions.js
  tests/baselines/reference/tscWatch/watchEnvironment/fsEvent-for-change-is-repeated.js
Labels: Author: Team, For Uncommitted Bug

#51545 Fix isUnitLikeType to (again) handle tagged literal types
  src/compiler/checker.ts
  tests/baselines/reference/unknownControlFlow.errors.txt
  tests/baselines/reference/unknownControlFlow.js
  tests/baselines/reference/unknownControlFlow.symbols
  tests/baselines/reference/unknownControlFlow.types
  tests/cases/conformance/types/unknown/unknownControlFlow.ts
Labels: Author: Team, For Milestone Bug
