Repository microsoft/TypeScript, pull requests merged in 2023-01, with the labels that each got.

#51157 Infer fixed-size tuples from infer type parameters with extends clauses at variadic positions
  src/compiler/checker.ts
  tests/baselines/reference/inferTypesWithFixedTupleExtendsAtVariadicPosition.symbols
  tests/baselines/reference/inferTypesWithFixedTupleExtendsAtVariadicPosition.types
  tests/cases/compiler/inferTypesWithFixedTupleExtendsAtVariadicPosition.ts
Labels: For Backlog Bug

#52085 Add RegExp indices and hasIndices
  src/compiler/commandLineParser.ts
  src/lib/es2022.d.ts
  src/lib/es2022.regexp.d.ts
  src/lib/libs.json
  tests/baselines/reference/config/commandLineParsing/parseCommandLine/Parse --lib option with extra comma.js
  tests/baselines/reference/config/commandLineParsing/parseCommandLine/Parse --lib option with trailing white-space.js
  tests/baselines/reference/config/commandLineParsing/parseCommandLine/Parse invalid option of library flags.js
  tests/baselines/reference/contextualOverloadListFromUnionWithPrimitiveNoImplicitAny.symbols
  tests/baselines/reference/tsc/runWithoutArgs/does-not-add-color-when-NO_COLOR-is-set.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped-when-host-can't-provide-terminal-width.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
Labels: Author: Team, For Milestone Bug

#51216 fix(51198): The 'this' context of type 'T' is not assignable to method's 'this' of type 'this'
  src/compiler/checker.ts
  tests/baselines/reference/thisTypeInFunctionsNegative.errors.txt
  tests/baselines/reference/thisTypeInFunctionsNegative.js
  tests/baselines/reference/thisTypeInFunctionsNegative.symbols
  tests/baselines/reference/thisTypeInFunctionsNegative.types
  tests/cases/conformance/types/thisType/thisTypeInFunctionsNegative.ts
Labels: For Backlog Bug

#51964 Make Collection and ReadonlyCollection internal
  src/compiler/corePublic.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Breaking Change, API, Author: Team, For Uncommitted Bug

#51914 Call `getTypeOfSymbol` in `getNarrowedTypeOfSymbol` to avoid running into circularities when computing types
  src/compiler/checker.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  tests/cases/fourslash/circularGetTypeAtLocation.ts
  tests/cases/fourslash/fourslash.ts
Labels: Author: Team, For Milestone Bug

#52053 fix(52050): The space before satisfies after an array expression is removed when auto-formatting the statements
  src/services/formatting/rules.ts
  tests/cases/fourslash/formatSatisfiesExpression.ts
Labels: For Uncommitted Bug

#51791 Remove doc folder (old archived spec and assets), word2md script
  Herebyfile.mjs
  README.md
  doc/README.md
  doc/TypeScript Language Specification (Change Markup) - ARCHIVED.docx
  doc/TypeScript Language Specification (Change Markup) - ARCHIVED.pdf
  doc/TypeScript Language Specification - ARCHIVED.docx
  doc/TypeScript Language Specification - ARCHIVED.pdf
  doc/handbook/README.md
  doc/images/image1.png
  doc/images/image2.png
  doc/images/image3.png
  doc/images/image4.png
  doc/logo.svg
  doc/spec-ARCHIVED.md
  doc/wiki/README.md
  scripts/word.d.ts
  scripts/word2md.mjs
Labels: Author: Team, For Uncommitted Bug

#52122 Remove Push from public API
  src/compiler/commandLineParser.ts
  src/compiler/corePublic.ts
  src/compiler/utilitiesPublic.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Breaking Change, API, Author: Team, For Uncommitted Bug

#52123 Improve logic that chooses co- vs. contra-variant inferences
  src/compiler/checker.ts
  tests/baselines/reference/coAndContraVariantInferences2.js
  tests/baselines/reference/coAndContraVariantInferences2.symbols
  tests/baselines/reference/coAndContraVariantInferences2.types
  tests/cases/compiler/coAndContraVariantInferences2.ts
Labels: Author: Team, For Milestone Bug

#52091 Defer conditional types with multi-element tuple types in `extends` clause
  src/compiler/checker.ts
  tests/baselines/reference/deferredConditionalTypes.js
  tests/baselines/reference/deferredConditionalTypes.symbols
  tests/baselines/reference/deferredConditionalTypes.types
  tests/cases/compiler/deferredConditionalTypes.ts
Labels: Author: Team, For Milestone Bug

#52105 Improve JSX invalid children type error
  src/compiler/checker.ts
  tests/baselines/reference/jsxChildWrongType.errors.txt
  tests/baselines/reference/jsxChildWrongType.js
  tests/baselines/reference/jsxChildWrongType.symbols
  tests/baselines/reference/jsxChildWrongType.types
  tests/baselines/reference/jsxChildrenArrayWrongType.errors.txt
  tests/baselines/reference/jsxChildrenArrayWrongType.js
  tests/baselines/reference/jsxChildrenArrayWrongType.symbols
  tests/baselines/reference/jsxChildrenArrayWrongType.types
  tests/baselines/reference/jsxChildrenWrongType.errors.txt
  tests/baselines/reference/jsxChildrenWrongType.js
  tests/baselines/reference/jsxChildrenWrongType.symbols
  tests/baselines/reference/jsxChildrenWrongType.types
  tests/cases/compiler/jsxChildWrongType.tsx
  tests/cases/compiler/jsxChildrenArrayWrongType.tsx
  tests/cases/compiler/jsxChildrenWrongType.tsx
  tests/lib/react18/global.d.ts
  tests/lib/react18/react18.d.ts
Labels: Author: Team, For Milestone Bug

#51921 Use native generators/iterables, remove helper cruft
  src/compiler/builderState.ts
  src/compiler/checker.ts
  src/compiler/commandLineParser.ts
  src/compiler/core.ts
  src/compiler/corePublic.ts
  src/compiler/resolutionCache.ts
  src/compiler/scanner.ts
  src/compiler/sourcemap.ts
  src/compiler/transformers/declarations.ts
  src/compiler/transformers/jsx.ts
  src/compiler/tsbuildPublic.ts
  src/compiler/utilities.ts
  src/compiler/watchPublic.ts
  src/executeCommandLine/executeCommandLine.ts
  src/harness/collectionsImpl.ts
  src/harness/compilerImpl.ts
  src/harness/documentsUtil.ts
  src/harness/fourslashImpl.ts
  src/harness/harnessIO.ts
  src/harness/typeWriter.ts
  src/harness/vfsUtil.ts
  src/jsTyping/jsTyping.ts
  src/server/editorServices.ts
  src/server/session.ts
  src/services/codefixes/fixAddMissingMember.ts
  src/services/codefixes/helpers.ts
  src/services/codefixes/importFixes.ts
  src/services/documentHighlights.ts
  src/services/refactors/convertImport.ts
  src/services/refactors/extractSymbol.ts
  src/services/services.ts
  src/services/stringCompletions.ts
  src/services/transpile.ts
  src/testRunner/test262Runner.ts
  src/testRunner/unittests/config/commandLineParsing.ts
  src/testRunner/unittests/config/showConfig.ts
  src/testRunner/unittests/customTransforms.ts
  src/testRunner/unittests/moduleResolution.ts
  src/testRunner/unittests/tsc/helpers.ts
  src/testRunner/unittests/tsserver/cachingFileSystemInformation.ts
  src/testRunner/unittests/tsserver/completionsIncomplete.ts
  src/testRunner/unittests/tsserver/externalProjects.ts
  src/testRunner/unittests/tsserver/typingsInstaller.ts
  src/tsserver/nodeServer.ts
  src/typingsInstaller/nodeTypingsInstaller.ts
Labels: Author: Team, For Uncommitted Bug

#51855 Basic JSX attribute snippet fixes
  src/services/completions.ts
  tests/cases/fourslash/jsxAttributeSnippetCompletionClosed.ts
Labels: For Backlog Bug

#52109 Issue error on export= in esm mode declaration file
  src/compiler/checker.ts
  tests/baselines/reference/esmModeDeclarationFileWithExportAssignment.errors.txt
  tests/baselines/reference/esmModeDeclarationFileWithExportAssignment.js
  tests/baselines/reference/esmModeDeclarationFileWithExportAssignment.symbols
  tests/baselines/reference/esmModeDeclarationFileWithExportAssignment.types
  tests/cases/compiler/esmModeDeclarationFileWithExportAssignment.ts
Labels: Author: Team, For Uncommitted Bug

#52089 Reuse existing module specifiers in js declaration emit
  src/compiler/checker.ts
  tests/baselines/reference/importDeclFromTypeNodeInJsSource.js
  tests/baselines/reference/jsDeclarationEmitExportedClassWithExtends.js
  tests/baselines/reference/jsDeclarationEmitExportedClassWithExtends.symbols
  tests/baselines/reference/jsDeclarationEmitExportedClassWithExtends.types
  tests/baselines/reference/jsDeclarationsImportAliasExposedWithinNamespace.js
  tests/baselines/reference/jsDeclarationsReactComponents.js
  tests/baselines/reference/jsxDeclarationsWithEsModuleInteropNoCrash.js
  tests/cases/compiler/jsDeclarationEmitExportedClassWithExtends.ts
Labels: Author: Team, For Uncommitted Bug

#51126 Fixed false positive circular errors for await expressions with simple non-generic calls in CFA loops
  src/compiler/checker.ts
  tests/baselines/reference/controlFlowIterationErrorsAsync.errors.txt
  tests/baselines/reference/controlFlowIterationErrorsAsync.symbols
  tests/baselines/reference/controlFlowIterationErrorsAsync.types
  tests/baselines/reference/implicitAnyFromCircularInference.errors.txt
  tests/baselines/reference/implicitAnyFromCircularInference.js
  tests/baselines/reference/implicitAnyFromCircularInference.symbols
  tests/baselines/reference/implicitAnyFromCircularInference.types
  tests/cases/compiler/implicitAnyFromCircularInference.ts
  tests/cases/conformance/controlFlow/controlFlowIterationErrorsAsync.ts
Labels: For Backlog Bug, Merge/Review for Next Release

#52006 fix(51963): Invalid property read for find-all-references when exporting non-existent binding
  src/services/importTracker.ts
  tests/baselines/reference/findAllReferencesNonExistentExportBinding.baseline.jsonc
  tests/cases/fourslash/findAllReferencesNonExistentExportBinding.ts
Labels: For Uncommitted Bug

#51989 Allow indirect calls
  src/compiler/checker.ts
  tests/baselines/reference/commaOperatorLeftSideUnused.errors.txt
  tests/baselines/reference/commaOperatorLeftSideUnused.js
  tests/baselines/reference/commaOperatorLeftSideUnused.symbols
  tests/baselines/reference/commaOperatorLeftSideUnused.types
  tests/cases/compiler/commaOperatorLeftSideUnused.ts
Labels: For Backlog Bug

#52063 Add tests for excess property check for intersection containing a recursive type
  tests/baselines/reference/excessPropertyCheckIntersectionWithRecursiveType.errors.txt
  tests/baselines/reference/excessPropertyCheckIntersectionWithRecursiveType.symbols
  tests/baselines/reference/excessPropertyCheckIntersectionWithRecursiveType.types
  tests/cases/compiler/excessPropertyCheckIntersectionWithRecursiveType.ts
Labels: For Backlog Bug

#52136 fix narrowTypeByDiscriminant for non null expression access
  src/compiler/checker.ts
  src/compiler/utilities.ts
  tests/baselines/reference/narrowingUnionWithBang.js
  tests/baselines/reference/narrowingUnionWithBang.symbols
  tests/baselines/reference/narrowingUnionWithBang.types
  tests/cases/compiler/narrowingUnionWithBang.ts
Labels: Author: Team, For Milestone Bug

#52071 Add an extra test case for circular base type
  tests/baselines/reference/circularBaseTypes.errors.txt
  tests/baselines/reference/circularBaseTypes.js
  tests/baselines/reference/circularBaseTypes.symbols
  tests/baselines/reference/circularBaseTypes.types
  tests/cases/compiler/circularBaseTypes.ts
Labels: For Backlog Bug

#52032 Fixed crash when reporting infer extends on invalid name with declaration
  src/compiler/diagnosticMessages.json
  src/compiler/transformers/declarations/diagnostics.ts
  tests/baselines/reference/inferTypesInvalidExtendsDeclaration.errors.txt
  tests/baselines/reference/inferTypesInvalidExtendsDeclaration.js
  tests/baselines/reference/inferTypesInvalidExtendsDeclaration.symbols
  tests/baselines/reference/inferTypesInvalidExtendsDeclaration.types
  tests/baselines/reference/tsserver/plugins/getSupportedCodeFixes-can-be-proxied.js
  tests/cases/conformance/types/conditional/inferTypesInvalidExtendsDeclaration.ts
Labels: For Milestone Bug

#52070 Add a regression test for mapped type with as clause that bypassed interface extension check
  tests/baselines/reference/genericMappedTypeAsClause.errors.txt
  tests/baselines/reference/genericMappedTypeAsClause.js
  tests/baselines/reference/genericMappedTypeAsClause.symbols
  tests/baselines/reference/genericMappedTypeAsClause.types
  tests/cases/compiler/genericMappedTypeAsClause.ts
Labels: For Backlog Bug

#52069 Add a test for indexed access on generic mapped type
  tests/baselines/reference/correlatedUnions.js
  tests/baselines/reference/correlatedUnions.symbols
  tests/baselines/reference/correlatedUnions.types
  tests/cases/compiler/correlatedUnions.ts
Labels: For Uncommitted Bug

#52185 Ensure self-name resolution uses same extension priorities as external imports
  src/compiler/moduleNameResolver.ts
  tests/baselines/reference/selfNameModuleAugmentation.symbols
  tests/baselines/reference/selfNameModuleAugmentation.trace.json
  tests/baselines/reference/selfNameModuleAugmentation.types
  tests/cases/conformance/moduleResolution/selfNameModuleAugmentation.ts
Labels: Author: Team, For Uncommitted Bug

#49049 Fixed an issue with quickInfo crashing on a function property returned from generic function
  src/compiler/checker.ts
  tests/cases/fourslash/quickInfoOnFunctionPropertyReturnedFromGenericFunction1.ts
  tests/cases/fourslash/quickInfoOnFunctionPropertyReturnedFromGenericFunction2.ts
  tests/cases/fourslash/quickInfoOnFunctionPropertyReturnedFromGenericFunction3.ts
Labels: For Backlog Bug

#52189 Suppress resolvedUsingTsExtension during loadModuleFromDirectory
  src/compiler/moduleNameResolver.ts
  tests/baselines/reference/resolutionCandidateFromPackageJsonField1.js
  tests/baselines/reference/resolutionCandidateFromPackageJsonField1.symbols
  tests/baselines/reference/resolutionCandidateFromPackageJsonField1.types
  tests/baselines/reference/resolutionCandidateFromPackageJsonField2(moduleresolution=bundler).errors.txt
  tests/baselines/reference/resolutionCandidateFromPackageJsonField2(moduleresolution=bundler).js
  tests/baselines/reference/resolutionCandidateFromPackageJsonField2(moduleresolution=bundler).symbols
  tests/baselines/reference/resolutionCandidateFromPackageJsonField2(moduleresolution=bundler).types
  tests/baselines/reference/resolutionCandidateFromPackageJsonField2(moduleresolution=node10).errors.txt
  tests/baselines/reference/resolutionCandidateFromPackageJsonField2(moduleresolution=node10).js
  tests/baselines/reference/resolutionCandidateFromPackageJsonField2(moduleresolution=node10).symbols
  tests/baselines/reference/resolutionCandidateFromPackageJsonField2(moduleresolution=node10).types
  tests/cases/compiler/resolutionCandidateFromPackageJsonField1.ts
  tests/cases/compiler/resolutionCandidateFromPackageJsonField2.ts
Labels: Author: Team, For Uncommitted Bug

#51995 Fix nested package json lookup in modes that respect package.json exports
  src/compiler/moduleNameResolver.ts
  tests/baselines/reference/nestedPackageJsonRedirect(moduleresolution=bundler).trace.json
  tests/baselines/reference/nestedPackageJsonRedirect(moduleresolution=node16).trace.json
  tests/baselines/reference/nestedPackageJsonRedirect(moduleresolution=nodenext).trace.json
  tests/cases/conformance/moduleResolution/nestedPackageJsonRedirect.ts
Labels: Author: Team, For Uncommitted Bug

#52180 Tweak co/contra inference logic from #52123
  src/compiler/checker.ts
  tests/baselines/reference/coAndContraVariantInferences3.js
  tests/baselines/reference/coAndContraVariantInferences3.symbols
  tests/baselines/reference/coAndContraVariantInferences3.types
  tests/baselines/reference/coAndContraVariantInferences4.js
  tests/baselines/reference/coAndContraVariantInferences4.symbols
  tests/baselines/reference/coAndContraVariantInferences4.types
  tests/cases/compiler/coAndContraVariantInferences3.ts
  tests/cases/compiler/coAndContraVariantInferences4.ts
Labels: Author: Team, For Uncommitted Bug

#52184 fix(52177): Wrong space in type assertions when using array
  src/services/formatting/rules.ts
  tests/cases/fourslash/formatInsertSpaceAfterTypeAssertion.ts
Labels: For Backlog Bug

#51771 Fix inferences between alias type arguments and defaulted alias type arguments
  src/compiler/checker.ts
  tests/baselines/reference/importedAliasedConditionalTypeInstantiation.js
  tests/baselines/reference/importedAliasedConditionalTypeInstantiation.symbols
  tests/baselines/reference/importedAliasedConditionalTypeInstantiation.types
  tests/cases/compiler/importedAliasedConditionalTypeInstantiation.ts
Labels: Author: Team, For Milestone Bug

#52201 Fix bad baseline on main
  tests/baselines/reference/importedAliasedConditionalTypeInstantiation.js
Labels: Author: Team, For Uncommitted Bug

#52031 Don't widen when type parameter occurs at top level in type predicate
  src/compiler/checker.ts
  tests/baselines/reference/typePredicateTopLevelTypeParameter.js
  tests/baselines/reference/typePredicateTopLevelTypeParameter.symbols
  tests/baselines/reference/typePredicateTopLevelTypeParameter.types
  tests/cases/compiler/typePredicateTopLevelTypeParameter.ts
Labels: Author: Team, For Milestone Bug

#52170 Remove some properties from `Identifier`
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/factory/emitNode.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/factory/utilities.ts
  src/compiler/parser.ts
  src/compiler/transformers/classFields.ts
  src/compiler/transformers/es2015.ts
  src/compiler/transformers/es5.ts
  src/compiler/transformers/jsx.ts
  src/compiler/transformers/module/module.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/compiler/utilitiesPublic.ts
  src/compiler/visitorPublic.ts
  src/deprecatedCompat/4.0/nodeFactoryTopLevelExports.ts
  src/deprecatedCompat/5.0/identifierProperties.ts
  src/deprecatedCompat/_namespaces/ts.ts
  src/deprecatedCompat/deprecate.ts
  src/harness/harnessUtils.ts
  src/services/codefixes/convertToEsModule.ts
  src/services/completions.ts
  src/services/findAllReferences.ts
  src/services/refactors/extractSymbol.ts
  src/services/rename.ts
  src/services/services.ts
  src/services/textChanges.ts
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.@@ does not start a new tag.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.leadingAsterisk.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.no space before @ is not a new tag.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.noLeadingAsterisk.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.noReturnType.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.returnTag1.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.returnTag2.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.typeTag.json
  tests/baselines/reference/JSDocParsing/TypeExpressions.parsesCorrectly.keyword1.json
  tests/baselines/reference/JSDocParsing/TypeExpressions.parsesCorrectly.newType1.json
  tests/baselines/reference/JSDocParsing/TypeExpressions.parsesCorrectly.recordType8.json
  tests/baselines/reference/JSDocParsing/TypeExpressions.parsesCorrectly.thisType1.json
  tests/baselines/reference/JSDocParsing/TypeExpressions.parsesCorrectly.typeReference1.json
  tests/baselines/reference/JSDocParsing/TypeExpressions.parsesCorrectly.typeReference2.json
  tests/baselines/reference/JSDocParsing/TypeExpressions.parsesCorrectly.typeReference3.json
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#52173 Add additional diagnostic for packages that only resolve under non-`exports`-respecting modes
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/moduleNameResolver.ts
  src/compiler/types.ts
  tests/baselines/reference/nodeModulesExportsBlocksTypesVersions(module=node16).errors.txt
  tests/baselines/reference/nodeModulesExportsBlocksTypesVersions(module=node16).trace.json
  tests/baselines/reference/nodeModulesExportsBlocksTypesVersions(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesExportsBlocksTypesVersions(module=nodenext).trace.json
  tests/baselines/reference/resolvesWithoutExportsDiagnostic1(moduleresolution=bundler).errors.txt
  tests/baselines/reference/resolvesWithoutExportsDiagnostic1(moduleresolution=bundler).trace.json
  tests/baselines/reference/resolvesWithoutExportsDiagnostic1(moduleresolution=node16).errors.txt
  tests/baselines/reference/resolvesWithoutExportsDiagnostic1(moduleresolution=node16).trace.json
  tests/cases/conformance/moduleResolution/resolvesWithoutExportsDiagnostic1.ts
Labels: Author: Team, For Uncommitted Bug

#52129 Propagate constness of type parameters in variadic tuples
  src/compiler/checker.ts
  tests/baselines/reference/typeParameterConstModifiers.errors.txt
  tests/baselines/reference/typeParameterConstModifiers.js
  tests/baselines/reference/typeParameterConstModifiers.symbols
  tests/baselines/reference/typeParameterConstModifiers.types
  tests/cases/conformance/types/typeParameters/typeParameterLists/typeParameterConstModifiers.ts
Labels: Author: Team, For Milestone Bug

#52215 Instantiate rest type as needed in `getNarrowedTypeOfSymbol`
  src/compiler/checker.ts
  tests/baselines/reference/dependentDestructuredVariables.errors.txt
  tests/baselines/reference/dependentDestructuredVariables.js
  tests/baselines/reference/dependentDestructuredVariables.symbols
  tests/baselines/reference/dependentDestructuredVariables.types
  tests/cases/conformance/controlFlow/dependentDestructuredVariables.ts
Labels: Author: Team, For Milestone Bug

#52224 Only used cached `undefined` contextual type for requests with no flags
  src/compiler/checker.ts
  tests/baselines/reference/cachedContextualTypes.js
  tests/baselines/reference/cachedContextualTypes.symbols
  tests/baselines/reference/cachedContextualTypes.types
  tests/cases/compiler/cachedContextualTypes.ts
Labels: Author: Team, For Milestone Bug

#52213 fix(52212): No member completions, and irrelevant value completions, when class property initializer has no semicolon
  src/services/completions.ts
  tests/baselines/reference/completionsClassMembers1.baseline
  tests/baselines/reference/completionsClassMembers2.baseline
  tests/baselines/reference/completionsClassMembers3.baseline
  tests/cases/fourslash/completionsClassMembers1.ts
  tests/cases/fourslash/completionsClassMembers2.ts
  tests/cases/fourslash/completionsClassMembers3.ts
Labels: For Milestone Bug

#49636 Add Array.prototype.findLast() and Array.prototype.findLastIndex()
  src/compiler/commandLineParser.ts
  src/lib/es2023.array.d.ts
  src/lib/es2023.d.ts
  src/lib/es2023.full.d.ts
  src/lib/esnext.d.ts
  src/lib/libs.json
  tests/baselines/reference/callWithSpread4.symbols
  tests/baselines/reference/config/commandLineParsing/parseCommandLine/Parse --lib option with extra comma.js
  tests/baselines/reference/config/commandLineParsing/parseCommandLine/Parse --lib option with trailing white-space.js
  tests/baselines/reference/config/commandLineParsing/parseCommandLine/Parse invalid option of library flags.js
  tests/baselines/reference/dependentDestructuredVariables.symbols
  tests/baselines/reference/findLast.js
  tests/baselines/reference/findLast.symbols
  tests/baselines/reference/findLast.types
  tests/baselines/reference/flatArrayNoExcessiveStackDepth.symbols
  tests/baselines/reference/importExportInternalComments.symbols
  tests/baselines/reference/indexAt(target=esnext).symbols
  tests/baselines/reference/keyofAndIndexedAccess2.symbols
  tests/baselines/reference/noIterationTypeErrorsInCFA.symbols
  tests/baselines/reference/recursiveConditionalTypes.symbols
  tests/baselines/reference/taggedTemplatesWithTypeArguments1.symbols
  tests/baselines/reference/tsc/runWithoutArgs/does-not-add-color-when-NO_COLOR-is-set.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped-when-host-can't-provide-terminal-width.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
  tests/baselines/reference/typeGuardConstructorNarrowAny.symbols
  tests/baselines/reference/typeGuardConstructorPrimitiveTypes.symbols
  tests/cases/compiler/findLast.ts
Labels: For Milestone Bug

#52231 Fix `replacementSpan` for class member snippet completion entries
  src/harness/fourslashImpl.ts
  src/services/completions.ts
  src/services/stringCompletions.ts
  tests/baselines/reference/completionsClassMembers2.baseline
  tests/cases/fourslash/completionsOverridingMethod17.ts
  tests/cases/fourslash/importStatementCompletions1.ts
Labels: Author: Team, For Milestone Bug

#52246 fix(52233): Ambient modules declared with patterns are offered in path completions
  src/services/stringCompletions.ts
  tests/baselines/reference/completionForStringLiteralImport3.baseline
  tests/cases/fourslash/completionForStringLiteralImport3.ts
Labels: For Milestone Bug

#51981 Fix(51828): `extends` field in `tsconfig.json` does nothing with empty string
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  src/testRunner/unittests/config/configurationExtension.ts
  tests/baselines/reference/tsserver/plugins/getSupportedCodeFixes-can-be-proxied.js
Labels: Author: Team, For Milestone Bug

#50756 Improve uncalled function check related to parenthesized and binary expressions
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/transformers/es2021.ts
  src/compiler/utilities.ts
  tests/baselines/reference/truthinessCallExpressionCoercion2.errors.txt
  tests/baselines/reference/truthinessCallExpressionCoercion2.js
  tests/baselines/reference/truthinessCallExpressionCoercion2.symbols
  tests/baselines/reference/truthinessCallExpressionCoercion2.types
  tests/baselines/reference/uncalledFunctionChecksInConditional2.errors.txt
  tests/baselines/reference/uncalledFunctionChecksInConditional2.js
  tests/baselines/reference/uncalledFunctionChecksInConditional2.symbols
  tests/baselines/reference/uncalledFunctionChecksInConditional2.types
  tests/cases/compiler/truthinessCallExpressionCoercion2.ts
  tests/cases/compiler/uncalledFunctionChecksInConditional2.ts
Labels: For Backlog Bug

#52278 fix(52277): switch/case completions fail when has a negative literal type
  src/services/completions.ts
  tests/cases/fourslash/exhaustiveCaseCompletions7.ts
  tests/cases/fourslash/exhaustiveCaseCompletions8.ts
Labels: For Milestone Bug

#52230 Allow `allowImportingTsExtensions` to be set in any module resolution mode
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  src/compiler/moduleNameResolver.ts
  src/compiler/program.ts
  src/testRunner/unittests/tscWatch/programUpdates.ts
  tests/baselines/reference/bundlerImportTsExtensions(allowimportingtsextensions=true,noemit=false).errors.txt
  tests/baselines/reference/tscWatch/programUpdates/when-changing-`allowImportingTsExtensions`-of-config-file.js
  tests/cases/conformance/moduleResolution/allowImportingTsExtensions.ts
Labels: Author: Team, For Uncommitted Bug

#49929 Enable strictFunctionTypes
  src/compiler/builder.ts
  src/compiler/checker.ts
  src/compiler/commandLineParser.ts
  src/compiler/core.ts
  src/compiler/debug.ts
  src/compiler/emitter.ts
  src/compiler/factory/baseNodeFactory.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/factory/utilities.ts
  src/compiler/parser.ts
  src/compiler/path.ts
  src/compiler/program.ts
  src/compiler/scanner.ts
  src/compiler/symbolWalker.ts
  src/compiler/sys.ts
  src/compiler/transformers/classFields.ts
  src/compiler/transformers/declarations.ts
  src/compiler/transformers/destructuring.ts
  src/compiler/transformers/es2015.ts
  src/compiler/transformers/es2017.ts
  src/compiler/transformers/es2018.ts
  src/compiler/transformers/generators.ts
  src/compiler/transformers/jsx.ts
  src/compiler/transformers/legacyDecorators.ts
  src/compiler/transformers/module/esnextAnd2015.ts
  src/compiler/transformers/module/module.ts
  src/compiler/transformers/module/system.ts
  src/compiler/transformers/taggedTemplate.ts
  src/compiler/transformers/ts.ts
  src/compiler/tsbuildPublic.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/compiler/utilitiesPublic.ts
  src/compiler/visitorPublic.ts
  src/compiler/watch.ts
  src/compiler/watchPublic.ts
  src/harness/fakesHosts.ts
  src/harness/fourslashImpl.ts
  src/harness/harnessLanguageService.ts
  src/harness/harnessUtils.ts
  src/server/editorServices.ts
  src/server/project.ts
  src/server/session.ts
  src/services/codefixes/annotateWithTypeFromJSDoc.ts
  src/services/codefixes/helpers.ts
  src/services/codefixes/importFixes.ts
  src/services/refactors/extractSymbol.ts
  src/services/textChanges.ts
  src/services/utilities.ts
  src/testRunner/unittests/compilerCore.ts
  src/testRunner/unittests/customTransforms.ts
  src/testRunner/unittests/services/textChanges.ts
  src/testRunner/unittests/transform.ts
  src/testRunner/unittests/tsserver/cachingFileSystemInformation.ts
  src/testRunner/unittests/tsserver/helpers.ts
  src/testRunner/unittests/tsserver/session.ts
  src/tsconfig-base.json
  src/typingsInstallerCore/typingsInstaller.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Breaking Change, API, Author: Team, For Uncommitted Bug

#52238 Update to esbuild 0.17
  Herebyfile.mjs
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#52290 Enable noImplicitOverride
  src/harness/evaluatorImpl.ts
  src/harness/harnessLanguageService.ts
  src/server/project.ts
  src/services/services.ts
  src/services/shims.ts
  src/testRunner/externalCompileRunner.ts
  src/testRunner/parallel/host.ts
  src/testRunner/parallel/worker.ts
  src/testRunner/projectsRunner.ts
  src/testRunner/unittests/tsserver/helpers.ts
  src/testRunner/unittests/tsserver/session.ts
  src/testRunner/unittests/tsserver/typingsInstaller.ts
  src/tsconfig-base.json
  src/tsserver/nodeServer.ts
Labels: Author: Team, For Uncommitted Bug

#52026 Remove unnecessary `isTupleType` checks in `inferFromObjectTypes`
  src/compiler/checker.ts
Labels: Housekeeping, For Uncommitted Bug

#52307 Revert "Add undefined to JSON.stringify return type (#51897)"
  src/lib/es5.d.ts
  tests/baselines/reference/controlFlowPropertyDeclarations.symbols
  tests/baselines/reference/controlFlowPropertyDeclarations.types
  tests/baselines/reference/destructuringInitializerContextualTypeFromContext.symbols
  tests/baselines/reference/destructuringInitializerContextualTypeFromContext.types
  tests/baselines/reference/destructuringParameterDeclaration4.errors.txt
  tests/baselines/reference/destructuringTuple.errors.txt
  tests/baselines/reference/duplicateNumericIndexers.errors.txt
  tests/baselines/reference/json.stringify.js
  tests/baselines/reference/json.stringify.symbols
  tests/baselines/reference/json.stringify.types
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty.errors.txt
  tests/baselines/reference/parserharness.symbols
  tests/baselines/reference/parserharness.types
  tests/baselines/reference/promisePermutations.errors.txt
  tests/baselines/reference/promisePermutations2.errors.txt
  tests/baselines/reference/promisePermutations3.errors.txt
  tests/baselines/reference/redefineArray.errors.txt
  tests/baselines/reference/staticAnonymousTypeNotReferencingTypeParameter.symbols
  tests/baselines/reference/staticAnonymousTypeNotReferencingTypeParameter.types
  tests/cases/compiler/json.stringify.ts
Labels: Author: Team, For Uncommitted Bug

#52240 Make catch clause checking consistent with variable declarations
  src/compiler/checker.ts
  tests/baselines/reference/catchClauseWithTypeAnnotation.errors.txt
  tests/baselines/reference/catchClauseWithTypeAnnotation.js
  tests/baselines/reference/catchClauseWithTypeAnnotation.symbols
  tests/baselines/reference/catchClauseWithTypeAnnotation.types
  tests/baselines/reference/destructureCatchClause(strict=false,useunknownincatchvariables=false).errors.txt
  tests/baselines/reference/destructureCatchClause(strict=false,useunknownincatchvariables=false).js
  tests/baselines/reference/destructureCatchClause(strict=false,useunknownincatchvariables=false).symbols
  tests/baselines/reference/destructureCatchClause(strict=false,useunknownincatchvariables=false).types
  tests/baselines/reference/destructureCatchClause(strict=false,useunknownincatchvariables=true).errors.txt
  tests/baselines/reference/destructureCatchClause(strict=false,useunknownincatchvariables=true).js
  tests/baselines/reference/destructureCatchClause(strict=false,useunknownincatchvariables=true).symbols
  tests/baselines/reference/destructureCatchClause(strict=false,useunknownincatchvariables=true).types
  tests/baselines/reference/destructureCatchClause(strict=true,useunknownincatchvariables=false).errors.txt
  tests/baselines/reference/destructureCatchClause(strict=true,useunknownincatchvariables=false).js
  tests/baselines/reference/destructureCatchClause(strict=true,useunknownincatchvariables=false).symbols
  tests/baselines/reference/destructureCatchClause(strict=true,useunknownincatchvariables=false).types
  tests/baselines/reference/destructureCatchClause(strict=true,useunknownincatchvariables=true).errors.txt
  tests/baselines/reference/destructureCatchClause(strict=true,useunknownincatchvariables=true).js
  tests/baselines/reference/destructureCatchClause(strict=true,useunknownincatchvariables=true).symbols
  tests/baselines/reference/destructureCatchClause(strict=true,useunknownincatchvariables=true).types
  tests/baselines/reference/destructuringCatch.symbols
  tests/baselines/reference/jsdocCatchClauseWithTypeAnnotation.errors.txt
  tests/baselines/reference/jsdocCatchClauseWithTypeAnnotation.js
  tests/baselines/reference/jsdocCatchClauseWithTypeAnnotation.symbols
  tests/baselines/reference/jsdocCatchClauseWithTypeAnnotation.types
  tests/baselines/reference/redeclareParameterInCatchBlock.symbols
  tests/cases/compiler/destructureCatchClause.ts
  tests/cases/conformance/jsdoc/jsdocCatchClauseWithTypeAnnotation.ts
  tests/cases/conformance/statements/tryStatements/catchClauseWithTypeAnnotation.ts
Labels: Breaking Change, Author: Team, For Milestone Bug

#52178 Add followup test to #52123 test
  tests/baselines/reference/coAndContraVariantInferences2.js
  tests/baselines/reference/coAndContraVariantInferences2.symbols
  tests/baselines/reference/coAndContraVariantInferences2.types
  tests/cases/compiler/coAndContraVariantInferences2.ts
Labels: Author: Team, For Uncommitted Bug

#52115 Organize imports collation
  src/compiler/core.ts
  src/compiler/types.ts
  src/server/protocol.ts
  src/services/codefixes/importFixes.ts
  src/services/organizeImports.ts
  src/services/refactors/moveToNewFile.ts
  src/services/utilities.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/importNameCodeFix_order2.ts
  tests/cases/fourslash/organizeImportsPathsUnicode1.ts
  tests/cases/fourslash/organizeImportsPathsUnicode2.ts
  tests/cases/fourslash/organizeImportsPathsUnicode3.ts
  tests/cases/fourslash/organizeImportsPathsUnicode4.ts
  tests/cases/fourslash/organizeImportsUnicode1.ts
  tests/cases/fourslash/organizeImportsUnicode2.ts
  tests/cases/fourslash/organizeImportsUnicode3.ts
  tests/cases/fourslash/organizeImportsUnicode4.ts
Labels: Author: Team, For Uncommitted Bug

#52208 Deprecate CommandNames in favor of protocol.CommandTypes, direct import for better bundler output
  src/harness/client.ts
  src/server/editorServices.ts
  src/server/project.ts
  src/server/scriptInfo.ts
  src/server/scriptVersionCache.ts
  src/server/session.ts
  src/testRunner/unittests/tsserver/compileOnSave.ts
  src/testRunner/unittests/tsserver/declarationFileMaps.ts
  src/testRunner/unittests/tsserver/events/projectUpdatedInBackground.ts
  src/testRunner/unittests/tsserver/getEditsForFileRename.ts
  src/testRunner/unittests/tsserver/helpers.ts
  src/testRunner/unittests/tsserver/inferredProjects.ts
  src/testRunner/unittests/tsserver/navTo.ts
  src/testRunner/unittests/tsserver/occurences.ts
  src/testRunner/unittests/tsserver/projectErrors.ts
  src/testRunner/unittests/tsserver/projects.ts
  src/testRunner/unittests/tsserver/resolutionCache.ts
  src/testRunner/unittests/tsserver/session.ts
  src/testRunner/unittests/tsserver/skipLibCheck.ts
  src/testRunner/unittests/tsserver/smartSelection.ts
  src/tsserver/nodeServer.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/tsserver/resolutionCache/suppressed-diagnostic-events.js
Labels: Author: Team, For Uncommitted Bug

#52276 fix(52274): Suggestion code action adds another JSDoc
  src/services/codefixes/fixUnmatchedParameter.ts
  tests/cases/fourslash/codeFixDeleteUnmatchedParameter5.ts
Labels: For Milestone Bug

#52319 Derive allCommandNames from CommandTypes enum
  src/server/protocol.ts
  src/testRunner/unittests/tsserver/session.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
Labels: Author: Team, For Uncommitted Bug

#52209 fix type checking of variables named "exports"
  src/compiler/checker.ts
  tests/baselines/reference/typeCheckExportsVariable.errors.txt
  tests/baselines/reference/typeCheckExportsVariable.js
  tests/baselines/reference/typeCheckExportsVariable.symbols
  tests/baselines/reference/typeCheckExportsVariable.types
  tests/cases/compiler/typeCheckExportsVariable.ts
Labels: For Backlog Bug

#52287 fix(52270): update optionalReplacementSpan in continuePreviousIncompleteResponse
  src/services/completions.ts
  src/testRunner/unittests/tsserver/completionsIncomplete.ts
Labels: For Uncommitted Bug

#52314 Remove outdated deprecations
  src/deprecatedCompat/4.0/nodeFactoryTopLevelExports.ts
  src/deprecatedCompat/4.0/renamedNodeTests.ts
  src/deprecatedCompat/4.2/abstractConstructorTypes.ts
  src/deprecatedCompat/4.2/renamedNodeTests.ts
  src/deprecatedCompat/4.6/importTypeAssertions.ts
  src/deprecatedCompat/4.7/typeParameterModifiers.ts
  src/deprecatedCompat/4.8/mergeDecoratorsAndModifiers.ts
  src/deprecatedCompat/_namespaces/ts.ts
  src/testRunner/unittests/factory.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#52332 Don’t let unsorted import groups eagerly derail sort detection
  src/services/organizeImports.ts
  tests/cases/fourslash/organizeImports17.ts
Labels: Author: Team, For Uncommitted Bug

#52335 Make GitHub render json as jsonc
  .gitattributes
Labels: Author: Team, For Uncommitted Bug

#52048 Improve comparison operators type checking to disallow unions containing numbers as an operand
  src/compiler/checker.ts
  tests/baselines/reference/comparisonOperatorWithNoRelationshipTypeParameter.errors.txt
  tests/baselines/reference/comparisonOperatorWithNumberOperand.errors.txt
  tests/baselines/reference/comparisonOperatorWithNumberOperand.symbols
  tests/baselines/reference/comparisonOperatorWithNumberOperand.types
  tests/baselines/reference/controlFlowWhileStatement.errors.txt
  tests/cases/conformance/expressions/binaryOperators/comparisonOperator/comparisonOperatorWithNumberOperand.ts
Labels: Breaking Change, For Uncommitted Bug

#51524 fix(51521): Using a of property declared after an initializing constructor triggers an assertion failure in JS
  src/compiler/utilities.ts
  tests/baselines/reference/ambientPropertyDeclarationInJs.errors.txt
  tests/baselines/reference/ambientPropertyDeclarationInJs.symbols
  tests/baselines/reference/ambientPropertyDeclarationInJs.types
  tests/baselines/reference/quickInfoAtPropWithAmbientDeclarationInJs.baseline
  tests/cases/compiler/ambientPropertyDeclarationInJs.ts
  tests/cases/fourslash/quickInfoAtPropWithAmbientDeclarationInJs.ts
Labels: For Milestone Bug

#52284 Export more Node tests for use in public API
  src/compiler/factory/nodeTests.ts
  src/compiler/factory/utilities.ts
  src/compiler/utilitiesPublic.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#52328 Update DOM and baselines
  src/lib/dom.generated.d.ts
  src/lib/dom.iterable.generated.d.ts
  src/lib/webworker.generated.d.ts
  tests/baselines/reference/baseCheck.errors.txt
  tests/baselines/reference/expressionTypeNodeShouldError.symbols
  tests/baselines/reference/expressionTypeNodeShouldError.types
  tests/baselines/reference/extendArray.errors.txt
  tests/baselines/reference/globalThisBlockscopedProperties.types
  tests/baselines/reference/intersectionsOfLargeUnions2.errors.txt
  tests/baselines/reference/jsxFactoryIdentifierWithAbsentParameter.errors.txt
  tests/baselines/reference/jsxFactoryQualifiedNameResolutionError.errors.txt
  tests/baselines/reference/mappedTypeRecursiveInference.errors.txt
  tests/baselines/reference/mappedTypeRecursiveInference.types
  tests/baselines/reference/modularizeLibrary_Dom.iterable.symbols
  tests/baselines/reference/modularizeLibrary_Dom.iterable.types
  tests/baselines/reference/nonnullAssertionPropegatesContextualType.symbols
  tests/baselines/reference/nonnullAssertionPropegatesContextualType.types
  tests/baselines/reference/parserRealSource7.errors.txt
  tests/baselines/reference/typeFromPropertyAssignment21.types
Labels: Author: Team, For Milestone Bug

#52330 Elide line:col info in "!!! related" errors when from default lib.d.ts files
  src/harness/harnessIO.ts
  tests/baselines/reference/DateTimeFormatAndNumberFormatES2021.errors.txt
  tests/baselines/reference/asyncArrowFunction9_es2017.errors.txt
  tests/baselines/reference/asyncArrowFunction9_es5.errors.txt
  tests/baselines/reference/asyncArrowFunction9_es6.errors.txt
  tests/baselines/reference/baseCheck.errors.txt
  tests/baselines/reference/checkIndexConstraintOfJavascriptClassExpression.errors.txt
  tests/baselines/reference/destructuringParameterDeclaration4.errors.txt
  tests/baselines/reference/destructuringTuple.errors.txt
  tests/baselines/reference/errorMessageOnObjectLiteralType.errors.txt
  tests/baselines/reference/es2020IntlAPIs.errors.txt
  tests/baselines/reference/extendArray.errors.txt
  tests/baselines/reference/externModule.errors.txt
  tests/baselines/reference/intersectionsOfLargeUnions2.errors.txt
  tests/baselines/reference/invalidTypeOfTarget.errors.txt
  tests/baselines/reference/jsxFactoryIdentifierWithAbsentParameter.errors.txt
  tests/baselines/reference/jsxFactoryQualifiedNameResolutionError.errors.txt
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty.errors.txt
  tests/baselines/reference/narrowExceptionVariableInCatchClause.errors.txt
  tests/baselines/reference/narrowFromAnyWithInstanceof.errors.txt
  tests/baselines/reference/narrowFromAnyWithTypePredicate.errors.txt
  tests/baselines/reference/parserMemberAccessAfterPostfixExpression1.errors.txt
  tests/baselines/reference/parserRealSource7.errors.txt
  tests/baselines/reference/parserRegularExpressionDivideAmbiguity1.errors.txt
  tests/baselines/reference/parserRegularExpressionDivideAmbiguity2.errors.txt
  tests/baselines/reference/parserS7.2_A1.5_T2.errors.txt
  tests/baselines/reference/parserS7.3_A1.1_T2.errors.txt
  tests/baselines/reference/parserS7.6_A4.2_T1.errors.txt
  tests/baselines/reference/parserSymbolIndexer5.errors.txt
  tests/baselines/reference/parserUnicode1.errors.txt
  tests/baselines/reference/promisePermutations.errors.txt
  tests/baselines/reference/promisePermutations2.errors.txt
  tests/baselines/reference/promisePermutations3.errors.txt
  tests/baselines/reference/redefineArray.errors.txt
  tests/baselines/reference/scannerS7.2_A1.5_T2.errors.txt
  tests/baselines/reference/scannerS7.3_A1.1_T2.errors.txt
  tests/baselines/reference/scannerS7.6_A4.2_T1.errors.txt
  tests/baselines/reference/taggedTemplateStringsWithOverloadResolution1.errors.txt
  tests/baselines/reference/taggedTemplateStringsWithOverloadResolution1_ES6.errors.txt
  tests/baselines/reference/taggedTemplateStringsWithOverloadResolution3_ES6.errors.txt
  tests/baselines/reference/tsxStatelessFunctionComponents2.errors.txt
  tests/baselines/reference/types.asyncGenerators.es2018.2.errors.txt
  tests/baselines/reference/variableDeclarationInStrictMode1.errors.txt
Labels: Author: Team, For Uncommitted Bug

#52333 Add test case for #52271
  tests/baselines/reference/substitutionTypePassedToExtends.js
  tests/baselines/reference/substitutionTypePassedToExtends.symbols
  tests/baselines/reference/substitutionTypePassedToExtends.types
  tests/cases/compiler/substitutionTypePassedToExtends.ts
Labels: Author: Team, For Uncommitted Bug

#52374 Swap minestarks for zkat and joj in fabricbot.json
  .github/fabricbot.json
Labels: Author: Team, For Uncommitted Bug

#52376 Fix error in herebyfile after comparison strictness change
  scripts/build/options.mjs
  scripts/build/tests.mjs
Labels: Author: Team, For Uncommitted Bug

#52349 Plumb formatting to getDocCommentTemplateAtPosition
  src/harness/client.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/harness/harnessLanguageService.ts
  src/server/session.ts
  src/services/services.ts
  src/services/shims.ts
  src/services/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/docCommentTemplateClassDeclMethods01.ts
  tests/cases/fourslash/docCommentTemplateClassDeclMethods02.ts
  tests/cases/fourslash/docCommentTemplateClassDeclProperty01.ts
  tests/cases/fourslash/docCommentTemplateConstructor01.ts
  tests/cases/fourslash/docCommentTemplateExportAssignmentJS.ts
  tests/cases/fourslash/docCommentTemplateFunctionExpression.ts
  tests/cases/fourslash/docCommentTemplateFunctionWithParameters.ts
  tests/cases/fourslash/docCommentTemplateFunctionWithParameters_js.ts
  tests/cases/fourslash/docCommentTemplateInterfacePropertyFunctionType.ts
  tests/cases/fourslash/docCommentTemplateInterfacesEnumsAndTypeAliases.ts
  tests/cases/fourslash/docCommentTemplateJsSpecialPropertyAssignment.ts
  tests/cases/fourslash/docCommentTemplateObjectLiteralMethods01.ts
  tests/cases/fourslash/docCommentTemplatePrototypeMethod.ts
  tests/cases/fourslash/docCommentTemplateReturnsTag1.ts
  tests/cases/fourslash/docCommentTemplateReturnsTag2.ts
  tests/cases/fourslash/docCommentTemplateVariableStatements01.ts
  tests/cases/fourslash/docCommentTemplateVariableStatements03.ts
  tests/cases/fourslash/docCommentTemplate_insideEmptyComment.ts
Labels: Author: Team, For Uncommitted Bug

#52176 Add linkcode and linkplain to jsdoc tags
  src/services/jsDoc.ts
Labels: For Backlog Bug

#52384 feat(52366): @prop is not provided as a valid JSDoc tag in autocompletion
  src/services/jsDoc.ts
  tests/cases/fourslash/jsdocPropTagCompletion.ts
Labels: For Uncommitted Bug

#52390 fix(52386): JSDoc code fixes for arrow-function initialized const duplicates comment
  src/services/codefixes/fixUnmatchedParameter.ts
  tests/cases/fourslash/codeFixRenameUnmatchedParameter4.ts
Labels: For Milestone Bug

#52414 Suppress verbatimModuleSyntax error on ambient `export default`
  src/compiler/checker.ts
  tests/baselines/reference/verbatimModuleSyntaxRestrictionsCJS.errors.txt
  tests/baselines/reference/verbatimModuleSyntaxRestrictionsCJS.js
  tests/baselines/reference/verbatimModuleSyntaxRestrictionsCJS.symbols
  tests/baselines/reference/verbatimModuleSyntaxRestrictionsCJS.types
  tests/baselines/reference/verbatimModuleSyntaxRestrictionsESM(esmoduleinterop=false).errors.txt
  tests/baselines/reference/verbatimModuleSyntaxRestrictionsESM(esmoduleinterop=false).js
  tests/baselines/reference/verbatimModuleSyntaxRestrictionsESM(esmoduleinterop=true).errors.txt
  tests/baselines/reference/verbatimModuleSyntaxRestrictionsESM(esmoduleinterop=true).js
  tests/cases/conformance/externalModules/verbatimModuleSyntaxRestrictionsCJS.ts
  tests/cases/conformance/externalModules/verbatimModuleSyntaxRestrictionsESM.ts
Labels: Author: Team, For Uncommitted Bug

#52403 Revert part of catch clause PR which broke other declarations
  src/compiler/checker.ts
  tests/baselines/reference/potentiallyUnassignedVariableInCatch.js
  tests/baselines/reference/potentiallyUnassignedVariableInCatch.symbols
  tests/baselines/reference/potentiallyUnassignedVariableInCatch.types
  tests/cases/compiler/potentiallyUnassignedVariableInCatch.ts
Labels: Author: Team, For Uncommitted Bug

#52242 Add 2023 array methods to target features
  src/compiler/utilities.ts
  tests/baselines/reference/findLast(target=es2022).errors.txt
  tests/baselines/reference/findLast(target=es2022).js
  tests/baselines/reference/findLast(target=es2022).symbols
  tests/baselines/reference/findLast(target=es2022).types
  tests/baselines/reference/findLast(target=esnext).js
  tests/baselines/reference/findLast(target=esnext).symbols
  tests/baselines/reference/findLast(target=esnext).types
  tests/cases/compiler/findLast.ts
Labels: For Milestone Bug

#52411 Fixed a mistake in the `narrowingDestructuring` test
  tests/baselines/reference/narrowingDestructuring.js
  tests/baselines/reference/narrowingDestructuring.symbols
  tests/baselines/reference/narrowingDestructuring.types
  tests/cases/compiler/narrowingDestructuring.ts
Labels: For Uncommitted Bug

#52382 Reuse Printers with common options
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/services/callHierarchy.ts
  src/services/inlayHints.ts
  src/services/signatureHelp.ts
  src/services/symbolDisplay.ts
  src/services/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#52426 Port timestamp fix to 4.9
  src/compiler/watch.ts
Labels: Author: Team, For Uncommitted Bug

#52419 Port ignore deprecations to 4.9
  src/compiler/commandLineParser.ts
  tests/baselines/reference/config/showConfig/Shows tsconfig for single option/ignoreDeprecations/tsconfig.json
Labels: Author: Team, For Uncommitted Bug

#52423 Fix auto-imports with `--moduleResolution bundler` and `customConditions`
  src/compiler/moduleNameResolver.ts
  src/compiler/moduleSpecifiers.ts
  tests/cases/fourslash/autoImportBundlerExports.ts
  tests/cases/fourslash/autoImportsCustomConditions.ts
Labels: Author: Team, For Uncommitted Bug

#52437 Mark allowArbitraryExtensions as affectsProgramStructure
  src/compiler/commandLineParser.ts
  src/testRunner/unittests/tscWatch/programUpdates.ts
  tests/baselines/reference/tscWatch/programUpdates/Updates-diagnostics-when-'--allowArbitraryExtensions'-changes.js
Labels: Author: Team, For Uncommitted Bug

#52438 Mark new createPrinter vars as pure to remove new code from typingsInstaller
  src/compiler/emitter.ts
Labels: Author: Team, For Uncommitted Bug

#52448 Get export symbol if needed for verbatimModuleSyntax check on default/equals exports
  src/compiler/checker.ts
  tests/baselines/reference/verbatimModuleSyntaxDefaultValue.js
  tests/baselines/reference/verbatimModuleSyntaxDefaultValue.symbols
  tests/baselines/reference/verbatimModuleSyntaxDefaultValue.types
  tests/cases/compiler/verbatimModuleSyntaxDefaultValue.ts
Labels: Author: Team, For Uncommitted Bug

#52468 Ensure built/local exists before producing typesMap.json
  Herebyfile.mjs
Labels: Author: Team, For Uncommitted Bug

#52482 Remove extra checkDefined in visitEachChildOfJsxExpression
  src/compiler/visitorPublic.ts
  src/testRunner/unittests/transform.ts
  tests/baselines/reference/transformApi/transformsCorrectly.jsxExpression.js
Labels: Author: Team, For Uncommitted Bug

#52456 fix(52440): typeof ... === "undefined" check on mapped object member doesn't narrow correctly, for only some purposes
  src/compiler/checker.ts
  tests/baselines/reference/narrowingTypeofUndefined.symbols
  tests/baselines/reference/narrowingTypeofUndefined1.js
  tests/baselines/reference/narrowingTypeofUndefined1.symbols
  tests/baselines/reference/narrowingTypeofUndefined1.types
  tests/baselines/reference/narrowingTypeofUndefined2.js
  tests/baselines/reference/narrowingTypeofUndefined2.symbols
  tests/baselines/reference/narrowingTypeofUndefined2.types
  tests/cases/compiler/narrowingTypeofUndefined1.ts
  tests/cases/compiler/narrowingTypeofUndefined2.ts
Labels: For Backlog Bug

#52522 Prevent generation of dynamic require in library bundles
  Herebyfile.mjs
Labels: Author: Team, For Milestone Bug

#52523 Restore global `onProfilerEvent` hook for ts-perf
  src/compiler/performance.ts
Labels: Author: Team, For Uncommitted Bug

#52518 fix(52514): overload Tags do not receive noImplicitAny errors on missing return types
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/jsFileMethodOverloads3.errors.txt
  tests/baselines/reference/jsFileMethodOverloads3.symbols
  tests/baselines/reference/jsFileMethodOverloads3.types
  tests/baselines/reference/tsserver/plugins/getSupportedCodeFixes-can-be-proxied.js
  tests/cases/compiler/jsFileMethodOverloads3.ts
Labels: For Milestone Bug

#52373 Fix(50161): Instantiation expressions trigger incorrect error messages
  src/compiler/checker.ts
  src/testRunner/tests.ts
  src/testRunner/unittests/tsserver/inconsistentErrorInEditor.ts
  tests/baselines/reference/classExtendingClassLikeType.symbols
  tests/baselines/reference/classExtendsEveryObjectType.symbols
  tests/baselines/reference/classExtendsInterface.symbols
  tests/baselines/reference/classExtendsInterfaceInModule.symbols
  tests/baselines/reference/genericTypeReferenceWithoutTypeArgument2.symbols
  tests/baselines/reference/tsserver/inconsistentErrorInEditor/should-not-error.js
Labels: Author: Team, For Milestone Bug

#52536 Reject auto-imports of relative paths through node_modules in `bundler` resolution
  src/services/utilities.ts
  tests/cases/fourslash/autoImportBundlerBlockRelativeNodeModulesPaths.ts
Labels: Author: Team, For Uncommitted Bug
