Repository microsoft/TypeScript, pull requests merged in 2023-07, with the labels that each got.

#54802 Eliminate addJSDocComment in favor of consistently using withJSDoc
  src/compiler/parser.ts
Labels: Author: Team, For Uncommitted Bug

#54819 Fix self-name input linking for --allowJs --declaration projects
  src/compiler/commandLineParser.ts
  src/compiler/moduleNameResolver.ts
  tests/baselines/reference/nodeAllowJsPackageSelfName2.js
  tests/baselines/reference/nodeAllowJsPackageSelfName2.symbols
  tests/baselines/reference/nodeAllowJsPackageSelfName2.types
  tests/baselines/reference/tsserver/documentRegistry/Caches-the-source-file-if-script-info-is-orphan,-and-orphan-script-info-changes.js
  tests/baselines/reference/tsserver/documentRegistry/Caches-the-source-file-if-script-info-is-orphan.js
  tests/cases/conformance/node/allowJs/nodeAllowJsPackageSelfName2.ts
Labels: Author: Team, For Milestone Bug

#54869 Fix path completions with sibling dts lookup in exports
  src/services/stringCompletions.ts
  tests/cases/fourslash/pathCompletionsPackageJsonExportsWildcard7.ts
  tests/cases/fourslash/pathCompletionsPackageJsonExportsWildcard8.ts
  tests/cases/fourslash/pathCompletionsPackageJsonExportsWildcard9.ts
Labels: Author: Team, For Milestone Bug

#54868 Fix auto import path mapping when first pattern fails
  src/compiler/moduleSpecifiers.ts
  tests/cases/fourslash/autoImportPaths.ts
Labels: Author: Team, For Milestone Bug

#54875 Remove lib.d.ts line number info from new definition baselines
  src/harness/fourslashImpl.ts
  tests/baselines/reference/goToTypeDefinition_Pick.baseline.jsonc
  tests/baselines/reference/goToTypeDefinition_arrayType.baseline.jsonc
  tests/baselines/reference/goToTypeDefinition_promiseType.baseline.jsonc
Labels: Author: Team, For Uncommitted Bug

#54846 Emit `@overload` comments on generated overloads in.d.ts
  src/compiler/checker.ts
  tests/baselines/reference/jsFileFunctionOverloads.js
  tests/baselines/reference/jsFileFunctionOverloads2.js
  tests/baselines/reference/jsFileMethodOverloads.js
  tests/baselines/reference/jsFileMethodOverloads2.js
  tests/baselines/reference/overloadTag1.js
  tests/baselines/reference/overloadTag2.js
  tests/baselines/reference/templateInsideCallback.js
Labels: Author: Team, For Milestone Bug

#53647 Infer into recursive mapped type targets
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypeRecursiveInference.errors.txt
  tests/baselines/reference/mappedTypeRecursiveInference.types
  tests/baselines/reference/mappedTypeRecursiveInference2.symbols
  tests/baselines/reference/mappedTypeRecursiveInference2.types
  tests/cases/compiler/mappedTypeRecursiveInference2.ts
Labels: For Backlog Bug

#54534 scanNumber: smaller return value + side effects
  src/compiler/scanner.ts
Labels: Author: Team, For Uncommitted Bug

#54831 Offer auto-imports from wildcard exports with AutoImportProvider
  src/compiler/moduleNameResolver.ts
  src/compiler/moduleSpecifiers.ts
  src/server/project.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/cases/fourslash/server/autoImportProvider_wildcardExports1.ts
Labels: Author: Team, For Milestone Bug

#54329 fix(54310): "Move to file" does not eliminate re-export
  src/services/refactors/moveToFile.ts
  src/services/textChanges.ts
  tests/cases/fourslash/moveToFile_reExports1.ts
  tests/cases/fourslash/moveToFile_reExports2.ts
  tests/cases/fourslash/moveToFile_reExports3.ts
  tests/cases/fourslash/moveToFile_reExports4.ts
  tests/cases/fourslash/moveToFile_reExports5.ts
Labels: For Backlog Bug

#54912 fix(54902): Incorrect quick info on using declarations
  src/services/symbolDisplay.ts
  src/services/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/quickInfoDisplayPartsUsing.baseline
  tests/cases/fourslash/quickInfoDisplayPartsUsing.ts
Labels: For Milestone Bug

#54871 Fix export as default not auto importing
  src/services/utilities.ts
  tests/cases/fourslash/importNameCodeFixExportAsDefault.ts
  tests/cases/fourslash/importNameCodeFixExportAsDefaultExistingImport.ts
Labels: For Uncommitted Bug

#54922 ParseConfigHost needs to extend ModuleResolutionHost
  src/compiler/program.ts
  src/compiler/types.ts
  src/harness/fakesHosts.ts
  src/services/services.ts
  src/testRunner/tests.ts
  src/testRunner/unittests/helpers/extends.ts
  src/testRunner/unittests/tsbuild/extends.ts
  src/testRunner/unittests/tsc/extends.ts
  src/testRunner/unittests/tscWatch/extends.ts
  src/testRunner/unittests/tsserver/extends.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/tsbuild/extends/resolves-the-symlink-path.js
  tests/baselines/reference/tsc/extends/resolves-the-symlink-path.js
  tests/baselines/reference/tscWatch/extends/resolves-the-symlink-path.js
  tests/baselines/reference/tsserver/tsserver/resolves-the-symlink-path.js
Labels: Author: Team, For Backlog Bug

#54920 Add test for const enum usage with verbatimModuleSyntax
  tests/baselines/reference/verbatimModuleSyntaxConstEnumUsage.js
  tests/baselines/reference/verbatimModuleSyntaxConstEnumUsage.symbols
  tests/baselines/reference/verbatimModuleSyntaxConstEnumUsage.types
  tests/cases/conformance/externalModules/verbatimModuleSyntaxConstEnumUsage.ts
Labels: Author: Team, For Uncommitted Bug

#54975 Fix(54376)
  src/services/codefixes/importFixes.ts
  src/services/refactors/moveToFile.ts
  tests/cases/fourslash/moveToFile_blankExistingFile.ts
  tests/cases/fourslash/moveToFile_consistentQuoteStyle.ts
  tests/cases/fourslash/moveToFile_differentDirectories2.ts
Labels: Author: Team, For Milestone Bug

#54991 Downgrade octokit back to v19 to regain node 14/16 support
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#54994 Mark return type as referenced for metadata in parameter decorators
  src/compiler/checker.ts
  tests/baselines/reference/decoratorMetadataElidedImport(module=commonjs).js
  tests/baselines/reference/decoratorMetadataElidedImport(module=commonjs).symbols
  tests/baselines/reference/decoratorMetadataElidedImport(module=commonjs).types
  tests/baselines/reference/decoratorMetadataElidedImport(module=esnext).js
  tests/baselines/reference/decoratorMetadataElidedImport(module=esnext).symbols
  tests/baselines/reference/decoratorMetadataElidedImport(module=esnext).types
  tests/cases/compiler/decoratorMetadataElidedImport.ts
Labels: Author: Team, For Milestone Bug

#55008 Ensure all JSX spread properties get visited
  src/compiler/transformers/jsx.ts
  tests/baselines/reference/jsxSpreadTag.errors.txt
  tests/baselines/reference/jsxSpreadTag.js
  tests/baselines/reference/jsxSpreadTag.symbols
  tests/baselines/reference/jsxSpreadTag.types
  tests/cases/compiler/jsxSpreadTag.ts
Labels: Author: Team, For Uncommitted Bug

#54997 Consider `import.meta` a qualified name/property access
  src/compiler/utilities.ts
  tests/baselines/reference/importMeta(module=commonjs,target=es5).types
  tests/baselines/reference/importMeta(module=commonjs,target=esnext).types
  tests/baselines/reference/importMeta(module=es2020,target=es5).types
  tests/baselines/reference/importMeta(module=es2020,target=esnext).types
  tests/baselines/reference/importMeta(module=esnext,target=es5).types
  tests/baselines/reference/importMeta(module=esnext,target=esnext).types
  tests/baselines/reference/importMeta(module=system,target=es5).types
  tests/baselines/reference/importMeta(module=system,target=esnext).types
  tests/baselines/reference/importMetaNarrowing(module=es2020).types
  tests/baselines/reference/importMetaNarrowing(module=esnext).types
  tests/baselines/reference/importMetaNarrowing(module=system).types
  tests/baselines/reference/misspelledNewMetaProperty.types
  tests/baselines/reference/newTarget.es5.types
  tests/baselines/reference/newTarget.es6.types
  tests/baselines/reference/newTargetNarrowing.types
  tests/baselines/reference/nodeModulesAllowJsImportMeta(module=node16).types
  tests/baselines/reference/nodeModulesAllowJsImportMeta(module=nodenext).types
  tests/baselines/reference/nodeModulesImportMeta(module=node16).types
  tests/baselines/reference/nodeModulesImportMeta(module=nodenext).types
  tests/baselines/reference/plainJSGrammarErrors.types
  tests/baselines/reference/shadowedReservedCompilerDeclarationsWithNoEmit.types
  tests/cases/fourslash/importMetaCompletionDetails.ts
Labels: Author: Team, For Milestone Bug

#54959 Add test for old completion bug from prop of constraint
  tests/baselines/reference/completionPropertyFromConstraint.baseline
  tests/cases/fourslash/completionPropertyFromConstraint.ts
Labels: Author: Team, For Backlog Bug

#54972 Add test case for intersection/constraint bug fixed in 4.9
  tests/baselines/reference/intersectionSatisfiesConstraint.js
  tests/baselines/reference/intersectionSatisfiesConstraint.symbols
  tests/baselines/reference/intersectionSatisfiesConstraint.types
  tests/cases/compiler/intersectionSatisfiesConstraint.ts
Labels: Author: Team, For Backlog Bug

#54693 Updated typescript-eslint to v6
  .eslintrc.json
  package-lock.json
  package.json
  scripts/eslint/rules/argument-trivia.cjs
  scripts/eslint/rules/debug-assert.cjs
  scripts/eslint/rules/jsdoc-format.cjs
  scripts/eslint/rules/no-double-space.cjs
  scripts/eslint/rules/no-in-operator.cjs
  scripts/eslint/rules/no-keywords.cjs
  scripts/eslint/rules/no-type-assertion-whitespace.cjs
  scripts/eslint/rules/object-literal-surrounding-space.cjs
  scripts/eslint/rules/only-arrow-functions.cjs
  scripts/eslint/rules/simple-indent.cjs
  scripts/eslint/rules/type-operator-spacing.cjs
  src/compiler/checker.ts
  src/compiler/program.ts
  src/harness/fourslashImpl.ts
  src/server/editorServices.ts
  src/services/codefixes/convertToTypeOnlyImport.ts
  src/services/completions.ts
  src/services/refactors/convertImport.ts
  src/testRunner/unittests/helpers/virtualFileSystemWithWatch.ts
  src/testRunner/unittests/publicApi.ts
Labels: For Backlog Bug

#54835 Remove eslint-plugin-import
  .eslintrc.json
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#54969 fix(54951): using being too strict to throw on Function type
  src/compiler/factory/emitHelpers.ts
  src/testRunner/unittests/evaluation/usingDeclarations.ts
  tests/baselines/reference/awaitUsingDeclarations.1(target=es2015).js
  tests/baselines/reference/awaitUsingDeclarations.1(target=es2017).js
  tests/baselines/reference/awaitUsingDeclarations.1(target=es2022).js
  tests/baselines/reference/awaitUsingDeclarations.1(target=es5).js
  tests/baselines/reference/awaitUsingDeclarations.2(target=es2015).js
  tests/baselines/reference/awaitUsingDeclarations.2(target=es2017).js
  tests/baselines/reference/awaitUsingDeclarations.2(target=es2022).js
  tests/baselines/reference/awaitUsingDeclarations.2(target=es5).js
  tests/baselines/reference/awaitUsingDeclarations.3(target=es2015).js
  tests/baselines/reference/awaitUsingDeclarations.3(target=es2017).js
  tests/baselines/reference/awaitUsingDeclarations.3(target=es2022).js
  tests/baselines/reference/awaitUsingDeclarations.3(target=es5).js
  tests/baselines/reference/awaitUsingDeclarationsInFor(target=es2015).js
  tests/baselines/reference/awaitUsingDeclarationsInFor(target=es2017).js
  tests/baselines/reference/awaitUsingDeclarationsInFor(target=es2022).js
  tests/baselines/reference/awaitUsingDeclarationsInFor(target=es5).js
  tests/baselines/reference/awaitUsingDeclarationsInForAwaitOf(target=es2015).js
  tests/baselines/reference/awaitUsingDeclarationsInForAwaitOf(target=es2017).js
  tests/baselines/reference/awaitUsingDeclarationsInForAwaitOf(target=es2022).js
  tests/baselines/reference/awaitUsingDeclarationsInForAwaitOf(target=es5).js
  tests/baselines/reference/awaitUsingDeclarationsInForOf.1(target=es2015).js
  tests/baselines/reference/awaitUsingDeclarationsInForOf.1(target=es2017).js
  tests/baselines/reference/awaitUsingDeclarationsInForOf.1(target=es2022).js
  tests/baselines/reference/awaitUsingDeclarationsInForOf.1(target=es5).js
  tests/baselines/reference/usingDeclarations.1(target=es2015).js
  tests/baselines/reference/usingDeclarations.1(target=es2017).js
  tests/baselines/reference/usingDeclarations.1(target=es2022).js
  tests/baselines/reference/usingDeclarations.1(target=es5).js
  tests/baselines/reference/usingDeclarations.11.js
  tests/baselines/reference/usingDeclarations.12(usedefineforclassfields=false).js
  tests/baselines/reference/usingDeclarations.12(usedefineforclassfields=true).js
  tests/baselines/reference/usingDeclarations.2(target=es2015).js
  tests/baselines/reference/usingDeclarations.2(target=es2017).js
  tests/baselines/reference/usingDeclarations.2(target=es2022).js
  tests/baselines/reference/usingDeclarations.2(target=es5).js
  tests/baselines/reference/usingDeclarations.3(target=es2015).js
  tests/baselines/reference/usingDeclarations.3(target=es2017).js
  tests/baselines/reference/usingDeclarations.3(target=es2022).js
  tests/baselines/reference/usingDeclarations.3(target=es5).js
  tests/baselines/reference/usingDeclarationsInFor(target=es2015).js
  tests/baselines/reference/usingDeclarationsInFor(target=es2017).js
  tests/baselines/reference/usingDeclarationsInFor(target=es2022).js
  tests/baselines/reference/usingDeclarationsInFor(target=es5).js
  tests/baselines/reference/usingDeclarationsInForAwaitOf(target=es2015).js
  tests/baselines/reference/usingDeclarationsInForAwaitOf(target=es2017).js
  tests/baselines/reference/usingDeclarationsInForAwaitOf(target=es2022).js
  tests/baselines/reference/usingDeclarationsInForAwaitOf(target=es5).js
  tests/baselines/reference/usingDeclarationsInForOf.1(target=es2015).js
  tests/baselines/reference/usingDeclarationsInForOf.1(target=es2017).js
  tests/baselines/reference/usingDeclarationsInForOf.1(target=es2022).js
  tests/baselines/reference/usingDeclarationsInForOf.1(target=es5).js
  tests/baselines/reference/usingDeclarationsNamedEvaluationDecoratorsAndClassFields.js
Labels: For Milestone Bug

#54988 fix(54982): "Inline variable" causes failure when variable is used as the initializer of a destructured variable declaration
  src/services/refactors/inlineVariable.ts
  tests/cases/fourslash/inlineVariableDestructuredVariableDeclaration1.ts
  tests/cases/fourslash/inlineVariableDestructuredVariableDeclaration2.ts
  tests/cases/fourslash/inlineVariableDestructuredVariableDeclaration3.ts
  tests/cases/fourslash/inlineVariableDestructuredVariableDeclaration4.ts
Labels: For Milestone Bug

#54067 fix(54013): bug: Incorrect Typescript completion with computed property name
  src/services/completions.ts
  tests/baselines/reference/completionsUniqueSymbol2.baseline
  tests/cases/fourslash/completionsUniqueSymbol1.ts
  tests/cases/fourslash/completionsUniqueSymbol2.ts
Labels: For Backlog Bug

#54945 fix(54872): Have createUnionOfSignaturesForOverloadFailure() combine @deprecated tags properly
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/cases/fourslash/jsdocDeprecated_suggestion22.ts
Labels: For Backlog Bug

#54795 Grab the left type when narrowing by in operator lazily
  src/compiler/checker.ts
  tests/baselines/reference/controlFlowInOperator.js
  tests/baselines/reference/controlFlowInOperator.symbols
  tests/baselines/reference/controlFlowInOperator.types
  tests/cases/conformance/controlFlow/controlFlowInOperator.ts
Labels: For Backlog Bug

#54873 Fixed looking up assigned dynamic names on expando function expressions
  src/compiler/checker.ts
  tests/baselines/reference/expandoFunctionExpressionsWithDynamicNames.js
  tests/baselines/reference/expandoFunctionExpressionsWithDynamicNames.symbols
  tests/baselines/reference/expandoFunctionExpressionsWithDynamicNames.types
  tests/cases/compiler/expandoFunctionExpressionsWithDynamicNames.ts
Labels: For Backlog Bug

#54728 Fixed expando functions with nullish properties
  src/compiler/checker.ts
  tests/baselines/reference/expandoFunctionNullishProperty.js
  tests/baselines/reference/expandoFunctionNullishProperty.symbols
  tests/baselines/reference/expandoFunctionNullishProperty.types
  tests/cases/compiler/expandoFunctionNullishProperty.ts
Labels: For Uncommitted Bug

#54761 fix(54760): Report error for 'declare type' followed by newline
  src/compiler/parser.ts
  tests/baselines/reference/typeAliasDeclareKeywordNewlines.errors.txt
  tests/baselines/reference/typeAliasDeclareKeywordNewlines.js
  tests/baselines/reference/typeAliasDeclareKeywordNewlines.symbols
  tests/baselines/reference/typeAliasDeclareKeywordNewlines.types
  tests/cases/compiler/typeAliasDeclareKeywordNewlines.ts
Labels: For Milestone Bug

#54801 Fixed false positive syntax errors with in inside for
  src/compiler/parser.ts
  tests/baselines/reference/parserForInStatement8.errors.txt
  tests/baselines/reference/parserForInStatement8.js
  tests/baselines/reference/parserForInStatement8.symbols
  tests/baselines/reference/parserForInStatement8.types
  tests/baselines/reference/parserForOfStatement25.errors.txt
  tests/baselines/reference/parserForOfStatement25.js
  tests/baselines/reference/parserForOfStatement25.symbols
  tests/baselines/reference/parserForOfStatement25.types
  tests/baselines/reference/parserForStatement9.js
  tests/baselines/reference/parserForStatement9.symbols
  tests/baselines/reference/parserForStatement9.types
  tests/cases/conformance/parser/ecmascript5/Statements/parserForInStatement8.ts
  tests/cases/conformance/parser/ecmascript5/Statements/parserForStatement9.ts
  tests/cases/conformance/parser/ecmascript6/Iterators/parserForOfStatement25.ts
Labels: For Backlog Bug

#54726 Fixed expando functions with symbol-only properties
  src/compiler/checker.ts
  tests/baselines/reference/expandoFunctionSymbolProperty.js
  tests/baselines/reference/expandoFunctionSymbolProperty.symbols
  tests/baselines/reference/expandoFunctionSymbolProperty.types
  tests/baselines/reference/expandoFunctionSymbolPropertyJs.js
  tests/baselines/reference/expandoFunctionSymbolPropertyJs.symbols
  tests/baselines/reference/expandoFunctionSymbolPropertyJs.types
  tests/cases/compiler/expandoFunctionSymbolProperty.ts
  tests/cases/compiler/expandoFunctionSymbolPropertyJs.ts
Labels: For Backlog Bug

#54715 fix(54694): Class incorrectly implements interface generated with template string literal mapped type
  src/compiler/checker.ts
  src/compiler/utilities.ts
  src/services/codefixes/helpers.ts
  tests/cases/fourslash/codeFixClassImplementInterfaceMappedType1.ts
  tests/cases/fourslash/codeFixClassImplementInterfaceMappedType2.ts
Labels: For Backlog Bug

#54763 Fixed quick info display for aliased symbols in type-narrowed locations
  src/services/symbolDisplay.ts
  tests/cases/fourslash/quickInfoNarrowedTypeOfAliasSymbol.ts
Labels: For Backlog Bug

#54734 Interactable parameter inlay hints
  src/compiler/checker.ts
  src/compiler/types.ts
  src/harness/client.ts
  src/server/protocol.ts
  src/server/session.ts
  src/services/inlayHints.ts
  src/services/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/inlayHintsShouldWork1.baseline
  tests/baselines/reference/inlayHintsShouldWork11.baseline
  tests/baselines/reference/inlayHintsShouldWork12.baseline
  tests/baselines/reference/inlayHintsShouldWork13.baseline
  tests/baselines/reference/inlayHintsShouldWork2.baseline
  tests/baselines/reference/inlayHintsShouldWork23.baseline
  tests/baselines/reference/inlayHintsShouldWork3.baseline
  tests/baselines/reference/inlayHintsShouldWork32.baseline
  tests/baselines/reference/inlayHintsShouldWork33.baseline
  tests/baselines/reference/inlayHintsShouldWork34.baseline
  tests/baselines/reference/inlayHintsShouldWork35.baseline
  tests/baselines/reference/inlayHintsShouldWork36.baseline
  tests/baselines/reference/inlayHintsShouldWork4.baseline
  tests/baselines/reference/inlayHintsShouldWork5.baseline
  tests/baselines/reference/inlayHintsShouldWork50.baseline
  tests/baselines/reference/inlayHintsShouldWork52.baseline
  tests/baselines/reference/inlayHintsShouldWork53.baseline
  tests/baselines/reference/inlayHintsShouldWork6.baseline
  tests/baselines/reference/inlayHintsShouldWork62.baseline
  tests/baselines/reference/inlayHintsShouldWork63.baseline
  tests/baselines/reference/inlayHintsShouldWork64.baseline
  tests/baselines/reference/inlayHintsShouldWork68.baseline
  tests/baselines/reference/inlayHintsShouldWork7.baseline
  tests/baselines/reference/inlayHintsShouldWork8.baseline
  tests/baselines/reference/inlayHintsShouldWork9.baseline
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/inlayHintsShouldWork1.ts
  tests/cases/fourslash/inlayHintsShouldWork11.ts
  tests/cases/fourslash/inlayHintsShouldWork12.ts
  tests/cases/fourslash/inlayHintsShouldWork13.ts
  tests/cases/fourslash/inlayHintsShouldWork2.ts
  tests/cases/fourslash/inlayHintsShouldWork23.ts
  tests/cases/fourslash/inlayHintsShouldWork3.ts
  tests/cases/fourslash/inlayHintsShouldWork32.ts
  tests/cases/fourslash/inlayHintsShouldWork33.ts
  tests/cases/fourslash/inlayHintsShouldWork34.ts
  tests/cases/fourslash/inlayHintsShouldWork35.ts
  tests/cases/fourslash/inlayHintsShouldWork36.ts
  tests/cases/fourslash/inlayHintsShouldWork4.ts
  tests/cases/fourslash/inlayHintsShouldWork5.ts
  tests/cases/fourslash/inlayHintsShouldWork50.ts
  tests/cases/fourslash/inlayHintsShouldWork52.ts
  tests/cases/fourslash/inlayHintsShouldWork53.ts
  tests/cases/fourslash/inlayHintsShouldWork6.ts
  tests/cases/fourslash/inlayHintsShouldWork62.ts
  tests/cases/fourslash/inlayHintsShouldWork63.ts
  tests/cases/fourslash/inlayHintsShouldWork64.ts
  tests/cases/fourslash/inlayHintsShouldWork68.ts
  tests/cases/fourslash/inlayHintsShouldWork7.ts
  tests/cases/fourslash/inlayHintsShouldWork8.ts
  tests/cases/fourslash/inlayHintsShouldWork9.ts
Labels: For Uncommitted Bug

#54893 allow a colon directly after @ts-check/nocheck
  src/compiler/parser.ts
  tests/baselines/reference/ts-expect-error.errors.txt
  tests/baselines/reference/ts-expect-error.js
  tests/baselines/reference/ts-expect-error.symbols
  tests/baselines/reference/ts-expect-error.types
  tests/baselines/reference/ts-ignore.errors.txt
  tests/baselines/reference/ts-ignore.js
  tests/baselines/reference/ts-ignore.symbols
  tests/baselines/reference/ts-ignore.types
  tests/baselines/reference/tsNoCheckForTypescriptComments1.js
  tests/baselines/reference/tsNoCheckForTypescriptComments1.symbols
  tests/baselines/reference/tsNoCheckForTypescriptComments1.types
  tests/baselines/reference/tsNoCheckForTypescriptComments2.js
  tests/baselines/reference/tsNoCheckForTypescriptComments2.symbols
  tests/baselines/reference/tsNoCheckForTypescriptComments2.types
  tests/cases/conformance/directives/ts-expect-error.ts
  tests/cases/conformance/directives/ts-ignore.ts
  tests/cases/conformance/jsdoc/tsNoCheckForTypescriptComments1.ts
  tests/cases/conformance/jsdoc/tsNoCheckForTypescriptComments2.ts
Labels: For Backlog Bug

#54667 fix(54666): Codefix `convertTypedefToType to work for multiple typedefs in a row
  src/services/codefixes/convertTypedefToType.ts
  src/services/suggestionDiagnostics.ts
  tests/cases/fourslash/codeFixConvertTypedefToType4.ts
  tests/cases/fourslash/codeFixConvertTypedefToType6.ts
  tests/cases/fourslash/codeFixConvertTypedefToType7.ts
Labels: For Backlog Bug

#53921 fix(53919): Cannot read properties of undefined (reading 'flags') in returnValueCorrect
  src/services/codefixes/returnValueCorrect.ts
  tests/cases/fourslash/codeFixCorrectReturnValue28.ts
Labels: For Backlog Bug

#55054 Declaration emit for inlined mapped types preserves modifier-preserving behavior
  src/compiler/checker.ts
  tests/baselines/reference/inlineMappedTypeModifierDeclarationEmit.js
  tests/baselines/reference/inlineMappedTypeModifierDeclarationEmit.symbols
  tests/baselines/reference/inlineMappedTypeModifierDeclarationEmit.types
  tests/cases/compiler/inlineMappedTypeModifierDeclarationEmit.ts
Labels: Author: Team, For Milestone Bug

#54816 Export declarations exporting aliases make the namespace instantiated
  src/compiler/binder.ts
  tests/baselines/reference/reExportAliasMakesInstantiated.js
  tests/baselines/reference/reExportAliasMakesInstantiated.symbols
  tests/baselines/reference/reExportAliasMakesInstantiated.types
  tests/cases/conformance/internalModules/moduleDeclarations/reExportAliasMakesInstantiated.ts
Labels: Author: Team, For Milestone Bug

#55136 Triage and fix some eslint rules
  .eslintrc.json
  src/compiler/debug.ts
  src/compiler/watchPublic.ts
Labels: Author: Team, For Uncommitted Bug

#55131 Fix broken PR issue close command in GHA
  .github/workflows/pr-modified-files.yml
Labels: Author: Team, For Uncommitted Bug

#54746 Proposal: Always allow type-only imports to reference .ts extensions
  src/compiler/checker.ts
  src/services/codefixes/importFixes.ts
  tests/baselines/reference/allowsImportingTsExtension.errors.txt
  tests/baselines/reference/allowsImportingTsExtension.js
  tests/baselines/reference/allowsImportingTsExtension.symbols
  tests/baselines/reference/allowsImportingTsExtension.types
  tests/cases/conformance/externalModules/typeOnly/allowsImportingTsExtension.ts
  tests/cases/fourslash/completionsImport_promoteTypeOnly6.ts
  tests/cases/fourslash/completionsImport_promoteTypeOnly7.ts
Labels: Author: Team, For Uncommitted Bug

#54625 fix(45901): Error 1064 should apply to @callback definitions in the same way as @param, but doesn't
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/asyncFunctionDeclaration16_es5.errors.txt
  tests/baselines/reference/asyncFunctionDeclaration16_es5.symbols
  tests/baselines/reference/asyncFunctionDeclaration16_es5.types
  tests/baselines/reference/errorOnFunctionReturnType.errors.txt
  tests/cases/conformance/async/es5/functionDeclarations/asyncFunctionDeclaration16_es5.ts
Labels: For Backlog Bug

#55165 Handle composite signatures in isResolvingReturnTypeOfSignature
  src/compiler/checker.ts
  tests/baselines/reference/compositeContextualSignature.symbols
  tests/baselines/reference/compositeContextualSignature.types
  tests/cases/compiler/compositeContextualSignature.ts
Labels: Author: Team, For Milestone Bug

#55133 Enable @typescript-eslint/ban-types
  .eslintrc.json
  src/compiler/sys.ts
  src/harness/fourslashImpl.ts
Labels: Author: Team, For Uncommitted Bug

#55180 Move @typescript-eslint/no-namespace to disabled list
  .eslintrc.json
Labels: Author: Team, For Uncommitted Bug

#54558 Do not include undefined in indexed access on tuple types within range of total fixed elements
  src/compiler/checker.ts
  tests/baselines/reference/destructureTupleWithVariableElement.types
  tests/baselines/reference/indexedAccessWithVariableElement.errors.txt
  tests/baselines/reference/indexedAccessWithVariableElement.symbols
  tests/baselines/reference/indexedAccessWithVariableElement.types
  tests/baselines/reference/variadicTuples1.errors.txt
  tests/baselines/reference/variadicTuples1.js
  tests/baselines/reference/variadicTuples1.symbols
  tests/baselines/reference/variadicTuples1.types
  tests/cases/compiler/indexedAccessWithVariableElement.ts
  tests/cases/conformance/types/tuple/variadicTuples1.ts
Labels: For Backlog Bug

#54486 Provide member completions after dot in type locations using typeof
  src/compiler/checker.ts
  src/compiler/utilities.ts
  src/services/completions.ts
  tests/cases/fourslash/completionListObjectMembersInTypeLocationWithTypeof.ts
Labels: For Backlog Bug

#55028 fix use-before-init error when targeting ES2022
  src/compiler/checker.ts
  src/compiler/utilities.ts
  tests/baselines/reference/assignParameterPropertyToPropertyDeclarationES2022.errors.txt
  tests/baselines/reference/initializationOrdering1(target=es2021,usedefineforclassfields=false).js
  tests/baselines/reference/initializationOrdering1(target=es2021,usedefineforclassfields=false).symbols
  tests/baselines/reference/initializationOrdering1(target=es2021,usedefineforclassfields=false).types
  tests/baselines/reference/initializationOrdering1(target=es2021,usedefineforclassfields=true).js
  tests/baselines/reference/initializationOrdering1(target=es2021,usedefineforclassfields=true).symbols
  tests/baselines/reference/initializationOrdering1(target=es2021,usedefineforclassfields=true).types
  tests/baselines/reference/initializationOrdering1(target=es2022,usedefineforclassfields=false).js
  tests/baselines/reference/initializationOrdering1(target=es2022,usedefineforclassfields=false).symbols
  tests/baselines/reference/initializationOrdering1(target=es2022,usedefineforclassfields=false).types
  tests/baselines/reference/initializationOrdering1(target=es2022,usedefineforclassfields=true).errors.txt
  tests/baselines/reference/initializationOrdering1(target=es2022,usedefineforclassfields=true).js
  tests/baselines/reference/initializationOrdering1(target=es2022,usedefineforclassfields=true).symbols
  tests/baselines/reference/initializationOrdering1(target=es2022,usedefineforclassfields=true).types
  tests/baselines/reference/initializationOrdering1(target=esnext,usedefineforclassfields=false).js
  tests/baselines/reference/initializationOrdering1(target=esnext,usedefineforclassfields=false).symbols
  tests/baselines/reference/initializationOrdering1(target=esnext,usedefineforclassfields=false).types
  tests/baselines/reference/initializationOrdering1(target=esnext,usedefineforclassfields=true).errors.txt
  tests/baselines/reference/initializationOrdering1(target=esnext,usedefineforclassfields=true).js
  tests/baselines/reference/initializationOrdering1(target=esnext,usedefineforclassfields=true).symbols
  tests/baselines/reference/initializationOrdering1(target=esnext,usedefineforclassfields=true).types
  tests/baselines/reference/privateNameBadSuperUseDefineForClassFields(target=es2022).errors.txt
  tests/cases/conformance/classes/propertyMemberDeclarations/initializationOrdering1.ts
Labels: For Backlog Bug

#55138 Enable eslint rule no-useless-escape
  .eslintrc.json
  scripts/build/tests.mjs
  scripts/configurePrerelease.mjs
  src/compiler/core.ts
  src/compiler/debug.ts
  src/compiler/emitter.ts
  src/compiler/scanner.ts
  src/compiler/semver.ts
  src/compiler/utilities.ts
  src/compiler/utilitiesPublic.ts
  src/harness/fourslashImpl.ts
  src/harness/harnessIO.ts
  src/server/editorServices.ts
  src/services/codefixes/convertTypedefToType.ts
  src/services/codefixes/fixNaNEquality.ts
  src/services/completions.ts
  src/services/outliningElementsCollector.ts
  src/services/services.ts
  src/services/sourcemaps.ts
  src/testRunner/fourslashRunner.ts
  src/testRunner/projectsRunner.ts
  src/testRunner/runner.ts
  src/testRunner/unittests/base64.ts
  src/testRunner/unittests/convertToBase64.ts
  src/testRunner/unittests/helpers/tsserver.ts
  src/testRunner/unittests/incrementalParser.ts
  src/testRunner/unittests/tsbuild/commandLine.ts
  src/testRunner/unittests/tsc/incremental.ts
  src/testRunner/unittests/tscWatch/programUpdates.ts
  src/testRunner/unittests/tsserver/cachingFileSystemInformation.ts
  tests/baselines/reference/tsserver/cachingFileSystemInformation/npm-install-works-when-timeout-occurs-after-installation.js
  tests/baselines/reference/tsserver/cachingFileSystemInformation/npm-install-works-when-timeout-occurs-inbetween-installation.js
Labels: Author: Team, For Uncommitted Bug

#55012 Fix the type of Array.copyWithin #54967
  src/lib/es2015.core.d.ts
  src/lib/es2020.bigint.d.ts
  src/lib/es5.d.ts
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty.errors.txt
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty.types
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty2.js
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty2.types
Labels: For Uncommitted Bug

#55219 Temp fix till we investigate #55069 making project.ts changes building error free
  src/server/project.ts
Labels: Author: Team, For Uncommitted Bug

#55065 Wrap inline negative const enum with parens
  src/compiler/emitter.ts
  src/compiler/transformers/ts.ts
  src/testRunner/tests.ts
  src/testRunner/unittests/evaluation/constEnum.ts
  tests/baselines/reference/constEnumPropertyAccess3.js
  tests/baselines/reference/constEnumPropertyAccess3.symbols
  tests/baselines/reference/constEnumPropertyAccess3.types
  tests/baselines/reference/constEnumToStringNoComments.js
  tests/baselines/reference/constEnumToStringWithComments.js
  tests/cases/conformance/constEnums/constEnumPropertyAccess3.ts
Labels: For Backlog Bug
