Repository microsoft/TypeScript, pull requests merged in 2023-09, with the labels that each got.

#55602 Run dprint on json
  .c8rc.json
  .dprint.jsonc
  .eslintrc.json
  .github/workflow-resources/.lsifrc.json
  .vscode/extensions.json
  .vscode/launch.template.json
  .vscode/tasks.json
  scripts/tsconfig.json
  src/.eslintrc.json
  src/compiler/diagnosticMessages.json
  src/compiler/tsconfig.json
  src/harness/tsconfig.json
  src/server/typesMap.json
  src/testRunner/tsconfig.json
  src/tsconfig.json
  src/tsserver/tsconfig.json
Labels: Author: Team, For Uncommitted Bug

#55438 error on duplicate symbols in classes
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypeProperties.errors.txt
  tests/baselines/reference/staticPropertyNameConflicts(usedefineforclassfields=false).errors.txt
  tests/baselines/reference/staticPropertyNameConflicts(usedefineforclassfields=false).js
  tests/baselines/reference/staticPropertyNameConflicts(usedefineforclassfields=false).symbols
  tests/baselines/reference/staticPropertyNameConflicts(usedefineforclassfields=false).types
  tests/baselines/reference/staticPropertyNameConflicts(usedefineforclassfields=true).errors.txt
  tests/baselines/reference/staticPropertyNameConflicts(usedefineforclassfields=true).js
  tests/baselines/reference/staticPropertyNameConflicts(usedefineforclassfields=true).symbols
  tests/baselines/reference/staticPropertyNameConflicts(usedefineforclassfields=true).types
  tests/baselines/reference/symbolDeclarationEmit12.errors.txt
  tests/baselines/reference/symbolDeclarationEmit12.js
  tests/baselines/reference/symbolDeclarationEmit12.symbols
  tests/baselines/reference/symbolDeclarationEmit12.types
  tests/baselines/reference/symbolProperty44.errors.txt
  tests/baselines/reference/symbolProperty44.symbols
  tests/baselines/reference/uniqueSymbolsPropertyNames.errors.txt
  tests/baselines/reference/uniqueSymbolsPropertyNames.js
  tests/baselines/reference/uniqueSymbolsPropertyNames.symbols
  tests/baselines/reference/uniqueSymbolsPropertyNames.types
  tests/cases/conformance/classes/propertyMemberDeclarations/staticPropertyNameConflicts.ts
  tests/cases/conformance/types/uniqueSymbol/uniqueSymbolsPropertyNames.ts
Labels: For Backlog Bug

#55466 Ensure readJson in build throws when errors are present
  scripts/build/utils.mjs
Labels: Author: Team, For Uncommitted Bug

#55649 Don't debug assert on broken link in moduleNameResolver
  src/compiler/moduleNameResolver.ts
Labels: Author: Team, For Uncommitted Bug

#55651 Update SECURITY.md from 0.0.5 to 0.0.9
  SECURITY.md
Labels: For Uncommitted Bug

#55605 Add option to exclude library symbols from navTo results
  src/compiler/types.ts
  src/harness/client.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/server/protocol.ts
  src/server/session.ts
  src/services/navigateTo.ts
  src/services/services.ts
  src/services/types.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/navto_excludeLib1.ts
  tests/cases/fourslash/navto_excludeLib2.ts
  tests/cases/fourslash/navto_excludeLib3.ts
  tests/cases/fourslash/navto_excludeLib4.ts
  tests/cases/fourslash/server/navto_serverExcludeLib.ts
Labels: Author: Team, For Milestone Bug

#55443 fix: type key typo
  src/testRunner/unittests/helpers/baseline.ts
Labels: For Uncommitted Bug

#55624 Remove redundant code related to argument string completions
  src/compiler/checker.ts
  src/compiler/types.ts
  src/services/stringCompletions.ts
Labels: For Uncommitted Bug

#55233 Fix an off-by-one error in getBaseDirectoriesFromRootDirs
  src/services/stringCompletions.ts
  tests/cases/fourslash/completionForStringLiteralRelativeImport5.ts
  tests/cases/fourslash/completionForStringLiteralRelativeImport6.ts
Labels: For Uncommitted Bug

#55638 Track recursive homomorphic mapped types by the symbol of their target
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/deeplyNestedMappedTypes.errors.txt
  tests/baselines/reference/deeplyNestedMappedTypes.symbols
  tests/baselines/reference/deeplyNestedMappedTypes.types
  tests/cases/compiler/deeplyNestedMappedTypes.ts
Labels: Author: Team, For Milestone Bug

#55695 Fixed cache key computation for tuple target types with partially named members
  src/compiler/checker.ts
  tests/baselines/reference/partiallyNamedTuples2.js
  tests/baselines/reference/partiallyNamedTuples2.symbols
  tests/baselines/reference/partiallyNamedTuples2.types
  tests/cases/conformance/types/tuple/named/partiallyNamedTuples2.ts
Labels: For Uncommitted Bug

#55580 Update dprint to 0.41 and bump plugins
  .dprint.jsonc
  .github/workflows/ci.yml
  .vscode/settings.template.json
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#55721 fix(55694): format issues
  src/services/formatting/rules.ts
  tests/cases/fourslash/optionalPropertyFormatting.ts
Labels: For Backlog Bug

#55716 Fix issue with wildcard with supported extensions when plugins add external files and override getScriptKind to add script kinds for the additional extensions
  src/compiler/watchUtilities.ts
  src/server/editorServices.ts
  src/server/project.ts
  src/testRunner/unittests/tsserver/plugins.ts
  tests/baselines/reference/tsserver/plugins/new-files-with-non-ts-extensions-with-wildcard-matching.js
Labels: Author: Team, For Milestone Bug

#55690 Fix file matching with tsx and dts of same name are included by include patterns
  src/compiler/commandLineParser.ts
  src/testRunner/unittests/config/matchFiles.ts
  src/testRunner/unittests/tsbuild/clean.ts
  tests/baselines/reference/config/matchFiles/same named declarations with include dts tsx with json api.js
  tests/baselines/reference/config/matchFiles/same named declarations with include dts tsx with jsonSourceFile api.js
  tests/baselines/reference/config/matchFiles/same named declarations with include ts dts with json api.js
  tests/baselines/reference/config/matchFiles/same named declarations with include ts dts with jsonSourceFile api.js
  tests/baselines/reference/config/matchFiles/same named declarations with include ts tsx with json api.js
  tests/baselines/reference/config/matchFiles/same named declarations with include ts tsx with jsonSourceFile api.js
  tests/baselines/reference/config/matchFiles/same named declarations with include ts with json api.js
  tests/baselines/reference/config/matchFiles/same named declarations with include ts with jsonSourceFile api.js
  tests/baselines/reference/config/matchFiles/same named declarations with include tsx dts with json api.js
  tests/baselines/reference/config/matchFiles/same named declarations with include tsx dts with jsonSourceFile api.js
  tests/baselines/reference/config/matchFiles/same named declarations with include tsx ts with json api.js
  tests/baselines/reference/config/matchFiles/same named declarations with include tsx ts with jsonSourceFile api.js
  tests/baselines/reference/config/matchFiles/same named declarations with include tsx with json api.js
  tests/baselines/reference/config/matchFiles/same named declarations with include tsx with jsonSourceFile api.js
  tests/baselines/reference/tsbuild/clean/tsx-with-dts-emit.js
Labels: Author: Team, For Milestone Bug

#54678 refactor: let exportMapKey accepts bad symbol name
  src/harness/fourslashImpl.ts
  src/services/codefixes/importFixes.ts
  src/services/completions.ts
  src/services/exportInfoMap.ts
  src/services/types.ts
  src/testRunner/unittests/helpers/tsserver.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/importStatementCompletions3.baseline
  tests/baselines/reference/tsserver/autoImportProvider/Shared-source-files-between-AutoImportProvider-and-main-program.js
  tests/baselines/reference/tsserver/completions/works.js
  tests/baselines/reference/tsserver/completionsIncomplete/ambient-module-specifier-resolutions-do-not-count-against-the-resolution-limit.js
  tests/baselines/reference/tsserver/completionsIncomplete/resolves-more-when-available-from-module-specifier-cache-(1).js
  tests/baselines/reference/tsserver/completionsIncomplete/resolves-more-when-available-from-module-specifier-cache-(2).js
  tests/baselines/reference/tsserver/completionsIncomplete/works-for-transient-symbols-between-requests.js
  tests/baselines/reference/tsserver/completionsIncomplete/works-with-PackageJsonAutoImportProvider.js
  tests/baselines/reference/tsserver/completionsIncomplete/works.js
  tests/baselines/reference/tsserver/exportMapCache/caches-auto-imports-in-the-same-file.js
  tests/baselines/reference/tsserver/exportMapCache/does-not-invalidate-the-cache-when-package.json-is-changed-inconsequentially.js
  tests/baselines/reference/tsserver/exportMapCache/does-not-store-transient-symbols-through-program-updates.js
  tests/baselines/reference/tsserver/exportMapCache/invalidates-the-cache-when-files-are-deleted.js
  tests/baselines/reference/tsserver/exportMapCache/invalidates-the-cache-when-new-files-are-added.js
  tests/baselines/reference/tsserver/exportMapCache/invalidates-the-cache-when-package.json-change-results-in-AutoImportProvider-change.js
  tests/baselines/reference/tsserver/moduleSpecifierCache/caches-importability-within-a-file.js
  tests/baselines/reference/tsserver/moduleSpecifierCache/caches-module-specifiers-within-a-file.js
  tests/baselines/reference/tsserver/moduleSpecifierCache/does-not-invalidate-the-cache-when-new-files-are-added.js
  tests/baselines/reference/tsserver/moduleSpecifierCache/invalidates-module-specifiers-when-changes-happen-in-contained-node_modules-directories.js
  tests/baselines/reference/tsserver/moduleSpecifierCache/invalidates-the-cache-when-local-packageJson-changes.js
  tests/baselines/reference/tsserver/moduleSpecifierCache/invalidates-the-cache-when-module-resolution-settings-change.js
  tests/baselines/reference/tsserver/moduleSpecifierCache/invalidates-the-cache-when-symlinks-are-added-or-removed.js
  tests/baselines/reference/tsserver/moduleSpecifierCache/invalidates-the-cache-when-user-preferences-change.js
Labels: For Uncommitted Bug

#55723 Fix test harness bugs hidden by method behavior
  src/harness/fakesHosts.ts
  src/harness/harnessIO.ts
Labels: Author: Team, For Uncommitted Bug

#55625 Fixed display of optional and rest parameters created as result of combining union parameters
  src/compiler/checker.ts
  tests/baselines/reference/completionEntryForUnionMethod.baseline
  tests/cases/fourslash/completionEntryForUnionMethod.ts
  tests/cases/fourslash/quickInfoSignatureOptionalParameterFromUnion1.ts
  tests/cases/fourslash/quickInfoSignatureRestParameterFromUnion1.ts
  tests/cases/fourslash/quickInfoSignatureRestParameterFromUnion2.ts
  tests/cases/fourslash/quickInfoSignatureRestParameterFromUnion3.ts
  tests/cases/fourslash/quickInfoSignatureRestParameterFromUnion4.ts
Labels: For Milestone Bug

#55613 Fix issue with optional chaining and type inference in type guard
  src/compiler/checker.ts
  tests/baselines/reference/typePredicatesOptionalChaining1.js
  tests/baselines/reference/typePredicatesOptionalChaining1.symbols
  tests/baselines/reference/typePredicatesOptionalChaining1.types
  tests/baselines/reference/typePredicatesOptionalChaining2.js
  tests/baselines/reference/typePredicatesOptionalChaining2.symbols
  tests/baselines/reference/typePredicatesOptionalChaining2.types
  tests/baselines/reference/typePredicatesOptionalChaining3.js
  tests/baselines/reference/typePredicatesOptionalChaining3.symbols
  tests/baselines/reference/typePredicatesOptionalChaining3.types
  tests/cases/compiler/typePredicatesOptionalChaining1.ts
  tests/cases/compiler/typePredicatesOptionalChaining2.ts
  tests/cases/compiler/typePredicatesOptionalChaining3.ts
Labels: For Backlog Bug

#55541 Preserve `readonly` on mapped index signatures
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypeIndexSignatureModifiers.symbols
  tests/baselines/reference/mappedTypeIndexSignatureModifiers.types
  tests/baselines/reference/mappedTypes1.types
  tests/baselines/reference/staticIndexSignature5.types
  tests/cases/conformance/types/mapped/mappedTypeIndexSignatureModifiers.ts
Labels: For Backlog Bug

#55444 Fixed JSDoc get-only accessors to be serialized as `const`
  src/compiler/checker.ts
  tests/baselines/reference/accessorDeclarationEmitJs.js
Labels: For Uncommitted Bug

#55183 Fixed declaration emit for expando properties on function declarations declared using element access expressions
  src/compiler/checker.ts
  src/compiler/transformers/declarations.ts
  src/compiler/utilities.ts
  tests/baselines/reference/declarationEmitLateBoundAssignments2.js
  tests/baselines/reference/declarationEmitLateBoundAssignments2.symbols
  tests/baselines/reference/declarationEmitLateBoundAssignments2.types
  tests/cases/compiler/declarationEmitLateBoundAssignments2.ts
Labels: For Backlog Bug

#55554 Add friendly name to intrinsics in debug helpers
  src/compiler/checker.ts
  src/compiler/debug.ts
  src/compiler/types.ts
Labels: Author: Team, For Uncommitted Bug

#54271 fix(54266): Navtree doesn't return computed class members
  src/services/navigationBar.ts
  tests/cases/fourslash/navigationBarItemsComputedNames.ts
Labels: For Backlog Bug

#54944 Fixed an issue with errors not being correctly reported after completion requests in functions within nested calls
  src/compiler/checker.ts
  tests/baselines/reference/typeErrorAfterStringCompletionsInNestedCall2.baseline
  tests/cases/fourslash/typeErrorAfterStringCompletionsInNestedCall2.ts
Labels: For Uncommitted Bug

#52921 Skip parsing JSDoc when not needed
  src/compiler/parser.ts
  src/compiler/program.ts
  src/compiler/scanner.ts
  src/compiler/types.ts
  src/compiler/watch.ts
  src/compiler/watchPublic.ts
  src/executeCommandLine/executeCommandLine.ts
  src/testRunner/tests.ts
  src/testRunner/unittests/skipNonSemanticJSDocParsing.ts
  tests/baselines/reference/arrowFunctionJSDocAnnotation.symbols
  tests/baselines/reference/arrowFunctionJSDocAnnotation.types
  tests/baselines/reference/skipNonSemanticJSDocParsing/deprecated.diff
  tests/baselines/reference/skipNonSemanticJSDocParsing/link.diff
  tests/baselines/reference/skipNonSemanticJSDocParsing/see.diff
  tests/cases/compiler/arrowFunctionJSDocAnnotation.ts
Labels: Author: Team, For Uncommitted Bug

#55585 Fixed element access expression writes for divergent write types
  src/compiler/checker.ts
  src/compiler/utilities.ts
  tests/baselines/reference/divergentAccessorsTypes7.js
  tests/baselines/reference/divergentAccessorsTypes7.symbols
  tests/baselines/reference/divergentAccessorsTypes7.types
  tests/baselines/reference/divergentAccessorsTypes8.errors.txt
  tests/baselines/reference/divergentAccessorsTypes8.symbols
  tests/baselines/reference/divergentAccessorsTypes8.types
  tests/cases/compiler/divergentAccessorsTypes7.ts
  tests/cases/compiler/divergentAccessorsTypes8.ts
  tests/cases/fourslash/quickInfoOnElementAccessInWriteLocation1.ts
  tests/cases/fourslash/quickInfoOnElementAccessInWriteLocation2.ts
  tests/cases/fourslash/quickInfoOnElementAccessInWriteLocation3.ts
  tests/cases/fourslash/quickInfoOnElementAccessInWriteLocation4.ts
  tests/cases/fourslash/quickInfoOnElementAccessInWriteLocation5.ts
Labels: For Uncommitted Bug

#55740 Fix playright browser installs due to upstream breaking change
  .github/workflows/ci.yml
  .github/workflows/release-branch-artifact.yaml
  package-lock.json
  package.json
  scripts/browserIntegrationTest.mjs
Labels: Author: Team, For Uncommitted Bug

#55738 Special case "/workspaces" for watching root so that codespaces work correctly
  src/compiler/resolutionCache.ts
  src/testRunner/unittests/canWatch.ts
  src/testRunner/unittests/tsserver/watchEnvironment.ts
  tests/baselines/reference/canWatch/canWatchAffectingLocationDos.baseline.md
  tests/baselines/reference/canWatch/canWatchAffectingLocationPosix.baseline.md
  tests/baselines/reference/canWatch/canWatchAffectingLocationUnc.baseline.md
  tests/baselines/reference/canWatch/canWatchAffectingLocationUncDos.baseline.md
  tests/baselines/reference/canWatch/canWatchAtTypesDos.baseline.md
  tests/baselines/reference/canWatch/canWatchAtTypesPosix.baseline.md
  tests/baselines/reference/canWatch/canWatchAtTypesUnc.baseline.md
  tests/baselines/reference/canWatch/canWatchAtTypesUncDos.baseline.md
  tests/baselines/reference/canWatch/canWatchDirectoryOrFileDos.baseline.md
  tests/baselines/reference/canWatch/canWatchDirectoryOrFilePosix.baseline.md
  tests/baselines/reference/canWatch/canWatchDirectoryOrFileUnc.baseline.md
  tests/baselines/reference/canWatch/canWatchDirectoryOrFileUncDos.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationAtTypesDos.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationAtTypesPosix.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationAtTypesUnc.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationAtTypesUncDos.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationDos.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationFromTypeRootDos.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationFromTypeRootPosix.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationFromTypeRootUnc.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationFromTypeRootUncDos.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationNodeModulesDos.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationNodeModulesPosix.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationNodeModulesUnc.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationNodeModulesUncDos.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationPosix.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationUnc.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationUncDos.baseline.md
  tests/baselines/reference/tsserver/watchEnvironment/watching-npm-install-in-codespaces-where-workspaces-folder-is-hosted-at-root.js
Labels: Author: Team, For Milestone Bug

#55744 Fix narrowing of destructured tuples with different arities
  src/compiler/checker.ts
  tests/baselines/reference/dependentDestructuredVariables.errors.txt
  tests/baselines/reference/dependentDestructuredVariables.js
  tests/baselines/reference/dependentDestructuredVariables.symbols
  tests/baselines/reference/dependentDestructuredVariables.types
  tests/cases/conformance/controlFlow/dependentDestructuredVariables.ts
Labels: Author: Team, For Milestone Bug

#55506 Consistently return `errorType` for super expressions in classes that extend `null`
  src/compiler/checker.ts
  tests/baselines/reference/classExtendsNull2.errors.txt
  tests/baselines/reference/classExtendsNull2.symbols
  tests/baselines/reference/classExtendsNull2.types
  tests/baselines/reference/classExtendsNull3.errors.txt
  tests/baselines/reference/classExtendsNull3.symbols
  tests/baselines/reference/classExtendsNull3.types
  tests/cases/compiler/classExtendsNull2.ts
  tests/cases/compiler/classExtendsNull3.ts
Labels: For Milestone Bug

#53869 Allow unescaped paragraph and line separators in string literal
  src/compiler/scanner.ts
  tests/baselines/reference/allowUnescapedParagraphAndLineSeparatorsInStringLiteral.js
  tests/baselines/reference/allowUnescapedParagraphAndLineSeparatorsInStringLiteral.symbols
  tests/baselines/reference/allowUnescapedParagraphAndLineSeparatorsInStringLiteral.types
  tests/cases/conformance/es2019/allowUnescapedParagraphAndLineSeparatorsInStringLiteral.ts
Labels: For Uncommitted Bug

#50097 🐛 Fix not emitting comments between sibling fields of object literals
  src/compiler/emitter.ts
  tests/baselines/reference/arrowFunctionParsingDoesNotConfuseParenthesizedObjectForArrowHead.js
  tests/baselines/reference/assignmentCompatBug3.js
  tests/baselines/reference/bindingPatternCannotBeOnlyInferenceSource.js
  tests/baselines/reference/callSignaturesWithParameterInitializers2.js
  tests/baselines/reference/circularResolvedSignature.js
  tests/baselines/reference/commentsOnObjectLiteral5.js
  tests/baselines/reference/commentsOnObjectLiteral5.symbols
  tests/baselines/reference/commentsOnObjectLiteral5.types
  tests/baselines/reference/divergentAccessorsTypes6.js
  tests/baselines/reference/duplicateObjectLiteralProperty.js
  tests/baselines/reference/excessPropertyCheckWithMultipleDiscriminants.js
  tests/baselines/reference/excessPropertyCheckWithNestedArrayIntersection.js
  tests/baselines/reference/indexSignatures1.js
  tests/baselines/reference/namespaceImportTypeQuery2.js
  tests/baselines/reference/namespaceImportTypeQuery3.js
  tests/baselines/reference/namespaceImportTypeQuery4.js
  tests/baselines/reference/objectLitArrayDeclNoNew.js
  tests/baselines/reference/objectLiteralShorthandPropertiesErrorFromNoneExistingIdentifier.js
  tests/baselines/reference/privateNameBadDeclaration.js
  tests/baselines/reference/thisTypeInFunctions.js
  tests/baselines/reference/thisTypeInFunctionsNegative.js
  tests/baselines/reference/typeSatisfaction_contextualTyping2.js
  tests/baselines/reference/typeSatisfaction_propertyValueConformance3.js
  tests/baselines/reference/variableDeclaratorResolvedDuringContextualTyping.js
  tests/cases/compiler/commentsOnObjectLiteral5.ts
Labels: For Backlog Bug

#55750 Ensure generated property names for methods named "new" are quoted
  src/compiler/checker.ts
  src/compiler/utilities.ts
  src/services/codefixes/fixAddMissingMember.ts
  tests/baselines/reference/emitMethodCalledNew.js
  tests/baselines/reference/emitMethodCalledNew.symbols
  tests/baselines/reference/emitMethodCalledNew.types
  tests/baselines/reference/objectTypesIdentityWithConstructSignatures2.types
  tests/baselines/reference/objectTypesIdentityWithConstructSignaturesDifferingParamCounts.types
  tests/baselines/reference/objectTypesIdentityWithGenericConstructSignaturesDifferingByConstraints.types
  tests/baselines/reference/objectTypesIdentityWithGenericConstructSignaturesDifferingByConstraints2.types
  tests/baselines/reference/objectTypesIdentityWithGenericConstructSignaturesDifferingByConstraints3.types
  tests/baselines/reference/objectTypesIdentityWithGenericConstructSignaturesDifferingByReturnType.types
  tests/baselines/reference/objectTypesIdentityWithGenericConstructSignaturesDifferingByReturnType2.types
  tests/baselines/reference/objectTypesIdentityWithGenericConstructSignaturesDifferingTypeParameterCounts.types
  tests/baselines/reference/objectTypesIdentityWithGenericConstructSignaturesDifferingTypeParameterNames.types
  tests/baselines/reference/objectTypesIdentityWithGenericConstructSignaturesOptionalParams.types
  tests/baselines/reference/objectTypesIdentityWithGenericConstructSignaturesOptionalParams2.types
  tests/baselines/reference/objectTypesIdentityWithGenericConstructSignaturesOptionalParams3.types
  tests/baselines/reference/parser645484.types
  tests/baselines/reference/vardecl.types
  tests/cases/compiler/emitMethodCalledNew.ts
  tests/cases/fourslash/codeFixAddMissingMember31.ts
Labels: Author: Team, For Backlog Bug

#53681 Narrow by clause expressions in switches with `true` condition
  src/compiler/binder.ts
  src/compiler/checker.ts
  tests/baselines/reference/narrowByClauseExpressionInSwitchTrue.symbols
  tests/baselines/reference/narrowByClauseExpressionInSwitchTrue.types
  tests/cases/compiler/narrowByClauseExpressionInSwitchTrue.ts
Labels: For Uncommitted Bug

#53714 Narrow by comparisons to boolean literals
  src/compiler/binder.ts
  src/compiler/checker.ts
  tests/baselines/reference/narrowByBooleanComparison.symbols
  tests/baselines/reference/narrowByBooleanComparison.types
  tests/cases/compiler/narrowByBooleanComparison.ts
Labels: For Backlog Bug

#55264 fix(55258): JSDoc render with @param Object properties
  src/services/jsDoc.ts
  tests/baselines/reference/quickInfoJsDocTags12.baseline
  tests/cases/fourslash/quickInfoJsDocTags12.ts
Labels: For Backlog Bug

#55798 Update DOM before 5.3 beta
  src/lib/dom.generated.d.ts
  src/lib/webworker.generated.d.ts
Labels: Author: Team, For Milestone Bug

#55790 Source files not affected by all module resolution options
  src/compiler/builderState.ts
  src/compiler/checker.ts
  src/compiler/commandLineParser.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/moduleNameResolver.ts
  src/compiler/program.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/compiler/watch.ts
  src/server/project.ts
  src/services/codefixes/convertToEsModule.ts
  src/services/codefixes/fixImportNonExportedMember.ts
  src/services/codefixes/fixSpelling.ts
  src/services/codefixes/importFixes.ts
  src/services/findAllReferences.ts
  src/services/getEditsForFileRename.ts
  src/services/goToDefinition.ts
  src/services/refactors/moveToFile.ts
  src/services/services.ts
  src/services/suggestionDiagnostics.ts
  src/testRunner/unittests/reuseProgramStructure.ts
  src/testRunner/unittests/tsserver/symlinkCache.ts
  src/testRunner/unittests/tsserver/typingsInstaller.ts
  tests/baselines/reference/nodeColonModuleResolution.trace.json
  tests/baselines/reference/tsserver/documentRegistry/Caches-the-source-file-if-script-info-is-orphan,-and-orphan-script-info-changes.js
  tests/baselines/reference/tsserver/documentRegistry/Caches-the-source-file-if-script-info-is-orphan.js
Labels: Author: Team, For Uncommitted Bug

#54647 Support converting string literals to templates outside of concatenation
  src/compiler/diagnosticMessages.json
  src/services/refactors/convertStringOrTemplateLiteral.ts
  tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_ToTemplateInvalidLocation.ts
  tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_ToTemplateSimple.ts
  tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_ToTemplateSingleQuote.ts
Labels: Author: Team, For Uncommitted Bug

#55053 Fix CJS export of typedef and class w/latebound names
  src/compiler/checker.ts
  tests/baselines/reference/jsDeclarationsTypedefAndLatebound.symbols
  tests/baselines/reference/jsDeclarationsTypedefAndLatebound.types
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsTypedefAndLatebound.ts
Labels: Author: Team, For Milestone Bug

#55815 Fix export path patterns with .d.ts target extensions in AutoImportProvider
  src/compiler/moduleNameResolver.ts
  tests/cases/fourslash/server/autoImportProvider_wildcardExports2.ts
Labels: Author: Team, For Milestone Bug

#55118 Fixed string completions that require escaping
  src/services/stringCompletions.ts
  tests/cases/fourslash/stringCompletionsVsEscaping.ts
Labels: For Uncommitted Bug

#55739 Make JSDoc skipping public, plus more configurable
  src/compiler/parser.ts
  src/compiler/program.ts
  src/compiler/scanner.ts
  src/compiler/types.ts
  src/compiler/watch.ts
  src/compiler/watchPublic.ts
  src/executeCommandLine/executeCommandLine.ts
  src/harness/fakesHosts.ts
  src/harness/fourslashImpl.ts
  src/harness/harnessLanguageService.ts
  src/server/editorServices.ts
  src/server/project.ts
  src/services/documentRegistry.ts
  src/services/services.ts
  src/services/shims.ts
  src/services/textChanges.ts
  src/services/transpile.ts
  src/services/types.ts
  src/testRunner/tests.ts
  src/testRunner/unittests/skipJSDocParsing.ts
  src/testRunner/unittests/skipNonSemanticJSDocParsing.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/skipJSDocParsing/deprecated-ParseAll-file.js.diff
  tests/baselines/reference/skipJSDocParsing/deprecated-ParseAll-file.ts.diff
  tests/baselines/reference/skipJSDocParsing/deprecated-ParseForTypeErrors-file.js.diff
  tests/baselines/reference/skipJSDocParsing/deprecated-ParseForTypeErrors-file.ts.diff
  tests/baselines/reference/skipJSDocParsing/deprecated-ParseForTypeInfo-file.js.diff
  tests/baselines/reference/skipJSDocParsing/deprecated-ParseForTypeInfo-file.ts.diff
  tests/baselines/reference/skipJSDocParsing/deprecated-ParseNone-file.js.diff
  tests/baselines/reference/skipJSDocParsing/deprecated-ParseNone-file.ts.diff
  tests/baselines/reference/skipJSDocParsing/link-ParseAll-file.js.diff
  tests/baselines/reference/skipJSDocParsing/link-ParseAll-file.ts.diff
  tests/baselines/reference/skipJSDocParsing/link-ParseForTypeErrors-file.js.diff
  tests/baselines/reference/skipJSDocParsing/link-ParseForTypeErrors-file.ts.diff
  tests/baselines/reference/skipJSDocParsing/link-ParseForTypeInfo-file.js.diff
  tests/baselines/reference/skipJSDocParsing/link-ParseForTypeInfo-file.ts.diff
  tests/baselines/reference/skipJSDocParsing/link-ParseNone-file.js.diff
  tests/baselines/reference/skipJSDocParsing/link-ParseNone-file.ts.diff
  tests/baselines/reference/skipJSDocParsing/see-ParseAll-file.js.diff
  tests/baselines/reference/skipJSDocParsing/see-ParseAll-file.ts.diff
  tests/baselines/reference/skipJSDocParsing/see-ParseForTypeErrors-file.js.diff
  tests/baselines/reference/skipJSDocParsing/see-ParseForTypeErrors-file.ts.diff
  tests/baselines/reference/skipJSDocParsing/see-ParseForTypeInfo-file.js.diff
  tests/baselines/reference/skipJSDocParsing/see-ParseForTypeInfo-file.ts.diff
  tests/baselines/reference/skipJSDocParsing/see-ParseNone-file.js.diff
  tests/baselines/reference/skipJSDocParsing/see-ParseNone-file.ts.diff
Labels: Author: Team, For Uncommitted Bug

#55818 Picking resolutions of module for sourceFile as method
  src/compiler/builderState.ts
  src/compiler/checker.ts
  src/compiler/program.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/server/project.ts
  src/services/codefixes/convertToEsModule.ts
  src/services/codefixes/fixImportNonExportedMember.ts
  src/services/codefixes/fixSpelling.ts
  src/services/codefixes/importFixes.ts
  src/services/findAllReferences.ts
  src/services/getEditsForFileRename.ts
  src/services/goToDefinition.ts
  src/services/refactors/moveToFile.ts
  src/services/suggestionDiagnostics.ts
  src/testRunner/unittests/reuseProgramStructure.ts
  src/testRunner/unittests/tsserver/symlinkCache.ts
  src/testRunner/unittests/tsserver/typingsInstaller.ts
  tests/baselines/reference/reuseProgramStructure/can-reuse-ambient-module-declarations-from-non-modified-files.js
  tests/baselines/reference/reuseProgramStructure/can-reuse-module-resolutions-from-non-modified-files.js
  tests/baselines/reference/reuseProgramStructure/change-affects-a-single-module-of-a-package.js
  tests/baselines/reference/reuseProgramStructure/change-affects-imports.js
  tests/baselines/reference/reuseProgramStructure/change-affects-tripleslash-references.js
  tests/baselines/reference/reuseProgramStructure/change-affects-type-directives.js
  tests/baselines/reference/reuseProgramStructure/change-affects-type-references.js
  tests/baselines/reference/reuseProgramStructure/change-does-not-affect-imports-or-type-refs.js
  tests/baselines/reference/reuseProgramStructure/change-doesnot-affect-type-references.js
  tests/baselines/reference/reuseProgramStructure/config-path-changes.js
  tests/baselines/reference/reuseProgramStructure/fetches-imports-after-npm-install.js
  tests/baselines/reference/reuseProgramStructure/missing-file-is-created.js
  tests/baselines/reference/reuseProgramStructure/missing-files-remain-missing.js
  tests/baselines/reference/reuseProgramStructure/module-kind-changes.js
  tests/baselines/reference/reuseProgramStructure/redirect-no-change.js
  tests/baselines/reference/reuseProgramStructure/redirect-previous-duplicate-packages.js
  tests/baselines/reference/reuseProgramStructure/redirect-target-changes.js
  tests/baselines/reference/reuseProgramStructure/redirect-underlying-changes.js
  tests/baselines/reference/reuseProgramStructure/redirect-with-getSourceFileByPath-no-change.js
  tests/baselines/reference/reuseProgramStructure/redirect-with-getSourceFileByPath-previous-duplicate-packages.js
  tests/baselines/reference/reuseProgramStructure/redirect-with-getSourceFileByPath-target-changes.js
  tests/baselines/reference/reuseProgramStructure/redirect-with-getSourceFileByPath-underlying-changes.js
  tests/baselines/reference/reuseProgramStructure/resolution-cache-follows-imports.js
  tests/baselines/reference/reuseProgramStructure/resolved-type-directives-cache-follows-type-directives.js
  tests/baselines/reference/reuseProgramStructure/resolvedImports-after-re-using-an-ambient-external-module-declaration.js
  tests/baselines/reference/reuseProgramStructure/rootdir-changes.js
  tests/baselines/reference/reuseProgramStructure/works-with-updated-SourceFiles.js
Labels: Author: Team, For Uncommitted Bug

#55814 Incremental testing for program structure and resolutions and fixes
  src/compiler/program.ts
  src/compiler/resolutionCache.ts
  src/compiler/watchPublic.ts
  src/harness/incrementalUtils.ts
  src/server/editorServices.ts
  src/server/project.ts
  src/testRunner/unittests/helpers/baseline.ts
  src/testRunner/unittests/helpers/tsc.ts
  src/testRunner/unittests/helpers/tscWatch.ts
  src/testRunner/unittests/helpers/tsserver.ts
  src/testRunner/unittests/helpers/virtualFileSystemWithWatch.ts
  src/testRunner/unittests/tsbuild/publicApi.ts
  src/testRunner/unittests/tscWatch/forceConsistentCasingInFileNames.ts
  src/testRunner/unittests/tscWatch/resolutionCache.ts
  src/testRunner/unittests/tscWatch/sourceOfProjectReferenceRedirect.ts
  src/testRunner/unittests/tscWatch/watchApi.ts
  src/testRunner/unittests/tsserver/cachingFileSystemInformation.ts
  src/testRunner/unittests/tsserver/inferredProjects.ts
  src/testRunner/unittests/tsserver/maxNodeModuleJsDepth.ts
  src/testRunner/unittests/tsserver/symLinks.ts
  tests/baselines/reference/tsserver/inferredProjects/when-existing-inferred-project-has-no-root-files.js
  tests/baselines/reference/tsserver/maxNodeModuleJsDepth/handles-resolutions-when-currentNodeModulesDepth-changes-when-referencing-file-from-another-file.js
  tests/baselines/reference/tsserver/symLinks/when-not-symlink-but-differs-in-casing.js
Labels: Author: Team, For Uncommitted Bug

#55833 Use forEachResolvedModule in incremental utils
  src/harness/incrementalUtils.ts
Labels: Author: Team, For Uncommitted Bug

#55831 fix(55823) - Remove Braces From Arrow function fails when using satisfies
  src/services/utilities.ts
  tests/cases/fourslash/refactorAddOrRemoveBracesToArrowFunction35.ts
Labels: For Uncommitted Bug

#55822 Partially revert PR 55723 to fix OOM in testing
  src/harness/fakesHosts.ts
Labels: Author: Team, For Uncommitted Bug

#54662 Support using client watch in tsserver using events
  src/server/editorServices.ts
  src/server/protocol.ts
  src/server/session.ts
  src/testRunner/tests.ts
  src/testRunner/unittests/helpers/tsserver.ts
  src/testRunner/unittests/helpers/virtualFileSystemWithWatch.ts
  src/testRunner/unittests/tsserver/events/watchEvents.ts
  src/tsserver/common.ts
  src/tsserver/server.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/tsserver/events/watchEvents/canUseWatchEvents-without-canUseEvents.js
  tests/baselines/reference/tsserver/events/watchEvents/canUseWatchEvents.js
Labels: Author: Team, For Uncommitted Bug

#53628 Expose Signature.thisParameter
  src/compiler/types.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Uncommitted Bug

#49827 More did-you-mean errors on classes in plain JS
  src/compiler/checker.ts
  tests/cases/fourslash/codeFixSpellingJs9.ts
Labels: Author: Team, For Milestone Bug

#55429 fix(55404): Remove braces from arrow function" generates invalid code in JavaScript
  src/services/refactors/addOrRemoveBracesToArrowFunction.ts
  tests/cases/fourslash/refactorAddOrRemoveBracesToArrowFunction36.ts
Labels: For Backlog Bug

#54056 fix: class field is not accessible via super
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/utilitiesPublic.ts
  tests/baselines/reference/checkSuperCallBeforeThisAccess.errors.txt
  tests/baselines/reference/classFieldSuperAccessible.js
  tests/baselines/reference/classFieldSuperAccessible.symbols
  tests/baselines/reference/classFieldSuperAccessible.types
  tests/baselines/reference/classFieldSuperNotAccessible.errors.txt
  tests/baselines/reference/classFieldSuperNotAccessible.js
  tests/baselines/reference/classFieldSuperNotAccessible.symbols
  tests/baselines/reference/classFieldSuperNotAccessible.types
  tests/cases/compiler/classFieldSuperAccessible.ts
  tests/cases/compiler/classFieldSuperNotAccessible.ts
Labels: Breaking Change, For Backlog Bug

#55836 Make unchangedTextChangeRange const
  src/compiler/utilitiesPublic.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#54121 Include source node inferences in string literal completions
  src/compiler/checker.ts
  src/compiler/types.ts
  src/compiler/utilitiesPublic.ts
  src/services/stringCompletions.ts
  tests/cases/fourslash/stringLiteralCompletionsForGenericConditionalTypesUsingTemplateLiteralTypes.ts
  tests/cases/fourslash/stringLiteralCompletionsInPositionTypedUsingRest.ts
Labels: Author: Team, For Milestone Bug

#55865 Fix issue with trailing directory separator not present if symlink wasnt detected by program
  src/compiler/utilities.ts
  src/server/project.ts
  src/testRunner/unittests/helpers/virtualFileSystemWithWatch.ts
  src/testRunner/unittests/tsserver/moduleResolution.ts
  tests/baselines/reference/tsserver/moduleResolution/using-referenced-project-built.js
  tests/baselines/reference/tsserver/moduleResolution/using-referenced-project.js
Labels: Author: Team, For Milestone Bug

#55725 Support resolution-mode overrides in type-only constructs in all moduleResolution modes
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/moduleNameResolver.ts
  src/compiler/program.ts
  tests/baselines/reference/nodeModulesTripleSlashReferenceModeOverrideOldResolutionError.errors.txt
  tests/baselines/reference/nodeModulesTripleSlashReferenceModeOverrideOldResolutionError.js
  tests/baselines/reference/nodeModulesTripleSlashReferenceModeOverrideOldResolutionError.symbols
  tests/baselines/reference/nodeModulesTripleSlashReferenceModeOverrideOldResolutionError.types
  tests/baselines/reference/resolutionModeImportType1(moduleresolution=bundler).symbols
  tests/baselines/reference/resolutionModeImportType1(moduleresolution=bundler).types
  tests/baselines/reference/resolutionModeImportType1(moduleresolution=classic).errors.txt
  tests/baselines/reference/resolutionModeImportType1(moduleresolution=classic).symbols
  tests/baselines/reference/resolutionModeImportType1(moduleresolution=classic).types
  tests/baselines/reference/resolutionModeImportType1(moduleresolution=node10).errors.txt
  tests/baselines/reference/resolutionModeImportType1(moduleresolution=node10).symbols
  tests/baselines/reference/resolutionModeImportType1(moduleresolution=node10).types
  tests/baselines/reference/resolutionModeTripleSlash1.errors.txt
  tests/baselines/reference/resolutionModeTripleSlash2.errors.txt
  tests/baselines/reference/resolutionModeTripleSlash2.js
  tests/baselines/reference/resolutionModeTripleSlash3.errors.txt
  tests/baselines/reference/resolutionModeTripleSlash4.errors.txt
  tests/baselines/reference/resolutionModeTripleSlash5.errors.txt
  tests/baselines/reference/resolutionModeTypeOnlyImport1(moduleresolution=bundler).js
  tests/baselines/reference/resolutionModeTypeOnlyImport1(moduleresolution=bundler).symbols
  tests/baselines/reference/resolutionModeTypeOnlyImport1(moduleresolution=bundler).types
  tests/baselines/reference/resolutionModeTypeOnlyImport1(moduleresolution=classic).errors.txt
  tests/baselines/reference/resolutionModeTypeOnlyImport1(moduleresolution=classic).js
  tests/baselines/reference/resolutionModeTypeOnlyImport1(moduleresolution=classic).symbols
  tests/baselines/reference/resolutionModeTypeOnlyImport1(moduleresolution=classic).types
  tests/baselines/reference/resolutionModeTypeOnlyImport1(moduleresolution=node10).errors.txt
  tests/baselines/reference/resolutionModeTypeOnlyImport1(moduleresolution=node10).js
  tests/baselines/reference/resolutionModeTypeOnlyImport1(moduleresolution=node10).symbols
  tests/baselines/reference/resolutionModeTypeOnlyImport1(moduleresolution=node10).types
  tests/cases/conformance/moduleResolution/resolutionModeImportType1.ts
  tests/cases/conformance/moduleResolution/resolutionModeTripleSlash1.ts
  tests/cases/conformance/moduleResolution/resolutionModeTripleSlash2.ts
  tests/cases/conformance/moduleResolution/resolutionModeTripleSlash3.ts
  tests/cases/conformance/moduleResolution/resolutionModeTripleSlash4.ts
  tests/cases/conformance/moduleResolution/resolutionModeTripleSlash5.ts
  tests/cases/conformance/moduleResolution/resolutionModeTypeOnlyImport1.ts
  tests/cases/conformance/node/nodeModulesTripleSlashReferenceModeOverrideOldResolutionError.ts
Labels: Author: Team, For Uncommitted Bug

#55881 change transpile to compile
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/nodeModulesImportAssertions(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesImportAttributes(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesImportAttributesModeDeclarationEmit1(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesImportAttributesModeDeclarationEmitErrors(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesImportModeDeclarationEmit1(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesImportModeDeclarationEmitErrors1(module=nodenext).errors.txt
Labels: For Uncommitted Bug

#55851 Error on excessive relation complexity
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/relationComplexityError.errors.txt
  tests/baselines/reference/relationComplexityError.symbols
  tests/baselines/reference/relationComplexityError.types
  tests/cases/compiler/relationComplexityError.ts
Labels: Author: Team, For Milestone Bug

#55780 fix(55775) - TS parameter inlay hints disconsiders used parameters when set to literals
  tests/baselines/reference/inlayHintsParameterNames.baseline
  tests/cases/fourslash/inlayHintsParameterNames.ts
Labels: For Milestone Bug

#55893 Fix new-release-branch workflow
  .github/workflows/new-release-branch.yaml
  .github/workflows/set-version.yaml
Labels: Author: Team, For Uncommitted Bug

#55892 Error on class fields accesses through `super` in JS files
  src/compiler/utilitiesPublic.ts
  tests/baselines/reference/classFieldSuperAccessible.js
  tests/baselines/reference/classFieldSuperAccessible.symbols
  tests/baselines/reference/classFieldSuperAccessible.types
  tests/baselines/reference/classFieldSuperAccessibleJs1.errors.txt
  tests/baselines/reference/classFieldSuperAccessibleJs1.symbols
  tests/baselines/reference/classFieldSuperAccessibleJs1.types
  tests/baselines/reference/classFieldSuperAccessibleJs2.symbols
  tests/baselines/reference/classFieldSuperAccessibleJs2.types
  tests/baselines/reference/classFieldSuperNotAccessibleJs.errors.txt
  tests/baselines/reference/classFieldSuperNotAccessibleJs.symbols
  tests/baselines/reference/classFieldSuperNotAccessibleJs.types
  tests/cases/compiler/classFieldSuperAccessible.ts
  tests/cases/compiler/classFieldSuperAccessibleJs1.ts
  tests/cases/compiler/classFieldSuperAccessibleJs2.ts
  tests/cases/compiler/classFieldSuperNotAccessibleJs.ts
Labels: For Backlog Bug

#55910 Fixed na issue with evaluator using binding element initializers as const values
  src/compiler/checker.ts
  tests/baselines/reference/enumErrorOnConstantBindingWithInitializer.errors.txt
  tests/baselines/reference/enumErrorOnConstantBindingWithInitializer.js
  tests/baselines/reference/enumErrorOnConstantBindingWithInitializer.symbols
  tests/baselines/reference/enumErrorOnConstantBindingWithInitializer.types
  tests/baselines/reference/templateExpressionNoInlininingOfConstantBindingWithInitializer.js
  tests/baselines/reference/templateExpressionNoInlininingOfConstantBindingWithInitializer.symbols
  tests/baselines/reference/templateExpressionNoInlininingOfConstantBindingWithInitializer.types
  tests/cases/compiler/templateExpressionNoInlininingOfConstantBindingWithInitializer.ts
  tests/cases/conformance/enums/enumErrorOnConstantBindingWithInitializer.ts
Labels: For Uncommitted Bug

#55918 Show interactive inlay hints in parameter types
  src/services/inlayHints.ts
  tests/baselines/reference/inlayHintsInteractiveFunctionParameterTypes1.baseline
  tests/baselines/reference/inlayHintsInteractiveFunctionParameterTypes3.baseline
  tests/cases/fourslash/inlayHintsInteractiveFunctionParameterTypes1.ts
Labels: For Milestone Bug

#55913 Update dprint-typescript to 0.88.1, reformat
  .dprint.jsonc
  src/testRunner/unittests/services/colorization.ts
Labels: Author: Team, For Uncommitted Bug

#55921 Rename `isClassFieldAndNotAutoAccessor` to `isClassInstanceProperty`
  src/compiler/checker.ts
  src/compiler/utilitiesPublic.ts
Labels: For Uncommitted Bug

#55867 Remove `CheckMode.IsForStringLiteralArgumentCompletions`
  src/compiler/checker.ts
  tests/cases/fourslash/stringCompletionsFromGenericConditionalTypesUsingTemplateLiteralTypes.ts
Labels: For Uncommitted Bug
