Repository microsoft/TypeScript, pull requests merged in 2023-05, with the labels that each got.

#52754 Ensure call return() for an abrupt completion at for await of loop
  src/compiler/transformers/es2018.ts
  src/testRunner/unittests/evaluation/forAwaitOf.ts
  tests/baselines/reference/emitter.forAwait(target=es2015).js
  tests/baselines/reference/emitter.forAwait(target=es2017).js
  tests/baselines/reference/emitter.forAwait(target=es5).js
  tests/baselines/reference/forAwaitPerIterationBindingDownlevel.js
  tests/baselines/reference/nodeModulesAllowJsTopLevelAwait(module=node16).js
  tests/baselines/reference/nodeModulesAllowJsTopLevelAwait(module=nodenext).js
  tests/baselines/reference/nodeModulesTopLevelAwait(module=node16).js
  tests/baselines/reference/nodeModulesTopLevelAwait(module=nodenext).js
  tests/baselines/reference/operationsAvailableOnPromisedType.js
  tests/baselines/reference/topLevelAwait.1(module=es2022,target=es2015).js
  tests/baselines/reference/topLevelAwait.1(module=es2022,target=es2017).js
  tests/baselines/reference/topLevelAwait.1(module=esnext,target=es2015).js
  tests/baselines/reference/topLevelAwait.1(module=esnext,target=es2017).js
  tests/baselines/reference/topLevelAwait.1(module=system,target=es2015).js
  tests/baselines/reference/topLevelAwait.1(module=system,target=es2017).js
Labels: For Milestone Bug

#54072 Add fallback when both co- and contra-variant inference candidates exist
  src/compiler/checker.ts
  tests/baselines/reference/coAndContraVariantInferences5.symbols
  tests/baselines/reference/coAndContraVariantInferences5.types
  tests/cases/compiler/coAndContraVariantInferences5.ts
Labels: Author: Team, For Milestone Bug

#54033 Type with diverging read/write normalizations still identical to itself
  src/compiler/checker.ts
  tests/baselines/reference/identityAndDivergentNormalizedTypes.symbols
  tests/baselines/reference/identityAndDivergentNormalizedTypes.types
  tests/cases/compiler/identityAndDivergentNormalizedTypes.ts
Labels: Author: Team, For Milestone Bug

#53672 Constraints for generic tuple types
  src/compiler/checker.ts
  tests/baselines/reference/variadicTuples1.errors.txt
  tests/baselines/reference/variadicTuples1.js
  tests/baselines/reference/variadicTuples1.symbols
  tests/baselines/reference/variadicTuples1.types
  tests/baselines/reference/variadicTuples2.errors.txt
  tests/cases/conformance/types/tuple/variadicTuples1.ts
Labels: Author: Team, For Milestone Bug

#54062 JS declaration emit uses `this` for method returns
  src/compiler/checker.ts
  tests/baselines/reference/jsFileMethodOverloads2.js
  tests/baselines/reference/thisPropertyAssignmentInherited.js
Labels: Author: Team, For Milestone Bug

#53885 Fix/issue 53286
  src/compiler/checker.ts
  tests/baselines/reference/assignParameterPropertyToPropertyDeclarationES2022.errors.txt
  tests/baselines/reference/assignParameterPropertyToPropertyDeclarationES2022.js
  tests/baselines/reference/assignParameterPropertyToPropertyDeclarationES2022.symbols
  tests/baselines/reference/assignParameterPropertyToPropertyDeclarationES2022.types
  tests/cases/conformance/classes/propertyMemberDeclarations/assignParameterPropertyToPropertyDeclarationES2022.ts
Labels: For Backlog Bug

#53897 Add Node 20 to CI, remove Node 19
  .github/workflows/ci.yml
Labels: Author: Team, For Uncommitted Bug

#54107 Fix crash in getAwaitedType
  src/compiler/checker.ts
  tests/baselines/reference/crashInYieldStarInAsyncFunction.errors.txt
  tests/baselines/reference/crashInYieldStarInAsyncFunction.js
  tests/baselines/reference/crashInYieldStarInAsyncFunction.symbols
  tests/baselines/reference/crashInYieldStarInAsyncFunction.types
  tests/cases/compiler/crashInYieldStarInAsyncFunction.ts
Labels: Author: Team, For Milestone Bug

#54114 runtests-watch: Don't try to listen for SIGKILL
  Herebyfile.mjs
Labels: For Uncommitted Bug

#54118 Error on template tag inside callback/overload/typedef tag
  src/compiler/diagnosticMessages.json
  src/compiler/parser.ts
  tests/baselines/reference/templateInsideCallback.errors.txt
  tests/baselines/reference/templateInsideCallback.js
  tests/baselines/reference/templateInsideCallback.symbols
  tests/baselines/reference/templateInsideCallback.types
  tests/cases/conformance/jsdoc/templateInsideCallback.ts
Labels: Author: Team, For Milestone Bug

#52710 Ensure that JSDoc parsing happens within a ParsingContext
  src/compiler/parser.ts
  tests/baselines/reference/jsDocDontBreakWithNamespaces.baseline
  tests/baselines/reference/jsdocFunctionTypeFalsePositive.errors.txt
  tests/baselines/reference/jsdocFunctionTypeFalsePositive.types
  tests/cases/fourslash/jsdocWithBarInTypeLiteral.ts
Labels: Author: Team, For Milestone Bug

#53995 Ignore self tail calls when collecting the return type of a function
  src/compiler/checker.ts
  tests/baselines/reference/callSignatureWithoutReturnTypeAnnotationInference.types
  tests/baselines/reference/functionImplementations.errors.txt
  tests/baselines/reference/functionImplementations.types
  tests/baselines/reference/implicitAnyFromCircularInference.errors.txt
  tests/baselines/reference/implicitAnyFromCircularInference.types
  tests/baselines/reference/recursiveGenericSignatureInstantiation.types
  tests/baselines/reference/simpleRecursionWithBaseCase.errors.txt
  tests/baselines/reference/simpleRecursionWithBaseCase.js
  tests/baselines/reference/simpleRecursionWithBaseCase.symbols
  tests/baselines/reference/simpleRecursionWithBaseCase.types
  tests/baselines/reference/witness.errors.txt
  tests/baselines/reference/witness.types
  tests/cases/compiler/simpleRecursionWithBaseCase.ts
Labels: Author: Team, For Uncommitted Bug

#54141 Add CI job that detects unused baselines
  .github/workflows/ci.yml
  tests/baselines/reference/NonNullableInNonStrictMode.js
  tests/baselines/reference/NonNullableInNonStrictMode.symbols
  tests/baselines/reference/NonNullableInNonStrictMode.types
  tests/baselines/reference/contextualSignatureInArrayElementPrefersArrayUnionMemberLibEs2015.errors.txt
  tests/baselines/reference/contextualSignatureInArrayElementPrefersArrayUnionMemberLibEs5.errors.txt
  tests/baselines/reference/esDecorators-classDeclaration-nonStatic-methods(target=es2015).js
  tests/baselines/reference/esDecorators-classDeclaration-nonStatic-methods(target=es2022).js
  tests/baselines/reference/esDecorators-classDeclaration-nonStatic-methods(target=es5).js
  tests/baselines/reference/esDecorators-classDeclaration-nonStatic-methods(target=esnext).js
  tests/baselines/reference/esDecorators-classDeclaration-setFunctionName1.js
  tests/baselines/reference/findLast.js
  tests/baselines/reference/findLast.symbols
  tests/baselines/reference/findLast.types
  tests/baselines/reference/moduleCrashInJSFile.errors.txt
  tests/baselines/reference/moduleCrashInJSFile.js
  tests/baselines/reference/moduleCrashInJSFile.symbols
  tests/baselines/reference/moduleCrashInJSFile.types
  tests/baselines/reference/showConfig/Shows tsconfig for single option/allowImportingTsExtensions/tsconfig.json
  tests/baselines/reference/verbatimModuleSyntaxNoElision.errors.txt
  tests/baselines/reference/verbatimModuleSyntaxNoElision.js
  tests/baselines/reference/verbatimModuleSyntaxNoElision.symbols
  tests/baselines/reference/verbatimModuleSyntaxNoElision.types
Labels: Author: Team, For Uncommitted Bug

#54138 Handle undefined `location.parent` when getting completionEntryDetails
  src/services/symbolDisplay.ts
  tests/baselines/reference/completionNoParentLocation.baseline
  tests/cases/fourslash/completionNoParentLocation.ts
Labels: For Milestone Bug

#53444 Fixed issue with spreading a generic call expression into generic JSX and gather intra expression inference sites from spread expressions
  src/compiler/checker.ts
  tests/baselines/reference/intraExpressionInferences.errors.txt
  tests/baselines/reference/intraExpressionInferences.js
  tests/baselines/reference/intraExpressionInferences.symbols
  tests/baselines/reference/intraExpressionInferences.types
  tests/baselines/reference/jsxGenericComponentWithSpreadingResultOfGenericFunction.symbols
  tests/baselines/reference/jsxGenericComponentWithSpreadingResultOfGenericFunction.types
  tests/cases/compiler/jsxGenericComponentWithSpreadingResultOfGenericFunction.tsx
  tests/cases/conformance/types/typeRelationships/typeInference/intraExpressionInferences.ts
Labels: For Milestone Bug

#53964 fix(53424): in code documentation is not working upon import if function expression reuse function type
  src/services/symbolDisplay.ts
  tests/baselines/reference/quickInfoJsDocAlias.baseline
  tests/cases/fourslash/quickInfoJsDocAlias.ts
Labels: For Backlog Bug

#54024 Cover more cases for node module auto-import
  src/compiler/moduleSpecifiers.ts
  tests/cases/fourslash/autoImportPackageRootPath.ts
  tests/cases/fourslash/autoImportPackageRootPathExtension.ts
  tests/cases/fourslash/autoImportPackageRootPathTypeModule.ts
Labels: For Uncommitted Bug

#54185 fix jsdoc errors in .ts in tsserver
  src/compiler/checker.ts
  src/testRunner/tests.ts
  src/testRunner/unittests/services/goToDefinition.ts
  tests/baselines/reference/classMemberInitializerScoping.symbols
  tests/baselines/reference/classMemberInitializerScoping2(target=es2017,usedefineforclassfields=false).symbols
  tests/baselines/reference/classMemberInitializerScoping2(target=es2017,usedefineforclassfields=true).symbols
  tests/baselines/reference/classMemberInitializerScoping2(target=esnext,usedefineforclassfields=false).symbols
  tests/baselines/reference/classMemberInitializerWithLamdaScoping.symbols
  tests/baselines/reference/classMemberInitializerWithLamdaScoping2.symbols
  tests/baselines/reference/classMemberInitializerWithLamdaScoping3.symbols
  tests/baselines/reference/constructorParameterShadowsOuterScopes.symbols
  tests/baselines/reference/constructorParametersThatShadowExternalNamesInVariableDeclarations.symbols
  tests/baselines/reference/tsserver/goToDefinition/does-not-issue-errors-on-jsdoc-in-TS.js
  tests/baselines/reference/tsserver/goToDefinition/does-not-issue-errors-on-jsdoc-in-TS2.js
Labels: Author: Team, For Milestone Bug, For Backlog Bug

#54104 JSX namespace names should not be considered expressions
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/parser.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/compiler/utilitiesPublic.ts
  src/services/signatureHelp.ts
  src/services/utilities.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/checkJsxNamespaceNamesQuestionableForms.errors.txt
  tests/baselines/reference/checkJsxNamespaceNamesQuestionableForms.js
  tests/baselines/reference/checkJsxNamespaceNamesQuestionableForms.symbols
  tests/baselines/reference/checkJsxNamespaceNamesQuestionableForms.types
  tests/baselines/reference/jsxInvalidEsprimaTestSuite.errors.txt
  tests/baselines/reference/jsxInvalidEsprimaTestSuite.js
  tests/baselines/reference/jsxInvalidEsprimaTestSuite.symbols
  tests/baselines/reference/jsxInvalidEsprimaTestSuite.types
  tests/baselines/reference/jsxNamespacedNameNotComparedToNonMatchingIndexSignature.js
  tests/baselines/reference/jsxNamespacedNameNotComparedToNonMatchingIndexSignature.symbols
  tests/baselines/reference/jsxNamespacedNameNotComparedToNonMatchingIndexSignature.types
  tests/cases/compiler/jsxNamespacedNameNotComparedToNonMatchingIndexSignature.tsx
Labels: Author: Team, For Uncommitted Bug

#53940 Add extra tests for contextual typing of unannotated parameters with default initializers
  tests/baselines/reference/typeSatisfaction_contextualTyping3.symbols
  tests/baselines/reference/typeSatisfaction_contextualTyping3.types
  tests/cases/conformance/expressions/typeSatisfaction/typeSatisfaction_contextualTyping3.ts
Labels: For Uncommitted Bug

#54115 Handle module node found error reporting in incremental and watch scneario
  src/compiler/builder.ts
  src/compiler/checker.ts
  src/compiler/core.ts
  src/compiler/moduleNameResolver.ts
  src/compiler/program.ts
  src/compiler/resolutionCache.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/testRunner/tests.ts
  src/testRunner/unittests/helpers/node10Result.ts
  src/testRunner/unittests/tsc/moduleResolution.ts
  src/testRunner/unittests/tscWatch/moduleResolution.ts
  src/testRunner/unittests/tsserver/moduleResolution.ts
  tests/baselines/reference/tsc/moduleResolution/node10Result.js
  tests/baselines/reference/tscWatch/moduleResolution/node10Result.js
  tests/baselines/reference/tsserver/moduleResolution/node10Result.js
Labels: Author: Team, For Uncommitted Bug

#54199 Fix for formatter crash for Move to file
  src/services/textChanges.ts
  tests/cases/fourslash/moveToFile_multipleStatements2.ts
Labels: Author: Team, For Milestone Bug

#52809 Skip resolving files directly inside node_modules
  src/compiler/diagnosticMessages.json
  src/compiler/moduleNameResolver.ts
  src/testRunner/unittests/tsserver/configuredProjects.ts
  tests/baselines/reference/cachedModuleResolution1.js
  tests/baselines/reference/cachedModuleResolution5.js
  tests/baselines/reference/nodeColonModuleResolution.js
  tests/baselines/reference/nodeColonModuleResolution.symbols
  tests/baselines/reference/nodeColonModuleResolution.trace.json
  tests/baselines/reference/nodeColonModuleResolution.types
  tests/baselines/reference/nodeColonModuleResolution2.js
  tests/baselines/reference/nodeColonModuleResolution2.symbols
  tests/baselines/reference/nodeColonModuleResolution2.trace.json
  tests/baselines/reference/nodeColonModuleResolution2.types
  tests/baselines/reference/nodeNextModuleResolution1.errors.txt
  tests/baselines/reference/nodeNextModuleResolution1.js
  tests/baselines/reference/nodeNextModuleResolution1.symbols
  tests/baselines/reference/nodeNextModuleResolution1.trace.json
  tests/baselines/reference/nodeNextModuleResolution1.types
  tests/baselines/reference/nodeNextModuleResolution2.js
  tests/baselines/reference/nodeNextModuleResolution2.symbols
  tests/baselines/reference/nodeNextModuleResolution2.trace.json
  tests/baselines/reference/nodeNextModuleResolution2.types
  tests/baselines/reference/nodeResolution2.js
  tests/baselines/reference/pathMappingBasedModuleResolution5_node.js
  tests/baselines/reference/pathMappingBasedModuleResolution_rootImport_aliasWithRoot_differentRootTypes.trace.json
  tests/baselines/reference/requireOfJsonFileNonRelative.js
  tests/baselines/reference/requireOfJsonFileNonRelative.symbols
  tests/baselines/reference/requireOfJsonFileNonRelative.types
  tests/baselines/reference/requireOfJsonFileNonRelativeWithoutExtensionResolvesToTs.js
  tests/baselines/reference/requireOfJsonFileNonRelativeWithoutExtensionResolvesToTs.symbols
  tests/baselines/reference/requireOfJsonFileNonRelativeWithoutExtensionResolvesToTs.types
  tests/cases/compiler/cachedModuleResolution1.ts
  tests/cases/compiler/cachedModuleResolution5.ts
  tests/cases/compiler/nodeColonModuleResolution.ts
  tests/cases/compiler/nodeColonModuleResolution2.ts
  tests/cases/compiler/nodeNextModuleResolution1.ts
  tests/cases/compiler/nodeNextModuleResolution2.ts
  tests/cases/compiler/nodeResolution2.ts
  tests/cases/compiler/pathMappingBasedModuleResolution5_node.ts
  tests/cases/compiler/requireOfJsonFileNonRelative.ts
  tests/cases/compiler/requireOfJsonFileNonRelativeWithoutExtensionResolvesToTs.ts
Labels: Author: Team, For Milestone Bug

#54219 move some tests that depend on tsserver into tsserver/
  src/testRunner/tests.ts
  src/testRunner/unittests/tsserver/findAllReferences.ts
  src/testRunner/unittests/tsserver/goToDefinition.ts
Labels: Author: Team, Housekeeping, For Uncommitted Bug

#54153 Update Bug_report.md
  .github/ISSUE_TEMPLATE/Bug_report.md
Labels: Author: Team, For Uncommitted Bug

#53966 Revert octokit pinning now that the package is fixed
  package-lock.json
  package.json
Labels: Author: Team, Housekeeping, For Uncommitted Bug

#54218 `isolatedModules` does not imply every file is a module
  src/compiler/utilities.ts
  src/testRunner/unittests/services/transpile.ts
  src/testRunner/unittests/transform.ts
  tests/baselines/reference/importHelpersInIsolatedModules.js
  tests/baselines/reference/isolatedModulesPlainFile-AMD.js
  tests/baselines/reference/isolatedModulesPlainFile-System.js
  tests/baselines/reference/isolatedModulesPlainFile-UMD.js
  tests/baselines/reference/transformApi/transformsCorrectly.transformAddImportStar.js
  tests/baselines/reference/transpile/Generates module output.errors.txt
  tests/baselines/reference/transpile/Generates module output.js
  tests/baselines/reference/transpile/Generates module output.oldTranspile.errors.txt
  tests/baselines/reference/transpile/Generates module output.oldTranspile.js
  tests/baselines/reference/transpile/Sets module name.errors.txt
  tests/baselines/reference/transpile/Sets module name.js
  tests/baselines/reference/transpile/Sets module name.oldTranspile.errors.txt
  tests/baselines/reference/transpile/Sets module name.oldTranspile.js
Labels: Author: Team, For Milestone Bug

#54224 Cache expression type when checking assertion
  src/compiler/checker.ts
  src/compiler/types.ts
Labels: Author: Team, For Uncommitted Bug

#53729 Improved go to type definition on type references of global container-like types using allowlist
  src/services/goToDefinition.ts
  tests/baselines/reference/goToTypeDefinition_Pick.baseline.jsonc
  tests/baselines/reference/goToTypeDefinition_arrayType.baseline.jsonc
  tests/baselines/reference/goToTypeDefinition_promiseType.baseline.jsonc
  tests/baselines/reference/goToTypeDefinition_typeReference.baseline.jsonc
  tests/cases/fourslash/goToTypeDefinition_Pick.ts
  tests/cases/fourslash/goToTypeDefinition_arrayType.ts
  tests/cases/fourslash/goToTypeDefinition_promiseType.ts
  tests/cases/fourslash/goToTypeDefinition_typeReference.ts
Labels: For Milestone Bug

#53489 Add fallback logic for generating signatures for unions of array members
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/completionEntryForUnionMethod.baseline
  tests/baselines/reference/unionOfArraysFilterCall.js
  tests/baselines/reference/unionOfArraysFilterCall.symbols
  tests/baselines/reference/unionOfArraysFilterCall.types
  tests/baselines/reference/unionOfClassCalls.errors.txt
  tests/baselines/reference/unionOfClassCalls.types
  tests/cases/compiler/unionOfArraysFilterCall.ts
Labels: Author: Team, For Uncommitted Bug

#53810 Fix JSX inference with excess properties
  src/compiler/checker.ts
  tests/baselines/reference/typeInferenceWithExcessPropertiesJsx.symbols
  tests/baselines/reference/typeInferenceWithExcessPropertiesJsx.types
  tests/cases/compiler/typeInferenceWithExcessPropertiesJsx.tsx
Labels: For Backlog Bug

#54269 Reverse order of decorator-injected initializers
  src/compiler/factory/emitHelpers.ts
  src/testRunner/unittests/evaluation/esDecorators.ts
  tests/baselines/reference/esDecorators-classDeclaration-commonjs-classNamespaceMerge.js
  tests/baselines/reference/esDecorators-classDeclaration-commonjs.js
  tests/baselines/reference/esDecorators-classDeclaration-sourceMap(target=es2015).js
  tests/baselines/reference/esDecorators-classDeclaration-sourceMap(target=es2015).js.map
  tests/baselines/reference/esDecorators-classDeclaration-sourceMap(target=es2015).sourcemap.txt
  tests/baselines/reference/esDecorators-classDeclaration-sourceMap(target=es2022).js
  tests/baselines/reference/esDecorators-classDeclaration-sourceMap(target=es2022).js.map
  tests/baselines/reference/esDecorators-classDeclaration-sourceMap(target=es2022).sourcemap.txt
  tests/baselines/reference/tscWatch/programUpdates/updates-diagnostics-and-emit-for-decorators.js
Labels: Author: Team, For Milestone Bug

#52525 Improve class member snippet completions and keyword completions interaction
  src/compiler/factory/nodeFactory.ts
  src/compiler/types.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/server/protocol.ts
  src/server/session.ts
  src/services/codefixes/helpers.ts
  src/services/completions.ts
  src/services/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/completionsClassMembers2.baseline
  tests/baselines/reference/completionsClassMembers4.baseline
  tests/baselines/reference/completionsClassMembers5.baseline
  tests/baselines/reference/completionsOverridingMethod15.baseline
  tests/baselines/reference/completionsOverridingMethod16.baseline
  tests/baselines/reference/tsserver/exportMapCache/invalidates-the-cache-when-a-file-is-opened-with-different-contents.js
  tests/cases/fourslash/completionsOverridingMethod0.ts
  tests/cases/fourslash/completionsOverridingMethod1.ts
  tests/cases/fourslash/completionsOverridingMethod10.ts
  tests/cases/fourslash/completionsOverridingMethod11.ts
  tests/cases/fourslash/completionsOverridingMethod12.ts
  tests/cases/fourslash/completionsOverridingMethod13.ts
  tests/cases/fourslash/completionsOverridingMethod14.ts
  tests/cases/fourslash/completionsOverridingMethod17.ts
  tests/cases/fourslash/completionsOverridingMethod2.ts
  tests/cases/fourslash/completionsOverridingMethod3.ts
  tests/cases/fourslash/completionsOverridingMethod4.ts
  tests/cases/fourslash/completionsOverridingMethod5.ts
  tests/cases/fourslash/completionsOverridingMethod6.ts
  tests/cases/fourslash/completionsOverridingMethod7.ts
  tests/cases/fourslash/completionsOverridingMethod8.ts
  tests/cases/fourslash/completionsOverridingMethod9.ts
  tests/cases/fourslash/completionsOverridingMethodCrash1.ts
  tests/cases/fourslash/completionsOverridingMethodDefaultExported.ts
  tests/cases/fourslash/completionsOverridingProperties1.ts
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/server/completionsOverridingMethodCrash2.ts
Labels: Author: Team, For Milestone Bug

#54317 Resolve re-exports when looking for tslib helpers
  src/compiler/checker.ts
  tests/baselines/reference/tslibReExportHelpers.js
  tests/baselines/reference/tslibReExportHelpers.symbols
  tests/baselines/reference/tslibReExportHelpers.types
  tests/cases/compiler/tslibReExportHelpers.ts
Labels: Author: Team, For Uncommitted Bug

#54169 Fix creation of composite union type predicates
  src/compiler/checker.ts
  tests/baselines/reference/typePredicatesInUnion3.errors.txt
  tests/baselines/reference/typePredicatesInUnion3.symbols
  tests/baselines/reference/typePredicatesInUnion3.types
  tests/cases/compiler/typePredicatesInUnion3.ts
Labels: Author: Team, For Milestone Bug

#54142 Ensure GHA jobs fail fast in scripts
  .github/workflows/accept-baselines-fix-lints.yaml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/ensure-related-repos-run-crons.yml
  .github/workflows/error-deltas-watchdog.yaml
  .github/workflows/new-release-branch.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release-branch-artifact.yaml
  .github/workflows/rich-navigation.yml
  .github/workflows/scorecard.yml
  .github/workflows/set-version.yaml
  .github/workflows/sync-branch.yaml
  .github/workflows/sync-wiki.yml
  .github/workflows/twoslash-repros.yaml
  .github/workflows/update-lkg.yml
  .github/workflows/update-package-lock.yaml
Labels: Author: Team, For Uncommitted Bug

#54112 Fix `isGenericReducibleType` to allow HKT technique to function again
  src/compiler/checker.ts
  tests/baselines/reference/inferenceAndHKTs.symbols
  tests/baselines/reference/inferenceAndHKTs.types
  tests/cases/compiler/inferenceAndHKTs.ts
Labels: Author: Team, For Milestone Bug

#54208 Properly handle `typeof this.xxx` in `isTypeParameterPossiblyReferenced`
  src/compiler/checker.ts
  tests/baselines/reference/typeofThisInMethodSignature.symbols
  tests/baselines/reference/typeofThisInMethodSignature.types
  tests/cases/compiler/typeofThisInMethodSignature.ts
Labels: Author: Team, For Milestone Bug

#54321 Fix a logic-changing typo in getRecursionIdentity
  src/compiler/checker.ts
Labels: For Uncommitted Bug

#54125 Add extra Date.UTC signature to reflect ES2017 changes
  src/compiler/commandLineParser.ts
  src/lib/es2017.d.ts
  src/lib/es2017.date.d.ts
  src/lib/libs.json
  tests/baselines/reference/config/commandLineParsing/parseCommandLine/Parse --lib option with extra comma.js
  tests/baselines/reference/config/commandLineParsing/parseCommandLine/Parse --lib option with trailing white-space.js
  tests/baselines/reference/config/commandLineParsing/parseCommandLine/Parse invalid option of library flags.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert empty string option of libs array to compiler-options with json api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert empty string option of libs array to compiler-options with jsonSourceFile api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert empty string option of libs to compiler-options with json api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert empty string option of libs to compiler-options with jsonSourceFile api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert incorrect option of libs to compiler-options with json api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert incorrect option of libs to compiler-options with jsonSourceFile api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert trailing-whitespace string option of libs to compiler-options with json api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert trailing-whitespace string option of libs to compiler-options with jsonSourceFile api.js
  tests/baselines/reference/es2017DateAPIs.js
  tests/baselines/reference/es2017DateAPIs.symbols
  tests/baselines/reference/es2017DateAPIs.types
  tests/baselines/reference/es5DateAPIs.errors.txt
  tests/baselines/reference/es5DateAPIs.js
  tests/baselines/reference/es5DateAPIs.symbols
  tests/baselines/reference/es5DateAPIs.types
  tests/baselines/reference/tsc/runWithoutArgs/does-not-add-color-when-NO_COLOR-is-set.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped-when-host-can't-provide-terminal-width.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
  tests/baselines/reference/tsserver/telemetry/does-not-expose-paths.js
  tests/baselines/reference/typesVersions.ambientModules.trace.json
  tests/baselines/reference/typesVersions.emptyTypes.trace.json
  tests/baselines/reference/typesVersions.justIndex.trace.json
  tests/baselines/reference/typesVersions.multiFile.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.ambient.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFile.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFileBackReferenceToSelf.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFileBackReferenceToUnmapped.trace.json
  tests/cases/conformance/es2017/es2017DateAPIs.ts
  tests/cases/conformance/es5/es5DateAPIs.ts
Labels: For Backlog Bug

#54198 Allow to define valid static fields with names conflicting with builtin properties
  src/compiler/checker.ts
  tests/baselines/reference/staticPropertyNameConflicts(usedefineforclassfields=false).errors.txt
  tests/baselines/reference/staticPropertyNameConflicts(usedefineforclassfields=false).js
  tests/baselines/reference/staticPropertyNameConflicts(usedefineforclassfields=false).symbols
  tests/baselines/reference/staticPropertyNameConflicts(usedefineforclassfields=false).types
  tests/baselines/reference/staticPropertyNameConflicts(usedefineforclassfields=true).errors.txt
  tests/baselines/reference/staticPropertyNameConflicts(usedefineforclassfields=true).js
  tests/baselines/reference/staticPropertyNameConflicts(usedefineforclassfields=true).symbols
  tests/baselines/reference/staticPropertyNameConflicts(usedefineforclassfields=true).types
  tests/cases/conformance/classes/propertyMemberDeclarations/staticPropertyNameConflicts.ts
Labels: For Backlog Bug

#53938 Fixed declaration emit for undefined properties inferred from functions in other array elements
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitInferredUndefinedPropFromFunctionInArray.js
  tests/baselines/reference/declarationEmitInferredUndefinedPropFromFunctionInArray.symbols
  tests/baselines/reference/declarationEmitInferredUndefinedPropFromFunctionInArray.types
  tests/cases/compiler/declarationEmitInferredUndefinedPropFromFunctionInArray.ts
Labels: For Milestone Bug

#54030 Add extra tests for recursive conditional types
  tests/baselines/reference/recursiveConditionalTypes2.symbols
  tests/baselines/reference/recursiveConditionalTypes2.types
  tests/cases/compiler/recursiveConditionalTypes2.ts
Labels: For Milestone Bug

#53522 Avoid infinite recursion when instantiating circular inline mapped generic tuple type
  src/compiler/checker.ts
  tests/baselines/reference/circularInlineMappedGenericTupleTypeNoCrash.symbols
  tests/baselines/reference/circularInlineMappedGenericTupleTypeNoCrash.types
  tests/cases/compiler/circularInlineMappedGenericTupleTypeNoCrash.ts
Labels: For Backlog Bug

#53662 Don't linearly search for fresh param in getConditionalType
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug

#54165 fix(54152): Cannot use const enum to define an interface key in isolatedModules mode
  src/compiler/checker.ts
  tests/baselines/reference/isolatedModulesConstEnum.js
  tests/baselines/reference/isolatedModulesConstEnum.symbols
  tests/baselines/reference/isolatedModulesConstEnum.types
  tests/cases/compiler/isolatedModulesConstEnum.ts
Labels: For Backlog Bug

#54358 Don't use text change's `createNewFile` for existing empty file
  src/harness/client.ts
  src/services/refactors/moveToFile.ts
  src/services/textChanges.ts
  src/services/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/moveToFile_blankExistingFile.ts
  tests/cases/fourslash/moveToFile_differentDirectories2.ts
  tests/cases/fourslash/server/moveToFile_emptyTargetFile.ts
Labels: Author: Team, For Milestone Bug

#54108 fix(54085): Cannot navigate down object hierarchy if an interface is not directly implemented
  src/services/findAllReferences.ts
  tests/baselines/reference/goToImplementationInterface_00.baseline.jsonc
  tests/baselines/reference/goToImplementationInterface_10.baseline.jsonc
  tests/cases/fourslash/goToImplementationInterface_10.ts
Labels: For Uncommitted Bug

#54210 feat(54190): Convert to template string quick fix not available in assignment expressions
  src/services/refactors/convertStringOrTemplateLiteral.ts
  tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_ToTemplateBinaryExpr1.ts
  tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_ToTemplateBinaryExpr2.ts
Labels: For Backlog Bug

#54236 fix flow type of this inside arrow function
  src/compiler/checker.ts
  tests/baselines/reference/thisTypeInFunctions4.js
  tests/baselines/reference/thisTypeInFunctions4.symbols
  tests/baselines/reference/thisTypeInFunctions4.types
  tests/cases/conformance/types/thisType/thisTypeInFunctions4.ts
Labels: For Backlog Bug

#54164 fix(54155): "Move to file" does not carry all function overload and implementation signatures
  src/services/refactors/moveToFile.ts
  tests/cases/fourslash/moveToFile_overloads1.ts
  tests/cases/fourslash/moveToFile_overloads2.ts
  tests/cases/fourslash/moveToFile_overloads3.ts
  tests/cases/fourslash/moveToFile_overloads4.ts
  tests/cases/fourslash/moveToFile_overloads5.ts
  tests/cases/fourslash/moveToNewFile_overloads1.ts
  tests/cases/fourslash/moveToNewFile_overloads2.ts
  tests/cases/fourslash/moveToNewFile_overloads3.ts
  tests/cases/fourslash/moveToNewFile_overloads4.ts
Labels: For Milestone Bug

#54132 fix(52517): JSDoc Comment Template not provided when unrelated JSDoc with tag exists
  src/services/jsDoc.ts
  tests/cases/fourslash/docCommentTemplateWithMultipleJSDoc1.ts
  tests/cases/fourslash/docCommentTemplateWithMultipleJSDoc2.ts
  tests/cases/fourslash/docCommentTemplateWithMultipleJSDoc3.ts
  tests/cases/fourslash/docCommentTemplateWithMultipleJSDocAndParameters.ts
Labels: For Backlog Bug

#54382 Revert GHA fail-fast for OpenSSF workflow
  .github/workflows/scorecard.yml
Labels: Author: Team, For Uncommitted Bug

#54250 Formatter: fix indentation of comments at end of range
  src/services/formatting/formatting.ts
  tests/cases/fourslash/formatSelectionWithTrivia3.ts
  tests/cases/fourslash/formatSelectionWithTrivia4.ts
  tests/cases/fourslash/formatSelectionWithTrivia5.ts
  tests/cases/fourslash/formatSelectionWithTrivia6.ts
  tests/cases/fourslash/formatSelectionWithTrivia7.ts
  tests/cases/fourslash/formatSelectionWithTrivia8.ts
Labels: For Backlog Bug

#54401 Handle already released source files that dont match scriptKind
  src/services/services.ts
  src/testRunner/unittests/tsserver/documentRegistry.ts
  tests/baselines/reference/tsserver/documentRegistry/works-when-reusing-orphan-script-info-with-different-scriptKind.js
Labels: Author: Team, For Uncommitted Bug

#54379 Localize refactor descriptions
  src/services/refactors/addOrRemoveBracesToArrowFunction.ts
  src/services/refactors/convertExport.ts
  src/services/refactors/convertImport.ts
  src/services/refactors/convertOverloadListToSingleSignature.ts
  src/services/refactors/generateGetAccessorAndSetAccessor.ts
  src/services/refactors/inferFunctionReturnType.ts
Labels: For Uncommitted Bug

#54400 fix(54383): Declare method quick fix not returned for #private method
  src/services/codefixes/fixAddMissingMember.ts
  src/services/codefixes/helpers.ts
  tests/cases/fourslash/codeFixAddMissingMember29.ts
Labels: For Uncommitted Bug

#54417 Fix fs.watch callback type for new @types/node
  package-lock.json
  src/compiler/sys.ts
Labels: Author: Team, For Uncommitted Bug

#54315 add baseline for linked editing
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  tests/baselines/reference/linkedEditingJsxTag10.linkedEditing.txt
  tests/baselines/reference/linkedEditingJsxTag11.linkedEditing.txt
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/linkedEditingJsxTag10.ts
  tests/cases/fourslash/linkedEditingJsxTag11.ts
Labels: Author: Team, For Uncommitted Bug

#54452 delete extra comments in tests
  tests/cases/fourslash/linkedEditingJsxTag10.ts
  tests/cases/fourslash/linkedEditingJsxTag11.ts
Labels: Author: Team, For Uncommitted Bug

#54454 Use `replaceAll` instead of an incorrect `RegExp` for tsserver log sanitization.
  src/testRunner/unittests/helpers/tsserver.ts
Labels: Author: Team, For Uncommitted Bug

#54450 Resolve tslib re-exports before checking arity
  src/compiler/checker.ts
  tests/baselines/reference/tslibReExportHelpers2.js
  tests/baselines/reference/tslibReExportHelpers2.symbols
  tests/baselines/reference/tslibReExportHelpers2.types
  tests/cases/compiler/tslibReExportHelpers2.ts
Labels: Author: Team, For Uncommitted Bug

#54432 fix(54366): bug: getCodeFixesAtPosition fails when TS2339 diagnostic paired with large pojo; Debug Failure. False expression: Token end is child end
  src/services/codefixes/helpers.ts
  tests/cases/fourslash/codeFixAddMissingFunctionDeclaration28.ts
  tests/cases/fourslash/codeFixAddMissingMember30.ts
Labels: For Uncommitted Bug

#54474 Fix incorrect 'this' substitution in decorated static 'accessor' fields
  src/compiler/transformers/classFields.ts
  tests/baselines/reference/esDecorators-classDeclaration-classThisReference(target=es2015).js
  tests/baselines/reference/esDecorators-classDeclaration-fields-staticAccessor(target=es2015).js
Labels: Author: Team, For Uncommitted Bug
