Repository microsoft/TypeScript, pull requests merged in 2023-08, with the labels that each got.

#55231 Do not offer completions for default module member symbol
  src/compiler/checker.ts
  tests/cases/fourslash/completionsDefaultKeywordWhenDefaultExportAvailable.ts
Labels: For Backlog Bug

#55230 fix(55227): useUnknownInCatchVariables sets default value differently to other strict commandline options
  src/compiler/commandLineParser.ts
Labels: For Uncommitted Bug

#55018 Correctly error on enum member values referring to identifiers shadowing `Infinity` and `NaN`
  src/compiler/checker.ts
  tests/baselines/reference/enumShadowedInfinityNaN.errors.txt
  tests/baselines/reference/enumShadowedInfinityNaN.js
  tests/baselines/reference/enumShadowedInfinityNaN.symbols
  tests/baselines/reference/enumShadowedInfinityNaN.types
  tests/cases/conformance/enums/enumShadowedInfinityNaN.ts
Labels: For Backlog Bug

#55228 Error on shadowed var declarations without initializers
  src/compiler/checker.ts
  tests/baselines/reference/for-of53.errors.txt
  tests/baselines/reference/shadowedFunctionScopedVariablesByBlockScopedOnes.errors.txt
  tests/baselines/reference/shadowedFunctionScopedVariablesByBlockScopedOnes.symbols
  tests/baselines/reference/shadowedFunctionScopedVariablesByBlockScopedOnes.types
  tests/cases/compiler/shadowedFunctionScopedVariablesByBlockScopedOnes.ts
Labels: For Backlog Bug

#54799 Fix reference marking of values merged with unresolvable type-only imports
  src/compiler/checker.ts
  src/compiler/types.ts
  src/testRunner/unittests/services/transpile.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/importElisionExportNonExportAndDefault.symbols
  tests/baselines/reference/importEquals3.js
  tests/baselines/reference/namespaceImportTypeQuery2.js
  tests/baselines/reference/namespaceImportTypeQuery2.symbols
  tests/baselines/reference/namespaceImportTypeQuery2.types
  tests/baselines/reference/namespaceImportTypeQuery3.errors.txt
  tests/baselines/reference/namespaceImportTypeQuery3.js
  tests/baselines/reference/namespaceImportTypeQuery3.symbols
  tests/baselines/reference/namespaceImportTypeQuery3.types
  tests/baselines/reference/namespaceImportTypeQuery4.errors.txt
  tests/baselines/reference/namespaceImportTypeQuery4.js
  tests/baselines/reference/namespaceImportTypeQuery4.symbols
  tests/baselines/reference/namespaceImportTypeQuery4.types
  tests/baselines/reference/transpile/Preserves exported const merged with type-only import (verbatimModuleSyntax=true).js
  tests/baselines/reference/transpile/Preserves exported const merged with type-only import (verbatimModuleSyntax=true).oldTranspile.js
  tests/baselines/reference/transpile/Preserves exported const merged with type-only import.js
  tests/baselines/reference/transpile/Preserves exported const merged with type-only import.oldTranspile.js
  tests/baselines/reference/typeOnlyMerge3.js
  tests/cases/conformance/externalModules/typeOnly/namespaceImportTypeQuery2.ts
  tests/cases/conformance/externalModules/typeOnly/namespaceImportTypeQuery3.ts
  tests/cases/conformance/externalModules/typeOnly/namespaceImportTypeQuery4.ts
Labels: Author: Team, For Milestone Bug

#55153 Convert issue templates to issue forms
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/lib_change.md
  .github/ISSUE_TEMPLATE/lib_change.yml
  .github/ISSUE_TEMPLATE/module_resolution.yml
  .github/ISSUE_TEMPLATE/other.yml
  .github/ISSUE_TEMPLATE/types-not-correct-in-with-callback.md
Labels: For Backlog Bug

#55224 Improve performance of maybe stack in recursiveTypeRelatedTo
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug

#55119 fix(54954): Javascript Intellisense adding "this." to function declaration
  src/services/completions.ts
  tests/baselines/reference/completionsAfterPropertyNameInClass.baseline
  tests/cases/fourslash/completionsAfterPropertyNameInClass.ts
Labels: For Milestone Bug

#55274 Modify interactive inlay hints API to be more backwards compatible
  src/harness/client.ts
  src/server/protocol.ts
  src/server/session.ts
  src/services/inlayHints.ts
  src/services/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/inlayHintsShouldWork1.baseline
  tests/baselines/reference/inlayHintsShouldWork11.baseline
  tests/baselines/reference/inlayHintsShouldWork12.baseline
  tests/baselines/reference/inlayHintsShouldWork13.baseline
  tests/baselines/reference/inlayHintsShouldWork2.baseline
  tests/baselines/reference/inlayHintsShouldWork3.baseline
  tests/baselines/reference/inlayHintsShouldWork32.baseline
  tests/baselines/reference/inlayHintsShouldWork33.baseline
  tests/baselines/reference/inlayHintsShouldWork34.baseline
  tests/baselines/reference/inlayHintsShouldWork35.baseline
  tests/baselines/reference/inlayHintsShouldWork36.baseline
  tests/baselines/reference/inlayHintsShouldWork4.baseline
  tests/baselines/reference/inlayHintsShouldWork5.baseline
  tests/baselines/reference/inlayHintsShouldWork50.baseline
  tests/baselines/reference/inlayHintsShouldWork52.baseline
  tests/baselines/reference/inlayHintsShouldWork53.baseline
  tests/baselines/reference/inlayHintsShouldWork6.baseline
  tests/baselines/reference/inlayHintsShouldWork62.baseline
  tests/baselines/reference/inlayHintsShouldWork63.baseline
  tests/baselines/reference/inlayHintsShouldWork64.baseline
  tests/baselines/reference/inlayHintsShouldWork68.baseline
  tests/baselines/reference/inlayHintsShouldWork7.baseline
  tests/baselines/reference/inlayHintsShouldWork8.baseline
  tests/baselines/reference/inlayHintsShouldWork9.baseline
Labels: Author: Team, For Uncommitted Bug

#55262 Fix class name references
  src/compiler/checker.ts
  src/compiler/transformers/classFields.ts
  src/compiler/transformers/legacyDecorators.ts
  src/compiler/types.ts
  tests/baselines/reference/classBlockScoping.js
  tests/baselines/reference/classNameReferencesInStaticElements.js
  tests/baselines/reference/classStaticBlock12.js
  tests/baselines/reference/classStaticBlock13(target=es2015).js
  tests/baselines/reference/computedPropertyNames52(target=es2015).js
  tests/baselines/reference/computedPropertyNames52(target=es5).js
  tests/baselines/reference/decoratedClassExportsCommonJS1.js
  tests/baselines/reference/decoratedClassExportsCommonJS2.js
  tests/baselines/reference/decoratedClassExportsSystem1.js
  tests/baselines/reference/decoratedClassExportsSystem2.js
  tests/baselines/reference/decoratorOnClassConstructorParameter5.js
  tests/baselines/reference/decoratorReferences.js
  tests/baselines/reference/privateNameAndObjectRestSpread.js
  tests/baselines/reference/privateNameNestedMethodAccess.js
  tests/baselines/reference/privateNameStaticAccessors.js
  tests/baselines/reference/privateNameStaticAccessorsAccess.js
  tests/baselines/reference/privateNameStaticAccessorsCallExpression.js
  tests/baselines/reference/privateNameStaticEmitHelpers.js
  tests/baselines/reference/privateNameStaticFieldAccess.js
  tests/baselines/reference/privateNameStaticFieldAssignment.js
  tests/baselines/reference/privateNameStaticFieldCallExpression.js
  tests/baselines/reference/privateNameStaticFieldClassExpression.js
  tests/baselines/reference/privateNameStaticFieldDerivedClasses.js
  tests/baselines/reference/privateNameStaticFieldDestructuredBinding(target=es2015).js
  tests/baselines/reference/privateNameStaticFieldUnaryMutation.js
  tests/baselines/reference/privateNameStaticMethod.js
  tests/baselines/reference/privateNameStaticMethodAssignment.js
  tests/baselines/reference/privateNameStaticMethodCallExpression.js
  tests/baselines/reference/privateNameStaticMethodClassExpression.js
  tests/baselines/reference/privateNameStaticMethodInStaticFieldInit.js
  tests/baselines/reference/privateNameWhenNotUseDefineForClassFieldsInEsNext(target=es2020).js
  tests/baselines/reference/privateNamesAndStaticFields.js
  tests/baselines/reference/privateNamesInNestedClasses-2.js
  tests/baselines/reference/privateStaticNameShadowing.js
  tests/baselines/reference/tslibReExportHelpers2.js
  tests/cases/compiler/classNameReferencesInStaticElements.ts
Labels: Author: Team, For Milestone Bug

#55276 Decorators normative updates
  src/compiler/checker.ts
  src/compiler/factory/utilities.ts
  src/compiler/transformers/classFields.ts
  src/compiler/transformers/esDecorators.ts
  tests/baselines/reference/autoAccessor1(target=es2015).js
  tests/baselines/reference/autoAccessor1(target=es2022).js
  tests/baselines/reference/autoAccessor10.js
  tests/baselines/reference/autoAccessor2(target=es2015).js
  tests/baselines/reference/autoAccessor2(target=es2022).js
  tests/baselines/reference/autoAccessor3(target=es2015).js
  tests/baselines/reference/autoAccessor3(target=es2022).js
  tests/baselines/reference/autoAccessor4(target=es2015).js
  tests/baselines/reference/autoAccessor4(target=es2022).js
  tests/baselines/reference/autoAccessor5(target=es2015).js
  tests/baselines/reference/autoAccessor5(target=es2022).js
  tests/baselines/reference/autoAccessor5(target=es5).js
  tests/baselines/reference/autoAccessorExperimentalDecorators(target=es2015).js
  tests/baselines/reference/autoAccessorExperimentalDecorators(target=es2022).js
  tests/baselines/reference/esDecorators-classDeclaration-classThisReference(target=es2015).js
  tests/baselines/reference/esDecorators-classDeclaration-classThisReference(target=es2022).js
  tests/baselines/reference/esDecorators-classDeclaration-fields-staticAccessor(target=es2015).js
  tests/baselines/reference/esDecorators-classDeclaration-fields-staticAccessor(target=es2022).js
  tests/baselines/reference/esDecorators-classDeclaration-fields-staticPrivateAccessor(target=es2015).js
  tests/baselines/reference/esDecorators-classDeclaration-fields-staticPrivateAccessor(target=es2022).js
  tests/baselines/reference/esDecorators-classDeclaration-missingEmitHelpers-staticComputedAutoAccessor.js
  tests/baselines/reference/esDecorators-preservesThis.js
  tests/baselines/reference/esDecorators-preservesThis.symbols
  tests/baselines/reference/esDecorators-preservesThis.types
  tests/baselines/reference/staticAutoAccessors(target=es2017).js
  tests/baselines/reference/staticAutoAccessors(target=es2022).js
  tests/baselines/reference/staticAutoAccessorsWithDecorators(target=es2017).js
  tests/baselines/reference/staticAutoAccessorsWithDecorators(target=es2022).js
  tests/cases/conformance/classes/propertyMemberDeclarations/staticAutoAccessors.ts
  tests/cases/conformance/classes/propertyMemberDeclarations/staticAutoAccessorsWithDecorators.ts
  tests/cases/conformance/esDecorators/esDecorators-preservesThis.ts
Labels: Author: Team, For Milestone Bug

#55245 Resolve JSX intrinsic elements to index signature symbols
  src/compiler/checker.ts
  tests/baselines/reference/inlineJsxAndJsxFragPragma.symbols
  tests/baselines/reference/inlineJsxAndJsxFragPragmaOverridesCompilerOptions.symbols
  tests/baselines/reference/inlineJsxFactoryDeclarations.symbols
  tests/baselines/reference/inlineJsxFactoryDeclarationsLocalTypes.symbols
  tests/baselines/reference/inlineJsxFactoryLocalTypeGlobalFallback.symbols
  tests/baselines/reference/inlineJsxFactoryOverridesCompilerOption.symbols
  tests/baselines/reference/inlineJsxFactoryWithFragmentIsError.symbols
  tests/baselines/reference/jsxChildrenGenericContextualTypes.symbols
  tests/baselines/reference/jsxIntrinsicDeclaredUsingTemplateLiteralTypeSignatures.errors.txt
  tests/baselines/reference/jsxIntrinsicDeclaredUsingTemplateLiteralTypeSignatures.symbols
  tests/baselines/reference/jsxIntrinsicDeclaredUsingTemplateLiteralTypeSignatures.types
  tests/baselines/reference/jsxLocalNamespaceIndexSignatureNoCrash.symbols
  tests/baselines/reference/jsxNamespaceReexports.symbols
  tests/baselines/reference/jsxParsingError1.symbols
  tests/baselines/reference/jsxParsingError2.symbols
  tests/baselines/reference/jsxParsingError3.symbols
  tests/baselines/reference/jsxParsingError4(strict=false).symbols
  tests/baselines/reference/jsxParsingError4(strict=true).symbols
  tests/baselines/reference/quickInfoOnJsxIntrinsicDeclaredUsingCatchCallIndexSignature.baseline
  tests/baselines/reference/quickInfoOnJsxIntrinsicDeclaredUsingTemplateLiteralTypeSignatures.baseline
  tests/baselines/reference/reactJsxReactResolvedNodeNext.symbols
  tests/baselines/reference/reactJsxReactResolvedNodeNextEsm.symbols
  tests/baselines/reference/tsxElementResolution2.symbols
  tests/baselines/reference/tsxElementResolution3.symbols
  tests/baselines/reference/tsxEmit1.symbols
  tests/baselines/reference/tsxEmit2.symbols
  tests/baselines/reference/tsxFragmentPreserveEmit.symbols
  tests/baselines/reference/tsxFragmentReactEmit.symbols
  tests/baselines/reference/tsxReactEmit1.symbols
  tests/baselines/reference/tsxReactEmit2.symbols
  tests/baselines/reference/tsxReactEmit4.symbols
  tests/baselines/reference/tsxReactEmit5.symbols
  tests/baselines/reference/tsxReactEmit6.symbols
  tests/baselines/reference/tsxReactEmit7.symbols
  tests/baselines/reference/tsxReactEmitEntities.symbols
  tests/baselines/reference/tsxReactEmitWhitespace.symbols
  tests/baselines/reference/tsxReactEmitWhitespace2.symbols
  tests/baselines/reference/tsxSpreadChildren.symbols
  tests/baselines/reference/tsxSpreadChildrenInvalidType(jsx=react,target=es2015).symbols
  tests/baselines/reference/tsxSpreadChildrenInvalidType(jsx=react,target=es5).symbols
  tests/baselines/reference/tsxSpreadInvalidType.symbols
  tests/cases/compiler/jsxIntrinsicDeclaredUsingTemplateLiteralTypeSignatures.tsx
  tests/cases/fourslash/quickInfoOnJsxIntrinsicDeclaredUsingCatchCallIndexSignature.ts
  tests/cases/fourslash/quickInfoOnJsxIntrinsicDeclaredUsingTemplateLiteralTypeSignatures.ts
Labels: For Backlog Bug

#55187 Remove RWC runner and related infrastructure
  Herebyfile.mjs
  scripts/build/tests.mjs
  scripts/importDefinitelyTypedTests.mjs
  src/harness/runnerbase.ts
  src/loggedIO/_namespaces/Harness.ts
  src/loggedIO/_namespaces/Playback.ts
  src/loggedIO/_namespaces/ts.server.ts
  src/loggedIO/_namespaces/ts.ts
  src/loggedIO/loggedIO.ts
  src/loggedIO/tsconfig.json
  src/testRunner/_namespaces/Harness.ts
  src/testRunner/_namespaces/Playback.ts
  src/testRunner/_namespaces/RWC.ts
  src/testRunner/_namespaces/ts.server.ts
  src/testRunner/_namespaces/ts.ts
  src/testRunner/runner.ts
  src/testRunner/rwcRunner.ts
  src/testRunner/tsconfig.json
  src/tsconfig.json
Labels: Author: Team, For Uncommitted Bug

#55299 Switch devcontainer to use Node.js 18.
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: Author: Team, For Uncommitted Bug

#55268 Disallow numeric literals with negative numbers
  src/compiler/checker.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/transformers/declarations.ts
  src/compiler/transformers/generators.ts
  src/compiler/transformers/ts.ts
  tests/baselines/reference/binaryIntegerLiteral.types
  tests/baselines/reference/binaryIntegerLiteralES6.types
  tests/baselines/reference/octalIntegerLiteral.types
  tests/baselines/reference/octalIntegerLiteralES6.types
Labels: For Uncommitted Bug

#55306 Attempt to make Search Terms more obvious in issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: Author: Team, For Uncommitted Bug

#55310 Don't mix NodeBuilder and TypeFormat flags
  src/services/inlayHints.ts
Labels: For Milestone Bug

#55177 Fixed contextual types of optional properties with `exactOptionalPropertyTypes`
  src/compiler/checker.ts
  tests/baselines/reference/contextuallyTypedOptionalProperty(exactoptionalpropertytypes=false).errors.txt
  tests/baselines/reference/contextuallyTypedOptionalProperty(exactoptionalpropertytypes=false).symbols
  tests/baselines/reference/contextuallyTypedOptionalProperty(exactoptionalpropertytypes=false).types
  tests/baselines/reference/contextuallyTypedOptionalProperty(exactoptionalpropertytypes=true).symbols
  tests/baselines/reference/contextuallyTypedOptionalProperty(exactoptionalpropertytypes=true).types
  tests/cases/compiler/contextuallyTypedOptionalProperty.ts
Labels: For Backlog Bug

#55304 Update esbuild to 0.19
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#55320 Use correct Node.flags instead of Node.kind in `isInsideAwaitableBody`
  src/services/codefixes/addMissingAwait.ts
Labels: Author: Team, For Uncommitted Bug

#55322 Add a code block to the default value of the bug template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Author: Team, For Uncommitted Bug

#48609 chore: disallows unicode escape sequence in JSX
  src/compiler/diagnosticMessages.json
  src/compiler/parser.ts
  tests/baselines/reference/unicodeEscapesInJsxtags.errors.txt
  tests/baselines/reference/unicodeEscapesInJsxtags.js
  tests/baselines/reference/unicodeEscapesInJsxtags.symbols
  tests/baselines/reference/unicodeEscapesInJsxtags.types
  tests/cases/conformance/jsx/unicodeEscapesInJsxtags.tsx
Labels: For Backlog Bug

#54188 Allow intersections to be used as valid types for template literal placeholders
  src/compiler/checker.ts
  tests/baselines/reference/templateLiteralTypesPatterns.errors.txt
  tests/baselines/reference/templateLiteralTypesPatterns.js
  tests/baselines/reference/templateLiteralTypesPatterns.symbols
  tests/baselines/reference/templateLiteralTypesPatterns.types
  tests/cases/conformance/types/literal/templateLiteralTypesPatterns.ts
  tests/cases/fourslash/stringLiteralCompletionsForOpenEndedTemplateLiteralType.ts
Labels: For Uncommitted Bug

#55181 Enable eslint rules prefer-rest-params and prefer-spread
  .eslintrc.json
  src/compiler/checker.ts
  src/compiler/commandLineParser.ts
  src/compiler/core.ts
  src/compiler/moduleNameResolver.ts
  src/compiler/utilities.ts
  src/deprecatedCompat/deprecate.ts
  src/executeCommandLine/executeCommandLine.ts
  src/harness/fourslashImpl.ts
  src/harness/harnessLanguageService.ts
  src/services/services.ts
Labels: Author: Team, For Uncommitted Bug

#55273 Move tsserverlibrary.js to typescript.js, make tsserverlibrary.js a shim
  Herebyfile.mjs
  src/testRunner/unittests/publicApi.ts
  src/tsconfig.json
  src/tsserverlibrary/_namespaces/ts.ts
  src/tsserverlibrary/tsconfig.json
  src/tsserverlibrary/tsserverlibrary.ts
  src/typescript/_namespaces/ts.server.ts
  src/typescript/_namespaces/ts.ts
  src/typescript/tsconfig.json
  tests/baselines/reference/APILibCheck.types
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Breaking Change, API, Author: Team, For Uncommitted Bug

#55373 Fixed `hasInvalidEscape` implementation
  src/compiler/utilities.ts
  tests/baselines/reference/invalidTaggedTemplateEscapeSequences(target=es2015).js
  tests/baselines/reference/taggedTemplateStringsHexadecimalEscapesES6.js
  tests/baselines/reference/taggedTemplateStringsWithUnicodeEscapesES6.js
Labels: For Uncommitted Bug

#55298 Preserve input key style of computed properties in declaration emit
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitPropertyNumericStringKey.js
  tests/baselines/reference/declarationEmitPropertyNumericStringKey.symbols
  tests/baselines/reference/declarationEmitPropertyNumericStringKey.types
  tests/baselines/reference/declarationEmitStringEnumUsedInNonlocalSpread.js
  tests/baselines/reference/declarationEmitStringEnumUsedInNonlocalSpread.types
  tests/baselines/reference/duplicateObjectLiteralProperty_computedName1.types
  tests/baselines/reference/literalsInComputedProperties1.types
  tests/cases/compiler/declarationEmitPropertyNumericStringKey.ts
Labels: For Backlog Bug

#55360 Add additional information section to the bug report template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: For Uncommitted Bug

#55379 Fix unused baseline failure on main
  tests/baselines/reference/inlayHintsInteractiveReturnType.baseline
Labels: Author: Team, For Uncommitted Bug

#55376 Share redirects cache key calculation between multiple caches used for module resolution and type reference directive
  src/compiler/moduleNameResolver.ts
  src/compiler/program.ts
  src/compiler/resolutionCache.ts
  src/compiler/tsbuildPublic.ts
Labels: Author: Team, For Uncommitted Bug

#55381 Prevent detached diagnostics from running off the end of the file
  src/compiler/parser.ts
  src/compiler/utilities.ts
  tests/baselines/reference/parseUnmatchedTypeAssertion.errors.txt
  tests/baselines/reference/parseUnmatchedTypeAssertion.js
  tests/baselines/reference/parseUnmatchedTypeAssertion.symbols
  tests/baselines/reference/parseUnmatchedTypeAssertion.types
  tests/cases/compiler/parseUnmatchedTypeAssertion.ts
Labels: Author: Team, For Milestone Bug

#54815 Remove allowComplexConstraintInference in inferTypes
  src/compiler/checker.ts
Labels: Author: Team, For Backlog Bug

#55151 Discriminate contextual types using shorthand properties
  src/compiler/checker.ts
  tests/baselines/reference/contextuallyTypedByDiscriminableUnion.js
  tests/baselines/reference/contextuallyTypedByDiscriminableUnion.symbols
  tests/baselines/reference/contextuallyTypedByDiscriminableUnion.types
  tests/cases/compiler/contextuallyTypedByDiscriminableUnion.ts
Labels: For Uncommitted Bug

#55384 fix(55374): Invalid Parameter Inlay Hint
  src/services/inlayHints.ts
  tests/baselines/reference/inlayHintsParameterNames.baseline
  tests/cases/fourslash/inlayHintsParameterNames.ts
Labels: For Milestone Bug

#54777 Display write type for property accesses in write locations
  src/compiler/checker.ts
  tests/cases/fourslash/quickInfoOnPropertyAccessInWriteLocation1.ts
  tests/cases/fourslash/quickInfoOnPropertyAccessInWriteLocation2.ts
  tests/cases/fourslash/quickInfoOnPropertyAccessInWriteLocation3.ts
  tests/cases/fourslash/quickInfoOnPropertyAccessInWriteLocation4.ts
  tests/cases/fourslash/quickInfoOnPropertyAccessInWriteLocation5.ts
Labels: For Backlog Bug

#52493 Widen widening literal types through compound-like assignments
  src/compiler/checker.ts
  src/compiler/factory/utilities.ts
  src/compiler/utilities.ts
  tests/baselines/reference/literalWideningWithCompoundLikeAssignments.symbols
  tests/baselines/reference/literalWideningWithCompoundLikeAssignments.types
  tests/cases/compiler/literalWideningWithCompoundLikeAssignments.ts
Labels: For Backlog Bug

#55387 Add extra tests for type and value symbol merging
  tests/baselines/reference/typeValueMerge1.symbols
  tests/baselines/reference/typeValueMerge1.types
  tests/cases/conformance/externalModules/typeValueMerge1.ts
Labels: For Backlog Bug

#55390 Don't track private symbol roots in other files during js declaration emit
  src/compiler/checker.ts
  tests/baselines/reference/jsDeclarationEmitDoesNotRenameImport.js
  tests/baselines/reference/jsDeclarationEmitDoesNotRenameImport.symbols
  tests/baselines/reference/jsDeclarationEmitDoesNotRenameImport.types
  tests/cases/compiler/jsDeclarationEmitDoesNotRenameImport.ts
Labels: Author: Team, For Milestone Bug

#55402 Add dprint commit to git-blame-ignore-revs
  .git-blame-ignore-revs
Labels: Author: Team, For Uncommitted Bug

#55397 Fixed contravariant inferences from annotated optional parameters
  src/compiler/checker.ts
  tests/baselines/reference/contravariantOnlyInferenceWithAnnotatedOptionalParameter.symbols
  tests/baselines/reference/contravariantOnlyInferenceWithAnnotatedOptionalParameter.types
  tests/baselines/reference/contravariantOnlyInferenceWithAnnotatedOptionalParameterJs.symbols
  tests/baselines/reference/contravariantOnlyInferenceWithAnnotatedOptionalParameterJs.types
  tests/cases/compiler/contravariantOnlyInferenceWithAnnotatedOptionalParameter.ts
  tests/cases/compiler/contravariantOnlyInferenceWithAnnotatedOptionalParameterJs.ts
Labels: For Milestone Bug

#55403 Enforce CRLF in TS/JS files
  .dprint.jsonc
  src/lib/es2023.collection.d.ts
  src/lib/esnext.decorators.d.ts
Labels: Author: Team, For Uncommitted Bug

#55401 Reference ATTW in module_resolution.yml
  .github/ISSUE_TEMPLATE/module_resolution.yml
Labels: Author: Team, For Uncommitted Bug

#55407 Make sure emitted d.ts files are LF, not CRLF
  scripts/dtsBundler.mjs
Labels: Author: Team, For Uncommitted Bug

#55414 Fix typo isInvalid -> isValid
  src/compiler/parser.ts
Labels: For Uncommitted Bug

#55416 Consistently use ECMAScript and CommonJS wording
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/types.ts
  tests/baselines/reference/moduleResolutionWithoutExtension1.errors.txt
  tests/baselines/reference/moduleResolutionWithoutExtension3.errors.txt
  tests/baselines/reference/moduleResolutionWithoutExtension4.errors.txt
  tests/baselines/reference/moduleResolutionWithoutExtension5.errors.txt
  tests/baselines/reference/moduleResolutionWithoutExtension8.errors.txt
  tests/baselines/reference/nodeModules1(module=node16).errors.txt
  tests/baselines/reference/nodeModules1(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesAllowJs1(module=node16).errors.txt
  tests/baselines/reference/nodeModulesAllowJs1(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesImportAssertions(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesImportModeDeclarationEmit1(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesImportModeDeclarationEmitErrors1(module=nodenext).errors.txt
  tests/baselines/reference/nodeNextImportModeImplicitIndexResolution.errors.txt
Labels: For Uncommitted Bug

#55193 error on duplicate symbols in object literals
  src/compiler/checker.ts
  tests/baselines/reference/symbolProperty36.errors.txt
  tests/baselines/reference/uniqueSymbolsPropertyNames.errors.txt
  tests/baselines/reference/uniqueSymbolsPropertyNames.js
  tests/baselines/reference/uniqueSymbolsPropertyNames.symbols
  tests/baselines/reference/uniqueSymbolsPropertyNames.types
  tests/cases/conformance/types/uniqueSymbol/uniqueSymbolsPropertyNames.ts
Labels: For Backlog Bug

#54960 Make contextually-typed parameter with question token optional
  src/compiler/checker.ts
  tests/baselines/reference/argumentsReferenceInFunction1_Js.errors.txt
  tests/baselines/reference/argumentsReferenceInFunction1_Js.symbols
  tests/baselines/reference/argumentsReferenceInFunction1_Js.types
  tests/baselines/reference/contextuallyTypedIifeStrict.errors.txt
  tests/baselines/reference/contextuallyTypedIifeStrict.js
  tests/baselines/reference/contextuallyTypedIifeStrict.symbols
  tests/baselines/reference/contextuallyTypedIifeStrict.types
  tests/baselines/reference/contextuallyTypedParametersOptionalInJSDoc.errors.txt
  tests/baselines/reference/contextuallyTypedParametersOptionalInJSDoc.symbols
  tests/baselines/reference/contextuallyTypedParametersOptionalInJSDoc.types
  tests/baselines/reference/contextuallyTypedParametersWithQuestionToken.errors.txt
  tests/baselines/reference/contextuallyTypedParametersWithQuestionToken.symbols
  tests/baselines/reference/contextuallyTypedParametersWithQuestionToken.types
  tests/baselines/reference/restTuplesFromContextualTypes.types
  tests/cases/compiler/argumentsReferenceInFunction1_Js.ts
  tests/cases/compiler/contextuallyTypedParametersOptionalInJSDoc.ts
  tests/cases/compiler/contextuallyTypedParametersWithQuestionToken.ts
  tests/cases/conformance/expressions/functions/contextuallyTypedIifeStrict.ts
Labels: For Uncommitted Bug

#55393 Fixed serialization of param names in setters from JS files
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitClassSetAccessorParamNameInJs.js
  tests/baselines/reference/declarationEmitClassSetAccessorParamNameInJs.symbols
  tests/baselines/reference/declarationEmitClassSetAccessorParamNameInJs.types
  tests/baselines/reference/declarationEmitClassSetAccessorParamNameInJs2.js
  tests/baselines/reference/declarationEmitClassSetAccessorParamNameInJs2.symbols
  tests/baselines/reference/declarationEmitClassSetAccessorParamNameInJs2.types
  tests/baselines/reference/declarationEmitClassSetAccessorParamNameInJs3.js
  tests/baselines/reference/declarationEmitClassSetAccessorParamNameInJs3.symbols
  tests/baselines/reference/declarationEmitClassSetAccessorParamNameInJs3.types
  tests/baselines/reference/genericSetterInClassTypeJsDoc.js
  tests/baselines/reference/jsDeclarationsClasses.js
  tests/baselines/reference/jsDeclarationsFunctionLikeClasses2.js
  tests/baselines/reference/jsDeclarationsGetterSetter.js
  tests/baselines/reference/jsDeclarationsGetterSetter.symbols
  tests/baselines/reference/jsDeclarationsGetterSetter.types
  tests/baselines/reference/jsDeclarationsReusesExistingTypeAnnotations.js
  tests/baselines/reference/jsdocAccessibilityTagsDeclarations.js
  tests/baselines/reference/thisPropertyAssignmentInherited.js
  tests/cases/compiler/declarationEmitClassSetAccessorParamNameInJs.ts
  tests/cases/compiler/declarationEmitClassSetAccessorParamNameInJs2.ts
  tests/cases/compiler/declarationEmitClassSetAccessorParamNameInJs3.ts
  tests/cases/conformance/jsdoc/declarations/jsDeclarationsGetterSetter.ts
Labels: For Backlog Bug

#55426 Remove lib.d.ts line info in inlay hint baselines
  src/harness/fourslashImpl.ts
Labels: For Uncommitted Bug

#54448 Improve inference between types with multiple signatures
  src/compiler/checker.ts
  tests/baselines/reference/multiSignatureTypeInference.symbols
  tests/baselines/reference/multiSignatureTypeInference.types
  tests/cases/compiler/multiSignatureTypeInference.ts
Labels: Author: Team, For Milestone Bug

#55464 Fix check in getDiscriminantPropertyAccess
  src/compiler/checker.ts
  tests/baselines/reference/narrowingUnionToUnion.js
  tests/baselines/reference/narrowingUnionToUnion.symbols
  tests/baselines/reference/narrowingUnionToUnion.types
  tests/cases/compiler/narrowingUnionToUnion.ts
Labels: Author: Team, For Uncommitted Bug

#55484 perf: reduce GC pressure by hoisting script target features object
  src/compiler/utilities.ts
Labels: For Uncommitted Bug

#55470 Remove perf-result-post
  scripts/perf-result-post.mjs
Labels: Author: Team, For Uncommitted Bug

#55476 [Interactive inlay hints] Get source file from parameter node
  src/server/session.ts
  src/services/inlayHints.ts
  tests/baselines/reference/inlayHintsInteractiveMultifileFunctionCalls.baseline
  tests/cases/fourslash/inlayHintsInteractiveMultifileFunctionCalls.ts
Labels: For Milestone Bug

#55112 Remove the dependency of "del"
  Herebyfile.mjs
  package-lock.json
  package.json
  scripts/build/tests.mjs
  scripts/build/utils.mjs
Labels: For Uncommitted Bug

#55468 Remove use of fs-extra
  package-lock.json
  package.json
  scripts/produceLKG.mjs
Labels: Author: Team, For Uncommitted Bug

#55469 fix(55434): Renamed field takes on documentation from other field with the same name
  src/services/symbolDisplay.ts
  tests/baselines/reference/quickInfoForObjectBindingElementName06.baseline
  tests/cases/fourslash/quickInfoForObjectBindingElementName06.ts
Labels: For Backlog Bug

#55488 Fix typo in getScriptTargetFeatures map
  src/compiler/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#55283 Fixed a redundant used before defined error
  src/compiler/checker.ts
  tests/baselines/reference/noUsedBeforeDefinedErrorInTypeContext.symbols
  tests/baselines/reference/noUsedBeforeDefinedErrorInTypeContext.types
  tests/cases/compiler/noUsedBeforeDefinedErrorInTypeContext.ts
Labels: For Backlog Bug

#55449 Fix double error on invalid delete of readonly property
  src/compiler/checker.ts
  tests/baselines/reference/deleteReadonlyInStrictNullChecks.errors.txt
  tests/baselines/reference/deleteReadonlyInStrictNullChecks.js
  tests/baselines/reference/deleteReadonlyInStrictNullChecks.symbols
  tests/baselines/reference/deleteReadonlyInStrictNullChecks.types
  tests/cases/compiler/deleteReadonlyInStrictNullChecks.ts
Labels: For Backlog Bug

#55459 Avoid resolving objects in getTypeFacts when caller doesn't need that info
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug

#55284 Don't parse `DotDotDotToken` in JSX attribute values
  src/compiler/parser.ts
  tests/baselines/reference/jsxParsingErrorImmediateSpreadInAttributeValue.errors.txt
  tests/baselines/reference/jsxParsingErrorImmediateSpreadInAttributeValue.js
  tests/baselines/reference/jsxParsingErrorImmediateSpreadInAttributeValue.symbols
  tests/baselines/reference/jsxParsingErrorImmediateSpreadInAttributeValue.types
  tests/cases/conformance/jsx/jsxParsingErrorImmediateSpreadInAttributeValue.tsx
Labels: For Uncommitted Bug

#55482 perf: replace String and Array indexOf method calls with includes method call
  scripts/errorCheck.mjs
  scripts/eslint/rules/argument-trivia.cjs
  scripts/update-experimental-branches.mjs
  src/cancellationToken/cancellationToken.ts
  src/compiler/checker.ts
  src/compiler/commandLineParser.ts
  src/compiler/core.ts
  src/compiler/emitter.ts
  src/compiler/moduleNameResolver.ts
  src/compiler/moduleSpecifiers.ts
  src/compiler/parser.ts
  src/compiler/path.ts
  src/compiler/program.ts
  src/compiler/resolutionCache.ts
  src/compiler/sys.ts
  src/compiler/transformers/declarations.ts
  src/compiler/utilities.ts
  src/executeCommandLine/executeCommandLine.ts
  src/harness/compilerImpl.ts
  src/harness/fourslashImpl.ts
  src/harness/harnessIO.ts
  src/harness/harnessLanguageService.ts
  src/harness/harnessUtils.ts
  src/harness/vpathUtil.ts
  src/jsTyping/shared.ts
  src/server/editorServices.ts
  src/server/project.ts
  src/server/scriptInfo.ts
  src/server/session.ts
  src/services/codefixes/fixUnusedIdentifier.ts
  src/services/exportInfoMap.ts
  src/services/formatting/rules.ts
  src/services/formatting/smartIndenter.ts
  src/services/refactors/extractSymbol.ts
  src/services/services.ts
  src/services/stringCompletions.ts
  src/services/utilities.ts
  src/testRunner/compilerRunner.ts
  src/testRunner/runner.ts
  src/testRunner/unittests/helpers/vfs.ts
  src/testRunner/unittests/moduleResolution.ts
  src/testRunner/unittests/tsbuild/graphOrdering.ts
  src/testRunner/unittests/tsc/declarationEmit.ts
  src/testRunner/unittests/tscWatch/resolutionCache.ts
  src/testRunner/unittests/tsserver/typingsInstaller.ts
  src/typingsInstaller/nodeTypingsInstaller.ts
Labels: For Uncommitted Bug

#55229 Only infer readonly tuples for `const` type parameters when constraints permit
  src/compiler/checker.ts
  tests/baselines/reference/typeParameterConstModifiers.errors.txt
  tests/baselines/reference/typeParameterConstModifiers.js
  tests/baselines/reference/typeParameterConstModifiers.symbols
  tests/baselines/reference/typeParameterConstModifiers.types
  tests/cases/conformance/types/typeParameters/typeParameterLists/typeParameterConstModifiers.ts
Labels: Author: Team, For Milestone Bug

#55513 Add a fourslash completions test related to JSDoc `@template` on prototype method
  tests/cases/fourslash/jsdocTemplatePrototypeCompletions.ts
Labels: For Backlog Bug

#55514 Add a test case with a generic member call returning a closed over object
  tests/baselines/reference/genericCallOnMemberReturningClosedOverObject.symbols
  tests/baselines/reference/genericCallOnMemberReturningClosedOverObject.types
  tests/cases/compiler/genericCallOnMemberReturningClosedOverObject.ts
Labels: For Backlog Bug

#55519 Add a test for finding all references of same-named imports from two missing modules
  tests/baselines/reference/findAllRefsMissingModulesOverlappingSpecifiers.baseline.jsonc
  tests/cases/fourslash/findAllRefsMissingModulesOverlappingSpecifiers.ts
Labels: For Backlog Bug

#55522 Add an extra test for `as const satisfies` with a mutable array
  tests/baselines/reference/typeSatisfaction_asConstArrays.symbols
  tests/baselines/reference/typeSatisfaction_asConstArrays.types
  tests/cases/conformance/expressions/typeSatisfaction/typeSatisfaction_asConstArrays.ts
Labels: For Uncommitted Bug

#55537 Ensure parsing context is restored in jsdoc parser
  src/compiler/parser.ts
Labels: Author: Team, For Uncommitted Bug

#55279 do not report use-before-declaration error in async like IIFE initial…
  src/compiler/checker.ts
  tests/baselines/reference/blockScopedVariablesUseBeforeDef.errors.txt
  tests/baselines/reference/blockScopedVariablesUseBeforeDef.js
  tests/baselines/reference/blockScopedVariablesUseBeforeDef.symbols
  tests/baselines/reference/blockScopedVariablesUseBeforeDef.types
  tests/cases/compiler/blockScopedVariablesUseBeforeDef.ts
Labels: For Backlog Bug

#55472 Avoid trying to emit anonymous classish/expando functions as assignments
  src/compiler/checker.ts
  tests/baselines/reference/jsDeclarationsFunctionClassesCjsExportAssignment.js
  tests/baselines/reference/jsDeclarationsGlobalFileConstFunction.js
  tests/baselines/reference/jsDeclarationsGlobalFileConstFunction.symbols
  tests/baselines/reference/jsDeclarationsGlobalFileConstFunction.types
  tests/baselines/reference/jsDeclarationsGlobalFileConstFunctionNamed.js
  tests/baselines/reference/jsDeclarationsGlobalFileConstFunctionNamed.symbols
  tests/baselines/reference/jsDeclarationsGlobalFileConstFunctionNamed.types
  tests/cases/compiler/jsDeclarationsGlobalFileConstFunction.ts
  tests/cases/compiler/jsDeclarationsGlobalFileConstFunctionNamed.ts
Labels: Author: Team, For Uncommitted Bug

#55515 Clean up helpers which are always present in ES2020
  src/compiler/commandLineParser.ts
  src/compiler/core.ts
  src/compiler/parser.ts
  src/compiler/program.ts
  src/compiler/scanner.ts
  src/compiler/semver.ts
  src/compiler/sourcemap.ts
  src/compiler/utilities.ts
  src/executeCommandLine/executeCommandLine.ts
  src/harness/fourslashImpl.ts
  src/jsTyping/shared.ts
  src/services/outliningElementsCollector.ts
  src/testRunner/unittests/canWatch.ts
Labels: Author: Team, For Uncommitted Bug

#55282 Parse reserved identifiers as dotted names of ambient modules
  src/compiler/parser.ts
  tests/baselines/reference/ambientModuleDeclarationWithReservedIdentifierInDottedPath.errors.txt
  tests/baselines/reference/ambientModuleDeclarationWithReservedIdentifierInDottedPath.js
  tests/baselines/reference/ambientModuleDeclarationWithReservedIdentifierInDottedPath.symbols
  tests/baselines/reference/ambientModuleDeclarationWithReservedIdentifierInDottedPath.types
  tests/baselines/reference/ambientModuleDeclarationWithReservedIdentifierInDottedPath2.errors.txt
  tests/baselines/reference/ambientModuleDeclarationWithReservedIdentifierInDottedPath2.js
  tests/baselines/reference/ambientModuleDeclarationWithReservedIdentifierInDottedPath2.symbols
  tests/baselines/reference/ambientModuleDeclarationWithReservedIdentifierInDottedPath2.types
  tests/cases/conformance/ambient/ambientModuleDeclarationWithReservedIdentifierInDottedPath.ts
  tests/cases/conformance/ambient/ambientModuleDeclarationWithReservedIdentifierInDottedPath2.ts
Labels: For Backlog Bug

#55552 Fixed a string completions regression when requested directly in argument position
  src/compiler/checker.ts
  tests/cases/fourslash/stringLiteralCompletionsInArgUsingInferenceResultFromPreviousArg.ts
Labels: For Backlog Bug

#55252 Transfer all declared symbols onto the type from the interface that extends another
  src/compiler/checker.ts
  tests/baselines/reference/classExtendingAbstractClassWithMemberCalledTheSameAsItsOwnTypeParam.symbols
  tests/baselines/reference/classExtendingAbstractClassWithMemberCalledTheSameAsItsOwnTypeParam.types
  tests/cases/compiler/classExtendingAbstractClassWithMemberCalledTheSameAsItsOwnTypeParam.ts
  tests/cases/fourslash/quickInfoOnPropDeclaredUsingIndexSignatureOnInterfaceWithBase.ts
Labels: For Backlog Bug

#55424 Disallow object prototype property access on const enums
  src/compiler/checker.ts
  tests/baselines/reference/constEnumNoObjectPrototypePropertyAccess.errors.txt
  tests/baselines/reference/constEnumNoObjectPrototypePropertyAccess.symbols
  tests/baselines/reference/constEnumNoObjectPrototypePropertyAccess.types
  tests/cases/conformance/constEnums/constEnumNoObjectPrototypePropertyAccess.ts
Labels: For Backlog Bug

#55419 Make formatting settings in settings template apply to all filetypes
  .vscode/settings.template.json
Labels: Author: Team, Housekeeping, For Uncommitted Bug

#55030 support generic variant setter
  src/compiler/checker.ts
  tests/baselines/reference/divergentAccessorsTypes7.js
  tests/baselines/reference/divergentAccessorsTypes7.symbols
  tests/baselines/reference/divergentAccessorsTypes7.types
  tests/cases/compiler/divergentAccessorsTypes7.ts
Labels: For Backlog Bug

#55020 fix(55014): Quick fix for ts7051 introduces incorrect type
  src/services/codefixes/addNameToNamelessParameter.ts
  tests/cases/fourslash/codeFixAddParameterNames4.ts
  tests/cases/fourslash/codeFixAddParameterNames5.ts
  tests/cases/fourslash/codeFixAddParameterNames6.ts
Labels: For Backlog Bug

#55581 Add dprint to devcontainer
  .devcontainer/devcontainer.json
Labels: Author: Team, For Uncommitted Bug

#55556 Prevents auto import in module: "none"
  tests/cases/fourslash/autoImportModuleNone1.ts
  tests/cases/fourslash/autoImportModuleNone2.ts
Labels: For Milestone Bug
