Repository microsoft/TypeScript, pull requests merged in 2023-02, with the labels that each got.

#51149 fix(50952): Can't infer from this type on static class method call in JS Doc
  src/compiler/checker.ts
  tests/baselines/reference/constructorTagWithThisTag.symbols
  tests/baselines/reference/inferThis.symbols
  tests/baselines/reference/inferThis.types
  tests/baselines/reference/thisTag1.symbols
  tests/cases/conformance/jsdoc/inferThis.ts
Labels: For Backlog Bug

#52140 Fixed type lookup on non-exported value symbol when it has an export symbol
  src/compiler/checker.ts
  tests/cases/fourslash/quickInfoOnValueSymbolWithoutExportWithSameNameExportSymbol.ts
Labels: For Backlog Bug

#52450 Prevent valid JSX from being seen as the start of a generic arrow function, fix crashes
  src/compiler/parser.ts
  src/compiler/utilities.ts
  tests/baselines/reference/parseJsxExtends1.js
  tests/baselines/reference/parseJsxExtends1.symbols
  tests/baselines/reference/parseJsxExtends1.types
  tests/baselines/reference/parseJsxExtends2.errors.txt
  tests/baselines/reference/parseJsxExtends2.js
  tests/baselines/reference/parseJsxExtends2.symbols
  tests/baselines/reference/parseJsxExtends2.types
  tests/cases/compiler/parseJsxExtends1.ts
  tests/cases/compiler/parseJsxExtends2.ts
  tests/cases/fourslash/jsxElementExtendsNoCrash1.ts
  tests/cases/fourslash/jsxElementExtendsNoCrash2.ts
  tests/cases/fourslash/jsxElementExtendsNoCrash3.ts
Labels: Author: Team, For Milestone Bug

#52532 Permit instantiation expressions in `typeof import(...)`
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/types.ts
  tests/baselines/reference/tsserver/plugins/getSupportedCodeFixes-can-be-proxied.js
  tests/baselines/reference/typeofImportInstantiationExpression.js
  tests/baselines/reference/typeofImportInstantiationExpression.symbols
  tests/baselines/reference/typeofImportInstantiationExpression.types
  tests/cases/compiler/typeofImportInstantiationExpression.ts
Labels: Author: Team, For Milestone Bug

#52380 Remove line/col for all lib file diagnostics in baselines, completions
  Herebyfile.mjs
  src/harness/fourslashImpl.ts
  src/harness/harnessIO.ts
  tests/baselines/reference/completionsStringMethods.baseline
  tests/baselines/reference/duplicateNumericIndexers.errors.txt
  tests/baselines/reference/objectTypeHidingMembersOfExtendedObject.errors.txt
  tests/baselines/reference/objectTypeWithStringIndexerHidingObjectIndexer.errors.txt
  tests/baselines/reference/variableDeclarationInStrictMode1.errors.txt
Labels: Author: Team, Housekeeping, For Uncommitted Bug

#52541 fix/52457: remove extra the from TS(2809)
  src/compiler/diagnosticMessages.json
  src/compiler/parser.ts
  tests/baselines/reference/assignmentLHSIsValue.errors.txt
  tests/baselines/reference/destructionAssignmentError.errors.txt
  tests/baselines/reference/unicodeEscapesInNames02(target=es5).errors.txt
Labels: lib update, For Backlog Bug

#52538 Fix auto-imports of aliased packages with `exports`
  src/compiler/moduleSpecifiers.ts
  tests/baselines/reference/tsbuild/moduleSpecifiers/synthesized-module-specifiers-across-projects-resolve-correctly.js
  tests/cases/fourslash/server/autoImportNodeModuleSymlinkRenamed.ts
Labels: Author: Team, For Uncommitted Bug

#51228 Better compatibility error for indexed access type
  src/compiler/checker.ts
  tests/baselines/reference/conditionalTypes1.errors.txt
  tests/baselines/reference/indexedAccessRelation.errors.txt
  tests/baselines/reference/keyofAndIndexedAccess2.errors.txt
  tests/baselines/reference/keyofAndIndexedAccessErrors.errors.txt
  tests/baselines/reference/keyofAndIndexedAccessErrors.js
  tests/baselines/reference/keyofAndIndexedAccessErrors.symbols
  tests/baselines/reference/keyofAndIndexedAccessErrors.types
  tests/baselines/reference/mappedTypeRelationships.errors.txt
  tests/baselines/reference/nonPrimitiveConstraintOfIndexAccessType.errors.txt
  tests/cases/conformance/types/keyof/keyofAndIndexedAccessErrors.ts
Labels: For Backlog Bug

#52544 fix(52455): destructuring function props with "enum" as property name breaks .d.ts
  src/compiler/transformers/declarations.ts
  tests/baselines/reference/declarationEmitKeywordDestructuring.js
  tests/baselines/reference/declarationEmitKeywordDestructuring.symbols
  tests/baselines/reference/declarationEmitKeywordDestructuring.types
  tests/cases/compiler/declarationEmitKeywordDestructuring.ts
Labels: For Milestone Bug

#52546 Fixed accidental propagation of caching-related `objectFlags`
  src/compiler/checker.ts
  tests/baselines/reference/unknownLikeUnionObjectFlagsNotPropagated.symbols
  tests/baselines/reference/unknownLikeUnionObjectFlagsNotPropagated.types
  tests/cases/compiler/unknownLikeUnionObjectFlagsNotPropagated.ts
Labels: For Backlog Bug

#52406 imports: display completions to files with extensions from ambient modules
  src/services/stringCompletions.ts
  tests/cases/fourslash/pathCompletionsAllowModuleAugmentationExtensions.ts
Labels: For Uncommitted Bug

#52181 Cover more literal expressions in `getQuickTypeOfExpression`
  src/compiler/checker.ts
Labels: For Uncommitted Bug

#52467 Make getTypeOfSymbol, isArrayType, isTupleType public on TypeChecker
  src/compiler/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#52392 Consistently propagate `intersectionState` in relations
  src/compiler/checker.ts
  tests/baselines/reference/nestedExcessPropertyChecking.errors.txt
  tests/baselines/reference/nestedExcessPropertyChecking.js
  tests/baselines/reference/nestedExcessPropertyChecking.symbols
  tests/baselines/reference/nestedExcessPropertyChecking.types
  tests/baselines/reference/unionThisTypeInFunctions.errors.txt
  tests/cases/compiler/nestedExcessPropertyChecking.ts
Labels: Author: Team, For Uncommitted Bug

#52554 Fix crash when looking for `__esModule` during symbol table merging
  src/compiler/checker.ts
  tests/baselines/reference/crashDeclareGlobalTypeofExport.symbols
  tests/baselines/reference/crashDeclareGlobalTypeofExport.types
  tests/cases/compiler/crashDeclareGlobalTypeofExport.ts
  tests/cases/fourslash/codefixCrashExportGlobal.ts
Labels: Author: Team, For Milestone Bug

#52574 fix(52543): Module specifier should be escaped for snippet in import statement completion
  src/services/completions.ts
  tests/baselines/reference/importStatementCompletions3.baseline
  tests/cases/fourslash/importStatementCompletions3.ts
Labels: For Backlog Bug

#51842 Always respect preserveSymlinks
  src/compiler/moduleNameResolver.ts
  tests/baselines/reference/moduleResolutionWithExtensions_withPaths.trace.json
  tests/baselines/reference/moduleResolutionWithSuffixes_one_externalModule_withPaths.trace.json
  tests/baselines/reference/nodeModulesExportsBlocksTypesVersions(module=node16).trace.json
  tests/baselines/reference/nodeModulesExportsBlocksTypesVersions(module=nodenext).trace.json
  tests/baselines/reference/pathMappingBasedModuleResolution_withExtension_MapedToNodeModules.trace.json
  tests/baselines/reference/requireOfJsonFile_PathMapping.trace.json
  tests/baselines/reference/resolvesWithoutExportsDiagnostic1(moduleresolution=bundler).trace.json
  tests/baselines/reference/resolvesWithoutExportsDiagnostic1(moduleresolution=node16).trace.json
  tests/baselines/reference/scopedPackagesClassic.trace.json
  tests/baselines/reference/typingsLookupAmd.trace.json
Labels: For Backlog Bug

#52556 don't use `Extension[]` cast
  src/services/stringCompletions.ts
Labels: For Uncommitted Bug

#52434 fix(52418): "Convert to named function" breaks on concise return of async function
  src/services/refactors/convertArrowFunctionOrFunctionExpression.ts
  tests/cases/fourslash/refactorConvertArrowFunctionOrFunctionExpression_InnerAsyncFunction1.ts
  tests/cases/fourslash/refactorConvertArrowFunctionOrFunctionExpression_InnerAsyncFunction2.ts
  tests/cases/fourslash/refactorConvertArrowFunctionOrFunctionExpression_InnerAsyncFunction3.ts
Labels: For Backlog Bug

#52577 Improve `@overload`'s interactions with constructors
  src/compiler/checker.ts
  tests/baselines/reference/overloadTag2.errors.txt
  tests/baselines/reference/overloadTag2.js
  tests/baselines/reference/overloadTag2.symbols
  tests/baselines/reference/overloadTag2.types
  tests/cases/conformance/jsdoc/overloadTag2.ts
Labels: Author: Team, For Milestone Bug

#52573 return `baseType` in `getSubstitutionType` when `baseType` is `any`
  src/compiler/checker.ts
  tests/baselines/reference/conditionalTypeAnyUnion.js
  tests/baselines/reference/conditionalTypeAnyUnion.symbols
  tests/baselines/reference/conditionalTypeAnyUnion.types
  tests/cases/compiler/conditionalTypeAnyUnion.ts
Labels: For Milestone Bug

#52584 Speed up debug attach by setting outFiles
  .vscode/launch.template.json
Labels: Author: Team, For Uncommitted Bug

#52555 Fix false verbatimModuleSyntax error on `export namespace` in ESM
  src/compiler/checker.ts
  tests/baselines/reference/verbatimModuleSyntaxRestrictionsESM(esmoduleinterop=false).errors.txt
  tests/baselines/reference/verbatimModuleSyntaxRestrictionsESM(esmoduleinterop=false).js
  tests/baselines/reference/verbatimModuleSyntaxRestrictionsESM(esmoduleinterop=false).symbols
  tests/baselines/reference/verbatimModuleSyntaxRestrictionsESM(esmoduleinterop=false).types
  tests/baselines/reference/verbatimModuleSyntaxRestrictionsESM(esmoduleinterop=true).errors.txt
  tests/baselines/reference/verbatimModuleSyntaxRestrictionsESM(esmoduleinterop=true).js
  tests/baselines/reference/verbatimModuleSyntaxRestrictionsESM(esmoduleinterop=true).symbols
  tests/baselines/reference/verbatimModuleSyntaxRestrictionsESM(esmoduleinterop=true).types
  tests/cases/conformance/externalModules/verbatimModuleSyntaxRestrictionsESM.ts
Labels: Author: Team, For Milestone Bug

#52596 Make getSupportedCodeFixes plugin test such that we dont need to update its baseline for every new error
  src/testRunner/unittests/tsserver/plugins.ts
  tests/baselines/reference/tsserver/plugins/getSupportedCodeFixes-can-be-proxied.js
Labels: Author: Team, For Uncommitted Bug

#52595 Remove always-incorrect error message about importing .ts extensions
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/allowImportingTsExtensions(moduleresolution=bundler).errors.txt
  tests/baselines/reference/allowImportingTsExtensions(moduleresolution=classic).errors.txt
  tests/baselines/reference/allowImportingTsExtensions(moduleresolution=node10).errors.txt
  tests/baselines/reference/allowImportingTsExtensions(moduleresolution=node16).errors.txt
  tests/baselines/reference/allowImportingTsExtensions(moduleresolution=nodenext).errors.txt
  tests/baselines/reference/declarationFileForTsJsImport.errors.txt
  tests/baselines/reference/tsserver/plugins/getSupportedCodeFixes-can-be-proxied.js
  tests/cases/conformance/moduleResolution/allowImportingTsExtensions.ts
Labels: Author: Team, For Milestone Bug

#52562 Handle literal string union complete pattern for JSX attribute snippets (`<input type />`)
  src/compiler/checker.ts
  src/compiler/types.ts
  src/services/completions.ts
  src/services/utilities.ts
  tests/cases/fourslash/jsxAttributeCompletionStyleAuto.ts
Labels: For Uncommitted Bug

#52016 Replace `missingType` with `undefinedType` in the `IndexedAccessTypeNode`'s type
  src/compiler/checker.ts
  tests/baselines/reference/typePredicateAcceptingPartialOfRefinedType.symbols
  tests/baselines/reference/typePredicateAcceptingPartialOfRefinedType.types
  tests/cases/compiler/typePredicateAcceptingPartialOfRefinedType.ts
Labels: For Milestone Bug

#52572 Fix completion of partial identifier inside a JsxExpression
  src/services/completions.ts
  src/testRunner/tests.ts
  tests/cases/fourslash/completionsJsxExpression.ts
Labels: For Backlog Bug

#52599 Make `emitModuleKindIsNonNodeESM` internal
  src/compiler/moduleNameResolver.ts
  src/compiler/utilities.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#52592 Improve handling of corner cases in `narrowTypeByInstanceof`
  src/compiler/checker.ts
  tests/baselines/reference/narrowByInstanceof.js
  tests/baselines/reference/narrowByInstanceof.symbols
  tests/baselines/reference/narrowByInstanceof.types
  tests/cases/compiler/narrowByInstanceof.ts
Labels: Author: Team, For Milestone Bug

#52422 Add cache to auto-import package.json filter
  src/compiler/moduleSpecifiers.ts
  src/services/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#52633 Filter out existing cases from string completions
  src/services/completions.ts
  src/services/stringCompletions.ts
  src/services/utilities.ts
  tests/cases/fourslash/switchCompletions.ts
Labels: For Backlog Bug

#52640 Don't consult JSDoc outside of JS in expando function assignment declarations
  src/compiler/checker.ts
  tests/baselines/reference/expandoFunctionContextualTypesJSDocInTs.js
  tests/baselines/reference/expandoFunctionContextualTypesJSDocInTs.symbols
  tests/baselines/reference/expandoFunctionContextualTypesJSDocInTs.types
  tests/cases/compiler/expandoFunctionContextualTypesJSDocInTs.ts
Labels: Author: Team, For Uncommitted Bug

#52583 Ensure projects are updated for find all references
  src/compiler/program.ts
  src/server/session.ts
  src/testRunner/tests.ts
  src/testRunner/unittests/services/findAllReferences.ts
  tests/baselines/reference/tsserver/findAllReferences/does-not-try-to-open-a-file-in-a-project-that-was-updated-and-no-longer-has-the-file.js
Labels: Author: Team, For Uncommitted Bug

#52059 Narrow references within optional chains in for-in loops
  src/compiler/checker.ts
  tests/baselines/reference/controlFlowOptionalChain.errors.txt
  tests/baselines/reference/controlFlowOptionalChain.js
  tests/baselines/reference/controlFlowOptionalChain.symbols
  tests/baselines/reference/controlFlowOptionalChain.types
  tests/cases/conformance/controlFlow/controlFlowOptionalChain.ts
Labels: For Backlog Bug

#52318 Fixed binding element types coming from the out of tuple bounds under `noUncheckedIndexedAccess`
  src/compiler/checker.ts
  tests/baselines/reference/destructureTupleWithVariableElement.errors.txt
  tests/baselines/reference/destructureTupleWithVariableElement.symbols
  tests/baselines/reference/destructureTupleWithVariableElement.types
  tests/cases/compiler/destructureTupleWithVariableElement.ts
Labels: For Backlog Bug

#50942 feat(48702): Emit for dynamic import (import()) when target >= ES2020 and module == None
  src/compiler/transformers/module/module.ts
  tests/baselines/reference/moduleNoneDynamicImport(target=es2015).js
  tests/baselines/reference/moduleNoneDynamicImport(target=es2015).symbols
  tests/baselines/reference/moduleNoneDynamicImport(target=es2015).types
  tests/baselines/reference/moduleNoneDynamicImport(target=es2020).js
  tests/baselines/reference/moduleNoneDynamicImport(target=es2020).symbols
  tests/baselines/reference/moduleNoneDynamicImport(target=es2020).types
  tests/cases/compiler/moduleNoneDynamicImport.ts
Labels: For Milestone Bug

#52683 Avoid caching duplicate export info from AutoImportProvider
  src/services/exportInfoMap.ts
  src/testRunner/unittests/tsserver/autoImportProvider.ts
Labels: Author: Team, For Uncommitted Bug

#52135 feat(52097): "Add missing properties" quick fix for calculated string values ...
  src/services/codefixes/fixAddMissingMember.ts
  tests/cases/fourslash/codeFixAddMissingProperties27.ts
Labels: For Backlog Bug

#52680 Exclude `typeof this` from check in `isConstantReference`
  src/compiler/checker.ts
  tests/baselines/reference/thisInTypeQuery.symbols
  tests/baselines/reference/thisInTypeQuery.types
  tests/cases/compiler/thisInTypeQuery.ts
Labels: Author: Team, For Milestone Bug

#52340 Fix accessing `toString` of features map
  src/compiler/checker.ts
  src/compiler/utilities.ts
  tests/baselines/reference/inexistentPropertyInsideToStringType.errors.txt
  tests/baselines/reference/inexistentPropertyInsideToStringType.symbols
  tests/baselines/reference/inexistentPropertyInsideToStringType.types
  tests/cases/compiler/inexistentPropertyInsideToStringType.ts
Labels: Author: Team, For Uncommitted Bug

#52668 Add test for already fixed issue 49778
  tests/baselines/reference/relatedViaDiscriminatedTypeNoError2.js
  tests/baselines/reference/relatedViaDiscriminatedTypeNoError2.symbols
  tests/baselines/reference/relatedViaDiscriminatedTypeNoError2.types
  tests/cases/compiler/relatedViaDiscriminatedTypeNoError2.ts
Labels: Author: Team, For Milestone Bug

#52667 Ensure we treat "type assertions" as JSX within a unary expression
  src/compiler/parser.ts
  tests/baselines/reference/parseUnaryExpressionNoTypeAssertionInJsx1.errors.txt
  tests/baselines/reference/parseUnaryExpressionNoTypeAssertionInJsx1.symbols
  tests/baselines/reference/parseUnaryExpressionNoTypeAssertionInJsx1.types
  tests/baselines/reference/parseUnaryExpressionNoTypeAssertionInJsx2.errors.txt
  tests/baselines/reference/parseUnaryExpressionNoTypeAssertionInJsx2.symbols
  tests/baselines/reference/parseUnaryExpressionNoTypeAssertionInJsx2.types
  tests/baselines/reference/parseUnaryExpressionNoTypeAssertionInJsx3.errors.txt
  tests/baselines/reference/parseUnaryExpressionNoTypeAssertionInJsx3.symbols
  tests/baselines/reference/parseUnaryExpressionNoTypeAssertionInJsx3.types
  tests/baselines/reference/parseUnaryExpressionNoTypeAssertionInJsx4.errors.txt
  tests/baselines/reference/parseUnaryExpressionNoTypeAssertionInJsx4.js
  tests/baselines/reference/parseUnaryExpressionNoTypeAssertionInJsx4.symbols
  tests/baselines/reference/parseUnaryExpressionNoTypeAssertionInJsx4.types
  tests/cases/compiler/parseUnaryExpressionNoTypeAssertionInJsx1.ts
  tests/cases/compiler/parseUnaryExpressionNoTypeAssertionInJsx2.ts
  tests/cases/compiler/parseUnaryExpressionNoTypeAssertionInJsx3.ts
  tests/cases/compiler/parseUnaryExpressionNoTypeAssertionInJsx4.ts
Labels: Author: Team, For Milestone Bug

#52699 Fix crash in union subtype reduction involving template literal and string mapping types
  src/compiler/checker.ts
  tests/baselines/reference/templateLiteralTypes3.errors.txt
  tests/baselines/reference/templateLiteralTypes3.js
  tests/baselines/reference/templateLiteralTypes3.symbols
  tests/baselines/reference/templateLiteralTypes3.types
  tests/cases/conformance/types/literal/templateLiteralTypes3.ts
Labels: Author: Team, For Milestone Bug

#52694 Fix crash on `addImportFromExportedSymbol` with default exported symbol
  src/services/utilities.ts
  tests/cases/fourslash/completionsOverridingMethodDefaultExported.ts
Labels: Author: Team, For Milestone Bug

#52611 Consult cached contextual types only when no contextFlags
  src/compiler/checker.ts
  tests/baselines/reference/contextualTypeCaching.symbols
  tests/baselines/reference/contextualTypeCaching.types
  tests/cases/compiler/contextualTypeCaching.ts
Labels: Author: Team, For Milestone Bug

#52686 Fix completion details auto-imports crashes
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/services/codefixes/importFixes.ts
  src/services/completions.ts
  src/services/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/importStatementCompletions3.baseline
  tests/baselines/reference/tsserver/moduleSpecifierCache/caches-module-specifiers-within-a-file.js
  tests/baselines/reference/tsserver/moduleSpecifierCache/invalidates-module-specifiers-when-changes-happen-in-contained-node_modules-directories.js
  tests/cases/fourslash/completionsImport_named_didNotExistBefore.ts
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/server/autoImportReExportFromAmbientModule.ts
Labels: Author: Team, For Milestone Bug

#52740 Fixed crash in `checkExportsOnMergedDeclarationsWorker`
  src/compiler/checker.ts
  tests/baselines/reference/conflictingDeclarationsImportFromNamespace1.errors.txt
  tests/baselines/reference/conflictingDeclarationsImportFromNamespace1.js
  tests/baselines/reference/conflictingDeclarationsImportFromNamespace1.symbols
  tests/baselines/reference/conflictingDeclarationsImportFromNamespace1.types
  tests/baselines/reference/conflictingDeclarationsImportFromNamespace2.errors.txt
  tests/baselines/reference/conflictingDeclarationsImportFromNamespace2.js
  tests/baselines/reference/conflictingDeclarationsImportFromNamespace2.symbols
  tests/baselines/reference/conflictingDeclarationsImportFromNamespace2.types
  tests/cases/compiler/conflictingDeclarationsImportFromNamespace1.ts
  tests/cases/compiler/conflictingDeclarationsImportFromNamespace2.ts
Labels: For Backlog Bug

#52606 Drop `deferredNodes` after checking them all.
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug

#52696 Fix spurious circularity caused by removeOptionalityFromDeclaredType, cache result
  src/compiler/checker.ts
  src/compiler/types.ts
  src/testRunner/unittests/tsserver/inconsistentErrorInEditor.ts
  tests/baselines/reference/tsserver/inconsistentErrorInEditor2/should-not-error.js
Labels: Author: Team, For Milestone Bug

#52734 Don't allow everything to be assignable to string within string mappings like Uppercase/Lowercase
  src/compiler/checker.ts
  tests/baselines/reference/stringMappingAssignability.errors.txt
  tests/baselines/reference/stringMappingAssignability.js
  tests/baselines/reference/stringMappingAssignability.symbols
  tests/baselines/reference/stringMappingAssignability.types
  tests/cases/compiler/stringMappingAssignability.ts
Labels: Author: Team, For Milestone Bug

#52746 Replace all instances of `compilerOptions.isolatedModules` with function considering `verbatimModuleSyntax`
  src/compiler/builder.ts
  src/compiler/builderState.ts
  src/compiler/program.ts
  src/compiler/transformers/module/esnextAnd2015.ts
  src/compiler/transformers/ts.ts
  src/compiler/utilities.ts
  src/services/codefixes/fixImportNonExportedMember.ts
  src/services/codefixes/importFixes.ts
  tests/baselines/reference/verbatimModuleSyntaxConstEnum.js
  tests/baselines/reference/verbatimModuleSyntaxConstEnum.symbols
  tests/baselines/reference/verbatimModuleSyntaxConstEnum.types
  tests/cases/conformance/externalModules/verbatimModuleSyntaxConstEnum.ts
Labels: Author: Team, For Milestone Bug

#52648 Check conditional types in depth in `isTypeParameterAtTopLevel`
  src/compiler/checker.ts
  tests/baselines/reference/wideningWithTopLevelTypeParameter.symbols
  tests/baselines/reference/wideningWithTopLevelTypeParameter.types
  tests/cases/compiler/wideningWithTopLevelTypeParameter.ts
Labels: Author: Team, For Milestone Bug

#52679 Avoid caching resolved signatures for language service requests like signature help
  src/compiler/checker.ts
  tests/cases/fourslash/arityErrorAfterSignatureHelp.ts
  tests/cases/fourslash/arityErrorAfterStringCompletions.ts
Labels: For Milestone Bug

#52747 Prefer top-level type-only imports in verbatimModuleSyntax
  src/services/codefixes/importFixes.ts
  tests/cases/fourslash/autoImportTypeOnlyPreferred1.ts
Labels: Author: Team, For Uncommitted Bug

#52196 fix property completion in unions of object types and template literal types
  src/compiler/types.ts
  tests/cases/fourslash/completionsObjectLiteralUnionTemplateLiteralType.ts
Labels: For Backlog Bug

#52138 fix(52061): Constructor parameters exported as type included in emitted metadata
  src/compiler/checker.ts
  tests/baselines/reference/decoratorMetadataTypeOnlyExport.js
  tests/baselines/reference/decoratorMetadataTypeOnlyExport.symbols
  tests/baselines/reference/decoratorMetadataTypeOnlyExport.types
  tests/cases/compiler/decoratorMetadataTypeOnlyExport.ts
Labels: For Backlog Bug

#52282 Improvements to `strictSubtypeRelation` and `getNarrowedType`
  src/compiler/checker.ts
  tests/baselines/reference/controlFlowBinaryOrExpression.symbols
  tests/baselines/reference/controlFlowBinaryOrExpression.types
  tests/baselines/reference/controlFlowFavorAssertedTypeThroughTypePredicate.types
  tests/baselines/reference/instanceofWithStructurallyIdenticalTypes.symbols
  tests/baselines/reference/instanceofWithStructurallyIdenticalTypes.types
  tests/baselines/reference/narrowingMutualSubtypes.js
  tests/baselines/reference/narrowingMutualSubtypes.symbols
  tests/baselines/reference/narrowingMutualSubtypes.types
  tests/baselines/reference/strictSubtypeAndNarrowing.errors.txt
  tests/baselines/reference/strictSubtypeAndNarrowing.js
  tests/baselines/reference/strictSubtypeAndNarrowing.symbols
  tests/baselines/reference/strictSubtypeAndNarrowing.types
  tests/baselines/reference/typePredicateStructuralMatch.symbols
  tests/baselines/reference/unionWithIndexSignature.types
  tests/cases/compiler/narrowingMutualSubtypes.ts
  tests/cases/compiler/strictSubtypeAndNarrowing.ts
Labels: Author: Team, For Milestone Bug

#52762 fix(52761): overload tag is not supported in completions
  src/services/jsDoc.ts
  tests/cases/fourslash/jsdocOverloadTagCompletion.ts
Labels: For Milestone Bug

#52542 Widening and non-widening computed enum types
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/ambientDeclarations.types
  tests/baselines/reference/ambientEnum1.types
  tests/baselines/reference/ambientErrors.types
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/computedEnumTypeWidening.js
  tests/baselines/reference/computedEnumTypeWidening.symbols
  tests/baselines/reference/computedEnumTypeWidening.types
  tests/baselines/reference/declarationEmitForGlobalishSpecifierSymlink.types
  tests/baselines/reference/declarationEmitForGlobalishSpecifierSymlink2.types
  tests/baselines/reference/disallowLineTerminatorBeforeArrow.types
  tests/baselines/reference/enumBasics.types
  tests/baselines/reference/enumErrors.types
  tests/baselines/reference/enumMerging.types
  tests/baselines/reference/enumWithExport.types
  tests/baselines/reference/methodContainingLocalFunction.types
  tests/baselines/reference/moduleLocalImportNotIncorrectlyRedirected.types
  tests/baselines/reference/numericEnumMappedType.types
  tests/baselines/reference/this_inside-enum-should-not-be-allowed.types
  tests/cases/compiler/computedEnumTypeWidening.ts
Labels: Author: Team, For Milestone Bug

#52763 Enforce NLT restriction after 'accessor' keyword
  src/compiler/parser.ts
  tests/baselines/reference/autoAccessor11.errors.txt
  tests/baselines/reference/autoAccessor11.js
  tests/baselines/reference/autoAccessor11.symbols
  tests/baselines/reference/autoAccessor11.types
  tests/cases/conformance/classes/propertyMemberDeclarations/autoAccessor11.ts
Labels: Author: Team, For Milestone Bug

#52787 fix(52749): Assertion failure in derived class completion
  src/services/codefixes/helpers.ts
  tests/baselines/reference/completionsClassMembers4.baseline
  tests/cases/fourslash/completionsClassMembers4.ts
Labels: For Milestone Bug

#52703 Prefer using enum literal's own base type rather than enum's base type in comparison
  src/compiler/checker.ts
  tests/baselines/reference/comparisonOperatorWithNoRelationshipPrimitiveType.errors.txt
  tests/baselines/reference/comparisonOperatorWithNoRelationshipTypeParameter.errors.txt
  tests/baselines/reference/mixedTypeEnumComparison.js
  tests/baselines/reference/mixedTypeEnumComparison.symbols
  tests/baselines/reference/mixedTypeEnumComparison.types
  tests/cases/compiler/mixedTypeEnumComparison.ts
Labels: Author: Team, For Uncommitted Bug

#52677 Don't add redundant await in completions
  src/services/completions.ts
  tests/cases/fourslash/completionOfAwaitPromiseNoRedundant.ts
Labels: For Backlog Bug

#52785 Fix crash in private accessor emit
  src/compiler/transformers/classFields.ts
  tests/baselines/reference/autoAccessorNoUseDefineForClassFields.js
  tests/baselines/reference/autoAccessorNoUseDefineForClassFields.symbols
  tests/baselines/reference/autoAccessorNoUseDefineForClassFields.types
  tests/cases/conformance/classes/propertyMemberDeclarations/autoAccessorNoUseDefineForClassFields.ts
Labels: Author: Team, For Milestone Bug

#52803 Fix crash in extract type and generate get/set refactors
  src/compiler/checker.ts
  src/compiler/factory/utilities.ts
  src/compiler/parser.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/services/codefixes/generateAccessors.ts
  src/services/formatting/formatting.ts
  tests/cases/fourslash/refactorConvertToGetAccessAndSetAccessRemoveGrammarErrors1.ts
  tests/cases/fourslash/refactorExtractTypeRemoveGrammarError1.ts
  tests/cases/fourslash/refactorExtractTypeRemoveGrammarError2.ts
Labels: Author: Team, For Milestone Bug

#51650 Filtering mapped types declarations
  src/compiler/checker.ts
  tests/baselines/reference/findAllReferencesFilteringMappedTypeProperty.baseline.jsonc
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty.errors.txt
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty2.errors.txt
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty2.js
  tests/cases/fourslash/findAllReferencesFilteringMappedTypeProperty.ts
  tests/cases/fourslash/goToDefinition_filteringMappedType.ts
Labels: For Backlog Bug

#52474 Check overload tag against implementation
  src/compiler/checker.ts
  tests/baselines/reference/overloadTag1.errors.txt
  tests/baselines/reference/overloadTag1.js
  tests/baselines/reference/overloadTag1.symbols
  tests/baselines/reference/overloadTag1.types
  tests/cases/conformance/jsdoc/overloadTag1.ts
Labels: Author: Team, For Uncommitted Bug

#52728 Do not report errors when inference is partially blocked
  src/compiler/checker.ts
  tests/cases/fourslash/noErrorsAfterCompletionsRequestWithinGenericFunction1.ts
  tests/cases/fourslash/noErrorsAfterCompletionsRequestWithinGenericFunction2.ts
  tests/cases/fourslash/noErrorsAfterCompletionsRequestWithinGenericFunction3.ts
Labels: For Milestone Bug

#52814 Fix overloadTag2 test
  tests/baselines/reference/overloadTag2.errors.txt
Labels: Author: Team, For Uncommitted Bug

#52816 Fix crash in 'Wrap in JSX Fragment' quick fix
  src/services/formatting/formatting.ts
  tests/cases/fourslash/codeFixWrapJsxInFragmentWithGrammarError1.ts
  tests/cases/fourslash/refactorExtractTypeRemoveGrammarError2.ts
Labels: Author: Team, For Milestone Bug

#52741 Add an extra test case for inferring return type of generic class without a constructor
  tests/baselines/reference/inferringReturnTypeFromConstructSignatureGeneric.js
  tests/baselines/reference/inferringReturnTypeFromConstructSignatureGeneric.symbols
  tests/baselines/reference/inferringReturnTypeFromConstructSignatureGeneric.types
  tests/cases/compiler/inferringReturnTypeFromConstructSignatureGeneric.ts
Labels: For Backlog Bug

#52818 Don't parse out a name for JSX fragments
  src/compiler/parser.ts
  tests/baselines/reference/tsxFragmentErrors.errors.txt
  tests/baselines/reference/tsxFragmentErrors.js
  tests/baselines/reference/tsxFragmentErrors.types
  tests/cases/fourslash/jsxElementMissingOpeningTagNoCrash.ts
Labels: Author: Team, For Milestone Bug

#51214 fix(51202): Circular instantiation expression crashing IDEs
  src/compiler/checker.ts
  tests/baselines/reference/arrayTypeOfTypeOf.types
  tests/baselines/reference/circularInstantiationExpression.js
  tests/baselines/reference/circularInstantiationExpression.symbols
  tests/baselines/reference/circularInstantiationExpression.types
  tests/baselines/reference/expressionWithJSDocTypeArguments.types
  tests/baselines/reference/instantiationExpressions.types
  tests/baselines/reference/quickInfoCircularInstantiationExpression.baseline
  tests/baselines/reference/selfReferentialFunctionType.js
  tests/baselines/reference/selfReferentialFunctionType.symbols
  tests/baselines/reference/selfReferentialFunctionType.types
  tests/cases/compiler/circularInstantiationExpression.ts
  tests/cases/compiler/selfReferentialFunctionType.ts
  tests/cases/fourslash/quickInfoCircularInstantiationExpression.ts
Labels: For Milestone Bug

#49627 Ensure parameters are in scope when converting parameter/return types to type nodes
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/declarationEmitGlobalThisPreserved.js
  tests/baselines/reference/declarationEmitGlobalThisPreserved.symbols
  tests/baselines/reference/declarationEmitGlobalThisPreserved.types
  tests/baselines/reference/declarationsWithRecursiveInternalTypesProduceUniqueTypeParams.types
  tests/baselines/reference/genericTypeWithNonGenericBaseMisMatch.types
  tests/baselines/reference/parenthesizedContexualTyping2.types
  tests/baselines/reference/recursiveTypesWithTypeof.types
  tests/baselines/reference/taggedTemplateContextualTyping1.types
  tests/baselines/reference/taggedTemplateContextualTyping2.types
  tests/baselines/reference/targetTypeCastTest.types
  tests/baselines/reference/typeParametersInStaticMethods.types
  tests/baselines/reference/vardecl.types
  tests/cases/compiler/declarationEmitGlobalThisPreserved.ts
Labels: Author: Team, For Milestone Bug

#52832 Switch let/const to var in the scanner & parser for top-levelish variables.
  src/compiler/parser.ts
  src/compiler/scanner.ts
Labels: Author: Team, For Uncommitted Bug

#52673 fix(52664): Assertion failure on completions for derived class with computed base property name
  src/compiler/checker.ts
  src/compiler/types.ts
  src/services/completions.ts
  src/services/stringCompletions.ts
  tests/baselines/reference/completionsClassMembers5.baseline
  tests/cases/fourslash/completionsClassMembers5.ts
Labels: For Milestone Bug

#52769 Fix contextual typing for post-spread tuple elements
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/spreadsAndContextualTupleTypes.symbols
  tests/baselines/reference/spreadsAndContextualTupleTypes.types
  tests/baselines/reference/variadicTuples2.types
  tests/cases/compiler/spreadsAndContextualTupleTypes.ts
Labels: Author: Team, For Milestone Bug

#52854 fix(52852): "Move to a new file" refactoring does not maintain "import type" semantics
  src/services/refactors/moveToNewFile.ts
  tests/cases/fourslash/moveToNewFile_typeImport1.ts
  tests/cases/fourslash/moveToNewFile_typeImport2.ts
Labels: For Uncommitted Bug

#52890 Remove ts namespace import from checker
  src/compiler/checker.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/services/completions.ts
Labels: Author: Team, For Uncommitted Bug

#52881 Fixed crash in switch completions related to parenthesized expressions
  src/services/stringCompletions.ts
  src/services/utilities.ts
  tests/cases/fourslash/switchCompletions.ts
Labels: For Milestone Bug

#52848 Handle multiple levels of substitutions and indexed accesses in getActualTypeVariable
  src/compiler/checker.ts
  tests/baselines/reference/inferRestArgumentsMappedTuple.js
  tests/baselines/reference/inferRestArgumentsMappedTuple.symbols
  tests/baselines/reference/inferRestArgumentsMappedTuple.types
  tests/cases/compiler/inferRestArgumentsMappedTuple.ts
Labels: Author: Team, For Milestone Bug

#52824 Fix RWC tests with errors in tsconfig
  src/harness/harnessIO.ts
Labels: Author: Team, For Uncommitted Bug

#52861 Fix type import node circularity errors in eager diagnostic mode, deprecations
  src/compiler/checker.ts
  tests/baselines/reference/spuriousCircularityOnTypeImport.js
  tests/baselines/reference/spuriousCircularityOnTypeImport.symbols
  tests/baselines/reference/spuriousCircularityOnTypeImport.types
  tests/cases/compiler/spuriousCircularityOnTypeImport.ts
  tests/cases/fourslash/typeReferenceAndImportDeprecated.ts
Labels: Author: Team, For Backlog Bug

#52903 Switch to var in binder for top level variables
  src/compiler/binder.ts
Labels: Author: Team, For Uncommitted Bug

#52835 Swap closure state in the type-checker to `var` to avoid TDZ checks.
  src/compiler/checker.ts
  src/compiler/scanner.ts
Labels: Author: Team, For Uncommitted Bug

#52880 Don't emit binding pattern pattern / optional parameter error when an initializer is present
  src/compiler/checker.ts
  tests/baselines/reference/optionalBindingParameters4.symbols
  tests/baselines/reference/optionalBindingParameters4.types
  tests/cases/conformance/es6/destructuring/optionalBindingParameters4.ts
Labels: Author: Team, For Milestone Bug

#42566 Fix definition of `Array.prototype[Symbol.unscopables]`
  src/lib/es2015.symbol.wellknown.d.ts
  tests/baselines/reference/accessorsOverrideProperty9.symbols
  tests/baselines/reference/arrayFakeFlatNoCrashInferenceDeclarations.symbols
  tests/baselines/reference/arrayFind.symbols
  tests/baselines/reference/arrayFlatMap.symbols
  tests/baselines/reference/callWithSpread4.symbols
  tests/baselines/reference/intersectionTypeInference3.symbols
  tests/baselines/reference/keyofAndIndexedAccess2.symbols
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty.errors.txt
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty.types
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty2.js
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty2.types
  tests/baselines/reference/templateStringsArrayTypeRedefinedInES6Mode.errors.txt
Labels: For Uncommitted Bug

#52919 Fix debug assert for type assertions / JSX
  src/compiler/parser.ts
Labels: Author: Team, For Uncommitted Bug

#52904 Defer creation of node typings installer
  src/typingsInstaller/nodeTypingsInstaller.ts
Labels: Author: Team, For Uncommitted Bug

#52906 Switch to var in emitter, writer, printer
  src/compiler/emitter.ts
  src/compiler/sourcemap.ts
  src/compiler/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#52925 Add links to github above big var blocks
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/parser.ts
  src/compiler/scanner.ts
  src/compiler/sourcemap.ts
  src/compiler/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#52922 Fix emit for nested object rest in assignment pattern
  src/compiler/factory/nodeFactory.ts
  src/compiler/factory/utilities.ts
  src/compiler/transformers/es2018.ts
  tests/baselines/reference/nestedObjectRest.js
  tests/baselines/reference/nestedObjectRest.symbols
  tests/baselines/reference/nestedObjectRest.types
  tests/baselines/reference/privateWriteOnlyAccessorRead.js
  tests/cases/compiler/nestedObjectRest.ts
Labels: Author: Team, For Milestone Bug

#52875 Retry querying string completions from the inferred type if the original completions request doesn't return anything
  src/services/stringCompletions.ts
  tests/cases/fourslash/completionPreferredSuggestions1.ts
  tests/cases/fourslash/completionsLiteralFromInferenceWithinInferredType1.ts
  tests/cases/fourslash/completionsLiteralFromInferenceWithinInferredType2.ts
Labels: For Uncommitted Bug

#52920 Destructure common factory methods in the parser.
  src/compiler/parser.ts
Labels: Author: Team, For Uncommitted Bug

#52987 Remove unused eslint-disable directives
  scripts/build/utils.mjs
  src/compiler/program.ts
  src/compiler/sourcemap.ts
  src/compiler/sys.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/compiler/visitorPublic.ts
  src/harness/harnessLanguageService.ts
  src/harness/runnerbase.ts
  src/services/organizeImports.ts
  src/services/types.ts
  src/testRunner/parallel/host.ts
  src/testRunner/unittests/services/preProcessFile.ts
Labels: Author: Team, For Uncommitted Bug

#52957 Remove most direct uses of `factory` from `src/compilers/transformers`
  src/compiler/transformers/classFields.ts
  src/compiler/transformers/declarations.ts
  src/compiler/transformers/destructuring.ts
  src/compiler/transformers/taggedTemplate.ts
  src/compiler/transformers/typeSerializer.ts
Labels: Author: Team, For Uncommitted Bug

#52945 Run lint in parallel with runtests-parallel
  .github/workflows/ci.yml
  Herebyfile.mjs
  scripts/build/options.mjs
Labels: Author: Team, For Uncommitted Bug

#53015 Downgrade glob to v8 to fix build
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#53012 Omit intersection property check when source includes target
  src/compiler/checker.ts
  tests/baselines/reference/normalizedIntersectionTooComplex.errors.txt
Labels: Author: Team, For Milestone Bug

#53029 Remove createUnderscoreEscapedMultiMap
  src/compiler/checker.ts
  src/compiler/core.ts
Labels: Author: Team, For Uncommitted Bug

#52676 Exclude literal completions after closing quote and JSX attribute location
  src/services/completions.ts
  tests/cases/fourslash/completionsLiterals.ts
  tests/cases/fourslash/stringLiteralCompletionsInJsxAttributeInitializer.ts
Labels: For Backlog Bug

#50449 lib Fix Part 1/6 – WeakMap constructor
  src/lib/es2015.collection.d.ts
  tests/baselines/reference/mapConstructorOnReadonlyTuple.js
  tests/baselines/reference/mapConstructorOnReadonlyTuple.symbols
  tests/baselines/reference/mapConstructorOnReadonlyTuple.types
  tests/cases/compiler/mapConstructorOnReadonlyTuple.ts
Labels: For Milestone Bug
