Repository microsoft/TypeScript, pull requests merged in 2023-11, with the labels that each got.

#55746 Add 'not a request for a utility type' to the feature issue template
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: Author: Team, For Uncommitted Bug

#56277 Add more nodes for inlay hints
  src/services/inlayHints.ts
  tests/baselines/reference/inlayHintsInteractiveFunctionParameterTypes1.baseline
  tests/baselines/reference/inlayHintsInteractiveVariableTypes1.baseline
  tests/cases/fourslash/inlayHintsInteractiveFunctionParameterTypes1.ts
  tests/cases/fourslash/inlayHintsInteractiveVariableTypes1.ts
Labels: For Uncommitted Bug

#56295 Handle dts emit time errors for incremental scenarios and buildInfo
  src/compiler/builder.ts
  src/compiler/emitter.ts
  src/compiler/tsbuildPublic.ts
  src/testRunner/unittests/helpers/baseline.ts
  src/testRunner/unittests/helpers/tsc.ts
  src/testRunner/unittests/tsbuild/declarationEmit.ts
  src/testRunner/unittests/tsc/incremental.ts
  tests/baselines/reference/tsbuild/declarationEmit/reports-dts-generation-errors-with-incremental.js
  tests/baselines/reference/tsbuildWatch/programUpdates/reportErrors/declarationEmitErrors/introduceError/when-file-with-no-error-changes.js
  tests/baselines/reference/tsbuildWatch/programUpdates/reportErrors/declarationEmitErrors/introduceError/when-fixing-errors-only-changed-file-is-emitted.js
  tests/baselines/reference/tsbuildWatch/programUpdates/reportErrors/declarationEmitErrors/when-file-with-no-error-changes.js
  tests/baselines/reference/tsbuildWatch/programUpdates/reportErrors/declarationEmitErrors/when-fixing-error-files-all-files-are-emitted.js
  tests/baselines/reference/tsc/incremental/change-to-modifier-of-class-expression-field-with-declaration-emit-enabled.js
  tests/baselines/reference/tsc/incremental/change-to-modifier-of-class-expression-field.js
  tests/baselines/reference/tsc/incremental/reports-dts-generation-errors.js
Labels: Author: Team, For Uncommitted Bug

#56021 fix(55998): Ability to Place Open Brace On New Line For Try Catch Blocks
  src/services/formatting/rules.ts
  tests/cases/fourslash/formatIfTryCatchBlocks.ts
Labels: For Backlog Bug

#56048 Do not narrow using JSDoc type assertion nodes
  src/compiler/binder.ts
  tests/baselines/reference/parenthesizedJSDocCastDoesNotNarrow.errors.txt
  tests/baselines/reference/parenthesizedJSDocCastDoesNotNarrow.symbols
  tests/baselines/reference/parenthesizedJSDocCastDoesNotNarrow.types
  tests/cases/compiler/parenthesizedJSDocCastDoesNotNarrow.ts
Labels: For Uncommitted Bug

#56293 pass 'detached:true' for diff tool
  scripts/build/utils.mjs
Labels: Author: Team, For Uncommitted Bug

#56060 Make esbuild require hack look better in output
  Herebyfile.mjs
Labels: Author: Team, For Uncommitted Bug

#56296 Move complex parameter lists of async function into downlevel generator body
  src/compiler/checker.ts
  src/compiler/factory/emitHelpers.ts
  src/compiler/transformers/es2017.ts
  src/compiler/transformers/es2018.ts
  src/compiler/transformers/utilities.ts
  tests/baselines/reference/asyncArrowFunction6_es5.js
  tests/baselines/reference/asyncArrowFunction6_es6.js
  tests/baselines/reference/asyncArrowFunction7_es5.js
  tests/baselines/reference/asyncArrowFunction7_es6.js
  tests/baselines/reference/asyncArrowFunctionCapturesArguments_es5.js
  tests/baselines/reference/asyncArrowFunctionCapturesArguments_es6.js
  tests/baselines/reference/asyncArrowFunctionCapturesArguments_es6.symbols
  tests/baselines/reference/asyncArrowFunctionCapturesArguments_es6.types
  tests/baselines/reference/asyncFunctionDeclaration10_es5.js
  tests/baselines/reference/asyncFunctionDeclaration10_es6.js
  tests/baselines/reference/asyncFunctionDeclaration6_es5.js
  tests/baselines/reference/asyncFunctionDeclaration6_es6.js
  tests/baselines/reference/asyncFunctionDeclaration7_es5.js
  tests/baselines/reference/asyncFunctionDeclaration7_es6.js
  tests/baselines/reference/asyncFunctionDeclarationCapturesArguments_es5.js
  tests/baselines/reference/asyncFunctionDeclarationParameterEvaluation(target=es2015).errors.txt
  tests/baselines/reference/asyncFunctionDeclarationParameterEvaluation(target=es2015).js
  tests/baselines/reference/asyncFunctionDeclarationParameterEvaluation(target=es2017).errors.txt
  tests/baselines/reference/asyncFunctionDeclarationParameterEvaluation(target=es2017).js
  tests/baselines/reference/asyncGeneratorGenericNonWrappedReturn.symbols
  tests/baselines/reference/asyncGeneratorGenericNonWrappedReturn.types
  tests/baselines/reference/asyncGeneratorParameterEvaluation(target=es2015).errors.txt
  tests/baselines/reference/asyncGeneratorParameterEvaluation(target=es2015).js
  tests/baselines/reference/asyncGeneratorParameterEvaluation(target=es2017).errors.txt
  tests/baselines/reference/asyncGeneratorParameterEvaluation(target=es2017).js
  tests/baselines/reference/asyncGeneratorParameterEvaluation(target=es2018).errors.txt
  tests/baselines/reference/asyncGeneratorParameterEvaluation(target=es2018).js
  tests/baselines/reference/asyncUseStrict_es5.js
  tests/baselines/reference/asyncUseStrict_es6.js
  tests/baselines/reference/asyncWithVarShadowing_es6.js
  tests/baselines/reference/awaitUsingDeclarationsInForAwaitOf(target=es2015).js
  tests/baselines/reference/awaitUsingDeclarationsInForAwaitOf(target=es5).js
  tests/baselines/reference/classStaticBlock6.js
  tests/baselines/reference/emitter.forAwait(target=es2015).js
  tests/baselines/reference/emitter.forAwait(target=es5).js
  tests/baselines/reference/expressionsForbiddenInParameterInitializers.js
  tests/baselines/reference/jsDeclarationsNestedParams.js
  tests/baselines/reference/jsxElementType.js
  tests/baselines/reference/noImplicitReturnsInAsync1.js
  tests/baselines/reference/noImplicitReturnsInAsync2.js
  tests/baselines/reference/nullishCoalescingOperatorInAsyncGenerator(target=es2015).js
  tests/baselines/reference/nullishCoalescingOperatorInAsyncGenerator(target=es5).js
  tests/baselines/reference/operationsAvailableOnPromisedType.js
  tests/baselines/reference/reactReduxLikeDeferredInferenceAllowsAssignment.js
  tests/baselines/reference/superMethodCall.js
  tests/baselines/reference/usingDeclarationsInForAwaitOf(target=es2015).js
  tests/baselines/reference/usingDeclarationsInForAwaitOf(target=es5).js
  tests/cases/conformance/async/asyncFunctionDeclarationParameterEvaluation.ts
  tests/cases/conformance/async/es6/asyncArrowFunction/asyncArrowFunctionCapturesArguments_es6.ts
  tests/cases/conformance/asyncGenerators/asyncGeneratorGenericNonWrappedReturn.ts
  tests/cases/conformance/asyncGenerators/asyncGeneratorParameterEvaluation.ts
Labels: Author: Team, For Milestone Bug

#56088 Improve quick info display on properties belonging to all union contextual type members
  src/services/services.ts
  tests/cases/fourslash/quickInfoJsDocNonDiscriminatedUnionSharedProp.ts
Labels: For Backlog Bug

#56079 fix: add `Intl.getCanonicalLocales` type definition
  src/compiler/commandLineParser.ts
  src/lib/es2016.d.ts
  src/lib/es2016.intl.d.ts
  src/lib/libs.json
  tests/baselines/reference/DateTimeFormatAndNumberFormatES2021.symbols
  tests/baselines/reference/bigintWithLib.symbols
  tests/baselines/reference/config/commandLineParsing/parseCommandLine/Parse --lib option with extra comma.js
  tests/baselines/reference/config/commandLineParsing/parseCommandLine/Parse --lib option with trailing white-space.js
  tests/baselines/reference/config/commandLineParsing/parseCommandLine/Parse invalid option of library flags.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert empty string option of libs array to compiler-options with json api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert empty string option of libs array to compiler-options with jsonSourceFile api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert empty string option of libs to compiler-options with json api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert empty string option of libs to compiler-options with jsonSourceFile api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert incorrect option of libs to compiler-options with json api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert incorrect option of libs to compiler-options with jsonSourceFile api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert trailing-whitespace string option of libs to compiler-options with json api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert trailing-whitespace string option of libs to compiler-options with jsonSourceFile api.js
  tests/baselines/reference/es2016IntlAPIs.js
  tests/baselines/reference/es2016IntlAPIs.symbols
  tests/baselines/reference/es2016IntlAPIs.types
  tests/baselines/reference/es2018IntlAPIs.symbols
  tests/baselines/reference/es2020IntlAPIs.symbols
  tests/baselines/reference/es2022IntlAPIs.symbols
  tests/baselines/reference/formatToPartsBigInt.symbols
  tests/baselines/reference/formatToPartsFractionalSecond.symbols
  tests/baselines/reference/localesObjectArgument.symbols
  tests/baselines/reference/numberFormatCurrencySign.symbols
  tests/baselines/reference/numberFormatCurrencySignResolved.symbols
  tests/baselines/reference/tsc/runWithoutArgs/does-not-add-color-when-NO_COLOR-is-set.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped-when-host-can't-provide-terminal-width.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportProvider6.js
  tests/baselines/reference/tsserver/telemetry/does-not-expose-paths.js
  tests/baselines/reference/typesVersions.ambientModules.trace.json
  tests/baselines/reference/typesVersions.emptyTypes.trace.json
  tests/baselines/reference/typesVersions.justIndex.trace.json
  tests/baselines/reference/typesVersions.multiFile.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.ambient.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFile.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFileBackReferenceToSelf.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFileBackReferenceToUnmapped.trace.json
  tests/cases/conformance/es2016/es2016IntlAPIs.ts
Labels: For Uncommitted Bug

#56304 Deprecate ES3 in commandline parser
  src/compiler/commandLineParser.ts
  src/executeCommandLine/executeCommandLine.ts
  tests/baselines/reference/config/commandLineParsing/parseCommandLine/Parse empty options of --target.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert incorrect option of target to compiler-options with json api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert incorrect option of target to compiler-options with jsonSourceFile api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert tsconfig options when there are multiple invalid strings with jsonSourceFile api.js
  tests/baselines/reference/tsc/runWithoutArgs/does-not-add-color-when-NO_COLOR-is-set.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped-when-host-can't-provide-terminal-width.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
Labels: Author: Team, For Uncommitted Bug

#55926 Bail early in getNarrowedTypeWorker if type is candidate
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug

#56064 Ensure instantiation expressions have symbols, preventing crash in signature relations
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/aliasInstantiationExpressionGenericIntersectionNoCrash1.errors.txt
  tests/baselines/reference/aliasInstantiationExpressionGenericIntersectionNoCrash1.js
  tests/baselines/reference/aliasInstantiationExpressionGenericIntersectionNoCrash1.symbols
  tests/baselines/reference/aliasInstantiationExpressionGenericIntersectionNoCrash1.types
  tests/baselines/reference/aliasInstantiationExpressionGenericIntersectionNoCrash2.errors.txt
  tests/baselines/reference/aliasInstantiationExpressionGenericIntersectionNoCrash2.js
  tests/baselines/reference/aliasInstantiationExpressionGenericIntersectionNoCrash2.symbols
  tests/baselines/reference/aliasInstantiationExpressionGenericIntersectionNoCrash2.types
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/compiler/aliasInstantiationExpressionGenericIntersectionNoCrash1.ts
  tests/cases/compiler/aliasInstantiationExpressionGenericIntersectionNoCrash2.ts
Labels: Author: Team, For Milestone Bug

#56173 Add Support for Using Aliased Discriminants in Conditional Statements
  src/compiler/checker.ts
  tests/baselines/reference/controlFlowAliasedDiscriminants.errors.txt
  tests/baselines/reference/controlFlowAliasedDiscriminants.js
  tests/baselines/reference/controlFlowAliasedDiscriminants.symbols
  tests/baselines/reference/controlFlowAliasedDiscriminants.types
  tests/cases/compiler/controlFlowAliasedDiscriminants.ts
Labels: For Backlog Bug

#56355 If the project is orphan dont queue up TI reqquest
  src/server/project.ts
  tests/baselines/reference/tsserver/configFileSearch/tsconfig-for-the-file-does-not-exist.js
  tests/baselines/reference/tsserver/configFileSearch/tsconfig-for-the-file-exists.js
  tests/baselines/reference/tsserver/configuredProjects/Open-ref-of-configured-project-when-open-file-gets-added-to-the-project-as-part-of-configured-file-update-buts-its-open-file-references-are-all-closed-when-the-update-happens.js
  tests/baselines/reference/tsserver/configuredProjects/Open-ref-of-configured-project-when-open-file-gets-added-to-the-project-as-part-of-configured-file-update.js
  tests/baselines/reference/tsserver/configuredProjects/add-and-then-remove-a-config-file-in-a-folder-with-loose-files.js
  tests/baselines/reference/tsserver/configuredProjects/open-file-become-a-part-of-configured-project-if-it-is-referenced-from-root-file.js
  tests/baselines/reference/tsserver/configuredProjects/should-properly-handle-module-resolution-changes-in-config-file.js
  tests/baselines/reference/tsserver/inferredProjects/project-settings-for-inferred-projects.js
  tests/baselines/reference/tsserver/inferredProjects/when-existing-inferred-project-has-no-root-files.js
  tests/baselines/reference/tsserver/projects/changes-in-closed-files-are-reflected-in-project-structure.js
  tests/baselines/reference/tsserver/projects/correctly-migrate-files-between-projects.js
Labels: Author: Team, For Uncommitted Bug

#56356 Always update LS state through Project
  src/server/project.ts
  src/services/services.ts
  src/services/types.ts
  src/testRunner/unittests/tsserver/plugins.ts
  tests/baselines/reference/tsserver/plugins/when-plugins-use-LS-to-get-program-and-update-is-pending.js
Labels: Author: Team, For Uncommitted Bug

#56029 Autocomplete `from` keyword in export declarations
  src/services/completions.ts
  tests/cases/fourslash/completionExportFrom.ts
Labels: For Backlog Bug

#56358 Fixed narrowing in case clauses that follow other clauses that return
  src/compiler/binder.ts
  tests/baselines/reference/narrowingInCaseClauseAfterCaseClauseWithReturn.symbols
  tests/baselines/reference/narrowingInCaseClauseAfterCaseClauseWithReturn.types
  tests/cases/compiler/narrowingInCaseClauseAfterCaseClauseWithReturn.ts
Labels: For Milestone Bug

#56385 fix(56376): import type from from "foo"
  src/compiler/parser.ts
  tests/baselines/reference/importDefaultNamedType2.js
  tests/baselines/reference/importDefaultNamedType2.symbols
  tests/baselines/reference/importDefaultNamedType2.types
  tests/cases/conformance/externalModules/typeOnly/importDefaultNamedType2.ts
Labels: For Milestone Bug

#56408 Fixed a crash when getting document highlights on `out` variance annotation
  src/services/documentHighlights.ts
  tests/baselines/reference/documentHighlightVarianceModifiers.baseline.jsonc
  tests/cases/fourslash/documentHighlightVarianceModifiers.ts
Labels: For Uncommitted Bug

#56403 Handle fsWatch event with accesstime change on mac os
  src/compiler/sys.ts
  src/testRunner/unittests/helpers/virtualFileSystemWithWatch.ts
  src/testRunner/unittests/tscWatch/watchEnvironment.ts
  tests/baselines/reference/tscWatch/watchEnvironment/fsWatch/fsWatchWithTimestamp-false.js
  tests/baselines/reference/tscWatch/watchEnvironment/fsWatch/fsWatchWithTimestamp-true.js
Labels: Author: Team, For Uncommitted Bug

#56354 isolatedModules error on alias merging with local value
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/testRunner/compilerRunner.ts
  tests/baselines/reference/isolatedModulesSketchyAliasLocalMerge(isolatedmodules=false,verbatimmodulesyntax=true).errors.txt
  tests/baselines/reference/isolatedModulesSketchyAliasLocalMerge(isolatedmodules=true,verbatimmodulesyntax=false).errors.txt
  tests/baselines/reference/isolatedModulesSketchyAliasLocalMerge(isolatedmodules=true,verbatimmodulesyntax=true).errors.txt
  tests/cases/compiler/isolatedModulesSketchyAliasLocalMerge.ts
Labels: Breaking Change, Author: Team, For Milestone Bug

#56422 Revert "Disallow numeric literals with negative numbers (#55268)"
  src/compiler/checker.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/transformers/declarations.ts
  src/compiler/transformers/generators.ts
  src/compiler/transformers/ts.ts
  tests/baselines/reference/binaryIntegerLiteral.types
  tests/baselines/reference/binaryIntegerLiteralES6.types
  tests/baselines/reference/fakeInfinity1.errors.txt
  tests/baselines/reference/fakeInfinity1.js
  tests/baselines/reference/fakeInfinity1.symbols
  tests/baselines/reference/fakeInfinity1.types
  tests/baselines/reference/fakeInfinity2.js
  tests/baselines/reference/fakeInfinity2.symbols
  tests/baselines/reference/fakeInfinity2.types
  tests/baselines/reference/fakeInfinity3.js
  tests/baselines/reference/fakeInfinity3.symbols
  tests/baselines/reference/fakeInfinity3.types
  tests/baselines/reference/octalIntegerLiteral.types
  tests/baselines/reference/octalIntegerLiteralES6.types
  tests/cases/compiler/fakeInfinity1.ts
  tests/cases/compiler/fakeInfinity2.ts
  tests/cases/compiler/fakeInfinity3.ts
Labels: Author: Team, For Uncommitted Bug

#56257 Fixed a crash in completions on functionlike types
  src/compiler/checker.ts
  src/compiler/utilitiesPublic.ts
  tests/cases/fourslash/jsDocFunctionTypeCompletionsNoCrash.ts
Labels: For Uncommitted Bug

#56400 Fix crash when there are multiple packages to install per code fix action
  src/jsTyping/types.ts
  src/server/typingInstallerAdapter.ts
  src/testRunner/tests.ts
  src/testRunner/unittests/tsserver/codeFix.ts
  src/typingsInstallerCore/typingsInstaller.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/tsserver/codeFix/install-package-when-serialized.js
  tests/baselines/reference/tsserver/codeFix/install-package.js
Labels: Author: Team, For Milestone Bug

#56421 Track symbols per type thats cached and dont keep adding to them
  src/compiler/checker.ts
  tests/baselines/reference/trackedSymbolsNoCrash.js
  tests/baselines/reference/trackedSymbolsNoCrash.symbols
  tests/baselines/reference/trackedSymbolsNoCrash.types
  tests/cases/compiler/trackedSymbolsNoCrash.ts
Labels: Author: Team, For Uncommitted Bug

#55824 Remove a few unused scripts
  scripts/open-user-pr.mjs
  scripts/request-pr-review.mjs
  scripts/update-experimental-branches.mjs
Labels: Author: Team, For Uncommitted Bug

#56258 Fixed a crash when inferring return type of an accessor with errors in its return statement
  src/compiler/checker.ts
  tests/baselines/reference/accessorInferredReturnTypeErrorInReturnStatement.errors.txt
  tests/baselines/reference/accessorInferredReturnTypeErrorInReturnStatement.js
  tests/baselines/reference/accessorInferredReturnTypeErrorInReturnStatement.symbols
  tests/baselines/reference/accessorInferredReturnTypeErrorInReturnStatement.types
  tests/cases/compiler/accessorInferredReturnTypeErrorInReturnStatement.ts
Labels: For Uncommitted Bug

#53619 Filtered out types from import suggestions in JS files
  src/services/completions.ts
  src/testRunner/unittests/tsserver/completions.ts
  tests/baselines/reference/jsFileImportNoTypes.baseline
  tests/baselines/reference/tsserver/completions/works-when-files-are-included-from-two-different-drives-of-windows.js
  tests/cases/fourslash/importStatementCompletions_js.ts
  tests/cases/fourslash/importStatementCompletions_js2.ts
  tests/cases/fourslash/javascriptModulesTypeImport.ts
  tests/cases/fourslash/javascriptModulesTypeImportAsValue.ts
  tests/cases/fourslash/jsFileImportNoTypes.ts
Labels: For Backlog Bug

#55817 Remove SuppressedErrorConstructor's extends clause
  src/lib/esnext.disposable.d.ts
Labels: Author: Team, For Milestone Bug

#56226 fix(54268): Renaming JSDoc @param symbol only renames the first instance
  src/services/findAllReferences.ts
  tests/baselines/reference/renameJsDocTypeLiteral.baseline.jsonc
  tests/cases/fourslash/renameJsDocTypeLiteral.ts
Labels: For Backlog Bug

#56449 Elide re-exports of unresolved type-only imports
  src/compiler/checker.ts
  src/testRunner/unittests/services/transpile.ts
  tests/baselines/reference/transpile/Elides re-export of type-only import.js
  tests/baselines/reference/transpile/Elides re-export of type-only import.oldTranspile.js
Labels: Author: Team, For Milestone Bug

#56244 feat(55737): JSDoc {@link} support all 4 types of links
  src/services/utilities.ts
  tests/baselines/reference/quickInfoLink11.baseline
  tests/cases/fourslash/quickInfoLink11.ts
Labels: For Backlog Bug

#56451 Pick #56449 into release-5.3
  src/compiler/checker.ts
  src/testRunner/unittests/services/transpile.ts
  tests/baselines/reference/transpile/Elides re-export of type-only import.js
  tests/baselines/reference/transpile/Elides re-export of type-only import.oldTranspile.js
Labels: Author: Team, For Uncommitted Bug

#55097 Error on export default of type: issue https://github.com/microsoft/TypeScript/issues/55087
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/exportDeclaration(isolatedmodules=false).errors.txt
  tests/baselines/reference/exportDeclaration(isolatedmodules=false).js
  tests/baselines/reference/exportDeclaration(isolatedmodules=false).symbols
  tests/baselines/reference/exportDeclaration(isolatedmodules=false).types
  tests/baselines/reference/exportDeclaration(isolatedmodules=true).errors.txt
  tests/baselines/reference/exportDeclaration(isolatedmodules=true).js
  tests/baselines/reference/exportDeclaration(isolatedmodules=true).symbols
  tests/baselines/reference/exportDeclaration(isolatedmodules=true).types
  tests/baselines/reference/exportDefault.js
  tests/baselines/reference/importEquals1.js
  tests/baselines/reference/isolatedModulesExportDeclarationType.errors.txt
  tests/baselines/reference/isolatedModulesExportDeclarationType.js
  tests/cases/compiler/isolatedModulesExportDeclarationType.ts
  tests/cases/conformance/externalModules/typeOnly/exportDeclaration.ts
Labels: For Uncommitted Bug

#55061 Skip invalid completion check immediately after newline
  src/services/completions.ts
  tests/cases/fourslash/completionAfterNewline.ts
  tests/cases/fourslash/completionAfterNewline2.ts
Labels: For Milestone Bug

#56438 Handle file name casing when deduplicating results from the project
  src/harness/fourslashImpl.ts
  src/server/session.ts
  src/services/utilities.ts
  src/testRunner/unittests/tsserver/rename.ts
  tests/baselines/reference/tsserver/rename/with-symlinks-and-case-difference.js
Labels: Author: Team, For Milestone Bug

#56207 Propagate `intersectionState` in `typeRelatedToSomeType`
  src/compiler/checker.ts
  tests/baselines/reference/nestedExcessPropertyChecking.errors.txt
  tests/baselines/reference/nestedExcessPropertyChecking.js
  tests/baselines/reference/nestedExcessPropertyChecking.symbols
  tests/baselines/reference/nestedExcessPropertyChecking.types
  tests/cases/compiler/nestedExcessPropertyChecking.ts
Labels: Author: Team, For Uncommitted Bug

#56280 Only call `getLowerBoundOfKeyType` on non-generic mapped types
  src/compiler/checker.ts
  tests/baselines/reference/circularMappedTypeConstraint.symbols
  tests/baselines/reference/circularMappedTypeConstraint.types
  tests/cases/compiler/circularMappedTypeConstraint.ts
Labels: Author: Team, For Milestone Bug

#56004 Improve constraints of conditional types applied to constrained type variables
  src/compiler/checker.ts
  tests/baselines/reference/circularlyConstrainedMappedTypeContainingConditionalNoInfiniteInstantiationDepth.errors.txt
  tests/baselines/reference/conditionalTypes1.errors.txt
  tests/baselines/reference/conditionalTypes2.errors.txt
  tests/baselines/reference/distributiveConditionalTypeConstraints.errors.txt
  tests/baselines/reference/distributiveConditionalTypeConstraints.symbols
  tests/baselines/reference/distributiveConditionalTypeConstraints.types
  tests/baselines/reference/flatArrayNoExcessiveStackDepth.errors.txt
  tests/baselines/reference/flatArrayNoExcessiveStackDepth.types
  tests/baselines/reference/genericConditionalConstrainedToUnknownNotAssignableToConcreteObject.errors.txt
  tests/baselines/reference/keyofAndIndexedAccessErrors.errors.txt
  tests/baselines/reference/reactReduxLikeDeferredInferenceAllowsAssignment.errors.txt
  tests/cases/compiler/distributiveConditionalTypeConstraints.ts
Labels: Author: Team, For Milestone Bug

#56434 Fix support for intersections in template literal placeholder types
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/templateLiteralTypesPatterns.errors.txt
  tests/baselines/reference/templateLiteralTypesPatterns.js
  tests/baselines/reference/templateLiteralTypesPatterns.symbols
  tests/baselines/reference/templateLiteralTypesPatterns.types
  tests/cases/conformance/types/literal/templateLiteralTypesPatterns.ts
  tests/cases/fourslash/stringLiteralCompletionsForOpenEndedTemplateLiteralType.ts
Labels: Author: Team, For Milestone Bug

#56489 Make our dts files compile when exactOptionalPropertyTypes is enabled downstream
  src/compiler/types.ts
  src/server/project.ts
  src/services/types.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/compiler/APILibCheck.ts
Labels: Author: Team, For Uncommitted Bug

#56486 Pick #56485 into release-5.3
  src/compiler/types.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#56490 Cherry-pick #56489 into release-5.3
  src/compiler/types.ts
  src/server/project.ts
  src/services/types.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/compiler/APILibCheck.ts
Labels: Author: Team, For Uncommitted Bug

#56485 Make AssertEntry and AssertClause interfaces
  src/compiler/types.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#56347 Avoid incorrect narrowings using const variables from binding elemens with literal initializers
  src/compiler/checker.ts
  tests/baselines/reference/avoidNarrowingUsingConstVariableFromBindingElementWithLiteralInitializer.symbols
  tests/baselines/reference/avoidNarrowingUsingConstVariableFromBindingElementWithLiteralInitializer.types
  tests/cases/compiler/avoidNarrowingUsingConstVariableFromBindingElementWithLiteralInitializer.ts
Labels: For Backlog Bug

#56439 When reparsing top level await dont set original node for the new source file
  src/compiler/factory/nodeFactory.ts
  src/compiler/parser.ts
  tests/baselines/reference/dynamicImportsDeclaration.js
  tests/baselines/reference/dynamicImportsDeclaration.symbols
  tests/baselines/reference/dynamicImportsDeclaration.types
  tests/cases/compiler/dynamicImportsDeclaration.ts
Labels: Author: Team, For Milestone Bug

#56368 fix(47327): Inlay Hint for TypeScript broken for spread operation
  tests/baselines/reference/inlayHintsInteractiveRestParameters3.baseline
  tests/cases/fourslash/inlayHintsInteractiveRestParameters3.ts
Labels: For Backlog Bug

#56493 Add a new cherry-pick GHA workflow
  .github/workflows/create-cherry-pick-pr.yml
Labels: Author: Team, For Uncommitted Bug

#56494 Fix branch name in new cherry pick workflow
  .github/workflows/create-cherry-pick-pr.yml
Labels: Author: Team, For Uncommitted Bug

#56495 Add git user info to cherry-pick task
  .github/workflows/create-cherry-pick-pr.yml
Labels: Author: Team, For Uncommitted Bug

#56498 Remove open-cherry-pick-pr.mjs
  scripts/open-cherry-pick-pr.mjs
Labels: Author: Team, For Uncommitted Bug

#56499 Fix repository_dispatch syntax
  .github/workflows/new-release-branch.yaml
  .github/workflows/nightly.yaml
  .github/workflows/set-version.yaml
  .github/workflows/sync-branch.yaml
  .github/workflows/twoslash-repros.yaml
Labels: Author: Team, For Uncommitted Bug

#56510 Fix cherry-pick job for unmerged PRs
  .github/workflows/create-cherry-pick-pr.yml
Labels: Author: Team, For Uncommitted Bug

#56511 Fix typo in cherry-pick job
  .github/workflows/create-cherry-pick-pr.yml
Labels: Author: Team, For Uncommitted Bug

#56504 Fixed an issue in boolean comparison narrowing when the reference is an optional chain
  src/compiler/checker.ts
  tests/baselines/reference/controlFlowOptionalChain3.errors.txt
  tests/baselines/reference/controlFlowOptionalChain3.symbols
  tests/baselines/reference/controlFlowOptionalChain3.types
  tests/cases/conformance/controlFlow/controlFlowOptionalChain3.tsx
Labels: For Milestone Bug

#55794 Fixed const reverse mapped types themselves to be treated as const
  src/compiler/checker.ts
  tests/baselines/reference/typeParameterConstModifiers.types
  tests/baselines/reference/typeParameterConstModifiersReverseMappedTypes.symbols
  tests/baselines/reference/typeParameterConstModifiersReverseMappedTypes.types
  tests/cases/conformance/types/typeParameters/typeParameterLists/typeParameterConstModifiersReverseMappedTypes.ts
Labels: For Uncommitted Bug

#56488 Handle package json watch life time
  src/server/editorServices.ts
  src/server/moduleSpecifierCache.ts
  src/server/packageJsonCache.ts
  src/server/project.ts
  src/testRunner/unittests/tsserver/packageJsonInfo.ts
  tests/baselines/reference/tsserver/autoImportProvider/Closes-AutoImportProviderProject-when-host-project-closes.js
  tests/baselines/reference/tsserver/autoImportProvider/Does-not-schedule-ensureProjectForOpenFiles-on-AutoImportProviderProject-creation.js
  tests/baselines/reference/tsserver/autoImportProvider/Responds-to-manual-changes-in-node_modules.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportProvider_globalTypingsCache.js
  tests/baselines/reference/tsserver/packageJsonInfo/detects-new-package.json-files-that-are-added,-caches-them,-and-watches-them.js
  tests/baselines/reference/tsserver/packageJsonInfo/finds-multiple-package.json-files-when-present.js
  tests/baselines/reference/tsserver/packageJsonInfo/finds-package.json-on-demand,-watches-for-deletion,-and-removes-them-from-cache.js
  tests/baselines/reference/tsserver/packageJsonInfo/handles-empty-package.json.js
  tests/baselines/reference/tsserver/packageJsonInfo/handles-errors-in-json-parsing-of-package.json.js
  tests/baselines/reference/tsserver/projects/loading-files-with-correct-priority.js
  tests/baselines/reference/tsserver/telemetry/even-for-project-with-ts-check-in-config.js
  tests/baselines/reference/tsserver/telemetry/sends-telemetry-for-file-sizes.js
  tests/baselines/reference/tsserver/telemetry/sends-telemetry-for-typeAcquisition-settings.js
  tests/baselines/reference/tsserver/typingsInstaller/configured-projects-discover-from-bower_components.js
  tests/baselines/reference/tsserver/typingsInstaller/discover-from-bower.js
  tests/baselines/reference/tsserver/typingsInstaller/discover-from-node_modules-empty-types-has-import.js
  tests/baselines/reference/tsserver/typingsInstaller/discover-from-node_modules-empty-types.js
  tests/baselines/reference/tsserver/typingsInstaller/discover-from-node_modules-explicit-types.js
  tests/baselines/reference/tsserver/typingsInstaller/discover-from-node_modules.js
  tests/baselines/reference/tsserver/typingsInstaller/multiple-projects.js
  tests/baselines/reference/tsserver/typingsInstaller/scoped-name-discovery.js
Labels: Author: Team, For Uncommitted Bug

#56568 fix(56567): import type from = require('foo') fails to parse
  src/compiler/parser.ts
  tests/baselines/reference/importDefaultNamedType3.js
  tests/baselines/reference/importDefaultNamedType3.symbols
  tests/baselines/reference/importDefaultNamedType3.types
  tests/cases/conformance/externalModules/typeOnly/importDefaultNamedType3.ts
Labels: For Milestone Bug

#56306 Fixed dependent variables narrowing when they are declared using nested binding patterns
  src/compiler/checker.ts
  tests/baselines/reference/dependentDestructuredVariablesFromNestedPatterns.symbols
  tests/baselines/reference/dependentDestructuredVariablesFromNestedPatterns.types
  tests/cases/conformance/controlFlow/dependentDestructuredVariablesFromNestedPatterns.ts
Labels: For Backlog Bug

#56309 fix inlay hints for template literal type
  src/compiler/utilities.ts
  src/services/inlayHints.ts
  tests/baselines/reference/inlayHintsInteractiveTemplateLiteralTypes.baseline
  tests/cases/fourslash/inlayHintsInteractiveTemplateLiteralTypes.ts
Labels: For Backlog Bug

#56338 fix(50303): Using @linkcode in combination with private methods causes TS1003 in JavaScript files.
  src/compiler/parser.ts
  tests/baselines/reference/jsdocLinkTag7.symbols
  tests/baselines/reference/jsdocLinkTag7.types
  tests/cases/conformance/jsdoc/jsdocLinkTag7.ts
Labels: For Backlog Bug

#56593 Add types for Promise.withResolvers()
  src/compiler/commandLineParser.ts
  src/lib/esnext.d.ts
  src/lib/esnext.promise.d.ts
  src/lib/libs.json
  tests/baselines/reference/promiseWithResolvers.js
  tests/baselines/reference/promiseWithResolvers.symbols
  tests/baselines/reference/promiseWithResolvers.types
  tests/baselines/reference/tsc/runWithoutArgs/does-not-add-color-when-NO_COLOR-is-set.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped-when-host-can't-provide-terminal-width.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
  tests/baselines/reference/typesVersions.ambientModules.trace.json
  tests/baselines/reference/typesVersions.emptyTypes.trace.json
  tests/baselines/reference/typesVersions.justIndex.trace.json
  tests/baselines/reference/typesVersions.multiFile.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.ambient.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFile.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFileBackReferenceToSelf.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFileBackReferenceToUnmapped.trace.json
  tests/cases/compiler/promiseWithResolvers.ts
Labels: For Milestone Bug

#52996 Consistently allow Locale objects in locale list params
  src/lib/es2018.intl.d.ts
  src/lib/es2020.intl.d.ts
  src/lib/es2020.string.d.ts
  src/lib/es2021.intl.d.ts
  src/lib/es2022.intl.d.ts
  src/lib/es5.d.ts
  tests/baselines/reference/DateTimeFormatAndNumberFormatES2021.symbols
  tests/baselines/reference/DateTimeFormatAndNumberFormatES2021.types
  tests/baselines/reference/bigintWithLib.types
  tests/baselines/reference/bigintWithoutLib.types
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2016Plus.types
  tests/baselines/reference/es2018IntlAPIs.symbols
  tests/baselines/reference/es2018IntlAPIs.types
  tests/baselines/reference/es2020IntlAPIs.types
  tests/baselines/reference/es2021LocalesObjectArgument.js
  tests/baselines/reference/es2021LocalesObjectArgument.symbols
  tests/baselines/reference/es2021LocalesObjectArgument.types
  tests/baselines/reference/es2022IntlAPIs.types
  tests/baselines/reference/es2022LocalesObjectArgument.js
  tests/baselines/reference/es2022LocalesObjectArgument.symbols
  tests/baselines/reference/es2022LocalesObjectArgument.types
  tests/baselines/reference/formatToPartsBigInt.types
  tests/baselines/reference/formatToPartsFractionalSecond.types
  tests/baselines/reference/localesObjectArgument.js
  tests/baselines/reference/localesObjectArgument.symbols
  tests/baselines/reference/localesObjectArgument.types
  tests/baselines/reference/numberFormatCurrencySign.types
  tests/baselines/reference/numberFormatCurrencySignResolved.types
  tests/cases/conformance/es2020/localesObjectArgument.ts
  tests/cases/conformance/es2021/es2021LocalesObjectArgument.ts
  tests/cases/conformance/es2022/es2022LocalesObjectArgument.ts
Labels: For Backlog Bug

#56580 Add inlay hints for IndexSignature
  src/services/inlayHints.ts
  tests/baselines/reference/inlayHintsInteractiveFunctionParameterTypes1.baseline
  tests/cases/fourslash/inlayHintsInteractiveFunctionParameterTypes1.ts
Labels: For Uncommitted Bug

#56552 Fixed symbol lookup for binding expando properties in blocks
  src/compiler/binder.ts
  tests/baselines/reference/expandoFunctionBlockShadowing.js
  tests/baselines/reference/expandoFunctionBlockShadowing.symbols
  tests/baselines/reference/expandoFunctionBlockShadowing.types
  tests/cases/compiler/expandoFunctionBlockShadowing.ts
Labels: For Uncommitted Bug

#56598 Consistently check assignability to template literal placeholders
  src/compiler/checker.ts
  tests/baselines/reference/templateLiteralTypes3.errors.txt
  tests/baselines/reference/templateLiteralTypes3.js
  tests/baselines/reference/templateLiteralTypes3.symbols
  tests/baselines/reference/templateLiteralTypes3.types
  tests/cases/conformance/types/literal/templateLiteralTypes3.ts
Labels: Author: Team, For Milestone Bug

#54443 Report arity errors on call target nodes
  src/compiler/checker.ts
  tests/baselines/reference/arityErrorRelatedSpanBindingPattern.errors.txt
  tests/baselines/reference/baseCheck.errors.txt
  tests/baselines/reference/blockScopedSameNameFunctionDeclarationES5.errors.txt
  tests/baselines/reference/blockScopedSameNameFunctionDeclarationES6.errors.txt
  tests/baselines/reference/blockScopedSameNameFunctionDeclarationStrictES5.errors.txt
  tests/baselines/reference/blockScopedSameNameFunctionDeclarationStrictES6.errors.txt
  tests/baselines/reference/callOverload.errors.txt
  tests/baselines/reference/callWithMissingVoid.errors.txt
  tests/baselines/reference/callWithMissingVoidUndefinedUnknownAnyInJs(strict=false).errors.txt
  tests/baselines/reference/callWithMissingVoidUndefinedUnknownAnyInJs(strict=true).errors.txt
  tests/baselines/reference/classCanExtendConstructorFunction.errors.txt
  tests/baselines/reference/derivedTypeCallingBaseImplWithOptionalParams.errors.txt
  tests/baselines/reference/es5DateAPIs.errors.txt
  tests/baselines/reference/functionCall11.errors.txt
  tests/baselines/reference/functionCall12.errors.txt
  tests/baselines/reference/functionCall13.errors.txt
  tests/baselines/reference/functionCall16.errors.txt
  tests/baselines/reference/functionCall17.errors.txt
  tests/baselines/reference/functionCall18.errors.txt
  tests/baselines/reference/functionCall6.errors.txt
  tests/baselines/reference/functionCall7.errors.txt
  tests/baselines/reference/functionOverloads29.errors.txt
  tests/baselines/reference/functionOverloads34.errors.txt
  tests/baselines/reference/functionOverloads37.errors.txt
  tests/baselines/reference/functionParameterArityMismatch.errors.txt
  tests/baselines/reference/genericFunctionsWithOptionalParameters2.errors.txt
  tests/baselines/reference/genericRestArity.errors.txt
  tests/baselines/reference/genericRestArityStrict.errors.txt
  tests/baselines/reference/genericRestParameters3.errors.txt
  tests/baselines/reference/iterableArrayPattern25.errors.txt
  tests/baselines/reference/jsFileFunctionParametersAsOptional2.errors.txt
  tests/baselines/reference/jsdocTypeTagRequiredParameters.errors.txt
  tests/baselines/reference/methodChainError.errors.txt
  tests/baselines/reference/moduleExportWithExportPropertyAssignment.errors.txt
  tests/baselines/reference/optionalParamArgsTest.errors.txt
  tests/baselines/reference/overload1.errors.txt
  tests/baselines/reference/overloadsAndTypeArgumentArityErrors.errors.txt
  tests/baselines/reference/privateNameMethod.errors.txt
  tests/baselines/reference/privateNameStaticMethod.errors.txt
  tests/baselines/reference/requiredInitializedParameter1.errors.txt
  tests/baselines/reference/restParamsWithNonRestParams.errors.txt
  tests/baselines/reference/simpleRecursionWithBaseCase1.errors.txt
  tests/baselines/reference/spreadOfParamsFromGeneratorMakesRequiredParams.errors.txt
  tests/baselines/reference/strictBindCallApply1.errors.txt
  tests/baselines/reference/templateLiteralsInTypes.errors.txt
  tests/baselines/reference/thisTypeInFunctionsNegative.errors.txt
  tests/baselines/reference/typeAssertionToGenericFunctionType.errors.txt
  tests/baselines/reference/unionTypeCallSignatures.errors.txt
  tests/baselines/reference/unionTypeCallSignatures4.errors.txt
  tests/baselines/reference/unionTypeReduction2.errors.txt
  tests/baselines/reference/variadicTuples1.errors.txt
  tests/cases/fourslash/arityErrorAfterSignatureHelp.ts
  tests/cases/fourslash/arityErrorAfterStringCompletions.ts
Labels: For Backlog Bug

#54447 Report more "No overload matches this call" errors on call target nodes
  src/compiler/checker.ts
  tests/baselines/reference/contextuallyTypedStringLiteralsInJsxAttributes02.errors.txt
  tests/baselines/reference/dissallowSymbolAsWeakType.errors.txt
  tests/baselines/reference/for-of39.errors.txt
  tests/baselines/reference/inheritedConstructorWithRestParams2.errors.txt
  tests/baselines/reference/iterableArrayPattern28.errors.txt
  tests/baselines/reference/jsxChildrenArrayWrongType.errors.txt
  tests/baselines/reference/jsxChildrenWrongType.errors.txt
  tests/baselines/reference/orderMattersForSignatureGroupIdentity.errors.txt
  tests/baselines/reference/overload1.errors.txt
  tests/baselines/reference/overloadTag1.errors.txt
  tests/baselines/reference/overloadresolutionWithConstraintCheckingDeferred.errors.txt
  tests/baselines/reference/overloadsWithProvisionalErrors.errors.txt
  tests/baselines/reference/specializedSignatureAsCallbackParameter1.errors.txt
  tests/baselines/reference/strictBindCallApply1.errors.txt
  tests/baselines/reference/tsxStatelessFunctionComponentOverload4.errors.txt
  tests/baselines/reference/tsxStatelessFunctionComponentOverload5.errors.txt
  tests/baselines/reference/tsxStatelessFunctionComponentsWithTypeArguments4.errors.txt
  tests/baselines/reference/underscoreTest1.errors.txt
Labels: For Uncommitted Bug

#54753 Avoid pulling object function property augmentations when resolving intersections' properties
  src/compiler/checker.ts
  tests/baselines/reference/intersectionIncludingPropFromGlobalAugmentation.symbols
  tests/baselines/reference/intersectionIncludingPropFromGlobalAugmentation.types
  tests/baselines/reference/intersectionWithConstructSignaturePrototypeResult.symbols
  tests/baselines/reference/intersectionWithConstructSignaturePrototypeResult.types
  tests/baselines/reference/mappedTypeAsClauses.types
  tests/baselines/reference/uncalledFunctionChecksInConditional2.errors.txt
  tests/baselines/reference/uncalledFunctionChecksInConditional2.js
  tests/baselines/reference/uncalledFunctionChecksInConditional2.symbols
  tests/baselines/reference/uncalledFunctionChecksInConditional2.types
  tests/cases/compiler/intersectionWithConstructSignaturePrototypeResult.ts
  tests/cases/compiler/uncalledFunctionChecksInConditional2.ts
  tests/cases/conformance/types/typeRelationships/assignmentCompatibility/intersectionIncludingPropFromGlobalAugmentation.ts
Labels: For Backlog Bug

#54477 Allow non-generic return types to be read from single generic call signatures
  src/compiler/checker.ts
  tests/baselines/reference/arrayFrom.types
  tests/baselines/reference/circularReferenceInReturnType.symbols
  tests/baselines/reference/circularReferenceInReturnType.types
  tests/baselines/reference/circularReferenceInReturnType2.symbols
  tests/baselines/reference/circularReferenceInReturnType2.types
  tests/cases/compiler/circularReferenceInReturnType.ts
  tests/cases/compiler/circularReferenceInReturnType2.ts
Labels: For Uncommitted Bug

#55447 Prefer non-partial signature match in non-generic case
  src/compiler/checker.ts
  tests/baselines/reference/unionTypeCallSignatures6.errors.txt
  tests/baselines/reference/unionTypeCallSignatures7.symbols
  tests/baselines/reference/unionTypeCallSignatures7.types
  tests/cases/conformance/types/union/unionTypeCallSignatures7.ts
Labels: For Backlog Bug

#55140 Defer index types on remapping mapped types
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypeAsClauses.errors.txt
  tests/baselines/reference/mappedTypeAsClauses.js
  tests/baselines/reference/mappedTypeAsClauses.symbols
  tests/baselines/reference/mappedTypeAsClauses.types
  tests/cases/conformance/types/mapped/mappedTypeAsClauses.ts
Labels: For Backlog Bug

#55811 Reverse mapped types with intersection constraint
  src/compiler/checker.ts
  tests/baselines/reference/reverseMappedTypeIntersectionConstraint.errors.txt
  tests/baselines/reference/reverseMappedTypeIntersectionConstraint.js
  tests/baselines/reference/reverseMappedTypeIntersectionConstraint.symbols
  tests/baselines/reference/reverseMappedTypeIntersectionConstraint.types
  tests/baselines/reference/reverseMappedTypeLimitedConstraint.errors.txt
  tests/baselines/reference/reverseMappedTypeLimitedConstraint.js
  tests/baselines/reference/reverseMappedTypeLimitedConstraint.symbols
  tests/baselines/reference/reverseMappedTypeLimitedConstraint.types
  tests/cases/compiler/reverseMappedTypeIntersectionConstraint.ts
  tests/cases/compiler/reverseMappedTypeLimitedConstraint.ts
Labels: For Backlog Bug

#54813 Defer processing of nested generic calls that return constructor types
  src/compiler/checker.ts
  tests/baselines/reference/inferenceGenericNestedCallReturningConstructor.symbols
  tests/baselines/reference/inferenceGenericNestedCallReturningConstructor.types
  tests/cases/compiler/inferenceGenericNestedCallReturningConstructor.ts
Labels: For Uncommitted Bug

#55565 String#matchAll should return iterable of RegExpExecArray (fixes #36788)
  src/lib/es2020.string.d.ts
  tests/baselines/reference/stringMatchAll.types
Labels: For Uncommitted Bug

#56617 Do not suggest lib.dom.d.ts
  .github/ISSUE_TEMPLATE/lib_change.yml
Labels: For Uncommitted Bug

#55941 Fixed an issue with reverse mapped types inference when single type variable is left after inferring from matching types
  src/compiler/checker.ts
  tests/baselines/reference/reverseMappedUnionInference.symbols
  tests/baselines/reference/reverseMappedUnionInference.types
  tests/cases/compiler/reverseMappedUnionInference.ts
Labels: For Uncommitted Bug
