Repository microsoft/TypeScript, pull requests merged in 2023-03, with the labels that each got.

#52103 Add the OpenSSF Scorecard GitHub Action
  .github/workflows/scorecard.yml
  README.md
Labels: For Backlog Bug

#52742 Add an extra test case for an aliased mapped type inference
  tests/baselines/reference/mappedTypeInferenceAliasSubstitution.symbols
  tests/baselines/reference/mappedTypeInferenceAliasSubstitution.types
  tests/cases/compiler/mappedTypeInferenceAliasSubstitution.ts
Labels: For Milestone Bug

#53032 Deprecate UnderscoreEscapedMap and remove internal uses
  src/compiler/checker.ts
  src/compiler/core.ts
  src/compiler/resolutionCache.ts
  src/compiler/sys.ts
  src/compiler/transformers/ts.ts
  src/compiler/transformers/utilities.ts
  src/compiler/types.ts
  src/harness/fourslashImpl.ts
  src/services/codeFixProvider.ts
  src/services/codefixes/convertToAsyncFunction.ts
  src/services/codefixes/convertToEsModule.ts
  src/services/codefixes/importFixes.ts
  src/services/codefixes/inferFromUsage.ts
  src/services/services.ts
  src/services/types.ts
  src/testRunner/unittests/tsserver/cachingFileSystemInformation.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#53026 Pin all of the deps besides @types/node and @octokit/rest
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#52133 Completely remove Push type
  src/compiler/commandLineParser.ts
  src/compiler/core.ts
  src/compiler/corePublic.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/moduleNameResolver.ts
  src/compiler/types.ts
  src/compiler/utilitiesPublic.ts
  src/services/classifier.ts
  src/services/codeFixProvider.ts
  src/services/documentHighlights.ts
  src/services/findAllReferences.ts
  src/services/navigateTo.ts
  src/services/outliningElementsCollector.ts
  src/services/services.ts
  src/services/suggestionDiagnostics.ts
Labels: Author: Team, For Uncommitted Bug

#52387 Fixed an issue with top function type being callable with no arguments
  src/compiler/checker.ts
  tests/baselines/reference/topFunctionTypeNotCallable.errors.txt
  tests/baselines/reference/topFunctionTypeNotCallable.symbols
  tests/baselines/reference/topFunctionTypeNotCallable.types
  tests/cases/compiler/topFunctionTypeNotCallable.ts
Labels: For Backlog Bug

#51430 convert JSDoc typedef to type, issue 50644
  src/compiler/diagnosticMessages.json
  src/services/_namespaces/ts.codefix.ts
  src/services/codefixes/convertTypedefToType.ts
  src/services/suggestionDiagnostics.ts
  tests/baselines/reference/tsserver/plugins/getSupportedCodeFixes-can-be-proxied.js
  tests/cases/fourslash/codeFixConvertTypedefToType1.ts
  tests/cases/fourslash/codeFixConvertTypedefToType2.ts
  tests/cases/fourslash/codeFixConvertTypedefToType3.ts
  tests/cases/fourslash/codeFixConvertTypedefToType4.ts
  tests/cases/fourslash/codeFixConvertTypedefToType5.ts
Labels: For Backlog Bug

#52960 Add tests for Awaited<null> and Awaited<undefined>
  tests/baselines/reference/awaitedType.errors.txt
  tests/baselines/reference/awaitedType.js
  tests/baselines/reference/awaitedType.symbols
  tests/baselines/reference/awaitedType.types
  tests/baselines/reference/awaitedTypeStrictNull.errors.txt
  tests/baselines/reference/awaitedTypeStrictNull.js
  tests/baselines/reference/awaitedTypeStrictNull.symbols
  tests/baselines/reference/awaitedTypeStrictNull.types
  tests/cases/compiler/awaitedType.ts
  tests/cases/compiler/awaitedTypeStrictNull.ts
Labels: Author: Team, For Uncommitted Bug

#53047 Also set javascript.unstable for organize imports in settings.json
  .vscode/settings.template.json
Labels: Author: Team, For Uncommitted Bug

#50816 Fixed false positive errors in empty optional binding patterns in declaration signatures
  src/compiler/checker.ts
  tests/baselines/reference/emptyOptionalBindingPatternInDeclarationSignature.symbols
  tests/baselines/reference/emptyOptionalBindingPatternInDeclarationSignature.types
  tests/cases/compiler/emptyOptionalBindingPatternInDeclarationSignature.ts
Labels: For Backlog Bug

#52347 Remove long deprecated occurrences request
  src/harness/client.ts
  src/harness/fourslashImpl.ts
  src/harness/harnessLanguageService.ts
  src/server/protocol.ts
  src/server/session.ts
  src/services/services.ts
  src/services/shims.ts
  src/services/types.ts
  src/testRunner/unittests/tsserver/cancellationToken.ts
  src/testRunner/unittests/tsserver/occurences.ts
  src/testRunner/unittests/tsserver/projects.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/tsserver/occurences/should-be-marked-if-only-on-string-values.js
  tests/baselines/reference/tsserver/projects/files-opened-and-closed-affecting-multiple-projects.js
Labels: Author: Team, For Uncommitted Bug

#52519 Use `missingType` instead of `undefinedType` for optional methods under `exactOptionalPropertyTypes`
  src/compiler/checker.ts
  tests/baselines/reference/stripMembersOptionality(exactoptionalpropertytypes=false).symbols
  tests/baselines/reference/stripMembersOptionality(exactoptionalpropertytypes=false).types
  tests/baselines/reference/stripMembersOptionality(exactoptionalpropertytypes=true).symbols
  tests/baselines/reference/stripMembersOptionality(exactoptionalpropertytypes=true).types
  tests/cases/compiler/stripMembersOptionality.ts
Labels: For Uncommitted Bug

#52565 fix(52444): "... is a type and must be imported using a type-only import ..." should have a quick fix
  src/services/codefixes/convertToTypeOnlyImport.ts
  tests/baselines/reference/tsserver/plugins/getSupportedCodeFixes-can-be-proxied.js
  tests/cases/fourslash/codeFixConvertToTypeOnlyImport1.ts
  tests/cases/fourslash/codeFixConvertToTypeOnlyImport2.ts
  tests/cases/fourslash/codeFixConvertToTypeOnlyImport3.ts
  tests/cases/fourslash/codeFixConvertToTypeOnlyImport4.ts
Labels: For Backlog Bug

#52106 Mark indexed access object type comparisons as unreliable
  src/compiler/checker.ts
  tests/baselines/reference/genericIndexedAccessVarianceComparisonResultCorrect.js
  tests/baselines/reference/genericIndexedAccessVarianceComparisonResultCorrect.symbols
  tests/baselines/reference/genericIndexedAccessVarianceComparisonResultCorrect.types
  tests/cases/compiler/genericIndexedAccessVarianceComparisonResultCorrect.ts
Labels: Author: Team, For Uncommitted Bug

#53052 Uncomment gitlens option in template
  .vscode/settings.template.json
Labels: Author: Team, For Uncommitted Bug

#52838 Fixed spreading iterables into arguments list directly into rest-only signatures
  src/compiler/checker.ts
  tests/baselines/reference/argumentsSpreadRestIterables(target=es5).errors.txt
  tests/baselines/reference/argumentsSpreadRestIterables(target=es5).symbols
  tests/baselines/reference/argumentsSpreadRestIterables(target=es5).types
  tests/baselines/reference/argumentsSpreadRestIterables(target=esnext).symbols
  tests/baselines/reference/argumentsSpreadRestIterables(target=esnext).types
  tests/cases/compiler/argumentsSpreadRestIterables.tsx
Labels: For Backlog Bug

#53055 Cherry-pick #52565 to release-5.0
  src/services/codefixes/convertToTypeOnlyImport.ts
  tests/baselines/reference/tsserver/plugins/getSupportedCodeFixes-can-be-proxied.js
  tests/cases/fourslash/codeFixConvertToTypeOnlyImport1.ts
  tests/cases/fourslash/codeFixConvertToTypeOnlyImport2.ts
  tests/cases/fourslash/codeFixConvertToTypeOnlyImport3.ts
  tests/cases/fourslash/codeFixConvertToTypeOnlyImport4.ts
Labels: Author: Team, For Uncommitted Bug

#53058 Remove perf_hooks patch needed for old versions of Node
  src/compiler/performanceCore.ts
Labels: Author: Team, For Uncommitted Bug

#53070 Make getSupportedCodeFixes plugin test such that we dont need to update its baseline for every new error
  src/services/codeFixProvider.ts
  src/testRunner/unittests/tsserver/helpers.ts
  src/testRunner/unittests/tsserver/plugins.ts
  tests/baselines/reference/tsserver/plugins/getSupportedCodeFixes-can-be-proxied.js
Labels: Author: Team, For Uncommitted Bug

#52709 Add tests for inferring contextual generic mapped types
  tests/baselines/reference/genericContextualTypes2.symbols
  tests/baselines/reference/genericContextualTypes2.types
  tests/baselines/reference/genericContextualTypes3.symbols
  tests/baselines/reference/genericContextualTypes3.types
  tests/cases/conformance/types/typeRelationships/typeInference/genericContextualTypes2.ts
  tests/cases/conformance/types/typeRelationships/typeInference/genericContextualTypes3.ts
Labels: For Uncommitted Bug

#53079 fix(53074): Functions with async keyword don't autocomplete
  src/services/completions.ts
  tests/cases/fourslash/completionsObjectLiteralMethod6.ts
Labels: For Backlog Bug

#52984 Check for strict subtypes and then regular subtypes in getNarrowedType
  src/compiler/checker.ts
  tests/baselines/reference/controlFlowFavorAssertedTypeThroughTypePredicate.errors.txt
  tests/baselines/reference/controlFlowFavorAssertedTypeThroughTypePredicate.types
  tests/baselines/reference/narrowingMutualSubtypes.types
  tests/baselines/reference/strictSubtypeAndNarrowing.errors.txt
  tests/baselines/reference/strictSubtypeAndNarrowing.js
  tests/baselines/reference/strictSubtypeAndNarrowing.symbols
  tests/baselines/reference/strictSubtypeAndNarrowing.types
  tests/cases/compiler/strictSubtypeAndNarrowing.ts
Labels: Author: Team, For Milestone Bug

#52982 feat(52883): Organize Imports doesn't treat exports the same way and merges groups
  src/services/organizeImports.ts
  tests/baselines/reference/organizeImports/TopLevelAndAmbientModule.exports.ts
  tests/cases/fourslash/organizeImports18.ts
  tests/cases/fourslash/organizeImports19.ts
  tests/cases/fourslash/organizeImports20.ts
Labels: For Backlog Bug

#53107 Mark binder as pure to tree shake in typingsInstaller
  src/compiler/binder.ts
Labels: Author: Team, For Uncommitted Bug

#53113 Add a test for an error on required JSX children when an empty JSX expression is used
  tests/baselines/reference/jsxEmptyExpressionNotCountedAsChild2.errors.txt
  tests/baselines/reference/jsxEmptyExpressionNotCountedAsChild2.symbols
  tests/baselines/reference/jsxEmptyExpressionNotCountedAsChild2.types
  tests/cases/compiler/jsxEmptyExpressionNotCountedAsChild2.tsx
Labels: For Milestone Bug

#53067 Add an extra test case for deferred conditional types
  tests/baselines/reference/deferredConditionalTypes.js
  tests/baselines/reference/deferredConditionalTypes.symbols
  tests/baselines/reference/deferredConditionalTypes.types
  tests/cases/compiler/deferredConditionalTypes.ts
Labels: For Milestone Bug

#52951 feat(52569): fixUnusedIdentifier: Unwanted side-effects when removing an unused destructuring declaration containing a function call
  src/services/codefixes/fixUnusedIdentifier.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_destructuring_elements7.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_destructuring_elements8.ts
Labels: For Backlog Bug

#52943 Report assignability errors on the return/yield keywords
  src/compiler/utilities.ts
  tests/baselines/reference/accessors_spec_section-4.5_error-cases.errors.txt
  tests/baselines/reference/asyncArrowFunction_allowJs.errors.txt
  tests/baselines/reference/baseConstraintOfDecorator.errors.txt
  tests/baselines/reference/checkJsdocReturnTag2.errors.txt
  tests/baselines/reference/checkJsdocTypeTag5.errors.txt
  tests/baselines/reference/checkJsdocTypeTagOnObjectProperty2.errors.txt
  tests/baselines/reference/complicatedIndexedAccessKeyofReliesOnKeyofNeverUpperBound.errors.txt
  tests/baselines/reference/conditionalTypeAssignabilityWhenDeferred.errors.txt
  tests/baselines/reference/constEnumPropertyAccess1.errors.txt
  tests/baselines/reference/constructorReturnsInvalidType.errors.txt
  tests/baselines/reference/constructorWithAssignableReturnExpression.errors.txt
  tests/baselines/reference/derivedGenericClassWithAny.errors.txt
  tests/baselines/reference/doNotElaborateAssignabilityToTypeParameters.errors.txt
  tests/baselines/reference/emptyObjectNotSubtypeOfIndexSignatureContainingObject1.errors.txt
  tests/baselines/reference/emptyObjectNotSubtypeOfIndexSignatureContainingObject2.errors.txt
  tests/baselines/reference/errorOnFunctionReturnType.errors.txt
  tests/baselines/reference/expressionsForbiddenInParameterInitializers.errors.txt
  tests/baselines/reference/generatorExplicitReturnType.errors.txt
  tests/baselines/reference/generatorReturnContextualType.errors.txt
  tests/baselines/reference/generatorReturnTypeInference.errors.txt
  tests/baselines/reference/generatorReturnTypeInferenceNonStrict.errors.txt
  tests/baselines/reference/getSetAccessorContextualTyping.errors.txt
  tests/baselines/reference/importHelpersNoHelpersForAsyncGenerators.errors.txt
  tests/baselines/reference/inferSetterParamType.errors.txt
  tests/baselines/reference/invalidReturnStatements.errors.txt
  tests/baselines/reference/keyofAndIndexedAccess2.errors.txt
  tests/baselines/reference/matchReturnTypeInAllBranches.errors.txt
  tests/baselines/reference/narrowByEquality.errors.txt
  tests/baselines/reference/neverTypeErrors1.errors.txt
  tests/baselines/reference/neverTypeErrors2.errors.txt
  tests/baselines/reference/noImplicitReturnsWithoutReturnExpression.errors.txt
  tests/baselines/reference/noUncheckedIndexedAccess.errors.txt
  tests/baselines/reference/nonPrimitiveInFunction.errors.txt
  tests/baselines/reference/numberToString.errors.txt
  tests/baselines/reference/objectLiteralErrors.errors.txt
  tests/baselines/reference/parseInvalidNullableTypes.errors.txt
  tests/baselines/reference/promiseEmptyTupleNoException.errors.txt
  tests/baselines/reference/propertyAccessOnTypeParameterWithConstraints5.errors.txt
  tests/baselines/reference/recursiveConditionalTypes.errors.txt
  tests/baselines/reference/recursiveFunctionTypes.errors.txt
  tests/baselines/reference/returnInConstructor1.errors.txt
  tests/baselines/reference/returnValueInSetter.errors.txt
  tests/baselines/reference/setterWithReturn.errors.txt
  tests/baselines/reference/symbolProperty47.errors.txt
  tests/baselines/reference/targetTypeVoidFunc.errors.txt
  tests/baselines/reference/typeGuardFunctionErrors.errors.txt
  tests/baselines/reference/typeParameterAssignmentCompat1.errors.txt
  tests/baselines/reference/typeParameterHasSelfAsConstraint.errors.txt
  tests/baselines/reference/unknownType1.errors.txt
  tests/baselines/reference/unknownType2.errors.txt
  tests/baselines/reference/yieldExpressionInControlFlow.errors.txt
  tests/baselines/reference/yieldExpressionInFlowLoop.errors.txt
Labels: For Backlog Bug

#53090 Add extra test cases for the `Awaited` type
  tests/baselines/reference/awaitedType.errors.txt
  tests/baselines/reference/awaitedType.js
  tests/baselines/reference/awaitedType.symbols
  tests/baselines/reference/awaitedType.types
  tests/cases/compiler/awaitedType.ts
Labels: For Milestone Bug

#53126 Pin dependencies in `release-5.0`
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#47932 Attach commit as `package.json#gitHead` in prerelease versions
  scripts/configurePrerelease.mjs
Labels: Housekeeping, For Uncommitted Bug

#52473 Expose getStringLiteralType and getNumberLiteralType on the TypeChecker, plus remove /** @internal */ from several useful methods.
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Uncommitted Bug

#53136 Fix script compile
  scripts/configurePrerelease.mjs
Labels: Author: Team, For Uncommitted Bug

#52974 Move to New File: Respect Quote Style in import updates
  src/services/refactors/moveToNewFile.ts
  tests/cases/fourslash/moveToNewFile_inferQuoteStyle.ts
Labels: For Backlog Bug

#52973 fix(52879): No autocompletions after the typeof keyword inside JSDoc comments.
  src/services/completions.ts
  tests/baselines/reference/jsFileJsdocTypedefTagTypeExpressionCompletion4.baseline
  tests/cases/fourslash/jsFileJsdocTypedefTagTypeExpressionCompletion4.ts
Labels: For Backlog Bug

#53139 Make ModuleResolutionKind.Node10 change backward-compatible
  src/compiler/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#52452 fix(52443): Regression: constructor accessor not allowed on plain objects
  src/compiler/checker.ts
  tests/baselines/reference/constructorNameInObjectLiteralAccessor.js
  tests/baselines/reference/constructorNameInObjectLiteralAccessor.symbols
  tests/baselines/reference/constructorNameInObjectLiteralAccessor.types
  tests/cases/conformance/salsa/constructorNameInObjectLiteralAccessor.ts
Labels: For Backlog Bug

#53125 Remove old test262 and dt runner infra
  .gitignore
  scripts/build/tests.mjs
  src/.eslintrc.json
  src/harness/harnessIO.ts
  src/harness/runnerbase.ts
  src/testRunner/_namespaces/Harness.ts
  src/testRunner/compilerRunner.ts
  src/testRunner/externalCompileRunner.ts
  src/testRunner/runner.ts
  src/testRunner/test262Runner.ts
  src/tsconfig-eslint.json
  tests/cases/test262-harness/helpers.d.ts
Labels: Author: Team, For Uncommitted Bug

#53078 Rename scanner token methods
  src/compiler/parser.ts
  src/compiler/scanner.ts
  src/compiler/utilities.ts
  src/harness/fourslashImpl.ts
  src/services/classifier.ts
  src/services/formatting/formatting.ts
  src/services/formatting/formattingScanner.ts
  src/services/organizeImports.ts
  src/services/preProcess.ts
  src/services/services.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#52782 Make special intersections order-independent
  src/compiler/checker.ts
  src/services/utilities.ts
  tests/baselines/reference/unknownControlFlow.errors.txt
  tests/baselines/reference/unknownControlFlow.js
  tests/baselines/reference/unknownControlFlow.symbols
  tests/baselines/reference/unknownControlFlow.types
  tests/cases/conformance/types/unknown/unknownControlFlow.ts
  tests/cases/fourslash/specialIntersectionsOrderIndependent.ts
Labels: For Backlog Bug

#52603 Skip derived override assignment declarations
  src/compiler/checker.ts
  tests/baselines/reference/inferringClassMembersFromAssignments3.symbols
  tests/baselines/reference/inferringClassMembersFromAssignments4.symbols
  tests/baselines/reference/thisPropertyAssignmentInherited.js
  tests/baselines/reference/thisPropertyAssignmentInherited.symbols
  tests/baselines/reference/thisPropertyAssignmentInherited.types
  tests/cases/conformance/salsa/thisPropertyAssignmentInherited.ts
Labels: Author: Team, For Milestone Bug

#53081 Scan bigger/fewer jsdoc tokens
  src/compiler/parser.ts
  src/compiler/scanner.ts
  src/compiler/types.ts
  src/testRunner/unittests/jsDocParsing.ts
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.Initial star space is not a tag.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.Single trailing whitespace.json
  tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.asteriskAfterPreamble.json
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#52767 Fix property completion in unions of object types and string mappings
  src/compiler/types.ts
  tests/cases/fourslash/completionsObjectLiteralUnionStringMappingType.ts
Labels: For Uncommitted Bug

#52717 Fix string completions depending on contextual signatures
  src/compiler/checker.ts
  tests/cases/fourslash/completionsForStringDependingOnContexSensitiveSignature.ts
Labels: For Uncommitted Bug

#53156 Fix smoke test failure due to bad git restore post-LKG-deletion
  .github/workflows/ci.yml
Labels: Author: Team, For Uncommitted Bug

#52427 check computed property names in overloads
  src/compiler/checker.ts
  tests/baselines/reference/overloadsWithComputedNames.errors.txt
  tests/baselines/reference/overloadsWithComputedNames.js
  tests/baselines/reference/overloadsWithComputedNames.symbols
  tests/baselines/reference/overloadsWithComputedNames.types
  tests/cases/compiler/overloadsWithComputedNames.ts
Labels: For Backlog Bug

#52537 Fix(49702): LS crash in binder for module in a JS file
  src/compiler/binder.ts
  tests/baselines/reference/moduleCrashInJSFile.errors.txt
  tests/baselines/reference/moduleCrashInJSFile.js
  tests/baselines/reference/moduleCrashInJSFile.symbols
  tests/baselines/reference/moduleCrashInJSFile.types
  tests/baselines/reference/thisAssignmentInNamespaceDeclaration1.errors.txt
  tests/baselines/reference/thisAssignmentInNamespaceDeclaration1.js
  tests/baselines/reference/thisAssignmentInNamespaceDeclaration1.symbols
  tests/baselines/reference/thisAssignmentInNamespaceDeclaration1.types
  tests/cases/compiler/thisAssignmentInNamespaceDeclaration1.ts
Labels: Author: Team, For Milestone Bug

#53100 Add an extra test for excess property check for intersection containing a recursive type
  tests/baselines/reference/excessPropertyCheckIntersectionWithRecursiveType.errors.txt
  tests/baselines/reference/excessPropertyCheckIntersectionWithRecursiveType.symbols
  tests/baselines/reference/excessPropertyCheckIntersectionWithRecursiveType.types
  tests/cases/compiler/excessPropertyCheckIntersectionWithRecursiveType.ts
Labels: For Milestone Bug

#52845 Fixed array expression spreads into variadic const calls
  src/compiler/checker.ts
  tests/baselines/reference/arraySpreadInCall.errors.txt
  tests/baselines/reference/arraySpreadInCall.symbols
  tests/baselines/reference/arraySpreadInCall.types
  tests/baselines/reference/callChain.types
  tests/baselines/reference/callWithSpread.types
  tests/baselines/reference/callWithSpreadES6.types
  tests/baselines/reference/functionParameterArityMismatch.errors.txt
  tests/baselines/reference/functionParameterArityMismatch.js
  tests/baselines/reference/functionParameterArityMismatch.symbols
  tests/baselines/reference/functionParameterArityMismatch.types
  tests/baselines/reference/importCallExpressionGrammarError.types
  tests/baselines/reference/iteratorSpreadInCall12.types
  tests/baselines/reference/iteratorSpreadInCall9.types
  tests/baselines/reference/keyofAndIndexedAccess.types
  tests/baselines/reference/newLexicalEnvironmentForConvertedLoop.types
  tests/baselines/reference/plainJSGrammarErrors.types
  tests/baselines/reference/trailingCommasInFunctionParametersAndArguments.types
  tests/baselines/reference/typeParameterConstModifiers.errors.txt
  tests/baselines/reference/typeParameterConstModifiers.js
  tests/baselines/reference/typeParameterConstModifiers.symbols
  tests/baselines/reference/typeParameterConstModifiers.types
  tests/cases/compiler/functionParameterArityMismatch.ts
  tests/cases/conformance/es6/spread/arraySpreadInCall.ts
  tests/cases/conformance/types/typeParameters/typeParameterLists/typeParameterConstModifiers.ts
Labels: For Backlog Bug

#53028 fix(53011): Illegal declaration file can be emitted (duplicate parameter names) when spreading tuples into parameter positions
  src/compiler/checker.ts
  tests/baselines/reference/spreadParameterTupleType.js
  tests/baselines/reference/spreadParameterTupleType.symbols
  tests/baselines/reference/spreadParameterTupleType.types
  tests/cases/compiler/spreadParameterTupleType.ts
Labels: For Backlog Bug

#53004 fix(52992): no add missing properties quick for nested object literal
  src/services/codefixes/fixAddMissingMember.ts
  tests/cases/fourslash/codeFixAddMissingProperties28.ts
Labels: For Backlog Bug

#53133 DOM update 2023-03-07
  src/lib/dom.generated.d.ts
  src/lib/dom.iterable.generated.d.ts
  src/lib/webworker.generated.d.ts
  src/lib/webworker.iterable.generated.d.ts
  tests/baselines/reference/globalThisBlockscopedProperties.types
  tests/baselines/reference/mappedTypeRecursiveInference.errors.txt
  tests/baselines/reference/mappedTypeRecursiveInference.types
  tests/baselines/reference/objectFromEntries.types
Labels: Author: Team, For Uncommitted Bug

#53184 Fix ThirdPartyNoticeText.txt encoding
  ThirdPartyNoticeText.txt
Labels: Author: Team, For Uncommitted Bug

#53183 Set package.json minimum to Node 12.20
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#53174 Remove old references to Node v4, small cleanup of node version stuff
  src/compiler/sys.ts
  src/tsserver/nodeServer.ts
  src/tsserver/server.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#53190 Fix build watch task in tasks.json post-LKG removal
  .vscode/tasks.json
Labels: Author: Team, For Uncommitted Bug

#52589 Filter out non-array types when contextually typing array literal elements
  src/compiler/checker.ts
  tests/baselines/reference/contextualSignatureInArrayElementPrefersArrayUnionMemberLibEs2015.symbols
  tests/baselines/reference/contextualSignatureInArrayElementPrefersArrayUnionMemberLibEs2015.types
  tests/baselines/reference/contextualSignatureInArrayElementPrefersArrayUnionMemberLibEs5.symbols
  tests/baselines/reference/contextualSignatureInArrayElementPrefersArrayUnionMemberLibEs5.types
  tests/baselines/reference/contextualTypeCaching.symbols
  tests/baselines/reference/contextualTypeCaching.types
  tests/cases/compiler/contextualSignatureInArrayElementPrefersArrayUnionMemberLibEs2015.ts
  tests/cases/compiler/contextualSignatureInArrayElementPrefersArrayUnionMemberLibEs5.ts
  tests/cases/compiler/contextualTypeCaching.ts
Labels: For Backlog Bug

#53176 Remove declares in sys, core, evaluatorImpl
  src/compiler/core.ts
  src/compiler/sys.ts
  src/harness/evaluatorImpl.ts
Labels: Author: Team, For Uncommitted Bug

#53166 When resolving type reference from custom typeRoot localtion use mangled scope name if the package is scoped name
  src/compiler/moduleNameResolver.ts
  tests/baselines/reference/moduleResolutionAsTypeReferenceDirectiveScoped.errors.txt
  tests/baselines/reference/moduleResolutionAsTypeReferenceDirectiveScoped.js
  tests/baselines/reference/moduleResolutionAsTypeReferenceDirectiveScoped.symbols
  tests/baselines/reference/moduleResolutionAsTypeReferenceDirectiveScoped.trace.json
  tests/baselines/reference/moduleResolutionAsTypeReferenceDirectiveScoped.types
  tests/baselines/reference/typeReferenceDirectiveScopedPackageCustomTypeRoot.errors.txt
  tests/baselines/reference/typeReferenceDirectiveScopedPackageCustomTypeRoot.js
  tests/baselines/reference/typeReferenceDirectiveScopedPackageCustomTypeRoot.symbols
  tests/baselines/reference/typeReferenceDirectiveScopedPackageCustomTypeRoot.trace.json
  tests/baselines/reference/typeReferenceDirectiveScopedPackageCustomTypeRoot.types
  tests/cases/compiler/moduleResolutionAsTypeReferenceDirectiveScoped.ts
  tests/cases/compiler/typeReferenceDirectiveScopedPackageCustomTypeRoot.ts
Labels: Author: Team, For Uncommitted Bug

#53209 Don't recommend installing typescript package globally in README
  README.md
Labels: Author: Team, For Uncommitted Bug

#53243 Bump TS devDep to 5.0 RC to fix eslint
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#53241 Add custom GHA report for package size
  .github/workflows/ci.yml
  Herebyfile.mjs
  scripts/build/utils.mjs
  scripts/checkPackageSize.mjs
Labels: Author: Team, For Uncommitted Bug

#53151 Test and LKG before push in dep bump
  .github/workflows/update-package-lock.yaml
Labels: Author: Team, For Uncommitted Bug

#53232 Add an extra test case for mapped type relationships
  tests/baselines/reference/mappedTypeRelationships.errors.txt
  tests/baselines/reference/mappedTypeRelationships.js
  tests/baselines/reference/mappedTypeRelationships.symbols
  tests/baselines/reference/mappedTypeRelationships.types
  tests/cases/conformance/types/mapped/mappedTypeRelationships.ts
Labels: For Milestone Bug

#53152 Enable corepack in CI
  .github/workflows/accept-baselines-fix-lints.yaml
  .github/workflows/ci.yml
  .github/workflows/new-release-branch.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release-branch-artifact.yaml
  .github/workflows/set-version.yaml
  .github/workflows/update-package-lock.yaml
Labels: Author: Team, For Uncommitted Bug

#53251 fix(53242): Wrong error message when defined abstract property in non-abstract class
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/abstractPropertyNegative.errors.txt
Labels: For Backlog Bug

#53098 Defer resolution of indexed access types with reducible object types
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/complicatedIndexedAccessKeyofReliesOnKeyofNeverUpperBound.errors.txt
  tests/baselines/reference/reducibleIndexedAccessTypes.symbols
  tests/baselines/reference/reducibleIndexedAccessTypes.types
  tests/cases/compiler/reducibleIndexedAccessTypes.ts
Labels: Author: Team, For Milestone Bug

#53245 Move smoke test package script into scripts
  .github/workflows/ci.yml
  package-lock.json
  package.json
  scripts/checkModuleFormat.mjs
Labels: Author: Team, For Uncommitted Bug

#52837 Add intra expression inference sites based on JSX attributes
  src/compiler/checker.ts
  tests/baselines/reference/intraExpressionInferencesJsx.symbols
  tests/baselines/reference/intraExpressionInferencesJsx.types
  tests/cases/conformance/types/typeRelationships/typeInference/intraExpressionInferencesJsx.tsx
Labels: For Backlog Bug

#53207 Fixed symbol declarations for generic filtering mapped types
  src/compiler/checker.ts
  tests/cases/fourslash/goToDefinition_filteringGenericMappedType.ts
Labels: For Uncommitted Bug

#52651 Do not resolve apparent type of mapped types with a tuple constraint
  src/compiler/checker.ts
  tests/baselines/reference/reverseMappedTypeContextualTypesPerElementOfTupleConstraint.symbols
  tests/baselines/reference/reverseMappedTypeContextualTypesPerElementOfTupleConstraint.types
  tests/cases/compiler/reverseMappedTypeContextualTypesPerElementOfTupleConstraint.ts
Labels: For Backlog Bug

#51136 Ensure moduleType is structured during cloneTypeAsModuleType
  src/compiler/checker.ts
  tests/baselines/reference/moduleExportNonStructured.js
  tests/baselines/reference/moduleExportNonStructured.symbols
  tests/baselines/reference/moduleExportNonStructured.types
  tests/cases/compiler/moduleExportNonStructured.ts
Labels: Author: Team, For Milestone Bug

#51580 Fixed an issue with spreading a spreadable generic expression into generic JSX
  src/compiler/checker.ts
  tests/baselines/reference/jsxGenericComponentWithSpreadingResultOfGenericFunction.symbols
  tests/baselines/reference/jsxGenericComponentWithSpreadingResultOfGenericFunction.types
  tests/cases/compiler/jsxGenericComponentWithSpreadingResultOfGenericFunction.tsx
Labels: For Uncommitted Bug

#53229 Make perfLogger potentially undefined rather than using a noop logger
  src/compiler/binder.ts
  src/compiler/moduleNameResolver.ts
  src/compiler/parser.ts
  src/compiler/perfLogger.ts
  src/compiler/sys.ts
  src/compiler/watchPublic.ts
  src/server/project.ts
  src/server/session.ts
  src/server/utilities.ts
  src/tsserver/nodeServer.ts
Labels: Author: Team, For Uncommitted Bug

#53283 Revert PR #51580
  src/compiler/checker.ts
  tests/baselines/reference/jsxGenericComponentWithSpreadingResultOfGenericFunction.symbols
  tests/baselines/reference/jsxGenericComponentWithSpreadingResultOfGenericFunction.types
  tests/cases/compiler/jsxGenericComponentWithSpreadingResultOfGenericFunction.tsx
Labels: Author: Team, For Uncommitted Bug

#53280 Revert PR #52589
  src/compiler/checker.ts
  tests/baselines/reference/contextualSignatureInArrayElementLibEs2015.errors.txt
  tests/baselines/reference/contextualSignatureInArrayElementLibEs2015.symbols
  tests/baselines/reference/contextualSignatureInArrayElementLibEs2015.types
  tests/baselines/reference/contextualSignatureInArrayElementLibEs5.errors.txt
  tests/baselines/reference/contextualSignatureInArrayElementLibEs5.symbols
  tests/baselines/reference/contextualSignatureInArrayElementLibEs5.types
  tests/baselines/reference/contextualSignatureInArrayElementPrefersArrayUnionMemberLibEs2015.symbols
  tests/baselines/reference/contextualSignatureInArrayElementPrefersArrayUnionMemberLibEs5.symbols
  tests/baselines/reference/inferringAnyFunctionType1.js
  tests/cases/compiler/contextualSignatureInArrayElementLibEs2015.ts
  tests/cases/compiler/contextualSignatureInArrayElementLibEs5.ts
  tests/cases/compiler/inferringAnyFunctionType1.ts
Labels: Author: Team, For Uncommitted Bug

#50487 Avoid bogus circularity error on context sensitive expando assingment
  src/compiler/checker.ts
  tests/baselines/reference/contextualReturnTypeOfIIFE2.js
  tests/baselines/reference/contextualReturnTypeOfIIFE2.symbols
  tests/baselines/reference/contextualReturnTypeOfIIFE2.types
  tests/baselines/reference/contextualReturnTypeOfIIFE3.js
  tests/baselines/reference/contextualReturnTypeOfIIFE3.symbols
  tests/baselines/reference/contextualReturnTypeOfIIFE3.types
  tests/cases/compiler/contextualReturnTypeOfIIFE2.ts
  tests/cases/compiler/contextualReturnTypeOfIIFE3.ts
Labels: For Backlog Bug

#53175 Fix esDecorators evaluation test on Node 16+
  src/testRunner/unittests/evaluation/esDecorators.ts
Labels: Author: Team, For Uncommitted Bug

#52609 Collect contravariant-only inference candidates from shorter annotated functions
  src/compiler/checker.ts
  tests/baselines/reference/contravariantOnlyInferenceFromAnnotatedFunction.symbols
  tests/baselines/reference/contravariantOnlyInferenceFromAnnotatedFunction.types
  tests/cases/compiler/contravariantOnlyInferenceFromAnnotatedFunction.ts
Labels: For Backlog Bug

#53117 Skip asking for jsdoc in checkObjectLiteral for enums in TS
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug

#53297 Set minimal workflow permissions
  .github/workflows/accept-baselines-fix-lints.yaml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/ensure-related-repos-run-crons.yml
  .github/workflows/error-deltas-watchdog.yaml
  .github/workflows/new-release-branch.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release-branch-artifact.yaml
  .github/workflows/rich-navigation.yml
  .github/workflows/set-version.yaml
  .github/workflows/sync-branch.yaml
  .github/workflows/sync-wiki.yml
  .github/workflows/twoslash-repros.yaml
  .github/workflows/update-lkg.yml
  .github/workflows/update-package-lock.yaml
Labels: For Uncommitted Bug

#52628 Add an extra test case related to return statements and annotated return types
  tests/baselines/reference/contextualTypingReturnStatementWithReturnTypeAnnotation.symbols
  tests/baselines/reference/contextualTypingReturnStatementWithReturnTypeAnnotation.types
  tests/cases/compiler/contextualTypingReturnStatementWithReturnTypeAnnotation.ts
Labels: For Uncommitted Bug

#53299 Bump TS devDep to ^5.0.2
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#53192 Fast path for negative case when relating to unions of primtives
  src/compiler/checker.ts
  src/compiler/types.ts
Labels: Author: Team, For Milestone Bug

#53092 Allow implicit return with explicit `undefined` return type
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/services/codefixes/returnValueCorrect.ts
  tests/baselines/reference/controlFlowGenericTypes.errors.txt
  tests/baselines/reference/functionsMissingReturnStatementsAndExpressions.errors.txt
  tests/baselines/reference/functionsMissingReturnStatementsAndExpressions.js
  tests/baselines/reference/functionsMissingReturnStatementsAndExpressions.symbols
  tests/baselines/reference/functionsMissingReturnStatementsAndExpressions.types
  tests/baselines/reference/functionsMissingReturnStatementsAndExpressionsStrictNullChecks.errors.txt
  tests/baselines/reference/functionsMissingReturnStatementsAndExpressionsStrictNullChecks.js
  tests/baselines/reference/functionsMissingReturnStatementsAndExpressionsStrictNullChecks.symbols
  tests/baselines/reference/functionsMissingReturnStatementsAndExpressionsStrictNullChecks.types
  tests/baselines/reference/jsdocFunction_missingReturn.errors.txt
  tests/baselines/reference/parseInvalidNonNullableTypes.errors.txt
  tests/baselines/reference/unknownType1.errors.txt
  tests/cases/compiler/functionsMissingReturnStatementsAndExpressions.ts
  tests/cases/compiler/functionsMissingReturnStatementsAndExpressionsStrictNullChecks.ts
  tests/cases/fourslash/codeFixCorrectReturnValue6.ts
Labels: For Uncommitted Bug

#53323 Disallow instantiation expressions on the right side of instanceof
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/instanceofOnInstantiationExpression.errors.txt
  tests/baselines/reference/instanceofOnInstantiationExpression.js
  tests/baselines/reference/instanceofOnInstantiationExpression.symbols
  tests/baselines/reference/instanceofOnInstantiationExpression.types
  tests/cases/compiler/instanceofOnInstantiationExpression.ts
Labels: Author: Team, For Uncommitted Bug

#53000 Fix missing reference in js (#50509)
  src/compiler/checker.ts
  tests/baselines/reference/findAllRefsJsThisPropertyAssignment.baseline.jsonc
  tests/cases/fourslash/findAllRefsJsThisPropertyAssignment.ts
Labels: For Backlog Bug

#53036 Improve contextual typing of ending tuple elements
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/contextualSignatureInArrayElementPrefersArrayUnionMemberLibEs2015.errors.txt
  tests/baselines/reference/contextualSignatureInArrayElementPrefersArrayUnionMemberLibEs5.errors.txt
  tests/baselines/reference/contextualTypeTupleEnd.errors.txt
  tests/baselines/reference/contextualTypeTupleEnd.symbols
  tests/baselines/reference/contextualTypeTupleEnd.types
  tests/baselines/reference/narrowingByTypeofInSwitch.types
  tests/baselines/reference/spreadsAndContextualTupleTypes.types
  tests/baselines/reference/variadicTuples1.errors.txt
  tests/baselines/reference/variadicTuples1.types
  tests/baselines/reference/variadicTuples2.errors.txt
  tests/cases/conformance/types/tuple/contextualTypeTupleEnd.ts
Labels: Author: Team, For Milestone Bug

#53246 Improve detection of type variables in instantiated object types
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug

#52836 Revert fix for intersections in template literals, fix differently
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/deeplyNestedTemplateLiteralIntersection.errors.txt
  tests/baselines/reference/templateLiteralIntersection.types
  tests/baselines/reference/templateLiteralIntersection2.errors.txt
  tests/baselines/reference/templateLiteralIntersection2.symbols
  tests/baselines/reference/templateLiteralIntersection2.types
  tests/baselines/reference/templateLiteralIntersection3.symbols
  tests/baselines/reference/templateLiteralIntersection3.types
  tests/cases/compiler/deeplyNestedTemplateLiteralIntersection.ts
  tests/cases/compiler/templateLiteralIntersection2.ts
  tests/cases/compiler/templateLiteralIntersection3.ts
Labels: Author: Team, For Uncommitted Bug

#53301 Rewrite getPropFromRaw slightly to surface T in the parameters
  src/compiler/commandLineParser.ts
Labels: For Uncommitted Bug

#53366 Revert PR #53301
  src/compiler/commandLineParser.ts
Labels: Author: Team, For Uncommitted Bug

#53365 Change ParamaterDecorator to allow an undefined propertyKey
  src/lib/decorators.legacy.d.ts
Labels: For Milestone Bug

#53336 Fix package-lock update task
  .github/workflows/update-package-lock.yaml
Labels: Author: Team, For Uncommitted Bug

#53335 Remove random code from fourslash test
  tests/cases/fourslash/codeFixUnreachableCode.ts
Labels: Author: Team, For Uncommitted Bug

#49226 Fixed issues with inference from nested tuple types of the same shape
  src/compiler/checker.ts
  tests/baselines/reference/inferFromNestedSameShapeTuple.symbols
  tests/baselines/reference/inferFromNestedSameShapeTuple.types
  tests/cases/compiler/inferFromNestedSameShapeTuple.ts
Labels: For Backlog Bug

#53331 Refactor config file parsing such that json and jsonSourceFile api use same paths
  src/compiler/commandLineParser.ts
  src/compiler/parser.ts
  src/compiler/types.ts
  tests/baselines/reference/config/tsconfigParsing/generates errors for when invalid comment type present in tsconfig with jsonSourceFile api.js
Labels: Author: Team, For Uncommitted Bug

#53385 Add missing ambient check to `verbatimModuleSyntax` `export =` error
  src/compiler/checker.ts
  tests/baselines/reference/verbatimModuleSyntaxDeclarationFile.symbols
  tests/baselines/reference/verbatimModuleSyntaxDeclarationFile.types
  tests/baselines/reference/verbatimModuleSyntaxNoElisionCJS.errors.txt
  tests/cases/conformance/externalModules/verbatimModuleSyntaxDeclarationFile.ts
Labels: Author: Team, For Milestone Bug

#53386 Fix crash when importsNotUsedAsValues is set alongside verbatimModuleSyntax
  src/compiler/checker.ts
  tests/baselines/reference/noCrashWithVerbatimModuleSyntaxAndImportsNotUsedAsValues.errors.txt
  tests/baselines/reference/noCrashWithVerbatimModuleSyntaxAndImportsNotUsedAsValues.js
  tests/baselines/reference/noCrashWithVerbatimModuleSyntaxAndImportsNotUsedAsValues.symbols
  tests/baselines/reference/noCrashWithVerbatimModuleSyntaxAndImportsNotUsedAsValues.types
  tests/cases/compiler/noCrashWithVerbatimModuleSyntaxAndImportsNotUsedAsValues.ts
Labels: Author: Team, For Milestone Bug

#53193 Consistently use '...args' for diagnostic args
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  src/compiler/parser.ts
  src/compiler/program.ts
  src/compiler/scanner.ts
  src/compiler/transformers/declarations.ts
  src/compiler/tsbuildPublic.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/compiler/watch.ts
  src/services/codeFixProvider.ts
  src/services/codefixes/fixImplicitThis.ts
  src/services/codefixes/fixUnusedIdentifier.ts
  src/services/codefixes/importFixes.ts
  src/services/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#53397 Report error if commanline only option is specified in tsconfig
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  src/testRunner/unittests/config/tsconfigParsing.ts
  tests/baselines/reference/config/tsconfigParsing/generates errors when commandline option is in tsconfig with json api.js
  tests/baselines/reference/config/tsconfigParsing/generates errors when commandline option is in tsconfig with jsonSourceFile api.js
  tests/baselines/reference/tsserver/telemetry/does-not-expose-paths.js
Labels: Author: Team, For Uncommitted Bug

#53383 Remove incorrect handling of intersections in getStringMappingType
  src/compiler/checker.ts
  tests/baselines/reference/templateLiteralIntersection3.types
  tests/baselines/reference/templateLiteralIntersection4.js
  tests/baselines/reference/templateLiteralIntersection4.symbols
  tests/baselines/reference/templateLiteralIntersection4.types
  tests/cases/compiler/templateLiteralIntersection4.ts
Labels: Author: Team, For Milestone Bug

#51884 Consider all union types matching discriminator for excess property checks
  src/compiler/checker.ts
  tests/baselines/reference/excessPropertyCheckWithMultipleDiscriminants.errors.txt
  tests/baselines/reference/excessPropertyCheckWithMultipleDiscriminants.js
  tests/baselines/reference/excessPropertyCheckWithMultipleDiscriminants.symbols
  tests/baselines/reference/excessPropertyCheckWithMultipleDiscriminants.types
  tests/baselines/reference/excessPropertyCheckWithUnions.errors.txt
  tests/baselines/reference/excessPropertyCheckWithUnions.js
  tests/baselines/reference/excessPropertyCheckWithUnions.symbols
  tests/baselines/reference/excessPropertyCheckWithUnions.types
  tests/baselines/reference/objectLiteralNormalization.errors.txt
  tests/cases/compiler/excessPropertyCheckWithMultipleDiscriminants.ts
  tests/cases/compiler/excessPropertyCheckWithUnions.ts
Labels: For Uncommitted Bug

#50903 Make function properties context-sensitive based on their return statements
  src/compiler/checker.ts
  tests/baselines/reference/inferPropertyWithContextSensitiveReturnStatement.symbols
  tests/baselines/reference/inferPropertyWithContextSensitiveReturnStatement.types
  tests/cases/compiler/inferPropertyWithContextSensitiveReturnStatement.ts
Labels: For Backlog Bug

#53387 Fix resolving entity name of namespace member after alias is merged with type
  src/compiler/checker.ts
  tests/baselines/reference/exportTypeMergedWithExportStarAsNamespace.js
  tests/baselines/reference/exportTypeMergedWithExportStarAsNamespace.symbols
  tests/baselines/reference/exportTypeMergedWithExportStarAsNamespace.types
  tests/cases/conformance/externalModules/exportTypeMergedWithExportStarAsNamespace.ts
Labels: Author: Team, For Milestone Bug

#53258 Ensure rest type for source parameter is readonly in relations
  src/compiler/checker.ts
  tests/baselines/reference/contextualTupleTypeParameterReadonly.js
  tests/baselines/reference/contextualTupleTypeParameterReadonly.symbols
  tests/baselines/reference/contextualTupleTypeParameterReadonly.types
  tests/baselines/reference/genericRestParameters3.errors.txt
  tests/baselines/reference/restTuplesFromContextualTypes.errors.txt
  tests/cases/compiler/contextualTupleTypeParameterReadonly.ts
Labels: Author: Team, For Milestone Bug

#53215 Avoid rewriting homomorphic mapped types with homomorphic instantiations
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypeGenericInstantiationPreservesInlineForm.js
  tests/baselines/reference/mappedTypeGenericInstantiationPreservesInlineForm.symbols
  tests/baselines/reference/mappedTypeGenericInstantiationPreservesInlineForm.types
  tests/baselines/reference/mappedTypeUnionConstraintInferences.js
  tests/cases/compiler/mappedTypeGenericInstantiationPreservesInlineForm.ts
Labels: For Uncommitted Bug

#53401 Make deeplyNestedTemplateLiteralIntersection run a little faster
  tests/baselines/reference/deeplyNestedTemplateLiteralIntersection.errors.txt
  tests/cases/compiler/deeplyNestedTemplateLiteralIntersection.ts
Labels: Author: Team, For Uncommitted Bug

#53066 Always substitute indexed generic mapped type when getting constraint from indexed access
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypeConstraints2.errors.txt
  tests/baselines/reference/mappedTypeConstraints2.js
  tests/baselines/reference/mappedTypeConstraints2.symbols
  tests/baselines/reference/mappedTypeConstraints2.types
  tests/cases/conformance/types/mapped/mappedTypeConstraints2.ts
Labels: For Milestone Bug

#53351 Fix subtype reduction involving type variables with union constraints
  src/compiler/checker.ts
  tests/baselines/reference/subtypeReductionUnionConstraints.symbols
  tests/baselines/reference/subtypeReductionUnionConstraints.types
  tests/cases/compiler/subtypeReductionUnionConstraints.ts
Labels: Author: Team, For Milestone Bug

#53418 fix(53372): TypeScript cannot auto-complete keyword extends
  src/services/completions.ts
  tests/cases/fourslash/extendsKeywordCompletion.ts
Labels: For Backlog Bug

#49100 Optimize the transformed output of `JSXSpreadAttribute`s containing an `ObjectLiteralExpression`
  src/compiler/transformers/jsx.ts
  tests/baselines/reference/tsxEmitSpreadAttribute(target=es2015).js
  tests/baselines/reference/tsxEmitSpreadAttribute(target=es2015).symbols
  tests/baselines/reference/tsxEmitSpreadAttribute(target=es2015).types
  tests/baselines/reference/tsxEmitSpreadAttribute(target=es2018).js
  tests/baselines/reference/tsxEmitSpreadAttribute(target=es2018).symbols
  tests/baselines/reference/tsxEmitSpreadAttribute(target=es2018).types
  tests/baselines/reference/tsxEmitSpreadAttribute(target=esnext).js
  tests/baselines/reference/tsxEmitSpreadAttribute(target=esnext).symbols
  tests/baselines/reference/tsxEmitSpreadAttribute(target=esnext).types
  tests/baselines/reference/tsxReactEmitSpreadAttribute(target=es2015).js
  tests/baselines/reference/tsxReactEmitSpreadAttribute(target=es2015).symbols
  tests/baselines/reference/tsxReactEmitSpreadAttribute(target=es2015).types
  tests/baselines/reference/tsxReactEmitSpreadAttribute(target=es2018).js
  tests/baselines/reference/tsxReactEmitSpreadAttribute(target=es2018).symbols
  tests/baselines/reference/tsxReactEmitSpreadAttribute(target=es2018).types
  tests/baselines/reference/tsxReactEmitSpreadAttribute(target=esnext).js
  tests/baselines/reference/tsxReactEmitSpreadAttribute(target=esnext).symbols
  tests/baselines/reference/tsxReactEmitSpreadAttribute(target=esnext).types
  tests/cases/conformance/jsx/tsxEmitSpreadAttribute.ts
  tests/cases/conformance/jsx/tsxReactEmitSpreadAttribute.ts
Labels: For Backlog Bug

#53405 Remove redundant throws of Debug.assertNever
  src/compiler/checker.ts
  src/jsTyping/jsTyping.ts
  src/services/classifier.ts
  src/services/codefixes/requireInTs.ts
  src/services/refactors/extractSymbol.ts
Labels: Author: Team, For Uncommitted Bug

#53423 perf: ensure compiler options affecting semantic diagnostics get included in build info
  src/compiler/commandLineParser.ts
  src/testRunner/unittests/config/commandLineParsing.ts
Labels: For Uncommitted Bug

#53407 fix: escape module specifier for snippet after quoted
  src/services/completions.ts
  tests/baselines/reference/importStatementCompletions3.baseline
Labels: For Backlog Bug

#53340 Fix the type of `copyWithin`
  src/lib/es2015.core.d.ts
  src/lib/es2020.bigint.d.ts
  src/lib/es5.d.ts
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty.errors.txt
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty.types
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty2.js
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty2.types
Labels: For Backlog Bug

#53428 Include type parameters in tagged template literals in `isPartOfTypeNode`
  src/compiler/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#53443 Support wildcard exports in tsconfig lookup
  src/compiler/moduleNameResolver.ts
  tests/baselines/reference/tsconfigExtendsPackageJsonExportsWildcard.errors.txt
  tests/cases/compiler/tsconfigExtendsPackageJsonExportsWildcard.ts
Labels: Author: Team, For Milestone Bug

#53435 Improve detection of cases where subtype reduction is unnecessary
  src/compiler/checker.ts
  tests/baselines/reference/noSubtypeReduction.symbols
  tests/baselines/reference/noSubtypeReduction.types
  tests/cases/compiler/noSubtypeReduction.ts
Labels: Breaking Change, Author: Team, For Milestone Bug

#53441 Don't error when calling `resolveEntityName`
  src/compiler/checker.ts
  tests/cases/fourslash/classSymbolLookup.ts
Labels: Author: Team, For Milestone Bug

#53261 Defer type comparability check for assertions
  src/compiler/checker.ts
  tests/baselines/reference/classVarianceCircularity.js
  tests/baselines/reference/classVarianceCircularity.symbols
  tests/baselines/reference/classVarianceCircularity.types
  tests/baselines/reference/classVarianceResolveCircularity.errors.txt
  tests/baselines/reference/classVarianceResolveCircularity.js
  tests/baselines/reference/classVarianceResolveCircularity.symbols
  tests/baselines/reference/classVarianceResolveCircularity.types
  tests/cases/compiler/classVarianceCircularity.ts
  tests/cases/compiler/classVarianceResolveCircularity.ts
Labels: Author: Team, For Milestone Bug

#51319 Handle jsx runtime implicit synthetic import in find all references
  src/services/findAllReferences.ts
  src/services/importTracker.ts
  tests/baselines/reference/jsxFindAllReferencesOnRuntimeImportWithPaths1.baseline.jsonc
  tests/baselines/reference/tslibFindAllReferencesOnRuntimeImportWithPaths1.baseline.jsonc
  tests/cases/fourslash/jsxFindAllReferencesOnRuntimeImportWithPaths1.ts
  tests/cases/fourslash/tslibFindAllReferencesOnRuntimeImportWithPaths1.ts
Labels: Author: Team, For Milestone Bug

#52146 Fixed an issue with an incorrect resolved signature being cached/returned sometimes for signatures depending on the contextual type/outer inference
  src/compiler/checker.ts
  tests/cases/fourslash/quickInfoNestedGenericCalls.ts
Labels: For Backlog Bug

#53464 Revert PR #53255
  src/compiler/checker.ts
  tests/baselines/reference/classImplementsMethodWIthTupleArgs.js
  tests/baselines/reference/classImplementsMethodWIthTupleArgs.symbols
  tests/baselines/reference/classImplementsMethodWIthTupleArgs.types
  tests/baselines/reference/contextualTupleTypeParameterReadonly.errors.txt
  tests/baselines/reference/contextualTupleTypeParameterReadonly.js
  tests/baselines/reference/contextualTupleTypeParameterReadonly.symbols
  tests/baselines/reference/contextualTupleTypeParameterReadonly.types
  tests/baselines/reference/genericRestParameters3.errors.txt
  tests/baselines/reference/restTuplesFromContextualTypes.errors.txt
  tests/cases/compiler/classImplementsMethodWIthTupleArgs.ts
  tests/cases/compiler/contextualTupleTypeParameterReadonly.ts
Labels: Author: Team, For Milestone Bug

#53471 Pick PR #53468 (Fix incorrect assert about configFi...) into release-5.0
  src/compiler/watchPublic.ts
  src/testRunner/unittests/tscWatch/watchApi.ts
  tests/baselines/reference/tscWatch/watchApi/when-watching-referenced-project-when-there-is-no-config-file-name.js
  tests/baselines/reference/tscWatch/watchApi/when-watching-referenced-project-with-extends-when-there-is-no-config-file-name.js
Labels: Author: Team, For Uncommitted Bug

#53472 Add tests for completions crash
  src/testRunner/unittests/tsserver/exportMapCache.ts
  tests/baselines/reference/tsserver/exportMapCache/invalidates-the-cache-when-a-file-is-opened-with-different-contents.js
  tests/cases/fourslash/server/completionsOverridingMethodCrash2.ts
Labels: Author: Team, For Milestone Bug

#53266 fix(53257): Illegal .d.ts class property definition for "constructor" generated from JavaScript
  src/compiler/checker.ts
  tests/baselines/reference/constructorPropertyJs.js
  tests/baselines/reference/constructorPropertyJs.symbols
  tests/baselines/reference/constructorPropertyJs.types
  tests/cases/compiler/constructorPropertyJs.ts
Labels: For Backlog Bug

#53490 Don't error when function has an implicit return but its return type is assignable to `undefined`
  src/compiler/checker.ts
  tests/baselines/reference/functionsWithImplicitReturnTypeAssignableToUndefined(strictnullchecks=false).js
  tests/baselines/reference/functionsWithImplicitReturnTypeAssignableToUndefined(strictnullchecks=false).symbols
  tests/baselines/reference/functionsWithImplicitReturnTypeAssignableToUndefined(strictnullchecks=false).types
  tests/baselines/reference/functionsWithImplicitReturnTypeAssignableToUndefined(strictnullchecks=true).errors.txt
  tests/baselines/reference/functionsWithImplicitReturnTypeAssignableToUndefined(strictnullchecks=true).js
  tests/baselines/reference/functionsWithImplicitReturnTypeAssignableToUndefined(strictnullchecks=true).symbols
  tests/baselines/reference/functionsWithImplicitReturnTypeAssignableToUndefined(strictnullchecks=true).types
  tests/baselines/reference/unknownType1.errors.txt
  tests/cases/compiler/functionsWithImplicitReturnTypeAssignableToUndefined.ts
Labels: For Milestone Bug

#53546 Fix baselines after bad merge
  tests/baselines/reference/declarationEmitLateBoundJSAssignments.js
Labels: Author: Team, For Uncommitted Bug

#53358 Cache getConstraintOfDistributiveConditionalType
  src/compiler/checker.ts
  src/compiler/types.ts
Labels: Author: Team, For Uncommitted Bug

#53547 Fix double-emit in constructor
  src/compiler/transformers/esDecorators.ts
  tests/baselines/reference/esDecorators-classDeclaration-classSuper.7.js
  tests/baselines/reference/esDecorators-classExpression-classSuper.7.js
  tests/cases/conformance/esDecorators/classDeclaration/classSuper/esDecorators-classDeclaration-classSuper.7.ts
Labels: Author: Team, For Milestone Bug

#53543 Don't capture type parameters defined inside the extraction range with "Extract to function"
  src/services/refactors/extractSymbol.ts
  tests/cases/fourslash/extract-method-generics-inside-extraction1.ts
  tests/cases/fourslash/extract-method-generics-inside-extraction2.ts
Labels: For Milestone Bug

#53481 Retry string completions from the inferred type by default
  src/services/stringCompletions.ts
  tests/cases/fourslash/completionsLiteralFromInferenceWithinInferredType3.ts
Labels: For Uncommitted Bug

#53434 fix(53347): Incorrect generated JS code when private (hashtag) property is used with parenthesis in left assignment
  src/compiler/transformers/classFields.ts
  tests/baselines/reference/privateNameFieldParenthesisLeftAssignment.js
  tests/baselines/reference/privateNameFieldParenthesisLeftAssignment.symbols
  tests/baselines/reference/privateNameFieldParenthesisLeftAssignment.types
  tests/cases/conformance/classes/members/privateNames/privateNameFieldParenthesisLeftAssignment.ts
Labels: For Backlog Bug

#53225 Provide string completions within unions in indexed access types
  src/services/stringCompletions.ts
  tests/cases/fourslash/stringLiteralCompletionsForTypeIndexedAccess.ts
Labels: For Uncommitted Bug

#53370 Update azure-devops-node-api
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#53590 Type-only auto-import improvements
  src/services/codefixes/importFixes.ts
  tests/cases/fourslash/autoImportTypeOnlyPreferred2.ts
  tests/cases/fourslash/importNameCodeFixConvertTypeOnly1.ts
Labels: Author: Team, For Milestone Bug

#53599 Ignore `allowImportingTsExtensions` in transpileModule to suppress option validation error with `noEmit`
  src/compiler/commandLineParser.ts
  src/testRunner/unittests/services/transpile.ts
  tests/baselines/reference/transpile/Can transpile .ts extensions without error (verbatimModuleSyntax=true).js
  tests/baselines/reference/transpile/Can transpile .ts extensions without error (verbatimModuleSyntax=true).oldTranspile.js
  tests/baselines/reference/transpile/Can transpile .ts extensions without error.js
  tests/baselines/reference/transpile/Can transpile .ts extensions without error.oldTranspile.js
  tests/baselines/reference/transpile/Ignores allowImportingTsExtensions without noEmit error (verbatimModuleSyntax=true).js
  tests/baselines/reference/transpile/Ignores allowImportingTsExtensions without noEmit error (verbatimModuleSyntax=true).oldTranspile.js
  tests/baselines/reference/transpile/Ignores allowImportingTsExtensions without noEmit error.js
  tests/baselines/reference/transpile/Ignores allowImportingTsExtensions without noEmit error.oldTranspile.js
Labels: Author: Team, For Uncommitted Bug

#53608 Remove non-ascii characters from internal code comments
  src/compiler/scanner.ts
  src/services/codefixes/addMissingAwait.ts
  src/services/exportInfoMap.ts
  src/services/findAllReferences.ts
  src/services/formatting/rules.ts
  src/services/organizeImports.ts
  src/services/signatureHelp.ts
  src/services/smartSelection.ts
  src/services/utilities.ts
Labels: For Uncommitted Bug

#53613 Fix Go To Source Definition in `--moduleResolution bundler`
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/program.ts
  src/compiler/utilities.ts
  tests/baselines/reference/goToSource15_bundler.baseline.jsonc
  tests/cases/fourslash/server/goToSource15_bundler.ts
Labels: Author: Team, For Uncommitted Bug

#53616 Add baselines per root for affected file watching
  src/testRunner/unittests/canWatch.ts
  tests/baselines/reference/canWatch/canWatchAffectingLocationDos.baseline.md
  tests/baselines/reference/canWatch/canWatchAffectingLocationPosix.baseline.md
  tests/baselines/reference/canWatch/canWatchAffectingLocationUnc.baseline.md
  tests/baselines/reference/canWatch/canWatchAffectingLocationUncDos.baseline.md
Labels: Author: Team, For Uncommitted Bug
