Repository microsoft/TypeScript, pull requests merged in 2023-12, with the labels that each got.

#56627 Transpile jsdoc parsing mode
  src/services/transpile.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#56514 fix(42220): Missing 'used before declaration' for class expression used in own computed property name
  src/compiler/checker.ts
  tests/baselines/reference/computedPropertyNamesWithStaticProperty.errors.txt
  tests/baselines/reference/computedPropertyNamesWithStaticProperty.js
  tests/baselines/reference/computedPropertyNamesWithStaticProperty.symbols
  tests/baselines/reference/computedPropertyNamesWithStaticProperty.types
  tests/cases/conformance/es6/computedProperties/computedPropertyNamesWithStaticProperty.ts
Labels: For Backlog Bug

#56610 feat(56600): JSDoc @callback doesn't support this parameters via @this
  src/compiler/checker.ts
  src/compiler/parser.ts
  tests/baselines/reference/callbackTag4.symbols
  tests/baselines/reference/callbackTag4.types
  tests/cases/conformance/jsdoc/callbackTag4.ts
Labels: For Backlog Bug

#56639 ParseNone -> ParseAll
  src/services/transpile.ts
Labels: Author: Team, For Uncommitted Bug

#56372 fix(48260): Incorrect parameter hint is highlighted when arguments contain spread syntax
  src/services/completions.ts
  src/services/signatureHelp.ts
  src/services/stringCompletions.ts
  tests/baselines/reference/signatureHelpRestArgs.baseline
  tests/cases/fourslash/signatureHelpRestArgs.ts
Labels: For Backlog Bug

#56607 Try and deal with CodeQL reports on replace("*", ...)
  src/compiler/moduleNameResolver.ts
  src/compiler/moduleSpecifiers.ts
  src/compiler/utilities.ts
  src/services/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#53317 fix(53181): Overloads Are Not Generated as Expected When Using JsDocOverload Tag to Declare Overloads of Functions Assigned to a Prototype
  src/compiler/checker.ts
  src/compiler/utilities.ts
  tests/baselines/reference/jsFileAlternativeUseOfOverloadTag.js
  tests/baselines/reference/jsFileAlternativeUseOfOverloadTag.types
  tests/baselines/reference/jsFileMethodOverloads4.js
  tests/baselines/reference/jsFileMethodOverloads4.symbols
  tests/baselines/reference/jsFileMethodOverloads4.types
  tests/baselines/reference/jsFileMethodOverloads5.js
  tests/baselines/reference/jsFileMethodOverloads5.symbols
  tests/baselines/reference/jsFileMethodOverloads5.types
  tests/cases/compiler/jsFileMethodOverloads4.ts
  tests/cases/compiler/jsFileMethodOverloads5.ts
Labels: For Backlog Bug

#56161 Disallow `Infinity`, `-Infinity` and `NaN` as an enum key name
  src/compiler/checker.ts
  tests/baselines/reference/enumWithInfinityProperty.errors.txt
  tests/baselines/reference/enumWithNaNProperty.errors.txt
  tests/baselines/reference/enumWithNegativeInfinityProperty.errors.txt
Labels: For Backlog Bug

#56694 Improve JSDocFunctionType readability
  src/compiler/parser.ts
Labels: Author: Team, For Uncommitted Bug

#56613 Address comments on IndexSignature inlay hint PR
  src/services/inlayHints.ts
Labels: For Uncommitted Bug

#56565 fix(56562): Type with negative properties cause crash in infer return type
  src/compiler/checker.ts
  tests/cases/fourslash/refactorInferFunctionReturnType25.ts
Labels: For Backlog Bug

#56626 Directly copy only the index signature in addition to declared properties
  src/compiler/checker.ts
  tests/baselines/reference/conflictingTypeParameterSymbolTransfer.errors.txt
  tests/baselines/reference/conflictingTypeParameterSymbolTransfer.js
  tests/baselines/reference/conflictingTypeParameterSymbolTransfer.symbols
  tests/baselines/reference/conflictingTypeParameterSymbolTransfer.types
  tests/cases/compiler/conflictingTypeParameterSymbolTransfer.ts
Labels: Author: Team, For Backlog Bug

#56570 Disallow negative numbers in create numeric literal (take 2)
  src/compiler/checker.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/transformers/declarations.ts
  src/compiler/transformers/generators.ts
  src/compiler/transformers/ts.ts
Labels: For Uncommitted Bug

#56395 ImportAttributes should go through the same emit phases when in an ImportTypeNode
  src/compiler/emitter.ts
  src/compiler/types.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/refactorToReturnTypeWithImportAssertions.ts
Labels: For Backlog Bug

#56247 Check auto-import completion for spread assignment
  src/services/completions.ts
  tests/cases/fourslash/completionForObjectProperty.ts
  tests/cases/fourslash/completionPropertyShorthandForObjectLiteral5.ts
Labels: For Backlog Bug

#56701 Show implied options in --showConfig
  package-lock.json
  package.json
  src/compiler/commandLineParser.ts
  src/compiler/utilities.ts
  tests/baselines/reference/config/showConfig/Show TSConfig with compileOnSave and more/tsconfig.json
  tests/baselines/reference/config/showConfig/Show TSConfig with paths and more/tsconfig.json
  tests/baselines/reference/config/showConfig/Shows tsconfig for single option/checkJs/tsconfig.json
  tests/baselines/reference/config/showConfig/Shows tsconfig for single option/composite/tsconfig.json
  tests/baselines/reference/config/showConfig/Shows tsconfig for single option/isolatedModules/tsconfig.json
  tests/baselines/reference/config/showConfig/Shows tsconfig for single option/module/tsconfig.json
  tests/baselines/reference/config/showConfig/Shows tsconfig for single option/strict/tsconfig.json
  tests/baselines/reference/config/showConfig/Shows tsconfig for single option/verbatimModuleSyntax/tsconfig.json
Labels: Author: Team, For Uncommitted Bug

#56271 Defer conditional types with parenthesized multi-element tuple types in `extends` clause
  src/compiler/checker.ts
  tests/baselines/reference/deferredConditionalTypes2.symbols
  tests/baselines/reference/deferredConditionalTypes2.types
  tests/cases/compiler/deferredConditionalTypes2.ts
Labels: For Uncommitted Bug

#56448 Make isTypeAssignableTo public on TypeChecker
  src/compiler/types.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#56418 Allow variance annotations on generic references
  src/compiler/checker.ts
  tests/baselines/reference/varianceReferences.errors.txt
  tests/baselines/reference/varianceReferences.js
  tests/baselines/reference/varianceReferences.symbols
  tests/baselines/reference/varianceReferences.types
  tests/cases/compiler/varianceReferences.ts
Labels: For Backlog Bug

#56585 Remove old "start" script from package.json
  package.json
Labels: For Uncommitted Bug

#56313 Avoid dependent parameters narrowings if any declared symbol of the parameter is assigned to
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/dependentDestructuredVariables.errors.txt
  tests/baselines/reference/dependentDestructuredVariables.js
  tests/baselines/reference/dependentDestructuredVariables.symbols
  tests/baselines/reference/dependentDestructuredVariables.types
  tests/baselines/reference/narrowRefinedConstLikeParameterBIndingElementNameInInnerScope.symbols
  tests/baselines/reference/narrowRefinedConstLikeParameterBIndingElementNameInInnerScope.types
  tests/cases/compiler/narrowRefinedConstLikeParameterBIndingElementNameInInnerScope.ts
  tests/cases/conformance/controlFlow/dependentDestructuredVariables.ts
Labels: For Backlog Bug

#56540 fix(49419): Referencing this through a variable causes "Rename Symbol" to misbehave in Javascript
  src/compiler/checker.ts
  tests/baselines/reference/inferringClassMembersFromAssignments6.symbols
  tests/baselines/reference/inferringClassMembersFromAssignments7.symbols
  tests/baselines/reference/renameJsPropertyAssignment4.baseline.jsonc
  tests/baselines/reference/typeFromPropertyAssignment10.symbols
  tests/baselines/reference/typeFromPropertyAssignment10_1.symbols
  tests/baselines/reference/typeFromPropertyAssignment40.symbols
  tests/baselines/reference/typeFromPropertyAssignment9.symbols
  tests/baselines/reference/typeFromPropertyAssignment9_1.symbols
  tests/cases/fourslash/renameJsPropertyAssignment4.ts
Labels: For Milestone Bug

#56614 Don’t emit file references that are already referenced via imports
  src/compiler/transformers/declarations.ts
  tests/baselines/reference/declFileForExportedImport.js
  tests/baselines/reference/declarationEmitRedundantTripleSlashModuleAugmentation.js
  tests/baselines/reference/importDecl.js
  tests/baselines/reference/importDeclarationUsedAsTypeQuery.js
  tests/cases/compiler/declarationEmitRedundantTripleSlashModuleAugmentation.ts
Labels: Author: Team, For Uncommitted Bug

#56294 fix(56127): TypeScript "Move to File" refactor causes self import
  src/services/refactors/moveToFile.ts
  tests/cases/fourslash/moveToFile_existingImports5.ts
Labels: For Milestone Bug

#56657 fix(56602): JSDoc render with @param Sub-object properties
  src/services/jsDoc.ts
  tests/baselines/reference/quickInfoJsDocTags14.baseline
  tests/cases/fourslash/quickInfoJsDocTags14.ts
Labels: For Backlog Bug

#55683 Perform usage analysis on refenced binding aliases in function signatures.
  src/compiler/checker.ts
  src/compiler/transformers/declarations.ts
  src/compiler/types.ts
  tests/baselines/reference/declarationEmitBindingPatternsUnused.errors.txt
  tests/baselines/reference/declarationEmitBindingPatternsUnused.js
  tests/baselines/reference/declarationEmitBindingPatternsUnused.symbols
  tests/baselines/reference/declarationEmitBindingPatternsUnused.types
  tests/cases/compiler/declarationEmitBindingPatternsUnused.ts
Labels: For Backlog Bug

#56555 Treat array literal contextually typed by homomorphic mapped types as in tuple context
  src/compiler/checker.ts
  tests/baselines/reference/reverseMappedTupleContext.symbols
  tests/baselines/reference/reverseMappedTupleContext.types
  tests/baselines/reference/reverseMappedUnionInference.types
  tests/cases/compiler/reverseMappedTupleContext.ts
Labels: For Backlog Bug

#56667 fix(56665): Improve Outline for template literals
  src/services/navigationBar.ts
  tests/cases/fourslash/navigationBarAnonymousClassAndFunctionExpressions.ts
  tests/cases/fourslash/navigationBarAnonymousClassAndFunctionExpressions3.ts
Labels: For Backlog Bug

#56707 fix(56699): [Formatting] Missing space after implements / extends generic
  src/services/formatting/rules.ts
  tests/cases/fourslash/formatSpaceAfterImplementsExtends.ts
  tests/cases/fourslash/genericsFormatting.ts
Labels: For Uncommitted Bug

#56649 feat(56634): Support for "const modifier on type parameters" with JSDoc
  src/compiler/checker.ts
  src/compiler/parser.ts
  tests/baselines/reference/jsdocTemplateTag6.symbols
  tests/baselines/reference/jsdocTemplateTag6.types
  tests/baselines/reference/jsdocTemplateTag7.errors.txt
  tests/baselines/reference/jsdocTemplateTag7.symbols
  tests/baselines/reference/jsdocTemplateTag7.types
  tests/baselines/reference/jsdocTemplateTag8.errors.txt
  tests/baselines/reference/jsdocTemplateTag8.symbols
  tests/baselines/reference/jsdocTemplateTag8.types
  tests/cases/conformance/jsdoc/jsdocTemplateTag6.ts
  tests/cases/conformance/jsdoc/jsdocTemplateTag7.ts
  tests/cases/conformance/jsdoc/jsdocTemplateTag8.ts
Labels: For Milestone Bug

#56795 Give suggestion for @types/bun when Bun global is not found
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/typingsSuggestionBun1.errors.txt
  tests/baselines/reference/typingsSuggestionBun1.js
  tests/baselines/reference/typingsSuggestionBun1.symbols
  tests/baselines/reference/typingsSuggestionBun1.types
  tests/baselines/reference/typingsSuggestionBun2.errors.txt
  tests/baselines/reference/typingsSuggestionBun2.js
  tests/baselines/reference/typingsSuggestionBun2.symbols
  tests/baselines/reference/typingsSuggestionBun2.types
  tests/cases/conformance/typings/typingsSuggestionBun1.ts
  tests/cases/conformance/typings/typingsSuggestionBun2.ts
Labels: Author: Team, For Uncommitted Bug

#55924 Enforce identical enum values in compatibility checks
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/types.ts
  tests/baselines/reference/enumAssignmentCompat3.errors.txt
  tests/baselines/reference/enumAssignmentCompat3.js
  tests/baselines/reference/enumAssignmentCompat3.symbols
  tests/baselines/reference/enumAssignmentCompat3.types
  tests/baselines/reference/enumAssignmentCompat6.errors.txt
  tests/baselines/reference/enumAssignmentCompat6.js
  tests/baselines/reference/enumAssignmentCompat6.symbols
  tests/baselines/reference/enumAssignmentCompat6.types
  tests/baselines/reference/enumAssignmentCompat7.errors.txt
  tests/baselines/reference/enumAssignmentCompat7.js
  tests/baselines/reference/enumAssignmentCompat7.symbols
  tests/baselines/reference/enumAssignmentCompat7.types
  tests/cases/compiler/enumAssignmentCompat3.ts
  tests/cases/compiler/enumAssignmentCompat6.ts
  tests/cases/compiler/enumAssignmentCompat7.ts
Labels: Breaking Change, Author: Team, For Milestone Bug
