Repository microsoft/TypeScript, pull requests merged in 2023-10, with the labels that each got.

#55944 Remove ensure-related-repos-run-crons
  .github/workflows/ensure-related-repos-run-crons.yml
Labels: Author: Team, For Uncommitted Bug

#55923 Speed up GHA workflows, use consistent bot token, etc
  .github/workflows/accept-baselines-fix-lints.yaml
  .github/workflows/new-release-branch.yaml
  .github/workflows/rich-navigation.yml
  .github/workflows/set-version.yaml
  .github/workflows/sync-branch.yaml
  .github/workflows/twoslash-repros.yaml
  .github/workflows/update-lkg.yml
  .github/workflows/update-package-lock.yaml
Labels: Author: Team, For Uncommitted Bug

#55938 fix(55937): 'Infer function return type' offered in preceding trivia
  src/services/refactors/inferFunctionReturnType.ts
  tests/cases/fourslash/refactorInferFunctionReturnType24.ts
Labels: For Uncommitted Bug

#55949 fix(55946): Errant case causes crash in switch/case snippet completions
  src/services/completions.ts
  tests/baselines/reference/exhaustiveCaseCompletions9.baseline
  tests/cases/fourslash/exhaustiveCaseCompletions9.ts
Labels: For Milestone Bug

#55947 fix(55945): Inlay hints don't work for bigint literals
  src/services/inlayHints.ts
  tests/baselines/reference/inlayHintsInteractiveFunctionParameterTypes5.baseline
  tests/baselines/reference/inlayHintsInteractiveMultifile1.baseline
  tests/baselines/reference/inlayHintsQuotePreference1.baseline
  tests/baselines/reference/inlayHintsQuotePreference2.baseline
  tests/cases/fourslash/inlayHintsInteractiveFunctionParameterTypes5.ts
  tests/cases/fourslash/inlayHintsQuotePreference1.ts
  tests/cases/fourslash/inlayHintsQuotePreference2.ts
Labels: For Milestone Bug

#55981 Don't create children prop out of non-semantic JSX children
  src/compiler/checker.ts
  tests/baselines/reference/jsxContainsOnlyTriviaWhiteSpacesNotCountedAsChild.js
  tests/baselines/reference/jsxContainsOnlyTriviaWhiteSpacesNotCountedAsChild.symbols
  tests/baselines/reference/jsxContainsOnlyTriviaWhiteSpacesNotCountedAsChild.types
  tests/baselines/reference/jsxEmptyExpressionNotCountedAsChild2.errors.txt
  tests/cases/compiler/jsxContainsOnlyTriviaWhiteSpacesNotCountedAsChild.tsx
Labels: For Uncommitted Bug

#55807 Add a test for a property of reverse mapped type having a primitive type
  tests/baselines/reference/reverseMappedTypePrimitiveConstraintProperty.symbols
  tests/baselines/reference/reverseMappedTypePrimitiveConstraintProperty.types
  tests/cases/compiler/reverseMappedTypePrimitiveConstraintProperty.ts
Labels: For Uncommitted Bug

#55789 Preserve partially typed tuple names in more places
  src/compiler/checker.ts
  tests/baselines/reference/argumentsReferenceInFunction1_Js.errors.txt
  tests/baselines/reference/partiallyNamedTuples3.js
  tests/baselines/reference/partiallyNamedTuples3.symbols
  tests/baselines/reference/partiallyNamedTuples3.types
  tests/baselines/reference/restTuplesFromContextualTypes.types
  tests/cases/conformance/types/tuple/named/partiallyNamedTuples3.ts
Labels: Author: Team, For Uncommitted Bug

#55985 Recognize `export * as default` as a syntactic default export for synthetic default detection
  src/compiler/checker.ts
  tests/baselines/reference/exportAsNamespace5.js
  tests/baselines/reference/exportAsNamespace5.symbols
  tests/baselines/reference/exportAsNamespace5.types
  tests/cases/conformance/es2020/modules/exportAsNamespace5.ts
Labels: Author: Team, For Milestone Bug

#55962 Initial add of Support.md
  SUPPORT.md
Labels: For Uncommitted Bug

#56001 Allow valid contextual keyword completions even when an auto-import by the same name exists
  src/services/completions.ts
  tests/cases/fourslash/completionsImportTypeKeyword.ts
Labels: Author: Team, For Milestone Bug

#55442 Fixed declaration emit of object literals withs divergent accessors
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitObjectLiteralAccessors1.js
  tests/baselines/reference/declarationEmitObjectLiteralAccessors1.symbols
  tests/baselines/reference/declarationEmitObjectLiteralAccessors1.types
  tests/baselines/reference/declarationEmitObjectLiteralAccessorsJs1.js
  tests/baselines/reference/declarationEmitObjectLiteralAccessorsJs1.symbols
  tests/baselines/reference/declarationEmitObjectLiteralAccessorsJs1.types
  tests/baselines/reference/discriminateWithDivergentAccessors1.types
  tests/baselines/reference/divergentAccessors1.types
  tests/baselines/reference/divergentAccessorsTypes1.types
  tests/baselines/reference/divergentAccessorsTypes6.types
  tests/baselines/reference/objectLiteralErrors.types
  tests/cases/compiler/declarationEmitObjectLiteralAccessors1.ts
  tests/cases/compiler/declarationEmitObjectLiteralAccessorsJs1.ts
Labels: For Uncommitted Bug

#55991 Fix fallthrough and default in new switch-true narrowing
  src/compiler/checker.ts
  tests/baselines/reference/narrowByClauseExpressionInSwitchTrue.symbols
  tests/baselines/reference/narrowByClauseExpressionInSwitchTrue1.symbols
  tests/baselines/reference/narrowByClauseExpressionInSwitchTrue1.types
  tests/baselines/reference/narrowByClauseExpressionInSwitchTrue10.symbols
  tests/baselines/reference/narrowByClauseExpressionInSwitchTrue10.types
  tests/baselines/reference/narrowByClauseExpressionInSwitchTrue2.symbols
  tests/baselines/reference/narrowByClauseExpressionInSwitchTrue2.types
  tests/baselines/reference/narrowByClauseExpressionInSwitchTrue3.errors.txt
  tests/baselines/reference/narrowByClauseExpressionInSwitchTrue3.symbols
  tests/baselines/reference/narrowByClauseExpressionInSwitchTrue3.types
  tests/baselines/reference/narrowByClauseExpressionInSwitchTrue4.symbols
  tests/baselines/reference/narrowByClauseExpressionInSwitchTrue4.types
  tests/baselines/reference/narrowByClauseExpressionInSwitchTrue5.symbols
  tests/baselines/reference/narrowByClauseExpressionInSwitchTrue5.types
  tests/baselines/reference/narrowByClauseExpressionInSwitchTrue6.errors.txt
  tests/baselines/reference/narrowByClauseExpressionInSwitchTrue6.symbols
  tests/baselines/reference/narrowByClauseExpressionInSwitchTrue6.types
  tests/baselines/reference/narrowByClauseExpressionInSwitchTrue7.errors.txt
  tests/baselines/reference/narrowByClauseExpressionInSwitchTrue7.symbols
  tests/baselines/reference/narrowByClauseExpressionInSwitchTrue7.types
  tests/baselines/reference/narrowByClauseExpressionInSwitchTrue8.symbols
  tests/baselines/reference/narrowByClauseExpressionInSwitchTrue8.types
  tests/baselines/reference/narrowByClauseExpressionInSwitchTrue9.symbols
  tests/baselines/reference/narrowByClauseExpressionInSwitchTrue9.types
  tests/cases/compiler/narrowByClauseExpressionInSwitchTrue1.ts
  tests/cases/compiler/narrowByClauseExpressionInSwitchTrue10.ts
  tests/cases/compiler/narrowByClauseExpressionInSwitchTrue2.ts
  tests/cases/compiler/narrowByClauseExpressionInSwitchTrue3.ts
  tests/cases/compiler/narrowByClauseExpressionInSwitchTrue4.ts
  tests/cases/compiler/narrowByClauseExpressionInSwitchTrue5.ts
  tests/cases/compiler/narrowByClauseExpressionInSwitchTrue6.ts
  tests/cases/compiler/narrowByClauseExpressionInSwitchTrue7.ts
  tests/cases/compiler/narrowByClauseExpressionInSwitchTrue8.ts
  tests/cases/compiler/narrowByClauseExpressionInSwitchTrue9.ts
Labels: Author: Team, For Milestone Bug

#56035 Fixed type narrowing in switch statements with parenthesized expressions
  src/compiler/checker.ts
  tests/baselines/reference/narrowByParenthesizedSwitchExpression.symbols
  tests/baselines/reference/narrowByParenthesizedSwitchExpression.types
  tests/cases/compiler/narrowByParenthesizedSwitchExpression.ts
Labels: For Uncommitted Bug

#56015 Add type reference directive for all visited references to ambient modules
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/transformers/declarations.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  tests/baselines/reference/declarationEmitBundleWithAmbientReferences.js
  tests/baselines/reference/declarationEmitTripleSlashReferenceAmbientModule.js
  tests/baselines/reference/nodeModulesAllowJsImportHelpersCollisions2(module=node16).js
  tests/baselines/reference/nodeModulesAllowJsImportHelpersCollisions2(module=nodenext).js
  tests/baselines/reference/nodeModulesImportAssignments(module=node16).js
  tests/baselines/reference/nodeModulesImportAssignments(module=nodenext).js
  tests/baselines/reference/nodeModulesImportHelpersCollisions2(module=node16).js
  tests/baselines/reference/nodeModulesImportHelpersCollisions2(module=nodenext).js
  tests/baselines/reference/nodeModulesImportHelpersCollisions3(module=node16).js
  tests/baselines/reference/nodeModulesImportHelpersCollisions3(module=nodenext).js
  tests/cases/compiler/declarationEmitTripleSlashReferenceAmbientModule.ts
Labels: Author: Team, For Milestone Bug

#56047 pass program update level to getExternalFiles in tsserver plugins so plugins can make decision about their cache based on that
  src/compiler/tsbuildPublic.ts
  src/compiler/watchPublic.ts
  src/compiler/watchUtilities.ts
  src/server/editorServices.ts
  src/server/project.ts
  src/testRunner/unittests/tsserver/externalProjects.ts
  src/testRunner/unittests/tsserver/plugins.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/tsserver/plugins/new-files-with-non-ts-extensions-with-wildcard-matching.js
Labels: Author: Team, For Uncommitted Bug

#56020 Ignore awaited self tail calls when collecting the return type of an async function
  src/compiler/checker.ts
  tests/baselines/reference/parenthesizedJSDocCastAtReturnStatement.symbols
  tests/baselines/reference/parenthesizedJSDocCastAtReturnStatement.types
  tests/baselines/reference/simpleRecursionWithBaseCase.symbols
  tests/baselines/reference/simpleRecursionWithBaseCase1.errors.txt
  tests/baselines/reference/simpleRecursionWithBaseCase1.js
  tests/baselines/reference/simpleRecursionWithBaseCase1.symbols
  tests/baselines/reference/simpleRecursionWithBaseCase1.types
  tests/baselines/reference/simpleRecursionWithBaseCase2.symbols
  tests/baselines/reference/simpleRecursionWithBaseCase2.types
  tests/cases/compiler/parenthesizedJSDocCastAtReturnStatement.ts
  tests/cases/compiler/simpleRecursionWithBaseCase1.ts
  tests/cases/compiler/simpleRecursionWithBaseCase2.ts
Labels: For Uncommitted Bug

#56016 noDts project resolutions verification and updates for incremental behaviour
  src/compiler/moduleNameResolver.ts
  src/compiler/resolutionCache.ts
  src/harness/incrementalUtils.ts
  src/server/editorServices.ts
  src/server/project.ts
  src/server/scriptInfo.ts
  src/server/session.ts
  src/testRunner/unittests/tsserver/auxiliaryProject.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/goToSource16_callbackParamDifferentFile.baseline.jsonc
  tests/baselines/reference/goToSource17_AddsFileToProject.baseline.jsonc
  tests/baselines/reference/goToSource18_reusedFromDifferentFolder.baseline.jsonc
  tests/baselines/reference/tsserver/auxiliaryProject/does-not-remove-scrips-from-InferredProject.js
  tests/baselines/reference/tsserver/auxiliaryProject/file-is-added-later-through-finding-definition.js
  tests/baselines/reference/tsserver/auxiliaryProject/resolution-is-reused-from-different-folder.js
  tests/cases/fourslash/server/goToSource16_callbackParamDifferentFile.ts
  tests/cases/fourslash/server/goToSource17_AddsFileToProject.ts
  tests/cases/fourslash/server/goToSource18_reusedFromDifferentFolder.ts
Labels: Author: Team, For Uncommitted Bug

#56062 Add perf_hooks to the package.json browser list
  package.json
Labels: Author: Team, For Uncommitted Bug

#56073 Remove old references to deprecated assertion node types
  src/compiler/program.ts
  src/services/outliningElementsCollector.ts
Labels: Author: Team, For Uncommitted Bug

#56084 Rewrite bug report template to mention every-ts bisecting
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Author: Team, For Uncommitted Bug

#56086 Fix bug template line breaks, which do not follow normal markdown behavior
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Author: Team, For Uncommitted Bug

#56104 Remove dead pipelines badge from README
  README.md
Labels: Author: Team, For Uncommitted Bug

#56116 Provide contextual `this` to functions assigned using compound assignments
  src/compiler/checker.ts
  src/compiler/utilities.ts
  tests/baselines/reference/thisPrototypeMethodCompoundAssignment.symbols
  tests/baselines/reference/thisPrototypeMethodCompoundAssignment.types
  tests/baselines/reference/thisPrototypeMethodCompoundAssignmentJs.symbols
  tests/baselines/reference/thisPrototypeMethodCompoundAssignmentJs.types
  tests/cases/conformance/jsdoc/thisPrototypeMethodCompoundAssignment.ts
  tests/cases/conformance/jsdoc/thisPrototypeMethodCompoundAssignmentJs.ts
Labels: For Uncommitted Bug

#55906 Improve error message for index signature on generic type when writing
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/cannotIndexGenericWritingError.errors.txt
  tests/baselines/reference/cannotIndexGenericWritingError.symbols
  tests/baselines/reference/cannotIndexGenericWritingError.types
  tests/baselines/reference/keyofAndIndexedAccess2.errors.txt
  tests/baselines/reference/mappedTypeGenericWithKnownKeys.errors.txt
  tests/cases/compiler/cannotIndexGenericWritingError.ts
Labels: Author: Team, For Milestone Bug

#56156 Fix discriminant property check in CFA
  src/compiler/checker.ts
  tests/baselines/reference/narrowingUnionToUnion.js
  tests/baselines/reference/narrowingUnionToUnion.symbols
  tests/baselines/reference/narrowingUnionToUnion.types
  tests/cases/compiler/narrowingUnionToUnion.ts
Labels: Author: Team, For Uncommitted Bug

#56150 Properly handle AsyncGeneratorUnwrapYieldResumption
  src/compiler/factory/emitHelpers.ts
  src/testRunner/unittests/evaluation/asyncGenerator.ts
  tests/baselines/reference/asyncImportNestedYield.js
  tests/baselines/reference/awaitUsingDeclarations.1(target=es2015).js
  tests/baselines/reference/awaitUsingDeclarations.1(target=es2017).js
  tests/baselines/reference/awaitUsingDeclarations.1(target=es5).js
  tests/baselines/reference/blockScopedVariablesUseBeforeDef.js
  tests/baselines/reference/dependentDestructuredVariables.js
  tests/baselines/reference/emitter.asyncGenerators.classMethods.es2015.js
  tests/baselines/reference/emitter.asyncGenerators.classMethods.es5.js
  tests/baselines/reference/emitter.asyncGenerators.functionDeclarations.es2015.js
  tests/baselines/reference/emitter.asyncGenerators.functionDeclarations.es5.js
  tests/baselines/reference/emitter.asyncGenerators.functionExpressions.es2015.js
  tests/baselines/reference/emitter.asyncGenerators.functionExpressions.es5.js
  tests/baselines/reference/emitter.asyncGenerators.objectLiteralMethods.es2015.js
  tests/baselines/reference/emitter.asyncGenerators.objectLiteralMethods.es5.js
  tests/baselines/reference/emitter.forAwait(target=es2015).js
  tests/baselines/reference/emitter.forAwait(target=es2017).js
  tests/baselines/reference/emitter.forAwait(target=es5).js
  tests/baselines/reference/forAwaitPerIterationBindingDownlevel.js
  tests/baselines/reference/objectRestSpread.js
  tests/baselines/reference/privateNamesIncompatibleModifiers.js
  tests/baselines/reference/usingDeclarations.1(target=es2015).js
  tests/baselines/reference/usingDeclarations.1(target=es2017).js
  tests/baselines/reference/usingDeclarations.1(target=es5).js
Labels: Author: Team, For Milestone Bug

#56090 Add user preference for preferring type-only auto imports
  src/compiler/types.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/services/codefixes/importFixes.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/autoImportTypeOnlyPreferred3.ts
  tests/cases/fourslash/fourslash.ts
Labels: Author: Team, For Milestone Bug

#56169 Improve `isDeeplyNestedType` for homomorphic mapped types
  src/compiler/checker.ts
  tests/baselines/reference/deeplyNestedMappedTypes.errors.txt
  tests/baselines/reference/deeplyNestedMappedTypes.symbols
  tests/baselines/reference/deeplyNestedMappedTypes.types
  tests/cases/compiler/deeplyNestedMappedTypes.ts
Labels: Author: Team, For Uncommitted Bug

#56189 Fix spacing in issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/lib_change.yml
  .github/ISSUE_TEMPLATE/module_resolution.yml
Labels: Author: Team, For Uncommitted Bug

#56194 Expose 'updateModifiers' in public NodeFactory API
  src/compiler/checker.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/transformers/declarations.ts
  src/compiler/types.ts
  src/services/codefixes/addMissingAsync.ts
  src/services/completions.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Milestone Bug

#56130 More reliable mechanism for `_this`/`_super` simplification
  src/compiler/factory/nodeFactory.ts
  src/compiler/transformers/es2015.ts
  src/compiler/types.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/callWithSpread.js
  tests/baselines/reference/checkSuperCallBeforeThisAccessing6.js
  tests/baselines/reference/checkSuperCallBeforeThisAccessing7.js
  tests/baselines/reference/checkSuperCallBeforeThisAccessing8.js
  tests/baselines/reference/classUpdateTests.js
  tests/baselines/reference/derivedClassConstructorWithExplicitReturns01.js.map
  tests/baselines/reference/derivedClassConstructorWithExplicitReturns01.sourcemap.txt
  tests/baselines/reference/derivedClassParameterProperties.js
  tests/baselines/reference/derivedClassSuperCallsWithThisArg.js
  tests/baselines/reference/derivedClassSuperProperties.js
  tests/baselines/reference/derivedClassSuperStatementPosition.js
  tests/baselines/reference/errorSuperCalls.js
  tests/baselines/reference/nestedSuperCallEmit.js
  tests/baselines/reference/sourceMapValidationClassWithDefaultConstructorAndExtendsClause.js.map
  tests/baselines/reference/sourceMapValidationClassWithDefaultConstructorAndExtendsClause.sourcemap.txt
  tests/baselines/reference/strictModeInConstructor.js
  tests/baselines/reference/superCallArgsMustMatch.js
  tests/baselines/reference/superCallBeforeThisAccessing2.js
  tests/baselines/reference/superCallBeforeThisAccessing3.js
  tests/baselines/reference/superCallBeforeThisAccessing4.js
  tests/baselines/reference/superCallBeforeThisAccessing7.js
  tests/baselines/reference/superCallFromClassThatHasNoBaseTypeButWithSameSymbolInterface.js
  tests/baselines/reference/superCallInConstructorWithNoBaseType.js
  tests/baselines/reference/superCallParameterContextualTyping3.js
  tests/baselines/reference/superWithGenericSpecialization.js
  tests/baselines/reference/thisInConstructorParameter2.js
  tests/baselines/reference/thisInInvalidContexts.js
  tests/baselines/reference/thisInInvalidContextsExternalModule.js
  tests/baselines/reference/thisInSuperCall.js
  tests/baselines/reference/thisInSuperCall2.js
  tests/baselines/reference/usingDeclarations.1(target=es5).js
  tests/baselines/reference/usingDeclarations.11.js
  tests/baselines/reference/validUseOfThisInSuper.js
  tests/cases/compiler/nestedSuperCallEmit.ts
Labels: Author: Team, For Milestone Bug

#56148 Fix for #56119 - Update JSDoc for TypedArrays
  src/lib/es2023.array.d.ts
Labels: For Backlog Bug

#56190 Explicitly declare type=commonjs in package.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#55877 fix(55796): JSDoc does not support @this when using an arrow function as method in class
  src/compiler/checker.ts
  tests/baselines/reference/thisTag3.errors.txt
  tests/baselines/reference/thisTag3.symbols
  tests/baselines/reference/thisTag3.types
  tests/cases/conformance/jsdoc/thisTag3.ts
Labels: For Backlog Bug

#56193 Expose TypeChecker.getMergedSymbol to public (#56192)
  src/compiler/types.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Backlog Bug

#51721 When caching type references cache the tracked symbols so they can be emitted in the d.ts file
  src/compiler/checker.ts
  src/compiler/types.ts
  src/testRunner/unittests/tsc/incremental.ts
  tests/baselines/reference/tsc/incremental/generates-typerefs-correctly.js
Labels: Author: Team, For Milestone Bug

#56198 Fix incorrect flags in modifierFlagsCache
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/services/codefixes/fixSpelling.ts
  src/testRunner/unittests/publicApi.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Milestone Bug

#55856 Fixed an issue with string mappings over generic intersections not being deferred in conditional types
  src/compiler/checker.ts
  tests/baselines/reference/stringMappingDeferralInConditionalTypes.symbols
  tests/baselines/reference/stringMappingDeferralInConditionalTypes.types
  tests/cases/conformance/types/literal/stringMappingDeferralInConditionalTypes.ts
Labels: For Backlog Bug

#51196 Filter possible contextual return types from unions for async functions and generators
  src/compiler/checker.ts
  tests/baselines/reference/contextualTypeOnYield1.types
  tests/baselines/reference/contextualTypeOnYield2.types
  tests/baselines/reference/contextuallyTypeAsyncFunctionReturnType.symbols
  tests/baselines/reference/contextuallyTypeAsyncFunctionReturnType.types
  tests/baselines/reference/contextuallyTypeAsyncFunctionReturnTypeFromUnion.symbols
  tests/baselines/reference/contextuallyTypeAsyncFunctionReturnTypeFromUnion.types
  tests/baselines/reference/contextuallyTypeGeneratorReturnTypeFromUnion.symbols
  tests/baselines/reference/contextuallyTypeGeneratorReturnTypeFromUnion.types
  tests/baselines/reference/generatorYieldContextualType.symbols
  tests/baselines/reference/generatorYieldContextualType.types
  tests/baselines/reference/noImplicitReturnsExclusions.errors.txt
  tests/baselines/reference/noImplicitReturnsExclusions.symbols
  tests/baselines/reference/noImplicitReturnsExclusions.types
  tests/baselines/reference/typeOfYieldWithUnionInContextualReturnType.js
  tests/baselines/reference/typeOfYieldWithUnionInContextualReturnType.symbols
  tests/baselines/reference/typeOfYieldWithUnionInContextualReturnType.types
  tests/cases/compiler/contextuallyTypeAsyncFunctionReturnTypeFromUnion.ts
  tests/cases/compiler/contextuallyTypeGeneratorReturnTypeFromUnion.ts
  tests/cases/compiler/noImplicitReturnsExclusions.ts
  tests/cases/compiler/typeOfYieldWithUnionInContextualReturnType.ts
  tests/cases/conformance/generators/generatorYieldContextualType.ts
  tests/cases/conformance/types/contextualTypes/asyncFunctions/contextuallyTypeAsyncFunctionReturnType.ts
Labels: For Milestone Bug

#56211 Hash-pin GitHub Actions, use dependabot to update them
  .github/dependabot.yml
  .github/workflows/accept-baselines-fix-lints.yaml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/new-release-branch.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release-branch-artifact.yaml
  .github/workflows/rich-navigation.yml
  .github/workflows/scorecard.yml
  .github/workflows/set-version.yaml
  .github/workflows/sync-branch.yaml
  .github/workflows/sync-wiki.yml
  .github/workflows/twoslash-repros.yaml
  .github/workflows/update-package-lock.yaml
Labels: For Backlog Bug

#55712 Add conditions to check for class extension or implementation of prim…
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/classExtendingPrimitive.errors.txt
  tests/baselines/reference/classImplementsPrimitive.errors.txt
  tests/baselines/reference/classImplementsPrimitive.js
  tests/baselines/reference/classImplementsPrimitive.symbols
  tests/baselines/reference/classImplementsPrimitive.types
  tests/baselines/reference/errorLocationForInterfaceExtension.errors.txt
  tests/baselines/reference/interfacedeclWithIndexerErrors.errors.txt
  tests/baselines/reference/topLevelAwaitErrors.1(module=es2022).errors.txt
  tests/baselines/reference/topLevelAwaitErrors.1(module=esnext).errors.txt
  tests/cases/compiler/classImplementsPrimitive.ts
Labels: For Uncommitted Bug

#55859 Ensure all JSX spread properties get visited in ES2018+
  src/compiler/transformers/jsx.ts
  tests/baselines/reference/jsxSpreadTag(target=es2015).errors.txt
  tests/baselines/reference/jsxSpreadTag(target=es2015).js
  tests/baselines/reference/jsxSpreadTag(target=es2015).symbols
  tests/baselines/reference/jsxSpreadTag(target=es2015).types
  tests/baselines/reference/jsxSpreadTag(target=esnext).errors.txt
  tests/baselines/reference/jsxSpreadTag(target=esnext).js
  tests/baselines/reference/jsxSpreadTag(target=esnext).symbols
  tests/baselines/reference/jsxSpreadTag(target=esnext).types
  tests/cases/compiler/jsxSpreadTag.ts
Labels: For Milestone Bug

#56139 fix(55939): JS Doc comment not shown in signature help when overload tag exists
  src/services/jsDoc.ts
  tests/baselines/reference/quickInfoJsDocTags13.baseline
  tests/cases/fourslash/quickInfoJsDocTags13.ts
Labels: For Milestone Bug

#56131 fix54035, extractType now allows parts of union and intersection types to be extracted
  src/services/refactors/extractType.ts
  tests/cases/fourslash/refactorExtractType78.ts
  tests/cases/fourslash/refactorExtractType79.ts
  tests/cases/fourslash/refactorExtractType80.ts
  tests/cases/fourslash/refactorExtractType81.ts
  tests/cases/fourslash/refactorExtractType82.ts
  tests/cases/fourslash/refactorExtractType83.ts
  tests/cases/fourslash/refactorExtractType84.ts
  tests/cases/fourslash/refactorExtractType85.ts
  tests/cases/fourslash/refactorExtractType86.ts
  tests/cases/fourslash/refactorExtractType87.ts
  tests/cases/fourslash/refactorExtractType88.ts
  tests/cases/fourslash/refactorExtractType_js9.ts
Labels: Author: Team, For Milestone Bug

#52642 add pushTypeResolution to getTypeOfAlias
  src/compiler/checker.ts
  tests/baselines/reference/pushTypeGetTypeOfAlias.errors.txt
  tests/baselines/reference/pushTypeGetTypeOfAlias.symbols
  tests/baselines/reference/pushTypeGetTypeOfAlias.types
  tests/baselines/reference/recursiveExportAssignmentAndFindAliasedType7.types
  tests/cases/compiler/pushTypeGetTypeOfAlias.ts
Labels: Author: Team, For Milestone Bug

#56237 Revert "Explicitly declare type=commonjs in package.json (#56190)"
  package.json
Labels: Author: Team, For Uncommitted Bug

#56163 Update dprint and plugins
  .dprint.jsonc
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#56187 fix(55237): TypeScript 5.2 "move to file" results in duplicate imports
  src/services/refactors/moveToFile.ts
  tests/cases/fourslash/moveToFile_existingImports1.ts
  tests/cases/fourslash/moveToFile_existingImports2.ts
  tests/cases/fourslash/moveToFile_existingImports3.ts
  tests/cases/fourslash/moveToFile_existingImports4.ts
Labels: For Milestone Bug

#56263 Add dependabot to pr_owners
  .github/pr_owners.txt
Labels: Author: Team, For Uncommitted Bug

#56265 Fix declaration emit in `--moduleResolution bundler` using wrong exports conditions
  src/compiler/moduleNameResolver.ts
  src/compiler/moduleSpecifiers.ts
  src/services/stringCompletions.ts
  tests/baselines/reference/declarationEmitBundlerConditions.js
  tests/cases/compiler/declarationEmitBundlerConditions.ts
Labels: Author: Team, For Milestone Bug

#55558 Allow of in `await using` declarations in for-of loops
  src/compiler/parser.ts
  tests/baselines/reference/awaitUsingDeclarationsInForAwaitOf.2.errors.txt
  tests/baselines/reference/awaitUsingDeclarationsInForAwaitOf.2.js
  tests/baselines/reference/awaitUsingDeclarationsInForOf.2.errors.txt
  tests/baselines/reference/awaitUsingDeclarationsInForOf.2.js
  tests/baselines/reference/awaitUsingDeclarationsInForOf.4.errors.txt
  tests/baselines/reference/awaitUsingDeclarationsInForOf.4.js
  tests/cases/conformance/statements/VariableStatements/usingDeclarations/awaitUsingDeclarationsInForAwaitOf.2.ts
  tests/cases/conformance/statements/VariableStatements/usingDeclarations/awaitUsingDeclarationsInForOf.4.ts
Labels: For Milestone Bug
