Repository microsoft/TypeScript, pull requests merged in 2023-04, with the labels that each got.

#53607 Explicit `undefined` return type checked similar to explicit `void` return type
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/services/codefixes/returnValueCorrect.ts
  tests/baselines/reference/ParameterList5.errors.txt
  tests/baselines/reference/asyncFunctionDeclaration15_es5.errors.txt
  tests/baselines/reference/asyncFunctionDeclaration15_es6.errors.txt
  tests/baselines/reference/conflictingTypeAnnotatedVar.errors.txt
  tests/baselines/reference/controlFlowGenericTypes.errors.txt
  tests/baselines/reference/errorOnContextuallyTypedReturnType.errors.txt
  tests/baselines/reference/errorOnFunctionReturnType.errors.txt
  tests/baselines/reference/functionImplementationErrors.errors.txt
  tests/baselines/reference/functionsMissingReturnStatementsAndExpressions.errors.txt
  tests/baselines/reference/functionsMissingReturnStatementsAndExpressions.js
  tests/baselines/reference/functionsMissingReturnStatementsAndExpressions.symbols
  tests/baselines/reference/functionsMissingReturnStatementsAndExpressions.types
  tests/baselines/reference/functionsMissingReturnStatementsAndExpressionsStrictNullChecks.errors.txt
  tests/baselines/reference/functionsMissingReturnStatementsAndExpressionsStrictNullChecks.js
  tests/baselines/reference/functionsMissingReturnStatementsAndExpressionsStrictNullChecks.symbols
  tests/baselines/reference/functionsMissingReturnStatementsAndExpressionsStrictNullChecks.types
  tests/baselines/reference/invalidReturnStatements.errors.txt
  tests/baselines/reference/jsdocFunction_missingReturn.errors.txt
  tests/baselines/reference/jsdocOuterTypeParameters2.errors.txt
  tests/baselines/reference/methodInAmbientClass1.errors.txt
  tests/baselines/reference/missingReturnStatement.errors.txt
  tests/baselines/reference/missingReturnStatement1.errors.txt
  tests/baselines/reference/multiLineErrors.errors.txt
  tests/baselines/reference/noImplicitReturnsExclusions.errors.txt
  tests/baselines/reference/noImplicitReturnsExclusions.symbols
  tests/baselines/reference/noImplicitReturnsExclusions.types
  tests/baselines/reference/parseInvalidNonNullableTypes.errors.txt
  tests/baselines/reference/parserErrorRecovery_Block3.errors.txt
  tests/baselines/reference/parserParameterList5.errors.txt
  tests/baselines/reference/reachabilityChecks5.errors.txt
  tests/baselines/reference/reachabilityChecks7.errors.txt
  tests/baselines/reference/recursiveFunctionTypes.errors.txt
  tests/baselines/reference/returnTypeParameter.errors.txt
  tests/baselines/reference/unknownType1.errors.txt
  tests/cases/compiler/functionsMissingReturnStatementsAndExpressions.ts
  tests/cases/compiler/functionsMissingReturnStatementsAndExpressionsStrictNullChecks.ts
  tests/cases/compiler/noImplicitReturnsExclusions.ts
Labels: Author: Team, For Milestone Bug

#53341 More complete check in isConstTypeVariable
  src/compiler/checker.ts
  tests/baselines/reference/typeParameterConstModifiers.errors.txt
  tests/baselines/reference/typeParameterConstModifiers.js
  tests/baselines/reference/typeParameterConstModifiers.symbols
  tests/baselines/reference/typeParameterConstModifiers.types
  tests/cases/conformance/types/typeParameters/typeParameterLists/typeParameterConstModifiers.ts
Labels: Author: Team, For Milestone Bug

#52840 fix(52828): No signature help in parameter declaration before , and )
  src/services/signatureHelp.ts
  tests/baselines/reference/signatureHelpAfterParameter.baseline
  tests/cases/fourslash/signatureHelpAfterParameter.ts
Labels: For Uncommitted Bug

#53653 More directory patterns for testing that we will care about
  src/testRunner/unittests/canWatch.ts
  tests/baselines/reference/canWatch/canWatchAffectingLocationDos.baseline.md
  tests/baselines/reference/canWatch/canWatchAffectingLocationPosix.baseline.md
  tests/baselines/reference/canWatch/canWatchAffectingLocationUnc.baseline.md
  tests/baselines/reference/canWatch/canWatchAffectingLocationUncDos.baseline.md
  tests/baselines/reference/canWatch/canWatchAtTypesDos.baseline.md
  tests/baselines/reference/canWatch/canWatchAtTypesPosix.baseline.md
  tests/baselines/reference/canWatch/canWatchAtTypesUnc.baseline.md
  tests/baselines/reference/canWatch/canWatchAtTypesUncDos.baseline.md
  tests/baselines/reference/canWatch/canWatchDirectoryOrFileDos.baseline.md
  tests/baselines/reference/canWatch/canWatchDirectoryOrFilePosix.baseline.md
  tests/baselines/reference/canWatch/canWatchDirectoryOrFileUnc.baseline.md
  tests/baselines/reference/canWatch/canWatchDirectoryOrFileUncDos.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationAtTypesDos.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationAtTypesPosix.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationAtTypesUnc.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationAtTypesUncDos.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationDos.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationFromTypeRootDos.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationFromTypeRootPosix.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationFromTypeRootUnc.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationFromTypeRootUncDos.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationNodeModulesDos.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationNodeModulesPosix.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationNodeModulesUnc.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationNodeModulesUncDos.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationPosix.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationUnc.baseline.md
  tests/baselines/reference/canWatch/getDirectoryToWatchFailedLookupLocationUncDos.baseline.md
Labels: Author: Team, For Uncommitted Bug

#53652 DOM update 2023-04-23
  src/lib/dom.generated.d.ts
  src/lib/dom.iterable.generated.d.ts
  src/lib/webworker.generated.d.ts
  src/lib/webworker.iterable.generated.d.ts
  tests/baselines/reference/globalThisBlockscopedProperties.types
  tests/baselines/reference/mappedTypeRecursiveInference.types
Labels: Author: Team, For Uncommitted Bug

#53260 Provide snippet completions for @param in JSDoc
  src/compiler/checker.ts
  src/services/completions.ts
  tests/baselines/reference/jsdocParameterTagSnippetCompletion1.baseline
  tests/baselines/reference/jsdocParameterTagSnippetCompletion2.baseline
  tests/baselines/reference/jsdocParameterTagSnippetCompletion3.baseline
  tests/cases/fourslash/jsdocParameterTagSnippetCompletion1.ts
  tests/cases/fourslash/jsdocParameterTagSnippetCompletion2.ts
  tests/cases/fourslash/jsdocParameterTagSnippetCompletion3.ts
Labels: Author: Team, For Milestone Bug

#53665 Fix crash when private id in array assignment
  src/compiler/transformers/classFields.ts
  tests/baselines/reference/parserPrivateIdentifierInArrayAssignment.errors.txt
  tests/baselines/reference/parserPrivateIdentifierInArrayAssignment.js
  tests/baselines/reference/parserPrivateIdentifierInArrayAssignment.symbols
  tests/baselines/reference/parserPrivateIdentifierInArrayAssignment.types
  tests/cases/compiler/parserPrivateIdentifierInArrayAssignment.ts
Labels: Author: Team, For Uncommitted Bug

#53666 Disable JSX recovery hack when in unary expression context
  src/compiler/parser.ts
  tests/baselines/reference/parseJsxElementInUnaryExpressionNoCrash1.errors.txt
  tests/baselines/reference/parseJsxElementInUnaryExpressionNoCrash1.js
  tests/baselines/reference/parseJsxElementInUnaryExpressionNoCrash1.symbols
  tests/baselines/reference/parseJsxElementInUnaryExpressionNoCrash1.types
  tests/baselines/reference/parseJsxElementInUnaryExpressionNoCrash2.errors.txt
  tests/baselines/reference/parseJsxElementInUnaryExpressionNoCrash2.js
  tests/baselines/reference/parseJsxElementInUnaryExpressionNoCrash2.symbols
  tests/baselines/reference/parseJsxElementInUnaryExpressionNoCrash2.types
  tests/cases/compiler/parseJsxElementInUnaryExpressionNoCrash1.ts
  tests/cases/compiler/parseJsxElementInUnaryExpressionNoCrash2.ts
Labels: Author: Team, For Milestone Bug

#53674 Fix crash in parseJsxChild found by fuzzing
  src/compiler/parser.ts
  tests/baselines/reference/parseJsxElementInUnaryExpressionNoCrash3.errors.txt
  tests/baselines/reference/parseJsxElementInUnaryExpressionNoCrash3.js
  tests/baselines/reference/parseJsxElementInUnaryExpressionNoCrash3.symbols
  tests/baselines/reference/parseJsxElementInUnaryExpressionNoCrash3.types
  tests/cases/compiler/parseJsxElementInUnaryExpressionNoCrash3.ts
Labels: Author: Team, For Uncommitted Bug

#53611 Remove error on redundant isolatedModules/verbatimModuleSyntax combination
  src/compiler/program.ts
  tests/baselines/reference/transpile/Does not support setting isolatedModules (verbatimModuleSyntax=true).errors.txt
  tests/baselines/reference/transpile/Does not support setting isolatedModules (verbatimModuleSyntax=true).oldTranspile.errors.txt
  tests/baselines/reference/verbatimModuleSyntaxCompat.errors.txt
  tests/baselines/reference/verbatimModuleSyntaxCompat2.errors.txt
  tests/baselines/reference/verbatimModuleSyntaxCompat4.errors.txt
Labels: Author: Team, For Milestone Bug

#53691 Fix two module specifier ending preference detection issues
  src/compiler/moduleSpecifiers.ts
  src/compiler/utilities.ts
  tests/cases/fourslash/importNameCodeFixInferEndingPreference.ts
  tests/cases/fourslash/importNameCodeFixInferEndingPreference_classic.ts
Labels: Author: Team, For Milestone Bug

#53682 Reuse operandType in checkPrefixUnaryExpression
  src/compiler/checker.ts
  tests/baselines/reference/nestedUnaryExpressionHang.errors.txt
  tests/baselines/reference/nestedUnaryExpressionHang.js
  tests/baselines/reference/nestedUnaryExpressionHang.symbols
  tests/baselines/reference/nestedUnaryExpressionHang.types
  tests/cases/compiler/nestedUnaryExpressionHang.ts
Labels: Author: Team, For Uncommitted Bug

#53394 export TypingsInstaller from tsserverlibrary
  src/jsTyping/jsTyping.ts
  src/jsTyping/types.ts
  src/server/_namespaces/ts.server.ts
  src/server/tsconfig.json
  src/typingsInstallerCore/typingsInstaller.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Uncommitted Bug

#53667 Detect malformed UTF-8 files and refuse to engage further
  src/compiler/diagnosticMessages.json
  src/compiler/program.ts
  src/compiler/scanner.ts
  src/compiler/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/corrupted.errors.txt
  tests/baselines/reference/corrupted.js
  tests/baselines/reference/corrupted.symbols
  tests/baselines/reference/corrupted.types
  tests/cases/compiler/corrupted.ts
Labels: Author: Team, For Uncommitted Bug

#53284 Adds linked editing for JSX tags
  src/harness/client.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/harness/harnessLanguageService.ts
  src/server/protocol.ts
  src/server/session.ts
  src/services/services.ts
  src/services/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/linkedEditingJsxTag1.ts
  tests/cases/fourslash/linkedEditingJsxTag10.ts
  tests/cases/fourslash/linkedEditingJsxTag2.ts
  tests/cases/fourslash/linkedEditingJsxTag3.ts
  tests/cases/fourslash/linkedEditingJsxTag4.ts
  tests/cases/fourslash/linkedEditingJsxTag5.ts
  tests/cases/fourslash/linkedEditingJsxTag6.ts
  tests/cases/fourslash/linkedEditingJsxTag7.ts
  tests/cases/fourslash/linkedEditingJsxTag8.ts
  tests/cases/fourslash/linkedEditingJsxTag9.ts
Labels: lib update, For Milestone Bug

#52484 fix ordering of code fix import with triple-slash directives
  src/compiler/utilities.ts
  tests/baselines/reference/libReferenceDeclarationEmit.js
  tests/baselines/reference/libReferenceDeclarationEmitBundle.js
  tests/baselines/reference/libReferenceNoLib.js
  tests/baselines/reference/libReferenceNoLibBundle.js
  tests/cases/fourslash/importNameCodeFix_tripleSlashOrdering.ts
Labels: For Backlog Bug

#52860 infer from usages: support short-circuiting assignment operators
  src/services/codefixes/inferFromUsage.ts
  tests/cases/fourslash/codeFixInferFromUsageAllAssignments.ts
Labels: For Uncommitted Bug

#53728 Update more tests for paths
  src/testRunner/unittests/tscWatch/resolutionCache.ts
  src/testRunner/unittests/tsserver/resolutionCache.ts
  tests/baselines/reference/tscWatch/resolutionCache/caching-works.js
  tests/baselines/reference/tscWatch/resolutionCache/loads-missing-files-from-disk.js
  tests/baselines/reference/tscWatch/resolutionCache/should-compile-correctly-when-resolved-module-goes-missing-and-then-comes-back.js
  tests/baselines/reference/tscWatch/resolutionCache/works-when-included-file-with-ambient-module-changes.js
  tests/baselines/reference/tsserver/resolutionCache/not-sharing-across-references.js
  tests/baselines/reference/tsserver/resolutionCache/sharing-across-references.js
Labels: Author: Team, For Uncommitted Bug

#50092 fix(19577): fix regression with fully inferred types and non-null assertions
  src/compiler/checker.ts
  tests/baselines/reference/nonNullFullInference.js
  tests/baselines/reference/nonNullFullInference.symbols
  tests/baselines/reference/nonNullFullInference.types
  tests/cases/compiler/nonNullFullInference.ts
Labels: For Backlog Bug

#53741 Declare `reportError` as returning `never` in fourslash
  src/harness/fourslashImpl.ts
Labels: Author: Team, For Uncommitted Bug

#53549 Reset type resolution stack when starting to compute variance
  src/compiler/checker.ts
  tests/baselines/reference/classVarianceResolveCircularity.errors.txt
  tests/baselines/reference/classVarianceResolveCircularity.symbols
  tests/baselines/reference/classVarianceResolveCircularity1.js
  tests/baselines/reference/classVarianceResolveCircularity1.symbols
  tests/baselines/reference/classVarianceResolveCircularity1.types
  tests/baselines/reference/classVarianceResolveCircularity2.js
  tests/baselines/reference/classVarianceResolveCircularity2.symbols
  tests/baselines/reference/classVarianceResolveCircularity2.types
  tests/cases/compiler/classVarianceResolveCircularity1.ts
  tests/cases/compiler/classVarianceResolveCircularity2.ts
Labels: Author: Team, For Uncommitted Bug

#53487 Ensure findPrecedingToken recurses into JSDoc children when needed
  src/services/utilities.ts
  src/testRunner/tests.ts
  src/testRunner/unittests/services/utilities.ts
Labels: Author: Team, For Milestone Bug

#53511 add Intl.supportedValuesOf
  src/lib/es2022.intl.d.ts
  tests/baselines/reference/es2022IntlAPIs.js
  tests/baselines/reference/es2022IntlAPIs.symbols
  tests/baselines/reference/es2022IntlAPIs.types
  tests/cases/conformance/es2022/es2022IntlAPIs.ts
Labels: For Milestone Bug

#53625 Removed unnecessary use-before-define error for const enums
  src/compiler/checker.ts
  tests/baselines/reference/blockScopedEnumVariablesUseBeforeDef_preserve.errors.txt
  tests/baselines/reference/blockScopedEnumVariablesUseBeforeDef_preserve.js
  tests/baselines/reference/blockScopedEnumVariablesUseBeforeDef_preserve.symbols
  tests/baselines/reference/blockScopedEnumVariablesUseBeforeDef_preserve.types
  tests/cases/compiler/blockScopedEnumVariablesUseBeforeDef_preserve.ts
Labels: For Backlog Bug

#50453 lib Fix Part 5/6 – Function.{apply, bind}
  src/lib/es5.d.ts
  tests/baselines/reference/strictBindCallApply1.errors.txt
  tests/baselines/reference/strictBindCallApply1.symbols
  tests/baselines/reference/strictBindCallApply1.types
  tests/baselines/reference/strictBindCallApply2.symbols
  tests/baselines/reference/strictBindCallApply2.types
Labels: For Backlog Bug

#53733 Allow custom switch-case indentation in formatting
  src/server/protocol.ts
  src/services/formatting/smartIndenter.ts
  src/services/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/tsserver/formatSettings/works-when-extends-is-specified-with-a-case-insensitive-file-system.js
  tests/cases/fourslash/formattingIndentSwitchCase.ts
  tests/cases/fourslash/fourslash.ts
Labels: For Backlog Bug

#52445 Fix transform flags for certain ES2020 features.
  src/compiler/factory/nodeFactory.ts
Labels: Author: Team, For Uncommitted Bug

#53164 fix(53138): go-to-definition not working on expression of SatisfiesExpression
  src/services/goToDefinition.ts
  tests/baselines/reference/goToDefinitionSatisfiesExpression1.baseline.jsonc
  tests/cases/fourslash/goToDefinitionSatisfiesExpression1.ts
Labels: For Backlog Bug

#53771 Optimize union type creation
  src/compiler/checker.ts
Labels: Author: Team, For Milestone Bug

#51328 RFC: Consult new JSX.ElementType for valid JSX element types
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/jsxElementType.errors.txt
  tests/baselines/reference/jsxElementType.js
  tests/baselines/reference/jsxElementType.symbols
  tests/baselines/reference/jsxElementType.types
  tests/baselines/reference/jsxElementTypeLiteral.errors.txt
  tests/baselines/reference/jsxElementTypeLiteral.js
  tests/baselines/reference/jsxElementTypeLiteral.symbols
  tests/baselines/reference/jsxElementTypeLiteral.types
  tests/cases/compiler/jsxElementType.tsx
  tests/cases/compiler/jsxElementTypeLiteral.tsx
Labels: For Milestone Bug, For Backlog Bug

#53756 Exclude parameters of non-inferrable signatures from inference
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/nonInferrableTypePropagation3.symbols
  tests/baselines/reference/nonInferrableTypePropagation3.types
  tests/cases/compiler/nonInferrableTypePropagation3.ts
Labels: Author: Team, For Milestone Bug

#53248 Force add lib in workflows which commit LKG
  .github/workflows/new-release-branch.yaml
  .github/workflows/set-version.yaml
  .github/workflows/update-lkg.yml
Labels: Author: Team, For Uncommitted Bug

#47356 feat(7411): JSX namespaced attribute syntax not supported
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/emitter.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/factory/nodeTests.ts
  src/compiler/parser.ts
  src/compiler/scanner.ts
  src/compiler/transformers/jsx.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/compiler/utilitiesPublic.ts
  src/compiler/visitorPublic.ts
  src/services/codefixes/fixAddMissingMember.ts
  src/services/completions.ts
  src/services/stringCompletions.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/checkJsxNamespaceNamesQuestionableForms.errors.txt
  tests/baselines/reference/checkJsxNamespaceNamesQuestionableForms.symbols
  tests/baselines/reference/checkJsxNamespaceNamesQuestionableForms.types
  tests/baselines/reference/jsxEsprimaFbTestSuite.types
  tests/baselines/reference/jsxInvalidEsprimaTestSuite.errors.txt
  tests/baselines/reference/jsxInvalidEsprimaTestSuite.js
  tests/baselines/reference/jsxInvalidEsprimaTestSuite.types
  tests/baselines/reference/jsxNamespacePrefixInName.errors.txt
  tests/baselines/reference/jsxNamespacePrefixInName.js
  tests/baselines/reference/jsxNamespacePrefixInName.symbols
  tests/baselines/reference/jsxNamespacePrefixInName.types
  tests/baselines/reference/jsxNamespacePrefixInNameReact.errors.txt
  tests/baselines/reference/jsxNamespacePrefixInNameReact.js
  tests/baselines/reference/jsxNamespacePrefixInNameReact.symbols
  tests/baselines/reference/jsxNamespacePrefixInNameReact.types
  tests/baselines/reference/jsxNamespacePrefixIntrinsics.errors.txt
  tests/baselines/reference/jsxNamespacePrefixIntrinsics.symbols
  tests/baselines/reference/jsxNamespacePrefixIntrinsics.types
  tests/baselines/reference/tsxNamespacedAttributeName1.js
  tests/baselines/reference/tsxNamespacedAttributeName1.symbols
  tests/baselines/reference/tsxNamespacedAttributeName1.types
  tests/baselines/reference/tsxNamespacedAttributeName2.js
  tests/baselines/reference/tsxNamespacedAttributeName2.symbols
  tests/baselines/reference/tsxNamespacedAttributeName2.types
  tests/baselines/reference/tsxNamespacedTagName1.js
  tests/baselines/reference/tsxNamespacedTagName1.symbols
  tests/baselines/reference/tsxNamespacedTagName1.types
  tests/baselines/reference/tsxNamespacedTagName2.errors.txt
  tests/baselines/reference/tsxNamespacedTagName2.js
  tests/baselines/reference/tsxNamespacedTagName2.symbols
  tests/baselines/reference/tsxNamespacedTagName2.types
  tests/cases/conformance/jsx/tsxNamespacedAttributeName1.tsx
  tests/cases/conformance/jsx/tsxNamespacedAttributeName2.tsx
  tests/cases/conformance/jsx/tsxNamespacedTagName1.tsx
  tests/cases/conformance/jsx/tsxNamespacedTagName2.tsx
Labels: For Backlog Bug

#52690 Don't include completions for current and later parameters
  src/services/completions.ts
  tests/cases/fourslash/completionListInClosedFunction02.ts
  tests/cases/fourslash/completionListInClosedFunction03.ts
  tests/cases/fourslash/completionListInClosedFunction04.ts
  tests/cases/fourslash/completionListInClosedFunction05.ts
  tests/cases/fourslash/completionListInTypeParameterOfClassExpression1.ts
  tests/cases/fourslash/completionListInUnclosedFunction02.ts
  tests/cases/fourslash/completionListInUnclosedFunction03.ts
  tests/cases/fourslash/completionListInUnclosedFunction04.ts
  tests/cases/fourslash/completionListInUnclosedFunction05.ts
  tests/cases/fourslash/completionListInUnclosedFunction06.ts
  tests/cases/fourslash/completionListInUnclosedFunction07.ts
  tests/cases/fourslash/completionListInUnclosedFunction08.ts
  tests/cases/fourslash/completionListInUnclosedFunction09.ts
  tests/cases/fourslash/completionListWithoutVariableinitializer.ts
  tests/cases/fourslash/noCompletionsForCurrentOrLaterParameters.ts
Labels: For Backlog Bug

#53291 Bump minimum Node to 14.17, ES to 2020 for TS 5.1
  Herebyfile.mjs
  package-lock.json
  package.json
  src/tsconfig-base.json
Labels: Breaking Change, Author: Team, For Uncommitted Bug

#53797 Report assignability errors on the `satisfies` keyword
  src/compiler/checker.ts
  src/compiler/utilities.ts
  tests/baselines/reference/checkJsdocSatisfiesTag1.errors.txt
  tests/baselines/reference/checkJsdocSatisfiesTag12.errors.txt
  tests/baselines/reference/checkJsdocSatisfiesTag4.errors.txt
  tests/baselines/reference/typeSatisfaction.errors.txt
  tests/baselines/reference/typeSatisfactionWithDefaultExport.errors.txt
Labels: For Uncommitted Bug

#53801 Propagate `errorType` in `getConditionalType`
  src/compiler/checker.ts
  tests/baselines/reference/excessivelyLargeTupleSpread.errors.txt
  tests/baselines/reference/recursiveConditionalCrash4.errors.txt
  tests/baselines/reference/recursiveConditionalCrash4.symbols
  tests/baselines/reference/recursiveConditionalCrash4.types
  tests/cases/compiler/recursiveConditionalCrash4.ts
Labels: Author: Team, For Uncommitted Bug

#53799 feat(7411): Resolve intrinsics elements by JSX namespaced tag names
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/utilities.ts
  src/services/services.ts
  tests/baselines/reference/jsxElementType.errors.txt
  tests/baselines/reference/jsxElementType.js
  tests/baselines/reference/jsxElementType.symbols
  tests/baselines/reference/jsxElementType.types
  tests/baselines/reference/jsxNamespacePrefixIntrinsics.errors.txt
  tests/baselines/reference/quickInfoOnJsxNamespacedName.baseline
  tests/cases/compiler/jsxElementType.tsx
  tests/cases/fourslash/quickInfoOnJsxNamespacedName.ts
Labels: For Uncommitted Bug

#53794 Properly handle partial union type properties in `isTypePresencePossible`
  src/compiler/checker.ts
  tests/baselines/reference/inKeywordTypeguard(strict=false).errors.txt
  tests/baselines/reference/inKeywordTypeguard(strict=false).js
  tests/baselines/reference/inKeywordTypeguard(strict=false).symbols
  tests/baselines/reference/inKeywordTypeguard(strict=false).types
  tests/baselines/reference/inKeywordTypeguard(strict=true).errors.txt
  tests/baselines/reference/inKeywordTypeguard(strict=true).js
  tests/baselines/reference/inKeywordTypeguard(strict=true).symbols
  tests/baselines/reference/inKeywordTypeguard(strict=true).types
  tests/cases/compiler/inKeywordTypeguard.ts
Labels: Author: Team, For Milestone Bug

#53809 feat(7411): Add additional test cases
  tests/baselines/reference/jsxElementType.errors.txt
  tests/baselines/reference/jsxElementType.js
  tests/baselines/reference/jsxElementType.symbols
  tests/baselines/reference/jsxElementType.types
  tests/cases/compiler/jsxElementType.tsx
Labels: For Uncommitted Bug

#53502 Fixed an issue with JSX children expression not being contextually discriminated
  src/compiler/checker.ts
  tests/baselines/reference/checkJsxChildrenProperty16.symbols
  tests/baselines/reference/checkJsxChildrenProperty16.types
  tests/cases/conformance/jsx/checkJsxChildrenProperty16.tsx
Labels: For Milestone Bug

#53876 feat(7411) - Replace helper to get namespaced name
  src/compiler/binder.ts
Labels: For Uncommitted Bug

#53890 Add tests for importing types from `.d.ts` with explicit extension
  tests/cases/conformance/moduleResolution/allowImportingTypesDtsExtension.ts
Labels: For Uncommitted Bug

#53732 Fix 53482 : Preserve newline/space behavior
  src/compiler/emitter.ts
  tests/cases/fourslash/preserveSpace.ts
Labels: For Backlog Bug

#53882 Instead of clearing out all resolutions and closing all the directory watchers, mark everything as invalidated when changes affect module resolution
  src/compiler/resolutionCache.ts
  src/compiler/watchPublic.ts
  src/server/project.ts
  tests/baselines/reference/tscWatch/programUpdates/updates-emit-on-jsx-option-change.js
  tests/baselines/reference/tscWatch/programUpdates/updates-moduleResolution-when-resolveJsonModule-changes.js
  tests/baselines/reference/tscWatch/projectsWithReferences/on-transitive-references-in-different-folders-with-no-files-clause.js
  tests/baselines/reference/tscWatch/projectsWithReferences/on-transitive-references-in-different-folders.js
  tests/baselines/reference/tscWatch/projectsWithReferences/on-transitive-references.js
  tests/baselines/reference/tsserver/externalProjects/handles-creation-of-external-project-with-jsconfig-before-jsconfig-creation-watcher-is-invoked.js
  tests/baselines/reference/tsserver/inferredProjects/inferred-projects-per-project-root-with-case-sensitive-system.js
  tests/baselines/reference/tsserver/inferredProjects/should-still-retain-configured-project-created-while-opening-the-file.js
  tests/baselines/reference/tsserver/projectsWithReferences/transitive-references-with-edit-on-config-file.js
  tests/baselines/reference/tsserver/projectsWithReferences/trasitive-references-without-files-with-edit-on-config-file.js
  tests/baselines/reference/tsserver/symLinks/module-resolution-when-project-compiles-from-sources.js
  tests/baselines/reference/tsserver/symLinks/module-resolution-with-path-mapping-when-project-compiles-from-sources.js
Labels: Author: Team, For Uncommitted Bug

#53646 fix(53467): extends keyword not suggested inside of generic
  src/services/completions.ts
  tests/cases/fourslash/extendsKeywordCompletion1.ts
  tests/cases/fourslash/extendsKeywordCompletion2.ts
Labels: For Backlog Bug

#53915 Interactive refactor actions
  src/server/protocol.ts
  src/services/refactorProvider.ts
  src/services/services.ts
  src/services/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#53554 Improve contextual completions
  src/services/completions.ts
  tests/cases/fourslash/completionEntryForArgumentConstrainedToString.ts
  tests/cases/fourslash/completionEntryForArrayElementConstrainedToString.ts
  tests/cases/fourslash/completionEntryForArrayElementConstrainedToString2.ts
  tests/cases/fourslash/completionEntryForPropertyConstrainedToString.ts
  tests/cases/fourslash/completionsLiteralFromInferenceWithinInferredType1.ts
  tests/cases/fourslash/completionsLiteralFromInferenceWithinInferredType3.ts
Labels: For Backlog Bug

#53935 Add iisaduan to pr_owners.txt
  .github/pr_owners.txt
Labels: Author: Team, For Uncommitted Bug

#53877 Add resolveLibrary method on hosts and store resolvedLibraries in program so that resolutions can be reused
  src/compiler/moduleNameResolver.ts
  src/compiler/program.ts
  src/compiler/resolutionCache.ts
  src/compiler/tsbuildPublic.ts
  src/compiler/types.ts
  src/compiler/watchPublic.ts
  src/server/project.ts
  src/services/services.ts
  src/services/types.ts
  src/testRunner/tests.ts
  src/testRunner/unittests/helpers/contents.ts
  src/testRunner/unittests/helpers/libraryResolution.ts
  src/testRunner/unittests/helpers/tsc.ts
  src/testRunner/unittests/helpers/vfs.ts
  src/testRunner/unittests/reuseProgramStructure.ts
  src/testRunner/unittests/tsbuild/libraryResolution.ts
  src/testRunner/unittests/tsbuildWatch/libraryResolution.ts
  src/testRunner/unittests/tsc/libraryResolution.ts
  src/testRunner/unittests/tscWatch/libraryResolution.ts
  src/testRunner/unittests/tsserver/libraryResolution.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/jsdocInTypeScript.trace.json
  tests/baselines/reference/libTypeScriptOverrideSimple.trace.json
  tests/baselines/reference/libTypeScriptOverrideSimpleConfig.trace.json
  tests/baselines/reference/moduleResolutionWithExtensions_withPaths.trace.json
  tests/baselines/reference/tsbuild/libraryResolution/with-config-with-redirection.js
  tests/baselines/reference/tsbuild/libraryResolution/with-config.js
  tests/baselines/reference/tsbuildWatch/libraryResolution/with-config-with-redirection.js
  tests/baselines/reference/tsbuildWatch/libraryResolution/with-config.js
  tests/baselines/reference/tsc/libraryResolution/with-config-with-redirection.js
  tests/baselines/reference/tsc/libraryResolution/with-config.js
  tests/baselines/reference/tsc/libraryResolution/without-config-with-redirection.js
  tests/baselines/reference/tsc/libraryResolution/without-config.js
  tests/baselines/reference/tscWatch/libraryResolution/with-config-with-redirection.js
  tests/baselines/reference/tscWatch/libraryResolution/with-config.js
  tests/baselines/reference/tscWatch/libraryResolution/without-config-with-redirection.js
  tests/baselines/reference/tscWatch/libraryResolution/without-config.js
  tests/baselines/reference/tsserver/configuredProjects/when-multiple-projects-are-open-detects-correct-default-project.js
  tests/baselines/reference/tsserver/libraryResolution/with-config-with-redirection.js
  tests/baselines/reference/tsserver/libraryResolution/with-config.js
  tests/baselines/reference/typesVersions.ambientModules.trace.json
  tests/baselines/reference/typesVersions.emptyTypes.trace.json
  tests/baselines/reference/typesVersions.justIndex.trace.json
  tests/baselines/reference/typesVersions.multiFile.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.ambient.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFile.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFileBackReferenceToSelf.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFileBackReferenceToUnmapped.trace.json
Labels: Author: Team, For Milestone Bug

#53937 Fix script compilation by pinning back some deps
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#53934 added `wordPattern` Regex to include more characters
  src/services/services.ts
  tests/cases/fourslash/linkedEditingJsxTag1.ts
  tests/cases/fourslash/linkedEditingJsxTag10.ts
  tests/cases/fourslash/linkedEditingJsxTag11.ts
  tests/cases/fourslash/linkedEditingJsxTag2.ts
  tests/cases/fourslash/linkedEditingJsxTag4.ts
  tests/cases/fourslash/linkedEditingJsxTag5.ts
  tests/cases/fourslash/linkedEditingJsxTag6.ts
  tests/cases/fourslash/linkedEditingJsxTag7.ts
  tests/cases/fourslash/linkedEditingJsxTag9.ts
Labels: Author: Team, For Uncommitted Bug

#53705 fix(53645): JSDoc extends doesn't work with multiple lines
  src/compiler/parser.ts
  tests/baselines/reference/extendsTag5.errors.txt
  tests/baselines/reference/extendsTag5.symbols
  tests/baselines/reference/extendsTag5.types
  tests/cases/conformance/jsdoc/extendsTag5.ts
Labels: For Milestone Bug

#53742 fix(53722): Overloaded constructors: 'TValue' not assignable to 'string'
  src/compiler/checker.ts
  tests/baselines/reference/overloadTag3.symbols
  tests/baselines/reference/overloadTag3.types
  tests/cases/conformance/jsdoc/overloadTag3.ts
Labels: For Milestone Bug

#53942 Refactor plugin related code
  src/compiler/sys.ts
  src/compiler/types.ts
  src/harness/harnessLanguageService.ts
  src/server/editorServices.ts
  src/server/project.ts
  src/testRunner/unittests/helpers/virtualFileSystemWithWatch.ts
  src/tsserver/nodeServer.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
Labels: Author: Team, For Uncommitted Bug

#53596 Add quotes when renaming numerical indices
  src/harness/client.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/harness/harnessLanguageService.ts
  src/server/session.ts
  src/services/findAllReferences.ts
  src/services/services.ts
  src/services/shims.ts
  src/services/types.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/renameNumericalIndex.baseline.jsonc
  tests/baselines/reference/renameNumericalIndexSingleQuoted.baseline.jsonc
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/renameNumericalIndex.ts
  tests/cases/fourslash/renameNumericalIndexSingleQuoted.ts
Labels: For Backlog Bug

#53542 'Move to file' refactor
  src/compiler/diagnosticMessages.json
  src/compiler/moduleSpecifiers.ts
  src/compiler/types.ts
  src/harness/client.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/harness/harnessLanguageService.ts
  src/server/protocol.ts
  src/server/session.ts
  src/services/_namespaces/ts.refactor.ts
  src/services/refactorProvider.ts
  src/services/refactors/moveToFile.ts
  src/services/refactors/moveToNewFile.ts
  src/services/services.ts
  src/services/textChanges.ts
  src/services/types.ts
  src/services/utilities.ts
  src/testRunner/tests.ts
  src/testRunner/unittests/tsserver/getMoveToRefactoringFileSuggestions.ts
  src/testRunner/unittests/tsserver/refactors.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/tsserver/getMoveToRefactoringFileSuggestions/skips-lib.d.ts-files.js
  tests/baselines/reference/tsserver/getMoveToRefactoringFileSuggestions/suggests-only-.js-file-for-a-.js-filepath.js
  tests/baselines/reference/tsserver/getMoveToRefactoringFileSuggestions/suggests-only-.ts-file-for-a-.ts-filepath.js
  tests/baselines/reference/tsserver/getMoveToRefactoringFileSuggestions/works-for-suggesting-a-list-of-files,-excluding-node_modules-within-a-project.js
  tests/baselines/reference/tsserver/getMoveToRefactoringFileSuggestions/works-for-suggesting-a-list-of-files,-for-a-file-belonging-to-multiple-projects.js
  tests/baselines/reference/tsserver/getMoveToRefactoringFileSuggestions/works-for-suggesting-a-list-of-files,-for-an-inferred-project-for-a-.js-file.js
  tests/baselines/reference/tsserver/getMoveToRefactoringFileSuggestions/works-for-suggesting-a-list-of-files,-for-an-inferred-project-for-a-.ts-file.js
  tests/baselines/reference/tsserver/getMoveToRefactoringFileSuggestions/works-with-different-.ts-extensions.js
  tests/baselines/reference/tsserver/getMoveToRefactoringFileSuggestions/works-with-different-extensions.js
  tests/baselines/reference/tsserver/refactors/handles-moving-statement-to-an-existing-file.js
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/moveToFile_addImportFromTargetFile.ts
  tests/cases/fourslash/moveToFile_blankExistingFile.ts
  tests/cases/fourslash/moveToFile_ctsTomts.ts
  tests/cases/fourslash/moveToFile_differentDirectories.ts
  tests/cases/fourslash/moveToFile_differentDirectories2.ts
  tests/cases/fourslash/moveToFile_impossibleImport.ts
  tests/cases/fourslash/moveToFile_multipleStatements.ts
  tests/cases/fourslash/moveToFile_namedImports.ts
  tests/cases/fourslash/moveToFile_newFile.ts
  tests/cases/fourslash/moveToFile_noImportExport.ts
  tests/cases/fourslash/moveToFile_nonExportedImports.ts
  tests/cases/fourslash/moveToFile_requireImport.ts
  tests/cases/fourslash/moveToFile_requireImport2.ts
  tests/cases/fourslash/moveToFile_typeImport.ts
  tests/cases/fourslash/moveToFile_unresolvedImport.ts
Labels: Author: Team, For Milestone Bug

#53957 Ensure paths-based resolution does not generate module specifiers with `..` in the middle
  src/compiler/moduleSpecifiers.ts
  tests/cases/fourslash/server/autoImportCrossPackage_pathsAndSymlink.ts
Labels: Author: Team, For Milestone Bug

#53943 Instantiate generic ElementType declarations
  src/compiler/checker.ts
  tests/baselines/reference/jsxElementTypeLiteralWithGeneric.errors.txt
  tests/baselines/reference/jsxElementTypeLiteralWithGeneric.js
  tests/baselines/reference/jsxElementTypeLiteralWithGeneric.symbols
  tests/baselines/reference/jsxElementTypeLiteralWithGeneric.types
  tests/cases/compiler/jsxElementTypeLiteralWithGeneric.tsx
Labels: Author: Team, For Milestone Bug

#53627 Expose getJSDocCommentsAndTags
  src/compiler/utilities.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Uncommitted Bug

#53768 fix(53735): Definition file generated from javascript is missing getter
  src/compiler/checker.ts
  tests/baselines/reference/accessorDeclarationEmitJs.js
  tests/baselines/reference/accessorDeclarationEmitJs.symbols
  tests/baselines/reference/accessorDeclarationEmitJs.types
  tests/cases/compiler/accessorDeclarationEmitJs.ts
Labels: For Backlog Bug

#53786 fix: add more strict type to Intl.CollatorOptions
  src/lib/es5.d.ts
Labels: For Backlog Bug

#54016 Fix 'var' hoisting in 'if' in SystemJS emit
  src/compiler/transformers/module/system.ts
  tests/baselines/reference/topLevelVarHoistingSystem.js
  tests/cases/conformance/es6/moduleExportsSystem/topLevelVarHoistingSystem.ts
Labels: Author: Team, For Uncommitted Bug

#54019 Add back tests for async plugin that got deleted as part of #51699
  src/testRunner/tests.ts
  src/testRunner/unittests/helpers/virtualFileSystemWithWatch.ts
  src/testRunner/unittests/tsserver/pluginsAsync.ts
  tests/baselines/reference/tsserver/pluginsAsync/adds-external-files.js
  tests/baselines/reference/tsserver/pluginsAsync/plugins-are-not-loaded-immediately.js
  tests/baselines/reference/tsserver/pluginsAsync/plugins-evaluation-in-correct-order-even-if-imports-resolve-out-of-order.js
  tests/baselines/reference/tsserver/pluginsAsync/project-is-closed-before-plugins-are-loaded.js
  tests/baselines/reference/tsserver/pluginsAsync/sends-projectsUpdatedInBackground-event.js
Labels: Author: Team, For Uncommitted Bug

#54025 Close TypingInstaller watches on project close
  src/server/project.ts
  src/testRunner/unittests/helpers/tsserver.ts
  src/testRunner/unittests/tsserver/typingsInstaller.ts
  tests/baselines/reference/tsserver/inferredProjects/inferred-projects-per-project-root-with-case-insensitive-system.js
  tests/baselines/reference/tsserver/inferredProjects/inferred-projects-per-project-root-with-case-sensitive-system.js
  tests/baselines/reference/tsserver/inferredProjects/should-still-retain-configured-project-created-while-opening-the-file.js
  tests/baselines/reference/tsserver/skipLibCheck/jsonly-inferred-project.js
  tests/baselines/reference/tsserver/typingsInstaller/multiple-projects.js
Labels: Author: Team, For Uncommitted Bug

#53980 Fixed JSX attributes discriminating based on optional children
  src/compiler/checker.ts
  tests/baselines/reference/contextuallyTypedJsxChildren.symbols
  tests/baselines/reference/contextuallyTypedJsxChildren.types
  tests/cases/compiler/contextuallyTypedJsxChildren.tsx
Labels: For Milestone Bug

#54034 Fix callback return type annotation before constructor
  src/compiler/checker.ts
  tests/baselines/reference/callbackOnConstructor.js
  tests/baselines/reference/callbackOnConstructor.symbols
  tests/baselines/reference/callbackOnConstructor.types
  tests/cases/conformance/jsdoc/callbackOnConstructor.ts
Labels: Author: Team, For Milestone Bug

#53808 fix(53754): Re-exported symbol marked with deprecated doesn't get correct deprecation highlighting
  src/compiler/checker.ts
  tests/cases/fourslash/jsdocDeprecated_suggestion20.ts
  tests/cases/fourslash/jsdocDeprecated_suggestion21.ts
Labels: For Backlog Bug

#54044 Bind JSDoc on SemicolonClassElement
  src/compiler/parser.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/typedefOnSemicolonClassElement.js
  tests/baselines/reference/typedefOnSemicolonClassElement.symbols
  tests/baselines/reference/typedefOnSemicolonClassElement.types
  tests/cases/conformance/jsdoc/typedefOnSemicolonClassElement.ts
Labels: Author: Team, For Milestone Bug

#54045 Adding missing parameter
  src/server/session.ts
Labels: Author: Team, For Uncommitted Bug

#54036 Fix 'var' hoisting in 'if' in CJS/AMD emit
  src/compiler/transformers/module/module.ts
  tests/baselines/reference/declarationEmitInvalidExport.js
  tests/baselines/reference/topLevelVarHoistingCommonJS.js
  tests/cases/conformance/es6/moduleExportsSystem/topLevelVarHoistingCommonJS.ts
Labels: Author: Team, For Uncommitted Bug

#54046 Fix class alias reference in static initializer for legacy class decorators
  src/compiler/transformers/legacyDecorators.ts
  tests/baselines/reference/staticInitializersAndLegacyClassDecorators.js
  tests/cases/compiler/staticInitializersAndLegacyClassDecorators.ts
Labels: Author: Team, For Milestone Bug
