Repository microsoft/TypeScript, pull requests merged in 2024-05, with the labels that each got.

#58001 Fixed an issue with `missingType` narrowing by `case undefined` in default cases
  src/compiler/checker.ts
  tests/baselines/reference/narrowBySwitchDiscriminantUndefinedCase1(exactoptionalpropertytypes=false,nouncheckedindexedaccess=false).symbols
  tests/baselines/reference/narrowBySwitchDiscriminantUndefinedCase1(exactoptionalpropertytypes=false,nouncheckedindexedaccess=false).types
  tests/baselines/reference/narrowBySwitchDiscriminantUndefinedCase1(exactoptionalpropertytypes=false,nouncheckedindexedaccess=true).symbols
  tests/baselines/reference/narrowBySwitchDiscriminantUndefinedCase1(exactoptionalpropertytypes=false,nouncheckedindexedaccess=true).types
  tests/baselines/reference/narrowBySwitchDiscriminantUndefinedCase1(exactoptionalpropertytypes=true,nouncheckedindexedaccess=false).symbols
  tests/baselines/reference/narrowBySwitchDiscriminantUndefinedCase1(exactoptionalpropertytypes=true,nouncheckedindexedaccess=false).types
  tests/baselines/reference/narrowBySwitchDiscriminantUndefinedCase1(exactoptionalpropertytypes=true,nouncheckedindexedaccess=true).symbols
  tests/baselines/reference/narrowBySwitchDiscriminantUndefinedCase1(exactoptionalpropertytypes=true,nouncheckedindexedaccess=true).types
  tests/cases/compiler/narrowBySwitchDiscriminantUndefinedCase1.ts
Labels: For Backlog Bug

#58386 Update baselines after PR 58001
  tests/baselines/reference/narrowBySwitchDiscriminantUndefinedCase1(exactoptionalpropertytypes=false,nouncheckedindexedaccess=false).types
  tests/baselines/reference/narrowBySwitchDiscriminantUndefinedCase1(exactoptionalpropertytypes=false,nouncheckedindexedaccess=true).types
  tests/baselines/reference/narrowBySwitchDiscriminantUndefinedCase1(exactoptionalpropertytypes=true,nouncheckedindexedaccess=false).types
  tests/baselines/reference/narrowBySwitchDiscriminantUndefinedCase1(exactoptionalpropertytypes=true,nouncheckedindexedaccess=true).types
Labels: Author: Team, For Uncommitted Bug

#58338 fix(58259): getTextOfJSDocComment is stripping # from JSDoc comment
  src/compiler/utilities.ts
  src/testRunner/unittests/jsDocParsing.ts
Labels: For Uncommitted Bug

#58388 Validate the options passed in are numbers instead of strings for our custom commandline options
  src/compiler/commandLineParser.ts
  src/compiler/program.ts
  src/testRunner/unittests/publicApi.ts
Labels: Author: Team, For Uncommitted Bug

#58403 Disable constraint reduction in intersections created by constraint hoisting
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/intersectionConstraintReduction.symbols
  tests/baselines/reference/intersectionConstraintReduction.types
  tests/baselines/reference/intersectionsOfLargeUnions.types
  tests/baselines/reference/intersectionsOfLargeUnions2.types
  tests/cases/compiler/intersectionConstraintReduction.ts
Labels: Author: Team, For Milestone Bug

#58410 Type alias declarations should not return an effective annotation node
  src/compiler/utilities.ts
  tests/baselines/reference/declarationEmitMergedAliasWithConst.js
  tests/baselines/reference/declarationEmitMergedAliasWithConst.symbols
  tests/baselines/reference/declarationEmitMergedAliasWithConst.types
  tests/cases/compiler/declarationEmitMergedAliasWithConst.ts
Labels: Author: Team, For Milestone Bug

#58418 Fix name generation scoping
  src/compiler/emitter.ts
  src/testRunner/unittests/evaluation/asyncArrow.ts
  tests/baselines/reference/asyncFunctionDeclarationParameterEvaluation(target=es2015).js
  tests/baselines/reference/autoAccessor5(target=es2022).js
  tests/baselines/reference/esDecorators-classDeclaration-commentPreservation(module=commonjs,target=es2022).js
  tests/baselines/reference/esDecorators-classDeclaration-commentPreservation(module=esnext,target=es2022).js
  tests/baselines/reference/esDecorators-classDeclaration-sourceMap(target=es2022).js
  tests/baselines/reference/esDecorators-classDeclaration-sourceMap(target=es2022).js.map
  tests/baselines/reference/esDecorators-classDeclaration-sourceMap(target=es2022).sourcemap.txt
  tests/baselines/reference/esDecorators-classExpression-commentPreservation(target=es2022).js
  tests/baselines/reference/privateNameStaticFieldDestructuredBinding(target=es2015).js
Labels: Author: Team, For Milestone Bug

#58404 Ensure jsDocParsingMode is passed to LanguageService document registry
  src/services/services.ts
Labels: Author: Team, For Uncommitted Bug

#58398 Lazy calculation of expensive file explaining diagnsotics and some caching to be used to share the diagnostic data
  src/compiler/program.ts
  src/compiler/types.ts
  src/compiler/watchPublic.ts
  src/testRunner/unittests/helpers.ts
  src/testRunner/unittests/helpers/forceConsistentCasingInFileNames.ts
  src/testRunner/unittests/helpers/libraryResolution.ts
  src/testRunner/unittests/reuseProgramStructure.ts
  src/testRunner/unittests/tsc/forceConsistentCasingInFileNames.ts
  src/testRunner/unittests/tsc/libraryResolution.ts
  src/testRunner/unittests/tscWatch/forceConsistentCasingInFileNames.ts
  src/testRunner/unittests/tscWatch/libraryResolution.ts
  src/testRunner/unittests/tsserver/forceConsistentCasingInFileNames.ts
  tests/baselines/reference/reuseProgramStructure/can-reuse-ambient-module-declarations-from-non-modified-files.js
  tests/baselines/reference/reuseProgramStructure/can-reuse-module-resolutions-from-non-modified-files.js
  tests/baselines/reference/reuseProgramStructure/change-affects-a-single-module-of-a-package.js
  tests/baselines/reference/reuseProgramStructure/change-affects-imports.js
  tests/baselines/reference/reuseProgramStructure/change-affects-tripleslash-references.js
  tests/baselines/reference/reuseProgramStructure/change-affects-type-directives.js
  tests/baselines/reference/reuseProgramStructure/change-affects-type-references.js
  tests/baselines/reference/reuseProgramStructure/change-does-not-affect-imports-or-type-refs.js
  tests/baselines/reference/reuseProgramStructure/change-doesnot-affect-type-references.js
  tests/baselines/reference/reuseProgramStructure/config-path-changes.js
  tests/baselines/reference/reuseProgramStructure/fetches-imports-after-npm-install.js
  tests/baselines/reference/reuseProgramStructure/handles-file-preprocessing-dignostics-when-diagnostics-are-not-queried.js
  tests/baselines/reference/reuseProgramStructure/handles-file-preprocessing-dignostics.js
  tests/baselines/reference/reuseProgramStructure/missing-file-is-created.js
  tests/baselines/reference/reuseProgramStructure/missing-files-remain-missing.js
  tests/baselines/reference/reuseProgramStructure/module-kind-changes.js
  tests/baselines/reference/reuseProgramStructure/redirect-no-change.js
  tests/baselines/reference/reuseProgramStructure/redirect-previous-duplicate-packages.js
  tests/baselines/reference/reuseProgramStructure/redirect-target-changes.js
  tests/baselines/reference/reuseProgramStructure/redirect-underlying-changes.js
  tests/baselines/reference/reuseProgramStructure/redirect-with-getSourceFileByPath-no-change.js
  tests/baselines/reference/reuseProgramStructure/redirect-with-getSourceFileByPath-previous-duplicate-packages.js
  tests/baselines/reference/reuseProgramStructure/redirect-with-getSourceFileByPath-target-changes.js
  tests/baselines/reference/reuseProgramStructure/redirect-with-getSourceFileByPath-underlying-changes.js
  tests/baselines/reference/reuseProgramStructure/resolution-cache-follows-imports.js
  tests/baselines/reference/reuseProgramStructure/resolved-type-directives-cache-follows-type-directives.js
  tests/baselines/reference/reuseProgramStructure/resolvedImports-after-re-using-an-ambient-external-module-declaration.js
  tests/baselines/reference/reuseProgramStructure/rootdir-changes.js
  tests/baselines/reference/reuseProgramStructure/works-with-updated-SourceFiles.js
  tests/baselines/reference/tsc/forceConsistentCasingInFileNames/when-file-is-included-from-multiple-places-with-different-casing.js
  tests/baselines/reference/tsc/libraryResolution/unknown-lib.js
  tests/baselines/reference/tscWatch/forceConsistentCasingInFileNames/when-file-is-included-from-multiple-places-with-different-casing.js
  tests/baselines/reference/tscWatch/libraryResolution/unknwon-lib.js
  tests/baselines/reference/tsserver/forceConsistentCasingInFileNames/when-file-is-included-from-multiple-places-with-different-casing.js
  tests/baselines/reference/tsserver/watchEnvironment/external-project-watch-options-errors.js
  tests/baselines/reference/tsserver/watchEnvironment/external-project-watch-options-in-host-configuration.js
  tests/baselines/reference/tsserver/watchEnvironment/external-project-watch-options.js
Labels: Author: Team, For Uncommitted Bug

#58392 Avoid getting single call signatures when parameter types are the same
  src/compiler/checker.ts
  tests/baselines/reference/classReferencedInContextualParameterWithinItsOwnBaseExpression.js
  tests/baselines/reference/classReferencedInContextualParameterWithinItsOwnBaseExpression.symbols
  tests/baselines/reference/classReferencedInContextualParameterWithinItsOwnBaseExpression.types
  tests/cases/compiler/classReferencedInContextualParameterWithinItsOwnBaseExpression.ts
Labels: For Uncommitted Bug

#58428 Declaration emit should retain (instead of elide) unresolved computed names
  src/compiler/checker.ts
  src/compiler/transformers/declarations.ts
  src/compiler/types.ts
  tests/baselines/reference/complicatedPrivacy.types
  tests/baselines/reference/giant.errors.txt
  tests/baselines/reference/giant.js
  tests/baselines/reference/giant.symbols
  tests/baselines/reference/giant.types
  tests/baselines/reference/isolatedDeclarationErrorsClasses.errors.txt
  tests/baselines/reference/transpile/declarationTypeWithComputedName.d.ts
  tests/cases/compiler/giant.ts
  tests/cases/transpile/declarationTypeWithComputedName.ts
Labels: Author: Team, For Milestone Bug

#58454 Upgrade to esbuild 0.21
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#58451 Fix tslib resolutions
  src/compiler/checker.ts
  src/compiler/program.ts
  tests/baselines/reference/importHelpersBundler.js
  tests/baselines/reference/importHelpersBundler.symbols
  tests/baselines/reference/importHelpersBundler.types
  tests/baselines/reference/importHelpersCommonJSJavaScript(verbatimmodulesyntax=false).js
  tests/baselines/reference/importHelpersCommonJSJavaScript(verbatimmodulesyntax=false).symbols
  tests/baselines/reference/importHelpersCommonJSJavaScript(verbatimmodulesyntax=false).types
  tests/baselines/reference/importHelpersCommonJSJavaScript(verbatimmodulesyntax=true).js
  tests/baselines/reference/importHelpersCommonJSJavaScript(verbatimmodulesyntax=true).symbols
  tests/baselines/reference/importHelpersCommonJSJavaScript(verbatimmodulesyntax=true).types
  tests/baselines/reference/importHelpersVerbatimModuleSyntax.js
  tests/baselines/reference/importHelpersVerbatimModuleSyntax.symbols
  tests/baselines/reference/importHelpersVerbatimModuleSyntax.types
  tests/cases/compiler/importHelpersBundler.ts
  tests/cases/compiler/importHelpersCommonJSJavaScript.ts
  tests/cases/compiler/importHelpersVerbatimModuleSyntax.ts
Labels: Author: Team, For Milestone Bug

#58458 Update dependencies
  .dprint.jsonc
  package-lock.json
  package.json
  src/testRunner/unittests/comments.ts
  src/testRunner/unittests/evaluation/autoAccessors.ts
  src/testRunner/unittests/evaluation/awaitUsingDeclarations.ts
  src/testRunner/unittests/evaluation/usingDeclarations.ts
  src/testRunner/unittests/jsDocParsing.ts
  src/testRunner/unittests/publicApi.ts
  src/testRunner/unittests/tsserver/exportMapCache.ts
  src/testRunner/unittests/tsserver/partialSemanticServer.ts
Labels: Author: Team, For Uncommitted Bug

#58460 Refactor default export info name gathering
  src/compiler/checker.ts
  src/compiler/types.ts
  src/services/codefixes/convertToEsModule.ts
  src/services/codefixes/importFixes.ts
  src/services/exportInfoMap.ts
  src/services/refactors/convertImport.ts
  src/services/refactors/moveToFile.ts
  src/services/utilities.ts
  tests/cases/fourslash/completionsImportDefaultExportCrash.ts
  tests/cases/fourslash/completionsImport_default_reExport.ts
  tests/cases/fourslash/importNameCodeFix_reExportDefault.ts
Labels: Author: Team, For Milestone Bug

#58478 fix(58399): [isolatedDeclarations][5.5] Autofix does not work when JSX prop contains a dash
  src/services/utilities.ts
  tests/baselines/reference/extractFunction/extractFunction_VariableDeclaration_Writes_Let_LiteralType1.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports47.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports48.ts
Labels: For Backlog Bug

#57262 Implementing copy/paste
  src/harness/client.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/server/project.ts
  src/server/protocol.ts
  src/server/session.ts
  src/services/_namespaces/ts.PasteEdits.ts
  src/services/_namespaces/ts.ts
  src/services/codefixes/importFixes.ts
  src/services/pasteEdits.ts
  src/services/refactors/moveToFile.ts
  src/services/services.ts
  src/services/types.ts
  src/testRunner/tests.ts
  src/testRunner/unittests/tsserver/pasteEdits.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_existingImports1.js
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_existingImports2.js
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_knownSourceFile.js
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_multiplePastes1.js
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_multiplePastes2.js
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_multiplePastes3.js
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_multiplePastes4.js
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_pasteComments.js
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_revertUpdatedFile.js
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_unknownSourceFile.js
  tests/baselines/reference/tsserver/pasteEdits/adds-paste-edits.js
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/moveToFile_existingImports1.ts
  tests/cases/fourslash/server/pasteEdits_existingImports1.ts
  tests/cases/fourslash/server/pasteEdits_existingImports2.ts
  tests/cases/fourslash/server/pasteEdits_knownSourceFile.ts
  tests/cases/fourslash/server/pasteEdits_multiplePastes1.ts
  tests/cases/fourslash/server/pasteEdits_multiplePastes2.ts
  tests/cases/fourslash/server/pasteEdits_multiplePastes3.ts
  tests/cases/fourslash/server/pasteEdits_multiplePastes4.ts
  tests/cases/fourslash/server/pasteEdits_pasteComments.ts
  tests/cases/fourslash/server/pasteEdits_revertUpdatedFile.ts
  tests/cases/fourslash/server/pasteEdits_unknownSourceFile.ts
Labels: Author: Team, For Milestone Bug

#58481 Load unit tests more consistently (pulled from ESM branch)
  src/testRunner/_namespaces/Harness.ts
  src/testRunner/parallel/host.ts
  src/testRunner/parallel/worker.ts
  src/testRunner/runner.ts
Labels: Author: Team, For Uncommitted Bug

#58487 Re-export more referenced types from protocol.ts
  src/server/protocol.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#58366 Move all js emit alias marking behavior behind a single entrypoint
  src/compiler/checker.ts
  tests/baselines/reference/importDeclWithDeclareModifier.errors.txt
  tests/baselines/reference/moduleImport.errors.txt
  tests/baselines/reference/reexportedMissingAlias.errors.txt
Labels: Author: Team, For Uncommitted Bug

#57969 fix37816: goToDefinition skips call signatures for jsx components
  src/services/goToDefinition.ts
  tests/baselines/reference/goToDefinitionJsxCall.baseline.jsonc
  tests/cases/fourslash/goToDefinitionJsxCall.ts
Labels: Author: Team, For Milestone Bug

#55767 fix(55765): Implement Interface Code Action is not available under certain circumstances
  src/services/codefixes/helpers.ts
  tests/cases/fourslash/codeFixClassImplementInterfaceTypeLiterals.ts
Labels: For Backlog Bug

#58393 Remove unused SymbolLinks properties
  src/compiler/checker.ts
  src/compiler/types.ts
Labels: For Uncommitted Bug

#58521 Update unicode identifier start/part with more recent unicode version
  scripts/regenerate-unicode-identifier-parts.mjs
  src/compiler/scanner.ts
Labels: Author: Team, For Uncommitted Bug

#58522 Preserve return type nodes which resolve to errors in declaration emit
  src/compiler/checker.ts
  tests/baselines/reference/asyncAwaitIsolatedModules_es2017.types
  tests/baselines/reference/asyncAwaitIsolatedModules_es5.types
  tests/baselines/reference/asyncAwaitIsolatedModules_es6.types
  tests/baselines/reference/badExternalModuleReference.types
  tests/baselines/reference/bluebirdStaticThis.types
  tests/baselines/reference/constructorWithIncompleteTypeAnnotation.types
  tests/baselines/reference/exportSpecifierAndLocalMemberDeclaration.types
  tests/baselines/reference/exportSpecifierReferencingOuterDeclaration3.types
  tests/baselines/reference/exportSpecifierReferencingOuterDeclaration4.types
  tests/baselines/reference/functionTypesLackingReturnTypes.types
  tests/baselines/reference/functionVariableInReturnTypeAnnotation.types
  tests/baselines/reference/genericCallWithGenericSignatureArguments2.types
  tests/baselines/reference/genericRecursiveImplicitConstructorErrors3.types
  tests/baselines/reference/genericTypeReferenceWithoutTypeArgument.d.types
  tests/baselines/reference/genericTypeReferenceWithoutTypeArgument.types
  tests/baselines/reference/genericTypeReferenceWithoutTypeArgument2.types
  tests/baselines/reference/genericTypeReferenceWithoutTypeArgument3.types
  tests/baselines/reference/genericsWithoutTypeParameters1.types
  tests/baselines/reference/importTypeGeneric.types
  tests/baselines/reference/importedModuleAddToGlobal.types
  tests/baselines/reference/localTypes4.types
  tests/baselines/reference/missingTypeArguments1.types
  tests/baselines/reference/missingTypeArguments2.types
  tests/baselines/reference/moduleAugmentationImportsAndExports2.types
  tests/baselines/reference/moduleAugmentationImportsAndExports3.types
  tests/baselines/reference/noTypeArgumentOnReturnType1.types
  tests/baselines/reference/parserArrowFunctionExpression10.types
  tests/baselines/reference/parserArrowFunctionExpression17.types
  tests/baselines/reference/parserGenericsInTypeContexts1.types
  tests/baselines/reference/parserGenericsInTypeContexts2.types
  tests/baselines/reference/parserMissingLambdaOpenBrace1.types
  tests/baselines/reference/parserRealSource11.types
  tests/baselines/reference/parserRealSource12.types
  tests/baselines/reference/parserRealSource14.types
  tests/baselines/reference/parserRealSource6.types
  tests/baselines/reference/parserUnterminatedGeneric1.types
  tests/baselines/reference/parserUnterminatedGeneric2.types
  tests/baselines/reference/parserharness.types
  tests/baselines/reference/parserindenter.types
  tests/baselines/reference/privacyImportParseErrors.types
  tests/baselines/reference/prototypePropertyAssignmentMergeWithInterfaceMethod.types
  tests/baselines/reference/recursiveClassReferenceTest.types
  tests/baselines/reference/recursiveTypeComparison2.types
  tests/baselines/reference/returnTypeTypeArguments.types
  tests/baselines/reference/sourceMapSample.types
  tests/baselines/reference/thisTypeErrors.types
  tests/baselines/reference/transpile/declarationLocalAliasOfImportAlias.d.ts
  tests/baselines/reference/transpile/declarationLocalAliasOfImportAlias.js
  tests/baselines/reference/typeGuardFunctionErrors.types
  tests/baselines/reference/typeParameterUsedAsTypeParameterConstraint4.types
  tests/baselines/reference/typeParametersInStaticAccessors.types
  tests/baselines/reference/typedefTagTypeResolution.types
  tests/baselines/reference/undefinedTypeArgument2.types
  tests/baselines/reference/unknownSymbolInGenericReturnType.types
  tests/baselines/reference/unknownSymbols1.types
  tests/cases/transpile/declarationLocalAliasOfImportAlias.ts
Labels: Author: Team, For Uncommitted Bug

#58527 Fix incorrect usage of getResolvedTypeReferenceDirectives and some refactoring
  src/compiler/program.ts
  src/compiler/types.ts
  src/services/codefixes/convertToEsModule.ts
  src/services/codefixes/fixImportNonExportedMember.ts
  src/services/codefixes/fixSpelling.ts
  src/services/codefixes/importFixes.ts
  src/services/getEditsForFileRename.ts
  src/services/goToDefinition.ts
  src/services/importTracker.ts
  src/services/suggestionDiagnostics.ts
Labels: Author: Team, For Uncommitted Bug

#58525 Do not lowercase typeReference directive name
  src/compiler/program.ts
  src/testRunner/unittests/tsc/forceConsistentCasingInFileNames.ts
  src/testRunner/unittests/tsserver/typeReferenceDirectives.ts
  tests/baselines/reference/tsc/forceConsistentCasingInFileNames/with-type-ref-from-file.js
  tests/baselines/reference/tsserver/typeReferenceDirectives/when-typeReferenceDirective-contains-UpperCasePackage.js
  tests/baselines/reference/typingsLookup3.errors.txt
  tests/baselines/reference/typingsLookup3.trace.json
  tests/baselines/reference/typingsLookup3.types
  tests/cases/conformance/typings/typingsLookup3.ts
Labels: Author: Team, For Milestone Bug

#58500 Fix constant evaluation of template string expressions
  src/compiler/checker.ts
  tests/baselines/reference/templateLiteralConstantEvaluation.symbols
  tests/baselines/reference/templateLiteralConstantEvaluation.types
  tests/cases/compiler/templateLiteralConstantEvaluation.ts
Labels: Author: Team, For Uncommitted Bug

#58528 Stop checking existing resolution now that we have concept of package ID
  src/compiler/diagnosticMessages.json
  src/compiler/program.ts
  tests/baselines/reference/library-reference-4.symbols
  tests/baselines/reference/library-reference-4.trace.json
  tests/baselines/reference/library-reference-4.types
  tests/baselines/reference/library-reference-5.errors.txt
  tests/baselines/reference/library-reference-5.symbols
  tests/baselines/reference/library-reference-5.trace.json
  tests/baselines/reference/library-reference-5.types
  tests/baselines/reference/tsserver/typeReferenceDirectives/when-typeReferenceDirective-contains-UpperCasePackage.js
Labels: Author: Team, For Uncommitted Bug

#58536 Declaration emit should avoid issuing errors on unresolved names
  src/compiler/checker.ts
  src/compiler/transformers/declarations.ts
  src/compiler/types.ts
  tests/baselines/reference/accessorDeclarationEmitVisibilityErrors.errors.txt
  tests/baselines/reference/accessorDeclarationEmitVisibilityErrors.js
  tests/baselines/reference/declarationEmitExpressionInExtends4.errors.txt
  tests/baselines/reference/declarationEmitExpressionInExtends4.js
  tests/baselines/reference/declarationEmitExpressionInExtends7.errors.txt
  tests/baselines/reference/declarationEmitExpressionInExtends7.js
  tests/baselines/reference/declarationEmitIndexTypeNotFound.errors.txt
  tests/baselines/reference/declarationEmitIndexTypeNotFound.js
  tests/baselines/reference/declarationEmitInvalidExport.errors.txt
  tests/baselines/reference/declarationEmitInvalidExport.js
  tests/baselines/reference/declarationEmitLambdaWithMissingTypeParameterNoCrash.errors.txt
  tests/baselines/reference/declarationEmitLambdaWithMissingTypeParameterNoCrash.js
  tests/baselines/reference/declarationEmitMappedPrivateTypeTypeParameter.errors.txt
  tests/baselines/reference/declarationEmitMappedPrivateTypeTypeParameter.js
  tests/baselines/reference/declarationEmitTypeAliasTypeParameterExtendingUnknownSymbol.errors.txt
  tests/baselines/reference/declarationEmitTypeAliasTypeParameterExtendingUnknownSymbol.js
  tests/baselines/reference/declarationEmitUnknownImport.errors.txt
  tests/baselines/reference/declarationEmitUnknownImport.js
  tests/baselines/reference/declarationEmitUnknownImport2.errors.txt
  tests/baselines/reference/declarationEmitUnknownImport2.js
  tests/baselines/reference/genericDefaultsErrors.errors.txt
  tests/baselines/reference/genericDefaultsErrors.js
  tests/baselines/reference/inferTypes1.errors.txt
  tests/baselines/reference/inferTypes1.js
  tests/baselines/reference/inferTypesInvalidExtendsDeclaration.errors.txt
  tests/baselines/reference/inferTypesInvalidExtendsDeclaration.js
  tests/baselines/reference/intrinsics.errors.txt
  tests/baselines/reference/intrinsics.js
  tests/baselines/reference/isolatedDeclarationErrorsClasses.errors.txt
  tests/baselines/reference/mappedTypeNoTypeNoCrash.errors.txt
  tests/baselines/reference/mappedTypeNoTypeNoCrash.js
  tests/baselines/reference/transpile/declarationUnresolvedGlobalReferencesNoErrors.d.ts
  tests/baselines/reference/tsc/declarationEmit/when-using-Windows-paths-and-uppercase-letters.js
  tests/baselines/reference/typePredicateOnVariableDeclaration02.errors.txt
  tests/baselines/reference/typePredicateOnVariableDeclaration02.js
  tests/cases/transpile/declarationUnresolvedGlobalReferencesNoErrors.ts
Labels: Author: Team, For Backlog Bug

#58516 Partially reuse type nodes
  src/compiler/checker.ts
  tests/baselines/reference/callbackTagNamespace.types
  tests/baselines/reference/callsOnComplexSignatures.types
  tests/baselines/reference/correlatedUnions.types
  tests/baselines/reference/declarationEmitExportAliasVisibiilityMarking.types
  tests/baselines/reference/declarationEmitExportAssignedNamespaceNoTripleSlashTypesReference.types
  tests/baselines/reference/declarationEmitPartialNodeReuseTypeOf.js
  tests/baselines/reference/declarationEmitPartialNodeReuseTypeOf.types
  tests/baselines/reference/declarationEmitPartialNodeReuseTypeReferences.js
  tests/baselines/reference/declarationEmitPartialNodeReuseTypeReferences.types
  tests/baselines/reference/declarationEmitPartialReuseComputedProperty.js
  tests/baselines/reference/declarationEmitPartialReuseComputedProperty.symbols
  tests/baselines/reference/declarationEmitPartialReuseComputedProperty.types
  tests/baselines/reference/declarationEmitRetainedAnnotationRetainsImportInOutput.types
  tests/baselines/reference/declarationEmitScopeConsistency.types
  tests/baselines/reference/declarationEmitTypeofRest.types
  tests/baselines/reference/duplicatePackage.types
  tests/baselines/reference/duplicatePackage_relativeImportWithinPackage.types
  tests/baselines/reference/duplicatePackage_relativeImportWithinPackage_scoped.types
  tests/baselines/reference/errorsForCallAndAssignmentAreSimilar.types
  tests/baselines/reference/es2020IntlAPIs.types
  tests/baselines/reference/es2021LocalesObjectArgument.types
  tests/baselines/reference/es2022LocalesObjectArgument.types
  tests/baselines/reference/genericArgumentCallSigAssignmentCompat.types
  tests/baselines/reference/genericTypeArgumentInference1.types
  tests/baselines/reference/indirectTypeParameterReferences.types
  tests/baselines/reference/inferrenceInfiniteLoopWithSubtyping.types
  tests/baselines/reference/inlineJsxFactoryDeclarationsLocalTypes.types
  tests/baselines/reference/intlNumberFormatES2023.types
  tests/baselines/reference/jsDeclarationsExportDefinePropertyEmit.types
  tests/baselines/reference/jsDeclarationsFunctions.types
  tests/baselines/reference/jsDeclarationsFunctionsCjs.types
  tests/baselines/reference/jsDeclarationsMissingTypeParameters.types
  tests/baselines/reference/jsDeclarationsRestArgsWithThisTypeInJSDocFunction.types
  tests/baselines/reference/jsdocArrayObjectPromiseImplicitAny.types
  tests/baselines/reference/jsdocParameterParsingInfiniteLoop.types
  tests/baselines/reference/jsdocTemplateTag.types
  tests/baselines/reference/jsdocThisType.types
  tests/baselines/reference/jsdocTypeNongenericInstantiationAttempt.types
  tests/baselines/reference/jsdocTypeReferenceToValue.types
  tests/baselines/reference/jsxFragmentFactoryNoUnusedLocals.types
  tests/baselines/reference/localesObjectArgument.types
  tests/baselines/reference/noInferRedeclaration.types
  tests/baselines/reference/prototypePropertyAssignmentMergeWithInterfaceMethod.types
  tests/baselines/reference/returnInfiniteIntersection.types
  tests/baselines/reference/transpile/declarationEmitPartialNodeReuse.d.ts
  tests/baselines/reference/transpile/declarationPartialNodeReuseTypeOf.d.ts
  tests/baselines/reference/transpile/declarationRestParameters.d.ts
  tests/baselines/reference/transpile/declarationUnresolvedTypeReference2.d.ts
  tests/baselines/reference/underscoreMapFirst.types
  tests/baselines/reference/visibilityOfCrossModuleTypeUsage.types
  tests/cases/compiler/declarationEmitPartialReuseComputedProperty.ts
  tests/cases/transpile/declarationEmitPartialNodeReuse.ts
  tests/cases/transpile/declarationPartialNodeReuseTypeOf.ts
  tests/cases/transpile/declarationRestParameters.ts
  tests/cases/transpile/declarationUnresolvedTypeReference2.ts
Labels: For Uncommitted Bug

#58538 Make sure that jsdoc is always in range with parameter declaration
  src/compiler/utilities.ts
  src/testRunner/unittests/incrementalParser.ts
Labels: Author: Team, For Milestone Bug

#57230 add types for set methods proposal
  src/lib/esnext.collection.d.ts
  tests/baselines/reference/classExtendingAbstractClassWithMemberCalledTheSameAsItsOwnTypeParam.symbols
  tests/baselines/reference/esNextWeakRefs_IterableWeakMap.symbols
  tests/baselines/reference/extendsTag1.symbols
  tests/baselines/reference/mapGroupBy.symbols
  tests/baselines/reference/objectGroupBy.symbols
  tests/baselines/reference/setMethods.errors.txt
  tests/baselines/reference/setMethods.js
  tests/baselines/reference/setMethods.symbols
  tests/baselines/reference/setMethods.types
  tests/baselines/reference/substitutionTypePassedToExtends.symbols
  tests/cases/compiler/setMethods.ts
Labels: For Backlog Bug

#58560 Handle root files listed in project config from referenced project to be same as if they were included through import
  src/compiler/builder.ts
  src/compiler/program.ts
  src/compiler/tsbuildPublic.ts
  src/testRunner/tests.ts
  src/testRunner/unittests/helpers/baseline.ts
  src/testRunner/unittests/helpers/projectRoots.ts
  src/testRunner/unittests/tsbuild/roots.ts
  src/testRunner/unittests/tsbuildWatch/roots.ts
  src/testRunner/unittests/tsserver/projectRootFiles.ts
  tests/baselines/reference/tsbuild/roots/when-root-file-is-from-referenced-project-and-shared-is-first.js
  tests/baselines/reference/tsbuild/roots/when-root-file-is-from-referenced-project.js
  tests/baselines/reference/tsbuildWatch/roots/when-root-file-is-from-referenced-project-and-shared-is-first.js
  tests/baselines/reference/tsbuildWatch/roots/when-root-file-is-from-referenced-project.js
  tests/baselines/reference/tsserver/projectReferences/root-file-is-file-from-referenced-project-and-using-declaration-maps.js
  tests/baselines/reference/tsserver/projectReferences/root-file-is-file-from-referenced-project.js
  tests/baselines/reference/tsserver/projectRootFiles/when-root-file-is-from-referenced-project-and-shared-is-first.js
  tests/baselines/reference/tsserver/projectRootFiles/when-root-file-is-from-referenced-project.js
Labels: Author: Team, For Milestone Bug

#58562 Handle project / program roots in tsserver correctly
  src/server/editorServices.ts
  src/server/project.ts
  src/testRunner/unittests/tsserver/dynamicFiles.ts
  src/testRunner/unittests/tsserver/projectReferences.ts
  src/testRunner/unittests/tsserver/projects.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/tsserver/dynamicFiles/dynamic-file-with-projectRootPath-fails-when-useInferredProjectPerProjectRoot-is-false.js
  tests/baselines/reference/tsserver/projectReferences/root-file-is-file-from-referenced-project-and-using-declaration-maps.js
  tests/baselines/reference/tsserver/projectReferences/with-dts-file-next-to-ts-file.js
  tests/baselines/reference/tsserver/projects/assert-when-removing-project.js
Labels: Author: Team, For Milestone Bug

#58597 Respect `importModuleSpecifierPreference` in sort order between fixes for the same symbol from different files
  src/compiler/moduleSpecifiers.ts
  src/compiler/types.ts
  src/server/moduleSpecifierCache.ts
  src/services/codefixes/importFixes.ts
  tests/baselines/reference/tsserver/fourslashServer/autoImportProvider_importsMap1.js
  tests/baselines/reference/tsserver/moduleSpecifierCache/caches-module-specifiers-within-a-file.js
  tests/cases/fourslash/completionsImport_packageJsonImportsPreference.ts
  tests/cases/fourslash/completionsImport_windowsPathsProjectRelative.ts
  tests/cases/fourslash/server/autoImportProvider_importsMap1.ts
Labels: Author: Team, For Milestone Bug

#58605 Fix elided var handling in declaration emit visibility checks
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitInvalidExport.errors.txt
  tests/baselines/reference/declarationEmitInvalidExport.js
  tests/baselines/reference/declarationEmitVarInElidedBlock.errors.txt
  tests/baselines/reference/declarationEmitVarInElidedBlock.symbols
  tests/baselines/reference/declarationEmitVarInElidedBlock.types
  tests/cases/compiler/declarationEmitVarInElidedBlock.ts
Labels: Author: Team, For Uncommitted Bug

#58594 If module exports const enum, invalidate js files along with dts as it can impact js emit as well
  src/compiler/builder.ts
  src/testRunner/unittests/tsc/incremental.ts
  tests/baselines/reference/tsc/incremental/with-aliased-const-enums-with-preserveConstEnums.js
  tests/baselines/reference/tsc/incremental/with-aliased-const-enums.js
  tests/baselines/reference/tsc/incremental/with-aliased-in-different-file-const-enums-with-preserveConstEnums.js
  tests/baselines/reference/tsc/incremental/with-aliased-in-different-file-const-enums.js
  tests/baselines/reference/tsc/incremental/with-const-enums-with-preserveConstEnums.js
  tests/baselines/reference/tsc/incremental/with-const-enums.js
Labels: Author: Team, For Milestone Bug

#58592 Skip typechecking file when generating declaraiton to get d.ts signature for incremental build
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/program.ts
  src/compiler/types.ts
  src/testRunner/unittests/tsc/cancellationToken.ts
  tests/baselines/reference/tsc/cancellationToken/when-emitting-buildInfo.js
  tests/baselines/reference/tsc/cancellationToken/when-using-state.js
Labels: Author: Team, For Uncommitted Bug

#58585 fix(58584): formatJSDocLink shouldn't introduce a trailing space when non link text.
  src/compiler/utilitiesPublic.ts
  src/testRunner/unittests/jsDocParsing.ts
  tests/baselines/reference/linkTagEmit1.js
Labels: For Uncommitted Bug

#58596 Lock down computed names in object literals and classes under --isolatedDeclarations
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/emitter.ts
  src/compiler/expressionToTypeNode.ts
  src/compiler/transformers/declarations.ts
  src/compiler/transformers/declarations/diagnostics.ts
  src/compiler/types.ts
  src/services/codefixes/fixMissingTypeAnnotationOnExports.ts
  tests/baselines/reference/computedPropertiesNarrowed.errors.txt
  tests/baselines/reference/isolatedDeclarationErrorsClasses.errors.txt
  tests/baselines/reference/isolatedDeclarationErrorsObjects.errors.txt
  tests/baselines/reference/isolatedDeclarationLazySymbols.errors.txt
  tests/baselines/reference/transpile/declarationBasicSyntax.d.ts
  tests/baselines/reference/transpile/declarationComputedPropertyNames.d.ts
  tests/cases/transpile/declarationComputedPropertyNames.ts
Labels: Author: Team, For Uncommitted Bug

#58623 Fix issue where sometimes modified timestamp file was not shown in baseline
  src/harness/vfsUtil.ts
  tests/baselines/reference/tsbuild/outFile/rebuilds-completely-when-command-line-incremental-flag-changes-between-non-dts-changes.js
  tests/baselines/reference/tsbuild/outFile/when-final-project-is-not-composite-but-uses-project-references.js
Labels: Author: Team, For Uncommitted Bug

#58625 Use dprint package for dtsBundler formatting rather than dprint CLI
  .dprint.jsonc
  package-lock.json
  package.json
  scripts/dtsBundler.mjs
Labels: Author: Team, For Uncommitted Bug

#58620 Error if type node uses inaccessible type in isolated declarations
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/transformers/declarations/diagnostics.ts
  src/services/codefixes/fixMissingTypeAnnotationOnExports.ts
  tests/baselines/reference/transpile/declarationNotInScopeTypes.d.ts
  tests/baselines/reference/transpile/declarationNotInScopeTypes.js
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports49-private-name.ts
  tests/cases/transpile/declarationNotInScopeTypes.ts
Labels: For Uncommitted Bug

#58628 Ban inferred return type on async and generator functions.
  src/compiler/checker.ts
  src/compiler/expressionToTypeNode.ts
  tests/baselines/reference/transpile/declarationAsyncAndGeneratorFunctions.d.ts
  tests/baselines/reference/transpile/declarationAsyncAndGeneratorFunctions.js
  tests/cases/transpile/declarationAsyncAndGeneratorFunctions.ts
Labels: For Uncommitted Bug

#58610 Propagate the error any type in union and intersection construction
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/jsDeclarationsExportDoubleAssignmentInClosure.types
  tests/baselines/reference/jsxNestedWithinTernaryParsesCorrectly.types
  tests/baselines/reference/logicalAssignment10(target=es2015).types
  tests/baselines/reference/logicalAssignment10(target=es2020).types
  tests/baselines/reference/logicalAssignment10(target=es2021).types
  tests/baselines/reference/logicalAssignment10(target=esnext).types
  tests/baselines/reference/parsingDeepParenthensizedExpression.types
  tests/baselines/reference/transpile/declarationSelfReferentialConstraint.d.ts
  tests/baselines/reference/tsxReactEmitNesting.types
  tests/baselines/reference/unionOfFunctionAndSignatureIsCallable.types
  tests/cases/transpile/declarationSelfReferentialConstraint.ts
Labels: Author: Team, For Uncommitted Bug

#58635 Add test for issue fixed by #58546
  tests/baselines/reference/declarationEmitHigherOrderRetainedGenerics.js
  tests/baselines/reference/declarationEmitHigherOrderRetainedGenerics.symbols
  tests/baselines/reference/declarationEmitHigherOrderRetainedGenerics.types
  tests/cases/compiler/declarationEmitHigherOrderRetainedGenerics.ts
Labels: Author: Team, For Milestone Bug

#58554 Fix class decorator detection in class fields transform
  src/compiler/transformers/classFields.ts
  tests/baselines/reference/esDecorators-classExpression-commentPreservation(target=es2015).js
  tests/baselines/reference/esDecorators-classExpression-commentPreservation(target=es2022).js
  tests/baselines/reference/esDecorators-emitDecoratorMetadata(target=es2015).js
  tests/baselines/reference/esDecorators-emitDecoratorMetadata(target=es5).js
  tests/baselines/reference/esDecoratorsClassFieldsCrash.js
  tests/baselines/reference/usingDeclarationsNamedEvaluationDecoratorsAndClassFields.js
  tests/cases/compiler/esDecoratorsClassFieldsCrash.ts
Labels: Author: Team, For Milestone Bug

#58326 fix53287 `mergeSymbol` checks if the resolved target can merge with the source
  src/compiler/checker.ts
  tests/baselines/reference/checkMergedGlobalUMDSymbol.errors.txt
  tests/baselines/reference/checkMergedGlobalUMDSymbol.symbols
  tests/baselines/reference/checkMergedGlobalUMDSymbol.types
  tests/baselines/reference/checkerInitializationCrash.errors.txt
  tests/baselines/reference/checkerInitializationCrash.symbols
  tests/baselines/reference/checkerInitializationCrash.types
  tests/baselines/reference/crashDeclareGlobalTypeofExport.errors.txt
  tests/baselines/reference/crashDeclareGlobalTypeofExport.symbols
  tests/baselines/reference/crashDeclareGlobalTypeofExport.types
  tests/baselines/reference/declarationFileNoCrashOnExtraExportModifier.errors.txt
  tests/baselines/reference/declarationFileNoCrashOnExtraExportModifier.symbols
  tests/baselines/reference/declarationFileNoCrashOnExtraExportModifier.types
  tests/baselines/reference/findAllReferencesUmdModuleAsGlobalConst.baseline.jsonc
  tests/baselines/reference/mergeSymbolReexportInterface.errors.txt
  tests/baselines/reference/mergeSymbolReexportInterface.js
  tests/baselines/reference/mergeSymbolReexportInterface.symbols
  tests/baselines/reference/mergeSymbolReexportInterface.types
  tests/baselines/reference/mergeSymbolReexportedTypeAliasInstantiation.errors.txt
  tests/baselines/reference/mergeSymbolReexportedTypeAliasInstantiation.js
  tests/baselines/reference/mergeSymbolReexportedTypeAliasInstantiation.symbols
  tests/baselines/reference/mergeSymbolReexportedTypeAliasInstantiation.types
  tests/baselines/reference/mergeSymbolRexportFunction.errors.txt
  tests/baselines/reference/mergeSymbolRexportFunction.js
  tests/baselines/reference/mergeSymbolRexportFunction.symbols
  tests/baselines/reference/mergeSymbolRexportFunction.types
  tests/baselines/reference/umdGlobalAugmentationNoCrash.errors.txt
  tests/baselines/reference/umdGlobalAugmentationNoCrash.symbols
  tests/baselines/reference/umdNamespaceMergedWithGlobalAugmentationIsNotCircular.errors.txt
  tests/baselines/reference/umdNamespaceMergedWithGlobalAugmentationIsNotCircular.symbols
  tests/baselines/reference/umdNamespaceMergedWithGlobalAugmentationIsNotCircular.types
  tests/cases/compiler/mergeSymbolReexportInterface.ts
  tests/cases/compiler/mergeSymbolReexportedTypeAliasInstantiation.ts
  tests/cases/compiler/mergeSymbolRexportFunction.ts
  tests/cases/fourslash/findAllReferencesUmdModuleAsGlobalConst.ts
  tests/cases/fourslash/moduleReexportedIntoGlobalQuickInfo.ts
Labels: Author: Team, For Milestone Bug

#58637 Improved errors for required parameters with default values in isolated declaration
  src/compiler/checker.ts
  src/compiler/expressionToTypeNode.ts
  tests/baselines/reference/isolatedDeclarationsAddUndefined.errors.txt
  tests/baselines/reference/isolatedDeclarationsAddUndefined.js
  tests/baselines/reference/isolatedDeclarationsAddUndefined.symbols
  tests/baselines/reference/isolatedDeclarationsAddUndefined.types
  tests/baselines/reference/transpile/declarationFunctionDeclarations.d.ts
  tests/baselines/reference/transpile/declarationFunctionDeclarations.js
  tests/cases/compiler/isolatedDeclarationsAddUndefined.ts
  tests/cases/transpile/declarationFunctionDeclarations.ts
Labels: For Milestone Bug

#57201 fix(57022): Rename of string literal property name doesn't rename all occurences
  src/services/findAllReferences.ts
  tests/baselines/reference/renameStringPropertyNames2.baseline.jsonc
  tests/cases/fourslash/renameStringPropertyNames2.ts
Labels: For Backlog Bug

#58654 Check resolution of tslib per file
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/esModuleInteropTslibHelpers.errors.txt
  tests/baselines/reference/tslibMissingHelper.errors.txt
  tests/baselines/reference/tslibMissingHelper.js
  tests/baselines/reference/tslibMissingHelper.symbols
  tests/baselines/reference/tslibMissingHelper.types
  tests/baselines/reference/tslibMultipleMissingHelper.errors.txt
  tests/baselines/reference/tslibMultipleMissingHelper.js
  tests/baselines/reference/tslibMultipleMissingHelper.symbols
  tests/baselines/reference/tslibMultipleMissingHelper.types
  tests/baselines/reference/tslibNotFoundDifferentModules.errors.txt
  tests/baselines/reference/tslibNotFoundDifferentModules.js
  tests/baselines/reference/tslibNotFoundDifferentModules.symbols
  tests/baselines/reference/tslibNotFoundDifferentModules.types
  tests/cases/compiler/tslibMissingHelper.ts
  tests/cases/compiler/tslibMultipleMissingHelper.ts
  tests/cases/compiler/tslibNotFoundDifferentModules.ts
Labels: Author: Team, For Uncommitted Bug

#58489 Handle exported functions in ExportDeclarations for CJS/AMD/UMD emit
  src/compiler/transformers/module/module.ts
  src/compiler/transformers/module/system.ts
  src/compiler/transformers/utilities.ts
  tests/baselines/reference/assertionFunctionWildcardImport2.js
  tests/baselines/reference/declarationEmitInferredTypeAlias2.js
  tests/baselines/reference/declarationsForIndirectTypeAliasReference.js
  tests/baselines/reference/exportsAndImports1-amd.js
  tests/baselines/reference/exportsAndImports1-es6.js
  tests/baselines/reference/exportsAndImports1.js
  tests/baselines/reference/exportsAndImports3-amd.js
  tests/baselines/reference/exportsAndImports3-es6.js
  tests/baselines/reference/exportsAndImports3.js
  tests/baselines/reference/importNonExportedMember.js
  tests/baselines/reference/importNonExportedMember1.js
  tests/baselines/reference/jsDeclarationsDefault.js
  tests/baselines/reference/jsDeclarationsFunctions.js
  tests/baselines/reference/jsxNamespaceReexports.js
  tests/baselines/reference/nodeModulesAllowJsGeneratedNameCollisions(module=node16).js
  tests/baselines/reference/nodeModulesAllowJsGeneratedNameCollisions(module=nodenext).js
  tests/baselines/reference/nodeModulesGeneratedNameCollisions(module=node16).js
  tests/baselines/reference/nodeModulesGeneratedNameCollisions(module=nodenext).js
  tests/baselines/reference/reExportDefaultExport.js
  tests/baselines/reference/spreadExpressionContextualTypeWithNamespace.js
  tests/baselines/reference/valuesMergingAcrossModules.js
Labels: Author: Team, For Uncommitted Bug

#58320 Correct Regular Expressions Behavior Related to Annex B
  src/compiler/diagnosticMessages.json
  src/compiler/scanner.ts
  tests/baselines/reference/regularExpressionAnnexB.errors.txt
  tests/baselines/reference/regularExpressionAnnexB.js
  tests/baselines/reference/regularExpressionAnnexB.symbols
  tests/baselines/reference/regularExpressionAnnexB.types
  tests/baselines/reference/regularExpressionScanning(target=es2015).errors.txt
  tests/baselines/reference/regularExpressionScanning(target=es2015).js
  tests/baselines/reference/regularExpressionScanning(target=es2015).symbols
  tests/baselines/reference/regularExpressionScanning(target=es2015).types
  tests/baselines/reference/regularExpressionScanning(target=es5).errors.txt
  tests/baselines/reference/regularExpressionScanning(target=es5).js
  tests/baselines/reference/regularExpressionScanning(target=es5).symbols
  tests/baselines/reference/regularExpressionScanning(target=es5).types
  tests/baselines/reference/regularExpressionScanning(target=esnext).errors.txt
  tests/baselines/reference/regularExpressionScanning(target=esnext).js
  tests/baselines/reference/regularExpressionScanning(target=esnext).symbols
  tests/baselines/reference/regularExpressionScanning(target=esnext).types
  tests/cases/compiler/regularExpressionAnnexB.ts
  tests/cases/compiler/regularExpressionScanning.ts
Labels: For Uncommitted Bug

#58679 Handling statements from a known source file
  src/services/pasteEdits.ts
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_blankTargetFile.js
  tests/cases/fourslash/server/pasteEdits_blankTargetFile.ts
Labels: Author: Team, For Uncommitted Bug

#58621 Do not infer `yield*` type from contextual `TReturn`
  src/compiler/checker.ts
  tests/baselines/reference/asyncYieldStarContextualType.symbols
  tests/baselines/reference/asyncYieldStarContextualType.types
  tests/baselines/reference/yieldStarContextualType.symbols
  tests/baselines/reference/yieldStarContextualType.types
  tests/cases/compiler/asyncYieldStarContextualType.ts
  tests/cases/compiler/yieldStarContextualType.ts
Labels: Author: Team, For Milestone Bug

#58705 Fix baselines after PR 58621
  tests/baselines/reference/asyncYieldStarContextualType.types
  tests/baselines/reference/yieldStarContextualType.types
Labels: Author: Team, For Uncommitted Bug

#58639 Update dependencies
  .dprint.jsonc
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#58702 Revert PR 55371
  src/compiler/checker.ts
  tests/baselines/reference/numericStringLiteralTypes.types
  tests/baselines/reference/recursiveConditionalCrash3.types
  tests/baselines/reference/recursiveConditionalCrash4.types
  tests/baselines/reference/templateLiteralIntersection.types
  tests/baselines/reference/templateLiteralIntersection3.types
  tests/baselines/reference/templateLiteralTypes5.errors.txt
  tests/baselines/reference/templateLiteralTypes5.types
  tests/baselines/reference/templateLiteralTypes8.symbols
  tests/baselines/reference/templateLiteralTypes8.types
  tests/cases/conformance/types/literal/templateLiteralTypes8.ts
Labels: Author: Team, For Milestone Bug

#58364 Enable JS emit for noCheck and noCheck for transpileModule
  src/compiler/checker.ts
  src/compiler/commandLineParser.ts
  src/compiler/debug.ts
  src/compiler/emitter.ts
  src/compiler/program.ts
  src/compiler/transformers/classFields.ts
  src/compiler/transformers/es2015.ts
  src/compiler/transformers/es2017.ts
  src/compiler/transformers/es2018.ts
  src/compiler/transformers/legacyDecorators.ts
  src/compiler/types.ts
  src/harness/harnessIO.ts
  src/services/transpile.ts
  tests/baselines/reference/autoAccessor1(target=es5).js
  tests/baselines/reference/autoAccessor3(target=es5).js
  tests/baselines/reference/autoAccessor4(target=es5).js
  tests/baselines/reference/declFileTypeAnnotationUnionType.js
  tests/baselines/reference/importDeclWithDeclareModifier.js
  tests/baselines/reference/isolatedModulesNoEmitOnError.js
  tests/baselines/reference/multiLinePropertyAccessAndArrowFunctionIndent1.errors.txt
  tests/baselines/reference/noCheckRequiresEmitDeclarationOnly.errors.txt
  tests/baselines/reference/noEmitOnError.js
  tests/baselines/reference/outModuleConcatCommonjs.js
  tests/baselines/reference/outModuleConcatES6.js
  tests/baselines/reference/outModuleConcatUmd.js
  tests/baselines/reference/parseErrorIncorrectReturnToken.errors.txt
  tests/baselines/reference/parserStatementIsNotAMemberVariableDeclaration1.errors.txt
  tests/baselines/reference/typeReferenceDirectives11.js
  tests/baselines/reference/typeReferenceDirectives12.js
  tests/baselines/reference/unicodeEscapesInNames02(target=es5).errors.txt
  tests/baselines/reference/variadicTuples1.js
Labels: Author: Team, For Uncommitted Bug

#58718 Fixing self import
  src/services/refactors/moveToFile.ts
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_pasteIntoSameFile.js
  tests/cases/fourslash/server/pasteEdits_pasteIntoSameFile.ts
Labels: Author: Team, For Uncommitted Bug

#58720 Recover from type reuse errors by falling back to inferred type printing
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitUsingTypeAlias2.js
  tests/baselines/reference/declarationEmitUsingTypeAlias2.symbols
  tests/baselines/reference/declarationEmitUsingTypeAlias2.types
  tests/cases/compiler/declarationEmitUsingTypeAlias2.ts
Labels: For Uncommitted Bug

#58292 Unwrap `NoInfer` types when narrowing
  src/compiler/checker.ts
  tests/baselines/reference/narrowingNoInfer1.symbols
  tests/baselines/reference/narrowingNoInfer1.types
  tests/baselines/reference/noInfer.types
  tests/cases/compiler/narrowingNoInfer1.ts
Labels: For Backlog Bug

#58722 Improve the performance of isolatedDeclarations quickfix
  src/compiler/checker.ts
  src/compiler/types.ts
  src/services/codefixes/fixMissingTypeAnnotationOnExports.ts
Labels: For Uncommitted Bug

#58715 Do not expand type references in keyof and index access
  src/compiler/checker.ts
  tests/baselines/reference/correlatedUnions.types
  tests/baselines/reference/declarationEmitAliasInlineing.js
  tests/baselines/reference/declarationEmitAliasInlineing.symbols
  tests/baselines/reference/declarationEmitAliasInlineing.types
  tests/baselines/reference/indexedAccessTypeConstraints.types
  tests/baselines/reference/inferTypes1.types
  tests/baselines/reference/mappedTypeNestedGenericInstantiation.types
  tests/baselines/reference/templateLiteralTypes4.types
  tests/baselines/reference/unionOfClassCalls.types
  tests/cases/compiler/declarationEmitAliasInlineing.ts
  tests/cases/fourslash/quickInfoForContextuallyTypedParameters.ts
Labels: For Uncommitted Bug

#56466 Fixed an issue with broken `await using` declarations in `for of` loops
  src/compiler/checker.ts
  src/compiler/transformers/esnext.ts
  tests/baselines/reference/awaitUsingDeclarationsInForAwaitOf.3(target=es5).errors.txt
  tests/baselines/reference/awaitUsingDeclarationsInForAwaitOf.3(target=es5).js
  tests/baselines/reference/awaitUsingDeclarationsInForAwaitOf.3(target=esnext).errors.txt
  tests/baselines/reference/awaitUsingDeclarationsInForAwaitOf.3(target=esnext).js
  tests/baselines/reference/awaitUsingDeclarationsInForOf.5(target=es5).errors.txt
  tests/baselines/reference/awaitUsingDeclarationsInForOf.5(target=es5).js
  tests/baselines/reference/awaitUsingDeclarationsInForOf.5(target=esnext).errors.txt
  tests/baselines/reference/awaitUsingDeclarationsInForOf.5(target=esnext).js
  tests/cases/conformance/statements/VariableStatements/usingDeclarations/awaitUsingDeclarationsInForAwaitOf.3.ts
  tests/cases/conformance/statements/VariableStatements/usingDeclarations/awaitUsingDeclarationsInForOf.5.ts
Labels: For Uncommitted Bug

#58593 Mark file as skips typechecking if it contains ts-nocheck
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/program.ts
  src/compiler/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#58061 Shorten error spans for errors reported on constructor declarations
  src/compiler/utilities.ts
  tests/baselines/reference/ClassDeclaration10.errors.txt
  tests/baselines/reference/ClassDeclaration11.errors.txt
  tests/baselines/reference/ClassDeclaration14.errors.txt
  tests/baselines/reference/ClassDeclaration8.errors.txt
  tests/baselines/reference/bases.errors.txt
  tests/baselines/reference/classConstructorOverloadsAccessibility.errors.txt
  tests/baselines/reference/classUpdateTests.errors.txt
  tests/baselines/reference/classWithTwoConstructorDefinitions.errors.txt
  tests/baselines/reference/constructorOverloads1.errors.txt
  tests/baselines/reference/constructorOverloads3.errors.txt
  tests/baselines/reference/constructorOverloads8.errors.txt
  tests/baselines/reference/constructorWithIncompleteTypeAnnotation.errors.txt
  tests/baselines/reference/constructorsWithSpecializedSignatures.errors.txt
  tests/baselines/reference/derivedClassConstructorWithoutSuperCall.errors.txt
  tests/baselines/reference/derivedClassParameterProperties.errors.txt
  tests/baselines/reference/derivedClassSuperProperties.errors.txt
  tests/baselines/reference/externModule.errors.txt
  tests/baselines/reference/illegalSuperCallsInConstructor.errors.txt
  tests/baselines/reference/jsFileCompilationConstructorOverloadSyntax.errors.txt
  tests/baselines/reference/parameterPropertyInConstructor2.errors.txt
  tests/baselines/reference/parserClassDeclaration10.errors.txt
  tests/baselines/reference/parserClassDeclaration11.errors.txt
  tests/baselines/reference/parserClassDeclaration12.errors.txt
  tests/baselines/reference/parserClassDeclaration14.errors.txt
  tests/baselines/reference/parserClassDeclaration8.errors.txt
  tests/baselines/reference/parserConstructorDeclaration12.errors.txt
  tests/baselines/reference/parserConstructorDeclaration8.errors.txt
  tests/baselines/reference/parserParameterList17.errors.txt
  tests/baselines/reference/privateNameBadSuper.errors.txt
  tests/baselines/reference/staticPropSuper.errors.txt
  tests/baselines/reference/strictModeInConstructor.errors.txt
  tests/baselines/reference/superCallInsideClassDeclaration.errors.txt
  tests/baselines/reference/superCallInsideClassExpression.errors.txt
  tests/baselines/reference/superInConstructorParam1.errors.txt
  tests/baselines/reference/superNewCall1.errors.txt
  tests/baselines/reference/taggedTemplatesWithTypeArguments2.errors.txt
Labels: For Uncommitted Bug

#58615 Fix: Include Values of Script Extensions for Unicode Property Value Expressions in Regular Expressions
  src/compiler/scanner.ts
  tests/baselines/reference/regularExpressionUnicodePropertyValueExpressionSuggestions.errors.txt
  tests/baselines/reference/regularExpressionUnicodePropertyValueExpressionSuggestions.js
  tests/baselines/reference/regularExpressionUnicodePropertyValueExpressionSuggestions.symbols
  tests/baselines/reference/regularExpressionUnicodePropertyValueExpressionSuggestions.types
  tests/cases/compiler/regularExpressionUnicodePropertyValueExpressionSuggestions.ts
Labels: For Uncommitted Bug

#58677 Properly account for `this` argument in intersection apparent type caching
  src/compiler/checker.ts
  tests/baselines/reference/intersectionApparentTypeCaching.symbols
  tests/baselines/reference/intersectionApparentTypeCaching.types
  tests/cases/compiler/intersectionApparentTypeCaching.ts
Labels: Author: Team, For Milestone Bug
