Repository microsoft/TypeScript, pull requests merged in 2024-07, with the labels that each got.

#58186 Fixed intersections of primitive unions with `exactOptionalPropertyTypes` when mixing `undefinedType` with `missingType`
  src/compiler/checker.ts
  tests/baselines/reference/intersectionsAndOptionalProperties2(exactoptionalpropertytypes=false).symbols
  tests/baselines/reference/intersectionsAndOptionalProperties2(exactoptionalpropertytypes=false).types
  tests/baselines/reference/intersectionsAndOptionalProperties2(exactoptionalpropertytypes=true).errors.txt
  tests/baselines/reference/intersectionsAndOptionalProperties2(exactoptionalpropertytypes=true).symbols
  tests/baselines/reference/intersectionsAndOptionalProperties2(exactoptionalpropertytypes=true).types
  tests/baselines/reference/intersectionsAndOptionalProperties3(exactoptionalpropertytypes=false).symbols
  tests/baselines/reference/intersectionsAndOptionalProperties3(exactoptionalpropertytypes=false).types
  tests/baselines/reference/intersectionsAndOptionalProperties3(exactoptionalpropertytypes=true).errors.txt
  tests/baselines/reference/intersectionsAndOptionalProperties3(exactoptionalpropertytypes=true).symbols
  tests/baselines/reference/intersectionsAndOptionalProperties3(exactoptionalpropertytypes=true).types
  tests/cases/compiler/intersectionsAndOptionalProperties2.ts
  tests/cases/compiler/intersectionsAndOptionalProperties3.ts
Labels: For Backlog Bug

#59084 Update to esbuild v0.22
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#59093 Paste without imports
  src/services/pasteEdits.ts
  src/services/refactors/moveToFile.ts
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_noImportNeeded.js
  tests/cases/fourslash/server/pasteEdits_noImportNeeded.ts
Labels: Author: Team, For Uncommitted Bug

#58216 Fixed crash when cross-file reusing nodes for class member snippet completions
  src/compiler/emitter.ts
  tests/cases/fourslash/completionClassMemberSnippetCrossFileNodeReuse1.ts
Labels: For Backlog Bug

#59182 Update knip
  package-lock.json
  package.json
Labels: For Uncommitted Bug

#59181 In project, instead of iterating over program files to determine if file needs to be detached, do it through existing mechanism of releasing oldSourceFile
  src/compiler/program.ts
  src/compiler/resolutionCache.ts
  src/compiler/types.ts
  src/server/project.ts
  src/services/services.ts
  src/services/types.ts
  tests/baselines/reference/tsserver/moduleResolution/using-referenced-project-built.js
  tests/baselines/reference/tsserver/moduleResolution/using-referenced-project.js
Labels: Author: Team, For Uncommitted Bug

#59154 Create a `SourceFile`-level indirection on children maps, store `SyntaxList` children directly on nodes.
  src/compiler/factory/nodeChildren.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/parser.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/services/services.ts
Labels: Author: Team, For Milestone Bug

#59189 pasteEdits returns no edit when there are no imports needed
  src/harness/client.ts
  src/services/pasteEdits.ts
  src/testRunner/unittests/tsserver/pasteEdits.ts
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_noImportNeeded.js
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_pasteComments.js
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_pasteIntoSameFile.js
  tests/baselines/reference/tsserver/pasteEdits/adds-paste-edits.js
  tests/cases/fourslash/server/pasteEdits_noImportNeeded.ts
  tests/cases/fourslash/server/pasteEdits_pasteComments.ts
  tests/cases/fourslash/server/pasteEdits_pasteIntoSameFile.ts
  tests/cases/fourslash/server/pasteEdits_unknownSourceFile.ts
Labels: Author: Team, For Milestone Bug

#59121 Fixed regression in signature instantiation
  src/compiler/checker.ts
  tests/baselines/reference/excessiveStackDepthFlatArray.types
  tests/baselines/reference/genericCallInferenceConditionalType1.symbols
  tests/baselines/reference/genericCallInferenceConditionalType1.types
  tests/cases/compiler/genericCallInferenceConditionalType1.ts
Labels: For Milestone Bug

#59207 Fixed crash when finding all references when `JSDocImportTag`s are involved
  src/services/importTracker.ts
  tests/baselines/reference/findAllRefsJsDocImportTag2.baseline.jsonc
  tests/baselines/reference/findAllRefsJsDocImportTag3.baseline.jsonc
  tests/baselines/reference/findAllRefsJsDocImportTag4.baseline.jsonc
  tests/baselines/reference/findAllRefsJsDocImportTag5.baseline.jsonc
  tests/cases/fourslash/findAllRefsJsDocImportTag2.ts
  tests/cases/fourslash/findAllRefsJsDocImportTag3.ts
  tests/cases/fourslash/findAllRefsJsDocImportTag4.ts
  tests/cases/fourslash/findAllRefsJsDocImportTag5.ts
Labels: For Uncommitted Bug

#59073 Enable typed linting for scripts dir
  eslint.config.mjs
  scripts/configurePrerelease.mjs
Labels: Author: Team, Housekeeping, For Uncommitted Bug

#59203 Skip ID inference errors on nodes collected from other files
  src/compiler/transformers/declarations.ts
  tests/baselines/reference/declarationEmitIsolatedDeclarationErrorNotEmittedForNonEmittedFile.errors.txt
  tests/baselines/reference/declarationEmitIsolatedDeclarationErrorNotEmittedForNonEmittedFile.js
  tests/baselines/reference/declarationEmitIsolatedDeclarationErrorNotEmittedForNonEmittedFile.symbols
  tests/baselines/reference/declarationEmitIsolatedDeclarationErrorNotEmittedForNonEmittedFile.types
  tests/cases/compiler/declarationEmitIsolatedDeclarationErrorNotEmittedForNonEmittedFile.ts
Labels: Author: Team, For Milestone Bug

#59216 Fix baselines from PR 59203
  tests/baselines/reference/declarationEmitIsolatedDeclarationErrorNotEmittedForNonEmittedFile.types
Labels: Author: Team, For Uncommitted Bug

#59223 Disable noEmitOnError
  src/tsconfig-base.json
Labels: Author: Team, For Uncommitted Bug

#59208 Write non-missing undefined on mapped type results into output
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitExactOptionalPropertyTypesNodeNotReused(exactoptionalpropertytypes=false).js
  tests/baselines/reference/declarationEmitExactOptionalPropertyTypesNodeNotReused(exactoptionalpropertytypes=false).symbols
  tests/baselines/reference/declarationEmitExactOptionalPropertyTypesNodeNotReused(exactoptionalpropertytypes=false).types
  tests/baselines/reference/declarationEmitExactOptionalPropertyTypesNodeNotReused(exactoptionalpropertytypes=true).js
  tests/baselines/reference/declarationEmitExactOptionalPropertyTypesNodeNotReused(exactoptionalpropertytypes=true).symbols
  tests/baselines/reference/declarationEmitExactOptionalPropertyTypesNodeNotReused(exactoptionalpropertytypes=true).types
  tests/baselines/reference/declarationEmitUsingAlternativeContainingModules1.types
  tests/baselines/reference/declarationEmitUsingAlternativeContainingModules2.types
  tests/baselines/reference/identityAndDivergentNormalizedTypes.types
  tests/baselines/reference/isomorphicMappedTypeInference.types
  tests/baselines/reference/mappedTypeErrors.types
  tests/cases/compiler/declarationEmitExactOptionalPropertyTypesNodeNotReused.ts
Labels: Author: Team, For Milestone Bug

#59215 Fix codefix crash on circular aliases
  src/services/exportInfoMap.ts
  tests/baselines/reference/tsserver/fourslashServer/importFixes_ambientCircularDefaultCrash.js
  tests/cases/fourslash/server/importFixes_ambientCircularDefaultCrash.ts
Labels: Author: Team, For Milestone Bug

#59026 fix(59011): TypeScript generates invalid types if @import tags are spread over multiple lines
  src/compiler/parser.ts
  src/compiler/scanner.ts
  src/compiler/types.ts
  tests/baselines/reference/importTag18.js
  tests/baselines/reference/importTag18.symbols
  tests/baselines/reference/importTag18.types
  tests/baselines/reference/importTag19.js
  tests/baselines/reference/importTag19.symbols
  tests/baselines/reference/importTag19.types
  tests/baselines/reference/importTag20.js
  tests/baselines/reference/importTag20.symbols
  tests/baselines/reference/importTag20.types
  tests/baselines/reference/importTag6.types
  tests/baselines/reference/importTag7.types
  tests/baselines/reference/signatureHelpInferenceJsDocImportTag.baseline
  tests/cases/conformance/jsdoc/importTag18.ts
  tests/cases/conformance/jsdoc/importTag19.ts
  tests/cases/conformance/jsdoc/importTag20.ts
  tests/cases/fourslash/signatureHelpInferenceJsDocImportTag.ts
Labels: For Milestone Bug

#59243 Do not reuse ambient module name resolution from other files while determining if resolution can be reused
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/program.ts
  src/compiler/resolutionCache.ts
  src/compiler/types.ts
  src/testRunner/unittests/helpers/tscWatch.ts
  src/testRunner/unittests/reuseProgramStructure.ts
  src/testRunner/unittests/tscWatch/moduleResolution.ts
  src/testRunner/unittests/tscWatch/resolutionCache.ts
  src/testRunner/unittests/tsserver/resolutionCache.ts
  tests/baselines/reference/reuseProgramStructure/should-not-reuse-ambient-module-declarations-from-non-modified-files.js
  tests/baselines/reference/tscWatch/moduleResolution/ambient-module-names-are-resolved-correctly.js
  tests/baselines/reference/tscWatch/resolutionCache/works-when-module-resolution-changes-to-ambient-module.js
  tests/baselines/reference/tsserver/completions/works-when-files-are-included-from-two-different-drives-of-windows.js
  tests/baselines/reference/tsserver/projectErrors/correct-errors-when-resolution-resolves-to-file-that-has-same-ambient-module-and-is-also-module.js
  tests/baselines/reference/tsserver/resolutionCache/when-resolution-fails.js
  tests/baselines/reference/tsserver/resolutionCache/when-resolves-to-ambient-module.js
Labels: Author: Team, For Uncommitted Bug

#59232 Fixed regression in reverse mapped type inference caused by cache leak
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypeRecursiveInference.errors.txt
  tests/baselines/reference/mappedTypeRecursiveInference.types
  tests/baselines/reference/reverseMappedTypeInferenceSameSource1.symbols
  tests/baselines/reference/reverseMappedTypeInferenceSameSource1.types
  tests/cases/compiler/reverseMappedTypeInferenceSameSource1.ts
Labels: For Uncommitted Bug

#59183 Fix circularity errors in intra-binding-pattern references
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/types.ts
  tests/baselines/reference/checkDestructuringShorthandAssigment.types
  tests/baselines/reference/checkDestructuringShorthandAssigment2.errors.txt
  tests/baselines/reference/circularReferenceInReturnType2.types
  tests/baselines/reference/contextualTypeForInitalizedVariablesFiltersUndefined.types
  tests/baselines/reference/controlFlowDestructuringVariablesInTryCatch.types
  tests/baselines/reference/declarationsAndAssignments.errors.txt
  tests/baselines/reference/declarationsAndAssignments.types
  tests/baselines/reference/destructuredLateBoundNameHasCorrectTypes.errors.txt
  tests/baselines/reference/destructuredLateBoundNameHasCorrectTypes.types
  tests/baselines/reference/destructuringArrayBindingPatternAndAssignment3.types
  tests/baselines/reference/destructuringFromUnionSpread.errors.txt
  tests/baselines/reference/destructuringFromUnionSpread.types
  tests/baselines/reference/destructuringObjectBindingPatternAndAssignment3.errors.txt
  tests/baselines/reference/destructuringObjectBindingPatternAndAssignment3.types
  tests/baselines/reference/destructuringObjectBindingPatternAndAssignment9SiblingInitializer.types
  tests/baselines/reference/destructuringSpread.errors.txt
  tests/baselines/reference/destructuringSpread.types
  tests/baselines/reference/destructuringWithLiteralInitializers.types
  tests/baselines/reference/esDecorators-classExpression-missingEmitHelpers-classDecorator.17.errors.txt
  tests/baselines/reference/intraBindingPatternReferences.errors.txt
  tests/baselines/reference/intraBindingPatternReferences.symbols
  tests/baselines/reference/intraBindingPatternReferences.types
  tests/baselines/reference/missingAndExcessProperties.errors.txt
  tests/baselines/reference/missingAndExcessProperties.types
  tests/baselines/reference/parserForOfStatement25.errors.txt
  tests/baselines/reference/parserForOfStatement25.types
  tests/baselines/reference/parserForStatement9.types
  tests/baselines/reference/privateNameFieldDestructuredBinding(target=es2015).types
  tests/baselines/reference/privateNameFieldDestructuredBinding(target=es2022).types
  tests/baselines/reference/privateNameFieldDestructuredBinding(target=esnext).types
  tests/baselines/reference/privateNameStaticFieldDestructuredBinding(target=es2015).types
  tests/baselines/reference/privateNameStaticFieldDestructuredBinding(target=es2022).types
  tests/baselines/reference/privateNameStaticFieldDestructuredBinding(target=esnext).types
  tests/baselines/reference/shorthandPropertyAssignmentsInDestructuring.errors.txt
  tests/baselines/reference/shorthandPropertyAssignmentsInDestructuring.types
  tests/baselines/reference/shorthandPropertyAssignmentsInDestructuring_ES6.errors.txt
  tests/baselines/reference/shorthandPropertyAssignmentsInDestructuring_ES6.types
  tests/baselines/reference/useBeforeDeclaration_destructuring.types
  tests/cases/compiler/intraBindingPatternReferences.ts
Labels: Author: Team, For Milestone Bug, For Backlog Bug

#59089 Fixed crash on circular local type arguments when outer ones are present too
  src/compiler/checker.ts
  tests/baselines/reference/circularTypeArgumentsLocalAndOuterNoCrash1.errors.txt
  tests/baselines/reference/circularTypeArgumentsLocalAndOuterNoCrash1.symbols
  tests/baselines/reference/circularTypeArgumentsLocalAndOuterNoCrash1.types
  tests/cases/compiler/circularTypeArgumentsLocalAndOuterNoCrash1.ts
Labels: For Uncommitted Bug

#59300 Verify that perf_hooks result actually contains the performance object
  src/compiler/performanceCore.ts
Labels: Author: Team, For Uncommitted Bug

#59286 Store information in buildInfo to repopulate mode mismatch based on status of package.json
  src/compiler/builder.ts
  src/compiler/checker.ts
  src/compiler/moduleNameResolver.ts
  src/compiler/moduleSpecifiers.ts
  src/compiler/program.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/server/session.ts
  src/testRunner/unittests/tsc/moduleResolution.ts
  tests/baselines/reference/tsc/composite/synthetic-jsx-import-of-ESM-module-from-CJS-module-error-on-jsx-element.js
  tests/baselines/reference/tsc/moduleResolution/package-json-scope.js
Labels: Author: Team, For Uncommitted Bug

#59163 fix: fix the return type of Int8Array::toReversed in es2023.array.d.ts
  src/lib/es2023.array.d.ts
Labels: For Uncommitted Bug

#59305 Revert "🤖 Pick PR #59285 (Fix captured shorthand properties i...) into release-5.5 (#59288)"
  src/compiler/checker.ts
  src/compiler/utilities.ts
  tests/baselines/reference/capturedShorthandPropertyAssignmentNoCheck.js
  tests/baselines/reference/capturedShorthandPropertyAssignmentNoCheck.symbols
  tests/baselines/reference/capturedShorthandPropertyAssignmentNoCheck.types
  tests/baselines/reference/checkJsdocTypeTagOnObjectProperty2.types
  tests/baselines/reference/complicatedIndexedAccessKeyofReliesOnKeyofNeverUpperBound.types
  tests/baselines/reference/declarationEmitDestructuringObjectLiteralPattern.types
  tests/baselines/reference/declarationEmitDestructuringObjectLiteralPattern2.types
  tests/baselines/reference/declarationsAndAssignments.types
  tests/baselines/reference/inferenceOptionalPropertiesToIndexSignatures.types
  tests/baselines/reference/jsExportAssignmentNonMutableLocation.types
  tests/baselines/reference/literalFreshnessPropagationOnNarrowing.types
  tests/baselines/reference/shorthand-property-es5-es6.types
  tests/baselines/reference/shorthand-property-es6-amd.types
  tests/baselines/reference/shorthand-property-es6-es6.types
  tests/baselines/reference/shorthandOfExportedEntity01_targetES2015_CommonJS.types
  tests/baselines/reference/shorthandOfExportedEntity02_targetES5_CommonJS.types
  tests/baselines/reference/systemObjectShorthandRename.types
  tests/cases/compiler/capturedShorthandPropertyAssignmentNoCheck.ts
Labels: Author: Team, For Uncommitted Bug

#59285 Fix captured shorthand properties in ES2015 loops
  src/compiler/checker.ts
  src/compiler/utilities.ts
  tests/baselines/reference/capturedShorthandPropertyAssignmentNoCheck.js
  tests/baselines/reference/capturedShorthandPropertyAssignmentNoCheck.symbols
  tests/baselines/reference/capturedShorthandPropertyAssignmentNoCheck.types
  tests/cases/compiler/capturedShorthandPropertyAssignmentNoCheck.ts
Labels: Author: Team, For Milestone Bug

#59193 Mark `jsxFactorySymbol` as referenced for noUnusedLocals even in verbatimModuleSyntax
  src/compiler/checker.ts
  tests/cases/compiler/verbatimModuleSyntaxReactReference.ts
Labels: Author: Team, For Milestone Bug

#59137 `visitNodesWithoutCopyingPositions` always makes a new `NodeArray`
  src/compiler/checker.ts
  tests/cases/fourslash/nodeArrayCloneCrash.ts
Labels: Author: Team, For Milestone Bug

#59306 fix(59304): Convert to ESM uses template strings instead of string literals
  src/services/codefixes/requireInTs.ts
  tests/cases/fourslash/codeFixRequireInTs4.ts
  tests/cases/fourslash/codeFixRequireInTs5.ts
Labels: For Backlog Bug

#59311 Always watch package jsons for the sourceFile
  src/compiler/resolutionCache.ts
  src/testRunner/unittests/tscWatch/moduleResolution.ts
  tests/baselines/reference/tscWatch/moduleResolution/type-reference-resolutions-with-impliedMode.js
Labels: Author: Team, For Uncommitted Bug

#59045 Derive tuple labels for rest elements from array binding patterns
  src/compiler/checker.ts
  tests/baselines/reference/argumentsSpreadRestIterables(target=es5).types
  tests/baselines/reference/argumentsSpreadRestIterables(target=esnext).types
  tests/baselines/reference/genericRestParameters2.types
  tests/baselines/reference/iterableArrayPattern14.types
  tests/baselines/reference/iterableArrayPattern25.types
  tests/baselines/reference/restParameterWithBindingPattern2.types
  tests/baselines/reference/restParameterWithBindingPattern3.types
  tests/baselines/reference/restTupleElements1.types
  tests/baselines/reference/restTuplesFromContextualTypes.types
  tests/baselines/reference/signatureHelpExpandedRestTuplesLocalLabels1.baseline
  tests/baselines/reference/variadicTuples1.js
  tests/baselines/reference/variadicTuples1.types
  tests/cases/fourslash/signatureHelpExpandedRestTuplesLocalLabels1.ts
  tests/cases/fourslash/signatureHelpExpandedRestUnlabeledTuples.ts
Labels: Author: Team, For Backlog Bug

#58982 Fix: False Positive "Range out of order in character class" in Regular Expressions in Unicode Modes
  src/compiler/scanner.ts
  tests/baselines/reference/regularExpressionCharacterClassRangeOrder.errors.txt
  tests/baselines/reference/regularExpressionCharacterClassRangeOrder.js
  tests/baselines/reference/regularExpressionCharacterClassRangeOrder.symbols
  tests/baselines/reference/regularExpressionCharacterClassRangeOrder.types
  tests/cases/compiler/regularExpressionCharacterClassRangeOrder.ts
Labels: For Uncommitted Bug

#59328 Work around inconsistent recursive directory watch events
  src/testRunner/unittests/sys/symlinkWatching.ts
Labels: Author: Team, For Uncommitted Bug

#59330 Fix baselines on release-5.5
  tests/baselines/reference/capturedShorthandPropertyAssignmentNoCheck.types
  tests/baselines/reference/declarationEmitIsolatedDeclarationErrorNotEmittedForNonEmittedFile.types
  tests/baselines/reference/excessiveStackDepthFlatArray.types
Labels: Author: Team, For Uncommitted Bug

#58850 Use monocart for coverage reports, enable codecov
  .c8rc.json
  .github/codecov.yml
  .github/workflows/ci.yml
  knip.jsonc
  package-lock.json
  package.json
  scripts/build/tests.mjs
Labels: Author: Team, For Uncommitted Bug

#59334 Fix coverage uploading
  .github/workflows/ci.yml
Labels: Author: Team, For Uncommitted Bug

#59325 Don't skip markLinkedReferences on ambient properties
  src/compiler/checker.ts
  tests/baselines/reference/decoratorMetadataElidedImportOnDeclare(module=commonjs).js
  tests/baselines/reference/decoratorMetadataElidedImportOnDeclare(module=commonjs).symbols
  tests/baselines/reference/decoratorMetadataElidedImportOnDeclare(module=commonjs).types
  tests/baselines/reference/decoratorMetadataElidedImportOnDeclare(module=esnext).js
  tests/baselines/reference/decoratorMetadataElidedImportOnDeclare(module=esnext).symbols
  tests/baselines/reference/decoratorMetadataElidedImportOnDeclare(module=esnext).types
  tests/cases/compiler/decoratorMetadataElidedImportOnDeclare.ts
Labels: Author: Team, For Milestone Bug

#59160 Fixed crash on authored import type nodes when serializing for declarations
  src/services/codefixes/helpers.ts
  tests/cases/fourslash/completionsClassMemberImportTypeNodeParameter1.ts
  tests/cases/fourslash/completionsClassMemberImportTypeNodeParameter2.ts
  tests/cases/fourslash/completionsClassMemberImportTypeNodeParameter3.ts
  tests/cases/fourslash/completionsClassMemberImportTypeNodeParameter4.ts
Labels: For Milestone Bug

#58981 Provide User-Friendly Message for Extended Unicode Escapes in Regular Expressions in Non-Unicode Modes
  src/compiler/diagnosticMessages.json
  src/compiler/scanner.ts
  tests/baselines/reference/regularExpressionCharacterClassRangeOrder.errors.txt
  tests/baselines/reference/regularExpressionExtendedUnicodeEscapes.errors.txt
  tests/baselines/reference/regularExpressionExtendedUnicodeEscapes.js
  tests/baselines/reference/regularExpressionExtendedUnicodeEscapes.symbols
  tests/baselines/reference/regularExpressionExtendedUnicodeEscapes.types
  tests/cases/compiler/regularExpressionExtendedUnicodeEscapes.ts
Labels: For Uncommitted Bug

#59188 Update deps
  .dprint.jsonc
  package-lock.json
  package.json
  scripts/dtsBundler.mjs
Labels: Author: Team, For Uncommitted Bug

#59347 Stop using latest Node in CI
  .github/workflows/ci.yml
  .github/workflows/update-package-lock.yaml
Labels: Author: Team, For Uncommitted Bug

#59348 Cherry-pick "Stop using latest Node in CI" to release-5.5
  .github/workflows/ci.yml
  .github/workflows/update-package-lock.yaml
Labels: Author: Team, For Uncommitted Bug

#59259 DOM update 2024-07-12
  src/lib/dom.generated.d.ts
  src/lib/dom.iterable.generated.d.ts
  src/lib/webworker.generated.d.ts
  src/lib/webworker.iterable.generated.d.ts
  tests/baselines/reference/contextuallyTypedParametersWithInitializers1.symbols
  tests/baselines/reference/globalThisBlockscopedProperties.types
  tests/baselines/reference/importMeta(module=commonjs,target=es5).types
  tests/baselines/reference/importMeta(module=commonjs,target=esnext).types
  tests/baselines/reference/importMeta(module=es2020,target=es5).types
  tests/baselines/reference/importMeta(module=es2020,target=esnext).types
  tests/baselines/reference/importMeta(module=esnext,target=es5).types
  tests/baselines/reference/importMeta(module=esnext,target=esnext).types
  tests/baselines/reference/importMeta(module=system,target=es5).types
  tests/baselines/reference/importMeta(module=system,target=esnext).types
  tests/baselines/reference/mappedTypeRecursiveInference.errors.txt
  tests/baselines/reference/mappedTypeRecursiveInference.types
Labels: Author: Team, For Uncommitted Bug

#59351 Dont filter type aquisition when its not enabled
  src/server/project.ts
Labels: Author: Team, For Uncommitted Bug

#59360 Use tuple name inference for `Iterator.next` et al
  src/lib/es2015.generator.d.ts
  src/lib/es2015.iterable.d.ts
  src/lib/es2018.asyncgenerator.d.ts
  src/lib/es2018.asynciterable.d.ts
  tests/baselines/reference/dependentDestructuredVariables.types
  tests/baselines/reference/destructuringAssignmentWithDefault2.types
  tests/baselines/reference/discriminateWithOptionalProperty2(exactoptionalpropertytypes=false).types
  tests/baselines/reference/discriminateWithOptionalProperty2(exactoptionalpropertytypes=true).types
  tests/baselines/reference/iterableTReturnTNext(strictbuiltiniteratorreturn=false).types
  tests/baselines/reference/iterableTReturnTNext(strictbuiltiniteratorreturn=true).types
  tests/baselines/reference/privateNameMethodAsync.types
  tests/baselines/reference/privateNameStaticMethodAsync.types
  tests/baselines/reference/signatureHelpIteratorNext.baseline
  tests/cases/fourslash/signatureHelpIteratorNext.ts
Labels: Author: Team, For Uncommitted Bug

#59366 Manual update of generated DOM and Worker libs
  src/lib/dom.asynciterable.generated.d.ts
  src/lib/dom.iterable.generated.d.ts
  src/lib/webworker.asynciterable.generated.d.ts
  src/lib/webworker.iterable.generated.d.ts
Labels: Author: Team, For Uncommitted Bug

#59368 Add fast paths for 'BuiltinIterator' and 'AsyncBuiltinIterator'
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug

#58608 fix35982: allow BigIntLiteral to parse as PropertyName for literal object and indices
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/parser.ts
  src/compiler/transformers/destructuring.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/bigintArbirtraryIdentifier.errors.txt
  tests/baselines/reference/bigintArbirtraryIdentifier.js
  tests/baselines/reference/bigintArbirtraryIdentifier.symbols
  tests/baselines/reference/bigintArbirtraryIdentifier.types
  tests/baselines/reference/bigintIndex.errors.txt
  tests/baselines/reference/bigintIndex.js
  tests/baselines/reference/bigintIndex.symbols
  tests/baselines/reference/bigintIndex.types
  tests/baselines/reference/bigintPropertyName.errors.txt
  tests/baselines/reference/bigintPropertyName.js
  tests/baselines/reference/bigintPropertyName.symbols
  tests/baselines/reference/bigintPropertyName.types
  tests/cases/compiler/bigintArbirtraryIdentifier.ts
  tests/cases/compiler/bigintIndex.ts
  tests/cases/compiler/bigintPropertyName.ts
Labels: Breaking Change, API, Author: Team, For Milestone Bug

#59358 Update dprint to pick up comment bugfix
  .dprint.jsonc
Labels: Author: Team, For Uncommitted Bug

#59388 Use 'BuiltinAsyncIterator' spelling
  src/compiler/checker.ts
  src/lib/dom.asynciterable.generated.d.ts
  src/lib/es2018.asyncgenerator.d.ts
  src/lib/es2018.asynciterable.d.ts
  src/lib/webworker.asynciterable.generated.d.ts
Labels: Author: Team, For Uncommitted Bug

#57701 Use more universal ANSI sequence for 'clear screen and clear buffer'
  src/compiler/sys.ts
Labels: For Backlog Bug

#59376 Don't crash when observing invalid `export`s in any kind of container
  src/services/documentHighlights.ts
  tests/baselines/reference/exportInLabeledStatement.baseline.jsonc
  tests/cases/fourslash/exportInLabeledStatement.ts
Labels: For Uncommitted Bug

#59374 Fixed a crash when transforming modules with top-level labels
  src/compiler/transformers/module/module.ts
  src/compiler/transformers/module/system.ts
  tests/baselines/reference/labeledStatementExportDeclarationNoCrash1(module=commonjs).errors.txt
  tests/baselines/reference/labeledStatementExportDeclarationNoCrash1(module=commonjs).js
  tests/baselines/reference/labeledStatementExportDeclarationNoCrash1(module=commonjs).symbols
  tests/baselines/reference/labeledStatementExportDeclarationNoCrash1(module=commonjs).types
  tests/baselines/reference/labeledStatementExportDeclarationNoCrash1(module=esnext).errors.txt
  tests/baselines/reference/labeledStatementExportDeclarationNoCrash1(module=esnext).js
  tests/baselines/reference/labeledStatementExportDeclarationNoCrash1(module=esnext).symbols
  tests/baselines/reference/labeledStatementExportDeclarationNoCrash1(module=esnext).types
  tests/baselines/reference/labeledStatementExportDeclarationNoCrash1(module=system).errors.txt
  tests/baselines/reference/labeledStatementExportDeclarationNoCrash1(module=system).js
  tests/baselines/reference/labeledStatementExportDeclarationNoCrash1(module=system).symbols
  tests/baselines/reference/labeledStatementExportDeclarationNoCrash1(module=system).types
  tests/cases/conformance/statements/labeledStatements/labeledStatementExportDeclarationNoCrash1.ts
Labels: For Uncommitted Bug

#59375 Fixed crash when transforming modules with top-level if statements incorrectly containining export statements
  src/compiler/transformers/module/module.ts
  src/compiler/transformers/module/system.ts
  tests/baselines/reference/exportNonInitializedVariablesInIfThenStatementNoCrash1(module=commonjs).errors.txt
  tests/baselines/reference/exportNonInitializedVariablesInIfThenStatementNoCrash1(module=commonjs).js
  tests/baselines/reference/exportNonInitializedVariablesInIfThenStatementNoCrash1(module=commonjs).symbols
  tests/baselines/reference/exportNonInitializedVariablesInIfThenStatementNoCrash1(module=commonjs).types
  tests/baselines/reference/exportNonInitializedVariablesInIfThenStatementNoCrash1(module=esnext).errors.txt
  tests/baselines/reference/exportNonInitializedVariablesInIfThenStatementNoCrash1(module=esnext).js
  tests/baselines/reference/exportNonInitializedVariablesInIfThenStatementNoCrash1(module=esnext).symbols
  tests/baselines/reference/exportNonInitializedVariablesInIfThenStatementNoCrash1(module=esnext).types
  tests/baselines/reference/exportNonInitializedVariablesInIfThenStatementNoCrash1(module=system).errors.txt
  tests/baselines/reference/exportNonInitializedVariablesInIfThenStatementNoCrash1(module=system).js
  tests/baselines/reference/exportNonInitializedVariablesInIfThenStatementNoCrash1(module=system).symbols
  tests/baselines/reference/exportNonInitializedVariablesInIfThenStatementNoCrash1(module=system).types
  tests/cases/conformance/externalModules/exportNonInitializedVariablesInIfThenStatementNoCrash1.ts
Labels: For Uncommitted Bug

#59280 Fixed crash in `classFields` transform related to broken bodyless constructors
  src/compiler/transformers/classFields.ts
  tests/baselines/reference/classFieldsBrokenConstructorEmitNoCrash1.errors.txt
  tests/baselines/reference/classFieldsBrokenConstructorEmitNoCrash1.js
  tests/baselines/reference/classFieldsBrokenConstructorEmitNoCrash1.symbols
  tests/baselines/reference/classFieldsBrokenConstructorEmitNoCrash1.types
  tests/cases/compiler/classFieldsBrokenConstructorEmitNoCrash1.ts
Labels: For Uncommitted Bug

#59120 fix(58772): Duplicate exports.* = assignments in CommonJS output in some cases
  src/compiler/transformers/utilities.ts
  tests/baselines/reference/exportsAndImports5.js
  tests/baselines/reference/exportsAndImports5.symbols
  tests/baselines/reference/exportsAndImports5.types
  tests/cases/conformance/es6/modules/exportsAndImports5.ts
Labels: For Milestone Bug

#59369 Fixing range for primary edit
  src/server/project.ts
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_addInNextLine.js
  tests/cases/fourslash/server/pasteEdits_addInNextLine.ts
Labels: Author: Team, For Milestone Bug

#59395 Update deps, to TS 5.5.4
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#59398 Skip markLinkedReferences import elision walk entirely in some common cases
  src/compiler/checker.ts
  src/compiler/emitter.ts
Labels: Author: Team, For Uncommitted Bug

#58007 Deprecate module keyword for namespace declarations
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/utilities.ts
  tests/cases/fourslash/moduleDeclarationDeprecated_suggestion1.ts
  tests/cases/fourslash/moduleDeclarationDeprecated_suggestion2.ts
Labels: For Milestone Bug

#55728 Remove stableSort, rename sort to toSorted
  src/compiler/core.ts
  src/compiler/debug.ts
  src/compiler/emitter.ts
  src/compiler/executeCommandLine.ts
  src/compiler/moduleNameResolver.ts
  src/compiler/program.ts
  src/compiler/utilities.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/harness/harnessIO.ts
  src/server/project.ts
  src/services/codefixes/importFixes.ts
  src/services/completions.ts
  src/services/organizeImports.ts
  src/services/textChanges.ts
  src/services/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#59359 Unpin Node 22 now that 22.5.1 is out
  .github/workflows/ci.yml
Labels: Author: Team, For Uncommitted Bug

#59410 Fix completion entry conversion to protocol format
  src/server/session.ts
  tests/baselines/reference/completionsServerCommitCharacters.baseline
  tests/baselines/reference/tsserver/completions/works-when-files-are-included-from-two-different-drives-of-windows.js
  tests/baselines/reference/tsserver/fourslashServer/completionEntryDetailAcrossFiles01.js
  tests/baselines/reference/tsserver/fourslashServer/completionEntryDetailAcrossFiles02.js
  tests/baselines/reference/tsserver/fourslashServer/completionsServerCommitCharacters.js
  tests/baselines/reference/tsserver/fourslashServer/jsdocParamTagSpecialKeywords.js
  tests/baselines/reference/tsserver/fourslashServer/jsdocTypedefTag.js
  tests/baselines/reference/tsserver/fourslashServer/jsdocTypedefTag1.js
  tests/baselines/reference/tsserver/fourslashServer/jsdocTypedefTag2.js
  tests/baselines/reference/tsserver/fourslashServer/jsdocTypedefTagNamespace.js
  tests/baselines/reference/tsserver/fourslashServer/openFileWithSyntaxKind.js
  tests/cases/fourslash/server/completionsServerCommitCharacters.ts
Labels: Author: Team, For Uncommitted Bug

#59213 fix(59116): Codefix add missing function declaration inserts function in wrong file
  src/services/codefixes/fixAddMissingMember.ts
  tests/cases/fourslash/codeFixAddMissingFunctionDeclaration29.ts
Labels: For Backlog Bug

#59418 Use open file to determine file existence
  src/compiler/watchUtilities.ts
  src/server/editorServices.ts
  src/server/project.ts
  src/testRunner/unittests/tsserver/getEditsForFileRename.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/tsserver/cachingFileSystemInformation/works-using-legacy-resolution-logic.js
  tests/baselines/reference/tsserver/configuredProjects/creating-new-file-and-then-open-it-after-watcher-is-invoked,-ask-errors-on-it-after-old-one-without-file-being-in-config.js
  tests/baselines/reference/tsserver/configuredProjects/creating-new-file-and-then-open-it-after-watcher-is-invoked,-ask-errors-on-it-after-old-one.js
  tests/baselines/reference/tsserver/configuredProjects/creating-new-file-and-then-open-it-after-watcher-is-invoked,-ask-errors-on-it-before-old-one-without-file-being-in-config.js
  tests/baselines/reference/tsserver/configuredProjects/creating-new-file-and-then-open-it-after-watcher-is-invoked,-ask-errors-on-it-before-old-one.js
  tests/baselines/reference/tsserver/configuredProjects/creating-new-file-and-then-open-it-before-watcher-is-invoked,-ask-errors-on-it-after-old-one-without-file-being-in-config.js
  tests/baselines/reference/tsserver/configuredProjects/creating-new-file-and-then-open-it-before-watcher-is-invoked,-ask-errors-on-it-after-old-one.js
  tests/baselines/reference/tsserver/configuredProjects/creating-new-file-and-then-open-it-before-watcher-is-invoked,-ask-errors-on-it-before-old-one-without-file-being-in-config.js
  tests/baselines/reference/tsserver/configuredProjects/creating-new-file-and-then-open-it-before-watcher-is-invoked,-ask-errors-on-it-before-old-one.js
  tests/baselines/reference/tsserver/externalProjects/handles-creation-of-external-project-with-jsconfig-before-jsconfig-creation-watcher-is-invoked.js
  tests/baselines/reference/tsserver/getEditsForFileRename/works-with-when-file-is-opened-after-seeing-file-existance-on-the-disk-with-updateOpen.js
  tests/baselines/reference/tsserver/getEditsForFileRename/works-with-when-file-is-opened-after-seeing-file-existance-on-the-disk.js
  tests/baselines/reference/tsserver/getEditsForFileRename/works-with-when-file-is-opened-before-seeing-file-existance-on-the-disk-closed-before-change-with-updateOpen.js
  tests/baselines/reference/tsserver/getEditsForFileRename/works-with-when-file-is-opened-before-seeing-file-existance-on-the-disk-closed-before-change.js
  tests/baselines/reference/tsserver/getEditsForFileRename/works-with-when-file-is-opened-before-seeing-file-existance-on-the-disk-with-updateOpen.js
  tests/baselines/reference/tsserver/getEditsForFileRename/works-with-when-file-is-opened-before-seeing-file-existance-on-the-disk.js
  tests/baselines/reference/tsserver/inferredProjects/should-still-retain-configured-project-created-while-opening-the-file.js
  tests/baselines/reference/tsserver/openfile/uses-existing-project-even-if-project-refresh-is-pending.js
  tests/baselines/reference/tsserver/projectErrors/file-rename-on-wsl2.js
  tests/baselines/reference/tsserver/projects/handles-delayed-directory-watch-invoke-on-file-creation.js
  tests/baselines/reference/tsserver/projects/loading-files-with-correct-priority.js
Labels: Author: Team, For Milestone Bug

#58903 `organizeImports` makes no changes if there are parse errors in the sourceFile
  src/services/services.ts
  src/testRunner/unittests/services/organizeImports.ts
  tests/baselines/reference/organizeImports/JsxFactoryUsedTs.ts
  tests/baselines/reference/organizeImports/Syntax_Error_Body.ts
  tests/baselines/reference/organizeImports/Syntax_Error_Body_skipDestructiveCodeActions.ts
  tests/baselines/reference/organizeImports/Syntax_Error_Imports.ts
  tests/baselines/reference/organizeImports/Syntax_Error_Imports_skipDestructiveCodeActions.ts
  tests/baselines/reference/organizeImports/parseErrors.ts
  tests/cases/fourslash/organizeImports17.ts
Labels: Author: Team, For Milestone Bug

#59427 Don't include "this is a crash" as a version in the bug template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Author: Team, For Uncommitted Bug

#59426 Tighten signature of append
  src/compiler/core.ts
  src/server/session.ts
  src/testRunner/unittests/tsbuildWatch/watchEnvironment.ts
Labels: Author: Team, For Uncommitted Bug

#58049 Bailout early from `isFunctionObjectType` for evolving arrays
  src/compiler/checker.ts
  tests/baselines/reference/narrowSwitchOptionalChainContainmentEvolvingArrayNoCrash1.errors.txt
  tests/baselines/reference/narrowSwitchOptionalChainContainmentEvolvingArrayNoCrash1.symbols
  tests/baselines/reference/narrowSwitchOptionalChainContainmentEvolvingArrayNoCrash1.types
  tests/cases/compiler/narrowSwitchOptionalChainContainmentEvolvingArrayNoCrash1.ts
Labels: For Milestone Bug

#58958 Fixed quick fixes for inferred type predicates
  src/compiler/checker.ts
  src/compiler/types.ts
  src/services/codefixes/fixMissingTypeAnnotationOnExports.ts
  src/services/codefixes/helpers.ts
  src/services/refactors/inferFunctionReturnType.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExportsTypePredicate1.ts
  tests/cases/fourslash/refactorInferFunctionReturnTypePredicate1.ts
Labels: For Backlog Bug

#59436 Bring back exported defaultInitCompilerOptions
  src/compiler/commandLineParser.ts
Labels: Author: Team, For Uncommitted Bug

#59434 Fixed crashed related to emptied labeled statements in converted loop bodies
  src/compiler/transformers/es2015.ts
  src/compiler/transformers/module/module.ts
  tests/baselines/reference/capturedLetConstInLoop14.errors.txt
  tests/baselines/reference/capturedLetConstInLoop14.js
  tests/baselines/reference/labeledStatementDeclarationListInLoopNoCrash1.errors.txt
  tests/baselines/reference/labeledStatementDeclarationListInLoopNoCrash1.js
  tests/baselines/reference/labeledStatementDeclarationListInLoopNoCrash2.js
  tests/baselines/reference/labeledStatementDeclarationListInLoopNoCrash3.errors.txt
  tests/baselines/reference/labeledStatementDeclarationListInLoopNoCrash3.js
  tests/baselines/reference/labeledStatementDeclarationListInLoopNoCrash4.errors.txt
  tests/baselines/reference/labeledStatementDeclarationListInLoopNoCrash4.js
  tests/cases/compiler/capturedLetConstInLoop14.ts
  tests/cases/conformance/statements/labeledStatements/labeledStatementDeclarationListInLoopNoCrash1.ts
  tests/cases/conformance/statements/labeledStatements/labeledStatementDeclarationListInLoopNoCrash2.ts
  tests/cases/conformance/statements/labeledStatements/labeledStatementDeclarationListInLoopNoCrash3.ts
  tests/cases/conformance/statements/labeledStatements/labeledStatementDeclarationListInLoopNoCrash4.ts
Labels: For Milestone Bug

#59416 Don’t enforce export/declare overload modifier consistency across module augmentations
  src/compiler/checker.ts
  tests/baselines/reference/missingFunctionImplementation2.errors.txt
  tests/baselines/reference/parserStrictMode8.errors.txt
  tests/cases/compiler/crossFileOverloadModifierConsistency.ts
Labels: Author: Team, For Milestone Bug

#59428 Fixed crash related to creating file diagnostics outside of the source file range in `checkPotentialUncheckedRenamedBindingElementsInTypes`
  src/compiler/checker.ts
  tests/baselines/reference/parametersSyntaxErrorNoCrash1.errors.txt
  tests/baselines/reference/parametersSyntaxErrorNoCrash2.errors.txt
  tests/baselines/reference/parametersSyntaxErrorNoCrash3.errors.txt
  tests/cases/compiler/parametersSyntaxErrorNoCrash1.ts
  tests/cases/compiler/parametersSyntaxErrorNoCrash2.ts
  tests/cases/compiler/parametersSyntaxErrorNoCrash3.ts
Labels: For Milestone Bug

#59441 Fixed inlay hints for inferred type predicates
  src/services/inlayHints.ts
  tests/baselines/reference/inlayHintsInferredTypePredicate1.baseline
  tests/baselines/reference/inlayHintsInteractiveInferredTypePredicate1.baseline
  tests/cases/fourslash/inlayHintsInferredTypePredicate1.ts
  tests/cases/fourslash/inlayHintsInteractiveInferredTypePredicate1.ts
Labels: For Uncommitted Bug

#59468 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20240730011406039 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#59438 Move ambient const enum error from use site to import in verbatimModuleSyntax
  src/compiler/checker.ts
  src/testRunner/unittests/tsc/projectReferences.ts
  tests/baselines/reference/tsc/projectReferences/importing-const-enum-from-referenced-project-with-preserveConstEnums-and-verbatimModuleSyntax.js
  tests/baselines/reference/verbatimModuleSyntaxAmbientConstEnum.errors.txt
  tests/cases/conformance/externalModules/verbatimModuleSyntaxAmbientConstEnum.ts
Labels: Author: Team, For Milestone Bug

#59493 Use local symbol rather then target symbol for tracking reused references
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitEnumReferenceViaImportEquals.js
  tests/baselines/reference/declarationEmitEnumReferenceViaImportEquals.symbols
  tests/baselines/reference/declarationEmitEnumReferenceViaImportEquals.types
  tests/baselines/reference/declarationEmitForModuleImportingModuleAugmentationRetainsImport.types
  tests/baselines/reference/declarationEmitUsingTypeAlias2.types
  tests/baselines/reference/exportClassExtendingIntersection.types
  tests/baselines/reference/functionVariableInReturnTypeAnnotation.types
  tests/baselines/reference/importDecl.types
  tests/baselines/reference/isolatedDeclarationErrorsAugmentation.types
  tests/baselines/reference/umd-augmentation-1.types
  tests/baselines/reference/umd-augmentation-2.types
  tests/baselines/reference/umd-augmentation-3.types
  tests/baselines/reference/umd-augmentation-4.types
  tests/cases/compiler/declarationEmitEnumReferenceViaImportEquals.ts
Labels: Author: Team, For Milestone Bug
