Repository microsoft/TypeScript, pull requests merged in 2024-12, with the labels that each got.

#60416 Allow assignments to readonly class properties within IIFEs contained in constructors
  src/compiler/checker.ts
  tests/baselines/reference/readonlyMembers.errors.txt
  tests/baselines/reference/readonlyMembers.js
  tests/baselines/reference/readonlyMembers.symbols
  tests/baselines/reference/readonlyMembers.types
  tests/cases/compiler/readonlyMembers.ts
Labels: For Uncommitted Bug

#60644 Check if switch statements are exhaustive when their expressions is generic with a literal type constraint
  src/compiler/checker.ts
  tests/baselines/reference/dependentReturnType9.errors.txt
  tests/baselines/reference/dependentReturnType9.symbols
  tests/baselines/reference/dependentReturnType9.types
  tests/cases/compiler/dependentReturnType9.ts
Labels: For Uncommitted Bug

#60622 Fix library inclusions for ES2024 target
  src/compiler/commandLineParser.ts
  src/compiler/transformers/esnext.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/compiler/utilitiesPublic.ts
  tests/baselines/reference/tscWatch/symlinks/monorepo-style-sibling-packages-symlinked-Linux.js
  tests/baselines/reference/tscWatch/symlinks/monorepo-style-sibling-packages-symlinked-package1-built-Linux.js
  tests/baselines/reference/tscWatch/symlinks/packages-outside-project-folder-Linux.js
  tests/baselines/reference/tscWatch/symlinks/packages-outside-project-folder-MacOs.js
  tests/baselines/reference/tscWatch/symlinks/packages-outside-project-folder-built-Linux.js
  tests/baselines/reference/tscWatch/symlinks/packages-outside-project-folder-built-MacOs.js
  tests/baselines/reference/tscWatch/watchEnvironment/fsWatch/fsWatchWithTimestamp-true-useFsEventsOnParentDirectory.js
  tests/baselines/reference/tscWatch/watchEnvironment/fsWatch/fsWatchWithTimestamp-true.js
  tests/baselines/reference/tscWatch/watchEnvironment/fsWatch/when-using-file-watching-thats-on-inode-when-rename-event-ends-with-tilde.js
  tests/baselines/reference/tscWatch/watchEnvironment/fsWatch/when-using-file-watching-thats-on-inode-when-rename-occurs-when-file-is-still-on-the-disk.js
  tests/baselines/reference/tscWatch/watchEnvironment/fsWatch/when-using-file-watching-thats-on-inode.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchDirectories/uses-non-recursive-dynamic-polling-when-renaming-file-in-subfolder.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchDirectories/uses-non-recursive-watchDirectory-when-renaming-file-in-subfolder.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchDirectories/uses-watchFile-when-renaming-file-in-subfolder.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchDirectories/when-there-are-symlinks-to-folders-in-recursive-folders-with-synchronousWatchDirectory.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchDirectories/when-there-are-symlinks-to-folders-in-recursive-folders.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchDirectories/with-non-synchronous-watch-directory-renaming-a-file.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchDirectories/with-non-synchronous-watch-directory-with-outDir-and-declaration-enabled.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchDirectories/with-non-synchronous-watch-directory.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchOptions/with-excludeDirectories-option-with-recursive-directory-watching-extendedDiagnostics.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchOptions/with-excludeDirectories-option-with-recursive-directory-watching.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchOptions/with-fallbackPolling-option.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchOptions/with-watchDirectory-option.js
  tests/baselines/reference/tsserver/projectErrors/file-rename-on-wsl2.js
  tests/baselines/reference/tsserver/resolutionCache/when-resolution-fails-in-global-typings-location-with-currentDirectory-at-root.js
  tests/baselines/reference/tsserver/resolutionCache/when-resolution-fails-in-global-typings-location.js
  tests/baselines/reference/tsserver/resolutionCache/when-resolution-is-succeeds-in-global-typings-location-with-import-from-the-cache-file-failing-with-currentDirectory-at-root.js
  tests/baselines/reference/tsserver/resolutionCache/when-resolution-is-succeeds-in-global-typings-location-with-import-from-the-cache-file-failing.js
  tests/baselines/reference/tsserver/resolutionCache/when-resolution-is-succeeds-in-global-typings-location-with-import-from-the-cache-file-with-currentDirectory-at-root.js
  tests/baselines/reference/tsserver/resolutionCache/when-resolution-is-succeeds-in-global-typings-location-with-import-from-the-cache-file.js
  tests/baselines/reference/tsserver/resolutionCache/when-resolution-is-succeeds-in-global-typings-location-with-relative-import-from-the-cache-file-with-currentDirectory-at-root.js
  tests/baselines/reference/tsserver/resolutionCache/when-resolution-is-succeeds-in-global-typings-location-with-relative-import-from-the-cache-file.js
  tests/baselines/reference/tsserver/symLinks/monorepo-style-sibling-packages-symlinked-Linux-canUseWatchEvents.js
  tests/baselines/reference/tsserver/symLinks/monorepo-style-sibling-packages-symlinked-Linux.js
  tests/baselines/reference/tsserver/symLinks/monorepo-style-sibling-packages-symlinked-package1-built-Linux-canUseWatchEvents.js
  tests/baselines/reference/tsserver/symLinks/monorepo-style-sibling-packages-symlinked-package1-built-Linux.js
  tests/baselines/reference/tsserver/symLinks/packages-outside-project-folder-Linux-canUseWatchEvents.js
  tests/baselines/reference/tsserver/symLinks/packages-outside-project-folder-Linux.js
  tests/baselines/reference/tsserver/symLinks/packages-outside-project-folder-MacOs-canUseWatchEvents.js
  tests/baselines/reference/tsserver/symLinks/packages-outside-project-folder-MacOs.js
  tests/baselines/reference/tsserver/symLinks/packages-outside-project-folder-built-Linux-canUseWatchEvents.js
  tests/baselines/reference/tsserver/symLinks/packages-outside-project-folder-built-Linux.js
  tests/baselines/reference/tsserver/symLinks/packages-outside-project-folder-built-MacOs-canUseWatchEvents.js
  tests/baselines/reference/tsserver/symLinks/packages-outside-project-folder-built-MacOs.js
  tests/baselines/reference/tsserver/watchEnvironment/recursive-directory-does-not-watch-files-starting-with-dot-in-node_modules.js
  tests/baselines/reference/tsserver/watchEnvironment/uses-dynamic-polling-when-file-is-added-to-subfolder.js
  tests/baselines/reference/tsserver/watchEnvironment/uses-non-recursive-watchDirectory-when-file-is-added-to-subfolder.js
  tests/baselines/reference/tsserver/watchEnvironment/uses-watchFile-when-file-is-added-to-subfolder.js
  tests/baselines/reference/tsserver/watchEnvironment/watching-npm-install-in-codespaces-where-workspaces-folder-is-hosted-at-root.js
Labels: For Milestone Bug

#60673 Do not require import attributes for JSON imports in `--module node16`
  src/compiler/checker.ts
  tests/baselines/reference/nodeModulesJson(module=node16).errors.txt
  tests/baselines/reference/nodeModulesJson(module=node16).symbols
  tests/baselines/reference/nodeModulesJson(module=node16).types
  tests/baselines/reference/nodeModulesJson(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesJson(module=nodenext).symbols
  tests/baselines/reference/nodeModulesJson(module=nodenext).types
  tests/cases/conformance/node/nodeModulesJson.ts
Labels: Author: Team, For Milestone Bug

#60662 Fix flow node improper reuse
  src/compiler/binder.ts
  tests/cases/fourslash/unreachableStatementNodeReuse.ts
Labels: Author: Team, For Uncommitted Bug

#60576 Avoid incorrectly reusing assertion nodes from property assignments
  src/compiler/expressionToTypeNode.ts
  tests/baselines/reference/declarationAssertionNodeNotReusedWhenTypeNotEquivalent1.js
  tests/baselines/reference/declarationAssertionNodeNotReusedWhenTypeNotEquivalent1.symbols
  tests/baselines/reference/declarationAssertionNodeNotReusedWhenTypeNotEquivalent1.types
  tests/cases/compiler/declarationAssertionNodeNotReusedWhenTypeNotEquivalent1.ts
  tests/cases/fourslash/quickInfoAssertionNodeNotReusedWhenTypeNotEquivalent1.ts
Labels: For Milestone Bug

#60680 Mark the inherited any-based index signature so it can be elided in declaration emit
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitClassInherritsAny.js
  tests/baselines/reference/declarationEmitClassInherritsAny.symbols
  tests/baselines/reference/declarationEmitClassInherritsAny.types
  tests/cases/compiler/declarationEmitClassInherritsAny.ts
Labels: Author: Team, For Milestone Bug

#59853 Include type-meaning 'extends' clause in auto-import fix list
  src/services/codefixes/importFixes.ts
  tests/cases/fourslash/importNameCodeFix_all.ts
Labels: Author: Team, For Milestone Bug

#60683 Cache started nonexistent property error checks to prevent reentrancy in the check
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/checkingObjectWithThisInNamePositionNoCrash.errors.txt
  tests/baselines/reference/checkingObjectWithThisInNamePositionNoCrash.js
  tests/baselines/reference/checkingObjectWithThisInNamePositionNoCrash.symbols
  tests/baselines/reference/checkingObjectWithThisInNamePositionNoCrash.types
  tests/cases/compiler/checkingObjectWithThisInNamePositionNoCrash.ts
Labels: Author: Team, For Milestone Bug

#60684 Lookup non-local element factory for reference marking when marking fragment references
  src/compiler/checker.ts
  tests/baselines/reference/jsxFragmentAndFactoryUsedOnFragmentUse.js
  tests/baselines/reference/jsxFragmentAndFactoryUsedOnFragmentUse.symbols
  tests/baselines/reference/jsxFragmentAndFactoryUsedOnFragmentUse.types
  tests/cases/compiler/jsxFragmentAndFactoryUsedOnFragmentUse.tsx
Labels: Author: Team, For Milestone Bug

#60690 Add extra test cases for fixed `reportNonexistentProperty` crashes
  tests/baselines/reference/checkingObjectDefinePropertyOnFunctionNonexistentPropertyNoCrash1.errors.txt
  tests/baselines/reference/checkingObjectDefinePropertyOnFunctionNonexistentPropertyNoCrash1.js
  tests/baselines/reference/checkingObjectDefinePropertyOnFunctionNonexistentPropertyNoCrash1.symbols
  tests/baselines/reference/checkingObjectDefinePropertyOnFunctionNonexistentPropertyNoCrash1.types
  tests/baselines/reference/findAllRefsNonexistentPropertyNoCrash1.baseline.jsonc
  tests/cases/compiler/checkingObjectDefinePropertyOnFunctionNonexistentPropertyNoCrash1.ts
  tests/cases/fourslash/findAllRefsNonexistentPropertyNoCrash1.ts
Labels: For Backlog Bug

#60541 Switch coverage image from ubuntu-22.04 to mariner-2.0
  .github/workflows/ci.yml
Labels: For Uncommitted Bug

#60691 Error on `override` used on dynamically named class members
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/overrideDynamicName1(noimplicitoverride=false).errors.txt
  tests/baselines/reference/overrideDynamicName1(noimplicitoverride=false).js
  tests/baselines/reference/overrideDynamicName1(noimplicitoverride=false).symbols
  tests/baselines/reference/overrideDynamicName1(noimplicitoverride=false).types
  tests/baselines/reference/overrideDynamicName1(noimplicitoverride=true).errors.txt
  tests/baselines/reference/overrideDynamicName1(noimplicitoverride=true).js
  tests/baselines/reference/overrideDynamicName1(noimplicitoverride=true).symbols
  tests/baselines/reference/overrideDynamicName1(noimplicitoverride=true).types
  tests/baselines/reference/overrideLateBindableIndexSignature1(noimplicitoverride=false).errors.txt
  tests/baselines/reference/overrideLateBindableIndexSignature1(noimplicitoverride=false).js
  tests/baselines/reference/overrideLateBindableIndexSignature1(noimplicitoverride=false).symbols
  tests/baselines/reference/overrideLateBindableIndexSignature1(noimplicitoverride=false).types
  tests/baselines/reference/overrideLateBindableIndexSignature1(noimplicitoverride=true).errors.txt
  tests/baselines/reference/overrideLateBindableIndexSignature1(noimplicitoverride=true).js
  tests/baselines/reference/overrideLateBindableIndexSignature1(noimplicitoverride=true).symbols
  tests/baselines/reference/overrideLateBindableIndexSignature1(noimplicitoverride=true).types
  tests/baselines/reference/overrideLateBindableName1(noimplicitoverride=false).errors.txt
  tests/baselines/reference/overrideLateBindableName1(noimplicitoverride=false).js
  tests/baselines/reference/overrideLateBindableName1(noimplicitoverride=false).symbols
  tests/baselines/reference/overrideLateBindableName1(noimplicitoverride=false).types
  tests/baselines/reference/overrideLateBindableName1(noimplicitoverride=true).errors.txt
  tests/baselines/reference/overrideLateBindableName1(noimplicitoverride=true).js
  tests/baselines/reference/overrideLateBindableName1(noimplicitoverride=true).symbols
  tests/baselines/reference/overrideLateBindableName1(noimplicitoverride=true).types
  tests/cases/conformance/override/overrideDynamicName1.ts
  tests/cases/conformance/override/overrideLateBindableIndexSignature1.ts
  tests/cases/conformance/override/overrideLateBindableName1.ts
Labels: Breaking Change, For Backlog Bug

#60696 Fix incorrect usage of package.json `types`/`main` in package subdirectories
  src/compiler/moduleNameResolver.ts
  tests/baselines/reference/moduleResolution_packageJson_yesAtPackageRoot.trace.json
  tests/baselines/reference/moduleResolution_packageJson_yesAtPackageRoot_fakeScopedPackage.trace.json
  tests/baselines/reference/typesVersions.ambientModules.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.ambient.trace.json
Labels: Author: Team, For Uncommitted Bug

#60687 Remove reference not found errors from `jsx: preserve`
  src/compiler/checker.ts
  tests/baselines/reference/jsxFragmentFactoryReference(jsx=react).errors.txt
  tests/baselines/reference/jsxFragmentFactoryReference(jsx=react-jsx).errors.txt
  tests/baselines/reference/jsxFragmentFactoryReference(jsx=react-jsxdev).errors.txt
  tests/baselines/reference/jsxJsxsCjsTransformCustomImport(jsx=react-jsx).errors.txt
  tests/baselines/reference/jsxJsxsCjsTransformCustomImport(jsx=react-jsxdev).errors.txt
  tests/baselines/reference/jsxJsxsCjsTransformCustomImportPragma(jsx=react-jsx).errors.txt
  tests/baselines/reference/jsxJsxsCjsTransformCustomImportPragma(jsx=react-jsxdev).errors.txt
  tests/baselines/reference/jsxRuntimePragma(jsx=preserve).js
  tests/baselines/reference/jsxRuntimePragma(jsx=preserve).symbols
  tests/baselines/reference/jsxRuntimePragma(jsx=preserve).types
  tests/baselines/reference/parseUnaryExpressionNoTypeAssertionInJsx2.errors.txt
  tests/baselines/reference/parseUnaryExpressionNoTypeAssertionInJsx4.errors.txt
  tests/cases/compiler/jsxFragmentFactoryReference.tsx
  tests/cases/compiler/jsxRuntimePragma.ts
Labels: Author: Team, For Uncommitted Bug

#60749 Do not require import attribute on type-only JSON import
  src/compiler/checker.ts
  tests/baselines/reference/nodeModulesJson(module=node16).errors.txt
  tests/baselines/reference/nodeModulesJson(module=node16).symbols
  tests/baselines/reference/nodeModulesJson(module=node16).types
  tests/baselines/reference/nodeModulesJson(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesJson(module=nodenext).symbols
  tests/baselines/reference/nodeModulesJson(module=nodenext).types
  tests/cases/conformance/node/nodeModulesJson.ts
Labels: Author: Team, For Milestone Bug

#60752 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20241212204530251 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#60779 Point TypeScript-Twoslash-Repro-Action back to main branch
  .github/workflows/twoslash-repros.yaml
Labels: Author: Team, For Uncommitted Bug

#60780 Use macos-latest in CI
  .github/workflows/ci.yml
Labels: Author: Team, For Uncommitted Bug

#60777 Cherry-pick #60402, #60440, #60616 into release-5.7
  src/compiler/checker.ts
  tests/baselines/reference/predicateSemantics.errors.txt
  tests/baselines/reference/predicateSemantics.js
  tests/baselines/reference/predicateSemantics.symbols
  tests/baselines/reference/predicateSemantics.types
  tests/cases/compiler/predicateSemantics.ts
Labels: Author: Team, For Uncommitted Bug

#60792 Fix coverage build on release-5.7
  .github/workflows/ci.yml
Labels: Author: Team, For Uncommitted Bug

#60794 Harden `sanitizeLog` against incorrect matches on TypeScript versions.
  src/harness/tsserverLogger.ts
Labels: Author: Team, For Uncommitted Bug

#60797 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20241217202808030 to main
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#60802 Add tests for `getNormalizedAbsolutePath`.
  src/testRunner/unittests/paths.ts
Labels: Author: Team, For Uncommitted Bug

#60781 Update dependencies
  .dprint.jsonc
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#60795 Improve `unknown` narrowing by negated type predicates
  src/compiler/checker.ts
  tests/baselines/reference/narrowUnknownByTypePredicate.symbols
  tests/baselines/reference/narrowUnknownByTypePredicate.types
  tests/cases/compiler/narrowUnknownByTypePredicate.ts
Labels: For Uncommitted Bug

#60393 Don't try to add an implicit undefined for mapped properties outside of `strictNullChecks`
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitOptionalMappedTypePropertyNoStrictNullChecks1.js
  tests/baselines/reference/declarationEmitOptionalMappedTypePropertyNoStrictNullChecks1.symbols
  tests/baselines/reference/declarationEmitOptionalMappedTypePropertyNoStrictNullChecks1.types
  tests/baselines/reference/declarationEmitOptionalMappedTypePropertyNoStrictNullChecks2.js
  tests/baselines/reference/declarationEmitOptionalMappedTypePropertyNoStrictNullChecks2.symbols
  tests/baselines/reference/declarationEmitOptionalMappedTypePropertyNoStrictNullChecks2.types
  tests/baselines/reference/declarationEmitOptionalMappedTypePropertyNoStrictNullChecks3.js
  tests/baselines/reference/declarationEmitOptionalMappedTypePropertyNoStrictNullChecks3.symbols
  tests/baselines/reference/declarationEmitOptionalMappedTypePropertyNoStrictNullChecks3.types
  tests/baselines/reference/declarationEmitOptionalMappedTypePropertyNoStrictNullChecks4.js
  tests/baselines/reference/declarationEmitOptionalMappedTypePropertyNoStrictNullChecks4.symbols
  tests/baselines/reference/declarationEmitOptionalMappedTypePropertyNoStrictNullChecks4.types
  tests/cases/compiler/declarationEmitOptionalMappedTypePropertyNoStrictNullChecks1.ts
  tests/cases/compiler/declarationEmitOptionalMappedTypePropertyNoStrictNullChecks2.ts
  tests/cases/compiler/declarationEmitOptionalMappedTypePropertyNoStrictNullChecks3.ts
  tests/cases/compiler/declarationEmitOptionalMappedTypePropertyNoStrictNullChecks4.ts
Labels: For Milestone Bug

#60826 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20241219202405650 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug
