Repository microsoft/TypeScript, pull requests merged in 2024-10, with the labels that each got.

#60109 Remove references to tsserverlibrary.d.ts baseline from workflows
  .github/workflows/new-release-branch.yaml
  .github/workflows/pr-modified-files.yml
  .github/workflows/set-version.yaml
Labels: Author: Team, For Uncommitted Bug

#60083 Don't issue implicit any when obtaining the implied type for a binding pattern
  src/compiler/checker.ts
  tests/baselines/reference/destructuringParameterDeclaration10(strict=false).symbols
  tests/baselines/reference/destructuringParameterDeclaration10(strict=false).types
  tests/baselines/reference/destructuringParameterDeclaration10(strict=true).symbols
  tests/baselines/reference/destructuringParameterDeclaration10(strict=true).types
  tests/baselines/reference/destructuringParameterDeclaration9(strict=false).symbols
  tests/baselines/reference/destructuringParameterDeclaration9(strict=false).types
  tests/baselines/reference/destructuringParameterDeclaration9(strict=true).errors.txt
  tests/baselines/reference/destructuringParameterDeclaration9(strict=true).symbols
  tests/baselines/reference/destructuringParameterDeclaration9(strict=true).types
  tests/cases/conformance/es6/destructuring/destructuringParameterDeclaration10.ts
  tests/cases/conformance/es6/destructuring/destructuringParameterDeclaration9.ts
Labels: Author: Team, For Backlog Bug

#60122 fix fragment resolving behavior with `jsx: preserve` and `jsxFragmentFactory: null`
  src/compiler/checker.ts
  tests/baselines/reference/inlineJsxAndJsxFragPragma.errors.txt
  tests/baselines/reference/inlineJsxAndJsxFragPragmaOverridesCompilerOptions.errors.txt
  tests/baselines/reference/inlineJsxAndJsxFragPragmaOverridesCompilerOptions.types
  tests/baselines/reference/jsxFactoryAndJsxFragmentFactory.types
  tests/baselines/reference/jsxFactoryAndJsxFragmentFactoryNull.errors.txt
  tests/baselines/reference/jsxFactoryAndJsxFragmentFactoryNull.types
Labels: Author: Team, For Uncommitted Bug

#60136 Fix grammar issue in TS9025 diagnostic message
  src/compiler/diagnosticMessages.json
  src/compiler/transformers/declarations/diagnostics.ts
  src/services/codefixes/fixMissingTypeAnnotationOnExports.ts
  tests/baselines/reference/transpile/declarationFunctionDeclarations.d.ts
Labels: For Uncommitted Bug

#60157 fix automatic type acquisition
  src/typingsInstaller/nodeTypingsInstaller.ts
Labels: For Uncommitted Bug

#60152 fix(59825): getNavigationTree crash on invalid class merge and function merge with expando members
  src/services/navigationBar.ts
  tests/cases/fourslash/navigationBarItemsClass6.ts
Labels: For Milestone Bug

#60163 Fix the type of `growable` on `SharedArrayBuffer`.
  src/lib/es2024.sharedmemory.d.ts
Labels: Author: Team, For Uncommitted Bug

#60147 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20241005101925367 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#60002 [release-5.6] Remove tsbuildInfo specification error now that we need it for non incremental scenarios as well and there is no way to disable it (#59960)
  src/compiler/diagnosticMessages.json
  src/compiler/emitter.ts
  src/compiler/program.ts
  tests/baselines/reference/optionsTsBuildInfoFileWithoutIncrementalAndComposite.errors.txt
  tests/baselines/reference/tsc/composite/when-setting-composite-false-on-command-line-but-has-tsbuild-info-in-config.js
Labels: Author: Team, For Uncommitted Bug

#60174 Fix codecov on PRs
  .github/workflows/ci.yml
Labels: Author: Team, For Uncommitted Bug

#60129 Avoid confusing TS9025 error in `isolatedDeclarations`
  src/compiler/checker.ts
  tests/baselines/reference/isolatedDeclarationsAddUndefined2.errors.txt
  tests/baselines/reference/isolatedDeclarationsAddUndefined2.js
  tests/baselines/reference/isolatedDeclarationsAddUndefined2.symbols
  tests/baselines/reference/isolatedDeclarationsAddUndefined2.types
  tests/cases/compiler/isolatedDeclarationsAddUndefined2.ts
Labels: For Backlog Bug

#60195 Assume that type node annotations resolving to error types can be reused
  src/compiler/checker.ts
  tests/baselines/reference/circularTypeofWithVarOrFunc.types
  tests/baselines/reference/isolatedDeclarationErrorTypes1.errors.txt
  tests/baselines/reference/isolatedDeclarationErrorTypes1.js
  tests/baselines/reference/isolatedDeclarationErrorTypes1.symbols
  tests/baselines/reference/isolatedDeclarationErrorTypes1.types
  tests/baselines/reference/isolatedDeclarationsAddUndefined2.types
  tests/cases/compiler/isolatedDeclarationErrorTypes1.ts
Labels: For Uncommitted Bug

#60203 moveToNewFile: fix quotes for module specifiers
  src/services/codefixes/importFixes.ts
  tests/cases/fourslash/moveToNewFile_inferQuoteStyle1.ts
  tests/cases/fourslash/moveToNewFile_inferQuoteStyle2.ts
  tests/cases/fourslash/moveToNewFile_moveNamedImport1.ts
  tests/cases/fourslash/moveToNewFile_moveNamedImport2.ts
Labels: Author: Team, For Uncommitted Bug

#60191 fix(60186): Quick fix "add missing properties" fails with enums from other module
  src/services/codefixes/fixAddMissingMember.ts
  tests/cases/fourslash/codeFixAddMissingProperties32.ts
Labels: For Uncommitted Bug

#60224 Fix decorator emit crash
  src/compiler/transformers/esDecorators.ts
  src/compiler/transformers/legacyDecorators.ts
  src/compiler/transformers/utilities.ts
  tests/baselines/reference/parameterDecoratorsEmitCrash.errors.txt
  tests/baselines/reference/parameterDecoratorsEmitCrash.js
  tests/cases/compiler/parameterDecoratorsEmitCrash.ts
Labels: Author: Team, For Milestone Bug

#60035 Fixed default-like export info lookup with `export=` that have `default` export
  src/services/exportInfoMap.ts
  tests/cases/fourslash/autoImportCompletionExportEqualsWithDefault1.ts
Labels: For Uncommitted Bug

#60228 Do not mark #imports and self-name imports as external library imports in module resolution
  src/compiler/moduleNameResolver.ts
  tests/baselines/reference/nodeModulesAllowJsConditionalPackageExports(module=node16).js
  tests/baselines/reference/nodeModulesAllowJsConditionalPackageExports(module=nodenext).js
  tests/baselines/reference/nodeModulesAllowJsPackageExports(module=node16).js
  tests/baselines/reference/nodeModulesAllowJsPackageExports(module=nodenext).js
  tests/baselines/reference/nodeModulesAllowJsPackageImports(module=node16).js
  tests/baselines/reference/nodeModulesAllowJsPackageImports(module=nodenext).js
  tests/baselines/reference/nodeModulesPackageImports(module=node16).trace.json
  tests/baselines/reference/nodeModulesPackageImports(module=nodenext).trace.json
  tests/baselines/reference/nodeModulesPackagePatternExportsTrailers(module=node16).trace.json
  tests/baselines/reference/nodeModulesPackagePatternExportsTrailers(module=nodenext).trace.json
  tests/baselines/reference/selfNameAndImportsEmitInclusion.js
  tests/baselines/reference/selfNameModuleAugmentation.trace.json
  tests/baselines/reference/tsbuild/moduleResolution/shared-resolution-should-not-report-error.js
  tests/baselines/reference/tsbuild/moduleResolution/when-resolution-is-not-shared.js
  tests/baselines/reference/tscWatch/forceConsistentCasingInFileNames/package-json-is-looked-up-for-file.js
  tests/baselines/reference/tscWatch/forceConsistentCasingInFileNames/self-name-package-reference.js
  tests/baselines/reference/tscWatch/moduleResolution/diagnostics-from-cache.js
  tests/cases/compiler/selfNameAndImportsEmitInclusion.ts
Labels: Author: Team, For Milestone Bug

#60236 Handle auto-import when `paths` pattern is absolute
  src/compiler/moduleSpecifiers.ts
  tests/cases/fourslash/autoImportPathsConfigDir.ts
Labels: Author: Team, For Milestone Bug

#59732 Allow auto accessor types to be inferred from their flow types in constructors and static blocks
  src/compiler/checker.ts
  tests/baselines/reference/classAccessorInitializationInferenceWithElementAccess1.js
  tests/baselines/reference/classAccessorInitializationInferenceWithElementAccess1.symbols
  tests/baselines/reference/classAccessorInitializationInferenceWithElementAccess1.types
  tests/baselines/reference/classAttributeInferenceTemplate.js
  tests/baselines/reference/classAttributeInferenceTemplate.symbols
  tests/baselines/reference/classAttributeInferenceTemplate.types
  tests/baselines/reference/classAttributeInferenceTemplateJS.symbols
  tests/baselines/reference/classAttributeInferenceTemplateJS.types
  tests/baselines/reference/classStaticBlockUseBeforeDef4.js
  tests/baselines/reference/classStaticBlockUseBeforeDef4.symbols
  tests/baselines/reference/classStaticBlockUseBeforeDef4.types
  tests/baselines/reference/classStaticBlockUseBeforeDef5.errors.txt
  tests/baselines/reference/classStaticBlockUseBeforeDef5.js
  tests/baselines/reference/classStaticBlockUseBeforeDef5.symbols
  tests/baselines/reference/classStaticBlockUseBeforeDef5.types
  tests/baselines/reference/controlFlowAutoAccessor1.errors.txt
  tests/baselines/reference/controlFlowAutoAccessor1.js
  tests/baselines/reference/controlFlowAutoAccessor1.symbols
  tests/baselines/reference/controlFlowAutoAccessor1.types
  tests/baselines/reference/inlayHintsPropertyDeclarations2.baseline
  tests/cases/compiler/classAccessorInitializationInferenceWithElementAccess1.ts
  tests/cases/compiler/classAttributeInferenceTemplate.ts
  tests/cases/compiler/classAttributeInferenceTemplateJS.ts
  tests/cases/compiler/controlFlowAutoAccessor1.ts
  tests/cases/conformance/classes/classStaticBlock/classStaticBlockUseBeforeDef4.ts
  tests/cases/conformance/classes/classStaticBlock/classStaticBlockUseBeforeDef5.ts
  tests/cases/fourslash/inlayHintsPropertyDeclarations2.ts
Labels: For Milestone Bug

#60225 Fix ASI after get/set keyword
  src/compiler/parser.ts
  tests/baselines/reference/canFollowGetSetKeyword.errors.txt
  tests/baselines/reference/canFollowGetSetKeyword.js
  tests/cases/conformance/classes/propertyMemberDeclarations/canFollowGetSetKeyword.ts
Labels: Author: Team, For Milestone Bug

#60240 Fix `--showConfig` to show transitively implied options that vary from the default config
  src/compiler/commandLineParser.ts
  src/compiler/utilities.ts
  src/server/editorServices.ts
  src/services/codefixes/convertConstToLet.ts
  src/services/codefixes/convertToTypeOnlyExport.ts
  src/services/codefixes/fixAddMissingConstraint.ts
  src/services/codefixes/fixAddMissingMember.ts
  src/services/codefixes/fixAwaitInSyncFunction.ts
  src/services/codefixes/fixClassDoesntImplementInheritedAbstractMember.ts
  src/services/codefixes/fixClassIncorrectlyImplementsInterface.ts
  src/services/codefixes/fixClassSuperMustPrecedeThisAccess.ts
  src/services/completions.ts
  src/services/exportInfoMap.ts
  src/services/findAllReferences.ts
  src/services/refactors/extractType.ts
  src/services/stringCompletions.ts
  src/services/textChanges.ts
  src/testRunner/unittests/config/showConfig.ts
  tests/baselines/reference/config/showConfig/Show TSConfig with transitively implied options/tsconfig.json
Labels: Author: Team, For Milestone Bug

#60257 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20241017172255112 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#60183 Disallow type and interface declarations in statements with blockless bodies
  src/compiler/checker.ts
  tests/baselines/reference/typeAliasDeclarationEmit3.errors.txt
  tests/baselines/reference/typeInterfaceDeclarationsInBlockStatements1.errors.txt
  tests/baselines/reference/typeInterfaceDeclarationsInBlockStatements1.js
  tests/baselines/reference/typeInterfaceDeclarationsInBlockStatements1.symbols
  tests/baselines/reference/typeInterfaceDeclarationsInBlockStatements1.types
  tests/cases/compiler/typeInterfaceDeclarationsInBlockStatements1.ts
Labels: For Backlog Bug

#59504 fix(59463): Feature that displays method argument names inline does not correctly handle method overloading
  src/services/inlayHints.ts
  tests/baselines/reference/inlayHintsOverloadCall1.baseline
  tests/baselines/reference/inlayHintsOverloadCall2.baseline
  tests/cases/fourslash/inlayHintsOverloadCall1.ts
  tests/cases/fourslash/inlayHintsOverloadCall2.ts
Labels: For Backlog Bug

#60303 Fix template string escaping
  src/compiler/utilities.ts
  src/testRunner/unittests/printer.ts
  tests/baselines/reference/printerApi/printsNodeCorrectly.template string.js
Labels: Author: Team, For Milestone Bug

#59760 Add a test for constraint of an infer type parameter not being fully instantiated previously
  tests/baselines/reference/inferTypesWithExtendsDependingOnTypeVariables.symbols
  tests/baselines/reference/inferTypesWithExtendsDependingOnTypeVariables.types
  tests/cases/conformance/types/conditional/inferTypesWithExtendsDependingOnTypeVariables.ts
Labels: For Milestone Bug

#60321 Error on too many parameters for iterator method
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/asyncIteratorExtraParameters.errors.txt
  tests/baselines/reference/iteratorExtraParameters.errors.txt
  tests/cases/compiler/asyncIteratorExtraParameters.ts
  tests/cases/compiler/iteratorExtraParameters.ts
Labels: Author: Team, For Milestone Bug

#55178 fix(55168): Computed properties do not respect setter signatures
  tests/baselines/reference/computedPropertiesWithSetterAssignment.js
  tests/baselines/reference/computedPropertiesWithSetterAssignment.symbols
  tests/baselines/reference/computedPropertiesWithSetterAssignment.types
  tests/cases/compiler/computedPropertiesWithSetterAssignment.ts
Labels: For Backlog Bug

#59797 fix(59779): The semicolons: "remove" formatting option doesn't remove extraneous semicolons
  src/services/formatting/rules.ts
  tests/cases/fourslash/formatRemoveSemicolons1.ts
  tests/cases/fourslash/formatRemoveSemicolons4.ts
Labels: For Backlog Bug

#60304 More rigorous ASI prevention when emitting `return`/`yield`
  src/compiler/emitter.ts
  tests/baselines/reference/returnStatementNoAsiAfterTransform(target=es5).js
  tests/baselines/reference/returnStatementNoAsiAfterTransform(target=esnext).js
  tests/baselines/reference/yieldStatementNoAsiAfterTransform(target=es5).js
  tests/baselines/reference/yieldStatementNoAsiAfterTransform(target=esnext).js
  tests/cases/conformance/generators/yieldStatementNoAsiAfterTransform.ts
  tests/cases/conformance/statements/returnStatements/returnStatementNoAsiAfterTransform.ts
Labels: Author: Team, For Milestone Bug

#60313 Fixed crash in auto import suggestions for `default` of exported UMD objects
  src/services/utilities.ts
  tests/cases/fourslash/completionsImportDefaultExportCrash1.ts
  tests/cases/fourslash/completionsImportDefaultExportCrash2.ts
  tests/cases/fourslash/completionsImport_umdDefaultNoCrash1.ts
  tests/cases/fourslash/completionsImport_umdDefaultNoCrash2.ts
Labels: For Uncommitted Bug

#60328 Fixed "add missing properties" codefix for positions with nullable contextual types
  src/services/codefixes/fixAddMissingMember.ts
  tests/cases/fourslash/codeFixAddMissingProperties30.ts
  tests/cases/fourslash/codeFixAddMissingProperties31.ts
  tests/cases/fourslash/codeFixAddMissingProperties45.ts
  tests/cases/fourslash/codeFixAddMissingProperties46.ts
  tests/cases/fourslash/codeFixAddMissingProperties47.ts
  tests/cases/fourslash/codeFixAddMissingProperties48.ts
Labels: For Uncommitted Bug

#59675 fix(59397): JsDoc is missing/duplicated in declarations for overloads declared in classes declared in functions
  src/compiler/checker.ts
  tests/baselines/reference/signatureOverloadsWithComments.js
  tests/baselines/reference/signatureOverloadsWithComments.symbols
  tests/baselines/reference/signatureOverloadsWithComments.types
  tests/cases/compiler/signatureOverloadsWithComments.ts
Labels: For Backlog Bug

#60238 Fix prioritization of `paths` specifiers over node_modules package specifiers
  src/compiler/moduleSpecifiers.ts
  tests/cases/fourslash/autoImportPathsNodeModules.ts
Labels: Author: Team, For Milestone Bug

#60358 Fixed a JSDoc-related crash when obtaining type of a type literal type argument
  src/compiler/checker.ts
  tests/cases/fourslash/completionsJSDocNoCrash3.ts
Labels: For Uncommitted Bug

#60339 fix paste edits range: include all completely selected identifiers
  src/services/pasteEdits.ts
  src/services/textChanges.ts
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_rangeSelection0.js
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_rangeSelection1.js
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_rangeSelection2.js
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_rangeSelection3.js
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_rangeSelection4.js
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_rangeSelection5.js
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_rangeSelection6.js
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_rangeSelection7.js
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_rangeSelection8.js
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_rangeSelection9.js
  tests/cases/fourslash/server/pasteEdits_rangeSelection0.ts
  tests/cases/fourslash/server/pasteEdits_rangeSelection1.ts
  tests/cases/fourslash/server/pasteEdits_rangeSelection2.ts
  tests/cases/fourslash/server/pasteEdits_rangeSelection3.ts
  tests/cases/fourslash/server/pasteEdits_rangeSelection4.ts
  tests/cases/fourslash/server/pasteEdits_rangeSelection5.ts
  tests/cases/fourslash/server/pasteEdits_rangeSelection6.ts
  tests/cases/fourslash/server/pasteEdits_rangeSelection7.ts
  tests/cases/fourslash/server/pasteEdits_rangeSelection8.ts
  tests/cases/fourslash/server/pasteEdits_rangeSelection9.ts
Labels: Author: Team, For Uncommitted Bug

#60377 Fix a crash in an anonymous buffer that copilot is writing to.
  src/server/scriptVersionCache.ts
Labels: Author: Team, For Milestone Bug

#60385 Remove unused `SymbolLinks["bindingElement"]`
  src/compiler/checker.ts
  src/compiler/types.ts
Labels: For Uncommitted Bug

#58816 Use `canHaveFlowNode` in `checkIfExpressionRefinesParameter`
  src/compiler/checker.ts
Labels: For Uncommitted Bug

#60340 Fixed crash on class member completions with auto imports from merged ambient modules
  src/services/codefixes/importFixes.ts
  tests/cases/fourslash/autoImportCompletionAmbientMergedModule1.ts
Labels: For Uncommitted Bug

#58669 Fixed an accidental `undefined` leak into `getAccessibleSymbolChain`'s cache key
  src/compiler/checker.ts
Labels: For Uncommitted Bug
