Repository microsoft/TypeScript, pull requests merged in 2024-03, with the labels that each got.

#57586 Fixed a crash when computing flow type of destructured never
  src/compiler/checker.ts
  tests/baselines/reference/autoTypeAssignedUsingDestructuringFromNeverNoCrash.errors.txt
  tests/baselines/reference/autoTypeAssignedUsingDestructuringFromNeverNoCrash.symbols
  tests/baselines/reference/autoTypeAssignedUsingDestructuringFromNeverNoCrash.types
  tests/cases/compiler/autoTypeAssignedUsingDestructuringFromNeverNoCrash.ts
Labels: For Milestone Bug

#57598 Add baselines missed in #56902
  tests/baselines/reference/bundlerDirectoryModule(moduleresolution=bundler).trace.json
  tests/baselines/reference/bundlerDirectoryModule(moduleresolution=nodenext).trace.json
  tests/baselines/reference/nodeModulesExportsBlocksTypesVersions(module=nodenext).trace.json
  tests/baselines/reference/nodeModulesPackageImports(module=nodenext).trace.json
  tests/baselines/reference/nodeModulesPackagePatternExportsTrailers(module=nodenext).trace.json
  tests/baselines/reference/reactJsxReactResolvedNodeNext.trace.json
  tests/baselines/reference/reactJsxReactResolvedNodeNextEsm.trace.json
Labels: Author: Team, For Uncommitted Bug

#57391 fix(57386): Invalid use of 'eval' when defining a namespaced eval function
  src/compiler/binder.ts
  tests/baselines/reference/evalOrArgumentsInDeclarationFunctions.symbols
  tests/baselines/reference/evalOrArgumentsInDeclarationFunctions.types
  tests/cases/compiler/evalOrArgumentsInDeclarationFunctions.ts
Labels: For Backlog Bug

#57409 Refactor workflows for new typescript-bot triggers
  .github/workflows/create-cherry-pick-pr.yml
  .github/workflows/new-release-branch.yaml
  .github/workflows/nightly.yaml
  .github/workflows/set-version.yaml
  .github/workflows/sync-branch.yaml
  .github/workflows/twoslash-repros.yaml
Labels: Author: Team, For Uncommitted Bug

#57602 Fix `instanceof` use with `Symbol.hasInstance` in conjunction with union/intersection
  src/compiler/checker.ts
  tests/baselines/reference/instanceofOperatorWithRHSHasSymbolHasInstance.js
  tests/baselines/reference/instanceofOperatorWithRHSHasSymbolHasInstance.symbols
  tests/baselines/reference/instanceofOperatorWithRHSHasSymbolHasInstance.types
  tests/cases/conformance/expressions/binaryOperators/instanceofOperator/instanceofOperatorWithRHSHasSymbolHasInstance.ts
Labels: Author: Team, For Milestone Bug

#57611 Fix copy paste error in new workflows
  .github/workflows/new-release-branch.yaml
  .github/workflows/set-version.yaml
  .github/workflows/sync-branch.yaml
Labels: Author: Team, For Uncommitted Bug

#57604 fix(57590): [Formatting] Remove spaces between `...` and type name in tuple spread
  src/services/formatting/rules.ts
  tests/cases/fourslash/formatRemoveSpaceBetweenDotDotDotAndTypeName.ts
Labels: For Backlog Bug

#57361 Deduplicate protocol.ts content
  scripts/dtsBundler.mjs
  src/compiler/types.ts
  src/server/protocol.ts
  src/services/types.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/tsserver/cachingFileSystemInformation/loads-missing-files-from-disk.js
  tests/baselines/reference/tsserver/cachingFileSystemInformation/works-using-legacy-resolution-logic.js
  tests/baselines/reference/tsserver/dynamicFiles/dynamic-file-without-external-project.js
  tests/baselines/reference/tsserver/inferredProjects/Setting-compiler-options-for-inferred-projects-when-there-are-no-open-files-should-not-schedule-any-refresh.js
  tests/baselines/reference/tsserver/inferredProjects/inferred-projects-per-project-root-with-case-insensitive-system.js
  tests/baselines/reference/tsserver/inferredProjects/inferred-projects-per-project-root-with-case-sensitive-system.js
  tests/baselines/reference/tsserver/inferredProjects/inferred-projects-per-project-root.js
  tests/baselines/reference/tsserver/inferredProjects/project-settings-for-inferred-projects.js
  tests/baselines/reference/tsserver/maxNodeModuleJsDepth/should-be-set-to-2-if-the-project-has-js-root-files.js
  tests/baselines/reference/tsserver/projectErrors/for-external-project.js
  tests/baselines/reference/tsserver/projectErrors/for-inferred-project.js
  tests/baselines/reference/tsserver/projects/syntax-tree-cache-handles-changes-in-project-settings.js
  tests/baselines/reference/tsserver/typingsInstaller/projectRootPath-is-provided-for-inferred-project.js
Labels: Author: Team, For Uncommitted Bug

#57133 "Annotate" exported object to fix named / namespace imports of our API in Node ESM
  Herebyfile.mjs
  scripts/checkModuleFormat.mjs
  src/compiler/core.ts
  src/typescript/typescript.ts
Labels: Author: Team, For Milestone Bug

#57549 Add optionality to mapped type indexed access substitutions
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypeIndexedAccessConstraint.errors.txt
  tests/baselines/reference/mappedTypeIndexedAccessConstraint.symbols
  tests/baselines/reference/mappedTypeIndexedAccessConstraint.types
  tests/cases/compiler/mappedTypeIndexedAccessConstraint.ts
Labels: Author: Team, For Uncommitted Bug

#57642 Add a test case related to spreading objects
  tests/baselines/reference/spreadObjectNoCircular1.symbols
  tests/baselines/reference/spreadObjectNoCircular1.types
  tests/cases/compiler/spreadObjectNoCircular1.ts
Labels: For Uncommitted Bug

#57641 Ensure correct script kind and text when using cached sourceFile from scriptInfo
  src/harness/incrementalUtils.ts
  src/services/documentRegistry.ts
  src/testRunner/unittests/tsserver/plugins.ts
  tests/baselines/reference/tsserver/plugins/when-scriptKind-changes-for-the-external-file.js
Labels: Author: Team, For Uncommitted Bug

#57664 Update typescript dep to v5.4.2, other dependencies
  package-lock.json
  package.json
  src/compiler/commandLineParser.ts
Labels: Author: Team, For Uncommitted Bug

#57696 Update 'pack this' result script to update new status comment
  scripts/post-vsts-artifact-comment.mjs
Labels: Author: Team, For Uncommitted Bug

#57698 Fix typo in artifact script
  scripts/post-vsts-artifact-comment.mjs
Labels: Author: Team, For Uncommitted Bug

#57447 Remove `missingType` when inferring from properties in EOPT
  src/compiler/checker.ts
  tests/baselines/reference/inferenceExactOptionalProperties1.symbols
  tests/baselines/reference/inferenceExactOptionalProperties1.types
  tests/baselines/reference/inferenceExactOptionalProperties2.errors.txt
  tests/baselines/reference/inferenceExactOptionalProperties2.symbols
  tests/baselines/reference/inferenceExactOptionalProperties2.types
  tests/cases/compiler/inferenceExactOptionalProperties1.ts
  tests/cases/compiler/inferenceExactOptionalProperties2.ts
Labels: For Uncommitted Bug

#57575 Error on types named "undefined"
  src/compiler/checker.ts
  tests/baselines/reference/typeNamedUndefined1.errors.txt
  tests/baselines/reference/typeNamedUndefined1.js
  tests/baselines/reference/typeNamedUndefined1.symbols
  tests/baselines/reference/typeNamedUndefined1.types
  tests/baselines/reference/typeNamedUndefined2.errors.txt
  tests/baselines/reference/typeNamedUndefined2.js
  tests/baselines/reference/typeNamedUndefined2.symbols
  tests/baselines/reference/typeNamedUndefined2.types
  tests/baselines/reference/undefinedTypeAssignment1.errors.txt
  tests/baselines/reference/undefinedTypeAssignment4.errors.txt
  tests/cases/compiler/typeNamedUndefined1.ts
  tests/cases/compiler/typeNamedUndefined2.ts
Labels: Breaking Change, Author: Team, For Backlog Bug

#57724 Fix nullability intersections in CFA and relations
  src/compiler/checker.ts
  tests/baselines/reference/indexedAccessAndNullableNarrowing.symbols
  tests/baselines/reference/indexedAccessAndNullableNarrowing.types
  tests/cases/compiler/indexedAccessAndNullableNarrowing.ts
Labels: Author: Team, For Milestone Bug

#57666 Report error when referencing class name from decorator
  src/compiler/checker.ts
  tests/baselines/reference/decoratorReferences.js
  tests/baselines/reference/decoratorReferences.symbols
  tests/baselines/reference/decoratorReferences.types
  tests/baselines/reference/useBeforeDeclaration_classDecorators.1.errors.txt
  tests/baselines/reference/useBeforeDeclaration_classDecorators.2.errors.txt
  tests/cases/compiler/decoratorReferences.ts
  tests/cases/compiler/useBeforeDeclaration_classDecorators.1.ts
  tests/cases/compiler/useBeforeDeclaration_classDecorators.2.ts
Labels: Author: Team, For Milestone Bug

#57670 Track minimum language version for various language features
  src/compiler/checker.ts
  src/compiler/commandLineParser.ts
  src/compiler/transformers/esnext.ts
  src/compiler/types.ts
  tests/baselines/reference/awaitUsingDeclarationsWithImportHelpers.js
  tests/baselines/reference/usingDeclarationsWithImportHelpers.js
  tests/cases/conformance/statements/VariableStatements/usingDeclarations/awaitUsingDeclarationsWithImportHelpers.ts
  tests/cases/conformance/statements/VariableStatements/usingDeclarations/usingDeclarationsWithImportHelpers.ts
Labels: Author: Team, For Milestone Bug

#57220 Fix emit for `export { default } from ...` when both `importHelpers` and `esModuleInterop` are enabled
  src/compiler/transformers/utilities.ts
  tests/baselines/reference/importHelpersNoEmitHelpersExportDefault.js
  tests/baselines/reference/nodeModulesAllowJsImportHelpersCollisions3(module=node16).js
  tests/baselines/reference/nodeModulesAllowJsImportHelpersCollisions3(module=nodenext).js
  tests/baselines/reference/nodeModulesImportHelpersCollisions3(module=node16).js
  tests/baselines/reference/nodeModulesImportHelpersCollisions3(module=nodenext).js
  tests/cases/compiler/importHelpersNoEmitHelpersExportDefault.ts
Labels: Author: Team, For Milestone Bug

#57728 Fix failing tests after merging 57220
  tests/cases/conformance/node/allowJs/nodeModulesAllowJsImportHelpersCollisions3.ts
  tests/cases/conformance/node/nodeModulesImportHelpersCollisions3.ts
Labels: Author: Team, For Uncommitted Bug

#57580 Fixed an out-of-order quick info issue with contextual rest parameter
  src/compiler/checker.ts
  src/compiler/utilities.ts
  tests/baselines/reference/completionDetailsOfContextSensitiveParameterNoCrash.baseline
Labels: For Uncommitted Bug

#57746 Revert "Defer processing of nested generic calls that return construc…
  src/compiler/checker.ts
  tests/baselines/reference/inferenceGenericNestedCallReturningConstructor.symbols
  tests/baselines/reference/inferenceGenericNestedCallReturningConstructor.types
  tests/cases/compiler/inferenceGenericNestedCallReturningConstructor.ts
Labels: Author: Team, For Uncommitted Bug

#57745 Use alphanumeric sorting for completions
  src/compiler/core.ts
  tests/baselines/reference/completionNoParentLocation.baseline
  tests/baselines/reference/completionsCommentsClass.baseline
  tests/baselines/reference/completionsCommentsClassMembers.baseline
  tests/baselines/reference/completionsCommentsCommentParsing.baseline
  tests/baselines/reference/completionsCommentsFunctionDeclaration.baseline
  tests/baselines/reference/completionsCommentsFunctionExpression.baseline
  tests/baselines/reference/completionsImportWithKeyword.baseline
  tests/baselines/reference/completionsImport_asKeyword.baseline
  tests/baselines/reference/completionsImport_satisfiesKeyword.baseline
  tests/baselines/reference/exhaustiveCaseCompletions9.baseline
  tests/baselines/reference/tsserver/completionsIncomplete/ambient-module-specifier-resolutions-do-not-count-against-the-resolution-limit.js
  tests/baselines/reference/tsserver/completionsIncomplete/resolves-more-when-available-from-module-specifier-cache-(1).js
  tests/baselines/reference/tsserver/completionsIncomplete/resolves-more-when-available-from-module-specifier-cache-(2).js
  tests/baselines/reference/tsserver/completionsIncomplete/works-for-transient-symbols-between-requests.js
  tests/baselines/reference/tsserver/completionsIncomplete/works-with-PackageJsonAutoImportProvider.js
  tests/baselines/reference/tsserver/completionsIncomplete/works.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportFileExcludePatterns1.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportFileExcludePatterns2.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportFileExcludePatterns_networkPaths.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportFileExcludePatterns_symlinks.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportFileExcludePatterns_symlinks2.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportFileExcludePatterns_windowsPaths.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportProvider6.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportProvider7.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportProvider8.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportProvider_exportMap1.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportProvider_exportMap2.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportProvider_exportMap3.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportProvider_exportMap4.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportProvider_exportMap5.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportProvider_exportMap6.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportProvider_exportMap7.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportProvider_exportMap8.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportProvider_exportMap9.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportProvider_globalTypingsCache.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportProvider_namespaceSameNameAsIntrinsic.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportProvider_wildcardExports1.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportProvider_wildcardExports2.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportProvider_wildcardExports3.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportReExportFromAmbientModule.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportSymlinkedJsPackages.js
  tests/baselines/reference/tsserver/fourslashServer/completionEntryDetailAcrossFiles01.js
  tests/baselines/reference/tsserver/fourslashServer/completionEntryDetailAcrossFiles02.js
  tests/baselines/reference/tsserver/fourslashServer/completionsImport_addToNamedWithDifferentCacheValue.js
  tests/baselines/reference/tsserver/fourslashServer/completionsImport_computedSymbolName.js
  tests/baselines/reference/tsserver/fourslashServer/completionsImport_jsModuleExportsAssignment.js
  tests/baselines/reference/tsserver/fourslashServer/completionsImport_mergedReExport.js
  tests/baselines/reference/tsserver/fourslashServer/completionsImport_sortingModuleSpecifiers.js
  tests/baselines/reference/tsserver/fourslashServer/importSuggestionsCache_ambient.js
  tests/baselines/reference/tsserver/fourslashServer/importSuggestionsCache_coreNodeModules.js
  tests/baselines/reference/tsserver/fourslashServer/importSuggestionsCache_exportUndefined.js
  tests/baselines/reference/tsserver/fourslashServer/importSuggestionsCache_invalidPackageJson.js
  tests/baselines/reference/tsserver/fourslashServer/importSuggestionsCache_moduleAugmentation.js
Labels: Author: Team, For Uncommitted Bug

#57494 fix(57445): No inlay hints for property declaration types inferred from constructor
  src/services/inlayHints.ts
  tests/baselines/reference/inlayHintsPropertyDeclarations.baseline
  tests/cases/fourslash/inlayHintsPropertyDeclarations.ts
Labels: For Backlog Bug

#57291 feat(57240): Unimplemented abstract methods result in verbose, repetitive message
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/services/codefixes/fixClassDoesntImplementInheritedAbstractMember.ts
  tests/baselines/reference/abstractPropertyNegative.errors.txt
  tests/baselines/reference/classAbstractDeclarations.d.errors.txt
  tests/baselines/reference/classAbstractExtends.errors.txt
  tests/baselines/reference/classAbstractGeneric.errors.txt
  tests/baselines/reference/classAbstractInheritance.errors.txt
  tests/baselines/reference/classAbstractInheritance.symbols
  tests/baselines/reference/classAbstractInheritance1.errors.txt
  tests/baselines/reference/classAbstractInheritance1.js
  tests/baselines/reference/classAbstractInheritance1.symbols
  tests/baselines/reference/classAbstractInheritance1.types
  tests/baselines/reference/classAbstractInheritance2.errors.txt
  tests/baselines/reference/classAbstractInheritance2.js
  tests/baselines/reference/classAbstractInheritance2.symbols
  tests/baselines/reference/classAbstractInheritance2.types
  tests/baselines/reference/classAbstractInstantiations2.errors.txt
  tests/baselines/reference/classAbstractOverrideWithAbstract.errors.txt
  tests/baselines/reference/classAbstractUsingAbstractMethods2.errors.txt
  tests/baselines/reference/classExpressionExtendingAbstractClass.errors.txt
  tests/baselines/reference/mixinAbstractClasses.2.errors.txt
  tests/cases/conformance/classes/classDeclarations/classAbstractKeyword/classAbstractInheritance1.ts
  tests/cases/conformance/classes/classDeclarations/classAbstractKeyword/classAbstractInheritance2.ts
Labels: For Backlog Bug

#57749 Report grammar errors for invalid decorator grammar
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/services/_namespaces/ts.codefix.ts
  src/services/codefixes/wrapDecoratorInParentheses.ts
  src/testRunner/compilerRunner.ts
  tests/baselines/reference/decoratorOnClassMethod11.errors.txt
  tests/baselines/reference/decoratorOnClassMethod11.js
  tests/baselines/reference/decoratorOnClassMethod11.symbols
  tests/baselines/reference/decoratorOnClassMethod11.types
  tests/baselines/reference/decoratorOnClassMethod12.errors.txt
  tests/baselines/reference/decoratorOnClassMethod12.js
  tests/baselines/reference/decoratorOnClassMethod12.symbols
  tests/baselines/reference/decoratorOnClassMethod12.types
  tests/baselines/reference/esDecorators-decoratorExpression.1(experimentaldecorators=false).errors.txt
  tests/baselines/reference/esDecorators-decoratorExpression.1(experimentaldecorators=false).js
  tests/baselines/reference/esDecorators-decoratorExpression.1(experimentaldecorators=true).errors.txt
  tests/baselines/reference/esDecorators-decoratorExpression.1(experimentaldecorators=true).js
  tests/baselines/reference/esDecorators-decoratorExpression.2(experimentaldecorators=false).js
  tests/baselines/reference/esDecorators-decoratorExpression.2(experimentaldecorators=true).js
  tests/baselines/reference/esDecorators-decoratorExpression.3(experimentaldecorators=false).errors.txt
  tests/baselines/reference/esDecorators-decoratorExpression.3(experimentaldecorators=false).js
  tests/baselines/reference/esDecorators-decoratorExpression.3(experimentaldecorators=true).errors.txt
  tests/baselines/reference/esDecorators-decoratorExpression.3(experimentaldecorators=true).js
  tests/baselines/reference/esDecorators-preservesThis.js
  tests/baselines/reference/esDecorators-preservesThis.symbols
  tests/baselines/reference/esDecorators-preservesThis.types
  tests/cases/conformance/decorators/class/method/decoratorOnClassMethod11.ts
  tests/cases/conformance/decorators/class/method/decoratorOnClassMethod12.ts
  tests/cases/conformance/esDecorators/esDecorators-decoratorExpression.1.ts
  tests/cases/conformance/esDecorators/esDecorators-decoratorExpression.2.ts
  tests/cases/conformance/esDecorators/esDecorators-decoratorExpression.3.ts
  tests/cases/conformance/esDecorators/esDecorators-preservesThis.ts
  tests/cases/fourslash/codeFixWrapDecoratorInParentheses01.ts
  tests/cases/fourslash/codeFixWrapDecoratorInParentheses_all.ts
Labels: Author: Team, For Milestone Bug

#52350 Run tests on all OSs
  .github/workflows/ci.yml
Labels: Author: Team, For Uncommitted Bug

#57686 Ensure enum members syntactically determinable to be strings do not get reverse mappings
  src/compiler/transformers/ts.ts
  src/compiler/utilities.ts
  src/testRunner/unittests/services/transpile.ts
  tests/baselines/reference/computedEnumMemberSyntacticallyString(isolatedmodules=false).errors.txt
  tests/baselines/reference/computedEnumMemberSyntacticallyString(isolatedmodules=false).js
  tests/baselines/reference/computedEnumMemberSyntacticallyString(isolatedmodules=true).errors.txt
  tests/baselines/reference/computedEnumMemberSyntacticallyString(isolatedmodules=true).js
  tests/baselines/reference/computedEnumMemberSyntacticallyString2(isolatedmodules=false).js
  tests/baselines/reference/computedEnumMemberSyntacticallyString2(isolatedmodules=true).js
  tests/baselines/reference/transpile/Syntactically string but non-evaluatable enum members do not get reverse mapping.js
  tests/baselines/reference/transpile/Syntactically string but non-evaluatable enum members do not get reverse mapping.oldTranspile.js
  tests/cases/compiler/computedEnumMemberSyntacticallyString.ts
  tests/cases/compiler/computedEnumMemberSyntacticallyString2.ts
Labels: Author: Team, For Uncommitted Bug

#57751 Exclude generic string-like types from intersection reduction
  src/compiler/checker.ts
  tests/baselines/reference/intersectionReductionGenericStringLikeType.symbols
  tests/baselines/reference/intersectionReductionGenericStringLikeType.types
  tests/cases/compiler/intersectionReductionGenericStringLikeType.ts
Labels: Author: Team, For Uncommitted Bug

#55371 Reduce template literal types with a single placeholder and no extra texts
  src/compiler/checker.ts
  tests/baselines/reference/numericStringLiteralTypes.types
  tests/baselines/reference/recursiveConditionalCrash3.types
  tests/baselines/reference/templateLiteralIntersection.types
  tests/baselines/reference/templateLiteralIntersection3.types
  tests/baselines/reference/templateLiteralTypes3.types
  tests/baselines/reference/templateLiteralTypes5.symbols
  tests/baselines/reference/templateLiteralTypes5.types
  tests/baselines/reference/templateLiteralTypes6.symbols
  tests/baselines/reference/templateLiteralTypes6.types
  tests/cases/conformance/types/literal/templateLiteralTypes5.ts
  tests/cases/conformance/types/literal/templateLiteralTypes6.ts
Labels: For Backlog Bug

#57465 Infer type predicates from function bodies using control flow analysis
  src/compiler/binder.ts
  src/compiler/checker.ts
  tests/baselines/reference/circularConstructorWithReturn.js
  tests/baselines/reference/circularConstructorWithReturn.symbols
  tests/baselines/reference/circularConstructorWithReturn.types
  tests/baselines/reference/findLast(target=esnext).types
  tests/baselines/reference/importHelpersES6.types
  tests/baselines/reference/inKeywordAndUnknown.types
  tests/baselines/reference/inferTypePredicates.errors.txt
  tests/baselines/reference/inferTypePredicates.js
  tests/baselines/reference/inferTypePredicates.symbols
  tests/baselines/reference/inferTypePredicates.types
  tests/baselines/reference/javascriptThisAssignmentInStaticBlock.errors.txt
  tests/baselines/reference/javascriptThisAssignmentInStaticBlock.types
  tests/baselines/reference/narrowByInstanceof.types
  tests/cases/compiler/circularConstructorWithReturn.ts
  tests/cases/compiler/inferTypePredicates.ts
  tests/cases/fourslash/thisPredicateFunctionQuickInfo.ts
Labels: For Uncommitted Bug

#57750 Revert "Allow (non-assert) type predicates to narrow by discriminant"
  src/compiler/checker.ts
  src/compiler/commandLineParser.ts
  tests/baselines/reference/discriminantNarrowingCouldBeCircular.js
  tests/baselines/reference/discriminantNarrowingCouldBeCircular.symbols
  tests/baselines/reference/discriminantNarrowingCouldBeCircular.types
  tests/baselines/reference/typePredicatesCanNarrowByDiscriminant.symbols
  tests/baselines/reference/typePredicatesCanNarrowByDiscriminant.types
  tests/cases/compiler/discriminantNarrowingCouldBeCircular.ts
Labels: Author: Team, For Milestone Bug

#55326 Make tsserver and typingsInstaller thin wrappers around public API
  Herebyfile.mjs
  src/tsserver/_namespaces/ts.server.ts
  src/tsserver/_namespaces/ts.ts
  src/tsserver/common.ts
  src/tsserver/nodeServer.ts
  src/tsserver/server.ts
  src/tsserver/tsconfig.json
  src/typingsInstaller/_namespaces/ts.server.ts
  src/typingsInstaller/_namespaces/ts.server.typingsInstaller.ts
  src/typingsInstaller/_namespaces/ts.ts
  src/typingsInstaller/nodeTypingsInstaller.ts
  src/typingsInstaller/tsconfig.json
Labels: Author: Team, For Uncommitted Bug

#57782 Require exactly 'true' for truthy reference directive prop
  src/compiler/parser.ts
Labels: Author: Team, For Uncommitted Bug

#57665 Remove nonNullUnknownType
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug

#57798 Fix baselines after baseline change in main
  tests/baselines/reference/jsxElementTypeLiteralWithGeneric.types
  tests/baselines/reference/jsxIssuesErrorWhenTagExpectsTooManyArguments.types
Labels: Author: Team, For Uncommitted Bug

#57267 Change detection to detection by diff in organizeImports
  src/compiler/core.ts
  src/compiler/types.ts
  src/services/codefixes/importFixes.ts
  src/services/organizeImports.ts
  src/services/utilities.ts
  src/testRunner/unittests/services/organizeImports.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/organizeImports/detection1.ts
  tests/baselines/reference/organizeImports/detection10.ts
  tests/baselines/reference/organizeImports/detection2.ts
  tests/baselines/reference/organizeImports/detection3.ts
  tests/baselines/reference/organizeImports/detection4.ts
  tests/baselines/reference/organizeImports/detection5.ts
  tests/baselines/reference/organizeImports/detection6.ts
  tests/baselines/reference/organizeImports/detection7.ts
  tests/baselines/reference/organizeImports/detection8.ts
  tests/baselines/reference/organizeImports/detection9.ts
  tests/cases/fourslash/autoImportSortCaseSensitivity1.ts
  tests/cases/fourslash/autoImportTypeImport4.ts
  tests/cases/fourslash/autoImportTypeImport5.ts
  tests/cases/fourslash/codeFixInferFromUsageContextualImport1.ts
  tests/cases/fourslash/importNameCodeFix_all_promoteType.ts
  tests/cases/fourslash/importNameCodeFix_importType7.ts
  tests/cases/fourslash/organizeImports22.ts
  tests/cases/fourslash/organizeImports23.ts
  tests/cases/fourslash/organizeImportsType10.ts
  tests/cases/fourslash/organizeImportsType11.ts
  tests/cases/fourslash/organizeImportsType5.ts
  tests/cases/fourslash/organizeImportsType8.ts
  tests/cases/fourslash/organizeImportsType9.ts
Labels: Author: Team, For Uncommitted Bug

#57799 Use noTypesAndSymbols for API tests
  src/testRunner/compilerRunner.ts
  tests/baselines/reference/APILibCheck.symbols
  tests/baselines/reference/APILibCheck.types
  tests/cases/compiler/APILibCheck.ts
  tests/cases/compiler/APISample_Watch.ts
  tests/cases/compiler/APISample_WatchWithDefaults.ts
  tests/cases/compiler/APISample_WatchWithOwnWatchHost.ts
  tests/cases/compiler/APISample_compile.ts
  tests/cases/compiler/APISample_jsdoc.ts
  tests/cases/compiler/APISample_linter.ts
  tests/cases/compiler/APISample_parseConfig.ts
  tests/cases/compiler/APISample_transform.ts
  tests/cases/compiler/APISample_watcher.ts
Labels: Author: Team, For Uncommitted Bug

#57801 Distribute mapped types over array/tuple intersections
  src/compiler/checker.ts
  tests/baselines/reference/mappedArrayTupleIntersections.symbols
  tests/baselines/reference/mappedArrayTupleIntersections.types
  tests/cases/compiler/mappedArrayTupleIntersections.ts
Labels: Author: Team, For Uncommitted Bug

#57835 Add workflow to update LKG on release branches
  .github/workflows/lkg.yml
Labels: Author: Team, For Uncommitted Bug

#57808 Fixed inference between type placeholders with non-string constraints in template literal types
  src/compiler/checker.ts
  tests/baselines/reference/templateLiteralTypes7.errors.txt
  tests/baselines/reference/templateLiteralTypes7.symbols
  tests/baselines/reference/templateLiteralTypes7.types
  tests/cases/conformance/types/literal/templateLiteralTypes7.ts
Labels: For Uncommitted Bug

#57608 Adopt code action ranges for refactorings
  src/server/session.ts
  src/services/refactors/extractSymbol.ts
  src/services/refactors/extractType.ts
  src/services/refactors/moveToFile.ts
  src/services/refactors/moveToNewFile.ts
  src/services/types.ts
  src/testRunner/unittests/tsserver/getApplicableRefactors.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/tsserver/fourslashServer/fixExtractToInnerFunctionDuplicaton.js
  tests/baselines/reference/tsserver/fourslashServer/moveToFile_emptyTargetFile.js
  tests/baselines/reference/tsserver/getApplicableRefactors/returns-the-affected-range-of-text-for-'move-to-file'-and-'move-to-new-file'-refactors.js
  tests/baselines/reference/tsserver/getApplicableRefactors/returns-the-affected-range-of-text-for-extract-symbol-refactor.js
  tests/baselines/reference/tsserver/getApplicableRefactors/returns-the-affected-range-of-text-for-extract-type-refactor.js
Labels: Author: Team, For Milestone Bug

#57111 Add lib declaration for RegExp#unicodeSets
  src/compiler/commandLineParser.ts
  src/lib/es2022.regexp.d.ts
  src/lib/esnext.d.ts
  src/lib/esnext.regexp.d.ts
  src/lib/libs.json
  tests/baselines/reference/bundlerDirectoryModule(moduleresolution=bundler).trace.json
  tests/baselines/reference/bundlerDirectoryModule(moduleresolution=nodenext).trace.json
  tests/baselines/reference/config/commandLineParsing/parseCommandLine/Parse --lib option with extra comma.js
  tests/baselines/reference/config/commandLineParsing/parseCommandLine/Parse --lib option with trailing white-space.js
  tests/baselines/reference/config/commandLineParsing/parseCommandLine/Parse invalid option of library flags.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert empty string option of libs array to compiler-options with json api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert empty string option of libs array to compiler-options with jsonSourceFile api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert empty string option of libs to compiler-options with json api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert empty string option of libs to compiler-options with jsonSourceFile api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert incorrect option of libs to compiler-options with json api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert incorrect option of libs to compiler-options with jsonSourceFile api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert trailing-whitespace string option of libs to compiler-options with json api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert trailing-whitespace string option of libs to compiler-options with jsonSourceFile api.js
  tests/baselines/reference/contextualOverloadListFromUnionWithPrimitiveNoImplicitAny.symbols
  tests/baselines/reference/modulePreserve2.trace.json
  tests/baselines/reference/modulePreserve3.trace.json
  tests/baselines/reference/nodeModulesExportsBlocksTypesVersions(module=nodenext).trace.json
  tests/baselines/reference/nodeModulesPackageImports(module=nodenext).trace.json
  tests/baselines/reference/nodeModulesPackagePatternExportsTrailers(module=nodenext).trace.json
  tests/baselines/reference/reactJsxReactResolvedNodeNext.trace.json
  tests/baselines/reference/reactJsxReactResolvedNodeNextEsm.trace.json
  tests/baselines/reference/truthinessCallExpressionCoercion2.types
  tests/baselines/reference/tsc/runWithoutArgs/does-not-add-color-when-NO_COLOR-is-set.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped-when-host-can't-provide-terminal-width.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
  tests/baselines/reference/tsserver/telemetry/does-not-expose-paths.js
  tests/baselines/reference/typesVersions.ambientModules.trace.json
  tests/baselines/reference/typesVersions.emptyTypes.trace.json
  tests/baselines/reference/typesVersions.justIndex.trace.json
  tests/baselines/reference/typesVersions.multiFile.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.ambient.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFile.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFileBackReferenceToSelf.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFileBackReferenceToUnmapped.trace.json
Labels: For Backlog Bug

#57748 add `Array.fromAsync` to `esnext`
  src/compiler/commandLineParser.ts
  src/compiler/utilities.ts
  src/lib/esnext.array.d.ts
  src/lib/esnext.d.ts
  src/lib/libs.json
  tests/baselines/reference/arrayFromAsync.js
  tests/baselines/reference/arrayFromAsync.symbols
  tests/baselines/reference/arrayFromAsync.types
  tests/baselines/reference/bundlerDirectoryModule(moduleresolution=bundler).trace.json
  tests/baselines/reference/bundlerDirectoryModule(moduleresolution=nodenext).trace.json
  tests/baselines/reference/modulePreserve2.trace.json
  tests/baselines/reference/modulePreserve3.trace.json
  tests/baselines/reference/nodeModulesExportsBlocksTypesVersions(module=nodenext).trace.json
  tests/baselines/reference/nodeModulesPackageImports(module=nodenext).trace.json
  tests/baselines/reference/nodeModulesPackagePatternExportsTrailers(module=nodenext).trace.json
  tests/baselines/reference/reactJsxReactResolvedNodeNext.trace.json
  tests/baselines/reference/reactJsxReactResolvedNodeNextEsm.trace.json
  tests/baselines/reference/tsc/runWithoutArgs/does-not-add-color-when-NO_COLOR-is-set.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped-when-host-can't-provide-terminal-width.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
  tests/baselines/reference/typesVersions.ambientModules.trace.json
  tests/baselines/reference/typesVersions.emptyTypes.trace.json
  tests/baselines/reference/typesVersions.justIndex.trace.json
  tests/baselines/reference/typesVersions.multiFile.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.ambient.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFile.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFileBackReferenceToSelf.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFileBackReferenceToUnmapped.trace.json
  tests/cases/compiler/arrayFromAsync.ts
Labels: Author: Team, For Milestone Bug

#57852 Print baseline diffs on test failures
  .github/workflows/ci.yml
Labels: Author: Team, For Uncommitted Bug

#57849 Revert PR 56087
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitUsingTypeAlias1.errors.txt
  tests/baselines/reference/declarationEmitUsingTypeAlias1.js
  tests/baselines/reference/unusedTypeParametersCheckedByNoUnusedParameters.types
  tests/baselines/reference/unusedTypeParametersNotCheckedByNoUnusedLocals.types
Labels: Author: Team, For Milestone Bug

#57850 release-5.4: Revert PR 56087
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitUsingTypeAlias1.errors.txt
  tests/baselines/reference/declarationEmitUsingTypeAlias1.js
Labels: Author: Team, For Uncommitted Bug

#57853 Revert PR 56161
  src/compiler/checker.ts
  tests/baselines/reference/enumWithInfinityProperty.errors.txt
  tests/baselines/reference/enumWithNaNProperty.errors.txt
  tests/baselines/reference/enumWithNegativeInfinityProperty.errors.txt
Labels: Author: Team, For Uncommitted Bug

#57739 Fixed referencing properties that are reserved keywords in `@link`
  src/compiler/parser.ts
  tests/baselines/reference/jsdocLinkTag8.symbols
  tests/baselines/reference/jsdocLinkTag8.types
  tests/cases/conformance/jsdoc/jsdocLinkTag8.ts
Labels: For Uncommitted Bug

#56736 isolatedModules errors for non-literal enum initializers
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/enumNoInitializerFollowsNonLiteralInitializer.errors.txt
  tests/baselines/reference/enumNoInitializerFollowsNonLiteralInitializer.js
  tests/baselines/reference/enumWithNonLiteralStringInitializer.errors.txt
  tests/baselines/reference/enumWithNonLiteralStringInitializer.js
  tests/baselines/reference/isolatedModulesGlobalNamespacesAndEnums.errors.txt
  tests/cases/compiler/enumNoInitializerFollowsNonLiteralInitializer.ts
  tests/cases/compiler/enumWithNonLiteralStringInitializer.ts
Labels: For Backlog Bug

#57839 fix54092: return replacement ranges for completions on unclosed strings
  src/services/utilities.ts
  tests/cases/fourslash/stringCompletionsUnterminated.ts
Labels: Author: Team, For Uncommitted Bug

#57530 fix(57451): Prevent self-imports when using the "Move to File" refactor
  src/services/refactors/moveToFile.ts
  tests/cases/fourslash/moveToFile_noSelfImports1.ts
  tests/cases/fourslash/moveToFile_noSelfImports2.ts
Labels: For Backlog Bug

#57829 Don't indirect through _namespaces in tsserver/typingsInstaller
  src/tsserver/_namespaces/ts.ts
  src/tsserver/common.ts
  src/tsserver/nodeServer.ts
  src/tsserver/server.ts
  src/typingsInstaller/_namespaces/ts.ts
  src/typingsInstaller/nodeTypingsInstaller.ts
Labels: Author: Team, For Uncommitted Bug

#57870 Update deps and fix new lints
  package-lock.json
  package.json
  src/compiler/commandLineParser.ts
  src/harness/client.ts
  src/server/session.ts
  src/services/organizeImports.ts
  src/testRunner/unittests/tsserver/externalProjects.ts
  src/testRunner/unittests/tsserver/navTo.ts
  src/testRunner/unittests/tsserver/projectReferences.ts
  src/testRunner/unittests/tsserver/skipLibCheck.ts
Labels: Author: Team, For Uncommitted Bug

#57869 Remove `getSuggestionForNonexistent*` from `TypeChecker`
  src/compiler/checker.ts
  src/compiler/types.ts
Labels: Author: Team, For Uncommitted Bug

#57867 Preserve resolution-mode as-written too
  src/compiler/emitter.ts
  tests/baselines/reference/nodeModulesTripleSlashReferenceModeDeclarationEmit5(module=node16).js
  tests/baselines/reference/nodeModulesTripleSlashReferenceModeDeclarationEmit5(module=nodenext).js
Labels: Author: Team, For Uncommitted Bug

#57871 Divide-and-conquer strategy for intersections of unions
  src/compiler/checker.ts
  tests/baselines/reference/divideAndConquerIntersections.symbols
  tests/baselines/reference/divideAndConquerIntersections.types
  tests/baselines/reference/normalizedIntersectionTooComplex.types
  tests/baselines/reference/styledComponentsInstantiaionLimitNotReached.types
  tests/baselines/reference/templateLiteralTypes1.types
  tests/cases/compiler/divideAndConquerIntersections.ts
Labels: Author: Team, For Uncommitted Bug

#57887 Lookup retained type nodes in the node builder using correct, specific SymbolFlags meaning
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitGlobalThisPreserved.types
  tests/baselines/reference/declarationEmitRetainedAnnotationRetainsImportInOutput.js
  tests/baselines/reference/declarationEmitRetainedAnnotationRetainsImportInOutput.symbols
  tests/baselines/reference/declarationEmitRetainedAnnotationRetainsImportInOutput.types
  tests/baselines/reference/intraExpressionInferences.types
  tests/baselines/reference/jsDeclarationsImportAliasExposedWithinNamespace.js
  tests/baselines/reference/reverseMappedUnionInference.types
  tests/cases/compiler/declarationEmitRetainedAnnotationRetainsImportInOutput.ts
Labels: Author: Team, For Milestone Bug

#57889 Properly add assignees and reviewers for cherry picked PRs
  .github/workflows/create-cherry-pick-pr.yml
Labels: Author: Team, For Uncommitted Bug

#57875 Use performance.now when possible, re-disable unconditional perf marking on all Node versions
  src/compiler/performance.ts
  src/compiler/performanceCore.ts
Labels: Author: Team, For Uncommitted Bug

#57916 Remove sys.bufferFrom, duplicate Buffer declarations, etc
  src/compiler/sys.ts
  src/harness/harnessUtils.ts
  src/harness/vfsUtil.ts
  src/tsserver/nodeServer.ts
Labels: Author: Team, For Uncommitted Bug

#57931 Fix incorrect use of "path" instead of "resolvedPath" when watching file's package json locations
  src/compiler/resolutionCache.ts
  src/testRunner/unittests/helpers/sampleProjectReferences.ts
  src/testRunner/unittests/tscWatch/projectsWithReferences.ts
  tests/baselines/reference/tscWatch/projectsWithReferences/on-sample-project-with-nodenext.js
Labels: Author: Team, For Uncommitted Bug

#57933 Limit decorator use-before-def check to ES decorators only
  src/compiler/checker.ts
  tests/baselines/reference/useBeforeDeclaration_classDecorators.2(experimentaldecorators=false).errors.txt
  tests/cases/compiler/useBeforeDeclaration_classDecorators.2.ts
Labels: Author: Team

#57917 Add extra tests for inference with any co-inference with a different contra-inference
  tests/baselines/reference/coAndContraVariantInferences6.errors.txt
  tests/baselines/reference/coAndContraVariantInferences6.symbols
  tests/baselines/reference/coAndContraVariantInferences6.types
  tests/cases/compiler/coAndContraVariantInferences6.ts
Labels: For Milestone Bug

#57938 Directories dont check modified time when sending "change" event
  src/compiler/sys.ts
  src/testRunner/unittests/helpers/virtualFileSystemWithWatch.ts
  src/testRunner/unittests/tscWatch/watchEnvironment.ts
  tests/baselines/reference/tscWatch/watchEnvironment/fsWatch/fsWatchWithTimestamp-false-useFsEventsOnParentDirectory.js
  tests/baselines/reference/tscWatch/watchEnvironment/fsWatch/fsWatchWithTimestamp-true-useFsEventsOnParentDirectory.js
Labels: Author: Team, For Uncommitted Bug

#57717 fix(57635): duplicate property name error when trying to overwrite early-bound prop with late-bound prop
  src/compiler/checker.ts
  tests/baselines/reference/dynamicNamesErrors.errors.txt
  tests/baselines/reference/dynamicNamesErrors.symbols
  tests/cases/fourslash/allowLateBoundSymbolsOverwriteEarlyBoundSymbols.ts
Labels: For Backlog Bug

#57847 Control flow analysis for element access with variable index
  src/compiler/checker.ts
  tests/baselines/reference/controlFlowComputedPropertyNames.symbols
  tests/baselines/reference/controlFlowComputedPropertyNames.types
  tests/baselines/reference/mappedTypeGenericIndexedAccess.types
  tests/baselines/reference/noUncheckedIndexedAccess.errors.txt
  tests/baselines/reference/noUncheckedIndexedAccess.types
  tests/cases/conformance/controlFlow/controlFlowComputedPropertyNames.ts
Labels: Author: Team, For Uncommitted Bug

#57403 Propagate outer type parameters of single signature types
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/genericCallWithinOwnBodyCastTypeParameterIdentity.js
  tests/baselines/reference/genericCallWithinOwnBodyCastTypeParameterIdentity.symbols
  tests/baselines/reference/genericCallWithinOwnBodyCastTypeParameterIdentity.types
  tests/baselines/reference/nestedGenericSpreadInference.js
  tests/baselines/reference/nestedGenericSpreadInference.symbols
  tests/baselines/reference/nestedGenericSpreadInference.types
  tests/cases/compiler/genericCallWithinOwnBodyCastTypeParameterIdentity.ts
  tests/cases/compiler/nestedGenericSpreadInference.ts
Labels: Author: Team, For Milestone Bug

#57962 Fix main baselines
  tests/baselines/reference/genericFunctionInference1.types
  tests/baselines/reference/nestedGenericSpreadInference.types
  tests/baselines/reference/promisePermutations.types
  tests/baselines/reference/promisePermutations2.types
  tests/baselines/reference/promisePermutations3.types
  tests/baselines/reference/promiseType.types
  tests/baselines/reference/propTypeValidatorInference.types
  tests/baselines/reference/recursiveConditionalTypes.types
Labels: Author: Team, For Uncommitted Bug

#57679 Add missing parameters from Array.toLocaleString on ES2015 libs
  src/lib/es2015.core.d.ts
  src/lib/es2020.bigint.d.ts
  tests/baselines/reference/arrayToLocaleStringES2015.js
  tests/baselines/reference/arrayToLocaleStringES2015.symbols
  tests/baselines/reference/arrayToLocaleStringES2015.types
  tests/baselines/reference/arrayToLocaleStringES2020.js
  tests/baselines/reference/arrayToLocaleStringES2020.symbols
  tests/baselines/reference/arrayToLocaleStringES2020.types
  tests/baselines/reference/arrayToLocaleStringES5.errors.txt
  tests/baselines/reference/arrayToLocaleStringES5.js
  tests/baselines/reference/arrayToLocaleStringES5.symbols
  tests/baselines/reference/arrayToLocaleStringES5.types
  tests/baselines/reference/bigintIndex.symbols
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2016Plus.symbols
  tests/baselines/reference/es2022SharedMemory.symbols
  tests/baselines/reference/findLast(target=es2022).symbols
  tests/baselines/reference/findLast(target=esnext).symbols
  tests/baselines/reference/indexAt(target=es2021).symbols
  tests/baselines/reference/indexAt(target=es2022).symbols
  tests/baselines/reference/indexAt(target=esnext).symbols
  tests/baselines/reference/jsxChildrenWrongType.types
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty.errors.txt
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty.types
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty2.js
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty2.types
  tests/baselines/reference/templateLiteralTypes4.types
  tests/baselines/reference/typedArrays-es6.symbols
  tests/baselines/reference/typedArrays.symbols
  tests/baselines/reference/typedArraysCrossAssignability01.symbols
  tests/baselines/reference/unionAndIntersectionInference3.types
  tests/baselines/reference/valueOfTypedArray.symbols
  tests/baselines/reference/verifyDefaultLib_webworker.types
  tests/cases/compiler/arrayToLocaleStringES2015.ts
  tests/cases/compiler/arrayToLocaleStringES2020.ts
  tests/cases/compiler/arrayToLocaleStringES5.ts
Labels: For Backlog Bug

#57964 Fix main baselines. Again.
  tests/baselines/reference/nestedGenericSpreadInference.types
Labels: Author: Team, For Uncommitted Bug

#57955 Refactor expression evaluator
  src/compiler/checker.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
Labels: For Uncommitted Bug

#57914 Allow cross-project references to const enums in isolatedModules when referenced project has preserveConstEnums
  src/compiler/checker.ts
  src/compiler/program.ts
  src/compiler/types.ts
  src/testRunner/unittests/tsc/projectReferences.ts
  src/testRunner/unittests/tsserver/projectReferences.ts
  tests/baselines/reference/tsc/projectReferences/referencing-ambient-const-enum-from-referenced-project-with-preserveConstEnums.js
  tests/baselines/reference/tsserver/projectReferences/referencing-const-enum-from-referenced-project-with-preserveConstEnums.js
Labels: Author: Team, For Milestone Bug

#57950 Watch events enhancements
  src/server/editorServices.ts
  src/server/protocol.ts
  src/testRunner/unittests/tsserver/events/watchEvents.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/tsserver/events/watchEvents/canUseWatchEvents-without-canUseEvents.js
  tests/baselines/reference/tsserver/events/watchEvents/canUseWatchEvents.js
Labels: Author: Team, For Uncommitted Bug

#57971 Dont fail on "create" event when watching package json files
  src/server/editorServices.ts
  src/testRunner/unittests/helpers/virtualFileSystemWithWatch.ts
  src/testRunner/unittests/tsserver/moduleResolution.ts
  tests/baselines/reference/tsserver/moduleResolution/package-json-file-is-edited.js
Labels: Author: Team, For Uncommitted Bug

#57778 fix type import check for default-import/re-export in js files
  src/services/completions.ts
  tests/cases/fourslash/jsFileImportNoTypes2.ts
Labels: For Backlog Bug

#57946 Improve optionality detection in mapped type indexed access substitutions
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypeIndexedAccessConstraint.errors.txt
  tests/baselines/reference/mappedTypeIndexedAccessConstraint.symbols
  tests/baselines/reference/mappedTypeIndexedAccessConstraint.types
  tests/cases/compiler/mappedTypeIndexedAccessConstraint.ts
Labels: Author: Team, For Milestone Bug

#57973 Compare package.json paths with correct sensitivity in getLocalModuleSpecifier
  src/compiler/moduleSpecifiers.ts
  src/testRunner/unittests/tsc/declarationEmit.ts
  tests/baselines/reference/tsc/declarationEmit/when-using-Windows-paths-and-uppercase-letters.js
Labels: Author: Team, For Milestone Bug

#57988 Ensure that we are checking if correct file with resolved path is present in the new program when removing the existing packageJson watching
  src/compiler/resolutionCache.ts
  src/testRunner/unittests/helpers/contents.ts
  src/testRunner/unittests/helpers/sampleProjectReferences.ts
  src/testRunner/unittests/helpers/transitiveReferences.ts
  src/testRunner/unittests/tscWatch/projectsWithReferences.ts
  tests/baselines/reference/tscWatch/projectsWithReferences/on-transitive-references-with-nodenext.js
Labels: Author: Team, For Uncommitted Bug

#57637 Fixed a regression related to determining argument index when spread elements are involved
  src/services/completions.ts
  src/services/signatureHelp.ts
  tests/baselines/reference/signatureHelpRestArgs1.baseline
  tests/baselines/reference/signatureHelpRestArgs2.baseline
  tests/baselines/reference/signatureHelpSkippedArgs1.baseline
  tests/cases/fourslash/signatureHelpRestArgs1.ts
  tests/cases/fourslash/signatureHelpRestArgs2.ts
  tests/cases/fourslash/signatureHelpSkippedArgs1.ts
Labels: For Backlog Bug

#57993 Remove getAllAccessorDeclarations from the EmitResolver
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/transformers/declarations.ts
  src/compiler/transformers/ts.ts
  src/compiler/transformers/typeSerializer.ts
  src/compiler/types.ts
Labels: Author: Team, For Uncommitted Bug

#57994 Remove some unneeded parameters from NodeBuilder APIs
  src/compiler/checker.ts
  src/compiler/transformers/declarations.ts
  src/compiler/types.ts
  tests/baselines/reference/jsDeclarationsFunctionClassesCjsExportAssignment.js
Labels: Author: Team, For Uncommitted Bug

#57998 Now that we have osFlavour some of the TestServerHostOptions can be removed
  src/testRunner/unittests/helpers/virtualFileSystemWithWatch.ts
  src/testRunner/unittests/tscWatch/watchEnvironment.ts
  src/testRunner/unittests/tsserver/watchEnvironment.ts
  tests/baselines/reference/tscWatch/watchEnvironment/fsWatch/fsWatchWithTimestamp-true-useFsEventsOnParentDirectory.js
  tests/baselines/reference/tscWatch/watchEnvironment/fsWatch/fsWatchWithTimestamp-true.js
  tests/baselines/reference/tscWatch/watchEnvironment/fsWatch/when-using-file-watching-thats-on-inode-when-rename-occurs-when-file-is-still-on-the-disk.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchDirectories/uses-non-recursive-dynamic-polling-when-renaming-file-in-subfolder.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchDirectories/uses-non-recursive-watchDirectory-when-renaming-file-in-subfolder.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchDirectories/uses-watchFile-when-renaming-file-in-subfolder.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchDirectories/when-there-are-symlinks-to-folders-in-recursive-folders.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchDirectories/with-non-synchronous-watch-directory-renaming-a-file.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchDirectories/with-non-synchronous-watch-directory-with-outDir-and-declaration-enabled.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchDirectories/with-non-synchronous-watch-directory.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchOptions/with-excludeDirectories-option-with-recursive-directory-watching-extendedDiagnostics.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchOptions/with-excludeDirectories-option-with-recursive-directory-watching.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchOptions/with-fallbackPolling-option.js
  tests/baselines/reference/tscWatch/watchEnvironment/watchOptions/with-watchDirectory-option.js
  tests/baselines/reference/tsserver/watchEnvironment/recursive-directory-does-not-watch-files-starting-with-dot-in-node_modules.js
  tests/baselines/reference/tsserver/watchEnvironment/uses-dynamic-polling-when-file-is-added-to-subfolder.js
  tests/baselines/reference/tsserver/watchEnvironment/uses-non-recursive-watchDirectory-when-file-is-added-to-subfolder.js
  tests/baselines/reference/tsserver/watchEnvironment/uses-watchFile-when-file-is-added-to-subfolder.js
  tests/baselines/reference/tsserver/watchEnvironment/with-fallbackPolling-option-as-host-configuration.js
  tests/baselines/reference/tsserver/watchEnvironment/with-fallbackPolling-option-in-configFile.js
  tests/baselines/reference/tsserver/watchEnvironment/with-watchDirectory-option-as-host-configuration.js
  tests/baselines/reference/tsserver/watchEnvironment/with-watchDirectory-option-in-configFile.js
Labels: Author: Team, For Uncommitted Bug

#58003 Update OpenSSF scorecard link to new page rather than raw API
  README.md
Labels: Author: Team, For Uncommitted Bug
