Repository microsoft/TypeScript, pull requests merged in 2024-02, with the labels that each got.

#57256 Consider dtsBundler.mjs mod time in `hereby dts`
  Herebyfile.mjs
Labels: Author: Team, For Uncommitted Bug

#57250 fix 57215 -- add support for import attributes to OrganizeImports
  src/services/organizeImports.ts
  tests/cases/fourslash/organizeImportsAttributes.ts
  tests/cases/fourslash/organizeImportsAttributes2.ts
  tests/cases/fourslash/organizeImportsAttributes3.ts
  tests/cases/fourslash/organizeImportsAttributes4.ts
Labels: Author: Team, For Milestone Bug

#57275 Add test for issue 54655
  tests/baselines/reference/declarationEmitArrowFunctionNoRenaming.js
  tests/baselines/reference/declarationEmitArrowFunctionNoRenaming.symbols
  tests/baselines/reference/declarationEmitArrowFunctionNoRenaming.types
  tests/cases/compiler/declarationEmitArrowFunctionNoRenaming.ts
Labels: Author: Team, For Milestone Bug

#56594 Always emit `Object` type in decorator metadata for import type
  src/compiler/checker.ts
  tests/baselines/reference/decoratorMetadataTypeOnlyImport.errors.txt
  tests/baselines/reference/decoratorMetadataTypeOnlyImport.js
  tests/baselines/reference/decoratorMetadataTypeOnlyImport.symbols
  tests/baselines/reference/decoratorMetadataTypeOnlyImport.types
  tests/cases/compiler/decoratorMetadataTypeOnlyImport.ts
Labels: For Milestone Bug

#57312 Fix path completions missing extensions for exports wildcards
  src/compiler/moduleSpecifiers.ts
  src/compiler/utilities.ts
  src/services/stringCompletions.ts
  tests/cases/fourslash/pathCompletionsPackageJsonExportsWildcard10.ts
  tests/cases/fourslash/pathCompletionsPackageJsonExportsWildcard11.ts
Labels: Author: Team, For Milestone Bug

#57327 fix(57326): 'resolves to a type-only declaration and must be imported using a type-only import' doesn't have a quick fix
  src/services/codefixes/convertToTypeOnlyImport.ts
  tests/cases/fourslash/codeFixConvertToTypeOnlyImport8.ts
Labels: For Backlog Bug

#57345 Fixed distributive conditional types with never intersections
  src/compiler/checker.ts
  tests/baselines/reference/distributiveConditionalTypeNeverIntersection1.symbols
  tests/baselines/reference/distributiveConditionalTypeNeverIntersection1.types
  tests/cases/compiler/distributiveConditionalTypeNeverIntersection1.ts
Labels: For Uncommitted Bug

#57369 Fix duplicated import suggestions
  src/services/stringCompletions.ts
  tests/cases/fourslash/completionForStringLiteralRelativeImport5.ts
Labels: For Uncommitted Bug

#57371 Fixed type parameter leak in union calls with mixed type parameter presence
  src/compiler/checker.ts
  tests/baselines/reference/unionCallMixedTypeParameterPresence.symbols
  tests/baselines/reference/unionCallMixedTypeParameterPresence.types
  tests/cases/compiler/unionCallMixedTypeParameterPresence.ts
Labels: For Milestone Bug

#57399 Fix scripts/errorCheck.mjs
  scripts/errorCheck.mjs
Labels: Author: Team, Housekeeping, For Uncommitted Bug

#57358 Allow (non-assert) type predicates to narrow by discriminant
  src/compiler/checker.ts
  tests/baselines/reference/typePredicatesCanNarrowByDiscriminant.js
  tests/baselines/reference/typePredicatesCanNarrowByDiscriminant.symbols
  tests/baselines/reference/typePredicatesCanNarrowByDiscriminant.types
  tests/cases/compiler/typePredicatesCanNarrowByDiscriminant.ts
Labels: Author: Team, For Milestone Bug

#57271 When attaching JSDoc diagnostics, make sure to only include diagnostics that actually belong with the JSDoc
  src/compiler/parser.ts
  tests/baselines/reference/errorIsolation.symbols
  tests/baselines/reference/errorIsolation.types
  tests/cases/conformance/jsdoc/errorIsolation.ts
Labels: For Uncommitted Bug

#57407 Set NODE_ENV to development and not testing in launch template
  .vscode/launch.template.json
Labels: Author: Team, For Uncommitted Bug

#57410 Update TypeScript-Twoslash-Repro-Action action version
  .github/workflows/twoslash-repros.yaml
Labels: Author: Team, For Uncommitted Bug

#57143 Add missing members to array of objects in quickfix
  src/services/codefixes/fixAddMissingMember.ts
  tests/cases/fourslash/codeFixAddMissingProperties30.ts
  tests/cases/fourslash/codeFixAddMissingProperties31.ts
Labels: For Uncommitted Bug

#57144 Preserve separators in numeric literals with target=ES2021+
  src/compiler/emitter.ts
  tests/baselines/reference/parser.numericSeparators.decimal(target=es2020).js
  tests/baselines/reference/parser.numericSeparators.decimal(target=es2020).symbols
  tests/baselines/reference/parser.numericSeparators.decimal(target=es2020).types
  tests/baselines/reference/parser.numericSeparators.decimal(target=es2021).js
  tests/baselines/reference/parser.numericSeparators.decimal(target=es2021).symbols
  tests/baselines/reference/parser.numericSeparators.decimal(target=es2021).types
  tests/baselines/reference/parser.numericSeparators.decimal(target=es5).js
  tests/baselines/reference/parser.numericSeparators.decimal(target=es5).symbols
  tests/baselines/reference/parser.numericSeparators.decimal(target=es5).types
  tests/cases/conformance/parser/ecmascript2021/numericSeparators/parser.numericSeparators.decimal.ts
Labels: For Uncommitted Bug

#57305 fix(57302): Cannot move symbols from tsx to ts files
  src/services/refactors/moveToFile.ts
  src/services/refactors/moveToNewFile.ts
  src/services/services.ts
  src/testRunner/unittests/tsserver/getMoveToRefactoringFileSuggestions.ts
  tests/baselines/reference/tsserver/getMoveToRefactoringFileSuggestions/should-show-js-files-when-moving-non-jsx-content-from-jsx-file.js
  tests/baselines/reference/tsserver/getMoveToRefactoringFileSuggestions/should-show-ts-files-when-moving-non-tsx-content-from-tsx-file.js
Labels: For Backlog Bug

#57116 Avoid creating rest elements with `errorType` when `any` is spread
  src/compiler/checker.ts
  tests/baselines/reference/argumentsSpreadRestIterables(target=es5).types
  tests/baselines/reference/mappedTypeOverArrayWithBareAnyRestCanBeUsedAsRestParam1.symbols
  tests/baselines/reference/mappedTypeOverArrayWithBareAnyRestCanBeUsedAsRestParam1.types
  tests/baselines/reference/mappedTypesGenericTuples2.symbols
  tests/baselines/reference/mappedTypesGenericTuples2.types
  tests/baselines/reference/variadicTuples1.errors.txt
  tests/baselines/reference/variadicTuples1.js
  tests/baselines/reference/variadicTuples1.symbols
  tests/baselines/reference/variadicTuples1.types
  tests/cases/compiler/mappedTypeOverArrayWithBareAnyRestCanBeUsedAsRestParam1.ts
  tests/cases/conformance/types/mapped/mappedTypesGenericTuples2.ts
  tests/cases/conformance/types/tuple/variadicTuples1.ts
Labels: For Uncommitted Bug

#57122 Improve apparent type of mapped types
  src/compiler/checker.ts
  tests/baselines/reference/assignmentToAnyArrayRestParameters.errors.txt
  tests/baselines/reference/assignmentToAnyArrayRestParameters.symbols
  tests/baselines/reference/assignmentToAnyArrayRestParameters.types
  tests/baselines/reference/homomorphicMappedTypeWithNonHomomorphicInstantiationSpreadable1.symbols
  tests/baselines/reference/homomorphicMappedTypeWithNonHomomorphicInstantiationSpreadable1.types
  tests/cases/compiler/assignmentToAnyArrayRestParameters.ts
  tests/cases/compiler/homomorphicMappedTypeWithNonHomomorphicInstantiationSpreadable1.ts
Labels: Author: Team, For Milestone Bug

#57266 Allow plugins to be loaded from package subpaths
  src/server/editorServices.ts
  src/testRunner/unittests/tsserver/plugins.ts
  tests/baselines/reference/tsserver/plugins/With-global-plugins.js
  tests/baselines/reference/tsserver/plugins/With-local-plugins.js
Labels: For Backlog Bug

#57473 Disable fail-fast in CI
  .github/workflows/ci.yml
Labels: Author: Team, For Uncommitted Bug

#57489 Fix current document position mappers
  src/harness/projectServiceStateLogger.ts
  tests/baselines/reference/tsserver/declarationFileMaps/does-not-jump-to-source-if-inlined-sources.js
  tests/baselines/reference/tsserver/declarationFileMaps/findAllReferences-target-does-not-exist.js
  tests/baselines/reference/tsserver/declarationFileMaps/findAllReferences.js
  tests/baselines/reference/tsserver/declarationFileMaps/findAllReferencesFull.js
  tests/baselines/reference/tsserver/declarationFileMaps/getDefinitionAndBoundSpan.js
  tests/baselines/reference/tsserver/declarationFileMaps/getEditsForFileRename.js
  tests/baselines/reference/tsserver/declarationFileMaps/goToDefinition-target-does-not-exist.js
  tests/baselines/reference/tsserver/declarationFileMaps/goToDefinition.js
  tests/baselines/reference/tsserver/declarationFileMaps/goToImplementation.js
  tests/baselines/reference/tsserver/declarationFileMaps/goToType.js
  tests/baselines/reference/tsserver/declarationFileMaps/navigateTo.js
  tests/baselines/reference/tsserver/declarationFileMaps/renameLocations-target-does-not-exist.js
  tests/baselines/reference/tsserver/declarationFileMaps/renameLocations.js
  tests/baselines/reference/tsserver/declarationFileMaps/renameLocationsFull.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependency/configHasNoReference/dependency-dts-created.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependency/configHasNoReference/dependency-dts-deleted.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependency/configHasNoReference/dependency-dtsMap-created.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependency/configHasNoReference/dependency-dtsMap-deleted.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependency/configHasNoReference/rename-locations.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependency/configWithReference/dependency-dts-created.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependency/configWithReference/dependency-dts-deleted.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependency/configWithReference/dependency-dtsMap-created.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependency/configWithReference/dependency-dtsMap-deleted.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependency/configWithReference/rename-locations.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependency/disabledSourceRef/dependency-dts-created.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependency/disabledSourceRef/dependency-dts-deleted.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependency/disabledSourceRef/dependency-dtsMap-created.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependency/disabledSourceRef/dependency-dtsMap-deleted.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependency/disabledSourceRef/rename-locations.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependencyAndUsage/configHasNoReference/dependency-dts-created.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependencyAndUsage/configHasNoReference/dependency-dts-deleted.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependencyAndUsage/configHasNoReference/dependency-dtsMap-created.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependencyAndUsage/configHasNoReference/dependency-dtsMap-deleted.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependencyAndUsage/configHasNoReference/goToDef-and-rename-locations.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependencyAndUsage/configWithReference/dependency-dts-created.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependencyAndUsage/configWithReference/dependency-dts-deleted.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependencyAndUsage/configWithReference/dependency-dtsMap-created.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependencyAndUsage/configWithReference/dependency-dtsMap-deleted.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependencyAndUsage/configWithReference/goToDef-and-rename-locations.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependencyAndUsage/disabledSourceRef/dependency-dts-created.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependencyAndUsage/disabledSourceRef/dependency-dts-deleted.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependencyAndUsage/disabledSourceRef/dependency-dtsMap-created.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependencyAndUsage/disabledSourceRef/dependency-dtsMap-deleted.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/dependencyAndUsage/disabledSourceRef/goToDef-and-rename-locations.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/usageProject/configHasNoReference/can-go-to-definition-correctly.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/usageProject/configHasNoReference/dependency-dts-created.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/usageProject/configHasNoReference/dependency-dts-deleted.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/usageProject/configHasNoReference/dependency-dtsMap-created.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/usageProject/configHasNoReference/dependency-dtsMap-deleted.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/usageProject/disabledSourceRef/can-go-to-definition-correctly.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/usageProject/disabledSourceRef/dependency-dts-created.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/usageProject/disabledSourceRef/dependency-dts-deleted.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/usageProject/disabledSourceRef/dependency-dtsMap-created.js
  tests/baselines/reference/tsserver/projectReferencesSourcemap/usageProject/disabledSourceRef/dependency-dtsMap-deleted.js
Labels: Author: Team, For Uncommitted Bug

#57363 Add replacement release pipeline
  .github/workflows/insiders.yaml
  azure-pipelines.release.yml
Labels: Author: Team, For Uncommitted Bug

#57495 Fix output artifact in new release pipeline
  azure-pipelines.release.yml
Labels: Author: Team, For Uncommitted Bug

#57496 Add even more config to release pipeline
  azure-pipelines.release.yml
Labels: Author: Team, For Uncommitted Bug

#57509 Switch release pipeline image
  azure-pipelines.release.yml
Labels: Author: Team, For Uncommitted Bug

#57213 Switch our tsconfigs over to NodeNext
  src/cancellationToken/tsconfig.json
  src/tsconfig-base.json
Labels: Author: Team, Housekeeping, For Uncommitted Bug

#57513 Add release pipeline to release-5.4
  azure-pipelines.release.yml
Labels: Author: Team, For Uncommitted Bug

#57364 fix(57348): Auto-complete on satisfies auto-imports satisfies
  src/services/completions.ts
  tests/baselines/reference/completionsImport_asKeyword.baseline
  tests/baselines/reference/completionsImport_satisfiesKeyword.baseline
  tests/cases/fourslash/completionsImport_asKeyword.ts
  tests/cases/fourslash/completionsImport_satisfiesKeyword.ts
Labels: For Backlog Bug

#57554 Close "Design Limitation" automatically
  .github/workflows/close-issues.yml
Labels: Author: Team, For Uncommitted Bug

#57350 Error on unused eslint directives, reenable lost eslint rules
  .eslintrc.json
  Herebyfile.mjs
  scripts/build/options.mjs
  src/compiler/moduleNameResolver.ts
  src/compiler/types.ts
  src/server/editorServices.ts
  src/typingsInstallerCore/typingsInstaller.ts
Labels: Author: Team, For Uncommitted Bug

#57542 Prefer global over object members completions after `...`
  src/services/completions.ts
  tests/cases/fourslash/completionsDotDotDotInObjectLiteral1.ts
Labels: For Backlog Bug

#57382 Get narrowable types for new expressions
  src/compiler/checker.ts
  tests/baselines/reference/typeVariableTypeGuards.js
  tests/baselines/reference/typeVariableTypeGuards.symbols
  tests/baselines/reference/typeVariableTypeGuards.types
  tests/cases/compiler/typeVariableTypeGuards.ts
Labels: For Backlog Bug

#57484 Preserve parameter types for optional parameters /fields with undefined in type and for required params with default value
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/transformers/declarations.ts
  src/compiler/types.ts
  tests/baselines/reference/verbatim-declarations-parameters.js
  tests/baselines/reference/verbatim-declarations-parameters.symbols
  tests/baselines/reference/verbatim-declarations-parameters.types
  tests/cases/compiler/verbatim-declarations-parameters.ts
Labels: For Backlog Bug
