Repository microsoft/TypeScript, pull requests merged in 2024-11, with the labels that each got.

#60252 Fix incorrect details in lib.decorators
  src/lib/decorators.d.ts
Labels: For Uncommitted Bug

#60391 Add compatible overloads that accept ArrayBuffer to BigInt64Array/BigUint64Array
  src/lib/es2020.bigint.d.ts
  tests/baselines/reference/bigintWithLib.errors.txt
  tests/cases/compiler/typedArrayConstructorOverloads.ts
Labels: Author: Team, For Milestone Bug

#60362 Fixing exception on unsaved file
  src/server/session.ts
  src/testRunner/unittests/tsserver/pasteEdits.ts
  tests/baselines/reference/tsserver/pasteEdits/should-not-error.js
Labels: Author: Team, For Milestone Bug

#60402 Fixed syntactic nullisness semantics for comma expressions
  src/compiler/checker.ts
  tests/baselines/reference/predicateSemantics.errors.txt
  tests/baselines/reference/predicateSemantics.js
  tests/baselines/reference/predicateSemantics.symbols
  tests/baselines/reference/predicateSemantics.types
  tests/cases/compiler/predicateSemantics.ts
Labels: For Uncommitted Bug

#60422 Bump version to 5.8.
  package-lock.json
  package.json
  src/compiler/corePublic.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#60415 Fix false positive rewriteRelativeImportExtensions error on non-TS extensions
  src/compiler/utilities.ts
  tests/baselines/reference/nonTSExtensions.js
  tests/cases/conformance/externalModules/rewriteRelativeImportExtensions/nonTSExtensions.ts
Labels: Author: Team, For Milestone Bug

#60250 Remove cancellationToken.js
  Herebyfile.mjs
  knip.jsonc
  scripts/produceLKG.mjs
  src/cancellationToken/cancellationToken.ts
  src/cancellationToken/tsconfig.json
  src/tsconfig.json
  src/tsserver/nodeServer.ts
Labels: Author: Team, For Uncommitted Bug

#59940 Proposed expandable hover API
  src/compiler/checker.ts
  src/compiler/types.ts
  src/harness/client.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/server/protocol.ts
  src/server/session.ts
  src/services/services.ts
  src/services/symbolDisplay.ts
  src/services/types.ts
  src/services/utilities.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/quickinfoVerbosity1.baseline
  tests/baselines/reference/quickinfoVerbosity2.baseline
  tests/baselines/reference/quickinfoVerbosityClass1.baseline
  tests/baselines/reference/quickinfoVerbosityInterface1.baseline
  tests/baselines/reference/quickinfoVerbosityIntersection1.baseline
  tests/baselines/reference/quickinfoVerbosityObjectType1.baseline
  tests/baselines/reference/quickinfoVerbosityServer.baseline
  tests/baselines/reference/quickinfoVerbosityTruncation.baseline
  tests/baselines/reference/tsserver/fourslashServer/quickinfoVerbosityServer.js
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/quickinfoVerbosity1.ts
  tests/cases/fourslash/quickinfoVerbosity2.ts
  tests/cases/fourslash/quickinfoVerbosityClass1.ts
  tests/cases/fourslash/quickinfoVerbosityInterface1.ts
  tests/cases/fourslash/quickinfoVerbosityIntersection1.ts
  tests/cases/fourslash/quickinfoVerbosityObjectType1.ts
  tests/cases/fourslash/quickinfoVerbosityTruncation.ts
  tests/cases/fourslash/server/quickinfoVerbosityServer.ts
Labels: Author: Team, For Uncommitted Bug

#60309 Fix `getEffectiveCheckNode`
  src/compiler/checker.ts
  src/compiler/factory/utilities.ts
  src/compiler/types.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/arrowExpressionBodyJSDoc.errors.txt
  tests/baselines/reference/arrowExpressionBodyJSDoc.symbols
  tests/baselines/reference/arrowExpressionBodyJSDoc.types
  tests/baselines/reference/typeSatisfaction_errorLocations1.errors.txt
  tests/baselines/reference/typeSatisfaction_errorLocations1.symbols
  tests/baselines/reference/typeSatisfaction_errorLocations1.types
  tests/cases/compiler/arrowExpressionBodyJSDoc.ts
  tests/cases/conformance/expressions/typeSatisfaction/typeSatisfaction_errorLocations1.ts
Labels: Author: Team, For Uncommitted Bug

#60208 Reuse cached resolved signatures early
  src/compiler/checker.ts
  tests/baselines/reference/mixinWithBaseDependingOnSelfNoCrash1.errors.txt
  tests/baselines/reference/mixinWithBaseDependingOnSelfNoCrash1.symbols
  tests/baselines/reference/mixinWithBaseDependingOnSelfNoCrash1.types
  tests/cases/conformance/classes/mixinWithBaseDependingOnSelfNoCrash1.ts
Labels: For Uncommitted Bug

#56941 Narrow generic conditional and indexed access return types when checking return statements
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/types.ts
  tests/baselines/reference/arrowExpressionJs.symbols
  tests/baselines/reference/arrowExpressionJs.types
  tests/baselines/reference/dependentReturnType1.errors.txt
  tests/baselines/reference/dependentReturnType1.symbols
  tests/baselines/reference/dependentReturnType1.types
  tests/baselines/reference/dependentReturnType2.errors.txt
  tests/baselines/reference/dependentReturnType2.symbols
  tests/baselines/reference/dependentReturnType2.types
  tests/baselines/reference/dependentReturnType3.errors.txt
  tests/baselines/reference/dependentReturnType3.symbols
  tests/baselines/reference/dependentReturnType3.types
  tests/baselines/reference/dependentReturnType4.errors.txt
  tests/baselines/reference/dependentReturnType4.symbols
  tests/baselines/reference/dependentReturnType4.types
  tests/baselines/reference/dependentReturnType5.errors.txt
  tests/baselines/reference/dependentReturnType5.symbols
  tests/baselines/reference/dependentReturnType5.types
  tests/baselines/reference/dependentReturnType6.errors.txt
  tests/baselines/reference/dependentReturnType6.symbols
  tests/baselines/reference/dependentReturnType6.types
  tests/baselines/reference/dependentReturnType8.symbols
  tests/baselines/reference/dependentReturnType8.types
  tests/baselines/reference/returnConditionalExpressionJSDocCast.symbols
  tests/baselines/reference/returnConditionalExpressionJSDocCast.types
  tests/baselines/reference/unusedLocalsInRecursiveReturn.symbols
  tests/baselines/reference/unusedLocalsInRecursiveReturn.types
  tests/cases/compiler/arrowExpressionJs.ts
  tests/cases/compiler/dependentReturnType1.ts
  tests/cases/compiler/dependentReturnType2.ts
  tests/cases/compiler/dependentReturnType3.ts
  tests/cases/compiler/dependentReturnType4.ts
  tests/cases/compiler/dependentReturnType5.ts
  tests/cases/compiler/dependentReturnType6.ts
  tests/cases/compiler/dependentReturnType8.ts
  tests/cases/compiler/returnConditionalExpressionJSDocCast.ts
  tests/cases/compiler/unusedLocalsInRecursiveReturn.ts
  tests/cases/fourslash/returnTypeNarrowingAfterCachingTypes.ts
Labels: Author: Team, For Uncommitted Bug

#60440 MetaProperty is possibly nullish
  src/compiler/checker.ts
  tests/baselines/reference/predicateSemantics.errors.txt
  tests/baselines/reference/predicateSemantics.js
  tests/baselines/reference/predicateSemantics.symbols
  tests/baselines/reference/predicateSemantics.types
  tests/cases/compiler/predicateSemantics.ts
Labels: Author: Team, For Milestone Bug

#60314 feat(60312): Add missing properties for satisfies
  src/services/codefixes/fixAddMissingMember.ts
  tests/cases/fourslash/codeFixAddMissingProperties33.ts
  tests/cases/fourslash/codeFixAddMissingProperties34.ts
  tests/cases/fourslash/codeFixAddMissingProperties35.ts
  tests/cases/fourslash/codeFixAddMissingProperties36.ts
  tests/cases/fourslash/codeFixAddMissingProperties37.ts
  tests/cases/fourslash/codeFixAddMissingProperties38.ts
  tests/cases/fourslash/codeFixAddMissingProperties39.ts
  tests/cases/fourslash/codeFixAddMissingProperties40.ts
  tests/cases/fourslash/codeFixAddMissingProperties41.ts
  tests/cases/fourslash/codeFixAddMissingProperties42.ts
  tests/cases/fourslash/codeFixAddMissingProperties43.ts
  tests/cases/fourslash/codeFixAddMissingProperties44.ts
  tests/cases/fourslash/codeFixAddMissingProperties_all.ts
Labels: For Backlog Bug

#60488 Stub out copilotRelated command
  src/harness/client.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/server/protocol.ts
  src/server/session.ts
  src/services/services.ts
  src/services/types.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/getImportsDuplicate.ts
  tests/cases/fourslash/getImportsDynamic.ts
  tests/cases/fourslash/getImportsJSXFactory.ts
  tests/cases/fourslash/getImportsNone.ts
  tests/cases/fourslash/getImportsOne.ts
  tests/cases/fourslash/getImportsOneJs.ts
  tests/cases/fourslash/getImportsReexport.ts
  tests/cases/fourslash/getImportsTslib.ts
Labels: Author: Team, For Uncommitted Bug

#60267 Let isolated declarations fixer add toplevel imports more
  src/services/codefixes/helpers.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports56-toplevel-import.ts
Labels: For Uncommitted Bug

#60450 Move to file: fix detection of references to globals that shouldn't be moved
  src/services/refactors/moveToFile.ts
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_globalAndLocal1.js
  tests/baselines/reference/tsserver/fourslashServer/pasteEdits_globalAndLocal2.js
  tests/cases/fourslash/codeFixClassImplementInterfaceGlobal.ts
  tests/cases/fourslash/moveToNewFile_globalAndLocal1.ts
  tests/cases/fourslash/moveToNewFile_globalAndLocal2.ts
  tests/cases/fourslash/moveToNewFile_globalAndLocal3.ts
  tests/cases/fourslash/moveToNewFile_globalAndLocal4.ts
  tests/cases/fourslash/moveToNewFile_globalAndLocal5.ts
  tests/cases/fourslash/moveToNewFile_globalAndLocal6.ts
  tests/cases/fourslash/moveToNewFile_importNameLikeGlobal1.ts
  tests/cases/fourslash/server/pasteEdits_globalAndLocal1.ts
  tests/cases/fourslash/server/pasteEdits_globalAndLocal2.ts
Labels: Author: Team, For Milestone Bug

#60510 fix(60505): Convert to namespace import refactoring should drop file extensions on namespace name
  src/services/utilities.ts
  tests/cases/fourslash/refactorConvertImport_namedToNamespace11.ts
Labels: For Uncommitted Bug

#60490 fix(60484): Implementing a prim type in a class expression should report error
  src/compiler/checker.ts
  tests/baselines/reference/classExtendingPrimitive.errors.txt
  tests/baselines/reference/classExtendingPrimitive.js
  tests/baselines/reference/classExtendingPrimitive.symbols
  tests/baselines/reference/classExtendingPrimitive.types
  tests/baselines/reference/classImplementsPrimitive.errors.txt
  tests/baselines/reference/classImplementsPrimitive.js
  tests/baselines/reference/classImplementsPrimitive.symbols
  tests/baselines/reference/classImplementsPrimitive.types
  tests/cases/compiler/classImplementsPrimitive.ts
  tests/cases/conformance/classes/classDeclarations/classHeritageSpecification/classExtendingPrimitive.ts
Labels: For Backlog Bug

#60615 fix missing react error with fragments in `react-native`
  src/compiler/checker.ts
  tests/baselines/reference/jsxFragReactReferenceErrors(jsx=preserve).js
  tests/baselines/reference/jsxFragReactReferenceErrors(jsx=preserve).symbols
  tests/baselines/reference/jsxFragReactReferenceErrors(jsx=preserve).types
  tests/baselines/reference/jsxFragReactReferenceErrors(jsx=react-native).js
  tests/baselines/reference/jsxFragReactReferenceErrors(jsx=react-native).symbols
  tests/baselines/reference/jsxFragReactReferenceErrors(jsx=react-native).types
  tests/cases/compiler/jsxFragReactReferenceErrors.tsx
Labels: Author: Team, For Uncommitted Bug

#60616 Fixed syntactic nullisness semantics for tagged template expressions
  src/compiler/checker.ts
  tests/baselines/reference/predicateSemantics.errors.txt
  tests/baselines/reference/predicateSemantics.js
  tests/baselines/reference/predicateSemantics.symbols
  tests/baselines/reference/predicateSemantics.types
  tests/cases/compiler/predicateSemantics.ts
Labels: For Uncommitted Bug

#60493 Improve the definition of atan2()
  src/lib/es5.d.ts
Labels: For Uncommitted Bug
