Repository microsoft/TypeScript, pull requests merged in 2024-08, with the labels that each got.

#59500 Add support for the @jsxruntime pragma
  src/compiler/utilities.ts
  tests/baselines/reference/jsxRuntimePragma(jsx=react).js
  tests/baselines/reference/jsxRuntimePragma(jsx=react).symbols
  tests/baselines/reference/jsxRuntimePragma(jsx=react).types
  tests/baselines/reference/jsxRuntimePragma(jsx=react-jsx).js
  tests/baselines/reference/jsxRuntimePragma(jsx=react-jsx).symbols
  tests/baselines/reference/jsxRuntimePragma(jsx=react-jsx).types
  tests/baselines/reference/jsxRuntimePragma(jsx=react-jsxdev).js
  tests/baselines/reference/jsxRuntimePragma(jsx=react-jsxdev).symbols
  tests/baselines/reference/jsxRuntimePragma(jsx=react-jsxdev).types
  tests/cases/compiler/jsxRuntimePragma.ts
Labels: Author: Team, For Milestone Bug

#59310 Allow `this` when it appears in `this is T` positions
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitThisPredicates02.errors.txt
  tests/baselines/reference/declarationEmitThisPredicates02.types
  tests/baselines/reference/declarationEmitThisPredicatesWithPrivateName02.errors.txt
  tests/baselines/reference/declarationEmitThisPredicatesWithPrivateName02.types
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty2.js
  tests/baselines/reference/thisPredicateInObjectLiteral.errors.txt
  tests/baselines/reference/thisPredicateInObjectLiteral.js
  tests/baselines/reference/thisPredicateInObjectLiteral.symbols
  tests/baselines/reference/thisPredicateInObjectLiteral.types
  tests/baselines/reference/typeGuardFunctionOfFormThisErrors.errors.txt
  tests/cases/compiler/thisPredicateInObjectLiteral.ts
Labels: Author: Team, For Uncommitted Bug

#59466 Update deps
  .dprint.jsonc
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#59511 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20240802111725489 to main
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#59507 Remove incorrect call to checkTruthinessExpression
  src/compiler/checker.ts
  tests/baselines/reference/nullishCoalescingOperator7.errors.txt
  tests/baselines/reference/predicateSemantics.errors.txt
  tests/baselines/reference/predicateSemantics.js
  tests/baselines/reference/predicateSemantics.symbols
  tests/baselines/reference/predicateSemantics.types
  tests/cases/compiler/predicateSemantics.ts
Labels: Author: Team, For Uncommitted Bug

#57704 Allow `import =` in module augmentations
  src/compiler/checker.ts
  tests/baselines/reference/importAliasInModuleAugmentation.errors.txt
  tests/baselines/reference/importAliasInModuleAugmentation.js
  tests/baselines/reference/importAliasInModuleAugmentation.symbols
  tests/baselines/reference/importAliasInModuleAugmentation.types
  tests/baselines/reference/moduleAugmentationImportsAndExports2.errors.txt
  tests/baselines/reference/moduleAugmentationImportsAndExports3.errors.txt
  tests/baselines/reference/newNamesInGlobalAugmentations1.errors.txt
  tests/cases/compiler/importAliasInModuleAugmentation.ts
Labels: Author: Team, For Backlog Bug

#59522 Fix mismerged baselines
  tests/baselines/reference/importAliasInModuleAugmentation.types
  tests/baselines/reference/newNamesInGlobalAugmentations1.types
Labels: Author: Team, For Uncommitted Bug

#59538 Don't treat an instantiation expression as an assertion in skipOuterExpressions
  src/compiler/factory/nodeFactory.ts
  src/compiler/factory/utilities.ts
  src/compiler/transformers/ts.ts
  src/compiler/types.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/assignmentToInstantiationExpression.errors.txt
  tests/baselines/reference/assignmentToInstantiationExpression.js
  tests/baselines/reference/assignmentToInstantiationExpression.symbols
  tests/baselines/reference/assignmentToInstantiationExpression.types
  tests/cases/compiler/assignmentToInstantiationExpression.ts
Labels: Author: Team, For Uncommitted Bug

#56201 Fixed types of properties of contextual filtering mapped types
  src/compiler/checker.ts
  tests/baselines/reference/contextualPropertyOfGenericFilteringMappedType.symbols
  tests/baselines/reference/contextualPropertyOfGenericFilteringMappedType.types
  tests/cases/compiler/contextualPropertyOfGenericFilteringMappedType.ts
Labels: For Backlog Bug

#59544 Fix accidental relative imports from non namespace barrels
  eslint.config.mjs
  scripts/eslint/rules/no-direct-import.cjs
  src/services/codefixes/fixMissingTypeAnnotationOnExports.ts
  src/services/pasteEdits.ts
  src/services/refactors/moveToFile.ts
  src/services/stringCompletions.ts
Labels: Author: Team, For Uncommitted Bug

#59440 Refactored node builder flags and tests
  src/compiler/checker.ts
  src/compiler/transformers/declarations.ts
  src/compiler/types.ts
  src/harness/typeWriter.ts
  src/services/codefixes/fixAddMissingConstraint.ts
  src/services/codefixes/fixAddMissingMember.ts
  src/services/codefixes/fixAddMissingParam.ts
  src/services/codefixes/fixClassIncorrectlyImplementsInterface.ts
  src/services/codefixes/fixMissingTypeAnnotationOnExports.ts
  src/services/codefixes/helpers.ts
  src/services/completions.ts
  src/services/refactors/extractSymbol.ts
  src/services/refactors/inferFunctionReturnType.ts
  src/services/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#59516 Properly account for type parameters introduced by contextual types
  src/compiler/checker.ts
  tests/baselines/reference/contextualOuterTypeParameters.symbols
  tests/baselines/reference/contextualOuterTypeParameters.types
  tests/cases/compiler/contextualOuterTypeParameters.ts
Labels: Author: Team, For Milestone Bug

#59510 Fixed regression in generic signature instantiation with default type args
  src/compiler/checker.ts
  tests/baselines/reference/genericCallInferenceConditionalType2.symbols
  tests/baselines/reference/genericCallInferenceConditionalType2.types
  tests/cases/compiler/genericCallInferenceConditionalType2.ts
Labels: For Milestone Bug

#59543 Add `autoImportSpecifierExcludeRegexes` preference
  src/compiler/moduleSpecifiers.ts
  src/compiler/types.ts
  src/services/completions.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/autoImportSpecifierExcludeRegexes1.ts
  tests/cases/fourslash/autoImportSpecifierExcludeRegexes2.ts
  tests/cases/fourslash/autoImportSpecifierExcludeRegexes3.ts
  tests/cases/fourslash/fourslash.ts
Labels: Author: Team, For Uncommitted Bug

#59316 fix: filtering promise properties in object literal completion
  src/services/completions.ts
  tests/cases/fourslash/completionsPropertiesWithPromiseUnionType.ts
Labels: For Backlog Bug

#59564 Fix auto import file extensions with package.json imports wildcards
  src/compiler/moduleSpecifiers.ts
  src/compiler/utilities.ts
  tests/cases/fourslash/autoImportAllowImportingTsExtensionsPackageJsonImports1.ts
  tests/cases/fourslash/autoImportAllowImportingTsExtensionsPackageJsonImports2.ts
  tests/cases/fourslash/autoImportPackageJsonImportsCaseSensitivity.ts
Labels: Author: Team, For Milestone Bug

#59527 Fixed completion crashes related to `JSDocImportTag`
  src/compiler/binder.ts
  tests/cases/fourslash/completionsImportDeclarationAttributesEmptyModuleSpecifier1.ts
  tests/cases/fourslash/completionsImportDeclarationAttributesErrorModuleSpecifier1.ts
  tests/cases/fourslash/completionsJSDocImportTagAttributesEmptyModuleSpecifier1.ts
  tests/cases/fourslash/completionsJSDocImportTagAttributesErrorModuleSpecifier1.ts
  tests/cases/fourslash/completionsJSDocImportTagEmptyModuleSpecifier1.ts
  tests/cases/fourslash/completionsJSDocNoCrash1.ts
  tests/cases/fourslash/completionsJSDocNoCrash2.ts
Labels: For Backlog Bug

#58177 fix(58166): Class parameter property with initializer before required property emits non-nullable parameter for declaration emit
  src/compiler/checker.ts
  src/compiler/expressionToTypeNode.ts
  src/compiler/transformers/declarations.ts
  src/compiler/transformers/declarations/diagnostics.ts
  src/compiler/types.ts
  src/services/codefixes/fixMissingTypeAnnotationOnExports.ts
  tests/baselines/reference/parameterPropertyInConstructor4.js
  tests/baselines/reference/parameterPropertyInConstructor4.symbols
  tests/baselines/reference/parameterPropertyInConstructor4.types
  tests/cases/compiler/parameterPropertyInConstructor4.ts
Labels: For Backlog Bug

#59518 Update to eslint v9, typescript-eslint v8
  eslint.config.mjs
  package-lock.json
  package.json
  scripts/eslint/tests/argument-trivia.test.cjs
  scripts/eslint/tests/debug-assert.test.cjs
  scripts/eslint/tests/js-extensions.cjs
  scripts/eslint/tests/no-in-operator.test.cjs
  scripts/eslint/tests/no-keywords.test.cjs
  scripts/eslint/tests/only-arrow-functions.test.cjs
  scripts/eslint/tests/support/RuleTester.cjs
  scripts/failed-tests.cjs
  scripts/find-unused-diganostic-messages.mjs
  src/compiler/sys.ts
  src/compiler/utilitiesPublic.ts
  src/compiler/watchUtilities.ts
  src/harness/harnessUtils.ts
  src/tsserver/nodeServer.ts
  src/typingsInstaller/nodeTypingsInstaller.ts
Labels: Author: Team, For Uncommitted Bug

#59611 Add a regression test related to narrowing in plain JS files
  tests/baselines/reference/narrowingPlainJsNoCrash1.js
  tests/baselines/reference/narrowingPlainJsNoCrash1.symbols
  tests/baselines/reference/narrowingPlainJsNoCrash1.types
  tests/cases/compiler/narrowingPlainJsNoCrash1.ts
Labels: For Backlog Bug

#59612 Allow trailing commas on lambda type parameter lists
  src/compiler/emitter.ts
  src/testRunner/unittests/printer.ts
  tests/baselines/reference/printerApi/printsFileCorrectly.lambda type parameter lists in tsx.js
Labels: Author: Team, For Milestone Bug

#59621 Add v8-json to coverage output for use with monocart VS Code extension
  .c8rc.json
Labels: Author: Team, For Uncommitted Bug

#59590 Avoid reporting EPC on unannotated using declarations
  src/compiler/checker.ts
  tests/baselines/reference/usingDeclarationsWithObjectLiterals1.errors.txt
  tests/baselines/reference/usingDeclarationsWithObjectLiterals1.symbols
  tests/baselines/reference/usingDeclarationsWithObjectLiterals1.types
  tests/baselines/reference/usingDeclarationsWithObjectLiterals2(noimplicitany=false).symbols
  tests/baselines/reference/usingDeclarationsWithObjectLiterals2(noimplicitany=false).types
  tests/baselines/reference/usingDeclarationsWithObjectLiterals2(noimplicitany=true).errors.txt
  tests/baselines/reference/usingDeclarationsWithObjectLiterals2(noimplicitany=true).symbols
  tests/baselines/reference/usingDeclarationsWithObjectLiterals2(noimplicitany=true).types
  tests/cases/conformance/statements/VariableStatements/usingDeclarations/usingDeclarationsWithObjectLiterals1.ts
  tests/cases/conformance/statements/VariableStatements/usingDeclarations/usingDeclarationsWithObjectLiterals2.ts
Labels: For Milestone Bug

#59371 Add regex eslint plugin, fix lints
  eslint.config.mjs
  package-lock.json
  package.json
  scripts/build/tests.mjs
  scripts/configurePrerelease.mjs
  scripts/failed-tests.cjs
  scripts/generateLocalizedDiagnosticMessages.mjs
  scripts/processDiagnosticMessages.mjs
  scripts/regenerate-unicode-identifier-parts.mjs
  src/compiler/checker.ts
  src/compiler/commandLineParser.ts
  src/compiler/debug.ts
  src/compiler/emitter.ts
  src/compiler/parser.ts
  src/compiler/path.ts
  src/compiler/program.ts
  src/compiler/resolutionCache.ts
  src/compiler/semver.ts
  src/compiler/sourcemap.ts
  src/compiler/sys.ts
  src/compiler/transformers/jsx.ts
  src/compiler/utilities.ts
  src/compiler/utilitiesPublic.ts
  src/harness/documentsUtil.ts
  src/harness/fourslashImpl.ts
  src/harness/harnessIO.ts
  src/harness/harnessUtils.ts
  src/harness/incrementalUtils.ts
  src/harness/runnerbase.ts
  src/harness/typeWriter.ts
  src/harness/util.ts
  src/harness/vpathUtil.ts
  src/server/editorServices.ts
  src/services/classifier.ts
  src/services/codefixes/convertTypedefToType.ts
  src/services/navigationBar.ts
  src/services/outliningElementsCollector.ts
  src/services/services.ts
  src/services/sourcemaps.ts
  src/testRunner/runner.ts
  src/testRunner/unittests/config/initializeTSConfig.ts
  src/testRunner/unittests/config/showConfig.ts
  src/testRunner/unittests/helpers/baseline.ts
  src/testRunner/unittests/jsonParserRecovery.ts
  src/testRunner/unittests/printer.ts
  src/testRunner/unittests/services/transpile.ts
  src/testRunner/unittests/tsserver/cachingFileSystemInformation.ts
Labels: Author: Team, For Uncommitted Bug

#59625 Handle delayed or missed watches for project updates
  src/compiler/watchUtilities.ts
  src/server/editorServices.ts
  src/testRunner/unittests/helpers/virtualFileSystemWithWatch.ts
  src/testRunner/unittests/tsserver/getEditsForFileRename.ts
  src/testRunner/unittests/tsserver/projects.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/tscWatch/resolutionCache/works-when-renaming-node_modules-folder-that-already-contains-@types-folder.js
  tests/baselines/reference/tsserver/getEditsForFileRename/works-when-moving-file-to-and-from-folder-canUseWatchEvents.js
  tests/baselines/reference/tsserver/getEditsForFileRename/works-when-moving-file-to-and-from-folder.js
  tests/baselines/reference/tsserver/projectErrors/folder-rename-updates-project-structure-and-reports-no-errors.js
  tests/baselines/reference/tsserver/projects/handles-delayed-directory-watch-invoke-on-file-creation.js
  tests/baselines/reference/tsserver/watchEnvironment/uses-dynamic-polling-when-file-is-added-to-subfolder.js
  tests/baselines/reference/tsserver/watchEnvironment/uses-watchFile-when-file-is-added-to-subfolder.js
Labels: Author: Team, For Uncommitted Bug

#59526 Add custom eslint rule 'no-array-mutating-method-expressions'
  eslint.config.mjs
  package-lock.json
  package.json
  scripts/eslint/rules/no-array-mutating-method-expressions.cjs
  src/harness/fourslashImpl.ts
  src/harness/projectServiceStateLogger.ts
  src/services/mapCode.ts
  src/services/navigateTo.ts
  src/services/outliningElementsCollector.ts
  src/services/refactors/extractSymbol.ts
  src/services/suggestionDiagnostics.ts
  src/testRunner/unittests/services/extract/ranges.ts
Labels: Author: Team, For Uncommitted Bug

#59519 Suggest simplifications for overzealous shifts
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/harness/compilerImpl.ts
  src/harness/harnessIO.ts
  tests/baselines/reference/overshifts.errors.txt
  tests/baselines/reference/overshifts.js
  tests/baselines/reference/overshifts.symbols
  tests/baselines/reference/overshifts.types
  tests/cases/compiler/overshifts.ts
Labels: Author: Team, For Uncommitted Bug

#59425 Expand intersection reduction division strategy down to 3-member intersections
  src/compiler/checker.ts
  tests/baselines/reference/pickOfLargeObjectUnionWorks.js
  tests/baselines/reference/pickOfLargeObjectUnionWorks.symbols
  tests/baselines/reference/pickOfLargeObjectUnionWorks.types
  tests/cases/compiler/pickOfLargeObjectUnionWorks.ts
Labels: Author: Team, For Uncommitted Bug

#58380 Report unreachable on enums
  src/compiler/binder.ts
  tests/baselines/reference/reachabilityChecks1.errors.txt
  tests/baselines/reference/unreachableDeclarations(preserveconstenums=false).errors.txt
  tests/baselines/reference/unreachableDeclarations(preserveconstenums=false).js
  tests/baselines/reference/unreachableDeclarations(preserveconstenums=false).symbols
  tests/baselines/reference/unreachableDeclarations(preserveconstenums=false).types
  tests/baselines/reference/unreachableDeclarations(preserveconstenums=true).errors.txt
  tests/baselines/reference/unreachableDeclarations(preserveconstenums=true).js
  tests/baselines/reference/unreachableDeclarations(preserveconstenums=true).symbols
  tests/baselines/reference/unreachableDeclarations(preserveconstenums=true).types
  tests/cases/compiler/unreachableDeclarations.ts
  tests/cases/fourslash/codeFixUnreachableCode.ts
Labels: Author: Team, For Milestone Bug

#59639 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20240815102137942 to main
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#59636 allow `generateTrace` in tsconfig and compiler API
  src/compiler/commandLineParser.ts
Labels: For Uncommitted Bug

#54849 Improve inlining of string variables in template literals
  src/services/refactors/inlineVariable.ts
  tests/cases/fourslash/inlineVariableTemplateString1.ts
  tests/cases/fourslash/inlineVariableTemplateString10.ts
  tests/cases/fourslash/inlineVariableTemplateString11.ts
  tests/cases/fourslash/inlineVariableTemplateString2.ts
  tests/cases/fourslash/inlineVariableTemplateString3.ts
  tests/cases/fourslash/inlineVariableTemplateString4.ts
  tests/cases/fourslash/inlineVariableTemplateString5.ts
  tests/cases/fourslash/inlineVariableTemplateString6.ts
  tests/cases/fourslash/inlineVariableTemplateString7.ts
  tests/cases/fourslash/inlineVariableTemplateString8.ts
  tests/cases/fourslash/inlineVariableTemplateString9.ts
Labels: For Backlog Bug

#59628 Add an extra test case for narrowing of union containing a type parameter
  tests/baselines/reference/controlFlowUnionContainingTypeParameter1.symbols
  tests/baselines/reference/controlFlowUnionContainingTypeParameter1.types
  tests/cases/compiler/controlFlowUnionContainingTypeParameter1.ts
Labels: For Milestone Bug

#59604 Allow existing imports in file to supersede package.json filter
  src/compiler/types.ts
  src/server/moduleSpecifierCache.ts
  src/services/codefixes/importFixes.ts
  src/services/completions.ts
  src/services/exportInfoMap.ts
  src/services/utilities.ts
  tests/baselines/reference/tsserver/fourslashServer/autoImportPackageJsonFilterExistingImport1.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportPackageJsonFilterExistingImport2.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportPackageJsonFilterExistingImport3.js
  tests/cases/fourslash/server/autoImportPackageJsonFilterExistingImport1.ts
  tests/cases/fourslash/server/autoImportPackageJsonFilterExistingImport2.ts
  tests/cases/fourslash/server/autoImportPackageJsonFilterExistingImport3.ts
Labels: Author: Team, For Milestone Bug

#59609 Set parents of augmented module exports
  src/compiler/checker.ts
  tests/cases/fourslash/autoImportCompletionExportListAugmentation1.ts
  tests/cases/fourslash/autoImportCompletionExportListAugmentation2.ts
  tests/cases/fourslash/autoImportCompletionExportListAugmentation3.ts
  tests/cases/fourslash/autoImportCompletionExportListAugmentation4.ts
Labels: Author: Team, For Milestone Bug

#59642 Set declarationMap to false in transpileModule.
  src/services/transpile.ts
  src/testRunner/unittests/services/transpile.ts
  tests/baselines/reference/transpile/Supports setting declarationMap (verbatimModuleSyntax=true).js
  tests/baselines/reference/transpile/Supports setting declarationMap (verbatimModuleSyntax=true).oldTranspile.js
  tests/baselines/reference/transpile/Supports setting declarationMap.js
  tests/baselines/reference/transpile/Supports setting declarationMap.oldTranspile.js
Labels: For Uncommitted Bug

#59647 Do not overwrite original pointer when indirectly points to location
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug

#59644 Do not get awaited type of AsyncGenerator TNext
  src/compiler/checker.ts
  tests/baselines/reference/asyncGeneratorPromiseNextType.symbols
  tests/baselines/reference/asyncGeneratorPromiseNextType.types
  tests/cases/conformance/asyncGenerators/asyncGeneratorPromiseNextType.ts
Labels: Author: Team, For Milestone Bug

#59633 built-in iterators should be disposable
  src/harness/evaluatorImpl.ts
  src/lib/esnext.disposable.d.ts
  src/testRunner/unittests/evaluation/awaitUsingDeclarations.ts
  src/testRunner/unittests/evaluation/usingDeclarations.ts
  tests/baselines/reference/awaitUsingDeclarationsWithAsyncIteratorObject.errors.txt
  tests/baselines/reference/awaitUsingDeclarationsWithAsyncIteratorObject.symbols
  tests/baselines/reference/awaitUsingDeclarationsWithAsyncIteratorObject.types
  tests/baselines/reference/awaitUsingDeclarationsWithIteratorObject.errors.txt
  tests/baselines/reference/awaitUsingDeclarationsWithIteratorObject.symbols
  tests/baselines/reference/awaitUsingDeclarationsWithIteratorObject.types
  tests/baselines/reference/builtinIterator.symbols
  tests/baselines/reference/discriminateWithOptionalProperty2(exactoptionalpropertytypes=false).symbols
  tests/baselines/reference/discriminateWithOptionalProperty2(exactoptionalpropertytypes=false).types
  tests/baselines/reference/discriminateWithOptionalProperty2(exactoptionalpropertytypes=true).symbols
  tests/baselines/reference/discriminateWithOptionalProperty2(exactoptionalpropertytypes=true).types
  tests/baselines/reference/usingDeclarationsWithIteratorObject.errors.txt
  tests/baselines/reference/usingDeclarationsWithIteratorObject.symbols
  tests/baselines/reference/usingDeclarationsWithIteratorObject.types
  tests/cases/compiler/discriminateWithOptionalProperty2.ts
  tests/cases/conformance/statements/VariableStatements/usingDeclarations/awaitUsingDeclarationsWithAsyncIteratorObject.ts
  tests/cases/conformance/statements/VariableStatements/usingDeclarations/awaitUsingDeclarationsWithIteratorObject.ts
  tests/cases/conformance/statements/VariableStatements/usingDeclarations/usingDeclarationsWithIteratorObject.ts
Labels: Author: Team, For Milestone Bug

#59421 also return classes when caling goToDef on a constructor call
  src/services/goToDefinition.ts
  tests/baselines/reference/goToDefinitionAmbiants.baseline.jsonc
  tests/baselines/reference/goToDefinitionClassConstructors.baseline.jsonc
  tests/baselines/reference/goToDefinitionConstructorOfClassExpression01.baseline.jsonc
  tests/baselines/reference/goToDefinitionConstructorOfClassWhenClassIsPrecededByNamespace01.baseline.jsonc
  tests/baselines/reference/goToDefinitionConstructorOverloads.baseline.jsonc
  tests/cases/fourslash/goToDefinitionClassConstructors.ts
  tests/cases/fourslash/goToDefinitionConstructorOfClassExpression01.ts
  tests/cases/fourslash/goToDefinitionConstructorOverloads.ts
Labels: Author: Team, For Uncommitted Bug

#59663 fix test/basellines
  tests/baselines/reference/goToDefinitionClassConstructors.baseline.jsonc
  tests/cases/fourslash/goToDefinitionClassConstructors.ts
Labels: Author: Team, For Uncommitted Bug

#59563 fix(59558): Implement Interface Quick Fix generates duplicate declarations
  src/services/codefixes/helpers.ts
  tests/cases/fourslash/codeFixClassImplementInterfaceWithAmbientSignatures1.ts
  tests/cases/fourslash/codeFixClassImplementInterfaceWithAmbientSignatures2.ts
  tests/cases/fourslash/codeFixClassImplementInterfaceWithAmbientSignatures3.ts
Labels: For Milestone Bug

#59433 Add option --stopBuildOnErrors to tsbuild to get previous behavior of not building downstream projects if upstream has errors
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  src/compiler/tsbuild.ts
  src/compiler/tsbuildPublic.ts
  src/testRunner/unittests/helpers/sampleProjectReferences.ts
  src/testRunner/unittests/tsbuild/sample.ts
  src/testRunner/unittests/tsbuildWatch/programUpdates.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/tsbuild/sample1/skips-builds-downstream-projects-if-upstream-projects-have-errors-with-stopBuildOnErrors-when-test-does-not-reference-core.js
  tests/baselines/reference/tsbuild/sample1/skips-builds-downstream-projects-if-upstream-projects-have-errors-with-stopBuildOnErrors.js
  tests/baselines/reference/tsbuildWatch/programUpdates/reportErrors/when-stopBuildOnErrors-is-passed-on-command-line.js
  tests/baselines/reference/tsbuildWatch/programUpdates/skips-builds-downstream-projects-if-upstream-projects-have-errors-with-stopBuildOnErrors-when-test-does-not-reference-core.js
  tests/baselines/reference/tsbuildWatch/programUpdates/skips-builds-downstream-projects-if-upstream-projects-have-errors-with-stopBuildOnErrors.js
Labels: Author: Team, For Uncommitted Bug

#59669 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20240817191120857 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#59687 Use correct line endings in built typesMap.json
  Herebyfile.mjs
Labels: Author: Team, For Uncommitted Bug

#59686 Fix Set of one string literal bug in openExternalProject
  src/server/editorServices.ts
Labels: Author: Team, For Uncommitted Bug

#52095 Fixed an issue with contextual type for intersection properties (take 2)
  src/compiler/checker.ts
  tests/baselines/reference/contextualPropertyOfGenericFilteringMappedType.errors.txt
  tests/baselines/reference/contextualPropertyOfGenericFilteringMappedType.symbols
  tests/baselines/reference/contextualPropertyOfGenericFilteringMappedType.types
  tests/baselines/reference/contextualTypeBasedOnIntersectionWithAnyInTheMix1.symbols
  tests/baselines/reference/contextualTypeBasedOnIntersectionWithAnyInTheMix1.types
  tests/baselines/reference/contextualTypeBasedOnIntersectionWithAnyInTheMix2.symbols
  tests/baselines/reference/contextualTypeBasedOnIntersectionWithAnyInTheMix2.types
  tests/baselines/reference/contextualTypeBasedOnIntersectionWithAnyInTheMix3.symbols
  tests/baselines/reference/contextualTypeBasedOnIntersectionWithAnyInTheMix3.types
  tests/baselines/reference/contextualTypeBasedOnIntersectionWithAnyInTheMix4.errors.txt
  tests/baselines/reference/contextualTypeBasedOnIntersectionWithAnyInTheMix4.symbols
  tests/baselines/reference/contextualTypeBasedOnIntersectionWithAnyInTheMix4.types
  tests/baselines/reference/contextualTypeBasedOnIntersectionWithAnyInTheMix5.symbols
  tests/baselines/reference/contextualTypeBasedOnIntersectionWithAnyInTheMix5.types
  tests/baselines/reference/contextualTypeFunctionObjectPropertyIntersection.errors.txt
  tests/baselines/reference/contextualTypeFunctionObjectPropertyIntersection.symbols
  tests/baselines/reference/contextualTypeFunctionObjectPropertyIntersection.types
  tests/baselines/reference/contextualTypesNegatedTypeLikeConstraintInGenericMappedType1.symbols
  tests/baselines/reference/contextualTypesNegatedTypeLikeConstraintInGenericMappedType1.types
  tests/baselines/reference/contextualTypesNegatedTypeLikeConstraintInGenericMappedType2.errors.txt
  tests/baselines/reference/contextualTypesNegatedTypeLikeConstraintInGenericMappedType2.symbols
  tests/baselines/reference/contextualTypesNegatedTypeLikeConstraintInGenericMappedType2.types
  tests/baselines/reference/contextualTypesNegatedTypeLikeConstraintInGenericMappedType3.symbols
  tests/baselines/reference/contextualTypesNegatedTypeLikeConstraintInGenericMappedType3.types
  tests/baselines/reference/contextuallyTypedJsxAttribute2.symbols
  tests/baselines/reference/contextuallyTypedJsxAttribute2.types
  tests/baselines/reference/reverseMappedIntersectionInference1.symbols
  tests/baselines/reference/reverseMappedIntersectionInference1.types
  tests/baselines/reference/reverseMappedIntersectionInference2.symbols
  tests/baselines/reference/reverseMappedIntersectionInference2.types
  tests/cases/compiler/contextualPropertyOfGenericFilteringMappedType.ts
  tests/cases/compiler/contextualTypeBasedOnIntersectionWithAnyInTheMix1.ts
  tests/cases/compiler/contextualTypeBasedOnIntersectionWithAnyInTheMix2.ts
  tests/cases/compiler/contextualTypeBasedOnIntersectionWithAnyInTheMix3.ts
  tests/cases/compiler/contextualTypeBasedOnIntersectionWithAnyInTheMix4.ts
  tests/cases/compiler/contextualTypeBasedOnIntersectionWithAnyInTheMix5.ts
  tests/cases/compiler/contextualTypeFunctionObjectPropertyIntersection.ts
  tests/cases/compiler/contextualTypesNegatedTypeLikeConstraintInGenericMappedType1.ts
  tests/cases/compiler/contextualTypesNegatedTypeLikeConstraintInGenericMappedType2.ts
  tests/cases/compiler/contextualTypesNegatedTypeLikeConstraintInGenericMappedType3.ts
  tests/cases/compiler/contextuallyTypedJsxAttribute2.tsx
  tests/cases/compiler/reverseMappedIntersectionInference1.ts
  tests/cases/compiler/reverseMappedIntersectionInference2.ts
Labels: For Milestone Bug, For Backlog Bug

#59693 Bump version to 5.7
  package-lock.json
  package.json
  src/compiler/corePublic.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#59689 Add fast path exits if we are retaining all configured projects
  src/server/editorServices.ts
Labels: Author: Team, For Milestone Bug

#55887 error on variables that are used but never initialized
  src/compiler/checker.ts
  src/compiler/transformers/classFields.ts
  src/compiler/transformers/es2015.ts
  src/compiler/transformers/es2017.ts
  src/compiler/transformers/es2018.ts
  src/compiler/transformers/ts.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  tests/baselines/reference/findAllRefsObjectBindingElementPropertyName06.baseline.jsonc
  tests/baselines/reference/narrowingPastLastAssignment.errors.txt
  tests/baselines/reference/narrowingPastLastAssignment.symbols
  tests/baselines/reference/narrowingPastLastAssignment.types
  tests/baselines/reference/typeGuardsAsAssertions.errors.txt
  tests/baselines/reference/unusedLocalsInMethod4.errors.txt
  tests/baselines/reference/unusedLocalsInMethod4.js
  tests/baselines/reference/unusedLocalsInMethod4.symbols
  tests/baselines/reference/unusedLocalsInMethod4.types
  tests/cases/compiler/narrowingPastLastAssignment.ts
  tests/cases/compiler/unusedLocalsInMethod4.ts
Labels: For Backlog Bug

#59708 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20240821102429476 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#59702 Simplify handling of `node:`-prefixed modules in auto-imports
  src/compiler/program.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/jsTyping/jsTyping.ts
  src/services/codefixes/fixCannotFindModule.ts
  src/services/codefixes/importFixes.ts
  src/services/completions.ts
  src/services/exportInfoMap.ts
  src/services/utilities.ts
  src/testRunner/unittests/tsserver/duplicatePackages.ts
  src/testRunner/unittests/tsserver/typingsInstaller.ts
  tests/baselines/reference/tsserver/typingsInstaller/discover-typings-should-return-node-for-core-modules.js
  tests/cases/fourslash/completionsImport_uriStyleNodeCoreModules1.ts
  tests/cases/fourslash/completionsImport_uriStyleNodeCoreModules3.ts
  tests/cases/fourslash/importNameCodeFix_uriStyleNodeCoreModules2.ts
  tests/cases/fourslash/importNameCodeFix_uriStyleNodeCoreModules3.ts
Labels: Author: Team, For Uncommitted Bug

#59714 Add missing test case for assertion functions with `PropertySignature` declarations
  tests/baselines/reference/assertionTypePredicates1.errors.txt
  tests/baselines/reference/assertionTypePredicates1.js
  tests/baselines/reference/assertionTypePredicates1.symbols
  tests/baselines/reference/assertionTypePredicates1.types
  tests/cases/conformance/controlFlow/assertionTypePredicates1.ts
Labels: For Uncommitted Bug

#59722 Drop tsserverlibrary.d.ts from baselines, simplify APILibCheck
  src/testRunner/unittests/publicApi.ts
  tests/baselines/reference/APILibCheck.js
  tests/baselines/reference/api/tsserverlibrary.d.ts
  tests/cases/compiler/APILibCheck.ts
Labels: Author: Team, For Uncommitted Bug

#59694 devcontainer.json Updates
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/dependabot.yml
Labels: Author: Team, For Uncommitted Bug

#59670 fix(59649): ts Move to a new file doesn't respect importModuleSpecifier setting
  src/compiler/moduleSpecifiers.ts
  src/services/codefixes/importFixes.ts
  tests/cases/fourslash/moveToNewFile_nonRelativePaths.ts
Labels: For Milestone Bug

#59711 Fix error message for type-only import of ES module from CJS
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/harness/fourslashImpl.ts
  src/services/_namespaces/ts.codefix.ts
  src/services/codefixes/addMissingResolutionModeImportAttribute.ts
  tests/baselines/reference/tsbuildWatch/moduleResolution/resolves-specifier-in-output-declaration-file-from-referenced-project-correctly-with-cts-and-mts-extensions.js
  tests/baselines/reference/typeOnlyESMImportFromCJS.errors.txt
  tests/baselines/reference/typeOnlyESMImportFromCJS.js
  tests/baselines/reference/typeOnlyESMImportFromCJS.symbols
  tests/baselines/reference/typeOnlyESMImportFromCJS.types
  tests/cases/conformance/externalModules/typeOnly/typeOnlyESMImportFromCJS.ts
  tests/cases/fourslash/codeFixMissingResolutionModeImportAttribute.ts
Labels: Author: Team, For Uncommitted Bug

#59757 Switch from prettier to pretty_yaml for yaml formatting
  .dprint.jsonc
Labels: Author: Team, For Uncommitted Bug

#58818 refactor: improve string export name completions
  src/services/completions.ts
  tests/cases/fourslash/completionsImportOrExportSpecifier.ts
Labels: For Uncommitted Bug

#59761 `this` can be nullish
  src/compiler/checker.ts
  tests/baselines/reference/predicateSemantics.errors.txt
  tests/baselines/reference/predicateSemantics.js
  tests/baselines/reference/predicateSemantics.symbols
  tests/baselines/reference/predicateSemantics.types
  tests/cases/compiler/predicateSemantics.ts
Labels: Author: Team, For Milestone Bug

#59783 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20240828095615951 to main
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#59048 Optimize path mapping lookups
  src/compiler/commandLineParser.ts
  src/compiler/core.ts
  src/compiler/moduleNameResolver.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#59795 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20240829095357792 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#59774 Don't generalize when assigment target is never (fix: #41707)
  src/compiler/checker.ts
  tests/baselines/reference/controlFlowArrayErrors.errors.txt
  tests/baselines/reference/dependentDestructuredVariables.errors.txt
  tests/baselines/reference/errorOnFunctionReturnType.errors.txt
  tests/baselines/reference/exhaustiveSwitchCheckCircularity.errors.txt
  tests/baselines/reference/extractInferenceImprovement.errors.txt
  tests/baselines/reference/functionCallOnConstrainedTypeVariable.errors.txt
  tests/baselines/reference/keyofAndIndexedAccess2.errors.txt
  tests/baselines/reference/logicalAssignment6(target=es2015).errors.txt
  tests/baselines/reference/logicalAssignment6(target=es2020).errors.txt
  tests/baselines/reference/logicalAssignment6(target=es2021).errors.txt
  tests/baselines/reference/logicalAssignment6(target=esnext).errors.txt
  tests/baselines/reference/logicalAssignment7(target=es2015).errors.txt
  tests/baselines/reference/logicalAssignment7(target=es2020).errors.txt
  tests/baselines/reference/logicalAssignment7(target=es2021).errors.txt
  tests/baselines/reference/logicalAssignment7(target=esnext).errors.txt
  tests/baselines/reference/narrowingUnionToNeverAssigment.errors.txt
  tests/baselines/reference/narrowingUnionToNeverAssigment.js
  tests/baselines/reference/narrowingUnionToNeverAssigment.symbols
  tests/baselines/reference/narrowingUnionToNeverAssigment.types
  tests/baselines/reference/neverTypeErrors1.errors.txt
  tests/baselines/reference/neverTypeErrors2.errors.txt
  tests/baselines/reference/nonPrimitiveUnionIntersection.errors.txt
  tests/baselines/reference/tsxUnionElementType1.errors.txt
  tests/baselines/reference/tsxUnionElementType4.errors.txt
  tests/baselines/reference/unionTypeCallSignatures.errors.txt
  tests/baselines/reference/unionTypeConstructSignatures.errors.txt
  tests/baselines/reference/unionTypeInference.errors.txt
  tests/baselines/reference/unknownControlFlow.errors.txt
  tests/cases/compiler/narrowingUnionToNeverAssigment.ts
Labels: For Backlog Bug

#59801 Fixed formatting to fix the CI on `main`
  src/compiler/checker.ts
Labels: For Uncommitted Bug

#59810 Update deps, dprint plugins
  .dprint.jsonc
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug
