Repository microsoft/TypeScript, pull requests merged in 2024-04, with the labels that each got.

#58004 Update getTimezoneOffset JSDoc
  src/lib/es5.d.ts
  tests/baselines/reference/1.0lib-noErrors.js
  tests/baselines/reference/1.0lib-noErrors.symbols
  tests/baselines/reference/1.0lib-noErrors.types
  tests/cases/conformance/decorators/1.0lib-noErrors.ts
  tests/lib/lib.d.ts
Labels: For Backlog Bug

#57029 Take into account peerDependency versions when calculating packageId
  src/compiler/diagnosticMessages.json
  src/compiler/moduleNameResolver.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/testRunner/unittests/tsc/moduleResolution.ts
  tests/baselines/reference/allowJsCrossMonorepoPackage.trace.json
  tests/baselines/reference/bundlerConditionsExcludesNode(module=esnext).trace.json
  tests/baselines/reference/bundlerConditionsExcludesNode(module=preserve).trace.json
  tests/baselines/reference/bundlerNodeModules1(module=esnext).trace.json
  tests/baselines/reference/bundlerNodeModules1(module=preserve).trace.json
  tests/baselines/reference/conditionalExportsResolutionFallback(moduleresolution=bundler).trace.json
  tests/baselines/reference/conditionalExportsResolutionFallback(moduleresolution=node16).trace.json
  tests/baselines/reference/conditionalExportsResolutionFallback(moduleresolution=nodenext).trace.json
  tests/baselines/reference/customConditions(resolvepackagejsonexports=false).trace.json
  tests/baselines/reference/customConditions(resolvepackagejsonexports=true).trace.json
  tests/baselines/reference/duplicatePackage_relativeImportWithinPackage.trace.json
  tests/baselines/reference/duplicatePackage_relativeImportWithinPackage_scoped.trace.json
  tests/baselines/reference/moduleResolutionAsTypeReferenceDirective.trace.json
  tests/baselines/reference/moduleResolutionAsTypeReferenceDirectiveAmbient.trace.json
  tests/baselines/reference/moduleResolutionPackageIdWithRelativeAndAbsolutePath.trace.json
  tests/baselines/reference/moduleResolution_packageJson_yesAtPackageRoot.trace.json
  tests/baselines/reference/moduleResolution_packageJson_yesAtPackageRoot_fakeScopedPackage.trace.json
  tests/baselines/reference/moduleResolution_packageJson_yesAtPackageRoot_mainFieldInSubDirectory.trace.json
  tests/baselines/reference/node10AlternateResult_noResolution.trace.json
  tests/baselines/reference/node10Alternateresult_noTypes.trace.json
  tests/baselines/reference/node10IsNode_node.trace.json
  tests/baselines/reference/node10IsNode_node10.trace.json
  tests/baselines/reference/nodeModulesExportsBlocksTypesVersions(module=node16).trace.json
  tests/baselines/reference/nodeModulesExportsBlocksTypesVersions(module=nodenext).trace.json
  tests/baselines/reference/reactJsxReactResolvedNodeNext.trace.json
  tests/baselines/reference/reactJsxReactResolvedNodeNextEsm.trace.json
  tests/baselines/reference/resolvesWithoutExportsDiagnostic1(moduleresolution=bundler).trace.json
  tests/baselines/reference/resolvesWithoutExportsDiagnostic1(moduleresolution=node16).trace.json
  tests/baselines/reference/selfNameModuleAugmentation.trace.json
  tests/baselines/reference/tsbuild/moduleResolution/resolves-specifier-in-output-declaration-file-from-referenced-project-correctly-with-preserveSymlinks.js
  tests/baselines/reference/tsbuild/moduleResolution/resolves-specifier-in-output-declaration-file-from-referenced-project-correctly.js
  tests/baselines/reference/tsbuildWatch/moduleResolution/build-mode-watches-for-changes-to-package-json-main-fields.js
  tests/baselines/reference/tsbuildWatch/moduleResolution/resolves-specifier-in-output-declaration-file-from-referenced-project-correctly-with-cts-and-mts-extensions.js
  tests/baselines/reference/tsc/declarationEmit/when-same-version-is-referenced-through-source-and-another-symlinked-package-moduleCaseChange.js
  tests/baselines/reference/tsc/declarationEmit/when-same-version-is-referenced-through-source-and-another-symlinked-package-with-indirect-link-moduleCaseChange.js
  tests/baselines/reference/tsc/declarationEmit/when-same-version-is-referenced-through-source-and-another-symlinked-package-with-indirect-link.js
  tests/baselines/reference/tsc/declarationEmit/when-same-version-is-referenced-through-source-and-another-symlinked-package.js
  tests/baselines/reference/tsc/moduleResolution/alternateResult.js
  tests/baselines/reference/tsc/moduleResolution/pnpm-style-layout.js
  tests/baselines/reference/tscWatch/forceConsistentCasingInFileNames/package-json-is-looked-up-for-file.js
  tests/baselines/reference/tscWatch/forceConsistentCasingInFileNames/with-nodeNext-resolution.js
  tests/baselines/reference/tscWatch/moduleResolution/alternateResult.js
  tests/baselines/reference/tscWatch/moduleResolution/module-resolutions-from-file-are-partially-used.js
  tests/baselines/reference/tscWatch/moduleResolution/module-resolutions-from-files-with-partially-used-import-attributes.js
  tests/baselines/reference/tscWatch/moduleResolution/type-reference-resolutions-reuse.js
  tests/baselines/reference/tscWatch/moduleResolution/watches-for-changes-to-package-json-main-fields.js
  tests/baselines/reference/tsserver/moduleResolution/alternateResult.js
  tests/baselines/reference/tsserver/moduleResolution/using-referenced-project-built.js
  tests/baselines/reference/tsserver/moduleResolution/using-referenced-project.js
  tests/baselines/reference/typesVersions.ambientModules.trace.json
  tests/baselines/reference/typesVersions.multiFile.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.ambient.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFile.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFileBackReferenceToSelf.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFileBackReferenceToUnmapped.trace.json
Labels: Author: Team, For Backlog Bug

#57673 Fixed excess and common property checks with `NoInfer`
  src/compiler/checker.ts
  tests/baselines/reference/noInferCommonPropertyCheck1.errors.txt
  tests/baselines/reference/noInferCommonPropertyCheck1.symbols
  tests/baselines/reference/noInferCommonPropertyCheck1.types
  tests/baselines/reference/noInferUnionExcessPropertyCheck1.errors.txt
  tests/baselines/reference/noInferUnionExcessPropertyCheck1.symbols
  tests/baselines/reference/noInferUnionExcessPropertyCheck1.types
  tests/cases/compiler/noInferCommonPropertyCheck1.ts
  tests/cases/compiler/noInferUnionExcessPropertyCheck1.ts
Labels: For Uncommitted Bug

#58037 Fix baselines from recent merge
  tests/baselines/reference/noInferCommonPropertyCheck1.types
  tests/baselines/reference/noInferUnionExcessPropertyCheck1.types
Labels: Author: Team, For Uncommitted Bug

#57952 Fixed type predicate inference for discriminated union parameters
  src/compiler/checker.ts
  tests/baselines/reference/inferTypePredicates.errors.txt
  tests/baselines/reference/inferTypePredicates.js
  tests/baselines/reference/inferTypePredicates.symbols
  tests/baselines/reference/inferTypePredicates.types
  tests/cases/compiler/inferTypePredicates.ts
Labels: For Uncommitted Bug

#58039 fix51686: don't indent mapped types on new lines
  src/services/formatting/smartIndenter.ts
  tests/cases/fourslash/formatMultilineTypesWithMapped.ts
Labels: Author: Team, For Milestone Bug

#58036 Remove FlowNodes and FlowFlags from public API
  src/compiler/types.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#58059 Make unused variable rule a warning, error on warnings for CI
  .eslintrc.json
  Herebyfile.mjs
Labels: Author: Team, For Uncommitted Bug

#58058 Sort imports with dprint instead of eslint
  .dprint.jsonc
  .eslintrc.json
  .vscode/settings.template.json
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#58066 Adjust the node builder compatible reference check to handle aliased tuples
  src/compiler/checker.ts
  tests/baselines/reference/contextualTypeTupleEnd.types
  tests/baselines/reference/destructuringParameterDeclaration3ES5.types
  tests/baselines/reference/destructuringParameterDeclaration3ES5iterable.types
  tests/baselines/reference/destructuringParameterDeclaration3ES6.types
  tests/baselines/reference/directDependenceBetweenTypeAliases.types
  tests/baselines/reference/inferFromNestedSameShapeTuple.types
  tests/baselines/reference/jsdocTemplateTagDefault.js
  tests/baselines/reference/mapOnTupleTypes02.types
  tests/baselines/reference/objectTypeWithStringAndNumberIndexSignatureToAny.types
  tests/baselines/reference/optionalTupleElements1.types
  tests/baselines/reference/partiallyNamedTuples.types
  tests/baselines/reference/recursiveConditionalTypes.types
  tests/baselines/reference/recursiveMappedTypes.types
  tests/baselines/reference/recursiveTypeReferences1.types
  tests/baselines/reference/recursiveTypeReferences2.js
  tests/baselines/reference/sourceMapValidationDestructuringParametertArrayBindingPattern.types
  tests/baselines/reference/sourceMapValidationDestructuringParametertArrayBindingPattern2.types
  tests/baselines/reference/sourceMapValidationDestructuringParametertArrayBindingPatternDefaultValues.types
  tests/baselines/reference/sourceMapValidationDestructuringParametertArrayBindingPatternDefaultValues2.types
  tests/baselines/reference/typeAliases.types
  tests/baselines/reference/typePredicateStructuralMatch.types
  tests/baselines/reference/unionsOfTupleTypes1.types
  tests/baselines/reference/variadicTuples1.types
Labels: Author: Team, For Uncommitted Bug

#57769 fix(57761): Invalid verbatimModuleSyntax quick fix offered when also reexporting a value
  src/compiler/checker.ts
  src/compiler/types.ts
  src/services/codefixes/convertToTypeOnlyImport.ts
  tests/cases/fourslash/codeFixConvertToTypeOnlyImport10.ts
  tests/cases/fourslash/codeFixConvertToTypeOnlyImport11.ts
  tests/cases/fourslash/codeFixConvertToTypeOnlyImport12.ts
  tests/cases/fourslash/codeFixConvertToTypeOnlyImport9.ts
Labels: For Backlog Bug

#58069 Don't clear _children on NodeArrays
  src/compiler/parser.ts
Labels: Author: Team, For Uncommitted Bug

#58067 Skip visits to child nodes of entity names in visitExistingNodeTreeSymbols
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug

#57966 Use evaluator for isolatedModules enum restrictions
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/transformers/ts.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  tests/baselines/reference/computedEnumMemberSyntacticallyString(isolatedmodules=false).errors.txt
  tests/baselines/reference/computedEnumMemberSyntacticallyString(isolatedmodules=false).js
  tests/baselines/reference/computedEnumMemberSyntacticallyString(isolatedmodules=true).errors.txt
  tests/baselines/reference/computedEnumMemberSyntacticallyString(isolatedmodules=true).js
  tests/baselines/reference/computedEnumMemberSyntacticallyString2(isolatedmodules=false).errors.txt
  tests/baselines/reference/computedEnumMemberSyntacticallyString2(isolatedmodules=false).js
  tests/baselines/reference/computedEnumMemberSyntacticallyString2(isolatedmodules=true).errors.txt
  tests/baselines/reference/computedEnumMemberSyntacticallyString2(isolatedmodules=true).js
  tests/baselines/reference/enumNoInitializerFollowsNonLiteralInitializer.errors.txt
  tests/baselines/reference/enumNoInitializerFollowsNonLiteralInitializer.js
  tests/cases/compiler/computedEnumMemberSyntacticallyString.ts
  tests/cases/compiler/computedEnumMemberSyntacticallyString2.ts
  tests/cases/compiler/enumNoInitializerFollowsNonLiteralInitializer.ts
Labels: Author: Team, For Uncommitted Bug

#58075 Always consider parameters in scope visible to node builder
  src/compiler/checker.ts
  tests/baselines/reference/conditionallyDuplicateOverloadsCausedByOverloadResolution.types
  tests/baselines/reference/renamingDestructuredPropertyInFunctionType.js
  tests/baselines/reference/renamingDestructuredPropertyInFunctionType.types
  tests/baselines/reference/subtypingWithCallSignatures.types
  tests/baselines/reference/subtypingWithCallSignatures3.types
  tests/baselines/reference/subtypingWithConstructSignatures.types
  tests/baselines/reference/subtypingWithConstructSignatures3.types
Labels: Author: Team, For Uncommitted Bug

#57110 Fixed crashes when looking up symbols of jsdoc nodes in TS files
  src/compiler/checker.ts
  src/services/services.ts
  tests/baselines/reference/findReferencesBindingPatternInJsdocNoCrash1.baseline.jsonc
  tests/baselines/reference/findReferencesBindingPatternInJsdocNoCrash2.baseline.jsonc
  tests/baselines/reference/findReferencesSeeTagInTs.baseline.jsonc
  tests/cases/fourslash/findReferencesBindingPatternInJsdocNoCrash1.ts
  tests/cases/fourslash/findReferencesBindingPatternInJsdocNoCrash2.ts
  tests/cases/fourslash/findReferencesSeeTagInTs.ts
  tests/cases/fourslash/quickInfoBindingPatternInJsdocNoCrash1.ts
  tests/cases/fourslash/quickInfoInJsdocInTsFile1.ts
Labels: For Backlog Bug

#58079 Special case check for this identifiers to skip exhaustive scope traversal
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug

#58057 Export executeCommandLine from public API (internal for now)
  src/compiler/_namespaces/ts.ts
  src/compiler/executeCommandLine.ts
  src/executeCommandLine/_namespaces/ts.ts
  src/executeCommandLine/tsconfig.json
  src/testRunner/_namespaces/ts.ts
  src/testRunner/tsconfig.json
  src/tsc/_namespaces/ts.ts
  src/tsc/tsconfig.json
  src/tsconfig.json
Labels: Author: Team, For Uncommitted Bug

#58013 Omit effects-free conditional constructs from control flow graph
  src/compiler/binder.ts
Labels: Author: Team, For Uncommitted Bug

#57977 Monomorphic flow nodes
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/debug.ts
  src/compiler/types.ts
Labels: Author: Team, For Uncommitted Bug

#57595 Accept decimal strings in Intl.NumberFormat
  src/lib/es2023.intl.d.ts
  tests/baselines/reference/intlNumberFormatES2023.js
  tests/baselines/reference/intlNumberFormatES2023.symbols
  tests/baselines/reference/intlNumberFormatES2023.types
  tests/cases/conformance/es2023/intlNumberFormatES2023.ts
Labels: For Uncommitted Bug

#57167 Fixed braceless type tags with types starting with an open parenthesis
  src/compiler/scanner.ts
  src/compiler/types.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/jsdocBracelessTypeTag1.errors.txt
  tests/baselines/reference/jsdocBracelessTypeTag1.symbols
  tests/baselines/reference/jsdocBracelessTypeTag1.types
  tests/cases/compiler/jsdocBracelessTypeTag1.ts
Labels: For Backlog Bug

#58102 Always set node-version for setup-node
  .github/workflows/accept-baselines-fix-lints.yaml
  .github/workflows/insiders.yaml
  .github/workflows/lkg.yml
  .github/workflows/new-release-branch.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release-branch-artifact.yaml
  .github/workflows/set-version.yaml
  .github/workflows/sync-branch.yaml
  .github/workflows/twoslash-repros.yaml
Labels: Author: Team, For Uncommitted Bug

#58117 release-5.4: Always set node-version for setup-node
  .github/workflows/accept-baselines-fix-lints.yaml
  .github/workflows/new-release-branch.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release-branch-artifact.yaml
  .github/workflows/rich-navigation.yml
  .github/workflows/set-version.yaml
  .github/workflows/sync-branch.yaml
  .github/workflows/twoslash-repros.yaml
Labels: Author: Team, For Uncommitted Bug

#57341 check return type of this type predicates
  src/compiler/checker.ts
  src/server/scriptVersionCache.ts
  tests/baselines/reference/implementArrayInterface.errors.txt
  tests/baselines/reference/implementArrayInterface.types
  tests/baselines/reference/typePredicateInherit.errors.txt
  tests/baselines/reference/typePredicateInherit.js
  tests/baselines/reference/typePredicateInherit.symbols
  tests/baselines/reference/typePredicateInherit.types
  tests/cases/compiler/typePredicateInherit.ts
Labels: For Backlog Bug

#58120 Send configFileDiag event when presence of errors change on project.update
  src/server/editorServices.ts
  src/server/project.ts
  src/testRunner/unittests/tsserver/projectErrors.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/tsserver/autoImportProvider/Does-not-create-auto-import-providers-upon-opening-projects-for-find-all-references.js
  tests/baselines/reference/tsserver/compileOnSave/emit-in-project-with-dts-emit.js
  tests/baselines/reference/tsserver/compileOnSave/emit-in-project-with-module-with-dts-emit.js
  tests/baselines/reference/tsserver/compileOnSave/emit-in-project-with-module.js
  tests/baselines/reference/tsserver/compileOnSave/emit-in-project.js
  tests/baselines/reference/tsserver/declarationFileMaps/findAllReferences.js
  tests/baselines/reference/tsserver/declarationFileMaps/findAllReferencesFull.js
  tests/baselines/reference/tsserver/declarationFileMaps/renameLocations.js
  tests/baselines/reference/tsserver/declarationFileMaps/renameLocationsFull.js
  tests/baselines/reference/tsserver/navTo/should-de-duplicate-symbols-when-searching-all-projects.js
  tests/baselines/reference/tsserver/projectErrors/file-rename-on-wsl2.js
  tests/baselines/reference/tsserver/projectReferenceCompileOnSave/save-on-dependency-and-change-to-dependency.js
  tests/baselines/reference/tsserver/projectReferenceCompileOnSave/save-on-dependency-and-change-to-usage.js
  tests/baselines/reference/tsserver/projectReferenceCompileOnSave/save-on-dependency-and-local-change-to-dependency.js
  tests/baselines/reference/tsserver/projectReferenceCompileOnSave/save-on-dependency-and-local-change-to-usage.js
  tests/baselines/reference/tsserver/projectReferenceCompileOnSave/save-on-usage-and-change-to-dependency.js
  tests/baselines/reference/tsserver/projectReferenceCompileOnSave/save-on-usage-and-change-to-usage.js
  tests/baselines/reference/tsserver/projectReferenceCompileOnSave/save-on-usage-and-local-change-to-dependency.js
  tests/baselines/reference/tsserver/projectReferenceCompileOnSave/save-on-usage-and-local-change-to-usage.js
  tests/baselines/reference/tsserver/projectReferenceCompileOnSave/when-dependency-project-is-not-open-and-save-on-dependency-and-change-to-usage.js
  tests/baselines/reference/tsserver/projectReferenceCompileOnSave/when-dependency-project-is-not-open-and-save-on-dependency-and-local-change-to-usage.js
  tests/baselines/reference/tsserver/projectReferenceCompileOnSave/when-dependency-project-is-not-open-and-save-on-usage-and-change-to-usage.js
  tests/baselines/reference/tsserver/projectReferenceCompileOnSave/when-dependency-project-is-not-open-and-save-on-usage-and-local-change-to-usage.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-not-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-disabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-not-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-missing.js
  tests/baselines/reference/tsserver/projectReferences/find-refs-to-decl-in-other-proj-when-proj-is-not-loaded-and-refd-proj-loading-is-enabled-and-proj-ref-redirects-are-enabled-and-a-decl-map-is-present.js
  tests/baselines/reference/tsserver/projects/handles-delayed-directory-watch-invoke-on-file-creation.js
Labels: Author: Team, For Milestone Bug

#58098 Fix constraints of nested homomorphic mapped type instantiations
  src/compiler/checker.ts
  tests/baselines/reference/deepComparisons.types
  tests/baselines/reference/homomorphicMappedTypeNesting.symbols
  tests/baselines/reference/homomorphicMappedTypeNesting.types
  tests/cases/compiler/homomorphicMappedTypeNesting.ts
Labels: Author: Team, For Uncommitted Bug

#58083 Don't propagate partial union/intersection properties between caches
  src/compiler/checker.ts
  tests/baselines/reference/checkJsxChildrenCanBeTupleType.types
  tests/baselines/reference/infiniteConstraints.types
  tests/baselines/reference/styledComponentsInstantiaionLimitNotReached.types
  tests/baselines/reference/tsxReactEmitSpreadAttribute(target=esnext).types
  tests/cases/fourslash/partialUnionPropertyCacheInconsistentErrors.ts
Labels: Author: Team, For Milestone Bug

#58123 Do not populate exports pattern keys if more than one `*` exists
  src/compiler/moduleNameResolver.ts
  tests/baselines/reference/nodeModulesExportsDoubleAsterisk.errors.txt
  tests/cases/conformance/node/nodeModulesExportsDoubleAsterisk.ts
Labels: Author: Team, For Milestone Bug

#58124 Fix self tail call return type inference in assigned anonymous functions
  src/compiler/checker.ts
  tests/baselines/reference/implicitAnyFromCircularInference.errors.txt
  tests/baselines/reference/implicitAnyFromCircularInference.types
  tests/baselines/reference/simpleRecursionWithBaseCase3.symbols
  tests/baselines/reference/simpleRecursionWithBaseCase3.types
  tests/baselines/reference/simpleRecursionWithBaseCase4.symbols
  tests/baselines/reference/simpleRecursionWithBaseCase4.types
  tests/cases/compiler/simpleRecursionWithBaseCase3.ts
  tests/cases/compiler/simpleRecursionWithBaseCase4.ts
Labels: Author: Team, For Milestone Bug

#58140 Add es2023 target
  src/compiler/commandLineParser.ts
  src/compiler/types.ts
  src/compiler/utilitiesPublic.ts
  src/server/protocol.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/callChainWithSuper(target=es2023).js
  tests/baselines/reference/config/commandLineParsing/parseCommandLine/Parse empty options of --target.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert incorrect option of target to compiler-options with json api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert incorrect option of target to compiler-options with jsonSourceFile api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert tsconfig options when there are multiple invalid strings with jsonSourceFile api.js
  tests/baselines/reference/tsc/runWithoutArgs/does-not-add-color-when-NO_COLOR-is-set.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped-when-host-can't-provide-terminal-width.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
Labels: Author: Team, For Milestone Bug

#58165 Add missing recursive vistor on copied `import` type nodes
  src/compiler/checker.ts
  tests/baselines/reference/callbackCrossModule.types
  tests/baselines/reference/declarationEmitCrossFileCopiedGeneratedImportType.js
  tests/baselines/reference/declarationEmitCrossFileCopiedGeneratedImportType.symbols
  tests/baselines/reference/declarationEmitCrossFileCopiedGeneratedImportType.types
  tests/baselines/reference/jsDeclarationsClassImplementsGenericsSerialization.js
  tests/baselines/reference/jsDeclarationsParameterTagReusesInputNodeInEmit2.js
  tests/baselines/reference/jsDeclarationsTypedefPropertyAndExportAssignment.js
  tests/baselines/reference/jsDeclarationsUniqueSymbolUsage.js
  tests/baselines/reference/jsDeclarationsUniqueSymbolUsage.types
  tests/baselines/reference/jsdocThisType.types
  tests/baselines/reference/moduleExportAssignment7.types
  tests/baselines/reference/privateNamesUnique-2.types
  tests/baselines/reference/spuriousCircularityOnTypeImport.types
  tests/cases/compiler/declarationEmitCrossFileCopiedGeneratedImportType.ts
Labels: Author: Team, For Milestone Bug

#58169 Don’t emit __esModule on CJS files that didn’t use ESM syntax
  src/compiler/transformers/module/module.ts
  tests/baselines/reference/nodeModulesAllowJsExportAssignment(module=node16).js
  tests/baselines/reference/nodeModulesAllowJsExportAssignment(module=nodenext).js
  tests/baselines/reference/nodeModulesCJSEmit1.errors.txt
  tests/baselines/reference/nodeModulesCJSEmit1.js
  tests/cases/conformance/node/nodeModulesCJSEmit1.ts
Labels: Author: Team, For Milestone Bug

#58168 Use better context scope for class constructor implementation signatures
  src/compiler/checker.ts
  tests/baselines/reference/inferenceOuterResultNotIncorrectlyInstantiatedWithInnerResult.js
  tests/baselines/reference/inferenceOuterResultNotIncorrectlyInstantiatedWithInnerResult.symbols
  tests/baselines/reference/inferenceOuterResultNotIncorrectlyInstantiatedWithInnerResult.types
  tests/cases/compiler/inferenceOuterResultNotIncorrectlyInstantiatedWithInnerResult.ts
Labels: Author: Team, For Milestone Bug

#58171 fix(58146): enum quick info can display non ascii strings
  src/compiler/utilities.ts
  tests/cases/fourslash/quickInfoEnumMembersAcceptNonAsciiStrings.ts
Labels: For Backlog Bug

#58183 fix(58151): JSDoc tags get lost when inheriting from a grandparent class
  src/services/services.ts
  tests/baselines/reference/quickInfoJsDocTags16.baseline
  tests/cases/fourslash/quickInfoJsDocTags16.ts
Labels: For Backlog Bug

#58172 Fix declaration emit of divergent accessors in JS classes
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitClassAccessorsJs1.js
  tests/baselines/reference/declarationEmitClassAccessorsJs1.symbols
  tests/baselines/reference/declarationEmitClassAccessorsJs1.types
  tests/cases/compiler/declarationEmitClassAccessorsJs1.ts
Labels: For Uncommitted Bug

#57837 Avoid infinite recursion with `inferReverseMappedType`
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypeRecursiveInference.errors.txt
  tests/baselines/reference/mappedTypeRecursiveInference.types
  tests/baselines/reference/reverseMappedTypeRecursiveInference.js
  tests/baselines/reference/reverseMappedTypeRecursiveInference.symbols
  tests/baselines/reference/reverseMappedTypeRecursiveInference.types
  tests/cases/compiler/reverseMappedTypeRecursiveInference.ts
Labels: Author: Team, For Milestone Bug

#57467 Propagate object flags related to object and array literals onto `module.exports` types
  src/compiler/checker.ts
  tests/baselines/reference/moduleExportsTypeNoExcessPropertyCheckFromContainedLiteral.symbols
  tests/baselines/reference/moduleExportsTypeNoExcessPropertyCheckFromContainedLiteral.types
  tests/baselines/reference/typedefCrossModule2.symbols
  tests/baselines/reference/typedefCrossModule2.types
  tests/cases/compiler/moduleExportsTypeNoExcessPropertyCheckFromContainedLiteral.ts
Labels: For Backlog Bug

#58227 Error on replacement character only in top-level scanning
  src/compiler/scanner.ts
  src/compiler/types.ts
  tests/baselines/reference/TransportStream.errors.txt
  tests/baselines/reference/TransportStream.js
  tests/baselines/reference/TransportStream.types
  tests/baselines/reference/parseReplacementCharacter.js
  tests/baselines/reference/parseReplacementCharacter.symbols
  tests/baselines/reference/parseReplacementCharacter.types
  tests/cases/compiler/parseReplacementCharacter.ts
Labels: Author: Team, For Backlog Bug

#58229 Add lint error for declarations marked internal, but unexported
  scripts/eslint/rules/jsdoc-format.cjs
  src/compiler/scanner.ts
  src/services/services.ts
Labels: Author: Team, For Uncommitted Bug

#58228 Remove deprecated originalKeywordKind and isInJSDocNamespace
  src/deprecatedCompat/5.0/identifierProperties.ts
  src/deprecatedCompat/_namespaces/ts.ts
  src/harness/harnessUtils.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#58095 Use built-in no-restricted-syntax to ban null instead of plugin, ban null type too
  .eslintrc.json
  package-lock.json
  package.json
  scripts/configurePrerelease.mjs
  scripts/eslint/rules/argument-trivia.cjs
  scripts/eslint/rules/only-arrow-functions.cjs
  src/compiler/commandLineParser.ts
  src/compiler/core.ts
  src/compiler/debug.ts
  src/compiler/executeCommandLine.ts
  src/compiler/moduleNameResolver.ts
  src/compiler/moduleSpecifiers.ts
  src/compiler/parser.ts
  src/compiler/program.ts
  src/compiler/sourcemap.ts
  src/compiler/sys.ts
  src/compiler/tracing.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/harness/collectionsImpl.ts
  src/harness/documentsUtil.ts
  src/harness/evaluatorImpl.ts
  src/harness/harnessIO.ts
  src/harness/harnessLanguageService.ts
  src/harness/sourceMapRecorder.ts
  src/harness/util.ts
  src/harness/vfsUtil.ts
  src/services/formatting/formatting.ts
  src/services/formatting/smartIndenter.ts
  src/services/outliningElementsCollector.ts
  src/services/services.ts
  src/services/stringCompletions.ts
  src/testRunner/compilerRunner.ts
  src/testRunner/parallel/host.ts
  src/testRunner/projectsRunner.ts
  src/testRunner/unittests/config/configurationExtension.ts
  src/testRunner/unittests/config/showConfig.ts
  src/testRunner/unittests/evaluation/esDecorators.ts
  src/testRunner/unittests/helpers/tsc.ts
  src/testRunner/unittests/moduleResolution.ts
  src/testRunner/unittests/services/convertToAsyncFunction.ts
  src/testRunner/unittests/services/transpile.ts
  src/testRunner/unittests/sys/symlinkWatching.ts
  src/testRunner/unittests/tsserver/session.ts
  src/tsserver/nodeServer.ts
Labels: Author: Team, For Uncommitted Bug

#58087 Move incremental state to WeakSets
  src/compiler/parser.ts
Labels: Author: Team, For Uncommitted Bug

#58242 Try sorting and deduplicating events before comparing.
  src/testRunner/unittests/sys/symlinkWatching.ts
Labels: Author: Team, For Uncommitted Bug

#57948 Correct the type of return value of FinalizationRegistry.unregister
  src/lib/es2021.weakref.d.ts
  tests/baselines/reference/acceptSymbolAsWeakType.types
  tests/baselines/reference/dissallowSymbolAsWeakType.types
  tests/baselines/reference/esNextWeakRefs_IterableWeakMap.types
Labels: For Backlog Bug

#58176 Check nearest package.json dependencies for possible package names for specifier candidates
  src/compiler/moduleNameResolver.ts
  src/compiler/moduleSpecifiers.ts
  src/compiler/program.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/testRunner/unittests/tsc/moduleResolution.ts
  tests/baselines/reference/symlinkedWorkspaceDependenciesNoDirectLinkGeneratesDeepNonrelativeName.js
  tests/baselines/reference/symlinkedWorkspaceDependenciesNoDirectLinkGeneratesDeepNonrelativeName.symbols
  tests/baselines/reference/symlinkedWorkspaceDependenciesNoDirectLinkGeneratesDeepNonrelativeName.types
  tests/baselines/reference/symlinkedWorkspaceDependenciesNoDirectLinkGeneratesNonrelativeName.js
  tests/baselines/reference/symlinkedWorkspaceDependenciesNoDirectLinkGeneratesNonrelativeName.symbols
  tests/baselines/reference/symlinkedWorkspaceDependenciesNoDirectLinkGeneratesNonrelativeName.types
  tests/baselines/reference/symlinkedWorkspaceDependenciesNoDirectLinkOptionalGeneratesNonrelativeName.js
  tests/baselines/reference/symlinkedWorkspaceDependenciesNoDirectLinkOptionalGeneratesNonrelativeName.symbols
  tests/baselines/reference/symlinkedWorkspaceDependenciesNoDirectLinkOptionalGeneratesNonrelativeName.types
  tests/baselines/reference/symlinkedWorkspaceDependenciesNoDirectLinkPeerGeneratesNonrelativeName.js
  tests/baselines/reference/symlinkedWorkspaceDependenciesNoDirectLinkPeerGeneratesNonrelativeName.symbols
  tests/baselines/reference/symlinkedWorkspaceDependenciesNoDirectLinkPeerGeneratesNonrelativeName.types
  tests/baselines/reference/tscWatch/moduleResolution/late-discovered-dependency-symlink.js
  tests/cases/compiler/symlinkedWorkspaceDependenciesNoDirectLinkGeneratesDeepNonrelativeName.ts
  tests/cases/compiler/symlinkedWorkspaceDependenciesNoDirectLinkGeneratesNonrelativeName.ts
  tests/cases/compiler/symlinkedWorkspaceDependenciesNoDirectLinkOptionalGeneratesNonrelativeName.ts
  tests/cases/compiler/symlinkedWorkspaceDependenciesNoDirectLinkPeerGeneratesNonrelativeName.ts
Labels: Author: Team, For Uncommitted Bug

#58211 DOM update 2024-04-16
  src/lib/dom.asynciterable.generated.d.ts
  src/lib/dom.generated.d.ts
  src/lib/dom.iterable.generated.d.ts
  src/lib/webworker.asynciterable.generated.d.ts
  src/lib/webworker.generated.d.ts
  src/lib/webworker.iterable.generated.d.ts
  tests/baselines/reference/globalThisBlockscopedProperties.types
  tests/baselines/reference/intersectionsOfLargeUnions.types
  tests/baselines/reference/intersectionsOfLargeUnions2.types
  tests/baselines/reference/mappedTypeRecursiveInference.errors.txt
  tests/baselines/reference/mappedTypeRecursiveInference.types
Labels: Author: Team, For Uncommitted Bug

#58251 Rename isParameterDeclaration to isPartOfParameterDeclaration
  src/compiler/binder.ts
  src/compiler/checker.ts
  src/compiler/utilities.ts
  src/services/inlayHints.ts
Labels: Author: Team, For Uncommitted Bug

#58008 Fixed single signature type parameter leak
  src/compiler/checker.ts
  tests/baselines/reference/genericCallInferenceWithGenericLocalFunction.symbols
  tests/baselines/reference/genericCallInferenceWithGenericLocalFunction.types
  tests/cases/compiler/genericCallInferenceWithGenericLocalFunction.ts
Labels: For Backlog Bug

#58254 Report positionless tsconfig option errors on `compilerOptions` key
  src/compiler/program.ts
  tests/baselines/reference/resolutionCandidateFromPackageJsonField2(moduleresolution=bundler).errors.txt
  tests/baselines/reference/tsc/moduleResolution/alternateResult.js
  tests/baselines/reference/tscWatch/forceConsistentCasingInFileNames/with-nodeNext-resolution.js
  tests/baselines/reference/tscWatch/moduleResolution/alternateResult.js
  tests/baselines/reference/tscWatch/moduleResolution/diagnostics-from-cache.js
  tests/baselines/reference/tscWatch/moduleResolution/module-resolutions-from-file-are-partially-used.js
  tests/baselines/reference/tscWatch/moduleResolution/module-resolutions-from-files-with-partially-used-import-attributes.js
  tests/baselines/reference/tscWatch/moduleResolution/type-reference-resolutions-reuse.js
  tests/baselines/reference/tsserver/moduleResolution/alternateResult.js
  tests/baselines/reference/verbatimModuleSyntaxCompat3.errors.txt
Labels: Author: Team, For Uncommitted Bug

#58010 Add types for `String#isWellFormed` and `String#toWellFormed`
  src/compiler/commandLineParser.ts
  src/compiler/utilities.ts
  src/lib/esnext.d.ts
  src/lib/esnext.string.d.ts
  src/lib/libs.json
  tests/baselines/reference/bundlerDirectoryModule(moduleresolution=bundler).trace.json
  tests/baselines/reference/bundlerDirectoryModule(moduleresolution=nodenext).trace.json
  tests/baselines/reference/dependentDestructuredVariablesFromNestedPatterns.symbols
  tests/baselines/reference/modulePreserve2.trace.json
  tests/baselines/reference/modulePreserve3.trace.json
  tests/baselines/reference/nodeModulesExportsBlocksTypesVersions(module=nodenext).trace.json
  tests/baselines/reference/nodeModulesPackageImports(module=nodenext).trace.json
  tests/baselines/reference/nodeModulesPackagePatternExportsTrailers(module=nodenext).trace.json
  tests/baselines/reference/reactJsxReactResolvedNodeNext.trace.json
  tests/baselines/reference/reactJsxReactResolvedNodeNextEsm.trace.json
  tests/baselines/reference/tsc/runWithoutArgs/does-not-add-color-when-NO_COLOR-is-set.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped-when-host-can't-provide-terminal-width.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
  tests/baselines/reference/typeGuardConstructorNarrowAny.symbols
  tests/baselines/reference/typeGuardConstructorPrimitiveTypes.symbols
  tests/baselines/reference/typesVersions.ambientModules.trace.json
  tests/baselines/reference/typesVersions.emptyTypes.trace.json
  tests/baselines/reference/typesVersions.justIndex.trace.json
  tests/baselines/reference/typesVersions.multiFile.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.ambient.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFile.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFileBackReferenceToSelf.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFileBackReferenceToUnmapped.trace.json
Labels: For Milestone Bug

#58239 Correctly compute noUncheckedIndexedAccess effects on compound/increment/decrement assignments
  src/compiler/checker.ts
  tests/baselines/reference/noUncheckedIndexedAccessCompoundAssignments.errors.txt
  tests/baselines/reference/noUncheckedIndexedAccessCompoundAssignments.js
  tests/baselines/reference/noUncheckedIndexedAccessCompoundAssignments.symbols
  tests/baselines/reference/noUncheckedIndexedAccessCompoundAssignments.types
  tests/cases/compiler/noUncheckedIndexedAccessCompoundAssignments.ts
Labels: Author: Team, For Backlog Bug

#58233 Don't cache child lists for tokens
  src/compiler/factory/nodeChildren.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/types.ts
  src/services/services.ts
  src/services/smartSelection.ts
  src/services/types.ts
  src/services/utilities.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Breaking Change, API, Author: Team, For Uncommitted Bug

#58135 Add gitHead to package.json in all release workflows
  .github/workflows/ci.yml
  .github/workflows/insiders.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release-branch-artifact.yaml
  azure-pipelines.release.yml
  scripts/addPackageJsonGitHead.mjs
  scripts/configurePrerelease.mjs
Labels: Author: Team, For Uncommitted Bug

#57281 Fix bug#56997 - Parenthesized SatisfiesExpressions with comments are not unwrapped consistently in emitted JS
  src/compiler/transformers/ts.ts
  tests/baselines/reference/commentEmitOnParenthesizedAssertionInReturnStatement2.js
  tests/baselines/reference/commentEmitOnParenthesizedAssertionInReturnStatement2.symbols
  tests/baselines/reference/commentEmitOnParenthesizedAssertionInReturnStatement2.types
  tests/baselines/reference/parenthesizedSatisfiesExpressionWithComments.js
  tests/baselines/reference/parenthesizedSatisfiesExpressionWithComments.symbols
  tests/baselines/reference/parenthesizedSatisfiesExpressionWithComments.types
  tests/baselines/reference/referenceSatisfiesExpression.js
  tests/baselines/reference/referenceSatisfiesExpression.symbols
  tests/baselines/reference/referenceSatisfiesExpression.types
  tests/cases/compiler/commentEmitOnParenthesizedAssertionInReturnStatement2.ts
  tests/cases/compiler/parenthesizedSatisfiesExpressionWithComments.ts
  tests/cases/compiler/referenceSatisfiesExpression.ts
Labels: For Backlog Bug

#57628 Fixed crash in go to definition related to expando classes in JS files
  src/services/goToDefinition.ts
  tests/baselines/reference/goToDefinitionExpandoClass1.baseline.jsonc
  tests/baselines/reference/goToDefinitionExpandoClass2.baseline.jsonc
  tests/cases/fourslash/goToDefinitionExpandoClass1.ts
  tests/cases/fourslash/goToDefinitionExpandoClass2.ts
Labels: For Uncommitted Bug

#58217 Add an extra test case for an error on async function typed using `@type`
  tests/baselines/reference/asyncArrowFunction_allowJs.errors.txt
  tests/baselines/reference/asyncArrowFunction_allowJs.symbols
  tests/baselines/reference/asyncArrowFunction_allowJs.types
  tests/cases/conformance/async/es2017/asyncArrowFunction/asyncArrowFunction_allowJs.ts
Labels: For Uncommitted Bug

#58155 Modify `CONTRIBUTING.md` and the issue templates `bug_report.yml` and `feature_request.yml` to reduce duplicate issues and improve the quality of further submitted issues
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  CONTRIBUTING.md
Labels: For Backlog Bug

#58261 Add `transpileDeclaration` API method
  src/compiler/emitter.ts
  src/harness/harnessIO.ts
  src/harness/runnerbase.ts
  src/services/transpile.ts
  src/testRunner/_namespaces/Harness.ts
  src/testRunner/runner.ts
  src/testRunner/transpileRunner.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/transpile/declarationBasicSyntax.d.ts
  tests/baselines/reference/transpile/declarationBasicSyntax.js
  tests/baselines/reference/transpile/declarationCrossFileInferences.d.ts
  tests/baselines/reference/transpile/declarationCrossFileInferences.js
  tests/baselines/reference/transpile/declarationLinkedAliases.d.ts
  tests/baselines/reference/transpile/declarationLinkedAliases.js
  tests/baselines/reference/transpile/declarationSingleFileHasErrors.d.ts
  tests/baselines/reference/transpile/declarationSingleFileHasErrors.js
  tests/baselines/reference/transpile/declarationSingleFileHasErrorsReported.d.ts
  tests/baselines/reference/transpile/declarationSingleFileHasErrorsReported.js
  tests/baselines/reference/transpile/declarationsSimple.d.ts
  tests/baselines/reference/transpile/declarationsSimple.js
  tests/cases/transpile/declarationBasicSyntax.ts
  tests/cases/transpile/declarationCrossFileInferences.ts
  tests/cases/transpile/declarationLinkedAliases.ts
  tests/cases/transpile/declarationSingleFileHasErrors.ts
  tests/cases/transpile/declarationSingleFileHasErrorsReported.ts
  tests/cases/transpile/declarationsSimple.ts
Labels: Author: Team, For Uncommitted Bug

#58306 Disable no-inferrable-types eslint rule
  .eslintrc.json
  src/compiler/corePublic.ts
Labels: Author: Team, For Uncommitted Bug

#58264 Error on references to literal enum members in conditions
  src/compiler/checker.ts
  tests/baselines/reference/errorOnEnumReferenceInCondition.errors.txt
  tests/baselines/reference/errorOnEnumReferenceInCondition.js
  tests/baselines/reference/errorOnEnumReferenceInCondition.symbols
  tests/baselines/reference/errorOnEnumReferenceInCondition.types
  tests/cases/compiler/errorOnEnumReferenceInCondition.ts
Labels: Author: Team, For Uncommitted Bug

#58295 Report RegExp errors in grammar check, use Annex B grammar
  src/compiler/checker.ts
  src/compiler/scanner.ts
  src/testRunner/unittests/incrementalParser.ts
  tests/baselines/reference/parserRegularExpression1.errors.txt
  tests/baselines/reference/parserRegularExpression1.js
  tests/baselines/reference/parserRegularExpression1.symbols
  tests/baselines/reference/parserRegularExpression1.types
  tests/baselines/reference/parserRegularExpression6.js
  tests/baselines/reference/parserRegularExpression6.symbols
  tests/baselines/reference/parserRegularExpression6.types
  tests/baselines/reference/parserRegularExpressionDivideAmbiguity4.errors.txt
  tests/baselines/reference/parserRegularExpressionDivideAmbiguity4.js
  tests/baselines/reference/parserRegularExpressionDivideAmbiguity4.types
  tests/baselines/reference/regularExpressionScanning(target=es2015).errors.txt
  tests/baselines/reference/regularExpressionScanning(target=es5).errors.txt
  tests/baselines/reference/regularExpressionScanning(target=esnext).errors.txt
  tests/baselines/reference/regularExpressionUnicodePropertyValueExpressionSuggestions.errors.txt
  tests/baselines/reference/shebangError.errors.txt
  tests/cases/conformance/parser/ecmascript5/RegularExpressions/parserRegularExpression1.ts
  tests/cases/conformance/parser/ecmascript5/RegularExpressions/parserRegularExpression6.ts
Labels: Author: Team, For Uncommitted Bug

#58297 fix(58265): JSDoc comment string with the keyword "@private" before import statement in JS file result in cryptic error TS1191 during compilation
  src/compiler/checker.ts
  tests/baselines/reference/es6ImportWithJsDocTags.symbols
  tests/baselines/reference/es6ImportWithJsDocTags.types
  tests/cases/compiler/es6ImportWithJsDocTags.ts
Labels: For Backlog Bug

#58310 Rephrase error messages on backrererences.
  src/compiler/diagnosticMessages.json
  src/compiler/scanner.ts
  tests/baselines/reference/regularExpressionScanning(target=es2015).errors.txt
  tests/baselines/reference/regularExpressionScanning(target=es2015).js
  tests/baselines/reference/regularExpressionScanning(target=es2015).symbols
  tests/baselines/reference/regularExpressionScanning(target=es2015).types
  tests/baselines/reference/regularExpressionScanning(target=es5).errors.txt
  tests/baselines/reference/regularExpressionScanning(target=es5).js
  tests/baselines/reference/regularExpressionScanning(target=es5).symbols
  tests/baselines/reference/regularExpressionScanning(target=es5).types
  tests/baselines/reference/regularExpressionScanning(target=esnext).errors.txt
  tests/baselines/reference/regularExpressionScanning(target=esnext).js
  tests/baselines/reference/regularExpressionScanning(target=esnext).symbols
  tests/baselines/reference/regularExpressionScanning(target=esnext).types
  tests/cases/compiler/regularExpressionScanning.ts
Labels: Author: Team, For Uncommitted Bug

#58313 5.5 deprecations are no-ops, not errors
  src/compiler/program.ts
  tests/baselines/reference/alwaysStrictNoImplicitUseStrict.errors.txt
  tests/baselines/reference/deprecatedCompilerOptions4.errors.txt
  tests/baselines/reference/excessPropertyErrorsSuppressed.errors.txt
  tests/baselines/reference/importsNotUsedAsValues_error.errors.txt
  tests/baselines/reference/isolatedModulesOut.errors.txt
  tests/baselines/reference/keyofDoesntContainSymbols.errors.txt
  tests/baselines/reference/lateBoundConstraintTypeChecksCorrectly.errors.txt
  tests/baselines/reference/mappedTypeUnionConstraintInferences.errors.txt
  tests/baselines/reference/noCrashWithVerbatimModuleSyntaxAndImportsNotUsedAsValues.errors.txt
  tests/baselines/reference/noImplicitAnyIndexingSuppressed.errors.txt
  tests/baselines/reference/noImplicitUseStrict_amd.errors.txt
  tests/baselines/reference/noImplicitUseStrict_commonjs.errors.txt
  tests/baselines/reference/noImplicitUseStrict_es6.errors.txt
  tests/baselines/reference/noImplicitUseStrict_system.errors.txt
  tests/baselines/reference/noImplicitUseStrict_umd.errors.txt
  tests/baselines/reference/noStrictGenericChecks.errors.txt
  tests/baselines/reference/nonPrimitiveIndexingWithForInSupressError.errors.txt
  tests/baselines/reference/preserveUnusedImports.errors.txt
  tests/baselines/reference/preserveValueImports(isolatedmodules=false).errors.txt
  tests/baselines/reference/preserveValueImports(isolatedmodules=true).errors.txt
  tests/baselines/reference/preserveValueImports_errors(isolatedmodules=false).errors.txt
  tests/baselines/reference/preserveValueImports_errors(isolatedmodules=true).errors.txt
  tests/baselines/reference/preserveValueImports_importsNotUsedAsValues.errors.txt
  tests/baselines/reference/preserveValueImports_mixedImports.errors.txt
  tests/baselines/reference/preserveValueImports_module(module=amd).errors.txt
  tests/baselines/reference/preserveValueImports_module(module=commonjs).errors.txt
  tests/baselines/reference/preserveValueImports_module(module=es2015).errors.txt
  tests/baselines/reference/preserveValueImports_module(module=system).errors.txt
  tests/baselines/reference/transpile/Supports setting charset (verbatimModuleSyntax=true).errors.txt
  tests/baselines/reference/transpile/Supports setting charset (verbatimModuleSyntax=true).oldTranspile.errors.txt
  tests/baselines/reference/transpile/Supports setting charset.errors.txt
  tests/baselines/reference/transpile/Supports setting charset.oldTranspile.errors.txt
  tests/baselines/reference/transpile/Supports setting noImplicitUseStrict (verbatimModuleSyntax=true).errors.txt
  tests/baselines/reference/transpile/Supports setting noImplicitUseStrict (verbatimModuleSyntax=true).oldTranspile.errors.txt
  tests/baselines/reference/transpile/Supports setting noImplicitUseStrict.errors.txt
  tests/baselines/reference/transpile/Supports setting noImplicitUseStrict.oldTranspile.errors.txt
  tests/baselines/reference/transpile/Supports setting suppressExcessPropertyErrors (verbatimModuleSyntax=true).errors.txt
  tests/baselines/reference/transpile/Supports setting suppressExcessPropertyErrors (verbatimModuleSyntax=true).oldTranspile.errors.txt
  tests/baselines/reference/transpile/Supports setting suppressExcessPropertyErrors.errors.txt
  tests/baselines/reference/transpile/Supports setting suppressExcessPropertyErrors.oldTranspile.errors.txt
  tests/baselines/reference/transpile/Supports setting suppressImplicitAnyIndexErrors (verbatimModuleSyntax=true).errors.txt
  tests/baselines/reference/transpile/Supports setting suppressImplicitAnyIndexErrors (verbatimModuleSyntax=true).oldTranspile.errors.txt
  tests/baselines/reference/transpile/Supports setting suppressImplicitAnyIndexErrors.errors.txt
  tests/baselines/reference/transpile/Supports setting suppressImplicitAnyIndexErrors.oldTranspile.errors.txt
  tests/baselines/reference/tsbuild/amdModulesWithOut/prepend-reports-deprecation-error.js
  tests/baselines/reference/tscWatch/emit/emit-with-outFile-or-out-setting/config-has-out.js
  tests/baselines/reference/tsserver/telemetry/does-not-expose-paths.js
  tests/baselines/reference/verbatimModuleSyntaxCompat.errors.txt
  tests/baselines/reference/verbatimModuleSyntaxCompat2.errors.txt
  tests/baselines/reference/verbatimModuleSyntaxCompat3.errors.txt
  tests/baselines/reference/verbatimModuleSyntaxCompat4.errors.txt
Labels: Author: Team, For Uncommitted Bug

#58309 Test Node 22
  .github/workflows/ci.yml
Labels: Author: Team, For Uncommitted Bug

#58311 Move RegExp flag version mapping to LanguageFeatureMinimumTarget
  src/compiler/scanner.ts
  src/compiler/types.ts
Labels: Author: Team, For Uncommitted Bug

#58257 Updating move to file
  src/services/codefixes/importFixes.ts
  src/services/refactors/helpers.ts
  src/services/refactors/moveToFile.ts
  src/services/refactors/moveToNewFile.ts
  src/services/utilities.ts
  tests/baselines/reference/tsserver/fourslashServer/moveToFile_emptyTargetFile.js
  tests/baselines/reference/tsserver/getApplicableRefactors/returns-the-affected-range-of-text-for-'move-to-file'-and-'move-to-new-file'-refactors.js
  tests/cases/fourslash/moveToFile_blankExistingFile.ts
  tests/cases/fourslash/moveToFile_consistentQuoteStyle.ts
  tests/cases/fourslash/moveToFile_differentDirectories2.ts
  tests/cases/fourslash/moveToFile_expandSelectionRange4.ts
  tests/cases/fourslash/moveToFile_namedImports.ts
  tests/cases/fourslash/moveToFile_unresolvedImport.ts
  tests/cases/fourslash/moveToNewFile.ts
  tests/cases/fourslash/moveToNewFile_decorators.ts
  tests/cases/fourslash/moveToNewFile_decorators1.ts
  tests/cases/fourslash/moveToNewFile_decorators2.ts
  tests/cases/fourslash/moveToNewFile_decorators3.ts
  tests/cases/fourslash/moveToNewFile_global.ts
  tests/cases/fourslash/moveToNewFile_js.ts
  tests/cases/fourslash/moveToNewFile_prologueDirectives1.ts
  tests/cases/fourslash/moveToNewFile_prologueDirectives7.ts
  tests/cases/fourslash/moveToNewFile_requireImport1.ts
  tests/cases/fourslash/moveToNewFile_requireImport2.ts
  tests/cases/fourslash/moveToNewFile_requireImport3.ts
  tests/cases/fourslash/moveToNewFile_typeImport2.ts
  tests/cases/fourslash/moveToNewFile_updateUses.ts
  tests/cases/fourslash/moveToNewFile_updateUses_js.ts
Labels: Author: Team, For Uncommitted Bug

#58317 Make diagnostics public on EmitOutput
  src/compiler/builderStatePublic.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#58335 Exclude outDir and declarationDir even if they come from extended config
  src/compiler/commandLineParser.ts
  src/testRunner/unittests/config/tsconfigParsing.ts
  tests/baselines/reference/config/showConfig/Show TSConfig with paths and more/tsconfig.json
  tests/baselines/reference/config/tsconfigParsing/generates errors for empty files list when no references are provided with jsonSourceFile api.js
  tests/baselines/reference/config/tsconfigParsing/generates errors for empty files list with jsonSourceFile api.js
  tests/baselines/reference/config/tsconfigParsing/generates errors for includes with outDir with json api.js
  tests/baselines/reference/config/tsconfigParsing/generates errors for includes with outDir with jsonSourceFile api.js
  tests/baselines/reference/config/tsconfigParsing/generates errors for when invalid comment type present in tsconfig with jsonSourceFile api.js
  tests/baselines/reference/config/tsconfigParsing/generates errors when commandline option is in tsconfig with jsonSourceFile api.js
  tests/baselines/reference/config/tsconfigParsing/generates errors when files is not string with jsonSourceFile api.js
  tests/baselines/reference/config/tsconfigParsing/generates errors when include is not string with jsonSourceFile api.js
  tests/baselines/reference/config/tsconfigParsing/with outDir from base tsconfig with json api.js
  tests/baselines/reference/config/tsconfigParsing/with outDir from base tsconfig with jsonSourceFile api.js
  tests/baselines/reference/tsc/extends/configDir-template-showConfig.js
Labels: Author: Team, For Uncommitted Bug

#58308 Treat the input file name from referenced project as "ts" rather than file extension it is when determining eliding file for program construction
  src/compiler/program.ts
  src/testRunner/unittests/tsbuild/moduleResolution.ts
  tests/baselines/reference/tsbuild/moduleResolution/shared-resolution-should-not-report-error.js
  tests/baselines/reference/tsbuild/moduleResolution/when-resolution-is-not-shared.js
Labels: Author: Team, For Uncommitted Bug

#57934 Add `noCheck` API option
  src/compiler/checker.ts
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  src/compiler/emitter.ts
  src/compiler/program.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/harness/harnessIO.ts
  src/services/transpile.ts
  src/testRunner/compilerRunner.ts
  src/testRunner/tests.ts
  src/testRunner/unittests/tsbuild/noCheck.ts
  tests/baselines/reference/config/showConfig/Shows tsconfig for single option/noCheck/tsconfig.json
  tests/baselines/reference/deferredLookupTypeResolution.js
  tests/baselines/reference/indexSignatures1.js
  tests/baselines/reference/jsDeclarationsCrossfileMerge.js
  tests/baselines/reference/noCheckDoesNotReportError.js
  tests/baselines/reference/noCheckDoesNotReportError.symbols
  tests/baselines/reference/noCheckDoesNotReportError.types
  tests/baselines/reference/noCheckNoEmit.errors.txt
  tests/baselines/reference/noCheckNoEmit.symbols
  tests/baselines/reference/noCheckNoEmit.types
  tests/baselines/reference/noCheckRequiresEmitDeclarationOnly.errors.txt
  tests/baselines/reference/noCheckRequiresEmitDeclarationOnly.js
  tests/baselines/reference/noCheckRequiresEmitDeclarationOnly.symbols
  tests/baselines/reference/noCheckRequiresEmitDeclarationOnly.types
  tests/baselines/reference/noEmitOnError.js
  tests/baselines/reference/outModuleConcatCommonjs.js
  tests/baselines/reference/outModuleConcatES6.js
  tests/baselines/reference/outModuleConcatUmd.js
  tests/baselines/reference/tsbuild/noCheck-errors/semantic-errors-with-incremental.js
  tests/baselines/reference/tsbuild/noCheck-errors/semantic-errors.js
  tests/baselines/reference/tsbuild/noCheck-errors/syntax-errors-with-incremental.js
  tests/baselines/reference/tsbuild/noCheck-errors/syntax-errors.js
  tests/baselines/reference/tsbuild/noCheck/semantic-errors-with-incremental-discrepancies.js
  tests/baselines/reference/tsbuild/noCheck/semantic-errors-with-incremental.js
  tests/baselines/reference/tsbuild/noCheck/semantic-errors.js
  tests/baselines/reference/tsbuild/noCheck/syntax-errors-with-incremental-discrepancies.js
  tests/baselines/reference/tsbuild/noCheck/syntax-errors-with-incremental.js
  tests/baselines/reference/tsbuild/noCheck/syntax-errors.js
  tests/baselines/reference/typeReferenceDirectives11.js
  tests/baselines/reference/typeReferenceDirectives12.js
  tests/baselines/reference/variadicTuples1.js
  tests/baselines/reference/weakTypesAndLiterals01.js
  tests/cases/compiler/noCheckDoesNotReportError.ts
  tests/cases/compiler/noCheckNoEmit.ts
  tests/cases/compiler/noCheckRequiresEmitDeclarationOnly.ts
Labels: Author: Team, For Uncommitted Bug

#58333 Dont get declaration diagnostics for file from referenced project
  src/compiler/transformers/declarations.ts
  src/testRunner/unittests/tsserver/projectReferenceErrors.ts
  tests/baselines/reference/tsserver/projectReferenceErrors/when-options-for-dependency-project-are-different-from-usage-project.js
Labels: Author: Team, For Uncommitted Bug

#58220 Improve diagnostics deduplication
  src/compiler/core.ts
  src/compiler/utilities.ts
  src/compiler/utilitiesPublic.ts
  src/services/completions.ts
  src/testRunner/tests.ts
  src/testRunner/unittests/diagnosticCollection.ts
  tests/baselines/reference/destructuringAssignmentWithDefault2.errors.txt
  tests/baselines/reference/duplicateErrorClassExpression.errors.txt
  tests/baselines/reference/duplicateErrorClassExpression.js
  tests/baselines/reference/duplicateErrorClassExpression.symbols
  tests/baselines/reference/duplicateErrorClassExpression.types
  tests/baselines/reference/multipleDefaultExports05.errors.txt
  tests/cases/compiler/duplicateErrorClassExpression.ts
Labels: Author: Team, For Uncommitted Bug

#58318 Improve diagnostics deduplication 2
  src/compiler/checker.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  tests/baselines/reference/duplicateErrorAssignability.errors.txt
  tests/baselines/reference/duplicateErrorAssignability.js
  tests/baselines/reference/duplicateErrorAssignability.symbols
  tests/baselines/reference/duplicateErrorAssignability.types
  tests/baselines/reference/duplicateErrorNameNotFound.errors.txt
  tests/baselines/reference/duplicateErrorNameNotFound.js
  tests/baselines/reference/duplicateErrorNameNotFound.symbols
  tests/baselines/reference/duplicateErrorNameNotFound.types
  tests/baselines/reference/mappedTypeRecursiveInference.types
  tests/baselines/reference/tscWatch/resolutionCache/reusing-type-ref-resolution.js
  tests/cases/compiler/duplicateErrorAssignability.ts
  tests/cases/compiler/duplicateErrorNameNotFound.ts
Labels: Author: Team, For Uncommitted Bug

#58339 RegExp syntax checking performance
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/scanner.ts
  src/compiler/types.ts
  tests/baselines/reference/regularExpressionScanning(target=es2015).errors.txt
  tests/baselines/reference/regularExpressionScanning(target=es5).errors.txt
  tests/baselines/reference/regularExpressionScanning(target=esnext).errors.txt
Labels: Author: Team, For Uncommitted Bug

#58337 Fix ghost errors resulting from out-of-order type checking
  src/compiler/checker.ts
  tests/baselines/reference/circularReferenceInReturnType.errors.txt
  tests/baselines/reference/circularReferenceInReturnType2.errors.txt
  tests/baselines/reference/circularReferenceInReturnType2.types
  tests/baselines/reference/recursiveExportAssignmentAndFindAliasedType7.types
  tests/cases/fourslash/issue57429.ts
  tests/cases/fourslash/issue57585-2.ts
  tests/cases/fourslash/issue57585.ts
Labels: Author: Team, For Milestone Bug

#58365 fix(58360): Cheese being inserted on TypeScript Quick Fix
  src/services/codefixes/fixAddMissingParam.ts
  tests/cases/fourslash/codeFixAddMissingParam17.ts
Labels: For Milestone Bug

#58377 Remove seemingly unused SymbolLink `constEnumReferenced`
  src/compiler/checker.ts
  src/compiler/types.ts
Labels: Author: Team, For Uncommitted Bug

#58372 Cache discriminated contextual types
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug

#58260 Add a code fixer for --isolatedDeclarations errors
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/types.ts
  src/services/_namespaces/ts.codefix.ts
  src/services/codeFixProvider.ts
  src/services/codefixes/fixMissingTypeAnnotationOnExports.ts
  src/services/refactors/extractSymbol.ts
  src/services/refactors/helpers.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports10.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports11.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports12.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports13.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports14.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports15.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports16.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports17-unique-symbol.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports18.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports19.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports2.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports20.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports21-params-and-return.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports22-formatting.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports23-heritage-formatting.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports24-heritage-formatting-2.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports25-heritage-formatting-3.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports26-fn-in-object-literal.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports27-non-exported-bidings.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports28-long-types.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports29-inline.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports3.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports30-inline-import.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports31-inline-import-default.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports32-inline-short-hand.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports33-methods.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports34-object-spread.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports35-variable-releative.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports36-conditional-releative.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports37-array-spread.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports38-unique-symbol-return.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports39-extract-arr-to-variable.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports4.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports40-extract-other-to-variable.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports41-no-computed-enum-members.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports42-static-readonly-class-symbol.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports43-expando-functions-2.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports43-expando-functions-3.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports43-expando-functions-4.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports43-expando-functions-5.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports43-expando-functions.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports44-default-export.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports45-decorators.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports46-decorators-experimental.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports5.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports6.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports7.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports8.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports9.ts
Labels: For Uncommitted Bug
