Repository microsoft/TypeScript, pull requests merged in 2024-01, with the labels that each got.

#56715 fix(56706): "Show call hierarchy" does not work with arrow methods in a class
  src/services/callHierarchy.ts
  tests/baselines/reference/callHierarchyClassPropertyArrowFunction.callHierarchy.txt
  tests/cases/fourslash/callHierarchyClassPropertyArrowFunction.ts
Labels: For Backlog Bug

#56723 Add asynciterable libs
  src/compiler/commandLineParser.ts
  src/lib/dom.asynciterable.generated.d.ts
  src/lib/es2018.full.d.ts
  src/lib/es2019.full.d.ts
  src/lib/es2020.full.d.ts
  src/lib/es2021.full.d.ts
  src/lib/es2022.full.d.ts
  src/lib/es2023.full.d.ts
  src/lib/esnext.full.d.ts
  src/lib/libs.json
  src/lib/webworker.asynciterable.generated.d.ts
  tests/baselines/reference/config/commandLineParsing/parseCommandLine/Parse --lib option with extra comma.js
  tests/baselines/reference/config/commandLineParsing/parseCommandLine/Parse --lib option with trailing white-space.js
  tests/baselines/reference/config/commandLineParsing/parseCommandLine/Parse invalid option of library flags.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert empty string option of libs array to compiler-options with json api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert empty string option of libs array to compiler-options with jsonSourceFile api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert empty string option of libs to compiler-options with json api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert empty string option of libs to compiler-options with jsonSourceFile api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert incorrect option of libs to compiler-options with json api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert incorrect option of libs to compiler-options with jsonSourceFile api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert trailing-whitespace string option of libs to compiler-options with json api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert trailing-whitespace string option of libs to compiler-options with jsonSourceFile api.js
  tests/baselines/reference/modularizeLibrary_Dom.asynciterable.js
  tests/baselines/reference/modularizeLibrary_Dom.asynciterable.symbols
  tests/baselines/reference/modularizeLibrary_Dom.asynciterable.types
  tests/baselines/reference/modularizeLibrary_Worker.asynciterable.js
  tests/baselines/reference/modularizeLibrary_Worker.asynciterable.symbols
  tests/baselines/reference/modularizeLibrary_Worker.asynciterable.types
  tests/baselines/reference/modularizeLibrary_Worker.iterable.js
  tests/baselines/reference/modularizeLibrary_Worker.iterable.symbols
  tests/baselines/reference/modularizeLibrary_Worker.iterable.types
  tests/baselines/reference/tsc/runWithoutArgs/does-not-add-color-when-NO_COLOR-is-set.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped-when-host-can't-provide-terminal-width.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
  tests/baselines/reference/tsserver/telemetry/does-not-expose-paths.js
  tests/baselines/reference/typesVersions.ambientModules.trace.json
  tests/baselines/reference/typesVersions.emptyTypes.trace.json
  tests/baselines/reference/typesVersions.justIndex.trace.json
  tests/baselines/reference/typesVersions.multiFile.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.ambient.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFile.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFileBackReferenceToSelf.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFileBackReferenceToUnmapped.trace.json
  tests/cases/compiler/modularizeLibrary_Dom.asynciterable.ts
  tests/cases/compiler/modularizeLibrary_Worker.asynciterable.ts
  tests/cases/compiler/modularizeLibrary_Worker.iterable.ts
Labels: For Backlog Bug

#56739 fix(56733): Auto fix "add missing properties" of enums does not correct namespace of enum
  src/services/codefixes/fixAddMissingMember.ts
  tests/cases/fourslash/codeFixAddMissingProperties29.ts
Labels: For Backlog Bug

#56743 fix(56737): unique symbol quick info is different in JS than TS
  src/compiler/checker.ts
  tests/baselines/reference/quickInfoUniqueSymbolJsDoc.baseline
  tests/baselines/reference/uniqueSymbolJs.errors.txt
  tests/baselines/reference/uniqueSymbolJs.symbols
  tests/baselines/reference/uniqueSymbolJs.types
  tests/baselines/reference/uniqueSymbolsDeclarationsInJs.types
  tests/baselines/reference/uniqueSymbolsDeclarationsInJsErrors.types
  tests/cases/compiler/uniqueSymbolJs.ts
  tests/cases/fourslash/quickInfoUniqueSymbolJsDoc.ts
Labels: For Milestone Bug

#56788 fix(56756): using quick fix to add missing enum member will add extra empty lines
  src/services/codefixes/fixAddMissingMember.ts
  src/services/textChanges.ts
  tests/baselines/reference/textChanges/insertNodeInListAfter10.js
  tests/baselines/reference/textChanges/insertNodeInListAfter12.js
  tests/baselines/reference/textChanges/insertNodeInListAfter18.js
  tests/cases/fourslash/codeFixAddMissingEnumMember10.ts
  tests/cases/fourslash/codeFixAddMissingEnumMember14.ts
  tests/cases/fourslash/codeFixAddMissingEnumMember15.ts
  tests/cases/fourslash/codeFixAddMissingEnumMember4.ts
  tests/cases/fourslash/codeFixAddMissingEnumMember5.ts
  tests/cases/fourslash/codeFixAddMissingEnumMember9.ts
Labels: For Backlog Bug

#56802 fix(56475): Hyperlink in quick info generated by @link jumps to import statement for named or default imports, not symbol definition
  src/services/utilities.ts
  tests/baselines/reference/jsdocLink3.baseline
  tests/baselines/reference/jsdocLink6.baseline
  tests/cases/fourslash/jsdocLink6.ts
Labels: For Backlog Bug

#56640 Infer between generic mapped types before inferring from apparent type
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypeInferenceFromApparentType.errors.txt
  tests/baselines/reference/mappedTypeInferenceFromApparentType.symbols
  tests/baselines/reference/mappedTypeInferenceFromApparentType.types
  tests/baselines/reference/mappedTypeInferenceToMappedType.symbols
  tests/baselines/reference/mappedTypeInferenceToMappedType.types
  tests/cases/compiler/mappedTypeInferenceFromApparentType.ts
  tests/cases/compiler/mappedTypeInferenceToMappedType.ts
Labels: Author: Team, For Milestone Bug

#56853 `getImpliedNodeFormatForFile` does not need a Path
  src/compiler/program.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Milestone Bug

#56340 Fix declaration emit for JS default re-exports that resolve to modules through synthesized default exports
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitJsReExportDefault.js
  tests/cases/compiler/declarationEmitJsReExportDefault.ts
Labels: Author: Team, For Milestone Bug

#56318 Fixed an issue with property type display when contextual type is a union
  src/services/services.ts
  tests/cases/fourslash/quickInfoFromContextualUnionType1.ts
Labels: For Backlog Bug

#56944 Switch GHA workflows for LF line endings to work around dependabot bug
  .dprint.jsonc
  .github/ISSUE_TEMPLATE/config.yml
  .github/workflows/close-issues.yml
  .github/workflows/error-deltas-watchdog.yaml
  .github/workflows/new-release-branch.yaml
  .github/workflows/nightly.yaml
  .github/workflows/pr-modified-files.yml
  .github/workflows/release-branch-artifact.yaml
  .github/workflows/set-version.yaml
  .github/workflows/sync-branch.yaml
  .github/workflows/update-package-lock.yaml
Labels: Author: Team, For Uncommitted Bug

#56759 Remove hereby gulp shim warning
  .gulp.js
Labels: Author: Team, For Uncommitted Bug

#56893 Add an extra test case related to control flow of element access using non-const variable
  tests/baselines/reference/controlFlowElementAccessNoCrash1.symbols
  tests/baselines/reference/controlFlowElementAccessNoCrash1.types
  tests/cases/conformance/controlFlow/controlFlowElementAccessNoCrash1.ts
Labels: For Uncommitted Bug

#56770 Bump node in update-package-lock.yaml
  .github/workflows/update-package-lock.yaml
Labels: Author: Team, For Uncommitted Bug

#56467 Fix "Extract to type alias" not available at end of span
  src/services/refactors/extractType.ts
  tests/cases/fourslash/refactorExtractType89.ts
Labels: For Backlog Bug

#56860 Fixed narrowing based on aliased discriminants coming from destructured parameters
  src/compiler/checker.ts
  tests/baselines/reference/controlFlowAliasedDiscriminants.errors.txt
  tests/baselines/reference/controlFlowAliasedDiscriminants.js
  tests/baselines/reference/controlFlowAliasedDiscriminants.symbols
  tests/baselines/reference/controlFlowAliasedDiscriminants.types
  tests/cases/compiler/controlFlowAliasedDiscriminants.ts
Labels: For Backlog Bug

#56986 Update dprint and dprint plugins
  .dprint.jsonc
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#56908 Preserve type refinements in closures created past last assignment
  src/compiler/checker.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  tests/baselines/reference/controlFlowAliasing.errors.txt
  tests/baselines/reference/controlFlowAliasing.js
  tests/baselines/reference/controlFlowAliasing.symbols
  tests/baselines/reference/controlFlowAliasing.types
  tests/baselines/reference/implicitConstParameters.errors.txt
  tests/baselines/reference/implicitConstParameters.js
  tests/baselines/reference/implicitConstParameters.symbols
  tests/baselines/reference/implicitConstParameters.types
  tests/baselines/reference/narrowingPastLastAssignment.errors.txt
  tests/baselines/reference/narrowingPastLastAssignment.symbols
  tests/baselines/reference/narrowingPastLastAssignment.types
  tests/baselines/reference/narrowingPastLastAssignmentInModule.symbols
  tests/baselines/reference/narrowingPastLastAssignmentInModule.types
  tests/cases/compiler/implicitConstParameters.ts
  tests/cases/compiler/narrowingPastLastAssignment.ts
  tests/cases/compiler/narrowingPastLastAssignmentInModule.ts
  tests/cases/conformance/controlFlow/controlFlowAliasing.ts
Labels: Author: Team, For Backlog Bug

#56601 Fixed emit of return statements with parenthesized assertions and comments
  src/compiler/emitter.ts
  tests/baselines/reference/commentEmitOnParenthesizedAssertionInReturnStatement.js
  tests/baselines/reference/commentEmitOnParenthesizedAssertionInReturnStatement.symbols
  tests/baselines/reference/commentEmitOnParenthesizedAssertionInReturnStatement.types
  tests/cases/compiler/commentEmitOnParenthesizedAssertionInReturnStatement.ts
Labels: For Backlog Bug

#56727 Fixed apparent type of homomorphic mapped type with non-homomorphic instantiation
  src/compiler/checker.ts
  tests/baselines/reference/homomorphicMappedTypeWithNonHomomorphicInstantiationSpreadable1.symbols
  tests/baselines/reference/homomorphicMappedTypeWithNonHomomorphicInstantiationSpreadable1.types
  tests/cases/compiler/homomorphicMappedTypeWithNonHomomorphicInstantiationSpreadable1.ts
Labels: For Backlog Bug

#56322 Fixed an issue with write type being left as non-instantiated when coming from a merged instantiation
  src/compiler/checker.ts
  tests/baselines/reference/mergedInstantiationAssignment.symbols
  tests/baselines/reference/mergedInstantiationAssignment.types
  tests/cases/compiler/mergedInstantiationAssignment.ts
Labels: For Backlog Bug

#56742 When relating a deferred index type over a mapped type on the source side ...
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitNestedAnonymousMappedType.js
  tests/baselines/reference/declarationEmitNestedAnonymousMappedType.symbols
  tests/baselines/reference/declarationEmitNestedAnonymousMappedType.types
  tests/cases/compiler/declarationEmitNestedAnonymousMappedType.ts
Labels: Author: Team, For Milestone Bug

#56857 Emit declarations using alternative containing modules for types exported using separate export statements
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitUsingAlternativeContainingModules1.js
  tests/baselines/reference/declarationEmitUsingAlternativeContainingModules1.symbols
  tests/baselines/reference/declarationEmitUsingAlternativeContainingModules1.types
  tests/baselines/reference/declarationEmitUsingAlternativeContainingModules2.js
  tests/baselines/reference/declarationEmitUsingAlternativeContainingModules2.symbols
  tests/baselines/reference/declarationEmitUsingAlternativeContainingModules2.types
  tests/cases/compiler/declarationEmitUsingAlternativeContainingModules1.ts
  tests/cases/compiler/declarationEmitUsingAlternativeContainingModules2.ts
Labels: For Milestone Bug

#56884 fix(55650): Wrong/missing quick info in JSDoc @implements tag
  src/compiler/utilities.ts
  tests/baselines/reference/quickInfoJsDocTags15.baseline
  tests/cases/fourslash/quickInfoJsDocTags15.ts
Labels: For Milestone Bug

#55269 Organize type imports
  src/compiler/types.ts
  src/harness/fourslashImpl.ts
  src/server/protocol.ts
  src/services/codefixes/importFixes.ts
  src/services/organizeImports.ts
  src/testRunner/unittests/services/organizeImports.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/autoImportTypeImport1.ts
  tests/cases/fourslash/autoImportTypeImport2.ts
  tests/cases/fourslash/autoImportTypeImport3.ts
  tests/cases/fourslash/autoImportTypeImport4.ts
  tests/cases/fourslash/autoImportTypeImport5.ts
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/importNameCodeFix_importType7.ts
  tests/cases/fourslash/organizeImports1.ts
  tests/cases/fourslash/organizeImports16.ts
  tests/cases/fourslash/organizeImportsType1.ts
  tests/cases/fourslash/organizeImportsType2.ts
  tests/cases/fourslash/organizeImportsType3.ts
  tests/cases/fourslash/organizeImportsType4.ts
  tests/cases/fourslash/organizeImportsType5.ts
  tests/cases/fourslash/organizeImportsType6.ts
  tests/cases/fourslash/organizeImportsType7.ts
  tests/cases/fourslash/organizeImportsType8.ts
  tests/cases/fourslash/organizeImportsType9.ts
Labels: Author: Team, For Milestone Bug

#56946 With `allowJs`, process JS files found searching node_modules when they have a realpath outside node_modules
  src/compiler/program.ts
  tests/baselines/reference/allowJsCrossMonorepoPackage.symbols
  tests/baselines/reference/allowJsCrossMonorepoPackage.trace.json
  tests/baselines/reference/allowJsCrossMonorepoPackage.types
  tests/cases/compiler/allowJsCrossMonorepoPackage.ts
Labels: Author: Team, For Uncommitted Bug

#56753 Improve binding element type inference using CheckMode (rebased)
  src/compiler/checker.ts
  tests/baselines/reference/destructuringArrayBindingPatternAndAssignment3.types
  tests/baselines/reference/destructuringArrayBindingPatternAndAssignment5SiblingInitializer.js
  tests/baselines/reference/destructuringArrayBindingPatternAndAssignment5SiblingInitializer.symbols
  tests/baselines/reference/destructuringArrayBindingPatternAndAssignment5SiblingInitializer.types
  tests/baselines/reference/destructuringObjectBindingPatternAndAssignment9SiblingInitializer.js
  tests/baselines/reference/destructuringObjectBindingPatternAndAssignment9SiblingInitializer.symbols
  tests/baselines/reference/destructuringObjectBindingPatternAndAssignment9SiblingInitializer.types
  tests/cases/conformance/es6/destructuring/destructuringArrayBindingPatternAndAssignment5SiblingInitializer.ts
  tests/cases/conformance/es6/destructuring/destructuringObjectBindingPatternAndAssignment9SiblingInitializer.ts
Labels: For Backlog Bug

#56034 fix(55994): Type-check Import Attributes in static imports
  src/compiler/checker.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/harness/fourslashImpl.ts
  src/services/completions.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/completionListForImportAttributes.baseline
  tests/baselines/reference/completionPropertyFromConstraint.baseline
  tests/baselines/reference/importAssertionNonstring.errors.txt
  tests/baselines/reference/importAttributes6.errors.txt
  tests/baselines/reference/importAttributes9.errors.txt
  tests/baselines/reference/importAttributes9.js
  tests/baselines/reference/importAttributes9.symbols
  tests/baselines/reference/importAttributes9.types
  tests/cases/conformance/importAttributes/importAttributes9.ts
  tests/cases/fourslash/completionListForImportAttributes.ts
Labels: For Backlog Bug

#56243 Fxied declaration emit for JS files when `module.exports` is assigned a non-alias value and when it has extra type members
  src/compiler/checker.ts
  tests/baselines/reference/jsDeclarationEmitExportAssignedFunctionWithExtraTypedefsMembers.js
  tests/baselines/reference/jsDeclarationEmitExportAssignedFunctionWithExtraTypedefsMembers.symbols
  tests/baselines/reference/jsDeclarationEmitExportAssignedFunctionWithExtraTypedefsMembers.types
  tests/cases/compiler/jsDeclarationEmitExportAssignedFunctionWithExtraTypedefsMembers.ts
Labels: For Backlog Bug

#56791 Reduce file system calls during test setup.
  src/compiler/sys.ts
  src/harness/harnessIO.ts
  src/harness/runnerbase.ts
  src/testRunner/compilerRunner.ts
  src/testRunner/fourslashRunner.ts
  src/testRunner/parallel/host.ts
  src/testRunner/projectsRunner.ts
  src/testRunner/runner.ts
Labels: For Backlog Bug

#51236 fix(51225): Go-to-definition on case or default should jump to the containing switch statement if available.
  src/services/findAllReferences.ts
  src/services/goToDefinition.ts
  tests/baselines/reference/goToDefinitionSwitchCase1.baseline.jsonc
  tests/baselines/reference/goToDefinitionSwitchCase2.baseline.jsonc
  tests/baselines/reference/goToDefinitionSwitchCase3.baseline.jsonc
  tests/baselines/reference/goToDefinitionSwitchCase4.baseline.jsonc
  tests/baselines/reference/goToDefinitionSwitchCase5.baseline.jsonc
  tests/baselines/reference/goToDefinitionSwitchCase6.baseline.jsonc
  tests/baselines/reference/goToDefinitionSwitchCase7.baseline.jsonc
  tests/cases/fourslash/goToDefinitionSwitchCase1.ts
  tests/cases/fourslash/goToDefinitionSwitchCase2.ts
  tests/cases/fourslash/goToDefinitionSwitchCase3.ts
  tests/cases/fourslash/goToDefinitionSwitchCase4.ts
  tests/cases/fourslash/goToDefinitionSwitchCase5.ts
  tests/cases/fourslash/goToDefinitionSwitchCase6.ts
  tests/cases/fourslash/goToDefinitionSwitchCase7.ts
Labels: For Uncommitted Bug

#52941 Export internal functions needed by dtsBundler.mjs
  src/compiler/checker.ts
  src/compiler/transformers/declarations.ts
  src/compiler/transformers/es2015.ts
  src/compiler/utilities.ts
  src/compiler/utilitiesPublic.ts
  src/compiler/visitorPublic.ts
  src/services/codefixes/annotateWithTypeFromJSDoc.ts
  src/services/codefixes/helpers.ts
  src/services/refactors/extractSymbol.ts
  src/services/utilities.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#56805 Add types for Object.groupBy() and Map.groupBy()
  src/compiler/commandLineParser.ts
  src/lib/esnext.collection.d.ts
  src/lib/esnext.d.ts
  src/lib/esnext.object.d.ts
  src/lib/libs.json
  tests/baselines/reference/config/commandLineParsing/parseCommandLine/Parse --lib option with extra comma.js
  tests/baselines/reference/config/commandLineParsing/parseCommandLine/Parse --lib option with trailing white-space.js
  tests/baselines/reference/config/commandLineParsing/parseCommandLine/Parse invalid option of library flags.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert empty string option of libs array to compiler-options with json api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert empty string option of libs array to compiler-options with jsonSourceFile api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert empty string option of libs to compiler-options with json api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert empty string option of libs to compiler-options with jsonSourceFile api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert incorrect option of libs to compiler-options with json api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert incorrect option of libs to compiler-options with jsonSourceFile api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert trailing-whitespace string option of libs to compiler-options with json api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert trailing-whitespace string option of libs to compiler-options with jsonSourceFile api.js
  tests/baselines/reference/mapGroupBy.js
  tests/baselines/reference/mapGroupBy.symbols
  tests/baselines/reference/mapGroupBy.types
  tests/baselines/reference/objectGroupBy.errors.txt
  tests/baselines/reference/objectGroupBy.js
  tests/baselines/reference/objectGroupBy.symbols
  tests/baselines/reference/objectGroupBy.types
  tests/baselines/reference/tsc/runWithoutArgs/does-not-add-color-when-NO_COLOR-is-set.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped-when-host-can't-provide-terminal-width.js
  tests/baselines/reference/tsc/runWithoutArgs/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
  tests/baselines/reference/tsserver/telemetry/does-not-expose-paths.js
  tests/baselines/reference/typesVersions.ambientModules.trace.json
  tests/baselines/reference/typesVersions.emptyTypes.trace.json
  tests/baselines/reference/typesVersions.justIndex.trace.json
  tests/baselines/reference/typesVersions.multiFile.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.ambient.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFile.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFileBackReferenceToSelf.trace.json
  tests/baselines/reference/typesVersionsDeclarationEmit.multiFileBackReferenceToUnmapped.trace.json
  tests/cases/compiler/mapGroupBy.ts
  tests/cases/compiler/objectGroupBy.ts
Labels: For Backlog Bug

#56961 Reduce buffer to string conversions.
  src/harness/vfsUtil.ts
Labels: For Backlog Bug

#57020 Do not remove binding alias in function declarations
  src/compiler/checker.ts
  src/compiler/transformers/declarations.ts
  src/compiler/types.ts
  tests/baselines/reference/declarationEmitBindingPatternsFunctionExpr.js
  tests/baselines/reference/declarationEmitBindingPatternsFunctionExpr.symbols
  tests/baselines/reference/declarationEmitBindingPatternsFunctionExpr.types
  tests/baselines/reference/declarationEmitBindingPatternsUnused.errors.txt
  tests/baselines/reference/declarationEmitBindingPatternsUnused.js
  tests/baselines/reference/declarationEmitBindingPatternsUnused.symbols
  tests/baselines/reference/declarationEmitBindingPatternsUnused.types
  tests/baselines/reference/declarationEmitKeywordDestructuring.js
  tests/baselines/reference/destructuringInFunctionType.js
  tests/baselines/reference/paramterDestrcuturingDeclaration.js
  tests/baselines/reference/renamingDestructuredPropertyInFunctionType.js
  tests/cases/compiler/declarationEmitBindingPatternsFunctionExpr.ts
  tests/cases/compiler/declarationEmitBindingPatternsUnused.ts
Labels: For Backlog Bug

#56794 Add `NoInfer<T>` intrinsic represented as special substitution type
  src/compiler/checker.ts
  src/compiler/types.ts
  src/harness/fourslashInterfaceImpl.ts
  src/lib/es5.d.ts
  tests/baselines/reference/noInfer.errors.txt
  tests/baselines/reference/noInfer.js
  tests/baselines/reference/noInfer.symbols
  tests/baselines/reference/noInfer.types
  tests/baselines/reference/noInferRedeclaration.js
  tests/baselines/reference/noInferRedeclaration.symbols
  tests/baselines/reference/noInferRedeclaration.types
  tests/baselines/reference/tsserver/fourslashServer/autoImportProvider_namespaceSameNameAsIntrinsic.js
  tests/cases/conformance/types/typeRelationships/typeInference/noInfer.ts
  tests/cases/conformance/types/typeRelationships/typeInference/noInferRedeclaration.ts
Labels: Author: Team, For Uncommitted Bug

#57070 Fix unnecessary non-null assertions caught by newer ts-eslint
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/harness/client.ts
  src/services/completions.ts
  src/services/documentRegistry.ts
  src/services/utilities.ts
  src/testRunner/unittests/helpers/baseline.ts
  src/testRunner/unittests/tsbuild/outFile.ts
  src/testRunner/unittests/typeParameterIsPossiblyReferenced.ts
Labels: Author: Team, For Uncommitted Bug

#57027 Dom update 2024-01-11
  src/lib/dom.generated.d.ts
  src/lib/dom.iterable.generated.d.ts
  src/lib/webworker.generated.d.ts
  src/lib/webworker.iterable.generated.d.ts
  tests/baselines/reference/globalThisBlockscopedProperties.types
  tests/baselines/reference/identityAndDivergentNormalizedTypes.types
  tests/baselines/reference/mappedTypeRecursiveInference.errors.txt
  tests/baselines/reference/mappedTypeRecursiveInference.types
Labels: Author: Team, For Uncommitted Bug

#57076 Revert "Add numeric constraint to type parameter of mapped types with…
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypeHomomorphicTupleInstantiationNameTypeKeys.symbols
  tests/baselines/reference/mappedTypeHomomorphicTupleInstantiationNameTypeKeys.types
  tests/baselines/reference/mappedTypeTupleConstraintTypeParameterInNameType.symbols
  tests/baselines/reference/mappedTypeTupleConstraintTypeParameterInNameType.types
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty.errors.txt
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty.js
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty.symbols
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty.types
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty2.errors.txt
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty2.js
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty2.symbols
  tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty2.types
  tests/cases/compiler/mappedTypeHomomorphicTupleInstantiationNameTypeKeys.ts
  tests/cases/compiler/mappedTypeTupleConstraintTypeParameterInNameType.ts
  tests/cases/compiler/mappedTypeWithAsClauseAndLateBoundProperty.ts
  tests/cases/compiler/mappedTypeWithAsClauseAndLateBoundProperty2.ts
Labels: Author: Team, For Uncommitted Bug

#57008 Detect binary files by checking first 256 code units for 0xFFFD
  src/compiler/scanner.ts
  src/compiler/types.ts
  tests/baselines/reference/TransportStream.errors.txt
  tests/baselines/reference/TransportStream.js
  tests/baselines/reference/TransportStream.symbols
  tests/baselines/reference/TransportStream.types
  tests/cases/compiler/TransportStream.ts
Labels: Author: Team, For Backlog Bug

#57012 mark the ImportAssertions as deprecated
  src/harness/fourslashInterfaceImpl.ts
  src/lib/es5.d.ts
  tests/baselines/reference/tsserver/fourslashServer/autoImportProvider_namespaceSameNameAsIntrinsic.js
Labels: For Uncommitted Bug

#57051 feat(57028): Support inlining variables that are used in object literal shorthand
  src/services/refactors/inlineVariable.ts
  tests/cases/fourslash/inlineVariableShorthandPropertyAssignment.ts
Labels: For Backlog Bug

#56411 feat(51870): Add a Quick Fix to add an additional parameter to a method or function
  src/compiler/diagnosticMessages.json
  src/services/_namespaces/ts.codefix.ts
  src/services/codefixes/fixAddMissingParam.ts
  tests/cases/fourslash/arityErrorAfterSignatureHelp.ts
  tests/cases/fourslash/codeFixAddMissingParam1.ts
  tests/cases/fourslash/codeFixAddMissingParam10.ts
  tests/cases/fourslash/codeFixAddMissingParam11.ts
  tests/cases/fourslash/codeFixAddMissingParam12.ts
  tests/cases/fourslash/codeFixAddMissingParam13.ts
  tests/cases/fourslash/codeFixAddMissingParam14.ts
  tests/cases/fourslash/codeFixAddMissingParam15.ts
  tests/cases/fourslash/codeFixAddMissingParam16.ts
  tests/cases/fourslash/codeFixAddMissingParam2.ts
  tests/cases/fourslash/codeFixAddMissingParam3.ts
  tests/cases/fourslash/codeFixAddMissingParam4.ts
  tests/cases/fourslash/codeFixAddMissingParam5.ts
  tests/cases/fourslash/codeFixAddMissingParam6.ts
  tests/cases/fourslash/codeFixAddMissingParam7.ts
  tests/cases/fourslash/codeFixAddMissingParam8.ts
  tests/cases/fourslash/codeFixAddMissingParam9.ts
  tests/cases/fourslash/codeFixAddMissingParam_all.ts
  tests/cases/fourslash/codeFixAddOptionalParam1.ts
  tests/cases/fourslash/codeFixAddOptionalParam10.ts
  tests/cases/fourslash/codeFixAddOptionalParam11.ts
  tests/cases/fourslash/codeFixAddOptionalParam12.ts
  tests/cases/fourslash/codeFixAddOptionalParam13.ts
  tests/cases/fourslash/codeFixAddOptionalParam14.ts
  tests/cases/fourslash/codeFixAddOptionalParam15.ts
  tests/cases/fourslash/codeFixAddOptionalParam16.ts
  tests/cases/fourslash/codeFixAddOptionalParam17.ts
  tests/cases/fourslash/codeFixAddOptionalParam18.ts
  tests/cases/fourslash/codeFixAddOptionalParam2.ts
  tests/cases/fourslash/codeFixAddOptionalParam3.ts
  tests/cases/fourslash/codeFixAddOptionalParam4.ts
  tests/cases/fourslash/codeFixAddOptionalParam5.ts
  tests/cases/fourslash/codeFixAddOptionalParam6.ts
  tests/cases/fourslash/codeFixAddOptionalParam7.ts
  tests/cases/fourslash/codeFixAddOptionalParam8.ts
  tests/cases/fourslash/codeFixAddOptionalParam9.ts
  tests/cases/fourslash/codeFixAddOptionalParam_all.ts
  tests/cases/fourslash/codeFixInferFromUsageCallBodyBoth.ts
Labels: For Uncommitted Bug

#57092 Revert "Fixed apparent type of homomorphic mapped type with non-homomorphic instantiation (#56727)" and add test
  src/compiler/checker.ts
  tests/baselines/reference/homomorphicMappedTypeWithNonHomomorphicInstantiationSpreadable1.symbols
  tests/baselines/reference/homomorphicMappedTypeWithNonHomomorphicInstantiationSpreadable1.types
  tests/baselines/reference/nestedHomomorphicMappedTypesWithArrayConstraint1.symbols
  tests/baselines/reference/nestedHomomorphicMappedTypesWithArrayConstraint1.types
  tests/cases/compiler/homomorphicMappedTypeWithNonHomomorphicInstantiationSpreadable1.ts
  tests/cases/compiler/nestedHomomorphicMappedTypesWithArrayConstraint1.ts
Labels: Author: Team, For Uncommitted Bug

#57031 Revise mapped tuple type instantiation logic
  src/compiler/checker.ts
  tests/baselines/reference/circularInlineMappedGenericTupleTypeNoCrash.errors.txt
  tests/baselines/reference/circularInlineMappedGenericTupleTypeNoCrash.types
  tests/baselines/reference/mappedTypesGenericTuples.symbols
  tests/baselines/reference/mappedTypesGenericTuples.types
  tests/baselines/reference/variadicTuples2.errors.txt
  tests/baselines/reference/variadicTuples2.js
  tests/baselines/reference/variadicTuples2.symbols
  tests/baselines/reference/variadicTuples2.types
  tests/cases/conformance/types/mapped/mappedTypesGenericTuples.ts
  tests/cases/conformance/types/tuple/variadicTuples2.ts
Labels: Author: Team, For Milestone Bug

#57090 Allow `autoImportFileExcludePatterns` to match anywhere in the file path
  src/compiler/utilities.ts
  src/services/exportInfoMap.ts
  tests/baselines/reference/tsserver/fourslashServer/autoImportFileExcludePatterns2.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportFileExcludePatterns_networkPaths.js
  tests/baselines/reference/tsserver/fourslashServer/autoImportFileExcludePatterns_windowsPaths.js
  tests/cases/fourslash/server/autoImportFileExcludePatterns2.ts
  tests/cases/fourslash/server/autoImportFileExcludePatterns_networkPaths.ts
  tests/cases/fourslash/server/autoImportFileExcludePatterns_windowsPaths.ts
Labels: Author: Team, For Milestone Bug

#56561 Update dependencies to latest compatible versions
  .dprint.jsonc
  .eslint-plugin-local.cjs
  Herebyfile.mjs
  package-lock.json
  package.json
  scripts/dtsBundler.mjs
  scripts/errorCheck.mjs
  scripts/produceLKG.mjs
  src/cancellationToken/cancellationToken.ts
  src/compiler/checker.ts
  src/compiler/moduleNameResolver.ts
  src/compiler/program.ts
  src/compiler/utilitiesPublic.ts
  src/server/editorServices.ts
  src/services/findAllReferences.ts
Labels: Author: Team, For Uncommitted Bug

#56918 Fixed error spans for `SatisfiesExpression` check nodes
  src/compiler/checker.ts
  tests/baselines/reference/typeSatisfaction_errorLocations1.errors.txt
  tests/baselines/reference/typeSatisfaction_errorLocations1.symbols
  tests/baselines/reference/typeSatisfaction_errorLocations1.types
  tests/cases/conformance/expressions/typeSatisfaction/typeSatisfaction_errorLocations1.ts
Labels: For Milestone Bug

#57093 No number constraint to mapped type with as clause
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypeWithNameClauseAppliedToArrayType.symbols
  tests/baselines/reference/mappedTypeWithNameClauseAppliedToArrayType.types
  tests/cases/compiler/mappedTypeWithNameClauseAppliedToArrayType.ts
Labels: Author: Team, For Milestone Bug

#56932 Exposed `TypeChecker.resolveName` API to public along with `SymbolFlags.All`
  src/compiler/types.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Uncommitted Bug

#57125 Fix release branch creation
  .github/workflows/new-release-branch.yaml
Labels: Author: Team, For Uncommitted Bug

#57128 Remove use of deprecated context.parserServices
  scripts/eslint/rules/argument-trivia.cjs
Labels: Author: Team, For Uncommitted Bug

#57145 Deprioritize declaration emit paths from baseUrl containing node_modules
  src/compiler/moduleSpecifiers.ts
  tests/baselines/reference/declarationEmitMonorepoBaseUrl.js
  tests/cases/compiler/declarationEmitMonorepoBaseUrl.ts
Labels: Author: Team, For Uncommitted Bug

#57148 Fix isolatedModules check for export assignments
  src/compiler/checker.ts
  tests/baselines/reference/exportDeclaration(isolatedmodules=true).errors.txt
  tests/cases/compiler/isolatedModulesReExportAlias.ts
Labels: Author: Team, For Milestone Bug

#57160 Revert #54477 but keep the tests
  src/compiler/checker.ts
  tests/baselines/reference/arrayFrom.types
  tests/baselines/reference/circularReferenceInReturnType.errors.txt
  tests/baselines/reference/circularReferenceInReturnType.symbols
  tests/baselines/reference/circularReferenceInReturnType.types
  tests/baselines/reference/circularReferenceInReturnType2.errors.txt
  tests/baselines/reference/circularReferenceInReturnType2.symbols
  tests/baselines/reference/circularReferenceInReturnType2.types
  tests/cases/compiler/circularReferenceInReturnType.ts
  tests/cases/compiler/circularReferenceInReturnType2.ts
Labels: Author: Team, For Uncommitted Bug

#57158 Fix ReloadRequest in protocol found while updating to use session in tests
  src/server/protocol.ts
  src/testRunner/unittests/tsserver/autoImportProvider.ts
  src/testRunner/unittests/tsserver/projectErrors.ts
  src/testRunner/unittests/tsserver/projectReferences.ts
  src/testRunner/unittests/tsserver/projects.ts
  src/testRunner/unittests/tsserver/reload.ts
  src/testRunner/unittests/tsserver/symlinkCache.ts
  src/testRunner/unittests/tsserver/typingsInstaller.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/tsserver/projectReferences/ancestor-and-project-ref-management.js
  tests/baselines/reference/tsserver/projectReferences/disables-looking-into-the-child-project-if-disableReferencedProjectLoad-is-set-in-first-indirect-project-but-not-in-another-one.js
  tests/baselines/reference/tsserver/projectReferences/disables-looking-into-the-child-project-if-disableReferencedProjectLoad-is-set-in-indirect-project.js
  tests/baselines/reference/tsserver/projectReferences/disables-looking-into-the-child-project-if-disableReferencedProjectLoad-is-set.js
  tests/baselines/reference/tsserver/projectReferences/does-not-error-on-container-only-project.js
  tests/baselines/reference/tsserver/projectReferences/project-is-directly-referenced-by-solution.js
  tests/baselines/reference/tsserver/projectReferences/project-is-indirectly-referenced-by-solution.js
  tests/baselines/reference/tsserver/projectReferences/solution-with-its-own-files-and-disables-looking-into-the-child-project-if-disableReferencedProjectLoad-is-set-in-first-indirect-project-but-not-in-another-one.js
  tests/baselines/reference/tsserver/projectReferences/solution-with-its-own-files-and-disables-looking-into-the-child-project-if-disableReferencedProjectLoad-is-set-in-indirect-project.js
  tests/baselines/reference/tsserver/projectReferences/solution-with-its-own-files-and-disables-looking-into-the-child-project-if-disableReferencedProjectLoad-is-set.js
  tests/baselines/reference/tsserver/projectReferences/solution-with-its-own-files-and-project-found-is-not-solution-but-references-open-file-through-project-reference.js
  tests/baselines/reference/tsserver/projectReferences/solution-with-its-own-files-and-project-is-indirectly-referenced-by-solution.js
Labels: Author: Team, For Uncommitted Bug

#57197 Properly handle non-generic string mapping types in unions and intersections
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/stringMappingReduction.symbols
  tests/baselines/reference/stringMappingReduction.types
  tests/baselines/reference/templateLiteralTypes3.types
  tests/cases/conformance/types/literal/stringMappingReduction.ts
Labels: Author: Team, For Milestone Bug

#57123 enable `@typescript-eslint/no-unused-vars`
  .eslintrc.json
  scripts/eslint/rules/argument-trivia.cjs
  scripts/eslint/rules/debug-assert.cjs
  scripts/eslint/rules/jsdoc-format.cjs
  scripts/eslint/rules/no-in-operator.cjs
  scripts/eslint/rules/no-keywords.cjs
  scripts/eslint/rules/only-arrow-functions.cjs
  scripts/tsconfig.json
  src/compiler/core.ts
  src/compiler/emitter.ts
  src/compiler/factory/utilities.ts
  src/compiler/moduleNameResolver.ts
  src/compiler/watchPublic.ts
  src/server/editorServices.ts
  src/services/codefixes/fixAddMissingConstraint.ts
  src/services/codefixes/fixNaNEquality.ts
  src/services/refactors/moveToFile.ts
  src/tsconfig-base.json
Labels: For Backlog Bug

#57202 Revert "Always substitute indexed generic mapped type when getting constraint from indexed access"
  src/compiler/checker.ts
  tests/baselines/reference/mappedTypeConstraints2.errors.txt
  tests/baselines/reference/mappedTypeConstraints2.js
  tests/baselines/reference/mappedTypeConstraints2.symbols
  tests/baselines/reference/mappedTypeConstraints2.types
  tests/cases/conformance/types/mapped/mappedTypeConstraints2.ts
Labels: For Uncommitted Bug

#57216 Update to esbuild 0.20
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#57132 fix57127: remove linkedediting from cases where JSX tags are not closed
  src/services/services.ts
  tests/baselines/reference/linkedEditingJsxTag10.linkedEditing.txt
  tests/baselines/reference/linkedEditingJsxTag12.linkedEditing.txt
  tests/cases/fourslash/linkedEditingJsxTag10.ts
  tests/cases/fourslash/linkedEditingJsxTag12.ts
Labels: Author: Team, For Milestone Bug

#57243 Update README.md
  README.md
Labels: For Uncommitted Bug

#57176 Fix missing error for accessing type-only `export *` member through namespace
  src/compiler/checker.ts
  tests/baselines/reference/exportNamespace11.errors.txt
  tests/baselines/reference/exportNamespace11.js
  tests/baselines/reference/exportNamespace11.symbols
  tests/baselines/reference/exportNamespace11.types
  tests/baselines/reference/exportNamespace12.errors.txt
  tests/baselines/reference/exportNamespace12.js
  tests/baselines/reference/exportNamespace12.symbols
  tests/baselines/reference/exportNamespace12.types
  tests/cases/conformance/externalModules/typeOnly/exportNamespace11.ts
  tests/cases/conformance/externalModules/typeOnly/exportNamespace12.ts
Labels: Author: Team, For Milestone Bug

#57223 Looser import/export elision blocking in visitElidableStatement
  src/compiler/transformers/ts.ts
  src/testRunner/unittests/customTransforms.ts
  tests/baselines/reference/customTransforms/importDeclarationBeforeTransformElision.js
Labels: Author: Team, For Milestone Bug
