Repository microsoft/TypeScript, pull requests merged in 2024-09, with the labels that each got.

#59837 Add missing `index` parameter to the `Array.fromAsync`'s `mapFn`
  src/lib/esnext.array.d.ts
  tests/baselines/reference/arrayFromAsync.js
  tests/baselines/reference/arrayFromAsync.symbols
  tests/baselines/reference/arrayFromAsync.types
  tests/cases/compiler/arrayFromAsync.ts
Labels: For Uncommitted Bug

#59793 Revert "Allow variance annotations on generic references (#56418)"
  src/compiler/checker.ts
  tests/baselines/reference/varianceReferences.errors.txt
  tests/baselines/reference/varianceReferences.js
  tests/baselines/reference/varianceReferences.symbols
  tests/baselines/reference/varianceReferences.types
  tests/cases/compiler/varianceReferences.ts
Labels: For Uncommitted Bug

#59871 Fix the incorrect copy over for watchOptions and fix order of watches for referenced projects
  src/compiler/commandLineParser.ts
  src/compiler/watchPublic.ts
  src/testRunner/unittests/tscWatch/projectsWithReferences.ts
  tests/baselines/reference/tscWatch/programUpdates/when-new-file-is-added-to-the-referenced-project.js
  tests/baselines/reference/tscWatch/projectsWithReferences/watch-options-differing-between-projects.js
  tests/baselines/reference/tscWatch/watchApi/when-new-file-is-added-to-the-referenced-project-with-host-implementing-getParsedCommandLine-without-implementing-useSourceOfProjectReferenceRedirect.js
  tests/baselines/reference/tscWatch/watchApi/when-new-file-is-added-to-the-referenced-project-with-host-implementing-getParsedCommandLine.js
  tests/baselines/reference/tscWatch/watchApi/when-watching-referenced-project-when-there-is-no-config-file-name.js
  tests/baselines/reference/tscWatch/watchApi/when-watching-referenced-project-with-extends-when-there-is-no-config-file-name.js
Labels: Author: Team, For Uncommitted Bug

#59852 Support importHelpers with module:preserve
  src/compiler/factory/utilities.ts
  src/compiler/transformers/module/esnextAnd2015.ts
  src/compiler/transformers/utilities.ts
  tests/baselines/reference/importHelpersVerbatimModuleSyntax.js
  tests/baselines/reference/modulePreserveImportHelpers.js
  tests/baselines/reference/modulePreserveImportHelpers.symbols
  tests/baselines/reference/modulePreserveImportHelpers.types
  tests/cases/compiler/modulePreserveImportHelpers.ts
Labels: Author: Team, For Milestone Bug

#59875 Make "/home/src/workspaces/project" as default current directory without having to specify it for tsc tests
  src/testRunner/unittests/helpers/declarationEmit.ts
  src/testRunner/unittests/helpers/noCheck.ts
  src/testRunner/unittests/helpers/noEmit.ts
  src/testRunner/unittests/helpers/virtualFileSystemWithWatch.ts
  src/testRunner/unittests/tsbuild/commandLine.ts
  src/testRunner/unittests/tsbuild/configFileErrors.ts
  src/testRunner/unittests/tsbuild/declarationEmit.ts
  src/testRunner/unittests/tsbuild/emitDeclarationOnly.ts
  src/testRunner/unittests/tsbuild/exitCodeOnBogusFile.ts
  src/testRunner/unittests/tsbuild/graphOrdering.ts
  src/testRunner/unittests/tsbuild/inferredTypeFromTransitiveModule.ts
  src/testRunner/unittests/tsbuild/lateBoundSymbol.ts
  src/testRunner/unittests/tsbuild/moduleResolution.ts
  src/testRunner/unittests/tsbuild/outputPaths.ts
  src/testRunner/unittests/tsbuild/roots.ts
  src/testRunner/unittests/tsbuild/sample.ts
  src/testRunner/unittests/tsc/composite.ts
  src/testRunner/unittests/tsc/incremental.ts
  src/testRunner/unittests/tsc/libraryResolution.ts
  src/testRunner/unittests/tsc/listFilesOnly.ts
  src/testRunner/unittests/tsc/moduleResolution.ts
  src/testRunner/unittests/tsc/noEmit.ts
  src/testRunner/unittests/tsc/noEmitOnError.ts
  src/testRunner/unittests/tsc/projectReferences.ts
  src/testRunner/unittests/tsc/projectReferencesConfig.ts
  src/testRunner/unittests/tsc/redirect.ts
  src/testRunner/unittests/tsc/runWithoutArgs.ts
  src/testRunner/unittests/tscWatch/listFilesOnly.ts
  src/testRunner/unittests/tscWatch/moduleResolution.ts
Labels: Author: Team, For Uncommitted Bug

#59882 We may not always get file notifications for file creation, so always check for failed lookups starting with the path as well as exact path
  src/compiler/resolutionCache.ts
  src/testRunner/unittests/tscWatch/resolutionCache.ts
  tests/baselines/reference/tscWatch/resolutionCache/when-dir-watcher-is-invoked-without-file-change.js
Labels: Author: Team, For Milestone Bug

#59874 Updates to --build parsing on command line
  src/compiler/commandLineParser.ts
  src/compiler/executeCommandLine.ts
  src/testRunner/tests.ts
  src/testRunner/unittests/config/commandLineParsing.ts
  src/testRunner/unittests/helpers/baseline.ts
  src/testRunner/unittests/tsbuild/commandLine.ts
  src/testRunner/unittests/tsc/commandLine.ts
  src/testRunner/unittests/tscWatch/incremental.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/config/commandLineParsing/parseCommandLine/Handles may only be used with --build flags.js
  tests/baselines/reference/config/showConfig/Shows tsconfig for single option/build/tsconfig.json
  tests/baselines/reference/tsbuild/commandLine/help.js
  tests/baselines/reference/tsc/commandLine/does-not-add-color-when-NO_COLOR-is-set.js
  tests/baselines/reference/tsc/commandLine/help-all.js
  tests/baselines/reference/tsc/commandLine/help.js
  tests/baselines/reference/tsc/commandLine/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped-when-host-can't-provide-terminal-width.js
  tests/baselines/reference/tsc/commandLine/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
  tests/baselines/reference/tsc/commandLine/when-build-not-first-argument.js
Labels: Author: Team, For Milestone Bug

#56543 Include all type parameters in completions within type parameters' constraints
  src/services/completions.ts
  tests/cases/fourslash/completionsForLatterTypeParametersInConstraints1.ts
  tests/cases/fourslash/completionsForSelfTypeParameterInConstraint1.ts
  tests/cases/fourslash/noCompletionsForCurrentOrLaterParametersInDefaults.ts
Labels: For Backlog Bug

#59885 add support for autoimports/moveToFile to generate aliased named imports
  src/services/codefixes/importFixes.ts
  tests/cases/fourslash/moveToFile_alias.ts
  tests/cases/fourslash/moveToFile_alias2.ts
  tests/cases/fourslash/moveToFile_alias3.ts
  tests/cases/fourslash/moveToNewFile_alias.ts
Labels: Author: Team, For Milestone Bug

#59665 Drop unnecessary type arguments in the isolated declarations quick fix
  src/compiler/checker.ts
  src/compiler/types.ts
  src/services/codefixes/fixMissingTypeAnnotationOnExports.ts
  src/services/codefixes/helpers.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports50-generics-with-default.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports51-slightly-more-complex-generics-with-default.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports52-generics-oversimplification.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports53-nested-generic-types.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports54-generator-generics.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports55-generator-return.ts
Labels: For Backlog Bug

#59960 Remove tsbuildInfo specification error now that we need it for non incremental scenarios as well and there is no way to disable it
  src/compiler/diagnosticMessages.json
  src/compiler/emitter.ts
  src/compiler/program.ts
  tests/baselines/reference/optionsTsBuildInfoFileWithoutIncrementalAndComposite.errors.txt
  tests/baselines/reference/tsc/composite/when-setting-composite-false-on-command-line-but-has-tsbuild-info-in-config.js
Labels: Author: Team, For Uncommitted Bug

#60009 Replace `Debug.checkDefined` to avoid redundant debugger stops
  src/testRunner/unittests/helpers/virtualFileSystemWithWatch.ts
Labels: For Uncommitted Bug

#59889 Fixed a crash when trying to find references on `NoSubstitutionTemplateLiteral` with `LiteralType` parent
  src/compiler/utilities.ts
  tests/baselines/reference/findAllRefsNoSubstitutionTemplateLiteralNoCrash1.baseline.jsonc
  tests/cases/fourslash/findAllRefsNoSubstitutionTemplateLiteralNoCrash1.ts
Labels: For Milestone Bug

#59931 Cache instantiation expression types early enough to prevent reentrancy during printback
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/instantiationExpressionErrorNoCrash.errors.txt
  tests/baselines/reference/instantiationExpressionErrorNoCrash.js
  tests/baselines/reference/instantiationExpressionErrorNoCrash.symbols
  tests/baselines/reference/instantiationExpressionErrorNoCrash.types
  tests/baselines/reference/instantiationExpressionErrors.types
  tests/cases/compiler/instantiationExpressionErrorNoCrash.ts
Labels: Author: Team, For Milestone Bug

#59860 Support interpreting non-literal computed properties in classes as implicit index signatures
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/transformers/declarations.ts
  src/compiler/types.ts
  tests/baselines/reference/ES5SymbolProperty2.types
  tests/baselines/reference/ES5SymbolProperty3.types
  tests/baselines/reference/ES5SymbolProperty4.types
  tests/baselines/reference/ES5SymbolProperty5.errors.txt
  tests/baselines/reference/ES5SymbolProperty5.types
  tests/baselines/reference/ES5SymbolProperty6.types
  tests/baselines/reference/ES5SymbolProperty7.types
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/classNonUniqueSymbolMethodHasSymbolIndexer.js
  tests/baselines/reference/classNonUniqueSymbolMethodHasSymbolIndexer.symbols
  tests/baselines/reference/classNonUniqueSymbolMethodHasSymbolIndexer.types
  tests/baselines/reference/complicatedPrivacy.types
  tests/baselines/reference/computedPropertyNames12_ES5.errors.txt
  tests/baselines/reference/computedPropertyNames12_ES6.errors.txt
  tests/baselines/reference/declarationEmitAnyComputedPropertyInClass.js
  tests/baselines/reference/declarationEmitComputedPropertyNameEnum2.types
  tests/baselines/reference/parserComputedPropertyName13.types
  tests/baselines/reference/parserComputedPropertyName14.types
  tests/baselines/reference/parserComputedPropertyName18.types
  tests/baselines/reference/parserComputedPropertyName19.types
  tests/baselines/reference/parserES5ComputedPropertyName8.types
  tests/baselines/reference/parserES5SymbolProperty8.types
  tests/baselines/reference/parserES5SymbolProperty9.types
  tests/baselines/reference/propertyAssignment.types
  tests/baselines/reference/superSymbolIndexedAccess1.types
  tests/baselines/reference/superSymbolIndexedAccess5.types
  tests/baselines/reference/superSymbolIndexedAccess6.types
  tests/baselines/reference/transpile/declarationComputedPropertyNames.d.ts
  tests/cases/compiler/classNonUniqueSymbolMethodHasSymbolIndexer.ts
  tests/cases/fourslash/quickInfoInInvalidIndexSignature.ts
Labels: Breaking Change, Author: Team, For Uncommitted Bug

#58870 Specialize the message on JSX tags looking for the JSX factory namespace
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/services/codefixes/fixCannotFindModule.ts
  src/services/codefixes/importFixes.ts
  tests/baselines/reference/commentsOnJSXExpressionsArePreserved(jsx=react,module=commonjs,moduledetection=auto).errors.txt
  tests/baselines/reference/commentsOnJSXExpressionsArePreserved(jsx=react,module=commonjs,moduledetection=force).errors.txt
  tests/baselines/reference/commentsOnJSXExpressionsArePreserved(jsx=react,module=commonjs,moduledetection=legacy).errors.txt
  tests/baselines/reference/commentsOnJSXExpressionsArePreserved(jsx=react,module=system,moduledetection=auto).errors.txt
  tests/baselines/reference/commentsOnJSXExpressionsArePreserved(jsx=react,module=system,moduledetection=force).errors.txt
  tests/baselines/reference/commentsOnJSXExpressionsArePreserved(jsx=react,module=system,moduledetection=legacy).errors.txt
  tests/baselines/reference/commentsOnJSXExpressionsArePreserved(jsx=react-jsx,module=commonjs,moduledetection=auto).errors.txt
  tests/baselines/reference/commentsOnJSXExpressionsArePreserved(jsx=react-jsx,module=commonjs,moduledetection=force).errors.txt
  tests/baselines/reference/commentsOnJSXExpressionsArePreserved(jsx=react-jsx,module=commonjs,moduledetection=legacy).errors.txt
  tests/baselines/reference/commentsOnJSXExpressionsArePreserved(jsx=react-jsxdev,module=commonjs,moduledetection=auto).errors.txt
  tests/baselines/reference/commentsOnJSXExpressionsArePreserved(jsx=react-jsxdev,module=commonjs,moduledetection=force).errors.txt
  tests/baselines/reference/commentsOnJSXExpressionsArePreserved(jsx=react-jsxdev,module=commonjs,moduledetection=legacy).errors.txt
  tests/baselines/reference/inlineJsxAndJsxFragPragma.errors.txt
  tests/baselines/reference/inlineJsxFactoryWithFragmentIsError.errors.txt
  tests/baselines/reference/jsxFactoryMissingErrorInsideAClass.errors.txt
  tests/baselines/reference/jsxFactoryNotIdentifierOrQualifiedName.errors.txt
  tests/baselines/reference/jsxFactoryNotIdentifierOrQualifiedName2.errors.txt
  tests/baselines/reference/jsxImportSourceNonPragmaComment.errors.txt
  tests/baselines/reference/jsxJsxsCjsTransformCustomImport(jsx=react-jsx).errors.txt
  tests/baselines/reference/jsxJsxsCjsTransformCustomImport(jsx=react-jsxdev).errors.txt
  tests/baselines/reference/jsxJsxsCjsTransformCustomImportPragma(jsx=react-jsx).errors.txt
  tests/baselines/reference/jsxJsxsCjsTransformCustomImportPragma(jsx=react-jsxdev).errors.txt
  tests/baselines/reference/jsxJsxsCjsTransformKeyPropCustomImport(jsx=react-jsx).errors.txt
  tests/baselines/reference/jsxJsxsCjsTransformKeyPropCustomImport(jsx=react-jsxdev).errors.txt
  tests/baselines/reference/jsxJsxsCjsTransformKeyPropCustomImportPragma(jsx=react-jsx).errors.txt
  tests/baselines/reference/jsxJsxsCjsTransformKeyPropCustomImportPragma(jsx=react-jsxdev).errors.txt
  tests/baselines/reference/quickIntersectionCheckCorrectlyCachesErrors.errors.txt
  tests/baselines/reference/reactNamespaceInvalidInput.errors.txt
  tests/baselines/reference/reactNamespaceMissingDeclaration.errors.txt
  tests/baselines/reference/tscWatch/incremental/jsxImportSource-backing-types-added-incremental.js
  tests/baselines/reference/tscWatch/incremental/jsxImportSource-backing-types-added-watch.js
  tests/baselines/reference/tscWatch/incremental/jsxImportSource-backing-types-removed-incremental.js
  tests/baselines/reference/tscWatch/incremental/jsxImportSource-backing-types-removed-watch.js
  tests/baselines/reference/tsxErrorRecovery3.errors.txt
  tests/baselines/reference/tsxReactEmit7.errors.txt
  tests/baselines/reference/tsxSpreadChildrenInvalidType(jsx=react-jsx,target=es5).errors.txt
  tests/cases/fourslash/codeFixCannotFindModuleJsxRuntime01.ts
  tests/cases/fourslash/codeFixCannotFindModuleJsxRuntimePragma01.ts
Labels: Author: Team, For Uncommitted Bug

#60019 Validate JSON imports into ESM in `--module nodenext`
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/parser.ts
  tests/baselines/reference/nodeModulesJson.errors.txt
  tests/baselines/reference/nodeModulesJson.symbols
  tests/baselines/reference/nodeModulesJson.types
  tests/baselines/reference/nodeModulesResolveJsonModule(module=node16).errors.txt
  tests/baselines/reference/nodeModulesResolveJsonModule(module=node16).js
  tests/baselines/reference/nodeModulesResolveJsonModule(module=node16).symbols
  tests/baselines/reference/nodeModulesResolveJsonModule(module=node16).types
  tests/baselines/reference/nodeModulesResolveJsonModule(module=nodenext).js
  tests/baselines/reference/nodeModulesResolveJsonModule(module=nodenext).symbols
  tests/baselines/reference/nodeModulesResolveJsonModule(module=nodenext).types
  tests/cases/conformance/node/nodeModulesJson.ts
  tests/cases/conformance/node/nodeModulesResolveJsonModule.ts
Labels: Breaking Change, Author: Team, For Milestone Bug

#60049 Fix incorrect mode calculation in typereference resolution
  src/compiler/program.ts
Labels: Author: Team, For Uncommitted Bug

#60013 Fixed crash when resolving a symbol on invalid private identifier in type reference
  src/compiler/checker.ts
  tests/cases/fourslash/quickInfoPrivateIdentifierInTypeReferenceNoCrash1.ts
Labels: For Uncommitted Bug

#60027 Fixed crash when looking for contextual inherited JSDocs for setters and getters
  src/services/services.ts
  tests/cases/fourslash/quickInfoJsDocGetterSetterNoCrash1.ts
Labels: For Uncommitted Bug

#58440 Fixed incorrect `SignatureFlags.HasRestParameter` propagation when combining signatures
  src/compiler/checker.ts
  tests/baselines/reference/signatureCombiningRestParameters1.errors.txt
  tests/baselines/reference/signatureCombiningRestParameters1.symbols
  tests/baselines/reference/signatureCombiningRestParameters1.types
  tests/baselines/reference/signatureCombiningRestParameters2.symbols
  tests/baselines/reference/signatureCombiningRestParameters2.types
  tests/baselines/reference/signatureCombiningRestParameters3.errors.txt
  tests/baselines/reference/signatureCombiningRestParameters3.symbols
  tests/baselines/reference/signatureCombiningRestParameters3.types
  tests/baselines/reference/signatureCombiningRestParameters4.errors.txt
  tests/baselines/reference/signatureCombiningRestParameters4.symbols
  tests/baselines/reference/signatureCombiningRestParameters4.types
  tests/baselines/reference/signatureCombiningRestParameters5.errors.txt
  tests/baselines/reference/signatureCombiningRestParameters5.symbols
  tests/baselines/reference/signatureCombiningRestParameters5.types
  tests/cases/compiler/signatureCombiningRestParameters1.ts
  tests/cases/compiler/signatureCombiningRestParameters2.ts
  tests/cases/compiler/signatureCombiningRestParameters3.ts
  tests/cases/compiler/signatureCombiningRestParameters4.ts
  tests/cases/compiler/signatureCombiningRestParameters5.ts
  tests/cases/fourslash/quickInfoContextuallyTypedSignatureOptionalParameterFromIntersection1.ts
Labels: For Milestone Bug

#60011 Fix JSDoc @import resolution in `--moduleResolution bundler`
  src/compiler/checker.ts
  tests/baselines/reference/importTag22.errors.txt
  tests/cases/conformance/jsdoc/importTag21.ts
  tests/cases/conformance/jsdoc/importTag22.ts
Labels: Author: Team, For Milestone Bug

#60034 Fix occasional silent error emit for JSDoc declaration emit and overzealous node serialization of jsdoc optional parameters.
  src/compiler/checker.ts
  src/compiler/transformers/declarations.ts
  src/compiler/types.ts
  tests/baselines/reference/contextuallyTypedParametersOptionalInJSDoc.types
  tests/baselines/reference/contravariantOnlyInferenceWithAnnotatedOptionalParameterJs.types
  tests/baselines/reference/jsDocDeclarationEmitDoesNotUseNodeModulesPathWithoutError.js
  tests/baselines/reference/jsDocDeclarationEmitDoesNotUseNodeModulesPathWithoutError.symbols
  tests/baselines/reference/jsDocDeclarationEmitDoesNotUseNodeModulesPathWithoutError.types
  tests/baselines/reference/paramTagBracketsAddOptionalUndefined.types
  tests/cases/compiler/jsDocDeclarationEmitDoesNotUseNodeModulesPathWithoutError.ts
Labels: Domain: JSDoc, Domain: Declaration Emit, Author: Team, For Milestone Bug

#60053 Adding preparePasteEdits method to check if smart copy/paste should be applied
  src/harness/client.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/server/protocol.ts
  src/server/session.ts
  src/services/_namespaces/ts.preparePasteEdits.ts
  src/services/_namespaces/ts.ts
  src/services/preparePasteEdits.ts
  src/services/refactors/moveToFile.ts
  src/services/services.ts
  src/services/types.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/preparePasteEdits_multipleLocations.ts
  tests/cases/fourslash/preparePasteEdits_resolvedIdentifiers.ts
  tests/cases/fourslash/preparePasteEdits_resolvedTypeParameters.ts
  tests/cases/fourslash/preparePasteEdits_returnFalse.ts
Labels: Author: Team, For Uncommitted Bug

#60075 Unexport NodeTypingsInstaller in typingsInstaller.js
  src/typingsInstaller/nodeTypingsInstaller.ts
Labels: Author: Team, For Uncommitted Bug

#59661 Report implict any error when widening null/undefined in presence of …
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/generatorReturnTypeInferenceNonStrict.errors.txt
  tests/baselines/reference/generatorTypeCheck62.errors.txt
  tests/baselines/reference/implicitAnyGenericTypeInference.errors.txt
  tests/baselines/reference/implicitAnyGenericTypeInference.js
  tests/baselines/reference/implicitAnyGenericTypeInference.symbols
  tests/baselines/reference/implicitAnyGenericTypeInference.types
  tests/cases/compiler/implicitAnyGenericTypeInference.ts
Labels: Author: Team, For Milestone Bug

#59720 Enable Node.js/v8 compile caching via entrypoint shims
  Herebyfile.mjs
  scripts/produceLKG.mjs
Labels: Author: Team, For Uncommitted Bug

#59276 Simplify statSync
  src/compiler/sys.ts
Labels: Author: Team, For Uncommitted Bug

#60078 Make noCheck non-internal on CompilerOptions
  src/compiler/types.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#59963 Add CopilotRelated command
  src/harness/client.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/server/protocol.ts
  src/server/session.ts
  src/services/services.ts
  src/services/types.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/getImportsDuplicate.ts
  tests/cases/fourslash/getImportsDynamic.ts
  tests/cases/fourslash/getImportsJSXFactory.ts
  tests/cases/fourslash/getImportsNone.ts
  tests/cases/fourslash/getImportsOne.ts
  tests/cases/fourslash/getImportsOneJs.ts
  tests/cases/fourslash/getImportsReexport.ts
  tests/cases/fourslash/getImportsTslib.ts
Labels: Author: Team, For Uncommitted Bug

#59767 Rewrite relative import extensions with flag
  src/compiler/checker.ts
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  src/compiler/factory/emitHelpers.ts
  src/compiler/moduleNameResolver.ts
  src/compiler/program.ts
  src/compiler/transformers/module/esnextAnd2015.ts
  src/compiler/transformers/module/module.ts
  src/compiler/transformers/ts.ts
  src/compiler/transformers/utilities.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/compiler/utilitiesPublic.ts
  src/services/utilities.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/cjsErrors.errors.txt
  tests/baselines/reference/cjsErrors.js
  tests/baselines/reference/config/initTSConfig/Default initialized TSConfig/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with --help/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with --watch/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with advanced options/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with boolean value compiler options/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with enum value compiler options/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with files options/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with incorrect compiler option value/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with incorrect compiler option/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with list compiler options with enum value/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with list compiler options/tsconfig.json
  tests/baselines/reference/config/showConfig/Shows tsconfig for single option/rewriteRelativeImportExtensions/tsconfig.json
  tests/baselines/reference/emit(jsx=preserve).errors.txt
  tests/baselines/reference/emit(jsx=preserve).js
  tests/baselines/reference/emit(jsx=react).errors.txt
  tests/baselines/reference/emit(jsx=react).js
  tests/baselines/reference/emitModuleCommonJS(module=commonjs).errors.txt
  tests/baselines/reference/emitModuleCommonJS(module=commonjs).js
  tests/baselines/reference/emitModuleCommonJS(module=nodenext).errors.txt
  tests/baselines/reference/emitModuleCommonJS(module=nodenext).js
  tests/baselines/reference/packageJsonImportsErrors.errors.txt
  tests/baselines/reference/packageJsonImportsErrors.js
  tests/baselines/reference/rewriteRelativeImportExtensionsProjectReferences1.baseline
  tests/baselines/reference/rewriteRelativeImportExtensionsProjectReferences2.baseline
  tests/baselines/reference/rewriteRelativeImportExtensionsProjectReferences3.baseline
  tests/baselines/reference/tsc/commandLine/help-all.js
  tests/baselines/reference/tsserver/fourslashServer/rewriteRelativeImportExtensionsProjectReferences1.js
  tests/baselines/reference/tsserver/fourslashServer/rewriteRelativeImportExtensionsProjectReferences2.js
  tests/baselines/reference/tsserver/fourslashServer/rewriteRelativeImportExtensionsProjectReferences3.js
  tests/cases/conformance/externalModules/rewriteRelativeImportExtensions/cjsErrors.ts
  tests/cases/conformance/externalModules/rewriteRelativeImportExtensions/emit.ts
  tests/cases/conformance/externalModules/rewriteRelativeImportExtensions/emitModuleCommonJS.ts
  tests/cases/conformance/externalModules/rewriteRelativeImportExtensions/nodeModulesTsFiles.ts
  tests/cases/conformance/externalModules/rewriteRelativeImportExtensions/packageJsonImportsErrors.ts
  tests/cases/fourslash/server/rewriteRelativeImportExtensionsProjectReferences1.ts
  tests/cases/fourslash/server/rewriteRelativeImportExtensionsProjectReferences2.ts
  tests/cases/fourslash/server/rewriteRelativeImportExtensionsProjectReferences3.ts
Labels: Author: Team, For Uncommitted Bug

#59933 add jsx fragments to callLikeExpression
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/compiler/utilitiesPublic.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/inlineJsxAndJsxFragPragma.errors.txt
  tests/baselines/reference/inlineJsxAndJsxFragPragmaOverridesCompilerOptions.errors.txt
  tests/baselines/reference/inlineJsxAndJsxFragPragmaOverridesCompilerOptions.types
  tests/baselines/reference/inlineJsxFactoryWithFragmentIsError.errors.txt
  tests/baselines/reference/jsxFactoryAndJsxFragmentFactoryNull.errors.txt
  tests/baselines/reference/jsxFactoryAndJsxFragmentFactoryNull.types
  tests/baselines/reference/jsxFragmentWrongType.errors.txt
  tests/baselines/reference/jsxFragmentWrongType.js
  tests/baselines/reference/jsxFragmentWrongType.symbols
  tests/baselines/reference/jsxFragmentWrongType.types
  tests/baselines/reference/jsxJsxsCjsTransformCustomImport(jsx=react-jsx).errors.txt
  tests/baselines/reference/jsxJsxsCjsTransformCustomImport(jsx=react-jsxdev).errors.txt
  tests/baselines/reference/jsxJsxsCjsTransformCustomImportPragma(jsx=react-jsx).errors.txt
  tests/baselines/reference/jsxJsxsCjsTransformCustomImportPragma(jsx=react-jsxdev).errors.txt
  tests/baselines/reference/parseUnaryExpressionNoTypeAssertionInJsx2.errors.txt
  tests/baselines/reference/parseUnaryExpressionNoTypeAssertionInJsx4.errors.txt
  tests/cases/compiler/jsxFragmentWrongType.tsx
Labels: Author: Team, For Milestone Bug

#60061 DOM update 2024-09-25
  src/lib/dom.generated.d.ts
  src/lib/webworker.generated.d.ts
  tests/baselines/reference/globalThisBlockscopedProperties.types
  tests/baselines/reference/mappedTypeRecursiveInference.errors.txt
  tests/baselines/reference/mappedTypeRecursiveInference.types
Labels: Author: Team, For Milestone Bug
