Repository microsoft/TypeScript, pull requests merged in 2024-06, with the labels that each got.

#58750 Preserve elided imports used in declarations
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitPreserveReferencedImports.js
  tests/baselines/reference/declarationEmitPreserveReferencedImports.symbols
  tests/baselines/reference/declarationEmitPreserveReferencedImports.types
  tests/cases/compiler/declarationEmitPreserveReferencedImports.ts
Labels: For Uncommitted Bug

#58753 Bump version to 5.6.
  package.json
  src/compiler/corePublic.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#58755 Check cancellation token in isolatedDeclarations codefix
  src/services/codefixes/fixMissingTypeAnnotationOnExports.ts
Labels: Author: Team, For Uncommitted Bug

#58758 Resolve keyof and index operations instead of their targets.
  src/compiler/checker.ts
  src/compiler/utilities.ts
  tests/baselines/reference/declarationEmitResolveTypesIfNotReusable.js
  tests/baselines/reference/declarationEmitResolveTypesIfNotReusable.symbols
  tests/baselines/reference/declarationEmitResolveTypesIfNotReusable.types
  tests/cases/compiler/declarationEmitResolveTypesIfNotReusable.ts
Labels: For Milestone Bug

#58768 Remove unwrapParenthesizedType, use skipTypeParentheses
  src/compiler/checker.ts
  src/compiler/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#58742 fix58438: do not delete comments/code following unterminated string completion
  src/services/completions.ts
  src/services/stringCompletions.ts
  src/services/utilities.ts
  tests/cases/fourslash/stringCompletionsUnterminated.ts
  tests/cases/fourslash/stringCompletionsUnterminated2.ts
Labels: Author: Team, For Uncommitted Bug

#58771 Allow references to the global Symbol in computed property names under isolatedDeclarations
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/expressionToTypeNode.ts
  src/compiler/transformers/declarations.ts
  src/compiler/types.ts
  tests/baselines/reference/transpile/declarationComputedPropertyNames.d.ts
  tests/cases/transpile/declarationComputedPropertyNames.ts
Labels: Author: Team, For Uncommitted Bug

#58612 Correct regular expression flags scanning for non-BMP characters
  src/compiler/scanner.ts
  tests/baselines/reference/regularExpressionWithNonBMPFlags.errors.txt
  tests/baselines/reference/regularExpressionWithNonBMPFlags.js
  tests/baselines/reference/regularExpressionWithNonBMPFlags.symbols
  tests/baselines/reference/regularExpressionWithNonBMPFlags.types
  tests/cases/compiler/regularExpressionWithNonBMPFlags.ts
Labels: For Uncommitted Bug

#58613 Provide Spelling Suggestions for Named Capture Group References in Regular Expressions
  src/compiler/scanner.ts
  tests/baselines/reference/regularExpressionGroupNameSuggestions.errors.txt
  tests/baselines/reference/regularExpressionGroupNameSuggestions.js
  tests/baselines/reference/regularExpressionGroupNameSuggestions.symbols
  tests/baselines/reference/regularExpressionGroupNameSuggestions.types
  tests/cases/compiler/regularExpressionGroupNameSuggestions.ts
Labels: For Uncommitted Bug

#58782 Some refactoring so we arent checking undefined on program or asserting it so much
  src/compiler/builder.ts
  src/compiler/builderPublic.ts
  src/compiler/watch.ts
  src/compiler/watchUtilities.ts
  src/testRunner/unittests/helpers/baseline.ts
  src/testRunner/unittests/helpers/tsc.ts
  src/testRunner/unittests/tscWatch/incremental.ts
Labels: Author: Team, For Uncommitted Bug

#58840 Fix typo in `canIncludeBindAndCheckDiagnostics`
  src/compiler/checker.ts
  src/compiler/emitter.ts
  src/compiler/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#58514 Fixed a regression with reporting unused parameters in potential predicates
  src/compiler/utilities.ts
  tests/baselines/reference/noUnusedLocals_potentialPredicateUnusedParam.errors.txt
  tests/baselines/reference/noUnusedLocals_potentialPredicateUnusedParam.symbols
  tests/baselines/reference/noUnusedLocals_potentialPredicateUnusedParam.types
  tests/cases/compiler/noUnusedLocals_potentialPredicateUnusedParam.ts
Labels: For Milestone Bug

#58846 Ensure the updates with crashes reverts the change to scriptInfo
  src/server/project.ts
Labels: Author: Team, For Uncommitted Bug

#58837 [DO NOT MERGE UNTIL 5.6] Fix re-exported defaults in ExportInfoMap
  src/services/codefixes/importFixes.ts
  src/services/exportInfoMap.ts
  src/services/utilities.ts
  tests/baselines/reference/tsserver/fourslashServer/completionsImport_jsModuleExportsAssignment.js
  tests/cases/fourslash/completionsImport_reExportDefault2.ts
Labels: Author: Team, For Milestone Bug

#57146 fix(57141): override keyword doesn't check symbol-key class members
  src/compiler/checker.ts
  tests/baselines/reference/override21.errors.txt
  tests/baselines/reference/override21.js
  tests/baselines/reference/override21.symbols
  tests/baselines/reference/override21.types
  tests/cases/conformance/override/override21.ts
Labels: For Backlog Bug

#58849 update baselines
  tests/baselines/reference/override21.types
Labels: Author: Team, For Uncommitted Bug

#58786 Fixed declaration emit crash related to enum entity name expressions
  src/compiler/checker.ts
  tests/baselines/reference/declarationEmitComputedPropertyNameEnum1.js
  tests/baselines/reference/declarationEmitComputedPropertyNameEnum1.symbols
  tests/baselines/reference/declarationEmitComputedPropertyNameEnum1.types
  tests/baselines/reference/declarationEmitComputedPropertyNameEnum2.errors.txt
  tests/baselines/reference/declarationEmitComputedPropertyNameEnum2.js
  tests/baselines/reference/declarationEmitComputedPropertyNameEnum2.symbols
  tests/baselines/reference/declarationEmitComputedPropertyNameEnum2.types
  tests/baselines/reference/declarationEmitComputedPropertyNameEnum3.errors.txt
  tests/baselines/reference/declarationEmitComputedPropertyNameEnum3.js
  tests/baselines/reference/declarationEmitComputedPropertyNameEnum3.symbols
  tests/baselines/reference/declarationEmitComputedPropertyNameEnum3.types
  tests/baselines/reference/declarationEmitComputedPropertyNameSymbol1.errors.txt
  tests/baselines/reference/declarationEmitComputedPropertyNameSymbol1.js
  tests/baselines/reference/declarationEmitComputedPropertyNameSymbol1.symbols
  tests/baselines/reference/declarationEmitComputedPropertyNameSymbol1.types
  tests/baselines/reference/declarationEmitComputedPropertyNameSymbol2.errors.txt
  tests/baselines/reference/declarationEmitComputedPropertyNameSymbol2.js
  tests/baselines/reference/declarationEmitComputedPropertyNameSymbol2.symbols
  tests/baselines/reference/declarationEmitComputedPropertyNameSymbol2.types
  tests/cases/compiler/declarationEmitComputedPropertyNameEnum1.ts
  tests/cases/compiler/declarationEmitComputedPropertyNameEnum2.ts
  tests/cases/compiler/declarationEmitComputedPropertyNameEnum3.ts
  tests/cases/compiler/declarationEmitComputedPropertyNameSymbol1.ts
  tests/cases/compiler/declarationEmitComputedPropertyNameSymbol2.ts
Labels: For Uncommitted Bug

#58854 Always build project irrespective of errors in dependency with tsc -b
  src/compiler/diagnosticMessages.json
  src/compiler/tsbuild.ts
  src/compiler/tsbuildPublic.ts
  src/testRunner/unittests/tsbuild/sample.ts
  src/testRunner/unittests/tsbuildWatch/programUpdates.ts
  tests/baselines/reference/tsbuild/demo/in-bad-ref-branch-reports-the-error-about-files-not-in-rootDir-at-the-import-location.js
  tests/baselines/reference/tsbuild/fileDelete/multiFile/detects-deleted-file.js
  tests/baselines/reference/tsbuild/fileDelete/outFile/detects-deleted-file.js
  tests/baselines/reference/tsbuild/javascriptProjectEmit/loads-js-based-projects-and-emits-them-correctly.js
  tests/baselines/reference/tsbuild/sample1/builds-downstream-projects-even-if-upstream-projects-have-errors.js
  tests/baselines/reference/tsbuild/sample1/reports-error-if-input-file-is-missing-with-force.js
  tests/baselines/reference/tsbuild/sample1/reports-error-if-input-file-is-missing.js
  tests/baselines/reference/tsbuild/transitiveReferences/reports-error-about-module-not-found-with-node-resolution-with-external-module-name.js
  tests/baselines/reference/tsbuildWatch/demo/updates-with-bad-reference.js
  tests/baselines/reference/tsbuildWatch/programUpdates/reportErrors/when-preserveWatchOutput-is-not-used.js
  tests/baselines/reference/tsbuildWatch/programUpdates/reportErrors/when-preserveWatchOutput-is-passed-on-command-line.js
  tests/baselines/reference/tsbuildWatch/programUpdates/watches-config-files-that-are-not-present.js
Labels: Author: Team, For Uncommitted Bug

#58708 Fixed reported errors for variadic element mismatches
  src/compiler/checker.ts
  tests/baselines/reference/variadicTuples1.errors.txt
  tests/baselines/reference/variadicTuples2.errors.txt
  tests/baselines/reference/variadicTuples3.errors.txt
  tests/baselines/reference/variadicTuples3.symbols
  tests/baselines/reference/variadicTuples3.types
  tests/cases/conformance/types/tuple/variadicTuples3.ts
Labels: For Backlog Bug

#58157 Fixed widening errors locations in union-normalized object literal types
  src/compiler/checker.ts
  tests/baselines/reference/noImplicitAnyUnionNormalizedObjectLiteral1.errors.txt
  tests/baselines/reference/noImplicitAnyUnionNormalizedObjectLiteral1.symbols
  tests/baselines/reference/noImplicitAnyUnionNormalizedObjectLiteral1.types
  tests/cases/compiler/noImplicitAnyUnionNormalizedObjectLiteral1.ts
Labels: For Backlog Bug

#58203 Allow signature help argument count to be equal to argument index
  src/services/signatureHelp.ts
  tests/baselines/reference/signatureHelpRestArgs3.baseline
  tests/cases/fourslash/completionsBeforeRestArg1.ts
  tests/cases/fourslash/signatureHelpRestArgs3.ts
Labels: For Uncommitted Bug

#58887 Expose getBigIntLiteralType
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Backlog Bug

#58872 Fix declaration emit crash
  src/compiler/checker.ts
  src/compiler/utilities.ts
  src/services/utilities.ts
  tests/baselines/reference/reuseTypeAnnotationImportTypeInGlobalThisTypeArgument.errors.txt
  tests/baselines/reference/reuseTypeAnnotationImportTypeInGlobalThisTypeArgument.js
  tests/cases/compiler/reuseTypeAnnotationImportTypeInGlobalThisTypeArgument.ts
Labels: Author: Team, For Milestone Bug

#58895 Fix global when typescript.js loaded as script
  Herebyfile.mjs
  scripts/browserIntegrationTest.mjs
Labels: Author: Team, For Uncommitted Bug

#57909 Improve logic that chooses co- vs. contra-variant inferences
  src/compiler/checker.ts
  tests/baselines/reference/coAndContraVariantInferences7.symbols
  tests/baselines/reference/coAndContraVariantInferences7.types
  tests/baselines/reference/coAndContraVariantInferences8.symbols
  tests/baselines/reference/coAndContraVariantInferences8.types
  tests/cases/compiler/coAndContraVariantInferences7.ts
  tests/cases/compiler/coAndContraVariantInferences8.ts
Labels: For Backlog Bug

#58906 Update deps, dprint config
  .dprint.jsonc
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#58537 fix55816: exclude files with re-exports if excluded by preferences.autoImportFileExcludePatterns
  src/services/codefixes/importFixes.ts
  src/services/exportInfoMap.ts
  tests/cases/fourslash/autoImportFileExcludePatterns10.ts
  tests/cases/fourslash/autoImportFileExcludePatterns11.ts
  tests/cases/fourslash/autoImportFileExcludePatterns12.ts
  tests/cases/fourslash/autoImportFileExcludePatterns13.ts
  tests/cases/fourslash/autoImportFileExcludePatterns4.ts
  tests/cases/fourslash/autoImportFileExcludePatterns5.ts
  tests/cases/fourslash/autoImportFileExcludePatterns6.ts
  tests/cases/fourslash/autoImportFileExcludePatterns7.ts
  tests/cases/fourslash/autoImportFileExcludePatterns8.ts
  tests/cases/fourslash/autoImportFileExcludePatterns9.ts
Labels: Author: Team, For Milestone Bug

#58867 Fix incorrect condition of noLib
  src/compiler/program.ts
  src/testRunner/unittests/tsc/incremental.ts
  tests/baselines/reference/tsbuild/libraryResolution/with-config-with-redirection.js
  tests/baselines/reference/tsbuild/libraryResolution/with-config.js
  tests/baselines/reference/tsbuildWatch/libraryResolution/with-config-with-redirection.js
  tests/baselines/reference/tsbuildWatch/libraryResolution/with-config.js
  tests/baselines/reference/tsc/incremental/when-noLib-toggles.js
  tests/baselines/reference/tsc/libraryResolution/with-config-with-redirection.js
  tests/baselines/reference/tsc/libraryResolution/with-config.js
  tests/baselines/reference/tscWatch/libraryResolution/with-config-with-redirection.js
  tests/baselines/reference/tscWatch/libraryResolution/with-config.js
  tests/baselines/reference/tscWatch/libraryResolution/without-config-with-redirection.js
  tests/baselines/reference/tscWatch/libraryResolution/without-config.js
Labels: Author: Team, For Uncommitted Bug

#58873 Use more explicit operations in core helpers (and other nits)
  src/compiler/checker.ts
  src/compiler/commandLineParser.ts
  src/compiler/core.ts
  src/compiler/debug.ts
  src/compiler/scanner.ts
  src/compiler/watch.ts
  src/harness/fourslashImpl.ts
  src/server/editorServices.ts
  src/services/jsDoc.ts
Labels: Author: Team, For Uncommitted Bug

#58869 Reject internal tag on private decls, strip comments from private decls in dtsBundler
  scripts/dtsBundler.mjs
  scripts/eslint/rules/jsdoc-format.cjs
  src/server/editorServices.ts
  src/server/project.ts
  src/server/scriptInfo.ts
  src/typingsInstallerCore/typingsInstaller.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#58811 fix(58801): "Move to file" on global code unnecessarily imports/exports, generates invalid code
  src/services/refactors/moveToFile.ts
  tests/cases/fourslash/moveToNewFile_global1.ts
  tests/cases/fourslash/moveToNewFile_global2.ts
  tests/cases/fourslash/moveToNewFile_global3.ts
Labels: For Uncommitted Bug

#58917 Set JSDocParsingMode.ParseForTypeErrors in compiler tests
  src/harness/fakesHosts.ts
  src/harness/harnessIO.ts
Labels: Author: Team, For Uncommitted Bug

#58931 Defer creation of barebonesLibSourceFile
  src/services/transpile.ts
Labels: Author: Team, For Uncommitted Bug

#58935 Revert "Fix incorrect condition of noLib" (PR 58867)
  src/compiler/program.ts
  src/testRunner/unittests/tsc/incremental.ts
  tests/baselines/reference/tsbuild/libraryResolution/with-config-with-redirection.js
  tests/baselines/reference/tsbuild/libraryResolution/with-config.js
  tests/baselines/reference/tsbuildWatch/libraryResolution/with-config-with-redirection.js
  tests/baselines/reference/tsbuildWatch/libraryResolution/with-config.js
  tests/baselines/reference/tsc/incremental/when-noLib-toggles.js
  tests/baselines/reference/tsc/libraryResolution/with-config-with-redirection.js
  tests/baselines/reference/tsc/libraryResolution/with-config.js
  tests/baselines/reference/tscWatch/libraryResolution/with-config-with-redirection.js
  tests/baselines/reference/tscWatch/libraryResolution/with-config.js
  tests/baselines/reference/tscWatch/libraryResolution/without-config-with-redirection.js
  tests/baselines/reference/tscWatch/libraryResolution/without-config.js
Labels: Author: Team, For Uncommitted Bug

#58947 Update to TS 5.5.2
  package-lock.json
  package.json
  src/compiler/checker.ts
  src/compiler/watch.ts
  src/services/codefixes/fixAddMissingMember.ts
  src/services/findAllReferences.ts
  src/services/goToDefinition.ts
  src/services/rename.ts
Labels: Author: Team, For Uncommitted Bug

#58945 Fix incorrect lib condition again!
  src/compiler/program.ts
  src/testRunner/unittests/tsc/libraryResolution.ts
  tests/baselines/reference/tsbuild/libraryResolution/with-config-with-redirection.js
  tests/baselines/reference/tsbuild/libraryResolution/with-config.js
  tests/baselines/reference/tsbuildWatch/libraryResolution/with-config-with-redirection.js
  tests/baselines/reference/tsbuildWatch/libraryResolution/with-config.js
  tests/baselines/reference/tsc/libraryResolution/when-noLib-toggles.js
  tests/baselines/reference/tsc/libraryResolution/when-one-of-the-file-skips-default-lib-inclusion.js
  tests/baselines/reference/tsc/libraryResolution/with-config-with-redirection.js
  tests/baselines/reference/tsc/libraryResolution/with-config.js
  tests/baselines/reference/tscWatch/libraryResolution/with-config-with-redirection.js
  tests/baselines/reference/tscWatch/libraryResolution/with-config.js
  tests/baselines/reference/tscWatch/libraryResolution/without-config-with-redirection.js
  tests/baselines/reference/tscWatch/libraryResolution/without-config.js
Labels: Author: Team, For Uncommitted Bug

#58951 Add non-mutating Array methods to es2023 in the lib/target suggestion list
  src/compiler/utilities.ts
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2023(target=es5).errors.txt
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2023(target=es5).symbols
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2023(target=es5).types
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2023(target=esnext).errors.txt
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2023(target=esnext).symbols
  tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2023(target=esnext).types
  tests/cases/compiler/doYouNeedToChangeYourTargetLibraryES2023.ts
Labels: Author: Team, For Uncommitted Bug

#58953 Update es2017.object.d.ts to indicate that Object.values/entries looks only at own properties
  src/lib/es2017.object.d.ts
Labels: For Uncommitted Bug

#58964 Fix missed baselines with merge of #58845
  tests/baselines/reference/tsserver/regionDiagnostics/diagnostics-for-select-nodes-and-whole-file-for-multiple-files.js
  tests/baselines/reference/tsserver/regionDiagnostics/diagnostics-for-select-nodes-in-a-single-file.js
  tests/baselines/reference/tsserver/regionDiagnostics/region-diagnostics-is-skipped-for-@ts-nocheck-file.js
  tests/baselines/reference/tsserver/regionDiagnostics/region-diagnostics-is-skipped-for-small-file.js
  tests/baselines/reference/tsserver/regionDiagnostics/region-does-not-have-suggestion.js
  tests/baselines/reference/tsserver/regionDiagnostics/region-has-suggestion.js
Labels: Author: Team, For Uncommitted Bug

#58963 Fix 'accessor' crash for invalid modifier locations
  src/compiler/transformers/classFields.ts
  tests/baselines/reference/autoAccessorDisallowedModifiers(target=es2017).errors.txt
  tests/baselines/reference/autoAccessorDisallowedModifiers(target=es2017).js
  tests/baselines/reference/autoAccessorDisallowedModifiers(target=esnext).errors.txt
  tests/baselines/reference/autoAccessorDisallowedModifiers(target=esnext).js
  tests/cases/conformance/classes/propertyMemberDeclarations/autoAccessorDisallowedModifiers.ts
Labels: Author: Team, For Milestone Bug

#58966 fix(58955): @import JSDoc tag doesn't seem to account for resolution-mode import attribute in TS v5.5.2
  src/compiler/checker.ts
  src/compiler/program.ts
  src/compiler/utilities.ts
  tests/baselines/reference/importTag17.errors.txt
  tests/baselines/reference/importTag17.symbols
  tests/baselines/reference/importTag17.types
  tests/cases/conformance/jsdoc/importTag17.ts
Labels: For Milestone Bug

#58974 Allow partial matches in discrimination logic
  src/compiler/checker.ts
  tests/baselines/reference/assignmentCompatWithDiscriminatedUnion.errors.txt
  tests/baselines/reference/assignmentCompatWithDiscriminatedUnion.js
  tests/baselines/reference/assignmentCompatWithDiscriminatedUnion.symbols
  tests/baselines/reference/assignmentCompatWithDiscriminatedUnion.types
  tests/cases/conformance/types/typeRelationships/assignmentCompatibility/assignmentCompatWithDiscriminatedUnion.ts
Labels: Author: Team, For Milestone Bug

#59005 Allow dynamic import attributes in `--module preserve`
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/importAssertion1(module=commonjs).errors.txt
  tests/baselines/reference/importAttributes1(module=commonjs).errors.txt
  tests/baselines/reference/importCallExpressionGrammarError.errors.txt
  tests/cases/compiler/modulePreserve5.ts
Labels: Author: Team, For Milestone Bug

#59014 Lowercase Microsoft github org links
  package.json
Labels: Author: Team, For Uncommitted Bug

#58962 Make canUseWatchEvents test framework more generic so we can add more tests easily
  src/testRunner/unittests/helpers/tsserver.ts
  src/testRunner/unittests/helpers/virtualFileSystemWithWatch.ts
  src/testRunner/unittests/tsserver/events/watchEvents.ts
  tests/baselines/reference/tsserver/events/watchEvents/canUseWatchEvents-on-windows.js
  tests/baselines/reference/tsserver/events/watchEvents/canUseWatchEvents-without-canUseEvents.js
  tests/baselines/reference/tsserver/events/watchEvents/canUseWatchEvents.js
Labels: Author: Team, For Uncommitted Bug

#58929 Implement deterministic collapse of 'await' in 'await using'
  src/compiler/factory/emitHelpers.ts
  src/testRunner/unittests/evaluation/usingDeclarations.ts
  tests/baselines/reference/awaitUsingDeclarations.1(target=es2015).js
  tests/baselines/reference/awaitUsingDeclarations.1(target=es2017).js
  tests/baselines/reference/awaitUsingDeclarations.1(target=es2022).js
  tests/baselines/reference/awaitUsingDeclarations.1(target=es5).js
  tests/baselines/reference/awaitUsingDeclarations.2(target=es2015).js
  tests/baselines/reference/awaitUsingDeclarations.2(target=es2017).js
  tests/baselines/reference/awaitUsingDeclarations.2(target=es2022).js
  tests/baselines/reference/awaitUsingDeclarations.2(target=es5).js
  tests/baselines/reference/awaitUsingDeclarations.3(target=es2015).js
  tests/baselines/reference/awaitUsingDeclarations.3(target=es2017).js
  tests/baselines/reference/awaitUsingDeclarations.3(target=es2022).js
  tests/baselines/reference/awaitUsingDeclarations.3(target=es5).js
  tests/baselines/reference/awaitUsingDeclarationsInFor(target=es2015).js
  tests/baselines/reference/awaitUsingDeclarationsInFor(target=es2017).js
  tests/baselines/reference/awaitUsingDeclarationsInFor(target=es2022).js
  tests/baselines/reference/awaitUsingDeclarationsInFor(target=es5).js
  tests/baselines/reference/awaitUsingDeclarationsInForAwaitOf(target=es2015).js
  tests/baselines/reference/awaitUsingDeclarationsInForAwaitOf(target=es2017).js
  tests/baselines/reference/awaitUsingDeclarationsInForAwaitOf(target=es2022).js
  tests/baselines/reference/awaitUsingDeclarationsInForAwaitOf(target=es5).js
  tests/baselines/reference/awaitUsingDeclarationsInForAwaitOf.3(target=es5).js
  tests/baselines/reference/awaitUsingDeclarationsInForOf.1(target=es2015).js
  tests/baselines/reference/awaitUsingDeclarationsInForOf.1(target=es2017).js
  tests/baselines/reference/awaitUsingDeclarationsInForOf.1(target=es2022).js
  tests/baselines/reference/awaitUsingDeclarationsInForOf.1(target=es5).js
  tests/baselines/reference/awaitUsingDeclarationsInForOf.5(target=es5).js
  tests/baselines/reference/transpile/declarationBasicSyntax.js
  tests/baselines/reference/usingDeclarations.1(target=es2015).js
  tests/baselines/reference/usingDeclarations.1(target=es2017).js
  tests/baselines/reference/usingDeclarations.1(target=es2022).js
  tests/baselines/reference/usingDeclarations.1(target=es5).js
  tests/baselines/reference/usingDeclarations.11.js
  tests/baselines/reference/usingDeclarations.12(usedefineforclassfields=false).js
  tests/baselines/reference/usingDeclarations.12(usedefineforclassfields=true).js
  tests/baselines/reference/usingDeclarations.2(target=es2015).js
  tests/baselines/reference/usingDeclarations.2(target=es2017).js
  tests/baselines/reference/usingDeclarations.2(target=es2022).js
  tests/baselines/reference/usingDeclarations.2(target=es5).js
  tests/baselines/reference/usingDeclarations.3(target=es2015).js
  tests/baselines/reference/usingDeclarations.3(target=es2017).js
  tests/baselines/reference/usingDeclarations.3(target=es2022).js
  tests/baselines/reference/usingDeclarations.3(target=es5).js
  tests/baselines/reference/usingDeclarationsInFor(target=es2015).js
  tests/baselines/reference/usingDeclarationsInFor(target=es2017).js
  tests/baselines/reference/usingDeclarationsInFor(target=es2022).js
  tests/baselines/reference/usingDeclarationsInFor(target=es5).js
  tests/baselines/reference/usingDeclarationsInForAwaitOf(target=es2015).js
  tests/baselines/reference/usingDeclarationsInForAwaitOf(target=es2017).js
  tests/baselines/reference/usingDeclarationsInForAwaitOf(target=es2022).js
  tests/baselines/reference/usingDeclarationsInForAwaitOf(target=es5).js
  tests/baselines/reference/usingDeclarationsInForOf.1(target=es2015).js
  tests/baselines/reference/usingDeclarationsInForOf.1(target=es2017).js
  tests/baselines/reference/usingDeclarationsInForOf.1(target=es2022).js
  tests/baselines/reference/usingDeclarationsInForOf.1(target=es5).js
  tests/baselines/reference/usingDeclarationsNamedEvaluationDecoratorsAndClassFields.js
Labels: Author: Team, For Milestone Bug

#59017 Use regular imports instead of require where possible
  package-lock.json
  package.json
  src/harness/fourslashImpl.ts
  src/harness/harnessIO.ts
  src/harness/harnessUtils.ts
  src/testRunner/parallel/host.ts
  src/testRunner/parallel/worker.ts
  src/testRunner/unittests/skipJSDocParsing.ts
  src/tsserver/nodeServer.ts
  src/tsserver/server.ts
  src/typingsInstaller/nodeTypingsInstaller.ts
Labels: Author: Team, For Uncommitted Bug

#59002 Cherry-pick #58966 to release-5.5
  src/compiler/checker.ts
  src/compiler/program.ts
  src/compiler/utilities.ts
  tests/baselines/reference/importTag17.errors.txt
  tests/baselines/reference/importTag17.symbols
  tests/baselines/reference/importTag17.types
  tests/cases/conformance/jsdoc/importTag17.ts
Labels: Author: Team, For Uncommitted Bug

#59042 Fixed an issue with top-level for-await loops not being allowed with `--module preserve`
  src/compiler/checker.ts
  tests/baselines/reference/modulePreserveTopLevelAwait1(target=es2016).errors.txt
  tests/baselines/reference/modulePreserveTopLevelAwait1(target=es2016).symbols
  tests/baselines/reference/modulePreserveTopLevelAwait1(target=es2016).types
  tests/baselines/reference/modulePreserveTopLevelAwait1(target=esnext).symbols
  tests/baselines/reference/modulePreserveTopLevelAwait1(target=esnext).types
  tests/cases/compiler/modulePreserveTopLevelAwait1.ts
Labels: For Uncommitted Bug

#59040 Refactor resolving module or type reference name
  src/compiler/program.ts
  src/compiler/resolutionCache.ts
  src/compiler/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#59041 Remove refCount from resolutions as we dont need it explicitly since its tracked by files it references
  src/compiler/resolutionCache.ts
  src/harness/incrementalUtils.ts
Labels: Author: Team, For Uncommitted Bug

#59043 Typings cache need not be a map but directly on the project
  src/server/_namespaces/ts.server.ts
  src/server/editorServices.ts
  src/server/project.ts
  src/server/types.ts
  src/server/typingsCache.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#59044 Remove unnecessary properties of TypingsCacheEntry
  src/server/project.ts
Labels: Author: Team, For Uncommitted Bug

#59006 Update deps
  package-lock.json
  package.json
Labels: Author: Team, For Uncommitted Bug

#56817 Remove unused exports & dead code (using Knip)
  .github/workflows/ci.yml
  Herebyfile.mjs
  knip.jsonc
  package-lock.json
  package.json
  src/compiler/builder.ts
  src/compiler/checker.ts
  src/compiler/commandLineParser.ts
  src/compiler/core.ts
  src/compiler/corePublic.ts
  src/compiler/emitter.ts
  src/compiler/factory/emitHelpers.ts
  src/compiler/factory/emitNode.ts
  src/compiler/factory/nodeFactory.ts
  src/compiler/factory/utilities.ts
  src/compiler/moduleNameResolver.ts
  src/compiler/parser.ts
  src/compiler/path.ts
  src/compiler/program.ts
  src/compiler/resolutionCache.ts
  src/compiler/scanner.ts
  src/compiler/sourcemap.ts
  src/compiler/sys.ts
  src/compiler/transformers/classThis.ts
  src/compiler/transformers/namedEvaluation.ts
  src/compiler/transformers/utilities.ts
  src/compiler/tsbuildPublic.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/compiler/utilitiesPublic.ts
  src/compiler/watch.ts
  src/deprecatedCompat/deprecations.ts
  src/harness/client.ts
  src/jsTyping/jsTyping.ts
  src/server/editorServices.ts
  src/server/protocol.ts
  src/server/utilities.ts
  src/services/codefixes/helpers.ts
  src/services/completions.ts
  src/services/findAllReferences.ts
  src/services/goToDefinition.ts
  src/services/organizeImports.ts
  src/services/refactors/moveToFile.ts
  src/services/utilities.ts
  src/testRunner/_namespaces/compiler.ts
Labels: Housekeeping, For Uncommitted Bug

#57684 Switch to eslint flat config
  .eslint-plugin-local.cjs
  .eslintrc.json
  eslint.config.mjs
  package-lock.json
  package.json
  src/.eslintrc.json
Labels: Author: Team, For Uncommitted Bug

#59068 Switch to JSDoc imports in scripts
  scripts/build/tests.mjs
  scripts/build/utils.mjs
  scripts/eslint/rules/argument-trivia.cjs
  scripts/eslint/rules/debug-assert.cjs
  scripts/eslint/rules/js-extensions.cjs
  scripts/eslint/rules/jsdoc-format.cjs
  scripts/eslint/rules/no-in-operator.cjs
  scripts/eslint/rules/no-keywords.cjs
  scripts/eslint/rules/only-arrow-functions.cjs
Labels: Author: Team, For Uncommitted Bug

#59070 Delay the calculation of common source root if it would be needed when calculation dts files
  src/compiler/program.ts
  src/compiler/utilities.ts
  src/server/project.ts
  src/services/sourcemaps.ts
  src/testRunner/unittests/tsserver/projectErrors.ts
  tests/baselines/reference/tsserver/projectErrors/dts-errors-when-files-dont-belong-to-common-root-with-declarationDir.js
  tests/baselines/reference/tsserver/projectErrors/dts-errors-when-files-dont-belong-to-common-root.js
  tests/baselines/reference/tsserver/projects/synchronizeProjectList-provides-updates-to-redirect-info-when-requested.js
Labels: Author: Team, For Uncommitted Bug

#59071 Remove errors if noEmit is sepcified with noCheck or emitDeclarationOnly
  src/compiler/program.ts
  src/harness/harnessIO.ts
  tests/baselines/reference/declFileEmitDeclarationOnlyError2.errors.txt
  tests/baselines/reference/noCheckNoEmit.errors.txt
Labels: Author: Team, For Uncommitted Bug
