Repository microsoft/TypeScript, pull requests merged in 2025-09, with the labels that each got.

#62351 Add missing Float16Array constructors
  src/lib/esnext.float16.d.ts
  tests/cases/compiler/typedArrayConstructorOverloads.ts
Labels: For Backlog Bug

#62443 Enable `noUncheckedSideEffectImports` by default
  src/compiler/checker.ts
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/amdDependencyCommentName4.errors.txt
  tests/baselines/reference/autoAccessorDisallowedModifiers(target=es2017).errors.txt
  tests/baselines/reference/autoAccessorDisallowedModifiers(target=esnext).errors.txt
  tests/baselines/reference/checkExportsObjectAssignPrototypeProperty.errors.txt
  tests/baselines/reference/emit(jsx=preserve).errors.txt
  tests/baselines/reference/emit(jsx=react).errors.txt
  tests/baselines/reference/es6ImportWithoutFromClauseInEs5.errors.txt
  tests/baselines/reference/es6ImportWithoutFromClauseWithExport.errors.txt
  tests/baselines/reference/extendGlobalThis.errors.txt
  tests/baselines/reference/extendGlobalThis.types
  tests/baselines/reference/jsxFactoryQualifiedNameWithEs5.errors.txt
  tests/baselines/reference/jsxFactoryQualifiedNameWithEs5.types
  tests/baselines/reference/jsxImportForSideEffectsNonExtantNoError.errors.txt
  tests/baselines/reference/moduleAugmentationInAmbientModule5.js
  tests/baselines/reference/moduleAugmentationsImports3.js
  tests/baselines/reference/moduleAugmentationsImports4.js
  tests/baselines/reference/moduleResolutionWithExtensions_unexpected2.errors.txt
  tests/baselines/reference/nodeModulesAllowJsExportAssignment(module=node16).errors.txt
  tests/baselines/reference/nodeModulesAllowJsExportAssignment(module=node18).errors.txt
  tests/baselines/reference/nodeModulesAllowJsExportAssignment(module=node20).errors.txt
  tests/baselines/reference/nodeModulesAllowJsExportAssignment(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesCJSEmit1(module=node18).errors.txt
  tests/baselines/reference/nodeModulesCJSEmit1(module=node20).errors.txt
  tests/baselines/reference/nodeModulesCJSEmit1(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesNoDirectoryModule.errors.txt
  tests/baselines/reference/pathsValidation4.errors.txt
  tests/baselines/reference/pathsValidation5.errors.txt
  tests/baselines/reference/sideEffectImports1(module=commonjs,nouncheckedsideeffectimports=true).errors.txt
  tests/baselines/reference/sideEffectImports1(module=nodenext,nouncheckedsideeffectimports=true).errors.txt
  tests/baselines/reference/sideEffectImports1(module=preserve,nouncheckedsideeffectimports=true).errors.txt
  tests/baselines/reference/systemModule9.errors.txt
  tests/baselines/reference/tsc/commandLine/help-all.js
  tests/baselines/reference/tscWatch/programUpdates/when-changing-`allowImportingTsExtensions`-of-config-file.js
  tests/baselines/reference/tscWatch/programUpdates/when-changing-noUncheckedSideEffectImports-of-config-file.js
  tests/cases/compiler/ambientExportDefaultErrors.ts
  tests/cases/compiler/moduleAugmentationGlobal5.ts
  tests/cases/compiler/moduleResolutionWithExtensions_unexpected.ts
Labels: Breaking Change, Author: Team, For Milestone Bug

#62483 Disable conditional exports fallbacks on `null` values
  src/compiler/moduleNameResolver.ts
  tests/baselines/reference/conditionalExportsResolutionFallbackNull(moduleresolution=bundler).errors.txt
  tests/baselines/reference/conditionalExportsResolutionFallbackNull(moduleresolution=bundler).trace.json
  tests/baselines/reference/conditionalExportsResolutionFallbackNull(moduleresolution=node16).errors.txt
  tests/baselines/reference/conditionalExportsResolutionFallbackNull(moduleresolution=node16).trace.json
  tests/baselines/reference/conditionalExportsResolutionFallbackNull(moduleresolution=nodenext).errors.txt
  tests/baselines/reference/conditionalExportsResolutionFallbackNull(moduleresolution=nodenext).trace.json
  tests/cases/conformance/moduleResolution/conditionalExportsResolutionFallbackNull.ts
Labels: Author: Team, For Backlog Bug

#62423 Revert PR 61928
  src/compiler/types.ts
  src/services/completions.ts
  src/services/services.ts
  src/services/utilities.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/syntacticClassificationsJsx1.ts
  tests/cases/fourslash/syntacticClassificationsJsx2.ts
Labels: Author: Team, For Uncommitted Bug

#62502 Port https://github.com/microsoft/typescript-go/pull/1759
  src/compiler/checker.ts
  tests/baselines/reference/jsDeclarationsFunctionClassesCjsExportAssignment.js
Labels: Author: Team, For Uncommitted Bug

#62501 Port microsoft/typescript-go#1757
  src/compiler/checker.ts
  tests/baselines/reference/missingDiscriminants2.errors.txt
  tests/baselines/reference/missingDiscriminants2.symbols
  tests/baselines/reference/missingDiscriminants2.types
  tests/cases/compiler/missingDiscriminants2.ts
Labels: Author: Team, For Uncommitted Bug

#62510 Port microsoft/typescript-go#1764
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug
