Repository microsoft/TypeScript, pull requests merged in 2025-02, with the labels that each got.

#61086 DOM update MessageEventTarget missed this parameters
  src/lib/dom.generated.d.ts
  src/lib/webworker.generated.d.ts
Labels: Author: Team, For Uncommitted Bug

#61114 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20250204202444390 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#61132 Revert "Proposed expandable hover API"
  src/compiler/checker.ts
  src/compiler/types.ts
  src/harness/client.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/server/protocol.ts
  src/server/session.ts
  src/services/services.ts
  src/services/symbolDisplay.ts
  src/services/types.ts
  src/services/utilities.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/quickinfoVerbosity1.baseline
  tests/baselines/reference/quickinfoVerbosity2.baseline
  tests/baselines/reference/quickinfoVerbosityClass1.baseline
  tests/baselines/reference/quickinfoVerbosityInterface1.baseline
  tests/baselines/reference/quickinfoVerbosityIntersection1.baseline
  tests/baselines/reference/quickinfoVerbosityObjectType1.baseline
  tests/baselines/reference/quickinfoVerbosityServer.baseline
  tests/baselines/reference/quickinfoVerbosityTruncation.baseline
  tests/baselines/reference/tsserver/fourslashServer/quickinfoVerbosityServer.js
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/quickinfoVerbosity1.ts
  tests/cases/fourslash/quickinfoVerbosity2.ts
  tests/cases/fourslash/quickinfoVerbosityClass1.ts
  tests/cases/fourslash/quickinfoVerbosityInterface1.ts
  tests/cases/fourslash/quickinfoVerbosityIntersection1.ts
  tests/cases/fourslash/quickinfoVerbosityObjectType1.ts
  tests/cases/fourslash/quickinfoVerbosityTruncation.ts
  tests/cases/fourslash/server/quickinfoVerbosityServer.ts
Labels: Author: Team, For Uncommitted Bug

#61175 Ban import=require and export= under erasableSyntaxOnly
  src/compiler/checker.ts
  tests/baselines/reference/erasableSyntaxOnly.errors.txt
  tests/baselines/reference/erasableSyntaxOnly.js
  tests/baselines/reference/erasableSyntaxOnly.symbols
  tests/baselines/reference/erasableSyntaxOnly.types
  tests/baselines/reference/erasableSyntaxOnlyDeclaration.errors.txt
  tests/baselines/reference/erasableSyntaxOnlyDeclaration.symbols
  tests/baselines/reference/erasableSyntaxOnlyDeclaration.types
  tests/cases/compiler/erasableSyntaxOnly.ts
  tests/cases/compiler/erasableSyntaxOnlyDeclaration.ts
Labels: Author: Team, For Uncommitted Bug

#61218 Bump version to 5.9
  package-lock.json
  package.json
  src/compiler/corePublic.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: Author: Team, For Uncommitted Bug

#60967 Update deps, a few majors
  .dprint.jsonc
  Herebyfile.mjs
  package-lock.json
  package.json
  scripts/browserIntegrationTest.mjs
  scripts/build/tests.mjs
  scripts/build/utils.mjs
Labels: Author: Team, For Uncommitted Bug

#56907 Treat contextually typed functions in JS files as typed
  src/compiler/checker.ts
  tests/baselines/reference/checkJsdocSatisfiesTag15.errors.txt
  tests/baselines/reference/checkJsdocSatisfiesTag15.js
  tests/baselines/reference/checkJsdocSatisfiesTag15.symbols
  tests/baselines/reference/checkJsdocSatisfiesTag15.types
  tests/cases/conformance/jsdoc/checkJsdocSatisfiesTag15.ts
Labels: For Backlog Bug

#61227 Fix quick fix for isolatedDeclarations to keep trailing unknown in generics
  src/services/codefixes/helpers.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports57-generics-doesnt-drop-trailing-unknown.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports58-genercs-doesnt-drop-trailing-unknown-2.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports59-drops-unneeded-after-unknown.ts
  tests/cases/fourslash/codeFixMissingTypeAnnotationOnExports60-drops-unneeded-non-trailing-unknown.ts
Labels: For Uncommitted Bug

#59803 Remove redundant `getStringLiteralType` call
  src/compiler/checker.ts
Labels: For Uncommitted Bug

#59155 Fix of #58996
  src/compiler/checker.ts
  tests/baselines/reference/inferTypePredicates.errors.txt
  tests/baselines/reference/inferTypePredicates.js
  tests/baselines/reference/inferTypePredicates.symbols
  tests/baselines/reference/inferTypePredicates.types
  tests/cases/compiler/inferTypePredicates.ts
Labels: For Backlog Bug

#60964 Infer from annotated return type nodes before assigning contextual parameter types
  src/compiler/checker.ts
  tests/baselines/reference/inferFromAnnotatedReturn1.errors.txt
  tests/baselines/reference/inferFromAnnotatedReturn1.symbols
  tests/baselines/reference/inferFromAnnotatedReturn1.types
  tests/cases/compiler/inferFromAnnotatedReturn1.ts
Labels: For Uncommitted Bug

#60272 Provide string completions for `in` keyword checks
  src/services/stringCompletions.ts
  tests/cases/fourslash/completionInChecks1.ts
Labels: For Uncommitted Bug

#59569 Account for right operands & fix a weird error message for leftmost nullish literals in checkNullishCoalesceOperands
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/predicateSemantics.errors.txt
  tests/baselines/reference/predicateSemantics.js
  tests/baselines/reference/predicateSemantics.symbols
  tests/baselines/reference/predicateSemantics.types
  tests/cases/compiler/predicateSemantics.ts
Labels: For Backlog Bug

#61171 fix(61167): Incorrect "Import may be converted to a default import" autofix for import export
  src/services/suggestionDiagnostics.ts
  tests/cases/fourslash/codeFixUseDefaultImport.ts
Labels: For Backlog Bug

#60150 Fix to use string literal type in ArrayBuffer's `Symbol.toStringTag`
  src/harness/vfsUtil.ts
  src/lib/es2015.symbol.wellknown.d.ts
  tests/baselines/reference/assignSharedArrayBufferToArrayBuffer.errors.txt
  tests/baselines/reference/assignSharedArrayBufferToArrayBuffer.js
  tests/baselines/reference/assignSharedArrayBufferToArrayBuffer.symbols
  tests/baselines/reference/assignSharedArrayBufferToArrayBuffer.types
  tests/cases/conformance/es2017/assignSharedArrayBufferToArrayBuffer.ts
Labels: Breaking Change, For Milestone Bug

#60898 fix(60887): Incorrect Formatting on if (a) try {} finally {}
  src/services/formatting/smartIndenter.ts
  tests/cases/fourslash/formatTryFinally.ts
Labels: For Backlog Bug

#61315 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20250227204102665 to main
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug
