Repository microsoft/TypeScript, pull requests merged in 2025-01, with the labels that each got.

#60833 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20241220203953707 to main
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#60828 Fix CodeQL configuration, releases
  .github/codeql/codeql-configuration.yml
  azure-pipelines.release.yml
Labels: Author: Team, For Uncommitted Bug

#60928 Narrow types by typeof operands with extra parenthesis
  src/compiler/binder.ts
  tests/baselines/reference/narrowingTypeofParenthesized1.symbols
  tests/baselines/reference/narrowingTypeofParenthesized1.types
  tests/cases/compiler/narrowingTypeofParenthesized1.ts
Labels: For Backlog Bug

#60925 Fixed BADCLIENT error message
  src/server/session.ts
Labels: Author: Team, For Uncommitted Bug

#60937 Fix GHA badge in readme
  README.md
Labels: Author: Team, For Uncommitted Bug

#60812 Write path normalization without array allocations
  src/compiler/path.ts
  src/testRunner/unittests/paths.ts
Labels: Author: Team, For Uncommitted Bug

#60934 Add non-generic fallback overloads for TypedArray constructors
  src/lib/es2020.bigint.d.ts
  src/lib/es5.d.ts
  tests/cases/compiler/typedArrayConstructorOverloads.ts
Labels: Author: Team, For Uncommitted Bug

#60754 Skip `verifyCompilerOptions` when possible on program updates
  src/compiler/_namespaces/ts.ts
  src/compiler/program.ts
  src/compiler/programDiagnostics.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#60983 Fix JSDoc for Array#sort, TypedArray#sort and Array#toSorted methods
  src/lib/es2023.array.d.ts
  src/lib/es5.d.ts
  tests/baselines/reference/completionEntryForUnionMethod.baseline
  tests/baselines/reference/goToTypeDefinition_arrayType.baseline.jsonc
  tests/lib/lib.d.ts
Labels: For Backlog Bug

#60502 feat(60475): Add getUnknownType to checker api
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Backlog Bug

#60801 fix(60551): satisfies is shown on go-to-implementation
  src/services/findAllReferences.ts
  tests/baselines/reference/goToImplementation_satisfies.baseline.jsonc
  tests/cases/fourslash/goToImplementation_satisfies.ts
Labels: For Milestone Bug

#60378 fix(60375): Parameter inlay hint is incorrect when function has a this type
  src/services/inlayHints.ts
  tests/baselines/reference/inlayHintsThisParameter.baseline
  tests/cases/fourslash/inlayHintsThisParameter.ts
Labels: For Backlog Bug

#60566 fix(60563):@import * as namespace cannot be used with @implements
  src/compiler/utilities.ts
  tests/baselines/reference/importTag23.errors.txt
  tests/baselines/reference/importTag23.symbols
  tests/baselines/reference/importTag23.types
  tests/cases/conformance/jsdoc/importTag23.ts
Labels: For Backlog Bug

#60980 Fixed wrong error being reported on required initialized parameters with `isolatedDeclarations`
  src/compiler/transformers/declarations/diagnostics.ts
  tests/baselines/reference/transpile/declarationFunctionDeclarations.d.ts
  tests/baselines/reference/transpile/declarationFunctionDeclarations.js
  tests/cases/transpile/declarationFunctionDeclarations.ts
Labels: For Backlog Bug

#60888 Fixed "Delete all unused declarations" to delete self-referential functions
  src/services/codefixes/fixUnusedIdentifier.ts
  tests/cases/fourslash/codeFixUnusedIdentifier_all_selfReferencingFunction.ts
Labels: For Backlog Bug

#60910 Fix ESM/CJS resolution cache collision in non-nodenext resolution modes
  src/compiler/moduleNameResolver.ts
  src/testRunner/unittests/tsserver/inferredProjects.ts
  tests/baselines/reference/resolutionModeCache.errors.txt
  tests/baselines/reference/resolutionModeCache.symbols
  tests/baselines/reference/resolutionModeCache.trace.json
  tests/baselines/reference/resolutionModeCache.types
  tests/baselines/reference/tsserver/inferredProjects/closing-file-with-shared-resolutions.js
  tests/cases/conformance/moduleResolution/resolutionModeCache.ts
Labels: Author: Team, For Milestone Bug

#60863 Treat `BigInt` type references in JSDoc as intended `bigint`s
  src/compiler/checker.ts
  tests/baselines/reference/checkJsdocTypeTag8.symbols
  tests/baselines/reference/checkJsdocTypeTag8.types
  tests/baselines/reference/jsdocTypeTag.js
  tests/baselines/reference/jsdocTypeTag.symbols
  tests/baselines/reference/jsdocTypeTag.types
  tests/cases/conformance/jsdoc/checkJsdocTypeTag8.ts
  tests/cases/conformance/jsdoc/jsdocTypeTag.ts
Labels: For Backlog Bug

#60987 DOM update 2025/01/16
  src/lib/dom.generated.d.ts
  src/lib/dom.iterable.generated.d.ts
  src/lib/webworker.generated.d.ts
  src/lib/webworker.iterable.generated.d.ts
  tests/baselines/reference/globalThisBlockscopedProperties.types
  tests/baselines/reference/implicitAnyInCatch.types
  tests/baselines/reference/mappedTypeRecursiveInference.errors.txt
  tests/baselines/reference/mappedTypeRecursiveInference.types
  tests/baselines/reference/verifyDefaultLib_webworker.types
Labels: Author: Team, For Uncommitted Bug

#60950 Fixed an issue with for statement's incrementor missing continue's control flow information
  src/compiler/binder.ts
  tests/baselines/reference/controlFlowForStatementContinueIntoIncrementor1.errors.txt
  tests/baselines/reference/controlFlowForStatementContinueIntoIncrementor1.symbols
  tests/baselines/reference/controlFlowForStatementContinueIntoIncrementor1.types
  tests/cases/compiler/controlFlowForStatementContinueIntoIncrementor1.ts
Labels: For Backlog Bug

#60782 Narrow types by satisfies expressions
  src/compiler/checker.ts
  tests/baselines/reference/inferTypePredicates.errors.txt
  tests/baselines/reference/inferTypePredicates.js
  tests/baselines/reference/inferTypePredicates.symbols
  tests/baselines/reference/inferTypePredicates.types
  tests/cases/compiler/inferTypePredicates.ts
Labels: For Backlog Bug

#61034 Ensure createProgram stops referencing rootNamesOrOptions to ensure oldProgram is GC'd
  src/compiler/program.ts
Labels: Author: Team, For Backlog Bug

#60924 Fix missing failed lookup locations when resolving bare-specifier package.json `"imports"`
  src/compiler/moduleNameResolver.ts
  tests/baselines/reference/tsserver/fourslashServer/packageJsonImportsFailedLookups.js
  tests/cases/fourslash/server/packageJsonImportsFailedLookups.ts
Labels: Author: Team, For Uncommitted Bug

#61011 `--erasableSyntaxOnly`
  src/compiler/checker.ts
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  src/compiler/types.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/config/initTSConfig/Default initialized TSConfig/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with --help/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with --watch/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with advanced options/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with boolean value compiler options/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with enum value compiler options/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with files options/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with incorrect compiler option value/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with incorrect compiler option/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with list compiler options with enum value/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with list compiler options/tsconfig.json
  tests/baselines/reference/config/showConfig/Shows tsconfig for single option/erasableSyntaxOnly/tsconfig.json
  tests/baselines/reference/erasableSyntaxOnly.errors.txt
  tests/baselines/reference/erasableSyntaxOnly.symbols
  tests/baselines/reference/erasableSyntaxOnly.types
  tests/baselines/reference/erasableSyntaxOnlyDeclaration.errors.txt
  tests/baselines/reference/erasableSyntaxOnlyDeclaration.symbols
  tests/baselines/reference/erasableSyntaxOnlyDeclaration.types
  tests/baselines/reference/tsc/commandLine/help-all.js
  tests/cases/compiler/erasableSyntaxOnly.ts
  tests/cases/compiler/erasableSyntaxOnlyDeclaration.ts
Labels: Author: Team, For Uncommitted Bug

#60880 fix: do not use `JSX.ElementChildrenAttribute` under `jsx: react-jsx` or `jsx: react-jsxdev`
  src/compiler/checker.ts
  tests/baselines/reference/jsxNamespaceElementChildrenAttributeIgnoredWhenReactJsx(jsx=react-jsx).errors.txt
  tests/baselines/reference/jsxNamespaceElementChildrenAttributeIgnoredWhenReactJsx(jsx=react-jsx).js
  tests/baselines/reference/jsxNamespaceElementChildrenAttributeIgnoredWhenReactJsx(jsx=react-jsx).symbols
  tests/baselines/reference/jsxNamespaceElementChildrenAttributeIgnoredWhenReactJsx(jsx=react-jsx).types
  tests/baselines/reference/jsxNamespaceElementChildrenAttributeIgnoredWhenReactJsx(jsx=react-jsxdev).errors.txt
  tests/baselines/reference/jsxNamespaceElementChildrenAttributeIgnoredWhenReactJsx(jsx=react-jsxdev).js
  tests/baselines/reference/jsxNamespaceElementChildrenAttributeIgnoredWhenReactJsx(jsx=react-jsxdev).symbols
  tests/baselines/reference/jsxNamespaceElementChildrenAttributeIgnoredWhenReactJsx(jsx=react-jsxdev).types
  tests/baselines/reference/jsxNamespaceNoElementChildrenAttributeReactJsx(jsx=react-jsx).js
  tests/baselines/reference/jsxNamespaceNoElementChildrenAttributeReactJsx(jsx=react-jsx).symbols
  tests/baselines/reference/jsxNamespaceNoElementChildrenAttributeReactJsx(jsx=react-jsx).types
  tests/baselines/reference/jsxNamespaceNoElementChildrenAttributeReactJsx(jsx=react-jsxdev).js
  tests/baselines/reference/jsxNamespaceNoElementChildrenAttributeReactJsx(jsx=react-jsxdev).symbols
  tests/baselines/reference/jsxNamespaceNoElementChildrenAttributeReactJsx(jsx=react-jsxdev).types
  tests/cases/compiler/jsxNamespaceElementChildrenAttributeIgnoredWhenReactJsx.tsx
  tests/cases/compiler/jsxNamespaceNoElementChildrenAttributeReactJsx.tsx
Labels: For Backlog Bug

#60201 Expose method for retrieving inferred generic type arguments for a signature on the TypeChecker (#59637)
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Backlog Bug

#60384 allow calling `goToDef` on modifiers of named declarations
  src/services/goToDefinition.ts
  tests/baselines/reference/goToDefinitionAwait1.baseline.jsonc
  tests/baselines/reference/goToDefinitionAwait3.baseline.jsonc
  tests/baselines/reference/goToDefinitionMember.baseline.jsonc
  tests/baselines/reference/goToDefinitionModifiers.baseline.jsonc
  tests/baselines/reference/goToDefinitionOverriddenMember6.baseline.jsonc
  tests/baselines/reference/goToDefinitionOverriddenMember7.baseline.jsonc
  tests/baselines/reference/goToDefinitionReturn5.baseline.jsonc
  tests/baselines/reference/goToDefinitionYield3.baseline.jsonc
  tests/baselines/reference/goToDefinitionYield4.baseline.jsonc
  tests/baselines/reference/goToTypeDefinitionModifiers.baseline.jsonc
  tests/cases/fourslash/goToDefinitionMember.ts
  tests/cases/fourslash/goToDefinitionModifiers.ts
  tests/cases/fourslash/goToTypeDefinitionModifiers.ts
Labels: Author: Team, For Milestone Bug

#60829 Add new option "libReplacement"
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  src/compiler/program.ts
  src/compiler/types.ts
  src/testRunner/unittests/helpers/libraryResolution.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/config/initTSConfig/Default initialized TSConfig/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with --help/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with --watch/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with advanced options/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with boolean value compiler options/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with enum value compiler options/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with files options/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with incorrect compiler option value/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with incorrect compiler option/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with list compiler options with enum value/tsconfig.json
  tests/baselines/reference/config/initTSConfig/Initialized TSConfig with list compiler options/tsconfig.json
  tests/baselines/reference/config/showConfig/Shows tsconfig for single option/libReplacement/tsconfig.json
  tests/baselines/reference/libReplacement(libreplacement=false).trace.json
  tests/baselines/reference/libReplacement(libreplacement=true).trace.json
  tests/baselines/reference/libTypeScriptOverrideSimple.errors.txt
  tests/baselines/reference/libTypeScriptOverrideSimple.js
  tests/baselines/reference/libTypeScriptOverrideSimple.symbols
  tests/baselines/reference/libTypeScriptOverrideSimpleConfig.errors.txt
  tests/baselines/reference/libTypeScriptOverrideSimpleConfig.js
  tests/baselines/reference/libTypeScriptOverrideSimpleConfig.symbols
  tests/baselines/reference/libTypeScriptSubfileResolving.errors.txt
  tests/baselines/reference/libTypeScriptSubfileResolving.js
  tests/baselines/reference/libTypeScriptSubfileResolving.symbols
  tests/baselines/reference/libTypeScriptSubfileResolvingConfig.errors.txt
  tests/baselines/reference/libTypeScriptSubfileResolvingConfig.js
  tests/baselines/reference/libTypeScriptSubfileResolvingConfig.symbols
  tests/baselines/reference/tsbuild/libraryResolution/with-config-with-redirection.js
  tests/baselines/reference/tsbuildWatch/libraryResolution/with-config-with-redirection.js
  tests/baselines/reference/tsc/commandLine/help-all.js
  tests/baselines/reference/tsc/libraryResolution/unknown-lib.js
  tests/baselines/reference/tsc/libraryResolution/with-config-with-redirection.js
  tests/baselines/reference/tsc/libraryResolution/without-config-with-redirection.js
  tests/baselines/reference/tscWatch/libraryResolution/unknwon-lib.js
  tests/baselines/reference/tscWatch/libraryResolution/with-config-with-redirection.js
  tests/baselines/reference/tscWatch/libraryResolution/with-config.js
  tests/baselines/reference/tscWatch/libraryResolution/without-config-with-redirection.js
  tests/baselines/reference/tsserver/libraryResolution/with-config-with-redirection.js
  tests/baselines/reference/tsserver/libraryResolution/with-config.js
  tests/cases/compiler/libReplacement.ts
  tests/cases/compiler/libTypeScriptOverrideSimple.ts
  tests/cases/compiler/libTypeScriptOverrideSimpleConfig.ts
  tests/cases/compiler/libTypeScriptSubfileResolving.ts
  tests/cases/compiler/libTypeScriptSubfileResolvingConfig.ts
Labels: Author: Team, For Uncommitted Bug

#61040 Disable broken CodeQL query
  .github/codeql/codeql-configuration.yml
Labels: Author: Team, For Uncommitted Bug

#61066 Fix error message incorrectly referencing 'asserts' instead of 'assert'.
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/importAssertionNonstring.errors.txt
  tests/baselines/reference/nodeModulesImportAssertions(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesImportModeDeclarationEmit1(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesImportModeDeclarationEmit2(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesImportModeDeclarationEmitErrors1(module=nodenext).errors.txt
Labels: Author: Team, For Uncommitted Bug

#61073 DOM update 2025/01/29
  src/lib/dom.generated.d.ts
  src/lib/webworker.generated.d.ts
Labels: Author: Team, For Uncommitted Bug

#61084 [moveToFile] Fix symbols with empty `declarations` being treated as importable
  src/services/refactors/moveToFile.ts
  tests/cases/fourslash/moveToFile_undefined.ts
Labels: Author: Team, For Milestone Bug
