Repository microsoft/TypeScript, pull requests merged in 2025-03, with the labels that each got.

#61342 Rename type parameters when they are shadowed.
  src/compiler/expressionToTypeNode.ts
  tests/baselines/reference/declarationEmitShadowing.js
  tests/baselines/reference/declarationEmitShadowing.symbols
  tests/baselines/reference/declarationEmitShadowing.types
  tests/cases/compiler/declarationEmitShadowing.ts
Labels: For Uncommitted Bug

#61368 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20250306202248269 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#61392 Fix serialization of accessor types in declaration files.
  src/compiler/checker.ts
  src/compiler/expressionToTypeNode.ts
  src/compiler/types.ts
  tests/baselines/reference/declarationEmitGenericTypeParamerSerialization.js
  tests/baselines/reference/declarationEmitGenericTypeParamerSerialization.symbols
  tests/baselines/reference/declarationEmitGenericTypeParamerSerialization.types
  tests/baselines/reference/declarationEmitGenericTypeParamerSerialization2.js
  tests/baselines/reference/declarationEmitGenericTypeParamerSerialization2.symbols
  tests/baselines/reference/declarationEmitGenericTypeParamerSerialization2.types
  tests/baselines/reference/discriminateWithDivergentAccessors1.types
  tests/baselines/reference/mappedTypeRecursiveInference.types
  tests/baselines/reference/objectLiteralShorthandPropertiesErrorFromNotUsingIdentifier.types
  tests/cases/compiler/declarationEmitGenericTypeParamerSerialization.ts
  tests/cases/compiler/declarationEmitGenericTypeParamerSerialization2.ts
Labels: For Uncommitted Bug

#60921 fix(60908): Unexpected "'Type' is declared but its value is never read." error with jsdoc @import syntax
  src/compiler/binder.ts
  tests/baselines/reference/importTag24.errors.txt
  tests/baselines/reference/importTag24.symbols
  tests/baselines/reference/importTag24.types
  tests/baselines/reference/importTag25.symbols
  tests/baselines/reference/importTag25.types
  tests/cases/conformance/jsdoc/importTag24.ts
  tests/cases/conformance/jsdoc/importTag25.ts
Labels: For Milestone Bug, For Backlog Bug

#61452 Fix errors on type assertions in erasableSyntaxOnly
  src/compiler/checker.ts
  tests/baselines/reference/erasableSyntaxOnly2.errors.txt
  tests/baselines/reference/erasableSyntaxOnly2.js
  tests/baselines/reference/erasableSyntaxOnly2.symbols
  tests/baselines/reference/erasableSyntaxOnly2.types
  tests/cases/compiler/erasableSyntaxOnly2.ts
Labels: Author: Team, For Uncommitted Bug

#61491 Add new release publisher yaml
  azure-pipelines.release-publish.yml
Labels: Author: Team, For Uncommitted Bug

#61514 Fix incorrect name in new release pipeline
  azure-pipelines.release-publish.yml
Labels: Author: Team, For Uncommitted Bug
