Repository microsoft/TypeScript, pull requests merged in 2025-06, with the labels that each got.

#61746 Initialize the map for dts to reference and source to reference when parsing project reference as its always needed
  src/compiler/builderState.ts
  src/compiler/checker.ts
  src/compiler/moduleSpecifiers.ts
  src/compiler/program.ts
  src/compiler/resolutionCache.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/server/project.ts
  src/services/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#61815 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20250604192236101 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#61764 fix(61747): for (using of = is incorrectly parsed
  src/compiler/parser.ts
  tests/baselines/reference/usingDeclarationsInForOf.4.errors.txt
  tests/baselines/reference/usingDeclarationsInForOf.4.js
  tests/cases/conformance/statements/VariableStatements/usingDeclarations/usingDeclarationsInForOf.4.ts
Labels: For Uncommitted Bug

#61777 fix(checker): report error when using bigint as enum key
  src/compiler/checker.ts
  tests/baselines/reference/enumWithBigint.errors.txt
  tests/baselines/reference/enumWithBigint.js
  tests/baselines/reference/enumWithBigint.symbols
  tests/baselines/reference/enumWithBigint.types
  tests/cases/compiler/enumWithBigint.ts
Labels: For Uncommitted Bug

#61781 explicitly disallow `using` in ambient contexts
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/awaitUsingDeclarations.16.errors.txt
  tests/baselines/reference/awaitUsingDeclarations.16.js
  tests/baselines/reference/usingDeclarations.16.errors.txt
  tests/baselines/reference/usingDeclarations.16.js
  tests/cases/conformance/statements/VariableStatements/usingDeclarations/awaitUsingDeclarations.16.ts
  tests/cases/conformance/statements/VariableStatements/usingDeclarations/usingDeclarations.16.ts
Labels: For Uncommitted Bug

#61824 Issue "'{0}' declarations can only be declared inside a block." for block-scoped variables in presence of parse errors
  src/compiler/checker.ts
  tests/baselines/reference/disallowedBlockScopedInPresenceOfParseErrors1.errors.txt
  tests/baselines/reference/disallowedBlockScopedInPresenceOfParseErrors1.symbols
  tests/baselines/reference/disallowedBlockScopedInPresenceOfParseErrors1.types
  tests/cases/compiler/disallowedBlockScopedInPresenceOfParseErrors1.ts
Labels: For Backlog Bug

#61814 Fix helpers emit for .cjs files in ESM module mode
  src/compiler/factory/utilities.ts
  tests/baselines/reference/ctsFileInEsnextHelpers.errors.txt
  tests/baselines/reference/ctsFileInEsnextHelpers.js
  tests/cases/compiler/ctsFileInEsnextHelpers.ts
Labels: Author: Team, For Uncommitted Bug

#61822 optimization, reduce memory usage
  src/compiler/program.ts
Labels: For Uncommitted Bug

#61828 Port "Improve type discrimination algorithm" from tsgo
  src/compiler/checker.ts
  src/services/codefixes/importFixes.ts
  tests/baselines/reference/discriminateWithMissingProperty.errors.txt
  tests/baselines/reference/missingDiscriminants.errors.txt
  tests/baselines/reference/missingDiscriminants.symbols
  tests/baselines/reference/missingDiscriminants.types
  tests/baselines/reference/promiseType.types
  tests/cases/compiler/missingDiscriminants.ts
Labels: Author: Team, For Uncommitted Bug

#61846 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20250611192551558 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/csy/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/deu/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/esn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/jpn/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/kor/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ptb/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/rus/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/trk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#61898 LEGO: Pull request from lego/hb_5378966c-b857-470a-8675-daebef4a6da1_20250618192323088 to main
  src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/cht/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/fra/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/ita/diagnosticMessages/diagnosticMessages.generated.json.lcl
  src/loc/lcl/plk/diagnosticMessages/diagnosticMessages.generated.json.lcl
Labels: For Uncommitted Bug

#61909 Don't ignore completions at source file locations
  src/services/completions.ts
  src/services/utilities.ts
  tests/baselines/reference/tsserver/completions/in-project-reference-setup-with-path-mapping-with-existing-import-without-includeCompletionsForModuleExports.js
  tests/baselines/reference/tsserver/completions/in-project-reference-setup-with-path-mapping-with-existing-import.js
  tests/cases/fourslash/asOperatorCompletion2.ts
  tests/cases/fourslash/asOperatorCompletion3.ts
Labels: For Uncommitted Bug

#61920 Allow trailing commas after import attributes in `ImportType`
  src/compiler/parser.ts
  tests/baselines/reference/importAttributes10.errors.txt
  tests/baselines/reference/importAttributes10.js
  tests/baselines/reference/importAttributes10.symbols
  tests/baselines/reference/importAttributes10.types
  tests/cases/conformance/importAttributes/importAttributes10.ts
Labels: For Uncommitted Bug

#61937 Update Copilot instructions and setup script
  .github/copilot-instructions.md
  .github/workflows/copilot-setup-steps.yml
Labels: Author: Team, For Uncommitted Bug

#61903 Use strict subtype relation in `getCommonSupertype`
  src/compiler/checker.ts
Labels: Author: Team, For Uncommitted Bug

#61947 Add line endings and printf debugging section
  .github/copilot-instructions.md
Labels: Author: Team, For Uncommitted Bug

#61928 Use jsx language variant for jsx file scanning in getChildren
  src/compiler/types.ts
  src/services/completions.ts
  src/services/services.ts
  src/services/utilities.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/cases/fourslash/syntacticClassificationsJsx1.ts
  tests/cases/fourslash/syntacticClassificationsJsx2.ts
Labels: Author: Team, For Uncommitted Bug

#61795 Fix capitalisation for `checkJs`
  src/compiler/commandLineParser.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/tsc/commandLine/does-not-add-color-when-NO_COLOR-is-set.js
  tests/baselines/reference/tsc/commandLine/help-all.js
  tests/baselines/reference/tsc/commandLine/help.js
  tests/baselines/reference/tsc/commandLine/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped-when-host-can't-provide-terminal-width.js
  tests/baselines/reference/tsc/commandLine/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
Labels: For Uncommitted Bug

#61551 Improve release publisher pipeline
  azure-pipelines.release-publish.yml
Labels: Author: Team, For Uncommitted Bug

#61857 Fixed crash on `ComputedPropertyName` when computing interactive inlay hints
  src/services/inlayHints.ts
  tests/baselines/reference/inlayHintsFunctionParameterTypes5.baseline
  tests/cases/fourslash/inlayHintsFunctionParameterTypes5.ts
Labels: For Uncommitted Bug

#60537 Fixed a printer crash caused by empty parameter modifiers
  src/compiler/expressionToTypeNode.ts
  tests/cases/fourslash/completionEntryClassMembersWithInferredFunctionReturnType1.ts
Labels: For Uncommitted Bug

#61317 Handle `silentNeverType` in iteration-related functions
  src/compiler/checker.ts
  tests/baselines/reference/genericCallAtYieldExpressionInGenericCall1.errors.txt
  tests/baselines/reference/genericCallAtYieldExpressionInGenericCall1.symbols
  tests/baselines/reference/genericCallAtYieldExpressionInGenericCall1.types
  tests/baselines/reference/genericCallAtYieldExpressionInGenericCall2.symbols
  tests/baselines/reference/genericCallAtYieldExpressionInGenericCall2.types
  tests/cases/compiler/genericCallAtYieldExpressionInGenericCall1.ts
  tests/cases/compiler/genericCallAtYieldExpressionInGenericCall2.ts
Labels: For Uncommitted Bug

#61977 Revert change to type print in an error message
  src/compiler/checker.ts
  tests/baselines/reference/accessorsOverrideProperty10.errors.txt
  tests/baselines/reference/propertyOverridesAccessors6.errors.txt
Labels: For Uncommitted Bug

#61976 Properly disallow `yield` in bodyless arrows
  src/compiler/parser.ts
  tests/baselines/reference/YieldExpression20_es6.errors.txt
  tests/baselines/reference/YieldExpression20_es6.js
  tests/baselines/reference/YieldExpression20_es6.symbols
  tests/baselines/reference/YieldExpression20_es6.types
  tests/cases/conformance/es6/yieldExpressions/YieldExpression20_es6.ts
Labels: For Uncommitted Bug

#58551 perf: improve regexp performance by using non-capturing groups
  src/compiler/utilities.ts
  src/compiler/watch.ts
Labels: For Uncommitted Bug

#61850 fix: diagnostic message for class name 'Object' when targeting different ECMAScript versions
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/checkForObjectTooStrict.errors.txt
  tests/baselines/reference/exportClassNameWithObjectAMD.errors.txt
  tests/baselines/reference/exportClassNameWithObjectCommonJS.errors.txt
  tests/baselines/reference/exportClassNameWithObjectSystem.errors.txt
  tests/baselines/reference/exportClassNameWithObjectUMD.errors.txt
  tests/baselines/reference/exportDefaultClassNameWithObject.errors.txt
  tests/baselines/reference/instanceofOperator.errors.txt
  tests/baselines/reference/nodeModulesAllowJsGeneratedNameCollisions(module=node16).errors.txt
  tests/baselines/reference/nodeModulesAllowJsGeneratedNameCollisions(module=node18).errors.txt
  tests/baselines/reference/nodeModulesAllowJsGeneratedNameCollisions(module=node20).errors.txt
  tests/baselines/reference/nodeModulesAllowJsGeneratedNameCollisions(module=nodenext).errors.txt
  tests/baselines/reference/nodeModulesGeneratedNameCollisions(module=node16).errors.txt
  tests/baselines/reference/nodeModulesGeneratedNameCollisions(module=node18).errors.txt
  tests/baselines/reference/nodeModulesGeneratedNameCollisions(module=node20).errors.txt
  tests/baselines/reference/nodeModulesGeneratedNameCollisions(module=nodenext).errors.txt
Labels: For Backlog Bug
