Repository microsoft/TypeScript, pull requests merged in 2025-05, with the labels that each got.

#48172 `arguments` should not be allowed in class static block
  src/compiler/checker.ts
  src/compiler/diagnosticMessages.json
  tests/baselines/reference/argumentsUsedInClassFieldInitializerOrStaticInitializationBlock.errors.txt
  tests/baselines/reference/argumentsUsedInClassFieldInitializerOrStaticInitializationBlock.js
  tests/baselines/reference/argumentsUsedInClassFieldInitializerOrStaticInitializationBlock.symbols
  tests/baselines/reference/argumentsUsedInClassFieldInitializerOrStaticInitializationBlock.types
  tests/baselines/reference/classStaticBlock6.errors.txt
  tests/baselines/reference/classStaticBlock6.js
  tests/baselines/reference/classStaticBlock6.symbols
  tests/baselines/reference/classStaticBlock6.types
  tests/cases/compiler/argumentsUsedInClassFieldInitializerOrStaticInitializationBlock.ts
  tests/cases/conformance/classes/classStaticBlock/classStaticBlock6.ts
Labels: For Backlog Bug

#50372 check usage before declaration for decorators
  src/compiler/checker.ts
  tests/baselines/reference/blockScopedVariablesUseBeforeDef.errors.txt
  tests/baselines/reference/blockScopedVariablesUseBeforeDef.js
  tests/baselines/reference/blockScopedVariablesUseBeforeDef.symbols
  tests/baselines/reference/blockScopedVariablesUseBeforeDef.types
  tests/baselines/reference/decoratorUsedBeforeDeclaration.errors.txt
  tests/baselines/reference/decoratorUsedBeforeDeclaration.js
  tests/baselines/reference/decoratorUsedBeforeDeclaration.symbols
  tests/baselines/reference/decoratorUsedBeforeDeclaration.types
  tests/cases/compiler/blockScopedVariablesUseBeforeDef.ts
  tests/cases/compiler/decoratorUsedBeforeDeclaration.ts
Labels: For Backlog Bug

#61596 docs(lib): add @throws JSDoc for JSON methods
  src/lib/es5.d.ts
Labels: For Uncommitted Bug

#61647 DOM Update 2025-05-02
  src/lib/dom.generated.d.ts
  src/lib/dom.iterable.generated.d.ts
  src/lib/webworker.generated.d.ts
  src/lib/webworker.iterable.generated.d.ts
  tests/baselines/reference/globalThisBlockscopedProperties.types
  tests/baselines/reference/mappedTypeRecursiveInference.errors.txt
  tests/baselines/reference/mappedTypeRecursiveInference.types
Labels: Author: Team, For Uncommitted Bug

#61662 Add configurable maximum hover length
  src/compiler/checker.ts
  src/compiler/types.ts
  src/compiler/utilities.ts
  src/harness/client.ts
  src/harness/fourslashImpl.ts
  src/harness/fourslashInterfaceImpl.ts
  src/server/session.ts
  src/services/services.ts
  src/services/symbolDisplay.ts
  src/services/types.ts
  src/services/utilities.ts
  tests/baselines/reference/api/typescript.d.ts
  tests/baselines/reference/quickinfoVerbosityToplevelTruncation1.baseline
  tests/baselines/reference/quickinfoVerbosityToplevelTruncation2.baseline
  tests/baselines/reference/quickinfoVerbosityTruncation1.baseline
  tests/baselines/reference/quickinfoVerbosityTruncation2.baseline
  tests/cases/fourslash/fourslash.ts
  tests/cases/fourslash/quickInfoCanBeTruncated.ts
  tests/cases/fourslash/quickinfoVerbosityToplevelTruncation1.ts
  tests/cases/fourslash/quickinfoVerbosityToplevelTruncation2.ts
  tests/cases/fourslash/quickinfoVerbosityTruncation1.ts
  tests/cases/fourslash/quickinfoVerbosityTruncation2.ts
Labels: Author: Team, For Backlog Bug

#61655 Fix unwanted constant comparisons potentially causing bugs
  src/compiler/resolutionCache.ts
  src/harness/fourslashImpl.ts
  tests/baselines/reference/jsdocParameterTagSnippetCompletion1.baseline
  tests/baselines/reference/jsdocParameterTagSnippetCompletion2.baseline
  tests/baselines/reference/quickInfoAlias.baseline
  tests/baselines/reference/quickinfoVerbosity3.baseline
  tests/baselines/reference/quickinfoVerbosityImport.baseline
  tests/baselines/reference/quickinfoVerbosityNamespace.baseline
Labels: For Backlog Bug

#60857 Stop reassigning `.valueDeclaration` to avoid replacing earlier declarations with late ones
  src/compiler/checker.ts
  tests/baselines/reference/lateBoundAssignmentCandidateJS1.js
  tests/baselines/reference/lateBoundAssignmentCandidateJS1.symbols
  tests/baselines/reference/lateBoundAssignmentCandidateJS1.types
  tests/baselines/reference/lateBoundAssignmentCandidateJS2.js
  tests/baselines/reference/lateBoundAssignmentCandidateJS2.symbols
  tests/baselines/reference/lateBoundAssignmentCandidateJS2.types
  tests/baselines/reference/lateBoundAssignmentCandidateJS3.errors.txt
  tests/baselines/reference/lateBoundAssignmentCandidateJS3.js
  tests/baselines/reference/lateBoundAssignmentCandidateJS3.symbols
  tests/baselines/reference/lateBoundAssignmentCandidateJS3.types
  tests/baselines/reference/lateBoundMethodNameAssigmentJS.js
  tests/baselines/reference/lateBoundMethodNameAssigmentJS.symbols
  tests/baselines/reference/lateBoundMethodNameAssigmentJS.types
  tests/cases/compiler/lateBoundAssignmentCandidateJS1.ts
  tests/cases/compiler/lateBoundAssignmentCandidateJS2.ts
  tests/cases/compiler/lateBoundAssignmentCandidateJS3.ts
Labels: For Backlog Bug

#61707 Fix getResolvePackageJsonImports utility
  src/compiler/utilities.ts
Labels: Author: Team, For Uncommitted Bug

#61730 Handle lock file 3 version when caching the typings ensuring we can reuse already installed packages
  src/testRunner/unittests/tsserver/typingsInstaller.ts
  src/typingsInstallerCore/typingsInstaller.ts
  tests/baselines/reference/tsserver/typingsInstaller/expired-cache-entry-lockFile3.js
  tests/baselines/reference/tsserver/typingsInstaller/non-expired-cache-entry-lockFile3.js
Labels: Author: Team, For Uncommitted Bug
