Repository microsoft/TypeScript, pull requests merged in 2025-04, with the labels that each got.

#55478 Fixed a symbol display crash on expando members write locations
  src/services/symbolDisplay.ts
  tests/cases/fourslash/quickInfoOnExpandoLikePropertyWithSetterDeclarationJs1.ts
  tests/cases/fourslash/quickInfoOnExpandoLikePropertyWithSetterDeclarationJs2.ts
Labels: For Uncommitted Bug

#61523 Convert release publishing inputs into parameters
  azure-pipelines.release-publish.yml
Labels: Author: Team, For Uncommitted Bug

#61586 Deemphasize old JSX transform
  src/compiler/commandLineParser.ts
  tests/baselines/reference/config/commandLineParsing/parseCommandLine/Parse empty options of --jsx.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert incorrect option of jsx to compiler-options with json api.js
  tests/baselines/reference/config/convertCompilerOptionsFromJson/Convert incorrect option of jsx to compiler-options with jsonSourceFile api.js
Labels: For Uncommitted Bug

#61113 Fix #61098
  src/compiler/checker.ts
  tests/baselines/reference/assignmentToConditionalBrandedStringTemplateOrMapping.js
  tests/baselines/reference/assignmentToConditionalBrandedStringTemplateOrMapping.symbols
  tests/baselines/reference/assignmentToConditionalBrandedStringTemplateOrMapping.types
  tests/cases/compiler/assignmentToConditionalBrandedStringTemplateOrMapping.ts
Labels: For Backlog Bug

#61562 Add the `.getNonPrimitiveType()` method to the `TypeChecker`
  src/compiler/checker.ts
  src/compiler/types.ts
  tests/baselines/reference/api/typescript.d.ts
Labels: For Backlog Bug

#61263 fix(61258): Renaming namespace with const enum doesn't update enum references
  src/services/findAllReferences.ts
  tests/baselines/reference/findAllRefs_importType_exportEquals.baseline.jsonc
  tests/baselines/reference/renameNamespace.baseline.jsonc
  tests/cases/fourslash/renameNamespace.ts
Labels: For Backlog Bug
